### ISSUE TITLE
need wording to clarify that the description should be the *Deleted* bases, nucleotides

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1000]
People often "name" alleles after the residues which are retained, but when we describe a deletion we capture the deleted bases/amino acides. I think we need this to be clearer in the prompts (some test somewhere, maybe bracketed in the box?)

eg below:

**Comment by ValWood** [comment]
![alp](https://cloud.githubusercontent.com/assets/7359272/10578137/26bc6d6c-7668-11e5-8c38-39400bd775f7.jpg)

**Comment by ValWood** [comment]
ends up as:

![alp6_desc](https://cloud.githubusercontent.com/assets/7359272/10578162/487673d0-7668-11e5-8fe2-304ba078b757.jpg)

**Comment by mah11** [comment]
more examples in duplicate ticket #1055

**Comment by mah11** [comment]
suggestion from duplicate ticket: change text to "please specify deleted residues"
(sounds fine to me)

**Comment by ValWood** [comment]
I know you have lots of stuff at high priority but this can be done quite soon as its only a small text change.

Somebody just made the error in a session Midori was checking....

**Comment by ValWood** [comment]
Kim has added this
