### ISSUE TITLE
possibly hide geneotypes not related to the gene when on gene page

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1001]
This isn't super critical, and I feel I mentioned it before and it was vetoed, but I'll mention it again in case not.

I feel that if I have selected a specific gene to annotate, I should only see the genotypes which include that gene.

Will upload eg.

**Comment by ValWood** [comment]
![seems odd from alp4 gene to see genotypes unrelaed to alp4](https://cloud.githubusercontent.com/assets/7359272/10588172/a492fc68-769c-11e5-9aa1-a597dbbe7da6.jpg)

**Comment by mah11** [comment]
kinda sorta related to #961, but not stated explicitly there, so this isn't entirely a duplicate.

no objection to the requested change as described in the ticket text, but the uploaded screenshot is NOT a gene page (it's the genotype summary for the paper, so of course all the genotypes should be listed there)

**Comment by ValWood** [comment]
I'm accessing it via a gene link though and I only see the "gene specific annotations" when I access from here so it would make sense to only see the "gene specific genotypes" when you go via this route.

**Comment by kimrutherford** [comment]
> I'm accessing it via a gene link though and I only see the "gene specific annotations" 

I don't think that's the case.  You should see all annotations for that genotype on the genotype page.

**Comment by mah11** [comment]
It would absolutely not make sense for one page to show different content depending on what path you took to reach the page. The genotype management page is behaving as it should.

When I click a gene link, I go to its gene page, which does show only genotypes involving the gene, and annotations to the gene or to genotypes including the gene.

 I think everything is OK here ...

**Comment by ValWood** [comment]
If I come from the alp4 page to add a multi gene genotype I still don't see why
I can't see  the same page but specific for alp4 genotypes.
http://curation.pombase.org/pombe/curs/a42509fe62ac69ca/genotype_manage

Here the page header would say 
Genotypes with Alp4 alleles for: PMID:16611237
and the table header would say  "Genotypes  with Alp4 alleles used in this session" and  genotypes which excluded alp4 would be excluded.

It would just be a *different* entry point  (page) to the genotype creation interface than the (any gene) add genotype page?  It seems sensible not to show the user things they don't need to see at any point. 

Anyway it isn't critical. Can wait for user feedback.

**Comment by ValWood** [comment]
non issue
