### ISSUE TITLE
Can we make the text a little more informative for adding a new genotype

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1003]
I think the [no alleles added yet]
has the potential to be confusing here:
![no alles yet added to this genotype](https://cloud.githubusercontent.com/assets/7359272/10588483/533dab18-769e-11e5-8921-9af7bf21355a.jpg)

**Comment by ValWood** [comment]
You might of added alleles previously, and if you are new it is difficult to process  (or easy to forget) that you are constructing  each genotype from the alleles.
Could we improve the text here?
Maybe along the lines  "add alleles until the genotype is fully specified" 
(I think we had something along these lines previously, maybe we made it shorter for some reason but it doesn't quite convey the task does it? apologies if it was my suggestion to change it).

It could  also be a bit confusing if the user knows they have  already  "added" the alleles previously.

**Comment by ValWood** [comment]
I see the text is in the blue bar where the actions are.
I think in cases where there are clearly other things to do its quite easy to mentally block this out as a 'header' rather than an instruction. I wonder if a different colour would make the instructions more prominent? (like a yellow which might 'backlight' it a bit?)

**Comment by ValWood** [comment]
We decided here that we can just lose the text
[no alleles added yet] 
as it isn't necessary and might be confusing if you have previusly added alleles/created another genotype

**Comment by kimrutherford** [comment]
> We decided here that we can just lose the text
> [no alleles added yet] 

Done.  Is that all that was needed here?

**Comment by kimrutherford** [comment]
Forgot to say - this isn't in the live Canto yet, only in test.  It will go into the live version when we update to the new extension code.

**Comment by ValWood** [comment]
yep
