### ISSUE TITLE
merge user

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1004]
Brad Nolen Deborah Wuttke are in canto twice. entris look identical (one is only a case diff). Please merge.
delete Hugh P. Cam (unused account name), all pubs curated from other e-mail

there are a few other duplicates but I'll wait to see which is their preferred e-mail

**Comment by kimrutherford** [comment]
Hugh P. Cam has a session.  Should I delete the session too?

**Comment by ValWood** [comment]
The session which is curated as this user PMID:25497836 shoudl transfer to the  other user ID. if possible as it is in progress.
