### ISSUE TITLE
possible bug, cannot edit existing session

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1005]
curs/4794f2ac68f1b5ba

In this session I want to change
"abolished transcription during vegetative growth" to "abolished transcription" 

However, when I do this the OK button does not work.

The first time I tried I was prompted to select a "with" field, which is odd since  phenotypes  don't have 'with' fields. On creating the ticket I don't see this bug, but I still can't "OK"

**Comment by ValWood** [comment]
I tried once more and I  saw the with field again:

![with_field](https://cloud.githubusercontent.com/assets/7359272/10599165/5085b45c-76f7-11e5-8ced-27e8f60da188.jpg)

**Comment by ValWood** [comment]
oddly has my old sanger e-mail  address too?

**Comment by ValWood** [comment]
Artemis. I didn't click because they *look* editable and they show as "new"

**Comment by ValWood** [comment]
nope, not in artemis.....

**Comment by ValWood** [comment]
Maybe these are the very early sessions which were in a separate 'blob' and not in the  main Canto?
I think I can work around by deleting the annotation and recreating the new one. No hurry as I am waiting fro the term, I'll leave them until  you have had a  look....

**Comment by ValWood** [comment]
Kim Let's look at this one fist

**Comment by ValWood** [comment]
evidence code is blank
with field  (not valid for phenotypes) shows instead of assayed_using

**Comment by mah11** [comment]
possible weirdness: I just had a look at that session, and I do not see any of the symptoms Val reports.

**Comment by ValWood** [comment]
did you try to edit the term ? You can change the term, but Canto will not let you update? You get blocked when you try to complete the change

**Comment by mah11** [comment]
Yep. No problems.

**Comment by ValWood** [comment]
very weird.  Anyway I demoed to Kim. He is going to take a look...

**Comment by Antonialock** [comment]
I seem to recall Jacky had a problem with editing annotations, and I had no problems editing hers. Were you logged in? Maybe there is an issue for non-logged in users?

**Comment by ValWood** [comment]
I was logged in and only this single annotation in the session was affected (the one with my sanger  e-mails0. Others I could edit fine...

**Comment by mah11** [comment]
a-ha. That annotation uses an evidence type that's no longer offered (use "transcript expression level evidence" instead). Once I chose one of the available evidence options, the "OK" button became active (tho I didn't save any changes).

I still don't see the "with", tho ...

**Comment by ValWood** [comment]
Ah OK, fixed. I'll call this a non-issue.

The "with" field thing appearing is sporadic so Kim might want to follow this up (will keep this ticket open for comment), but I no longer see it in this session...... It was not always there even when i was reporting this issue so will  probably be difficult to debug?

**Comment by kimrutherford** [comment]
> The "with" field thing appearing is sporadic so Kim might want to follow this up

OK, will do.  I should be easy to reproduce thanks to Midori's comment.

**Comment by kimrutherford** [comment]
> Kim might want to follow this up

Yep, but I've lowered the priority for now.

**Comment by kimrutherford** [comment]
> The "with" field thing appearing is sporadic so Kim might want to follow this up

There were a couple of bugs, the worst one being that the annotation was not displaying for me so it looked like the session was empty.  I've fixed that.

I think I've also fixed the "with" popping up where it shouldn't.  And now if you try to edit an annotation with a evidence type that's no longer offered, it highlights the evidence selector in red.  I think I'll close this now but please re-open if you see other problems.

![screenshot 2016-03-14 14 30 23](https://cloud.githubusercontent.com/assets/90474/13732983/69c56f12-e9f1-11e5-873f-6bb80596e2a7.png)
