### ISSUE TITLE
Handle extension ranges like: "SPAPB8E5.05|SPAC513.03"

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1006]

**Comment by kimrutherford** [comment]
For now maybe a free text box is a quick fix.

But what should the user interface be long term?  If the range is "SPAPB8E5.05|SPAC513.03" should the user have to add one of those gene to the session first?  Alternatively, should it just be a drop down listing those two genes?  In that case, if the user chooses a gene should it be added to the session?

**Comment by ValWood** [comment]
In eg GTPase activator -> GTPase activity
could use GO: id to identify all the genes which have GTPase activity, BUT this would be a different menaing of a GO ID in an extension

**Comment by ValWood** [comment]
Lets ditch this in short term and just force curators to add all IDs to the session. We can consider this or Kim's solution later
