### ISSUE TITLE
Implement cardinality constraints

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1008]
The cardinality column in the extension config file is currently ignored - needs implementing.

**Comment by kimrutherford** [comment]
I started this but it's trickier than I thought, so I'm putting it aside while I think about it.

**Comment by kimrutherford** [comment]
This is now partially implemented.  Currently the code assumes that the relations all have cardinality "0,1" as that the commonest case.  I'll work on the other cases.

**Comment by ValWood** [comment]
Protein binding phenotypes need this.
Will need separate text. Kim is suggesting the config file.

**Comment by mah11** [comment]
I have added helpful text to the display text column in the fypo config file. Let's see how we get on with just that, 'cos if it's OK we won't have to rejig the file format yet again.

**Comment by kimrutherford** [comment]
I've found a bug.

For "normal chromatin binding"/FYPO:0003086 two extension relations are shown, "assayed protein ..." and "assayed region ..." If you add one of them, both are greyed out.

**Comment by mah11** [comment]
FYPO:0003086 gets "assayed protein" from this line:
FYPO:0001092    is_a    assayed_using   ProteinID       assayed protein 0,1     user

... and "assayed region" from this:
FYPO:0002576    is_a    assayed_using   SO:0001411      assayed region  0,1     user

Both are correct - if a phenotype affects something binding to chromatin, you want to know both which protein and where it ought to bind.

(FYPO:0001092 is "binding phenotype" and FYPO:0002576 is "abnormal chromatin binding")

**Comment by mah11** [comment]
Warning: potentially scary.
I wonder if there's a more general issue with cases where one FYPO ID is an is_a descendant of another ID also in the config file -- FYPO:0002576 does have an is_a path to FYPO:0001092.

I got similar weirdness with FYPO:0001553, which gets "assayed_using" entries from paths to FYPO:0000294 (text prompt "assayed transcript") and FYPO:0000142 ("assayed protein"; just changed to "assayed gene/transcript/protein"). It actually shows "assayed transcript" twice, and I haven't figured out why.

I'm not sure what's the best way round this ... for FYPO:0003086 we do want to ask for both a protein and a region, but for FYPO:0001553 we really only need one extension for the transcript.

Maybe we have to introduce another extension relation for the sequence region extensions (assayed_at?). Ouch. But if we did that, then it would probably work to have Canto show only the "descendant" option for each relation. I can elaborate on a skype call if that will help. And should we split this off into its own ticket?

**Comment by mah11** [comment]
one more little thing: the "assayed protein" link for FYPO:0001553 doesn't provide the gene selector pulldown; the popup just has the "assayed protein" text

**Comment by kimrutherford** [comment]
> and "assayed region" from this:

The current code assumes that each extension relation is unique for any particular term.  So it assumes that there can be only one "assayed_using" in this case.  It should look at the relation+range.

>  It actually shows "assayed transcript" twice, and I haven't figured out why.

That's confusing.  Thanks for catching it.  I'll work out what's going on.

> Maybe we have to introduce another extension relation for the sequence region extensions (assayed_at?). Ouch

I think we can cope with this in the interface code without having to do that.

It would be good to chat about this before I dive in though to make sure I'm understanding things.

> one more little thing: the "assayed protein" link for FYPO:0001553 doesn't provide the gene
> selector pulldown; the popup just has the "assayed protein" text

I'll fix that.  Thanks.

**Comment by kimrutherford** [comment]
>> one more little thing: the "assayed protein" link for FYPO:0001553 doesn't provide the gene
>> selector pulldown; the popup just has the "assayed protein" text

> I'll fix that. Thanks.

Fixed.  The problem was that the range was configured as "GeneID".  That wasn't in the list of possible range feature types ("ProteinID", "TranscriptID" and "tRNAID") - I've added it.  They all do the same thing.

**Comment by mah11** [comment]
OK. Happy to chat at any mutually convenient time.

**Comment by ValWood** [comment]
I think we are good here. If not, I don't knwo what is still to do, so  maybe open a new ticket for outstanding?

**Comment by mah11** [comment]
Reopening because the bug noted for FYPO:0003086 has not been fixed, and there have been a lot of follow-up comments that would be a PITA to transfer to a new ticket.

**Comment by mah11** [comment]
Additional follow-up on the bug:

DNA binding FYPO terms are also affected. For them Canto should allow one protein (the one doing the binding),  one region (the bound DNA), or both (i.e. it should behave as Boolean OR, vernacular English and/or). At present, it's only allowing a protein XOR a region, i.e. can't specify one of each.

The config file now has separate entries:

FYPO:0000653    is_a    assayed_using   SO:0000110      assayed region  0,1     user
FYPO:0000653    is_a    assayed_using   ProteinID       assayed protein 0,1     user

(I just edited the file yesterday to do this, so if it's just that the config hasn't been reloaded, let me know and I'll test again when it's up to date. I'm also about to do a similar edit for FYPO:0003086, the term for which Kim initially spotted the bug.)

As far as I know, the fix is still for the code to use the relation+range instead of just the relation for cardinality.

**Comment by kimrutherford** [comment]
> As far as I know, the fix is still for the code to use the relation+range instead of just the relation
> for cardinality.

It's not fixed because it's a bit fiddly dealing with the ancestry in this case.  I'm having trouble implementing it in a way that isn't going to make Future Me sad and angry.

**Comment by ValWood** [comment]
Does this need to happen to go live with the AE interface (I'm not quite sure what the issue is). Will flag as "high priority" and can be demoted if not required.

**Comment by mah11** [comment]
If it doesn't go live with the rest of the AE interface, there may be lots to clean up in chado load logs for protein binding phenotype annotations that don't include both binding partners. There may also be some frustration with DNA binding phenotypes if it can't accept both the protein doing (or not doing) the binding and the region where it binds -- that's the outstanding bug, as I understand the situation.

**Comment by ValWood** [comment]
Its flagged as "next" which is above "high priority". Kim wanted me to remove so things did not have both labels "next" and "high priority".

This will be done for release.

**Comment by mah11** [comment]
Status note: it's not allowing two assayed-protein entries for protein binding phenotypes yet.

**Comment by kimrutherford** [comment]
> it's not allowing two assayed-protein entries for protein binding phenotypes yet.

I've reworked the code a lot and that should now be fixed.  Even the scary configuration for modifications seems to work.

It still assumes that all cardinality is configured as "0,1" but now I've reworked the code the protein binding phenotype case should be easy to fix.  I'll do that next.

**Comment by kimrutherford** [comment]
> It still assumes that all cardinality is configured as "0,1"

It now handles "*" and "2" but it isn't general yet, so you can't do anything funky like "0,2,5".

It also disables the proceed button on the extension selection page if a required extension is missing.  I hope that's what you were expecting.

Please give this new code a test when you have a chance.  I've changed quite a bit under the hood so there are probably bugs.

**Comment by mah11** [comment]
I am not yet getting the desired behaviour for cardinality "2". It still only lets me choose one protein (the configured use case is any protein binding phenotype, FYPO:0000702 and descendants). Is there anything specific I should try? (I've just done a FYPO:0000705 annotation as I normally would, and tried adding extensions.)

**Comment by mah11** [comment]
Another update on protein-binding FYPO and cardinality "2": 
It wil let me finish the whole annotation with only one "assayed protein" extension, so the bit that's supposed to require 2 isn't working for me.

I can add a second protein if I finish the extension with one, and then use the extension "edit" button, or if I finish the annotation and then edit it

... but I'm not sure if that's just another effect of the bug I just reported in #1069.

**Comment by kimrutherford** [comment]
> I am not yet getting the desired behaviour for cardinality "2". It still only lets me choose one protein

Sorry, I failed to update the test tool correctly so it was only using part of the changes.  Could you try again?  It's working for me.

**Comment by mah11** [comment]
It's working now - yay!

**Comment by kimrutherford** [comment]
I think this is done now.  If you have problems please open new issues.  (This one is a bit long)
