### ISSUE TITLE
admin-only annotation extensions

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1011]
As noted way back in #181, I've done two annotation extension configuration files for FYPO - one for options to offer to everybody, and one for rarely-used funny cases that should only be available to curators (i.e. admin users).

Canto should offer normal users extension options from the FYPO_A_E_config file, whereas admins/curators should get options from both FYPO_A_E_config and FYPO_A_E_admin_config.

We may want something similar for GO or PSI-MOD extension configs some time in the future, so the system will want to be generic.

**Comment by kimrutherford** [comment]
It might be better to have the admin and non-admin config in the same file, but add a column to specify who should see the extension type.

**Comment by mah11** [comment]
OK. What do you want for column header and contents? If you make an executive decision on that, I'll update the files (and merge the 2 for FYPO).

**Comment by kimrutherford** [comment]
> If you make an executive decision on that, I'll update the files

Thanks.  For now I suggest a column called "role" (because that's the terminology inside Canto) with the values: "user" and "admin".  It's not the clearest, but I'll add it to the documentation.

**Comment by mah11** [comment]
OK, file adjustments all done.

**Comment by kimrutherford** [comment]
Great, I'll update the code.

**Comment by kimrutherford** [comment]
The code now parses the config files correctly.  But I still need to fix it so that pays attention to role when decided which relations to show.
