### ISSUE TITLE
Fix allowed domain and range

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1012]

**Comment by ValWood** [comment]
i.e anything which  does not have the recorded relationship available for the term ID or  eventually also which is 'out of range'

**Comment by kimrutherford** [comment]
Need to decide what to do with "qualifier=different_pathway", "qualifier=contributes_to" and "qualifier=NOT".

**Comment by kimrutherford** [comment]
And "col17=PR:000027576"

**Comment by ValWood** [comment]
Oh yeah, I had forgotten about these. Can discuss this mornign (if you are avaiable fro 10 o'clock call). I didn't confirm...

**Comment by ValWood** [comment]
we forgot about this one...

**Comment by kimrutherford** [comment]
I should be able to send a log of problem extensions today.

**Comment by kimrutherford** [comment]
Here are the current warnings:
  https://www.dropbox.com/s/a3j9qvgezi1z9xs/v10_extension_warnings.txt?dl=0

Many of them (like "qualifier=NOT") will be fixed by the upgrade script.  Let me know which of the qualifiers in the extensions should be kept and I'll remove the warnings for them.

**Comment by ValWood** [comment]
looking good.

Most of the other anomolies will be fixed during normal log processing.
I spot a couple which may not be...will open a ticket.
val

**Comment by ValWood** [comment]
I'm going to move this to a new ticket as it is separate from the original issue.

**Comment by ValWood** [comment]
I misunderstood what the original purpose of this ticket was based on my comment
i.e anything which does not have the recorded relationship available for the term ID or eventually also which is 'out of range'

will sort tomorrow....sorry

**Comment by ValWood** [comment]
Is this  covered by #1006 and #1007 ?

**Comment by kimrutherford** [comment]
Could you explain this one a bit more?  I'm not following.
