### ISSUE TITLE
Add a shortcut way to add multiple independent extension

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1013]
How should we implement the equivalent of the "|" from the text version of extensions?

**Comment by ValWood** [comment]
From discussion
First, just allow by duplicating and editing.

Later will be a "big button" upon completion to re use the core annotation  you just made with a different extension.

Midori put some text in another ticket, I think? which we will probably still be able to use.

**Comment by ValWood** [comment]
When this is implemented, the following text addition is required:

When you finish one extension, you will have the option to add another independent extension. Any extension may be single or compound.

**Comment by ValWood** [comment]
This was Midori's original suggestion
from 
https://github.com/pombase/canto/issues/989

==
Initial step-by-step extension interface:
After clicking a relation to get the gene selector or autocomplete box (as appropriate), include two buttons: "Add another part to this extension" and "Finish this extension".

Then, after hitting "finish this ...", buttons for two possible next steps: "Add a separate extension" (goes back to full set of allowable relations, i.e. starts over) and "Finish all extensions" (exits extension interface and proceeds to final comment box).
==

I think you had a slightly different suggestion KIm?

**Comment by ValWood** [comment]
As a stopgap
duplication and editing works. However the user will not know this is possible.

I suggest, (VERY TEMPORARY STOPGAP, ADD TEXT)
You can use more than one of these types in one extension (this creates a "compound" annotation extension and implies that the extensions occur together).
You can add additional extensions to this annotation by duplicating an annotation and editing the extension.

The above suggestion (#989) sound slightly complicated

When you have completed and extension (i.e this page):
![insert here create the same annotation with a different extension](https://cloud.githubusercontent.com/assets/7359272/11337957/ec6d8c94-91e8-11e5-94eb-8e098da3edf7.jpg)

There could be an option:
"create additional extensions for existing annotation"  {button] (I think Kim aslo suggested this at some point)?
Clicking this button could provide a duplicated annotation , requiring only that the extension box is filled in (but could use the same code as the current extension editing )?

Then the temporary text suggested above would change to reflect this

**Comment by ValWood** [comment]
After chatting with Kim.

Thoughts. Duplicate and edit  should hopefully be really obviuos. If it isn't  users are missing a big part of the functionality.
Therefore maybe the first approach for this is to make this feature obvious. Kim has suggested some text at the point when you are about to complete an annotation along the lines

"After completing this annotation, to create another annotation quickly you can duplicate and edit any field"

Kim will do this sooner.

After user testing we can include some in line help for first time users (the sort you can dismiss so that it does not clutter up the interface on subsequent use)

**Comment by ValWood** [comment]
There is no another ticket to add the prompt for duplicating. The current interface is useable. We might need longer term improvements, I'll keep this as a place holder to describe more fully. Also happy to close and open another ticket when we know what changes we want.
This ticket will finish the short term suggestion:
https://github.com/pombase/canto/issues/1059

**Comment by ValWood** [comment]
closing, we will open new if further changes required....
