### ISSUE TITLE
Allow distinct genotypes that differ only by mating type

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1014]
At present, Canto ignores the text in the background box for the purpose of determining whether one genotype differs from another in a session. That's usually OK, because if an allele is important we'll put in the genotype proper. But for mating type, we don't have a convenient single gene to use to add an allele as usual.

What we'd like is for Canto to let us use the most common mating type designations -- i.e. h-, h+, and h90 -- as alleles somehow.

Antonia suggested tickboxes; I wouldn't mind entering them in an interface more like the usual allele-addition setup, maybe with a "mating type" button analogous to the gene buttons. Whatever's easy to code ... my goal is simply to be able to represent mating type in genotypes so we can capture the phenotypes where it makes a difference.

Let me know if I should also open a Chado ticket for anything connected with this.

**Comment by kimrutherford** [comment]
> At present, Canto ignores the text in the background box for the purpose of determining whether
> one genotype differs from another in a session

Would it be OK to not ignore the background when comparing genotypes?  Perhaps we could chat about this on the next Skype call.

**Comment by ValWood** [comment]
yes let talk about this on joint call. Tomorrow if possible?

**Comment by ValWood** [comment]
can we put some suggestion as to which text should be supplied?


![background](https://cloud.githubusercontent.com/assets/7359272/10755504/12821de0-7c96-11e5-8507-9979ee9a2c20.jpg)

**Comment by ValWood** [comment]
e.g.  leu2, h+

**Comment by kimrutherford** [comment]
I've read through this again and I think I'm missing something.  Could the fix for this just be to put the mating type in the background box.  And then make sure Canto treats genotypes as distinct if they have different alleles or background?  That's a quick fix it that's what's needed.

**Comment by mah11** [comment]
Yes, it will work to put the mating type in the background box now. Back when this ticket was opened, that wasn't the case, but Canto stopped ignoring the background for #1042. It's all fine now :)
