### ISSUE TITLE
Add Sequence Ontology to the Canto instances

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1018]
Do we need the full SO or will SOFA do?  SO isn't that big so either is fine.

**Comment by ValWood** [comment]
I don't really understand the difference. All I understand is that SOFA is a subset. We would know if we needed SO if anything we have used sofar is not in sofa.
I suspect SO.

**Comment by kimrutherford** [comment]
> I suspect SO.

OK, I'll do that.  It's not very big ~ 2500 terms.

**Comment by mah11** [comment]
We need the full SO -- we're using several terms that are not flagged as being in SOFA.

**Comment by kimrutherford** [comment]
> We need the full SO -- we're using several terms that are not flagged as being in SOFA.

Thanks.  I've added the full SO now so those annotation extensions that have a SO term in the range should work.  Currently it's all or nothing for SO terms in ranges because of #1023.

(There is a bug that is a problem though, which I'll fix tomorrow: https://github.com/pombase/canto/issues/1008#issuecomment-153681139)

**Comment by kimrutherford** [comment]
> (There is a bug that is a problem though, which I'll fix tomorrow: #1008 (comment))

There's still a bug but #1008 is the issue for that.

**Comment by kimrutherford** [comment]
Unfortunately adding SO causes problems when updating the ontologies in the main Canto.  There are some relations in SO that are in the existing ontologies (eg. "non_functional_homolog_of", "positively_regulates" and "has_part").  The loader is failing when it tries to stores a relation a second time.  I don't understand why that's a problem.  I'm looking into it.  

It works in the test tool which makes things more confusing - it's the same OBO files.

I'm reopening and I'll investigate.  For now I've removed SO from the ontology update script so that the update will work again.

**Comment by kimrutherford** [comment]
I think I've fixed the ontology loading problem and fixed a problem that been in the code for ages.  The ontology load is running now and should be done in an hour or so.

**Comment by kimrutherford** [comment]
The update finished without error so hopefully the latest terms should be in Canto now.  Let me know if you spot any problems.
