### ISSUE TITLE
Allow for free-text range values

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1019]
In some cases the best we can do is have a free-text field as the range.  Hopefully this won't be common and can will mostly be a temporary solution.

Until we get a better solution, we'll need it for #985 and #1006.

**Comment by ValWood** [comment]
and #1007 ?

**Comment by kimrutherford** [comment]
This is needed for penetrance too: "FYPO_EXT:1000000|%"

**Comment by kimrutherford** [comment]
The annotation extension config file can now have comment lines starting with "#".  So see can now comment any dodgy hacks like making ranges free text.

**Comment by kimrutherford** [comment]
I've added a temporary hack to just use the first part if you have a "|" in the config.  eg. "FYPO_EXT:1000000|%" will be treated as if the range was ""FYPO_EXT:1000000".
