### ISSUE TITLE
penetrance and expressivity not working

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1020]
testing FYPO annotation extensions ...

Both "penetrance" and "expressivity" options appear when they should, but they don't work. 

I've tried typing in text (e.g. "high", "low" for both, or numbers for penetrance, a la 47%) and FYPO_EXT IDs, but the same non-thing happens every time: No autocomplete suggestions appear, the "OK" button never becomes active, and the only possible action is to hit "cancel".

It doesn't seem to matter whether I use the multi-step interface or the Edit or Duplicate links, nor whether I'm logged in or not. Same symptoms.

**Comment by mah11** [comment]
p.s. penetrance may fall afould of #1007, because its range is "FYPO_EXT:1000000|%", but that wouldn't explain why expressivity is also borked, as it has only FYPO_EXT:1000000.

**Comment by kimrutherford** [comment]
> penetrance may fall afoul of #1007, because its range is "FYPO_EXT:1000000|%",

Yep.

> but that wouldn't explain why expressivity is also borked, as it has only FYPO_EXT:1000000

It's currently hard coded to allow GO terms as ranges, but nothing else yet.  I'll fix that.

**Comment by kimrutherford** [comment]
> It's currently hard coded to allow GO terms as ranges, but nothing else yet. I'll fix that.

Just fixed that.  I need to load the FYPO_EXT terms into the test Canto.  That will be done by morning.

> penetrance may fall afoul of #1007, because its range is "FYPO_EXT:1000000|%",

I've implement the hacky fix of ignoring everything after the "|", so that example should work in the morning.

It might be easier for the new users if the text for penetrance said something like "penetrance (i.e. high, low, medium or complete)" for now.  I'd made a new issue (#1022) for the idea of having a dropdown menu to select the term if the ontology is small.

I'll close this after I've check that the test tool is OK.

**Comment by ValWood** [comment]
Hmm, I think it would be better for curators if we could default to % for penetrance (I use that much more then the FYPO_EXT ID). Is that possible without changing the order in the files?
I know you are going to work on this first up after the initial changes but I reckon it would be a lot less fixing up for us...  would also force everyone to think about using % for penetrance...

**Comment by Antonialock** [comment]
I use the IDs more :p

On Wed, Nov 4, 2015 at 8:31 AM, Val Wood <notifications@github.com> wrote:

> Hmm, I think it would be better for curators if we could default to % for
> penetrance (I use that much more then the FYPO_EXT ID). Is that possible
> without changing the order in the files?
> I know you are going to work on this first up after the initial changes
> but I reckon it would be a lot less fixing up for us... would also force
> everyone to think about using % for penetrance...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pombase/canto/issues/1020#issuecomment-153634472>.
>



-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by kimrutherford** [comment]
> Is that possible without changing the order in the files?

Do you mean the order in the config file?  Why wouldn't you want to change that?

Supporting % for penetrance means implementing a free-text option for ranges.  I'm planning to do that next-ish.

If we have free-text as the range in these cases you'll be able to put a % or a FYPO_EXT term and the Chado loader will check and log problems.  It's a temporary solution but it's not the worst one ever.

**Comment by ValWood** [comment]
don't worry. I can do % in comments in the interim, for the hopefully short period that we will be using the new tool but  can't do both. It might be that we don't make the switch until both are available....we'll see what is done by the end of the week...
We can test a bit more now anyway......

**Comment by mah11** [comment]
I definitely use both, and it's a toss-up whether I use fypo-exts or percents more.

Anyway, both penetrance and expressivity seem to be working nicely with the FYPO_EXT term names. Yay!
