### ISSUE TITLE
Handle sub-ontologies in ranges

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1023]
We need to handle the case where the range constraint in the config file isn't the root term of an ontology.  eg. we'd like to be able to put "actomyosin contractile ring" (GO:0005826) instead of cellular_component as the range.

The main thing to implement is changing the term name autocomplete to restrict matches to a sub-ontology.

Note to self: we need to be able to restrict to allow multiple sub-ontologies as the restriction. eg "GO:0005826|GO:0051286"

Labelled as "next" for now.

(I thought I made an issue for this by apparently not)

**Comment by kimrutherford** [comment]
I've mostly implement this but I need some input.  When you configure the range of the relation to be a subset of an ontology like in this line:

    GO:0006897      is_a    occurs_at       GO:0032153|GO:0051286   occurs at       0,1     user

the term search box should only show descendants of GO:0032153 or GO:0051286 - no problem.  I just want to make sure you want to show the same descendants you get when you "drill down" to child terms in the interface.  Should it follow the same relations.  Here's the current list:

      - is_a
      - has_output
      - output_of
      - part_of
      - has_part
      - regulates
      - negatively_regulates
      - positively_regulates

**Comment by ValWood** [comment]
I think it could probably be restricted to is_a or part of. If anything is missing we can add a new line to the config.

**Comment by kimrutherford** [comment]
Ah, I should have said: it's easiest for me if we use the same relations as we do when we search the full ontology because then I don't have to change the loading code too much.  I can modify that if you like to use only is_a or part_of.

**Comment by ValWood** [comment]
I'm not convinced that the  AE relations will be the same for all GO  relationships.
I think in some places (for example with regulates) the relationship in the extension will change.

**Comment by kimrutherford** [comment]
In that case we would we need to change the configuration file to include the relation to follow for the range, like?:

    GO:0006897      is_a    occurs_at       is_a(GO:0032153)|part_of(GO:0032153)|is_a(GO:0051286)|part_of(GO:0051286)   occurs at       0,1     user

**Comment by ValWood** [comment]
Oh yeah, thats a pain. : Lets see if Midori  has any suggestions.

**Comment by mah11** [comment]
Drat, I was hoping to stay below the radar ;)

Short term: load 'em up as usual. See if we have any problems. If not, carry on. (I think we may well get away with it, because having the same things appear in a given ontology's drilldown everywhere it's used isn't a bad thing, and could well balance out any problems arising from having a term appear that you wouldn't want in an extension. I bet it won't make a big difference to the distribution of users between the "won't pick a stupid term anyway" and "will be flummoxed by the whole shebang anyway" camps.)

If we do have problems, then we suck it up and make the configuration file changes, and associated loader changes, knowing that we've shown it's worth doing.

**Comment by ValWood** [comment]
OK lets do that.....it should actually be OK for annotation. We could deal with the regulates by using a  different display label. You're right we shouldn't do it until we know that its necessary and right now I'm not sure...

**Comment by kimrutherford** [comment]
I think this is now ready for testing - if a range if configured with a term ID or term IDs separated by pipes, the range term name complete should show only that term and its descendants, as configured in the extension config files.  Please try it out.

@airvine

**Comment by ValWood** [comment]
works for me for SO

**Comment by ValWood** [comment]
yay, new stuff, new tickets
