### ISSUE TITLE
possible bug in  term editing pop up?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1024]
In this session
curs/7d2c05ef7277f909

I wanted to fix 
abnormal mitotic chromosome condensation
in the multigene section to a more specific term
abolished mitotic chromosome condensation at the kinetochore

The  odd  thing is that this term showed no existing children link. However in the pull down I can see
"decreased mitotic chromosome condensation"

which should be a descendant of  "abnormal mitotic chromosome condensation"

**Comment by kimrutherford** [comment]
I'm confused.  I can't see any child terms for "abnormal mitotic chromosome condensation" in the latest FYPO.  I can't see a term with the name "abolished mitotic chromosome condensation at the kinetochore".

Here are the term details for "decreased mitotic chromosome condensation", as of 2 hours ago.  It's not a child of abnormal mitotic chromosome condensation.

    [Term]
    id: FYPO:0003286
    name: decreased mitotic chromosome condensation
    def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which mitotic chromosome condensation occurs to a lower extent than normal." [PomBase:mah]
    synonym: "decreased mitotic chromosome condensation during vegetative growth" EXACT [PomBase:mah]
    synonym: "reduced mitotic chromosome condensation" EXACT [PomBase:mah]
    is_a: FYPO:0000159 ! abnormal chromosome condensation
    is_a: FYPO:0001346 ! DNA metabolism phenotype during vegetative growth
    intersection_of: PATO:0002052
    intersection_of: happens_during GO:0072690
    intersection_of: inheres_in GO:0007076
    created_by: midori
    creation_date: 2014-04-15T14:27:46Z

**Comment by ValWood** [comment]
OK, could be a missing rel in FYPO will move (i.e copy, only thing I miss from SF!)
 to FYPO tracker.

**Comment by ValWood** [comment]
moved to https://github.com/pombase/fypo/issues/2409
