### ISSUE TITLE
add prompt to encourage correct specification of disruption alleles

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1025]
Can we have 

e.g  pom1::ura4+ *under* the pull down

to encourage the correct syntax in the allele name field. Maybe there is another ticket about this but everything I could find by searching is closed. We can refine with other allowed 'types'

**Comment by ValWood** [comment]
like this for amino acid

![allele](https://cloud.githubusercontent.com/assets/7359272/10954351/c99d34f6-8344-11e5-8dd5-719f0ff04ac2.jpg)

**Comment by kimrutherford** [comment]
Sorry I don't follow.  Why do you want to show an example of the allele description before showing the box it goes in?  Won't that be confusing?

**Comment by ValWood** [comment]
Yes you are correct. That s for teh allele description, I'm referring to the allele name.

Could this be "greyed out" in the allele name box
(like e.g cdc2 on the PomBase search box)

**Comment by kimrutherford** [comment]
So put "e.g pom1::ura4+" under the dropdown just for "mutation of single amino acid residue"?

> Could this be "greyed out" in the allele name box

Do you want "e.g pom1::ura4+" in the allele name box too?

**Comment by ValWood** [comment]
nope ignore the amino acid mutations  stuff. It was just to display for another allele type but it was totally wrong.

only  put   greyed out
e.g. pom1::ura4+
in the allele name box.   Nothing else.

**Comment by kimrutherford** [comment]
Which allele types should it be displayed for?

**Comment by ValWood** [comment]
only disruption

**Comment by ValWood** [comment]
This is very similar to the text addition you just did for deletions.  Its just a prompt to encourage the correct syntax (quick)

**Comment by kimrutherford** [comment]
> This is very similar to the text addition you just did for deletions

Which text addition?  None of the other allele types put a greyed out text in the allele name box.  For deletions we put in eg. "cdc11delta", put it's not greyed out - you can edit it. We have suggestions for the descriptions but they are underneath rather than in the description field.

There's no problem putting some greyed out text in the allele name box, but I wanted to check I'm not confused before I go ahead.

**Comment by mah11** [comment]
I think it would be fine to put the suggestion under the description field, not in it. We just want an example to show up somewhere.

Nitty-gritty pedantic thing: "e.g." should have two dots everywhere (right now most of them have "eg.", missing the first dot).

**Comment by kimrutherford** [comment]
Fixed in the test Canto.

**Comment by ValWood** [comment]
I don't see the text where I expected to. i.e. here:

![result](https://cloud.githubusercontent.com/assets/7359272/13734476/4a572ba8-e996-11e5-8794-250ff8b21ecf.jpg)

**Comment by ValWood** [comment]
I see it now....

**Comment by kimrutherford** [comment]
Sorry, I forgot to update the test Canto with the change.
