### ISSUE TITLE
confusing reporting of "non new" sessions as "session created TODAY"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1027]
On 05/11/2015 09:57, Antonia Lock wrote:
> No, also this one isn't new, I started it quite a while ago and finished it the other day.
> Sessions created on 2015-11-04 with no curator
>  http://curation.pombase.org/pombe/curs/174f38dca3c10a1e PMID:23022480 "Mpn1, mutated in poikiloderma with neutropenia protein 1, is a conserved 3'-to-5' RNA exonuclease processing U6 small nuclear RNA."

> On 5 Nov 2015, at 08:15, Valerie Wood <vw253@cam.ac.uk> wrote:
>>
>> Any idea why these appeared in "curation started" list yesterday?
>> does this just mean that an approved session  was "reactivated"
>> I thought things only appeared in "curation started " once?
>> not a big deal, just thinking about this for later....

**Comment by kimrutherford** [comment]
> I thought things only appeared in "curation started " once?

Currently, if you reactivate a session it's as if you restarted the session.  The state of the session is set to CURATION_IN_PROGRESS and the CURATION_IN_PROGRESS timestamp is set.  So session can appear in "curation started" than once.

"curation started" is a list of those session the went into the "CURATION_IN_PROGRESS" state today.

**Comment by ValWood** [comment]
I think for the sessions we first spotted, curation had not need restarted (at least from the e-mail conversation with Antonia). However, don't work about this. I'll close and open if we get another example.
