### ISSUE TITLE
re establish has_part links

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1031]
A while ago, we remove has_part links from Canto because they were confusing for 'normal' phenotypes.

Midori has now removed has_part relationships from this branch so we would like to try again (it will improve annotation specificity if we have the links

**Comment by ValWood** [comment]
Just to check, this will go back in the way it was before. I think that its the opposite way around to the other relationships (i.e you show the whole, not the parts). Midori will be able to explain this better or point to a previous explanation). I can't explain it because I'm not allowed to use the words  'ancestors' or 'descendants' when I'm referring to has_part....

**Comment by kimrutherford** [comment]
> Just to check, this will go back in the way it was before. I think that its the opposite way around
> to the other relationships

No problem!  Midori helped me understand the has_part/part_of stuff last time this came up.  So I've gone through the pain on working it out and the code is in place to handle has_part - it's just that they aren't loaded at the moment.  I'll change the test Canto first so you can have a quick check.

**Comment by ValWood** [comment]
good plan, we all need to do some canto testing anyways. On my list for first thing Monday mornign... (don't worry if this isn't done, I will test AE thoroughly first)

**Comment by kimrutherford** [comment]
> A while ago, we remove has_part links from Canto

That's true, but I then added it back.

The long story is that has_part was added to Canto on Jan 29th (for FYPO only), then removed on Apr 30th, then added back again on May 19th.  Here's the ticket from May 19th:
  https://sourceforge.net/p/pombase/curation-tool/841/

has_part should be in the current Canto.  If it's not working please let me know.

**Comment by mah11** [comment]
Hereby letting you know it may not be working. Antonia reported https://github.com/pombase/fypo/issues/2457, which suggests Canto isn't properly using the has_part links in FYPO.

Happy to provide more info if it'll help.

**Comment by kimrutherford** [comment]
> Hereby letting you know it may not be working

Thanks.  It's not working for my test data either.  I'll fix it.

**Comment by kimrutherford** [comment]
> It's not working for my test data either.

Actually it is working for the test data but has_part confused me (big surprise!)

But all the has_part relations are missing from the main Canto for FYPO.  There are has_parts in the main Canto for SO which is confusing.  My guess is that loading SO has screwed up FYPO.  I'm trying to work out how.

**Comment by kimrutherford** [comment]
The problem was triggered by adding SO to the load.  I removed SO and it's been working fine but I've been struggling to fix things properly.  I think it's OK now and I'm testing on the test Canto.
