### ISSUE TITLE
different behavior of term suggestions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1032]
I'm not sure if this is caused by 
a) canto b) ontology or c) config file

If I  do
regulation of phosphorylation (GO:0042327)
I get the suggestion
regulates phosphorylation of ...

if I do
regulation of protein acetylation (GO:1901983 )

I get
regulates modification of ...
regulates acetylation of ...

I will refine the modification so that all the specificity is on the individual terms (or make it generic to the modification term). However, I think we should figure out what causes this as from a look at the ontology the parents are  equivalent.

**Comment by ValWood** [comment]
The acetylation one comes from
GO_BP_A_E_config:GO:0031399	is_a	has_regulation_target	ProteinID	regulates modification of	0,1	user

(I will delete this anyway as we can make the extensins appear only for specific children).

However before I do, the question is why doesn't it appear currently  for 
regulation of phosphorylation?

regulation of protein modification
is_a regulation of protein phosphorylation

**Comment by ValWood** [comment]
It might not be a bug, but Its behaviour I can't account for...

**Comment by kimrutherford** [comment]
This is making my head hurt, but could it be that you searched for:

GO:0042325 	regulation of phosphorylation
(which isn't a child of GO:0031399, regulation of protein modification process)

but you were looking for?:

GO:0001932 	regulation of protein phosphorylation
(which is a child of GO:0031399)

**Comment by ValWood** [comment]
doh, thats it...
So I need to refine so that the 
"modifies" is used for the non protein children and remove the parent one

**Comment by ValWood** [comment]
done
