### ISSUE TITLE
refine text for specifying genes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1033]
I wonder if we could do  something clever here:

![refine text](https://cloud.githubusercontent.com/assets/7359272/11336982/55d10588-91e1-11e5-9bef-dc9e159cc878.jpg)

**Comment by ValWood** [comment]
Currently whatever you are annotating the extension is always  going to be a gene.

Hoever, users might find it a bit disconcerting, they are describing which protein, or mRNA is being modified and they are asked to choose a gene.

We could use the information in the config file to make this a little bit clearer.

So, if the config file says
ProteinID  
the pop up could say

instead of
Add a relation 
processes [choose gene]] Add another gene


Choose
processes
protein encoded by [[ gene]]

and similarly for transcript TranscriptID

**Comment by mah11** [comment]
On a related note, the box in question shouldn't have "add a relation" as its header, because at this point the relation has already been chosen. It could say "Add details" or "Finish extension", or just show the display text without putting anything in the header space.

No objection to having the box add "transcript of", "protein encoded by", or similar based on the ID type in the range (tho I doubt it'll bother many users if we don't).

**Comment by ValWood** [comment]
Yeah my text above suggests 
"Add a relation" to 'Choose"
"Add details" is better, but you are right, I don't think it needs anything. Fewer words. Good.

**Comment by kimrutherford** [comment]
> "Add details" is better, but you are right, I don't think it needs anything. Fewer words. Good.

I've removed the header.

>  [choose gene]] Add another gene

Would it help if it showed:

    [choose protein] Add another protein

When you configure "ProteinID"?

and

    [choose transcript] Add another transcript

for TranscriptID, etc.

Or would that just be more confusing given that you can only choose gene IDs?

**Comment by ValWood** [comment]
Not sure.... see what others think... that would probably work. It might be work, especially if the pull down doesn't actually say "gene" too...
I think the pombe community are already trained to use gene names in context. We often use them when we are referring to proteins.

We could also always be more precise later......

**Comment by mah11** [comment]
"Choose a protein" (or transcript or whatever) would be OK. I still don't think it will cause much confusion whether we do that or not.

For adding more, how about just "Add another"? If it already says "choose protein" (etc.) there's no particular need to repeat gene/protein/transcript a mere inch away.

**Comment by ValWood** [comment]
OK

**Comment by kimrutherford** [comment]
> For adding more, how about just "Add another"?

Good idea, I've changed that.

**Comment by kimrutherford** [comment]
If I read this correctly there's nothing more to do.
