### ISSUE TITLE
refine text on edit extension box

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1036]
![refine](https://cloud.githubusercontent.com/assets/7359272/11338862/7795c5de-91ee-11e5-955c-eaa5738f977e.jpg)

**Comment by ValWood** [comment]
So this one would say
has function during "GO process"

**Comment by mah11** [comment]
This is a combination of two things:

- That's a bug making "rangeOntologyScope: [GO:0008150]" appear
- Add the text you want after "during" to the config file

**Comment by kimrutherford** [comment]
> That's a bug making "rangeOntologyScope: [GO:0008150]" appear

Sorry, that was debug code that I thought I'd removed.  I will disappear next time you reload a page.

Fixed by: 8f64b9219642

**Comment by ValWood** [comment]
Should work now?

**Comment by kimrutherford** [comment]
> Should work now?

I've just the "GO process" text to the config file.  It should appear by the morning.

**Comment by ValWood** [comment]
A gah sorry thats me.

So now it will say 
has function during GO process  [GO:0008150]"

it should just be "has function during". I was confused by the bug.  will fix

**Comment by ValWood** [comment]
removed. we  can refine when we see how users get on....
