### ISSUE TITLE
 trivial change to display of in progress extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1037]
Currently in progress annotation extensions are displayed: 
![display](https://cloud.githubusercontent.com/assets/7359272/11339480/a158e650-91f1-11e5-9ef2-ce962dd8c69a.jpg)

I think it would be better if the compound extensions were displayed 

Extension added so far
has,substrate cdc2 (delete), happens during xxx (delete)

to match how they are displayed on the gene pages and to emphasize that it is a single extension

(and singularize, as its a single compound extension)

**Comment by mah11** [comment]
Hmm. Good point about it being a single compound extension, but I'm not a big fan of "delete" links in the middle of a line of text. It would be a bit harder to be sure which bit would be deleted by each link.

**Comment by ValWood** [comment]
I did think that too about the embedded delete buttons.....

My original thought  was a single edit  button, then somehow a pop up the the ability to change independently from that point..... 

I  really prefer comma separated on a single line as reinforcing the "compoundness".

Lets see  if Kim has any ideas about presentation.....

**Comment by kimrutherford** [comment]
> Lets see if Kim has any ideas about presentation.....

We could have litle red crosses inline, like this:
![delete_icon](https://cloud.githubusercontent.com/assets/90474/11376253/8764c436-9344-11e5-94dc-48511306aa13.png)

**Comment by ValWood** [comment]
I like that....do you think you can make it clear that the x applies to a specific extension. maybe a shaded area around each annotation rather than just text  (that might be a rubbish idea). Again, see what others think.

But, OMG  now I have a smart phone I know all the  'action iconography'. Instructions really aren't necessary are they?

**Comment by kimrutherford** [comment]
> I like that....do you think you can make it clear that the x applies to a specific extension.

I think it will be OK just having it straight after the thing it will delete but let's try it and see.

**Comment by kimrutherford** [comment]
I've change the delete... to a "X" icon and put extensions on one line.  And I've changed "Extensions added so far" to "Extension added so far".

**Comment by mah11** [comment]
I don't love it, but mostly for individual aesthetic reasons (e.g. the "X" isn't quite aligned properly with the text on my screen; the spacing around the comma looks messy, especially in the annotation table; I'm an old curmudgeon who worries than only _almost_ everyone knows "the action iconography").

One less subjective point: the "X" icon is a smaller mousing target than the "delete" text was.

I've also just tested a long extension and seen that the text wraps, so it's not always going to be on one line anyway.

**Comment by kimrutherford** [comment]
I've improved the rendering of spaces around the commas in the annotation table.  Sorry about the alignment of the delete button.  It's challenging to get it right for inline images.

Slightly related, this text doesn't seem great: "Extension added so far".  Is it OK as is?

**Comment by ValWood** [comment]
Extension added?

**Comment by kimrutherford** [comment]
I think my problem with it is that the extension isn't added to anything at that point, we're still building it up.

**Comment by ValWood** [comment]
Extension created?

**Comment by ValWood** [comment]
Aesthetically  maybe a less "think" icon would look better?
One of these in red?

![x icon](https://cloud.githubusercontent.com/assets/7359272/11422096/27719584-9431-11e5-844b-27de8ce9b3cf.jpg)

**Comment by mah11** [comment]
>  Sorry about the alignment of the delete button.

Yeah, don't worry about me being fussy about alignment. In a few days I'll stop noticing ;)

Red's dangerous because it's hard for color-blind people to see.

For the wording, how about "Current extension details" or just "Current extension"?

I'll also put some comments on #1034 for the rest of the text.

**Comment by ValWood** [comment]
well not hard for them to see, they will see it a different colour, which is OK, but red signals 'delete' best

**Comment by mah11** [comment]
It very much depends on the exact shade of red, and the individual -- reds tend to look grey, and therefore don't stand out from background well.

**Comment by ValWood** [comment]
grey wouldn't look bad though.... They are grey on this page....I know theres a variation, but it doesn't really seem to stop people using red or green in applications, so it can't be a huge issue. We aren't flying planes here ;)

**Comment by mah11** [comment]
> it doesn't really seem to stop people using red or green in applications

that is because too many develpers are thoughtless

**Comment by ValWood** [comment]
Well it isn't really a problem if the contrast is strong,  I don't care if they can't see the exact shade we have painstakingly selected, if its visible in some colour!

**Comment by kimrutherford** [comment]
Let's close this for now and open a new ticket when we think of a better way to do this.
