### ISSUE TITLE
bundle 2 relations displaying the same text

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1038]
there are two "required for", for PSI-MOD extensions
GO:0008150
GO:0003674

can these be bundled into one?
![screen shot 2015-11-23 at 15 36 34](https://cloud.githubusercontent.com/assets/12727506/11340921/1b2e3592-91f8-11e5-958e-4fa4a62ca922.png)

**Comment by mah11** [comment]
GO:0008150 is the BP "root"; GO:0003674 is MF (and no, I didn't have to look them up ...)

So maybe separate "required for process" and "required for activity" would be best.

**Comment by Antonialock** [comment]
ok I changed it

**Comment by ValWood** [comment]
...be disappointed if you did......

**Comment by Antonialock** [comment]
:p I thought it might be neater to bundle but on second thought yeah, it would be really un-neat to search two different ontologies :-)

**Comment by ValWood** [comment]
i was referring to  :
and no, I didn't have to look them up ...)

**Comment by kimrutherford** [comment]
> GO:0008150 is the BP "root"; GO:0003674 is MF

Just to check: in the current config you can 0 or 1 or each of those.  Is that what's needed?  You could have the range as "GO:0008150|GO:0003674" is you wanted to and allow any term from either BP or MF.
