### ISSUE TITLE
excluding a sub-branch of an ontology from extension ranges

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1040]
We may eventually want to be able to specify an extension range as is_a ID:nnn1 but NOT is_a ID:nnn2 (where nnn2 is_a nnn1), to avoid having irrelevant terms appear in the extension autocomplete.

The use case I've spotted so far is for SO -- I've put SO:0001411 biological_region as the range for FYPO:0000063 (abnormal DNA recombination), but the SO term also encompasses polypeptide regions, and there isn't a convenient term that groups all DNA regions but only DNA regions. The range specification 'is_a SO:0001411 but not is_a SO:0000839' would work.

For now we can just hope people choose sensible terms, and don't get too put off by seeing terms that wouldn't ever apply (a la #1023).

This is analogous to the topic in #1021, but for the range instead of the annotated term.

**Comment by ValWood** [comment]
It seems a bit crazy that there is no way to specify DNA vs protein sequence region using SO (or didn't I get it?).

If that's the case, maybe a SO request could fix this?

**Comment by kimrutherford** [comment]
> We may eventually want to be able to specify an extension range as is_a ID:nnn1 but NOT is_a ID:nnn2

If it's needed, I _think_ this should be easy to implement now that the ontology subset stuff is done.

**Comment by mah11** [comment]
Might as well do it if it's easy, but it's not worth delaying the main extension interface release.

What should I put in the config file? ID:nnn1!ID:nnn2 or similar?

Val - I can put in a SO request in parallel, but I suspect there's a general case for Canto here, not just the specific SO branches that made me think of it.

**Comment by ValWood** [comment]
OK, good point.

**Comment by kimrutherford** [comment]
> Might as well do it if it's easy

It's easy-ish but I think delaying until other interface stuff is done is a good idea.

> What should I put in the config file? ID:nnn1!ID:nnn2 or similar?

I think:

    ID:01245-ID:567483

If it gets more complicated than that, I think  brackets are a good idea to make it clear what's going on:

     (ID:01245-(ID:567483&ID:00002))|(ID:61245-ID:00001)

I hope it doesn't come to that though :-)

**Comment by mah11** [comment]
> I hope it doesn't come to that though :-)

Me too!

I'll leave updating the FYPO config until this is implemented. No hurry. Syntax looks fine.

**Comment by mah11** [comment]
basically duplicates #1048, and I've just updated the FYPO extension config

**Comment by kimrutherford** [comment]
> (ID:01245-(ID:567483&ID:00002))|(ID:61245-ID:00001)

I've implemented a basic version of this.  The brackets aren't needed:

    ID:01245-ID:567483&ID:00002|ID:61245-ID:00001

If things get more complicated we'll need brackets.  For now it's quite fussy about the format so don't put any spaces in.

I've uncommented this config line and I'll test that it works in the test tool once the ontologies are updated:

    FYPO:0001985-FYPO:0005448&FYPO:0005449  is_a|has_part   has_expressivity        FYPO_EXT:1000001  expressivity  0,1  user

**Comment by kimrutherford** [comment]
> I've uncommented this config line and I'll test that it works in the test tool

It's working so I've updated the main Canto.  Please add any other config like that you can think of so we can give it a good test.

**Comment by ValWood** [comment]
I might need this explained to me with an example. I know what we need to do but its making my head curl a bit when it comes to using.... Hopefully all will become clear when I need it...
