### ISSUE TITLE
Load PATO?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1041]
I just noticed "PATO:0000014" as a range in the FYPO config file.  Do we need all of PATO loaded?

**Comment by mah11** [comment]
Oh ugh. I guess so ... we really only need the PATO:14 branch ("color") for extensions, but PATO's not huge-normous (~2500 terms, and growing slowly) and loading the lot would save me making a mini-pato.

It's for some of the most horrible hacky term/annotation/extension combinations we've got, which makes it annoying.

**Comment by kimrutherford** [comment]
I've added PATO to the ontology load script.  I'll check that extension is working after PATO is in.

**Comment by kimrutherford** [comment]
It works except that "color" is shown as a relation twice.  It looks like these config lines are redundant:

    FYPO:0002140    is_a    is_bearer_of    PATO:0000014    color   0,1     admin
    FYPO:0002723    is_a    is_bearer_of    PATO:0000014    color   0,1     admin

and only this is needed:

    FYPO:0000741    is_a    is_bearer_of    PATO:0000014    color   0,1     admin

**Comment by mah11** [comment]
config file fixed; thanks
