### ISSUE TITLE
same allele , different backgrounds

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1042]
It doesn't seem to be possible to capture the same allele in different backgrounds. when I tried, the already used background was 'remembered'

**Comment by kimrutherford** [comment]
This was mentioned in #1014 which was closed.  I remember we talked about it on Skype but I don't remember the details.  It's relatively easy to change things so that the background is included when Cantocompares genotypes.

**Comment by kimrutherford** [comment]
Shall I go ahead and do this?  It's quite quick.

**Comment by mah11** [comment]
Sure; I can use it

**Comment by kimrutherford** [comment]
> It doesn't seem to be possible to capture the same allele in different backgrounds.

What should happen in the case where there is an existing genotype with the same alleles but:

1. the existing genotype has a background and the new genotype doesn't
2. the existing genotype doesn't have a background, but the new one does

Should the new and existing be merged in these two cases?

**Comment by kimrutherford** [comment]
I've implemented this but it's only release in the test Canto so far.  For now it assumes that two genotypes are the same if both have no background or both have exactly the same background.

**Comment by mah11** [comment]
That sounds right. It feels a bit risky to merge if the backgrounds aren't identical (or identically absent).
