### ISSUE TITLE
Make display order of primary annotations configurable

### ISSUE THREAD

**Issue by airvine** [pombase/canto#1044]
I’m wondering is it possible to change the order in which the primary annotation types are displayed? When I put the appropriate details into canto.yaml I get them displayed like this:

![image](https://cloud.githubusercontent.com/assets/1037815/11594270/f87b62a2-9aa0-11e5-81b6-d0e96b2c0486.png)

But for the purposes of PHI-base the Phenotypes are by far the most important annotation type, so it would make sense to have this at the top, or at least before the genetic and physical interactions.
I rather naively thought that I could simply change the order in which they come in canto.yaml, but this does not seem to make any difference.

**Comment by kimrutherford** [comment]
This was easier to fix than I thought.  Could you try it and let me re-open the issue if there are problems?

**Comment by airvine** [comment]
This does work, but it may have introduced a new bug.

If I've got two phenotype namespaces defined in canto.yaml, then it now displays the phenotypes dialogue twice:

![image](https://cloud.githubusercontent.com/assets/1037815/11637412/251d7cbc-9d19-11e5-8c88-7762b936125e.png)

Obviously the Phenotypes allele options should only appear once.

For PHI-base, I was trying to separate phenotypes into Pathogen Phenotypes & Host Phenotypes, using different namespaces. I can easily get rid of this problem by using one namespace, but then I can only prompt for the generic PHI Phenotype.

I guess this isn't currently an issue in PomBase, since you only have one Phenotype namespace. But I'm wondering what will happen if we start using sub-ontologies for the primary annotations? Would the Phenotype options be displayed for each sub-ontology that was chosen?

**Comment by kimrutherford** [comment]
Could you send your settings for the annotation types?  The display code is assuming that there is only one sort of phenotype annotation.  It should be a quick fix.

**Comment by airvine** [comment]
I've actually already fixed it, by using one namespace in the ontology and only referring to this one namespace. But I thought I should mention the issue because of the potential for it to occur again if we were to implement using sub-ontologies.

________________________________

**Comment by kimrutherford** [comment]
It should be fixed now - the "Phenotypes:" heading was hard coded, but isn't now.
