### ISSUE TITLE
Wrong taxonomy IDs displayed in interaction summary

### ISSUE THREAD

**Issue by airvine** [pombase/canto#1045]
There is a bug in the summary after providing details of a physical interaction. The taxon IDs of the genes are displayed. However, even when we choose genes that are from different species (which for PHI-base would be the pathogen species and the host species) the same taxon ID is displayed for both. See this example:

![image](https://cloud.githubusercontent.com/assets/1037815/11594389/a0657304-9aa1-11e5-8b4d-c3ae7d7b2934.png)

Here the pathogen species is Hyaloperonospora parasitica (taxonomy ID: 123356) and the host species is Arabidopsis thaliana (taxonomy ID: 3702), but as you can see the host taxon ID is displayed for both.

**Comment by kimrutherford** [comment]
This should be fixed now.  Could you check it's OK for you?

**Comment by airvine** [comment]
Yes, this is working now.

On a techical note, I did have to merge changes with the master branch of canto before the changes were observed. The last 8 commits of master still need to be merged with the annex-gui branch. I was able to able to do this locally in order to see all of the fixes.

**Comment by kimrutherford** [comment]
> I did have to merge changes with the master branch of canto before the changes were observed.

Sorry, I forgot about that.  I've merged the changes from master into my branch now too.
