### ISSUE TITLE
Add a has_qualifier relation and a mini ontology of range terms

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1046]
We'd like to be able to store qualifiers like "NOT", "colocalizes_with" and "contributes_to" using the new interface.  It may be useful to configure these in a similar way too so we should add these to the extension config file with the range "Boolean".

**Comment by kimrutherford** [comment]
Now I've thought about this and had a better look at the qualifiers, I think a better approach would be to have a generic "has_qualifier()" relation and configure the range to be ontology terms.

I think this because most of the qualifiers are terms that we can get from an ontology (mostly from gorel.obo and ro.obo).  So those files were loaded with could just put the IDs of the terms we need in the range column of the configuration and it would be done.

The configuration would look like this to :

    GO:0008150  is_a   has_qualifier  RO:0002325|RO:0002326   qualifier    *    admin

This has the advantage that I have very little to do except for finishing the implementation of the cardinality column.

Since these qualifiers are just for admin users for now it's not so bad that this is a dodgy user interface.  We can work on something better if we decide to make any of the qualifiers non-admin.

The only oddball is "NOT".  It's not in any ontology as far as I can see.  We could easily make up a bogus term just for Canto though ("CANTO_QUAL:00001", name: NOT, def: er...)

**Comment by kimrutherford** [comment]
After adding "is_a" manually, I've updated to the latest relationship ontology.  So now colocalizes_with and contributes_to are in Canto (or will be once it re-loads).

But, they are both relations rather than terms so storing "has_qualifier(colocalizes_with)" in Canto seems a bit odd.  colocalizes_with() should really have an object unless I'm misunderstanding things.  Or is the object implicit?  Val, what's the story?

**Comment by ValWood** [comment]
They don't have an object as such.
If a gene product has  an annotation "ribosome" and colocalizes with it means it colocalizes with the ribosome, but is not part of it. Personally I don't like then and I never use them these days. We only have 22.....There is a possibility we could represent these better some other way?

Contributes_to is similar. It is associated with a MF term, and usually means the MF is preformed by a  complex and the gene products contribute to this activity.

Does that answer the question?

**Comment by kimrutherford** [comment]
> If a gene product has an annotation "ribosome" and colocalizes with it means it colocalizes
> with the ribosome, but is not part of it.

So are these qualifiers a substitute for having a relation column in the GAF file?  If the relation was included it could be explicit:

    (gene product) part_of (ribosome)

or

     (gene product) colocalizes_with (ribosome)

And is having "NOT" in the qualifiers column the same as:

    (gene product) not_part_of (ribosome)?

In summary, is the qualifiers column a bit of a hack?

It looks like things have changed for GPAD.  The documentation is a bit thin but it sounds like an explicit relation is required but colocalizes_with is still a qualifier.  I don't understand that.

This stuff is hacky in Chado too.  We store (gene product) <-> (ribosome) with no explicit relation, ie. they are relation in Chado but the relation doesn't have a type.  The "NOT" is a boolean flag on that anonymous relation.  For colocalizes_with we add a property (qualifier) to the relation.  The property is free text so can be anything including mispellings.  Hack!

**Comment by mah11** [comment]
> In summary, is the qualifiers column a bit of a hack?

Why yes, I do believe it is.

I don't understand the GPAD thing either. I wonder if colocalizes_with is still a qualifier because they copied that over from the GAF-verse without thinking it through.

Hackity hack.

**Comment by ValWood** [comment]
yep. I will ask if there is another long term plan for these quailifiers.

**Comment by kimrutherford** [comment]
> Why yes, I do believe it is.

:-)

I updated to the most recent RO to get colocalizes_with and contributes_to into Canto but they are relations in RO.  Using relations as terms in Canto makes me a bit queasy so I think a better plan would be to make a little OBO file with the (3-ish?) possible qualifiers terms.  Then we could have a has_qualifier relation that has the little ontology as its range.  Rather hacky but simple to implement.

That's if it's worthwhile.

> yep. I will ask if there is another long term plan for these quailifiers.

I'll wait a little before implementing this in case it's not needed.

**Comment by ValWood** [comment]
Well, I think they are at least going to exist for years so I think we will have to handle them, even if at some future point there is a better way..

**Comment by kimrutherford** [comment]
> Well, I think they are at least going to exist for years so I think we will have to handle them

:-)

OK, I've added pombe-embl/mini-ontologies/has_qualifier_range.obo and changed the extension interface configuration to show a "has_qualifier" extension for GO for admin users.

**Comment by kimrutherford** [comment]
> changed the extension interface configuration to show a "has_qualifier" extension for GO for admin users.

That's working now.  It's dodgy but it's working.
