### ISSUE TITLE
Two "assayed protein ..." links showing for FYPO:0002333 on extension page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1047]
See: https://github.com/pombase/canto/issues/1007#issuecomment-164302906

**Comment by mah11** [comment]
Actually, I just tried it, and there's one "assayed protein" link now. Maybe the config file edits I did fixed it?

**Comment by kimrutherford** [comment]
I still see two.

**Comment by mah11** [comment]
Hmm. I'll check again some time today and see if I was dreaming it last time ...

**Comment by mah11** [comment]
Not dreaming; I'm seeing one copy of "assayed protein" for FYPO:0002333 itself and a handful of randomly selected descendants (e.g. FYPO:0001371, FYPO:0002338, FYPO:0003541).

My test session is http://curation.pombase.org/test/curs/892645d1cd461bbf

**Comment by mah11** [comment]
oops

**Comment by kimrutherford** [comment]
All seems fine to me now too.

**Comment by mah11** [comment]
ARGH! It's back! We both saw the duplicate "assayed protein" go away, but now it's come back.

Is there a "Heisenbug" tag?

**Comment by mah11** [comment]
close this again if you thing the newer ticket will do ... I'll put follow-up comments there ...

**Comment by mah11** [comment]
closing because I may be onto a fix in t'other ticket
