### ISSUE TITLE
error trying to delete genotype name

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1048]
Yesterday I put in a few genotypes with names in session 7881e95072db6f1d. Today I decided to delete some of the names (but leave the genotypes and their annotations otherwise unchanged). The first one worked, but now I can't do it again -- I get this message in a red box in the upper left corner:

"Storing changes to genotype failed: internal error - please report this to the Canto developers"

example: try deleting the name on http://curation.pombase.org/pombe/curs/7881e95072db6f1d/feature/genotype/edit/2

**Comment by kimrutherford** [comment]
Sorry, I meant to look at this today but didn't get to it.  It's top of my list for the morning.

**Comment by kimrutherford** [comment]
Fixed now.  It was a difference between NULL in SQL and an empty string.  The Canto code wasn't being careful enough.

**Comment by mah11** [comment]
Thanks - but did the fix get rolled out? I just got the error message again ...

**Comment by kimrutherford** [comment]
Sorry!  I forgot to re-release the test tool.  I've done that now.

**Comment by mah11** [comment]
what about live pombe canto?

**Comment by kimrutherford** [comment]
Sorry, I've re-released the main Canto too now.  My head is in test tool mode.

**Comment by mah11** [comment]
At least you know where your head is ;)  Thanks! The session is tidier now.
