### ISSUE TITLE
SF-Trac error

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1049]
Not really Canto related but I just tried to access SF-Trac and got this error:
Error

TracError: The Trac Environment needs to be upgraded.

Run "trac-admin /data/pombase/trac-sf-copy upgrade"

**Comment by ValWood** [comment]
Hi Kim,

Happy New Year.
Could you look at this one early when you get back? Probably to do with oliver 0 stuff.

Thanks

Val

**Comment by kimrutherford** [comment]
I think I've fixed this. Let me know if have any problems.

**Comment by Antonialock** [comment]
thanks! looks ok
