### ISSUE TITLE
ontology update problem?

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1050]
Did the ontology update for PomBase Canto fall afoul of the server update? Or has something else gone wrong? Our shiny new FYPO terms from last week and this week haven't appeared yet.

**Comment by kimrutherford** [comment]
Yep sorry, the update is failing.  I'll fix it.

**Comment by kimrutherford** [comment]
I've fixed the problem and the update has run successfully.

I forgot that after this change: dd66defeb8b4, I needed to add is_a to the Canto DB manually.  The latest RO doesn't have is_a.
