### ISSUE TITLE
cannot create a session

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1053]
When I try to create a session for this paper, 
PMID:15800064

I am told a session already exists, but i don't see any way to get to it..?
Usually there is a link.

**Comment by kimrutherford** [comment]
Are you logged in?

**Comment by ValWood** [comment]
I was logged in. I managed to get to it via the admin interface, but it was odd that I did not get the usual link. I think it may be because a session was already created, but not assigned to a person, so I was not getting "this session is already in progress link"....(maybe?)

**Comment by kimrutherford** [comment]
> I think it may be because a session was already created

It should show the link if the session exists, even if it's only just been created.  It works when I try it so I show it is another problems that needs a Skype debugging session.

**Comment by ValWood** [comment]
will close, and open a new ticket if it happens again....
