### ISSUE TITLE
a small tweak to text for specifying amino acid or nucleotide deletions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1055]
It worries me that people (I have!, so maybe this should just say I)
will sometimes capture deletions incorrectly.

Authors tensd to refer to the deletions  by the residues which remain (see figure below, partial deletion_aa
![partial_deletion_aa](https://cloud.githubusercontent.com/assets/7359272/12429161/9b758e48-bee0-11e5-9045-cf0128980da6.jpg)
)

HOwever, when we describe the mutant we  add the deleted amino acids.

![partial deletion_canto](https://cloud.githubusercontent.com/assets/7359272/12429180/c03fa2c2-bee0-11e5-8db4-4b6f02242bfb.jpg)

**Comment by ValWood** [comment]
so above we would do cut7d as 851-1085

I worry that if curators are not paying attention to this they will automatically do  1-430 instead

Can we add  more specific text here

e.g 100-200  (please specify *deleted* residues)

**Comment by mah11** [comment]
Good thought, but duplicate ticket -- see #1000

**Comment by ValWood** [comment]
I've outsourced  my memory to you .....
