### ISSUE TITLE
cannot duplicate multigene phenotype rows

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1056]
session appears to be bugging

curs/558b22ef42aa6ec2

I can no longer duplicate and edit (or just duplicate) multigene phenotype rows?????

**Comment by kimrutherford** [comment]
Is there an error message?

**Comment by ValWood** [comment]
no I just do duplicate in this session to a multi gene row, and nothing happens

**Comment by kimrutherford** [comment]
I just tried on the main Canto and it worked for me. Might need a Skype chat to get a demo from you.

**Comment by kimrutherford** [comment]
> I just tried on the main Canto and it worked for me.

I didn't try in your session though. I'll make a copy of the database and do some testing.

**Comment by ValWood** [comment]
it works fine for duplicating single gene (I just did it), just not for multigene

**Comment by kimrutherford** [comment]
> I just did it

I'm confused, the session is in review-only mode. How did you edit it?

**Comment by ValWood** [comment]
its in approval?

**Comment by ValWood** [comment]
I now cancelled approval. You can try now in this session.

**Comment by kimrutherford** [comment]
Sorry, I think I clicked the review link.  I've got into the session.  I was able to able to duplicate and then edit a multi-gene phenotype row.  There's now one with "has_penetrance(99%)" that you'll need to delete.

I can Skype now or tomorrow to sort this out.

**Comment by ValWood** [comment]
Ah all of the ones I tried to add and could not see have now appeared!

I could only see the first 4   in my session yesterday!

**Comment by ValWood** [comment]
Kim any clues on this? I am going to delete all of the extra annotations tomorrow when I add the new terms. I guess we will just close this and watch our for it happening again?

**Comment by kimrutherford** [comment]
> Kim any clues on this?

Not really.  We'd need to debug it live to work out what's going on.

When you edit an annotation it only updates the display once it receives confirmation from the server that the annotation is safely stored in the database.  If might be that the annotation was stored but the confirmation got lost on the way from the server to your browser.

If it happens again we should debug it live on Skype.
