### ISSUE TITLE
ability to 'drill down' hierarchy for some extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1058]
This would sometimes be useful and Alistair asked about it too.

It could work a bit like the 'editing an ontology term' feature.

**Comment by airvine** [comment]
This would be the same as suggesting child terms that we have for the primary annotations.

**Comment by kimrutherford** [comment]
I've implemented this because it wasn't too hard.  It's only beta quality though.  Also it's not selective - it pops up the confirm dialog for all terms.

**Comment by ValWood** [comment]
I tested and seems to work OK.

**Comment by kimrutherford** [comment]
Thanks, I'll close this.  Please open new issues for any tweaks you need.
