### ISSUE TITLE
prompt for adding independent extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1059]
At this point, when you have begun to create an extension

![duplicating extensions](https://cloud.githubusercontent.com/assets/7359272/12548084/da1a7590-c34b-11e5-8d56-8690f58a672e.jpg)

add the text

"After completing this annotation extension, to create another (independent) annotation extension for this gene/term combination  quickly you can duplicate and edit any field"

Midori, please suggest improved text?

Transferred from
https://github.com/pombase/canto/issues/1013

**Comment by mah11** [comment]
how about "If you want to create another independent extension for this annotation, finish the annotation, and then use the "Duplicate" feature, where you can edit any field, including the extension."

**Comment by ValWood** [comment]
good, OK!

**Comment by kimrutherford** [comment]
Where on the page should the text go?  At the bottom somewhere?

**Comment by kimrutherford** [comment]
I've added it at the bottom of the page.  Let me know if you'd like any changes.
