### ISSUE TITLE
possible bug in isoform extension pop up

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1061]
This is what I  see. I'm not sure what I'm supposed to see here....

![isoforms](https://cloud.githubusercontent.com/assets/7359272/12559994/15ff1306-c390-11e5-98bd-3c44642b386b.jpg)

**Comment by kimrutherford** [comment]
I talked to Midori about this a while ago.  We think it doesn't make sense to load the whole of the protein ontology into Canto so this should be configured as free text.  So I think the message is right.

The curators can sort out any Chado loading issues that pop up in the logs.

**Comment by mah11** [comment]
Hmm. I'm not getting the "protein isoform" option at all in test Canto, even when logged in.

And the popup in Val's screenshot doesn't look like the desired behavior -- it ought to offer a text box for an admin user to paste in a PR:nn ID.

**Comment by kimrutherford** [comment]
> Hmm. I'm not getting the "protein isoform" option at all in test Canto, even when logged in.

That's odd.  I get the same as Val in her screenshot.

> it ought to offer a text box for an admin user to paste in a PR:nn ID.

I've changed the configuration in FYPO_A_E_config so that should be changed by the morning.
