### ISSUE TITLE
reinstate text box for extensions, admin-only

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1063]
I would very much like to have the extension box remain as an admin-only feature, because it would be a RRPITA to add more than a couple of extensions per annotation via the community-friendly interface ... and I've done papers that have had MANY extensions per annotation.

Additional relevant points from #1015, where this came up as a tangent (admins may need a text box for a few qualifier types anyway):

Kim: That could be done with a bit of re-engineering. It would also mean you'd have continue to check and fix syntax problems reported in the log file.

M: I could live with that. It'll be a lot less work than going through the step-by-step interface for big sets of extensions.

K: I'll have a think about how best to implement this. I like the idea of instant feed back that would let you know when the syntax and relations were correct. I'd prefer if only valid annotation extension strings were stored in the Canto database because it makes loading into Chado more straightforward.

**Comment by kimrutherford** [comment]
A prototype of the feature is now in the test Canto.  There's a "Edit as string (admin only) ..." link on the extension editing page.

Let me know what you think.

**Comment by mah11** [comment]
It appears to be working for single extensions, simple or compound.

A few thoughts:

- For extension options where one chooses a gene from a pulldown: Should the string that appears when one has selected a gene include the "PomBase:" prefix? At present, it doesn't; it just shows the systematic ID with no prefix. If we add a new gene-as-extension, or edit an existing one, as a string, should we paste in the "PomBase:" prefix?

- It's still a couple more clicks per edit than the old text-box-only interface, which isn't ideal, but is better than not having it at all. It will save some mousing &  clicking, especially for FYPO protein binding extensions. That's my whole aim with this request - make it a bit less mouse/click intensive.

- On a related note, how nasty would it be to have the "edit as string" link as another option beside the "edit" button in the duplicate/edit popup? 'Twould save a click ....

- Can support for pipe-separated extensions be restored? I envision it behaving as in the old version - they'd get separated into independent lines of annotation, each with one of the extensions entered. That would make for some nice click savings ...

**Comment by kimrutherford** [comment]
> It appears to be working for single extensions, simple or compound.

Great, thanks for testing.

> Should the string that appears when one has selected a gene include the "PomBase:" prefix?

Good question.  I think the answer is that that we don't need it unless you're likely to need to load genes from another organism (cerevisiae?) at some point.  But I'll have a think and get back to you.

> On a related note, how nasty would it be to have the "edit as string" link ...

I've made a separate issue for that: #1072

> Can support for pipe-separated extensions be restored?

It could be supported.  If you manually added one with a pipe it would display OK but for now the GUI extension editor would not work.  That can be fixed but will take longer.  Would that be OK?

**Comment by mah11** [comment]
I think it would be fine, since the string-edit option will be admin-only indefinitely .... and I may be the only admin who uses it much anyway ;)

Fixing the GUI to work alongside would be a nice touch but not critical in the short or even medium term.

**Comment by mah11** [comment]
We just had a quick chat about prefixes:

Certainly if anyone wanted to use Canto with genes from more than one organism, AND use this text extension addition option, they'd need to inculde prefixes. For PomBase specifically, and any other single-organism Canto instance, we decided to let you decide ;) Just tell me whether to include the prefix or not, and I'll carry on happily.

**Comment by mah11** [comment]
I'll also split the pipe-separation thing off into its own ticket, so we can close this sooner.

**Comment by mah11** [comment]
answer to outstanding question: omit the prefix for now, and until further notice (because we may eventually need other species genes for complementation annotations, but that's a ways off yet)
