### ISSUE TITLE
Fix exporting of annotations with independent extensions

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1066]
An annotation with extension "exists_during(GO:0123456),requires_feature(Pfam:PF00564)|exists_during(GO:0051329)"

should be written as two separate annotations, one with extension "exists_during(GO:0123456),requires_feature(Pfam:PF00564)" and the other with "exists_during(GO:0051329)".

(I'm making this ticket so I can close it and have a record on GitHub)

**Comment by ValWood** [comment]
I don't see *any* annotations using  requires_feature(Pfam:PF00564)| in the gaf?
Isn't this one deprecated?

**Comment by kimrutherford** [comment]
> I don't see any annotations using requires_feature(Pfam:PF00564)| in the gaf?

Sorry, that was a dodgy made up example from the Canto test data.  It's not in the main Canto.
