### ISSUE TITLE
duplicate annotation allows extra extension (cardinality problem)

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1069]
If I use the "duplicate" feature on an annotation that has any extensions, the extension editing interface offers me all of the available extension options, even the type(s) that are already added. For example, if a FYPO annotation has a penetrance extension, the duplicate interface happily lets me add another one, and displays the result as a compound extension.

Same for FYPO & "assayed protein", or for a GO CC annotation that has an "exists_during" extension. I haven't tried other annotation-extension combinations so far; let me know if it'll help to do so.

I've left some examples visible in a new test session, http://curation.pombase.org/test/curs/3283a4fb464133f1

**Comment by kimrutherford** [comment]
Whoops, thanks for catching that.  I forgot that when implementing it.

**Comment by kimrutherford** [comment]
Updating the code properly has fixed now too, I think.

**Comment by mah11** [comment]
yep, looks fixed
