### ISSUE TITLE
Add a shortcut "Edit as string" button

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1072]
Add a "As string ..." button beside the "Edit..." or "Add..." extension button in the edit dialog.

**Comment by ValWood** [comment]
@kimrutherford  don't  know what this one means, is it still relevant?

**Comment by ValWood** [comment]
I'm putting this as a low priority enhancement as I'm not sure what it is. If it seems more relevant please remove the low priority label and it will come back onto my radar.

**Comment by kimrutherford** [comment]
Midori suggested a shortcut button to get to the text box for manually editing extensions quickly.  I had a quick look and it wasn't quite as simple as adding the button and wiring it up, so I haven't done it.

**Comment by mah11** [comment]
Yes. It is still relevant. It's not urgent, and certainly doesn't have to be done for the initial extension interface release, but for me it will make a significant efficiency improvement so I'd like it to remain on the radar. Medium priority seems about right.

**Comment by kimrutherford** [comment]
This is fixed in the test Canto.  Please let me know if it was what you were thinking of and let me know if any problems.

**Comment by mah11** [comment]
That's just what I had in mind. Thanks!
