### ISSUE TITLE
Text  for prompting in text box when ontologies  can be used with extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1073]
At present we have, for example

assayed transcript [box]
This text requires that the user add a SO term ID or description, but it isn't super-obvious.

We would like to do one of two things, whichever is easiest
1. Preferred
   Text outside the box:

Start typing a description (e.g. centromere outer repeat transcript, snRNA U6)

Where the things in brackets are examples for use with the specific extension type/ontology combination.

or  2. Text suggestion in the box
(e.g. centromere outer repeat transcript, snRNA U6)

with the 'generic' part
Start typing a description
outside the box.

So, which would you prefer, and where should we put the configuration text?

**Comment by ValWood** [comment]
This might already be done? or have changed, it didn't have any labels so it might be in another ticket

**Comment by kimrutherford** [comment]
> This might already be done?

I hadn't noticed this ticket so I haven't made any of the changes.

**Comment by ValWood** [comment]
It might be superseded by other stuff....

**Comment by kimrutherford** [comment]
> It might be superseded by other stuff....

I think it still needs changing.  This is not at all obvious:

![screenshot 2016-03-14 09 49 40](https://cloud.githubusercontent.com/assets/90474/13731287/210e91c6-e9ca-11e5-84ef-9c1bd4c22d8f.png)

**Comment by kimrutherford** [comment]
> Start typing a description (e.g. centromere outer repeat transcript, snRNA U6)

Maybe we need to put a longer help text in the config file?  Currently we just have "assayed transcript".  That kind of works as a title when there is a list of extension types to choose from but perhaps we need more detail in the dialog box?

So instead of "assayed transcript" in the dialog, we could have something like "Specify as assayed transcript - type a description or select a gene from the session:"

Like this:
![screenshot 2016-03-14 10 32 00](https://cloud.githubusercontent.com/assets/90474/13731522/0788f236-e9d0-11e5-92ac-23b813298c2f.png)

That would mean adding an extra column to the config file.  We could make it optional in the case when the current text is OK.  Like "assayed protein", where the range is ProteinID.

**Comment by ValWood** [comment]
OK, that sounds reasonable.
So the action is

Add an additional column to the config to specify more detailed text to accompany the dialogue box.
In the first instance, this can be the same as the prompt (or it can be optional). We can then add/change these on a case by case basis to  provide improved help for the user.

I think we can release without this change.

**Comment by kimrutherford** [comment]
> I think we can release without this change.

I think I'll add the extra (empty) column to the config files and change the parser before release just to reduce the chances of breaking things later.

**Comment by kimrutherford** [comment]
> I think I'll add the extra (empty) column to the config files

Done.

**Comment by mah11** [comment]
Is there still a task for me here, and if so, can someone please clarify what it is?

**Comment by ValWood** [comment]
Maybe we have imagined a problem where there isn't one.

So currently the text in the config file is  (i.e assayed transcript) is used for both
i) the list for AE selection and
ii) The text prompt above the text box.

We now have the option to put more informative text  above the text box. Kim has created a column. 
 We can either choose to  keep as is, or we can change to more informative text describing what to type.

Lets see how people go with this.  We can add as required.

The only one I know so far is the one which spawned the ticket:

Start typing a description (e.g. centromere outer repeat transcript, snRNA U6).

**Comment by ValWood** [comment]
I'll label config file updates as "documentation".

We need to add the one we know about and test.  
Can add others as and when required.

**Comment by ValWood** [comment]
Can we close this one?

**Comment by mah11** [comment]
I have no need to keep it open.
