### ISSUE TITLE
Add support for pipe-separated extensions to admin text-based entry

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1074]
M: Can support for pipe-separated extensions be restored? I envision it behaving as in the old version - they'd get separated into independent lines of annotation, each with one of the extensions entered. That would make for some nice click savings ...

K: It could be supported. If you manually added one with a pipe it would display OK but for now the GUI extension editor would not work. That can be fixed but will take longer. Would that be OK?

M: 

I think it would be fine, since the string-edit option will be admin-only indefinitely .... and I may be the only admin who uses it much anyway ;)

Fixing the GUI to work alongside would be a nice touch but not critical in the short or even medium term.

Transferred from #1063

**Comment by kimrutherford** [comment]
Done, but I'm still testing.

**Comment by kimrutherford** [comment]
I think this is working.  Could you have a try in test?

**Comment by mah11** [comment]
Looks pretty good. The only thing I've noticed is that if I put an ontology ID in a string, the display keeps the ID instead of swapping for the term name (e.g. the string "happens_during GO:0000087 | happens_during GO:0000085" shows instead of "happens_during  mitotic M phase | happens_during mitotic G2 phase"). I can live with that, and it's not just admin-only, I'm the admin most likely to use it at all. So while it might be nice to get the display to update for the convenience of anyone else who might come along and look at the session, it's far from urgent.

**Comment by kimrutherford** [comment]
> the display keeps the ID instead of swapping for the term name

It was also not show the term name in existing annotations.  I've fixed that because it wasn't a big change.  So that next time I copy the main Canto over to test it should have the term names everywhere.

> I can live with that, and it's not just admin-only,

It's a bit fiddly to fix.  Currently it does no checking of what you type except for making sure the brackets match up.  So for the moment you can use anything as a relation name and put anything inside the brackets.
