### ISSUE TITLE
Do not show root ontology node in 'pulldown'

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1075]
This is general, we should not show the root ontology node in the extension pull down.

replaces 2. in
https://github.com/pombase/canto/issues/1060
where "FYPO_extesnion" appears in the pulldown

**Comment by mah11** [comment]
not exclusive to extensions, but fix is needed to release extension interface

**Comment by mah11** [comment]
will work via do_not_annotate subset, which M will add soon

**Comment by mah11** [comment]
note: this is mainly an issue for tiny little ontologies that fit into pulldowns, so we can deal (or not) with root nodes in big ontologies like GO etc. separately

**Comment by mah11** [comment]
Kim will also exclude roots from autocomplete suggestion system

**Comment by mah11** [comment]
we need this a lot sooner than we need to handle any other "do not annotate" subset stuff

**Comment by kimrutherford** [comment]
> Kim will also exclude roots from autocomplete suggestion system

After a bunch of changes, that's now done.  It's implemented internally by adding the root terms to a subset a bit like the subsets in an OBO file.  The code is now in place to exclude any subset of terms.  So with only a little bit of work we could exclude any do_not_annotate list.  We could exclude a list of terms you supply (like pombe-embl/supporting_files/GO_terms_excluded_from_pombase.txt) and/or the GO gocheck_do_not_manually_annotate subset.

Still need to add code to read and store subset definitions from OBO files.  Currently they are ignored.

The excluded terms are still in the database but won't appear in the autocomplete or the dropdown list.  You can still paste in the term ID into the auto complete box if you (curators) need to get to an excluded term.

**Comment by kimrutherford** [comment]
I'm reloading the ontologies in the test tool so these changes might be be visible for an hour or two.

**Comment by kimrutherford** [comment]
I'm now fixing the loading so the Canto will obey "subset: qc_do_not_annotate" in the OBO file (and any other subsets we'd like).

Then we should be able to change "FYPO_EXT:0000001|FYPO_EXT:0000002|FYPO_EXT:0000003|FYPO_EXT:0000004|%" to "FYPO_EXT:1000002|%" and "FYPO_EXT:0000001|FYPO_EXT:0000002|FYPO_EXT:0000003|FYPO_EXT:0000005" to "FYPO_EXT:1000001".

Should be done by Monday.  I'll change the config once the code is changed.

**Comment by kimrutherford** [comment]
Done.  So now (assuming no bugs) root terms and these subsets from the OBO files will be ignored by the autocomplete and the term drop-downs:
 
- qc_do_not_annotate
- gocheck_do_not_annotate
- gocheck_do_not_manually_annotate
- Grouping_terms (from PECO)

It's easy to change the config if those don't make sense.

I'll close this.  Please open new issues for bugs.

**Comment by mah11** [comment]
This looks like it's working fine for text autocompletes, although I still think it'll be good to have Antonia and Val test it too.

Note: for both annotations and extensions it does accept any typed/pasted ID from the applicable ontology, even for terms in the excluded subsets. But I think that's low-risk, because hardly anyone besides me pastes in IDs in the first place.
