### ISSUE TITLE
extend the allele name search to include 'wildcard'

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1076]
Currently you need to type the start of an allele name to match it when searching. It would be nice if you could search for the middle of an allele name. 

for example, typing in "NLS" does not find the cdc25 allele "cdc25-GFP-NLS", you need to type "cdc25-G..."

![screen shot 2016-02-11 at 16 59 40](https://cloud.githubusercontent.com/assets/12727506/12983387/f9bd9e3e-d0e0-11e5-89dd-38ac42ac4b69.png)

**Comment by kimrutherford** [comment]
The search now looks for sub-strings.
