### ISSUE TITLE
Information links for multi and single gene alleles

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1077]
Follow on from

We need to think about ways of stopping people doing multigene as single gene and single gene as multigene....
https://github.com/pombase/canto/issues/969

We don't want lots of text in the workflow and we can't think of a way to describe this simpli.

Multi gene and single gene need their own "information" links/pop ups to tell curators exactly what they are for

**Comment by mah11** [comment]
What is the task for me? I can't add links or popups ...

**Comment by ValWood** [comment]
Hmm, I think we just need some text to explain when single allele and multi allele are used.

(to make it clear that the 2 mutations at a single loci are single allele, changes in the same gene at different loci or one on a plasmid are multi etc.). Once we have suitable  text for  information icons, hand bakc to Kim.

**Comment by mah11** [comment]
So you just want me to draft some text? OK.

**Comment by mah11** [comment]
If you want short snippets suitable for mouseovers, I suggest:

single:
one or more mutations, or an expression change, in one copy of a gene at one locus

multiple: 
changes in sequence or expression at two or more loci


For something longer to link to, maybe the descriptions I've just put into the documentation:

single:
A single allele is a mutation, or set of mutations, in one copy of a gene at one locus (which may be the endogenous locus or a different locus, such as a plasmid or an insertion at a non-native position). You can also annotate under- or overexpression of the wild type allele as a single "mutation".

multiple:
Use the multi-allele phenotype option to annotate of a double mutant, triple mutant, or any strain in which more than one gene has its sequence or expression altered, including any case where you have more than one allele of the same gene present (e.g. one on the chromosome, and another on a plasmid).

**Comment by kimrutherford** [comment]
Thanks for the text Midori.

> Multi gene and single gene need their own "information" links/pop ups

Val, where should the links/pop ups go?

**Comment by ValWood** [comment]
Little ? icons at the end of the rows here?
Would that look odd?

![information_links](https://cloud.githubusercontent.com/assets/7359272/15926187/7cf4a00a-2e32-11e6-9881-314be808a3bd.jpg)

**Comment by ValWood** [comment]
Single allele phenotype (? = help text)

**Comment by kimrutherford** [comment]
I've changed it to look like this, but the help icons look a bit too permanent.  Any suggestions?  Should we have a icon/link to the right part of the docs for every annotation type?

![screenshot 2016-08-18 11 59 25](https://cloud.githubusercontent.com/assets/90474/17757489/42759fb6-653b-11e6-9621-d391e6df3587.png)

**Comment by kimrutherford** [comment]
> too permanent

That was meant to be "too prominent".

Mouse over the ? shows the longer text, clicking takes you do the new text that Midori has added to the docs.

**Comment by ValWood** [comment]
Just a bit lighter maybe?
I think links to all Docs here are a good idea....

**Comment by kimrutherford** [comment]
> Just a bit lighter maybe?

I've made it slightly lighter but perhaps not enough.

> I think links to all Docs here are a good idea....

OK, I'll do that.

**Comment by kimrutherford** [comment]
I've put a "?" icon that links to the docs beside each annotation type on the gene page.

For all except the phenotype links the text in the bubble is quite generic (see screenshot).  We could do with a one sentence blurb to put in each popup.

![screenshot 2016-08-23 16 48 58](https://cloud.githubusercontent.com/assets/90474/17880635/899511a0-6951-11e6-8e13-7a4ed167918d.png)

**Comment by kimrutherford** [comment]
If you'd like to edit the message yourselves they are in the config file, canto.yaml starting at this line:
https://github.com/pombase/canto/blob/master/canto.yaml#L1721

Change the text after "inline: "

I'm also happy to do that if you send me the text.

The "(Click to visit documentation)" is added automatically by the code.  We can change or remove it as needed.

**Comment by ValWood** [comment]
@mah11  could you?

**Comment by Antonialock** [comment]
Those icons look aggressively informational :-) 

Some suggestions...
Change the font color of the ? to dark, and keep a dark border around the circle, but no fill inside 
Align the icons vertically
Make the icons a bit smaller

**Comment by ValWood** [comment]
Yep maybe that would look better....

**Comment by kimrutherford** [comment]
> Change the font color of the ? to dark, and keep a dark border around the circle, but no fill inside 
> Make the icons a bit smaller

OK I'll try that in the test Canto.

> Align the icons vertically

I'm not so sure about that change.  How about I make the other two changes and then if we still need that?

**Comment by Antonialock** [comment]
Sure :-) just brainstorming

**Comment by ValWood** [comment]
yeah aligning them might be a bit odd, but smaller and less 'solid'

**Comment by kimrutherford** [comment]
> Change the font color of the ? to dark, and keep a dark border around the circle, but no fill inside 

I tried that but it didn't look so good that small.  In test I've changed it to a lightly background and a darker "?".  How does that look?

**Comment by kimrutherford** [comment]
I don't really like "?" as a help icon but I can't think of anything better.  Any suggestions?

![screenshot 2016-08-25 17 21 10](https://cloud.githubusercontent.com/assets/90474/17957759/5a9a63a8-6ae8-11e6-8a27-87a06bb45d5c.png)

**Comment by ValWood** [comment]
I think that looks fine. We can change if we have a better suggestion...

**Comment by kimrutherford** [comment]
I think this is done now?
