### ISSUE TITLE
workflow improvement in genotype creation/management

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1078]
Currently, when you add new genotype from this page, 
![add_a_genotype](https://cloud.githubusercontent.com/assets/7359272/13006176/d6d731e8-d17e-11e5-82a8-46e29784ffaa.jpg)

you go to this page:

![page2](https://cloud.githubusercontent.com/assets/7359272/13006200/17382328-d17f-11e5-9f06-be3ba8f0d1d3.jpg)

Which is a bit redundant. We decided to get rid of it
and go straight
![page3_rearrange](https://cloud.githubusercontent.com/assets/7359272/13006220/388e08f8-d17f-11e5-8f70-bde45ae7d7f9.jpg)
 to this page

With a few rearrangments

**Comment by ValWood** [comment]
The current "genotype management" page will be rearranged as follows

1. The genotypes used in this session will move to the left.
2. The  genotype details for the genotype you just added will appear on the right (with an add a phenotype to this genotype option)
3. There will be some way to make the current genotype disappear and make any exiting genotype the 'current genotype'
4. We will lose the "add, duplicate, delete" buttons from the rows to make it later. These will only be available for the "active" genotype

**Comment by ValWood** [comment]
Kim would like to discuss this with us to make sure we are sure. I think it would be helpful to go through it again once more too.

Kim's concerns, worried that genotype details page where you will see all annotations for a genotypes is a 'dead end' (I called it a leaf!). This might be OK. It will just be a place you go to sometimes. Maybe we will no longer want the 'actions' links  here.
If you do end up at genotype details, where should you go from here? 

Kim: Another option is to 'soop up' the  genotype management even further, so that  you can see the annotation on the genotype management page once you click on a genotype (but this would effectively reimplement the genotype details page on the genotype management page).

I guess the question is how useful is the genotype details page.

**Comment by ValWood** [comment]
Q What should it look like on the left when things are selected or not selected?
Q This will need to look less like a table and more l obvious what is available when you click on it
I. e how will it be obvious that they can add phenotypes to existing alleles

**Comment by kimrutherford** [comment]
> so that you can see the annotation on the genotype management page once you click on a genotype

I'm still not sure if that's a good idea or not.  Perhaps we could do the other changes first while we think about it.

I've been thinking about how the right hand side should look when you select a genotype.  It might be best to start with:

![screenshot 2016-04-07 14 41 31](https://cloud.githubusercontent.com/assets/90474/14339483/04055616-fcd3-11e5-859c-fbb6cf8d4960.png)

With a "Details ..." link underneath.  It might make sense to have "Edit ...", "Duplicate ..." and "Delete ..." too, but I'm not sure.

**Comment by ValWood** [comment]
OK do other changes first and we can re-discuss. I can't even remmber exactly what we decided.
We definitely need to do something here. I did this again yesterday when I really wanted to add lots of single alleles

![grrrr](https://cloud.githubusercontent.com/assets/7359272/14344073/5777e632-fc9d-11e5-901a-5503f99dd681.jpg)

(I call this the Gerry Smith error,  it's really easy to do this when you are adding lots of single mutant alleles)

**Comment by kimrutherford** [comment]
I've made a start on this issue.

Another question while we're at it.  Should we change the behaviour and look of the genotypes shown on the gene page?  In the "Genotypes for cdc11 in this session" section?

It looks a bit busy with all the links.  Maybe we should remove the link and make the row clickable.  Clicking could go to the genotype management page to show the details.

(I won't do this just yet, but I think it makes sense)

![screenshot 2016-04-25 17 38 34](https://cloud.githubusercontent.com/assets/90474/14774711/0d2719d0-0b0d-11e6-97f7-53a4c3dd57d8.png)

**Comment by ValWood** [comment]
I think it would be neater if we didn't need all the links. Should we discuss this one on our call?

Let me know if there are specific tickets you need earlier responses too.

**Comment by kimrutherford** [comment]
> I think it would be neater if we didn't need all the links. Should we discuss this one on our call?

No rush - they're easy to delete (or put back).

**Comment by kimrutherford** [comment]
I've made some of these changes and released them in the test Canto.  Could you have a look?

The list of genotypes on the genotype management page is now clickable.  And if you edit a genotype you get redirected back to the management page where the just-edited genotype will be selected.  (Hard to explain but pretty obvious if you try it)

Some things are missing or broken in the test tool: the list of genotypes on the gene page has lost its links and the duplicate... link for genotypes is missing.  I'm working on those problems.

**Comment by kimrutherford** [comment]
> the duplicate... link for genotypes is missing

Fixed.

**Comment by kimrutherford** [comment]
> the list of genotypes on the gene page has lost its links

I've added a "Details..." link beside each genotype in the list on the gene pages that takes you to the genotype management page.  We need to think about how that page should look in that case.  Currently it's a little bit jarring.  A bit of extra highlighting might help.

The background colour if you select a genotype is a bit horrible (picked at random).  See below.  Please suggest a better one.  If you have any ideas about making the genotypes in the list look more obviously clickable please let me know.  It's not good at the moment.

We also need to discuss how to display the annotations for the selected genotype.

![screenshot 2016-04-27 18 34 14](https://cloud.githubusercontent.com/assets/90474/14843749/df8cbebc-0ca6-11e6-995e-8f1554f24eb4.png)

**Comment by mah11** [comment]
Just had a quick look ...

The links appear but aren't working for me - any "duplicate" or "edit details" link gives me a "Not Found" error.

Color selection is not my strong suit, at least for webby things.

I agree that the genotypes don't look clickable at all, and that needs to change, but I'm not sure how. Maybe just make the text appear in hyperlink color (blue), even though clicking anywhere in the row works? (Is that even possible?)

I'm a little bit sad that it's now two clicks to duplicate a genotype (assuming we go with roughly this layout and behavior), but if everyone else likes the appearance with less link clutter I'll live with it.

**Comment by kimrutherford** [comment]
> The links appear but aren't working for me - any "duplicate" or "edit details" link gives me a "Not Found" error.

Whoops.  Fixed now.

> Maybe just make the text appear in hyperlink color (blue), even though clicking anywhere in the
> row works? (Is that even possible?)

Yep, no problem.  I'll try that.

**Comment by kimrutherford** [comment]
I've made the genotype description look like a link.

**Comment by kimrutherford** [comment]
Just tested on Internet Explorer 9 and it worked.  It's a but uglier though.

**Comment by Antonialock** [comment]
It doesn't really look like the two tables belong together, perhaps the tops of them should align?

I agree poo-brown isn't a great colour, maybe just go a shade darker than the normal background?

**Comment by ValWood** [comment]
suggestions:

1.
![1](https://cloud.githubusercontent.com/assets/7359272/14884624/0049f56a-0d3e-11e6-98f5-bf77867cef6f.jpg)
2.
![2](https://cloud.githubusercontent.com/assets/7359272/14884626/02424e8a-0d3e-11e6-87c5-ba80570f52dd.jpg)
3.
![3](https://cloud.githubusercontent.com/assets/7359272/14884634/087298d2-0d3e-11e6-98e1-4565388fa51b.jpg)

4.
![4](https://cloud.githubusercontent.com/assets/7359272/14884636/0cb1b266-0d3e-11e6-8924-3982848c9e4e.jpg)

**Comment by ValWood** [comment]
I think this works really well (much better), but, I think it would be even better if there was a visual connection between the  genotype details, and the active genotype in the list (it could be the background colour)

**Comment by kimrutherford** [comment]
> It doesn't really look like the two tables belong together, perhaps the tops of them should align?

Do you mean that the top of the "Genotypes used in this session" section should align with the top of the "Genotype details" section?

**Comment by Antonialock** [comment]
> Do you mean that the top of the "Genotypes used in this session" section should align with the top of the "Genotype details" section?

Yes :)

**Comment by kimrutherford** [comment]
> Yes :)

OK, that makes sense.  I'll change that tomorrow.

> it could be the background colour

I'll try that too, while we see if we can come up with a better idea.

**Comment by ValWood** [comment]
> I'm a little bit sad that it's now two clicks to duplicate a genotype (assuming we go with roughly this layout and behavior), but if everyone else likes the appearance with less link clutter I'll live with it.

Hopefully we can streamline a little more later  once we have got rid of the extra pages....

**Comment by ValWood** [comment]
I was just using test (for another reason, to look at a FYPO term), and I got really confused. If I do a single allele annotation now, I don't know how to add a phenotype?

I get plopped straight to the genome management page, but its really unclear what to do next?

v

**Comment by ValWood** [comment]
I cant actually find a way to add a phenotype at all, so it isn't super-obvious...

**Comment by kimrutherford** [comment]
> I cant actually find a way to add a phenotype at all, so it isn't super-obvious...

Whoops, that's a big oversight.  I forgot to put the "Add phenotype ..." link in.  I'll do that.

**Comment by kimrutherford** [comment]
The "Genotypes used in this session" section now aligns with the top of the "Genotype details" section.  Let me know what you think.

**Comment by kimrutherford** [comment]
> I cant actually find a way to add a phenotype at all, so it isn't super-obvious...

I've added the missing link.  After you make an annotation it sends you back to genotype management page.  But you currently can't see the annotation you just made.  We need to talk about that.

![screenshot 2016-04-30 18 14 50](https://cloud.githubusercontent.com/assets/90474/14934262/7aa86108-0eff-11e6-9381-212d433f19c3.png)

**Comment by kimrutherford** [comment]
As a test, I've changed the style of the genotype details section to match the select row in the genotype list.  It doesn't help:

![screenshot 2016-04-30 21 19 49](https://cloud.githubusercontent.com/assets/90474/14935084/63afebb4-0f19-11e6-93f0-8c06e077a1e1.png)

**Comment by ValWood** [comment]
1.
I think it would be better if the one you just added, with the actions was on the left,  and the list used in the session was on the right perhaps?

2.
Perhaps the colouring will only serve as a link if it does not have to 'compete' with the alternating buff/white colouring...
So a question, do we need the alternating buff colouring? or could all of the content except  for the 'active' genotype and the genotype details be white? Can we try that?

3.
The old wording was "Add a new phenotype for this genotype ..." should we keep that?

4. I think it would also be better if "add a new phenotype"  was the most prominent action, and the other 3  action were  to the right of the box

**Comment by ValWood** [comment]
I've added the missing link. After you make an annotation it sends you back to genotype management page. But you currently can't see the annotation you just made. We need to talk about that.

Yep!. Should we put this in a new ticket for discussion?

**Comment by mah11** [comment]
> 1 ... the actions was on the left, and the list used in the session was on the right perhaps?

Hmmm, I doubt it. I suspect the difference is small, but the fact that English goes left-to-right slightly favors having the list on the left - you look at the list, pick one, and then read on for its details. Could it just be that we're used to the list on the right from the current layout on live canto that's making you suggest otherwise?

> 2 ... do we need the alternating buff colouring?

Yes. It's good for

- tracking across a row to keep track of which details go with which genotype;
- consistency with the rest of the Canto interface - all the tables have it;
- consistency with the rest of the world - alternating white/color rows is commonly used for the row-disambiguation purpose. It may predate computers, and certainly predates the widespread use of computers smaller than conference rooms.

It doesn't have to be buff, of course. It can be whatever color we want (but should be the same throughout Canto).

> 3 [wording]

No preference.

> 4 I think it would also be better if "add a new phenotype" was the most prominent action,

I agree, but ...

> and the other 3 action were to the right of the box

I would have to see a mock-up of what you have in mind to tell whether it's a good way to accomplish the desired highlighting. I worry that it could just look messy, and wasn't "less messy" most of the motivation for doing any of this?

All that said, I'm starting to go off the notion of changing the existing behavior, but that's probably down to the teething problems with the appearance, or that I got used to the current thing and its idiosyncrasies. (Or it's just me and the anomalous way I work. That additional click to duplicate may drive me nuts.)

**Comment by ValWood** [comment]
OK scrub that.

Here are some small suggestions. I don't think it as so bad as it is  in test.
I think it would be better if
1. There was a stronger link between the active genotype and the entry in the table.
This could be done a bit more prettily by
i) making the contrast between the buff and the whit less strong. Would you object if the alternation was between white and the  current creamy/magnolia background? or isn't the contrast great enough?
Then the active colour could be a bit stronger? (the current buff colour)

ii) adding an additional visual clue, ( like the arrowhead used in submenus) to the end of the table
![sub1](https://cloud.githubusercontent.com/assets/7359272/14983171/79afb3ba-1133-11e6-9ae2-70ba5c1692bb.jpg)

2. Maybe  "genetyoe details" could say "active genotype details"

3. Should "add a genotype" say "add a new genotype" or "add another genotype"

4. The current text says
Click a description to view and edit genotype details
there needs to be a prompt for "or add a phenotype annotation" here, need wording

Less messy wasn't the major motivation, it was to remove  put you straight back to the genotype management page when you created a genotype. 


I don't understand the "additional click to duplicate" (for me its less clicking now?), so maybe you can demo on Thursday?

**Comment by ValWood** [comment]
I do think the 'duplicate' button is a bit misleading. But this is because I don't know if its clear that you would only duplicate if you wanted to  change the genotype slightly, not to add another phenotype to the same genotype. i.e it might not be clear to a novice how the duplicate option would be used.

**Comment by ValWood** [comment]
Note that it isn't possible to use the duplicate and edit an annotation yet, because annotations aren't appearing......

**Comment by mah11** [comment]
> I think it would be better if [t]here was a stronger link between the active genotype and the entry in the table.

Definitely; I just don't have great ideas how that might be done. The arrow thing might work.

> ... making the contrast between the buff and the white less strong ...

Lower contrast between rows would be fine, as long as it's the same everywhere in Canto.

> Maybe "genetype details" could say "active genotype details"

How about "selected genotype details"? Removes any danger of "active" being misunderstood.

> Should "add a genotype" say "add a new genotype" or "add another genotype"

Not convinced it needs any more words.

> Less messy wasn't the major motivation, it was to remove put you straight back to the genotype management page when you created a genotype.

That doesn't make sense: almost all the changes we've been discussing in this ticket are changes *to the genotype management page itself*, rather than changes to how the page is reached.

> I don't understand the "additional click to duplicate" 

From the live genotype management page, you can duplicate any genotype by clicking the "duplicate" link on the extreme right, outside the table border. In the new test version you have to click to select the genotype, and then click again on the "duplicate" link when it appears.

**Comment by mah11** [comment]
Re

> I do think the 'duplicate' button is a bit misleading.

and 

> Note that it isn't possible to use the duplicate and edit an annotation

I am talking about the links to duplicate genotypes, not annotations. That's what's on the genotype management page, both live and test versions.

**Comment by ValWood** [comment]
to me, the main motivation for these changes, was to get rid of this page, 

![main-motivation](https://cloud.githubusercontent.com/assets/7359272/14983887/bcb3dce6-1137-11e6-84d4-326854f2d152.jpg)

and plunk you straight back to genotype management showing the details, which we have done.

The rest is to  improve the presentation now the 'selected genotype' is visible. 
So this has a downside for you because of the extra click to select the genotype.  For me the removal of the extra page is a bigger win (I think before creating a genotype  was a bit confusing in the workflow, its much clearer now). 
It should also make it clearer for those people who  were stringing alleles together into a single genotype, because the 'finish' page makes it much clearer
It also looks a lot better (I think).

Also you will only need the extra click when you change genotype, so it might not be *so* many extra clicks? If it bothers you maybe we can add it to the admin option. Lets see what Antonia thinks. I think it solves bigger issues even if it isn't ideal yet....

**Comment by mah11** [comment]
> the main motivation for these changes, was to get rid of [the individual-genotype details] page, ... and plunk you straight back to genotype management showing the details

Returning to the genotype management page after adding a genotype doesn't require changing the genotype management page, though.

Also, to me the biggest problem isn't the existence of those pages, but that the only link back to the paper summary is small and out of the way in the breadcrumb trail. Removing the genotype details page is neutral to me, or would be if it didn't degrade my user experience of the genotype management page.

> I think before creating a genotype was a bit confusing in the workflow, its much clearer now

For me it is neither more nor less clear, but it is more clicking.

> It should also make it clearer for those people who were stringing alleles together into a single genotype, because the 'finish' page makes it much clearer

How does this affect that problem at all? The genotype addition steps work exactly the same way in test and live; we've requested no changes there. It's missing the "finish" button that causes the strung-together alleles (and I have no idea whatsoever how to make that less likely, since I've never done it myself). I.e. the problem happens *before* "finish, and therefore before you come back to the page you get after finishing, no matter what that destination page is.

> Also you will only need the extra click when you change genotype, so it might not be so many extra clicks?

It's one more click every time I want to duplicate a genotype. For some papers I've done that a lot.

**Comment by kimrutherford** [comment]
I'm not clear what to do next so I'm going to hold of on workflow changes until we've had a chat.

**Comment by ValWood** [comment]
I think the difference is that I’ve been using  create a new genotype  more frequently than edit an exiting one  and this part is now much clearer.
I know  that for people who have strung things together  it is too late, but  its clearer what has gone wrong because the genotypes are presented more clearly.

the difference:

LIVE
click  “add a genotype”

-finish intermediate page (its a bit unclear what to do next if you are only creating the genotype to use  with an exiting annotation)

- back to genotypes
find your genotype 


TEST
click  “add a genotype”
new allele is visible and ready to use


I also really like how this page is not so cluttered, its *much* more aesthetically pleasing.

Maybe  some quick links could be added back as an advanced mode option? (D | E at the end of the row)

My only complaint would be that loading the genotype details is a little slow, and the colour isn't optimal.

**Comment by ValWood** [comment]
I think the difference is that I’’ve been using  create a new genotype  more frequently than edit an exiting one  and this part is now much clearer.

LIVE
click  “add a genotype”

-finish intermediate page (its a bit unclear what to do next if you are only creating the genotype to use  with an exiting annotation)

- back to genotypes
find your geneotype


TEST
click  “add a genotype”
new allele is visible and ready to use


I know  that for people who have strung things together  it is too late, but  its clearer what has gone wrong because the genotypes are presented more clearly now.

I also really like how this page is not so cluttered, its *much* more aesthetically pleasing.

Maybe  some quick links could be added back as an advanced mode option? (D | E at the end of the row). Does anything else bother you?

**Comment by ValWood** [comment]
Also, the one you have just annotated is always the "current" one,  so you only need to click to change to another one...

**Comment by mah11** [comment]
> I think the difference is that I’’ve been using create a new genotype more frequently than edit an exiting one and this part is now much clearer.

That doesn't make sense: adding a genotype behaves exactly the same way in live and test, except where you end up AFTER you click "finish". There's also no difference in how you get TO "add a genotype".

**Comment by ValWood** [comment]
Its one less page now if you use "add a genotype"

**Comment by mah11** [comment]
I'm still not following. I'm talking only about the steps to define a genotype.

**Comment by Antonialock** [comment]
I'm not sure what you guys are on about

**Comment by mah11** [comment]
that's probably good for your mental health ;)

**Comment by ValWood** [comment]
I think part of these changes were implemented so that the Genotype detail box could sit alongside the genotypes used and get rid of the intermediate page. In order to do this Kim moved the edit options into the genotype details box, otherwise the page would be very cluttered.

I guess I am biased towards the new version, because I have never really liked the way the  "genotypes used in this session" table looked with the links down the side. It made the table rows 3 lines deep so it took up a lot more space and it looked very cluttered. 

I guess we could change back to have the full links at the side.

**Comment by Antonialock** [comment]
I don't like the wording "details" bottom right here. If we keep it like this it should probably say soething like "add phenotype" (I know you can do more stuff but that is the most important action cue for new curators)
![screen shot 2016-05-05 at 10 34 37](https://cloud.githubusercontent.com/assets/12727506/15040482/171ae672-12ad-11e6-8e9d-ab91ef047132.png)

**Comment by ValWood** [comment]
It looks much neater, but you still have the deeper rows once you add long genotypes.
Maybe the links could come back  and the "genotype details" could go  a bit higher up?


![neat](https://cloud.githubusercontent.com/assets/7359272/15040544/8d95e874-12ad-11e6-9385-f67bf578ddb6.jpg)

**Comment by ValWood** [comment]
Hi Antonia, could you put this in a different ticket....then we can keep this one to this page.

> I don't like the wording "details" bottom right here.

**Comment by ValWood** [comment]
I have read through this thread and I don't think that there is any useful  so I'll close it and we'll open new ones for the decisions.
