### ISSUE TITLE
slowness in session assigning

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1082]
I'm not sure if it is my imagination, but it seems to be taking much  longer to 
i) assign a user to a session,
ii) send a session link to a curator
(each step is taking me 20-30 secs)

**Comment by kimrutherford** [comment]
> each step is taking me 20-30 secs

Even reloading the page is slow for me (although more like 5-10 seconds).  It be more or less instant.  I'll look into it.

**Comment by kimrutherford** [comment]
Should be faster now.  Please let me know if it's still a problem.

**Comment by ValWood** [comment]
Much!
