### ISSUE TITLE
lucene search weighting for main DNA binding TF term

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1083]
Is there any way we can 'weight' this term,
so that if somebody types "transcription factor' this comes near to the top of the list, as its the most  likely term, but I never see it. I always need to look it up on a TF gene page.

GO:0000982 transcription factor activity, RNA polymerase II core promoter proximal region sequence-specific binding

**Comment by kimrutherford** [comment]
I think that's possible, but it's going to be a bit of a hack. I'll try it in the test Canto.

**Comment by ValWood** [comment]
I'll also look into whther this can be improved with synonyms. "Transcription factor" as a search returns about 500 GO terms, need to be able to locate the main ones easily

**Comment by kimrutherford** [comment]
> I think that's possible, but it's going to be a bit of a hack.

I've added a bit of a hack that reads term weights from the configuration file.  GO:0000982 now has twice the default weight so should appear further up the search list.  Each change of the weights needs a re-load the ontologies to change the index.  It could be a bit of trail and error to get the right weight.

**Comment by kimrutherford** [comment]
There's good news and bad news.

Good news: "transcription factor activity, RNA polymerase II core promoter proximal region sequence-specific binding" is now at the top of the list when you type "transcription factor" in the test Canto.

Bad news: it's also top of the list if you type "RNA", "core" or "proximal" :-(

Maybe a better strategy would be allow extra artificial synonyms to be configured.  If we could arrange for that term to have "transcription factor" as a synonym then it would pop to the top without extra work.  We'd probably want to hide these artificial synonyms from the user.  I'm not sure how to implement that so I'll have a think.

**Comment by ValWood** [comment]
I think that might be OK.... (certainly for core and proximal as they aren't used much if at all in any other contexts).

If its annoying we can remove it.

**Comment by ValWood** [comment]
Actually this should have broad synonym "transcription factor" I'll ask GO to do that.....

**Comment by ValWood** [comment]
Closing, GO added synonym.
