### ISSUE TITLE
GO "during" extensions should ignore don't-annotate for phases

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1084]
The extension interface no longer suggests cell cycle phases such as "mitotic S phase" for the "during phase or process" options.

I infer that this is because of the subset-related cleverness added for #1075. Most of that is still cool and desirable, but we do need to be able to create GO extensions of the  "exists_during S phase" or "happens_during mitotic M phase" ilk.

So the fix would be for the extension interface to ignore the gocheck_do_not_annotate flag for the cell cycle phase terms. Can that be done just for extensions? The autocomplete for choosing a GO term to annotate to in the first place should still exclude anything in the any "do_not_annotate" subset (the list in #1075).

Should we put something in the extension config files for this?

(Note: curators can still create these extensions because typing/pasting an ID still accepts any valid ID, but community users will never think of that, and we don't want them to have to futz with IDs.)

**Comment by ValWood** [comment]
Yep just spotted this one.

I have been thinking recently that for 'during' extensions we should restrict to 'phases'. This will be more consistent (and correct).

I think I wanted to include processes  originally so you could say "during cytokinesis' but really during "mitotic telophase" or "mitotic M phase" would work better.

There are other examples where we might have used "during' a process, but we should  revisit these at some point and see if phases would be better (or, if we really meant 'involved in').

For the past year or so I have always used phases with during.

**Comment by mah11** [comment]
We did also want to allow "during response to X", mainly for things observed during some stress response or other.

That should be doable in the config files - e.g. GO:0022403|GO:0033554 would allow anything under "cell cycle phase" or "cellular response to stress" but not any other process branches. Or maybe we'd need GO:0051716 "cellular response to stimulus" instead of just response to stress.

**Comment by ValWood** [comment]
Yes lets configure this way, just to allow these 2 branches. I forgot about the stress  stuff.

**Comment by mah11** [comment]
I suppose we should do the same for all of the "*during (GO:nnn)" extensions. I'll update the config files.

**Comment by ValWood** [comment]
Thanks!. I think this makes much sense.

**Comment by kimrutherford** [comment]
> I'll update the config files.

I had a bit of trouble following the discussion.  Does that mean we can still pay attention to the gocheck_do_not_annotate subset for extensions?  Or is that still a problem?

**Comment by mah11** [comment]
Sorry, extensions will still have to ignore the gocheck_do_not_annotate subset flag so phase terms can be offered. The config file change addresses a different aspect of the whole GO-BP-terms-in-extensions scary thing.

**Comment by kimrutherford** [comment]
> Sorry, extensions will still have to ignore the gocheck_do_not_annotate subset flag

Drat.  :-)

I'll work on that.

**Comment by kimrutherford** [comment]
Sorry for the delay.  I think this is done now.  I've tested using "mitotic S phase" in an extension.

Could you give it a try?

**Comment by ValWood** [comment]
Was going to test but Canto (test version, did not check live) appears to be hanging when you  click on the ontology link.

**Comment by ValWood** [comment]
only affecting test

**Comment by kimrutherford** [comment]
Whoops, the changes to allow ignored subsets for extensions seems to have stuffed up the usual ontology lookup.  I'll fix it.

**Comment by kimrutherford** [comment]
> Whoops, the changes to allow ignored subsets for extensions seems to have stuffed up the usual ontology lookup.

Fixed now.

**Comment by ValWood** [comment]
This is all working very nicely.
1. A  tiny, tiny thing,when you complete the annotation after drill down, you need to get rid of the original  selection box. It works and its fine so not urgent but its a tad annoying.

2. Another tiny thing.
If there is only a single extension option you see this text.

You have annotated cdc2 to cytosol (GO:0005829). Can you extend this annotation by providing additional details based on the experiments in this paper? These extension types are allowed for GO:0005829:
observed in this location during (cell cycle phase or process) ...
You can use more than one of these types in one extension (this creates a "compound" annotation extension and implies that the extensions occur together).

which is a bit confusing. If there is only a single option maybe it could just be:


You have annotated cdc2 to cytosol (GO:0005829). Can you extend this annotation by providing additional details based on the experiments in this paper? *This* extension type* is allowed for GO:0005829:

observed in this location during (cell cycle phase or process) ...


Neither of these needs to happen for release ....

**Comment by kimrutherford** [comment]
> Neither of these needs to happen for release ....

Could you make separate issues for these?  I think we can close this one after that.

**Comment by ValWood** [comment]
OK 2 new tickets opened
