### ISSUE TITLE
added during and removed during for modification

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1086]
At the moment, I see biological processes, but not phases, so it seems that this is everything *except* the phase branch, I think it should only be the phase branch (I think its better if we encourage people to used phases, rather than processes for 'during')

**Comment by mah11** [comment]
basically the same problem as in #1084

and we've allowed processes for the sake of things in the stress response branch (so maybe put something more specific in the config files? e.g. GO:0022403|GO:0033554)

**Comment by ValWood** [comment]
duplicate
https://github.com/pombase/canto/issues/1084
