### ISSUE TITLE
proportion of proteins with modification (change decimal value to percent)

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1087]
What do we expect people to supply? Decimal value sounds odd.

Should the prompt say
percentage of proteins with modification?

**Comment by ValWood** [comment]
ends up as
occupancy 45
I'm not sure what that means

**Comment by mah11** [comment]
right now it's configured to expect a decimal value, e.g. 0.45

I suspect it would be easy enough for Kim to change it to accept a percent, and for us to edit the config file accordingly.

**Comment by ValWood** [comment]
What would we prefer. I just thought it seemed odd to enter a decimal...It might just be me?

**Comment by mah11** [comment]
I don't have a strong preference.

Advantage of decimal: nobody has to change anything.

Advantage of percent: consistent with penetrance in FYPO extensions.

Somebody toss a coin.

**Comment by ValWood** [comment]
let's go percentage, more consistent

**Comment by mah11** [comment]
OK. I guess Kim should also remove the little up/down widget that increments integers.

**Comment by kimrutherford** [comment]
Currently it is configured as:

    MOD:00000       is_a    occupancy       Number  proportion of proteins with modification (decimal value)        0,1     user

with "Number" as the range type.  I'll try changing that column to "%" and see if it looks as you'd like.  It should be visible in the morning.

**Comment by kimrutherford** [comment]
I've made the change and I'm updating Canto.

Do you have existing annotation the uses decimal values?  If so, there will be percentages and decimal values stored in Canto and Chado.  So we won't know if 0.5 is 0.5% or a decimal value meaning 50%.

**Comment by mah11** [comment]
Actually, this hasn't been used at all yet, so we can do whatever we like. (A. Carpy requested it for some of the data in one of the bulk files, but then decided against including it after we'd adjsuted everything to accommodate it. So it's an option that exists in case anyone does want to use it someday.)

That reminds me, I should update the documentation on the web. Not tonight!

**Comment by kimrutherford** [comment]
> Actually, this hasn't been used at all yet, so we can do whatever we like.

OK, that's perfect.  Let's see how it looks in action and then tweak any bad wording.

**Comment by kimrutherford** [comment]
The configuration change for modifications is now live.  Could you have a look?

**Comment by mah11** [comment]
looks good!

**Comment by kimrutherford** [comment]
Great.  I'll close this.  Please open new issues for problems or tweaks.
