### ISSUE TITLE
remove out-of-date stuff from "curation finished" list

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1088]
On the "Curation finished" page, where we ask for any data they couldn't capture, the list needs updating. Right now it's got:

----
Examples include:

*substrates of gene products (e.g. protein substrates of kinases or protein transporters)
*"targets" of localization dependencies (e.g. gene A localizes gene B)
*cell cycle phases when a process occurs (during)
*specific residues modified in annotated protein modifications (e.g. phosphorylated on residue S45)

protein domain data or other protein sequence features
missing gene names (synonyms)
transcriptional regulation (of the WT allele - transcriptional changes due to mutations can be captured in the tool)
complementation data (whether the pombe gene complements a homologue in a different organism or vice versa; complementation may be full, partial or absent)
gene product name updates
human or budding yeast orthologs

----

To do:

Remove the first 4 entries (marked with * above), because they've been superseded by extensions. 

For the "transcriptional regulation" entry, change the wording to "transcriptional regulation (of the wild-type allele - transcriptional changes due to mutations can be captured in Canto)".

**Comment by kimrutherford** [comment]
I've changed the text.  If you need to do any tweaking, the text is buried in the config file:
  https://github.com/pombase/canto/blob/branch/annex-gui/canto.yaml#L1852

**Comment by mah11** [comment]
That looks good (plus, I fixed an old typo that I just spotted). When will it go into the test and pombe Canto instances?

**Comment by kimrutherford** [comment]
It's release in the test Canto.  Should I hold off on the main one since the extensions changes are live yet?

**Comment by mah11** [comment]
Yes - test will do for now (it'll let me get an updated screenshot for the docs). Then the new stuff can all gon into live pombe at once.
