### ISSUE TITLE
canto access message

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1090]
I get  this:
but I dont seem to get it all of the time....
However this was trying to access the help docs

![canto docs](https://cloud.githubusercontent.com/assets/7359272/13465635/803e34c0-e08e-11e5-9d26-8e29a8982754.jpg)

**Comment by ValWood** [comment]
its a bit scary...

**Comment by kimrutherford** [comment]
What was the URL and which browser are you using?

**Comment by ValWood** [comment]
chrome
https://curation.pombase.org/pombe/docs/index/
(although I am not being asked today?)

**Comment by kimrutherford** [comment]
I've tried various browsers and I can't reproduce this.

Perhaps you were using this very old URL somehow?:
  https://oliver0.sysbiol.cam.ac.uk/pombe/docs/index/

I'll make that to redirect to the https://curation.pombase.org/...

**Comment by ValWood** [comment]
I was using my bookmarked link. so I was accessing the demo from here.

https://curation.pombase.org/

I think once you have OK'd it it works for subsequent visits so I don't see the message now. I do see it periodically when I access canto though.....

**Comment by kimrutherford** [comment]
Could you make a note of the exact URL next time it happens?  Unfortunately your screenshot doesn't include it.

**Comment by ValWood** [comment]
will do but I'm sure it was this link:
https://curation.pombase.org/pombe/docs/index/

**Comment by tuli** [comment]
The link with the security problems was https://oliver0.sysbiol.cam.ac.uk/pombe/docs/index/ 

https://curation.pombase.org/pombe/docs/index/ is the same document and works fine. 

@ValWood I'll use the latter one in the CC doc.

**Comment by ValWood** [comment]
Yes sorry, I think I just gave you the wrong URL, 
that is the correct one

**Comment by tuli** [comment]
Great. Thanks. It's a much better looking URL. 

I'll let you close this ticket since I just barged in!

**Comment by ValWood** [comment]
We love people barging in !

**Comment by tuli** [comment]
Snort...
