### ISSUE TITLE
advanced mode not "sticky"

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1093]
I tried to put a session into advanced mode, and found that I had to redo it every time I changed genes — the session didn't just stay in advanced mode.

Seen in live pombe session 7b4c9e930c511158 ~16:45 GMT today. I think I may have also noticed the same thing in test canto the other day, but didn't save details.

**Comment by kimrutherford** [comment]
Fixed!  Although (embarrassingly) it was a case of not knowing how it could possibly have ever worked.

**Comment by mah11** [comment]
That's weird, because I could've sworn it worked at some point in the past. Happy it's working now (and I did check) anyway!

**Comment by kimrutherford** [comment]
Yep, I was sure it was working.  I must have broken it and not noticed.  Glad it's back.
