### ISSUE TITLE
Get rid of original "pop-up" box after accepting ontology term in annotation extension

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1095]
When you drill down to an ontology term, and accept one, you still have the original  pop-up box to dismiss, even though there is no other action required.
Maybe that's intentional  but it would be nice if you didn't need to explicitly dismiss this one (or some other solution)

**Comment by kimrutherford** [comment]
> Maybe that's intentional

Nope.  :-)

> it would be nice if you didn't need to explicitly dismiss this one

I agree, it's annoying.  It's something I meant to get back to.
