### ISSUE TITLE
extensions made before interface upgrade invisible

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1100]
This is related to the existing problem I think.
In the tool I can see a comma for some annotations 
The comma is the separator in the edit view

**Comment by ValWood** [comment]
![edit](https://cloud.githubusercontent.com/assets/7359272/13810809/b8744f74-eb69-11e5-9989-58bac6e393e9.jpg)

**Comment by ValWood** [comment]
![possible bug](https://cloud.githubusercontent.com/assets/7359272/13810818/cfe4a9d8-eb69-11e5-9f52-545f63917324.jpg)

**Comment by ValWood** [comment]
This is what you see if you try to edit
![untitled](https://cloud.githubusercontent.com/assets/7359272/13810847/f59e2bfe-eb69-11e5-8331-2656e4e7b356.jpg)

It might be because there were existing annotations of this type with extensions in this session?

**Comment by ValWood** [comment]
If it is otherwise working don't worry about this tonight....We don't need to put it back on line for CC yet, and I think we can probably use now (although I didn't check yet)

**Comment by kimrutherford** [comment]
> If it is otherwise working don't worry about this tonight

We're flying to Australia tomorrow so it may be a couple of days before I can look at this.

**Comment by ValWood** [comment]
Oh actually, its worse.
I think that what has happened is that any extensions are not visible on in progress sessions.
I see a comma, because that is present if there were 2 extensions. If  there   was only a single annotation extension I see nothing. 

If only in progress sessions are affected, we could just ignore these sessions for now and  concentrate on new ones. I haven't properly looked at completed sessions.

**Comment by mah11** [comment]
Extensions made the old way don't seem to be visible at all. Completed sessions are also affected - for example, compare "new" and "existing" tables in https://curation.pombase.org/pombe/curs/c7ee4622fd63b2da/ro/

**Comment by ValWood** [comment]
I wonder if we can do anything else today (I can). If we mess with sessions it might be harder for Kim to sort out?

**Comment by kimrutherford** [comment]
Has anyone made any new annotations that they want to keep?  If the upgrade went wrong I might need to go back to the back and then try again.

**Comment by ValWood** [comment]
I did some tweaks before I realised there was a problem, so nothing I 
can't redo.
I stopped using Canto at this point so OK for me if you need to go back.



On 16/03/2016 18:33, Kim Rutherford wrote:
>
> Has anyone made any new annotations that they want to keep? If the 
> upgrade went wrong I might need to go back to the back and then try again.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/pombase/canto/issues/1100#issuecomment-197475923>
>


-- 
Cambridge University
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood

**Comment by Antonialock** [comment]
I can redo the little I've done

On Wed, Mar 16, 2016 at 6:35 PM, Val Wood <notifications@github.com> wrote:

> I did some tweaks before I realised there was a problem, so nothing I
> can't redo.
> I stopped using Canto at this point so OK for me if you need to go back.
>
>
>
> On 16/03/2016 18:33, Kim Rutherford wrote:
> >
> > Has anyone made any new annotations that they want to keep? If the
> > upgrade went wrong I might need to go back to the back and then try
> again.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pombase/canto/issues/1100#issuecomment-197475923>
> >
>
>
> --
> Cambridge University
> PomBase http://www.pombase.org/
> Cambridge Systems Biology Centre
> http://www.sysbiol.cam.ac.uk/Investigators/val-wood
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pombase/canto/issues/1100#issuecomment-197477128>
>



-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by kimrutherford** [comment]
> I can redo the little I've done

OK, sorry about the hassle.  I probably won't get a chance to have a look until tomorrow.

**Comment by Antonialock** [comment]
no worries, not a hassle :-)

**Comment by ValWood** [comment]
no problem. Get to Australia and don't worry, we can do other stuff.

**Comment by mah11** [comment]
no problem for me either

**Comment by kimrutherford** [comment]
I think this is fixed now.  I've copied the main Canto database to the test Canto, then upgraded.  It all looks good.
