### ISSUE TITLE
Help button broken in Firefox

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1101]
In Firefox, clicking the "Help" button in the top right corner of a Canto page does nothing. It's working fine in Safari and Chrome (all Mac; haven't tried in Linux and have no windoze machines anyway).

I don't know if this is new with the annotation extension interface release, because it didn't occur to me to try it recently ...

**Comment by kimrutherford** [comment]
That's a bit embarrassing.  It's fixed now.  It wasn't working on IE either.
