### ISSUE TITLE
blank page for PMID:16179942 session

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1102]
The publication details page for PMID:16179942 looks normal, but when I try to follow the "Go to the curation session" link the page is completely empty - not even headers, borders, etc.

https://curation.pombase.org/pombe/curs/83c3ce6ba08ef0ba

Problem with Firefox or Safari, and if logged in or not. May be specific to this session, because lots of other session links are working as expected (see 'em if logged in; get the downtime message if not).

This may be a total coincidence, but I tried to look at the session because GOA's syntax checks report that an annotation extension from the paper fails validation. I can't see from the report why it failed, so I went to see if the session shed any light, and ...

**Comment by mah11** [comment]
problem also affects PMID:21518960 session f54393989e565d1a (frustrating because I know that one has a typo in an extension that I want to fix)

**Comment by mah11** [comment]
more with problems:
PMID:25733668 / d17a6f8397b4b058
PMID:24210919 / 1f991e4ad5694cb6

a few examples that are OK:
PMID:16407242 / b03ae5190e2fe612
PMID:20453833 / a309fa2c0e0a8d62
PMID:9718372 / 3d47d60b7e868097

**Comment by ValWood** [comment]
I'm pretty sure that the page for this session was available earlier today
PMID:9154838
but is blank now.

I think the disk full problems with oliver:0 maybe affecting Canto too?

**Comment by Antonialock** [comment]
we shouldn't be using the tool for real right? just checking...

**Comment by ValWood** [comment]
Not now no :)

**Comment by kimrutherford** [comment]
> problem also affects PMID:21518960 session f54393989e565d1a

I think things are OK now.

> I think the disk full problems with oliver:0 maybe affecting Canto too?

That could be it.  I've had a big clean out on oliver0 so we should be fine now.  I'll keep an eye on it though.
