### ISSUE TITLE
Handle multi-part extensions from upgrade

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1103]
The new extension interface doesn't handle extensions separated by "|".  We decided in #1013 to leave it for now.

Unfortunately the current database has lots of those extensions.  The upgrade script can successfully update and store them but the new extension code fails to handle them.

I think the best quick fix is to finish implementing #1074 and allow the pipe-separated extensions to be edited in the old way.

The code needs to change to handle the piped extensions in the DB first.

**Comment by ValWood** [comment]
Sounds good. Again no problem for me to wait. I have plenty to do....

**Comment by kimrutherford** [comment]
> Again no problem for me to wait. I have plenty to do....

The current main Canto is fine to use for curation.  When I've fixed things I'll take a copy of the current database and update it match the new code.

**Comment by kimrutherford** [comment]
I've mostly fixed the interface.  Older annotation extensions that have multiple parts now show up as in the screenshots below.  If an extension has a pipe currently only the first part is editable in the fancy new interface.  Although you can delete individual relations with the "X" links.

The whole extension is now editable with the "Edit as string ..." link.

Please have a test when you get a chance.  One thing I noticed that still needs fixing is that the relations that you've already used aren't greyed-out.  I'll work on that.

![screenshot 2016-03-31 20 20 43](https://cloud.githubusercontent.com/assets/90474/14168316/1658a8e0-f77e-11e5-9e39-fd40fd5a5a2b.png)
![screenshot 2016-03-31 20 21 28](https://cloud.githubusercontent.com/assets/90474/14168332/2f30125e-f77e-11e5-949c-b2175197af87.png)

**Comment by ValWood** [comment]
I'll  test now....

**Comment by mah11** [comment]
I've done a bit of testing, and I don't have anything to add besides today's new tickets.

**Comment by kimrutherford** [comment]
>  One thing I noticed that still needs fixing is that the relations that you've already used aren't greyed-out.

That's somewhat fixed now, except that if you use the "Edit as string (admin only) ..." function, the display isn't updated.  I'll add a separate issue for that as it's not so urgent.
