### ISSUE TITLE
cardinality of extensions not observed

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1104]
I'm sure that, at one point, when you used an extension you could not 're use' it which prevented 
"comma separated" type extensions.
At present the relation is always available, so I can add as many as I like?

**Comment by ValWood** [comment]
This applies to long interface and 'edit' menu

**Comment by mah11** [comment]
KIm said in his last comment on #1103 that he knows that's a problem.

**Comment by ValWood** [comment]
Ah right!
