### ISSUE TITLE
some  relations are mutually exclusive

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1106]
I don't know if we have dealt with this. If we have I have forgotten.

I just spotted that sometimes  if you selected, for example "assayed protein" here
you would not want to be able to subsequently select "assayed complex" (that would be an independent annotation.

Do we have a way to flag this type of thing?

![mutually exclusive](https://cloud.githubusercontent.com/assets/7359272/14170516/1db0887c-f726-11e5-8350-d5e78b7efc6c.jpg)

Also maybe we should have some ordering of relations (I was going to say  alphabetically, but by type and frequency of use  would  probably be most sensible).

We could even do something like:
assayed protein OR assayed protein complex OR assayed protein isoform
penetrance
expressivity

Curators can discuss.
Not required for release anyway.

**Comment by mah11** [comment]
"assayed complex" and "assayed protein isoform" are admin-only, so this is only an issue if you think you'll forget that you'd only add one per annotation

**Comment by ValWood** [comment]
non issue then ;)

**Comment by ValWood** [comment]
Is "qualifier" also admin only?

**Comment by mah11** [comment]
yep
