### ISSUE TITLE
translate IDs into terms in views

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1107]
Longer term it would be nicer if  extensions were presented as terms rather than IDs

i.e
present_during (mitotic S phase)
instead of
present_during( GO:0000084)

**Comment by ValWood** [comment]
Actually I think that already happens, so its only the display of legacy terms....

**Comment by ValWood** [comment]
It seems a bit of a mixture. This is annotation which is already ion the gene pages.
Look at new vs existing:

![new vs existing](https://cloud.githubusercontent.com/assets/7359272/14172000/df3bc95a-f72d-11e5-8c7c-50e1757dc1ba.jpg)

**Comment by ValWood** [comment]
this might not be right. I was not looking in test.

but in test ri
![yikes](https://cloud.githubusercontent.com/assets/7359272/14172218/e4e8db1c-f72e-11e5-9a79-3681fed53638.jpg)
ght not for this session I get:

**Comment by ValWood** [comment]
test/curs/80821af8a094ff52/ro/

**Comment by mah11** [comment]
I have opened #1108 for the "couldn't read annotations" problem, because it appears to be a separate issue.

**Comment by mah11** [comment]
I don't think there's a bug anywhere, and it doesn't seem like a big problem.

I've looked at several sessions of varying ages and I think it's behaving consistently.

In both test and live, any extension that was added as a string is displayed in the "new annotations" section showing the string that was entered, minus parentheses. Once it's been through a load to become an "existing annotation", the extension is displayed with ontology IDs converted to the term names. Interestingly, systematic IDs are not converted to gene names.

On test, new extensions made with the spiffy interactive GUI have ontology term names displayed immediately, without having to go through a save/load cycle. String-based extensions still behave the old way, whether they come from sessions done before the new extension interface existed, or from the new "edit as string" option (I bet I'll be the only one directly affected by that ;) ).

**Comment by kimrutherford** [comment]
> so its only the display of legacy terms....

That's fixed now so that term namew and gene names are shown instead of term IDs and gene systematic identifiers.

> could not read annotation from server

The should be fixed now.

> Interestingly, systematic IDs are not converted to gene names.

That was a conscious decision because the made up names for the post-composed term (like "increased protein localization to non-growing cell tip [assayed_using] SPAC3C7.12") need to be unique.  It's easier to guarantee that if we use systematic gene identifiers. 

The new and existing extensions are formatted differently, which isn't nice.  I made a new issue about that: #1117
