### ISSUE TITLE
Some annotations unreadable in test canto

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1108]
I've only looked at a couple of sessions that have modification annotations, but both times I saw this:

"Error for post_translational_modification: couldn't read annotations from the server - please contact the curators"

example sessions:
5251feea6fc8d5fc (finished; I looked at read-only)
982304b134332abd (reactivated for testing)

As an aside to #1107 Val had a problem with GO BP in one session (but I haven't seen a session with any GO annotations failing to load so far). 80821af8a094ff52

All of these look fine in live Canto, so I don't know how severe the problem is.

**Comment by mah11** [comment]
I suspect it's not connected with extensions because for the modifications I couldn't see, live Canto shows extensions for the one in 982304b134332abd, but none in 5251feea6fc8d5fc.

**Comment by kimrutherford** [comment]
This problem has gone away now.  I didn't fix it on purpose so I think the other changes must have solved it.  Please re-open if you see it again.
