### ISSUE TITLE
error reassigning session

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1109]
I tried to assign this session to myself and got this error
https://curation.pombase.org/pombe/view/object/pub/PMID:24478943?model=track

Internal error
Caught exception in Canto::Controller::Tools->reassign_session "Can't locate object method "not_exported_curs" via package "Canto::TrackDB::Pub" at lib/Canto/Controller/Tools.pm line 791."
There has been an internal error. The problem has been logged and will be investigated.

**Comment by kimrutherford** [comment]
This is fixed but only in the test Canto.  If it's urgent I can put the fix in the main Canto.  Otherwise I'd prefer to wait until I upgrade the main one again to the new extension code.
