### ISSUE TITLE
Annotations are editable in review mode

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1112]
The edit, duplicate and delete links are shown in review mode:
![screenshot 2016-04-04 16 22 33](https://cloud.githubusercontent.com/assets/90474/14238150/7f68979a-fa81-11e5-8cb2-65ede659b9de.png)

https://curation.pombase.org/test/curs/da671cd7/ro/

**Comment by ValWood** [comment]
Ohh good catch!
