### ISSUE TITLE
Canto is no longer following has_part links

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1113]
See:
https://github.com/pombase/fypo/issues/2609#issuecomment-205241654

**Comment by mah11** [comment]
looks OK in test now, so presumably live pombe will get the fix along with the new shininess

**Comment by kimrutherford** [comment]
> looks OK in test now, so presumably live pombe will get the fix

I'm updating the main Canto now and I'll check suggestions for "elongated vegetative cell" once it's done.
