### ISSUE TITLE
subtle bug: cardinality grey-out only partly fixed (problem deleting if there are multiple extensions)

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1115]
In #1103 the bit that greys out relations already used was completely broken. Now it's behaving in a partially-fixed way:

 - Any time I add an extension, its relation is greyed out as expected.
 - If an annotation has one extension, and I delete it, its relation is restored to blue.

BUT ...
 - If an annotation has two or more extensions, and I delete one, ALL of the relations turn blue, including any that are still "in use". It will then let me add another extension of a type that should have cardinality 1.

Tested in session cfa0410c2c949ac3, where I've left one example in place.

**Comment by mah11** [comment]
Behavior has improved now, but there's still a bit of a problem, and if anything it's even subtler. When I initially reported, the bug showed with any two or more extension types, whereas now, it's acting fixed as long as none of the extensions are "qualifier" ones. E.g. if I have a happens_during and a phosphorylates, I can delete either one and it won't let me add more of the same type as the remaining extension.

But if I try to add a qualifier, I still see the grey-out/not-greyed-out bug. So if I add a qualifier (such as NOT) and one or more extensions, then if I delete any extension (not just the NOT), all types become available again.

Qualifiers are admin-only, so this bug is now not a reason to delay release.

**Comment by kimrutherford** [comment]
I think I've fixed this.  Could you have a try?

It took a bit of tracking down.  It seems that it it was a bug in one of the Javascript libraries used to do the interaction stuff in the display.  The problem went away when I upgraded to the latest version.

**Comment by mah11** [comment]
That does look fixed now :)

**Comment by kimrutherford** [comment]
Great.  I'm still a bit suspicious of the code as it's a bit curly.  Please watch out for more problem.
