### ISSUE TITLE
penetrance

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1116]
I have been thinking for a while it might be useful to be able to add penetrance ranges 

In this paper I have
+++, >30%; ++, 5-30%; +, 1-5%.

so I'd like to use
 >30%
and
 5-30%

Could this be possible (It would be really useful for those cases where you need to estimate from a graph too).
I'll put  it in this session, can fix if we decide to disallow.

**Comment by kimrutherford** [comment]
It's no problem to allow this in Canto.  It's just a small tweak.

**Comment by kimrutherford** [comment]
I've change it to allow percent ranges.  I hope that's what you needed.

This is only in the test Canto for now.

**Comment by kimrutherford** [comment]
The values are always stored in the Canto DB without the "%".
