### ISSUE TITLE
Update demo, kpas and uniprot Cantos

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1118]
Update to the latest Canto version after the extension stuff is done.

**Comment by kimrutherford** [comment]
The demo Canto is now on the latest code.

**Comment by kimrutherford** [comment]
Is the picchia / K.pastoris Canto still needed?

**Comment by ValWood** [comment]
I think  we should just keep it static for now. I'll speak to Steve about what should happen with it. We need an interested part to get it moving.....

**Comment by kimrutherford** [comment]
The uniprot server is upgraded now too.

**Comment by ValWood** [comment]
testing
https://curation.pombase.org/uniprot//tools/start/PMID:10900382

gave Internal error
Caught exception in Canto::Controller::Tools->start "Can't find Cvterm for annotation_status_datestamp"

**Comment by kimrutherford** [comment]
> Caught exception in Canto::Controller::Tools->start "Can't find Cvterm for annotation_status_datestamp"

Sorry about that.  Upgrading the database didn't go smoothly.  Fixed now.
