### ISSUE TITLE
editing via pop-ups: clicking outside active pop-up cancels

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1119]
When there's an editing pop-up open, I would expect that clicking outside it would do nothing. Instead ...

Add an annotation. Use the pop-up (duplicate, edit, or "quick add") to add an extension. Pick an extension type that uses an ontology term (happens_during in the forthcoming pic). Type, choose a term, etc.

There are now 3 pop-ups visible (annotation, extension type, extension payload), of which the topmost is not greyed out. BUT even though the background is greyed out, if you click anywhere in the grey region it acts as though you hit "cancel" in the topmost pop-up.

A similar thing happens At the extension type step, when there are only 2 pop-ups, it's easier to avoid accidentally clicking the grey because the active pop-up is a bigger target (and I didn't even notice with just the first big pop-up until I deliberately tested).

I'm not sure this quite reaches "bug" status, but it has annoyance potential.

**Comment by kimrutherford** [comment]
I've fixed this.  I needed to add an option to each place in the code where a dialog is opened.  I may have missed some.  Please let me know if you spot any dialogs that don't act correctly.
