### ISSUE TITLE
cant edit existing annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1121]
in this session
curs/6fa5a621a1388c10

cdc48	GO:0033047	regulation of mitotic sister chromatid segregation	IGI	PomBase:SPCC5E4.04

**Comment by ValWood** [comment]
or delete

Couldn't delete the annotation: error: could not find a 'Annotation' with arg: 7473 at lib/Canto/Curs/ServiceUtils.pm line 1150.


note to self.
one IMP will do and should be involved in separation (not regulation, not sure)

**Comment by Antonialock** [comment]
Val I think this bug is because the annotation is in the artemis files, not in the tool (so it can't be deleted using the tool)

**Comment by mah11** [comment]
So the actual bug isn't that you can't delete the annotation; it's that the "edit" and "delete" links appear for annotations you can't alter in Canto.

elderly but relevant open feature request: !143
