### ISSUE TITLE
doesn't find 'YES* condition

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1122]
Normally when I type YES into the conditions box 
id: PECO:0000137
name: YES
Is the top hit

But since the update it doesn't seem to show?
![screen shot 2016-04-07 at 16 15 53](https://cloud.githubusercontent.com/assets/12727506/14356328/510deeba-fcdc-11e5-8006-20c74a644632.png)

I can still search on PECO:0000137

**Comment by kimrutherford** [comment]
YES is now not shown because it is in the "Grouping_terms" subset in the OBO file.  Should the grouping terms be shown conditions?

**Comment by mah11** [comment]
I think grouping terms should not be shown for conditions, but there are a few terms in PECO that have are in the "Grouping_terms" subset and shouldn't be. I can fix that now.

**Comment by mah11** [comment]
the PECO subset correction has fixed the Canto suggestions
