### ISSUE TITLE
extensions often not presented

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1123]
Very frequently I am seeing no extension option (for example in all of this session I did not see 'penetrance' or 'expressivity' options.
curs/6fa5a621a1388c10

It's OK because I haven't needed them...

**Comment by mah11** [comment]
which terms? might help trace whether it's a config problem or something else

**Comment by ValWood** [comment]
It isn't config because its sporadic. Sometimes I see the extensions, sometimes I don't, for the same terms....Usually I din't see them which was OK for this session as I didn't need them.

**Comment by ValWood** [comment]
I think I am seeing it, ignore me
