### ISSUE TITLE
genotype selection pulldown doesn't show background

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1125]
If there are two or more genotypes with identical "allele(s) of interest" but different backgrounds, the options in the pulldown in the edit/duplicate/quick add popup look identical. So far, I've been able to remember which is which for long enough to get my annotations done, but that's not exactly a long-term-reliable approach.

Something ought to show in the pulldown to distinguish backgrounds, but I wonder if the curators should discuss how this should appear - in some cases including the entire background description would make for a rather unwieldy menu.

example in b6b9d534da028509 - rtf2-C141G with and without a hairy background

**Comment by kimrutherford** [comment]
Ah, good point. let me know how you'd like that displayed after you've has a discussion.

**Comment by ValWood** [comment]
RTS1-mat1-SspI::inv-RTS1 (RTS1 moved to cenII-distal side of mat1 and inverted)

RTS1-mat1........
10 char .....

**Comment by kimrutherford** [comment]
I've made this change but might need to rethink it.  For example in a309fa2c0e0a8d62 the backgrounds look like allele descriptions which is a confusing.  In that session there is a genotype "pol4Δ" with a background "wi10Δ uve1Δ mlh1Δ" so in the genotype selector/dropdown it looks like:
  pol4Δ wi10Δ uve1Δ ...

Any ideas?  Using bold or italics or some other font trick is possible but a bit yucky to implement.

**Comment by Antonialock** [comment]
can't you just stick the background in the bracket
say you have pol4-Δ with two different backgrounds: uve1Δ mlh1Δ OR wi10Δ
In the dropdown:
pol4Δ (uve1Δ mlh1Δ)
pol4Δ (wi10Δ)

**Comment by kimrutherford** [comment]
We also put the allele description in brackets but I think putting the background in brackets can't hurt.  I'll try it.

**Comment by mah11** [comment]
If parentheses or brackets don't work out (and genotypes already have both; expression is in square brackets), we can try a different separator, such as a dash or even (gasp) a prefix.

hand-waving examples
- pol4Δ — uve1Δ mlh1Δ
- pol4Δ bkg: uve1Δ mlh1Δ
- pol4Δ (bkg: uve1Δ ml...)

**Comment by kimrutherford** [comment]
> pol4Δ (bkg: uve1Δ ml...)

I've gone for this option for now.  Please try it and let me know if it needs tweaking.

**Comment by ValWood** [comment]
That works fine.
Is it possible that allele descriptions which differ only by background are grouped next to each other in the pull down. If you have a long list you might select the wrong one if you don't realise you need to select the one with the correct background....

New ticket?
