### ISSUE TITLE
 only 'deletion' allele suggestions are appearing.

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1126]
For instance in this session

curs/3602d714a22a5fa7/
cut9-665

**Comment by kimrutherford** [comment]
Is that a new allele?  Canto was pointing at the v58 Chado.  I've fixed that.

I just checked and cut9-665 is now suggested in that session.

**Comment by ValWood** [comment]
Ah quite possibly. I have been annotating a lot of cuts.
I checked a couple of others in that session, for other genes, which I had assumed existed and they were totally new, so I think that will resolve. Will open a new if I notice again.
v
