### ISSUE TITLE
gene names missing 

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1127]
Here, see new vs existing....

![gene column blank](https://cloud.githubusercontent.com/assets/7359272/14801154/22a6a942-0b3f-11e6-97f4-9a4270196166.jpg)

**Comment by kimrutherford** [comment]
Which session is this?  The genes are appearing in my test session.

**Comment by ValWood** [comment]
sorry its
curs/f07cd572b2d0adcf/ro/

**Comment by kimrutherford** [comment]
OK, thanks.  It seems to be the /ro/ that's causing the problem.
