### ISSUE TITLE
Handle genotype edits that cause a duplicate

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1130]
Currently if you try to add genotype that is identical to an existing one, the interface redirects you to the existing genotype.  But if you edit a genotype to then be identical to an existing one, no merging is done and you could end up with two identical genotypes in the session.

This is harder to fix than the new genotype case because both the existing and edited genotypes may have annotation.  That needs to be handled when merging the genotypes.

Note from #1620, we can cause a duplicate genotype by editing the genotype strain too.  We should handle that case.

See also #1129

**Comment by kimrutherford** [comment]
> This is harder to fix than the new genotype case because both the existing and edited
> genotypes may have annotation. That needs to be handled when merging the genotypes.

Would it be OK if Canto just prevented the duplicate genotype by returning an error if you try to edit a genotype to be the same as an existing one?  That would be quicker to implement and less likely to have bugs.

**Comment by ValWood** [comment]
I think so.

**Comment by kimrutherford** [comment]
> Would it be OK if Canto just prevented the duplicate genotype by returning an error if
> you try to edit a genotype to be the same as an existing one?

I've made that change.  I think it is the safe option for now.

Let me know if you spot any problems.

**Comment by kimrutherford** [comment]
I'll close this.  Let me know if there are problems.
