### ISSUE TITLE
revise wording for the "details" link

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1132]
Submitted by Antonia
![wording 2](https://cloud.githubusercontent.com/assets/7359272/15043125/ce340a3c-12c1-11e6-8156-130c3cb3bda9.png)

wording for "details"

**Comment by mah11** [comment]
refers to the table of genotypes on gene pages in test

**Comment by kimrutherford** [comment]
What should the wording change to?

**Comment by ValWood** [comment]
@Antonialock  what was your original suggestion here?

**Comment by Antonialock** [comment]
It probably refers to the 'gene details' in the "bread crumb trail" 

I want it to say 'cdc2' instead of 'gene details'

**Comment by ValWood** [comment]
I transferred this out  of one of the long tickets after the last discussion. I can't find it now though.... Its possible that I deleted it when I transferred it to this ticket because I think it was embedded in this thread
https://github.com/pombase/canto/issues/1078

and the image above the comment  was this one.

If this isn't what you meant, could you close and open a new ticket?

Thanks

Val

**Comment by Antonialock** [comment]
I know I have definitely asked for  'gene details' to change to "specific gene name" on this page.

**Comment by kimrutherford** [comment]
In the breadcrumb trail it now shows the gene name (or else systematic ID) instead of "Gene details".

**Comment by Antonialock** [comment]
woo, super!
