### ISSUE TITLE
genotype management workflow (notes from 5 May call)

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1133]
Notes from the call. I don't think this is everything but I'm putting a list. We can split into separate tickets.

workflow improvement in genotype creation/management (2)
1. Make the genotype details a pop up as a menu  item by mouse over instead of clicking
(for this, how will it look when you just create a genotype and land on the page, you won't be mouse over-ed so you won't see the details, can  the 'active' one be defaulted in this situation?)

2. Genotype details  does not need to display "background" and "Name" , they are in the table
3.  Hide the 'description' the one allele of the genotype per row display with link to gene is sufficient (is that what we decided?)
4. Hide  the "background" and "name" columns of the table if none are added (they are optional)
5. There will be a link to the 'genotype page'  showing the annotations, from the pop-up. This is where you will land, IF you have mane a phenotype annotation, but not if you only created a genotype. The genotype page will have clear "back to summary" and "back to genotype management options"

**Comment by kimrutherford** [comment]
> for this, how will it look when you just create a genotype and land on the page, you won't be
> mouse over-ed so you won't see the details, can the 'active' one be defaulted in this situation?)

We should be able to do that, although it's a bit of an odd user interface.

**Comment by kimrutherford** [comment]
> 1. Genotype details does not need to display "background" and "Name" , they are in the table
> 2. Hide the 'description' the one allele of the genotype per row display with link to gene is sufficient
> 3. Hide the "background" and "name" columns of the table if none are added (they are optional)

I've done these three bits.  And I've changed the table to show the links at the right when you move the mouse over the row.  It's still a bit beta though.

Since Canto is down here's how it looks now.  The look can easily be changed.

![screenshot 2016-05-09 18 59 06](https://cloud.githubusercontent.com/assets/90474/15105763/683d07a6-1618-11e6-80f7-66ef5e193098.png)

**Comment by Antonialock** [comment]
It looks ok although personally I think I would prefer having the description one per line in the left hand description column, and getting rid of the description in the white box completely.

Yeah it will take up a bit more vertical space but it won't be ridiculously wide and I find the left hand table a bit illegible (and that's the one you need to scan in order to get to what's shown in the white box)

**Comment by kimrutherford** [comment]
> I would prefer having the description one per line in the left hand description column, and getting
> rid of the description in the white box completely

That makes sense.  I'll try that tomorrow.

**Comment by Antonialock** [comment]
the "click a description to view and edit genotype details" should probably also change :-)

"click a description to annotate or edit the genotype"?

**Comment by mah11** [comment]
>> how will it look when you just create a genotype and land on the page, you won't be
>> mouse over-ed so you won't see the details, can the 'active' one be defaulted in this situation?)
> 
> We should be able to do that, although it's a bit of an odd user interface.

I don't think I paid much attention to this bit when the ticket opened. Now that I am thinking about it, I admit I don't actually understand the request or what it would look like. Speaking only for my own oddball self, it would be fine to create a genotype and then return to the genotype management page with nothing selected or highlighted, same as if I'd got there from the summary page link. I would know that I hadn't selected anything/wasn't mousing over anything, and I would know to look at the bottom of the genotype list for the newest one.

**Comment by mah11** [comment]
>> I would prefer having the description one per line in the left hand description column, and getting
>> rid of the description in the white box completely
> 
> That makes sense. I'll try that tomorrow.

I agree that the popup box looks weird now, but where will the gene page links that use the standard gene names (in case of allele names that use synonyms) go in the new scenario?

**Comment by ValWood** [comment]
> We should be able to do that, although it's a bit of an odd user interface.

ignore this bit. Of course it is at the bottom of the list...

**Comment by mah11** [comment]
> the "click a description to view and edit genotype details" should probably also change :-)
> 
> "click a description to annotate or edit the genotype"?

I would lean away from using "annotate" here because "annotate a phenotype" is awfully long for a header on a half-page-width table, and without the "phenotype" part it's confusing whether it refers to adding a phenotype or changing details of the genotype itself.

**Comment by ValWood** [comment]
> I agree that the popup box looks weird now, but where will the gene page links that use the standard gene names (in case of allele names that use synonyms) go in the new scenario?

How often do we use these? (me almost never, if ever)
Do we actually need them here? (they can be on the genotype page)

**Comment by mah11** [comment]
Thinking more about the genotype table and popup box ...

If we have the full description only in the leftmost column of the table, with one allele per line, we could add the gene name links there if we want to (or not, if not).

Then we could add a something to each table row to invite clicking - a pivoty expand/collapse triangle, or a "see more" text link, or ..? Anyway, if we put something intuitive in each row, we probably wouldn't need text instructions at the top of the table at all.

**Comment by ValWood** [comment]
> Thinking more about the genotype table and popup box ...

That sounds good

**Comment by mah11** [comment]
> How often do we use these [gene page links]? (me almost never, if ever)

Well, I literally never use them; I've only ever clicked on as part of testing. But one of the things I get reminded of every time we discuss Canto interfaces is how unusual my work patterns are ;)

> Do we actually need them here? (they can be on the genotype page)

For a while it seemed like we were moving more of the genotype page functions to the box o' details on the management page popup, but I'm not bothered if you want to stop short of everything, and have gene page links only on the genotype details pages.

**Comment by ValWood** [comment]
In that case I think they can be tucked away....

**Comment by Antonialock** [comment]
I use the gene page links quite a bit...I can imagine that I'd miss having them....

**Comment by ValWood** [comment]
OKay doke back to plan A

**Comment by kimrutherford** [comment]
> I would prefer having the description one per line in the left hand description column, and getting
> rid of the description in the white box completely

Done.

**Comment by kimrutherford** [comment]
New look:
![screenshot 2016-05-10 18 07 56](https://cloud.githubusercontent.com/assets/90474/15136932/236723ec-16da-11e6-9f46-5250b6a614eb.png)

**Comment by kimrutherford** [comment]
> Anyway, if we put something intuitive in each row, we probably wouldn't need text instructions
> at the top of the table at all.

I think I agree but I'm not sure how it should look.

Currently you don't need to click, just moving the mouse over will show the links.  That's great, but only if you know about it.

**Comment by kimrutherford** [comment]
There's a know bug at the moment that if you make a GO annotation - it screws up and redirects to the genotype management page.  :-/

I'll fix that.

**Comment by ValWood** [comment]
Yeah, I think we need something at the top "mouse over to..."

**Comment by Antonialock** [comment]
Yay I like that look best :-)

How about "mouse over genotypes for more actions"

**Comment by ValWood** [comment]
So, now do we still need better text for the drop down?
Annotations for this genotype -> view annotations?
Edit details -> edit genotype details?
Duplicate -> Copy and Edit?

Suggestions?

**Comment by kimrutherford** [comment]
> There's a know bug at the moment that if you make a GO annotation - it screws up and
> redirects to the genotype management page.

Fixed.

**Comment by kimrutherford** [comment]
Just to confirm, is this the plan now:

- when you add a genotype, return to the genotype management page
- when you add annotation a phenotype, go to the details page for the genotype?

**Comment by mah11** [comment]
> ... is this the plan now?

That sounds fine to me.

**Comment by ValWood** [comment]
I'll go with that.

**Comment by kimrutherford** [comment]
> Just to confirm ...

I think I've changed all the links and I've added an arrow/triangle to make it more obvious that the rows are clickable (well, mouse-over-able).

Please have a look when you have a chance.

**Comment by kimrutherford** [comment]
> Please have a look when you have a chance.

I'm done some more tweaking and fixed some bugs.  I'll not sure about the current behaviour.  It more or less works but it's a bit odd.

**Comment by mah11** [comment]
I think I see what you mean about "a bit odd", although it seems to be working. I imagine I'd get used to it in a while if we deploy it.

One thing that's odd specifically is that there's no way (as far as I could tell) to dismiss the popped-up details/links box. I'm glad it doesn't go away when I mouse elsewhere, but maybe a "close" x-in-a-circle in a corner (that works, of course) might be a nice little thing, even if it's seldom used.

Maybe also use the slightly heavier border around the popup, so it looks that bit more continuous with the "highlighted" border that's used for the selected table row? But remember I'm not sure I'm all that brilliant at the subjective aesthetic stuff ...

**Comment by ValWood** [comment]
I think we are all done in this ticket. 
I will transfer Midori's final comments to a new ticket and we can decide what needs to happen.

If we need to change anything from here, open new tickets

**Comment by mah11** [comment]
note - #1140 is not related to this ticket
