### ISSUE TITLE
text changes for annotation extension prompt

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1134]
Above the extension option links:

old:
You have annotated to protein serine/threonine kinase activator activity (GO:0043539). Can you extend this annotation by providing additional details based on the experiments in this paper? These extension types are allowed for GO:0043539:

new:
Can you extend this annotation by providing additional details based on the experiments in this paper? These extension types are available for protein serine/threonine kinase activator activity (GO:0043539):

[links]

Below the links:

old:
You can use more than one of these types in one extension (this creates a "compound" annotation extension and implies that the extensions occur together).

If you want to create another independent extension for this annotation, finish the annotation, and then use the "Duplicate" feature, where you can edit any field, including 
the extension.

new:
Use as many extension types as apply to this annotation. ["More ." link or help icon]

I'm not sure we made a final decision about whether to use "more", a help icon, or both (probably don't need both). If we go with "more" it can use text from the documentation, which is nearly identical to the current blurb anyway.

I don't care where the "edit as string" admin option goes relative to the text or other links.

**Comment by kimrutherford** [comment]
This bit from the old text:

"Can you extend this annotation by providing additional details based on the experiments in this paper?"

Is only shown when making a new extension.  It's not shown if you're editing an extension.  Would you like to do anything like that for the new text?

**Comment by mah11** [comment]
I'm not 100% sure I understand the question. But I don't think we need the "Can you extend .." question in the extension editing popup. It'll probably do to have

    "These extension types are available for $term ($id):"
    
    [links]
    
    "Use as many extension types as apply to this annotation."

does that help?

**Comment by kimrutherford** [comment]
> does that help?

Yep, thanks.  I've changed it but not released it yet.

This bit currently only gets shown if there is more than one possible extension relation:
  "Use as many extension types as apply to this annotation."

Here is how it looks in the long workflow and if you edit an annotation in the case where there is just one extension:
![screenshot 2016-05-10 19 17 09](https://cloud.githubusercontent.com/assets/90474/15138429/eab2fc74-16e3-11e6-94ab-f61104d95f50.png)
![screenshot 2016-05-10 19 15 42](https://cloud.githubusercontent.com/assets/90474/15138434/f1766744-16e3-11e6-97dd-a62d9dd6336a.png)

Is it too brief now?

**Comment by ValWood** [comment]
I think thats really clear.

Maybe make the GO term more 'contained'?

Perhaps
"GO:0045944 positive regulation of transcription from RNA polymerase II promoter"
in quotes?

**Comment by mah11** [comment]
> Is it too brief now?

Well, I don't think so, but I like brevity ;)

**Comment by ValWood** [comment]
yep, as short as possible, but no shorter...

**Comment by mah11** [comment]
The GO term could be made more prominent with quotes, italics, or even just by starting a new line for the term name. In any case, I would leave the ID in parentheses at the end, not put it first.

**Comment by ValWood** [comment]
OK, maybe italics. Just to make it clear where term starts.

**Comment by kimrutherford** [comment]
I meant to add an example of the interface with there is more than one possibility in the extension interface.  I've also made the term name italic to see how it looks.

![screenshot 2016-05-11 17 28 39](https://cloud.githubusercontent.com/assets/90474/15170871/f97a8e60-179d-11e6-86c5-0385eb6c337e.png)
![screenshot 2016-05-11 17 26 56](https://cloud.githubusercontent.com/assets/90474/15170876/02287176-179e-11e6-89a6-2159cc5f03b3.png)

**Comment by kimrutherford** [comment]
Those changes are in the main Canto now if you want to have a look.

**Comment by ValWood** [comment]
Looks good to me (from figure)

**Comment by mah11** [comment]
Looks fine in real life, too. Closing as requested.
