### ISSUE TITLE
reorder list of modification extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1137]
I think  
"position modified" would be better at the top of the list. 
Agreed?
(Most commonly used?)

![position modified at top](https://cloud.githubusercontent.com/assets/7359272/15507566/170bf182-21c4-11e6-9e79-c4cb17c87046.jpg)
?

**Comment by kimrutherford** [comment]
The list is in the same order as in the configuration file - pombe-embl/supporting_files/annotation_ex_config/PSI-MOD_A_E_config

If you'd like "position modified" at the top, move it to the top of the config file.

**Comment by ValWood** [comment]
M&A do you approve of moving this up?

**Comment by mah11** [comment]
I don't care

**Comment by ValWood** [comment]
done
