### ISSUE TITLE
group allele descriptions which differ only by background  in pull down

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1139]
Make allele descriptions which differ only by background are grouped next to each other in the pull down. 

If you have a long list you might select the wrong one if you don't realise you need to select the one with the correct background....

Follow on from
https://github.com/pombase/canto/issues/1125

**Comment by kimrutherford** [comment]
Fixed in the test Canto.

**Comment by kimrutherford** [comment]
Reverted because of #1153.
