### ISSUE TITLE
Improve text  for GO config file prompts

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1140]
From
[ deleted link to irrelevant ticket -mah ]

This was for me.
I forgot  to do this before I went away and now I forgot what I was meant to do.

**Comment by mah11** [comment]
This may overlap with #1073. It certainly has nothing to do with the genotype workflow.

**Comment by kimrutherford** [comment]
>> I forgot to do this before I went away and now I forgot what I was meant to do.

> This may overlap with #1073.

Yep, it might be to do with:

> Add an additional column to the config to specify more detailed text to accompany the
> dialogue box. In the first instance, this can be the same as the prompt (or it can be optional).
> We can then add/change these on a case by case basis to provide improved help for the user.

I added the extra column to the config files but currently it is empty and the Canto code ignores it.

**Comment by ValWood** [comment]
Discussion is in duplicate 
https://github.com/pombase/canto/issues/1173
