### ISSUE TITLE
Improve text for first part of annotation extension editing

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1141]
From
[ deleted link to irrelevant ticket -mah ]

2. Improve text for first part of annotation extension editing. Hide the rest under an information icon (MAH). 

(Here maybe a short text like this:)
Tip: You can quickly make additional extensions on this annotation once you have finished one extension, by  using the "duplicate and edit" feature.

**Comment by mah11** [comment]
This is unrelated to the genotype workflow. Some of the relevant changes have been done in #1134. What remains outstanding is:

1. Decide whether to add a "More ..." link or a help icon to the box with the "can you extend ..." message (curators; I have no preference)
2. Draft text to appear when "more" or icon is clicked (unless the decision in step 1 is "neither") (mah)
3. Implement what we get from steps 1 & 2 (Kim)

Note that it's also all explained in the documentation, not that very many people actually read it.

**Comment by ValWood** [comment]
This is OK isn't it?
I'll close and we'll open a new one if anything esle is required.

Can everyone pay attention to the text and check it seems  OK for a naive user?
