### ISSUE TITLE
new text  for "genotypes used in this session" page

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1142]
from https://github.com/pombase/canto/issues/1133#issuecomment-219400256

Need to change
"click a description to view and edit genotype details" 

Antonia suggested: "click a description to annotate or edit the genotype"?

**Comment by ValWood** [comment]
Midori: I would lean away from using "annotate" here because "annotate a phenotype" is awfully long for a header on a half-page-width table, and without the "phenotype" part it's confusing whether it refers to adding a phenotype or changing details of the genotype itself.

**Comment by ValWood** [comment]
Antonia:
How about "mouse over genotypes for more actions"

**Comment by mah11** [comment]
Let's go with Antonia's suggestion - it's short, it says what to do immediately, and the links that appear are pretty self-explanatory.

**Comment by ValWood** [comment]
OK
