### ISSUE TITLE
genotype management workflow tweak (dismiss popped up box?)

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1144]
From:
https://github.com/pombase/canto/issues/1133#issuecomment-219400256

Midori:
I think I see what you mean about "a bit odd", although it seems to be working. I imagine I'd get used to it in a while if we deploy it.

One thing that's odd specifically is that there's no way (as far as I could tell) to dismiss the popped-up details/links box. I'm glad it doesn't go away when I mouse elsewhere, but maybe a "close" x-in-a-circle in a corner (that works, of course) might be a nice little thing, even if it's seldom used.

Maybe also use the slightly heavier border around the popup, so it looks that bit more continuous with the "highlighted" border that's used for the selected table row? But remember I'm not sure I'm all that brilliant at the subjective aesthetic stuff ...

**Comment by kimrutherford** [comment]
I've made the two changes suggested by Midori.  It still looks a bit odd.

**Comment by ValWood** [comment]
OK can open a new ticket for any further improvement...
