### ISSUE TITLE
genotypes not visible in review on www

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1146]
see
![missing genotypes](https://cloud.githubusercontent.com/assets/7359272/15544681/77547bc2-2291-11e6-821d-e9a367487c4f.jpg)

https://curation.pombase.org/pombe/curs/200ad9dc9f52e2f1/ro/

**Comment by kimrutherford** [comment]
That's fixed in the test Canto.

**Comment by ValWood** [comment]
Let me know when in main, waiting to send session to user
v

**Comment by kimrutherford** [comment]
I've just updated main.  Might be a good idea to do a little bit of annotation with it, including editing annotation with the edit dialog before sending out.  I'm fairly certain that the recent changes haven't broken anything but not 100%.

**Comment by ValWood** [comment]
ok, i'm about to curate a paper......will let you know.....
exciting!

**Comment by ValWood** [comment]
I'm struggling, it appears to be 'hanging'. At first I thought it was my connection but I haven't managed to do anything in canto yet...

**Comment by kimrutherford** [comment]
It seems OK at this end.  Which session are you using?

**Comment by ValWood** [comment]
https://curation.pombase.org/pombe/curs/9754872522d7e5a0/feature/gene/view/1

i seem to be able to access other websites but this has been hanging for about 10 mins

**Comment by kimrutherford** [comment]
That works fine for me.  Can you access the builds directory?:
  https://curation.pombase.org/dumps/latest_build/

or to this URL:
  http://oliver0.sysbiol.cam.ac.uk/

Those two aren't handled by the Canto code so should work.

What about the Sysbiol website?: http://www.sysbiol.cam.ac.uk/

**Comment by ValWood** [comment]
all fine now...

**Comment by ValWood** [comment]
should all the changes be in (the swanky new genotype stuff isn't there or are we still waiting to make that live?)

**Comment by kimrutherford** [comment]
The changes to the genotype management page (#1078) aren't in yet.

Also #1139 and #1110 aren't in I think.

**Comment by ValWood** [comment]
okay doke...everything looks fine so far.....
