### ISSUE TITLE
annotation extension config files (question behavior)

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1148]
When I make an entry to the config files, I try to go as specific as possible  so that, for example I have not added

protein localization localizes
because some descendants like
"protein import to the nucleus" can have the  more specific prompt "transports"

(transporting is a child of localizing, but not all localizing is transport, some is just 'holding something in place')

However, it gets a bit tricky for terms like
	"establishment of protein localization to organelle"

which are quite specific but could still occur by localization or transport.

I am wondering if we can have a system where, if I add 
"localizes" to a parent node, if we subsequently add "transports" (a more specific relation) to a  descendent, it can 'trump' the 'localizes' prompt?

This would means that I would not need to add lots and lots of config lines for specific terms (really tricky in this branch).

For now, I am going to add 'localizes' for 
GO:0071989 establishment of protein localization to spindle pole body
which means that 

GO:1990852	protein transport along microtubule to spindle pole body
will be 'localizes' instead of 'transports'

**Comment by mah11** [comment]
This seems related to #1021, in that both require doing something more sophisticated with ontology relations and paths than Canto does now.

**Comment by kimrutherford** [comment]
> if we subsequently add "transports" (a more specific relation) to a descendent, it can 'trump'
> the 'localizes' prompt

In #1040 we talk about being able to configure things like: "GO:0071989-GO:1990852", meaning GO:0071989 and its descendent except for GO:1990852 and its descendants.

If that issue was done I think this issue would just be configuration.

**Comment by ValWood** [comment]
Yes, that would work...

**Comment by kimrutherford** [comment]
OK, I think this is done now.  Hopefully I haven't misunderstood things.

I'm reloading the ontologies in the test tool now.  I've added this configuration:

    GO:0071989-GO:1990852   is_a    has_input       ProteinID       localizes               0,1     user

The "GO:0071989-GO:1990852" means show this extension for every term that is_a GO:0071989 and is NOT is_a GO:1990852.

**Comment by kimrutherford** [comment]
> I'm reloading the ontologies in the test tool now.

It didn't work so I'll do some debugging.  I haven't changed the main Canto.

**Comment by kimrutherford** [comment]
It's working now in test.

This configuration is working as advertised:

    GO:0071989-GO:1990852    is_a    has_input   ProteinID   localizes    0,1     user

It's also possible to use the "GO:0071989-GO:1990852" syntax for the range.  eg.

    GO:0006897   is_a   occurs_at   GO:0032153-GO:00123456|GO:00054321   occurs at    0,1     user

To make debugging the configuration easier if you're logged in as admin and you mouse over a extension relation description, it shows a pop up with a few details about the config.  Knowing the domain should be enough information to find the line in the configuration:

![screenshot 2016-06-20 19 12 58](https://cloud.githubusercontent.com/assets/90474/16188521/074e2726-372a-11e6-9bc7-00a0ae6c442e.png)

**Comment by ValWood** [comment]
OK, Im not sure that I got this right but I did this for the above:

>GO:0071989 establishment of protein localization to spindle pole body
>which means that
>GO:1990852 protein transport along microtubule to spindle pole body
>will be 'localizes' instead of 'transports'


GO:0071989-GO:1990852	is_a	has_input	ProteinID	localizes		0,1	user
GO:1990852	is_a	has_input	ProteinID	transports		0,1	user

Is that right?

**Comment by kimrutherford** [comment]
Looks right to me.  I'll run the ontology update for the test Canto so you can check.  It takes about an hour.

**Comment by ValWood** [comment]
hang on, still trying to commit....

**Comment by ValWood** [comment]
done

**Comment by mah11** [comment]
Can we also use parentheses as described in https://github.com/pombase/canto/issues/1040#issuecomment-159871248?

If so, I have a FYPO config to do that way (sorry to be awkward!).

**Comment by kimrutherford** [comment]
> Can we also use parentheses as described in #1040 (comment)?

Not yet, but it's not a big change.  I'd prefer to give the current changes a day or two of testing before I try to implement it.  Please prod me if I forget.

**Comment by mah11** [comment]
OK. I've got the config line present but commented out for now.

**Comment by mah11** [comment]
added some terms to use for this:
  abolished molecular function FYPO:0005446
  abnormal biological process FYPO:0005447
  abolished biological process FYPO:0005448
  abolished cellular process FYPO:0005449

config is ready (commented out), so closing.

edit file: 4158dd9b75bc28661c7d776c1236d095b9b8fc70
release: 39ee606b2a85f601036d35a66cc2045610c82bc2

**Comment by ValWood** [comment]
I'll test this for my example .......

**Comment by ValWood** [comment]
In test
GO:1990852
still prompts for "transports" and "localizes"


Possibly is getting  "localizes" from somewhere else other than GO:0071989-GO:1990852
but even though I am logged in I don't see the  "doamin" info when i mouse over?

**Comment by mah11** [comment]
GO:1990852 is also is_a is_a: GO:0071988; maybe that link should be deleted

[Term]
id: GO:1990852
name: protein transport along microtubule to spindle pole body
[snip]
is_a: GO:0071988 ! protein localization to spindle pole body
is_a: GO:0071989 ! establishment of protein localization to spindle pole body
is_a: GO:0098840 ! protein transport along microtubule
is_a: GO:1902580 ! single-organism cellular localization

**Comment by ValWood** [comment]
Isn't that link OK?
localization is transporting to or maintaining in a location?

If so I can tweak the config file....

**Comment by mah11** [comment]
In GO, the general pattern is establishment of localization part_of localization -- GO:0071989 is part_of GO:0071988. I would also say that transport is a type of establishment of localization, and that the GO:1990852 is_a GO:0071988 link isn't necessary because GO:1990852 has a path to GO:0071988 via the part_of step. As an additional bonus, removing GO:1990852 is_a GO:0071988 will also make your Canto config work as expected, because it says to follow only is_a links.

**Comment by ValWood** [comment]
Ah got it, will open a ticket...

**Comment by ValWood** [comment]
Will close when extension options look OK

**Comment by kimrutherford** [comment]
Should I release these changes in the main Canto?

**Comment by ValWood** [comment]
I think that will be OK...Occasionally there will be duplicate suggestions, but we can apply config file fixes for these. It seems to be working OK.

Just so I know, If we change the config file, how soon do the changes implement in the live tool?

**Comment by kimrutherford** [comment]
> how soon do the changes implement in the live tool?

Currently there is one update a day at 4am.  We could make that more often though.  The maximum would be once an hour as it takes that long to run (I want to improve that though).

**Comment by kimrutherford** [comment]
Although the code for excluding sub-ontologies isn't in the main tool yet.  Let me know if you're happy with the test Canto and then I'll update the main one.

**Comment by kimrutherford** [comment]
> To make debugging ... it shows a pop up with a few details about the config.

I forgot to re-release but it's in test Canto now.  The code for excluding subsets isn't in the main Canto yet so any configuration like:

    GO:0071989-GO:1990852    is_a    has_input   ProteinID   localizes    0,1     user

will be ignored.

**Comment by ValWood** [comment]
weird, I thought it was working......

**Comment by kimrutherford** [comment]
Shall I update the main Canto with these subset exclusion changes?  The test version seems OK.

**Comment by ValWood** [comment]
OK....

**Comment by ValWood** [comment]
Close?
