### ISSUE TITLE
session admin: some changes to "fields" available for reports

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#115]
List of publications with active sessions

~Has a field "Type"
This is always "unknown" 
What does this refer to?~
column no longer visible

~Has a field for "Session status"
I don't think we necessarily need this column as the sub lists from the main page will provide this information (by providing independent lists for status)~
fine as is

~Has field "approver name"
We don't need to see this field until a session is in approval?~
fine as is

Has fields "community curable"  and "Curation priority"
Possibly  have a column " Flags"
which lists the flags when they are "active"?
(we have a high priority list so maybe drop this one?)

~Has Field "load type" user load.
I don't think we need this as a column?~
no longer visible

~Has field "Triage status" but for this particular list "publications with active sessions"
triage status should always be "curable"?~
fine as is

**Comment by ValWood** [comment]
priority flag is up for discussion in
https://github.com/pombase/canto/issues/746
