### ISSUE TITLE
double mutant phenotype annotation not appearing

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1150]
I realised the paper I curated did not have any phenotypes.
Doing another one

curs/8d41506ec01aec5b/feature/genotype/view/2

all going fine until I tried to add a phenotype to the double mutant genetype. It doesn't appear. I tried twice?
I

**Comment by kimrutherford** [comment]
Which double mutant did you add it to?  Could you add the link to this issue?

The one you mentioned (curs/8d41506ec01aec5b/feature/genotype/view/2) is a single allele genotype.

**Comment by kimrutherford** [comment]
I've just successfully added a double mutant genotype in my test session and then added a phenotype.  I'll need help to reproduce this.

**Comment by ValWood** [comment]
skype?

**Comment by ValWood** [comment]
try adding a phenotype to the klp5/klp6 double mutant.
Add "viable vegetative population"
It doesn't appear?
https://curation.pombase.org/pombe/curs/8d41506ec01aec5b/genotype_manage

**Comment by ValWood** [comment]
now it did.... i did it twice honestly!

**Comment by kimrutherford** [comment]
Your Skype connection was a bit shake last night.  If the network is slow the annotation might take a while to show up.  I'll fix it to show a loading... message so you know what's going on.

**Comment by ValWood** [comment]
yes my network was playing up...I bet that's it...

**Comment by ValWood** [comment]
although the duplicate annotations didn't show up either...

**Comment by kimrutherford** [comment]
I've improved the error handling so it now should be more clear when a failure like this occurs - hopefully not too often.
