### ISSUE TITLE
reverse order of new genotypes ?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1152]
should we have these appear at the top of the list rather than the bottom?

When the list gets long you don't see the highlighted new ones...

**Comment by mah11** [comment]
I prefer not to. I kind of like that the list ends up in the order that I add the genotypes, and I really like that it's consistent with the annotation tables. (The latter also means it's not new to the genotype interface, and the having-to-scroll problem is not unique to genotypes.)

**Comment by ValWood** [comment]
Yeah I was going to say that in general I would prefer the new entries to appear at the top of the tables rather than the bottom, which would be consistent and preserve ordering.

**Comment by kimrutherford** [comment]
My guess is that for community curators, newest at the bottom would be least confusing.

**Comment by ValWood** [comment]
OK!
