### ISSUE TITLE
confusing genotype order

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1153]
I just added 6 new genotypes to session 85f3e68940957230

This is the order I entered them into canto:
![screen shot 2016-06-07 at 10 58 53](https://cloud.githubusercontent.com/assets/12727506/15853879/e27643a6-2c9e-11e6-8a38-38e971501807.png)

This is the order they appear in on the genotype management page:
![screen shot 2016-06-07 at 11 00 43](https://cloud.githubusercontent.com/assets/12727506/15853921/18474dea-2c9f-11e6-80ff-4826944a7625.png)

This is the order they appear in when you copy+edit a phenotype annotation:
![screen shot 2016-06-07 at 11 01 38](https://cloud.githubusercontent.com/assets/12727506/15853950/42d3bb8e-2c9f-11e6-9f9e-27104bbfde50.png)

I thought we agreed on 'newest at the bottom' this feels like a bit of a random mashup

**Comment by mah11** [comment]
It has just recently started putting genotypes in ASCII order in the pulldown (I hadn't spotted that it was also ascii-alphabetizing on the genotype management page, but that's what your second screenshot shows - same as the pulldown in the third pic). I'd really got used to the order in the pulldown matching the order I'd entered genotypes, but thought it was just me. If it's not me being weird then maybe it should be changed back to order-entered everywhere.

**Comment by Antonialock** [comment]
I think that would be more intuitive

**Comment by ValWood** [comment]
yep order entered

**Comment by ValWood** [comment]
oh in the pull down. I know why this happened
its a consequence of this ticket:
https://github.com/pombase/canto/issues/1139

Maybe this isn't such a big issue? reverse? other solution?

**Comment by mah11** [comment]
No, actually what Antonia and I are saying is that we don't like the effect of the change, even though it was done for a request in a ticket. We would like it restored to the order entered.

**Comment by ValWood** [comment]
I know. I'm saying maybe this isn't such a big issue
#1139
reverse the change.

There might be a solution which makes it easier to see same allele, diffferent background in a long list.

**Comment by mah11** [comment]
oh, ok. it wasn't clear that the change was the thing to reverse (could've meant put in reverse order)

**Comment by kimrutherford** [comment]
So is the decision to un-do the change in  #1139?

**Comment by mah11** [comment]
yup

**Comment by kimrutherford** [comment]
Fixed in the main Canto.

**Comment by mah11** [comment]
thanks, and sorry for the back-and-forth bother
