### ISSUE TITLE
Make each part of the extension editable

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1154]
From #1131:

https://github.com/pombase/canto/issues/1131#issuecomment-224846311

> Hmm, as a start, can you make the extension editable?  At the moment you need to delete the
> extension + add a new one in order to change it.
> 
> In the example below for instance, say I added the extension "telomere" but meant to add
> "rDNA". In order to change it I must delete "telomere" and then add "rDNA". It would be nicer
> to be able to click on "telomere" and then get to the "start typing a description" box.
> The ability to edit the extension might make copy+edit less painful.

**Comment by ValWood** [comment]
This isn't really a big problem. Let's close it.
