### ISSUE TITLE
Ordering....

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1156]
Is it annoying anyone else that genetic interactions are appearing above phenotypes 
I think the ordering should be

GO
phenotype (single/multiple)
Modification
Physical interaction
genetic interaction

Which happens to also be the order on the gene pages
(I though ti used to be this way)

**Comment by ValWood** [comment]
![ordering](https://cloud.githubusercontent.com/assets/7359272/16045711/9aa66c88-3241-11e6-9311-6d25480a0c6e.jpg)

**Comment by mah11** [comment]
It doesn't bother me much, but lately I have actually occasionally used the fact that phenotypes are last - I can reach them by going straight to the bottom of the page. Not a big deal, though.

**Comment by Antonialock** [comment]
I don't mind either way

**Comment by kimrutherford** [comment]
Changing the order is just a configuration change.  Let me know what you decide.

**Comment by ValWood** [comment]
I would prefer the change if nobody objects.....

**Comment by kimrutherford** [comment]
So this order:

GO molecular function
GO biological process
GO cellular component
protein modification
phenotype
genetic interaction
physical interaction

or should phenotype come before modification?

**Comment by ValWood** [comment]
phenotype before modification...
This will make phenotype close to the top ( because there are not usually so many GO annotations)

**Comment by kimrutherford** [comment]
I've changed the configuration and update the test Canto.  A side effect is that the order of the annotation types on the gene page has changed too.  It's consistent with the order of the annotation tables but the phenotype links look a bit odd.  Is this OK?:

![screenshot 2016-06-16 09 27 29](https://cloud.githubusercontent.com/assets/90474/16097930/af24cd62-33a4-11e6-8dd7-513b755098d6.png)

**Comment by ValWood** [comment]
Slightly.  Lets discuss later. 

Maybe 
Phenotype (single allele)
Phenotype (multiple allele) 

With the other info under a mouse over would be better?

**Comment by kimrutherford** [comment]
Yep, that makes sense.

**Comment by kimrutherford** [comment]
> With the other info under a mouse over would be better?

Should I go ahead with this change or would you like to discuss it first?

**Comment by ValWood** [comment]
Would this be OK, I'd be happy with this...would it be confusing?

**Comment by ValWood** [comment]
This is,'t really issue...will think if a better way longer term
