### ISSUE TITLE
Synchronise user name and email from sessions with main list

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1159]
When a user starts their own sessions they can enter whatever name and email they like.  We should check if the email is already in the database and check that the name matches what we have on record.  If it doesn't match ask the user to confirm which is correct.

Currently the user name is stored in the session which means the name can differ between sessions.

See also #593

**Comment by ValWood** [comment]
Also want to delete a user 	(Xie Tang- has left science)
I can't figure out if this is possible.

**Comment by ValWood** [comment]
Can we close this?
Since we have
https://github.com/pombase/canto/issues/593

**Comment by ValWood** [comment]
Will close, reopen if required
