### ISSUE TITLE
display GO qualifiers as  "real" text

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1160]
It took me a while to figure what this meant looking at a recent session......

![contributes_to](https://cloud.githubusercontent.com/assets/7359272/16187560/f8083132-36c8-11e6-8c35-1ca5b04b48bd.jpg)

**Comment by kimrutherford** [comment]
Could you give me a bit more detail about what the problem is?

**Comment by ValWood** [comment]
I want to see has_qualifier contributes_to
(if you come to a session later or in review you have no idea what you mean)

Maybe all of the terms should display instead of IDs (like the GO ID here)

**Comment by ValWood** [comment]
curs/b365bd06b75ce0d4

**Comment by kimrutherford** [comment]
> I want to see has_qualifier contributes_to

Right, got it.

> Maybe all of the terms should display instead of IDs (like the GO ID here)

All of which terms?

**Comment by Antonialock** [comment]
The extensions?

So instead of seeing PBHQ:xxx, PR:xxx, GO:xxx, SO:xxx etc etc you see the text term name

**Comment by ValWood** [comment]
yep...

**Comment by kimrutherford** [comment]
I think we decided to try just the IDs in the extension text because some term names are long.  Is that going to be a problem?

**Comment by ValWood** [comment]
Not sure.....

@Antonialock  @mah11 ? I know it isn't a big deal for us, we can usually look them up, but I think in review sessions they need to be spelled out. I don't know if length of term will be a problem (try it and see? Mouse over instead?

**Comment by mah11** [comment]
For relations and qualifiers, show the text all the time.

For term names vs. IDs, l like the name-by-mouseover idea best. I suspect long names would annoy me if they were always visible. Is there any sort of visual cue we could provide to invite the requisite mouseage (what, that isn't a cromulent word?)?

**Comment by ValWood** [comment]
+1

**Comment by Antonialock** [comment]
Hmm....I would really prefer to see the term name (most term names are not that unwieldy are they? If some are ridiculously long we could cut them after x characters with a '...' and then people would have to click it/mouseover to get the full name)

**Comment by ValWood** [comment]
I'd go for that too...

**Comment by ValWood** [comment]
Because I can't see the extensions, I often end up recording what I put in the comment so I can remember the difference. It adds quite a lot of time to keep track of this in a complicated session. So I'll call this 'high priority' as I think it might be really quick?



![see go term names in extensions](https://cloud.githubusercontent.com/assets/7359272/17975286/015822c8-6ae1-11e6-95f7-28e132514eba.jpg)

**Comment by kimrutherford** [comment]
I think I've fixed this.  The full name is now show.  If it's longer than 60 characters it will be truncated.  You can see the full name if you mouse-over or if you click on the "..." and the end of the truncated name.

Please have a look and see what you think.

**Comment by ValWood** [comment]
Is this only in test so far?
I don't see the changes here...
https://curation.pombase.org/pombe/curs/74dade3ace393390/ro/

**Comment by kimrutherford** [comment]
> Is this only in test so far?

It's in the main Canto so it should work for your session.  Thanks for the link.  I'll get on with fixing it.

**Comment by kimrutherford** [comment]
Should be fixed now.

**Comment by ValWood** [comment]
great, I can delete my notes from this session !
