### ISSUE TITLE
renamed -gene -> rename deletion allele

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1162]
There might be a ticket about this. I just wanted to add this example:

![fzr3](https://cloud.githubusercontent.com/assets/7359272/16188592/3ccc7922-36ce-11e6-86c3-86310895bcad.jpg)

**Comment by ValWood** [comment]
will this be re-named to delta fzr3, now that the gene is called fzr3?

**Comment by kimrutherford** [comment]
> will this be re-named to delta fzr3, now that the gene is called fzr3?

Nope.  There is a post-load task that fixes the case where the gene has been given a name after the allele was named.  It only changes deletion allele names that contain a systematic ID.

There are 55 deletion alleles in v60 where the allele name isn't gene_name + "delta":

  allele_name          |   gene_name   
-----------------------+----------
 mug80delta            | clg1
 mrpl6delta            | mrpl1602
 ptr6delta             | taf7
 mrpl11delta           | mrp11
 mrps5delta            | mrp5
 mug82delta            | pth4
 sod2delta             | nhe1
 mrpl16delta           | mrpl1601
 fub2delta             | uba2
 pmc1delta             | med14
 eic1delta             | mis19
 eic2delta             | mis20
 mug55delta            | fzr3
 gcg1delta             | ggc1
 matPidelta            | mat2-Pi
 gld1-delta            | gld1
 tup11-delta           | tup11
 dak1-delta            | dak1
 dak2-delta            | dak2
 scr1-delta            | scr1
 sts1delta             | erg4
 pub1-WWdelta          | pub1
 CDTdelta              | hrq1
 rrm1delta             | mug28
 rrm2delta             | mug28
 rrm3delta             | mug28
 rrm1delta rrm2delta   | mug28
 rrm1delta rrm3delta   | mug28
 rrm2delta rrm3delta   | mug28
 pho1-ncRNAdelta       | pho1
 mrx1delta             | mxr1
 ppg1delta             | ppa3
 abc1delta             | ybt1
 php2 delta            | php2
 sks1-delta            | rpn11
 delta/delta           | rhp6
 dil1delta             | dhc1
 atg18delta            | atg1801
 mug179delta           | atg1802
 atg14delta            | vps38
 lrp1delta             | sog2
 cdc27partial_delta    | cdc27
 cdt1-PIP28delta       | cdt1
 rad30delta            | eso1
 clr4delta             | sir2
 rad22delta            | rad52
 mat1-Mmdelta          | mat1-Mi
 matPcdelta            | mat2-Pc
 P3nmt1-egt1 egt2delta | egt2
 scn1delta             | scn3
 972-tsc1delta         | tsc1
 972-tsc2delta         | tsc2
 nup189n-delta         | nup189
 nup189c-delta         | nup189
 xba1-xba1delta        | ste4
(55 rows)

**Comment by ValWood** [comment]
I will fix  the fzr3 one in the session.
The others will need dealing with on a case by case basis. I think some are OK, some not.
I'll transfer task to curation tracker.
Val
