### ISSUE TITLE
GO config file query....

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1163]
This is in the file:
GO:0004672	is_a	has_substrate	ProteinID	phosphorylates		0,1	user

BUT I don't get a prompt for "phosphorylates" for this term.

I do get it for the descendant  GO:0004674

any ideas why?

I haven't done any hairy if this not this in this file yet:
https://curation.pombase.org/dumps/latest_build/pombe-embl/supporting_files/annotation_ex_config/GO_MF_A_E_config

**Comment by kimrutherford** [comment]
> BUT I don't get a prompt for "phosphorylates" for this term.

I look into that.

> I haven't done any hairy if this not this in this file yet:
https://curation.pombase.org/dumps/latest_build/pombe-embl/supporting_files/annotation_ex_config/GO_MF_A_E_config

That only gets updated when I do a Chado load which I haven't done in a few days.

**Comment by kimrutherford** [comment]
> BUT I don't get a prompt for "phosphorylates" for this term.

It works for me - I see phosphorylates for GO:0004672 in test and main Canto.

**Comment by ValWood** [comment]
how weird.
I definitely didn't see it in the session:
curs/edfddf218bf755ae/feature/gene/view/1
The protein  kinase activity annotations I made when testing are still there too....
