### ISSUE TITLE
New term requests not stored

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1165]
When you enter a new term request "the slow way" 
I.e. by going to a genotype or gene page -> add a new phenotype -> suggest a new child term
the term request is not stored.

The term request is stored if you add it the quick way, i.e. when copy+edit an existing annotation.

This happens for both GO (I tried an MF) and phenotypes.

**Comment by kimrutherford** [comment]
Thanks for spotting that - fixed now.
