### ISSUE TITLE
Link PMID search on Canto home to read-only session view

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1166]
When non-admin users search for a PubMed ID from https://curation.pombase.org/pombe/, the can start curating if there isn't already a session for the paper. But if there is a session, they just get the "sorry, being curated by someone else .. contact curators" message, and it's kind of a dead end. It's the same whether the session is in progress or approved (I suspect session status doesn't matter at all).

It would be much better to replace "please contact the curators" with a link to the read-only view of the session. Suggestion for accompanying text:

"PMID:nnn [is currently being curated|has been curated] by someone else. You can see <a read-only view of the annotations>, or contact the curation team for more information."

Not only is it a bit friendlier, it would mean anyone could see what's been or being curated from a paper starting from the PMID; they wouldn't have to have us look up the session link.

This has some overlap with #481, but isn't identical.

**Comment by mah11** [comment]
re-trying linky to ticket #481

**Comment by ValWood** [comment]
How much work is this one?  Is it quick

**Comment by ValWood** [comment]
This isn't directly attribution but it may have some overlap (people pages)

**Comment by kimrutherford** [comment]
> (I suspect session status doesn't matter at all)

Yep, you get the message if there is a session, whatever state it's in.

> You can see , or contact the curation team for more information.

Midori, did some words get lost from this sentence?

> How much work is this one? Is it quick

Should be quick.  I'll have a go now.

**Comment by kimrutherford** [comment]
This is done in the test Canto.  I didn't go with the exact wording you suggested but I hope it makes sense.  Could you have a look and let me know what you think?

The "Continue" button will now take you to the read-only / review link for the session one already exists for the publication.  If there is no session, it creates one.

**Comment by ValWood** [comment]
currently

PMID:16682348 is currently being curated by someone else. You can view, but not change the existing curation sesison. Contact the curation team for more information.

maybe

PMID:16682348 is currently being curated by someone else. You can view, but to change the existing curation session please contact the curation team (add helpdesk link here?).
(We don't want to put people off providing any input at this stage)

Also maybe the buttons could be reordered and relabelled

[ View session ] [ Find another]

(In case it was not quite clear what they are continuing to)

**Comment by kimrutherford** [comment]
> [ View session ] [ Find another]

So if there is a session:
  [ View session ] [ Find another ]

If there isn't an existing session:
  [ Find another ] [ Continue ]

Does it make sense for the "Find another" to move position?

**Comment by kimrutherford** [comment]
I've changed the label to say "View session" if there is an existing session.  So for now the buttons are:
[ Find another ] [ View session ]
or
[ Find another ] [ Continue ]

Is that order OK?

> You can view, but to change the existing curation session please contact the curation team 

I'm not sure about this.  They can't change the existing curation session.  Perhaps something like this instead?:

    You can view the curation session.  Please contact the curation team
    to suggest changes to the annotation.

**Comment by mah11** [comment]
> Is that order OK?

yup

>  Perhaps something like this instead?:
> 
> You can view the curation session.  Please contact the curation team
> to suggest changes to the annotation.

I agree - that's more accurate and sounds fine.

**Comment by ValWood** [comment]
All good.

**Comment by kimrutherford** [comment]
I think this is done now.
