### ISSUE TITLE
streamlining genotype management

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1168]
We want the "add a genotype page" and "genotype management page" combined, to reduce clicking between the two pages (to speed up copy+edit existing genotypes for example).

**Comment by kimrutherford** [comment]
What should the "Edit details ..." link do?  Should it still go to a new page?  A pop-up?  Or should it act like "Add a genotype..." and appear at the top of the page?

![screenshot 2016-07-04 11 27 39](https://cloud.githubusercontent.com/assets/90474/16548187/a5c9b7d4-41da-11e6-9f21-f9fe0beffee0.png)

**Comment by kimrutherford** [comment]
I've made some of the necessary changes and released them into the test tool.  The "Add a genotype ..." link on the genotype management page now puts the genotype editing form inline at the top of the page.

That mostly works except that the links box that pops up when you mouse-over a genotype ends up in wrong place on the page.  I'm working on that.  Both the "Cancel" and "Finish" button should work as expected.  Please let me know if they don't

Also the "Edit details ..." link doesn't work at all.  That's temporary.  Let me know how it should work - see comment above.

**Comment by mah11** [comment]
> What should the "Edit details ..." link do?

A pop-up, I guess, with going to a new page a close second (i.e. I don't have much preference). I do think filling in the top of the page might be too easy to overlook, especially for a genotype far down a long list (if you've had to scroll to reach the genotype, you won't see what happens if it's just the top of the page that changes).

**Comment by ValWood** [comment]
Should we look at this tomorrow? I'm getting a bit lost. Another walk through might help...

**Comment by kimrutherford** [comment]
> A pop-up, I guess, with going to a new page a close second (i.e. I don't have much preference).
> I do think filling in the top of the page might be too easy to overlook,

I agree, but I'm concerned about the pop-ups within pop-ups.  (The allele edit pop-up inside a genotype edit pop-up)

**Comment by mah11** [comment]
I wouldn't have a strong objection to going to a new page if the advantages of limiting popup frenzy is worth it. (see "not much preference" above)

**Comment by ValWood** [comment]
Closing this as outstanding is moving to  new tickets
