### ISSUE TITLE
add quick annotation links to summary page (advanced mode)

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1173]
Advanced mode is awesome. To make it even more convenient, add links to do annotations straight from the paper summary page.

I may have got a bit lost during the discussion on the skype call, so comment if any this is wrong:

Add the set of curation types to the summary page; it should appear for any session in advanced mode. Clicking a curation type link should spawn a pop-up for that type, just like the ones that appear for the gene page "quick add" links except with one or two pulldowns to select genes.

There'd be one gene selector for the ontology annotations, and two for interactions. This will make a lot more sense if #229 gets done, because the interaction popup should have pulldowns in the order 
1. first gene
2. evidence
3. second gene

We talked about putting "Quick add" links next to the gene links, but the problem with that is that the pop-up content isn't the same for all annotation types, so this would get into a jungle one way or another - pop-ups spawning more pop-ups, or having to have dynamic pop-up content (if that's even possible). So I've written up the version where the links are organized by annotation type, even though that means adding more linky text to the summary. It's worth it ;)

**Comment by ValWood** [comment]
sounds good to me.

**Comment by ValWood** [comment]
Isn't this done?

**Comment by kimrutherford** [comment]
> Isn't this done?

It isn't done.  I haven't added quick links on the paper summary page yet.

**Comment by mah11** [comment]
In other words, you still have to click a gene name to reach links to add a new GO, interaction, or modification annotation (as opposed to duplicating an existing one).

**Comment by kimrutherford** [comment]
I've added a "Quick links" section on front/publication page.  Currently it's only shown if you are logged in as admin.  Once you're happy with it I can make it visible in "Advanced mode" if that makes sense.

**Comment by mah11** [comment]
Seems to be working fine - very nice!

**Comment by kimrutherford** [comment]
The quick add links on the front page now appear only when "Advanced mode" is on.
