### ISSUE TITLE
one-click "add deletion allele"

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1174]
In the add-a-genotype interface, let's add a new button for each gene in the list, to add allele type:deletion and expression:null for the gene in one click (takes 3 now). The old button would still do the same allele detail pop-up thing as now.

button text could be 'add deletion allele' & 'add other allele'

We don't even have to remove 'deletion' from the pull-down in the pop-up for 'add other allele'; it'll just save clicks to have an instant deletion-adding button. (Can you tell I've been adding a lot of deletion alleles to sessions lately?)

**Comment by ValWood** [comment]
I like that too....

**Comment by ValWood** [comment]
replaced by this proposal
https://github.com/pombase/canto/issues/1381
