### ISSUE TITLE
select alleles & combine into new genotype

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1175]
This one might be pretty pie-in-the-sky, but the idea occurred to me so I'm recording it here for posterity:

We often see papers that look at single mutant A and single mutant B, and then put them together into multi-allele mutant AB. It would therefore be very handy to be able to select two or more alleles entered into a session, and make them into a new genotype.

I'm sort of imagining a column of tickboxes in the genotype table, at least for the single-allele genotypes*, and a button to "create new new genotype from selected genotypes".

I guess it should prompt for expression for non-deletion alleles all in one pop-up, maybe with the expression value entered for the single allele selected by default? Or it could just allow expression changes via the allele edit link, but that might not draw enough attention to expression ... something to discuss if this actually gets done.

*It could even support combining any existing genotypes to generate new ones, unless we think that's too complicated.

**Comment by ValWood** [comment]
Yes, I think we envisaged something like this early on.... it would be nice...

**Comment by ValWood** [comment]
this will be resolved by our new proposal:
https://github.com/pombase/canto/issues/1381
