### ISSUE TITLE
list of sessions created with no curator assigned

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1176]
Is there a way to get this list?
Maybe a link from Admin would be useful?

I have deleted most of these orphan sessions recently, I think, which should put them back into the curation pile....

closing
https://github.com/pombase/curation/issues/893

**Comment by ValWood** [comment]
Is this easy?
I just wanted to check

Its not urgent, but  some papers have a session, but no assigned curator

https://curation.pombase.org/pombe/view/list/curatable_publications_with_sessions?model=track

like
PMID:45343
PMID:1901818
which probably need removing....

If I had a list I can go through and either  i) delete the session,/ retriage as loaded in error

or make sure it gets back in this list
https://curation.pombase.org/pombe/view/list/curatable_publications_without_sessions?model=track

which is where we would select sessions from.

**Comment by kimrutherford** [comment]
I've added a new report at the bottom of the admin page: "Sessions without a curator"

**Comment by ValWood** [comment]
fantastic, all sorted....
