### ISSUE TITLE
expressivity not allowed with FYPO:0005229

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1177]
for eg FYPO:0005229  	decreased transcription from RNA polymerase II promoter during vegetative growth 
we allow penetrance but not expressivity
shouldn't it be the other way around?

**Comment by mah11** [comment]
It should allow both. Expressivity is missing because it doesn't have a path to abnormal phenotype. I'll fix that (https://github.com/pombase/fypo/issues/2723).
