### ISSUE TITLE
extension mouse over text

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1178]
when you mouse over the available extension options you get some weird text, see screenshot.

I think the mouse overs should say something friendly instead, like that expressivity = the severity of th phenotype, penetrance the proportion of population affected, etc (I thought this was implemented already?)
![screen shot 2016-07-06 at 12 28 13](https://cloud.githubusercontent.com/assets/12727506/16616475/6043c546-4375-11e6-864a-ece0ad1459ae.png)

**Comment by ValWood** [comment]
This is just temporarily in admin mode to help us with the config file configurations (I think?)

**Comment by mah11** [comment]
The configuration column for friendly mouseover text now exists, but I haven't spotted any filled in yet. I'll add some for penetrance and expressivity.

**Comment by ValWood** [comment]
Ha ha, was just about to open a ticket about that.

In the session I am approving  now (the one I began on FRIDAY!) Henar ignored "expressivity" and added 'low penetrance' as a comment....

**Comment by kimrutherford** [comment]
> This is just temporarily in admin mode to help us with the config file configurations (I think?)

Yep.  It's admin only.  I added it to help work out why a relation appeared twice in the dialog.  Sorry about the horrible formatting.
