### ISSUE TITLE
potential feature for new term requests

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1181]
This might be useful, it depends on others workflow.

when I make a term request I do this:

![hyperlink term requests](https://cloud.githubusercontent.com/assets/7359272/16646910/8fe7f66e-4424-11e6-9b1c-9d4a58e59f7e.jpg)

It would be nice if I could add
fypo/issues/2726 or GO equivalents and it would resolve to the fully hyperlinked URL

But only if useful for others.....

**Comment by Antonialock** [comment]
is that even possible? 

I guess I could modify my workflow to make this work. At the moment I just do one ticket per paper.
I do think it is good though to check that the terms + defs are correct (of course they are almost all the time, but occassionally there are problems, generally with the really straight forward copy+paste terms :-) )

**Comment by ValWood** [comment]
I don't want to change your workflow....I just wondered is anyone else would find it useful.
I often  do a bunch of papers and its a couple of weeks before I find time to fill the missing terms in. Until I did this I always had a  hard time  mapping the term requests to the tickets, especially for papers which need lots of new terms.    I usually go from  tickets to sessions, and fill them in as they come through but I always seem to have a  bunch of  sessions which have stagnated  and I do these by going from sessions to tickets....

I look at the session and I can go to the relevant ticket immediately, but at the moment I need to cut and paste the URL (I suspect it would only take a  few minutes  to implement or I wouldn't have suggested it).

Its not really required in the whole scheme of things.....

**Comment by Antonialock** [comment]
ohhh I misunderstood you, you want a clickable link? I thought you meant that you wanted the NTR to sort itself out!

**Comment by ValWood** [comment]
Now that, I do want ;)

One day you will hopefully be ably to go from her directly to the "correct" TG template  based on the parent ;)

**Comment by Antonialock** [comment]
in a galaxy far far away :p

**Comment by ValWood** [comment]
I would never click this link, I can always cut and paste it if I want to go to the ticket, but usually I am going from ticket-> canto, not from Canto -> ticket
