### ISSUE TITLE
default this table (and others in admin) to the left

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1186]
This can get pretty annoying when you want to scroll through a large dataset. 
 The final right hand columns are less important, but if I want to see the contents I always need to scroll right.
There is *loads* of while space to the left though (a big 'margin')
This applies to a few admin tables.

![default left2](https://cloud.githubusercontent.com/assets/7359272/16782869/70be77aa-4879-11e6-9682-787395c1d49e.jpg)

**Comment by kimrutherford** [comment]
I'm not sure how to move things to the left in this case without breaking other things.  I've made a quick change that might help: I've changed the header line style to allow word wrapping and I've made the font slightly smaller.

It now looks a bit worse, but fits on the page.

https://curation.pombase.org/pombe/view/list/curatable_low_priority_publications?model=track

**Comment by ValWood** [comment]
Thats better......

**Comment by mah11** [comment]
I've already got used to it ... let's close this and move on to more interesting stuff ;)
