### ISSUE TITLE
Allow editing of multiple extensions

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1188]
With the new "adding extensions for multiple annotations" feature
#1131

it would also be nice to be able to edit each separate extension "unit"

for example, say you have a protein kinase, and you add 2 different gene product substrates for it (has substrate x and has substrate y).
Then you realize you want to compound these with a "during cell cycle phase" extension.

Currently you'd need to delete the original extensions and then add the new compounded
"has substrate x during A" "has substrate y during A"

it would be nice to be able to tack on "during A" for both extensions without having to delete the original extensions.

**Comment by ValWood** [comment]
@Antonialock / @kimrutherford  is this ticket the same as
https://github.com/pombase/canto/issues/1154 ?

**Comment by Antonialock** [comment]
not quite...#1154  is about editing a single extension, this ticket is about editing piped extensions...i.e.
say you want to add happens_during(dna damage response) to each of tehse two genes

has_substrate(geneX) | has_substrate(geney)

at the moment if you add the has_substrate, it can only be added to the geneY extension

this ticket can be low priority because we have the "edit as string" option

**Comment by kimrutherford** [comment]
> this ticket can be low priority because we have the "edit as string" option

Also, we now have the "Add independent extension ..." option in admin mode which helps a bit.

**Comment by ValWood** [comment]
Is this an issue? It isn't clear how to me how this would be implemented as the curator would need to somehow specify  which extensions in the compound term the additional extension applied to anyway

**Comment by ValWood** [comment]
feedback required from @Antonialock

**Comment by ValWood** [comment]
@Antonialock  could you  can you clarify?

**Comment by Antonialock** [comment]
I think this is ok now since we can text edit
