### ISSUE TITLE
Duplicating an annotation & extensions

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1189]
Follow on from #1187

Val suggested that when an annotation is copied, we should be forced to tick/untick keeping any extensions. 
This is to
1. save clicking for removal of extensions
2. stop inadvertent carry over of extensions from duplicated annotations

Midori didn't like this because " Not having to add an extension over again is a big part of what makes duplicating useful."

For me, I think (1) is not so much of a problem any more with the solution in #1187
However, I think (2) could be an issue. 

Do we just need to make existing extensions (that will be copied over when duplicating) a bit more prominent? For example move it to between the term name and the evidence code?

![screen shot 2016-07-13 at 12 21 34](https://cloud.githubusercontent.com/assets/12727506/16801746/75ef7e2e-48f4-11e6-85b8-7f2f20a4aa43.png)

**Comment by mah11** [comment]
For me no. 2 is a complete and utter non-issue - when I copy an annotation that has an extension, it's on purpose and I want the extension included. Even no.1 isn't a huge thing, because if I don't want an extension, I copy an annotation that doesn't have one (even if I have to change something else, such as term ID or evidence).

I could accept a tick box if its default state is whichever would keep the extension ('keep' defaults to ticked, or 'remove' defaults to unticked).

**Comment by Antonialock** [comment]
How about moving the extension up to just underneath the term name and above the evidence? That will make it easier to see and separates it from the freetext boxes.

**Comment by mah11** [comment]
That probably wouldn't make any difference to me (once I got used to the new location), so if it'll help anyone else, ok.

**Comment by ValWood** [comment]
Lets leave for now. I'll monitor if mistakes are made (annotations not edited)

I think I generally choose the annotations with the same  term and  then switch the allele and penetrance. I perhaps should change which annotation I select to duplicate instead....

Will report back....
Also make a not if we notice sessions where the  evidence or extensions have obviously  been duplicated and not edited.

**Comment by ValWood** [comment]
- 

ACtion,

Go ahead and move  the extension up to between the GO term and the evidence

**Comment by kimrutherford** [comment]
> Go ahead and move the extension up to between the GO term and the evidence

I've done that.  Shall I close this issue?
