### ISSUE TITLE
Can't load annotations....

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1190]
Doesn't look good ;)

![default](https://cloud.githubusercontent.com/assets/7359272/16841689/4d17011e-49d2-11e6-8f42-81bd8f9449ad.jpg)

**Comment by kimrutherford** [comment]
Sorry about that.  The cv name for relationship ontology in Chado changed to "relations" but I didn't catch everywhere in the code where Canto was using the old name for querying.  I only switched Canto from Chado v60 to the latest load a day ago which will be why we didn't notice.
