### ISSUE TITLE
increase spacing between columns containing gene names

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1191]
Increase the spacing slightly between these columns at the top of the curation session home page, it looks a bit squashed at the moment

![screen shot 2016-07-18 at 12 10 32](https://cloud.githubusercontent.com/assets/12727506/16913187/af061944-4ce0-11e6-9ec2-ab80849947e1.png)

**Comment by kimrutherford** [comment]
Whoops, sorry about that.  My test session didn't have enough genes to make too columns so I didn't notice that when testing.
