### ISSUE TITLE
Improve the look of Canto

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1192]
We should discuss modernising Canto.  Here is a possibilty:

![screenshot 2016-07-18 23 00 05](https://cloud.githubusercontent.com/assets/90474/16914001/dad9a056-4d42-11e6-8618-d35f9e9ebf22.png)

**Comment by ValWood** [comment]
Like.

**Comment by Antonialock** [comment]
I think you can also drop "for PMID:23112169" where it says:
New annotations from this session for PMID:23112169

(the new vs existing annotations can probably be distinguished in a nicer way but can't think how )

**Comment by ValWood** [comment]
> I think you can also drop "for PMID:23112169" where it says:

yep, fewer words, good

**Comment by kimrutherford** [comment]
> I think you can also drop "for PMID:23112169"

That was quick, so it's done.

**Comment by Antonialock** [comment]
I see!

**Comment by kimrutherford** [comment]
I've made a few of the changes I've thought of but they are only in the test Canto for now.  I think it needs work.

**Comment by mah11** [comment]
Hmm. I admit I find it a bit funny-looking, but that's probably at least 90% due to just not being used to it.

**Comment by Antonialock** [comment]
some thoughts...

here I think "New annotations from this session " should:
- not be underlined, 
- the font should be smaller than for "GO molecular function" 
- indented from the header & aligned to the 'gene' column

![screen shot 2016-07-20 at 11 19 30](https://cloud.githubusercontent.com/assets/12727506/16983276/043308b4-4e6c-11e6-98dc-dd8350f76902.png)

" Click on a gene name to start entering data" is also an action?
"genotype management" sounds like it hsould come under "genes and genotypes.

I don't think these are very good headers in this case..
Maybe instead:

Add gene specific data
  Cdc2
  Mam2
  Psk1
Edit gene list
Genotype management

(No need to underline)

![screen shot 2016-07-20 at 11 22 03](https://cloud.githubusercontent.com/assets/12727506/16983337/4214d306-4e6c-11e6-9a15-501d2deaa849.png)

**Comment by kimrutherford** [comment]
Thanks Antonia.  I'll make those changes.

**Comment by kimrutherford** [comment]
>  I'll make those changes.

I've made those changes.  I hope I understood everything you mentioned.

**Comment by Antonialock** [comment]
I think that looks better thanks :-) Also "gene and genotypes" header could change, but not sure to what. 
Actions? Get started?

**Comment by Antonialock** [comment]
I think that looks better thanks :-) Also "gene and genotypes" header could change, but not sure to what. 
Actions? Get started?

**Comment by Antonialock** [comment]
Actually, "genes and genotypes" is an accurate description of the options, my only problem is that it doesn't inspire a reaction

**Comment by kimrutherford** [comment]
> it doesn't inspire a reaction

We could change:

### Genes and genotypes
#### Add gene specific data 

to:

### Add gene or genotype annotation

(ie. get rid of the sub-heading)

**Comment by Antonialock** [comment]
Might be ok? I dont have a better suggestion

**Comment by ValWood** [comment]
Annotate genes or genotypes?

**Comment by kimrutherford** [comment]
> Annotate genes or genotypes?

**Comment by kimrutherford** [comment]
This is in the main Canto now.  Please open new issues for problems.
