### ISSUE TITLE
merged columns

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1194]
The conditions column and the annotation extensions column are not separated by a vertical line. Example from session 292fcc3259a4f5aa

![screen shot 2016-07-20 at 09 53 56](https://cloud.githubusercontent.com/assets/12727506/16980949/4c1b963e-4e60-11e6-81e4-06bbb39b95d1.png)

**Comment by kimrutherford** [comment]
Is that a screenshot from Firefox?  If so can you try zooming in a bit?  Firefox has a bug where table cell borders get lost if you zoom out.

**Comment by mah11** [comment]
I don't have this problem, i.e. I see the vertical line as usual.

**Comment by kimrutherford** [comment]
I think this problem is caused by a bug in Firefox.  It was reported in 2008 but isn't fixed yet:
  https://bugzilla.mozilla.org/show_bug.cgi?id=410959#c23
