### ISSUE TITLE
review mode 'view phenotype annotations' link borked

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1195]
On any [session]/genotype_manage/ro page, the genotype page offers just one link, "View phenotype annotations", upon mousing over any entry in the table.

That's good, BUT the links don't work - each one displays the "Thank you for your contribution" content, i.e. like the page with the link to review the session (and for admins to do approval).

Are they just missing '/ro' at the end?

Any session you can look at in review mode will do for seeing the bug. I spotted it in 61c5a0ac6ec56979, but I've since started approval on it so you'd have to be logged out to see the symptoms.

Links from https://curation.pombase.org/pombe/curs/61c5a0ac6ec56979/genotype_manage/ro
show URLs like
https://curation.pombase.org/pombe/curs/61c5a0ac6ec56979/feature/genotype/view/3

but show page content as if they were
https://curation.pombase.org/pombe/curs/61c5a0ac6ec56979/

If I manually edit to
https://curation.pombase.org/pombe/curs/61c5a0ac6ec56979/feature/genotype/view/3/ro
I see annotations.

**Comment by kimrutherford** [comment]
Should be fixed now.  Hopefully there aren't any other links I've missed.
