### ISSUE TITLE
single allele background

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1196]
when adding a "single allele" allow the addition of a background

**Comment by ValWood** [comment]
You can add a background to a single allele,  but *only*  in the genotype management.
It would probably be better if this were avaiable on the single allele  pop up, but not urgent.

Raise priority f its a pain...

**Comment by ValWood** [comment]
this should become redundant with proposed changes? agreed?

**Comment by ValWood** [comment]
@Antonialock  
this should become redundant with proposed changes? agreed?

**Comment by Antonialock** [comment]
yeah
