### ISSUE TITLE
error reading GO annotations

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1199]
eg sessions
https://curation.pombase.org/pombe/curs/3c126315549fc38f/
https://curation.pombase.org/pombe/curs/dfcd11b5fda97a5f/ro/

![screen shot 2016-07-26 at 17 34 27](https://cloud.githubusercontent.com/assets/12727506/17146716/4e1baafe-5357-11e6-9822-3ae19ce2bce4.png)

**Comment by kimrutherford** [comment]
Sorry about that.  I changed the way term relationships were loaded into Chado a while ago and forgot to change the Canto code.  It's fixed now.
