### ISSUE TITLE
genotype "edit" link behavior

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1201]
What to do for "edit details" of a genotype:

- Fix it so it doesn't go to the "please come back later" message (as test does as of 2016-07-27)
- Keep the pop-up warning if a genotype has annotations
- Put the editing interface at the top of the genotype management page (same way "add" now behaves), and automagically scroll to the top when "edit details" is clicked

(follow-up to #1168)

**Comment by kimrutherford** [comment]
> Put the editing interface at the top of the genotype management page

How tied are we to that plan?  :-)

I've now had a look at what's involved in doing that.  It's going to be a bit yucky to implement.  It's completely doable but a pop-up or going to a separate would be simpler and involve fewer code changes.

If the consensus is that edit-at-the-top would be better, I'll go ahead with that.  But if you three are on the fence about it I'd rather implement it as a pop-up dialog.

Sorry to be asking about this again after we all made a decision.

**Comment by mah11** [comment]
>> Put the editing interface at the top of the genotype management page
> 
> How tied are we to that plan? :-)

I don't need it at all. Unless V&A really howl, go for what's easier to code.

**Comment by ValWood** [comment]
I can't remember which bit this is, so go with 'easy'

**Comment by kimrutherford** [comment]
Sorry, after trying a few things I've realised that a dialog wouldn't work because it would be too wide.  So I'll try the inline editing that we discussed first.

**Comment by kimrutherford** [comment]
After a fight with code and bugs, this is somewhat fixed in the test Canto.  There is (at least) one bug left - if you follow an edit link while editing, nothing happens.  My preferred solution is to hide the genotype table while editing.  Please try the test Canto and let me know what you think.

**Comment by mah11** [comment]
It seems to work fine.

>  My preferred solution is to hide the genotype table while editing.

That wouldn't bother me.

**Comment by mah11** [comment]
Tangent: one small thing that's disproportionately annoying (to me, anyway): the header needs a comma after "Add" (i.e. change to "Add, view and edit genotypes").

**Comment by kimrutherford** [comment]
> change to "Add, view and edit genotypes"

Fixed in the code now.

**Comment by kimrutherford** [comment]
> It seems to work fine.

Thanks for having a look.

>> My preferred solution is to hide the genotype table while editing.
> That wouldn't bother me.

Great, I've done that.

For me on Firefox there's a small but annoying lag between clicking "edit..." and the edit stuff appearing.  It's better on Chrome.  Is it a problem for anyone else?

**Comment by mah11** [comment]
> For me on Firefox there's a small but annoying lag between clicking "edit..." and the edit stuff appearing. 

I've just done ... oh, 20-30 seconds of testing on Firefox and Safari. Both seem to cough up variable lags - sometimes instantaneous, sometimes not, and if there is a lag it's not always the same length. It doesn't seem to correlate with anything about the genotype (different tries of the same one lag or not).

I don't edit details of existing genotypes often enough for it to be a big problem, though. Duplicating -- which I do waaay more often -- hasn't given me a lag so far.

**Comment by kimrutherford** [comment]
Thanks for testing.  

> Duplicating -- which I do waaay more often -- hasn't given me a lag so far.

Great, that may give me a hint as to how to speed up the edit lag.

**Comment by kimrutherford** [comment]
I think think is working so I've released it into the main Canto.  The edit link has a slight delay, but it's still faster than the existing code because it doesn't reload the page.  Please let me know if you spot a problem.

If you'd like to change the functionality please open a new issue.
