### ISSUE TITLE
Refine text for  selecting an ontology term

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1202]
from

![refine](https://cloud.githubusercontent.com/assets/7359272/17176908/c0da31a0-5406-11e6-976b-e3f975501567.jpg)

To:

Please read the term definition to ensure that it accurately described your gene.

Can you say anything more specific ?

These term a are available:
List specific terms

(Or suggest a new one HYPERLINK)

This will remove a lot of text....

**Comment by kimrutherford** [comment]
> (Or suggest a new one HYPERLINK)

Is that to replace all of this?:

The currently selected term has no children. If you need a more specific term to describe the experiment you are annotating, please follow the link below to suggest it:

(This text is shown if you click "more ...")
You may need a new term if the biology you are describing is not defined by existing terms in a way that will distinguish it from related function terms. Sometimes this will be a novel molecular function which has not been previously described, and so is not yet included in the ontology.

**Comment by kimrutherford** [comment]
> Is that to replace all of this?:

That is the text for the case where there are no child terms.  The text for the has child terms case is different.  It says this and has no "more ..." link:

"If you need a more specific term to describe the experiment you are annotating, and if none of terms above is appropriate, you can suggest a new term"

**Comment by kimrutherford** [comment]
> To:
> Please read the term definition to ensure that it accurately described your gene.
> Can you say anything more specific ?

I've made that change.

**Comment by Antonialock** [comment]
I think it looks a bit ugly that "can you say anything more specific" is underlined

I also think "can you say anything more specific" can move down a bit, so that it is further away from the selected term, and closer to "These terms are available:"

![screen shot 2016-07-28 at 08 53 04](https://cloud.githubusercontent.com/assets/12727506/17205100/1f9dff92-54a1-11e6-990b-fbbb0c86e619.png)

**Comment by ValWood** [comment]
This text could go in pop up  under a ? icon at the end of the row:

You may need a new term if the biology you are describing is not defined by existing terms in a way that will distinguish it from related function terms. Sometimes this will be a novel molecular function which has not been previously described, and so is not yet included in the ontology.

**Comment by ValWood** [comment]
Even less text if we did

replace
Can you say anything more specific
These terms are available

with
Can you use a more specific available term: (maybe refined @mah11 )

and then

Or suggest a new term?

(I forgot that this would need to be slightly  different on a page with no  term suggestions, so this will need to be adjusted accordingly)

**Comment by ValWood** [comment]
I also don't think the underlining will be a problem if it is a single line and there is a space between the section...

Just packed Antonia off to her new job this morning....exciting

**Comment by kimrutherford** [comment]
> with
> Can you use a more specific available term

I've done that.

> This text could go in pop up under a ? icon at the end of the row:

Sorry for not asking at the time: which row do you mean?  After "Can you use a more specific available term"?

**Comment by kimrutherford** [comment]
> and then
> Or suggest a new term?

I'm not sure about that.  We would be saying the same thing twice:

![screenshot 2016-08-10 17 09 31](https://cloud.githubusercontent.com/assets/90474/17542492/5243def4-5f1d-11e6-9d38-8ce203bcdddd.png)

**Comment by mah11** [comment]
Well, part of the reason I went with "can you say anything more specific" is that it did cover both "choose an existing one" and "suggest a new one". Whatever wording goes in the "can you ..." header, I think we don't need a second header above the "suggest a new child term for ..." link at all.

If others still want a second header, let's not use "Or suggest a new term?" as its text. Not only do I agree that it's redundant, it's also NOT GOOD GRAMMAR and therefore looks unprofessional.

**Comment by ValWood** [comment]
Do we know whats still needed here. Do we need to discuss further?

If anyone has refinements for the current test, suggest ?

**Comment by ValWood** [comment]
I'll Assume we are done here. We can open a new ticket for more
