### ISSUE TITLE
Add option to export all publication data with canto_export.pl

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1207]
For pombase/pombase-chado#67 we need to get the publication triage data into Chado.

Add it to the JSON output as an option.

**Comment by ValWood** [comment]
- [ ]

**Comment by kimrutherford** [comment]
Turns out that this is done.  I implemented it 4 years ago but forgot.  :-)

See: https://github.com/pombase/canto/blob/master/lib/Canto/Track/Serialise.pm#L167

**Comment by ValWood** [comment]
;)
