### ISSUE TITLE
small text change, boiler plate text

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1208]
#1169 
Or, open a new ticket to ask Kim if the first sentence can be suppressed just for FYPO. That might be the best approach if it's easy for him, because it's kind of odd to say gene products can be annotated to phenotype terms anyway, because phenotype annotations attach to genotypes, not products.

**Comment by kimrutherford** [comment]
I've hidden "Gene products may be annotated with multiple ... terms." for genotype/phenotype annotation.  It's only in the test Canto for now.  It now looks like this if you expand the help buttons:

![screenshot 2016-08-31 18 38 13](https://cloud.githubusercontent.com/assets/90474/18118597/239a12b0-6faa-11e6-8dff-55db5fca9140.png)
