### ISSUE TITLE
more info needed for sessions list

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1209]
So now, we have
![more_needed](https://cloud.githubusercontent.com/assets/7359272/17299724/6cc09d16-5807-11e6-8373-0ab33ef00c91.jpg)

so difficult to find sessions...maybe we could see part of the title to the right with  .......
(or ohter suggestions).

Not urgent but I do spend a bit of time trying to relocate sessions...(medium->low priority?)

**Comment by kimrutherford** [comment]
I've add the title beside the PMID.

**Comment by kimrutherford** [comment]
Long titles are truncated - click on the "..." to get the full title.

**Comment by ValWood** [comment]
yep
