### ISSUE TITLE
add triage  class 'structure' to canto admin report

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1212]
I forgot about this...

Can you add  under "curatable publications without sessions" Or somewhere suitable (probably the phenotype screen list should be in the same place)?
Once these are 'claimed' they can just revert to normal 'curatable', its really only for us to locate them easily...its a 'temporary' status

**Comment by kimrutherford** [comment]
> Once these are 'claimed' they can just revert to normal 'curatable',

Do you mean once they have a curator assigned?

**Comment by ValWood** [comment]
> Do you mean once they have a curator assigned?

yes but you don't need to do anything for this. It isn't many and we can just remove them from this bin as we do them. Longer term we'll  do it a  better way if we need to....

**Comment by kimrutherford** [comment]
> we can just remove them from this bin as we do them.

I'm a bit confused.  Which bin?

> Once these are 'claimed' they can just revert to normal 'curatable',

Do you mean you'll change them from "Structure" to "Curatable"?

**Comment by ValWood** [comment]
yes but we can do this manually when we have dealt with them. It's just a way of lumping them together so we can find them easily. Ideally they would be 'subsets" of curatable, but we can do that later with other "admin fixes". For now it seems easiest just to  make the "structure" label visible  in the same way as "phenotypic screen" is


Note: in case it wasn't clear, "structure" is already a "triage class", and I have been used it. Its just not visible on the  admin report
https://curation.pombase.org/pombe/track

v

**Comment by kimrutherford** [comment]
I've add Structure and Phenotype screen reports in the Curatable section.  Please let me know if that's what you need.

**Comment by ValWood** [comment]
yep, thanks!
