### ISSUE TITLE
average number of community curations is low

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1216]
I'm sure this must be right but its only 2.43 per paper. It seems as though it should be higher.

it has improved since my comment in 
https://github.com/pombase/canto/issues/1180

I'm thinking that the number of annotations looks very low for this year (118) based on the number of cc publications (87). I wonder why? It is possible I sent out more papers which were not suitable for CCur and came back with non, or that most of the papers had very few annotations but this seems statistically unlikely?
Especially compared to the number of annotations in the sessions we are checking right now...
Is there any way to check this?
list session IDs: number of CC annotations

I'll check again when some of the bigger sessions are through....

**Comment by kimrutherford** [comment]
It's now 268 annotations from 111 publications.

**Comment by ValWood** [comment]
Its now 559 from 227 publications! looking better...

**Comment by kimrutherford** [comment]
The counts now include interactions.  So for 2016 it's 965 community annotations from 74 community curated publications.  Sounds healthy?

**Comment by ValWood** [comment]
Yes sounds healthy!, but just to double check. BioGRID annotation are not assigned to community or PomBase are they?

**Comment by kimrutherford** [comment]
> BioGRID annotation are not assigned 

It only counts annotations from Canto, so BioGRID isn't included.

**Comment by ValWood** [comment]
Oh very nice healthy numbers then! Higher than I expected....
