### ISSUE TITLE
Fix title on term confirm dialog

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1217]
If you add an extension that needs a term, the confirmation dialog says "... accurately describes your gene" but that doesn't make sense here.  What should we change it to?

![screenshot 2016-08-10 17 20 48](https://cloud.githubusercontent.com/assets/90474/17542781/d9d4b940-5f1f-11e6-87c3-caed7d6ffe9e.png)

**Comment by kimrutherford** [comment]
For now I've changed it to "Please read and confirm the term definition" in that case.  Please let me know if that sound right.

**Comment by kimrutherford** [comment]
I've also changed "gene" to "genotype" in the phenotype workflow to fix this:

![screenshot 2016-08-10 17 56 01](https://cloud.githubusercontent.com/assets/90474/17543301/b9a924fe-5f23-11e6-92d5-5a1536b3987e.png)

**Comment by mah11** [comment]
> For now I've changed it to "Please read and confirm the term definition" in that case. Please let me know if that sounds right.

I think we could either leave it at that, or change it to "Please read the definition to ensure the term is applicable" (in case "confirm" makes it sound like we're asking if the term is correctly defined, when what we're asking is whether they still want this term when they've read the definition).

**Comment by kimrutherford** [comment]
> makes it sound like we're asking if the term is correctly defined

Good point.  I've changed it use your suggested text.  I'll close this issue but it's easy to update the text later if needed.
