### ISSUE TITLE
session list

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1218]
I thought my 'active sessions" looked low

https://github.com/pombase/canto/issues/1209#issuecomment-241252696

I have 21 CURATION_IN PROGRESS here
https://curation.pombase.org/pombe//view/object/person/vw253@cam.ac.uk?model=track
but I only see 8 when I acess the list.

Also Do we want to see "session created" here?
@mah11 @Antonialock ?

**Comment by kimrutherford** [comment]
> but I only see 8 when I acess the list.

Sorry about that.  The current implementation queries for the first 100 sessions that you are the current curator of.  It then splits those 100 into two groups - active and completed.

Perhaps it should show all the active sessions and just the most recent 20 completed sessions?

**Comment by ValWood** [comment]
That would better I think...

**Comment by mah11** [comment]
> Perhaps it should show all the active sessions and just the most recent 20 completed sessions?

Caveat: I never use the Canto home page list to look at/for my sessions, and I don't really know what community users would expect or prefer. With that in mind, how about:

For each list, show the first 10 (or pick a different number), and add a link to "show all".


> Do we want to see "session created" here?

For myself, I don't care - see "I never use this" above. Maybe it'd be useful for community curators; again, I really don't know.

**Comment by ValWood** [comment]
Just showing the first 10 is fine as long as the rest can be accessed in some way...

**Comment by kimrutherford** [comment]
> For each list, show the first 10 (or pick a different number), and add a link to "show all".

That's done now.
