### ISSUE TITLE
stats- uncurated paper location query

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1221]
From stats page,

1957 	1	1	0	0
1958	       1	1	0	0
1959	       1	1	0	0
1962 	1	1	0	0
1963	      1	1	0	0
1964	      2	2	0	0
1967	      1	1	0	0
1969  	3	2	1	0
1971 	3	2	1	0
1972 	1	1	0	0
1973	      8	3	5	0

I can't see any pre 1975 papers which require curating

so which bin are these in here?
I checked

Publications with new sessions (548)
Publications with active sessions (180)
Curatable publications without sessions (1893)

**Comment by kimrutherford** [comment]
I looks like there are some that are in the "Curatable, low priority" table:
  https://curation.pombase.org/pombe/view/list/curatable_low_priority_publications?model=track

This is the list of Curatable, low priority paper from before 1975.  None are curated:
 
 PMID:17248627
 PMID:14239779
 PMID:5312034
 PMID:13635553
 PMID:13495401
 PMID:4995430
 PMID:14198190
 PMID:4348926
 PMID:13902245
 PMID:6051345
 PMID:4836297
 PMID:13639938
 PMID:14021561
 PMID:4263279
 PMID:5312032

**Comment by ValWood** [comment]
Thanks, I forgot about that list. They can sit there for a while.

val
