### ISSUE TITLE
List of community curatable publications contains non-curatable

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1222]
If a paper is triaged as "non curatable"

https://curation.pombase.org/pombe/view/list/community_curatable_publications?page=2&numrows=500&model=track

The community curation flag should be forced to be toggled off.
(There might be another ticket about this...)

**Comment by ValWood** [comment]
So, we can ditch the "communiyt curatable flag/checkbox.

The list of community curatable sessions should be
i) Anything EVER assigned to a community curator
ii) Less anything which  does NOT have the label "curatable"

**Comment by ValWood** [comment]
Curatable publications without sessions (1897)

Community curatable publications (1388)
Kim says this is ALL sessions with communiyt curation flag set

Val says: This can't be true because
ALL
Curatable publications without sessions (1897)
has  the community curatable falg set by default. (i.e it is set, and I didn't set it)

**Comment by ValWood** [comment]
We have established that the flag is meaningless as used. But if we do it the other way it doesn't matter.

**Comment by ValWood** [comment]
For the first stage we want to assess the uptake.
I.e how many papers sent out. The base line for community curatable is  this paper has been assigned to a person., but we need to subtract any which were  subsequently retriaged as 'uncuratable'

How many have come back
How many of these had (any) annotation

**Comment by kimrutherford** [comment]
I've removed the community_curatable flag and modified the community_curatable_publications report.

The report now shows publications that are "Curatable" and have a session that was at some point assigned to a non-admin curator.  Hope I'm understanding that correctly.

It's only in test for now:
  https://curation.pombase.org/test/view/list/community_curatable_publications?model=track

**Comment by ValWood** [comment]
Hmm, 

test
Community curatable publications (1046)

live
Community curatable publications (1046)

how cant hat be???

**Comment by ValWood** [comment]
Is it possible, that even though we had that community curation flag, the  list of community curatable papers was not calculated using this flag?

**Comment by kimrutherford** [comment]
Sorry, I should have told you that I copied the main Canto db to the test Canto today.

**Comment by ValWood** [comment]
OK, that makes sense...I think it was higher before....

**Comment by ValWood** [comment]
so we can close this?
