### ISSUE TITLE
bug adding single allele phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1223]
When I add a new allele using the "single allele phenotype" link

I am punted straight to the  gene summary page after I add the allele, instead of a page where I can add the phenotype

**Comment by kimrutherford** [comment]
It now goes the genotype management page and select the row in the table for the new genotype.  Does that make sense?

**Comment by ValWood** [comment]
I think so, I'll reopen if anything is wrong when I test (shortly)

**Comment by ValWood** [comment]
Its still a bit odd...


 I think I expect to go straight here
https://curation.pombase.org/pombe/curs/c83c3de5e5b69049/feature/genotype/annotate/1/start/phenotype/

but I dont

**Comment by kimrutherford** [comment]
> I think I expect to go straight here

It currently goes to the same place you get sent when you make a multi allele genotype (the genotype management page).  Would it be OK for it to go somewhere different?  Would that inconsistency be a problem?

**Comment by ValWood** [comment]
No you are right, I think we decided to go to genotype management with the current genotype highlighted...

**Comment by kimrutherford** [comment]
OK, I'll close this for now.  We can revisit this later if it's confusing.
