### ISSUE TITLE
Change menu to say "Admin log in"

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1226]
Would it make sense to change the "gear" menu item names from "Admin" to "Admin pages" and "Log in" to "Admin log in"?

I'm suggesting the "Log in" change in case a user is clicking around and thinks they might need to log in to do anything.

![screenshot 2016-08-25 18 31 12](https://cloud.githubusercontent.com/assets/90474/17959074/20edf17e-6af2-11e6-8704-37f9d524313a.png)

**Comment by ValWood** [comment]
Sound sensible...
