### ISSUE TITLE
please come back later message

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1227]
I can add annotations etc in this session fine
https://curation.pombase.org/pombe/curs/7b30a1cc7d87ace2

but I want to edit a genotype that the community curator entered, but when I click the edit link here, (top right box of page)
https://curation.pombase.org/pombe/curs/7b30a1cc7d87ace2/feature/genotype/view/1

I get this message
(en) Please come back later
(fr) SVP veuillez revenir plus tard
(de) Bitte versuchen sie es spaeter nocheinmal
(at) Konnten's bitt'schoen spaeter nochmal reinschauen
(no) Vennligst prov igjen senere
(dk) Venligst prov igen senere
(pl) Prosze sprobowac pozniej
(pt) Por favor volte mais tarde
(ru) Попробуйте еще раз позже
(ua) Спробуйте ще раз пізніше
(it) Per favore riprova più tardi

**Comment by kimrutherford** [comment]
Whoops, I'll fix that.  While I'm fixing it you can edit that genotype from the genotype management page.

**Comment by kimrutherford** [comment]
Should be fixed now.
