### ISSUE TITLE
extension not found

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1228]
I'm trying to add the extension "during ceelular response to hydroxyurea" to a cellular component term. 

When I type in "cellular response to hydroxyurea" or just "hydroxyurea" the search doesn't find anything.
Howeer, typing in the GO ID works. 
![screen shot 2016-08-26 at 11 47 23](https://cloud.githubusercontent.com/assets/12727506/18003006/21cbf05a-6b83-11e6-9e38-f47d9ca343c5.png)
![screen shot 2016-08-26 at 11 47 40](https://cloud.githubusercontent.com/assets/12727506/18003007/24931782-6b83-11e6-928a-5c7a39659f4c.png)

**Comment by kimrutherford** [comment]
What was the component term you were adding the extension to?

**Comment by Antonialock** [comment]
nucleus

**Comment by kimrutherford** [comment]
existing_during for cellular component is configured to only allow descendants of GO:0022403, GO:0033554 and GO:0000747.

Does that need changing?

**Comment by Antonialock** [comment]
yes I think it would be sensible to add GO:0070887 cellular response to chemical stimulus too :-)

**Comment by kimrutherford** [comment]
OK, I've added GO:0070887 to the config file.  I'm reloading the ontologies and config now so it should be fixed in an hour or so.

**Comment by Antonialock** [comment]
thanks!
