### ISSUE TITLE
Question about allele names...

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1231]
alexander says
"Deletion mutants I made myself, I gave an allele designation in accordance with a recommendation put forward by Gerald R Smith and Susan Forsburg some time ago, this leeds to slightly awkward annotations, I hope this is not an issue. Please do not hesitate to contact me, if things need to be clarified. "

I thought I could deal with these by changing to 	dmc1Δ but by preserving Alexander's name  in the strain "name" field. We added this for the short names of multi-gene genotypes, but I think Alexanders names here are analogous (they are just an alternative name for the strain). I wonder if  this seems OK (and if we can use this field for synonyms in general?)
...In which case we  might need to be able to add more than one....(edge case)

![lorenz](https://cloud.githubusercontent.com/assets/7359272/18224522/5b34439e-71d0-11e6-9bcd-72ee2d1291ab.jpg)

Alternatively I could keep Alexanders names as these *are* different strains. I'm not sure which would be best...
What happens if we have 2 deletion strains with different names. Can we cope with that?

**Comment by kimrutherford** [comment]
Was this meant for the curation tracker?  I'm not sure what to do.

**Comment by mah11** [comment]
I think I see a Chado angle: the loader will throw a warning if we have "dmc1Δ" and "dmc1-12" both with the description "deletion".

Should I open a ticket for it now, or should the curators hash out what we want to do first?

**Comment by ValWood** [comment]
Lets discuss tomorrow....we needed a way to handle allele synonyms anyway.

Call dmc1Δ and put in "name" field for now?

**Comment by mah11** [comment]
By "name" I take it you mean genotype name? Genotypes and alleles can have names. If the type "deletion" is selected, Canto imposes dmc1Δ as the allele name.

**Comment by ValWood** [comment]
Yes genotype name (because this is essentially a lab specific name for a single allele genotype?)

**Comment by ValWood** [comment]
https://github.com/pombase/curation/issues/951

**Comment by ValWood** [comment]
I think we can close this then and pick up with new tickets?
