### ISSUE TITLE
possible small bug in editing genotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1232]
I think there is a bug here. I wanted to edit a genotype and I couldn't (from here). I got a pop up asking if I was sure, I said yes. Then nothing happens, I was still here:

![small bug](https://cloud.githubusercontent.com/assets/7359272/18225800/7e0a0d08-71f4-11e6-85cf-d642d9929cb5.jpg)

**Comment by kimrutherford** [comment]
Click OK now works.

**Comment by kimrutherford** [comment]
I've added a confirm box to the "Edit details ..." links on the genotype management page too.
