### ISSUE TITLE
paper look up bug

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1235]
I just got this  error

![paper_look_up_bug](https://cloud.githubusercontent.com/assets/7359272/18269008/316dbb12-741e-11e6-8849-60f5c8dcc76b.jpg)

I got it once yesterday too, but when I went back and reloaded it worked fine so I didn't get a screen shot.
Same here, it worked fine second time.

Are you using EBI ePubMED? I think there may be 'issues' as this morning publication details disappeared from the web pages for a while, and then later they reappeared.
(Oh the advantages of precompiled web pages....)

**Comment by kimrutherford** [comment]
Does this happen when you click on "Find ..."?

**Comment by ValWood** [comment]
yes, sometimes (twice for me now)

**Comment by kimrutherford** [comment]
Oh dear.  Which browser and browser version are you on?

**Comment by ValWood** [comment]
Google chrome, Version  says 52.0.2743.116 (64-bit)
but it appears to be updating as we speak...

**Comment by kimrutherford** [comment]
I still can't replicate this.

**Comment by ValWood** [comment]
I wonder if a few of my sporadic issues are a) network problems or b) browser bugs.

The other day, I say  a "ghost view" of  google from page load sporadically before the pombe home page loaded...I have never seen this before either.

I'll close this, and see if it keeps happening, can look in more detail?
