### ISSUE TITLE
keyboard shortcut for "OK" in popup

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1236]
I'd love a keyboard shortcut to do the job of clicking the "OK" button in any of the editing popups. It would cut down on the mousing significantly.

**Comment by kimrutherford** [comment]
I've added alt-enter as a shortcut on the annotation edit dialog.  Could you try it and let me know if it's what you're after.  I'll need to add an extra HTML tag to any other dialogs that you'd like the shortcut to work on.  Unfortunately I can't do it globally.

**Comment by mah11** [comment]
That. is. a. thing. of. beauty.

The other place where it would get a big bang-for-buck is the box for specifying allele details.

It's a little bit sad that there isn't a handy way to add it globally, but those two (allele details and annotation edit) probably account for most of my pop-up dealings, so will help a lot.

One thing: it appears to work in Firefox and Chrome, but not in Safari. I can adapt if necessary, if there isn't an obvious fix.

**Comment by kimrutherford** [comment]
> the box for specifying allele details

I've added that shortcut.

Let me know any others you'd like.  It's mostly a one line change for each of them but each needs a quick check to make sure it's not doing anything funky.
