### ISSUE TITLE
find box completely missing

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1238]
I just  got this...
(A reload fixed it)

![box missing](https://cloud.githubusercontent.com/assets/7359272/18323898/a2f48ce8-7531-11e6-98eb-fb16e35b7b3c.jpg)

**Comment by kimrutherford** [comment]
If your network connection is slow of flakey that could happen.  If it's just slow the box will appear when your network catches up.

Was that from home?

**Comment by ValWood** [comment]
yes from home...
