### ISSUE TITLE
table problem

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1240]
This table 

![per year](https://cloud.githubusercontent.com/assets/7359272/18344551/bbe22b88-75af-11e6-8468-70f2361f2465.jpg)

is annotations perpublication per year, but look, it only has SOME years ;)

**Comment by kimrutherford** [comment]
I think it's been like that for a while.  Fixed now.

**Comment by ValWood** [comment]
Yeah, I have looked it it loads and not spotted that!
