### ISSUE TITLE
partial deletion (allele)  prompt

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1241]
The prompt for "deletion of multiple aminoacid/nucleotides is

something like
specify deleted residues eg 1-455

I assume I can do this
![partial deletion](https://cloud.githubusercontent.com/assets/7359272/18349655/43ef04aa-75ca-11e6-862c-35a7d442e5e1.jpg)

is there room to do:
eg 1-455 or 1-455,600-769
or somehow let users know that this is how to form deletion of multiple segments?

**Comment by kimrutherford** [comment]
Do you mean for "partial deletion, nucleotide"?

The current prompt is: 
  Please specify deleted residues - eg. 100-200 OR -20--30 (for promoter region) 

And for "partial deletion, amino acid" the prompt is:
   Please specify deleted residues - eg. 100-200 

Let me know what the new text should be for each.


> 1-455,600-769

Yep, that's legal.

**Comment by ValWood** [comment]
I was on amino acid 
	Please specify deleted residues - eg. 100-200
So This  *could be*
eg 1-455 OR 1-455,600-769

and be no longer than the nucleotide one.
I think we are less likely to be  recording  multiple deleted segments with nucleotide coordinates.

@Antonialock  @mah11  sound OK?
Or does this only need to be in the documentation somewhere?

**Comment by kimrutherford** [comment]
You can edit the messages directly if you like.  Here's the amino acid one:

https://github.com/pombase/canto/blob/master/canto.yaml#L1220

**Comment by mah11** [comment]
I have no strong preference, so do what you like ;)

**Comment by ValWood** [comment]
done!

**Comment by kimrutherford** [comment]
Thanks, I've re-release the main Canto with the fix.
