### ISSUE TITLE
back to summary button on geneotype page not working

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1243]
For me right now (I wonder if this is sporadic to, I am sure I've been using it)

Anyway I can use the breadcrumb trail...

**Comment by kimrutherford** [comment]
I can't reproduce this.  Has anyone else seen it?

**Comment by ValWood** [comment]
This was quite persistent for me on Friday, it wasn't a one off, so  we'll keep it open, but  worry about it more if others are affected....

I'll add some links to affected sessions next time I see it.

**Comment by mah11** [comment]
I've seen it for the first time today, in my favorite test session (https://curation.pombase.org/test/curs/982304b134332abd) and in Jacky's current session (PMID:26869222 https://curation.pombase.org/pombe/curs/1bc92c0f892db627).

**Comment by mah11** [comment]
ooh, ooh, more symptoms!

In https://curation.pombase.org/pombe/curs/995720e27a54ba1b I noticed that if I just go to the genotype management page, and don't do anything but look at it, I can use the "back to summary" button. But once I add or edit any genotype, the button stops working.

It resumes working if I go back to the summary page via the breadcrumb trail link, and then to genotype management again (as long as I don't do any edits).

Deleting a genotype doesn't break the "back to summary" button.

(I was logged in, and have restarted session approval to add some double mutants I'd stashed. Not sure that makes any difference.)

**Comment by kimrutherford** [comment]
> But once I add or edit any genotype, the button stops working.

Ah!  Thanks for that!  I was able to reproduce that and fix it.

Cheers.

**Comment by ValWood** [comment]
The back to summary button is still sporadically not working for me. I haven't been able to identify any specific cases....

**Comment by ValWood** [comment]
From here:
https://curation.pombase.org/pombe/curs/a820cd9476653a92/feature/gene/view/2
