### ISSUE TITLE
wild type allele/expression restriction too strict

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1244]
At present, Canto behaves consistently with this error message:

"A wild type allele with wild type product level is only valid in a genotype that has a wild type allele of the same gene with non wild type product level (eg. Overexpression or Knockdown)"

But I have a case where a mutant allele was overexpressed with the wild type allele present at wild type levels, and it won't let me add the genotype.

The text and behavior should both change to

"A wild type allele with wild type product level is only valid in a genotype that also has another (i.e. mutant) allele of the same gene at any expression level, or a second wild type allele of the same gene with non-wild type product level (e.g. overexpression or knockdown)."

... Unless we don't want to fuss with wt + non-wt expression of wt in one genotype; then it could shorten to "A wild type allele with wild type product level is only valid in a genotype that also has another (i.e. mutant) allele of the same gene at any expression level".

(need pdp1+ at wt level to combine with pdp1-W66A or pdp1-F94A for PMID:19250904 7a38c014384c9f45; will remove placeholder wt overexp when this is fixed)

(follows on from #779 & #797)

**Comment by ValWood** [comment]
So Wild type is allowed  IF you have another allele of the same  gene (WT or mutant). If there are 2 copies of a gene, and both are WT, one must have increased or decreased expression.
If one gene is a mutant allele (non WT), the WT may have normal expression level.

Disallowed: having a WT allele with normal expression without another allele of the same gene?

**Comment by kimrutherford** [comment]
Consider doing this at the same time as: #976

**Comment by kimrutherford** [comment]
Consider doing this at the same time as: #976

**Comment by mah11** [comment]
> So Wild type is allowed IF you have another allele of the same gene (WT or mutant).

Yes - to clarify, wt sequence/wt level is allowed if there's another copy of the same gene present.

> If there are 2 copies of a gene, and both are WT, one must have increased or decreased expression.

Yes if the cell is otherwise haploid. (A diploid is allowed to have both copies of a gene be wt seq and wt level, but then we would rarely if ever bother to note that in a genotype.)

> If one gene is a mutant allele (non WT), the WT may have normal expression level.
 
yes, whether the cell is haploid or diploid

> Disallowed: having a WT allele with normal expression without another allele of the same gene?

yes, in a haploid; should be allowed in a diploid because that would be missing one copy (to check for haploinsufficiency etc)

**Comment by ValWood** [comment]
Hi Kim,

We are loathe to disturb you when you are in full flow on the gene pages. However, we  quite a large number of sessions building up which can't be approved because they don't have the correct allele combination. They are waiting until we can specify that a WT  normal expression copy of a gene is also present with a mutant copy.
So, could you have a look at this one when you next get change. We will flag up anything which we need like this but you can ignore other stuff until  we prod for it.

val

**Comment by ValWood** [comment]
It *might* be worth addressing this simultaneously
https://github.com/pombase/canto/issues/1277

**Comment by kimrutherford** [comment]
I've implemented this in the test Canto (I think).  Could you have a try?

Does it make sense to allow a genotype to have a deletion and a WT allele for the same gene?

**Comment by ValWood** [comment]
I think this is working fine, would be good if M. can also test


> Does it make sense to allow a genotype to have a deletion and a WT allele for the same gene ?

Yep, in a diploid you can have a WT copy and a mutated or knocked out copy. Jacky has a new paper where they do this for large gene set to see the effect of having only one copy  (i.e if the effect is dosage dependent, or dominant). Its a fairly common thing to do....

**Comment by kimrutherford** [comment]
> Yep, in a diploid you can have a WT copy and a mutated or knocked out copy.

What about for haploids?

**Comment by mah11** [comment]
Yes, it looks like it's working as expected on test now. Thanks!

**Comment by ValWood** [comment]
Oh my  session checking marathon can begin again tomorrow...once in live

**Comment by ValWood** [comment]
> What about for haploids?

I don't think so. But at present we only deal with diploids by adding "heterozygous/homozygous diploid" to the background. There is no way to exclude haploids at annotation time at present

until
https://github.com/pombase/canto/issues/976

**Comment by kimrutherford** [comment]
> Oh my session checking marathon can begin again tomorrow...once in live

Should be in the main Canto now.

**Comment by ValWood** [comment]
I think this can close?
