### ISSUE TITLE
problem editing symbols

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1245]
Jacky reported:

When I add a temperature e.g. 29°C I always get 29A°C- in fact the A  has a little ° above it. If I edit and deleted it goes but comes back again. 

==
Thanks Val I didn’t copy and paste but I have had these sorts of problems before with symbols.  I did try deleting it using the edit button at the end of the row and it went away however if I left the page and then went back it had reappeared.

==

I have been using Safari, I’ll  try Chrome to see if this makes any difference.

**Comment by ValWood** [comment]
> It seems to be Safari that is the problem.  I have just added 29°C using Chrome and it seems to be fine.

**Comment by ValWood** [comment]
or not...

JAcky
> Ignore my last but one email the dreaded symbol has return even withChrome

**Comment by ValWood** [comment]
@JackyVH

**Comment by kimrutherford** [comment]
Thanks for the report Jacky and sorry for the hassle.  I think I've fixed the problem.  The comments were being stored in the Canto database correctly but were being messed up on the way out.  So the good news is that the data is OK in the database and now the code is fixed your session looks fine.

We've seen oddness like this a few other times but I wasn't able to track it down.

**Comment by kimrutherford** [comment]
Looks like this is working now.
