### ISSUE TITLE
Canto mode to generate  large flat files

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1246]
Something to think about...

>> Down the line, if users start to do this, It might be nice to have some sort of rapid tab delimited file generating tool (is that what the thing Tim once wrote did for Array Express?)
>

 it might be nice to have a web based way to create these bigger tables
(or even a feature/ different mode of  canto where you could auto-magically apply an annotation to a gene list.....)

**Comment by kimrutherford** [comment]
Sorry, this confuses me.  Why would we need to create a table in Canto.  A table of what?

**Comment by ValWood** [comment]
It would be nice to have a quick way to generate a PHAF compliant file eventually.....
It's not even slightly urgent....and it might not be necessary.
Most biologists are probably totally happy to use excel.
In fact I'll close it, but we can keep it in mind.

**Comment by kimrutherford** [comment]
Like a bulk phenotype upload tool?  Sounds like a good idea but I'm not sure it should be part of Canto.

**Comment by ValWood** [comment]
I wasn't either....
