### ISSUE TITLE
Mr question mark

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1247]
some special character shenanigans?

![default](https://cloud.githubusercontent.com/assets/7359272/18472060/ff1b5072-79ac-11e6-99a3-bd96a74b3af0.jpg)

**Comment by kimrutherford** [comment]
Sorry about that!  It was caused by fixing #1245

I'm trying to work out how to fix this without breaking #1245 again.

**Comment by ValWood** [comment]
I thought it must be ;)

**Comment by kimrutherford** [comment]
I tracked it down.  Turns out that I was doing the right think but I hit a bug in one of the Perl libraries that Canto uses.  Upgrading to the latest version has fixed things.
