### ISSUE TITLE
lots of alleles not visible (list too short?)

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1250]
For cdc2 I couldn't see the allele cdc2-1w in the pull down immediately.

This is what I see upto "cdc-"

![many alleles not visible](https://cloud.githubusercontent.com/assets/7359272/18508993/727d6872-7a6e-11e6-9318-35e56ee11bf5.jpg)

I think it might be better fir users if there was some way to indicate that this was not all the alleles  
...more?

**Comment by ValWood** [comment]
The list is actually pretty short for some  genes....larger default? 20? 25?

**Comment by kimrutherford** [comment]
> some way to indicate that this was not all the alleles

Maybe, but for an autocomplete the idea is to reduce typing and errors by making suggestions - you keep typing until there are just a few options.  Having 20 or 25 suggestions might like a bit naff.  It's a quick change though if you'd like to try it.

**Comment by ValWood** [comment]
Hmm, the problem is that for allele naming they usually all begin with the same string
so cdc2-


I think I would like to see more if they match, and the list reduce once you get past the  dash (so it acts more like a filter)
Maybe 15 would help?

@Antonialock @mah11  thoughts?

**Comment by ValWood** [comment]
I think the reason I want this is that I often can't remember exactly how the allele was named when I search for it...

Its really not a big deal though so can close it it isn't bothering anyone.

**Comment by mah11** [comment]
I've got used to what it's doing now. I'm not sure it would help to see a lot more options for genes that have a lot of alleles.

The "more ..." suggestions sounds, er, more promising - the one potential problem I see is a short list being mistaken for everything in the db by infrequent users. "More ..." would give just enough of a hint that something might turn up if they keep typing.

**Comment by mah11** [comment]
> I think the reason I want this is that I often can't remember exactly how the allele was named when I search for it...

I suspect this would affect community users a lot less than any of us - they'll usually have the alleles they've used ready to hand.

**Comment by ValWood** [comment]
I think this was my main worry when I see the short list.

> I see is a short list being mistaken for everything in the db by infrequent users. "More ..." would give just enough of a hint that something might turn up if they keep typing.

Sometimes I am shocked myself when I don't see my allele in the list, and then I realise I just need to type more. I still think the default is *slightly* short,
BUT adding more will alleviate my immediate concerns.

So
 -[ ]  Add more....
and you can close this ticket.
