### ISSUE TITLE
Shorten "canto curator summary" legend

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1251]
This includes a text deletion that we talked about on a recent call (but I haven't spotted in any ticket), plus avoids repeating some other things I've suggested moving to the page blurb in #1234.

New legend:
Number of papers curated by professional and community curators, and total number of annotations created, per year. Any paper which is fully or partially curated by a community curator is classified as a community curated publication.

Note: The breakdown of annotations between professional and community curators is only accurate from 2013 onwards. Until the end of 2012, all annotations from a community curated paper were attributed to the community curator, even those added by a professional curator during the approval procedure.

**Comment by kimrutherford** [comment]
I've made that change.  I'm happy to make other changes or you can edit it directly:
  https://github.com/pombase/canto/blob/master/root/stats/annotation.mhtml

**Comment by ValWood** [comment]
MIdori, could you do this with your final suggestions, and then I'll have a read with fresh yes.

Kim, is the 'blob' configured to allow the addition of a text section at the top to describe the general page contents?
If not can you add a placeholder for this?

Thanks. I love this page...

**Comment by ValWood** [comment]
OK the other text changes required are in another ticket...

**Comment by kimrutherford** [comment]
> configured to allow the addition of a text section at the top to describe the general
> page contents?

Do you want the text between the PomBase log and the "Cumulative annotations by type and year" header?

**Comment by kimrutherford** [comment]
> addition of a text section at the top

I've added an empty DIV here:
https://github.com/pombase/canto/blob/master/root/stats/annotation.mhtml#L14

If you add what you need, I'll deploy it to test so we can check the formatting.

**Comment by mah11** [comment]
changed assignment because Kim did the change this ticket is about
