### ISSUE TITLE
stats page text

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1254]
Gathering outstanding things from other tickets (where they don't really belong), including #1234 and #1251 ...

stats page yaml:
https://github.com/pombase/canto/blob/master/root/stats/annotation.mhtml

- [x] legend for "Cumulative annotations by type and year" table

Val:
> Proposed legend for new table ... 
> Do we need to say anything else?

Midori:
We should say what's included in "other".

New table legend suggestion:
Cumulative totals of manually curated annotations over time. Includes annotations made by PomBase curators and community contributors; excludes interaction annotations imported from BioGRID and GO annotations based on computational methods (IEA evidence).  "Other" includes [what?] All annotation types are described in the PomBase documentation.

link "PomBase documentation" to http://www.pombase.org/documentation

- [x] Add text to top of page
- Text from #1234:

----
This page provides a set of metrics reflecting the current state of literature curation in PomBase.

In these metrics, an annotation is an assignment of a gene product to a term in an ontology, a genetic or physical interaction, or another curated statement about a gene or its product. For ontologies that support annotation extensions, each unique combination of an ontology term and an extension is counted as a separate annotation.

All of the Canto-specific annotation metrics exclude high-throughput datasets. 

Available reports [This ought to be a list of intra-page links using anchors; don't change graph/table labels for this ticket, but in some cases do use different text for the link]:

- All manual curation
- Canto curation
 - Curator summary
   - Publications
    - Participants [include this and the line above if a new table is added for #1213; otherwise just have the one "curator summary" link]
 - Curated and uncurated publications over time
 - Genes and annotations per publication over time
   - Annual
    - 5-year intervals
- [did I miss any? or are we waiting for any others?]

----

- Where to put it, from #1251 (removed from that ticket):

Val:
> Kim, is the 'blob' configured to allow the addition of a text section at the top to describe the general page contents?
> If not can you add a placeholder for this?

Kim:
> Do you want the text between the PomBase log and the "Cumulative annotations by type and year" header?
> 
> I've added an empty DIV here:
https://github.com/pombase/canto/blob/master/root/stats/annotation.mhtml#L14
> 
> If you add what you need, I'll deploy it to test so we can check the formatting.

**Comment by ValWood** [comment]
> Do you want the text between the PomBase log and the "Cumulative annotations by type and year" header?

I think so...

**Comment by ValWood** [comment]
I'm a bit confused, do I need to do anything else here?

**Comment by mah11** [comment]
> do I need to do anything else here?

Not now. I plan to do some edits tomorrow, and then you can have another look and see what you do and don't like.

**Comment by mah11** [comment]
I've added most of my text draft to the new div. (What I hope is) the list of items with links was a bit fiddly, so please make sure it looks OK and the links work.

To do:
- [ ] Kim release to test Canto
- [ ] Val & Antonia to review, spot errors, suggest further changes, etc.

**Comment by kimrutherford** [comment]
> Kim release to test Canto

Done!

**Comment by mah11** [comment]
Thanks. It does seem to be working as I intended with the links (phew; I wasn't entirely sure what I was doing), so let's see whether V&A like it.

**Comment by ValWood** [comment]
next up ;)

**Comment by ValWood** [comment]
Is it clear that  table "canto curator summary" is the date curated (not date published)?
I wonder if it will be obvious when this table shows 236/91 for 2016
and the graph below has 30/24

(I know that the next graph is explicit...curated vs. uncurated by *publication data*, but I think the table should be too (BY CURATION DATE), because its quite subtle!)

**Comment by ValWood** [comment]
Cumulative annotations by type and year

I know we say in the blurb at the beginning that canto excludes HTP, but I think again we could make it clearer  that this  graph includes  all experimental data (curated in canto and provided in PomBase HTP submission format). I can't think of a great way to  say this....

As this page is  aimed more at funders and reviewers in the long term, they might not quite get the differences  in numbers unless we really spell it out

I think this page is great now. We can ask Steve and Jurg if its all clear when we are done...

**Comment by mah11** [comment]
> Is it clear that table "canto curator summary" is the date curated (not date published)?

The old, longer version of the legend included this. I can add some of it back.

Watch this space - I'll copy legend drafts here so you can see them without making Kim re-do a release before we're all happy with the wordings.

**Comment by mah11** [comment]
oh yeah, at some point please also make sure the list of types I put for what's in "other" makes sense

**Comment by ValWood** [comment]
> oh yeah, at some point please also make sure the list of types I put for what's in "other" makes sense

Yep, although I believe orthology is excluded at present because that is 'different' @kimrutherford

**Comment by mah11** [comment]
Is it intended to include orthology? If so I'll leave the text as is rather than go back and forth while Kim futzes to get it working.

**Comment by ValWood** [comment]
I think it wont be in in the short term, and when it is it can maybe have its own column as its 7000 + for human and cerevisiae ...it might not be included at all in these stats...

**Comment by mah11** [comment]
OK, if it's going to be a while it's worth editing the text.

**Comment by kimrutherford** [comment]
> Yep, although I believe orthology is excluded at present because that is 'different'

Orthologs are stored in Chado in a similar way to interactions.  It wouldn't be hard to add them to the stats.

**Comment by mah11** [comment]
New drafts:

----
Cumulative annotations by type and year:
Cumulative totals of manually curated annotations over time. Totals include annotations made by PomBase curators and community contributors in Canto and via batch phenotype and modification data submission, but exclude interaction annotations imported from BioGRID and GO annotations based on computational methods (IEA evidence). "Other" includes taxon distribution, complementation, DNA and protein sequence features, genome organization, and miscellaneous data types. All annotation types are described in the PomBase documentation.

----
Canto curator summary:
Number of papers curated by professional and community curators, and total number of annotations created, per year. Any paper which is fully or partially curated by a community curator is classified as a community curated publication.

In this table, papers are counted towards the year in which they are curated (as opposed to publication date). Annotations are also individually date-stamped.

Note: The breakdown of annotations between professional and community curators is only accurate from 2013 onwards. Until the end of 2012, all annotations from a community curated paper were attributed to the community curator, even those added by a professional curator during the approval procedure.

----
I've committed these but it's easy enough to do further edits and a new commit.

**Comment by kimrutherford** [comment]
> I've committed these but it's easy enough to do further edits and a new commit.

I've re-release Canto.

**Comment by kimrutherford** [comment]
Is this done?

**Comment by ValWood** [comment]
Yes, any further text changes, new ticket.
