### ISSUE TITLE
stat page Break 'gene expression' out of 'other' 

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1255]
Cumulative annotations by type and year

 - [x] Break 'gene expression' out of 'other' (its quite a big component
(this *might* be in another ticket).

**Comment by mah11** [comment]
It's mentioned briefly in #1234. This ticket is good, because it's buried in the other one.

**Comment by ValWood** [comment]
https://curation.pombase.org/pombe/stats/annotation

currently the total numbers have dropped (other is now tiny), But gene expression isn't present as its own 'type'

(you might be working on this !)

**Comment by kimrutherford** [comment]
> (you might be working on this !)

I did swap to using the build from last night rather than the v61 release.  Maybe there is a problem with the latest load.  I'll swap it back until I can check.

**Comment by kimrutherford** [comment]
The numbers are back to normal again.  It's pointing at the v61 Chado now.

**Comment by kimrutherford** [comment]
I've made a separate issue about the low annotation counts: pombase/pombase-chado#581

**Comment by ValWood** [comment]
I think gene expression annotation might be totally missing:

val-woods-mbp:Quantitative_gene_expression_data val$ cat * |wc
   34449  409792 4514993

val-woods-mbp:pombe-embl val$ grep "gene expression" *.contig |wc
    3150   15737  301389


should be 37000+ (more than 'other')

**Comment by kimrutherford** [comment]
> Break 'gene expression' out of 'other' 

Done.  The numbers are quite small because most gene_ex annotation (33799 of them) don't have dates attached in Chado.  I think this is the bug: pombase/pombase-chado#583

**Comment by kimrutherford** [comment]
> I think gene expression annotation might be totally missing:

It's much better now.
