### ISSUE TITLE
Publications to add to Canto for triage

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1256]
These are publications that are in v60 Chado but not in Canto.

PMID:10087920
PMID:1062077
PMID:1062918
PMID:10704362
PMID:1077526
PMID:10781593
PMID:1095095
PMID:111071923
PMID:11179008
PMID:11313445
PMID:11483497
PMID:11560884
PMID:11759424
PMID:11790253
PMID:11886969
PMID:12077121
PMID:12163175
PMID:12183637
PMID:12220683
PMID:12472466
PMID:12497277
PMID:12522768
PMID:12562756
PMID:12627222
PMID:12684507
PMID:12725728
PMID:12764131
PMID:12939294
PMID:1296608
PMID:14517947
PMID:14576344
PMID:14637133
PMID:14645538
PMID:14680630
PMID:14729571
PMID:1497023
PMID:15007098
PMID:15047681
PMID:15106121
PMID:15126332
PMID:15175151
PMID:1518044
PMID:15215412
PMID:15350898
PMID:15372378
PMID:15615718
PMID:15647374
PMID:15719019
PMID:15821733
PMID:15866881
PMID:15882446
PMID:15889139
PMID:15929042
PMID:15965654
PMID:15988528
PMID:16162496
PMID:16231105
PMID:16393567
PMID:16537494
PMID:16754953
PMID:16887026
PMID:17112666
PMID:17287513
PMID:17409385
PMID:17497241
PMID:1762255
PMID:17735303
PMID:18022010
PMID:18042458
PMID:18257547
PMID:1836754
PMID:18381891
PMID:18408053
PMID:18426816
PMID:18461509
PMID:1853524
PMID:18591258
PMID:18775730
PMID:1884590
PMID:18976909
PMID:19029536
PMID:19206211
PMID:19342587
PMID:1938577
PMID:19818787
PMID:19888300
PMID:19966286
PMID:20301539
PMID:20301561
PMID:20347428
PMID:20360068
PMID:20427284
PMID:20456449
PMID:20462492
PMID:20692117
PMID:20801936
PMID:20949524
PMID:21062894
PMID:21138931
PMID:21149566
PMID:21549339
PMID:2171939
PMID:21723825
PMID:21728087
PMID:22187461
PMID:22264709
PMID:22307589
PMID:22308326
PMID:22442086
PMID:22561346
PMID:22608712
PMID:22754237
PMID:23099646
PMID:23169644
PMID:23266820
PMID:23293578
PMID:23399914
PMID:23459708
PMID:23536430
PMID:23859867
PMID:23934111
PMID:24001781
PMID:24124602
PMID:24131582
PMID:24204302
PMID:24450973
PMID:24607700
PMID:24793650
PMID:24868378
PMID:24938147
PMID:24952478
PMID:25057017
PMID:25186232
PMID:25194487
PMID:25262651
PMID:25351951
PMID:25483074
PMID:25776556
PMID:26310293
PMID:26486472
PMID:26522472
PMID:26801560
PMID:26812546
PMID:26968627
PMID:5533944
PMID:7780738
PMID:8265644
PMID:8389308
PMID:8826914
PMID:8937892
PMID:9161420
PMID:9256449
PMID:9323129
PMID:9585501
PMID:9740128

**Comment by kimrutherford** [comment]
All loaded now except for these two which aren't real Pubmed IDs:
PMID:111071923
PMID:12497277

And these two which are reviews which we can't handle because the XML from PubMed for reviews is quite different to the XML for articles:
PMID:20301539
PMID:20301561

**Comment by mah11** [comment]
Ah. I'll add a list of typos here. Will it be a pain to delete them? If so, leave 'em and I'll triage as wrong organism.

**Comment by kimrutherford** [comment]
> Will it be a pain to delete them?

No problem.

**Comment by mah11** [comment]
Great! These are the typos (all fixed at source except PMID:1497023 - waiting for UniProt to fix that one):

PMID:1062077
PMID:1062918
PMID:1077526
PMID:1095095
PMID:111071923
PMID:11313445
PMID:11759424
PMID:11886969
PMID:12764131
PMID:12939294
PMID:1296608
PMID:14637133
PMID:1497023
PMID:15047681
PMID:15647374
PMID:15965654
PMID:16393567
PMID:17287513
PMID:1762255
PMID:17735303
PMID:18022010
PMID:18257547
PMID:1836754
PMID:18426816
PMID:1853524
PMID:1884590
PMID:19206211
PMID:1938577
PMID:19818787
PMID:21138931
PMID:2171939
PMID:21728087
PMID:25483074
PMID:5533944
PMID:8265644
PMID:8389308
PMID:8826914
PMID:8937892
PMID:9161420

**Comment by ValWood** [comment]
> And these two which are reviews which we can't handle because the XML from PubMed for reviews is quite different to the XML for articles:

Thats weird, we usually load reviews no problem.... has something changed?

**Comment by kimrutherford** [comment]
> Thats weird, we usually load reviews no problem.... has something changed?

Most reviews in the Article XML format and only a few are in the Book XML format so most of them load OK.

> Great! These are the typos (all fixed at source except PMID:1497023 - waiting for UniProt
> to fix that one):

All deleted except for PMID:111071923 which didn't load the first time around because it's not a really PMID.

Instead of manually deleting the publications with SQL I've added a new option to the canto_delete.pl script do this as it comes up semi-regularly.
