### ISSUE TITLE
Improve colours of stats page charts

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1257]
Copied from pombase/pombase-chado#585:

When you look at this can you also review the colours (modification, gene expression and other are all a bit similar. There was a nice green colour before ;)

**Comment by kimrutherford** [comment]
It seems that the colours are assigned randomly each time the page is reloaded.  Which isn't great.  I'll see if that can be fixed.

**Comment by ValWood** [comment]
I thought there lots of colour changes!

**Comment by kimrutherford** [comment]
It's now fixed so the colours don't change each load but they colours aren't the best yet.

**Comment by ValWood** [comment]
They are OK!

**Comment by ValWood** [comment]
actually, in the table
Curated vs. uncurated by publication date
can we replace  swap the colours for  "uncurated" and "admin curated" so that the "uncoloured" is uncurated....its will show everything "done" as a strong colour block
