### ISSUE TITLE
Check the relation when handling subsets

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1258]
We use owltools to find all parents of each term so we can store the subsets information in the Canto database.  We currently don't record which relation owltools followed to find the parent.  This hasn't been a problem so far because all the subsets we've defined are "is_a" subsets.  In particular the "subset relation" column in the extension config files is always "is_a".

For #28 we need to know the relation that defines the subset (ie the relation that owltools follows to get to the parents).  We need to follow "never_in_taxon" relations and "only_in_taxon" relations are treat them separately.

So, we need to change the subset generation code here to store the relations:
  https://github.com/pombase/canto/blob/master/lib/Canto/Config/ExtensionProcess.pm#L74

And we need to change the code that uses the subsets to pay attention to relation and not assume everything is "is_a".

**Comment by kimrutherford** [comment]
I've spent today working on this.  I think I'm nearly there so it should be finished on Monday.  Once this is done the "never_in_taxon" restrictions should just be a matter of configuration.

Unfortunately I've broken the test Canto (temporarily).  I needed to test the changes by re-loading the ontologies.  I can't do it on my laptop because it doesn't have enough memory so I used the test Canto.  I'll fix that soon.

**Comment by ValWood** [comment]
Looking forward to this!

**Comment by kimrutherford** [comment]
I've fixed the last bug (that I know about at least).  I'm re-loading the ontologies in the test Canto now.  I added the "never_in_taxon NCBITaxon:4896" restriction for testing.

**Comment by ValWood** [comment]
I was going to find e.g.s, for testing but I can't find "never_in_taxon"
in the obo file here:

https://curation.pombase.org/dumps/latest_build/ontologies/

Should I look somewhere else?

**Comment by kimrutherford** [comment]
> I'm re-loading the ontologies in the test Canto now. 

That didn't work.  It seems to have ignored the taxon constraint I added.  I'll investigate. 

> I was going to find e.g.s, for testing but I can't find "never_in_taxon"
> in the obo file here:

The taxon restrictions are in go-plus.obo.  The load script gets that from GO SVN: go-svn/ontology/extensions/go-plus.obo

I've changed the load script to copy it to https://curation.pombase.org/dumps/latest_build/ontologies/ next time.

**Comment by kimrutherford** [comment]
> That didn't work. It seems to have ignored the taxon constraint I added. I'll investigate. 

The problem seems to be that Owltools isn't producing the transitive closure for the never_in_taxon relationship from the go-plus.obo file.  Oddly it seems to giving the closure I expect for the only_in_taxon relationship from the same file.  Tomorrow I'll install the latest Owltools and try that.  If that doesn't work I ask the Owltools team.

**Comment by kimrutherford** [comment]
I got the same result with the latest Owltools so I'll email Chris.

**Comment by kimrutherford** [comment]
This change was needed because the existing implementation was dodgy but now I've check back through my owltools emails I think it's a wrong approach.  I'll close this as I think it's done.  See #28 for more on owltools.
