### ISSUE TITLE
admin page reports 0 sessions with term requests

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1260]
The admin page (https://curation.pombase.org/pombe/track) claims "Sessions with term requests (0)", but sadly it ain't so. The "Summary of PomBase activity" emails (e.g. https://rt.sanger.ac.uk/Ticket/Display.html?id=548608) have included lists under "Sessions with outstanding term requests" for ages. A few spot checks indicate that the emails are right, and there are sessions with term requests that aren't being conveniently gathered into the relevant link on the admin page.

**Comment by kimrutherford** [comment]
This is one of those cases where I look at what I've done and wonder how it could ever have worked.  I changed the query in b85eb61ea5ab6e to fix the slow admin page.  But the query doesn't look right before then either.  Oh well, fixed now.
