### ISSUE TITLE
shorthand notation required for large block of AA

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1261]
follow on from example here
https://github.com/pombase/pombase-chado/issues/586

this one
58KRRKR62 substituted with NEHG
71KKRKK75 substituted with NEHG
OK, I think these could be done as KRRKR58NEHG and KKRKK71NEHG, if we're happy to use this syntax when 5 amino acids are replaced by 4.

I propose we have an additional syntax  to make this clearer for users
I'm doing a few for mto1 at the moment.
How about:
259-DNLRKEVFG->AAAAAAAA

**Comment by ValWood** [comment]
or just DNLRKEVFG-259-AAAAAAAA
some separators would be useful...

**Comment by mah11** [comment]
It might be nice for Canto & Chado to accept DNLRKEVFG-259-AAAAAAAA with or without the hyphens. I think that would be more convenient to enter than having to use a ->, and if the hyphens are allowed but optional, we wouldn't have to retrofit tons of existing allele descriptions.

**Comment by ValWood** [comment]
Agreed, it should be an option.

I was looking if there was anything more formal, but I don't think this would make so much sense to users.
http://varnomen.hgvs.org/recommendations/protein/

For now I am using
 DNLRKEVFG-259-AAAAAAAA and can fix if we decide to do it another way....

**Comment by ValWood** [comment]
moved to curation tracker
https://github.com/pombase/curation/issues/1130
