### ISSUE TITLE
infer "%" symbol when penetrance "edited as text"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1265]
If I add penetrance in the interface,  and I add a figure the "%" symbol is inferred.
If I "duplicate" and then  edit  as text (admin only) and change to a new number
the "%" is lost.

![infer](https://cloud.githubusercontent.com/assets/7359272/19022418/6615288e-88d0-11e6-9f9e-108deb65b4dc.jpg)

Is it possible to retain it (its much quicker than deleting and re-adding the existing one which is a few steps)

**Comment by kimrutherford** [comment]
> Is it possible to retain it (its much quicker than deleting and re-adding the existing one
> which is a few steps)

I'll look into this but for now don't worry about adding the "%" as the Chado loader should sort that out.  In Chado I thought we always stored without the "%" but it looks like there is inconsistency.  I've made a separate issue for that: https://github.com/pombase/pombase-chado/issues/588

**Comment by kimrutherford** [comment]
>  In Chado I thought we always stored without the "%" but it looks like there is inconsistency.

That's fixed now.

The edit as text function is very dumb at the moment and does no checking.  But the extensions and extension relations are checked when loaded into Chado so I don't think this is high priority.

**Comment by ValWood** [comment]
agreed

**Comment by ValWood** [comment]
Just to be sure. In this session I see "penetrance unknown"

but I can't see anything about this in the Canto logs?

![penetrance-unknown](https://cloud.githubusercontent.com/assets/7359272/20402748/e8f0d674-acf5-11e6-9d2e-4a507b433539.jpg)

**Comment by kimrutherford** [comment]
Sorry for the slow fix.  It was OK in Chado but the display was wrong.  It wasn't coping with penetrance or expressivity that had "<" or ">" or wasn't integer.
