### ISSUE TITLE
lost admin link to "comunity *curated* publications

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1266]
I think this link disappeared with the recent change to 
"community *curatable* publications"

I think it would be useful to keep this link here....

**Comment by ValWood** [comment]
![community curated publicationd](https://cloud.githubusercontent.com/assets/7359272/19023332/4cc3b22e-88e4-11e6-9140-53be82fa060a.jpg)

**Comment by kimrutherford** [comment]
As far as I can tell we never had a "community curated publications" report.  I'll add one.

**Comment by kimrutherford** [comment]
Should "curated" include "NEEDS_APPROVAL" and "APPROVAL_IN_PROGRESS" or just the "APPROVED" sessions?

**Comment by kimrutherford** [comment]
I've added two new reports on the admin page.  Both are restricted to those publications that have a session in the state "NEEDS_APPROVAL", "APPROVAL_IN_PROGRESS" or. "APPROVED"

![screenshot 2016-10-03 18 25 51](https://cloud.githubusercontent.com/assets/90474/19028286/d96e8976-8996-11e6-8f91-71d9f9a5ed2e.png)

**Comment by ValWood** [comment]
fantastic!

That's actually pretty amazing 416/1056 possible (sent out)....

**Comment by ValWood** [comment]
We should probably put that on the stats page!

**Comment by kimrutherford** [comment]
> We should probably put that on the stats page!

Would that be redundant because of the table in the "Canto curator summary" section of the stats page?

**Comment by ValWood** [comment]
Not really, because there is no way of knowing from the stats page how many were actually sent out, and therefore what the response rate is.... we can only see what is done, not what could be done. 
People who ask about community curation this is generally one of the first questions, "What is the response rate?" Right now we are at 40% I reckon I  we can get it to 70%..... I  know already who will *never* do it until it becomes mandatory.....

**Comment by kimrutherford** [comment]
I think I'm getting it now - it's the "1056" that needs adding to the stats page?

Currently the stats page says there are 366 community curated publications.  The admin page says 424 because it includes the "NEEDS_APPROVAL" and "APPROVAL_IN_PROGRESS" sessions.  Is that OK?

**Comment by ValWood** [comment]
Yep  but I think we should be explicit.

Maybe have a statement:
Current Community Curation response rate 40% (424/1056)

Its OK (good) to include those in approval too...

**Comment by kimrutherford** [comment]
I've added a new section "Community annotation response rate".  Let me know any changes you'd like.

**Comment by ValWood** [comment]
Thanks, we can make any text tweaks later.
