### ISSUE TITLE
Add by Pubmed on admin page broken

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1267]
I thought that I submitted this already, apparently not....
https://curation.pombase.org/pombe/tools/pubmed_id_start

**Comment by kimrutherford** [comment]
It got removed in https://github.com/pombase/canto/issues/1166 because I thought it wasn't used any more.

Would it be OK to get rid of that link and go to the front page to add a paper by ID?

**Comment by ValWood** [comment]
Yes thats fine. I was using it to locate papers, but there are other ways to do it...its habit. Also within admin it is now quicker to find a paper by PMID from the linked lists. I'll retrain myself and let you  know if we need it later. 
so remove for now.

**Comment by kimrutherford** [comment]
Great.  I've removed the link.
