### ISSUE TITLE
process terms not loading in specific session

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1268]
This appear to be  a session specific bug?
I spotted it last night, but I have not seen it in any other sessions

![server error](https://cloud.githubusercontent.com/assets/7359272/19029573/56d096b4-893f-11e6-877d-7bfa84b9594f.jpg)

**Comment by ValWood** [comment]
session was
16267d2a11f0cdbf

**Comment by kimrutherford** [comment]
The error is because there is an annotation to GO:0070885 but that isn't in the pombe-only subset generated by owltools.  Do you think that is an ontology problem or an owltools problem?

I'll check to see if there are any other missing IDs now.  We can switch back to the full GO OBO file is there is a big problem.

It's a old bug that Canto fails badly if a term goes missing.

**Comment by kimrutherford** [comment]
> The error is because there is an annotation to GO:0070885 but that isn't in the pombe-only subset 

I had a quick look.  That term has two is_a parents.  One is in the pombe-only subset and the other (GO:0070884 - "regulation of calcineurin-NFAT signaling cascade") is missing.  There is no taxon restriction on GO:0070884 and its is_a parent (GO:0050848 - "regulation of calcium-mediated signaling") *is* in the pombe-only subset.

I followed a few other relationships and got to GO:0033173 - "calcineurin-NFAT signaling cascade" which which is missing from the pombe-only subset.  But it doesn't have a taxon restriction and both of its is_a parents (GO:0019722 - "calcium-mediated signaling" and GO:0048016 - "inositol phosphate-mediated signaling") *are* in the pombe subset.  I gave up at that point.

**Comment by ValWood** [comment]
The annotation looks to be incorrect to me.

Pombe does not have NFAT, as far as I'm aware, so I'm sure it doesn't have 
NFAT signalling......
I'll transfer this to the curation tracker. 

I suspect we will need to check a few annotations and taxon contraints. Is it possible to get a list of any annotation violations?

**Comment by kimrutherford** [comment]
> Is it possible to get a list of any annotation violations

Yep.  That's what I meant by:

> I'll check to see if there are any other missing IDs now.

I haven't done it yet.  I'll make a curation ticket once I have a list.

> Pombe does not have NFAT, as far as I'm aware

I guess that's why it's not in the pombe-only subset.  I just can't see how that's configured in GO.

**Comment by ValWood** [comment]
It has "only in metazoa"
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0033173#info=3

**Comment by kimrutherford** [comment]
> It has "only in metazoa"

Interesting.  There must be some complicated owltools thing going on to filter that term out.

**Comment by ValWood** [comment]
another session
9e6658619f3b13c3/ro
I guess we need to see them to fix them (I'm not sure , but I think that no annotations are shown for the aspect which has violations)

**Comment by fypoadmin** [comment]
I've fixed the display code to cope better in this situation.  You now see this:

![screenshot 2016-10-12 13 14 00](https://cloud.githubusercontent.com/assets/13194034/19293148/05bac4de-907e-11e6-92b9-d48b30238e03.png)

**Comment by ValWood** [comment]
nice, I'll process these sessions back thorough approval today.

What is the normal route to identify suck sessions ? 
Can they be reported in the log file (I don't think they are right now, this is new from the taxon restrictions)

**Comment by kimrutherford** [comment]
> What is the normal route to identify suck sessions ? 

There is no easy way to do this add the moment.  I have a Perl snippet that can query for unknown term IDs.  Here's the current list:

c57f22a897472fa7 - GO:0009008
16267d2a11f0cdbf - GO:0070885
16267d2a11f0cdbf - GO:0070885
16267d2a11f0cdbf - GO:0033173
80b382d361649949 - GO:0000918
9e6658619f3b13c3 - GO:0035082
9e6658619f3b13c3 - GO:0035082

> Can they be reported in the log file

I think they would be reported if you missed them and they ended up in an APPROVED session.  They would show up in the next load.

**Comment by ValWood** [comment]
suck sessions was a typo ;) , lit should have been *such* sessions, I guess it could have been worse...

**Comment by kimrutherford** [comment]
> suck sessions was a typo

I guessed "stuck sessions".

I think this is done now.
