### ISSUE TITLE
some "penetrance" annotations display as "UNKNOWN"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1272]
I found an example session, 

![msd1](https://cloud.githubusercontent.com/assets/7359272/19434294/7d49d792-945c-11e6-825d-38c0ec3cb08b.jpg)

**Comment by ValWood** [comment]
Actually its fine now, its only a problem in "existing single alleles" section, fixed in current view

**Comment by kimrutherford** [comment]
I think this was a problem I fixed this last week.
