### ISSUE TITLE
new MF extension config not available

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1273]
On Friday, I added this line to the GO_MF_A_E_config file:

```
GO:0101005      is_a    has_substrate   ProteinID       modifies         0,1     user
```

But Canto still isn't offering me a "modifies" option in the extension pop-up for annotations to GO:0101005 or its is_a child GO:0061578 (attempting to edit existing annotations in d91d901cb0a83596).

I lazily copied/edited a working line, and nothing leaps out as obviously wrong with the config file. Whassup?

(I've since changed "modifies" to "deubiquitinates" but that's minor.)

**Comment by mah11** [comment]
I've also just noticed that GO cellular component should find SO:0002141 as an extension for GO:0000790, but doesn't.

SO:0002141 is fairly new (added mid-Sept.), and is_a SO:0000296, so this config line should cover it:

    GO:0000790      is_a    coincident_with GeneID|SO:0000296|SO:0001272|SO:0001914|SO:0002021|SO:0002020|SO:0000141|SO:0000186|SO:0000101|SO:0000286|SO:0001263|SO:0001659|SO:0001496|SO:0000628   found at genomic region         0,1     user

(I'll move this to a new ticket if it turns out not to be the same problem.)

**Comment by kimrutherford** [comment]
> On Friday, I added this line to the GO_MF_A_E_config file:

That seems OK now, with "deubiquitinates" as the text.  I don't know why it wasn't showing earlier.

> I've also just noticed that GO cellular component should find SO:0002141 as an extension
> for GO:0000790, but doesn't.

It looks like SO moved from SVN to Git/GitHub and I wasn't paying attention.  Canto has been using SVN as is way out of date.  I'm updating the test Canto now to check there are no problems caused by the updated SO.  If that works, I'll update the main Canto.

**Comment by kimrutherford** [comment]
> If that works, I'll update the main Canto.

SO:0002141 is now available for a coincident_with extension for CC annotations.

**Comment by ValWood** [comment]
Thanks. I sent an e-mail about not seeing my F involved in P link. This resolves this one too.
