### ISSUE TITLE
description box not available for disruption

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1274]
Older tickets (#681, #1025) imply that there should be a box to provide an optional description for alleles of type 'disruption'. But now I don't see such a field - and I want to use it in 1fecc0470053ec75, where there's a disruption that specifies positions (and is currently type 'other').

**Comment by kimrutherford** [comment]
Just to check: is description optional rather than required for disruption alleles?

**Comment by kimrutherford** [comment]
I've added an optional description field for disruption alleles.  I've made the change only in the test Canto for now.  Could you let me know if it's working as you'd like?

**Comment by mah11** [comment]
Yep, optional is correct, and it seems to be working fine in test Canto.
