### ISSUE TITLE
new allele types for Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1275]
We have been through the log file of annotation type "other"
and to begin to reduce these we would like to add some new "allele types"  as follows:
- [ ]  amino acid insertion 
  e.g.  858-MKGYP 
- Kim will  add "aa" behind scenes
- for our internal documentation, if the insertion is before the first amino acid we will used  put 0 

- [ ]  nucleotide insertion 
  e.g.  132-AATTT 
- Kim  will add nt behind scenes)

- [ ] Various allele combinations
  amino acid insertion and amino acid change  858-MKGYP,F124D
  amino acid insertion and deletion   858-MKGYP,100-200
  partial deletion and amino acid change   100-200,F124D

- [ ] A the list is growing quite long, we thought we could  reduce by merge

mutation of single amino acid and mutation of mutiple amino acid into  "amino acid substitution(s)"

and a similar merge for nucleotide substitution(s)

**Comment by ValWood** [comment]
first select mutation type (AA or NT)

Then
residues changed
residues deleted
residues inserted

**Comment by ValWood** [comment]
discussion about "types"

purpose is to get users to add descriptions in the  correct syntax.

**Comment by mah11** [comment]
Summary of discussion on call:

Chado
- leave as is, i.e. distinguish only amino acid vs. nucleotide changes; all the finer-grained classification is just for hand-holding in Canto 

Canto interface
- new allele description entry:
 - [ ] add the types as in the original ticket summary
 - [ ] merge single aa and multiple aa ditto
 - [ ] merge single nt and multiple nt ditto
- search and autocomplete for existing alleles
 - [ ] change the allele type display to just show amino acid vs. nucleotide

The new and existing allele type options thus become inconsistent, but we decided we could live with that to save the effort of either putting the more specific types into Chado or generating the more specific display on the fly in Canto.

Tangent: at some point in the future we may occasionally need to change the description for an existing allele. We decided to have that as an admin-only option whenever it may get added - we won't need the allele-type hand-holding, and everyone else can pester us via the helpdesk if they notice an allele description that needs a fix.

**Comment by kimrutherford** [comment]
This change is ready to go but I'm going to deploy over the weekend.  The allele autocomplete results (which come from Chado) are going to be a little bit inconsistent until the changes in Canto have gone through to Chado.  It's not going to be wrong just a bit odd.  So I'll do the change on Saturday and with any luck it will all be fine on Monday.  (It also gives me a day to fix things if the Chado load has problems.)

I have one thing still to do, which is out in the help text for the merged allele types.  Could someone suggest new text especially for the NT help.  This is what we have at the moment:

Single AA:
eg. K132A

Multi AA:
eg. K132A,K144A

Single NT:
eg. A25G, OR A-25G (for promoter region)

Multi NT:
eg. A25G,T40G

**Comment by kimrutherford** [comment]
Sorry, one other thing.

Here you say "change":

    amino acid insertion and amino acid change 858-MKGYP,F124D

and here you say "substitution":

    amino acid substitution(s)

should we change one of those?

**Comment by kimrutherford** [comment]
Sorry another question now that I've double checked things.  Under "Various allele combinations" you only list amino acid combinations.  Do you need nucleotide combinations too?

**Comment by kimrutherford** [comment]
What order would you like for the drop-down?  Here's the list:

wild type
deletion
disruption
unknown
amino acid insertion
amino acid substitution(s)
amino acid insertion and amino acid change
amino acid insertion and deletion
partial deletion and amino acid change
partial deletion, amino acid
nucleotide insertion
nucleotide substitution(s)
partial deletion, nucleotide
nonsense mutation
other

**Comment by kimrutherford** [comment]
The allele type list is updated in the test Canto.

**Comment by ValWood** [comment]
> Under "Various allele combinations" you only list amino acid combinations.  Do you need nucleotide combinations too?

we only need amin acid, if we do have any nucleotide we can do with "other" but these complicated ones are usually reported as AA changes


> amino acid insertion and amino acid change

I think
amino acid insertion and substitution
is better?

**Comment by ValWood** [comment]
what do we need to do here?
discuss thurs, or can we finish this before?

**Comment by Antonialock** [comment]
point mutation(s) instead of substitution(s)? I think that is more commonly used?

**Comment by ValWood** [comment]
Hmm, I don't know...I would use point mutation more for only a single  change, and substitution is a little shorter but just as clear in meaning?

**Comment by Antonialock** [comment]
ok, I'm not fussed, I just thought it might be more commonly used

**Comment by ValWood** [comment]
@mah11 ?

**Comment by mah11** [comment]
my only preference is for internal consistency

**Comment by kimrutherford** [comment]
> This change is ready to go but I'm going to deploy over the weekend.

Whoops, forgot.  For three months.  Sorry.

I've made a note in my calendar to do the update this weekend.

**Comment by kimrutherford** [comment]
I've fixed the allele types in the main Canto database and change the configuration.

The new Canto data will be in tonight's Chado load.  Until that load finishes, alleles from existing genotypes in  Chado may look a bit odd in Canto.  In particular the allele types won't match the possible types in Canto.  It will all be OK in the morning.

**Comment by ValWood** [comment]
looks good.  will open a new ticket if we want  to change the order ;)
