### ISSUE TITLE
Additional syntax for amino acid substitutions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1276]
Follow on from:
https://github.com/pombase/curation/issues/1130

 To make all allele descriptions  consistent we would like to also allow this format for
amino acid substitutions
DNLRKEVFG-259-AAAAAAAA 

because sometimes of substitutions get a bit long to describe with the current syntax, but 
58KRRKR62 substituted with NEHG which  aren't very parseable.

**Comment by kimrutherford** [comment]
There are no restrictions in Canto on the format of amino acid substitutions.

The only issue is that amino acid substitutions always have "aa" added to the start.  So your example will be displayed as:

    aaDNLRKEVFG-259-AAAAAAAA
