### ISSUE TITLE
log oddity

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1280]
phenotypes_from_PMID_27558664_phaf.txt is repeated from several days

![screen shot 2016-10-27 at 16 13 34](https://cloud.githubusercontent.com/assets/12727506/19773156/640cf226-9c60-11e6-98d1-e995189a4fb0.png)

**Comment by kimrutherford** [comment]
Thanks.  I've renamed the PMID_27558664 PHAF file to end in .tsv which should fix it.

The loading working fine with ".txt" but we end up with extra log file.
