### ISSUE TITLE
order of extensions in Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1285]
This is very minor, but it would be good if these could be ordered

phosphorylates,
involved in biological process
has function during,

In fact I think we have a file somewhere documenting the order in which the extensions should appear on the gene pages....this will be the same order...

@mah11 do you know where we documented this?

https://cloud.githubusercontent.com/assets/7359272/20233745/cf13ff04-a86a-11e6-8f3b-a40e26254be6.jpg

**Comment by mah11** [comment]
I don't know of this being _documented_ anywhere. The closest thing I know of is the parallel request for the gene page display, in https://github.com/pombase/website/issues/64

**Comment by ValWood** [comment]
The details will be in the jira ticket where the order on the gene page was requested...will try to track it down later.

**Comment by ValWood** [comment]
closing, duplicate of
https://github.com/pombase/canto/issues/2766
