### ISSUE TITLE
Canto can't read genotypes - server problem?

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1288]
When I try to look at genotypes (i.e. go to a genotype management page), I get a red pop-up error message saying "couldn't read the genotype list from the server".

The page then also "thinks" there are no genotypes in the session. If I try to add one, it gets through all of the steps except "Finish"; instead of saving, it coughs up a huge red error box with a lot of HTML-ish guff following "Accessing server failed".

The "can't read from server" message appears in review mode and approval mode as well as curation-in-progress, and I suspect it affects all sessions.

Example sessions: 8c5b305baa755d41, 817e75f5ee938916

**Comment by kimrutherford** [comment]
Sorry about that.  The oliver0 file system partition that Canto is on filled up.  The Canto data is on a small partition for historical reasons.  I'll move it all to the much larger partition one night this week.  There will be a Canto downtime of a minute or two so I'll switch when Canto is not in use.
