### ISSUE TITLE
Canto  test error

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1289]
https://curation.pombase.org/test/curs/aff89d3be4cec206/ro
when I try to access a session

DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=pombase-build-2016-09-06-v1;host=oliver0','kmr44',...) failed: FATAL: database "pombase-build-2016-09-06-v1" does not exist at /usr/local/perl-5.22.0/lib/site_perl/5.24.0/DBIx/Class/Storage/DBI.pm line 1517. Stack: [/usr/local/perl-5.22.0/lib/5.24.0/Carp.pm:167] [/usr/local/perl-5.22.0/lib/site_perl/5.24.0/x86_64-linux/DBI.pm:697] [/usr/local/perl-5.22.0/lib/site_perl/5.24.0/x86_64-linux/DBI.pm:753] [/usr/local/perl-5.22.0/lib/site_perl/5.24.0/DBIx/Class/Storage/DBI.pm:1517] [/usr/local/perl-5.22.0/lib/site_perl/5.24.0/Try/Tiny.pm:103] [/usr/local/perl-5.22.0/lib/site_perl/5.24.0/DBIx/Class/Storage/DBI.pm:1559] [/usr/local/perl-5.22.0/lib/site_perl/5.24.0/DBIx/Class/Storage/DBI.pm:1048] [/usr/local/perl-5.22.0/lib/site_perl/5.24.0/DBIx/Class/Storage/DBI.pm:962] [lib/Canto/DB.pm:138] [lib/Canto/DB.pm:84] [lib/Canto/Chado/ChadoLookup.pm:58] [reader Canto::Chado::GeneLookup::schema (defined at lib/Canto/Chado/ChadoLookup.pm line 48):8] [lib/Canto/Role/ChadoLikeGeneLookup.pm:198] [lib/Canto/Role/GeneLookupCache.pm:78] [/usr/local/perl-5.22.0/lib/site_perl/5.24.0/x86_64-linux/Class/MOP/Method/Wrapped.pm:164] [/usr/local/perl-5.22.0/lib/site_perl/5.24.0/x86_64-linux/Class/MOP/Method/Wrapped.pm:95] [lib/Canto/Curs/GeneProxy.pm:94] [reader Canto::Curs::GeneProxy::gene_data (defined at lib/Canto/Curs/GeneProxy.pm line 64):8] [lib/Canto/Curs/GeneProxy.pm:123] [reader Canto::Curs::GeneProxy::primary_name (defined at lib/Canto/Curs/GeneProxy.pm line 56):8] [/data/pombase/pomcur/apps/test/root/curs/gene_list.mhtml:79] [/data/pombase/pomcur/apps/test/root/curs/front.mhtml:17] [/data/pombase/pomcur/apps/test/root/curs/autohandler:30] [/data/pombase/pomcur/apps/test/root/curs/page_template.mhtml:35] at lib/Canto/DB.pm line 138

**Comment by kimrutherford** [comment]
Sorry about that.  When I was tidying up the disk space on oliver0 yesterday I deleted a bunch of old test loads of the Chado database.  I forgot to check what the test Canto was using.  It's now pointing at PomBase Chado v61.
