### ISSUE TITLE
ORCID login fails (test)

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1290]
I can't log in to test Canto - the "Admin log in" link takes me to the ORCID login page, but when I put in my ORCID and password, I get the message "Login failed - no such user". I have now put my ORCID in on live pombe Canto, but I don't think I got round to test - and now I can't check, because I can't log in there.

I know the ORCID password is correct because it works when I go directly to orcid.org and use their "sign in" button.

presumably related to #1187

**Comment by kimrutherford** [comment]
> and now I can't check, because I can't log in there

:-)

I've added your ORCID to the test DB.  Could you try again to log in?

**Comment by mah11** [comment]
Sorry, I just tried and got the same "no such user" message from test. Everything seem to be working for logging in to live pombe, or into ORCID directly at orcid.org.

**Comment by ValWood** [comment]
I  found a  request to make ORCID  log in landing page clearer and added a comment to it.

http://support.orcid.org/forums/175591-orcid-ideas-forum/suggestions/7298655-oauth-authentication-screen-sign-in-not-apparent

However I noticed at the bottom a comment about this landing page being configurable, so that might be an option?

**Comment by mah11** [comment]
> I found a request ...

That's interesting in its own right, but it looks totally unrelated to this bug ...

**Comment by kimrutherford** [comment]
> I've added your ORCID to the test DB. Could you try again to log in?

I checked and I hadn't actually added your ORCID to the test DB.  Sorry.  I've added your ID now.  Could you try again to login as admin?

**Comment by mah11** [comment]
Oops. That works now. Thanks!

Unless anyone else has a problem, this can close.
