### ISSUE TITLE
bug, duplicate term and trailing character

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1291]
I noticed a couple of odd things last night in Canto, they may or may not be related

1. cytoplasmic region is duplicated in the drill down. I have never seen this before...

![odd](https://cloud.githubusercontent.com/assets/7359272/20712709/3484396e-b63d-11e6-916a-44604aaf6116.jpg)

**Comment by ValWood** [comment]
and one of the terms cytoplasmic region seems
![odd2](https://cloud.githubusercontent.com/assets/7359272/20712756/67f6b150-b63d-11e6-9f76-83b4cf6821f9.jpg)
 to have a trailing space on the def in canto

**Comment by ValWood** [comment]
Hmm, I guess its most likely a GO issue  although there only seemsed to be a single term in GO

@mah11  could you check this ?

**Comment by mah11** [comment]
GO does have a typo at the end of the GO:0099568 def (not sure why you needed me to check that ...).

I don't see the duplication in the autocomplete options.

**Comment by ValWood** [comment]
That's odd I could not see the trailing space in Quickgo. I

but if the duplication has gone we can close this....
