### ISSUE TITLE
How long should we expect extension config updates to take?

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1297]
The last few times we've edited the annotation extension configuration files, the changes have taken several days to become available in Canto. Is that expected?

For example, I added a line for FYPO:0005800 to the FYPO config file on Thursday Dec. 1st, but the option (assayed protein) still isn't visible today (5th). Closed tickets #1273, #1282 and #1294 all also refer to config changes not taking effect as quickly as we thought they would.

**Comment by mah11** [comment]
Update: "assayed protein" is now available for FYPO:0005800. I didn't check yesterday, but it's taken 5 or 6 days to filter through.

It would be immensely convenient if it could happen as quickly/frequently as ontology updates, or at least in 2 or 3 days instead of almost a week. Is that realistic?

**Comment by ValWood** [comment]
So just to confirm.
If I have a phenotype where I can capture both  target, and the enzyme 

which qualifiers 2 do I use?

note to self fix PMID:27655872

**Comment by kimrutherford** [comment]
> Update: "assayed protein" is now available for FYPO:0005800. I didn't check yesterday, but
> it's taken 5 or 6 days to filter through.

The extension config is reloaded whenever the ontologies are reloading - it's the same process.  The ontology reload happens nightly.  I've checked the logs and there aren't any errors I can see in the last week so I don't know what the hold up was.  Perhaps if you could let me know next time you update a config and I'll keep an eye on the process and run it locally to check it?

**Comment by mah11** [comment]
Will do. I may even sneak something (maybe just a display text change, so no harm gets done) in just for testing ...

**Comment by mah11** [comment]
OK, on Monday I made a text change to test this (but forgot to ping you here). The change wasn't visible yesterday (Tuesday) but is now (Wednesday). So 2 days, which is a day longer than new ontology terms take, but shorter than the last few extension config changes I've done.

Now (2016-12-14 ~17:17 GMT) I'm going to revert the test change, so we can both see how long it takes to percolate through.

**Comment by kimrutherford** [comment]
I've had another look at the load script and the log file and I can't work this out.  The script updates the Canto copy of pombe-embl as one of its first steps and that seems to be working.  The script runs at 4:30am.

Please let me know if has worked this morning.  If not I'll see if the ontology structure is being cached incorrectly.  It's not supposed to be cached at all in order that it's always up to date for the user.

**Comment by mah11** [comment]
Yesterday afternoon's change hasn't reached live Canto as of just now.

Is the problem with the ontology structure, though? The config edits I've done for testing this week have only changed the display text for Canto's extension-adding interface, not which terms get the extension type.

**Comment by kimrutherford** [comment]
> Is the problem with the ontology structure, though? The config edits I've done for testing
> this week have only changed the display text for Canto's extension-adding interface, not
> which terms get the extension type.

Thanks for persisting.  I think that's it and I feel silly for not thinking of it.  When the ontologies are reloaded the loader checks the current extension config and runs owltools to get the closure for the extension terms.  But Canto still uses the whatever display text was in the config file when it was last restarted.

So I think we can test this by checking Canto before and after a restart.

If that's it, then the solution is to do a quick restart of Canto straight after reloading the ontologies each night.  That would happen at 5am-ish and shouldn't interrupt service.

**Comment by mah11** [comment]
OK. Let me know when to check again to confirm that restarting correlates as you now expect. (I don't see the update yet, so I'm assuming you haven't restarted Canto since your last comment.)

**Comment by kimrutherford** [comment]
I've just restarted the main Canto.

**Comment by mah11** [comment]
hey, it worked! hooray!

**Comment by kimrutherford** [comment]
Great.  I'll modify the load script to restart Canto when it's done.

**Comment by mah11** [comment]
if the load script edit is done, this can be closed

**Comment by ValWood** [comment]
I think this can be closed?
@kimrutherford holler if not

**Comment by kimrutherford** [comment]
Still not done.  I got distracted.

**Comment by ValWood** [comment]
hi @kimrutherford  is this done?

**Comment by kimrutherford** [comment]
Nope, still not done.  I'll try to get it sorted once we've finished moving to the new server.

**Comment by kimrutherford** [comment]
> Great. I'll modify the load script to restart Canto when it's done

Sorry this took over a year.  It's done now on the new server.
