### ISSUE TITLE
ORCID text

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1298]
Do we need to add some short text at this point explaining  briefly how we plan to use ORCiDs

![self select](https://user-images.githubusercontent.com/7359272/38992629-38f686e8-43d9-11e8-8c10-d33470e19745.jpg)

**Comment by ValWood** [comment]
I just added my Orcid , but it doesn't show up in the  table under people view?

**Comment by kimrutherford** [comment]
Where did you add your ORCID?  Was it when starting a new session?

**Comment by ValWood** [comment]
Oh no it was in an existing session. I didn't want to take any more right now. I have  84 in my in progress sessions folder and I don't think that is all of them.

I'll find a new one and try again.

**Comment by ValWood** [comment]
I took a new session, added ORCID, it is now in the file.

However, wen I took an additional session I am prompted for it again (it also still autocompletes with my e-mail).
This will probably make people feel obliged to add/confirm it each time which means you need to go look it up which could be a tad annoying ;)

Although I guess you should be able to  supply ORCID to log in?

Also, I think we are over writing names as blanks if people don't confirm them. For example TAkashi's "known as " name was blank (and quite a lot of others which I am sure I have filled in previously).

A few duplicate accounts are creeping in again....have made a note (not urgent)

**Comment by ValWood** [comment]
I'm deleting stuff unrelated to the text prompt and moving to 
https://github.com/pombase/canto/issues/1409

**Comment by ValWood** [comment]
I also notice that some people (presumably who don't have an ORCID) have added some random text! so perhaps the prompt should include a link about where/how to get/find their ORCID

**Comment by ValWood** [comment]
@mah11  do you think we should have some text about why/what for ORCIDs?
If so, could you draft something short and pithy ?

**Comment by mah11** [comment]
What do you want to convey with this text?

- How to get an ORCID?
- Why we recommend it?
- What we do with ORCIDs (now and/or in future)?
- All of the above?

What an ORCID is, how to get one, and why they're good in a broader context are explained at the ORCID site, which we already link to. So maybe we just need a text snippet to make people more likely to follow the existing link?

I don't think it makes a huge amount of sense to put a lengthy explanation of our plans on the confirm-your-details page, but we could write something for the documentation and then link to it from the confirmation page.

Come to think of it, maybe a link to a doc page could do for both - maybe with "what's this?" as link text.

**Comment by ValWood** [comment]
I think it came up in a discussion that we should let users know  why we were insisting on ORCIDs (which at the time was for attribution). I don't think we will exactly do the attribution via ORCID now , we since discussed Open Rif?, but did not make any progress...(although ORCID will be the way we uniquely identify someone)

I think your idea for a doc page is best  and we can add  a snippet that we plan in the future to use ORICDs as a way to uniquely identify community contributors, and  enable them to 
link to their curation contributions for "grants data-dissemination requirements"

**Comment by mah11** [comment]
I added a little page - you can see the text in github:

https://github.com/pombase/canto/blob/master/root/docs/orcid_canto.mhtml

I'll leave it to Kim to add a link to it (I don't know what to edit, and I'm not sure I'd trust myself not to bollix it up if I did know where to look).

**Comment by ValWood** [comment]
Perfect ;)

**Comment by ValWood** [comment]
@kimrutherford This is quick. We just need a link to the text about how we plan to use ORCIDs.

**Comment by ValWood** [comment]
Very quick, add a link to the documentation

**Comment by kimrutherford** [comment]
I've added the link.  Let me know if you'd like me to change to link text or link position.

![orcid-help-1](https://user-images.githubusercontent.com/90474/52546545-27ecaa80-2e25-11e9-9ee3-2e68f563dede.png)

**Comment by ValWood** [comment]
all good...
