### ISSUE TITLE
only allow one penetrance term per annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1299]
At lease except in admin where can be pipe separated.

At present if you duplicate you can add additional penetrance. JAcky mentioned that she may have sometimes not deleted the original one (although I have not seen this)

Maybe add a log check too...

**Comment by mah11** [comment]
I did a bit of testing, and found that it only allows a second penetrance entry upon duplicate/edit if the original penetrance was one of the qualitative options (low/medium/high). It correctly disallows multiple penetrance extensions if there's one quantitative (%) entry.

This reminds me of previous bugs in the extension cardinality system - see #1069 & #1115.

(The config file is fine.)

**Comment by ValWood** [comment]
Thank you. I thought it worked at some times!

**Comment by ValWood** [comment]
Is this quick?

**Comment by kimrutherford** [comment]
> Is this quick?

An hour or two I think.

**Comment by kimrutherford** [comment]
I think I've fixed this now.  Thanks for narrowing it down Midori.
