### ISSUE TITLE
gene names

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1300]
I noticed that gene names added last week have not propagated to canto yet....

**Comment by kimrutherford** [comment]
Canto is now pointing at the most recent successful Chado load.  Could you check that the genes are there?

**Comment by ValWood** [comment]
a search for pro2 *finds* the correct gene, but displays it thus:


![pro2](https://cloud.githubusercontent.com/assets/7359272/21420400/7289a66e-c825-11e6-91a8-dd4b805d761e.jpg)

names not displayed...

**Comment by kimrutherford** [comment]
> names not displayed...

Sorry about that.  I forgot to clear the cache that Canto uses to speed up gene lookups from Chado.  Should be OK now.
