### ISSUE TITLE
Demo "background"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1303]
Can we make the "demo" wording background a bit 'lighter"
https://curation.pombase.org/demo

(I'm making my slides so I was looking at it. On some pages it makes it quite hard to read text (see the help pages for instance)

**Comment by kimrutherford** [comment]
I've made it lighter.  You'll need to reload.  Let me know if that's better.

**Comment by ValWood** [comment]
Much better. It could even be lighter but its fine now
