### ISSUE TITLE
is canto updating OK?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1306]
I have  GO terms which I can see in GO, but don't appear in Canto ?

GO:1905785
GO:1905786

**Comment by mah11** [comment]
on the other hand, FYPO terms I added yesterday are available

**Comment by ValWood** [comment]
it culd just be a delay. I tried to request in term genie but they already existed. I don't remember getting the notification... will dig deeper if missing tomorrow

**Comment by kimrutherford** [comment]
Sorry, the GO SVN checkout on oliver0 wasn't being updated due to a typo by me.  I've fixed it and I'm now running the ontology update again.

**Comment by kimrutherford** [comment]
Those terms are in Canto now.

**Comment by ValWood** [comment]
thanks, all done ;)
