### ISSUE TITLE
column for curated + approved on the people page

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1309]
Hi Kim,

could you include a new column on this page:
https://curation.pombase.org/pombe/view/list/person?model=track&numrows=10&order_by=%3CNumber+of+sessions&page=1

I'd like to know the number of sessions curated by each person AND that have the approved status

so for example for this person the number would be 0:
https://curation.pombase.org/pombe/view/object/person/143?model=track

This one would be 1:
https://curation.pombase.org/pombe/view/object/person/484?model=track

**Comment by ValWood** [comment]
I don't want this on the public pages as yet.

We have the info to  provide this data as I needed it for the word cloud. 

If its for the wordcloud I can sort that part ( It took me ages to  find the best software  which had the appropriate output options/ fonts / colour  & size configuration etc). I needed to script conversion of the data from kim to wordcloud format, and configure so many options that I document  how to recreate it.......

**Comment by mah11** [comment]
Antonia's request shouldn't be a problem for the public pages. The person pages can only be seen by a logged-in admin, not a regular user.

**Comment by ValWood** [comment]
Ah I thought it was for the stats page...

I see.

Admin interface changes are even more out of scope with website deadlines, and I already have a couple of canto/chado tasks that will need to slot in at some point.

Antonia we'll chat about what the figure is and Kim can do a simple query if its easy.

**Comment by Antonialock** [comment]
I wanted to try make a little choropleth (? like a heatmap) world map of community curation contributions

**Comment by Antonialock** [comment]
for the community curation poster

**Comment by ValWood** [comment]
> for the community curation poster

Yep I know. That would be cool.  Kim can do the query for the  name/number of papers that he did for me for word-cloud.  

@kimrutherford
 I can't find the e-mail or my notes with the query....my instructions for the word-cloud start with "get Kim to run query"

**Comment by Antonialock** [comment]
Also I don't understand what the current "number of session" number is useful for?
https://curation.pombase.org/pombe/view/list/person?model=track&numrows=10&order_by=%3Cname&page=1

**Comment by ValWood** [comment]
ah I see, that could be a simple change to add column and number.
Kim if its quick,


or a query
email, approved_session_number (or whatever you need)

**Comment by kimrutherford** [comment]
I've changed the "Number of sessions" column to "Approved sessions".  Does that help?

I can add "Number of sessions" back if it's useful.

**Comment by ValWood** [comment]
I think both could be useful....
Good to see how many they had vs how many they completed so 2 columns...
