### ISSUE TITLE
canto bug? weird stuff data not showing in some views

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1317]
I'm recurating an old paper with modern standards and I begin by deleting the existing in artemis.

 In the paper summary  pom1 has
![pom1](https://cloud.githubusercontent.com/assets/7359272/25431946/8cc26914-2a7a-11e7-8ac3-146b18f87c8a.jpg)

but when I click on pom1 I only see
![pom1-2](https://cloud.githubusercontent.com/assets/7359272/25431962/9cf0bcb4-2a7a-11e7-8172-b95219c10c56.jpg)

so I don't see ~CC or~ phenotype.

**Comment by ValWood** [comment]
Ah, I suspect this might be due to the genotype merging ;)

**Comment by mah11** [comment]
The phrase "full view" is not applicable to Canto. Your first screenshot is of the paper summary.

There are no genotypes for this paper in Canto, so the issue isn't merging. I think it must be more to do with Canto not showing phenotype annotations on its gene pages if it doesn't have a genotype entry to make the connection between genotype and gene(s).

**Comment by ValWood** [comment]
do we want to display existing?
if so,  can add to 
https://github.com/pombase/canto/issues/726
as can be done at the same time...

(both are displaying data from artemis that is not currently visible)

**Comment by ValWood** [comment]
This is an issue that will go away eventually  so closing  (unless anyone has any ideas).
I'm not totally sure what it was , but it didn't bother me since...
