### ISSUE TITLE
bug in search for extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1318]
in the extension drill down for involved in this process

I could not find
GO:1990151	protein localization to cell tip
in extension search
even when searching on "protein localization to cell tip" (exacy match)

I could find it as the main suggestionin the main ontology search.

I could not even access "protein localization" to drill down. I  knew the term existed so I ended up looking up the ID and plugging in, but I don't think there is any way to get to it by browsing

**Comment by mah11** [comment]
What was the "main" term for this annotation? These usually turn out to be configuration issues ...

**Comment by ValWood** [comment]
I did think that initially, but its part_of for "protein kinase activity" , so it should allow any process?

**Comment by ValWood** [comment]
'twas curs/a475a61f06526c04/ro and sister paper

**Comment by mah11** [comment]
Aha. It looks like a GO issue: GO:1990151 does not have a path to cellular process GO:0009987. Not a Canto bug. Ask GO why it doesn't have GO:0051641 cellular localization is_a GO:0009987 if you want those worms out of that can, and good luck!

**Comment by ValWood** [comment]
I guess we could move up to "biological process" in the meantime (probably taxon filters will suppress most non-applicable stuff anyway), although it isn't a big deal because only curators are really  making F-P connections so we can do them manually...

Also I think GO want to get rid  of the cellular/non cellular process distinction. I don't really think that they should... It's up for discussion at the next consortium meeting.

**Comment by ValWood** [comment]
I can't remember what I need to do to which file to fix this.
@mah11  could you tell me what I need to do?

Thanks

**Comment by mah11** [comment]
Either

> Ask GO why it doesn't have GO:0051641 cellular localization is_a GO:0009987 (worm-can warning)

or add a config line for GO:0051641 cellular localization

**Comment by ValWood** [comment]
so, I changed

GO_MF_A_E_config:GO:0003674	is_a	part_of	GO:0009987	involved in biological process		0,1	user

to
GO_MF_A_E_config:GO:0003674	is_a	part_of	GO:0009987|GO:0051641	involved in biological process		0,1	user
