### ISSUE TITLE
demo server button with message when you try to select an "in progress" paper

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1319]
I think there is supposed to be some text in the small button?

![message](https://cloud.githubusercontent.com/assets/7359272/25555725/f17e2452-2ce5-11e7-9e1c-8c6fa21d0859.jpg)

at present it just says "find another" but  nothing else

**Comment by mah11** [comment]
For me, the second button is normal size and labeled "View session".

**Comment by ValWood** [comment]
On the demo server? that's odd...

I'm chrome.

**Comment by kimrutherford** [comment]
> For me, the second button is normal size and labeled "View session".

It was only going wrong for the case where a session existed for that PMID.

I've fixed it.

**Comment by mah11** [comment]
yeah, my point was that it wasn't going wrong for me even for one I checked that had an existing session. but if it's working in more cases now, yay
