### ISSUE TITLE
gene page annotations, different separator for affecting?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1320]
decreased mRNA splicing, via spliceosome
prp2-1(C387Y)  affecting nda3
prp2-1(C387Y)  affecting taf111 , cam1  and cgs2  and nda3 , cdc2
prp2-2(T259I)  affecting tbp1
prp2-2(T259I)  affecting taf111
prp2-9(E256A, D257A)  affecting cam1  and cgs2  and nda3

These should all be "|" separated I think?
If not, I don't understand what the "and" means in this context. We usually use it for protein binding etc when 2 things are affected or required simultaneously?

**Comment by ValWood** [comment]
OK closing this one...

**Comment by mah11** [comment]
https://github.com/pombase/pombase-chado/issues/625
