### ISSUE TITLE
special section for creating a "multi gene genotype"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1322]
Do we need one here?
https://curation.pombase.org/pombe/docs/fypo_annotation

So we cna  point people to a step by step "how to create a multi-gene genotype"

**Comment by mah11** [comment]
Scroll down - it's existed for ages.

If you mean you want more intra-page links near the top, please clarify.

**Comment by ValWood** [comment]
Oh yes, sorry for the delay, got buried.
I don't know how I missed it,  butI think  links at the top would be useful

**Comment by mah11** [comment]
done in source file; over to Kim to update live Canto
