### ISSUE TITLE
canto extension issue

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1323]
currently all say 

add independent extension?

and above
These extension types are available for {{termDetails.name}} ({{termDetails.id}}):

**Comment by kimrutherford** [comment]
Is your network dodgy?  Can you try a shift-reload?

I'll check the logs.

**Comment by ValWood** [comment]
It could be the network but I tried a few times and only this was affected.
I *could * add the extension in the edit section tho'

Network is crap

**Comment by kimrutherford** [comment]
Which term were you annotating with so I can try to reproduce the problem?

**Comment by ValWood** [comment]
curs/7cc0d044cd0fd080

try to replicate annotations in this session.

I was not logged in but was still the same when I did...

**Comment by kimrutherford** [comment]
Could you try again now?  (You might need to reload)

**Comment by ValWood** [comment]
yep its fine now.
