### ISSUE TITLE
Difference between publication status

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1324]
What is the difference between

publications with approved sessions 2912
and
curated publications 2928

I can't remember...

![diff](https://cloud.githubusercontent.com/assets/7359272/26285591/c5e86f52-3e4a-11e7-8552-05dea20879ee.jpg)

**Comment by kimrutherford** [comment]
"Curated publications" includes "NEEDS_APPROVAL" and "APPROVAL_IN_PROGRESS" sessions.  That label isn't very clear.  Can you suggest an alternative?  Maybe "Submitted publications"?

**Comment by ValWood** [comment]
Hmm, I wondered if it was that, but we only have 5 sessions with "NEEDS APPROVAL" or "APPRoVAL IN PROGRESS" so the numbers don't quite add up....

Trying to make sure we know when we get to 3000  ;).... countdown is on!

**Comment by kimrutherford** [comment]
Ah, sorry.  The "publications with approved sessions" report only includes sessions for publications that have a triage status of "Curatable".  That's probably historical.  Shall I remove that constraint?

**Comment by ValWood** [comment]
hmm, can you give me the diff list and I'll check if they should be "reclassified" as "curatable"

**Comment by kimrutherford** [comment]
Surely all curated publications should be flagged as "curatable"?  (I feel like we've had this discussion before)

**Comment by kimrutherford** [comment]
There are 15 curated publications that are "Curatable":

    PMID:22322963   Other     Expression of budding yeast IPT1 produces mannosyldiinositol phosphorylceramide in fission yeast and inhibits cell growth.
    PMID:21672643   Method or reagent     The oxidized thiol proteome in fission yeast--optimization of an ICAT-based method to identify H2O2-oxidized proteins.
    PMID:18029449   Other     In search of an optimal ring to couple microtubule depolymerization to processive chromosome motions.
    PMID:10593605   Not physically mapped     Cloning of a Schizosaccharomyces pombe homologue of elongation factor 1 alpha by two-hybrid selection of calmodulin-binding proteins.
    PMID:1502179   Method or reagent     Simple derivation of TFIID-dependent RNA polymerase II transcription systems from Schizosaccharomyces pombe and other organisms, and factors required for transcriptional activation.
    PMID:1620594   Other     Activity of chimeric RNAs of U6 snRNA and (-)sTRSV in the cleavage of a substrate RNA.
    PMID:2044950   Phylogeny and evolutionary studies     mRNA-type introns in U6 small nuclear RNA genes: implications for the catalysis in pre-mRNA splicing.
    PMID:2226803   Phylogeny and evolutionary studies     The RNA component of RNase P in Schizosaccharomyces species.
    PMID:23497645   Review or comment     Ndc80 Loop as a protein-protein interaction motif.
    PMID:23907116   Review or comment     Proteasome-dependent degradation of replisome components regulates faithful DNA replication.
    PMID:25402480   Sequence feature or region     RNA cytidine acetyltransferase of small-subunit ribosomal RNA: identification of acetylation sites and the responsible acetyltransferase in fission yeast, Schizosaccharomyces pombe.
    PMID:25747261   Sequence feature or region     Genome-wide analysis of core promoter structures in Schizosaccharomyces pombe with DeepCAGE.
    PMID:26727711   Review or comment     A nucleoporin that facilitates meiotic kinetochore reorganization.
    PMID:28228545   Phylogeny and evolutionary studies     Ablation of RNA interference and retrotransposons accompany acquisition and evolution of transposases to heterochromatin protein CENPB.

**Comment by ValWood** [comment]
OK, yes sorry  I was thinking the other way around. Sometimes  we might re-triage if no annotation.

Some appear to have the incorrect classification, I will fix.
Some are methods papers where we have obtained some annotation. I will keep these as "methods" because we will need them in that set later.

**Comment by ValWood** [comment]
looking at these, it seems that they are the publications which went out for curation, but were returned as "uncuratable" and reclassified, so the classifications are correct.
We could have another slot for these so we can check them later

"returned as uncuratable, reclassified"
this classifier could replace 
"curatable publications with no annotatable genes"
I think it meas the same but  it is a little more inclusive as to why  
(and "curatable publications with no annotatable genes" is empty *because* we reclassify but it would contain the list above)

This way we would be able to retain them in our community curation stats.

I think this means that we should use
"Curated publications (2932)" for our "curated paper" total

**Comment by ValWood** [comment]
I can't remember what we decided?

rename to
curated publications (approved and unapproved)

**Comment by kimrutherford** [comment]
I think we decided to ignore the "Curatable" flag for the "publications with approved sessions" report because "Curatable" means "we should try to curate this paper" rather than "this is a paper we were able to curate".

We also decided that I should check the other reports to make sure the Curatable status is checked only when it's sensible.  I've just done that and the other reports look OK.

I've fixed "publications with approved sessions".

> but were returned as "uncuratable" and reclassified

I'm not sure what you mean here.

**Comment by ValWood** [comment]
I think what I meant was
"curatable publications with no annotatable genes"
is a bit of an oxymoron. If it doesn't have annotatable genes, then it isn't curatable

so I wondered if
"returned as uncuratable, reclassify"

would be a better label. Without looking at them it's difficult to know if they belong anywhere else.

**Comment by kimrutherford** [comment]
> I've just done that and the other reports look OK.

I've had second thoughts.

There are a lot of reports that only include publications that are
triaged as "Curatable".  I'm not sure they all make sense:

    Curatable publications
    Community curatable publications
    Curatable low priority publications
    Curatable publications with sessions
    Publications with multiple sessions
    Curatable publications without sessions
    Publications with new sessions
    Publications with active sessions
    Curatable publications with no annotatable genes

For example "Publications with new sessions" - if a session is new (ie. created but not accepted) we know it must be Curatable don't we?

**Comment by ValWood** [comment]
I use all these lists to keep tabs on progress. Some are sub lists of others.
Some of the names might be a bit odd and their placement means it isn't always obviuos why they are there, but I use them all...

Curatable publications
- Community curatable publications 
- Curatable low priority publications (this is a list of very old we decided not to do for now)
- Curatable publications with sessions
---Publications with new sessions
---Publications with active sessions
---Publications with multiple sessions
- Curatable publications without sessions

**Comment by ValWood** [comment]
I think for now we can  keep everything else as it is.
In the future we might look at this and revise. In particular some of the labels are not so clear. Nothing urgent and it might be good to revise this as part of the PHI project to make sure that we have labels that are a) clear of meaning, b) can be configured per project c) and cover other project requirements. Maybe we could select the ones we want from a list?
I will open a new very general ticket for this.

**Comment by ValWood** [comment]
replaced by https://github.com/pombase/canto/issues/1410
