### ISSUE TITLE
is canto updating?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1325]
I cant find

http://www.ebi.ac.uk/QuickGO/GSearch?q=GO:0106006

**Comment by kimrutherford** [comment]
Ah sorry, it is failing.  OWLTools is throwing an error when extracting the pombe-only subset from go-plus.owl.  I've just reported the problem: https://github.com/owlcollab/owltools/issues/200

The ontology update was continuing after the error and using the subset OBO file from the last time OWLTools worked on April 14th.

I've changed the update script to tell us when this sort of error happens and I'll let you know when the OWLTools folk reply.

**Comment by mah11** [comment]
Would this affect all ontology updates or just GO? (Wondering specifically about the latest crop of FYPO additions ...)

**Comment by kimrutherford** [comment]
> Would this affect all ontology updates or just GO?

The whole load fails when owltools fails so it's a problem for FYPO too.

**Comment by kimrutherford** [comment]
I've just had another look at this.  See:
 https://github.com/owlcollab/owltools/issues/200#issuecomment-307626812

I've temporarily removed the lines that OWLTools doesn't like from Canto's copy of go-plus.owl and the ontology load seems to be fine now.  It hasn't finished but it looks like it will.

I compared the OBO file it produced against the last OBO file that we had from before the load started failing and the differences seem reasonable (there are some extra terms and some old term IDs are now alt_ids).

**Comment by ValWood** [comment]
Thanks Kim. 

So if all goes well we should be able to add new terms tomorrow  @Antonialock @mah11 

I won't be working until Tuesday. Travelling back tomowrrow.

**Comment by kimrutherford** [comment]
The update seems to have worked but I'll be more confident once OWLTools is fixed.

**Comment by kimrutherford** [comment]
Chris has fixed the go-plus.owl file:
  https://github.com/owlcollab/owltools/issues/200#event-1119816126

The nightly ontology update is working fine again.
