### ISSUE TITLE
no allele autocomplete

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1326]
The allele name autocomplete seems not to be working. I type part of an allele name, but don't get any suggestions, let alone the one I want. I know it's in chado somewhere, because it shows up on gene and genotype pages, and at least some of the papers have been done in Canto.

Seen with cdc6 (looking for cdc6-23) in session 76a3cc41b9c66144; tried Firefox, Safari and Chrome.

**Comment by mah11** [comment]
addendum: it does work for alleles already entered in the same session

**Comment by ValWood** [comment]
Yes I'm not sure it has ever worked for alleles in the database, but not the session. I think there could be a ticket about it somewhere...

**Comment by mah11** [comment]
This is most assuredly a recent bug - it has retrieved alleles in its database, not just those entered in one's current session, for ages.

**Comment by ValWood** [comment]
Yes of course. Its multi that  aren't available.

**Comment by mah11** [comment]
???

This bug affects adding an _allele_, regardless of how many alleles one wants to add to the genotype.

**Comment by ValWood** [comment]
yes thats what I'm saying. I was thinking of something else entirely.

**Comment by kimrutherford** [comment]
Sorry about that.  I updated Canto to point to the latest nightly Chado yesterday but it seems to be missing lots of data.  I've fixed the immediate problem by pointing at the previous Chado (from May 30th).  So the completion works again.

I'll investigate the Chado loading problem.

**Comment by kimrutherford** [comment]
> I'll investigate the Chado loading problem.

Sorry, it was my fault.  I had updated Linux on oliver0 and didn't notice that it restarted Postgres in the process.  It was mid-load when that happened and it all went wrong.

The load that's running now looks fine.
