### ISSUE TITLE
cant get to existing session

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1330]
i'm logged in.

can't create new session - a session already exists for: PMID:20434336

but I can't seem to get to it.
I can't see it in curated, even though I know that it is?

**Comment by kimrutherford** [comment]
It's in this list:
https://curation.pombase.org/pombe/view/list/all_publications?model=track

There's a session with no annotation:
https://curation.pombase.org/pombe/view/object/pub/893?model=track
https://curation.pombase.org/pombe/curs/c166fc9a9dd60e8d

**Comment by ValWood** [comment]
OK, I was searching the wrong list!
