### ISSUE TITLE
searching  for process extension

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1334]
This might be a consequence of some GO issues. When I am searching for 
"protein maturation" for a function involved_in process extension, I can't see the term

protein maturation GO:0051604
in the list. I would expect it to be the top hit since it is an exact match.

Lot of other terms show higher (though I think most of these would normally be hidden by taxon restrictions until recently)

**Comment by mah11** [comment]
This is because GO does not have a path from GO:0051604 to "cellular process" (and our MF configuration has part_of GO:0009987|GO:0051641, i.e. cellular process or cellular localization).

Not a Canto problem ...

**Comment by ValWood** [comment]
OK I need to figure out what to change in the config.

**Comment by ValWood** [comment]
@mah11 How do I fix this?
The immediate parents are 
1 gene expression
2. Protein metabolic process

It isn't a huge deal, can do manually... but good to get rid of the ticket

**Comment by mah11** [comment]
add either GO:0019538 (metabolic proc) or GO:0051604 (maturation) to the range column in this line:

    GO:0003674      is_a    part_of GO:0009987|GO:0051641   involved in biological process          0,1     user

in GO_MF_A_E_config

**Comment by ValWood** [comment]
done
