### ISSUE TITLE
show TASs/NASs in canto

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1335]
we decided not to show TAS/NASs in canto because we thought it might make us not make EXP annotations. 

I would prefer it if we show them because it can  prompt the removal of indirect annotations

**Comment by ValWood** [comment]
This probably isn't a bod plan.
But you should  always consistency check back to the gene pages after you finish a paper...
Its a good "blind check" that you got the same as existing annotations.

I always start by deleting the legacy annotation.  Although I think it would be helpful to be able to see them in Canto as an addition reminder that you need to do something with them....

but remember dealing with NAS and TAS should be done for each gene after any paper, even the ones not originating from the paper in question....

**Comment by Antonialock** [comment]
yeah, it will just make it wasier....especially now we hide evidence and references in the summary view

**Comment by ValWood** [comment]
good point...

**Comment by kimrutherford** [comment]
How urgent is this?

**Comment by ValWood** [comment]
not very.

**Comment by ValWood** [comment]
duplicate
https://github.com/pombase/canto/issues/726
