### ISSUE TITLE
adding % expressivity

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1336]
Should we still be able to do this? I can't see a workable option for it (I'm guessing this is the correct extension to pick but I can't add a value:

![screen shot 2017-07-21 at 15 29 29](https://user-images.githubusercontent.com/12727506/28468001-95ee51b8-6e29-11e7-9cbc-7a7198db34f1.png)

**Comment by mah11** [comment]
No, we have never had any way of capturing quantitative expressivity/severity. We've never even worked out how it might be measured quantitatively for most phenotypes ...

**Comment by Antonialock** [comment]
Ah ok, thought we might have used it with elongated phenotypes.

**Comment by Antonialock** [comment]
it looks like it appears in a few places...
![screen shot 2017-07-21 at 15 38 48](https://user-images.githubusercontent.com/12727506/28468419-d30d994a-6e2a-11e7-958a-4df321670cb3.png)
![screen shot 2017-07-21 at 15 38 38](https://user-images.githubusercontent.com/12727506/28468422-d4e5a6c2-6e2a-11e7-803d-ec050cbd7440.png)

**Comment by Antonialock** [comment]
ah that's penetrance. I though penetrance was the fraction of cells? And expressivity related to severity of phenotype?

**Comment by mah11** [comment]
yes, that's correct, and population phenotypes don't allow penetrance extensions

**Comment by Antonialock** [comment]
oh, so if you annotate to "elongated cell" + penentrance=11% 
it means that 11% of cells are elongated right? not that they are 11% longer?

**Comment by Antonialock** [comment]
just to clarify :-)

**Comment by mah11** [comment]
yup
