### ISSUE TITLE
users still creating "Uber genotypes"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1339]
We'll revisit this when things get more back to normal.

Correction, we have a whole new normal ;)

![uber phenotype](https://user-images.githubusercontent.com/7359272/30332098-6adff48c-97d1-11e7-9fa1-609b5663472c.jpg)

Keep thinking how to address this simply  and add your idea...

**Comment by kimrutherford** [comment]
Perhaps we need to do more more keep users away from the multi-allele interface if they only need a single allow genotypes?  Maybe a tick box for multi-allele mode?  If they had to tick the box hopefully they would think more about it.

As a last resort,  if the user adds lots of alleles (5 maybe?) to a genotype we could pop up a dialog that double checks that they are on the right track:

    You have added 5 alleles to this genotype.
    Did you mean to create 5 single allele genotypes?  [link to docs]

We'd only want to do that once per session.

**Comment by ValWood** [comment]
> Perhaps we need to do more more keep users away from the multi-allele interface if they only need a single allow genotypes? 

I think that might be tricky...most papers have both now....

This user figured it out, but they didn't delete the incorrect one, and they didn't add their multi genes. I suspect a lot of users make this mistake and delete so we never see it.

I'm sure we can improve if we put our heads together.... we'll have a think  about it in an upcoming call.

**Comment by mah11** [comment]
transferred from duplicate #1353:

-----

I [Val] don't know if we have an open ticket about the "gerry proble" but I still see it in user sessions.
Also  there are probably more people who do it and then figure out it was incorrect and fix.

I had another this week:
![val](https://user-images.githubusercontent.com/7359272/31682968-72c76474-b373-11e7-9503-f75a940f9144.jpg)

(this should have been 2 independent annotations, not a double mutant)

Last time it happened I thought of some little ways to improve slightly that we could try easily.
I'll  made notes so I'll dig out and add to this ticket.

-----

**Comment by mah11** [comment]
transferred from duplicate #1353:

-----
Here, I wonder if it should say
"add a new genotype" or "create a genotype"

![add a new](https://user-images.githubusercontent.com/7359272/31683352-ae7202d0-b374-11e7-8f37-03b99319f9e0.jpg)
 

Then here:

![add another or](https://user-images.githubusercontent.com/7359272/31683149-0f9315c8-b374-11e7-81f3-6785396d3b5e.jpg)


I feel that the instruction gets a little lost , because there is quite a lot going on here.
It would be better if

1. The text boxes to add name and background were not so prominent. They are optional. I think they would work better below.

This would associate the instruction  more closely with the requited action




-----

**Comment by mah11** [comment]
Is there also any way the instruction could be made clearer?

Antonia next time you are in the lab, could you get a few lab members to create a genotype and see what  they  are thinking ?
-----

**Comment by mah11** [comment]
I still think the single most helpful change we could make is to move the "Finish" button up to (or at least near) the top of the "alleles of this genotype" page. Even with a short gene list it's easy to overlook the button, and with a long gene list it can actually fall so far down that you have to scroll to see it, and not just on a tiny screen.

**Comment by ValWood** [comment]
Yes that too. That would not help in the situations I have seen, because this occurs on first genotype added when the button is directly below the alleles (see above)

**Comment by Antonialock** [comment]
yeah I'll check with them next week

**Comment by ValWood** [comment]
here,
https://github.com/pombase/canto/issues/1313
we suggest calling the button
 "finish genotype"
do we want to  do that?

**Comment by ValWood** [comment]
we should address this next. 2 more sessions did this over xmas
![fix](https://user-images.githubusercontent.com/7359272/34675658-38b93f82-f482-11e7-87ec-ba192f306a93.jpg)

**Comment by Antonialock** [comment]
and another
<img width="758" alt="screen shot 2018-01-17 at 14 33 08" src="https://user-images.githubusercontent.com/12727506/35062905-8cd03748-fb93-11e7-8725-86d7582a33ea.png">

**Comment by ValWood** [comment]
and another

![alot](https://user-images.githubusercontent.com/7359272/35063000-b3b1d36a-fbbd-11e7-9594-48facec042ac.jpg)

**Comment by Antonialock** [comment]
> here, #1313, we suggest calling the button "finish genotype" do we want to do that?

Hah, I was just going to suggest that. I think "create genotype" would be much clearer. 

the text "the alleles of this genotype" is very hard to spot.

**Comment by ValWood** [comment]
> the text "the alleles of this genotype" is very hard to spot.

Yes!
I  think small improvements could get us a long way as a stop gap.

**Comment by ValWood** [comment]
we need to address this next week...I just spotted this one in prgress...
(it's long.....)

![need to fix](https://user-images.githubusercontent.com/7359272/35766539-615d87fe-08d2-11e8-9f33-22350bb5d311.jpg)

**Comment by ValWood** [comment]
proposal is here:
https://github.com/pombase/canto/issues/1381
