### ISSUE TITLE
I see "plant-type vacuole" in Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1340]
...even though it is taxon restricted?

GO:0000325 | plant-type vacuole | Only in Taxon | 33090 | Viridiplantae
-- | -- | -- | -- | --

**Comment by kimrutherford** [comment]
Yep, there are suddenly lots of non-pombe terms.

I've added a new comment here:
  https://github.com/owlcollab/owltools/issues/165

**Comment by ValWood** [comment]
Still see plant terms....

**Comment by kimrutherford** [comment]
There has been progress.  We're now loading the taxon restricted GO again.  But there are still non-pombe terms.

See: owlcollab/owltools#165

**Comment by kimrutherford** [comment]
"plant-type vacuole" is gone now but there is still a auto-complete suggestion for "plant":

ID 	GO:0090395
Term name 	plant cell papilla 

In owlcollab/owltools#165 "unidirectional conjugation" is mentioned.  That is still in the taxon restricted ontology:

ID 	GO:0009291
Term name 	unidirectional conjugation

**Comment by ValWood** [comment]
requested last week with a batch of others
https://github.com/geneontology/go-ontology/issues/16018

**Comment by ValWood** [comment]
our conjugation is conjugation with cellular  fusion. 

![conjugation](https://user-images.githubusercontent.com/7359272/42996047-4f0002d8-8c0a-11e8-9d06-39e4bd96dc5a.jpg)


Term name unidirectional conjugation
is bacterial.

I think there might have been a parentage issue when I opened this ticket that was subsequently fixed.

**Comment by ValWood** [comment]
Oh I see. We can still see "unidirectional conjugation" in canto. So it didn't work in this case. This has the taxon restriction "only in eukaryotes"

Are we screening "only in" non fungal phyla?

**Comment by kimrutherford** [comment]
> Are we screening "only in" non fungal phyla?

We're are restricting to "only in S. pombe" and owltools infers the rest.

**Comment by ValWood** [comment]
I think this is working. The only terms I see are not taxon resticted.
