### ISSUE TITLE
Old annotations still showing in canto

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1342]
I removed these annotations last Friday e.g.
![screen shot 2017-09-18 at 13 12 33](https://user-images.githubusercontent.com/12727506/30541386-1e9822e2-9c73-11e7-8bbb-54a753ef36aa.png)

They are gone from preview.pombase, but are still showing in canto?
PMID:15870269 / 09a2ea749be9cd03

**Comment by kimrutherford** [comment]
Sorry, I haven't updated Canto this week to point to a new Chado release.  I've done that now.
