### ISSUE TITLE
Install locally a PHI-canto version Using the UniProt gene look-up adaptor

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1345]
Adapt the adaptor 
To display
 i) uniprot accession,
 ii) user friendly/recognisable name UniProt gene name: (primary gene name, user recognisable).
iii) Show ORF label in synonyms column.
iv) Product name 
v) taxon

Use the UniProt API.
@kimrutherford to add details of where  to access the UniPRot API

@CuzickA Alayne can explain to Henry  the difference between the types of ID and which  fields are needed with reference to a UniProt entry

**Comment by ValWood** [comment]
- [ ]  @henryosim  Try following installation instructions as they are and  feedback where there are issues.

**Comment by kimrutherford** [comment]
> iii) Show ORF label in synonyms column.

My Googling failed.  What's a "ORF label"?  Could you give an example?

**Comment by ValWood** [comment]
ORF = open reading frame
 "systematic ID", uniprot call it "orf_label" or similar....

**Comment by henryosim** [comment]
point number 1) and 2) have been actioned

**Comment by kimrutherford** [comment]
> Show ORF label in synonyms column.

Hi @henryosim

This is the Canto code that needs to be changed:
  https://github.com/pombase/canto/blob/master/lib/Canto/UniProt/UniProtUtil.pm#L70

Here is an example bit of UniProt XML here:
  https://github.com/pombase/canto/blob/master/t/data/uniprot_lookup.xml

The XML isn't too complicated.  Perhaps you and @CuzickA could have look together to decide what PHI-Canto needs to parse out of it?

The test for that code is here:
  https://github.com/pombase/canto/blob/master/t/70_uniprot_lookup.t

To execute that test inside Docker run:

```sh
  canto/script/canto_docker perl -Mlib=lib t/70_uniprot_lookup.t
```

This test reads use the code in UniProtUtil.pm to read the XML file above, then checks the results.

I'm happy to help we this.

**Comment by ValWood** [comment]
Need to get the name of the gene instead of the "useless" ID  (i.e CDC2_SCHPO)
Need to get Gene name instead.
@CuzickA

**Comment by CuzickA** [comment]
I have slide mock ups. Just waiting for a time slot to run through these with @henryosim. We plan to do this by the end of the week after the changes have been made to the PHI-Canto front page #1346

**Comment by kimrutherford** [comment]
I'm closing this in favour of: https://github.com/PHI-base/canto/issues/3
