### ISSUE TITLE
implement PHI_canto version with already  available configureable items configured

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1346]
These include:
- [ ] Logo
- [ ] Documentation (placeholder for extended documentation)
- [ ] Funding logo, explicit funding statements

We discussed looking at Alistair's implementation to see what he configured, and also what was hard coded.

- [ ]  Any hard coded features identified can be listed here and changed to configurable options.

**Comment by ValWood** [comment]
@CuzickA

**Comment by ValWood** [comment]
- [ ] Document text changes that need to happen here

  - [ ]  Provide details for branding, provide logo's

**Comment by ValWood** [comment]
@henryosim  after
https://github.com/pombase/canto/issues/1345

but  others to collect info

**Comment by CuzickA** [comment]
This is progressing.

Notes for the future regarding PHI-Canto front page
1) Help links will need to link out to NEW PHI-Canto documentation. This will be written in the future.
2) Demo link will need to link out to a Demo version of PHI-Canto (once it has been fully created).
Leave current link outs to PomBase for now.
