### ISSUE TITLE
Add "strain label" box as a configurable option

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1347]
The strain label will be available set if 
"pathogen mode"  or "multispecies mode" is configured on at set up.

- [ ]  strain label box ( a box where the user will supply the strain ID, available from  all of the the pathogen phenotype  curation types)
(List these here)

The strain ID will be an autocomplete look up. Only the strain IDs which match the taxon will be presented. If none are available the user will supply the strain ID

-  [x]  @CuzickA @martin2urban Alayne/Martin/Kim Decide on a  simple format for taxon/strain file
-  [ ]  @CuzickA @martin2urban Alayne/Martin? Prepare a file of existing strains (a small test file with only a few lines will do in the first instance)

- [ ] @kimrutherford Changes will need to be made to the Canto Database so that a list of Strain IDs for specific taxons can be imported

**Comment by kimrutherford** [comment]
I've added a "strain" column to the genotype table in the Canto database.  It isn't used for anything yet but database schema changes are annoying so I wanted to get it done early.

@henryosim after the next time you do a `git pull` you'll need to upgrade your test Canto database schema to version 15 with this command in your `canto-space` directory:

    ./canto/script/canto_docker ./etc/upgrade_db.pl 15

or since it's a test installation of Canto you can just delete the contents of `data` directory and re-initialise with `./canto/script/canto_start_docker --initialise /data`

**Comment by henryosim** [comment]
done, thanks @kimrutherford

**Comment by ValWood** [comment]
can this close?

**Comment by kimrutherford** [comment]
Yep, I think we can close this.  I'll make a separate issue for this bit:

> Changes will need to be made to the Canto Database so that a list of Strain IDs for specific taxons
> can be imported

**Comment by kimrutherford** [comment]
Notes from meeting:

- A drop down list would probably be OK as the number of strains is small-ish
- There will need to be an "Other" option that brings up a free-text box for saving a new strain in Canto

We need to talk about how to support complementation experiments.  The pathogen species might be different to the species of the gene entered by the user.  In that case we'll need to capture the species separately.

**Comment by ValWood** [comment]
We still need to include complementation experiments for fission yeast too. We do them in artemis currently. It should be fairly straightforward to do generically.
https://github.com/pombase/canto/issues/826

**Comment by kimrutherford** [comment]
I've made a bunch of PHI-Canto issues to replace this one.
