### ISSUE TITLE
Prepare a modified "condition ontology" for pathogen phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1349]
@CuzickA

The "conditions ontology" used with individual phenotype ontologies is configurable 
as soon as this is available  (even a mini-version) use at import to test

**Comment by CuzickA** [comment]
link to FYPO peco
https://github.com/pombase/fypo/blob/master/peco.obo

**Comment by CuzickA** [comment]
Also consider plant expt conditions ontology
http://purl.bioontology.org/ontology/PECO
