### ISSUE TITLE
make the small pathogen-host interaction phenotypes avaiable in obo format

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1350]
This might already  be available as part of previous work?

**Comment by CuzickA** [comment]
I have added the most recent versions from Alistair's files into the Dropbox 'PHI-base' folder created by Kim R. These include the 9 high level phenotype terms and working progress on lower level terms.

**Comment by ValWood** [comment]
From the discussion
It is required that all pathogen host interactions map to one of the "high level terms" for export to other resources

This could be achieved by making these " a  subset/ or slim"
Terms where a more specific annotation is required  in order for an annotation to be made under one of the high level terms could be flagged as "do not annotate" so that a more specific annotation  under the appropriate  high level terms is always obtained.

We use a very similar procedure with GO  to force annotation specificity.

the example we discussed was "penetration"
PHI phenotypes 
reduced virulence  (quantitative,  some disease)
—- penetration reduced 
—loss of pathogenicity (qualitative  no disease)
—- penetration abolished
altered penetration

**Comment by ValWood** [comment]
I do not see the dropbox PHI-base folder Could you send me a link?

**Comment by ValWood** [comment]
I was going to look at your ontology.
Do you have textual definitions  for all of the terms yet?

To make development easier  you will need "logical definitions" and @mah11  will be able to advise you on this soon.
It will be helpful if you have "textual definitions" in place, and if  these could follow  standard design patterns. You can look at FYPO  to see how Midori has constructed these.

It should not be too big a task whilst your ontology is still small.

**Comment by ValWood** [comment]
transferred to
https://github.com/PHI-base/PHI-base_ontologies/issues/4
