### ISSUE TITLE
aa capitalization

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1351]
super minor thing.

In the annotation tables, nt and aa are in lowercase letters, but in the popup box for allele descriptions it is in uppercase for nonsense mutations

popup box:
![screen shot 2017-10-13 at 09 48 32](https://user-images.githubusercontent.com/12727506/31538584-f4d237ce-affd-11e7-8ec2-2a2186f2d998.png)

annotation table:
![screen shot 2017-10-13 at 10 05 09](https://user-images.githubusercontent.com/12727506/31538614-0b3de242-affe-11e7-93c5-5bbe51991e79.png)

**Comment by ValWood** [comment]
It's lower case?

**Comment by Antonialock** [comment]
No the letters are screaming Val
![d571418b-6371-4972-ac12-daff70ae3624](https://user-images.githubusercontent.com/12727506/33166705-1963cc74-d033-11e7-826a-63281cc1377e.jpeg)

**Comment by ValWood** [comment]
Oh underneath!

**Comment by Antonialock** [comment]
:-)

**Comment by kimrutherford** [comment]
This is a quick but I'll do #1275 first.

**Comment by kimrutherford** [comment]
Finally fixed.
