### ISSUE TITLE
taxon constraints ignored by Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1352]
I should not see  component "proximal dendrite"
https://www.ebi.ac.uk/QuickGO/term/GO:1990635

due to taxon constrains.

Spotted a couple of others
GO:0009429 bacterial-type flagellum basal body, proximal rod

**Comment by kimrutherford** [comment]
Is this the same problem as #1340 ?

**Comment by ValWood** [comment]
Yep...

**Comment by ValWood** [comment]
duplicate
