### ISSUE TITLE
Users "compounding" geneotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1353]
I don't know if we have an open ticket about the "gerry proble" but I still see it in user sessions.
Also  there are probably more people who do it and then figure out it was incorrect and fix.

I had another this week:
![val](https://user-images.githubusercontent.com/7359272/31682968-72c76474-b373-11e7-9503-f75a940f9144.jpg)

(this should have been 2 independent annotations, not a double mutant)

Last time it happened I thought of some little ways to improve slightly that we could try easily.
I'll  made notes so I'll dig out and add to this ticket.

**Comment by ValWood** [comment]
This is how it looks

![add another or](https://user-images.githubusercontent.com/7359272/31683149-0f9315c8-b374-11e7-81f3-6785396d3b5e.jpg)


I feel that the instruction gets a little lost , because there is quite a lot going on here.
It would be better if

1. The text boxes to add name and background were not so prominent. They are optional. I think they would work better below.

This would associate the instruction  more closely with the requited action

**Comment by ValWood** [comment]
Is there also any way the instruction could be made clearer?

Antonia next time you are in the lab, could you get a few lab members to create a genotype and see what  they  are thinking ?

**Comment by mah11** [comment]
duplicates #1339
