### ISSUE TITLE
RNA and protein extensions for RNA binding - odd behavior

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1354]
I would like to add two extensions for an RNA binding phenotype term, to show which protein binds which RNA (in a mutant in a third gene, not the RNA or binding protein gene, at that).

If I add the transcript extension first, it works. But if I add the protein first, it greys out both "assayed protein" and "assayed transcript", and I can't add both. It's not a big deal, since there is a way to do the extensions I want, but it is rather odd - I don't see why the order matters.

This is in the config:

    FYPO:0001092-FYPO:0000702       is_a    assayed_using   ProteinID       assayed protein         0,1     user
    FYPO:0002131    is_a    assayed_using   TranscriptID|SO:0000673 assayed transcript              0,1     user

**Comment by kimrutherford** [comment]
Sorry for being so slow to investigate this.

It looks like the problem is that ProteinID and TranscriptID are both alias for "GeneID" because Canto only knows about gene IDs.  And the relation for both configuration items is the same.

So if you add an "assayed protein", it's actually adding an assayed_using(GeneID) to the annotation.  That matches both configurations so both get greyed out.

I'm not sure how to fix this without changing the configuration.  We should have a chat about it.

**Comment by mah11** [comment]
OK, understanding why it happens helps. And the fact that there is a workaround makes improving it a low priority.

**Comment by mah11** [comment]
It depends on what level of understanding you want. If you want to grasp why it works the way it does, in person is probably going to be best.

If you just want to know what to do, here goes:

1. choose an RNA binding phenotype term in FYPO
2. add an "assayed transcript" extension to say what RNA is bound (or not; anyway, which RNA was assayed)
3. add an "assayed protein" extension to say which protein did (or should have done) the binding to RNA

It works in that direction but not if you try to swap steps 2 and 3.

**Comment by ValWood** [comment]
I don't need to understand it. I only need to know what Kim needs to understand to move forwards. I now added it to the  "in person" list  to save  an ongoing fruitless discussion in the ticket ;)

**Comment by mah11** [comment]
If you are happy with the existing procedure (steps 1-3 above), then Kim doesn't have to do anything in the short or even medium term. That's pretty simple to understand ;)

Because there's a way to do the extensions in question, I don't think it's worth trying to come up with a fix just for them. That's the only thing that I think would need any explaining. Otherwise, we use the existing workaround until & unless Canto starts using separate IDs for transcripts and proteins - I think Kim already understands that that would take care of this issue as a side effect.
