### ISSUE TITLE
new triage option

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1355]
could we have an option for "models"

I have been stashing them under other but I see quite a lot and would like to  re-triage "other" at some point

**Comment by ValWood** [comment]
and "retracted"

**Comment by kimrutherford** [comment]
The new options should be live now.

**Comment by ValWood** [comment]
can't see them yet as I triaged up to date yesterday....
I'm sure it will be fine.

**Comment by ValWood** [comment]
I can see them (and have used "models"
but can they appear here:

https://curation.pombase.org/pombe/track

Also could you rename "models" to "modelling"

and

add "biotech" for the biotech applications, I'd like to sort these too...

**Comment by kimrutherford** [comment]
I've added "Biotech" and added reports for the new triage types to the admin page.
