### ISSUE TITLE
show first approval date on session detail page

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1356]
I've just noticed that the little table of "Database properties of this session" doesn't include the recently added "first approved" date.

example session details: https://curation.pombase.org/pombe/view/object/curs/4622?model=track

Tangent from https://github.com/pombase/website/issues/592, where Kim has looked up the session above and found "first approved ... 2017-10-31 16:01:51" - but we can't see that date in the admin GUI.

**Comment by kimrutherford** [comment]
The first_approved_timestamp is there now.
