### ISSUE TITLE
delta conversion for display

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1357]
In Canto some instances of the string "delta" are converted to upper-case Greek delta (∆), but not all. It appears to need a space or hyphen. We think the risk of mis-converting something is negligible, so we want the numpty unclever delta -> ∆ swap in all cases.

Companion ticket to https://github.com/pombase/website/issues/612

**Comment by kimrutherford** [comment]
I've made that change and re-release Canto.  Please re-open this issue if you spot any cases where the "delta" hasn't been changed.
