### ISSUE TITLE
new gene not found

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1358]
I added a new gene SPNCRNA.1712 but I can't add it to a canto session (not found)

**Comment by kimrutherford** [comment]
Sorry, it's there now.  I got distracted so for the last 2 weeks I forgot to update Canto to point to the latest Chado.  It's not automated yet.

**Comment by ValWood** [comment]
We can ping you if we need it ;) You can keep being distracted...

**Comment by Antonialock** [comment]
yeah no worries
