### ISSUE TITLE
alleles of type "other"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1361]
The standard allele types are
amino_acid_mutation
 deletion
 disruption
 nonsense_mutation
 nucleotide_mutation
 other
 partial_amino_acid_deletion
 partial_nucleotide_deletion
 unknown
 unrecorded
 wild_type

During the PomBase load we create a log file of all of the allele types described as "other"

The file is here
https://curation.pombase.org/dumps/builds/pombase-build-2017-11-12/logs/log.2017-11-12-21-23-09.alleles_of_type_other

The plan is to create new "types" for those which are frequently used

We have some new proposed allele types (and merges  where we split unecessarily):
https://github.com/pombase/canto/issues/1275

https://github.com/pombase/canto/issues/976 (diploids we plan to handle this more robustly, most of our experiments are in haploids, so it hasn't become urgent yet, may need  for PHI-Canto?)

Please add  any "new types required for PHI BAse to this ticket"

@CuzickA @Hammond-Kosack

**Comment by mah11** [comment]
also see #1275

**Comment by ValWood** [comment]
transferred to 
https://github.com/PHI-base/curation/issues/5
