### ISSUE TITLE
error unless you supply an orcid

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1363]
currently the tools is throwing an error unless you supply an ORCID

Internal error
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::SQLite::st execute failed: UNIQUE constraint failed: person.orcid [for Statement "INSERT INTO person ( added_date, email_address, name, orcid, role) VALUES ( ?, ?, ?, ?, ? )"] at lib/Canto/Track/CuratorManager.pm line 236
There has been an internal error. The problem has been logged and will be investigated.

https://curation.pombase.org/pombe/curs/035eff8fcdafd45c/assign_session

**Comment by kimrutherford** [comment]
I think I've fixed this.  Please let me know if you see it again.

Fixed by d3cb7639e4d8fa5b01fc4ba215d
