### ISSUE TITLE
triage options and PMIDs

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1365]
@CuzickA  will supply a set of triage options 
(are triage options  in a config file ?)
(Alayne remember that the triage options are mutually exclusive)

@CuzickA  will supply a list of test publications. The PHIBAse triage is currently quite complicated. We should discuss this on a future call.
 For starters can we import  from a list?

**Comment by ValWood** [comment]
Alayne also mentioned that PHI-Base molecular interactions collaborators curate in "batches"
It would be nice to  be able to "label" paper as being in a specific "batch"

**Comment by kimrutherford** [comment]
> are triage options in a config file ?

Yes, sort of.  The options are in the config file, but they are written into the database when a new Canto instance is created.  Henry's test Canto will have the PomBase options.

The triage options can be added to the Canto database after the instance is created but it's easier to get them sorted out up front as much as possible.

> For starters can we import from a list?

Yep, there a tool that comes with Canto that can load publications given a list of PubMed IDs.

**Comment by ValWood** [comment]
transferred to https://github.com/PHI-base/canto/issues/6
