### ISSUE TITLE
query about relationship directions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1371]
FYPO Canto suggestion “long mitotic spindle during anaphase” suggests abnormal mitotic spindle disassembly

this seems wrong

@mah11  h ow are these related?

Over the holidays I'll look at this and other examples and see if I can figure. We can discuss after hols....

**Comment by mah11** [comment]
It's disassembly, not assembly:

FYPO:0004620 ! abnormal spindle disassembly has_output FYPO:0004438 ! long mitotic spindle during anaphase

i.e. the ontology says that if spindle disassembly is abnormal, the spindle will be long in anaphase
(but there could be another way to get a long spindle in mitotic anaphase).

But I'm not sure that's correct - if disassembly is earlier (premature) or faster (increased rate) than normal, that's abnormal but wouldn't leave you with a longer-than-normal spindle. I also haven't tracked down what prompted me to include the has_output link, which makes me suspicious. It would be easy enough just to remove the link.

**Comment by ValWood** [comment]
yeah lets do that, seems safest.

**Comment by mah11** [comment]
OK, done. Don't know if there's anything else for this ticket ...

**Comment by ValWood** [comment]
don't think so...
