### ISSUE TITLE
change in "conditions" box

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1372]
looked like this just?

![condition](https://user-images.githubusercontent.com/7359272/34174722-cd0b0ea4-e4f1-11e7-9f3b-a05ab69c4471.jpg)

**Comment by Antonialock** [comment]
what are you suggesting?

**Comment by ValWood** [comment]
The conditions box looks different (scroll bars?)

**Comment by kimrutherford** [comment]
Which browser was this and do you still see the problem?

**Comment by ValWood** [comment]
Never seen it since....
