### ISSUE TITLE
reported session number

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1377]
This says 

sessions 6"

but there are only 4  showing?
https://curation.pombase.org/pombe/view/object/person/371?model=track

**Comment by kimrutherford** [comment]
Sorry, that's confusing.  The "6" is the number of sessions that the user has ever had, including those which were then re-assigned to someone else.  The table shows only the user's current sessions.

Should I change the way the "6" is calculated to make them match up?

**Comment by ValWood** [comment]
no worries, that's fine....we can think about this further in the distant future if we make other changes to the admin interface...
