### ISSUE TITLE
confusing extension options

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1379]
might be a configuration issue, but I found this confusing yesterday:
I didn't understand the difference between affected protein and assayed protein in this context.
(it was a loss of binding phenotype)

![extension](https://user-images.githubusercontent.com/7359272/35732079-0ae62d30-0810-11e8-9f0b-39e33edbce14.jpg)

**Comment by mah11** [comment]
there's a bug aspect to it, covered by #1373
