### ISSUE TITLE
interaction interface improvements

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1380]
ain't alliteration awesome?

On a tangent from something else, we decided to ask for a big change and a small change to the interface for adding physical or genetic interactions.

Big change: make what is now the "quick add" version the only interface for adding interactions (and therefore not admin-only). It's much more intuitive than stepping through from gene to gene to evidence one page at a time, it's easier to correct directionality, and it'll save space because we won't need the wall of text drawn from the documentation about directionality.

Small change: move the evidence code pulldown so it's between the "gene" and "interacting gene" pulldowns. That way it flows kind of like a sentence in English, e.g. yfg1 affinity captures yfg2.

Let us know if you have problems, questions, pithy observations, etc.

**Comment by ValWood** [comment]
could we do the small change, and punt the larger change?

**Comment by kimrutherford** [comment]
The one thing that's possible in the step by step interface that isn't possible in the dialog box is that you can create multiple interactions at once.  Is that a big loss?  If not, swapping to using the dialog box is just a matter of changing what the link does.

![interactors](https://user-images.githubusercontent.com/90474/38784531-5db2783a-4167-11e8-8756-7806fa290a00.png)

**Comment by ValWood** [comment]
Personally I don't mind not being able to create multiple interactions at once, since I always found that a bit confusing (and there are not so many to curate).
Anyone else?

**Comment by mah11** [comment]
agree, no loss - it's easy enough to use the duplicate/edit feature

**Comment by Antonialock** [comment]
no objections

**Comment by kimrutherford** [comment]
OK, I've removed the quick links for interactions and the main links now pop up the quick add dialog.

I've released the change in the main Canto.  Could you check that it's doing what you wanted?

**Comment by mah11** [comment]
Yes, working nicely. Thanks!

**Comment by kimrutherford** [comment]
> Yes, working nicely. Thanks!

Great.  Thanks for checking.
