### ISSUE TITLE
update SO

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1382]
I can't see SO:0002207 in canto

**Comment by kimrutherford** [comment]
> SO:0002207

Sorry about that, SO wasn't being updated in Canto.  It should be OK now.  I wasn't sure where to look in Canto to check.

**Comment by ValWood** [comment]
could you check and close.
v

**Comment by kimrutherford** [comment]
It's there now.

**Comment by Antonialock** [comment]
yep
