### ISSUE TITLE
Lots of random PMIDs

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1383]
I just did the triage , there were ~24 papers which seemed a lot since I did it a couple of days ago. However non of them were pombe (that's not so unusual, but they didn't appear to be very related to pombe, and most of them were old).

It is possible that PubMed have done some retro-fit of keywords, but these did all look a bit random (they were not totally random, they were cell biology).  I wondered whether to have a more detailed look at a couple of the papers, but before I do has anything changed that might affect which papers are pulled in?

**Comment by ValWood** [comment]
OK it must be some Pubmed thing...

**Comment by Antonialock** [comment]
I think they once in a blue moon do like a batch volume from a journal that hasn't been fully indexed (I remember requesting a PMID from an unindexed journal and they said they would start on it, but starting with the newest issues)
