### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1385]
I want to capture that mutant in one gene abrogates binding of a different protein to telomerase RNA.

I used decreased RNA binding.
I can only capture  one object in the  extension.
Either a protein, or a transcript, but not both

What do we need to do to the config here?

**Comment by ValWood** [comment]
> There's always the nuclear 

yes that was my plan. I wasn't sure what it  was supposed to do right now though...it's a bit of an edge case anyway...

**Comment by kimrutherford** [comment]
I've put this on my to-do list for the morning.

**Comment by kimrutherford** [comment]
I forgot to ask: which term were you annotating with?

**Comment by kimrutherford** [comment]
> It probably has to do with the way it works behind the scenes, where the gene ID gets used wherever
> the config has "ProteinID" or "TranscriptID" 

Sounds like it.  Probably the same problem as: #1354

**Comment by ValWood** [comment]
"decreased RNA binding"

**Comment by kimrutherford** [comment]
Yep, it's the same problem as #1354 

This configuration is triggering the problem:

    FYPO:0001092-is_a(FYPO:0000702) is_a    assayed_using   ProteinID   assayed protein ...
    FYPO:0002131                    is_a    assayed_using   TranscriptID|SO:0000673  assayed transcript ...
