### ISSUE TITLE
identical alleles

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1388]
Yesterday, as I was changing allele names of exiting alleles to remove WT construct I was able to create what were apparently identical alleles:

For example
![identical alleles](https://user-images.githubusercontent.com/7359272/36594021-553107c2-1894-11e8-8a6c-b01c0d886125.jpg)

I fixed by transferring the 3 annotations to the original allele and deleting the duplicate, but it would be better if this was prevented?

**Comment by kimrutherford** [comment]
> but it would be better if this was prevented?

I think this is the same problem as #1130
