### ISSUE TITLE
is the pub med updating running

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1390]
I haven't needed to triage for a while, no new papers, (but I know there are.....)

**Comment by kimrutherford** [comment]
Sorry, I noticed this while we were changing to the new server but forgot to look into it.  I'll do that today.

**Comment by kimrutherford** [comment]
I've fixed the code and I've run it on the pombe Canto - 11 publications were added.

**Comment by ValWood** [comment]
Triaged up to date...lots of new people working on pombe......
