### ISSUE TITLE
missing annotation in canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1393]
I curated this last week (an Juan had already done some annotation)
http://curation.pombase.org/pombe/curs/3233320f8849c7ea

but I no longer see it?

Is it still somewhere ?
(only the GO data seems to be loading for me...I left it a  few minutes, because there is an accompanying spreadsheet that I thought good be hampering, but nothing has appeared)

**Comment by kimrutherford** [comment]
What other annotation did you add to the sessions?  Phenotypes?

**Comment by ValWood** [comment]
Ignore me.... i forgot about that one. I thought i was looking at this one!
http://curation.pombase.org/pombe/curs/bf9cd1928a11ab87
