### ISSUE TITLE
background  decisions needed

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1395]
I reviewed  and tidied the backgrounds here
https://github.com/pombase/curation/issues/1957

Curation of backgrounds is problematic, largely because we include it as part of the genotype, but we do not capture consistently.

One of the  reasons that we exclude, is that often the same allele is used with different backgrounds and it is time consuming to  add all of the alleles without and with different backgrounds.

For example
![example2](https://user-images.githubusercontent.com/7359272/37913336-8b81b282-310c-11e8-8031-3cc3fbd333f1.jpg)

1. Biologically, background is part of genotype

2. Background is useful, but generally it is useful to people when considering if a strain can be used for a different experiment, not to interpret the experiment per se (although  for the experimental construct ones this is useful, just to know how the experiment was done).

3. Even if we collect background (which we should), it does not need to be included  as part of the genotypes we display and group by.

I would prefer as a solution:

1. Background can still be stored associated with the genotype (we could  have some notation behind the scenes "full genotype" vs  "displayed genotype". The background would be a string associated with the full genotype). 

2. We capture background at annotation time (preferably using a "look up" similar to "condition" where backgrounds that have previously been used in a session are available.

This would have 4 benefits
1. It would simplify the genotype interface, which is arguably the most complicated part
2. It would encourage us to capture backgrounds  (they are useful) 
3. It would make it less important that the background is not always consistently captured (it never will be, historically we have missed lots and will probably continue to do so)
4. It would make the  background syntax more consistent, where we have captured) if they  wanted by people later (for example metabolomics people might want to include them in downloadable datasets
5. It would improve the grouping by phenotype if we ignore background for this  purpose (already requested anyway https://github.com/pombase/website/issues/284) At the moment it is a string and  
x | ura4-D18 leu1-32
would make a different genotype to
x | leu1-32 ura4-D18 

Does anyone have any objection to this? If so we need a pragmatic alternative.
We need to make a decision this week because Kim will need to begin the genotype interface revisions after Easter. Quite a lot of Canto work is required  urgently so that the PHI-BAse project can continue.

Hopefully we can nail this down on Thursday.
Once this is decided I can go back to the mock-up and revise.

**Comment by ValWood** [comment]
or not.....;(

**Comment by ValWood** [comment]
One option:

Be able to specify the background, with alleles
This will require a new table.

This also includes h+ h- h90 which would  need to be specified somewhere

need to fill in my notes here with options...

**Comment by ValWood** [comment]
Here are 2  options:

option 1


![option1](https://user-images.githubusercontent.com/7359272/38797076-49cbbb5e-4155-11e8-86bd-6d1061b7765c.jpg)

List Pros and Cons here
Cons
Would slightly impinge on the new "rapid deletion" adding, since we would need an additional checkbox

**Comment by ValWood** [comment]
Option 2
![option2](https://user-images.githubusercontent.com/7359272/38797116-6ea5bce0-4155-11e8-9c5a-a9c17bd67375.jpg)

Option2 would involve another link "background management"

Pros
It would keep genotype management streamlined, and be much simpler (especially in cases where no  background is curated, as is often the case)

Cons

**Comment by ValWood** [comment]
option 3

stay more or less as we are but with more "controlled alleles"

Pros
-

Cons
-

**Comment by mah11** [comment]
Option 3 is the only one where I feel like I fully understand how it would work. It would be fine for me. If you go with any variation of options 1 or 2, I'll adjust with time once it's deployed, but probably won't be able to contribute much to developing it.

**Comment by ValWood** [comment]
how would  option 3 work with quick add deletion?

**Comment by ValWood** [comment]
@mah11 To me option 2 seems the clearest and simplest workflow, and has advantages over both of the other 2 methods...it would be useful to know what you find confusing about this option so that we could  improve it.

**Comment by ValWood** [comment]
I still think with "option 3" I would be inclined to exclude backgrounds....

**Comment by mah11** [comment]
> what you find confusing about this option (2)

Option 2 appears to decouple the background from the rest of the genotype. If so, I don't understand how it squares with "background should be part of genotype". On the other hand, if it doesn't decouple, there's some other level on which I don't get it.

I also don't see how it streamlines procedures.

**Comment by ValWood** [comment]
Thoughts:

Option 2 does decouple the background from the genotype in the database.
The database is not the place where we are trying to model biology, we are only *storing* things in the database in a  way that they will be the most accessible and useful. The schema doesn’t absolutely need to represent the real life relationship between the  “genotype of interest” and the “background”, if these 2 pieces of data are required  “decoupled” more often than coupled (If we want them “coupled” we can easily  put them together). The current  schema implementation shouldn’t be a reason not to make the changes under consideration here.

The primary  consideration is the workflow,  if there is an added bonus that the management of the data  for display on the website is made easier, that is an added bonus (but again this is a secondary consideration).

That said, I am leaning towards “option 3” because it  will be quicker to implement. I  would still be discouraged from adding genotypes in this workflow, but it will be less upheaval.

However, I am not quite sure how this would work in the new single allele multi allele background implementation.
Obviously any background alleles in the “single also genotypes” will propagate to the multi allele genotypes. If these backgrounds were not included, a new single allele genotype is created  without the background.
It might be confusing how to construct a multi allele genotype if a new background it introduced, which is not in any of the “single allele genotypes”? 
My other issue with this is  that as requires an extra column , might be more of an issue for PHI BAse where we already have additional columns for species and strain.

If we can negotiate these issues, I think we could go with 3  at least for now…

**Comment by ValWood** [comment]
> I also don't see how it streamlines procedures.

adjusted this comment. I mean simpler/ less cluttered

**Comment by ValWood** [comment]
For now we do option3 because it's easy
Step 1. add an add/edit background in the side menu

a) any background in a single mutant will be included in the "multi allele genotype" if  selected
b) if  the same backgrd is included in  more than one contributing allele, remove redundant copies (at first it will be schmoosed together)

**Comment by ValWood** [comment]
OK, closing this, replaced by #1407
