### ISSUE TITLE
Fix warning from etc/test_initialise.pl

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1396]
James Seager pointed this out:

    Use of uninitialized value in string ne at /usr/local/share/perl/5.26.1/PomBase/Chobo/OntologyConf.pm line 84.
    Use of uninitialized value in concatenation (.) or string at /usr/local/share/perl/5.26.1/PomBase/Chobo/OntologyConf.pm line 86.
    "def:" line differ

    versus:
      X part_of Y if X is a subregion of Y. at /usr/local/share/perl/5.26.1/PomBase/Chobo/OntologyConf.pm line 86.
    Creating database for 0_curs
    Creating database for 1_curs

**Comment by ValWood** [comment]
I put admin label on this, not sure if that is correct.

**Comment by ValWood** [comment]
I'll put next on this so if it is quick we can get it out of the way.

**Comment by kimrutherford** [comment]
@jseager7 I've fixed this bug in Chobo (https://github.com/pombase/chobo).

It's only triggered when the same term is read from two OBO files, but in one of the files the term has no definition.  So hopefully it's going to be rare.

I've updated the base Docker image to include the fix.  The scripts like `canto_docker` now use the new base image.  So next time you "git pull" you should get the fix.
