### ISSUE TITLE
globally change expressivity to severity

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1398]
from
https://github.com/pombase/curation/issues/1507
changes need to occur simultaneously in
i) Canto
ii) Chado
iii Website
iv) documentation

**Comment by ValWood** [comment]
probably should figure out how/when to do this  (next call)

(@Antonialock  let us know if you mention in NAR paper, if so it should happen before this)

**Comment by Antonialock** [comment]
No I didn't, should I?

**Comment by ValWood** [comment]
Not particularly. I just thought that if " expressivity" appeared anywhere (screenshots and the like),
we should wait until after the change to make the screenshot...it wouldn't really matter, but...

**Comment by Antonialock** [comment]
ah fair enough.

**Comment by ValWood** [comment]
should we action this? Requires coordinated changes.....

**Comment by kimrutherford** [comment]
> should we action this? Requires coordinated changes.....

I think it's just a matter of picking a date.  Canto would need to be offline for a while.  Hopefully just 10-20 minutes unless something goes wrong.  The main website will change when the nightly update goes live so there won't be any downtime.

**Comment by ValWood** [comment]
Another user has found "expressivity" confusing. SO we have clocked up quite a few now that we know about. MAybe this would be a good ticket to push through...

**Comment by kimrutherford** [comment]
> MAybe this would be a good ticket to push through...

I'll get the changes ready to go and then when can pick a day.  I'll need help with the documentation changes.

**Comment by kimrutherford** [comment]
There were only a few places in Canto that need changing, mostly the extension config file.  The changes are ready to check in.

There are data files in SVN that use "has_expressivity()" as a relation.  I've changed them.

@mah11 Could you have a look at pombe-embl/mini-ontologies/fypo_extension.obo ?  There are terms like "variable expressivity".

We'll need to coordinate when commit the changes to switch over.  Probably some Friday afternoon would be best because it will give me a few days to fix problems.

**Comment by mah11** [comment]
> Could you have a look at pombe-embl/mini-ontologies/fypo_extension.obo

Yup - done locally, and ready to commit.

> I'll need help with the documentation changes.

I'm happy to do the Canto user documentation and website documentation. Again, just pick a day -- I could even have it ready by the end of today if we're that keen.

**Comment by kimrutherford** [comment]
> I could even have it ready by the end of today if we're that keen.

If you're keen today is good for me.

**Comment by mah11** [comment]
> If you're keen today is good for me.

OK, will do! I'll comment again here when all the changes are committed, even though you'll probably be asleep by then.

**Comment by kimrutherford** [comment]
Thanks!  I'll commit my changes in the morning (my time) and fix any problems with the load over the weekend.

**Comment by mah11** [comment]
All done!

I've committed changes to:

website/src/docs/:
./documentation/gene-page-phenotypes.md
./documentation/phenotype-data-bulk-upload-format.md
./downloads/phenotype-annotations.md
./faq/what-is-an-annotation-extension.md

pombase-config/:
./canto/annotation_ex_config/FYPO_A_E_config
./website/pombase_v2_config.json

canto/root/docs/fypo_annotation.mhtml

pombe-embl/mini-ontologies/fypo_extension.obo

**Comment by ValWood** [comment]
We should announce this just so people know. I would add the announce lablel but it isn't available for the Canto tracker and not worth adding for only one.

**Comment by kimrutherford** [comment]
Thanks for all the fixes Midori.

I've made the code and config changes for Canto, Chado and the website.  I've also changed "has_expressivity" to "has_severity" in the Canto database.

There are two sessions that mention expressivity in an annotation comment.  When I changed the database I didn't change comments.  The comment in both cases is:
`strong phenotype = has_expressivity(FYPO_EXT:0000001)`
And the sessions are 2f1c2ad9160b5b20 and e2d5c2adaa68d91d

I delayed the overnight load until the Canto changes were done.  It's running now and should finish by mid morning (UK).  I'll check everything's OK then.

**Comment by kimrutherford** [comment]
> It's running now and should finish by mid morning (UK). I'll check everything's OK then

It failed because there was an input file I missed that was still using "has_expressivity".  I've restarted the load.

**Comment by kimrutherford** [comment]
Everything seem OK now.  Canto is using has_severity and has_expressivity is gone from the website:
https://www.pombase.org/reference/PMID:7262540

Midori, I needed to edit fypo/supplemental_files/fypo_extension_relations.obo to change has_expressivity to has_severity.  I didn't update the definition.  Could you have a look?

**Comment by mah11** [comment]
> Everything seem OK now.

Hooray!

> I needed to edit fypo/supplemental_files/fypo_extension_relations.obo 

I'd forgotten about that one, so thanks! I've edited the definition.

**Comment by mah11** [comment]
I think this is all done now - and nothing has caught fire in over three weeks. Closing :)

**Comment by kimrutherford** [comment]
I noticed that I had a bunch of local Subversion changes that I hadn't committed.  I have now.
Mostly I had changed "Expressivity" to "Severity" in the headers of the PHAF files.  That doesn't make any difference to loading because the column names are ignored but I wanted it to be consistent.

Midori, I also changed the occurrences in external_data/phaf_files/in-progress/proto-phaf_JL-RCS.csv
