### ISSUE TITLE
Allow configuring project specific logos

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1399]
Currently we have the Canto sponsors at the bottom of each page.  The PHI-base canto will need additional logos.

**Comment by kimrutherford** [comment]
I've added an extra optional configuration item to allow adding extra sponsor logos.

There is now an `extra_sponsors` list.  Here's an example to try in `canto_deploy.yaml`:

    extra_sponsors:
       - link_url: "http://www.rothamsted.ac.uk"
         logo_url: "https://www.rothamsted.ac.uk/sites/all/themes/site_theme/images/rothamsted-logo-175.png"

@jseager7 @barnabynorman: Could you give that a go?

**Comment by jseager7** [comment]
I've now tested the configuration on my Vagrant box and it works correctly, in that it finds the logo and displays it. Only problem is, the divider enclosing the logos doesn't have a maximum specified height, so the logo is displayed at its native resolution, which is too large in this case:

![logo_sizing](https://user-images.githubusercontent.com/37659591/38984496-b8b7b5b6-43be-11e8-8e2d-8d12fa4eef9a.PNG)

@kimrutherford – Looking at the Mason template, I think I can fix this quite easily by adding some extra style rules to the `#footer` selector in `root/static/css/styles.css`. Should I open a new issue for that?

**Comment by kimrutherford** [comment]
I think the logos will look better if we scale them down to the right size in advance rather than relying on the browser to do it.  Some of the logos we need are here:
  https://github.com/PHI-base/canto/tree/master/root/static/images

I think the PHI-Canto specific logos should be store outside of Canto and linked to rather than being checked in.

**Comment by jseager7** [comment]
Alright. I'll take a copy of the logos for Elixir UK, PhytoPath, and BBSRC, and I'll just try linking to them from my file system for now for testing.

**Comment by kimrutherford** [comment]
> I'll take a copy of the logos for Elixir UK, PhytoPath, and BBSRC, and I'll just try linking to them
> from my file system for now for testing.

Great.  @martin2urban has set up a cloud server for testing PHI-Canto.  You will be able to host them there once a web server is up and running there.

**Comment by jseager7** [comment]
I've managed to obtain original or high resolution copies of the logos for all of the following organisations:

- BBSRC
- Elixir UK
- PhytoPath
- Rothamsted Research

The only one I'm missing is an original copy of the PHI-base logo, but we can worry about that later, once the test server is set up. I'm closing this issue for now; we can re-open it or create a new issue when it's time to add the logos to PHI-Canto.
