### ISSUE TITLE
Add a test harness for the frontend code

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1400]
There are tests for the Perl code but none for the Javascript.

We should add:

  - a test framework
  - a script to run the tests - we'll run that with Jenkins on each check-in
  - some example tests for some of the simple controllers

We'll add more tests over time.

**Comment by kimrutherford** [comment]
From @barnabynorman:

> I also got the server working this morning based on the file you sent over
> Kim. It fails on vagrant authentication, but appears to work fine and I can
> start the server / modify the source etc and browse the application.
> 
> I built the test harness, which I have committed and pushed. I put a very
> simple test in there so you can see it working. You will need npm
> installed, then install dependencies (karma / jasmine etc):
> 
> npm install
> 
> To run the tests:
> 
> karma start
> 
> I did not spend much time on it so far, but tests including the module fail
> due to the module dependencies - I will look again on Monday and report
> back.

**Comment by barnabynorman** [comment]
I have updated the harness to include dependencies and started writing some unit tests
