### ISSUE TITLE
canto activity summary

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1401]
I didn't receive on since 9th April.....?

**Comment by kimrutherford** [comment]
Er, me neither.  Very odd.  I'll look into it.

**Comment by kimrutherford** [comment]
I'm still working on this.  I wondered if Canto or oliver1 was haven't problems sending email but I get an email when I assign a session to myself.  I'll keep digging in the logs.

In the meantime, if you'd like to see the daily summary, go to: http://curation.pombase.org/pombe/tools/daily_summary
(then make a cup of tea - it's a bit slow)

You can also see previous summaries by adding a date to the URL:
  http://curation.pombase.org/pombe/tools/daily_summary/2018-04-16

**Comment by ValWood** [comment]
nice ..I can delete the e-mails ;)

**Comment by kimrutherford** [comment]
The emails have started again.  I don't know why.  :-(
