### ISSUE TITLE
Show host and pathogen genes separately when editing genotypes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1403]
In pathogen/host mode, when there are host genes, a second gene table containing the host genes should appear on the genotype management/edit page.  This list shouldn't appear until the user selects which host organism they are interested in.

**Comment by kimrutherford** [comment]
I've made some progress on this.  I initially thought it would be a good task for @jseager7 and @barnabynorman.  I had a look at the code and it wasn't great.  While improving it I've added some support for having a separate list of genes for pathogen and host.

I've removed some of: root/curs/genotype_manage.mhtml and its controller, GenotypeManageCtrl
and moved things into two new directives: genotype-genes-panel and genotype-gene-list

**Comment by kimrutherford** [comment]
When I attempted to demonstrate this to James and Barnaby a week ago I hit a bug.  I've now fixed that so it works like the screenshots below.  If there is more than one pathogen gene it will show a dropdown for pathogens too.  At the moment the host drop-down doesn't show hosts that have no genes.

![host_path_genotype_gene_split_1](https://user-images.githubusercontent.com/90474/39741950-df5487b8-52ef-11e8-8038-20a99b80296e.png)
![host_path_genotype_gene_split_2](https://user-images.githubusercontent.com/90474/39741952-e2e538a0-52ef-11e8-82b5-1928ff51a2af.png)

**Comment by kimrutherford** [comment]
> At the moment the host drop-down doesn't show hosts that have no genes.

This can be fixed by using the new web service from #1448.

**Comment by kimrutherford** [comment]
>  At the moment the host drop-down doesn't show hosts that have no genes.

I think this would be a good task for @jseager7 and @barnabynorman to have a go at.  It's relatively small and self contained so it's a good task for getting up to speed on the front-end code.

**Comment by barnabynorman** [comment]
@kimrutherford I have added a service to get the organisms list, but it seems to respond with:
`{pathogen_or_host: "unknown",`
before the species list. Did I miss something in the request / is this an error?

**Comment by kimrutherford** [comment]
> Did I miss something in the request / is this an error?

It will return "unknown" for all the organisms unless Canto is in pathogen-host mode.

You'll need to set `host_organism_taxonids` and add some organisms to the database.  There is now some documentation about that setting:
https://curation.pombase.org/pombe/docs/canto_admin/configuration_file#host_organism_taxonids

If you're getting "unknown" after setting `host_organism_taxonids` - that's a bug.

**Comment by kimrutherford** [comment]
If you're in pathogen-host mode and you have entered some pathogen genes and some host genes then your gene confirmation page should be split pathogen-host like this:

https://github.com/pombase/canto/issues/1414#issuecomment-387298107

**Comment by jseager7** [comment]
With regards to this:

> you have entered some pathogen genes and some host genes

Could you remind us how pathogen genes are determined? Is it just that every organism that isn't specified as a host in `host_organism_taxonids` is assumed to be a pathogen?

**Comment by kimrutherford** [comment]
> Is it just that every organism that isn't specified as a host in host_organism_taxonids is assumed
> to be a pathogen?

Yep, that's it.  I should have been more clear.

**Comment by jseager7** [comment]
Closing this now, since I think this should have been closed ages ago, and most of the changes are going to be reverted by #1555.
