### ISSUE TITLE
formatting improvements for genotype management

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1406]
example session

https://curation.pombase.org/test/curs/2cc43eb21aa04239/genotype_manage#/select/11

- [x] put 
Single allele genotypes (Mouse over genotypes for more actions)
all on one line

- [x]  The expression section could be compacted if, at the point of selection you saw:

Overexpression  (OP)
Wild type product level  (WT)
Knockdown Null  (KD)
Not assayed (UNK)
Null (Null)

 (or similar) and then show only abbreviations in the table...Header could be Exp.
(these abbreviations are universal)

**Comment by ValWood** [comment]
@mah11 @Antonialock  I think this is all outstanding ?

**Comment by kimrutherford** [comment]
> Put Single allele genotypes (Mouse over genotypes for more actions)
> all on one line

That's done now.

> The expression section could be compacted if, at the point of selection you saw:

Just to check, do we definitely want to do this?

**Comment by kimrutherford** [comment]
The column heading is "Expression" so the column won't get narrower than that unless we change the heading too.

Instead of abbreviations, would it be enough to change "Wild type product level" to "Wild type" as that's the longest expression text?

**Comment by mah11** [comment]
To the modest extent that I have an opinion, I like Kim's suggestion better. For wild type we could include "level" to avoid any hint of confusion with the allele ("wild type level"), but I won't scream if we don't.

**Comment by kimrutherford** [comment]
"wild type level" is a shorter string than "overexpression" so it makes sense to include "level".

**Comment by ValWood** [comment]
Yes go with that. ....

**Comment by kimrutherford** [comment]
I've changed "Wild type product level" to "Wild type level" in the test Canto.

All done here?

**Comment by Antonialock** [comment]
looks like it
