### ISSUE TITLE
Implementing backgrounds in genotype management

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1407]
test session
https://curation.pombase.org/test/curs/2cc43eb21aa04239/genotype_manage#/select/11

We decided for now to go with the simplest option,  to get the pending changes through.
The discussion is here:
https://github.com/pombase/canto/issues/1395

For now we do option 3 because it's easy

There is a minor change that instead of adding the background whilst creating the allele, it can be optionally added from the side menu.
This won't actively encourage background addition, but we only really want to include the background when it's critical for experiement interpretation anyway....

- [x] Add an "add/edit background" in the side menu (it is still possible to do background in copy edit, otr edit)
- [x] Include background column in table

Behaviour:
a) any background in a single mutant will be included in the "multi allele genotype" if selected
b) if the same background is included in more than one contributing allele, remove redundant copies (at first it will be "schmoosed" together)

@mah11 @kimrutherford  did I miss anything?

**Comment by ValWood** [comment]
I saw this this morning when I was demoing.
If @Antonialock  and @mah11  are OK with it I suggest we take to live as soon as possible.

@mah11  could you update docs  and then we should announce this as a major change to Canto on pombelist  and encourage those who have bailed to try again.

**Comment by kimrutherford** [comment]
Could you have a go at a complex genotype + phenotype in the new interface?  It's also probably good to check that genotype editing is still OK and have a look on the front page to make sure the genotype looks right in an annotation.  Thanks!

I've tested things but I'm sure I don't do things the way you would.

Once everything's ready to go, I'd prefer to release it on a morning when one of you have time to do some real life phenotype curation as a live test.

**Comment by ValWood** [comment]
doing a real life paper in test now...

**Comment by kimrutherford** [comment]
> doing a real life paper in test now...

Thanks.  If you find any bugs or problems, I'll try to fix them before the morning so we can get on with releasing.

I've just noticed noticed some odd warnings in the Canto server logs.  I'll investigate those.  Here's a sample.  These two warnings seem unrelated to each other and unrelated to the genotype page changes, but I'll check.

    [error] Caught exception in engine "UTF-8 "\x80" does not map to Unicode at /usr/share/perl5/Catalyst.pm line 3665."

and:

    Use of uninitialized value $evidence_code in string eq at lib/Canto/Chado/OntologyAnnotationLookup.pm line 308.

**Comment by ValWood** [comment]
Lets go for  it! seems to work like a dream. I curated a paper, single alleles multi alleles, all good...much quicker..... thanks!

**Comment by kimrutherford** [comment]
> Lets go for it!

Great.  Thanks for checking it out.  I'll update the main Canto ready for Thursday (UK) morning.

**Comment by kimrutherford** [comment]
> I'll update the main Canto ready for Thursday (UK) morning.

Done!  It all works for me.  Please let me know if you have any problems.
