### ISSUE TITLE
future: fuzzy lucene searching

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#141]
Not sure if fuzzy is the right word to use, however, when searching GO terms it usually does not matter if a term is slightly misspelled, the search is usually clever enough to understand what you want.

This is not the case however when searching FYPO, and results can be wildly different. I've noticed this for a quite a few terms and for me it is just mildly annoying \(but admittedly user error...\) however I think it could have implications for future community curators who are not native english speakers. Any way to improve this?

Original comment by: Antonialock

**Comment by ValWood** [comment]
consider with
https://github.com/pombase/canto/issues/584

**Comment by ValWood** [comment]
I'll close this but tag a comment to 
https://github.com/pombase/canto/issues/584
