### ISSUE TITLE
Allow the use of ontology subsets in canto to restrict conditions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1412]
related to
https://github.com/pombase/canto/issues/1411

conditions defined the subset grouping_terms for terms should not be visible in the tool

~@Antonialock  can you add the subset tag details~

**Comment by mah11** [comment]
Canto already does this - see #1122

**Comment by kimrutherford** [comment]
I think I've fixed this.  It was a configuration problem.  Please let me know if it looks OK.

**Comment by ValWood** [comment]
Does this work? @mah11  I can't remember what it is?

Lets say it does...

**Comment by mah11** [comment]
yep, fixed
