### ISSUE TITLE
Fix the Canto UniProt XML loader to retreive the gene name

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1415]
(Moved from https://github.com/PHI-base/canto/issues/3 and re-opened)

Here is a sample XML file:
  https://github.com/pombase/canto/blob/master/t/data/uniprot_lookup.xml

The line to change is:
  https://github.com/pombase/canto/blob/dc35fda893eaa2aa12df8bf85fa7f34bf78d4280/lib/Canto/UniProt/UniProtUtil.pm#L70

Currently the code gets the "name" from the UniProt entry, but unfortunately that's not the gene name, it's the entry name.  We're getting that name from this line:
  https://github.com/pombase/canto/blob/master/t/data/uniprot_lookup.xml#L6

But we actually need to get the gene name from this line:
  https://github.com/pombase/canto/blob/master/t/data/uniprot_lookup.xml#L16

**Comment by kimrutherford** [comment]
> I'll test this commit on the Vagrant box. Should be able to do it later today.

Thanks.  Could you do a "make test" as well?  The tests pass for me and Jenkins so I hope it's all OK.

**Comment by jseager7** [comment]
I've confirmed that `make test` passes on the Vagrant box for commit 313512f. Sorry about the delay – got held up by a weird permissions issue where the Makefile was creating files without write permissions. I'm closing issue #1416 as well.
