### ISSUE TITLE
Prepare a file of existing PHI strains

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1418]
Perhaps separate pathogen and host files would make sense.

See discussion here about the file format: https://github.com/PHI-base/canto/issues/15

The format will be something like:

column 1: taxon ID
column 2: genus
column 3: species
column 4: strain name

We may need to get the genus and species of organisms from these files in the case where we don't have a gene in Canto for that organism.  Needs discussion.

**Comment by barnabynorman** [comment]
Data added and commited
