### ISSUE TITLE
Add the list of organisms to the front page / publication page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1425]
We need to display the (mostly host) organisms that have no genes that have been added to the session.

#### Option 1
Have a table of all pathogen organisms and a separate table of the host organisms. The organism table(s) should probably be near the gene table(s).

#### Option 2
Group the gene list by organism and include host without organisms. This could be a bit too verbose. eg.

##### Hosts and host genes:
 - Solanum lycopersicum
    - gene_1
    - gene_2
 - Solanum melongena (host)
 - Solanum tuberosum (host)
    - gene_a
    - gene_b

##### Pathogens and pathogen genes:
 - Pseudomonas syringae
   - ps_gene_1
 - Pseudomonas syringae pv. tomato
 - ...

**Comment by jseager7** [comment]
Personally I prefer Option 2, since it keeps all the information in one place, and makes it easier to see which organisms have no genes. If you had the genes and organisms in separate tables, I think it would be difficult to see which organisms didn't have genes, since you'd need to carefully cross-reference the table of genes with the table of organisms.

Having said that, I'm not a curator, and I think a lot will depend on whether users who are regularly curating the papers would rather see all the genes (and maybe all the organisms) in their own list, to make it easy to check them.

Another consideration might be how existing research papers lay out the genes and organisms that they're studying, in terms of lists and tables. If there's any sort of convention there, it might make sense to emulate that.

**Comment by ValWood** [comment]
good suggestions @CuzickA  what do you think?

**Comment by kimrutherford** [comment]
If no one has objections I'm going to have a go at implementing this using option 2.  For the single organism case I'll make sure it displays as it currently does.

**Comment by CuzickA** [comment]
Option 2 sounds good.

**Comment by kimrutherford** [comment]
> If no one has objections I'm going to have a go at implementing this using option 2.

I've done that now.  It might be that the list is too long if there are lots of organisms in the session.  We might need to have collapsible organism sections.  I'm going to close this issue.  We should open new issues for problems as we notice them.

![new-front-page-gene-section-1](https://user-images.githubusercontent.com/90474/43506745-25508c32-95bf-11e8-8c10-e214bd379fb2.png)

**Comment by jseager7** [comment]
Looks good to me &ndash; it's definitely a lot more usable when you know which organism the genes belong to. The only thing that might be missing is some explicit separation between Host and Pathogen organisms (they could be separated by columns or extra heading levels). While the researchers will probably be able to remember which organisms are the hosts and which are the pathogens, it might be confusing for reviewers if the session has the case where a usually-pathogenic organism is being treated as a host.

**Comment by kimrutherford** [comment]
> explicit separation between Host and Pathogen organisms

Thanks, I forgot that bit.  I'll fix it.

**Comment by CuzickA** [comment]
This is looking good. I agree it would be useful to have Pathogen and Host sub-headings.

Also it would probably better to display the organism 'species name' it looks like the 'common name/disease name' is being displayed. We can discuss this on Monday if needed.

**Comment by kimrutherford** [comment]
> I agree it would be useful to have Pathogen and Host sub-headings

I've made that code fix.

> Also it would probably better to display the organism 'species name' it looks like the 'common
> name/disease name' is being displayed.

I've done that too now.

**Comment by CuzickA** [comment]
Just having a look at these changes (I cleared my browser cache) and I still see

![image](https://user-images.githubusercontent.com/11753634/44001735-3320d560-9e2f-11e8-97ab-0487dbb1b46e.png)

Maybe the changes have not been pushed yet.

Talk tomorrow :-)

**Comment by kimrutherford** [comment]
The changes won't be visible until Barnaby is back as he has the keys to demo server.

**Comment by CuzickA** [comment]
OK thanks for the update. I'll close the issue.
