### ISSUE TITLE
text for physical interactions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1429]
disappeared from menu (annotation type)

**Comment by ValWood** [comment]
![text](https://user-images.githubusercontent.com/7359272/39313731-9fcaad40-496a-11e8-8fed-0c8760e802c6.jpg)

Go to bed!

**Comment by ValWood** [comment]
quicklinks is OK

**Comment by Antonialock** [comment]
fine for me in FF

**Comment by mah11** [comment]
I think I've figured it out: the text doesn't appear if you don't have "advanced mode" selected, presumably because we got rid of the non-advanced route to interactions. Antonia and I always use advanced mode, except when I go grubbing for screenshots for documentation.

**Comment by kimrutherford** [comment]
I think that's fixed now - it's working for me.  Could someone do a quick test?

**Comment by Antonialock** [comment]
I can see it both in advanced moe, and with advanced mode unchecked

**Comment by mah11** [comment]
looks good for me now, simple or advanced mode

**Comment by ValWood** [comment]
OK, I had switched advanced mode on, but not immediately  (I was using quick links), but if it's fixed that's good!
