### ISSUE TITLE
deleting existing annotations

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#143]
so, now we can get rid of the incorrect annotations we made during a session,  we need a way that a curator (or user)
can "strike through" an "existing annotation from this paper" to indicate that it needs deleting (although this would need to be confirmed during the "approval session", 

(we will also need a way to feed back to BioGRID annotations which are users have recommend removal.....)

I'll put this at low priority because we haven't needed it yet, and we can delete most existing annotations from Artemis....or directly from the database

Original comment by: ValWood

**Comment by ValWood** [comment]
This hasn't really arisen and, I can filter them
