### ISSUE TITLE
screen width

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1430]
I think we will need to look at this...a lot of the  cell biology papers I annotate have long alleles because they might be mutating (for example) lots of phosphorylation sites simultaneously...

The problem isn't only in "genotype management", it also affects the annotation view.

![annotation](https://user-images.githubusercontent.com/7359272/39329700-137554c6-4997-11e8-988e-ea3704ffe29b.jpg)

**Comment by ValWood** [comment]
We could explore a few things here:

- Whilst annotation  I wonder if you really need to see curator? it's really more useful in approval /review mode?

- very minor improvement but we  should do anyway:

rec8-7A(aaS400A,aaS402A,aaS404A,aaS410A,aaS412A,aaT414A,aaS416A)
could be (aaS400A,S402A,S404A,S410A,S412A,T414A,S416A)
only need to say aa or nt  once in an allele because amino acid and nucleotide descriptions are never mixed 

- don't display a colum if empty (i.e conditions in this session?)
I thought we used to do this (maybe not?)

- background box in multi-alleles in this session has unnecessary padding?
ombe/curs/4d3b0d5a0015df91

- I still think we need to be able to line wrap long allele names sensibly (it  is already allowed for hyphens as these are treated like grammatical hyphens. How about allowing on commas too, since most individual mutations will be comma separated?

- It seems  that the balance for line wrapping in the presentation isn't optimal. Maybe this is something that  @barnabynorman  or @jseager7  have some experience with?

- For example could the "expression" part of the allele  e.g. [not assayed] , always be on the following line if the box is over a certain width?

**Comment by ValWood** [comment]
edited previous comment.

**Comment by kimrutherford** [comment]
> What if we allow wrapping on commas too?

Here's how it looks if we allow wrapping, including after commas:

![phenotype_annotation_table_2](https://user-images.githubusercontent.com/90474/39342377-e52b51fc-4a2b-11e8-975f-667c2028e110.png)

**Comment by kimrutherford** [comment]
> don't display a colum if empty (i.e. conditions in this session?)
> I thought we used to do this (maybe not?)

Some of the columns are hidden when empty but conditions wasn't on the list.  I've just fixed that.

> "background" box in multi-alleles in this session has unnecessary padding

I can't see that.

> It seems that the balance for line wrapping in the presentation isn't optimal. Maybe this is
> something that @barnabynorman or @jseager7 have some experience with?

Good idea.  I'll have a chat to them about it.

> For example could the "expression" part of the allele e.g. [not assayed] , always be on the
> following line if the box is over a certain width?

We can allow wrapping just before the "[" in the expression.  It doesn't look too bad:

![phenotype_annotation_table_3](https://user-images.githubusercontent.com/90474/39343433-dd07e0d0-4a30-11e8-9100-35ab9576ab08.png)

**Comment by Antonialock** [comment]
not sure, maybe don't allow wrapping fr multi-gene alleles?

**Comment by mah11** [comment]
ditto - what do multi-allele genotypes look like with wrapping?

but ultimately, I don't have a horse in this race. do what you like.

**Comment by ValWood** [comment]
> It seems that the balance for line wrapping in the presentation isn't optimal. Maybe this is
something that @barnabynorman or @jseager7 have some experience with?

It seems that there should be some rule/algorithm for how best to lay out the page based on the  balance between the number of rows in  the allele column and the term column. Does such a thing exist?

**Comment by ValWood** [comment]
>>"background" box in multi-alleles in this session has unnecessary padding

>I can't see that.

You are right, it is the column header width. We could abbreviate background, but let's ignore for now and try other stuff.

**Comment by ValWood** [comment]
We could leave the line  breaking for a while. This might become more of an issue in the future as people   construct  more complicated mutants.

Does anybody  @mah @Antonialock object to  the removal of redundancy  "aa" in the allele descriptions?
If not we could do that because it would save a bit of space in a few places.

**Comment by kimrutherford** [comment]
> It seems that there should be some rule/algorithm for how best to lay out the page based on the
> balance between the number of rows in the allele column and the term column. Does such a thing exist?

I don't know of anything.

I think we should work on removing some columns or combining columns.  An example might be to combine the Term ID, Term name and Annotation extension columns and display it in one column like:

abolished homologous chromosome segregation (FYPO:0006315)
**has_penetrance** 70%

The column could be labelled "Term and extensions"

Another example might be to have an "Evidence and conditions" column.

> Whilst annotating I wonder if you really need to see curator? it's probably more useful in approval /review mode?

Removing the curator column would be helpful as it's quite wide.

**Comment by Antonialock** [comment]
> Does anybody @mah @Antonialock object to the removal of redundancy "aa" in the allele descriptions?

Yes I do. We added this for a reason so unless you need to suggest a new solution how to disambiguate nt and aa if these are removed from descriptions

**Comment by ValWood** [comment]
> Yes I do.
I'm not suggesting we remove them totally. I am suggesting that we only say it ONCE

rec8-7A(aaS400A,aaS402A,aaS404A,aaS410A,aaS412A,aaT414A,aaS416A)

could be (aaS400A,S402A,S404A,S410A,S412A,T414A,S416A)

the "aa" is there, but only once at the beginning of the string?
(it also looks more conventional)

**Comment by ValWood** [comment]
In fact, we could display it only  for amino acids when it could be ambiguous, but  that's more complicated (and would not save much more space)

**Comment by Antonialock** [comment]
Yeah that is a good suggestion for multiamino acid or multinucleotide changed mutants. 

What do we do in cases of a ‘mixed’ mutant? Eg say there is an nt change and an aa change?

**Comment by ValWood** [comment]
> What do we do in cases of a ‘mixed’ mutant? Eg say there is an nt change and an aa change?

good point, do we have any? (we would need to curate them as type 'other' anyway so
 we could be explicit in the description?

**Comment by ValWood** [comment]
I'm going to break this down into separate tickets...

**Comment by ValWood** [comment]
OK I think I got everything:

https://github.com/pombase/canto/issues/1433 for amino acid redundancy
https://github.com/pombase/canto/issues/1434 column merges
https://github.com/pombase/canto/issues/1435 hide curator column
https://github.com/pombase/canto/issues/1436 line wrapping experiments
