### ISSUE TITLE
potential column merges

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1434]
from @kimrutherford 
I think we should work on removing some columns or combining columns. An example might be to combine the Term ID, Term name and Annotation extension columns and display it in one column like:

abolished homologous chromosome segregation (FYPO:0006315)
has_penetrance 70%

The column could be labelled "Term and extensions"

Another example might be to have an "Evidence and conditions" column.

The term and extension are in the same column when you view term details on the main site so that might add consistency.

eg. from https://www.pombase.org/term/GO:0006302 :

![ext_under_term_1](https://user-images.githubusercontent.com/90474/39393355-82c458ae-4b18-11e8-8653-75b3b4d20db6.png)

**Comment by kimrutherford** [comment]
Does this suggestion make sense too, or should we just try merging term+extension?:

> Another example might be to have an "Evidence and conditions" column.

**Comment by ValWood** [comment]
I'm not *so* keen on that, still thinking.  I think it might be good to keep them separate ...especially for PHI base too.   I haven't thought about it deeply yet though, this is a 'gut feeling'....

**Comment by Antonialock** [comment]
looks fine to me. 

how about evidence code -> evidence?

**Comment by kimrutherford** [comment]
> how about evidence code -> evidence?

Good plan, especially for the GO annotation table.

**Comment by ValWood** [comment]
yup, I think this OK... difficult to judge  without a variety of sessions, but it looks good here...

**Comment by kimrutherford** [comment]
OK, I've released those changes.  Let me know what you think.

**Comment by kimrutherford** [comment]
> how about evidence code -> evidence?

I forgot that but I've changed it now.

**Comment by mah11** [comment]
Drat, I didn't see this before the change went live. Yuck.

> ...combine the Term ID, Term name and Annotation extension columns and display it in one column 
> 
> The column could be labelled "Term and extensions"

Yes to combining term name and ID, but I don't like lumping extensions with term in Canto. The name and ID can't ever be decoupled by curation, but you can easily keep a term but add or change an extension. To me it makes sense to have separate table columns for the things that are separate steps in the curation procedure.

I think it's a different situation from the web page display of annotations that have already been made and don't get changed via that interface.

> Another example might be to have an "Evidence and conditions" column.
> 
> Does this suggestion make sense too ...?

Well, I don't even like the merged term+extensions, so no, I don't want to merge evidence and conditions. They're even less coupled in meaning, the curation procedure, and other displays than terms and extensions are.

**Comment by mah11** [comment]
p.s. another thing I don't like is that it makes extensions a bit harder to spot (should one want to edit one, or consider it for duplication)

**Comment by ValWood** [comment]
- difficult to spot while editing is a good reason to keep them separate....probably should revert that....

**Comment by ValWood** [comment]
I agree that the  extensions under the terms is going to be misleading when using copy paste,
can we evert this change. an discuss tomorrow...

**Comment by kimrutherford** [comment]
I've reverted it.
