### ISSUE TITLE
hide curator column until approval mode?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1435]
Should we do this?
Usually every annotation pre-approval is done by the same person. I haven't yet seen any examples where labs swap the curator (they probably do but they haven't changed the assignee).

It probably doesn't matter so much to display it because the info will still be stored. It might be useful if there was a  way to see it, but not while  you are actively curating.

We still want to see it in review mode and approval mode.

**Comment by kimrutherford** [comment]
> It might be useful if there was a way to see it

It's a bit hacky, but you can see the curator in the dialog if you edit an annotation.

**Comment by ValWood** [comment]
That is probably sufficient. Its not really needed so its OK if it's a bit hidden...

**Comment by ValWood** [comment]
weird, but in a good way ;)
