### ISSUE TITLE
 workflow from  "add single allele phenotype"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1437]
from here you don't need to go to the "genotype management page".... shouldnt it just proceed through the old workflow 
-> ontology term selection, conditions etc

**Comment by ValWood** [comment]
i.e you can skip the step of going to the genotype management page?

**Comment by kimrutherford** [comment]
It now starts the annotation workflow after you create a single allele genotype from the gene page.  Could you give it a go?

**Comment by ValWood** [comment]
That  works.
We should discuss whether we really need the "long route" to add since everything, including drill down can be done via "quick Add"
I will open a ticket for that.

**Comment by ValWood** [comment]
It's good for new people thought. MAybe the best solution is to make "quick add" available  for everyone?
