### ISSUE TITLE
add a "quick add more genes" link

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1438]
form genotype management page....otherwise its 3 clicks  just to get back to the "add genes page"

**Comment by kimrutherford** [comment]
That's on the genotype management page right?

**Comment by ValWood** [comment]
yup, important piece of info missing!

**Comment by kimrutherford** [comment]
I think this is the same as?: #1439

**Comment by mah11** [comment]
> I think this is the same as?: #1439

yes
