### ISSUE TITLE
session admin: Sorting publications on the curator page

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#144]
copy paste from email...

It would be nice to sort the
http://oliver0.sysbiol.cam.ac.uk/test/view/object/person/21?model=track
page by more criteria

eg sort by
1. status of session (a) need approval b) approval in progress c) assigned
but not curated d) curation in progress e) accepted (or whatever order..)
2. PMID

Original comment by: Antonialock

**Comment by ValWood** [comment]
I de proritised this in Sept 2013. It isn't clear to me what still needs to be done, if anything.
The link takes me to a person page,
https://curation.pombase.org/pombe/view/object/person/753?model=track

but the current sorting seems fine.

**Comment by ValWood** [comment]
I can see now why we asked for this. It isn't really for community-type persons, since they don't have many sessions...it's for curators who have lots of sessions!
But it's covered in this ticket
https://github.com/pombase/canto/issues/1158
