### ISSUE TITLE
copy+edit enhancement

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1440]
when copying and editing a single allele mutant, instead of being taken to a page where you need to 1. click on edit and 2. confirm the modification 
i.e. this page:
![screen shot 2018-04-29 at 22 30 54](https://user-images.githubusercontent.com/12727506/39411189-07825480-4bfd-11e8-959a-4384600dcf3f.png)

it would be much more efficient to just have the popup pop up when you click copy+edit
i.e.
![screen shot 2018-04-29 at 22 31 33](https://user-images.githubusercontent.com/12727506/39411192-17efc5dc-4bfd-11e8-8e8b-e84476c9f731.png)

**Comment by kimrutherford** [comment]
The "Copy and edit" action now pops up the allele edit dialog.  Could you have a go and let me know if it's working OK?

**Comment by Antonialock** [comment]
Almost there..

would it be possible to 

1. implement the same thing for when 'editing' an allele

2. disambiguate whether you are copy+editing or just editing an allele in the header?
e.g. Allele details for byr2  
-> editing allele details for byr2 
-> copy and edit allele details for byr2 

3.
actually, it looks a bit weird to have the plain gene name there, so maybe
-> editing allele details 
-> copy and edit allele details
OR
-> editing "whatever the specified allele name is" 
-> copy and edit "whatever the specified allele name is"

**Comment by ValWood** [comment]
What is the action here? 
@kimrutherford

**Comment by kimrutherford** [comment]
> What is the action here?

Antonia's number three item above needs deciding.

**Comment by ValWood** [comment]
I don't understand 
"it looks a bit weird to have the plain gene name there"
so  @mah11  and @Antonialock  can decide !

**Comment by mah11** [comment]
> I don't understand
> "it looks a bit weird to have the plain gene name there"

This means that if you're editing an allele, the box header should include the entire allele name, not just the gene name (e.g. wee1-50, not just wee1). I agree with Antonia - better to use the allele name. I don't care whether the text includes "allele details".

**Comment by Antonialock** [comment]
Yeah allele details doesn't add much to the party

**Comment by mah11** [comment]
Change popup box header to "Editing [allele name]" (e.g. "Editing wee1-50").

If the allele is unnamed, can slot in gene name + allele description.

**Comment by ValWood** [comment]
This looks like a quick text change. we can discuss on Thursday if the action isn't clear.

**Comment by kimrutherford** [comment]
I've had a go at this.  I can now log into oliver1 so the change is deployed.

**Comment by ValWood** [comment]
@Antonialock  can you test htat this is as requested and close?
thansk

**Comment by Antonialock** [comment]
looks good except the text just says you are editing the allele, not copying and editing

<img width="523" alt="Screenshot 2019-09-05 at 13 35 48" src="https://user-images.githubusercontent.com/12727506/64342359-40e7c380-cfe2-11e9-87f0-ad6f899c039f.png">


Also the same change should happen for "edit" (only implemented for copy+edit)

**Comment by kimrutherford** [comment]
> Also the same change should happen for "edit" (only implemented for copy+edit)

I'm not sure we can do that at the moment because then there would be no way to edit the background.

**Comment by kimrutherford** [comment]
> looks good except the text just says you are editing the allele, not copying and editing

How should we word that?

Would "Editing a copy of ..." be OK?

**Comment by kimrutherford** [comment]
> Would "Editing a copy of ..." be OK?

I've done that for now.  Let me know if you'd like something different.

**Comment by ValWood** [comment]
@Antonialock  to test

**Comment by Antonialock** [comment]
thanks. I would love for 'edit' to behave the same as this 'copy+edit' but I guess we can close if that is not possible.

**Comment by Antonialock** [comment]
Just thought, why can't the background field be visible in the popup?

**Comment by kimrutherford** [comment]
> Just thought, why can't the background field be visible in the popup?

We could do that but it will require a bit of work because we can only edit allele information in the dialog currently but the background is part of the genotype.  I think this came up in another issue but I can't remember what we decided.

**Comment by ValWood** [comment]
This ticket can probably close if the problem of making the background more visible is covered by another ticket. I will look out for that. If we can't find it I think we should make a new ticket anyway with the outstanding tasks, and close this long one.

**Comment by ValWood** [comment]
Closing. Any further changes can be in new tickets. I don't think there is anything outstanding here?
