### ISSUE TITLE
config file update

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1444]
configure to prompt for "protein substrate" extensions
GO:0003755 | peptidyl-prolyl cis-trans isomerase activity

(I thought this should happen via protein modification?)

**Comment by mah11** [comment]
GO:0018193 is a BP term. For GO:0003755 you'll need an MF config entry.

**Comment by ValWood** [comment]
good point ;)

**Comment by ValWood** [comment]
OK I Needed to configure at
GO:0003755   peptidyl-prolyl cis-trans isomerase activity

GO:0003755      is_a    has_substrate   ProteinID       isomerizes              0,1     user

Did I do it OK?

**Comment by kimrutherford** [comment]
> Did I do it OK?

There were some spaces that should have been tabs.  Fixed now.  The changes will be visible in the morning.

**Comment by ValWood** [comment]
Crikey. I thought I checked that....
Thank you.
