### ISSUE TITLE
Add a sample strain file and add code to load the file

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1445]
Once #1418 is done we need to add a sample of that file (maybe just 10 lines) to the test data directory (https://github.com/pombase/canto/tree/master/t/data).

I've just added a test file of host organisms that can be read with `script/canto_load.pl`:
 `t/data/host_organisms.csv`

Once we have a test file we can add a --strains flag to `canto_load.pl` to populate the `strain` table.

**Comment by kimrutherford** [comment]
It would be helpful to do this issue soon-ish.

**Comment by barnabynorman** [comment]
Data added and commited

**Comment by barnabynorman** [comment]
Updated with the following files:
host_species_sample.csv
host_strains_sample.csv
pathogen_species_sample.csv
pathogen_strains_sample.csv

**Comment by kimrutherford** [comment]
> Updated with the following files:

Thanks.  I've changed the files to Linux line endings.

**Comment by kimrutherford** [comment]
I also changed the column order or pathogen_species_sample.csv and host_species_sample.csv to match what `canto_load.pl --organism` expects.

**Comment by kimrutherford** [comment]
I've added a --strains option to read the strains test files into the strain table in the database.  So these two commands work now in the canto directory:

```sh
./script/canto_load.pl --organisms t/data/host_species_sample.csv

./script/canto_load.pl --strains t/data/host_strains_sample.csv
```

@barnabynorman could you give it a go yourself?

**Comment by jseager7** [comment]
Running the following command:

    ./script/canto_load.pl --strains t/data/host_strains_sample.csv

Gave me an error about the following:

    DBD::SQLite::db prepare_cached failed: no such table: strain

I'm on the schema version 20, which I assume is the latest version, so is there anything I need to do to create the `strain` table besides re-initialising my database?

**Comment by kimrutherford** [comment]
> I'm on schema version 20,

Oh dear.  That's the right version.  The quickest fix it to re-initialise.

**Comment by jseager7** [comment]
> The quickest fix it to re-initialise.

Fortunately I just tried that, and I can confirm it fixes the problem.

**Comment by kimrutherford** [comment]
Great.  If you want to see how it looks in the database, try:

```sh

# organisms:
sqlite3 local/track.sqlite3 '.dump organism'

# taxon IDs:
sqlite3 local/track.sqlite3 '.dump organismprop'

# strains:
sqlite3 local/track.sqlite3 '.dump strain' 
```
