### ISSUE TITLE
Add a web service for looking up organisms

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1446]
We need this mostly so that we can get a list of possible host organisms on the gene upload confirmation page.

Something like:

```javascript
    CantoService.lookup('organisms')
        .then(function(response) {
              var organisms = response.data;
              ....
        }); 
```

where `organisms` looks something like:

```
    [
      {
        "genus": "Solanum",
        "species": "lycopersicum",
        "taxonid": "4081",
        "common_name": "tomato"
        "pathogen_or_host": "host"
      },
      {
        "genus": "Nicotiana",
        ...
      },
      ...
     ]
```

**Comment by kimrutherford** [comment]
@barnabynorman is working on the organism selector on the gene upload page, so I'll do this issue next.

**Comment by kimrutherford** [comment]
I've added an end point for retrieving all host or pathogen organisms.  The URL is:

http://localhost:7006/ws/lookup/organisms/host

or:

http://localhost:7006/ws/lookup/organisms/pathogen

I've only done a quick test but it should give output like:

```json
    [
      {
        "full_name": "Homo sapiens",
        "genus": "Homo",
        "pathogen_or_host": "host",
        "species": "sapiens",
        "taxonid": "9606"
      },
      {
        "full_name": "Mus musculus",
        "pathogen_or_host": "host",
        "taxonid": "10090",
        "species": "musculus",
        "genus": "Mus"
      }
    ]
```

**Comment by kimrutherford** [comment]
The end point should be accessible using CantoService like this (untested):

```javascript
var promise =
   CantoService.lookup('organisms', 'host', {});
```

**Comment by kimrutherford** [comment]
> The end point should be accessible using CantoService like this:

I've tried that now and it works.

@barnabynorman could you let me know if you have any problems?  If it works for you please close this issue.

**Comment by barnabynorman** [comment]
Sorry, @kimrutherford I should have mentioned here that I created a pull request for it - was nudging you in that direction....
