### ISSUE TITLE
Add a session web service for listing the organisms in the session

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1448]
This service is needed so that the current session organisms can be list on the gene confirmation page.

For each organism, as well as genus, species, taxon, etc. we will need to return a count of the number of gene from each organism in the session.  Alternatively it could return a list of the IDs of genes if that was useful.

The gene count or gene list is needed in the front end code to decide which organisms can be deleted from the session.  We won't put a delete button beside organisms with genes.

The `Curs` AngularJS service has a `list` action which could be extended to list the organisms:

https://github.com/pombase/canto/blob/1c8b1ab833e53ae96d13d82696fcff605c17e793/root/static/js/canto-modules.js#L239

eg.
```javascript
       var promise = Curs.list('organism', []);
       promise.success(function(organisms) {
          ...
       });
```

Where the returned list of organisms is something like:

```
    [
      {
        "genus": "Solanum",
        "species": "lycopersicum",
        "taxonid": "4081",
        "common_name": "tomato"
        "pathogen_or_host": "host",
        "gene_count": 4
      },
      {
        "genus": "Nicotiana",
        ...
      },
      ...
     ]
```

or alternatively:

```
    [
      {
        "genus": "Solanum",
        "species": "lycopersicum",
        "taxonid": "4081",
        "common_name": "tomato"
        "pathogen_or_host": "host",
        "genes": ["GENE_ID_1", "GENE_ID_2", ...]
      },
      {
        "genus": "Nicotiana",
        ...
      },
      ...
     ]
```

The service handler for this web service starts here:

https://github.com/pombase/canto/blob/1c8b1ab833e53ae96d13d82696fcff605c17e793/lib/Canto/Controller/Curs.pm#L2344

**Comment by kimrutherford** [comment]
I've added the web service for listing known organisms.  So this works now:

    var promise = Curs.list('organism');
    promise.success(function(organisms) {
        console.log(organisms);
    });

**Comment by jseager7** [comment]
We've decided we need to retrieve all the details for the genes of each organism, not just a number of the genes, and not just a gene ID.

**Comment by kimrutherford** [comment]
This service now returns the gene details too.  The response looks something like below.

After yesterday's discussion about genus, species and hybrids, I suggest we stick to using the "full_name" field in the code in case genus and species need to be removed later.

```json
             {
              "genus": "Schizosaccharomyces",
              "full_name": "Schizosaccharomyces pombe",
              "genes": [
                           {
                             "primary_identifier": "SPBC1826.01c",
                             "gene_id": 1,
                             "display_name": "mot1",
                             "primary_name": "mot1"
                           },
                           {
                             "primary_name": "ssm4",
                             "display_name": "ssm4",
                             "primary_identifier": "SPAC27D7.13c",
                             "gene_id": 2
                           },
                           {
                             "gene_id": 3,
                             "primary_identifier": "SPBC14F5.07",
                             "primary_name": "doa10",
                             "display_name": "doa10"
                           },
                           {
                             "gene_id": 4,
                             "primary_identifier": "SPCC63.05",
                             "primary_name": null,
                             "display_name": "SPCC63.05"
                           }
                         ],
              "species": "pombe",
              "taxonid": "4896",
              "pathogen_or_host": "unknown"
            },
            { ... },
            ...
```
