### ISSUE TITLE
MOD ID allowed

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1449]
I think somewhere we must configure a MOD subset. I really can't remember how or where because up until now everything I ever required was present.

I was going to use MOD:000664
as a placeholder  based on:

"This isomerization is not straightforward to describe as it does not only involve the proline residue. In fact here we talk about a prolyl isomerization cis-trans that is function of the relative geometry of the amide bond at the nterm of the proline residue and in particular of the carbonyl moiety of the previous residue. The proline itself does not change at all in this isomerization. We would need to model an isomerization of a pair of residues and not of a single residue.

Maybe one should add the term as child of MOD:000664  stereoisomerized residue  with source being a double residue including Proline And child of MOD:000915 modified L-proline residue"

 but it isn't accessible to me

**Comment by ValWood** [comment]
oh Kim, did you check that our MOD ontology was up to date?

**Comment by mah11** [comment]
Your problem is an extra 0 in the ID - I can reach MOD:00664 in Canto.

**Comment by ValWood** [comment]
Thanks!
