### ISSUE TITLE
genotype editing

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1450]
all the changes are brilliant, but it would still be useful to move the "finish" button closer to the details so you don't miss it when editing.
 I just used it and then used back to summary (or browser back) and couldn't figure why my allele details hadn't updated...)

![untitled](https://user-images.githubusercontent.com/7359272/39829350-11d6709a-53b6-11e8-8425-696828087820.jpg)

**Comment by ValWood** [comment]
Although no I wonder if we need this button here at all with the new workflow...Could it be in the box, need to think about this...don't have time  just now..

**Comment by ValWood** [comment]
Particularly important when you go in to edit alleles, because then you may  forget  that you need to click the hidden finish (well I do!):

![hidden](https://user-images.githubusercontent.com/7359272/40389305-effa9c68-5e09-11e8-816c-1a89a4b7f9ea.jpg)

**Comment by kimrutherford** [comment]
>  move the "finish" button closer to the details so you don't miss it when editing.

I've done that now.  Sorry it took a while.
