### ISSUE TITLE
a possible problem to think about in genotype management 

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1451]
Great feedback from  Hwei-Ling  on my additions

copy paste penetrance error (it might be useful to ask for confirmation n the first term)

but a bigger issue, I did something pretty silly here but I can really imagine others doing it too:

Because I had already captured
Cnp1-P13A  and Cnp1-P15A, I combined them to make
Cnp1-P13A,P15A

but of course this is creating a multi-allele annotation.....

We should make Canto clever enough to know, that these are in the same gene. But how would we do that because sometimes it might be 2 copies?

Thoughts?

![curation image 2](https://user-images.githubusercontent.com/7359272/39831025-1151a9aa-53bb-11e8-817d-694b8302dbd2.jpg)

**Comment by kimrutherford** [comment]
I'm not following what the problem is.  Could we have a quick chat on a call sometime?

**Comment by ValWood** [comment]
on list for next call...

**Comment by Antonialock** [comment]
I donn't think we can do anything about this because as you say, the two different point mutations could be two different copies of a gene
