### ISSUE TITLE
test loading publications

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1459]
related
https://github.com/pombase/canto/issues/1458

  ./canto/script/canto_docker script/canto_add.pl --pubmed-by-id 703759 318606 141274

You can run this once for each publication or you can put multiple IDs on one line which makes things faster.

**Comment by ValWood** [comment]
need to discuss how loading publications should happen

**Comment by ValWood** [comment]
I don't know what this means?

**Comment by kimrutherford** [comment]
Sorry I don't know either.

**Comment by ValWood** [comment]
Close?

**Comment by kimrutherford** [comment]
Yep, I can't remember what this was about.
