### ISSUE TITLE
WT gene with WT product level

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1460]
from https://github.com/PHI-base/canto/issues/7

from
https://github.com/pombase/canto/issues/1359

PHI base need to be able to specify WT gene and product level  for some WT alleles when comparing strains.

@CuzickA  @hammond-kosack @KEHammond We already have the functionality to specify WT phenotypes in Canto  since your old implementation.  We needed this for dominant negative, or haploinsufficiency in a diploid etc where people  keep the WT copy and also have one mutant copy in the genome or over expressed etc.
So I forgot,  it is already available, just that PomBase do not use it on its own. This should work for you though?

![wt gene and product level](https://user-images.githubusercontent.com/7359272/32725260-489f6134-c86c-11e7-88cd-a9ace258cd2e.jpg)

When you get a local install working  can you check that this will work for all of your use cases, and then close.

**Comment by ValWood** [comment]
Will test this once OBO files have been uploaded.

We particularly need this for the  'effectors'. https://github.com/PHI-base/PHI-base_ontologies/issues/7

We will want to record the WT genotype interaction phenotypes in the gene-for-gene interactions, before information from mutant allele phenotype is useful. Typically the pathogen avirulence (avr) gene is recognised by a corresponding host Resistance (R) in a strain specific manner to trigger host defence (such as Hypersensitive Response (HR) localised cell death which would kill a biotrophic pathogen)

**WT interactions** (NOTE: avr- could be caused by natural absence of gene in strain or naturally altered gene whose gene product is not recognised by the host R gene)
pathogen avr+ host R+ =incompatible/ resistant, no disease, resistance response (HR)
pathogen avr+ host R- =compatible/ susceptible, disease, no resistance response (no HR)
pathogen avr- host R+ =compatible/ susceptible, disease, no resistance response (no HR)
pathogen avr- host R- =compatible/ susceptible, disease, no resistance response (no HR)

**Mutant allele**
Take pathogen _avr- host R+ =compatible, disease, no resistance response (no HR)_
mutate few nt in avr- and change to avr+ which is now recognised by the host R gene and shifts the phenotype from susceptible to resistant

**Comment by kimrutherford** [comment]
It looks like this is the same as #1359.  Which one should we close?

**Comment by ValWood** [comment]
I closed the other ticket, this seems to have more

**Comment by ValWood** [comment]
@CuzickA  When you chance can you check that this will work for all of your use cases, and close if OK

**Comment by CuzickA** [comment]
We may be able to test this when we have time to finish the atr1/RPP1 curation.

**Comment by ValWood** [comment]
Will assign to @CuzickA   to test

**Comment by jseager7** [comment]
@CuzickA has this issue been tested yet? Specifically, have you finished curating the atr1/RPP1 paper? We can close this issue if so.

**Comment by CuzickA** [comment]
We are still working on the 'effectors' and @ValWood is currently checking the atr1/RPP1 paper so we should be able to check this soon.

**Comment by ValWood** [comment]
I did check this one already
https://github.com/PHI-base/curation/issues/19
although there are some things to finalize in the ticket

**Comment by CuzickA** [comment]
Closing this ticket now as there is further information in ticket https://github.com/PHI-base/curation/issues/19
