### ISSUE TITLE
Add a host organism form field to the gene upload/entry page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1465]
(I couldn't see an issue for this. Apologies if I missed an existing one)

On the gene upload page we need a way to enter the host organisms that are mentioned in the paper that don't have an genes.

I discussed that with @jseager7 and @barnabynorman and we decided that for testing we'll add a box where the user can add host taxon IDs.  This is easy to implement and will allow us to get on with other issues while we think about how the interface should really work.

**Comment by kimrutherford** [comment]
I've added a text box for entering a space separated list of host taxon IDs.  It only appears in pathogen-host mode.  There isn't much error checking yet so it's likely to go wrong if your enter a taxon ID that isn't in the database or isn't a host taxon ID.

**Comment by kimrutherford** [comment]
@barnabynorman has implemented an improved organism selector with auto-completion.

Barnaby, could you and Alayne have a chat about what text to add above the new organism selector to make it more user friendly?

**Comment by CuzickA** [comment]
I've started thinking about this text. I think we may also need additional text on this page to explain that a pathogen uniprot MUST be entered and that host genes/organisms can also be added. 

This page comes straight after the 'entering curator details' and we haven't yet introduced the 3 phenotype curation modes pathogen only/host only/ pathogen-host disease formation.

Within disease formation we can have 
'pathogen gene/allele and host gene/allele'
'pathogen gene/allele and host organism'
but NOT 'pathogen organism and host gene/allele'

I'm working on a mock up so more on this to follow...

**Comment by barnabynorman** [comment]
@kimrutherford to confirm the text needed above the picker is:

"Create host organism list (where there are no specified host genes) for PMID:446786" where "PMID:446786" is the id of the document being curated - I initially attempted to do this by copying the ref from the top of the page but the system did not like it and I reverted!

**Comment by kimrutherford** [comment]
> to confirm the text needed above the picker is:

Thanks Barnaby.  I've added the message.  The change is here:
  https://github.com/pombase/canto/blob/89d7b18ebd7005bb91879096a36f2c96331063a2/lib/Canto/Controller/Curs.pm#L615

I'll close this.  We can open new issues later if needed.
