### ISSUE TITLE
Organism synonyms are not retrieved from UniProt

### ISSUE THREAD

**Issue by CuzickA** [pombase/canto#1468]
(Related to #1467)

![no fg listed](https://user-images.githubusercontent.com/11753634/40423612-09cae838-5e8b-11e8-9a01-d511f16422da.PNG)

The gene list confirmation does not show _Fusarium graminearum_, which matches the NCBI Taxonomy and our species list.

The UniProt website does show the synonym, for example at http://www.uniprot.org/uniprot/Q00909. Do we just want a note to curators that they should only follow NCBI Taxonomy?

**Comment by kimrutherford** [comment]
> The UniProt website does show the synonym,

I could see  "Alternative name(s): Sesquiterpene cyclase" on that UniProt page but not any synonyms.  Which part of the page should I look at?

**Comment by ValWood** [comment]
UniProt should really be using the NCBI taxonomy...... We should log a ticket with them about that.

**Comment by ValWood** [comment]
But Gibberella zeae *is* the species name?
Shouldn't we be using that?

**Comment by ValWood** [comment]
Fusarium graminearum is the anamorph name, correct?

**Comment by Antonialock** [comment]
> Fusarium graminearum is the anamorph name, correct?
yes but it doesn't look like the official name "has" to reflect the teleomorphic name?
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3359808/

**Comment by kimrutherford** [comment]
Here's a summary of all the various taxon pages:

The "Taxonomic identifier" for that UniProt entry is taxon ID 229533.

UniProt/EBI call it "Gibberella zeae (strain PH-1 / ATCC MYA-4620 / FGSC 9075 / NRRL 31084) (Wheat head blight fungus) (Fusarium graminearum)" - http://www.uniprot.org/taxonomy/229533

NCBI call it "Fusarium graminearum PH-1" - https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=229533&lvl=3&lin=f&keep=1&srchmode=1&unlock

The parent taxon (the species) is named "Gibberella zeae (Wheat head blight fungus) (Fusarium graminearum)" in UniProt - http://www.uniprot.org/taxonomy/5518

NCBI just call it "Fusarium graminearum" - https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?lvl=0&amp;id=5518

Great fun!

**Comment by CuzickA** [comment]
Yep that summary just about sums it up!

**Comment by CuzickA** [comment]
> No, but we probably need to stick to the NCBI taxonomy. The other option is to have a config file with a "display name" to translate if PHI-BAse want to use non NCBI taxonomy names. But the same name should be used throughout for a single species not a mixture of names/synonyms...

I wondered about this but i think it may get tricky, as different labs may favor different synonyms and it may just be easier to stick to NCBI taxons and encourage curators to look up the correct one if they are unsure. The authors can make a note of synonyms in their publication if they wish.

**Comment by ValWood** [comment]
Closing, if  the incorrect organism name is the primary name we should inform UniProt
