### ISSUE TITLE
session admin: Add a "Show all ..." link underneath inline tables 

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#147]
The embedded/inline tables on pages like this:
http://oliver0.sysbiol.cam.ac.uk/pombe/view/object/person/1?model=track
can be quite long.  We should show the first 10 or 20 rows and add a "Show all ..." link which shows the whole table.

Original comment by: kimrutherford

**Comment by ValWood** [comment]
s this an issue? Which list are we referring to?
https://curation.pombase.org/pombe/view/list/person?model=track
?

has scrolling by number anyway?

**Comment by ValWood** [comment]
Although that lonk seems like it could be a specific person page, in which case I'm not sure what the task is. Suggest clodsing?

**Comment by kimrutherford** [comment]
> Which list are we referring to?

The "Publications currently being curated by this user" list is quite long here: https://curation.pombase.org/pombe/view/object/person/1?model=track

> Suggest closing?

I think so as it seems quite fast to load the page.
