### ISSUE TITLE
Selectively show genotypes depending on selected organisms

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1470]
Once #1469 is done we should think about only showing the single allele genotypes of the selected host and pathogen.  If the selected organisms change we should update the displayed genotypes.

**Comment by kimrutherford** [comment]
Can this be closed now.  I think it's all working isn't it?  @jseager7

**Comment by jseager7** [comment]
Yes, it's been implemented by #1602. Closing now.
