### ISSUE TITLE
Some PHI-base organisms can't be parsed by canto_load.pl

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1473]
In the list of host and pathogen organisms that we're using at the moment, there are organism names that don't follow the `<genus> <species>` format that `canto_load.pl` expects.

- We have taxon IDs for crossed / haploid organisms, for example:
  - _Citrus_ x _paradisi_
  - _Musa_ x _paradisiaca_
- And there are IDs with a genus but no species, for example:
  - _Rattus_
  - _Rosa_
  - _Artemia_

I'm not sure which of these we should even try to parse, since part of it depends on whether we only want to curate organisms at the species level.

**Comment by CuzickA** [comment]
I think we could remove these egs from the pathogen/host lists. 

> And there are IDs with a genus but no species, for example:
> Rattus
> Rosa
> Artemia

They came from papers were the authors were being vague and just said they used 'rat' or 'rose'. Moving forward with PHI-Canto curation we want the authors to specify the species name.

**Comment by CuzickA** [comment]
> We have taxon IDs for crossed / haploid organisms, for example:
> Citrus x paradisi

This is more tricky
Citrus x paradisi is grapefruit which is a hybrid between Citrus maxima and Citrus sinensis.
I'm not sure if that means that Grapefruit is not actually a 'species' but that it is an F1 hybrid that needs to be created from the above cross each time? @KEHammond

Perhaps we could add the 'citrus' to the 'genus'
and 'x paradisi' to the 'species' or is the space character a problem here?
Alternatively we could remove the 'x' and let people find this information themselves via the NCBI taxid which capture this information.

**Comment by ValWood** [comment]
Maybe we need to extend the format to deal with hybrids?

**Comment by jseager7** [comment]
After further discussion, we have two potential solutions to this problem:

1. Group the genus and species information into a single 'organism name' field.
   - This would make it easy to support any sort of organism name, regardless of whether it is genus-only, or a hybrid, or anything else.
   - In terms of implementation, it would involve changing the `canto_add.pl` syntax to:
   `canto_add.pl --organism <organism name> <taxon_id>`
   - Note that this would also mean changing the format of the data files used by `canto_load.pl`, specifically joining the 'genus' and 'species' column into a single species, and this change would have to be applied to the database schema as well.

2. Make the 'species' field optional (to support taxon IDs at the genus level), and add optional fields for 'hybrid genus' and 'hybrid species'.
   - This would require improving the parsing ability of `canto_add.pl` to support hybrid organisms.
   - Presumably it would also mean adding columns to the database (and the imported data files) for 'hybrid genus' and 'hybrid species' that will be empty almost all the time. 

Personally I support option 1 because it's much simpler, but if we ever need to query the genus, species, or hybrid genus and species directly from the database, option 2 may be more appropriate.

I'll leave the final decision up to @kimrutherford.

**Comment by kimrutherford** [comment]
> I'll leave the final decision up to @kimrutherford.

I'm not very good at decisions.

I like option one.  The important thing is to have a display name for each organism and to store the taxon ID.  As long as we have the taxon ID we can always look up any other details (like genus and species) in the taxonomy databases.

I've added the "high priority" label as I like to get schema changes done as early as possible.

**Comment by kimrutherford** [comment]
> Group the genus and species information into a single 'organism name' field.

I've done this now.  Unfortunately it's a really big change - more the 40 files.  And a schema change.

I'm about to push the changes.  After you pull the changes you'll need to upgrade your database before things will work again.  I recommend making a backup of your data directory before upgrading, just in case.  You'll also need to stop your Canto processes, if any.

The upgrade command is:

    ./etc/upgrade_db.pl 22

It shouldn't take more than a second or two to run.

Please let me know if you have any problems.

**Comment by jseager7** [comment]
I've tested upgrading the schema and I didn't have any problems &ndash; Canto starts successfully. I haven't tried loading any organisms though.

**Comment by kimrutherford** [comment]
> I've tested upgrading the schema and I didn't have any problems – Canto starts successfully.
> I haven't tried loading any organisms though.

Thanks!  Good enough for me.  :-)
