### ISSUE TITLE
Do we still need mutiple-allele annotation links?

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1477]
(Possibly related to #1456)

I couldn't see any existing issues that specifically discuss this, but @ValWood mentioned [in issue #1463](https://github.com/pombase/canto/issues/1463#issuecomment-391004436) that we might not need links for _multiple allele_ phenotype annotation types anymore, presumably since they all link to the _Genotype Management_ page.

This is more of a problem for the PHI-Canto version, since there are three different phenotype annotation types, and this means six links for single and _multiple allele_ modes:

![phipo_annotation_list](https://user-images.githubusercontent.com/37659591/40662157-7a9f2332-634d-11e8-9f10-867a9b18d975.PNG)

It might be a bit more confusing for the curators to simply remove the links; maybe for PHI-Canto we should have one 'multi-allele phenotype' link that goes to the _Genotype Management_ page, and keep the single allele annotation types specific to the PHIPO namespaces?

Here's a mock-up of what I mean:

![phi-canto_annotation_types](https://user-images.githubusercontent.com/37659591/40662454-4c7a9008-634e-11e8-8b04-ead0e06d80cb.png)

**Comment by ValWood** [comment]
Or just:
Disease formation
Pathogen phenotype
Host phenotype

?
We might want to get rid of the separate options in PomBase canto  too now.... will discuss this week. I think it's more confusing to have  different entry points not the genotype management is clearer.....

**Comment by kimrutherford** [comment]
This is a bit tricky.

> We might want to get rid of the separate options in PomBase canto too now

They do two quite different things.  How do we combine them?

I've never been keen on the two links in PomBase Canto ("Single allele Phenotype" and "Multiple allele Phenotype") because neither do the same thing as the other ontology annotation links in the same list.  We have them to make it easier for users to get into making genotypes, but I wonder if they confuse more people than they help.

I think I'd prefer to have the genotype/phenotype links in a separate section from the other annotation types.

**Comment by jseager7** [comment]
Following our decision to remove the phenotype annotation links, there's a pull request open now that does that (#1663).

However, I think there are some things we could do to mitigate the usability problems this removal could cause for users:

* We might want to **add some help text** for the case where curators have clicked on a gene and expect to make a single-allele mutant phenotype, and are confused when they don't see a link to do this.

* We could **include the phenotype annotation links in a separate section**, called 'phenotype annotations' or similar, but only have two links:

  * The first link would create single-allele phenotypes, which would work the same way as before;

  * The second link would handle multi-allele phenotypes, and would direct the user to the correct genotype page corresponding to the selected gene. We might also want some help text in this case to emphasise that the user will be creating a _genotype_ first.

Here's an example of what the links could look like:

![new_phenotype_links](https://user-images.githubusercontent.com/37659591/48069785-38f6a180-e1ce-11e8-9fd9-25de9c23a2e5.png)

**Comment by ValWood** [comment]
Fixed in a different way, out of date

**Comment by jseager7** [comment]
Specifically obsoleted by https://github.com/pombase/canto/issues/1896
