### ISSUE TITLE
Show phenotype name when phenotype annotation type is inferred

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1478]
(Depends on #1476 being fixed)

As discussed in #1463, the _Genotype Management_ page is able to infer which phenotype annotation to use, based on the alleles in the meta-genotype.

Since this process might not be obvious to the curators when adding annotations, it should be helpful to add some text on the _Search for phenotype term_ page showing the name of the phenotype type that was inferred (e.g. Host phenotype).

We'll also have to make sure the names in the configuration for the annotation types are correct; ideally we would be able to display one of those names.

I'll add a mock-up of how this might look when I have time.

**Comment by kimrutherford** [comment]
> some text on the Search for phenotype term page showing the name of the phenotype type that was
> inferred (e.g. Host phenotype).

It looks like this now that I've changed the annotation types configuration.  The example broad search terms ("multinucleate, abnormal spindle, inviable") can be changed in canto.yaml or canto_deploy.yaml.  So can the text "Annotate normal or abnormal phenotypes of cells with this genotype."

![host-phenotype-annotate-1](https://user-images.githubusercontent.com/90474/44506985-f0fecd00-a6fc-11e8-8307-c7d87808cafa.png)
