### ISSUE TITLE
can we make "no experimental  details"/ inability to Submit until curation added clearer?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1480]
Kurt
"
I curated the list of genes used but the web page will not allow me to submit it.  It was saved.
"

![refine](https://user-images.githubusercontent.com/7359272/40707640-3512c69c-63e9-11e8-9781-4a4143b199d4.jpg)

I think this is because if you have provided genes mentioned, but there is no gene specific annotation, what to do is not so clear.

Maybe we can improve this a bit?
Ideas?

**Comment by kimrutherford** [comment]
We could turn "No experimental results to add?" into a submit button.  I'd rather not though.

**Comment by ValWood** [comment]
What if, we had a pop- up if a user tries to "submit" at this point (i.e when the button is greyed out"

Text "You cannot submit the session until you have provided some annotation, or  checked the "no experimental result to add" box below.

Simple, and clear?

**Comment by kimrutherford** [comment]
> What if, we had a pop- up if a user tries to "submit" at this point (i.e when the button is greyed out"

> Text "You cannot submit the session until you have provided some annotation, or checked the "no
> experimental result to add" box below.

An alternative is to get rid of the "no experimental results to add" checkbox.  If the user click "Submit" without adding annotation we could catch that and show an "OK" or "Cancel" dialog with text like:

You have not creating any annotations.  If your papers has no gene specific information, you can finish submitting by clicking "OK".  If you have annotation to add, click "Cancel"

(With better wording)

**Comment by ValWood** [comment]
that would work too.

**Comment by ValWood** [comment]
This has "discuss" 

@Antonialock  @mah11   Do you think the solution proposed is OK?

**Comment by mah11** [comment]
This is another one where you have far stronger feelings/opinions/preferences than I do.

**Comment by ValWood** [comment]
Let's kepe as is for now. I worry that activating the submit button may encourage people to submit more sessions with no annotation.
