### ISSUE TITLE
Internal error: no CV with name phenotype_condition

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1481]
On the Vagrant version of Canto, I was creating a phenotype for testing purposes, and I added the condition 'rich medium'. I then got this error in the server console when finishing the annotation:

`internal error: Caught exception in Canto::Controller::Curs->annotation_set_term "no cv with name: phenotype_condition at lib/Canto/Track/OntologyLookup.pm line 368." at lib/Canto/Controller/Root.pm line 55.`

In the browser, an error-style popup appeared in the top right, but it had no text in it.

Is this a configuration issue?

**Comment by kimrutherford** [comment]
Sorry that Canto isn't very robust in this case.  The condition ontology name is hard coded in lib/Canto/Curs/ConditionUtil.pm and it shouldn't be.

It looks like the phenotype_condition isn't loaded, so as a temporary fix you could add peco.obo to the list of ontologies you load with canto_load.pl

**Comment by jseager7** [comment]
Adding peco.obo fixed this error. Thanks.
