### ISSUE TITLE
Lucene "Too Many Clauses" on short experimental conditions

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1482]
On the _Choose evidence and conditions_ view when adding a phenotype, I get the following error in the server console when entering an artificially short condition name, for example 's'.

`internal error: Caught exception in Canto::Controller::Service->lookup "[Lucene::Search::IndexSearcher->search()] Too Many Clauses" at lib/Canto/Controller/Root.pm line 55.`

There's no error feedback in the browser, but the spinner in the search box never disappears until after a page reload once this error occurs.

**Comment by kimrutherford** [comment]
"Too Many Clauses" is odd.  Are there any errors or warnings in the console?

**Comment by jseager7** [comment]
> Are there any errors or warnings in the console?

The internal error shows up in the server console, as output from Canto while it's running.

I've tried this again after loading the PECO ontology, and I still see the same error. I also have this in the browser console:

```
jquery.min.js:2 GET http://localhost:5000/ws/lookup/ontology/phenotype_condition?def=1&term=s&def=1 500 (Internal Server Error)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
fetch_conditions @ canto-modules.js:678
s @ jquery.min.js:2
_search @ jquery-ui.min.js:5
(anonymous) @ jquery-ui.min.js:5
search @ jquery-ui.min.js:5
(anonymous) @ jquery-ui.min.js:5
(anonymous) @ jquery-ui.min.js:5
n @ jquery-ui.min.js:5
setTimeout (async)
_delay @ jquery-ui.min.js:5
_searchTimeout @ jquery-ui.min.js:5
(anonymous) @ jquery-ui.min.js:5
input @ jquery-ui.min.js:5
u @ jquery-ui.min.js:5
dispatch @ jquery.min.js:2
u @ jquery.min.js:2
```

**Comment by kimrutherford** [comment]
This happens to me too.  I've never noticed that before.  I guess I type too fast for it to send the one character completion request.  Should be an easy fix.

**Comment by kimrutherford** [comment]
Should be fixed now if you update to the latest commit.
