### ISSUE TITLE
Add separate genotype sections on curation summary page

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1485]
(Related to #1477)

Following a discussion with @kimrutherford about where the _Multiple-allele_ links are located, we feel it would make more sense to have different sections on the curation summary page for gene-focused workflows and genotype-focused workflows.

The proposal is to add another heading for 'Add genotypes' (or 'Add or view genotypes') and then list genotype-related links under that heading: for example, a link to the genotype management page, and in the case of PHI-Canto, links to lists of host genotypes, pathogen genotypes, and pathogen–host genotypes. Here's a mockup:

![gene_and_genotype_sections](https://user-images.githubusercontent.com/37659591/40975620-70aec4a6-68c3-11e8-98ea-a50c68615ecf.png)

I think we might need to make the _Genotype Management_ link even more obvious than it is now, perhaps by styling it like a button.

If this change was implemented, we could then remove the _Multiple allele_ links from the _Choose curation type_ page, and make it so that when you click a gene, all you see are the gene-focused annotation links. If this is likely to confuse curators who used the _Multiple allele_ links, we could add a link for convenience below the gene annotation links, like so:

![genotype_management_gene_page_link](https://user-images.githubusercontent.com/37659591/40975967-880b4e70-68c4-11e8-9452-5f82fbb5ef8b.png)

- - -

@ValWood please let me know what you think, in particular if you think any of the text is inaccurate or misleading.

**Comment by kimrutherford** [comment]
I suggest these headings under the "Annotate genotypes" heading:

  - Host genotypes and phenotypes ...
  - Pathogen genotype and phenotype ...
  - Pathogen-host interactions and phenotype ..

Each link could go to the genotype management page, but with the management page in the appropriate mode (host genotype mode, pathogen genotype mode or pathogen+host).

**Comment by ValWood** [comment]
I like the  proposal to have a heading for  "annotate genes" and one for "annotate genotypes"

 I think annotate genotypes should offer the 3 options that Kim suggests and provide the appropriate mode.

**Comment by jseager7** [comment]
I've opened a pull request that implements the first part of this issue. Here is how the summary page will look once it's merged:

![summary_genotype_heading](https://user-images.githubusercontent.com/37659591/47495253-904e5680-d84b-11e8-8cd7-2402fb89edd2.PNG)

**Comment by jseager7** [comment]
The changes are merged now, so I'm closing this issue. The genotype heading doesn't have any help text at the moment, so I've opened a new issue about that here: #1658.
