### ISSUE TITLE
Import stops with error when loading ontologies

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1486]
When loading go-basic.obo with this command:

`./script/canto_load.pl --ontology http://snapshot.geneontology.org/ontology/go-basic.obo`

I am getting an error:

`Can't use string ("The distribution of mitochondria"...) as a HASH ref while "strict refs" in use at lib/Canto/Track/OntologyLoad.pm line 384.
DBIx::Class::Storage::TxnScopeGuard::DESTROY(): A DBIx::Class::Storage::TxnScopeGuard went out of scope without explicit commit or error. Rolling back. at lib/Canto/Track/OntologyLoad.pm line 383
	(in cleanup) Canto::Track::OntologyLoad::finalise() not called`

I have tried downloading the file and removing the last record that it processes, but it still fails!

**Comment by kimrutherford** [comment]
I've tried to reproduce this problem but I can't.  

I might have asked this before but could you run this and let me know the result?:

    perl -e 'use PomBase::Chobo; print "$PomBase::Chobo::VERSION\n"'

Also, could you check that you're using the latest Canto from the master branch?

**Comment by kimrutherford** [comment]
We fixed this on a Skype call yesterday.
