### ISSUE TITLE
duplicate people

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1492]
I just sent  kim a small list  of 'people" to merge/delete. I don't want to put the e-mails in  a ticket.

Ideally it would not be possible to add two people with the same name. It must be currently?

**Comment by kimrutherford** [comment]
> Ideally it would not be possible to add two people with the same name. It must be currently?

Yep that's possible at the moment.  Internally the email address is used as the main key for looking up people and the name is just a secondary attribute.

I wish we could just force everyone to log in with an ORCID then it's someone else's problem.

Here's the previous discussion: #593 

This is a bit related too: #1159

**Comment by kimrutherford** [comment]
> I just sent kim a small list of 'people" to merge/delete.

I've removed those duplicates.

Merges are error prone when I do them by hand so I've added "canto_merge" script that can do it automatically.  So next time it will the straight forward.
