### ISSUE TITLE
ORCIDs

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1493]
At present, I think it seems as though an ORCID is required (at lease some people are putting guff in there to get past it). It might put others off, so we should look into making it properly optional  (I think we found similar when we did the workshop?)

Also,  the box shouldn't appear of you have already added your ORCID.... (or it should be clear that your ORCID is already provided)?

It would be nice if password was remembered too?...I'm not sure how this works...

**Comment by kimrutherford** [comment]
> At present, I think it seems as though an ORCID is required

The ORCID isn't required.

> Also, the box shouldn't appear of you have already added your ORCID.

We won't know if a user has added an ORCID until they put their email address in.  Should we ask for the ORCID on a new page after they submit the name/email address form?

> It would be nice if password was remembered too?

Which password?

**Comment by kimrutherford** [comment]
Previous discussion: #1409.

**Comment by kimrutherford** [comment]
And #17.

**Comment by ValWood** [comment]
> Which password?

I was thinking of admin password here.   Ignore this for now...

**Comment by ValWood** [comment]
also I'm not sure where the ORCID issue arises either. Everything I just tried seems fine but I think there is one spot where it doesn't work as expected.

**Comment by ValWood** [comment]
OK this is covered by other tickets
