### ISSUE TITLE
Fix Bootstrap/jQuery warning

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1494]
Hi @barnabynorman 

Could you have a go at this?

```
Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 4
```

**Comment by barnabynorman** [comment]
Hi @kimrutherford,

Fixed the problem + checked and updated the other files (see below)
Have created a pull request #1500 

Installed versions
------------------
angular-1.5.3
angular-animate-1.5.3
Angular-touch (not included in source)
bootstrap-3.3.7
ui-bootstrap-tpls-2.1.3
Chart-v2.2.1
angular-chart-v1.0.0
angular-confirm-1.2.5
angular-mocks-1.5.3
angular-placeholder-shim (unknown version) - file does not appear to be used - added in 3f21e0fe2e26ad29d7a7b604e8582b6c61eaf6e5
jquery.html5-placeholder-shim (unknown version) - file does not appear to be used - added in 3f21e0fe2e26ad29d7a7b604e8582b6c61eaf6e5
bootstrap-3.3.7
jquery-1.8.3
jquery-ui-1.9.2
jquery.form.2.47
jquery.placeholder version 1.7
jquery.jtruncate (unknown version)
jquery.pnotify version 1.1.1
jquery.shiftcheckbox (unknown version)
jquery.validate-1.9.0
tag-it version 2
toaster-2.0.0


angular
-------
(latest version 1.6.10)
-- Downloaded 1.5.11 - staying conservative as deprecated success / error methods in $http


angular-animate
---------------
-- Downloaded to match angular (1.5.11)


angular-touch
-------------
-- Downloaded to match angular (1.5.11)


angular-mocks
-------------
-- Downloaded to match angular (1.5.11)


ui-bootstrap
------------
(latest version 2.5.4)
AngularJS (requires AngularJS 1.4.x or higher, tested with 1.6.1).
Angular-animate (the version should match with your angular's, tested with 1.6.1)
Angular-touch (the version should match with your angular's, tested with 1.6.1) (optional)
Bootstrap CSS (tested with version 3.3.7)
-- Downloaded 2.5.0


Chart js
--------
(latest version 2.7.2)
-- Downloaded 2.7.2


Angular-chart
-------------
(latest version v1.1.1)
AngularJS (requires at least 1.4.x)
Chart.js (requires Chart.js 2.x)
-- Downloaded 1.1.1


angular-confirm
---------------
(latest version 1.2.6)
Angular-UI-Bootstrap > 0.14
Bootstrap css 3.x
-- Downloaded 1.2.6


angular-placeholder-shim
------------------------
(latest version 0.3.1)
jquery.html5-placeholder-shim
jQuery (no version specified)
-- Downloaded 0.3.1


jquery.html5-placeholder-shim
-----------------------------
(unknown latest version)
-- Downloaded newer unknown version


bootstrap
---------
(latest version 3.3.7)
jquery": "1.9.1
-- Nothing to do


jquery
------
(latest version 3.3.1)
(no dependency)
-- Downloaded 1.9.1


jquery-ui
---------
(latest version 1.12.1)
jQuery 1.7+
-- Downloaded 1.12.1


jquery.form
-----------
(latest version 3.51.0-2014.06.20)
jQuery v1.5 or later
-- Downloaded 3.51


jquery.jtruncate
----------------
(latest version 0.8)
-- Download unavailable - project appears stalled


jquery.placeholder
------------------
(latest version unknown)
jQuery 1.6+
-- Downloaded newer version


jquery.pnotify
(unknown latest version and dependencies)
-- Nothing to do


jquery.shiftcheckbox
--------------------
(latest version 0.8.0)
jQuery 1.10.2+
-- Downloaded 0.8.0


jquery.validate
---------------
(latest version 1.17.0)
jQuery, tested with 1.7.2, 1.8.3, 1.9.1, 1.11.1, 3.1.1
-- Downloaded 1.17.0


tag-it
------
(latest version assumed 2)
jQuery (v1.4 or greater), 
jQuery UI (v1.8 or greater)
-- Nothing to do


toaster
-------
(latest Version 2.2.0)
AngularJS v1.2.6 or higher
angular-animate (no version specified)
-- Downloaded 2.2.0

**Comment by barnabynorman** [comment]
Hi Kim,

Yes saw it now - have updated and re-pushed as requested

Will make a new pull request....
