### ISSUE TITLE
remembering unused alleles?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1496]
I was curating a paper for  rpts(mst2).

The mutant used is called mts2-1 (there is no other  ts.mutant isolated only deletion)

When I begin to type mts2 I also see"mst mutant unknown"

![mts2](https://user-images.githubusercontent.com/7359272/41275771-ecb8b16e-6e19-11e8-9e94-f6fbda23763b.jpg)

I wanted to track this down and make sure that the   genotypes were represented consistently as mts2-1
but I can't see "mst mutant" in a session.

Which session is this from?

**Comment by ValWood** [comment]
I curated 3  papers before 8-30!

**Comment by kimrutherford** [comment]
It's from b732a3ac22de7b6e.  Here are the query results:

```
    name     |      session
-------------+------------------
 mts2-1      | 84dcea5bf4f580d2
 mts2-1      | 250962459bf6bd5e
 mts2-1      | 207d1283e42dcc66
 mts2-1      | aac1ee2617f3c41b
 mts2-1      | 0d6e46fca4be8cc5
 mts2-1      | aec91591ee01e7f9
 mts2-1      | a2af386d7f306918
 mts2-1      | dd0dc92db12b47e2
 mts2-1      | ee92e3801448ef56
 mts2-1      | 9197675c3ba9f5d1
 mts2 mutant | b732a3ac22de7b6e
```

**Comment by ValWood** [comment]
Ah OK yes I see it on the gene page now.
Fixed.
