### ISSUE TITLE
stuck in a "do not annotate" term

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1497]
I'm stuck in a "do not annotate term" in the phenotype ontology

![stuck](https://user-images.githubusercontent.com/7359272/41280464-e9cd1ece-6e26-11e8-93ff-fde99c18b49c.jpg)

I  need to create a new child to continue, but I still can't proceed.

Suggestion
Make it possible to over-ride "do not annotate" if you are suggesting a new descendant term.

Stop gap,  @mah11  maybe this one should be a 'soft check' for now?

**Comment by kimrutherford** [comment]
> if you are suggesting a new descendant term

Is that what you did in this case?  I'm having trouble reproducing the problem.

**Comment by kimrutherford** [comment]
Sorry about that.  I think I've fixed this.

> Make it possible to over-ride "do not annotate" if you are suggesting a new descendant term

It now does that.

**Comment by ValWood** [comment]
It needs to be a "do not annotate " term, like "decreased catalytic activity...

 with this term, you are stuck. It would be fine if you were allowed to proceed if you suggested a new child?

I worked around by using one of the existing children. Fine for us but a bit obtuse for community...

**Comment by ValWood** [comment]
wow that was quick!

**Comment by ValWood** [comment]
OK that works,
we should change the text slightly:


This term should not be used for direct annotations. Please select a more specific term, or suggest a new descendant term
?

**Comment by kimrutherford** [comment]
> we should change the text slightly:

I've changed the text.
