### ISSUE TITLE
it is possible to use "do not annotate" terms in the "pop up" interface

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1498]
I just noticed this when testing
https://github.com/pombase/canto/issues/1497#issuecomment-396520179

**Comment by kimrutherford** [comment]
Ah, I forgot about that.  I'll look at it next.

**Comment by kimrutherford** [comment]
I've had a go at fixing this.  I've also changed some of the prompt text so that it makes more sense.  Please let me know if you spot any problems or you'd like any text changed.

Since it's a bug fix I've released the change in the main Canto.
