### ISSUE TITLE
select an organism feature should not appear in Pombe Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1499]
We shouldn't see this n single organism mode...

![select](https://user-images.githubusercontent.com/7359272/41283507-ac78e6cc-6e2e-11e8-9a8b-b55283d84501.jpg)

**Comment by kimrutherford** [comment]
That's odd.  I went to the session by looking up the PMID and it doesn't do that for me - I don't need to select an organism.  Does it stay that way if you reload the page?

I was looking at this page:
https://curation.pombase.org/pombe/curs/33ab85af0ca986c2/genotype_manage

**Comment by ValWood** [comment]
Yes actually its the first time I saw it...and I have been in genotype management loads this morning...I'll try to figure when it happens...

**Comment by ValWood** [comment]
I can't replicate it in this session...

Will keep a look out how I got to it next time....

**Comment by kimrutherford** [comment]
> Will keep a look out how I got to it next time....

Thanks.

If it happens again could you make a note of what's in the dropdown?

I'll have a look at the code and see if I can see how it got in that state.

**Comment by ValWood** [comment]
once I had selected the organism it went away.....

but I did not see it in any other session yet....

**Comment by kimrutherford** [comment]
> I'll have a look at the code and see if I can see how it got in that state.

I've had a look and I can't see any way that could happen.  So it's still odd.

**Comment by ValWood** [comment]
no worries, I'll reopen  with more info if I see it again!
