### ISSUE TITLE
odd options visible in pombe canto

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1501]
this little box just popped up in the genotype interface :-)

![screen shot 2018-06-12 at 22 05 12](https://user-images.githubusercontent.com/12727506/41317349-d60feb58-6e8c-11e8-83af-f8b60cb17d37.png)

**Comment by kimrutherford** [comment]
This is the same thing Val had yesterday: #1499.

I'm still trying to work it out.  I can't reproduce the problem at the moment.

**Comment by ValWood** [comment]
@Antonialock  How did you get there?

**Comment by ValWood** [comment]
@kimrutherford probably only happens when you get a new session, because once you set it, you don't see it again?

**Comment by Antonialock** [comment]
from memory I think it was something along the lines of

- added K44R and cki3-OP alleles
-> back to curation interface
didn't add any mutations
-> back to genotype interface
added deletion allele
-> back to curation interface
didn't add any mutations
-> back to genotype interface
saw the bug
-> added a double mutant

**Comment by kimrutherford** [comment]
Thanks!  I'll try that.

**Comment by Antonialock** [comment]
ah just remembered

at some point in the workflow I also added the gene ste9 (using the add gene function in the genotype interface) and a deletion allele

I think it was like this:
added K44R and cki3-OP alleles
-> back to curation interface
didn't add any phenotypes
-> back to genotype interface
added deletion allele
-> added the ste9 gene
-> added the ste9 deletion

-> back to curation interface
didn't add any phenotypes

-> back to genotype interface
saw the bug
-> added a double mutant

**Comment by Antonialock** [comment]
maybe it was the addition of the ste9 gene?..

I added cki3 using the "initial" add gene (initial prompt when strating the session)
but ste9 from within the genotype interface

**Comment by Antonialock** [comment]
Ah got it

I went back into the same session, went into the genotype management and added a new gene (srs1)
After I  added the gene (using the add gene hyperlink) I saw the drop down menu

![screen shot 2018-06-12 at 22 51 23](https://user-images.githubusercontent.com/12727506/41319266-2393c542-6e93-11e8-91de-f0273e0e3c16.png)

**Comment by Antonialock** [comment]
If you add a gene using the "edit gene list " hyperlink on the summary page you don't get the bug

![screen shot 2018-06-12 at 22 52 20](https://user-images.githubusercontent.com/12727506/41319340-5f159ba4-6e93-11e8-8e44-a735567b1963.png)

**Comment by Antonialock** [comment]
Elementary M'Dr's :-)

**Comment by kimrutherford** [comment]
Excellent!  Thanks for persisting.  I can reproduce that too so I'll get on with fixing it.

Cheers!

**Comment by kimrutherford** [comment]
I think I've fixed this.  Could you let me know if it works for you?

**Comment by Antonialock** [comment]
looks ok!
