### ISSUE TITLE
Host file import weird character

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1510]
There appears to be a problem with the first character being imported from the host_species.csv file

The record for Acanthamoeba castellanii has some strange characters in front

This can be observed either in the db or from the url:

<http://canto.phi-base.org/ws/lookup/organisms/host>

I checked and replaced the first A in the file but it is not making a difference when the database is trashed and reloaded. Would it be a windows header or something in the import?

**Comment by kimrutherford** [comment]
It looks like the file of organisms you're loading has a Unicode byte order mark at the start.  The loader only supports ASCII encoding at the moment.  Could you try saving the file as ASCII and reloading into Canto?

**Comment by barnabynorman** [comment]
Yes, that did the trick thanks - could not see that in my editors until I changed the mode.

Will include @jseager7 so aware.
