### ISSUE TITLE
Removing all pathogen genes doesn't remove pathogen organism

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1514]
On the Genotype Management page (and probably elsewhere), it looks like we don't have any logic to automatically remove or hide pathogen organisms with no genes. The logic for pathogen organisms isn't the same as host organisms: we still want to show host organisms with no genes, but we _don't_ want to show pathogen organisms with no genes (the latter organism state is invalid as far as PHI-Canto is concerned).

Steps to reproduce this bug:

1. Start curation session PMID 100903
2. Add UniProt P29292 (_Ascochyta rabi_)
3. Add UniProt Q074X8 (_Cercospora api_)
4. Add UniProt Q8ZCX8 (_Yersinia pestis_)
5. Go to the Genotype Management page: _Ascochyta rabie_, _Cercospora api_, and _Yersinia pestis_ should appear in the Pathogen dropdown.
6. Remove UniProt P29292 (_Ascochyta rabi_)
7. Remove UniProt Q074X8 (_Cercospora api_)
8. Go to the Genotype Management page:
   * we expect _Yersinia pestis_ to still appear in the Pathogen dropdown, since it has one gene.
   * but we do not expect _Ascochyta rabie_ and _Cercospora api_ to appear, since they have now have no genes, but they still do appear.

I think this is due to the fact that the logic we used to show no-gene host organisms is applying to the pathogen gene panel as well.

**Comment by kimrutherford** [comment]
I've fixed this now - when the last gene of a pathogen is deleted, the organism is deleted too.
