### ISSUE TITLE
[No genes] in gene list when adding host genes only

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1515]
I saw this bug a while ago, but I wasn't able to reproduce it until now. If you start a new curation session in Pathogen–Host mode and enter _only_ host genes, then the gene list doesn't display on the confirmation screen:

![no_genes](https://user-images.githubusercontent.com/37659591/41710621-09a00e28-753e-11e8-9426-cb79845013ea.PNG)

I also get this warning in the server console, but I'm not sure if it's related:

`Use of uninitialized value $taxon_ids_text in split at lib/Canto/Controller/Curs.pm line 763.`

Also, if you add one or more pathogen genes afterwards, then both lists display as normal:

![no_gene_fix](https://user-images.githubusercontent.com/37659591/41710704-3b73c480-753e-11e8-870d-8f85541a2a8f.PNG)

But then, if you remove the pathogen gene using that screen, you get the [No genes] bug again. I've tested this with genes from two different hosts and they both cause the same result.

**Comment by kimrutherford** [comment]
Thanks James.  I noticed that too when working on #1512.  I have a fix nearly ready to commit.

**Comment by kimrutherford** [comment]
> Thanks James. I noticed that too when working on #1512. I have a fix nearly ready to commit.

I misread your comment and this is a different to the problem I noticed.

I think I've fixed this error though:

> I also get this warning in the server console, but I'm not sure if it's related:
> Use of uninitialized value $taxon_ids_text in split at lib/Canto/Controller/Curs.pm line 763.

Please let me know if you still get it.

**Comment by jseager7** [comment]
I can confirm that this error is fixed now:

`Use of uninitialized value $taxon_ids_text in split at lib/Canto/Controller/Curs.pm line 763.`

**Comment by kimrutherford** [comment]
I think I've fixed this.  Please re-open if there are still problems.
