### ISSUE TITLE
Need slightly different rules for "do not annotate" for extensions  / new do not annotate restrictions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1517]
There is a branch of GO, which historically were considered  "biological processes' but are not really processes, they are just 'times when things happen', like  "mitotic M-phase" "interphase" S-phase" etc. We kept them in GO BP because we need to use them in extensions, but made the branch "do not manually annotate".

the ancestral node
biological phase has the following 

comment
"Note that phases are is_a disjoint from other biological processes. happens_during relationships can operate between phases and other biological processes e.g. DNA replication happens_during S phase."

and Restrictions
This term should not be used for direct manual annotation; it may, however, be used for mapping to external vocabularies in order to create electronic annotations. 
See comment below for further information.

Really, they should be in a separate aspect for "phases"

So, because it is restricted, we can't use it in the as an extension in the annotation extension part of the interface:

![problem](https://user-images.githubusercontent.com/7359272/41741984-925e1182-7594-11e8-971f-2fdab94f7127.jpg)

Here, I need to go back or select a child term 
(all of the children should be do not annotate too, so you are effectively, stuck)

However, the annotation extension part of the interface is already configured via a config file to say which terms are allowed, so because the annotation extensions are restricted to allowable terms, we don't need to adhere to the global taxon restrictions here (i.e a more precise term selection is already presented).

I could easily work around by using the free text option, but community curators won't be able to do this, so it should be considered fairly high priority  (and we @mah11  @Antonialock  should be wary of omissions in sessions until fixed).

**Comment by kimrutherford** [comment]
Could you let me know what term you were annotating with so I can test my fix?

**Comment by ValWood** [comment]
Any allowed GO component term, I should be able to add these extensions (I think).

Just try with 'nucleus' for example.

**Comment by kimrutherford** [comment]
I've published the fix.  Could you give it a test when you get a chance?

**Comment by ValWood** [comment]
I can't select

mitotic M phase, or descendants (mitotic anaphase etc). I can only select the leaf node?

**Comment by kimrutherford** [comment]
That's weird.  I just added "exists_during mitotic M phase" to a nucleus annotation.  Maybe do a reload?

**Comment by mah11** [comment]
That's how the ontology term search box always works, in both "main" term selection and the extension interface.

**Comment by ValWood** [comment]
So it is! usually I do it without thinking about it... here I'm cancelling the pop-up, not the extension.
