### ISSUE TITLE
sessions difficult to negotiate width-wise on a laptop

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1518]
~curs/7803457eba12e494

we should chat about this but didn't we discuss some compaction at some point?

**Comment by ValWood** [comment]
During the session, and I have seen this before,  quite a lot of white space (margin) appears  when I try to scroll right.

I can't reproduce this now, but I took a screen shot:


![scroll right](https://user-images.githubusercontent.com/7359272/41879270-d3e0de02-78d0-11e8-914a-f8eca1d849e7.jpg)

I thought maybe it was something to do with the fact that I had some stuff checked but I tried that, and it didn't reappear????

**Comment by kimrutherford** [comment]
We discussed it here: #1436

**Comment by jseager7** [comment]
Presumably this problem is going to be even worse with PHI-Canto, because for _disease formation phenotypes_ the table will have to include two genotypes: one each for the pathogen and host organisms. Even wrapping long allele names might not be enough in that case.

**Comment by ValWood** [comment]
It will be worse, but because a  "multi organism genotype" will be analogous to a multi-allele phenotype (they will be in the same field).

It will be worse because we will need the individual organism/strain info though, but the allele constructs  will hopefully be simpler than some of the ones we encounter in pombe.


This is multi-allele genotypes in the same session

![multi](https://user-images.githubusercontent.com/7359272/41908107-cbe93fcc-793a-11e8-8655-a435528e83f5.jpg)

This session was particularly bad because 13 non consecutive amino acids were mutated.
I think there will be room here for species strain info in the genotype without it ever being much worse than this....

Out of curiosity @CuzickA  do you have a feeling for   what your more complicated allele constructs might look like (at least for the present, none of us can imagine what they might look like in the medium to long term). if we know what we are dealing with now that might help.

**Comment by CuzickA** [comment]
Historically in PHI-base we haven't captured allele names and the few we have don't really follow a controlled language format. Within our expt evidence we don't capture detailed changes to nt or aa instead we have broader terms such as 'gene mutation', 'partial/full gene deletion' etc. Therefore I don't have an existing 'list' of alleles from PHI-base to look through. 
Browsing through a couple of publications I wouldn't expect  the allele names to be particularly long or complicated. 
It would become complicated in expts with multiple organisms but I think these are out of scope for PHI-Canto at the moment eg gene from one pathogen transferred to another pathogen and inoculated on host etc

**Comment by ValWood** [comment]
I'll close this ticket- It's a bit non-specific now and was partially dealt with by 
#1436 which worked for the session in question.

-so we can put new suggestions in-new tickets (I'm just about to do that!).

**Comment by ValWood** [comment]
new questions/suggestions in
https://github.com/pombase/canto/issues/1587
