### ISSUE TITLE
Update annotation retrieval server code and web service for meta-genotypes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1525]
The web service that returns the information for the annotation tables on the gene pages and on the publication/front page currently ignores meta-genotypes.

The main changes will be here: https://github.com/pombase/canto/blob/master/lib/Canto/Curs/Utils.pm#L91

**Comment by kimrutherford** [comment]
This is mostly done now although it needs more testing.  The changes are currently only on this branch: tickets/ticket-1525

**Comment by kimrutherford** [comment]
This is now working enough that I can make a meta-genotype / phenotype annotation and then view it on the details page about the meta-genotype.  I had to make the meta-genotype manually in the database but everything else works in the interface.

There is a lot to do to fine tune things but the basics are there.  I've used the word "metagenotype" in the interface as a place-holder until we decide what we want instead.

![metagenotype-details-1](https://user-images.githubusercontent.com/90474/42556593-32b84a7a-8540-11e8-8b0a-5fd69c101bb8.png)

**Comment by kimrutherford** [comment]
I've just made a new branch called metagenotype-dev and I've moved these changes to that branch.  I don't want to merge the changes onto the master branch yet because it's likely to muck up Canto for PomBase.

**Comment by ValWood** [comment]
Great progress. I'll have a play around with it when I get back.

**Comment by kimrutherford** [comment]
This is done so I'll close it.
