### ISSUE TITLE
Error when organism common_name is null/undefined

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1529]
Hi Barnaby.

I noticed the error below in the console after a adding some UniProt IDs.  I also had a spinning "Loading..." message.  Could you change the organism picker to handle the case when common_name is undefined?

Thanks.

(I think the code for loading organisms is failing to get the common_name from the UnitProt XML.  But we still need to handle organisms with no common name.  I'll look at fixing the XML parsing code.)

```
TypeError: Cannot read property 'length' of null
    at canto-modules.js:5880
    at angular.js:15757
    at m.$eval (angular.js:17025)
    at m.$digest (angular.js:16841)
    at m.$apply (angular.js:17133)
    at g (angular.js:11454)
    at x (angular.js:11652)
    at XMLHttpRequest.v.onload (angular.js:11593)
```

**Comment by barnabynorman** [comment]
@kimrutherford I have updated the code that checks if the common name is set or not and added a  test to ensure its valid before testing its length - if it fails the field will be assigned an empty string.

Regarding the spinning, you should only see that while the code is loading. Once the ajax completes a value is assigned to the organismsCount variable, which then will update the display and then if it is set to zero it reports a problem

I have altered the code to also set organismsCount to zero if ajax returns anything other than a http 200 response

**Comment by kimrutherford** [comment]
Thanks.  It's working for me now.
