### ISSUE TITLE
Can't load organisms when host organisms are configured in advance

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1533]
#### Given:

- I have re-initialised the data directory
- **And:** I have set `host_organism_taxonids` in `canto_deploy.yaml` to a list of host taxon IDs

#### When:

- I run **either** of the following commands:
   `./script/canto_load.pl --organism ~/share/host_species.csv`
  `./script/canto_load.pl --organism ~/share/pathogen_species.csv`

#### Then:

- I get the following error:
  `can't find Organism in database for taxon ID "5755" at lib/Canto/Config.pm line 161.`

- - -

In my case, the organism with taxon ID "5755" is the first organism in the `host_organism_taxonids` list.

It seems the error only happens when you have set `host_organism_taxonids` in advance of trying to load the organisms. Maybe it's because the list is checked before the organisms are loaded?

**Comment by kimrutherford** [comment]
I think I've fixed this.  Could you give it a go?

**Comment by jseager7** [comment]
Tested this again and I can confirm I no longer get the error. Thanks.
