### ISSUE TITLE
hot fix required 

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1540]
delta representation corrupted. Now appears as 

&Delta

could be confusing if you are mid session (was for me!)

![hot fix](https://user-images.githubusercontent.com/7359272/42209270-288e522e-7ea6-11e8-91bd-32f32ba4fa19.jpg)

**Comment by ValWood** [comment]
looks OK in genotype management, only looks like this in annotation table

**Comment by kimrutherford** [comment]
I think I've fixed that.  Can you check?

**Comment by ValWood** [comment]
Yep!
