### ISSUE TITLE
Canto sometimes hangs when adding a UniProt

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1541]
- **Given** a fresh install of the database, host and pathogen organisms loaded, and a curation session PMID:100900,
- **When** I tried to add a UniProt ID 'O81270'
- **Then** the application locked up,
- **And:**
  - **When** I manually interrupted Canto (Ctrl-C),
  - **Then** I got the following error in the server console:
    `internal error: Caught exception in Canto::Controller::Curs->gene_upload "Failed, got 500 Caught SIGINT - exiting for https://www.uniprot.org/uniprot/?format=xml&query=id:O81270 (https://www.uniprot.org/uniprot/?format=xml&query= + O81270)" at lib/Canto/Controller/Root.pm line 55.`
- - -
- **Given** I had restarted Canto after that (without making any changes to the database),
- **When** I tried to add a UniProt 'O81270'
- **Then** I got the following error in the browser window:
  `No genes found for these identifiers: O81270`
- **When** I tried to add a UniProt 'O04200'
- **Then** the gene added successfully.
- - -
- **Given** another fresh install of the database after that, with host and pathogen organisms loaded, and a curation session PMID:100900,
- **When** I tried to add a UniProt ID 'O81270'
- **Then** the gene added successfully.

This bug might be something transient or related to Vagrant, but if it's the case that failing to look up a gene hangs the whole application, that might not be ideal. I'm also concerned about the fact that the gene identifier seems to permanently 'break' after terminating Canto; I wonder if the database is being put in an invalid state by that.

**Comment by kimrutherford** [comment]
That annoying.  Does it happen often?

> I wonder if the database is being put in an invalid state by that.

Next time it happens could you make a copy of the database?

**Comment by jseager7** [comment]
I've only noticed it happen once (today), but I'll try to add a few genes every day to see if I can trigger it again. If I see the bug again, then I'll take a copy of the data directory. In the event that the bug is related to a server error on UniProt's side, or an inability to connect to UniProt generally, do you have any ideas on how I could force the error?

**Comment by kimrutherford** [comment]
> In the event that the bug is related to a server error on UniProt's side, or an inability to connect to
> UniProt generally, do you have any ideas on how I could force the error?

It sounds like the connection is hanging.  That could be a problem at UniProt's end but could easily be a temporary network problem.  Or Vagrant could be the problem.  It's hard to diagnose.

We could add a timeout to the request from Canto to UniProt.  I'm not sure what number of seconds to use for a timeout though.

**Comment by jseager7** [comment]
Would the UniProt connection hanging cause the application to hang for all other sessions, or just for the current user? If it's the former case, then we absolutely need a timeout and we probably want it to be as short as possible; if it's the latter case, we could set the timeout longer, maybe 10 seconds or so.

I just tested loading 20 genes from the same organism and got a response in about 8 seconds.

Then I removed all the genes and tried again and got a response time in under 1 second. Maybe there's some caching mechanism on the UniProt side, if Canto isn't doing its own caching already.

Unfortunately I think the timeout might be dependent on how many genes are added at once.

**Comment by kimrutherford** [comment]
> Would the UniProt connection hanging cause the application to hang for all other sessions, or just for
> the current user?

On a production server there will be multiple Canto processes running to handle requests (PomBase has 16) so one can hang for a while without stopping the others.

> if it's the latter case, we could set the timeout longer, maybe 10 seconds or so.
>
> I just tested loading 20 genes from the same organism and got a response in about 8 seconds.

The timeout should probably be quite a bit higher than what we think it the worst case.  It's better that it takes a while than give an error.

> Then I removed all the genes and tried again and got a response time in under 1 second. Maybe there's
> some caching mechanism on the UniProt side, if Canto isn't doing its own caching already.

Canto caches the fields it needs so that it doesn't need to fetch the XML from UniProt again.

**Comment by jseager7** [comment]
@kimrutherford Just now I thought the problem with the selection border and the background colour could be solved if those CSS selectors targeted the `<tr>` elements _inside_ the `<tbody>` rather than the `<tbody>` element itself.

While that would work for single allele genotypes, it doesn't help us when it comes to multi-allele genotypes, because we want the selection border to cover a group of rows, not just one. I thought about nesting `<tbody>` elements to handle this, but that's a violation of the CSS specification (`<tbody>` only permits `<tr>` as children), so browsers can just choose to ignore it.

I'll have to keep thinking.

**Comment by jseager7** [comment]
Closing this now, because I've opened a new issue at #1572.
