### ISSUE TITLE
Think about improving UniProt XML parsing for gene names

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1543]
On Tuesday 3 July 2018 at 09:57:47, James Seager wrote:

> There's been some discussion in the following issue about the fact
> that (as I understand it) UniProt sometimes returns some long
> systematic identifiers instead of shorter gene names for some genes: 
>
> https://github.com/pombase/canto/issues/1508#issuecomment-401030625
>
> Val said that "the gene name should be retrieved from UniProt and
> displayed in the annotation tables (it will usually be more
> readable). This gene hasn't yet been assigned a real gene name...."
>
> Is this anything to do with Canto's logic (meaning, is Canto
> sometimes using the wrong data for display purposes), or is it a
> UniProt issue?

I'm not sure.  UniProt does some odd things but we might be able to
improve our XML pasrsing.

Here's the XML from that issue:
  https://www.uniprot.org/uniprot/A0A1Q4I1Y1.xml

And here is a better annotated protein:
  https://www.uniprot.org/uniprot/O74638.xml

In O74638 we get the gene name from this bit:

```xml
  <gene>
    <name type="primary">URA7</name>
    ...
```

The code looks for a gene name with type "primary".

If that bit is missing (like in A0A1Q4I1Y1) we fall back to the name field at the top of the entry ("A0A1Q4I1Y1_9MYCO" in this case):

```xml
  <entry dataset="TrEMBL" created="2017-04-12" modified="2017-06-07" version="3">
    <accession>A0A1Q4I1Y1</accession>
    <name>A0A1Q4I1Y1_9MYCO</name>
    ...
```

Using that name might not be best.  As Val points out there's a better name for A0A1Q4I1Y1.  It's in the `<gene>` section:

```xml
  <gene>
    <name type="ORF" evidence="4">BRW65_00080</name>
  </gene>
```

Maybe we should use that?

A complication is that there can be more than one name with type "ORF"
in that section so we'd just have a pick one and hope for the best.

I think this needs discussion.

**Comment by barnabynorman** [comment]
It should also be noted that gene names being returned for the same organism are sometimes different preventing the creation of a multi alleles.

For example on uniprot we see:
Q00909 -> Gibberella zeae (strain PH-1 / ATCC MYA-4620 / FGSC 9075 / NRRL 31084) (Wheat head blight fungus) (Fusarium graminearum)
P0CS93 -> Gibberella zeae (Wheat head blight fungus) (Fusarium graminearum)

But in phi-canto we have:
Q00909 -> Gibberella zeae (strain PH-1 / ATCC MYA-4620 / FGSC 9075 / NRRL 31084)
P0CS93 -> Fusarium graminearum

Both technically correct but inconsistent - is this a caching issue / or the uniprot api resolving from several sources?
I noted a 502 error on the summary page earlier

**Comment by kimrutherford** [comment]
The difference is that P0CS93 has taxon ID 5518 - which is the species (ie. Gibberella zeae):
 https://www.uniprot.org/uniprot/P0CS93#names_and_taxonomy
 https://www.uniprot.org/taxonomy/5518

But Q00909 has taxon ID 229533 which is a particular strain of Gibberella zeae:
 https://www.uniprot.org/uniprot/Q00909#names_and_taxonomy
 https://www.uniprot.org/taxonomy/229533

That's a big pain.  We talked a bit about that here: #1468

We may need to add the taxon IDs of the host strains to the configuration so we know which organism the users really meant.  So if they use a UniProt ID of a protein with taxon ID 229533 we could store 5518 in Canto's database.

It looks like we can retrieve all descendant nodes of a taxon with a query like:
https://www.uniprot.org/taxonomy/?sort=&desc=&compress=no&query=ancestor:5518&fil=&format=tab&force=yes&columns=id

**Comment by ValWood** [comment]
yes, you need some way to "normalise" to the species name here not the strain

**Comment by ValWood** [comment]
> A complication is that there can be more than one name with type "ORF"

that shouldn't really be possible.
Do you have examples and i'll ask Uniporot why.

 What type of "names" do Uniprot  provide?


Ideally we  would use 
Name:cdc2 (which *should* be unique)
if not 
Name: 
Use ORF name (which should also be unique, only one group will be naming the ORFS in a genome systematically)

**Comment by kimrutherford** [comment]
Here are some examples:

https://www.uniprot.org/uniprot/P04551.xml
https://www.uniprot.org/uniprot/Q00909.xml

> What type of "names" do Uniprot provide?

In the XML for cdc2 they have these IDs:

```xml
<accession>P04551</accession>
<name>CDK1_SCHPO</name>
```

then later they have these names:

```xml
<gene>
  <name type="primary">cdc2</name>
  <name type="synonym">cdk1</name>
  <name type="synonym">swo2</name>
  <name type="ORF">pi002</name>
  <name type="ORF">SPBC11B10.09</name>
</gene>
```

**Comment by ValWood** [comment]
yes  pi002  type names should probably be treated as synonyms ( they are obsolete really).

I guess different orf names would be assigned if different groups suenenced, and the entries were merged. I  Wonder how often this happens for the species of interest.

Ideally, you would use the more humanly recognizable "primary" when available.

Do they  always assign  "primary"  (i.e use the ORF name if not yet assigned official names?)

If so, this would solve the problem, we can just use "primary"

**Comment by kimrutherford** [comment]
> Do they always assign "primary" (i.e use the ORF name if not yet assigned official names?)

I've finally got to looking at this.  Sorry it took so long.

There is not always a primary gene name.  In example from #1858 the XML has:

```xml
    <accession>A9JX75</accession>
    <name>A9JX75_PHANO</name>
    <protein>
      <submittedName>
        <fullName evidence="2">Uncharacterized protein</fullName>
      </submittedName>
    </protein>
    <gene>
      <name type="ORF" evidence="2">SNOG_20078</name>
    </gene>
```

and sometimes the primary gene name isn't great. eg.
https://www.uniprot.org/uniprot/M1AWN5 -

```xml
    <accession>M1AWN5</accession>
    <name>M1AWN5_SOLTU</name>
    <protein>
      <submittedName>
        <fullName evidence="1">Uncharacterized protein</fullName>
      </submittedName>
    </protein>
    <gene>
      <name type="primary" evidence="1">102583820</name>
    </gene>
    <organism evidence="1 2">
      <name type="scientific">Solanum tuberosum</name>
      <name type="common">Potato</name>
      <dbReference type="NCBI Taxonomy" id="4113"/>
```

**Comment by ValWood** [comment]
gene name for potato isn't great, but at the moment that is it's name" <name type="primary" evidence="1">102583820</name> !

Also another question. Can we have a way to 'refresh'the names as these systematic identifiers are replaced with "real" names. Usually people name when they publish.  We can alert Uniprot to add the real name but it will take a few months to filter through to us.....

**Comment by kimrutherford** [comment]
> Can we have a way to 'refresh'the names as these systematic identifiers are replaced with "real" names.

There isn't a way to do it in the interface but at any time we can manually delete the local cache of gene names and force Canto to re-fetch from UniProt.

**Comment by kimrutherford** [comment]
This issue is related: #1736

**Comment by ValWood** [comment]
should use
primary if there is one and ORF if there isn't

A9JX75_PHANO
would use

<gene>
<name type="ORF" evidence="2">SNOG_20078</name>

**Comment by kimrutherford** [comment]
> should use primary gene name if there is one and ORF name if there isn't

I've finally made that change.

**Comment by kimrutherford** [comment]
@jseager7 could you test this out in PHI-Canto the next time you update to the latest code?

**Comment by jseager7** [comment]
@kimrutherford I've tested the example given by Val under my local copy, and it seems to work fine here: the gene name is SNOG_20078 as expected. I'm not aware of any other examples I can test. 

One oddity is that on the confirmation page, the gene lists its own name as a synonym:

![image](https://user-images.githubusercontent.com/37659591/68199704-75620680-ffb6-11e9-8e3b-a0b3ab34ad4a.png)

Maybe this is because Canto normally views ORF names as synonyms of the primary name: we probably want to blank this column if there's no primary name and only one ORF / alternative name.

**Comment by kimrutherford** [comment]
> One oddity is that on the confirmation page, the gene lists its own name as a synonym:

Thanks for spotting that.  I should be able to fix that.

**Comment by kimrutherford** [comment]
> One oddity is that on the confirmation page, the gene lists its own name as a synonym:

That's fixed now.

**Comment by jseager7** [comment]
I think this issue is all done now. Closing.

**Comment by jseager7** [comment]
Reopening because I've found another gene name case that doesn't seem to be handled by `UniProtUtil`.

One of our curation sessions uses accession number [Q9I1W9](https://www.uniprot.org/uniprotkb/Q9I1W9/entry), for which PHI-base requested the gene name PA2146, but Canto is showing the entry name (RGVIR_PSEAE) instead of the gene name:

![image](https://user-images.githubusercontent.com/37659591/203794629-6849e6b0-5221-4856-aa07-c4e3ecf5aa34.png)

In the [UniProt XML](https://rest.uniprot.org/uniprotkb/Q9I1W9.xml), the gene name has a type of "ordered locus".

```xml
<gene>
    <name evidence="4" type="ordered locus">PA2146</name>
</gene>
```
I can't find any reference to "ordered locus" in `UniProtUtil` so I'm assuming the code doesn't cover this case. 

Since there is only one gene name and it is not tagged as "primary", I'm guessing the following code in `UniProtUtil` is being executed:

https://github.com/pombase/canto/blob/4cc8a86a463faf5021052a7a89be69f788f61569/lib/Canto/UniProt/UniProtUtil.pm#L101-L111

So all that should need changing here is to add another case:

```perl
if ($synonym->{type} eq 'ORF' ||  $synonym->{type} eq 'ordered locus') {
  $name = $synonym_content;
  last;
}
```
Although I have no idea whether ORF names should be given higher precedence than ordered locus names.

(References https://github.com/PHI-base/curation/issues/102)

**Comment by kimrutherford** [comment]
Hi James.  Thanks for investigating that.

> So all that should need changing here is to add another case:

I think your change makes sense.

> Although I have no idea whether ORF names should be given higher precedence than ordered locus names.

I found an entry that has both: https://www.uniprot.org/uniprotkb/Q0DHH6/entry
The "ordered locus" (`Os05g0465800`) is shown in the header section as the "Gene" and in [the XML](https://rest.uniprot.org/uniprotkb/Q0DHH6.xml) the "ordered locus" comes first so I think we can assume that they are higher precedence than ORFs.

If we wanted to make sure we use the ordered locus where available we could make this change instead:

```perl
         }                                                                                                                                                             
       }                  
                                                                                   
+      if (!defined $name) {        
+        for my $synonym (@{$entry->{gene}->[0]->{name}}) {
+          my $synonym_content = _content($synonym);
+                                                                                  
+          if ($synonym->{type} eq 'ordered locus') {                              
+            $name = $synonym_content;
+            last;         
+          }
+        }                                                                         
+      }         
+                                                                                  
       if (!defined $name) {      
         for my $synonym (@{$entry->{gene}->[0]->{name}}) {                        
           my $synonym_content = _content($synonym); 
```

**Comment by ValWood** [comment]
Do ordered locus names ever differ from orf names? (I thought they were just different names for the same label). This is one of the things I would like to address at the  Biocuration focus group. It is an issue raised by the HGNC.

**Comment by kimrutherford** [comment]
> Do ordered locus names ever differ from orf names? 

There are some differences.  Here's an example:
https://www.uniprot.org/uniprotkb/Q0DHH6/entry#names_and_taxonomy

**Comment by jseager7** [comment]
> If we wanted to make sure we use the ordered locus where available we could make this change instead:

I think I'd still prefer to have the ORF name used as a fallback option rather than only checking for the ordered locus name (I assume that's what the code above is implying) just so we can avoid using the entry name wherever possible, since the  entry name is almost meaningless to curators (the only information you get in the entry name besides the UniProtKB accession number is an obscure species abbreviation, which is almost completely redundant in PHI-Canto since the curation summary page already groups genes by species).

So I'd suggest the following order of precedence:

1. primary gene name
2. ordered locus name
3. ORF name

And if there are multiple names of the same type with no primary attribute, then I guess we can just use the first name seen in the XML.

> The "ordered locus" (Os05g0465800) is shown in the header section as the "Gene" and in the XML the "ordered locus" comes first so I think we can assume that they are higher precedence than ORFs.

Oddly enough, the order is flipped on the entry page: the ORF name comes first and the ordered locus second.

**Comment by kimrutherford** [comment]
> I think I'd still prefer to have the ORF name used as a fallback option rather than only checking for the ordered locus name

I agree.  Here's my full patch:
  -  https://github.com/pombase/canto/pull/2675

If I have the logic correct, it checks the "ordered locus", then the "ORF" synonyms.

**Comment by kimrutherford** [comment]
Hi @jseager7

Can we close this now?

**Comment by jseager7** [comment]
Yes, I think so.
