### ISSUE TITLE
Gene and Organism Confirmation page

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1544]
@kimrutherford I have been looking at the confirmation / list page:

![image](https://user-images.githubusercontent.com/1710907/42231586-db928ad8-7ee3-11e8-9f7c-54c115cc7b63.png)

In my mind the simplest solution would be to add the "Host organisms" box conditionally to the existing confirm_genes page as another gene_list_edit_table, which would also bring the delete style in-line with the rest of the site.

An alternative would be for you to create a new static page with a angular js directive on it, and I generate the html, and either post deletions back to an api or mimic existing code with a hidden input field that is set when a row is deleted. It was suggested that this would reduce clicks but looking at it, it is a click neutral solution as the form has to be posted regardless to take the user to the next section.

I did think about a hybrid where we just replaced the gene_list_edit_tables with a directive and inject in json, but that felt hacky and would be messy!

Either way, this seems to be the next bit to code, so do you mind taking a look if you have time please?

**Comment by kimrutherford** [comment]
> In my mind the simplest solution would be to add the "Host organisms" box conditionally to the existing
> confirm_genes page

I agree.  As a first step, I've added a table of the hosts that have no genes.  It should look like this now:

![hosts-with-no-genes-1](https://user-images.githubusercontent.com/90474/42265137-c9cc5692-7fc6-11e8-9f57-965d95de230e.png)

Could you give it a try?

The text "Host organisms that have no genes in this curation session: " is just the first thing that came into my head.  The text is here when we need to edit it:

https://github.com/pombase/canto/blob/master/root/curs/gene_list_edit.mhtml#L43

**Comment by barnabynorman** [comment]
@kimrutherford thank you, it looks great apart from that it shows all the organisms in the system, rather than just the one that I specified.
Also would it be possible to remove the organisms here too, to make it the same as the genes?
I will update the text if its not right

**Comment by kimrutherford** [comment]
> it looks great apart from that it shows all the organisms in the system

Whoops, I think I've fixed that.  Could you try again?

> Also would it be possible to remove the organisms here too, to make it the same as the genes?

Yep, that's what I'll do next.  I just wanted to get the table working first.

**Comment by barnabynorman** [comment]
@kimrutherford looking good!

**Comment by barnabynorman** [comment]
@kimrutherford I have changed the order of the Host organisms to match the previous page.

Please can you update the text in two places, on the header and the add gene link as per slide 7 on the July mockup:

https://docs.google.com/presentation/d/116o9n4l7iAyInVHyXmXo3Ihr1JqSZhn0NFzGEUzffMQ/edit#slide=id.g3d4f85de30_9_2

"Confirm gene and host organism(s) list for PMID:1234"

"Add more genes and host organisms from PMID:1234 ..."

I could change them, but they need to be conditional so they still have the right text when not in multi organism mode

**Comment by kimrutherford** [comment]
> I have changed the order of the Host organisms to match the previous page.

Thanks.  When you make a commit could you reference the appropriate issue(s)?  Like I did in this commit with "Refs #1544" on a line by itself: https://github.com/pombase/canto/commit/937d54cf4e322eb582664ba6a7aacf7e68adf59f

> Please can you update the text in two places, on the header and the add gene link as per slide 7 on
> the July mockup:

I've made those changes.

**Comment by kimrutherford** [comment]
> Also would it be possible to remove the organisms here too, to make it the same as the genes?

I've added checkboxes for the host organisms on the gene upload confirmation page and the "Remove selected" now removes selected organisms.  I've also fixed a few of the messages to mention host additions and deletions.

Could you give it a go on Monday?

**Comment by barnabynorman** [comment]
@kimrutherford looks great - thanks!
