### ISSUE TITLE
can't edit existing genotype

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1553]
It doesn't matter whether the genotype has one or more alleles, nor whether it has any annotations or not. Fails every time, with a red popup:

![screen shot 2018-07-09 at 1 53 28 pm](https://user-images.githubusercontent.com/5196259/42452511-1d5d316e-8382-11e8-9d1e-f1b2728b8698.png)

Adding a background via the "Add/edit background ..." mouse-menu option also fails, but silently. The text-box popup appears, but clicking "Finish" acts just like clicking "Cancel".

Adding, duplicating/editing, and deleting (fortunately) all work fine.

first spotted in c480fb02b530ca54
also tested in 885eefd237119afe (no genotypes in that session just now - I added and deleted a couple fake ones just for the sake of more testing)

pretty important because there's at least one community session where I really ought to tidy one or two genotype names/descriptions before approving

**Comment by mah11** [comment]
p.s. Chrome or Firefox, no difference; logged in as myself (i.e. admin)

**Comment by kimrutherford** [comment]
Sorry about that.  I think I've fixed the problem.  Could you try again?

**Comment by kimrutherford** [comment]
I did a quick patch to fix this but I need to do a better job.  So I'll leave this issue open.

**Comment by mah11** [comment]
I'm happy to let you decide when to close it ;)
