### ISSUE TITLE
Make a meta-genotype management / creation page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1556]
We need to add the following elements for Pathogen and Host organisms:

- Organism selector (drop-down, re-used from Genotype Management page).
- Strain selector (to be decided).
- Genotype list (re-used from existing templates), plus selectors (radio-buttons, since we can't select more than one genotype for each organism).
- Shortcuts to edit the genotypes in the list (optional).
- a control to combine selected genotypes into a meta-genotype.
- Meta-genotype list (a meta-genotype is a combination of two genotype tables).

**Comment by jseager7** [comment]
Here's the latest mockup:

![metagenotype_tables](https://user-images.githubusercontent.com/37659591/42505962-5d7b7290-8438-11e8-994a-c259ec36bf30.png)

**Comment by ValWood** [comment]
This looks like a good approach,  where will your gene list(s) be, in the same place as the main version?

I think there is room for  it with this plan so it wouldn't be a problem.

It looks like a lot of tables, but in general the genotypes will be much simpler than ours. I suspect that, at the moment multi-gene alleles are rare within pathogen-host interactions for example. they are mainly one gene in each species?

v

**Comment by kimrutherford** [comment]
> This looks like a good approach, where will your gene list(s) be, in the same place as the main version?

We think it will be too complicated to have the genes tables on the meta-genotype page.  So the plan is to leave the genotype creation on the genotype management pages.  The meta-genotype management page will allow the user to pick one host and one pathogen genotype (that have been made previously) to create a meta-genotype.

We'll be able to get something up and running quickly this way.  Once we have something basic working we think about ways to improve the workflow.

**Comment by ValWood** [comment]
Sounds like a good plan.

**Comment by kimrutherford** [comment]
I've just added a skeleton `root/static/ng_templates/metagenotype_manage.html` for the `metagenotype-manage` directive.  It's on the metagenotype-dev branch.

**Comment by kimrutherford** [comment]
There is no link yet to the meta-genotype management page but you're on the branch you can get there by going to `/metagenotype_manage`, like:

http://localhost:7006/curs/d86eec684a0745bc/metagenotype_manage

I think the next step is to do #1558.

**Comment by barnabynorman** [comment]
@kimrutherford the meta-genotypes returned are not coming with allele arrays, so I could use the ref and look them up another way or do you have them stored so they can be returned with the rest of the genotype data please?

**Comment by kimrutherford** [comment]
Hi Barnaby.

I'm using the metagenotype-dev branch.  I tried to reproduce this locally but I don't get a "Make it -->" button.

Do I need to be on a different branch?

**Comment by kimrutherford** [comment]
> the meta-genotypes returned are not coming with allele arrays

That's fixed now.
