### ISSUE TITLE
Extend Organism service to filter by Pathogen or Host

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1557]
Due to the changes in thinking with the meta-genotype and genotype management views (see #1555), we now need to change the Perl organism webservice to have an option to return just the Pathogen or Host organisms, such that filtering can be done at the service level, rather than in an AngularJS controller.

**Comment by kimrutherford** [comment]
I've add a "pathogen_or_host" parameter to the genotype list lookup.  So you can now do something like:

```javascript
CursGenotypeList.cursGenotypeList({ pathogen_or_host: "host", include_allele: 1 }).then(...
```

If the "pathogen_or_host" parameter is undefined or not present the service will return all the genotypes.

I've committed the change to the master branch.
