### ISSUE TITLE
Storing Meta-genotypes on server

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1566]
@kimrutherford please could you take a look at the backend code that stores the metagenotype:

<'/feature/metagenotype/store'>

I am passing into it integers for pathogen and host ids via the CursGenotypeList::storeMetagenotype() service method in canto-modules.js

It looks like it is returning an http 200 response as the code in the storeGenotypeHelper::storeMetagenotypeHelper() helper method is not catching any error, but on inspecting the promise there is an error under value.data saying "Storing new meta-genotype failed: internal error - please report this to the Canto developers"

Its not erroring every time so I am guessing the back-end is checking they really are pathogen and host ids, but the error might need fixing!

**Comment by kimrutherford** [comment]
Thanks for giving it a test.  Are there any error messages from console on the server?

**Comment by barnabynorman** [comment]
Nope none

**Comment by kimrutherford** [comment]
I think I've fixed this problem.  I've pushed the fix to the metagenotype-dev branch.  A unique constraint was failing in the database.
