### ISSUE TITLE
populate "product" with uniprot "protein name"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1568]
the blank field (product) 
in this table

![product](https://user-images.githubusercontent.com/7359272/43193301-910aa76e-8ff7-11e8-9af8-4bc6c18496d2.jpg)

shoudl be populated  with the "protein name" from uniprot.

Note that sometimes there is more than one "product name", bu UniProt have selected on as "primary"

![protein name](https://user-images.githubusercontent.com/7359272/43193381-c988268e-8ff7-11e8-824f-67c7a6bb62ea.jpg)

here they have not selected the most informative one, but hey ho...

**Comment by kimrutherford** [comment]
The product is retrieved for some entries already (see example below).  The product in your example is stored in a different XML element.  "submittedName" versus "recommendedName".

It should be an easy fix to support both element types.

![uniprot-product-1](https://user-images.githubusercontent.com/90474/43823185-678a52c6-9b42-11e8-8649-bf26bb597a6b.png)

**Comment by kimrutherford** [comment]
Now fixed.
