### ISSUE TITLE
no extension prompt

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1569]
normal protein localization to mitotic spindle midzone FYPO:0003349

**Comment by mah11** [comment]
I checked the configuration, and it looks like it should work. The file has this:

    FYPO:0002333	is_a	assayed_using	ProteinID	assayed protein	0,1	user

and FYPO:0003349 has some all-is_a paths to FYPO:0002333

**Comment by ValWood** [comment]
weird. It's there. I checked a few similar terms in case I typo-ed but all seem to have it...
