### ISSUE TITLE
Gene names don't resolve after extension 'editing as text"

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1574]
Not a big thing but I find it a bit annoying.

If you edit an annotation extension as text (instead of selecting from e.g. dropdown of gene names) then the gene names do not resolve to primary names (whatever you entered free text is shown). Would be nice if it is possible to resolve them.

e.g. here I copied an extension (the one showing primary names) and pasted it into the second phenotype (the one showing sys IDs)

<img width="973" alt="screen shot 2018-07-26 at 22 43 54" src="https://user-images.githubusercontent.com/12727506/43290248-6d38311a-9125-11e8-9fd7-567f368d359b.png">

**Comment by ValWood** [comment]
I  had never made the connection, but I always wondered why they sometimes resolved differently...

**Comment by ValWood** [comment]
DO this if quick, if not quick  it's not urgent

**Comment by kimrutherford** [comment]
That should be fixed now.
