### ISSUE TITLE
annoying jump to top of page

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1575]
This is a thing that I find pretty annoying.

In this example I wanted to add an additional extension to several phenotypes (community curator had only specified one gene in an extension instead of two).

I click on edit (phenotype): 
<img width="938" alt="screen shot 2018-07-26 at 23 30 00" src="https://user-images.githubusercontent.com/12727506/43292170-1d682986-912c-11e8-89ef-5f5bad77020b.png">

and then on (annotation extension) edit:

<img width="1033" alt="screen shot 2018-07-26 at 23 30 09" src="https://user-images.githubusercontent.com/12727506/43292204-3862dd8a-912c-11e8-9d2a-77476bac95d1.png">

and then on "affected proteins, add two..."
at this point the background jumps up to the top of the screen

<img width="1129" alt="screen shot 2018-07-26 at 23 30 21" src="https://user-images.githubusercontent.com/12727506/43292218-413b8998-912c-11e8-9229-8e319f6b8437.png">

So when clicking OK I end up at the top of the page, instead of at the "point of entry" in the phenotype table
<img width="1112" alt="screen shot 2018-07-26 at 23 30 33" src="https://user-images.githubusercontent.com/12727506/43292235-52873b98-912c-11e8-8fe6-9c5c095f5580.png">

It's annoying when you are editing several phenotypes (because of one repeated mistake) because you keep having to find where in the phenotype table you were

**Comment by ValWood** [comment]
Is it possible to pin so that when pop-ups are closed you  return to the place in the page from where you called the pop-up?

**Comment by kimrutherford** [comment]
> at this point the background jumps up to the top of the screen

@Antonialock I think I've fixed this.  Could you give it a go?

**Comment by Antonialock** [comment]
will try once canto is back up.

**Comment by Antonialock** [comment]
So original problem fixed thanks! I noticed that this also happens when you click 'add independent extension' is it possible to apply the same fix for that?

**Comment by kimrutherford** [comment]
I've committed a fix but I can't update the main Canto yet.  We're still testing the changes to support PHI-base and I don't want to risk breaking anything.  I hope to update the main Canto next week.

**Comment by kimrutherford** [comment]
> So original problem fixed thanks! I noticed that this also happens when you click 'add independent
> extension' is it possible to apply the same fix for that?

I've just checked the test server and it's fixed there.  So it should be in the main Canto soon.

**Comment by kimrutherford** [comment]
> So it should be in the main Canto soon.

The fix is release now.
