### ISSUE TITLE
 self selecting a paper reveals names and e-mails (desabel autocomplete)

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1580]
When self-selecting a paper other users e-mails pop up in the e-mails and name fields.

For privacy purposes we should disable this.

**Comment by kimrutherford** [comment]
Could you add a screenshot of this?  Canto doesn't do any autocompletion of names or email addresses.

**Comment by ValWood** [comment]
![test](https://user-images.githubusercontent.com/7359272/43370674-5323ad7e-937b-11e8-9a19-c6d480d26435.jpg)

perhaps it's only in admin because it's needed to attach papers to users  for curation?
if jo public does not see this, it's OK

**Comment by kimrutherford** [comment]
> perhaps it's only in admin because it's needed to attach papers to users for curation?
> if jo public does not see this, it's OK

I think your browser is remembering the email address.  Canto doesn't isn't doing that autocompletion.

**Comment by ValWood** [comment]
ok!
