### ISSUE TITLE
Export meta-genotypes and meta-genotype annotation to JSON export file

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1581]
https://github.com/pombase/canto/blob/master/lib/Canto/Curs/Serialise.pm

**Comment by kimrutherford** [comment]
This is implemented now.  The command to export all approved sessions is:

    ./script/canto_export.pl canto-json --dump-approved --all > exported_sessions.json

**Comment by martin2urban** [comment]
I tried to export data, but no luck.
The command to export all data similar to the one given above is:
`./script/canto_export.pl canto-json --all > export.json`

The following error is obtained:
![image](https://user-images.githubusercontent.com/2812591/51074460-74529800-1677-11e9-94b7-063cedd03b5f.png)

**Comment by kimrutherford** [comment]
I'm not sure why that's happening.  Which server did you run the command on?

**Comment by martin2urban** [comment]
All Phicanto servers are affected. I understood that servers were rebuild in Nov/Dec last year while  the [instructions how to build the Phicanto servers](https://github.com/PHI-base/config/wiki/Setting-up-the-server-on-Hetzner ) were developed. Perhaps something was forgotten or or a new apt-get update caused the problem?

**Comment by martin2urban** [comment]
Success!  I can confirm that the servers were rebuilt using Docker. The above mentioned commands worked on 2019-01-14 on all Phicanto servers.
@kimrutherford @jseager7 : I made the PHI-base/config repository public and gave you write access. You should now be able to view and edit the [instructions how to build the Phicanto servers ](https://github.com/PHI-base/config/wiki/Setting-up-the-server-on-Hetzner). Perhaps it would be good if you also have direct access to the Hetzner Phicanto servers? If so, James could give you access.
