### ISSUE TITLE
PHI-Canto using common names instead of scientific names

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1595]
Certain elements on PHI-Canto are displaying organism names as common names instead of scientific (binomial) names, and @CuzickA would prefer if they always showed scientific names.

There's two places we've noticed so far where the problem occurs. First is the gene list on the curation summary page:

![common_name_gene_list](https://user-images.githubusercontent.com/37659591/43840310-49cd596a-9b18-11e8-95f5-927aded7f625.PNG)

(Note that the problem doesn't occur when no common name is specified.)

The second place is the list of existing annotations when viewing metagenotype details:

![common_name_annotation_list](https://user-images.githubusercontent.com/37659591/43840357-67ef1834-9b18-11e8-80a1-18ed5f91d2d8.PNG)

**Comment by jseager7** [comment]
I've just tested changing to scientific names on the gene list, and it all works fine except for the fact that we still have the strain information included in some cases, so the name can be very long:

![gene_list_long_strain](https://user-images.githubusercontent.com/37659591/43841499-3eb0a034-9b1b-11e8-83e8-d914e07bc44b.PNG)

**Comment by kimrutherford** [comment]
> First is the gene list on the curation summary page:

> The second place is the list of existing annotations when viewing metagenotype details:

I've fixed both those places.

> it all works fine except for the fact that we still have the strain information

I think that's covered by: #1467
