### ISSUE TITLE
Consider adding a comment field on genotypes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1599]
It could be very similar to the background.

**Comment by kimrutherford** [comment]
On the last PHI-Canto call @CuzickA mentioned a case where having a comment field for genotypes might be useful for PHI-Base too.  I think it was when a region is deleted from a chromosome.

**Comment by ValWood** [comment]
we also had a low priority ticket for this
https://github.com/pombase/canto/issues/1278
which I'm closing as "duplicate"

**Comment by kimrutherford** [comment]
This issue says "Consider" in the title and has the "discuss" label.  Should we definitely make this change or does it still discussion?

**Comment by ValWood** [comment]
Its definitely required.

**Comment by kimrutherford** [comment]
I've added a comment field for genotypes.  Comments can be added or edited in the same places as the background, the genotype edit page or in the menu on the right of the genotype lists:


--------------------------

![genotype-comment-2](https://user-images.githubusercontent.com/90474/54962832-3fde4f00-4fcb-11e9-9fbd-c80c9704caf4.png)

--------------------------

![genotype-comment-3](https://user-images.githubusercontent.com/90474/54962839-4371d600-4fcb-11e9-94d7-7996bfd94432.png)

**Comment by kimrutherford** [comment]
The change is now live on the fly-canto test server.  eg. https://curation.pombase.org/flybase-test/curs/e974e992ec7e2aad/genotype_manage

The comment isn't visible in the genotype tables so it's quite hidden.  We should talk about that.

**Comment by vmt25** [comment]
note on usage: this will be used for phenotype free text

**Comment by vmt25** [comment]
The comment is the summary of the allele's phenotypes found in a publication. Thus, it is associated with the allele-publication.

It would be nice if the field could be more easily accessed and more visible once a comment has been made

**Comment by vmt25** [comment]
This is for after sorting genotypes (#976) and genetic interactions

**Comment by kimrutherford** [comment]
Is there anything else to do here?

**Comment by vmt25** [comment]
Fly-Canto will need long-ish text fields for phenotypes (and genetic interactions).
I thought this was the ticket for it, but better to close this one and open another with a more descriptive title.
