### ISSUE TITLE
Genotype list doesn't always update on meta-genotype page

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1600]
I've noticed on the latest checkout of `pombase:metagenotype-dev` (c2691b859ed5e1d24f1cc664e8c898742ca9387b as of the time of writing) that the genotype list doesn't update when a different organism is selected: instead, it keeps showing the genes for the organism that was selected first.

Note that the problem only occurs when the selected organism is changed _after_ an organism has been selected first &ndash; if you unset the organism selector and _then_ select an organism, the genotype list displays correctly.

I'm not sure if this issue is to do with the organismSelector directive, or the containing directives on the `metagenotype_manage` page. @barnabynorman I might need your help to figure this out.

**Comment by barnabynorman** [comment]
@jseager7 please could you check this is working now?

**Comment by jseager7** [comment]
Looks like it's fixed for me. Thanks.
