### ISSUE TITLE
'Edit details...' is broken on Genotype Management page

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1604]
Commit a774b49926fe4544f6a643d1171fb71759789868 on `metagenotype-dev` has a bug where the genotype editing view isn't displaying on the genotype management page.

I've stepped back through the commit history, and the first commit I can find where this bug doesn't occur is e5c73992ef5377fbcd0b4d15ae1e18c8b5eed160 &ndash; it doesn't occur in e9f2b0368aaefac97cd596b7779c01c72f423620, so it seems like it's been broken for some time. I didn't check every commit in the chain, so it's possible that it's been fixed at some point since then, but has broken again now.

I've checked the `hashChangedHandler()` method in `genotypeManageCtrl` ([see here](https://github.com/pombase/canto/blob/53b9c6d6a0b8fd0aacadb7845bbec57a8a748a59/root/static/js/canto-modules.js#L3730-L3747)), but there don't seem to be any obvious problems there.

The `genotypeViewCtrl` seems to be responsible for changing the URL in `$scope.editGenotype(genotypeId)` ([see here](https://github.com/pombase/canto/blob/53b9c6d6a0b8fd0aacadb7845bbec57a8a748a59/root/static/js/canto-modules.js#L3486-L3489)) so that the `genotypeManageCtrl` can respond to it, but again there doesn't seem to be anything obviously wrong with that method.

**Comment by kimrutherford** [comment]
Thanks for investigating that.  I don't understand why but closing the "genotype-edit" directives with `</genotype-edit>` rather than `/>` seem to fix it.  We close directives with `/>` in other places and it works fine so that's weird.

**Comment by kimrutherford** [comment]
Ah, according to this we should be using `/>`:
  https://stackoverflow.com/questions/18103183/angularjs-element-directives-not-displaying-when-using-self-closing-tags
