### ISSUE TITLE
window.location.href doesn't match pathogen/host genotype pages

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1606]
(Possibly related to #1604)

Some of the AngularJS code manually sets the `window.location.href` to a hyperlink containing the directory `genotype_manage`, but this isn't used for PHI-Canto anymore since we split the genotype management pages: the correct paths should include `host_genotype_manage` and `pathogen_genotype_manage` instead.

The genotype management page is reset to the 'default' mode any time the `window.location.href` is changed to point at `genotype_manage`, which effectively reloads the page, resets the organism selector, and all hosts and pathogens are shown in the selector from then on.

Here's an example of the faulty code:

https://github.com/pombase/canto/blob/84792ec8f1e6b53f7e6c4a00f4eddecfdeb7ce4c/root/static/js/canto-modules.js#L3585-L3588

I guess there will need to be extra logic to detect what mode the genotype page is in before the `window.location.href` is set &ndash; we possibly _don't_ need to directly check whether we're supposed to be in Pathogen&ndash;Host mode, since we can infer that when the URL contains  `host_genotype_manage` or `pathogen_genotype_manage`. Alternatively, maybe we could just copy more of the current URL (including the genotype manage directory) and simply append the fragment (e.g. `/select/` or `/edit/`)?

**Comment by jseager7** [comment]
After further testing, it turns out this solution doesn't work well when the genotype manage segment isn't contained in the URL. The function ends up generating URLs like this:

`http://localhost:5000/curs/1bfbc66bb9a294fc#/select/14`

Which has the effect of moving the user back to the summary page.

This means that the solution doesn't work when trying to navigate _back_ to the genotype management page from some other URL. We can't hard-code `genotype_manage` into the URL as before, so we need some way to record and store which genotype management page the user navigated from. Perhaps the AngularJS `$location` service could help here ([see the docs](https://code.angularjs.org/1.5.11/docs/api/ng/service/$location)).

**Comment by jseager7** [comment]
Note that there's also the following references to `genotype_manage` that I'm not sure how to handle, mostly because they probably have no reference to a `window.location.href`.

`genotypeListRowLinksCtrl`

https://github.com/pombase/canto/blob/84792ec8f1e6b53f7e6c4a00f4eddecfdeb7ce4c/root/static/js/canto-modules.js#L4461-L4464

`metaGenotypeManage`

https://github.com/pombase/canto/blob/84792ec8f1e6b53f7e6c4a00f4eddecfdeb7ce4c/root/static/js/canto-modules.js#L6625

**Comment by kimrutherford** [comment]
I think this issue might be related:  #1614 

> so we need some way to record and store which genotype management page the user navigated from

Yep, I think so.   Perhaps we can have a Skype chat about this when you're back at work.

**Comment by jseager7** [comment]
# Sources of the problem

I've looked at this in more detail now, and I've found references to `genotype_management` in all the following places (but there could be more that I've missed): 

## Genotype management

I think all references to `genotype_management` on the Host Genotype Management and Pathogen Genotype Management pages can be fixed by just inspecting the current URL to see if the user is in host or pathogen mode, then setting the new URL accordingly.

The big problems are on other views, specifically:

## Genotype details view

There is a link to genotype management on the details view for every genotype: these have URLs of the form `curs/{session_id}/feature/genotype/view/{genotype_id}`, and they can be accessed either by:

- clicking on a gene name (navigating to any URL of the form `curs/{session_id}/feature/gene/view/{gene_id}`), then clicking on 'Details...' next to each row in the table of genotypes, or

- clicking on 'View annotations...' for any genotype on the genotype management page.

The problem here is that we have no reference to what the previous genotype management view was, and in some cases there _isn't_ a previous genotype management view.

(Note that the navigation button on the genotype details always sends the user back to the genotype management page, even if the user navigated to the page from the gene details view. Ideally the button should always send the user back where they came from.)

## Meta-genotype view

There's two problems here:

* We have no reference to the previous genotype management view, and

* the meta-genotype management page can be navigated to from the summary page, as well as either genotype management view, so we need to be able to change the button to link back to the correct page.

Unlike the genotype management page, some of this routing (e.g. summary page to meta-genotype page) is presumably performed by Catalyst, which would complicate things further.

# Potential solutions

Here's some potential solutions I can think of, but I haven't decided on any of them yet:

- Store the previous location in a global AngularJS service: I think this is precluded by the fact we're not using a single page application, so the state will be lost whenever Catalyst changes the route.

- Encode part of the previous URL in the new URL: this follows the existing system of encoding state about selected genotypes into the URL, and it has the advantage of being resistant to page reloads. However Catalyst will probably still be able to interfere with this when it changes the URL itself, and it could get complicated when genotype management views are also modifying the URL (e.g. appending `/select/` and `/edit/` to it).

  - (In terms of how this might look in practice, we could add a parameter like `?from=host_genotype_management`, maybe abbreviated as `?from=hgm`.)

- Store the previous location in a session cookie: this has the advantage of users being directed back to the correct genotype management mode, even if they reopen the page in a new browser session &ndash; although that's presuming the session cookie isn't cleared on exit (If the cookie is not set, perhaps the backwards navigation button should always redirect the user to the summary page).

It's possible that any solution will have to be implemented both in Catalyst (Mason) and AngularJS, since neither has full responsbility for routing and URL re-writing.

**Comment by jseager7** [comment]
To summarise, I did a search for the pattern `\bgenotype_manage\b`, and these are all of the template files that contain matches:

# Templates

## Mason templates

### breadcrumbs
https://github.com/pombase/canto/blob/509d8141088b370b9dca41a7a448b2ca23f411a9/root/curs/breadcrumbs.mhtml#L38-L45
The breadcrumbs seem to have no reference to `host_genotype_management` or `pathogen_genotype_management`, so maybe this needs to be updated to handle the new pages?

### front gene section
 https://github.com/pombase/canto/blob/509d8141088b370b9dca41a7a448b2ca23f411a9/root/curs/front_gene_section.mhtml#L134	
This page seems to just be setting variables, and it has ones for `host_genotype_management` and `pathogen_genotype_management` already.

### gene page
https://github.com/pombase/canto/blob/509d8141088b370b9dca41a7a448b2ca23f411a9/root/curs/gene_page.mhtml#L67-L72
I'm not entirely sure if this page is being used anymore, but it does contain a direct link to `genotype_manage`, so if the page isn't redundant, that will probably need to be fixed.

### genotype page
https://github.com/pombase/canto/blob/509d8141088b370b9dca41a7a448b2ca23f411a9/root/curs/genotype_page.mhtml#L100-L102
Again, I'm not sure if this page is still used, but it also contains a direct link to `genotype_manage`.

## AngularJS templates

### genotype list row links
https://github.com/pombase/canto/blob/509d8141088b370b9dca41a7a448b2ca23f411a9/root/static/ng_templates/genotype_list_row_links.html#L23-L25
This seems like a similar problem to the `genotype_page` above.

The next comment will cover the references in the JavaScript source files.

**Comment by jseager7** [comment]
# JavaScript

There are also references to `genotype_manage` at multiple points in the `canto_modules` file:

### GenotypeGeneListCtrl
https://github.com/pombase/canto/blob/509d8141088b370b9dca41a7a448b2ca23f411a9/root/static/js/canto-modules.js#L3880-L3883

https://github.com/pombase/canto/blob/509d8141088b370b9dca41a7a448b2ca23f411a9/root/static/js/canto-modules.js#L3925-L3928

Both of these are identical, and they need to be changed to respect the genotype management mode, or they will force the genotype management page out of pathogen&ndash;host mode. I think inspecting the current URL may work in this case, since this controller is used on the genotype management page (and possibly nowhere else).

### genotypeManageCtrl
https://github.com/pombase/canto/blob/509d8141088b370b9dca41a7a448b2ca23f411a9/root/static/js/canto-modules.js#L3995

This only sets the template URL, so it shouldn't need any changes.

### genotypeListRowLinksCtrl
https://github.com/pombase/canto/blob/509d8141088b370b9dca41a7a448b2ca23f411a9/root/static/js/canto-modules.js#L4391-L4394

https://github.com/pombase/canto/blob/509d8141088b370b9dca41a7a448b2ca23f411a9/root/static/js/canto-modules.js#L4417-L4420

https://github.com/pombase/canto/blob/509d8141088b370b9dca41a7a448b2ca23f411a9/root/static/js/canto-modules.js#L4457-L4461

### genotypeListViewCtrl
https://github.com/pombase/canto/blob/509d8141088b370b9dca41a7a448b2ca23f411a9/root/static/js/canto-modules.js#L4604-L4608

All of these examples need to be changed, but I'm not sure if they're exclusively used on the genotype management page. If so, then we can repeat the fix of inspecting the current URL, but that means the directives / controllers won't be reusable on different pages.

### metagenotypeManage
https://github.com/pombase/canto/blob/509d8141088b370b9dca41a7a448b2ca23f411a9/root/static/js/canto-modules.js#L6647

As previously noted, this link shouldn't target `genotype_manage` since it's not used anymore; it should link back to the correct one of three possible routes to the metagenotype management page: `host_genotype_manage`, `pathogen_genotype_manage`, or the summary page.

I think one easy-ish fix could be to amend the links on the source pages so that they insert a reference to their own URL in the URL for the metagenotype page, for example:

**Comment by jseager7** [comment]
Here's some other references to `genotype_manage` that I missed:

### ontologyWorkflowCtrl

https://github.com/pombase/canto/blob/53b9c6d6a0b8fd0aacadb7845bbec57a8a748a59/root/static/js/canto-modules.js#L2566-L2573

**NEEDS FIXING:** I think this might affect the back button when starting phenotype annotations on genotypes. I'm not sure we have any reference to the genotype in question in this controller though.

### genotypeViewCtrl

https://github.com/pombase/canto/blob/53b9c6d6a0b8fd0aacadb7845bbec57a8a748a59/root/static/js/canto-modules.js#L3486-L3489

https://github.com/pombase/canto/blob/53b9c6d6a0b8fd0aacadb7845bbec57a8a748a59/root/static/js/canto-modules.js#L3491-L3494

**NEEDS FIXING:** I'm assuming this controller is used when viewing annotations for a genotype. Unfortunately, there doesn't seem to be a reference in scope to the genotype being viewed.

**Comment by jseager7** [comment]
Closing now, since all of the urgent problems are fixed. There's a follow-up issue for the metagenotype page at #1647. Issue #1477 is also related to this bug, and still needs fixing.
