### ISSUE TITLE
Make the meta-genotype list style more consistent

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1607]
@kimrutherford requested that the list of meta-genotypes on the meta-genotype management page should look more consistent with how we display other genotypes (i.e. in a table).

In short, we should think about redesigning this:
![metagenotype_list](https://user-images.githubusercontent.com/37659591/44848247-f05ebd00-ac4d-11e8-9cdc-e2c11119b655.PNG)

&hellip;To look similar to this:
![genotype_list](https://user-images.githubusercontent.com/37659591/44848251-f3f24400-ac4d-11e8-9459-86a381d057ab.PNG)

&hellip;Or maybe similar to this:
![dfp_summary](https://user-images.githubusercontent.com/37659591/44848258-f785cb00-ac4d-11e8-9cc8-71caec7ff738.PNG)

**Comment by jseager7** [comment]
Here's some mock-ups of how the metagenotype table could look:

## 1. Metagenotype and annotations combined

![one_table](https://user-images.githubusercontent.com/37659591/44849187-3f5a2180-ac51-11e8-8e72-559828be9d2d.PNG)

## 2. Metagenotype and annotations separate

![two_tables](https://user-images.githubusercontent.com/37659591/44849200-4da83d80-ac51-11e8-8bb7-06c4098e6498.PNG)

## 3. No column for genes

![one_table_no_genes](https://user-images.githubusercontent.com/37659591/44849308-99f37d80-ac51-11e8-9780-47faca8b6b27.PNG)

- - -
Alternatively, if we don't want to show the annotations on the page at all (only the metagenotypes), then we can try the following design:

## 4. One row per metagenotype

![compact_columnar](https://user-images.githubusercontent.com/37659591/44849820-3cf8c700-ac53-11e8-9570-b7504cb9d59a.PNG)

This design could use a pop-up menu (similar to the one on the genotype management page) to handle actions like viewing annotations and editing and deleting metagenotypes.

**Comment by ValWood** [comment]
...becasue at least somewhere the  metagenotype will need to be a "single line"

for example here:

![pull down2](https://user-images.githubusercontent.com/7359272/44855398-d7143b80-ac62-11e8-8ab6-63c032b09a51.jpg)

in the pull down for copy and edit  the genotype will be displayed as a single long line.
The idea is that once you created the genotype, it is quite easy to differentiate between than in the one-line version.

**Comment by jseager7** [comment]
I think given how much information there would be in a metagenotype when it is compressed to one line, we might need to come up with some alternative form of picker, because the drop-down could get extremely wide otherwise (particularly when the strain name is very long, as with _Gibberella zeae_).

One thing we were considering (@barnabynorman, @kimrutherford, and myself) was to re-use the genotype picker from the metagenotype page, so that in the case where the user wanted to change one of the constituent genotypes of the metagenotype, they'd just repeat the process from when they originally created the metagenotype.

This process could also handle the case when the user wants to apply an annotation to a different metagenotype &ndash; only they'd have to select two genotypes instead of one. We haven't actually made a decision though.

**Comment by ValWood** [comment]
- I don't think the strains will be so long (this isn't the correct strian label it is 3
- because these pathogen host experiments  do not  get as complex (usually) as some of the model species ones, I think we will be OK for  a while.
We have some   multi allele genotypes which are longer than  any likely meta genotypes, at least in the short-medium term

**Comment by ValWood** [comment]
see for example

https://user-images.githubusercontent.com/7359272/42227817-41ea2520-7eda-11e8-91eb-5263f5e2b0fe.jpg

**Comment by ValWood** [comment]
Long alleles are more of a visual problem in the  annotation tables, but I never encountered a problem in the  selector.

**Comment by ValWood** [comment]
- one space saving tactic would be to use species short names once the species is confirmed.

- these may need to be configured, incase  they cannot be disambiguated

but usually  the  first part of the binominal is long and the second part shorter. This will save quite a bit of space and with the reduced complexity of the genotypes I think it could work OK.

**Comment by barnabynorman** [comment]
Have made changes as per discussion and above:

https://github.com/pombase/canto/commit/9777b4ecf2197ca79e4b8d2a6c8408506dc5998a
