### ISSUE TITLE
Update schema for strains

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1608]
Please add the following columns to the strains table:
- a numerical ID that can consistently be used as a primary key between sessions
- a dependencies flag used to track strains that have dependencies on them (ie used in an allele etc), to allow the application to prevent removal of strains from a curation session without first editing or removing the dependency.

**Comment by kimrutherford** [comment]
> a numerical ID that can consistently be used as a primary key between sessions

I've added a "strain_id" to the strain table in main Track database.  You'll need to upgrade the database schema version with:

    ./etc/upgrade_db.pl 23

in you canto directory.

I'm now working on storing that strain_id in the curation session and returning from the strains web service.

**Comment by kimrutherford** [comment]
@barnabynorman have been able to try this schema upgrade? Does it work for you?

**Comment by barnabynorman** [comment]
@kimrutherford yes, I did last week and yes, it works thank you!
