### ISSUE TITLE
Update the metagenotype list

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1609]
@kimrutherford can Curs.list('metagenotype') include the count of annotations please, otherwise the application is having to download all annotations in a separate API call just to count them?

**Comment by kimrutherford** [comment]
I've added an "annotation_count" field for each metagenotype that gets returned:

```
[
  {
    "host_genotype": {
       ...
    },
    "pathogen_genotype": {
       ...
    },
    "metagenotype_id": 14,
    "annotation_count": 2
  }
]

```
