### ISSUE TITLE
Add strain entry into the interface

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1610]
Add functionality to be able to add strains for each organism

**Comment by barnabynorman** [comment]
Added a work in progress solution.

To test:
Add a gene with id: P11383

In the summary page add strains to the triticum organism by using the dropdown picker

**Comment by barnabynorman** [comment]
You also need to add Triticum

**Comment by CuzickA** [comment]
Update
I have cleared the browser cache whilst on the above image page and now see the screen below
![image](https://user-images.githubusercontent.com/11753634/45217183-1235f080-b29b-11e8-9bbd-453ad548ad63.png)

Something may be need to be done about this or perhaps this is happening because it is a test?

**Comment by barnabynorman** [comment]
@CuzickA Thank you for testing. 
The problem with the missing dropdown is because your machine has remembered a previous time where you viewed this page for that pubmed id (before I reset it) and so it won't be a problem when the system goes into production as these pages (once complete) would not be changing, and in the event that they do change we will manage that change to avoid the caching issue that you documented above.

**Comment by CuzickA** [comment]
Thanks for explaining ;-)

**Comment by kimrutherford** [comment]
I've added a strain table for each session.  You'll need to upgrade schema versions with:

    ./etc/upgrade_db.pl 24

I'm working on the API for adding strains to the session and querying the strains.

**Comment by kimrutherford** [comment]
Hi @barnabynorman 

I've added two new services.  One for adding strains to the session and one for removing them.  It only works for the pre-configured strains for now (ie. those loaded with `canto_load.pl --strain ..`).  So you can't add a new strain.  I'll do that next.

This should work now:

`Curs.add('strain_by_id', 1234).then(...)`
and
`Curs.delete('strain_by_id', 1234).then(...)`

Could you give it a try and let me know if it works for you?

The delete service will fail if there are any genotypes for that strain.

The strain IDs are what is returned by calling `CantoService.lookup('strains', [taxonId]).then(...)`

----------------------

And I think this is old news but the list of current strains in the session can be retrieved with:
  `Curs.list('strain').then(...)`

**Comment by barnabynorman** [comment]
Thanks @kimrutherford worked a treat apart from the data part was expecting an array so:

`Curs.add('strain_by_id', [1234]).then(...)`

Have committed and pushed

**Comment by kimrutherford** [comment]
> worked a treat apart from the data part was expecting an array

Ah, sorry, I forgot that.

I'm considering adding this sort of interface next:

```
Curs.add('strain_by_name', ['some new strain']).then(...)

Curs.delete('strain_by_name', ['some new strain']).then(...)
```

Does that make sense?

Both of these calls could check for known strains and handle new strains.

> Have committed and pushed

Thanks.  I'll give it a go.

**Comment by kimrutherford** [comment]
> I'm considering adding this sort of interface next:
> `Curs.add('strain_by_name', ['some new strain']).then(...)`

I realised that the call should include the taxon ID, so I've implemented it as:

```
Curs.add('strain_by_name', [4321, 'some strain name']).then(...)
```

where 'some strain name' can be the name of an existing strain or the name of a new strain in this session.

I've checked in the change.

**Comment by kimrutherford** [comment]
> There is one case using the picker where I could not find any use for it:

Sorry, I don't follow.  What can't you find a use for?

That controller is used by `root/curs/gene_page.mhtml`

**Comment by kimrutherford** [comment]
> Next steps I need a way to use the chosen strain in the genotype creation @kimrutherford have
> you written the way to store these yet?

Not yet.  I'll do that next.

**Comment by barnabynorman** [comment]
> Sorry, I don't follow. What can't you find a use for?

> That controller is used by root/curs/gene_page.mhtml

Ahh with brain in gear I see.... 
So how do I get to that page in the interface? Its using makeAlleleEditInstance popup but the page generates a 404???

**Comment by kimrutherford** [comment]
> So how do I get to that page in the interface?

It's the page you get if you click on a gene name.  Like: http://canto.phi-base.org/curs/15bef85cce4e62ab/feature/gene/view/1

**Comment by barnabynorman** [comment]
Data is now passed into the method storeGenotypeHelper in the last parameter: alleles so every instance of alleles contains a strainData parameter (with one exception):

```javascript
strainData = {
  taxonId: taxon_id_provided,
  strainName: 'name of strain used'
}
```

At present the page: curs/32ae05516ce9cdb2/pathogen_genotype_manage# does not know these details for existing deletions etc so when it batch updates them, only the new alleles have the data.

@kimrutherford over to you to implement the save part in the back end.

**Comment by barnabynorman** [comment]
@kimrutherford I agree it would make much more sense to pass the taxon and strain as separate fields, however when I came to working with the page that looks like this:

![image](https://user-images.githubusercontent.com/1710907/47661840-bea49c80-db91-11e8-97ef-fc2fac56f8e3.png)

```
curs/d7cb4c7b59850b63/pathogen_genotype_manage#/select/6
```

I found that the system is batching the alleles and passing all at once in an array - without considerable refactoring I thought  a quick hack would get the job done.

In an ideal situation I would pass the strains to their own api

Perhaps I could change that page to send every time an allele is created like in all other places - what do you think?

**Comment by kimrutherford** [comment]
On that page the "Add allele ..." button really is adding an allele rather than creating a single allele genotype.  So it doesn't make sense to select a strain in the allele dialog here.  The genotype has a strain not the alleles.  If the user can select a strain when adding an allele they could select a different strain for each allele which wouldn't make sense within one genotype.

On this page we should probably have a Strain selector above or below the Background input field.

**Comment by kimrutherford** [comment]
Hi @barnabynorman.

I've changed the server side Perl code so that the taxon ID and strain name are handled when genotypes and edited or created.  I've pushed that change on the metagenotype-dev branch.

To test the code I changed storeGenotypeHelper() to pass those parameters and changed all the places I could see where storeGenotype() was called so that the extra args were added.  I also changed the way the taxon ID and strain are passed in and out of the allele edit dialog to separate the allele and the taxon/strain.  It all seems to work in the interface although the strains aren't visible in the table.  I've made a pull request with the JS changes: https://github.com/pombase/canto/pull/1653
If the changes are OK by you could you merge it?  Let me know if you see any problems.

**Comment by kimrutherford** [comment]
> It all seems to work in the interface although the strains aren't visible in the table.

I've just changed the genotype list service to return the strain name of each genotype (if set).

So Curs.list("genotype") will return something like `strain_name: "A549 cells"`.

I've added an issue about displaying the strains in the genotype tables: #1654

**Comment by barnabynorman** [comment]
@kimrutherford having implemented the displaying of used strains on the genotype page I can see that 'deletion' has saved the strain but when I tried several others using other genotype I am not seeing the strain. Was this intentional or did that bit not work?

**Comment by kimrutherford** [comment]
Sorry, I should have tested that better.  I think I've fixed things.

**Comment by barnabynorman** [comment]
@kimrutherford working now
