### ISSUE TITLE
Remove the strain information from genes / organisms loaded

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1611]
An example is:

<Brevibacillus brevis (strain 47 / JCM 6285 / NBRC 100599)>

Can the information in brackets be removed from the system in preparation for adding strain information selected by the curator?

**Comment by kimrutherford** [comment]
It's a tricky problem.  I suggested a fix here but I think it might be fragile to reply on yet another external service: https://github.com/pombase/canto/issues/1467#issuecomment-391522495

**Comment by kimrutherford** [comment]
> Perhaps, since the taxon name is always a binomial

There are some odd case like "Citrus x paradisi":
https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=37656

**Comment by barnabynorman** [comment]
@kimrutherford I noticed when looking at the pathogen_strains_sample.csv file that there is a column for common name - perhaps the solution is to identity the correct taxon id and populate from this file?

**Comment by barnabynorman** [comment]
Further to our conversation on Monday (14 Oct 18) I have investigated what I can get back from the [uniprot](https://www.uniprot.org) API - data comes back in RDF format, which I have written some php scripts to read it, that give me child class ids and strain names.

This is how I see the simplest solution working:

1 - I take the lists that we have of host and pathogen organisms with taxon ids
2 - Feed them into my script giving two lists: alias taxon ids and strain names per organism
3 - Add strains into canto as normal
4 - We need a way to upload and store taxon alias id lists, perhaps by parent taxon, list of children and children of children in a flat list: 4530 4536 39946 39947 1050722 1080340 etc (where 4530 is the parent taxon id and all others are children) - could get long - I suppose the better way might be one line for each child??

When the curator adds their gene, for example "Q7XL73", which refers to rice, canto does the same lookup as before giving gene details + taxon id - 39947 (Oryza sativa subsp. japonica)

The next step is canto looks at the alias taxon list for 39947, which gives the taxon id for rice that is already added (4530) and the system will now see it as a host (not pathogen).

@kimrutherford does that make sense technically?
@martin2urban does that make sense from a biological point?

**Comment by kimrutherford** [comment]
Hi Barnaby.

Would you be able to get what you need from the TSV output?  If so, it's likely to be less fragile than parsing RDF:
https://github.com/pombase/canto/issues/1635

**Comment by barnabynorman** [comment]
I know what you mean @kimrutherford - had done the hard bit by then so it squirts out nice lists with not trouble!

Here are the aliases for our rice example for you to play with:

```
4530 => 4536, 39946, 39947, 1050722, 1080340, 1736659, 1736656, 1736657, 1736658
```

When you are ready I will run the batch against all our organisms and make the final import file.

**Comment by kimrutherford** [comment]
We've talked about this now and we plan to add a map in the configuration to hold this information.  Then the UniProt ID lookup code can use the map to fix the organism before storing in the database.

The configuration in `canto_deploy.yaml` will look a bit like this:

```json
 species_strain_map:
   4565:
     reference_strain: 231718
     other_strains:
       - 231718
       - 425487
   168172:
     reference_strain: 1262395
     other_strains:
       - 1238467
       - 1262396
```

Implemented in 3ffbacb628f8

See also #1659

**Comment by kimrutherford** [comment]
> Then the UniProt ID lookup code can use the map to fix the organism before storing in the database.

That's implemented now.  If the strain and species is configured in `species_strain_map` then the UniProt ID lookup will replace the strain for the gene with the species details.

This should solve #1467 too.

@barnabynorman could you try this out next week and close the issue if you works for you?  Thanks.

**Comment by barnabynorman** [comment]
@kimrutherford it appears to be working well, although the configuration data was far more than the content of the rest of the config file!
