### ISSUE TITLE
Create an API for the strains table

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1613]
This is how I see the strains being recorded in the back-end and returned back to the javascript interface and when saving as part of creating alleles

**API**
CantoService.lookup('strains', [taxonId]) needs to return:

```
{
    id: 3,
    name: 'Bobwhite',
    dependencies: false
}

```
Where:
id - is an id assigned to the session and will always return that strain
name - is the strain name that has been added to the imported list
dependencies - is a flag to indicate if the strain has been used in the system and therefor would not be able to delete

Service method to add a strain to the list of strains that are available to the session:

```
{
    id: 3,
    taxonid: 6365
}
```

Service method to remove a strain from the list of strains that are available to the session:

```
{
    id: 3,
    taxonid: 6365
}

```
Note that the above will fail if the strain has dependencies

Service method to add a new (typed in) strain to the list of strains that are available to the session:

```
{
    name: 'goldfish',
    taxonid: 6365
}
```

Note that this method will add the new strain to a separate list (or flag on the main strain list), that can be returned via the admin interface for inclusion in the configuration if required. The strain will be returned as part of the CantoService.lookup('strains', [taxonId]) method with the other strains when requested

**Allele creation**
In the genotype section I would expect the available strains to be returned with the organisms. As deletions etc are made to organisms and strains are selected, this information will be passed back and added to the tables used to record the allele being created. In addition the save process would set the dependencies flag on the particular strain and unset it again if the allele is deleted.

**Comment by kimrutherford** [comment]
I've changed `CantoService.lookup('strains', [taxonId])` so that it returns results like:

```json
[
  { strain_id => 101, strain_name => 'strain 1' },
  { strain_id => 102, strain_name => 'strain 2' }
]
```

I haven't added the "dependencies" flag because this service doesn't know about sessions.  It just returns all strains for the given taxon ID that are loaded into the main Canto database.

> The strain will be returned as part of the CantoService.lookup('strains', [taxonId]) method with the
> other strains when requested

We should have a chat about that.  I think any new strains added in a session should only be added to the main (global) list when a session is approved by an admin.  The action of approving the session could add the new strains to the global list.
