### ISSUE TITLE
Should Canto use the snapshot version of go-plus.owl?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1615]
We're currently using:
  http://purl.obolibrary.org/obo/go/extensions/go-plus.owl

But perhaps we should be using:
  http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.owl

**Comment by mah11** [comment]
Yes. Use the snapshot version, because the non-snapshot URLs are about to change to monthly updates.

**Comment by ValWood** [comment]
Just for the record, I'm pasting the announcement ;)

As documented on the GO download page (http://www.geneontology.org/page/download-ontology), the URLs that should be used for downloading obo, owl and json versions of the GO are of the form:

http://purl.obolibrary.org/obo/go/go.obo

Currently this resolves to the "snapshot" version of the ontology that is constructed daily.

Starting on October 1, these URLs will resolve to the monthly release of the GO, and will be in sync with the annotation releases.

For most consumers of the GO, no changes are required. However, if you have a use case for retrieving the snapshot version you will need to change your URLs. The standard use case is a MOD curation tool or a tool like Protein2GO that needs to be able to retrieve terms shortly after a curator requests them.

The snapshot URLs have /snapshot/ in them. For example:

http://purl.obolibrary.org/obo/go/snapshot/go.obo
http://purl.obolibrary.org/obo/go/snapshot/go.owl
http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.owl

You can go ahead and make the switch to snapshot PURLs right now. Currently they resolve to the same content as the public release ones.

Note that Protein2GO already uses the snapshot PURLs

Follow-up on this ticket:
https://github.com/geneontology/go-site/issues/783

**Comment by kimrutherford** [comment]
OK, that's changed too now.  I'll check the Canto ontology update tonight.

**Comment by kimrutherford** [comment]
The load worked.  Let me know if new terms aren't appearing quickly.
