### ISSUE TITLE
Convert the "confirm genes" page to javascript

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1617]
Take the current formatted output the "confirm genes" page and recreate it using javascript to allow extending the interface to fully support strains etc

The existing perl code will output all required data including strain information into a variable, in json format. This will then populate a directive and hand over to angular js, which will use logic to render the form.

The json sould be something like this:

```json {
	"organisms": [{
		"name": "Brevibacillus brevis",
		"common_name": "",
		"taxonid": "55080",
		"type": "pathogen",
		"genes": [{
			"systematic_identifier": "C0ZDU6",
			"name": "HOA_BREBN",
			"synonyms": "BBR47_29780",
			"product": "4-hydroxy-2-oxovalerate aldolase",
			"added": true
		}],
		"selected_strains": [],
		"available_strains": [{
			"strain_id": 234,
			"strain_name": "x"
		}, {
			"strain_id": 235,
			"strain_name": "y"
		}, {
			"strain_id": 236,
			"strain_name": "z"
		}]
	}, {
		"name": "Influenza A virus",
		"taxonid": "384505",
		"common_name": "",
		"type": "pathogen",
		"genes": [{
			"systematic_identifier": "D3TDN8",
			"name": "NA",
			"synonyms": "",
			"product": "Neuraminidase",
			"added": true
		}],
		"selected_strains": [],
		"available_strains": [{
			"strain_id": 14,
			"strain_name": "a"
		}, {
			"strain_id": 15,
			"strain_name": "b"
		}, {
			"strain_id": 16,
			"strain_name": "c"
		}]
	}, {
		"name": "Triticum aestivum",
		"taxonid": "4565",
		"common_name": "Wheat",
		"type": "host",
		"genes": [{
			"systematic_identifier": "P01083",
			"name": "IMA1",
			"synonyms": "",
			"product": "Alpha-amylase inhibitor 0.28",

			"added": false
		}, {
			"systematic_identifier": "P11383",
			"name": "rbcL",
			"synonyms": "",
			"product": "Ribulose bisphosphate carboxylase large chain",
			"added": false
		}],
		"selected_strains": [{
			"strain_id": 10,
			"strain_name": "Amery"
		}, {
			"strain_id": 13,
			"strain_name": "Bobwhite"
		}, {
			"strain_name": "Bess",
			"strain_id": 11
		}],
		"available_strains": [{
			"strain_id": 10,
			"strain_name": "Amery"
		}, {
			"strain_id": 13,
			"strain_name": "Bobwhite"
		}, {
			"strain_name": "Bess",
			"strain_id": 11
		}]
	}, {
		"name": "Arabidopsis thaliana",
		"taxonid": "3702",
		"common_name": "thale cress",
		"type": "host",
		"genes": [],
		"selected_strains": [],
		"added": false
	}],
}
```

In the directive I can establish:
- the pathogen organisms, 
- host organisms
- host organisms with no genes
- which strains are available
- which strains have been used

I can also generate a toaster message based on which genes / organisms have been added from the "added" flag.

@kimrutherford have I missed anything here - would that still work in single host mode?

Also if you think it would be simpler to do the logic in the back-end and provide lists for:
pathogen genes, host genes and host without genes + the message + strain list, that would be fine.

Instead of checkboxes it might be better to replace with delete buttons with a confirm popup as the effect will be to immediately post using ajax and remove the row. The ajax will ignore the redirection action from the existing page logic, but this could be improved using a dedicated endpoint for the deletion.

In the scenario that all genes / organisms are removed, the page will display a message to tell the curator that there are none and inviting them to confirm continuation, which will trigger a page re-load that has the side effect of displaying the "Add genes" page.

The strain selection will continue to use the Strain service but the available strains list will be populated from the data passed into the directive rather than another api call as currently happens. It is the only place in the system where the available lists are shown as the curator must select the strains to be used here and the filtered list (generated here) is used in the rest of the application.

When the curator is ready they will click the continue button, which will trigger a page re-load, which has a different side effect of displaying the gene list summary page.

**Comment by kimrutherford** [comment]
> I can also generate a toaster message based on which genes / organisms have been added from
> the "added" flag.

We also need to hightlight the name or synonyms that matched.  As an example, I entered "pol3" on the gene upload page and it adds SPBC336.04/cdc6 but hightlights the "pol3" synonym.   The list of identifiers to highlight can be passed in a separate variable.

![gene-confirm-highlight-1](https://user-images.githubusercontent.com/90474/45666660-4eeecb00-bb6a-11e8-9343-d5408d040bce.png)

---------------

> host without genes + the message + strain list

What is "the message" in this context?

Everything else sounds good. I'm working on adding the organism, genes and strains as Javascript.

**Comment by barnabynorman** [comment]
> "host without genes + the message + strain list"

> What is "the message" in this context?

What I meant was whatever the existing message is ie perl is displaying at the top of the screen currently for example: "Added 0 genes, added 1 host organism"

**Comment by kimrutherford** [comment]
>What I meant was whatever the existing message is ie perl is displaying at the top of the screen currently for
> example: "Added 0 genes, added 1 host organism"

Ah, thanks.  Now I think about it probably that code can stay the same and the message can continue to be inserted with Perl.  At least initially.

So we can also ignore what I said here:

> The added field is missing from the genes. Currently we just display "Added X genes". The X is just the
> length of the highlightTerms array so perhaps the added flag isn't necessary?

The `highlightTerms` variable will still be needed for highlighting in the table.

**Comment by barnabynorman** [comment]
@kimrutherford am getting a 500 error when attempting to remove genes / organisms where strains have been added - thinking this is database integrity.  

* should I remove them on front-side?
* block deletion unless they remove?
* will you update the strain table first before the delete is done?

**Comment by kimrutherford** [comment]
> am getting a 500 error when attempting to remove genes / organisms where strains have been
> added

Do you have an example where you get an error when removing a gene?  That shouldn't happen.  Maybe the gene has alleles that are part of a genotype?

I'll change the server code to quietly handle removing strains when you remove an organism.  The exception is where there is a genotype that refers to the strain because I don't think we should delete the genotype if we delete the strain.

**Comment by barnabynorman** [comment]
> Do you have an example where you get an error when removing a gene? That shouldn't happen. Maybe the gene has alleles that are part of a genotype?

There is a http 500 error returned in the console for this url:
```
http://localhost:5000/curs/d7cb4c7b59850b63/edit_genes?host-org-select=7998&submit=Remove%20selected
```

It happens on a gene / organism that has a strain added

To recreate:
1. Add a new gene or organism
2. Pick a strain (or unknown)
3. Attempt delete

Its odd because on trying again some will delete and some give the error

I tested with these genes and hosts:

Q40294 C0ZDU6 D3TDN8 P09874 Q8JSD9 P03427 P03452 P11383 P01083 A0A0J6BXG6 Q1XH04 A8K660

Mango
Homo
Triticum
Zebrafish

**Comment by barnabynorman** [comment]
> Maybe the gene has alleles that are part of a genotype?

To be clear any that are part of a genotype can't be removed anyway as I disabled the remove button for these!

**Comment by kimrutherford** [comment]
> To recreate:

Thanks for that.  I think I've fixed the gene deletion.  Could pull my changes and test things?

@barnabynorman

**Comment by barnabynorman** [comment]
@kimrutherford spot on, thanks!
