### ISSUE TITLE
Prevent creating duplicate alleles when editing genotype strain

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1620]
This is a bit speculative, but if we're going to allow users to edit the strain for a particular genotype, we need to make sure that users aren't allowed to change the strain to something that already has an identical allele on it.

For example, if a user was curating mutations on _A. thaliana_, and created a _PYM&Delta;_ allele on strain _cv. Corsacalla-1_ and another _PYM&Delta;_ allele on strain _cv. Dijon_, there would (presumably) be nothing stopping them from switching the  _PYM&Delta;_ on  _cv. Dijon_ to  _cv. Corsacalla-1_, resulting in two _PYM&Delta;_ alleles on _cv. Corsacalla-1_, which is invalid.

Until #1619 is fixed, it might be the case that this bug can't occur yet anyway, because I think Canto will ignore the strain and just check for duplicate alleles on the organism, but I expect we'll have to make this check more sophisticated in order to support strains.

**Comment by jseager7** [comment]
I think this is possibly a duplicate of #1130, but I'm not sure. There might be cases where editing the strain causes one allele to be invalid even when it isn't an exact duplicate of another allele.

**Comment by kimrutherford** [comment]
> I think this is possibly a duplicate of #1130, but I'm not sure.

I think it is.  I've added a not about strains on #1130 so I'll close this.
