### ISSUE TITLE
Reformatting the gene summary page

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1621]
Looking at changing the way that the genes and organisms are laid out for the page from individual gene tables to having organism tables listing genes, it seems are more difficult task than first imagined. Coupled with the need to display pathogen organisms first it think it would be far quicker to render it using an angular directive.

I attempted to get the data from the page but can't find an easy way to convert hashes inside hashes inside hashes into a javascript object that can be injected in.

The alternative is to use the Curs.list('organism') service, which returns what I need, and I can work with it, however given that the page already loads with the data I need, what do I need to get the perl @gene_hashes_by_organism into a js var?

**Comment by barnabynorman** [comment]
@kimrutherford thank you. Everything is there, but the format is not good.

Its tricky getting it into the directive then I had to do some regex and find/replace to get it to validate into a js object because its missing the quotes round the parameters + undefined in the string.

Also its got hash variables inside, which means I would need to iterate it twice to get what I need.

For now I have switched it to read from the API but can switch it back again when if you can get nice json - its a bit slow, so if we can get clean json that would be best.

**Comment by kimrutherford** [comment]
> Also its got hash variables inside

Do you mean objects?

I thought that an array of organism details would be easiest to iterate over.  That's what we do on the "confirm genes" page.  It makes iteration easy doesn't it?  Like this?:

```html
<div ng-repeat="organismDetails in geneHashesByOrganism">
  {{organismDetails.scientific_name}}
  <div ng-repeat="geneDetails in organismDetails.gene_hashes">
     {{geneDetails.displayName}}
     (etc.)
  </div>
</div>
```

Could give an example of how you'd like the data structure to look like?

I forgot to split the organisms into pathogen and host groups.  I'll do that today.  There's now a lot of code that is similar on the gene confirm page (from #1617) and this page.  And the object fields aren't consistent ("genes" versus "gene_hashes").  I'll try to pull all that into one place.

**Comment by barnabynorman** [comment]
@kimrutherford perfect! Thanks
