### ISSUE TITLE
genotype_page only links to genotype_manage

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1625]
(Sub-issue of #1606)

@kimrutherford The genotype detail page currently has links to the old `genotype_manage` page, and these need to be fixed on the Perl side. 

https://github.com/pombase/canto/blob/509d8141088b370b9dca41a7a448b2ca23f411a9/root/curs/genotype_page.mhtml#L100-L102

**Comment by kimrutherford** [comment]
I've fixed this but discovered that the link doesn't work anyway.  I've made a separate issue about that: #1627
