### ISSUE TITLE
Add 'Disease name' as an annotation field

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1630]
@martin2urban requested some way to record a name for the disease caused by a pathogen, or a pathogen&ndash;host interaction. We could model this as an extra field on meta-genotype annotations, or we could add it as an annotation extension for certain existing phenotypes (those related to _virulence_ or _pathogenicity_).

**Comment by kimrutherford** [comment]
Another option is to add a new annotation type for metagenotypes so we can directly associate disease ontology terms with a pathogen-host interaction.
