### ISSUE TITLE
Record genetic sequence for strain-specific genes

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1631]
@CuzickA thought it would be useful for curators to provide gene / genome sequences in the case where they are using a gene that is specific to the strain, since we may not be able to reliably identify the gene from a UniProt ID.

We've discussed some initial ideas for how this would be handled at the user interface:

- Allow users to click on a strain tag, which presents an option to add genetic information for that strain,

- Provide a link under every strain selector for adding genes specific to a strain.

**Comment by kimrutherford** [comment]
This would require an extra database table to record strain specific information about genes.  Currently we have a `gene` table which holds the IDs of the genes that the user added to the session.  We'd need to add a `strain_gene` table to hold the extra details.

**Comment by jseager7** [comment]
I'm going to close this, since it's so out of date and much of the subsequent discussion has rendered it pretty much obsolete.

Also, I really don't think it's a good idea for PHI-base to become a repository of sequence information. If we have to link to sequences, it would be much better to have authors deposit the sequence in an actual sequence database and then extend PHI-Canto with an adaptor so that it can link to said sequence database. This ties into recent discussion about adding adaptors for sources other than UniProtKB.
