### ISSUE TITLE
How to delete wrongly entered 'pathogen': Oryza sativa subsp. japonica?

### ISSUE THREAD

**Issue by martin2urban** [pombase/canto#1633]
Can' t delete wrongly entered pathogen Oryza sativa subsp. japonica

![image](https://user-images.githubusercontent.com/2812591/46938945-ef96b480-d05c-11e8-916b-03da4fa64ebd.png)

**Comment by barnabynorman** [comment]
Following my struggle to delete the gene too, its clear we need better labeling of buttons or some way of better indicating that the gene is in use and where.
