### ISSUE TITLE
'Oryza sativa' cannot be used in host picker

### ISSUE THREAD

**Issue by martin2urban** [pombase/canto#1634]
'Oryza sativa' cannot be used in host picker; Uniprot only lists cultivars: Oryza sativa subsp. japonica 
These leads to data corruption.

![image](https://user-images.githubusercontent.com/2812591/46939278-cb87a300-d05d-11e8-8038-4004df99006a.png)

**Comment by CuzickA** [comment]
This seems to be another UniProt species/strain problem similar to Fg/Gz strain PH-1.

**Comment by kimrutherford** [comment]
> These leads to data corruption.

What corruption do you see?

@barnabynorman Is there a configuration problem?

**Comment by barnabynorman** [comment]
@martin2urban this is working now on demo-canto.phi-base.org.uk
