### ISSUE TITLE
Configure phenotype annotation extension for the BRENDA tissue ontology

### ISSUE THREAD

**Issue by martin2urban** [pombase/canto#1636]
Annotation extension for the BRENDA tissue ontology should be enabled for the PHI-canto phenotypes.  This is needed to obtain sample JSON output for PHI-Canto and will allow to demonstrate PHI-canto to stakeholders.

**Comment by jseager7** [comment]
The relevant configuration has been added now, but it's currently only working on local development versions of Canto. Here's proof that the annotations can be created:

![tissue_extension](https://user-images.githubusercontent.com/37659591/47859158-97460d80-dde5-11e8-9211-25611a117f94.PNG)

The staging server has memory capacity issues that need to be resolved before I can close this issue.

**Comment by jseager7** [comment]
The BRENDA Tissue Ontology is now loaded on both Canto servers, so I'm closing this now.
