### ISSUE TITLE
Add option to disable email in Canto development versions

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1640]
Canto's email notification system doesn't seem to work when Docker is nested within the Vagrant development environment that we're using. Plus, it might be related to a bug on my machine where Canto hangs for 60 seconds when creating a session.

It would be nice to have some way to disable email using a flag on the `canto_start` scripts, or in the `canto_deploy` file. This could also be useful to have if we want to do automated testing of the user interface or the curation workflow in future.

**Comment by kimrutherford** [comment]
It probably makes sense to do it in the canto_deploy.yaml.  I'll fixed it so that if no email addresses are configured it skips the email sending.

**Comment by kimrutherford** [comment]
> I'll fix it so that if no email addresses are configured it skips the email sending.

That's done now.  If you remove any `from_address` setting you have in your `canto_deploy.yaml` it will skip sending an email for session creation and assignment.

> Plus, it might be related to a bug on my machine where Canto hangs for 60 seconds when creating a session.

Please let me know if this change fixed the hangs.
