### ISSUE TITLE
Rename 'disease_formation_phenotype' namespace to match PHIPO

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1641]
The latest version of PHIPO has renamed the 'disease_formation_phenotype' namespace to 'pathogen_host_interaction_phenotype'. The PHI-Canto configuration files will need to be updated to match.

@kimrutherford I realise that 'pathogen_host_interaction_phenotype' is a particularly long property name. For annotation types, does Canto reference the 'name' property, or the 'namespace' property? If it references `name`, we could abbreviate it to `phi_phenotype` for the sake of the code, and set `namespace` to the full 'pathogen_host_interaction_phenotype'.

@barnabynorman If you're thinking of automatically loading the PHIPO ontology, the latest version will likely break meta-genotype annotations until this issue is fixed. In the short term, you can load an older version of the OBO file from here:

https://github.com/PHI-base/phipo/blob/b0fdc09ba80b266feb4682f203d396990614df0c/phipo.obo

**Comment by kimrutherford** [comment]
> For annotation types, does Canto reference the 'name' property, or the 'namespace' property?

It looks at the namespace of the terms.  It doesn't matter if it's long because it's not shown to the users.

**Comment by jseager7** [comment]
Ok, in that case I'll just update the config file and test PHI-Canto with the new version of PHIPO.
