### ISSUE TITLE
user friendliness annotation extensions prompt

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1651]
can we tweak this? ...I think munging in col17 and qualifiers makes it look confusing

<img width="602" alt="screen shot 2018-10-28 at 16 20 46" src="https://user-images.githubusercontent.com/12727506/47618669-8e93c580-dacd-11e8-99dd-58cc0c2186fd.png">

e.g.
column17(PR:NNN) -> protein form (should this be hidden? or asked to specify as free text? I cant see any community curator knowing the PR IDs...it looks a bit confusing)
qualifier - is this the place in the workflow where we would expect a user to make a NOT annotation? Maybe this should be a separate section from the gene page? 
Also would they think to add the contributes_to qualifier?

**Comment by kimrutherford** [comment]
The column 17 extension is admin-only.  If you log out it should go away.

**Comment by Antonialock** [comment]
ah that's good. 

What do we think about the qualifier part. If I was a community curator wanting to make a NOT annotation, it is probably not where I would expect to see the option. I probably would have no idea what 'contributes to' means, and I think it looks out of place among the extension options.

**Comment by kimrutherford** [comment]
> What do we think about the qualifier part. If I was a community curator wanting to make a NOT
> annotation, it is probably not where I would expect to see the option.

Sorry, I forgot to say that the qualifier extension is also only shown in admin mode.

> it is probably not where I would expect to see the option.

Yep, it's a big hack.  :-)  If we want community curators to make NOT annotations we need a better way to capture it.

**Comment by ValWood** [comment]
I don't think this is a problem. We don't encourage the community to make NOT annotations. They are so rarely used...

**Comment by mah11** [comment]
Qualifiers are also admin-only.

**Comment by mah11** [comment]
I agree that the current arrangement is fine, given that the oddities are all admin-only.

**Comment by Antonialock** [comment]
yep, all makes sense. Didn't think to log out to check if it is admin only :-) cheers

**Comment by mah11** [comment]
for extension things, you can also look in the config files - "admin" or "user" in the last column
