### ISSUE TITLE
"ReferenceError: toaster is not defined" in reloadOrganisms

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1652]
Hi @jseager7.

I noticed an error in my browser console:

```
ReferenceError: toaster is not defined
    at VM1606 canto-modules.js:3758
    at VM1591 angular-v1.5.11.js:11737
```

It looks like `toaster` is used in reloadOrganisms but is not passed in.  Could you have a look?  This is low priority though.

Line 3757 or so:
```
    }).error(function () {
      toaster.pop('error', 'failed to get organism list from server');
    });
```

**Comment by jseager7** [comment]
I've opened a pull request that I think should fix this, but I haven't been able to reproduce the error, so I'm not certain.

**Comment by kimrutherford** [comment]
Thanks for the fix.
