### ISSUE TITLE
Set up ability for admins to delete curated papers in the curation interface

### ISSUE THREAD

**Issue by martin2urban** [pombase/canto#1656]
Request the ability for admins to delete curated papers in the curation interface for outreach activities. 
This will allow wrongly curated papers to be deleted and curated again in demonstrations and public training sessions.
Options: Could be set up on Hetzner servers demo server only 
(a) Deletion could be configurable so that it’s only enabled on the demo server.
(b) Could be set up on Hetzner demo server  only

**Comment by barnabynorman** [comment]
@martin2urban it is not as simple as I first thought due to permissions
I have documented a work-around using standard functionality of canto, and sent to you

**Comment by martin2urban** [comment]
Thank you!

**Comment by ValWood** [comment]
We use a demo server for training and workshops.
But we can easily delete sessions in the main canto, but not papers. You can just retriage papers as "loaded in error'

**Comment by barnabynorman** [comment]
@ValWood it is on the demo server Martin is asking for - I think they want a nuclear option to go back to the start completely rather than rewinding where it went wrong!
