### ISSUE TITLE
Enable Google Analytics for PHI-Canto webpages

### ISSUE THREAD

**Issue by martin2urban** [pombase/canto#1657]
Google tracker ID to be used is: UA-12077899-6

**Comment by barnabynorman** [comment]
@kimrutherford is there a simple way to add this in the canto_deploy.yaml file and if set, render some js script, passing the ID from the config?

If so, I am happy to populate a file with the script. 

According to [docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/) it should be near the top of the head somewhere (no longer the last line in the body).

**Comment by kimrutherford** [comment]
The JS for Google Analytics in already included in `canto/root/footer.mhtml`.  You should be able to add this this `canto_deploy.yaml` to activate it:

```yaml
google_analytics_id: UA-12077899-6
```

> According to docs it should be near the top of the head somewhere (no longer the last line in the
> body).

We can move the JS code to the header if needed.

**Comment by jseager7** [comment]
I've added this to the config file, so we just have to test it now.

**Comment by barnabynorman** [comment]
Have updated the config on [demo-canto.phi-canto.org](demo-canto.phi-canto.org) and the tracking code is displaying in the footer as expected.
@martin2urban please can you confirm that it is working

**Comment by martin2urban** [comment]
Thanks All,
Google Analytics tracking on demo-canto.phi-canto.org  is working.
