### ISSUE TITLE
Add genotype creation shortcuts to metagenotype page

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1661]
Since we changed the metagenotype page's back button destination to the summary page (#1646), it's more inconvenient for users to create a new genotype from the metagenotype page &ndash; they have to go back to the summary and then into one of the genotype management pages.

I'm considering adding shortcut links in each of the genotype picker columns (host and pathogen) that point to the corresponding genotype management page. It would look like this:

![mg_genotype_shortcut](https://user-images.githubusercontent.com/37659591/48063421-e3fe5f80-e1bc-11e8-9757-8f282319c6af.png)

- - -

@kimrutherford My current plan is just to have these link back to the genotype management page, but I thought it might benefit users if the link passed a reference to the organism that was selected on the _metagenotype management_ organism selector, then automatically selected the same organism in the organism selector on the _genotype management_ page.

However, I'm not sure what Canto's convention is for passing this sort of state data around. Is there a webservice I can use to store this state, or could I pass it as a URL parameter?

**Comment by kimrutherford** [comment]
> I'm considering adding shortcut links in each of the genotype picker columns

I think that's a good plan.

> Is there a webservice I can use to store this state, or could I pass it as a URL parameter?

I think it would need to be passed in the URL because it's a different AngularJS page.

**Comment by jseager7** [comment]
Closing this now, and opening new issue (#1713) for future improvements.
