### ISSUE TITLE
UniProt lookup fails when case doesn't match

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1662]
@barnabynorman noticed that the UniProt webservice appears to be case-sensitive. For example, searching for the ID `p17745` fails:

![uniprot_case_error](https://user-images.githubusercontent.com/37659591/48064055-aa2e5880-e1be-11e8-89d6-95ade08265cd.PNG)

But searching for `P17745` succeeds:

![uniprot_case_success](https://user-images.githubusercontent.com/37659591/48064109-cdf19e80-e1be-11e8-952f-8f1ad3263b57.PNG)

I haven't seen any examples of UniProt using lowercase characters in their identifiers, so it might be safe to perform an uppercase conversion automatically. If we want to be more careful, we could convert to uppercase only when the initial lookup fails.

This might not be a very likely problem, since most users will probably paste the IDs in, but it should be easy to fix, providing we have assurance that lowercase identifiers aren't valid in UniProt.

**Comment by kimrutherford** [comment]
> so it might be safe to perform an uppercase conversion automatically.

Yep, I'm pretty sure that UniProt IDs are always uppercase.  So I think that would be safe.

**Comment by kimrutherford** [comment]
I've made the easy fix of forcing IDs into upper case before querying UniProt.
