### ISSUE TITLE
No feedback when copying annotation to different genotype

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1665]
I've noticed that when using 'Copy and edit' on a phenotype annotation (done from the `genotype_page.mhtml` template), and copying the annotation to a different genotype (e.g. changing the genotype from TRI5Δ to TRI5+), there is little to no feedback about the results of the action. You get a toaster notification about the annotation being stored, but there is no confirmation of success.

This is important in this case, because the new annotation can't appear on the current page: the page can only show annotations for the original genotype, not the genotype that the annotation is copied to. What currently happens is that the modal disappears and the page remains unchanged.

I can think of two obvious solutions:

* Redirect the user to the correct genotype page after the annotation is created, or

* Display another toaster message that confirms the annotation was copied, and if possible, provide a link in the toaster box to view the annotation on the correct genotype page.

I think the second option would probably be less confusing for the user, since we can't guarantee that the user wants to be redirected to a new page, and it's not obvious that a redirect should happen from the workflow.

## Relevant code

The directive that handles the annotation table is `annotationTableRow`, and its template is dynamically set based on an `annotationTypeName` attribute:

https://github.com/pombase/canto/blob/c4a3aed8093f7d5d544cf5ad399d208d02e92508/root/static/js/canto-modules.js#L5621-L5624

In this case, the template is `annotation_table_ontology_row`, which calls the `duplicate()` method:

https://github.com/pombase/canto/blob/c4a3aed8093f7d5d544cf5ad399d208d02e92508/root/static/ng_templates/annotation_table_ontology_row.html#L109-L110

This creates a modal controlled by `AnnotationEditDialogCtrl`, and that controller is responsible for creating `toaster` notifications:

https://github.com/pombase/canto/blob/c4a3aed8093f7d5d544cf5ad399d208d02e92508/root/static/js/canto-modules.js#L5194-L5199

@kimrutherford  Could I add a second toaster notification in the case this storing promise succeeds?
```js
q.then(function(annotation) {
  $uibModalInstance.close(annotation);
  // add a toaster notification here
})
```

**Comment by kimrutherford** [comment]
> This is important in this case, because the new annotation can't appear on the current page

You're right, it's confusing when the user edits the genotype.  It's clearer when the user edits other details, like the term or evidence.

> Could I add a second toaster notification in the case this storing promise succeeds?

Yep, I think that would work.  Thanks.

**Comment by jseager7** [comment]
Closing this now, I'll open a new issue if we decide to improve the solution.
