### ISSUE TITLE
Notify users of how many letters the phenotype lookup requires

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1667]
@kehammond suggested that the phenotype term search box (when creating phenotype annotations) could benefit from an explanation of how many characters must be entered before the lookup triggers. According to @barnabynorman, the lookup triggers after **3 characters**.

It's possible that if users aren't familiar with any of the terms in the ontology, they might just try first letters at random, and this won't help if it never triggers the lookup. Personally, I've had times where I wasn't sure if the ontology was loaded because I didn't know of a full word that would match. I think this is worsened by the fact that PHIPO doesn't have a huge amount of terms in it at the moment (compared to something like GO), and the terms are so general that it might be difficult for curators to predict them.

I don't know if the performance impact would be too great to suggest terms based on one character. I'm wondering whether it would be better to arbitrarily pick some common terms from the namespace and display them as a list when the user first enters the page &ndash; that is, display the full term names in additional to the broad suggestions of term components &ndash; just to give users an idea of how the terms are expressed.

Then again, I'm not representative of the users because I'm not a biologist, and it's possible that the users will have a good enough idea of what their phenotype is that they won't need to guess at what's in the ontology.

**Comment by ValWood** [comment]
What does the sech box say currently  something like "begin typing...?"

Greyed out  text could be added  to say 
 "begin typing (at least 3 characters)"

I think it is fairly common with any lucene type search to require a number of characters before suggestions are made. It's the same for PomBase Canto  isn't something we ever heard anyone mention (n=600+).

Is this really the issue or is it because terms are sometimes not suggested after 3 characters are typed? In which case it might not be a problem when the ontology has more terms.

I would evaluate more fully before you change. This seems more like something that could be evaluated and tweaked later based on user testing.

**Comment by jseager7** [comment]
> is it because terms are sometimes not suggested after 3 characters are typed?

This could happen, but not because of any issue with Lucene &ndash; it would be more likely if the broad term suggestions weren't representative of enough terms in PHIPO. Currently, we don't have any term suggestions for PHIPO, so it's difficult to judge.

I agree that this is probably where we should 'wait and see' if curators do have an issue with it, but I also think that adding some extra text explaining the character limit wouldn't hurt, so I agree with adding this:

> "begin typing (at least 3 characters)"

**Comment by kimrutherford** [comment]
> According to @barnabynorman, the lookup triggers after 3 characters.

It should be 2 characters if you're using the latest code.

> I don't know if the performance impact would be too great to suggest terms based on one character.

I tried it a while ago and it returned an error from the query.  So 2 characters is the minimum.

**Comment by jseager7** [comment]
I've added some text to explain the required number of characters in the ontology workflow.

![image](https://user-images.githubusercontent.com/37659591/70152219-bd06ab80-16a4-11ea-96a6-e1005d71ad1b.png)

Note that we don't have anything for the lookup when the user is in the pop-up workflow. However, I could amend the notice that shows when the term field is invalid:

![image](https://user-images.githubusercontent.com/37659591/70152317-de679780-16a4-11ea-95a1-7f8d6799e88e.png)

**Comment by ValWood** [comment]
I think these searches are common enough that we don't need to spell it out.
Can't the  "start typing to choose a term" appear in the box? (I see this sometimes so it disappears when you begin typing)
Maybe we discussed this in the past and there's a reason we did not do it.

**Comment by jseager7** [comment]
> Maybe we discussed this in the past and there's a reason we did not do it.

I think part of the problem was that sometimes the autocomplete reverts to a drop-down picker, rather than allowing typing, when the number of terms is small. That would make the "start typing to choose a term" placeholder misleading. However I'm not sure if this problem still applies now; see https://github.com/pombase/canto/issues/2038#issuecomment-554227910.

**Comment by jseager7** [comment]
I'm going to close this, since the request itself was implemented ages ago.
