### ISSUE TITLE
toxon restrictions not filtered though to Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1668]
These were added to GO 5 days ago, but I still see "cardiac muscle ' terms
https://github.com/geneontology/go-ontology/issues/16047

Let me know if we are up to date and I'll ask Pascale.

**Comment by kimrutherford** [comment]
We're up to date with GO.  The go-plus.owl we use via the PURL link last changed on Oct 31st so it won't include changes from 5 days ago.

http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.owl

**Comment by ValWood** [comment]
ok, can close, I'll notice later if there are still any visible in canto...
