### ISSUE TITLE
can't re-approve session

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1669]
https://curation.pombase.org/pombe/curs/3a2dde8117141243

cant approve because
GO:0033573 | high-affinity iron permease complex

isn't  in the database. But I can see it  in QuickGO (and it does not seem to have taxon restrictions)
https://www.ebi.ac.uk/QuickGO/term/GO:0033573

**Comment by kimrutherford** [comment]
I run owltools manually to make a pombe-only OBO and that term is definitely removed by the taxon constraints.

One of the parent terms is bateria only:
 GO:0015092 high-affinity ferric iron transmembrane transporter activity

It's not an is_a relation (it's "capable of") so I don't know if that would be enough to filter out your term GO:0033573.

**Comment by ValWood** [comment]
That would do it. I'll reopen the GO ticket.
v

**Comment by ValWood** [comment]
Actually, so I understand, are the taxon constraints dictated by the obo file. I'm not very familiar with the  "capable of" relation.  Do we decide ourselves which relations are followed for taxon constraints, or is that GO?

**Comment by kimrutherford** [comment]
> Actually, so I understand, are the taxon constraints dictated by the obo file.

We're using go-plus.owl and processing it with owltools.

OWLTools knows how the taxon constraints should be applied across relations.

**Comment by ValWood** [comment]
OK, to GO...

**Comment by ValWood** [comment]
I think this is all fixed...
