### ISSUE TITLE
Data needed for community curation paper and grant

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1671]
Just collecting ideas - putting this on hold for the time being so we can figure out exactly what we want to look at when it comes to it.

metric 1
- response rate over time (per year) - would be interesting to see if there is a steady increase

metric 2
- number of annotations made by community curator over consecutive sessions (do people add more annotations in their second, third, etc paper?)

**Comment by ValWood** [comment]
Might be useful for the grant we should add these graphs to the stats pages

**Comment by ValWood** [comment]
Also from https://github.com/pombase/canto/issues/1214

@Antonialock : Would also be nice to see if the proportion of annotations made by community vs staff goes up with time? (in a community curated session)

So, for the community curated sessions, per year:
[# annotations made by community curator] / [# annotations made by PomBase]

@ValWood : yep, good suggestion...that should improve over time (will need to do n/a for pre 2012 for this one).

**Comment by ValWood** [comment]
metric 1 how likely are people to have curated based on data publised?
Use publication date
- [ ]  need info that the session is assigned to a community curator
- [ ]  this info needs to be passed to chado
- [ ]  we will make another colour (redish) on the total annotations graph so we can see how many sent out, not curated yet
- [ ] separate view ratio of curated/uncurated(sent our) by year

**Comment by ValWood** [comment]
repeat curators.

- [ ] if community curators have curated mutiple papers, does number of annotations they make go up over time?

say a publication has 100 annotation/ what is fraction between the number the community made and us
score per paper 0.75 percentage of annotation for the paper attributed to them

A
1 0.25
2 0.5
3 0.75

authour B might have 7 papers
1
2 0.12
3
4
5
6
7

**Comment by ValWood** [comment]
metric 3
not based on individuals at all, does the  proportion go up ? This is as above but  not for individual

**Comment by Antonialock** [comment]
![img_2897](https://user-images.githubusercontent.com/12727506/53162867-d41c5700-35c4-11e9-975f-fdefb9c9573c.jpg)

**Comment by ValWood** [comment]
metric 2
Needs to include the order they did them (inferred from date submitted dates submitted) 
Number of annotations from community and number from staff for each paper

**Comment by kimrutherford** [comment]
> Would also be nice to see if the proportion of annotations made by community vs staff goes up with time?

Here's my first pass at that.  I suspect the numbers for 2012 are odd because Canto wasn't recording when admins made changes in community sessions.  I'll check that.

| annotation_year | community | admin | total | % 
|----------------- | ----------- | ------- | ------- | ---------
|            2012 |       466 |     2 |   468 |      99
|            2013 |       602 |  1460 |  2062 |      29
|            2014 |       974 |  2010 |  2984 |      32
|            2015 |      1592 |  2012 |  3604 |      44
|            2016 |      2453 |  3446 |  5899 |      41
|            2017 |      2294 |  2488 |  4782 |      47
|            2018 |      2788 |  3024 |  5812 |      47
|            2019 |       111 |   363 |   474 |      23

**Comment by kimrutherford** [comment]
> if community curators have curated multiple papers, does number of annotations they make go up over
> time?

I've extracted this table from Chado with the percentages of community annotations per community curated paper.  The table or ordered by curator name and session accepted date.  From this table I've made a CSV file with one line per curator with the percent community annotations:
 Dropbox/pombase/Community curation/queries/community_annotation_percent_by_user.csv

Is that what you were after?

-----

|     pmid      | community | admin | total | percent | session_accepted_date |     curator_name     
|---------------|-----------|-------|-------|---------|-----------------------------|----------------------------
| PMID:27558664 |        13 |    10 |    23 |      56 | 2016-09-21 02:41:34         | Abantika Ganguly
| PMID:28242692 |         6 |    21 |    27 |      22 | 2017-04-28 17:22:53         | Adam Frost
| PMID:26912660 |        10 |    49 |    59 |      16 | 2016-03-01 11:40:54         | Adi Cohen
| PMID:20404181 |         5 |     6 |    11 |      45 | 2014-06-11 21:25:04         | a. john callegari
| PMID:26652183 |        26 |     0 |    26 |     100 | 2016-06-07 17:23:01         | a. john callegari
| PMID:24876389 |         8 |    31 |    39 |      20 | 2014-06-10 00:31:02         | Akio Nakashima
| PMID:23980030 |         0 |    58 |    58 |       0 | 2013-11-15 01:33:46         | Akira Yamashita
| PMID:23755176 |         0 |    13 |    13 |       0 | 2013-12-28 13:06:41         | Akira Yamashita
| PMID:25736293 |         0 |    71 |    71 |       0 | 2017-04-06 02:36:31         | Akira Yamashita
| PMID:28671615 |         2 |     7 |     9 |      22 | 2017-07-12 05:59:36         | Akira Yamashita
| PMID:29330317 |        10 |    64 |    74 |      13 | 2018-07-04 05:28:07         | Akira Yamashita
| PMID:27481777 |        12 |    22 |    34 |      35 | 2016-08-03 11:57:53         | Akshay Vishwanatha
| PMID:29319508 |        13 |     0 |    13 |     100 | 2018-01-22 10:09:40         | Akshay Vishwanatha
| PMID:28784611 |        34 |    17 |    51 |      66 | 2017-08-21 21:47:25         | Alaina Willet
| PMID:29343550 |        33 |    16 |    49 |      67 | 2018-01-22 18:56:08         | Alaina Willet
...

Note to self:
```sql
SELECT annotation_summ.pmid,
       count(*) filter(WHERE community_curated) AS community,
       count(*) filter(WHERE NOT community_curated) AS ADMIN,
       count(*) AS total,
       100*count(*) filter(WHERE community_curated) / count(*) AS percent,
       canto_session_accepted_date,
       canto_curator_name
FROM pombase_annotation_summary annotation_summ
JOIN pombase_publication_curation_summary pub_summ ON annotation_summ.pmid = pub_summ.pmid
WHERE annotation_summ.session IS NOT NULL
  AND annotation_summ.publication_community_curated
  AND canto_session_accepted_date IS NOT NULL
GROUP BY annotation_summ.pmid, canto_session_accepted_date, canto_curator_name
ORDER BY canto_curator_name, canto_session_accepted_date;
```

**Comment by Antonialock** [comment]
maybe it would make the table easier to interpret if we do it like this:

% oldest paper curated | % second oldest paper curated | % third oldest paper curated | % fourth oldest paper curated | % fifth oldest paper curated | curator name

(don't know up to how many papers it's worth tracking)

**Comment by kimrutherford** [comment]
> response rate over time (per year) - would be interesting to see if there is a steady increase

This is a table of the number of community session sent out each year along with the response rate calculated by looking at the number of sessions that were accepted.  There isn't a steady increase you were looking for.

| sent_year | sent | accepted | response_rate \% 
| ----------- | ------ | ---------- | ---------------
|      2013 |  280 |      153 |          54.6 |
|      2014 |  217 |      105 |          48.3 |
|      2015 |  218 |      124 |          56.8 |
|      2016 |  217 |      122 |          56.2 |
|      2017 |  204 |      109 |          53.4 |
|      2018 |  193 |       93 |          48.1 |
|      2019 |   41 |       11 |          26.8 |

Note to self:
```sql
SELECT canto_first_sent_to_curator_year as sent_year,
       count(pmid) as sent,
       count(pmid) FILTER(WHERE canto_session_accepted_date IS NOT NULL) as accepted,
       TRUNC(100.0 * count(pmid) FILTER(WHERE canto_session_accepted_date IS NOT NULL) /
             count(pmid), 1) as response_rate
FROM pombase_publication_curation_summary
WHERE canto_session IS NOT NULL
  AND canto_first_sent_to_curator_date IS NOT NULL
  AND canto_approved_date IS NOT NULL
  AND canto_curator_role = 'community'
GROUP BY canto_first_sent_to_curator_year;
```

Here's a similar table but with the approved session counts rather than the accepted sessions count:

| sent_year | sent | approved | response_rate \% |
|----------- | ------ | ---------- | --------------- |
|      2013 |  280 |      122 |          43.5 |
|      2014 |  217 |       82 |          37.7 |
|      2015 |  218 |       96 |          44.0 |
|      2016 |  217 |       99 |          45.6 |
|      2017 |  204 |       86 |          42.1 |
|      2018 |  193 |       65 |          33.6 |
|      2019 |   41 |        4 |           9.7 |

note to self:
```sql
SELECT canto_first_sent_to_curator_year as sent_year,
       count(pmid) as sent,
       count(pmid) FILTER(WHERE canto_approved_date IS NOT NULL) as approved,
       TRUNC(100.0 * count(pmid) FILTER(WHERE canto_approved_date IS NOT NULL) /
             count(pmid), 1) as response_rate
FROM pombase_publication_curation_summary
WHERE canto_session IS NOT NULL
  AND canto_first_sent_to_curator_date IS NOT NULL
  AND canto_curator_role = 'community'
GROUP BY canto_first_sent_to_curator_year;
```

**Comment by Antonialock** [comment]
> There isn't a steady increase you were looking for.

Ah but I bet there is in reality. Initial invitations were targeted to people more likely to respond?

**Comment by ValWood** [comment]
response rate over years 
- I think its probably because some people do it straight away, but most people only do it after 2 years of nagging and 3 reminders! so definitely we would expect the 'peak' to be papers that are a couple of years old...

**Comment by ValWood** [comment]
I see some nice increases in that scatter plot data though!

**Comment by Antonialock** [comment]
> I've extracted this table from Chado with the percentages of community annotations per community curated paper. The table or ordered by curator name and session accepted date. From this table I've made a CSV file with one line per curator with the percent community annotations:
Dropbox/pombase/Community curation/queries/community_annotation_percent_by_user.csv

> Is that what you were after?

Thanks...unfortunately I thought we'd see more of a 20%->30%->60%->...

but 


Average 1st paper | 36.316726
Average 2nd paper | 41.4732143
Average 3d paper | 41.5614035
Average 4th | 40.6666667
Average 5th | 34.7142857
Average 6th | 34.1764706

**Comment by ValWood** [comment]
Thats a bit worryng, it might mean that people don't try as hard if they think we are going to do it. But 4th 5th 6th will be lower numbers so much more easily skewed. I thought you were going to do this as a bar/ with scatter?

**Comment by ValWood** [comment]
if there are only 10 or 20 in 6th paper and a few do really badly it will squew a lot...

**Comment by Antonialock** [comment]
gah, I need a graph for the poster!!

The box plot doesn't look great either. The trend looks like it is improving slightly but not much, weird

![box plot east](https://user-images.githubusercontent.com/12727506/54839806-8e39d800-4cc3-11e9-9b6d-3a4159890ee6.png)

**Comment by ValWood** [comment]
Just ditch this one and show %increase over time.

There is plenty of other stuff to sue.
Don't forget to include the stuff from the surve about why people do and don't curate.

**Comment by ValWood** [comment]
it  might be better to show the above as scatter plots rather than solid bars (see above comment)

**Comment by Antonialock** [comment]
marginally better in a violin plot

<img width="750" alt="violin plot east" src="https://user-images.githubusercontent.com/12727506/54840369-ce4d8a80-4cc4-11e9-8ff7-141d3dfae3ec.png">



bean plot

<img width="750" alt="bean plot east" src="https://user-images.githubusercontent.com/12727506/54840441-f6d58480-4cc4-11e9-9499-056ee5fe9ec2.png">

**Comment by Antonialock** [comment]
> Just ditch this one and show %increase over time.


What data do you exactly mean by this?

**Comment by ValWood** [comment]
> Just ditch this one and show %increase over time.

Don't use this graph. It doesn't really show a trend...
Maybe next time...

**Comment by ValWood** [comment]
You could try
1 paper
2 papers
more than 2 papers....

**Comment by Antonialock** [comment]
I'm still not following what you mean but really appreciate some suggestions (I'm a bit stuck trying to plot an interesting graph)

**Comment by ValWood** [comment]
so try the same graph but "bin" all "3 papers or more"

It is possible that will show a reasonable increase.

I think the reason it doesn't look so good not is that  a small  number of papers with not much curation skew this.

**Comment by ValWood** [comment]
Also, if you do the "binning all over 3" strategy you don't need to stop at 7, you can include all (which would include all of the papers Jacky has done, since I guess  JAcky and Kathy G. are the only people who have done more than 7 papers?)

**Comment by ValWood** [comment]
Only have 3 data points on the horizontal.

1 paper
2 papers
>2 papers

This way you might see quite a steep increase in percentage. Perhaps not but it might work. PArticularly if you go out beyond 7.

Gotta go for trian...

**Comment by ValWood** [comment]
Did my comment make sense?
I think it could work on 3 data points?
If not I suggest leaving for this time and we try again in the future when we have  a larger sample size.

**Comment by Antonialock** [comment]
Well it does look better but it feels very bad practice - in the other bins there is one person per data point - here we are massively skewing the data to a few individuals who have been very keen.

**Comment by ValWood** [comment]
Eh, there are 100s of people per datapoint. Unless I misunderstood what you are doing?

**Comment by Antonialock** [comment]
oh I thought you asked me to bin every data point 3 or more, which would make e.g. Jacky appear 50 times in that bin.

**Comment by Antonialock** [comment]
If you didn't then you need to explain because I don't understand what you mean :-)

**Comment by ValWood** [comment]
You are only including people in any datapoint if they have curated more than one paperanyway ? So you are already skewing for  keen- more than 2 is keen. I dont think more than 7 is any keener, its's just   "I have more papers to curate, but I am committed to this"

All we are saying in this graph is if you curate more than 2 papers you get better. But there should still only be a single data point per individual? (if this is not the case we should address).

**Comment by ValWood** [comment]
Ah right  I see what you mean, we can't do that - it would need to be normalised somehow. 

I would leave this plot out until we have more data maybe....

**Comment by Antonialock** [comment]
l think we are good for data for now.
