### ISSUE TITLE
child terms aren't selected

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1673]
Using the "quick add" method of adding a phenotype. 
- I search for a term, and select it.
- I then find a more specific term using the child term suggestions. 
- I select the child term I want and press finish. 
- Canto then reverts to the parent term, not the child term.

**Comment by kimrutherford** [comment]
I doesn't work for GO either.  It reverts to the parent term.

**Comment by kimrutherford** [comment]
I think I've fix this.  Could you have a try?
