### ISSUE TITLE
Publication details placement odd

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1675]
This seems strange underneath. Is there any compelling reason for it's placement here? Could we keep it in the top right corner?

![pmid_placement](https://user-images.githubusercontent.com/7359272/48481589-0bc97500-e806-11e8-9ff4-8edefd0bf258.jpg)

**Comment by ValWood** [comment]
I think I prefer each gene on its own line, Or maybe that's only because it is what I am used to.
Wrapping is an option too.
In PHI base, what is the largest number of genes in a single paper so far that would be curated via this route?

There is also the option to move the Pubmed stuff to the top but only have a 
"publication details" heading with a drop down to see them. You don't really ever refer to these once you are going with the curation, so it's probably an unnecessary use of space. It's nice to see  the publication details when you return to a session after a while  though..... so maybe it should only be fully visible in approval, or approved, but hidden during "curation in progress"

**Comment by ValWood** [comment]
You can see why this is a bit annoying as you begin to annotate 

http://canto.phi-base.org/curs/8bf2259e22c37d46

It's just not relevant to see the publication bunded here  and need to scroll past it to see the annotations

**Comment by jseager7** [comment]
Just to confirm, this displays correctly on my development copy of Canto:

![pubmed_column](https://user-images.githubusercontent.com/37659591/48547502-b4d5a580-e8c2-11e8-913f-5d808af35563.PNG)

**Comment by barnabynorman** [comment]
@kimrutherford much better!
