### ISSUE TITLE
disable access to  "meta-genotype management" page until meta-genotypes can be created

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1678]
I see this:

![not very clear](https://user-images.githubusercontent.com/7359272/48486421-61584e80-e813-11e8-9571-f77a54dc698a.jpg)

I don't know what to do from here?
There don't appear to be an "action" options.

**Comment by ValWood** [comment]
After staring at it for a while, I see I need to create single organism alleles first but this isn't clear.

I'm not sure why the organism names are displayed on this page in this case? Shouldn't these only be displayed after useable single organisms genotypes are created?

**Comment by ValWood** [comment]
OK, I think it would make sense not to see this link until the option is  avaiable.

Also, why is there a list with 
"wild type genotype" here.

Even when I come via the correct route I still see this:
![wild type](https://user-images.githubusercontent.com/7359272/48487587-9619d500-e816-11e8-99c0-65e1985c44d3.jpg)

but I have no idea why it is there, or what it's for?

**Comment by ValWood** [comment]
I'm moving the comment about "wild type genotype" to it's own ticket.

**Comment by kimrutherford** [comment]
> our plan was to disable the link to the meta-genotype page until the curator is actually
> able to create a meta-genotype

I've done that now.
