### ISSUE TITLE
style suggestions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1681]
![suggestions](https://user-images.githubusercontent.com/7359272/48488198-168d0580-e818-11e8-96b9-4f6095513e66.jpg)

I think this  page would look clearer (in addition to moving the  Publication box) if you:

- [ ]  removed the grey line a below the  "Pathogen organisms" and Host Organisms" rows and  allowed the text below to move slightly closer to the header  ( a 'simpler looking' list)

- [ ] indented  the"action links" under "annotate genes" and "annotate genotypes"  a little further (maybe to align with the  Organism/genes table

**Comment by jseager7** [comment]
I think this got fixed ages ago by pull request #1998. Closing now.
