### ISSUE TITLE
 not possible to edit  annotation comment field

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1682]
It isn't possible to edit the comments field once created (only tried in meta-genotype  pathogen-host interaction phenotype"

**Comment by ValWood** [comment]
Actually, you cant edit any field at all. Although you can "copy/edit"

**Comment by kimrutherford** [comment]
You should be able to click "Edit" to the right of annotations in the annotation tables to edit any field including the comments.  I thought that was possible for meta-genotype / phenotype annotations.

**Comment by ValWood** [comment]
In Canto it works for everything.

In PHI-canto it works for GO but not for phenotypes.

**Comment by kimrutherford** [comment]
Is the edit link missing or doesn't it work?

**Comment by ValWood** [comment]
I get the red pop up server error
"no such annotation field" 
when I try to click OK. I couldn't screen shot it because it disappears...

**Comment by jseager7** [comment]
I'm closing this since I'm presuming it's fixed now.
