### ISSUE TITLE
no strain displayed  in metagenotypes ?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1684]
http://canto.phi-base.org/curs/8bf2259e22c37d46/metagenotype_manage

Note to self:
Here it's Wsb for arabidopsis and Emoy2 for Hyaloperonospora arabidopsidis
in cas it is lost

**Comment by ValWood** [comment]
I get it.
I can  added the strain info to the single allelle strains. But when I get through to the multi allele genotype creator it no longer shows genotypes with strains.

**Comment by kimrutherford** [comment]
@barnabynorman could you look into this?

**Comment by barnabynorman** [comment]
I have added the strain info onto the meta-genotype page

@CuzickA do we need to add a picker for the wildtype strain??

**Comment by jseager7** [comment]
The metagenotype list seems to have two separate strain displays now, which I can see thanks to another unresolved bug preventing the strain to species mapping (#1696). Here's how it looks for me:

![mg_strain_display](https://user-images.githubusercontent.com/37659591/48898303-53728100-ee44-11e8-851f-ac803fd48b57.PNG)

The Gibberella zeae example shows that the strain name is included both as part of the organism name, and in a separate element below it. I think it should only be shown only in one or the other.

**Comment by jseager7** [comment]
Since we seem to be discussing two separate issues, I've opened new tickets at #1700 and #1702 to replace this one. Closing now.
