### ISSUE TITLE
Is the strain picker working

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1686]
I had to add the strains manually, none were displayed in the picker. Is this working or do these strains need adding to the strain selection
http://canto.phi-base.org/curs/8bf2259e22c37d46/edit_genes?

**Comment by kimrutherford** [comment]
It's possible that the organisms you using don't have strain loaded.  @barnabynorman can you check Hyaloperonospora parasitica and Arabidopsis thaliana?

**Comment by barnabynorman** [comment]
@ValWood checkout [http://demo-canto.phibase.org](http://demo-canto.phibase.org) where they have been loaded

**Comment by jseager7** [comment]
I've just confirmed that this is working, so closing now.
