### ISSUE TITLE
Improve display of strain selector in gene / organism table

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1687]
This is slightly confusing

![strain selection](https://user-images.githubusercontent.com/7359272/48495764-9622d080-e828-11e8-90ef-69e9b7c36401.jpg)

I think a simple improvement would be to make the strain selection and the genes in  in cleary separate table rows.

**Comment by jseager7** [comment]
If I've understood correctly, the gene and organism table would look something like this:

![confirmation_strain_row](https://user-images.githubusercontent.com/37659591/48551949-e2c0e700-e8ce-11e8-9971-7b729926e841.PNG)

That's just a mockup, so I didn't bother matching the colours of the existing gene table, but if you prefer the colours of the table above, we could change the existing table to match.

**Comment by jseager7** [comment]
I've fixed this on my fork now, here's how it looks:

![1676-compact-table](https://user-images.githubusercontent.com/37659591/51177783-840cef00-18b8-11e9-98d0-a47c6be0fc2d.PNG)

I'd like to include this change as part of a pull request that also fixes #1676, see [my comment](https://github.com/pombase/canto/issues/1676#issuecomment-454363747) in that issue for more details. However if it looks like it's going to take a long time to fix issue 1676, I can implement this separately.

**Comment by ValWood** [comment]
This looks  much better...

**Comment by jseager7** [comment]
Closing now; fixed by the pull request above.
