### ISSUE TITLE
import PomBase GO annotation extension files to PHI-Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1688]
I can't add extensions at all right now even via the free text option (presumbly because I am not logged in as Admin).

It would be useful to be able to use GO extensions straight away. We can extend as required.

**Comment by jseager7** [comment]
@kimrutherford if you can let me know which extension configuration I need to add, I should be able to do this. Currently we only have one extension configured, which is the BRENDA Tissue Ontology on _pathogen-host interaction phenotypes_. However, we do currently have a persistent error loading the full set of PHI-Canto ontologies when annotation extension processing is enabled, so that will probably have to be fixed first. I'll try to debug that today.

**Comment by kimrutherford** [comment]
Hi James.

See this comment: https://github.com/pombase/canto/issues/1592#issuecomment-411011695

You'll need to put something like this in your `canto_deploy.yaml`:

```yaml
extension_conf_files:
  - /some/data/directory/GO_BP_A_E_config
  - /some/data/directory/GO_CC_A_E_config
  - /some/data/directory/GO_MF_A_E_config
```

You'll need to put in absolute paths to the files.

The files that PomBase uses for GO are here:
  https://curation.pombase.org/ontologies/annotation_extensions/annotation_ex_config/

**Comment by jseager7** [comment]
Thanks. I assume I don't have to load any extra ontologies to enable these extensions?

**Comment by kimrutherford** [comment]
> I assume I don't have to load any extra ontologies to enable these extensions?

You'll need the sequence ontology (SO) and this one:
 https://curation.pombase.org/dumps/latest_build/pombe-embl/mini-ontologies/has_qualifier_range.obo
(for the PBHQ terms)

You can get SO from here if you don't have it already:
 https://github.com/The-Sequence-Ontology/SO-Ontologies/blob/master/so-simple.obo

**Comment by kimrutherford** [comment]
That all looks fine.  I'm trying your command above to see if I can reproduce the error locally:

```./canto/script/canto_docker ./script/canto_load.pl \
--process-extension-config \
--ontology https://curation.pombase.org/dumps/latest_build/pombe-embl/mini-ontologies/has_qualifier_range.obo \
--ontology https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/so-simple.obo \
--ontology http://snapshot.geneontology.org/ontology/go-basic.obo
```

**Comment by jseager7** [comment]
> So the solution is to add more memory to the server perhaps by adding swap space.

In that case I'll have to allocate more memory to the Vagrant machine as well, so I'll try that first.

**Comment by jseager7** [comment]
OK, I increased the memory on the Canto VirtualBox to 4 GB, and the script passed with no errors. It might've taken close to 30 minutes to run. We're going to try to run the command on Hetzner later today, and I'll commit the fix for Vagrant soon:

```ruby
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end
```

**Comment by kimrutherford** [comment]
I'm glad that fixed it.  You'll need to watch out if in future you add more OBO files to the load command.  You may need to increase the memory available in that case.

**Comment by jseager7** [comment]
@ValWood The annotation extensions for GO and BTO are loaded on `canto.phi-base.org`, so you should be able to finish your curation session now. Let me know if you find any more problems.
