### ISSUE TITLE
Move species_strain_map into a separate file

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1694]
(Follow-up from #1611)

The configuration data that maps species taxon IDs to their strain taxon IDs is large enough to make the `canto_deploy` file cumbersome to work with on GitHub. I think it would be better if we could store the mapping in a separate file and reference its path in `canto_deploy` instead, like what is currently done with the `extension_conf_files` property.

The new property could look like this:

```yaml
species_strain_map_file: /import_export/species_strain_map.yaml
```

**Comment by kimrutherford** [comment]
I've implement this by adding an extra config option so you can now put something like this in your `canto_deploy.yaml`:

```
 extra_config_files:
   - phibase_organism_maps.yaml
```

There can be multiple yaml files in the list.  The file names can be absolute paths or can be relative to the main Canto directory containing `canto_deploy.yaml` etc.
