### ISSUE TITLE
Strain mapping not working in development environment

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1696]
The process to map strain-level UniProt IDs back to their parent species taxon ID doesn't seem to be working on my Vagrant copy of Canto. I've added the `species_strain_map` property to `canto_deploy` (as copied from the config repository), and I've loaded the latest organism and species lists, but when I add the ID _Q00909_ (gene TRI5), the organism returned corresponds to the 'subspecies' taxon ID 229533: _Gibberella zeae (strain PH-1 / ATCC MYA-4620 / FGSC 9075 / NRRL 31084)_, instead of the expected species with taxon ID 5518: _Gibberella zeae_.

(Note that taxon ID 229533 is the 'correct' organism for Q00909 according to UniProt, but we don't want to use these lower taxonomic ranks.)

@kimrutherford are there any extra steps I need to do to enable the strain-to-species mapping? Should I need to re-initialise the data directory?

**Comment by jseager7** [comment]
I've now noticed that this bug only seems to occur with UniProt ID Q00909; other IDs get correctly mapped to _Fusarium graminearum_, rather than _Gibberella zeae (strain PH-1 / ATCC MYA-4620 / FGSC 9075 / NRRL 31084)_. No idea why, although I guess it could be stale data in the track or curs database, or another problem with UniProt's API.

![q00909_bug](https://user-images.githubusercontent.com/37659591/49150388-a183fa80-f304-11e8-987f-8af86eedd285.PNG)

**Comment by ValWood** [comment]
Gibberella zeae, also known by the name of its anamorph Fusarium graminearum
presumably would need to be resolved by UniPRot. Suggest waiting for @CuzickA

**Comment by kimrutherford** [comment]
> @kimrutherford are there any extra steps I need to do to enable the strain-to-species mapping? Should
> I need to re-initialise the data directory?

You'll need to restart Canto but that's all.  Let's debug this on Skype.

**Comment by kimrutherford** [comment]
> > I need to re-initialise the data directory?
> You'll need to restart Canto but that's all.

I forgot that Canto has a local cache of the genes from UniProt.  When you try Q00909 it's probably coming from the cache and won't have the fixed taxon ID.

The quick solution in this case is to remove the gene from the cache so that Canto is forced to re-fetch it from UniProt.  The taxon mapping is applied when the entry is fetched.

You can delete the cache gene with something like:

```
  sqlite3 data/track.sqlite3 "delete from gene where primary_identifier = 'Q00909';"
```
(Your path to track.sqlite3 might be different)

Or flush the cache completely with:

```
  sqlite3 data/track.sqlite3 "truncate gene;"
```

**Comment by jseager7** [comment]
> Or flush the cache completely

I tried this process and it worked. Q00909 returns 'Fusarium graminearum' instead of 'Gibberella zeae (strain PH-1 / ATCC MYA-4620 / FGSC 9075 / NRRL 31084)'. Just one thing to note: the original command didn't work because SQLite apparently lacks a `TRUNCATE` command. I used `DELETE FROM <table>` instead.

```
./canto/script/canto_docker sqlite3 /data/track.sqlite3 "DELETE FROM gene;"
```
