### ISSUE TITLE
Strain picker shows taxon IDs instead of names

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1697]
Not sure if we have an issue for this already, but the strain picker on the 'Confirm gene and host organism list' page is showing the taxon IDs instead of the strain names for the pre-populated strains in the strain selection drop-down menu. I've only seen the bug on _Fusarium graminearum_ so far:

![strain_picker_name_bug](https://user-images.githubusercontent.com/37659591/48900751-2c6b7d80-ee4b-11e8-8d65-300232b16aed.png)

The correct names for the strains in that list are as follows:

|Taxon ID|Strain name|
|---|---|
|1450154|Fusarium graminearum CS3005|
|229533|Gibberella zeae (strain PH-1 / ATCC MYA-4620 / FGSC 9075 / NRRL 31084)|
|449239|Fusarium graminearum GZ3639|

- - -

Also, I've noticed that there's a big list of _Fusarium graminearum_ strains on the [species-level page](https://www.uniprot.org/taxonomy/5518), none of which are returned by the picker. @CuzickA do you think we will need to provide any of the following strains?

- ATCC 46032 / CBS 110244 / NRRL 2903
- DSM 4527 / 183 ,DSM 4527
- F15
- GZ3639
- H-11
- IBT1958
- CBS 110263 / NRRL 13383 ,NRRL 13383
- CBS 110264 / NRRL 28063 ,NRRL 28063
- CBS 123654 / NRRL 28336 ,NRRL 28336
- CBS 110271 / NRRL 28439 ,NRRL 28439
- CBS 110266 / NRRL 29169 ,NRRL 29169
- CBS 110261 / NRRL 5883 ,NRRL 5883
- ATCC 34912 / CBS 110262 / NRRL 6394 / F184a ,NRRL 6394
- W-8 ,W8
- ZF43

**Comment by jseager7** [comment]
I should clarify that the three 'strains' currently shown in the picker (1450154, 229533, 449239) are represented as subspecies by UniProt, in case that wasn't obvious.

**Comment by barnabynorman** [comment]
@jseager7 I have updated these now - please check they are working as expected

**Comment by jseager7** [comment]
I've checked this on the production and demo Canto versions, and the strains display correctly now. I also seem to have a full list of _Fusarium graminearum_ strains; not sure if this was intended, but I think it's better that they're all there:

![fg_all_strains](https://user-images.githubusercontent.com/37659591/49149709-b52e6180-f302-11e8-93b2-625d30c37b3b.png)
