### ISSUE TITLE
Allow editing strains when editing genotype

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1701]
Currently there's no way to edit the strain of a genotype after it's been created. We need to add a field to display and edit the strain of the organism in the template [`genotype_edit.html`](https://github.com/pombase/canto/blob/cb4d0870c098d7e2a6a679681d8006b2ac624c49/root/static/ng_templates/genotype_edit.html), and add corresponding logic to the [`genotypeEdit`](https://github.com/pombase/canto/blob/53b9c6d6a0b8fd0aacadb7845bbec57a8a748a59/root/static/js/canto-modules.js#L3253) directive.

There's two possible places the strain picker could be located:

**Option 1:** Insert the picker below the other fields that apply to the whole genotype:

![edit_strain_picker_1](https://user-images.githubusercontent.com/37659591/49152118-bc0ca280-f309-11e8-8047-e682a7b3529d.PNG)

**Option 2:** Insert the picker on the edit dialog for every allele in the genotype:

![allele_edit_link](https://user-images.githubusercontent.com/37659591/49152352-6e446a00-f30a-11e8-89c1-81f23c2a02bd.PNG)
![allele_edit_strain_picker](https://user-images.githubusercontent.com/37659591/49152357-713f5a80-f30a-11e8-845e-a6746040bd5d.PNG)

The problem with Option 2 is that it allows users to edit the strain for a single allele in the genotype, which is presumably invalid since it makes that allele inconsistent with the multi-allele genotype as a whole. If a genotype should only ever have one strain, then Option 1 makes more sense.

Note that we will also need to guard against users inadvertently making the genotype identical to an existing strain by changing the strain. There's an issue for this at #1620.

**Comment by kimrutherford** [comment]
> Option 1: Insert the picker below the other fields that apply to the whole genotype:

I think that's the best plan.  We'll need to pull out the strain picker from alleleEdit into it's own component.  Could you have a look at that and see how tricky it would be?

**Comment by jseager7** [comment]
I've had a look at the current implementation of the strain picker, as it's used in the allele editing modal, and here's a model of how it fits into the existing code:

![1701_strain_picker_model](https://user-images.githubusercontent.com/37659591/50831248-24579680-1342-11e9-9c99-9d97a62f1ccb.png)

As for the selector itself, that's simply included as a `<select>` element in the `select_strain_picker` template:

https://github.com/pombase/canto/blob/fdccac139267802bb7f53c2c670cea6588de6cba/root/static/ng_templates/select_strain_picker.html#L14-L20

Where the strain names are supplied through `StrainsService`, as called by `strainPickerDialogCtrl`.

- - -

### Solution 1

Presuming we want to have an entirely self-contained strain selector &ndash; like what we have with the organism selector &ndash; I'd imagine it as a component that:

- takes a taxon ID as a parameter (binding),
- has the `StrainsService` as a dependency,
- populates a `<select>` element with the list of strains that match the taxon ID, as retrieved from `StrainsService`, and
- returns some identifying data about the selected strain.

I think the existing `strainPickerDialogCtrl` handles this logic, but it also includes logic for handling the modal, which surely won't be relevant when the picker is included as a field on the genotype edit view:

https://github.com/pombase/canto/blob/fdccac139267802bb7f53c2c670cea6588de6cba/root/static/js/canto-modules.js#L6983-L6989

There's probably a way to separate these concerns, so that the controller handling the strain picker modal delegates to another controller that handles the actual strain picker, but I'm not sure how to implement this yet, since I'm still confused by how the Angular UI Bootstrap modals integrate with the rest of the code. 

### Solution 2

One alternative is to extract only the selector into its own directive, creating a 'dumb' component that just takes a list of strains, displays them in a drop-down list, and returns the strain that's selected.

This means the containing directive (`genotypeEdit`) will need the `StrainsService` as a dependency (unless it can get the strains from the `Curs` service, which it already has injected). @kimrutherford I seem to remember you weren't keen on this dumb component style when I was designing the organism selector, so I'm happy to attempt either solution.

**Comment by kimrutherford** [comment]
Thanks for looking into that.  The selector seems so simple that I think solution 2 is the way to go.
