### ISSUE TITLE
Canto people list

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1705]
Could you provide me with the Canto people list? I have noticed recently that I don't even know most of the new people I am adding. ...and there are lots of them. They aren't on pombelist so I want to send them an invite.

Also might be useful to graph the growth in people added to canto. I'm adding lots of new people. This might be a metric I can use.

**Comment by kimrutherford** [comment]
I've added the list to Dropbox in:
 Dropbox/pombase/curation_tool/queries/canto_emails-2018-12-03.tsv
