### ISSUE TITLE
unknown term

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1710]
https://curation.pombase.org/pombe/curs/c3f91b7bec8a34a1#

<img width="488" alt="screenshot 2018-12-08 at 15 41 23" src="https://user-images.githubusercontent.com/12727506/49687772-cdbb2a80-faff-11e8-8637-951a4f0a643b.png">

**Comment by ValWood** [comment]
I think its a GO issue;

**Comment by kimrutherford** [comment]
All fixed now.
