### ISSUE TITLE
Missing wild type genotype

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1711]
If no strain is added to session for a host species, the Wildtype genotype section is empty:

![missing-wt-genotype-1](https://user-images.githubusercontent.com/90474/49712390-09452880-fca9-11e8-9cf3-3d9907e0f82a.png)

**Comment by jseager7** [comment]
I thought Canto wasn't supposed to let you get to this point &ndash; the 'Gene and host organism list' is supposed to prevent you continuing if you haven't added at least one strain for each organism, but I'm sure I've encountered a few unpredictable bugs that allowed me to continue without adding a strain.

**Comment by kimrutherford** [comment]
> I thought Canto wasn't supposed to let you get to this point

I have been using an old test session I might have got to that point before the checks were implemented.

**Comment by kimrutherford** [comment]
I think this is out of date now so I'll close it.
