### ISSUE TITLE
Same gene name in two different species for pathogen phenotype

### ISSUE THREAD

**Issue by CuzickA** [pombase/canto#1712]
Mock up image of this example (we will also need to check if the same happens for host phenotypes)

![image](https://user-images.githubusercontent.com/11753634/49731580-bc932a80-fc73-11e8-882b-67a9bffd9cb2.png)
- need to add organism names

The same issue for the GO annotation

![image](https://user-images.githubusercontent.com/11753634/49731684-18f64a00-fc74-11e8-9177-b340b63dbb9d.png)

This may need to go onto a separate ticket, but just to record that a meta-genotype could not be made here

![image](https://user-images.githubusercontent.com/11753634/49731767-4d6a0600-fc74-11e8-95e6-eee665e970eb.png)

**Comment by CuzickA** [comment]
Also to note that the pathogen strain information is not being displayed in the pathogen phenotype annotation summary.

**Comment by jseager7** [comment]
The solution to this is to add columns for the organism and the strain to any annotation tables that are missing them. I've opened a new issue for that at #1715.

> This may need to go onto a separate ticket, but just to record that a meta-genotype could not be made here

I think this is due to the server being out of date with the repository, but I'll investigate on my local copy.
