### ISSUE TITLE
Adding background breaks column order

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1716]
Recently we added a 'strain' column to the genotype tables:

![background_before](https://user-images.githubusercontent.com/37659591/49862906-11ab7980-fdf7-11e8-8672-57e444a54f0d.PNG)

But it looks like we didn't consider what happens when the background column is displayed, because it inserts itself before the strain column and gets the wrong header as a result:

![background_after](https://user-images.githubusercontent.com/37659591/49862995-415a8180-fdf7-11e8-9567-7c7813431ec2.PNG)

I presume this is something to do with the fact the header and rows are rendered in separate templates, so the strain `<tr>` element has probably been typed in the wrong place.

**Comment by kimrutherford** [comment]
I've fixed that and also disabled the strain column if Canto isn't in multi organism mode.
