### ISSUE TITLE
Strain synonyms appear as individual entries in strain picker

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1718]
The strain picker on the 'Gene and host organism list' page is showing strains that are synonyms of each other as individual entries, which implies they are somehow distinct. Using _Arabidopsis thaliana_ as an example, [the UniProt page](https://www.uniprot.org/taxonomy/3702) has all of the following strain names as synonymous:

> cv. Columbia ,cv. Col, cv. Col 0, cv. Col-0, cv. Columbia Col-0

But the strain picker in Canto displays most or all of these synonyms as individual entries in the list (see image below). We don't want different users to be able to pick inconsistent strain names, so I suggest we do one of two things:

1. **Filter out all synonyms**, and choose one strain as our 'canonical' choice. The choice of strain is effectively arbitrary, but I suggest we simply choose the first entry in the synonym list from UniProt (e.g. 'cv. Columbia').

2. **Merge the synonyms into one list entry**, which has the advantage of keeping the synonyms visible so users know that they're making the right choice, but has the disadvantage that it would make the drop-down menu very wide.

We also have to find a way to determine which strains are synonyms of each other when harvesting strains from the UniProt API.

- - -

![strain_synonyms](https://user-images.githubusercontent.com/37659591/49863987-605a1300-fdf9-11e8-8e99-2d523cf8170c.png)

**Comment by kimrutherford** [comment]
> The strain picker on the 'Gene and host organism list' page is showing strains that are synonyms of each
> other as individual entries

Oh dear.  Thanks for spotting that.

> Filter out all synonyms, and choose one strain as our 'canonical' choice.

I hope we can pick a single name for each strain and rely on the biologist to know which is which.  Is that possible @CuzickA ?

**Comment by kimrutherford** [comment]
Hi James.  Is this still an issue now you've done #2300?

@jseager7

**Comment by jseager7** [comment]
The issue itself isn't fixed yet because I haven't loaded the new strain lists to our Canto servers (there were problems when I tried to apply the new strain list on the demo server), but I'll close this issue anyway since it was more about the solution for supporting synonyms, which is implemented.
