### ISSUE TITLE
Show name of annotated feature when making annotations

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1719]
Currently, the annotation workflow page (which I think corresponds to `ontology.mhtml` and `OntologyWorkflowCtrl`) doesn't show the name of the feature that's being annotated (e.g. gene, genotype, metagenotype).

In the case of gene annotations, this isn't such a problem, since the name of the gene is visible in the breadcrumb links, but for genotypes and metagenotypes in multi-organism mode &ndash; where the number of variables is much greater than Canto for _pombe_ &ndash; it's more likely the user will be unsure of what they're annotating, particularly for metagenotypes that are subtly different (e.g. differing by only one allele).

I think an easy fix would be just to print the name of the gene / genotype as a title, and possibly include the organism (and strain) for metagenotypes. Here's an mock-up for genotypes:

![genotype_annotation_heading](https://user-images.githubusercontent.com/37659591/49866504-df524a00-fdff-11e8-905f-b52df417837c.PNG)

For metagenotypes this could display something like the following:

**Metagenotype: _F. graminearum_ (PH-1) TRI5&Delta;, URA7&Delta; / _A. thaliana_ (Columbia) RAD51+**

Or if we can trust users to remember the organisms and strains, it could be compressed to:

**Metagenotype: TRI5&Delta; URA7&Delta; / RAD51+**

Though I think the shorter form might be obscure when multi-allele genotypes are involved in the metagenotype.

@kimrutherford @ValWood Do you think this feature would be useful for single organism mode (for PomBase Canto), or should I restrict it to PHI-Canto?

**Comment by kimrutherford** [comment]
> Do you think this feature would be useful for single organism mode (for PomBase Canto)

I think it makes sense to have it for PomBase.

**Comment by jseager7** [comment]
@kimrutherford: turns out there was already code to allow a title to be shown on `ontology.mhtml`, but for some reason the title has never been enabled:

https://github.com/pombase/canto/blob/75ae5c961bf1c4410518418eea288d464cc9b471/lib/Canto/Controller/Curs.pm#L1159-L1160

Here's how it looks once it's turned back on:

![annotation_start_title](https://user-images.githubusercontent.com/37659591/57014624-dfb17d00-6c08-11e9-8059-1175a0e07a84.PNG)

Maybe the reason it was never enabled was because the title doesn't look too good when the feature display name is very long &ndash; and even worse on smaller screens:

![annotation_title_crush](https://user-images.githubusercontent.com/37659591/57014735-45056e00-6c09-11e9-93b5-755b2416a172.PNG)

I thought one solution might be to display the feature names in the subtitle instead:

```perl
  $st->{title} = "Curating $annotation_display_name";
  $st->{sub_title} = "$display_names";
  $st->{show_title} = 1;
```

But the subtitle doesn't seem to display on any page except the front page. Maybe the template doesn't reference it?

Here's a mockup of how it _would_ look if it worked:

![annotation_subtitle](https://user-images.githubusercontent.com/37659591/57015191-58b1d400-6c0b-11e9-8d4c-344c4c5ad982.PNG)

**Comment by jseager7** [comment]
There's also another option, which is to have the feature details as a heading in the body of the page, above the title for the annotation workflow step:

![annotation_body_title](https://user-images.githubusercontent.com/37659591/57015874-fa86f000-6c0e-11e9-97fe-780c17e19ea7.PNG)

I feel like I prefer this option, but I'd like to hear what everyone else thinks.

@ValWood @CuzickA Do you have any particular preference about where the feature details should be shown? By feature, I mean genotype, gene, metagenotype, etc.

**Comment by kimrutherford** [comment]
> Maybe the reason it was never enabled was because the title doesn't look too good when the feature
> display name is very long

Yep, I think that's the reason.

> There's also another option, which is to have the feature details as a heading in the body of the page,
> above the title for the annotation workflow step:

And another option is to change "Genotype details" in the breadcrumbs trail to show the full genotype (or meta-genotype) name.  I'm not sure why we don't do that.  Maybe it's too long and ugly?

**Comment by jseager7** [comment]
> And another option is to change "Genotype details" in the breadcrumbs trail to show the full genotype (or meta-genotype) name. I'm not sure why we don't do that. Maybe it's too long and ugly?

I've just tested this, and in the case of very long breadcrumb links, the text doesn't wrap, it just pushes the rest of the header to the side:

![long_breadcrumb](https://user-images.githubusercontent.com/37659591/57016087-2d7db380-6c10-11e9-9f43-a1a168c5648e.PNG)

**Comment by ValWood** [comment]
> I feel like I prefer this option, but I'd like to hear what everyone else thinks.

I like your suggestion here.

**Comment by jseager7** [comment]
@kimrutherford I've been working on implementing this, but unfortunately the title doesn't work as expected on gene annotation pages because the `feature_type` isn't set (I was expecting it to return 'gene', but it looks like this doesn't happen). Here's the error message:

`[error] Couldn't render component "curs/modules/ontology.mhtml" - error was "Can't locate object method "feature_type" via package "Canto::Curs::GeneProxy" at /canto/root/curs/modules/ontology.mhtml line 10.`

```
Stack:
  [/canto/root/curs/modules/ontology.mhtml:10]
  [/canto/root/curs/modules/autohandler:6]
  [/canto/root/curs/autohandler:37]
  [/canto/root/curs/page_template.mhtml:35]"
```

I can get around the error by adding a check to the Mason template: check if the `feature_type` method exists on the `$feature` object before displaying the heading:

```
% if ($feature->can('feature_type')) {
<div class="curs-annotate-feature-title">
  Annotating <% $feature->feature_type %> &ndash; <% $feature->display_name() %>
</div>
% }
```

But it would probably be better have the `feature_type` actually set to 'gene', so all the annotation pages can be consistent in showing the heading. Is this easy to do?

**Comment by kimrutherford** [comment]
> Annotating <% $feature->feature_type %> &ndash; <% $feature->display_name() %>

Hi James.  Does it work if you change `$feature->feature_type` to `$feature_type`?

**Comment by jseager7** [comment]
> Does it work if you change $feature->feature_type to $feature_type?

No, but it did give me an error message that pointed to the correct solution. I think the code should have been this:

```
<div class="curs-annotate-feature-title">
  Annotating <% $feature_type %> &ndash; <% $feature->display_name() %>
</div>
```

Not sure how I didn't notice that in the first place (considering `$feature_type` is already in the `%args`, but it seems to work in all cases now. Thanks. I'll open a pull request for this later.
