### ISSUE TITLE
Editing metagenotype annotation fails with error

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1721]
When I attempt to edit an existing metagenotype annotation, I get an error in a toaster saying the following:

> No such annotation field type: host_genotype

This bug occurs when editing any or all of the fields in the annotation. In some cases (possibly depending on the field being edited), it says 'pathogen_genotype' instead of 'host_genotype'.

Surprisingly, this bug doesn't occur when **copying and editing** the annotation &ndash; this works regardless of which field is being edited.

**Comment by jseager7** [comment]
Note: this bug isn't specific to my development environment; it occurs on the servers too.

**Comment by kimrutherford** [comment]
This should fixed now.  Please re-open if you see the problem again.
