### ISSUE TITLE
New triage classifiers

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1724]
Assessing how many priority browser sets we have to host

It would be useful to know how many browser data sets we have as this will help me to write justification for @Antonialock since antonia does all these.

For one, I think most of the 'browser only' datasets I have shuck away in

"sequence feature or region"

I'd like to re-triage these, with a few new "subset" labels

i) Browser datasets, to host
ii) Browser datasets, hosted
iii) DNA replication related
iv) DNA recombination related
(there seem to be many of these of various scales and types, first I would like to collect them all together, then we can ask the community which ones they would like us to host)
v) mitochondrial sequence related
vi) 3D genome organization (good to collect these in one place for future)
(this is probably worth mentioning in the grant since it's new and cool)
vii) transposon related
viii) mating-type related

(I know it's a lot more labels but they will be useful, and we can streamline this later when the admin tasks get done which is likely to be years away)

**Comment by ValWood** [comment]
Ideally do this fairly soon, if it isn't tricky for some reason.

**Comment by kimrutherford** [comment]
It's quick to add new ones.  Will it be OK to have so many triage categories?

**Comment by ValWood** [comment]
Well for me it will, and I do the triage so I think it is fine. Otherwise we have all these papers in a big lump and it's difficult to know what is in there. We might think of better ways to do this longer term (but it will probably be a few years before this percolated to the top of the list. This will work fine in the medium term.

**Comment by kimrutherford** [comment]
OK.  My worry is that you need to scroll the page up and down to get to all the options.  Perhaps we should put the common ones at the top later on.

I'll go ahead and add the new categories.

**Comment by ValWood** [comment]
I'm OK with that but if it's cumbersome I can suggest changes. Most frequently used at the top sounds sensible though!

**Comment by ValWood** [comment]
I just triaged and I already need to scroll on my default screen, it isn't a problem because most of the  commonly used options are visible.  If it really bothered me I guess I would have gone to full screen. It also only takes about one minute a week for this step so it doesn't really matter so much, it's not like having a cumbersome step in the curation workflow. The part of the triage which takes the time is tracking down  the e-mails of all the new  lab heads and entering them into Canto. But that's a good thing. Lots of people working on pombe and metazoa....

**Comment by kimrutherford** [comment]
I've added the new categories.  Let me know if they need any tweaking.

**Comment by ValWood** [comment]
This is working (I triaged a few). However the  admin summary page needs to be updated to match (these  could all be 'indented' under "sequence feature".
Once that is there I'll whizz through and re-triage these.
