### ISSUE TITLE
RNA binding IPI expects protein in "with"field

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1729]
If I use RNA-binding and IPI a protein is expected. This would be confusing for users. I'm going to use IDA instead so not urgent

**Comment by ValWood** [comment]
Then I select  "binds RNA gene or type"

I want to be able to select a SO term, but the only options are (protein coding) genes.

**Comment by mah11** [comment]
> If I use RNA binding and IPI a protein is expected.

The "with" field doesn't specify a protein (in Canto or in GO), but it does have to have a gene ID (not a SO term/ID).

> Then I select "binds RNA gene or type"
> I want to be able to select a SO term, but the only options are (protein coding) genes.

For genes, the pulldowns for extensions and the "with" field for IPI evidence will show all genes you have added for the session, protein-coding or ncRNA.

To get RNA binding extensions to offer the text-box option for a SO term, add the most general applicable SO term to the extension config file. It'll handle "TranscriptID|SO:nnn" just fine.

**Comment by ValWood** [comment]
Yes Antonia pointed this out.

I only encountered this issue because the RNA is an artificial construct with a poly -A tail and a PRE or ARE element, not a real *existing* RNA.

 So the only action here is to update the confic file to offer SO terms too.

**Comment by mah11** [comment]
done
