### ISSUE TITLE
display UniProt accession numbers not identifiers

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1736]
I notice that we are displaying  the "identifier" rather than the "gene name".
(sometimes these will be the same)

For example
http://canto.phi-base.org/curs/84fc0e5867452a4a

I don't think we should use the identifiers at all, they aren't stable. The accession numbers are.

We should use "gene symbols" if one is assigned (UniProt calls this 'Name'), and accession numbers if not.

"Four distinct tokens exist: ‘Name’, ‘Synonyms’, ‘Ordered locus names’ and ‘ORF names’."

For example here:
https://www.uniprot.org/uniprot/F9XHX3
we should use F9XHX3, the accession number.
It has a gene name  "MYCGRDRAFT_105487" but this is of class "orf name", so we would not display that in preference to the accession.

and here:
http://canto.phi-base.org/curs/84fc0e5867452a4a/feature/gene/view/6

Identifier | F9XMT4
Name | F9XMT4_ZYMTI

I think the labelling is incorrect. F9XMT4 is the accession,
https://www.uniprot.org/help/accession_numbers

 and F9XMT4_ZYMTI is the identifier. It seems that this is now called 'entry name'
https://www.uniprot.org/help/entry_name

https://www.uniprot.org/help/difference_accession_entryname

UniProt identifiers are a bit legacy,  I don't really see the point of them because they aren't stable. My rule of thumb is to ignore the "identifier/entry name and always use the accession.

**Comment by ValWood** [comment]
I notice these genes are named in this paper
http://canto.phi-base.org/curs/84fc0e5867452a4a
we should send these to uniprot.

The code should work  so that if a gene name ('Name') is added  it can be pulled in to the session via the accession number in some way ...

We also need a way for authors to supply published gene names .....

**Comment by kimrutherford** [comment]
> I don't think we should use the identifiers at all, they aren't stable

I don't know how the identifier ended up as the gene name in Canto but when I try it now on my machine it's fixed.  PHI-Canto has got the wrong names cached for your genes.

> we should use F9XHX3, the accession number.

> It has a gene name "MYCGRDRAFT_105487" but this is of class "orf name", so we
> would not display that in preference to the accession.

So the name should be "F9XHX3" in the interface for that gene?  Is the action to just ignore the "orf" names?

In #1543 you said:
> primary gene name if there is one and ORF name if there isn't

which is how it works at the moment.

**Comment by jseager7** [comment]
@kimrutherford Is there any easy way to clear the gene name cache? I've noticed that the caching is preventing the fix in #1543 from being applied properly.

**Comment by ValWood** [comment]
I think this is all OK. Closing. I will open a new ticket if there is a problem.
(I think part of this was my confusion).
