### ISSUE TITLE
Run JS Beautify

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1737]
This isn't urgent but there's a bit of inconsistency in coding styles.

https://www.npmjs.com/package/js-beautify

There will be lots of changes so it needs to be done at a point where there aren't major merges pending.  Once that is done keeping the formatting in good shape should be easy.  Some editors have plugins to help: https://github.com/HookyQR/VSCodeBeautify

---

"I usually work alone, but it’s like working as a team when I come back to a program after 3 years." -  Donald Knuth

**Comment by jseager7** [comment]
Also, I should be fine for this to run after I've finished issue #1715, since I don't think I've got any other major work in progress.

**Comment by kimrutherford** [comment]
I've run JS Beautify and checked it in.  The config is in .jsbeautifyrc if you'd like to play with the settings.

> --max-preserve-newlines 2

I've set this to 3 for now because I like to have an extra newline between the different controllers.  It helps me see when one ends and the next starts.

> wrap_line_length

I've left this unset because it think it would mangle some of the formatting.  I'll experiment when I have time.

Let me know if you spot any problems.  I plan to re-run JS Beautify before each check-in.
