### ISSUE TITLE
Make GO qualifiers available in PHI Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1740]
There are 3 qualifiers available for GO annotation. NOT contributes_to and colocalizes_with

These are not currently available

**Comment by kimrutherford** [comment]
Are they available in PomBase Canto?  How do you add them? - I've forgotten.

**Comment by mah11** [comment]
I'd forgotten too, so I looked. We're kludging it with a mini-ontology, PBHQ (self-described as "A fake ontology used for configuring GO qualifiers in Canto"), so we can put its IDs in extension config file entries. Example from our GO_MF_A_E_config:

    GO:0003674	is_a	has_qualifier	PBHQ:002|PBHQ:004	qualifier		*	admin


The mini-ontology itself is pombe-embl/supporting_files/mini-ontologies/has_qualifier_range.obo

**Comment by ValWood** [comment]
Thanks , I had forgotten too!

**Comment by kimrutherford** [comment]
@jseager7 for these extra qualifiers to be available you'll need to load this OBO file into Canto when you load the main ontologies:
  https://curation.pombase.org/dumps/latest_build/pombe-embl/mini-ontologies/has_qualifier_range.obo

**Comment by jseager7** [comment]
OK, I'll test loading that on the demo server first. How can I can test that the qualifiers are available in the user interface?

**Comment by ValWood** [comment]
In the extensions menu for GO there is a "qualifier" option. They are under this.
v

**Comment by jseager7** [comment]
I've tested this on the demo server, and I was able to add the NOT qualifier on the GO term for 'chitinase activity' (GO:0004568). I didn't see 'colocalizes_with' when picking a qualifier term in this case; not sure if that's expected or not. 

I'll do the ontology loading on the live server now, and if that works I'll close this issue.

**Comment by ValWood** [comment]
That would be correct. 
colocalizes_with will only appear with MF
contributes_to will only appear with MF
NOT will appear with all 3

v

**Comment by mah11** [comment]
corrected previous comment

**Comment by jseager7** [comment]
I've tested this on the live server now, and adding the NOT qualifier works there too. Closing now.
