### ISSUE TITLE
Canto won't let you use IPI with Chitin binding

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1741]
Are there any config changes we can make to allow IPI for non-protein substrates?

**Comment by mah11** [comment]
No, because GO requires a gene product ID in the 'with' column for IPI. (It can be any gene product, so for ncRNAs, use the gene ID as proxy, same as we do for proteins.)

**Comment by ValWood** [comment]
OK this is for chitin fragments so it isn't really a gene product. We'll use IDA...

**Comment by mah11** [comment]
Fragments have nothing to do with it; chitin is never a gene product.

**Comment by ValWood** [comment]
Of course. 

I didn't remember that it wasn't possible not to use anything in the with filed with terms where the object being bound was specified in the term name... seems sub optimal

**Comment by mah11** [comment]
OK, that last comment kinda does my head in, but I'm pretty sure it's orthogonal to the reason IPI doesn't work for chitin binding.

**Comment by ValWood** [comment]
OK revised comment
I did not know that you could only use IPI with a gene product...

**Comment by mah11** [comment]
really? it's been that way forever ...
