### ISSUE TITLE
FlyBase to supply  complete gene list

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1742]
Complete gene list is required to populate Canto independently of gene lists and  alleles attached to PubMed IDs

Initially a flat file.
(Eventually connect to Chado, but don't require a ticket for this until afterwards)

**Comment by gm119** [comment]
Would the following file do for now (this is from the latest public release, so not completely current compared to our production database and is not ALL genes (see **note** below), but I think we said that would be OK for initial testing).

Location: ftp://ftp.flybase.net/releases/current/precomputed_files/synonyms/fb_synonym_fb_2018_06.tsv.gz

(fb_2018_06 part of file name will change with each release, always of format fb_nnnn_dd)

Doc describing format:
https://wiki.flybase.org/wiki/FlyBase:Downloads_Overview#FlyBase_Synonyms_.28fb_synonym_.2A.tsv.29

and pasted below:

FlyBase Synonyms (fb_synonym_*.tsv)

The file reports current symbols and synonyms for the following objects in FlyBase: genes (FBgn), alleles (FBal), balancers (FBba), aberrations (FBab), transgenic constructs (FBtp), insertions (FBti), transcripts (FBtr), and proteins (FBpp).

The file includes:

    nuclear genes located to the sequence
    mitochondrial genes
    genes not located to the sequence
    genes from drosophilid species and genes from non-drosophilids that have been introduced into transgenic flies

File format:
Column heading 	Content Description
primary_FBid 	Primary FlyBase identifier for the object.
organism_abbreviation 	Abbreviation (from the Species Abbreviations list) indicating the species of origin.
current_symbol 	Current symbol used in FlyBase for the object.
current_fullname 	Current full name used in FlyBase for the object.
fullname_synonym(s) 	Non-current full name(s) associated with the object (comma separated values).
symbol_synonym(s) 	Non-current symbol(s) associated with the object (comma separated values).


**note**: this file doesn't have 'genes from drosophilid species and genes from non-drosophilids that have been introduced into transgenic flies' so is not a complete list - if thats not OK for initial testing let me know and can make another.

**note 2**: - you'll need to grep for lines beginning with 'FBgn' to limit this to just genes

**Comment by kimrutherford** [comment]
Thanks Gillian.  That looks great.

> if thats not OK for initial testing let me know and can make another.

I think it will be fine.  Hopefully we can move to querying Chado directly before you start using Canto in production.

**Comment by kimrutherford** [comment]
> Location: ftp://ftp.flybase.net/releases/current/precomputed_files/synonyms/fb_synonym_fb_2018_06.tsv.gz

Thanks Gillian.  That had most of what we needed.

Canto currently requires a taxon ID for each organism.  So I combined the fb_synonym file with this table: https://wiki.flybase.org/wiki/FlyBase:Abbreviations

There are a few typos.  Three taxon IDs appear twice in the table:

137079
30030
30031

And two taxon ID entries appear mangled: "6085 taxon: 6085" and "41714 taxon: 41714".

Apart from that I've been able to load all the FlyBase genes into a local Canto instance for testing.  Progress!

**Comment by gm119** [comment]
Hi Kim, ah - this file is quite out of date (its on our to-do list to make it up to date by pulling directly from chado). I guess it doesn't matter for testing, but I will double-check that the errors you found are fixed in the db

**Comment by kimrutherford** [comment]
> I guess it doesn't matter for testing, but I will double-check that the errors you found are fixed in the db

Yep, it will be fine for testing.  All of the melanogaster genes loaded successfully which I assume covers a lot of publications.

I now have a Canto instance with 250,000 genes and 623 organisms loaded.  It's a good test!

**Comment by kimrutherford** [comment]
I think we can close this in favour of: #1800
