### ISSUE TITLE
Allow searching on allele synonyms

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1744]
PomBase don't handle these in Chado yet, we need to do that
https://github.com/pombase/pombase-chado/issues/400

**Comment by kimrutherford** [comment]
I'd like to talk about this in the next meeting.  Is this needed for FlyBase-Canto or for PomBase?

For FlyBase we pre-load all the alleles so would putting this list in alphabetical order be enough?:
![Screenshot from 2019-03-22 18-41-23](https://user-images.githubusercontent.com/90474/54802968-6736d280-4cd2-11e9-8f24-a5e12aeda525.png)

**Comment by vmt25** [comment]
"For FlyBase we pre-load all the alleles so would putting this list in alphabetical order be enough?" - this  in combination with an allele description would probably do

**Comment by vmt25** [comment]
For FlyBase's purposes this ticket is sorted

**Comment by kimrutherford** [comment]
I've implemented this now.  I'll update the main PomBase Canto with these changes over night (UK time).

![allele-edit-existing-synonyms-3](https://user-images.githubusercontent.com/90474/58798296-5d2c3b00-8656-11e9-86ec-40356bad499a.png)

**Comment by kimrutherford** [comment]
That should work in the main Canto now.
