### ISSUE TITLE
FB supply ontologies used  in Obo format  

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1745]
Ontologies  obo format  for Kim to check the parser

 Ability to load multiple separate ontologies (I) anatomy  and ii)  basic descriptor (i.e bigger body , increased cell number) 

Anatomy 
Class
GO for componet

**Comment by gm119** [comment]
The ontologies used in the current version of FlyBase are available from the ftp site in this folder:

ftp://ftp.flybase.net/releases/current/precomputed_files/ontologies/

The ones we use for phenotype curation are:

i. anatomy

**- fly_anatomy.obo**
ftp://ftp.flybase.net/releases/current/precomputed_files/ontologies/fly_anatomy.obo.gz

**- go-basic.obo**
ftp://ftp.flybase.net/releases/current/precomputed_files/ontologies/go-basic.obo.gz
     (use cellular component branch only for phenotype curation)

ii. basic descriptor (class)

**- flybase_controlled_vocabulary.obo**
ftp://ftp.flybase.net/releases/current/precomputed_files/ontologies/flybase_controlled_vocabulary.obo.gz
   (use children of 'phenotypic class' only for phenotype curation)

iii. use as 'qualifiers' (what will go in extensions in Canto)

**- fly_development.obo**
ftp://ftp.flybase.net/releases/current/precomputed_files/ontologies/fly_development.obo.gz

 **- flybase_controlled_vocabulary.obo**
(as above)
(use children of 'phenotype qualifier ' only for phenotype curation)

**Comment by kimrutherford** [comment]
Thanks.  I'll test loading those OBO files and see if any warnings are serious.

**Comment by gm119** [comment]
as discussed on vc, here is the link to get the disease ontology we use (not needed for phenotype curation in Canto, but we might want to use it in the future with Canto to capture disease model info)

ftp://ftp.flybase.org/releases/FB2018_06/precomputed_files/ontologies/doid.obo.gz

**Comment by kimrutherford** [comment]
> I'll test loading those OBO files and see if any warnings are serious.

Thanks Gillian.  I had no problem loading all those OBO files into Canto.

There were some warnings from the loading code, but I don't think they'll be a problem.  The ones I noticed were for terms from external ontologies.  eg.
```
term without a name tag ignored:
[Term]
id: CHEBI:16199
namespace: phipo
relationship: is_a CHEBI:29347
relationship: is_a CHEBI:64708
```

**Comment by kimrutherford** [comment]
I think we can close this issue.
