### ISSUE TITLE
FB to provide examples of non-gene genotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1746]
Canto needs to handle chromosome aberrations trans genes etc.
These are mostly classic chromosomal aberrations (deletions/deficiencies, duplications, inversions, etc, which may affect none or several genes) (has an FBAB ID)

We could 'fudge this' initially and load 'dummy' genes (Canto requires a gene to attach a genotype to).
We think it would be more useful in the longer term  for other users if this requirement could be relaxed so that 
genotypes for aberrations  can be loaded without a 'gene object' dependency

**Comment by vmt25** [comment]
Here goes a range of genotype variations and some context - https://docs.google.com/spreadsheets/d/16fjZJzYXsrxgr-Oz6iMgtyz_S3PnG89UHcR4gU-rZ5Q/edit#gid=1866375701

There are a couple of examples with aberrations:
wg[1]/Df(2L)BSC226
Df(2L)BSC226/Df(2L)BSC226
Df(2L)BSC226/,Df(2L)B231
