### ISSUE TITLE
Handle sessions with no host genes in pathogen/host mode

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1747]
I accidentally added only pathogen genes to my session and then was confused by the appearance of the host genotype management page.  We should handle this better.

![phi-mode-no-path-1](https://user-images.githubusercontent.com/90474/51598633-d4dcb180-1f62-11e9-81b6-6a408db4a646.png)

**Comment by jseager7** [comment]
I guess we should handle this by denying access to the relevant genotype management pages until there are actually genes / genotypes available to use &ndash; this was also our plan with regards to the meta-genotype management link, which already has an issue here: #1678

**Comment by jseager7** [comment]
It looks like the Mason template at `front_gene_section.mhtml` has an array variable `@gene_hashes_by_organism` that we could potentially use to get the number of genes added for pathogens and hosts.

https://github.com/pombase/canto/blob/461b95fa0c0152a7f6c56a8963e4c6f7311eecae/root/curs/front_gene_section.mhtml#L100-L122

Maybe we could pre-process that list, store the gene counts for pathogens and hosts, and use those counts to disable the link and show a message instead?

**Comment by kimrutherford** [comment]
Unless I'm misunderstanding my own issue, I think we can close this.
