### ISSUE TITLE
distinguish between HTP and LTP annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1755]
External files in svn repository
- [ ]  @mah11  will set up and migrate small scale into the new small-scale directory
the PHAF directory will be split into 2 (Low priority)

- [x]  Kim will set up the code to add a flag to the script that loads 
PHAF/ modifications (HTP)/expression (ALL HTP)/  
to flag as HTP

i.e ALL external files will be loaded as HTP unless otherwise stated

-  [x] for BioGRID data we use their flag
(see https://github.com/pombase/website/issues/1123)
everything else will be LTP

Everything else LTP

EXCEPT for GO IEA, ISS, ISO, ISM, IC, NAS, TAS, IBA which will be classed as NON-EXPERIMENTAL

orthologs, taxon distribution NON-EXPERIMENTAL

and for HDA, HGI, HEP, HMP, HTP (GO HTP evidence codes)

Things to consider
~1. We will only count annotations done by PomBase, from publications in these counts~
2. Keep in mind the possibility that some PHAFS may have a HTP and LTP from the same paper (small number may be too small to worry about).

So individual annotations will flag as HTP or LTP or NON-EXPERIMENTAL

**Comment by kimrutherford** [comment]
The "Throughput" column in the BioGRID files sometimes contains the string:
```
High Throughput|Low Throughput
```

Any idea what that means?  I thought that each interaction from BioGRID is from a single experiment, but maybe not?  There's some documentation here: https://wiki.thebiogrid.org/doku.php/curation_guide:htp_ltp_interaction_tags

For an example click on "details" for NSE3/SPCC645.04 here:
https://thebiogrid.org/278084/summary/schizosaccharomyces-pombe/smc5.html

**Comment by mah11** [comment]
> Any idea what "High Throughput|Low Throughput" means?

Not a clue; it makes no sense, given that each line is supposed to be one interaction annotation. You're gonna have to ask them :P

**Comment by ValWood** [comment]
I'll shoot them an e-mail.

**Comment by ValWood** [comment]
How many?

**Comment by ValWood** [comment]
Actually,  had another thought. The likely reason our annotation stats are low for  genetic and physical interactions  that most  are  from Biogrid (we will only include the ones in Canto in our stats, although I am still surprised these are so low).

I think we can include these data in the LTP /HTP graphs because the purpose of this is to assess the ratio of LTP/HTP for pombe publications.

However, the totals will not be included in our "in-house annotation number" graph.

**Comment by kimrutherford** [comment]
> How many?

Only 25 out of about 75000

**Comment by ValWood** [comment]
Gosh I didn't think there were so many interactions from bioGRID?

**Comment by kimrutherford** [comment]
> Only 25 out of about 75000

> Gosh I didn't think there were so many interactions from bioGRID?

That was from looking at the raw file from BioGrid.  We actually loaded about 67487 from BioGRID.

In Chado we have 1973 interaction from PomBase directly.  There are also 2101 interactions in Chado that are from BioGRID but have the source as "POMBASE".  That's a mistake I think?  We don't want to load interactions that BioGRID got from us do we?  Also how do they have more interactions from us than you have curated?  I'll make a separate issue about it.

**Comment by kimrutherford** [comment]
> There are also 2101 interactions in Chado that are from BioGRID but have the source as "POMBASE".

Allegedly I sorted this out over 5 years ago: pombase/pombase-chado/issues/226 but I can't see anything in the code that filters out the PomBase interactions.

**Comment by ValWood** [comment]
That's weird because if you didn't filter them we would accumulate duplicates, and I'm sure we don't....

**Comment by kimrutherford** [comment]
> That's weird because if you didn't filter them we would accumulate duplicates, and I'm sure we don't....

Yep, it's odd.  I'll check for duplicates.

**Comment by kimrutherford** [comment]
I've updated the loading code to set the following flags:
  - BioGRID - sets high or low throughput in Chado based on the "Throughput" column
  - modifications - HTP
  - PHAF - all HTP for now
  - qualitative / quantitative data from external files - HTP
  - annotations Canto - LTP
  - contig file phenotype and GO annotations - LTP

Still to do:
  - [ ] need to check which other (ie. non-GO/FYPO) annotation types from the contig files should be LTP and which should be non-experimental
  - [ ] add the appropriate flags to other GO annotations (eg. from GOA) based on the evidence codes
  - [ ] orthologs, taxon distribution - flag as NON-EXPERIMENTAL

When the load successfully finishes I'll check to see which annotations don't have a flag set.

**Comment by ValWood** [comment]
great progress!

**Comment by kimrutherford** [comment]
> Everything else LTP
> EXCEPT for GO IEA, ISS, ISO, ISM, IC, NAS, TAS, IBA which will be classed as NON-EXPERIMENTAL
> ...
> and for HDA, HGI, HEP, HMP, HTP (GO HTP evidence codes)

Just to check: do those rules about GO evidence codes apply to all GO annotation including from contig files and Canto?

**Comment by kimrutherford** [comment]
Also, are all modification and gene expression annotation from the contig files low throughput?

**Comment by kimrutherford** [comment]
> do those rules about GO evidence codes apply to all GO annotation including from contig files and Canto?

Now I think about it, you don't use those evidence codes in Canto so that's not a problem.  What about the contig files?

**Comment by ValWood** [comment]
>Just to check: do those rules about GO evidence codes apply to all GO annotation including from contig files and Canto?

yep

>Also, are all modification and gene expression annotation from the contig files low throughput?
yep

**Comment by kimrutherford** [comment]
> Everything else LTP
> EXCEPT for GO IEA, ISS, ISO, ISM, IC, NAS, TAS, IBA which will be classed as NON-EXPERIMENTAL
> ...
> and for HDA, HGI, HEP, HMP, HTP (GO HTP evidence codes)

If I ignore those HTP evidence codes these are what's left from the contig files.  Are IKR or IEP non-experimental?  

 -   EXP
 -   IDA
 -   IEP
 -   IGI
 -   IKR
 -   IMP
 -   IPI

**Comment by ValWood** [comment]
All experimental except IKR, and I think we only use this once!

**Comment by kimrutherford** [comment]
> need to check which other (ie. non-GO/FYPO) annotation types from the contig files should be LTP and
> which should be non-experimental

That's done now.

> add the appropriate flags to other GO annotations (eg. from GOA) based on the evidence codes

That's done too (for tonight's load).

>orthologs, taxon distribution - flag as NON-EXPERIMENTAL

Those are done.

Tomorrow I'll check Chado to see which annotations still aren't labelled HTP, LTP or non-experiment.  I think we have most of them done now.

**Comment by kimrutherford** [comment]
It's all looking good.  Here's a breakdown of the throughput types and annotations types.  Please let me know if there's anything that looks weird: 

 annotation_throughput_type |           annotation_type            | count 
----------------------------|--------------------------------------|-------
 high throughput            | biological_process                   |    17
 high throughput            | cellular_component                   |  6882
 high throughput            | fission_yeast_phenotype              | 29938
 high throughput            | gene_ex                              | 34433
 high throughput            | interacts_genetically                | 96841
 high throughput            | interacts_physically                 |  6898
 high throughput            | molecular_function                   |  1552
 high throughput            | PSI-MOD                              | 32348
 low throughput             | biological_process                   |  5630
 low throughput             | cellular_component                   |  5374
 low throughput             | fission_yeast_phenotype              | 52081
 low throughput             | interacts_genetically                | 10972
 low throughput             | interacts_physically                 |  9231
 low throughput             | molecular_function                   |  5250
 low throughput             | PSI-MOD                              |  1861
 non-experimental           | biological_process                   |  5163
 non-experimental           | cat_act                              |    29
 non-experimental           | cellular_component                   |  3593
 non-experimental           | complementation                      |   422
 non-experimental           | disease_ontology                     |  2414
 non-experimental           | EC numbers                           |   835
 non-experimental           | external_link                        |     6
 non-experimental           | ex_tools                             |    21
 non-experimental           | gene_ex                              |  3232
 non-experimental           | genome_org                           |   237
 non-experimental           | m_f_g                                |    90
 non-experimental           | misc                                 |   398
 non-experimental           | molecular_function                   |  5132
 non-experimental           | name_description                     |   951
 non-experimental           | pathway                              |    30
 non-experimental           | PomBase family or domain             |  1861
 non-experimental           | PomBase gene characterisation status |  5138
 non-experimental           | PomBase gene products                |  6610
 non-experimental           | PSI-MOD                              |  1095
 non-experimental           | sequence                             |   953
 non-experimental           | species_dist                         | 24912
 non-experimental           | subunit_composition                  |   183
 non-experimental           | warning                              |  1724
 \-                           | interacts_genetically                |     4
 \-                           | interacts_physically                 |    22
 \-                           | species_dist                         |   153

**Comment by ValWood** [comment]
non-experimental | biological_process | 5163
non-experimental | cat_act | 29
non-experimental | cellular_component | 3593


should be experiemental

**Comment by kimrutherford** [comment]
> should be experiemental

I'll fix cat_act but I think the GO terms are non-experimental because of:

> EXCEPT for GO IEA, ISS, ISO, ISM, IC, NAS, TAS, IBA which will be classed as NON-EXPERIMENTAL

Is that not correct?

**Comment by ValWood** [comment]
Yes, ignore me

**Comment by kimrutherford** [comment]
> non-experimental | cat_act | 29

The cat_act annotations will be flagged as LTP from Thursday.

**Comment by kimrutherford** [comment]
I'll close this issue as I think it's more or less done.  I've opened a separate issue for the remaining task: pombase/curation#2343
