### ISSUE TITLE
Annotation warnings after merging ontology namespaces

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1761]
Recently it was decided that the PHIPO ontology should merge two of its 'namespaces' branches (_host_phenotype_ and _pathogen_phenotype_) into one new branch (_single_organism_phenotype_) in order to reduce redundancy.

Unfortunately, Canto now seems to think that these terms from the new namespace still have a type of `pathogen_phenotype`, and displays a warning any time a _single_organism_phenotype_ is used to annotate a _host_phenotype_:

<img width="500" alt="wrong-phenotype-ns" src="https://user-images.githubusercontent.com/37659591/52278074-10598180-294e-11e9-9eda-7062c7fc3fc4.png">

The cause for this can be seen in the function `$scope.render_term_item` in the `termNameComplete` controller, in particular with the following variables:

- `item.annotation_namespace` &rarr; `"single_organism_phenotype"` (correct),
- `item.annotation_type_name` &rarr; `"pathogen_phenotype"` (incorrect).

I think this is due to the `name` of the annotation type not matching the `namespace` of the annotation type in canto_deploy.yaml:

```yaml
  - name: pathogen_phenotype
    category: ontology
    namespace: 'single_organism_phenotype'
    ...

  - name: host_phenotype
    category: ontology
    namespace: 'single_organism_phenotype'
    ...
```

When the PHIPO branches were merged, the _pathogen_phenotype_ branch was renamed to _single_organism_phenotype_, so I suspect that means all of the terms that are now in the _single_organism_phenotype_ namespace still have an `annotation_type_name` of "pathogen_phenotype".

I'm not sure how to fix this, besides preventing Canto from warning about using terms from certain namespace combinations (i.e. it should view _host_phenotype_ and _pathogen_phenotype_ as equivalent for annotation purposes.

Assuming the `annotation_type_name` _is_ derived from canto_deploy.yaml, it can't be renamed without breaking the term lookup process &ndash; Canto still expects to find annotation types named 'host phenotype' and 'pathogen phenotype'; if we change those names, I think it will change all of the text substitutions on the annotation creation page to refer to 'single organism phenotypes', when isn't ideal either.

**Comment by jseager7** [comment]
Here's the ontology file I loaded to remove the old host and pathogen namespace terms:

```
format-version: 1.2
data-version: releases/2019-01-14
ontology: phipo

[Term]
id: PHIPO:9999999
name: destroy pathogen phenotypes
namespace: pathogen_phenotype
is_obsolete: true

[Term]
id: PHIPO:9999998
name: destroy host phenotypes
namespace: host_phenotype
is_obsolete: true
```

**Comment by kimrutherford** [comment]
Hi @jseager7.

I tried loading that OBO fragment to get rid of the host and pathogen namespaces in my local PHI-Canto database.  It didn't work initially.  I then realised that the PHIPO OBO file I was loading from GitHub (https://github.com/PHI-base/phipo/blob/master/phipo.obo) still had some host_pathogen terms in it.  When I removed those everything worked as expected.

Could you check to see if you've got the same problem?

**Comment by jseager7** [comment]
> When I removed those everything worked as expected.

Just to clarify, does removing the host terms stop Canto complaining about how you're browsing the wrong terms when adding a host annotation? @CuzickA requested that we keep the `host_phenotype` terms in the ontology, so that the ID range can be re-used in future. I'm aware that this is not best practice, and ideally these terms should be obsoleted rather than deleted or re-purposed.

If obsoleting all the `host_phenotype` terms would fix the problem, then we can consider that. If deleting from the database is the only fix, then I can try that too.

Another option I just thought of is keeping the host terms in the ontology, but removing the 'host phenotype' namespace from them. The terms are already categorised in Protege by the relation `subClassOf 'host phenotype'` (the `hasOBONamespace` property has no semantic meaning in OWL anyway), so it shouldn't affect the ontology structure. @CuzickA will be able to keep the terms in the ontology this way so they can re-purposed later. Would this work?

**Comment by ValWood** [comment]
Yes. It's bad practice (prohibited) to reuse IDs and we would not be able to do this after any public release. 

James option of keeping the terms is OK, becasue I'm assuming these were not logically defined yet,=. We haven't really changed the text definition, so changing the parentage in this situation is OK (best practice). You can change the wording of a text definition without changing it's meaning.

General rules.
Keep the term if the definition *meaning* did not change.
Obsolete the term if you minted a definition with a different meaning.

**Comment by kimrutherford** [comment]
> Just to clarify, does removing the host terms stop Canto complaining about how you're browsing the
> wrong terms when adding a host annotation?

Yep, that fixed that problem.  I had a different problem because I still had disease_formation_phenotype terms in the database.  I added another dodgy term to fix the problem:

**Comment by kimrutherford** [comment]
> I added another dodgy term to fix the problem:

Sorry, I hit comment too soon:

[Term]
id: PHIPO:9999997
name: destroy disease formation phenotype                                                                                                                                                    
namespace: disease_formation_phenotype                                                                                                                                                        is_obsolete: true

**Comment by kimrutherford** [comment]
> Yep, that fixed that problem.

Now I've reloaded and fixed my canto_deploy.yaml config, I'm seeing the same warning that you saw.  Drat.

I've configured my host and pathogen phenotype annotation_types like:

```
  - name: host_phenotype
    category: ontology
    namespace: 'single_organism_phenotype'
    ...
  - name: pathogen_phenotype
    category: ontology
    namespace: 'single_organism_phenotype'
    ...
```
Probably Canto is having trouble with the namespaces being the same for two different annotation types.  I think that should be fixable.  I'll work on that.

**Comment by kimrutherford** [comment]
> Probably Canto is having trouble with the namespaces being the same for two different annotation
> types. I think that should be fixable. I'll work on that.

It bunch of places needed tweaking to get this working but I think it's fixed now - Canto won't complain about terms being from the wrong ontology when making host or phenotype annotations.
