### ISSUE TITLE
Single organism mode: hide quick deletion strain selector

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1771]
In single organism mode, when you make a quick deletion on the genotype management page, using the 'Deletion' shortcut in the gene list:

![single-org-quick-deletion](https://user-images.githubusercontent.com/37659591/52407959-95b57100-2ac9-11e9-9cbb-5fa645686b17.PNG)

It still shows the strain selector, except there are no strains, so you can't finish the quick deletion and the button is effectively useless:

![single-org-strain-selector](https://user-images.githubusercontent.com/37659591/52408041-cf867780-2ac9-11e9-834d-c40b62e2c0d8.PNG)

There should be a check here to skip the modal for modes where strains aren't used, or when there are no strains added to the session.

**Comment by kimrutherford** [comment]
Thanks for the fix.
