### ISSUE TITLE
adding different backgrounds

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1772]
how do you add different backgrounds to an allele? 

say for example you have a deletion allele with no background, and you want the same deletion but + background, or with different backgrounds....is there currently a way of adding this?

**Comment by mah11** [comment]
Well, there isn't an intuitive or convenient way to do it, but yes, it can be done.

You have to add the allele, then add a background, and then duplicate it. The copy will go in without a background, and you can leave it or add a different background. No matter how many copies have different backgrounds, it will never add another copy as long as there's one in the list with no background, but if they all have different backgrounds entered, it will add a new copy without background.

Worryingly, it will also let you edit a background to be identical with an existing one. That might be a bug.

That's what happened when I tried just now, anyway.

**Comment by Antonialock** [comment]
ok...so it can be done at least. Cheers, we should perhaps think of a more intuitive workflow.

**Comment by ValWood** [comment]
I think there is a ticket about this somewhere...

**Comment by mah11** [comment]
might be #1519
