### ISSUE TITLE
Single organism mode: misaligned columns in genotype list

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1773]
There's an unequal number of columns in the genotype list on the genotype management page when in single-organism mode:

![misaligned-genotype-columns](https://user-images.githubusercontent.com/37659591/52412322-4fb2da00-2ad6-11e9-98d4-317deeb1df8a.PNG)

I noticed that the `<td>` (cell) for the strain value uses different logic from other cells: specifically, it doesn't seem to make use of `columnsToHide`:
 
https://github.com/pombase/canto/blob/72117a8a84b7e7ed3e752075d840611d3bfc9196/root/static/ng_templates/genotype_list_row.html#L17

But I think the actual problem lies with the calculation of `colspan` for the header row that has 'Genotype' in it:

https://github.com/pombase/canto/blob/72117a8a84b7e7ed3e752075d840611d3bfc9196/root/static/ng_templates/genotype_list_view.html#L9-L11

This should either check whether 'strain' should be hidden as well, or it should count all of the hidden columns and subtract them from a default `colspan` value. Unfortunately any change will need testing in pathogen&ndash;host mode too.

**Comment by kimrutherford** [comment]
I have a slightly different problem when I added a deletion genotype:
![genotype-list-view-1](https://user-images.githubusercontent.com/90474/52541691-d0d2df80-2dfc-11e9-82e4-17169b22ae49.png)

**Comment by kimrutherford** [comment]
> I have a slightly different problem when I added a deletion genotype:

I should have said, that was using your branch: jseager7:1773-misaligned-columns

**Comment by jseager7** [comment]
> I have a slightly different problem when I added a deletion genotype:

I think this was because I forgot to add an `ng-hide` on the name column. I've pushed a commit to the pull request to fix that.

**Comment by kimrutherford** [comment]
> I think this was because I forgot to add an ng-hide on the name column. I've pushed a commit to the
> pull request to fix that.

That fixed it.  Thanks.
