### ISSUE TITLE
Single organism mode: no phenotype annotation option

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1775]
This might be a configuration issue, but I don't see a link to start a FYPO phenotype annotation on the Genotype Management page when in single organism mode:

![single-org-no-phenotype](https://user-images.githubusercontent.com/37659591/52413672-27c57580-2ada-11e9-9a38-86114d170ff1.PNG)

@kimrutherford I can't see anything obviously wrong with the code in `genotype_list_row_links.html`, so maybe my copy of single-organism Canto doesn't have FYPO loaded.

**Comment by kimrutherford** [comment]
I think I've fixed this.  I caused the bug months ago by not being clear about when JS variables are "truthy".
