### ISSUE TITLE
Fix missing daily email

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1780]
From #1170

**Comment by kimrutherford** [comment]
Are the emails to users working?  Like when you assign a session does the user get an email?

**Comment by ValWood** [comment]
I think so, do you want me to test?

**Comment by ValWood** [comment]
Seems fine...

**Comment by kimrutherford** [comment]
> I think so, do you want me to test?
> Seems fine...

Thanks for testing.  I'm confused because the daily emails and the session confirmations are sent in the same way.  But the daily emails don't arrive.  I'll keep working on it.

**Comment by ValWood** [comment]
Yeh I miss the daily e-mails...

**Comment by ValWood** [comment]
Any ideas? If not I will lower the priority for a while. It was nice, but not critical...

**Comment by ValWood** [comment]
You fixed it!

**Comment by kimrutherford** [comment]
> You fixed it!

I think so.  The daily emails had the From address of "noreply@pombase.org" and it seems that the mail server didn't like that.  The noreply is not a real address.  I've changed the From to be "helpdesk@pombase.org" and it now works.

**Comment by mah11** [comment]
>  The daily emails had the From address of "noreply@pombase.org" 

I think if I'd known that (erm, i.e. _noticed_ it) before they stopped, I could have set up "noreply@pombase.org" to be a recognized alias. Want me to try?

**Comment by kimrutherford** [comment]
You can also go here to get the latest summary: https://curation.pombase.org/pombe/tools/daily_summary
(It's very slow to load, possibly a few minutes)

Or to a particular day by putting the date at the end: https://curation.pombase.org/pombe/tools/daily_summary/2019-02-16
(Also very slow)

**Comment by kimrutherford** [comment]
>  could have set up "noreply@pombase.org" to be a recognized alias.  Want me to try?

Thanks, but there's no need now.  The daily emails were the only place noreply was used and it's working without it.
