### ISSUE TITLE
PHI-Canto still has too many gene curation types

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1781]
This is a regression caused by commit 6f16368, which was a temporary fix for issue #1765.

I think we might need to change the way phenotype annotations are generated from Canto's configuration, because even after merging ontology namespaces in PHIPO in an attempt to simplify things, Canto still generates the phenotype links from the annotation names in its configuration, which generates way too many links in PHI-Canto's case:

![phi-canto_phenotype_links](https://user-images.githubusercontent.com/37659591/53099599-0d4dbc00-351e-11e9-9a95-c282d5bd8434.PNG)

Ideally, we should have a link that's something like 'Single species phenotype' or 'Single species phenotype (single allele)', to match PHIPO's term &ndash; I'm now of the opinion that the single allele phenotype link is a useful shortcut &ndash; and then have a separate section for multi-allele genotypes that links to the Genotype Management page.

There's more discussion of this in #1477, and a solution to this issue will probably fix that one too.

**Comment by jseager7** [comment]
I guess a faster workaround to this problem is just to conditionally disable these links in pathogen-host mode. I might do that first.

**Comment by kimrutherford** [comment]
> I guess a faster workaround to this problem is just to conditionally disable these links in pathogen-host
> mode. I might do that first.

Thanks, I think that's a good quick fix while we talk about a longer term fix.
