### ISSUE TITLE
annotation extension config

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1783]
Could we allow

- 1 or 2 genes for 'increased/decreased/normal intergenic meotic recombination'
- 1 for normal intragenic

**Comment by mah11** [comment]
yes, but it'll have to wait until either (a) we get SVN access back, or (b) we (read: Kim ;) ) move the extension configuration files to GitHub.

**Comment by kimrutherford** [comment]
> (b) we (read: Kim ;) ) move the extension configuration files to GitHub.

That makes sense as the next thing to move.  I'll do that today.

**Comment by kimrutherford** [comment]
> That makes sense as the next thing to move. I'll do that today.

I've moved it to:
https://github.com/pombase/pombase-config/tree/master/canto/annotation_ex_config

Any changes to the extension configuration should be visible after the nightly ontology update.  So if you commit a change on Tuesday if should be visible on Wednesday. Please let me know if it doesn't work.

**Comment by mah11** [comment]
Thanks! I've adjusted the configuration so I think it should offer sensible options.

@Antonialock , can you check in a day or two and close this if it worked?

**Comment by Antonialock** [comment]
yes, will check tomorrow (not live today)

**Comment by mah11** [comment]
I forgot to mention - it's still admin-only to add genes as extensions for recombination terms. But you're an admin, so you'll be able to see when the new config is live.

**Comment by Antonialock** [comment]
Just one missing:
normal intergenic meiotic recombination

**Comment by mah11** [comment]
Glad it's working. I've just added that last one, so I'll close this.
