### ISSUE TITLE
special characters no longer resolved/ font

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1785]
like in
https://github.com/pombase/canto/issues/1271
check top and bottom one here:
![special](https://user-images.githubusercontent.com/7359272/53284455-c5f94280-374c-11e9-8d37-d1ab22091d10.jpg)

**Comment by kimrutherford** [comment]
I checked and unfortunately the characters are in the Canto database so it's not a display issue.  It looks like the XML from PubMed is being parsed badly.  I'm sure we can fix that.

**Comment by kimrutherford** [comment]
I've got a fix for this.  I'll need to take Canto offline for a few minutes to fix the characters in the database.  I'll do it Sunday morning UK time.

**Comment by kimrutherford** [comment]
After a slight false start this is fix now.  Please let me know if you spot any similar problems.
