### ISSUE TITLE
stats, percentage of participation in community curation

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1789]
What was participation in 2015?

I want to show an increase (we are at 44.5% now!)

**Comment by ValWood** [comment]
https://github.com/pombase/canto/issues/1671
so from here I have a percentage for 2015, BUT that's the percentage curated today.

Is it possible to get the %participation (in total) for papers sent our/papers received back in 2015. I know it was quite a lot lower...

**Comment by kimrutherford** [comment]
I sent this by email but I'll include here for completeness:

-----

These response rates from a Chado query:

```
2012    3.5%
2013   18.3%
2014   24.6%
2015   29.2%
2016   37.4%
2017   39.4%
2018   44.0%
2019   44.2%
```

I think the 2019 value is slightly different from the stats page
because of different rounding.

These numbers are cumulative, so eg. "2018 44%" mean the response rate
up to 2018 was 44%.

I can query the numbers for each year separately if that would help.

**Comment by ValWood** [comment]
I think it's fine. Can we add a graph  "culmulative response rate"

**Comment by ValWood** [comment]
Feb 44.5
June 45.5

would be happy with  1% increase every few months, but I think we can  do better with a "drive" at the non-participating labs at the end of this year.

Anyway this graph is no longer urgently needed. We'll ask when the paper is closer...

**Comment by ValWood** [comment]
Response rat eis now 46% ;)

We can probably slot this one in while you are here since community curation will be the next paper after MAtrix.

**Comment by ValWood** [comment]
we have this date, and we can easily get it for the graph when we need it again.

**Comment by ValWood** [comment]
closing, there is a duplicate ticket on the chado tracker
https://github.com/pombase/pombase-chado/issues/651
