### ISSUE TITLE
Pathogen-host mode can create duplicate deletion genotypes

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1796]
(This issue is distinct from issue #1130, which is an unfixed bug related to renaming genotypes, that allows duplicate genotypes to be created in any mode.)

- - -

When Canto is in pathogen-host mode, it's possible to create multiple deletion alleles on the same gene by manipulating the background of the gene. This bug is likely possible with every allele type, but I'm focusing on deletions since deleting the same gene twice is surely invalid.

@ValWood Am I right in thinking that multiple deletion alleles should never exist on the same gene, even in the case where they can theoretically be distinguished by their backgrounds?

### Steps to reproduce

- Add a deletion allele for some gene _G_,
- Add a background to _G_,
- Add another deletion allele for _G_.

Two identical deletions should now exist. An indefinite number of deletion alleles can be created on the same gene by ensuring all the deletion alleles have unique backgrounds:

![duplicate_alleles](https://user-images.githubusercontent.com/37659591/54359769-44b21300-465b-11e9-835a-a55e4d373961.PNG)

I've also noticed a related bug: once Canto is in the state of having at least two deletions on the same gene &ndash; where one has a background and the other doesn't &ndash; if the page is reloaded and another quick deletion is created on that same gene, then the strain picker doesn't even appear, and a toaster notification is shown stating, for example, 'Using existing genotype: TRI5delta'.

**Comment by mah11** [comment]
> Am I right in thinking that multiple deletion alleles should never exist on the same gene, even in the case where they can theoretically be distinguished by their backgrounds?

Yes, but different genotypes with the same deletion allele and different backgrounds are fine. That's what the screenshot looks like to me: three different genotypes, each with TRI5Δ as the "allele of interest" but with different backgrounds to make them, well, different.

IOW ...

> An indefinite number of deletion alleles can be created on the same gene by ensuring all the deletion alleles have unique backgrounds:

It's actually the same deletion _allele_ every time, not additional ones. "Deletion alleles [that] have unique backgrounds" are unique _genotypes_. That's not a bug.

> I've also noticed a related bug: once Canto is in the state of having at least two deletions on the same gene – where one has a background and the other doesn't – if the page is reloaded and another quick deletion is created on that same gene, then the strain picker doesn't even appear, and a toaster notification is shown stating, for example, 'Using existing genotype: TRI5delta'.

This sounds related to #1519 (maybe even identical); #1772 notes the resulting annoyance, but also an inconvenient but effective workaround.

**Comment by jseager7** [comment]
Thanks for clarifying everything. Given that genotypes are made unique by their backgrounds, this issue isn't actually a bug, so I'm going to close it.

I think my misunderstanding stemmed from the fact that in single organism mode, the quick deletion button isn't re-enabled when you add a background to a deletion genotype. Given that **a)** genotypes are meant to be distinguishable by their backgrounds, and **b)** the quick deletion button always adds a deletion genotype without any background, the quick deletion button should be re-enabled when Canto detects that all existing deletion genotypes (for the gene in question) have backgrounds set. It's possible to add another deletion genotype (following the rules above) using the _Other genotype..._ button, so the quick deletion should offer the same functionality. This belongs to another issue though.

It seems there's a lot of open issues mentioned here that are related to backgrounds on genotypes, so I think I'll combine those other issues into a project to keep track of them.
