### ISSUE TITLE
Some genotype combinations disable the strain picker

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1802]
I've found some strange bugs when testing genotype backgrounds in pathogen–host mode. The strain picker seems to interact badly with page reloads, which can lead to the following problems:

- the strain picker not appearing when it should – instead showing a toaster notification stating, for example, 'Using existing genotype: TRI5delta' – or
- genotypes being created without any strain set.

I'm marking the bug as low priority, even though its effects can be somewhat serious, since it requires steps to be done in a specific enough order that I feel the bug is unlikely to occur in practice.
 
### Steps to reproduce

Note that in the following example, _g_ stands for any gene.

#### Disabling the strain picker

**Setup:** Start on the _Genotype Management_ page, with an organism selected that has no genotypes added. Hard-reload the page to ensure that the bug is reset.

1. Quick delete _g_ to create genotype _G_<sub>1</sub>.
2. Add a background on _G_<sub>1</sub>.
3. Quick delete _g_ to create genotype _G_<sub>2</sub>.
4. Do a normal reload of the page.
5. Quick delete _g_. No genotype should be created, and a toaster notification should be shown.

After this bug occurs, it can be fixed by a hard reload of the page (in Chrome), so it's possible that the bug is due to some unusual caching behaviour.

#### Adding genotypes with no strains

The previous bug can also lead to an even more serious bug where a genotype can be added with no strain, using the following steps.

**Setup:** Start on the _Genotype Management_ page, with an organism selected that has no genotypes added. Hard-reload the page to ensure that the bug is reset.

1. Quick delete _g_ to create genotype _G_<sub>1</sub>.
2. Add a background on _G_<sub>1</sub>.
3. Quick delete _g_ to create genotype _G_<sub>2</sub>.
4. Do a normal reload of the page.
5. Delete _G_<sub>2</sub> (the genotype with no background).
6. Quick delete _g_ to create genotype _G_<sub>3</sub>.

_G_<sub>3</sub> should have been added with no strain (that is, the strain column should be empty).

**Comment by kimrutherford** [comment]
Hi James.  I can't reproduce this using the current master branch.  Are the strains in your example existing or new ones?

**Comment by jseager7** [comment]
It's possible that this bug has been inadvertently fixed by other commits in the time since I first opened the issue. I'll check if I can reproduce this myself.

**Comment by jseager7** [comment]
I can't reproduce this bug either, so presumably it's been fixed by later changes related to FlyBase. Closing now.
