### ISSUE TITLE
Undeliverable email message from PHI-Canto demo sessions

### ISSUE THREAD

**Issue by CuzickA** [pombase/canto#1803]
I have just noticed several email messages in the PHI-Canto email account that look like this

![image](https://user-images.githubusercontent.com/11753634/54613010-e4074980-4a51-11e9-890b-e87c5dfbe0fb.png)

**Comment by mah11** [comment]
These look like they come from testing, and can therefore be ignored/deleted.

**Comment by ValWood** [comment]
non issue?
