### ISSUE TITLE
Add a strains_mode option

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1805]
We currently show strain selectors in multi organism mode but it's not always needed.  We should probably add an independent setting for it.

@jseager7 I think you suggested this a while ago.  It's now more urgent because we use multi organism for FlyBase-Canto and worrying about strains doesn't make sense in that case.

![Screenshot from 2019-03-22 16-02-55](https://user-images.githubusercontent.com/90474/54798145-11573000-4cbc-11e9-8517-906d7bae137e.png)

**Comment by kimrutherford** [comment]
I've had a go at this (#1809) but it still needs testing.

**Comment by kimrutherford** [comment]
And remove the strains column from the phenotype/genotype annotation tables.

**Comment by vmt25** [comment]
FlyBase does not need this - could it be excluded fro  FlyCanto's genotype workflow and table?

**Comment by kimrutherford** [comment]
> And remove the strains column from the phenotype/genotype annotation tables.

I've made that change too.

> I've had a go at this (#1809) but it still needs testing.

The changes are on a branch.  I'll do more testing tomorrow and then merge things.

> FlyBase does not need this - could it be excluded from FlyCanto's genotype workflow and table?

You'll be able to hide the strains with the new `strains_mode` option once the changes are merged.

**Comment by kimrutherford** [comment]
This working now and it's merged into the master Git branch.

Vitor, to disable strains in your Canto add this line to your `canto_deploy.yaml`:

```
strains_mode: 0
```

I've updated the flybase-test server with this change. eg.:
https://curation.pombase.org/flybase-test/curs/e974e992ec7e2aad
