### ISSUE TITLE
Can't add 2  with field entries to "protein binding,bridging"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1806]
at least in this session:
curs/8c596f264411204a

I want to add the additional with entry to the "protein binding,bridging" term (which supports a pipe separated with field).

**Comment by mah11** [comment]
The GO:0030674 branch is configured to allow "binds proteins" extensions in pairs, so if you had any trouble, we'll need a bit more information to diagnose the problem. It's working for me.

(fussy tangent: the entries are comma separated in the GAF)

**Comment by ValWood** [comment]
In this session I want to add skp1 as the bridging partner.
I just tried again and I can't see how to do it?

  | fbh1 | GO:0030674 | protein binding, bridging | IPI | rad57 |   |

Can you see if this is possible for you?

**Comment by mah11** [comment]
I get it; I didn't make this bit explicit in my last comment: for now, we have to add the bridged proteins as extensions. Canto doesn't support two (or more) 'with' field entries yet (requested in #1094). 

Using extensions, I didn't save the edit, but it does look like it's working in that session, for that annotation.

**Comment by ValWood** [comment]
OK, I just forgot how we were working around this.

Do we have a ticket to allow this ?

**Comment by mah11** [comment]
> Do we have a ticket to allow this ?

Did you read my entire comment?

**Comment by ValWood** [comment]
Oh yes. I did, but when I can back after fixing I forgot !
