### ISSUE TITLE
Sort genotype tables by gene name

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1811]
It would improve the table, especially for Fly-Canto:

![single-allele-genotype-table-1](https://user-images.githubusercontent.com/90474/55295108-0a6fb080-5466-11e9-8887-cf22c86b0689.png)

**Comment by kimrutherford** [comment]
@ValWood @mah11 @Antonialock - would you prefer to keep the list in the order you add the genotypes?  If so, we can make this sorting by gene name an option that we turn on for Fly-Canto.  If you're happy to have things sorted we won't make it optional.

**Comment by ValWood** [comment]
I think we discussed this at some point. I think we want to keep them in the order we add them?
@mah11 ?

**Comment by mah11** [comment]
#1153 has the history - yes, we did try having them sorted in ascii order, and realized that we'd got used to keeping the order entered. If need be I could adapt, but I like the option ...er, option.

**Comment by vmt25** [comment]
At today's meeting it was decided to sort alleles alphabetically by gene name - if I understood correctly, this only needs to apply to the genotype tables

Aberrations (non-gene alleles) should come first

**Comment by kimrutherford** [comment]
The genotypes and genes are now sorted when loaded from the JSON file.  At some point this week I'll reload the test Canto server using this new code.  The gene list is now also sorted on loading so that it's in order on the genotype management pages.  Let me know if that makes sense.

The sorting is currently case-sensitive but that quick to change if you'd prefer case-insensitive.

![sorted-genotype-lists-2](https://user-images.githubusercontent.com/90474/55452090-769f0f80-5632-11e9-9163-cbd1fdbed44d.png)

**Comment by vmt25** [comment]
> The genotypes and genes are now sorted when loaded from the JSON file. At some point this week I'll reload the test Canto server using this new code. The gene list is now also sorted on loading so that it's in order on the genotype management pages. Let me know if that makes sense.

Great! and makes total sense.


> The sorting is currently case-sensitive but that quick to change if you'd prefer case-insensitive.

If it is not too much work, probably better to be case-insensitive.

**Comment by kimrutherford** [comment]
> If it is not too much work, probably better to be case-insensitive.

Done!  I'll re-load the flycanto-test server later today.

**Comment by kimrutherford** [comment]
> I'll re-load the flycanto-test server later today.

I'm reloading now so there'll be no test curation sessions for a while.

**Comment by kimrutherford** [comment]
> I'm reloading now so there'll be no test curation sessions for a while.

That's done now.  Here's an example genotype management page:
  https://curation.pombase.org/flybase-test/curs/33dac4236dd1bfdb/genotype_manage

**Comment by vmt25** [comment]
Apologies for reopening this one, but would it also be possible to alpha-numerically order alleles from the same gene? (only if it is quick and easy)

e.g. from PMID:29520845:

bsk | bsk[K53R.UAS](UASbskDN)
drpr | drpr[I.UAS](other)
drpr | drpr[&Dgr;5](other)
drpr | drpr[dsRNA.UAS](UASdrprRNAi)
hep | hep[CA.UAS](UAShepCA)

becoming
bsk | bsk[K53R.UAS](UASbskDN)
drpr | drpr[&Dgr;5](other)
drpr | drpr[dsRNA.UAS](UASdrprRNAi)
drpr | drpr[I.UAS](other)
hep | hep[CA.UAS](UAShepCA)

and (can't remember the paper):
mir[2]
mir[1]

becoming
mir[1]
mir[2]

**Comment by kimrutherford** [comment]
> would it also be possible to alpha-numerically order alleles from the same gene

Hi Vitor.  I've done that now:
https://curation.pombase.org/flybase-test/curs/e73a5cef8ba6e3aa/genotype_manage

**Comment by vmt25** [comment]
Great and many thanks
