### ISSUE TITLE
Use consistent name for 'metagenotype'

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1812]
PHI-Canto currently uses different spellings for the word 'metagenotype': sometimes it is hyphenated as 'meta-genotype', whereas sometimes it is just 'metagenotype'. Given that the closest comparable word, 'metagenomics', typically does not use a hyphen, we've decided to use 'metagenotype' as the canonical spelling.

**Comment by ValWood** [comment]
IIRC correctly  it shouldn't be hyphenated?
@mah11

**Comment by mah11** [comment]
> IIRC correctly it shouldn't be hyphenated?
> @mah11

erm, James said they've decided to standardize on unhyphenated 'metagenotype'. That looks correct. Not sure anyone needs me to tell 'em that ...
