### ISSUE TITLE
Allele synonyms for Fly-canto

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1816]
Allow for alleles synonyms used in a publication to be displayed in a separate column in the 'Single allele genotypes' table.

This requires:
A) A new field in the database?
B) Changes to the JSON import file from FlyBase (something like an 'allele synonym' field)
C) Changes to Canto's 'Single allele genotypes' table
D) do not show synonyms that are the same as the gene symbol

(Could not find any older related issue, so creating this one - feel free to edit/move it to any relevant ticket)

**Comment by mah11** [comment]
I knew there were tickets somewhere ... some are closed, and one is open on our Chado tracker:

#480 has some relevant info, as does #269

https://github.com/pombase/pombase-chado/issues/400 is open and linked to #1744

Leave this one open too, though, because the others don't cover the publication-specific aspect (they only refer to connecting a synonym with an allele globally).

**Comment by kimrutherford** [comment]
I've added allele synonyms to the schema and altered the JSON importer (#1779) to handle synonyms and to store them correctly.  The synonyms aren't displayed yet.  I'll do that soon.

**Comment by kimrutherford** [comment]
> Allow for alleles synonyms used in a publication to be displayed

Hi Vitor.  Just to check, will you be only displaying synonyms from the current publication in Canto and not synonyms from other publications?

**Comment by vmt25** [comment]
> > Allow for alleles synonyms used in a publication to be displayed
> 
> Hi Vitor. Just to check, will you be only displaying synonyms from the current publication in Canto and not synonyms from other publications?

Yes, only synonyms for the current publication (which will be provided on the JSON file)

**Comment by kimrutherford** [comment]
For PomBase I think we'll need to:

 - add / view / remove allele synonyms from the current paper
 - view synonyms from other papers

**Comment by kimrutherford** [comment]
I think all the code is now in place to load allele synonyms from the JSON file to display them in the allele dialog and in the genotype details list.

We at PomBase will have a discussion about allele synonym editing.

**Comment by ValWood** [comment]
We can do this on next PomBAse call ...

**Comment by ValWood** [comment]
We want to edit allele synonyms (add , remove), 
want to be able to add a synonym to an existing allele.
Do we want to display allele synonyms from other sessions? yes 
Any added in Canto we will know the paper.
Midori has a 2 column flat file for loading existing (one off)
Display only on the genotype page (make searchable)

**Comment by mah11** [comment]
For PomBase, we've decided that a free-text box will do, since we only have dozens of alleles with a synonym, and a handful with 2 or 3.

- admin only
- "edit" link or symbol brings up the box, with any existing synonym(s) editable, and room to add more

**Comment by kimrutherford** [comment]
You can now add and edit allele synonyms.

> "edit" link or symbol brings up the box, with any existing synonym(s) editable, and room to add more

I decided to just put the box inline as it was easier.  Let me know if that's OK.

"Existing synonyms" are those from other papers and "New synonyms" are the ones for the current paper.  Both of those labels could be improved.

The "New synonyms" field is only visible in admin mode.  The "Existing synonyms" field is visible is admin mode and if there are any synonyms.  I think I'll change that though as you probably don't need to see `"Existing synonyms:  (none)` in every dialog box.

![edit-allele-synonyms-1](https://user-images.githubusercontent.com/90474/57675556-74d75b80-7676-11e9-8714-3f3eff9dba71.png)

This is how the synonyms are displayed currently.  Let me know how you'd like to see them:

![edit-allele-synonyms-2](https://user-images.githubusercontent.com/90474/57675560-786ae280-7676-11e9-8f46-be7c0206f57e.png)

**Comment by kimrutherford** [comment]
@ValWood, @mah11, @Antonialock let me know if this works OK.

I've added separate issues for showing existing allele synonyms (#1880) and for storing the new synonyms in Chado (pombase/pombase-chado#731).

**Comment by kimrutherford** [comment]
> @ValWood, @mah11, @Antonialock let me know if this works OK.

Also, could you let me know when you start adding allele synonyms so I can check that they are exported correctly from Canto?  And so I have an example for testing importing into Chado: https://github.com/pombase/pombase-chado/issues/731

**Comment by ValWood** [comment]
I'm unable to test this because  I can't find our record of allele synonyms. I'm not sure if we have one? I thought we did but I can't see anything on this tracker or the curation tracker.

**Comment by vmt25** [comment]
The synonyms look good no more is needed for FlyBase purposes

**Comment by ValWood** [comment]
I'm closing this. I'm not quite sure where we are at but I know it is working so if problems, new tickets.
