### ISSUE TITLE
Hide selector, show all organisms on genotype management page (optionally)

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1818]
I think @vmt25 mentioned this on Skype. FlyBase would like to show all genotypes on the genotype management page and hide the organism selector.  This would need to be an option as PHI-Canto needs the current functionality.

@jseager7 I won't attempt this until you're happy with the genotype management refactoring you're doing. This isn't an urgent issue.

**Comment by vmt25** [comment]
> I think @vmt25 mentioned this on Skype. FlyBase would like to show all genotypes on the genotype management page and hide the organism selector

That would be nice. Every now and then there are multi-allele genotypes that combine genes/alleles of different species.

(It also has the very minor bonus of requiring one less click!)

**Comment by kimrutherford** [comment]
> Every now and then there are multi-allele genotypes that combine genes/alleles of different species.

I've made a separate issue about that: #1826.

For now I'll add an option to remove the organism selector from the genotype management page. I'll disable the combining alleles from different organisms until we've chatted about #1826.

**Comment by kimrutherford** [comment]
I've now added this option.  So in the flybase-test Canto the organism selector is hidden and it now always shows genes and genotypes from all species on the genotype management page.

eg. https://curation.pombase.org/flybase-test/curs/33dac4236dd1bfdb/genotype_manage

I'm going to leave this issue open while I do more testing in pombe-mode and pathogen-host mode.

**Comment by vmt25** [comment]
Looks great! And seems to allow combining single-allele genotypes from different organisms (see #1826 https://github.com/pombase/canto/issues/1826)

**Comment by kimrutherford** [comment]
> I'm going to leave this issue open while I do more testing in pombe-mode and pathogen-host mode.

It all seem OK so I'll close this now.
