### ISSUE TITLE
Handle greek characters in FlyBase allele names

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1820]
eg. "&bgr;" in  `&bgr;4GalNAcTA[4.1]` from PMID:17498683

**Comment by kimrutherford** [comment]
I'm going to need some help with this one.  "&bgr;" isn't a standard HTML entity, perhaps it's SGML?

Is there a table to translate these entities for the FlyBase website?

Although perhaps this isn't a high priority?

**Comment by vmt25** [comment]
Hi Kim,

including @gm119 here

> I'm going to need some help with this one. "&bgr;" isn't a standard HTML entity, perhaps it's SGML?

It is SGML.
This is how these symbols are handled by the proformae parser and stored by the database.
So, if Canto converts them into nice greek symbols, it will still have to convert them back into SGML on export.

> Although perhaps this isn't a high priority?
It isn't but... Althoguh I am already used to the &agr; format a) I still have to check every new and then, and b) it would probably be a big help for newbie curators.
Lets leave it for later.


Anyways...
> Is there a table to translate these entities for the FlyBase website?
Here it is
Lower case letters:

α = &agr; = alpha
β = &bgr; = beta
γ = &ggr; = gamma
δ = &dgr; = delta
ε = &egr; = epsilon
ζ = &zgr; = zeta
η = &eegr; = eta
θ = &thgr; = theta
ι = &igr; = iota
κ = &kgr; = kappa
λ = &lgr; = lambda
μ = &mgr; = mu
ν = &ngr; = nu
ξ = &xgr; = xi
ο = &ogr; = omicron
π = &pgr; = pi
ρ = &rgr; = rho
σ = &sgr; = sigma
τ = &tgr; = tau
υ = &ugr; = upsilon
φ = &phgr; = phi
χ = &khgr; = chi
ψ = &psgr; = psi
ω = &ohgr; = omega
Upper case letters:

Α = &Agr; = Alpha
Β = &Bgr; = Beta
Γ = &Ggr; = Gamma
Δ = &Dgr; = Delta
Ε = &Egr; = Epsilon
Ζ = &Zgr; = Zeta
Η = &EEgr; = Eta
Θ = &THgr; = Theta
Ι = &Igr; = Iota
Κ = &Kgr; = Kappa
Λ = &Lgr; = Lambda
Μ = &Mgr; = Mu
Ν = &Ngr; = Nu
Ξ = &Xgr; = Xi
Ο = &Ogr; = Omicron
Π = &Pgr; = Pi
Ρ = &Rgr; = Rho
Σ = &Sgr; = Sigma
Τ = &Tgr; = Tau
Υ = &Ugr; = Upsilon
Φ = &PHgr; = Phi
Χ = &KHgr; = Chi
Ψ = &PSgr; = Psi
Ω = &OHgr; = Omega

**Comment by kimrutherford** [comment]
> So, if Canto converts them into nice greek symbols, it will still have to convert them back into
> SGML on export.

What we'd probably do it database version "&bgr;4GalNAcTA[4.1]" in Canto and change the display code to show the Greek characters to the user.

Thanks for the table.

**Comment by gm119** [comment]
> What we'd probably do it database version "&bgr;4GalNAcTA[4.1]" in Canto and change the display code to show the Greek characters to the user.

Hi Kim,

that sounds perfect - I could supply them as utf8 greeks in the json, but then I would have to convert those back to sgml when parsing the output, so if you can do it in the display, then that saves me two conversions :)

**Comment by kimrutherford** [comment]
No problem.  We already do something similar for delta for PomBase.  In the database we store "cdc5delta" but we display "cdc5Δ".  It should be quick to add your Greek letter codes.

**Comment by vmt25** [comment]
> No problem. We already do something similar for delta for PomBase. In the database we store "cdc5delta" but we display "cdc5Δ". It should be quick to add your Greek letter codes.

Great. Thanks

**Comment by kimrutherford** [comment]
I've changed the code so that the Greek characters are displayed.  How does this look?:
https://curation.pombase.org/flybase-test/curs/527034fd25f7711e/genotype_manage

**Comment by vmt25** [comment]
Closing this one because it is mostly done and the remaining issue is one another ticket (#1868 )
