### ISSUE TITLE
Show unique gene symbols in gene table under Summary>Delete or Edit genes and organisms list ...

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1823]
The gene list table under Summary>Delete or Edit genes and organisms list shows a huge list of repeated synonyms - it would be useful to show only unique entries for each synonym.

This field seems to be pulling all gene synonyms used in all publications, leading to multiple entries of the same synonyms. e.g. on the flybase test canto, the gene list for PMID:28246214 shows the following Delta/Dl synonyms:
"Dl,Delta,Dl,Delta,Dl,Overflow,Delta,CG3619,dmDelta,delta,CT12133,delta,Delta,Delta,delta D1,1485/04,1440/11,1423/11,1304/03,1119/09,1053/14,0926/11,0495/20,D,Complementation group 1,C1,Overflow,l(3)j8C3,l(3)92Ab,l(3)05151,CG3619,anon-WO0118547.269,Dl,Dl,Dl,Dl,Delta,Dl,Dl,Dl,Dl,Delta,Dl,E(ls)2,Delta,Delta,Delta,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Delta,Delta,Dl,Dl,Dl,Dl,Dl,Dl,Delta,Delta,Delta,Delta,Delta,Delta,Dl,Delta,Delta,Delta,Dl,Dl,Dl,CG3619,Dl,Delta,Dl,Dl,Delta,Dl,Dl,Dl,Dl,Dl,Delta,Dl,Dl,Dl,Delta,Dl,Dl,Delta,Dl,Delta,Delta,Dl,Delta,Delta,Delta,Delta,Delta,Dl,Dl,Dl,Delta,Delta,Dl,Dl,Dl,Dl,Dl,Dl,Dl,Dl,Dl,Dl,Dl,Delta,Dl,Delta,Dl,Dl,Delta,Dl,Dl,Delta,Dl,Delta,Delta,Delta,Dl,Dl,Delta,Dl,Delta,Delta,Dl,EC3-5,Dl,CG3619,Delta,Dl,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Dl,Delta,Dl,Dl,Dl,Dl,Delta,Delta,Delta,Dl,Delta,Delta,Delta,Delta,Delta,Dl,Delta,Delta,Delta,Delta,Delta,Delta,Delta,Delta,Dl,Delta,Delta,Dl,Delta,Dl,Dl,CG3619,Dl,Dl,Dl,Delta,Dl,DL,Delta,Delta,Delta,Delta,Delta,Dl,Delta,Delta,Delta,Dl,Delta,Dl,Delta,Delta,Dl,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Dl,Dl,Delta,Dl,Delta,Dl,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Delta,Dl,Delta,Dl,Delta,Delta,Delta,Dl,Delta,Delta,Delta,CG3619,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Delta,Dl,Delta,Dl,Delta,Dl,Dl,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Delta,Dl,Delta,Dl,Dl,Delta,Delta,Dl,Delta,Dl,Delta,Dl,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Dl,Dl,Dl,Delta,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Delta,Dl,Delta,Dl,Delta,Dl,DL,Delta,Dl,Delta,Delta,Dl,Delta,Dl,Delta,CG3619,Dl,Delta,Dl,Delta,Delta,CG3619,Dl,Delta,Dl,Delta,Delta,Dl,Delta,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Dl,Delta,Delta,Delta,Delta,Delta,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Delta,CG3619,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Delta,Delta,Dl,Delta,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Delta,Dl,Dl,Delta,Dl,Delta,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Delta,Delta,Dl,Delta,Dl,Dl,Delta,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Delta,Dl,Delta,Dl,Delta,Dl,Dl,Dl,Delta,Delta,Dl,Delta,Delta,Dl,Dl,Delta,Delta,CG3619,Delta,Dl,Dl,Delta,Dl,Delta,Delta,Dl,Delta,CG3619,Dl,Dl,Dl,Delta,Delta,Dl,Delta,Delta,Dl,Dl,Delta,Dl,Dl,Dl,Dl,Delta,Dl,Delta,Delta,Dl,Dl,Delta,Delta,Dl,Delta,Dl,Dl,Delta,Dl,Dl,dl,Dl,Delta,Dl,Delta,Dl,Dl,Delta,Delta,Delta,Dl,Delta,Dl,Dl,Dl,Delta,Dl,Dl,Delta,Delta,Dl,Delta,Dl,Delta,Delta,Delta,Delta,Dl,Delta,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Dl,Delta,Dl,Dl,Dl,Dl,Dl,Delta,Delta,Delta,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Dl,Delta,Dl,Dl,Delta,Delta,Dl,Delta,Delta,Dl,Dl,Delta,Dl,Dl,Delta,Delta,Delta,Delta,Dl,Delta,Dl,Delta,Dl,Dl,Dl,Dl,Delta,Dl,Delta,Delta,Delta,Dl,Delta,Dl,Delta,Delta,Delta,Delta,Dl,Delta,Delta,Delta,Delta,Dl,Delta,Dl,Delta,Dl,Dl,delta,Delta,Dl,Delta,Dl,Dl,Dl,Delta,Dl,Delta,Dl,Dl,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Dl,Dl,Dl,Dl,Dl,Delta,Dl,Dl,Delta,CG3619,delta,Delta,Dl,Dl,Dl,Dl,Delta,Dl,Dl,Delta,Dl,Delta,delta,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Dl,Delta,Dl,Dl,Delta,Delta,Delta,Delta,Dl,Dl,Dl,Delta,Delta,Delta,Dl,Dl,Delta,Delta,Delta,Dl,delta,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Delta,DL,Dl,Delta,Dl,Dl,Delta,Dl,Delta,Delta,Delta,Delta,Delta,Dl,Dl,Delta,Dl,Dl,Dl,Delta,Dl,Delta,Delta,Dl,dl,Dl,Dl,Delta,Delta,Dl,Dl,Delta,Dl,Delta,Dl,Dl,Dl,Delta,Dl,Delta,Dl,Delta,Dl,Dl,Dl,Dl"

**Comment by kimrutherford** [comment]
Fixed!
