### ISSUE TITLE
Link 'Suggest a new child term for ...' to FlyBase's ontology terms pipeline

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1824]
There is already a FlyBase GitHub channel handle new anatomy ontology terms -  FlyBase/drosophila-anatomy-developmental-ontology.
Could 'Suggest a new child term for ...' directly link there when doing 'anatomy' annotations?

Changes to the 'phenotype class' ontology are very strict, so will need internal discussion at FlyBase

[this is low priority]

**Comment by ValWood** [comment]
You can just ignore this. It's mainly for community curators,  we go directly to GitHub.
I  put the Github ID in to make it easy to find (you can't approve a session until all 'open' term requests are finalised. 

either way it's optional. you don't need to add all the definition details here.

**Comment by vmt25** [comment]
> You can just ignore this. It's mainly for community curators, we go directly to GitHub.

I'm fine with ignoring! Thanks
