### ISSUE TITLE
Allow multiple alleles/genotypes annotations in one go

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1830]
(May be very ambitious, thus putting it up for discussion)

There would be massive time savings if one could make 'bulk' annotations. I.e. make in one go the same phenotype annotation to multiple alleles/genotypes.

This would require something like:
a) A 'Make multiple phenotype annotations' button at the bottom of the 'single allele genotypes' list
b) A 'Make multiple phenotype annotations' button at the bottom of the 'multiple allele genotypes' list together with item selection boxes.
c) Allowing box selection work across all genotype lists?

(not sure this would make time savings in comparison with the current copy/edit genotype option... but no harm is discussing)
d) have a  'multiple genotype' editor
This would be a text field akin to the initial 'Create gene list', where a curator can type in several genotypes in one go?
(Hypothetical e.g. here, making vas transheterozygotes with the single alleles from PMID:25795910)
vas[PH165]/vas[1]
vas[PH165]/Df(2L)A267
vas[PH165]/vas[K295N.EGFP]
vas[PH165]/vas[G294A.EGFP]
vas[PH165]/vas[R378A.EGFP]
vas[PH165]/vas[&Dgr;94-127.EGFP]
vas[PH165]/vas[R644A.EGFP]
vas[PH165]/vas[&Dgr;17-110.3xAGG.EGFP]
vas[PH165]/vas[&Dgr;3-200.EGFP]
vas[PH165]/vas[PH165]

**Comment by kimrutherford** [comment]
Consider changing the genotype selector in the "Copy and edit" dialog so that multiple genotypes can be selected.

**Comment by ValWood** [comment]
would have saved about 10 mins here, just:
https://curation.pombase.org/pombe/curs/d833bfae23694c5b/ro/

had to copy 15 phenotypes 4x

**Comment by vmt25** [comment]
(bug report)

I was playing with this but did not manage to edit or copy/edit phenotype annotations in Fly-Canto.
Mouse over OK button shows a forbidden traffic sign plus 'Annotation incomplete - please edit the fields marked in red' message. However, there are no fields marked red...

**Comment by kimrutherford** [comment]
Sorry about that.  It's fixed now.  I didn't test the changes in #1815 well enough.

**Comment by kimrutherford** [comment]
> Consider changing the genotype selector in the "Copy and edit" annotation dialog so that multiple
> genotypes can be selected.

I've had a think about this.  I'd prefer if the actions beside each annotation became a small menu with "Transfer" as a new option:

![annotation-actions-1](https://user-images.githubusercontent.com/90474/56330301-90685700-61db-11e9-8d86-422bd43b1068.png)
![annotation-actions-menu-1](https://user-images.githubusercontent.com/90474/56330369-dde4c400-61db-11e9-9be6-d9b18d7e468f.png)

And then have a separate transfer dialog:

![transfer-dialog-1](https://user-images.githubusercontent.com/90474/56330343-bbeb4180-61db-11e9-951d-62bd239068dd.png)

**Comment by vmt25** [comment]
> > Consider changing the genotype selector in the "Copy and edit" annotation dialog so that multiple
> > genotypes can be selected.
> 
> I've had a think about this. I'd prefer if the actions beside each annotation became a small menu with "Transfer" as a new option:
> 
> ![annotation-actions-1](https://user-images.githubusercontent.com/90474/56330301-90685700-61db-11e9-8d86-422bd43b1068.png)
> ![annotation-actions-menu-1](https://user-images.githubusercontent.com/90474/56330369-dde4c400-61db-11e9-9be6-d9b18d7e468f.png)
> 
> And then have a separate transfer dialog:
> 
> ![transfer-dialog-1](https://user-images.githubusercontent.com/90474/56330407-0a98db80-61dc-11e9-9204-f87979f6d1f6.png)

This seems an elegant solution!

**Comment by kimrutherford** [comment]
> And then have a separate transfer dialog

I think my example dialog isn't going to work for long genotype list.  We'd need something cleverer in that case.

**Comment by vmt25** [comment]
> > And then have a separate transfer dialog
> 
> I think my example dialog isn't going to work for long genotype list. We'd need something cleverer in that case.

I understand but still think your example is really good.

Could you add a search filter (or pagination)? As long as previous selections are not lost after a search (or after moving to the next page)

**Comment by kimrutherford** [comment]
> And then have a separate transfer dialog

Would it make sense to have a checkbox/flag in the dialog like this?:

```
  [x]  transfer annotation extension
```

(if the original annotation has an extension)

**Comment by vmt25** [comment]
changed to high priority because this issues seems like the next big improvement to Fly-Canto.

I like the plan/mock-up above.

1 - Would it be possible toHave two Copy/Transfer modes?
a) Copy **one** specific annotation to several genotypes?
b) Copy all (or several) annotations associated with a given genotype to another genotype?

2 - Would it be possible to also allow copying of 'notes' into several genotypes?

**Comment by vmt25** [comment]
note from skype call:

this issue should be the next big priority

> 1 - Would it be possible toHave two Copy/Transfer modes?
> a) Copy **one** specific annotation to several genotypes?

seems relatively straight-forward as per the mock-up above

1st pass - just the full list of genotypes
2nd pass - order genotype for the same gene first, then all other genotypes
3rd pass? - have a filter/search option?

include a 'transfer extensions' button, ticked by default - admin-only?


> b) Copy all (or several) annotations associated with a given genotype to another genotype?

complicated - seems feasible from the genotype page
 
> 2 - Would it be possible to also allow copying of 'notes' into several genotypes?
on #2203.

**Comment by kimrutherford** [comment]
I've started work on this.  It's more or less working for me locally but isn't complete.  I'll work on it again tomorrow.

Things to do:

 - [ ] fix Greek characters (eg. "&Dgr;") in the title and in the list
 - [ ] add a checkbox for enabling/disabling the transfer of extensions
 - [ ] don't include the current feature in the list (in the screenshot "EcR[B1-&Dgr;C655.W650A.UAS]" shouldn't be in the list)
 - [ ] filter accessory-only genotypes (Does that make sense Vitor?)
 - [ ] discuss the title
   - currently it's: "Transfer this *CV NAME* annotation from *FEATURE NAME* to:"
   - would this be better?: "Transfer this *TERM NAME* annotation from *FEATURE NAME* to:"
   - or something else?

I should be able to get the first three items in the to-do list finished tomorrow and deploy the change to the flybase-test Canto instance.

![annotation-transfer-menu-1](https://user-images.githubusercontent.com/90474/74721449-44bf8780-529c-11ea-81c4-b59f6ae9f334.png)
![annotation-transfer-1](https://user-images.githubusercontent.com/90474/74721459-48530e80-529c-11ea-959c-62c077878de6.png)

**Comment by vmt25** [comment]
Hi Kim,

great to hear about this progress. Looks great.

All items on your list make sense.

>     * [ ]  add a checkbox for enabling/disabling the transfer of extensions
>       
>       * but be clever and grey out this checkbox if there is no extension to transfer

and ticked/selected by default, please!

>     * [ ]  filter accessory-only genotypes (Does that make sense Vitor?)

Yes, please.
> 
>     * [ ]  discuss the title
>       
>       * currently it's: "Transfer this _CV NAME_ annotation from _FEATURE NAME_ to:"
>       * would this be better?: "Transfer this _TERM NAME_ annotation from _FEATURE NAME_ to:"
>       * or something else?

What is the difference between CV name and Term name?
It would be better to show the full CV+extension annotation, so that curators are always reminded of the extensions, thus helping decide whether to include/exclude extensions.

> I should be able to get the first three items in the to-do list finished tomorrow and deploy the change to the flybase-test Canto instance.

Awesome.

**Comment by kimrutherford** [comment]
> What is the difference between CV name and Term name?

CV name would be something like "FlyBase phenotype" and term name would be something like "cell death defective".

> It would be better to show the full CV+extension annotation

Do you mean the term name + extension?

**Comment by vmt25** [comment]
> CV name would be something like "FlyBase phenotype" and term name would be something like "cell death defective".

Thanks .

> > It would be better to show the full CV+extension annotation
> 
> Do you mean the term name + extension?

Then 'term name + extensions' please.

**Comment by kimrutherford** [comment]
> Then 'term name + extensions' please.

No problem.

Could you let me know how you'd like it to be formatted?
Here's the first possibility that came into my head:
```
Transfer cell death defective (extension: cold sensitive) from drpr[δ5] to:
```

**Comment by kimrutherford** [comment]
I've just added "order the list more sensibly" to the to-do list.  What order would like the genotype to be?

**Comment by vmt25** [comment]
Looks good. Maybe put the term name or full annotation between quote marks?

```
Transfer 'cell death defective (extension: cold sensitive)' annotation from drpr[δ5] to:
```

**Comment by vmt25** [comment]
> I've just added "order the list more sensibly" to the to-do list. What order would like the genotype to be?

Not sure but...
Maybe alphanumerically, case-insensitive.

**Comment by vmt25** [comment]
>     * filter accessory-only genotypes (Does that make sense Vitor?)

Forgot to say: aberration-only genotypes should also be filtered-out from any CV annotation. But this a larger discussion for another day.

**Comment by kimrutherford** [comment]
> I should be able to get the first three items in the to-do list finished tomorrow and deploy the
> change to the flybase-test Canto instance.

I've made those changes and updated flybase-test:
https://curation.pombase.org/flybase-test/curs/2e523d5ee64ea295

I'll keep working on this today.

**Comment by vmt25** [comment]
Very nice!

**Comment by vmt25** [comment]
It would be good if this could be extended to the interaction type of annotations - genetic interaction, rescue and complementation - but probably needs additional discussion.

**Comment by vmt25** [comment]
I noticed that you pushed the 'Transfer' option to the online Fly-canto - cool and I'll test it.
It is only listing the 'single allele' but I assume it is going to expand to list all available phenotypes (diploids, multi-locus, multi-gene genotypes), right? I'm asking this because most of our annotations are not to single alleles.

**Comment by vmt25** [comment]
Ignore my previous comment. - I did not notice the slide bar... Oops
And my quick test is works great.
I am a very happy costumer... and will be a very fast curator from now on!

**Comment by kimrutherford** [comment]
> It would be good if this could be extended to the interaction type of annotations

I agree.

> but probably needs additional discussion

I agree with that too.  :-)

I think there will be quite a few cases to handle when transferring interactions because each type has different restrictions on what genotypes are valid.

**Comment by kimrutherford** [comment]
> It would be good if this could be extended to the interaction type of annotations

I've made a separate issue for that: #2244

**Comment by jseager7** [comment]
@kimrutherford We've been testing this feature in PHI-Canto, and it's useful for us too. Our only request is to have the species names displayed next to the feature name for gene and genotype annotations, because sometimes we have the same gene or allele on different organisms, and there's no way to distinguish them in this case.

The example below shows TRI5 genes from _Fusarium sporotrichioides_ and _Trichoderma arundinaceum_, but there's no way to tell which is which. (The annotation is being transferred from TRI5 on _F. graminearum_.)

![image](https://user-images.githubusercontent.com/37659591/82307746-afc24c80-99b8-11ea-9b35-370768f545c2.png)

The proposed fix would have it look like this:

![image](https://user-images.githubusercontent.com/37659591/82308650-ff554800-99b9-11ea-9ec2-f4a3b1467bc2.png)

If you think this is going to be complicated, then I'm happy to take a look at it myself.

**Comment by kimrutherford** [comment]
> Our only request is to have the species names displayed next to the feature name for gene
> and genotype annotations

Yep, that makes sense in multi-organism mode.  I'll implement that.

> The proposed fix would have it look like this:

Probably we should also put the organism in the "Transfer ... from ... to:" header eg.

```
Transfer "toxin activity (...)" from TRI5 (Fusarium graminearum) to:
```

> If you think this is going to be complicated, then I'm happy to take a look at it myself.

If you're running low on tasks then please have a look.  Otherwise I should get to it next week.

**Comment by jseager7** [comment]
> If you're running low on tasks then please have a look. Otherwise I should get to it next week.

I've opened a new issue for showing the species names at #2290, so it can be closed by a separate pull request.

**Comment by jseager7** [comment]
@kimrutherford I've just tested this on a pathogen-host interaction phenotype annotation, and it seems the code doesn't have any support for this yet. All I get is a toaster warning saying that the feature isn't available:

![image](https://user-images.githubusercontent.com/37659591/88293823-6e6d5680-ccf3-11ea-8447-a0e919c7d15c.png)

What's worse, the modal never finishes rendering when this happens, so there's no way to close it:

![image](https://user-images.githubusercontent.com/37659591/88293928-89d86180-ccf3-11ea-9fc2-57886927aede.png)

Note that I've definitely added the `allow_annotation_transfer` property in the config for this annotation type, because the Transfer link appears:

![image](https://user-images.githubusercontent.com/37659591/88294349-08350380-ccf4-11ea-8f1a-feb67bb0b5ff.png)

The relevant code is in `annotationTransferDialogCtrl`. Seems there's no case to handle metagenotype features.

https://github.com/pombase/canto/blob/6f65fd28d18c04f8f4ef0882bf89294f0a2911cc/root/static/js/canto-modules.js#L7198-L7213

**Comment by jseager7** [comment]
I also get an error in the web console when trying to use Transfer on Physical Interaction annotations:
```
TypeError: Cannot read property 'length' of undefined
```

The error originates from the call to `$.map` in the function `extensionAsString`. It happens both on the production server and my local copy. For now, I've just disabled the transfer feature on this annotation type.

https://github.com/pombase/canto/blob/6f65fd28d18c04f8f4ef0882bf89294f0a2911cc/root/static/js/canto-modules.js#L2174-L2193

**Comment by kimrutherford** [comment]
Thanks for testing.  I'll work on those problems.

**Comment by kimrutherford** [comment]
> I've just tested this on a pathogen-host interaction phenotype annotation, and it seems the code doesn't have any support for this yet. 

Thanks James.  For the moment I've disabled the transfer link for metagenotype annotation types.  I'll fix this properly a bit later.

> I also get an error in the web console when trying to use Transfer on Physical Interaction annotations

Thanks again.  I had forgotten to test physical interactions.  I think I've fixed that now.

**Comment by kimrutherford** [comment]
> Our only request is to have the species names displayed next to the feature name 

I implemented that a few weeks ago but forgot to comment on the issue.

**Comment by vmt25** [comment]
Mostly dealt with, so I would close it
