### ISSUE TITLE
'allele name' drop down menu when 'Edit' or 'Copy/edit' genotype management lists

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1831]
(may be difficult, so putting it up for discussion)
Implement an 'allele name' drop down menu when 'Edit'-ing or 'Copy/edit'-ing genotype management lists - single and multiple genotype lists and phenotype lists (and interaction lists).

This would save plenty of time when e.g. duplicating the same annotation for different genotypes.

**Comment by vmt25** [comment]
While playing around with the tool, I noticed that this feature is already in place for phenotype annotation lists. Apologies.

**Comment by ValWood** [comment]
Yes I was hoping that would be enough. You can copy edit any annotation. So for different genotype, you just work through your list  and copy edit the genotypes (which will all be in the edit pop-up"

At PomBase for large scale screens we have a flat file import format:
https://www.pombase.org/documentation/phenotype-data-bulk-upload-format

Most spreadsheets of single gene mutants we can easily munge into this and import. We don't currently have a HTP format for multi-allele phenotype import.
