### ISSUE TITLE
triage categories

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1833]
could you add one more classifier under "Sequence feature or region"
 "transcription motifs"

thanks

**Comment by kimrutherford** [comment]
I've added the new triage status.  Unfortunately it's gone to the bottom of the list on the triage page rather than under "Sequence feature or region" because it shows them in the order they were added to the database.  Is that OK?

**Comment by ValWood** [comment]
yes no problem. I'm sure we will do this differently at some point but it works ...
