### ISSUE TITLE
Load Canto JSON into FlyBase

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1834]
Note to self: send a small example of the current pombe JSON output, including some extensions.

**Comment by kimrutherford** [comment]
I'm attaching a small example of a fly paper with fly and cerevisiae genes with one (nonsense) annotation so you can see how things will look with your data.  This example has no extensions.

I'm also attaching a large pombe example that has phenotype annotations and extensions so you can see how that looks.

[PMID:16772170-small.json.txt](https://github.com/pombase/canto/files/3087452/PMID.16772170-small.json.txt)
[PMID:20679485-pombe.json.txt](https://github.com/pombase/canto/files/3087454/PMID.20679485-pombe.json.txt)

**Comment by kimrutherford** [comment]
This depends on #1854 - supporting diploids.  I think the other parts of the current JSON export format will be OK.

**Comment by ValWood** [comment]
Can this one close?  reopen if not.
