### ISSUE TITLE
Configure extensions for FlyBase

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1835]
This is a placeholder issue for discussing extensions in Fly-Canto.

Note to self: send PomBase configuration and the config file docs to Gillian and Vitor.

**Comment by kimrutherford** [comment]
The documentation for the extension configuration is here: https://github.com/pombase/canto/wiki/AnnotationExtensionConfig

The PomBase configuration is on GitHub:
 https://github.com/pombase/pombase-config/tree/master/canto/annotation_ex_config

This is what we use for phenotypes:
 https://github.com/pombase/pombase-config/blob/master/canto/annotation_ex_config/FYPO_A_E_config

I'm happy to chat about this on Skype sometime.

**Comment by vmt25** [comment]
Closing this - config file was emailed to Kim on the 24th June and seems to work fine
