### ISSUE TITLE
Have two phenotype annotation fields in Fly-Canto: Phenotype class and Anatomy

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1836]
Managed to do it on my machine by adding the a few bit to the canto_deploy.yaml file
(tried disallowing conditions but did not work; went with 'other' as the only evidence code allowed)

- name: phenotype
   category: ontology
   namespace: phenotypic_class
   very_short_display_name:
   short_display_name: 'FBphen'
   display_name: 'FlyBase phenotype'
   synonyms_to_display:
     - exact
   feature_type: 'genotype'
   can_have_conditions: 1
   evidence_codes:
     - other
   broad_term_suggestions: >
     lethal, sterile, visible, cell number defective, locomotor behavior defective
   specific_term_examples: >
     increased cell size, small body
   help_text: >
     Annotate abnormal phenotypes of organims or cells with this genotype.
   more_help_text: >
     This a basic discription of a phenotype, i.e. any observable characteristic or trait of an organism;
     observable characteristics include morphology, development, behaviour
   extra_help_text: >
     Alleles may be annotated with multiple phenotype terms.
   detailed_help_path: /docs/fypo_annotation
 - name: anatomy
   category: ontology
   namespace: fly_anatomy.ontology
   very_short_display_name:
   short_display_name: 'FBanat'
   display_name: 'FlyBase anatomy'
   synonyms_to_display:
     - exact
   feature_type: 'genotype'
   can_have_conditions: 1
   evidence_codes:
     - other
   broad_term_suggestions: >
     embryo, wing, eye, ovary, wing disc, neuromuscular junction
   specific_term_examples: >
     NMJ bouton, oocyte, photoreceptor cell of the eye
   help_text: >
     Annotate the anatomy (organ, structure, cell or subcellular structure) where abnormal phenotype occurs in organims or cells with this genotype.
   more_help_text: >
     A phenotype is any observable characteristic or trait of an organism;
     observable characteristics include morphology, development, behaviour
   extra_help_text: >
     Alleles may be annotated with multiple phenotype terms
   detailed_help_path: /docs/fypo_annotation

enabled_annotation_type_list:
 - phenotype
 - anatomy

Here is a screenshot of test curation
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/33721108/56203579-742eb380-603d-11e9-9868-08b3188c9295.png">

**Comment by kimrutherford** [comment]
Thanks Vitor for the example configuration.  I'll add this to the flybase-test Canto tomorrow.

**Comment by kimrutherford** [comment]
Hi Vitor.  I've changed the configuration as we discussed.  There are now two separate phenotype annotation types and two interaction types.  Could you have a look and see what you think?:
  https://curation.pombase.org/flybase-test/curs/d048aaffa62adc7d

Let me know what to fix.

I case you'd like to try it locally, here is the configuration for canto_deploy.yaml:
https://curation.pombase.org/kmr44/flybase_canto_deploy-2019-08-28.yaml

**Comment by vmt25** [comment]
The 'FlyBase phenotype' and respective interaction features seem to work fine. Thanks.

I could not really test the 'FlyBase anatomy' and respective interaction because I cannot 'confirm the term'. I assume this is to do with using the fused ontology of flybase anatomy+GO CC. As mentioned in #2000, could you load the standard flybase anatomy ontology instead?
Other than this hiccup, I assume these will work as well as for 'FlyBase phenotype'.


Could you replace the interaction evidence codes for both interaction types (phenotype and anatomy) with the following?

evidence_codes:
      - suppressible
      - suppressible | partially
      - enhanceable
      - non-suppressible
      - non-enhanceable
      - non-modified

It would be good to make a few changes for the help texts/examples, but we can leave it for later.

**Comment by vmt25** [comment]
This is done
