### ISSUE TITLE
longwinded adding genes to genotype interface

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1840]
to add a gene on the genotype interface page you need to click here

<img width="385" alt="Screenshot 2019-04-26 at 11 34 28" src="https://user-images.githubusercontent.com/12727506/56802222-67694700-6817-11e9-862e-b958622b7c20.png">

then here

<img width="341" alt="Screenshot 2019-04-26 at 11 34 38" src="https://user-images.githubusercontent.com/12727506/56802230-6df7be80-6817-11e9-832e-4b1547edcc00.png">

then here

<img width="907" alt="Screenshot 2019-04-26 at 11 34 54" src="https://user-images.githubusercontent.com/12727506/56802234-72bc7280-6817-11e9-9f32-84a6b6ffc006.png">

then here

<img width="1172" alt="Screenshot 2019-04-26 at 11 35 05" src="https://user-images.githubusercontent.com/12727506/56802244-7819bd00-6817-11e9-9ce5-9621fee47e69.png">

then you are taken here so you need to click back into the genotype interface

<img width="537" alt="Screenshot 2019-04-26 at 11 35 14" src="https://user-images.githubusercontent.com/12727506/56802255-7d770780-6817-11e9-9d59-6f332cb0ae09.png">

Can we have a quicker 'add gene to curation session' option? Also a quicker option to remove genes but it needs to be very clear that you are removing it (including all annotations to it)

**Comment by kimrutherford** [comment]
Sorry, that the same problem as #1839 - fixed now.

> Also a quicker option to remove genes

I'll make a separate issue about that.
