### ISSUE TITLE
adding genes in genotype interface

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1843]
when adding a gene in the genotype interface, I have to reload the page in order to see the newly added gene
(I thought this has been fixed before?)

<img width="326" alt="Screenshot 2019-04-29 at 22 31 35" src="https://user-images.githubusercontent.com/12727506/56928439-b7bdfe80-6ace-11e9-85cb-9759d193db3c.png">

**Comment by kimrutherford** [comment]
Sorry about that.  Probably that broke because of code changes to support PHI-Canto.  We'll fix it.

**Comment by kimrutherford** [comment]
That's fixed now.
