### ISSUE TITLE
should we have a stronger border around multi-allele genotypes?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1849]
Alternating colour only  doesn't work so well to differentiate (especially for newbies)

![colour](https://user-images.githubusercontent.com/7359272/57022864-58740180-6c28-11e9-9709-db42368b9d36.jpg)

**Comment by ValWood** [comment]
Or even no cells within genotypes.

I know we discussed this in older tickets, so should link the discussion to here to see why we eliminated some of the other options.

**Comment by mah11** [comment]
previous discussion in #1520

I don't require any changes from the current display.

**Comment by ValWood** [comment]
It's fine once you mouse over, but until then it isn't clear  which set of alleles constitutes a genotype.

**Comment by ValWood** [comment]
duplicate of 
previous discussion in #1520
