### ISSUE TITLE
Add explanation of strain to species mapping for users

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1850]
Some time ago we decided that we weren't going to curate at the strain-level in PHI-Canto. Currently, we automatically remap the taxon ID of any UniProt ID at the strain level to the parent species-level taxon ID. It would be useful for users if we had a notice explaining this after the organisms have been retrieved from UniProt. Otherwise, users are likely to think that something has gone wrong with UniProt or Canto, since they didn't get back the taxonomic rank they were expecting.

The notice could look something like this:

> ℹ️ Some UniProt identifiers correspond to a taxon identifier that is more specific than the species rank. These taxon identifiers have been replaced with their nearest species-level taxon identifier. <a href="#">More information&hellip;</a>

The 'More information&hellip;' link would go to a help page explaining the process in more detail, clarifying our rationale for doing the remapping, and the fact the original identifier is still stored, etc.

We could also list the UniProt identifiers that have been subject to remapping under the notice, or we could 'tag' the remapped identifiers on the page with text or an icon.

**Comment by jseager7** [comment]
I could look at adding this notice to the PHI-Canto page where you review the genes and organisms that have been added, and show the notice unconditionally &ndash; regardless of whether anything has been remapped or not &ndash; since that will be easier to get working. Long-term we'll need to create a help page (or some form of template) with more detailed justification. I'd like to have some way to indicate which IDs were remapped too.

**Comment by jseager7** [comment]
I've tested adding some text on the confirmation page. Here's how it looks on my local copy:

![image](https://user-images.githubusercontent.com/37659591/64334443-75528400-cfd0-11e9-886e-b68b97d793fa.png)

The text is repeated below for clarity:

> **Note:** PHI-Canto does not curate at taxonomic ranks lower than species. If you have entered UniProt identifiers that are at the strain or subspecies level, these identifiers may have been re-mapped to the nearest species rank. Please use the 'experimental strains' field to specify lower taxonomic ranks (strains, pathovars, subpsecies, etc.)

The text is configured to only show in pathogen-host mode. Since it currently shows regardless of whether any species have been remapped or not, I've reworded the notice accordingly.

@kimrutherford At the moment, the text is baked into the template, but it would probably be better stored in the config file. Unfortunately, this page is a mason template, so I'm not sure how to reference the config in this case.

**Comment by CuzickA** [comment]
@jseager7 Looks good to me thanks. There is a typo at the end of the text -should be 'subspecies'.

> The text is configured to only show in pathogen-host mode. Since it currently shows regardless of whether any species have been remapped or not, I've reworded the notice 

I think we would also need this in pathogen and host modes not just pathogen-host mode?? The above text location is before the 'mode' is selected so should be fine.

**Comment by jseager7** [comment]
> There is a typo at the end of the text -should be 'subspecies'.

Thanks for noticing that. I've amended my comment to fix it.

> I think we would also need this in pathogen and host modes not just pathogen-host mode??

This might be a misunderstanding &ndash; to clarify, I meant that this notice shows on the page after you enter your UniProt IDs, and it shows regardless of whether you've added just pathogens, or pathogens and hosts. The notice is not related to the annotation or genotype types you're working on; it's displayed earlier in the workflow than those pages. The notice _doesn't_ show if you're in single organism mode (PomBase) or multi-organism mode (FlyBase).

**Comment by jseager7** [comment]
Forgot to link this issue to the pull request that fixed it (#2063). The notice has been added now anyway. Closing.
