### ISSUE TITLE
Decide how to represent diploids in the JSON import file

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1853]
An example of the current format is here: https://github.com/pombase/canto/wiki/JSON-Import-Format

See also #1779.

We might be able to do something like:

```
   "genotypes": {
      "FB<something>": {
        "taxon_id": 7227,
        "genotype_name": "...",
        "background": "...",
        "comment": "...",
        "diploids": [
            [ 
                {
                     "allele_uniquename": "FBal0119310"
                },
                {
                     "allele_uniquename": "FBal0064432"
                }
            ]
        ]
      }
```

This needs a discussion on Skype I think.

**Comment by kimrutherford** [comment]
> We might be able to do something like:

I've done more thinking and added a slightly different suggestion at the bottom of this page:
https://github.com/pombase/canto/wiki/JSON-Import-Format

It needs some discussion.

**Comment by vmt25** [comment]
FlyBase does not need importing diploid genotypes (at least the foreseable future) - all compound genotypes (diploids and/or combining alleles from different genes) would be created during curation within Canto

**Comment by kimrutherford** [comment]
OK, that makes it easier.  :-)

I think we can put this on low priority for now.

**Comment by vmt25** [comment]
> FlyBase does not need importing diploid genotypes (at least the foreseable future) - all compound genotypes (diploids and/or combining alleles from different genes) would be created during curation within Canto

Unless you mean import from Canto into FlyBase...

**Comment by kimrutherford** [comment]
> thought that there was a separate ticket for the export format

Yep, we have a separate issue about exporting diploid genotypes: #1854

**Comment by ValWood** [comment]
I'm guessing this might be done now?

**Comment by kimrutherford** [comment]
> I'm guessing this might be done now?

Probably.  :-)

Let's close this once Gillian's had a good look at the FlyBase side of things.

**Comment by gm119** [comment]
closing this as FlyBase won't need this for the forseable future, but if we do, the suggested format looks good to me
