### ISSUE TITLE
Decide how to represent diploids when exporting JSON

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1854]
See also: #1834.

**Comment by kimrutherford** [comment]
I think I have a preliminary plan for this.  Currently in the JSON output each genotype has a list of alleles with optional expression levels.  A bit like this:

```json
          "genotypes" : {
             "aaaa0007-genotype-test-1" : {
                "alleles" : [
                   {
                      "id" : "SPAC27D7.13c:aaaa0007-1"
                   },
                   {
                      "id" : "SPCC63.05:aaaa0007-1"
                   }
                ],
                "name" : "h+ SPCC63.05delta ssm4KE"
             },
             "aaaa0007-genotype-test-2" : {
                "alleles" : [
                   {
                      "expression" : "Knockdown",
                      "id" : "SPAC27D7.13c:aaaa0007-3"
                   }
                ]
             }
          }
```
(The IDs are made up by Canto and were just for testing.  The allele details are elsewhere in the JSON)

I've made a branch (7d824e87b4cabee0c4a50e147d653fd293c49429) and changed the code to replace the "alleles" field with a "loci" field.  The "loci" field is a list, each element of which contains the alleles at a locus.  In the pombe haploid case could have an example like this with one locus and one allele:

```json
            "829221bfce6f2ab3-genotype-14" : {
               "loci" : [
                  [
                     {
                        "id" : "FBal0012432"
                     }
                  ]
               ],
               "organism_taxonid" : 7227
            }
```

For PomBase we need usually need to include the expression:

```json
            "aaaa0007-genotype-test-2" : {
               "loci" : [
                  [
                     {
                        "expression" : "Knockdown",
                        "id" : "SPAC27D7.13c:aaaa0007-3"
                     }
                  ]
               ],
               "organism_taxonid" : 4896
            }
```

A multi-allele haploid genotype might look like:

```json
            "829221bfce6f2ab3-genotype-18" : {
               "loci" : [
                  [
                     {
                        "id" : "FBal0012432"
                     }
                  ],
                  [
                     {
                        "id" : "FBab0002747"
                     }
                  ]
               ],
               "organism_taxonid" : 7227
            }
```

And in the single locus diploid case the "loci" field would be a list with one element.  That element would contain the two alleles of the diploid locus.  It might look like:

```json
            "829221bfce6f2ab3-genotype-16" : {
               "loci" : [
                  [
                     {
                        "id" : "FBal0340198"
                     },
                     {
                        "id" : "FBal0049393"
                     }
                  ]
               ],
               "organism_taxonid" : 7227
            }
```

This format is bit unreadable by humans but I think it covers all the cases we need including haploid+diploid in one genotype.  It would also cover tetraploids if that was needed in future. 

I won't do too much more on this until we've had a chat about it.

**Comment by kimrutherford** [comment]
I've just merged the code that writes the new format and I've changed the PomBase loading code to match:
https://github.com/pombase/pombase-chado/issues/734#issuecomment-500655108

We don't have any diploids in PomBase's Canto so this will only test the format for haploid loci.  It's a start though.

**Comment by kimrutherford** [comment]
> I won't do too much more on this until we've had a chat about it.

I think we had a short chat about this format on the last call.  Maybe the next step would be for @vmt25 or @gm119 to make a few diploids genotypes (single and multi-locus) and add a few dummy annotations.  We can then export the session(s) and see how it looks in the JSON output.

**Comment by ValWood** [comment]
I hope to test diploid interface  later today...

**Comment by vmt25** [comment]
> I think we had a short chat about this format on the last call. Maybe the next step would be for @vmt25 or @gm119 to make a few diploids genotypes (single and multi-locus) and add a few dummy annotations.

Doing it... and finding issues and thinking of new stuff and creating tickets as I go along. Apologies

**Comment by vmt25** [comment]
> I think we had a short chat about this format on the last call. Maybe the next step would be for @vmt25 or @gm119 to make a few diploids genotypes (single and multi-locus) and add a few dummy annotations.

Doing it on the pre-existing curation session: https://curation.pombase.org/flybase-test/curs/4e77f8cbed7cd6c6

**Comment by kimrutherford** [comment]
> Doing it on the pre-existing curation session

Thanks.  Let me know when we should try to export.

**Comment by vmt25** [comment]
> Thanks. Let me know when we should try to export.
ready - tried to do a combination of different stuff to provied diverse use cases

**Comment by kimrutherford** [comment]
> ready - tried to do a combination of different stuff to provied diverse use cases

Great, thanks.  I'm going to temporarily change the session to the "approved" state.  The exporter knows how to export all the sessions or (with the right command line option), just export the approved sessions.  If we export only approved sessions the output JSON file will be much more manageable.

The script is run like this:
```sh
./script/canto_export.pl canto-json --dump-approved > approved_sessions.json
```

**Comment by kimrutherford** [comment]
> I've just merged the code that writes the new format and I've changed the PomBase loading code
> to match

That worked fine with the existing haploid genotypes.  I still need to change the loading code to support diploids.

**Comment by kimrutherford** [comment]
> ready - tried to do a combination of different stuff to provied diverse use cases

One thing that session didn't have is any examples of aberrations.  When you get a chance could you find a session/publication with an aberration and use it in a genotype annotation?

Thanks!

**Comment by vmt25** [comment]
> One thing that session didn't have is any examples of aberrations. When you get a chance could you find a session/publication with an aberration and use it in a genotype annotation?

You are right and I am doing some tests.

When trying to make diploids, found that although aberrations appear on the third option/transheterozygous dropdown menu and I can select them, the combined genotype does not show up on the diploid/multiploid genotype table. It was working perfectly fine during earlier tests.

On "https://curation.pombase.org/flybase-test/curs/79ef0a0d649b4ffb/genotype_manage" I cannot see the β4GalNAcTA[4.1] / Df(2R)β4GalNAcTA[20.1](aberration) transheterozygote that I've made.

**Comment by vmt25** [comment]
Forgot to say that making homozygous aberrations (Df(2R)β4GalNAcTA[20.1] / Df(2R)β4GalNAcTA[20.1]) works fine

**Comment by kimrutherford** [comment]
Sorry about that.  The selector for alleles wasn't returning the correct allele.  I think I've fixed that now.  Could you test again?  Thanks!

**Comment by vmt25** [comment]
Now the 'Create diploid locus' disappeared.
The 'Combine selected genotypes' is working fine

**Comment by kimrutherford** [comment]
> Now the 'Create diploid locus' disappeared.

Are you logged in?

**Comment by vmt25** [comment]
> Are you logged in?

Now I am logged in and the button re-appeared - but why would one button still be present and functional and the other not?

Now I can make diploid loci. Will make a few more complicated stuff and will report back to you

**Comment by kimrutherford** [comment]
> but why would one button still be present and functional and the other not?

We're only showing the "Create diploid locus" button to admin users until it's ready for the community users. The combining genotypes functionality is available to everyone.

**Comment by vmt25** [comment]
> We're only showing the "Create diploid locus" button to admin users until it's ready for the community users. The combining genotypes functionality is available to everyone.

Got it. Now I vaguely remember a commentary about that.


You can now pick the 'https://curation.pombase.org/flybase-test/curs/79ef0a0d649b4ffb' session, with a few complex genotypes and annotation involving aberrations

**Comment by kimrutherford** [comment]
> You can now pick the 'https://curation.pombase.org/flybase-test/curs/79ef0a0d649b4ffb' session, with
> a few complex genotypes and annotation involving aberrations

Great, thanks.  As with the other session, I'll need to put it in the APPROVED state while exporting.

I'll do that now.

**Comment by kimrutherford** [comment]
I've exported the JSON file and un-APPROVED the two sessions.

**Comment by kimrutherford** [comment]
I think this old issue can be closed.

**Comment by vmt25** [comment]
agreed.
