### ISSUE TITLE
Allow free text in the "with" field

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1857]
When ISS annotation  enabled in Canto 

From #1852:
> we will need to allow free text for the "with" field because I usually use SGD: but can be
> UniProt: or Interpro:/Pfam: for ISM

**Comment by ValWood** [comment]
This will be required to complete
https://canto.phi-base.org/curs/bd02fdb6831712ca

Another option is to pick  a single ortholog sequence from the alignment, enter that and use it in the with field....?

Discuss possibilites on next call...

**Comment by kimrutherford** [comment]
What free text is needed in that session?

**Comment by ValWood** [comment]
Actually,  I  shouldn't need to add free text. We will just make sure the IDs are added to the session. We can do all via UniProt IDs
