### ISSUE TITLE
Uniprot identifier is displayed, not "gene"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1858]
see for example:

The name displayed should be SNOG_20078
(there might be an older ticket about this?)

![names and genes](https://user-images.githubusercontent.com/7359272/57529589-2a2fa980-732d-11e9-9ae2-53f5375746a2.jpg)

**Comment by kimrutherford** [comment]
> there might be an older ticket about this?

There's this?: #1543

**Comment by ValWood** [comment]
That's the one. It would be good to do this (It's quite confusing to see uniprot IDs instead of gene names). Will be needed before @CuzickA  does the screencasts.

@jseager7  could you look into this next week? @CuzickA  can explain on Monday if it isn't clear.

**Comment by kimrutherford** [comment]
I'm going to close this issue in favour of: #1543
