### ISSUE TITLE
header misleading

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1860]
I read this as  "Gene ID" when actually  the item under ID is a  "protein database entry accession"

I think it is OK to keep the column header as ID, but I wonder if the layout could be improved so that it is clearer that "Gene"  applies to the entire block

**Comment by kimrutherford** [comment]
Which part of Canto is this?

**Comment by ValWood** [comment]
sorry, pic didn't upload
PHI Canto

![fix header](https://user-images.githubusercontent.com/7359272/57567556-f8711e00-73d2-11e9-80db-965aba12911a.jpg)

**Comment by kimrutherford** [comment]
We could do something like:
![confirm-gene-heading-1](https://user-images.githubusercontent.com/90474/57567933-98ab5f00-7434-11e9-9b8e-dc8109b15d7e.png)

**Comment by ValWood** [comment]
Yes!

**Comment by kimrutherford** [comment]
I've made that change.

@jseager7 could you close this issue next time you re-deploy?
