### ISSUE TITLE
refine conditions text

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1861]
current
"Please add experimental conditions. Conditions are the aspects of the experimental setup that are independent of what cells (strain, genotype, constructs, etc.) are used."

is there anything we can add to this text to prevent everyone adding all aspects of their methods. For example "x staining". We don't really want every aspect of an experiment.

I'm thinking somethnig like

You only need to report conditions which alter the output of your experiment"

**Comment by ValWood** [comment]
Weird. I am absolutely certain  I just commented on  a duplicate of this but I can't find it...

**Comment by mah11** [comment]
#1549 ?

**Comment by ValWood** [comment]
https://github.com/pombase/canto/issues/1549
duplicate
