### ISSUE TITLE
For FlyBase, hide left hand gene table on genotype management page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1867]
Add an option for this.

**Comment by kimrutherford** [comment]
I've added a new option `show_genotype_management_genes_list` for hiding the genes on the genotype management page.

And I've applied the change to the flybase-test Canto: https://curation.pombase.org/flybase-test/curs/527034fd25f7711e/genotype_manage

**Comment by ValWood** [comment]
Really nitpicky but a slightly wider left-hand margin might be good (provided that we don't introduce the same amount of space in the version with the genotype management lists). 

Visually it just makes it easier to look at with a tiny bit more padding, especially if you are over the top of another window. Only a couple of millimeters. Ignore if it's a pain.

**Comment by kimrutherford** [comment]
Could you attach a screenshot of how it looks for you?

**Comment by ValWood** [comment]
It's not bad but seems a shame to have it so left justified when there is so much screen estate to the right now...

![page](https://user-images.githubusercontent.com/7359272/57701068-18167980-7653-11e9-985b-ae3b4e2ace9b.jpg)

**Comment by kimrutherford** [comment]
I've added a bit more space:
 https://curation.pombase.org/flybase-test/curs/527034fd25f7711e/genotype_manage

**Comment by ValWood** [comment]
yep! sorry that was s nitpicky, I have a thing about sufficient whitespace !
