### ISSUE TITLE
make it easier to distinguish 'haploid' and diploid' alleles in the table

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1870]
- [x]  put in a "diploid' sub header.

new alleles will sort to the bottom of either 'sub-table'

Later we will consider a configuration option to organize genotypes alphabetically

**Comment by kimrutherford** [comment]
I've added a sub-heading:
 https://curation.pombase.org/flybase-test/curs/527034fd25f7711e/genotype_manage

It looks a bit odd because the "Diploids" heading aligns with the "Genotypes" heading at the top.  It looked worse when "Diploids" was aligned on the left.  Any suggestions?

**Comment by ValWood** [comment]
this would introduce an extra row to the table but would be explicit  and would  get around the positioning issue

**Comment by ValWood** [comment]
![suggestion](https://user-images.githubusercontent.com/7359272/57831715-d51ce900-77ad-11e9-9d49-72974b17daf6.jpg)

**Comment by kimrutherford** [comment]
> this would introduce an extra row to the table but would be explicit and would get around the positioning
> issue

Thanks.  I've done that:
https://curation.pombase.org/flybase-test/curs/527034fd25f7711e/genotype_manage

**Comment by kimrutherford** [comment]
Is there anything else to do here?

**Comment by ValWood** [comment]
nope.

**Comment by ValWood** [comment]
if anyone wants to change anything can have a new ticket.
