### ISSUE TITLE
How to make it clear that a comment is available

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1872]
Geneotype comments will be imported for FlyBase, and will be used also sometimes by PhiBase and PomBase.

We need a way to alert curators that a comment is present because they are hidden from the main table.

**Comment by ValWood** [comment]
Thinking about this, our community curators wouldn't really need this, so, since it is an admin only option the "*" idea seems that it would be OK?

**Comment by kimrutherford** [comment]
> Thinking about this, our community curators wouldn't really need this, so, since it is an admin only
> option the "*" idea seems that it might work OK?

Should we hide the "Add/edit comment..." item in the menu at the right in non-admin mode?

I've added an indicator if there is a comment.  I've used "C*" because "*" wasn't very visible.  But perhaps it could just be "Comment..."?

If you click on the "C*" it pops up a box containing the comment.

![genotype-comment-indicator-1](https://user-images.githubusercontent.com/90474/57750253-a19e7800-7735-11e9-9a58-372fa6fb7d21.png)

**Comment by ValWood** [comment]
I think we could have as admin only to begin with. For the few cases we have comments curators can add them as required.

**Comment by kimrutherford** [comment]
The comment view and edit links are now shown only to admin users.

**Comment by kimrutherford** [comment]
> I've added an indicator if there is a comment.

I've tweaked this a bit.  The indicator is now "comment ...".  If you hover over the indicator it will show the comment and if you click you can edit and copy the comment.

**Comment by kimrutherford** [comment]
Sorry, I commented on the wrong issue (https://github.com/pombase/canto/issues/1779).  Here's the cut and paste:

I've loaded your JSON file with allele descriptions into my local Canto, storing the descriptions as comments.  It looks like this.  The comment/description pops up if you mouse over the "comment..." link.  Do you think that like be convenient enough for seeing the allele descriptions?

![flybase-genotype-comment-1](https://user-images.githubusercontent.com/90474/58229478-f79e9b80-7d85-11e9-9553-8a8a438fe644.png)

**Comment by vmt25** [comment]
Hi Kim,

The 'comment' indicator and the pop-up window look great.

Fly-Canto would need to allow new comments but it would help if existing/uploaded comments could be 'read-only' - should discuss this.

**Comment by vmt25** [comment]
> Fly-Canto would need to allow new comments but it would help if existing/uploaded comments could be 'read-only' - should discuss this.

Tuesday's decision was to append text (as a new paragraph?) to existing comments instead of allowing edits.

Also, comments must only be allowed for individual alleles, not for more complex genotypes.

**Comment by kimrutherford** [comment]
> Fly-Canto would need to allow new comments but it would help if existing/uploaded comments could be
> 'read-only' - should discuss this.

I've changed things so that the existing comments are shown with a link labelled "note..." and they are now read only.

You can add a new comment using "Add/edit comment..." option in the small menu on the right for each genotype.  Those new comments shown with the "comment..." links and are editable.

Here's an example:
https://curation.pombase.org/flybase-test/curs/4e77f8cbed7cd6c6/genotype_manage

![allele-notes-1](https://user-images.githubusercontent.com/90474/58699761-6c12b380-83f2-11e9-8be2-5d9a9b095b97.png)

**Comment by kimrutherford** [comment]
I forgot to say: the notes and comment link and menu item are only visible to admin users.

**Comment by kimrutherford** [comment]
Hi @gm119 and @vmt25 does this sound OK?:

> I've changed things so that the existing comments are shown with a link labelled "note..." and they
> are now read only.

> You can add a new comment using "Add/edit comment..." option in the small menu on the right for
> each genotype. Those new comments shown with the "comment..." links and are editable.

If so, can we close this issue?

**Comment by vmt25** [comment]
Hi Kim,

Fist of all, the mockups look great.

I was now going to test it further using your session above (https://curation.pombase.org/flybase-test/curs/4e77f8cbed7cd6c6/genotype_manage) but the notes disappeared and I cannot add comments/notes (see attachment). I see the same in other sessions.

![Screenshot 2019-06-10 at 11 03 14](https://user-images.githubusercontent.com/33721108/59188619-f2a45f00-8b6f-11e9-8dd6-294eb7f9268c.png)

Just couple of comments on this issue:
A) It is good to have old and new comments/notes as separate things, to make it clear which are from the current session. However, would it be possible to rename the 'comments' as 'new notes', as they will go to the same place as the pre-existing ones?
B) From my checking this previously, I thought new comments are available for all genotypes. Would it be possible to restrict new notes/comments to the single alleles?

**Comment by kimrutherford** [comment]
Hi Vitor.  Thanks for trying this out.  You'll need to be logged in to see the notes and comment links at the moment.

> would it be possible to rename the 'comments' as 'new notes', 

I'll do that.

> Would it be possible to restrict new notes/comments to the single alleles?

I'll add an option so you can disable the notes for diploids and multi-allele genotypes.

**Comment by vmt25** [comment]
> You'll need to be logged in to see the notes and comment links at the moment.

Oh, right. Probably I was on admin on previous tries.

I tried it now and works perfectly fine. Thanks

**Comment by kimrutherford** [comment]
> would it be possible to rename the 'comments' as 'new notes',

That's done now.

> Would it be possible to restrict new notes/comments to the single alleles?

I've added an option for that.  You'll need to add this to the configuration to hide the notes:
```
notes_on_single_allele_genotypes_only: 0
```

Both of those changes are in the test Canto: https://curation.pombase.org/flybase-test

**Comment by kimrutherford** [comment]
> I've added an option for that.  You'll need to add this to the configuration to hide the notes:
> `notes_on_single_allele_genotypes_only: 0`

Sorry that should be:
`notes_on_single_allele_genotypes_only: 1`

**Comment by vmt25** [comment]
Thanks

**Comment by vmt25** [comment]
'add/edit new notes' is still semi-functional in the diploid and multiallele genotype tables. The menu option is there, it is possible to add notes and edit them (imeaning they are stored, right?), but the 'new note' mark does not appear.

Does this mean that if a note is made by mistake it will be on the export?

**Comment by kimrutherford** [comment]
> 'add/edit new notes' is still semi-functional in the diploid and multiallele genotype tables. The menu
> option is there, it is possible to add notes and edit them (imeaning they are stored, right?), but the
> 'new note' mark does not appear.

I forgot about the menu item.  It's now hidden.

> Does this mean that if a note is made by mistake it will be on the export

Yep, all notes will be exported.

**Comment by vmt25** [comment]
Great! Thanks!

**Comment by ValWood** [comment]
Closing. Changes in new tickets.
