### ISSUE TITLE
Show synonyms from existing Chado alleles

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1880]
When an allele is read from Chado get any synonyms too.

**Comment by ValWood** [comment]
OK, I had the opportunity to use this.

I curated an allele as rad21-K31

later in the paper they figured out that the ts causing mutation was  I67F, so  (although the original mutant had other changes,  the phenotypes were all associated to this change)

Therefore I made I67F the primary for this  particular allele with rad21-k1 as a synonym 
(if we had synonym type, this would be narrow, I could add this as a genotype comment)

I could see the synonym, all good

![K21](https://user-images.githubusercontent.com/7359272/58548764-e29c8f00-8201-11e9-8373-af9e0f592513.jpg)

but when I look later, the synonym has dissappeaed?

**Comment by kimrutherford** [comment]
Which session was that?

**Comment by ValWood** [comment]
hmm, I have the session open on two laptops.... maybe I somehow overwrote it...but seems odd because I did it at the same time and the name change and the new name is current???

**Comment by ValWood** [comment]
I want a medal for this session
https://curation.pombase.org/pombe/curs/16ad711046a3f839/genotype_manage#/select/56

**Comment by kimrutherford** [comment]
Thanks for testing.  The synonyms aren't in the database so it's not a display issue.  I'll see if I can reproduce the problem.

**Comment by kimrutherford** [comment]
> When an allele is read from Chado get any synonyms too.

This isn't done yet.

There is now an allele synonym in Chado for:
wss2-E203Q | SPCC1442.07c:allele-2

The synonym is E203Q added in this session: https://curation.pombase.org/pombe/curs/d43ed7beb6c57947/genotype_manage/ro

**Comment by kimrutherford** [comment]
> When an allele is read from Chado get any synonyms too.

That's done now.  For example if you autocomplete on rad21-I67F you see the existing synonym "rad21-K1".

![allele-edit-existing-synonyms-1](https://user-images.githubusercontent.com/90474/58784740-3a8b2980-8638-11e9-987c-af816f1fb27d.png)

![allele-edit-existing-synonyms-2](https://user-images.githubusercontent.com/90474/58785098-f8161c80-8638-11e9-8552-3c9c8b2b59a9.png)

**Comment by kimrutherford** [comment]
Sorry, I forgot to say that this isn't in the main PomBase Canto.  I'll update the code overnight.
