### ISSUE TITLE
Change 'Multi allele genotypes' labels

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1888]
(related to #1870)

1. The 'Single allele genotype' header in the 'Multi allele genotypes' table is not appropriate. Please remove it or rename it 'Multi allele genotype' - (see attached screenshot)

2. Perhaps rename this section 'Multi locus genotypes', to match the 'Single locus genotypes' of the upper section?

<img width="576" alt="Screen Shot 2019-05-23 at 13 03 39" src="https://user-images.githubusercontent.com/33721108/58255168-4cc9b580-7d64-11e9-9189-7879a90f9485.png">

**Comment by kimrutherford** [comment]
I've renamed "Single allele genotype" to just "Genotype" for now.  We have a "Multi allele genotypes" heading just above the table so we probably don't need to repeat that.

**Comment by vmt25** [comment]
Cool. Thanks
