### ISSUE TITLE
duplicated aberrations on diploid dialog box

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1889]
(very low priority)
(related to 'Add aberrations to diploid dialog' #1865)

Spotted this in a paper with two aberrations.
Was trying to make a 'diploid' that combines both aberrations (which we would like to doevery now and then). When picking an aberration, the allele dialog box shows the other aberration twice! see image Could not find such duplications when picking conventional alleles

<img width="730" alt="Screen Shot 2019-05-23 at 14 47 10" src="https://user-images.githubusercontent.com/33721108/58258178-2c045e80-7d6a-11e9-8c74-f22e02584009.png">

**Comment by kimrutherford** [comment]
Thanks for spotting that.  It's fixed now.  The diploid code wasn't doing the right thing when starting from an aberration.

Do the other two options in the dialog make sense for aberrations?  (ie. homozygous and wild type)

**Comment by vmt25** [comment]
> Do the other two options in the dialog make sense for aberrations? (ie. homozygous and wild type)

Yes, they do!
Thanks

**Comment by kimrutherford** [comment]
> Yes, they do!

Great.
