### ISSUE TITLE
Fly-canto's 'Create gene list' feature allows alleles

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1890]
(For future discussion - very low priority)

While playing around with 'Create gene list' I managed to associate alleles(!) to a publication:

Searching for e.g. '11' (a search that no curator would do - for illustration purposes only) gives a 'multiple possible hits' kind of message with a mixed list of genes (FBgn) and alleles (FBal). Aberrations do not seem to be searched.
<img width="863" alt="Screen Shot 2019-05-23 at 16 34 16" src="https://user-images.githubusercontent.com/33721108/58266610-ed76a000-7d79-11e9-9921-fc3857b18920.png">

Searching for an allele identifier then adds it to the genes list
<img width="908" alt="Screen Shot 2019-05-23 at 16 44 15" src="https://user-images.githubusercontent.com/33721108/58266674-11d27c80-7d7a-11e9-8b2f-4703ae39c0be.png">

Although FlyBase is not planning to associate genes or alleles to publications in Fly-Canto in the near future, this may be a useful feature later on.
It would be good to discuss, namely wheter would it be useful/possible to either
a) only search for genes (FBgns)
b) search for all genetic entities (genes, alleles and aberrations) but then add them to the respective list of genetic entities? i.e. FBgn into the gene list, FBal and FBab into the single allele list

**Comment by kimrutherford** [comment]
I checked this.  The Canto code for finding genes queries the Chado feature table and constrains the search to features with the type "gene".  In the FlyBase Chado DB the alleles features have type "gene".  In PomBase, allele features have the SO type "allele".

Is there something we can add to the query to differentiate between genes and alleles, apart from the FB prefixes?

**Comment by vmt25** [comment]
> Is there something we can add to the query to differentiate between genes and alleles, apart from the FB prefixes?

Allele symbols are formed by the gene symbol prefix followed by the allele name within square brackets/superscripted.
e.g.1 the allele wg[1] is the allele '1' of the gene 'wg'
e.g.2 the allele dpp[d12] is the allele 'd12' of the gene 'dpp'
In fact, 

So, allele symbols always have [] whereas genes do not.

**Comment by kimrutherford** [comment]
Thanks.  I think it makes sense to check for the "FBgn" prefix because there are some gene names that contain square brackets.  eg.
```
 FBal0016326 | su(lz[34])[1]
 FBgn0003568 | su(lz[34])
```

**Comment by kimrutherford** [comment]
> In the FlyBase Chado DB the alleles features have type "gene".

In the latest FlyBase Chado, alleles have SO type "allele" so this issue is solved.
