### ISSUE TITLE
Adapt current genetic interactions to allow genotype-to-genotype associations

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1891]
FlyBase will need to make annotations same gene genotype-to-genotype relationships to describe whether e.g. a full-length wild-type transgene can rescues a loss-of-function 'diploid' mutant.

To explore that, I configured my local test canto so that an 'interaction' data type used genotypes instead of genes. Instead of making the genotype-to-genotype associations I was expecting, Canto tries (and fails) to make a genotype-to-gene associations:

Here are the canto_deploy.yaml lines:

<img width="641" alt="Screen Shot 2019-05-23 at 16 57 02" src="https://user-images.githubusercontent.com/33721108/58267665-ff594280-7d7b-11e9-89c8-31acde569d50.png">

Running canto I can select the type of annotation I configured:

<img width="654" alt="Screen Shot 2019-05-23 at 16 59 50" src="https://user-images.githubusercontent.com/33721108/58267843-43e4de00-7d7c-11e9-8bc1-3e8fdf790e1b.png">

I manage to select the right 'evidence code'/relationship:

<img width="437" alt="Screen Shot 2019-05-23 at 17 02 24" src="https://user-images.githubusercontent.com/33721108/58268019-91f9e180-7d7c-11e9-920e-4f61eed0ea39.png">

But then can only pick genes instead of genotypes, and the annotation fails:

<img width="1059" alt="Screen Shot 2019-05-23 at 17 07 04" src="https://user-images.githubusercontent.com/33721108/58268399-48f65d00-7d7d-11e9-9e12-2a286e5895a6.png">

Would this be easy to fix?

**Comment by kimrutherford** [comment]
> Would this be easy to fix?

This would need changes at the database level because an interaction can only reference genes at the moment.

I think Val has some ideas about how we could implement this so let's have a chat about it on the next Skype call.

**Comment by vmt25** [comment]
Sounds good

**Comment by ValWood** [comment]
Yes let's discuss this on the next call.  it will be really hepful to us to roll the existing GI interface so that  it is don as an extra curation type for multi-allele phenotypes.

Otherwise I often end up having to do the additional annotation to get the specific mutant and phenotype details...
like here:
https://curation.pombase.org/pombe/curs/396866ab84f69995/ro

**Comment by kimrutherford** [comment]
Can we close this in favour of: #1915 ?

**Comment by kimrutherford** [comment]
> Can we close this in favour of: #1915 ?

I've done that now.
