### ISSUE TITLE
automagically generate names

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1892]
some of the new methods make it really easy to generate suppressors, so increasingly we will have tonnes of mutants (even more than already)

![names](https://user-images.githubusercontent.com/7359272/58379940-432d9100-7fa2-11e9-9b67-44cfaec6105d.jpg)

I would like it if
1) I add the  description, the name is populated automatically

I.e
if I say this is a amino acid change in pli1

![populate name](https://user-images.githubusercontent.com/7359272/58379968-a15a7400-7fa2-11e9-829b-5216f973543a.jpg)

the name
pli1-S308P appears but can be edited if the user calls it something else.

It might then be better for users if the order was
type
description
name

because they won't know that if they go straight to "type" it gets prefilled.

**Comment by kimrutherford** [comment]
> It might then be better for users if the order was

That makes sense except that the name field an auto-complete.  So if you set the type and description and then auto-complete a name, the type will change.  Could that be confusing?

**Comment by ValWood** [comment]
good point. that's why name is at the top...

keep the order as it is.

**Comment by ValWood** [comment]
if this is possible (and quick) can we do it fairly soon?

I just realised these sessions are difficult to interpret when i didn't add the name:

https://www.pombase.org/reference/PMID:29352077

I could go back in and do it...but there are tonnes in these papers....so i'd rather not...

**Comment by kimrutherford** [comment]
Just to check, would you like this done when loading into Chado (so they display correctly on the website) or add the functionality to Canto?  To to it in Canto we'd also need to fix up the existing sessions.

Fixing when loading into Chado is a little bit easier.

**Comment by ValWood** [comment]
In canto. All existing should have both the BP already if they have the extension.

I'd be interested if we have any which have the extension but not the  BP annotation instantiated. If you can find these and give me a list I should be able to fix manually, because there shouldn't really be any....

**Comment by kimrutherford** [comment]
> All existing should have both the BP already if they have the extension.

Which extension?  Was that comment on the wrong issue?

**Comment by ValWood** [comment]
yes wrong ticket

**Comment by ValWood** [comment]
Actually, it was the right ticket, but I thought the question was realted to another ticket so I misinterpreted. Deleting and starting again!

**Comment by ValWood** [comment]
I think it could be at the Chado loading point.... in canto would be better eventually but much lower priority...

**Comment by kimrutherford** [comment]
Could you let me know which allele types this should apply too?  Is it just the allele types that have a residue change?

Here's the list:

  - wild type
  - deletion
  - disruption
  - unknown
  - amino acid insertion
  - amino acid substitution(s)
  - amino acid insertion and substitution
  - amino acid insertion and deletion
  - partial deletion and amino acid change
  - partial deletion, amino acid
  - nucleotide insertion
  - nucleotide substitution(s)
  - partial deletion, nucleotide
  - nonsense mutation
  - other

**Comment by ValWood** [comment]
- [x] n/a already does cdc2+ - wild type
 - [x]  n/a  already does cdc2delta - deletion
 - [x]  n/a  a prompt is given with Required for this allele type - disruption
  - unknown
  - amino acid insertion
  - amino acid substitution(s)
  - amino acid insertion and substitution
  - amino acid insertion and deletion
  - partial deletion and amino acid change
  - partial deletion, amino acid
  - nucleotide insertion
  - nucleotide substitution(s)
  - partial deletion, nucleotide
  - nonsense mutation
  - other

**Comment by ValWood** [comment]
in summary I think we should only do for these 2

amino acid insertion - use provided allele description preceded by xxx1-
amino acid substitution(s) - use provided allele description preceded by xxx1-

**Comment by ValWood** [comment]
Only if name is blank at the start

**Comment by ValWood** [comment]
Kim suggested an "autoname" button
