### ISSUE TITLE
show more entries by default in allele search

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1893]
![see more](https://user-images.githubusercontent.com/7359272/58381615-cd7ff000-7fb6-11e9-8680-6b94bc9c57d1.jpg)

and/or ideally some way to know that not all are showing (I often  think alleles are not present which already exist)

**Comment by ValWood** [comment]
i.e. here  G777E

**Comment by kimrutherford** [comment]
It's easy to make it longer. Is currently it shows 10 completions.  Should we change to 15?  20?

**Comment by ValWood** [comment]
Let's try 15.....

**Comment by kimrutherford** [comment]
> Let's try 15.....

That's done now.

**Comment by ValWood** [comment]
I would not mind seeing more... this doesn't feel like too many and because I type the gene name first (maybe I should stop this habit!) I always fill 15 if there are lots.

Anyway does anyone object if we go to 20?

**Comment by kimrutherford** [comment]
> Anyway does anyone object if we go to 20?

I've increased it to 20.

**Comment by ValWood** [comment]
OK thanks! better ;)
