### ISSUE TITLE
difficult to distinguish individual genotypes in this view

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1894]
1. The heading says "single-allele genotypes" but this is both single and multi
 2. It is difficult  to see which are single and which multi because there is no separation

I prefer  sorting single then multi with a separate header (can still be a single table)

**Comment by ValWood** [comment]
![hard](https://user-images.githubusercontent.com/7359272/58383645-44c27d80-7fd1-11e9-9bc8-c7f8c8adc4c5.jpg)

**Comment by ValWood** [comment]
![not only single allele](https://user-images.githubusercontent.com/7359272/58383654-53109980-7fd1-11e9-8c5a-82fb40491657.jpg)

**Comment by kimrutherford** [comment]
> The heading says "single-allele genotypes" but this is both single and multi

I've changed it to say "Genotype" for now.

**Comment by jseager7** [comment]
@ValWood would the ideal case be if you had separate tables for single and multi-allele genotypes, meaning the same display that we use on the Genotype Management page?

**Comment by ValWood** [comment]
a sub heading will probably fine: that was done here for haploid diploid 
https://github.com/pombase/canto/issues/1870

Otherwise we end up spawning lots of tables

**Comment by ValWood** [comment]
@kimrutherford  did you make some changes/improvements to this table recently via another ticket?

**Comment by kimrutherford** [comment]
>  did you make some changes/improvements to this table recently via another ticket?

There's this one, but I haven't checked in the changes yet: #1955

**Comment by ValWood** [comment]
OK I think that covers this ticket.
