### ISSUE TITLE
warning for  exact duplicate annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1895]
AS a sanity check I would like a warning when I try to create duplicate annotations

![duplicate](https://user-images.githubusercontent.com/7359272/58383666-6de30e00-7fd1-11e9-9c6b-84bdb7f395ab.jpg)

**Comment by ValWood** [comment]
https://github.com/pombase/canto/issues/1205
is sort of duplicate, closing

**Comment by ValWood** [comment]
We can't use "duplicate and edit", without changing anything.
However, it is possible to duplicate and edit, and make a duplicate of an existing annotation.

Sometimes, also when I am approving, if there are a lot of annotations I notice that I have made identical annotations to the community curator.

So we also need to know exact duplicates where everything is identical bar the curator

**Comment by kimrutherford** [comment]
I've had a first attempt at fixing this.  The changes are only in the test Canto for now until I've done a bit more testing.

**Comment by kimrutherford** [comment]
When you get a chance could you give this a test?  It's still only enabled in the test Canto.

I implemented it in a conservative way because I didn't want any bugs where a user couldn't make an annotation due to Canto mistakenly deciding there was a duplicate.  So there maybe still be cases where a duplicate is possible.

**Comment by ValWood** [comment]
I was able to create an exact duplicate of a FYPO term:

<img width="1103" alt="Screenshot 2022-07-28 at 11 35 37" src="https://user-images.githubusercontent.com/7359272/181485675-9fd0e12a-bad6-4ea8-abd9-7e5c7a9cd87f.png">

**Comment by ValWood** [comment]
https://curation.pombase.org/pombe/curs/4666975359de04dd

**Comment by kimrutherford** [comment]
It's only enabled in the test Canto.

**Comment by ValWood** [comment]
Sorry I thought I was using test. I will try again

**Comment by ValWood** [comment]
I can't seem to log into test. Tried for 3 mins

**Comment by kimrutherford** [comment]
> I can't seem to log into test. Tried for 3 mins

Could you try again?
Looks like I broke things trying to fix https://github.com/pombase/canto/issues/2596
I've reverted that change and I'll investigate in the morning.

**Comment by ValWood** [comment]
That works. I tested swapping to match  existing GO annotations by changing gene, term or evidence code.

I tested phenotypes too.

**Comment by kimrutherford** [comment]
Thanks for testing. I'll deploy it on the main site in the (UK) morning.

**Comment by kimrutherford** [comment]
> I've reverted that change and I'll investigate in the morning.

It looks like a temporary problem that's now fixed.

**Comment by kimrutherford** [comment]
> I'll deploy it on the main site in the (UK) morning.

That's done now.  Let me know if you see any problems.

**Comment by vmt25** [comment]
Hi @kimrutherford 
Thanks for looking into this.

Duplicates are not created when making annotations from scratch or from Copy/edit.

However, I found a couple of issues when using the Transfer functionality:
a) for regular 'ontology' annotations, duplicate s are not created but Canto still shows the green banner with the message "Annotation stored successfully."
b) for genetic interaction annotations, duplicates are still being created

**Comment by kimrutherford** [comment]
> a) for regular 'ontology' annotations, duplicate s are not created but Canto still shows the green banner with the message "Annotation stored successfully."

Thanks for testing.  I'll fix that on Monday.

> b) for genetic interaction annotations, duplicates are still being created

I've made a separate issue about that: #2603

**Comment by kimrutherford** [comment]
> for regular 'ontology' annotations, duplicate s are not created but Canto still shows the green banner with the message "Annotation stored successfully."

I've improved the code so that shows a notification about duplicates:

![screenshot-2022-08-08_16-41](https://user-images.githubusercontent.com/90474/183343653-30025798-6a0c-4b7f-8e36-08b149a1a42e.png)

![screenshot-2022-08-08_17-07](https://user-images.githubusercontent.com/90474/183343660-adea2b1c-814e-4ba8-a06a-101ff0a1f6c5.png)

**Comment by vmt25** [comment]
Hi Kim, 
Transfer of straight 'ontology' annotations now shows the correct blue 'banner' warning it is not storing the annotation because it is a duplicate! Thanks
