### ISSUE TITLE
change warning message for "unused genotypes"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1897]
Instead of saying
Warning: there are 19 unused genotypes in this session

we could only report the ones which are not used in annotated genotypes.

this would usually over-ride the message?

**Comment by kimrutherford** [comment]
Just to be clear, do you only want to warn about single allele genotypes with no annotation where the allele isn't used in a multi allele genotype?
And include multi-allele genotypes with no annotation.

**Comment by ValWood** [comment]
Yes. We should discuss though with @mah11 @Antonialock - I thinnk it makes sense to do this, and would be more useful

**Comment by Antonialock** [comment]
no objection..

**Comment by ValWood** [comment]
I just approved a session with an unused genotype and did not get a warning, so I presume we no longer display this warning. I don't think we need it because there are often unused genotypes, so closing. Reopen if I misunderstood.
