### ISSUE TITLE
add search genotype, in addition to browse?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1900]
I would like to be able to search on genotypes (well filter I guess), to the subset with a particular allele. It' gotten unwieldy. I have done 5 of these in the past week. one you made the genotype table finding the specific alleles is really difficult.

Especially as you can't see them all at once and many are quite similar..

![need another way](https://user-images.githubusercontent.com/7359272/58544241-c5af8e00-81f8-11e9-9cad-05c24217c94e.jpg)

**Comment by ValWood** [comment]
This will happen as part of PHI base changes.

we would like to 
i) still be able to browse,
but
b) have the option to autocomplete on a substring

**Comment by kimrutherford** [comment]
> b) have the option to autocomplete on a substring

This could be a search button/icon that changes the dropdown into an autocomplete field.

**Comment by kimrutherford** [comment]
> This could be a search button/icon that changes the dropdown into an autocomplete field.

Note to self: we can use the jQuery autocomplete like we do for term name completion.

**Comment by ValWood** [comment]
Required for genetic interaction work. Removed low priority

**Comment by kimrutherford** [comment]
I've had a go at this.  There is now a search icon beside genotype selectors that turns the selector into an completion field.  If you click on search icon with a line through you go back to the dropdown.  Please let me know if you have a better idea for that.

This change is in the flybase-test and the PomBase test instances.

https://curation.pombase.org/flybase-test
https://curation.pombase.org/test

![genotype-autocomplete-1](https://user-images.githubusercontent.com/90474/62209486-d7c2ce00-b3ed-11e9-85a1-fdb617c35bde.png)

![genotype-autocomplete-2](https://user-images.githubusercontent.com/90474/62209496-df827280-b3ed-11e9-90b5-4428b68374e4.png)

![genotype-autocomplete-3](https://user-images.githubusercontent.com/90474/62209499-e27d6300-b3ed-11e9-958e-8277014b83a6.png)

**Comment by ValWood** [comment]
Great.

Comments:
1. It all works well, but I'm not sure that people will notice the search option, or know that it is an alternative.... the first time I forgot what I was supposed to be looking at and this was quite easy to ignore. Maybe it needs to be clearer that there is a choice, pull down OR search

2. That said,   should the search options be all alleles available for genes in the session, or only all alleles in the session. If only all alleles in the session (as now) is there a  great advantage to having the search option? Or is this only really  for when the lists are very long? 

3. It wasn't very clear for me what the red slash over the active search was for ...

these might all be non-issues

**Comment by kimrutherford** [comment]
> but I'm not sure that people will notice the search option

I think it's only going to be needed by advanced users with dozens of genotypes so maybe that's not a problem?

> Or is this only really for when the lists are very long?

I think so.  Like in the screenshot from your initial comment.

> It wasn't very clear for me what the red slash over the active search was for ...

I'm not keen either.  I'll have a think about a better way of doing it.

**Comment by kimrutherford** [comment]
> I'll have a think about a better way of doing it.

I've made some slight tweaks.  The icon with the red slash is now a cross which I hope is more obvious.  Also after you select a genotype from the autocomplete list, it switches back to the dropdown.  So the "Finish search" icon/button shouldn't be as necessary.

**Comment by ValWood** [comment]
That's better.

**Comment by kimrutherford** [comment]
> That's better.

Great.  I'll close this and we can open new issues for changes.  This feature is only in the test and flybase Canto instances for now.
