### ISSUE TITLE
retain checked alleles after multi-allele genotype creation

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1902]
After you have selected 2 alleles to make a combined genotype, the checked boxes disappear.

I'd really like them to stay, because usually I just want to move one allele down to the next gene in the list.

Currently, I lose my place and need to re-find both alleles, and then move down one.

The worst that could happen is that a user tries to recreate an existing allele, but  I think this isn't possible anyway?

![retain checked boxes after combining selected](https://user-images.githubusercontent.com/7359272/58549233-f694c080-8202-11e9-87cd-d2d75e59b1aa.jpg)

**Comment by kimrutherford** [comment]
I've changed it to stay selected.  Do you remember why you wanted you wanted them to unselect?:
  https://github.com/pombase/canto/issues/1381#issuecomment-378980231

**Comment by ValWood** [comment]
I don't  know if we specifically requested it this way. Initially it might seem more intuitive to unselct (after all you did the action), but in light of the fact that we often do multiple commbonations by working through a list I think this will be much better.

Will see if @mah11  or @Antonialock  object for any reason.

**Comment by Antonialock** [comment]
I think I'd prefer them to unselect after combining......at least maybe nice to have a button to unselect all

**Comment by ValWood** [comment]
Hmm, good point --if you have a genotype with a lot of alleles it would be a pain.
Can we try with the current set up and a "unselect all" button to see if it's a good trade-off?

**Comment by kimrutherford** [comment]
I've added an "Unselect all" button.

**Comment by kimrutherford** [comment]
I forgot to say, the "Unselect all" link only appears when you select something.

**Comment by ValWood** [comment]
I think we will need to rethink this. It works well for me but it isn't going to work for everyone. I predict that  @mah11  is going to hate it.

It might work better as an admin option that could be toggled-"on"  on a session by session basis.

**Comment by mah11** [comment]
You know me well ;)

I've had plenty of opportunity to test this out now, and indeed I don't much like it.

For pairwise combinations, it doesn't save any clicks (it's fewer clicks only where there are three or more alleles combined, and you change one at a time).

For any combinations, it requires you to do something to remove all or part of the genotype you just created, and that adds mental effort.

It really doesn't fit my thought processes to have to remember anything about the previous genotype when I move on to the next one; I'd much rather have a "clean slate" for each one. I don't encounter genotypes with three or more alleles often enough for the additional clicks they'd require to outweigh the advantage of an interface that matches what I'm subconsciously expecting.

**Comment by vmt25** [comment]
I agree with Midori that you have to keep track of what is already ticked, but it can be very useful. As an example, it is very common in flies to use a transgene of interest with an array of drivers of expressions, so it would be useful to keep one allele selected while selecting/de-selecting the partner.

I am trying to think of a good way of having the best of both worlds, but nothing comes to mind

**Comment by ValWood** [comment]
I'm closing this ticket with  the current behavior to retain the checked boxes. 
For me it works well if you are combining. one allele with every other allele in the list to see the ones you chode last still checked.
 I'm happy for anyone to open a ticket with an improved suggestion though!
