### ISSUE TITLE
Add a script to check for Canto schema mismatch

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1904]
Currently, attempting to restart Canto after a schema change (meaning, after pulling from `pombase/canto`) causes Canto to not start. It's difficult to tell if the schema has changed until Canto fails, so it would be nice if we had some utility script that can check for a schema mismatch. This could allow us to forbid Canto from restarting in a server environment if it will be unable to start again without upgrading, or handle the upgrade automatically when needed.

**Comment by kimrutherford** [comment]
I've added a script: `etc/check_matching_schema.pl `

It takes no arguments and exits with 0 if the code matches the database schema.  It exits with 1 (failure) otherwise.

You should be able to use it like this:

```sh
if ./etc/check_matching_schema.pl
then
   echo all good - schema matches
else
   echo very bad - schema doesn't match
fi
```
