### ISSUE TITLE
where does this  allele name come from

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1906]
![where does name come from](https://user-images.githubusercontent.com/7359272/58629773-49d74380-82d5-11e9-81ab-36daa31dd0c7.jpg)

(it isn't in the session)

I will fix thse up manually once we know this...

**Comment by ValWood** [comment]
referring to G779D

**Comment by kimrutherford** [comment]
It's here: https://curation.pombase.org/pombe/curs/e674fe7ceba478aa/genotype_manage/ro

**Comment by ValWood** [comment]
I guess here because I though most were new , and to save time, I go to the description first.

In this case it would be good to autopopulate in the session if the description matches another session?

So do I need to fix this name in both places?

**Comment by ValWood** [comment]
I fixed all the eso1's in 
 https://curation.pombase.org/pombe/curs/e674fe7ceba478aa/genotype_manage/ro

so I will see what happens to my session. I might go in and add the names to this ...

**Comment by ValWood** [comment]
I don't understand this ticket so closing
