### ISSUE TITLE
update Canto Home page

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1908]
We should add PHI-BAse and FlyBAse as users here:
https://curation.pombase.org/

Is there a demo version of the multi-organism version we could host  too?

**Comment by kimrutherford** [comment]
> We should add PHI-BAse and FlyBAse as users here:

OK, I'll do that when I get a chance.

> Is there a demo version of the multi-organism version we could host too?

That's the "Generic Gene Ontology Implementation" version on the front page.  It hasn't been updated in ages though.

**Comment by ValWood** [comment]
Is there a demo version of the multi-organism version we could host too?

I ment for pathogen-host interactions (to showcase to  others in the pathogen community). I'm am hoping I can show people at the GO users meeting which is microbial focussed (late Oct)

**Comment by kimrutherford** [comment]
@jseager7 Can Val show one of your Canto instances at the GO meeting?  Even better can we add a permanent link from the Canto front page to a demo PHI-Canto instance?

**Comment by jseager7** [comment]
@kimrutherford Sure, I don't have any problems with PHI-Canto being demonstrated. I don't use the demo server as a sandbox or anything, so it should be as stable as the production server. Also, I think adding a permalink on Canto's landing page is a good idea (and CuzickA agrees).

**Comment by kimrutherford** [comment]
> Also, I think adding a permalink on Canto's landing page is a good idea (and CuzickA agrees).

Great.  I'll add a link to https://demo-canto.phi-base.org/

Val, what should we say about the FlyBase Canto?  Does it make sense to link to the flybase-test Canto instance?

**Comment by ValWood** [comment]
In collaboration with Rothamsted Research, we are extending Canto to enable the curation of pathogen-host interaction  (multispecies) phenotypes  and genotypes [ test button]

fro flybase we can just add text:

We are currently developing a Canto instance to support FlyBase phenotype  and genetic interaction annotation 

I think we should put  PHIPO at the top.

**Comment by kimrutherford** [comment]
Thanks for the text.

> I think we should put PHIPO at the top.

Do you mean PHI-Canto?

**Comment by ValWood** [comment]
doh

**Comment by kimrutherford** [comment]
> I think we should put PHI-Canto at the top.

Do you mean top after PomBase canto?

How's this?:
![canto-in-use-1](https://user-images.githubusercontent.com/90474/64249986-1574c280-cf69-11e9-8fb1-842892eb4c48.png)

**Comment by ValWood** [comment]
Yes, go for it.

**Comment by kimrutherford** [comment]
Done.
