### ISSUE TITLE
fonts

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1910]
current font library doesn't recognise quite a few special characters.

For eg

Pivoting of microtubules driven by minus-end-directed motors leads to spindle assembly.
--
Authors: | Winters L, Ban I, PrelogoviÄ M, Kalinina I, Pavin N, ToliÄ IM

Iva Tolić 

oddly it recognises in some places (Tolić  is from name store)

**Comment by kimrutherford** [comment]
Which session was that?

**Comment by ValWood** [comment]
pub/12712?model=track

but I noticed a few recently
pub/12666?model=track
PÃ©rez P, Soto T, GÃ³mez-Gil E, Cansado J !


pub/12638?model=track
Duempelmann L, Mohn F, Shimada Y, Oberti D, Andriollo A, Lochs S, BÃ¼hler M

oddly, it's not even consistent for authors!
view/object/pub/12331?model=track
Klemm AH, Bosilj A, Gluncˇic M, Pavin N, Tolic IM

**Comment by kimrutherford** [comment]
Thanks.  I'll look into that.

> oddly, it's not even consistent for authors!

I think that's because it's "Tolic" in PubMed:
https://www.ncbi.nlm.nih.gov/pubmed/29851559

**Comment by ValWood** [comment]
closing, duplicate of
https://github.com/pombase/canto/issues/1785
