### ISSUE TITLE
Add option to update Canto database to latest version

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1912]
Currently the database upgrade script (`upgrade_db.pl`) can only upgrade one schema version at a time, and there doesn't seem to be any option to automatically run all the schema updates sequentially to bring the database to the latest version. This would be useful to have in the case where Canto's source code is automatically updated.

Ideally the script would allow an option like this:
```
upgrade_db.pl latest
```
Which would run all the schema upgrades in sequence.

**Comment by kimrutherford** [comment]
I've added a "latest" argument.  If there are no database upgrades to do it reports something like "Database is up to date at version 29".
