### ISSUE TITLE
Hide gene and organims columns from all genotype and phenotype tables in Fly-canto

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1914]
Please hide the gene column from the genotype and phenotype tables in Fly-canto.
Please also hide the organims column from the phenotype tables in Fly-canto.

These are not necessary because both the organism and the gene symbols are encapsulated in the full allele symbol, in the form of: species abreviation\gene symbol[allelename]

For Drosophila melanogaster genes, the species abbreviation is ommited.

e.g. Scer\GAL4[VP16.nos.UTR]
  Scer is the abreviation of the species saccharomyces cerevisiae (even though Canto assumes all species are Drosophila melanogaster)
  GAL4 is the gene symbol
  VP16.nos.UTR is the allele name

e.g. grau[QE70]
  is a Dmel gene
  grau is the gene symbol
  QE70 is the allele name

**Comment by kimrutherford** [comment]
> Please hide the gene column from the genotype and phenotype tables in Fly-canto.
> Please also hide the organims column from the phenotype tables in Fly-canto.

I think these are done now.  I added an option ("show_genotype_management_genes_list") for hiding the genes a while ago but forgot to comment.

Hiding the organisms needed a configuration change which I've just made to the flybase-test Canto.

Vitor, here are the settings in case you'd like to add them to your local Canto:

```yaml
show_genotype_management_genes_list: 1

instance_organism:
   taxonid: 7227
```

(The spaces before "taxonid:" are needed.)

**Comment by vmt25** [comment]
Hi.
Looks good.
FlyCanto is not showing the organisms anymore but the gene is still showing up - did you push the config into fly-canto?
(but this is not a priority, so no worries)

**Comment by kimrutherford** [comment]
> FlyCanto is not showing the organisms anymore but the gene is still showing up - did you push
> the config into fly-canto?

I removed the genes table at the left but forgot about the genes column.  I'll remove that column next time I'm working on the genotypes table.

**Comment by vmt25** [comment]
Thanks!

**Comment by kimrutherford** [comment]
> Hiding the organisms needed a configuration change which I've just made to the flybase-test Canto.

Unfortunately that triggered a bug in the annotation editing dialog which made it unusable.  So I've changed the configuration back temporarily while I fix the problem.

**Comment by kimrutherford** [comment]
> Unfortunately that triggered a bug in the annotation editing dialog which made it unusable. So
> I've changed the configuration back temporarily while I fix the problem

That's fixed so the organism is not shown in the annotation tables any more.

**Comment by kimrutherford** [comment]
I think this is done now.  Please re-open or open new issues if there other places that need fixing.
