### ISSUE TITLE
FlyBase genetic interaction / genotype-genotype interactions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1915]
Draft specification and mock up here:

Seems fairly straightforward
https://docs.google.com/document/d/1f3LeVtYe_S1R2weyFIe-cehnQR2b-uLHaqsgQxcClc4/edit

@mah11  @Antonialock 
We need to figure how much of this PomBAse can use. We will use this  mechanism for complementation (as will PHIBase)

**Comment by ValWood** [comment]
when this is implemented, can  we add as admin only option for PomBAse in the first instance.
I'm saving genetic interaction creation for this session
PMID:31089172

session to test, since it has a lot of multi-gene synthetic lethals (inviable popularion[henotypes), that I can create synthetic lethal genetic interactions for.

We should discuss how this will work.
Should we put these into a new table (temporarily called genetic interactions II), and make this supersede the old table once we are happy that it isn't lossy. Or should we just add the additional columns to the existing table.

**Comment by ValWood** [comment]
We had a couple of long chats with the full team, and after going around the houses a few times we would like to suggest:

https://docs.google.com/document/d/1lQhZyB9D_R1-XLvrZDIDqmmW67rLouSZZ4J8HEG6ucM/edit

which we think should be the simplest way to get everything up and running quickly and robustly and then revisit  your enhancer/supressor  proposal as a "short cut" at a later date.

**Comment by ValWood** [comment]
@kimrutherford @Antonialock @mah11  please look and see if I missed anything we discussed. I tried to keep to the main points so I didn't include everything, but this should cover anything which affects  basic functionality to get this up and running.

**Comment by vmt25** [comment]
> We had a couple of long chats with the full team, and after going around the houses a few times we would like to suggest:
> 
> https://docs.google.com/document/d/1lQhZyB9D_R1-XLvrZDIDqmmW67rLouSZZ4J8HEG6ucM/edit
> 
> which we think should be the simplest way to get everything up and running quickly and robustly and then revisit your enhancer/supressor proposal as a "short cut" at a later date.

Went through the file and, at a first glance, the proposal seems to fit specs... and deal well with new and pre-existent annotations.

**Comment by kimrutherford** [comment]
I've started work on this. This is a slightly working, slightly mock version of the new interaction dialog.  Apologies for the random data in the fields.

![interaction-update-1](https://user-images.githubusercontent.com/90474/59601996-c41f1900-9159-11e9-97ca-6ee3df52ed9e.png)

Val, is that sort of what you were thinking of?

**Comment by ValWood** [comment]
yes!
I'm not sure of the best way to  allow browse and "search" for  genotypes, but  it seems that there might be space to have a (narrower)  pull down  and then OR  [search ] right next to it?

**Comment by kimrutherford** [comment]
>  OR [search ] right next to it?

Like this?:

![interaction-update-2](https://user-images.githubusercontent.com/90474/59633730-48e15580-91a1-11e9-85ee-3bc79670d143.png)

I was thinking that if you click the search icon, the dropdown could change to an autocomplete.

**Comment by kimrutherford** [comment]
Now I've done a bit on this I have some questions.

 - How do we display the existing gene-gene interactions?
 - What columns do we need for the genotype-genotype interaction tables?
 - Will we need to display two sorts of interaction table? ie.
     - existing gene-gene interactions
     - new genotype-genotype interactions
 
And from the Google Doc, what should interface look like?:
> i) present existing phenotypes of genotype B
>	allow selection 
> or dismissal  and go to iii)

**Comment by vmt25** [comment]
I really like the interface mock-up.



> Now I've done a bit on this I have some questions.
> 
>     * How do we display the existing gene-gene interactions?
> 
>     * What columns do we need for the genotype-genotype interaction tables?
> 
>     * Will we need to display two sorts of interaction table? ie.
>       
>       * existing gene-gene interactions
>       * new genotype-genotype interactions
> 
> 
> And from the Google Doc, what should interface look like?:
> 
> > i) present existing phenotypes of genotype B
> > allow selection
> > or dismissal  and go to iii)

Not completely sure about some of these issues; Lets chat in the meeting.

**Comment by ValWood** [comment]
I imagined

![browse or search](https://user-images.githubusercontent.com/7359272/59688123-ee61ec80-91d4-11e9-9b8e-6319d6fa1b06.jpg)

**Comment by ValWood** [comment]
i.e.  both options very prominent and obvious that it was a choice...

**Comment by kimrutherford** [comment]
> i.e. both options very prominent and obvious that it was a choice...

I'm not keen on having both visible at the same time because it will show two genotypes, one on the left and one on the right.

**Comment by ValWood** [comment]
So, in your scenario the users would  use the pull down, but if they click on the magnifier the pull down is replaced by a search option? If so  OK let's do that.

**Comment by kimrutherford** [comment]
> So, in your scenario the users would use the pull down, but if they click on the magnifier the pull down
> is replaced by a search option? If so OK let's do that.

Yep!

**Comment by kimrutherford** [comment]
Kim's list of things to do:
  - [ ] fix the annotation edit dialog  - STATUS: partly done, enough for testing the other changes
  - [ ] store the annotation in the Canto database  - STATUS: partly done
  - [ ] fix server code to understand the new annotation type when it is queried from the DB for display
  - [ ] fix Javascript and HTML to display the annotations in tables

**Comment by kimrutherford** [comment]
The new interaction system is progressing.  The interaction editing dialog works enough to store an interaction with a phenotype and extensions:

![interaction-update-3](https://user-images.githubusercontent.com/90474/60085561-a2dbaf80-978d-11e9-87cc-7fd5d06cc225.png)

The interaction is stored correctly in the database and shows up in the annotation tables:

![interaction-update-4](https://user-images.githubusercontent.com/90474/60085649-cdc60380-978d-11e9-9f13-9a885c78e75c.png)

There a quite a few bugs which I'm working on but it's a start.

**Comment by vmt25** [comment]
Very nice!

**Comment by kimrutherford** [comment]
The Canto test instance is now using the new code.  Unfortunately older sessions in the test server that contain interactions are likely to fail to load (for now) so I made a new session for trying the new style interactions: https://curation.pombase.org/test/curs/29ee7a6a21e59752

> There a quite a few bugs which I'm working on but it's a start.

That's still true.  :-)

Currently you can create a new interaction, edit it, or edit and copy.  There's lot's to do.  See my comment above for progress: https://github.com/pombase/canto/issues/1915#issuecomment-505252447

**Comment by kimrutherford** [comment]
Hi @jseager7.

As promised I've done some testing of the new interaction system in PHI mode and it's mostly OK.
I've updated the to-do list and I'll work on the remaining issues on Monday:
https://github.com/pombase/canto/issues/1915#issuecomment-505252447

When you get a chance next week could you try this code and see if there are any major problems?

One chance from the current phenotype annotation code is that the strain name is included in the feature selector:

![interaction-update-6](https://user-images.githubusercontent.com/90474/60328966-791bc600-99e3-11e9-9f12-b83ed429baae.png)

**Comment by jseager7** [comment]
@kimrutherford This looks good from the screenshot &ndash; and it also looks like a good solution that could be re-used when editing PHI-Canto phenotype annotations (see https://github.com/pombase/canto/issues/1925). Do you think it would take much work to apply this fix to the edit dialog?

I'm going to try testing this in PHI-Canto now. I'll open issues if I find any major problems.

**Comment by kimrutherford** [comment]
> Do you think it would take much work to apply this fix to the edit dialog?

The edit dialog more or less works now.  Do you mean change the dialog to edit PHI annotations using this new method?  It shouldn't be to much work.  Maybe a day of code changes and then a day of bug fixing.  :-)

> I'm going to try testing this in PHI-Canto now. I'll open issues if I find any major problems.

Thanks!

**Comment by jseager7** [comment]
> Do you mean change the dialog to edit PHI annotations using this new method?

I mean the edit dialog for pathogen phenotype and host phenotype annotations, yes. The dialog for pathogen-host interaction annotations probably doesn't need changing, because we're not allowing changes to the underlying genotypes of a metagenotype yet.

**Comment by kimrutherford** [comment]
I'm working on allowing interactions to not have a phenotype.  It's mostly working except that if you edit an interaction that has a phenotype, then remove the phenotype, the edit is ignored.  Should have that working too soon.

**Comment by kimrutherford** [comment]
> I'm working on allowing interactions to not have a phenotype. 

That's done now and the changes are in the test Canto.  Here's a session if you'd like play around with the changes: https://curation.pombase.org/test/curs/29ee7a6a21e59752

I'm going to do this next:
> fix annotation tables on the gene pages

then:
> write the code to convert old gene-gene interactions in to genotype-genotype interactions
> when the database is upgraded

**Comment by kimrutherford** [comment]
I don't think we've discussed complementation yet in detail yet.  I don't think it's a lot of extra work but I'd like to have a chat about it soon-ish to make sure that the database changes for interactions will also work for complementation.

**Comment by kimrutherford** [comment]
Is the Conditions field needed in the case where the phenotype is blank?  Or should it be hidden until a phenotype is selected?

**Comment by ValWood** [comment]
Hidden until a phenotype is selected would be good

**Comment by kimrutherford** [comment]
> Hidden until a phenotype is selected would be good

Thanks.

I've also changed the code to clear the extension and conditions if you remove the phenotype from an interaction.

**Comment by vmt25** [comment]
> That's done now and the changes are in the test Canto. Here's a session if you'd like play around with the changes: https://curation.pombase.org/test/curs/29ee7a6a21e59752

Hi Kim,

I've been trying to access these test sessions but they do not exist.

I've also been trying to create genetic interactions in the test fly-Canto but can only create old style gene-to-gene genetic interactions.

**Comment by kimrutherford** [comment]
Hi Vitor.

I had to re-create the test Canto database to fix a bug.  Try this session:
  https://curation.pombase.org/test/curs/05284071e0eba01a

> I've also been trying to create genetic interactions in the test fly-Canto but can only create
> old style gene-to-gene genetic interactions.

I haven't updated the Fly Canto yet.  I'll do that tomorrow and yet you know.

**Comment by vmt25** [comment]
> I don't think we've discussed complementation yet in detail yet. I don't think it's a lot of extra work but I'd like to have a chat about it soon-ish to make sure that the database changes for interactions will also work for complementation.

For FlyBase, this would be a simple genotype-to-genotype relationship, without specifying a phenotype. This is similar to Pombase's current genetic interactions scheme, but using genotypes instead of genes

e.g. genotype_A - rescued - genotype_B

This is mocked in #1981

**Comment by vmt25** [comment]
> Hidden until a phenotype is selected would be good

yes, please

**Comment by kimrutherford** [comment]
I've made a separate issue for complementation: #1980

**Comment by vmt25** [comment]
> Hi Vitor.
> 
> I had to re-create the test Canto database to fix a bug. Try this session:
> https://curation.pombase.org/test/curs/05284071e0eba01a
> 
> > I've also been trying to create genetic interactions in the test fly-Canto but can only create
> > old style gene-to-gene genetic interactions.
> 
> I haven't updated the Fly Canto yet. I'll do that tomorrow and yet you know.

Beautiful!


I managed to do interactions beween alleles of the same gene, which should not be allowed in principle. That is what 'diploid' phenotype annotations or rescue/complementation annotations are there for.

Alleles of genes included in genotype A should be excluded from the genotype B dropdown options, but this is complicated when using multiple gene genotypes. We will have to have a think about it.

**Comment by vmt25** [comment]
> I had to re-create the test Canto database to fix a bug. Try this session:
> https://curation.pombase.org/test/curs/05284071e0eba01a

just reporting incoherence in greek symbols between phenotype and interaction annotations (no biggy) -  pol1Δ shows as pol1Δ on the phenotype table and as pol1delta on the interactions table.

**Comment by kimrutherford** [comment]
> I managed to do interactions beween alleles of the same gene, which should not be allowed
> in principle. That is what 'diploid' phenotype annotations or rescue/complementation
> annotations are there for.

That might need to be a configuration setting because I think PomBase does have cases where the two genes in an interaction are the same.  We'll need input from Val and co. on that one.

**Comment by ValWood** [comment]
Hi Kim,
For the genetic interactions we record using this annotation type,  we can safely assume that they are in different genes. We would not curate interacting alleles of the same gene as genetic interactions (although the definitions  of 'genetic interaction' I am reading to confirm, do not exclude these as interactions).

**Comment by kimrutherford** [comment]
> We would not curate interacting alleles of the same gene as genetic interactions

How should we handle the existing interactions where both genes are the same? Do they need to be converted to genotype-genotype interactions?

**Comment by kimrutherford** [comment]
> I haven't updated the Fly Canto yet. I'll do that tomorrow and yet you know.

Sorry for delay.  I've done that now but the configuration isn't right.  For Fly-Canto, which phenotype CV should be used when adding a phenotype term to an interaction?

Because the CV isn't correctly configured, if you try to make an interaction currently it doesn't show the phenotype search field:

![interaction-update-bug-1](https://user-images.githubusercontent.com/90474/61529778-5a569f80-aa76-11e9-8781-47edf4c4f861.png)

**Comment by kimrutherford** [comment]
> For Fly-Canto, which phenotype CV should be used when adding a phenotype term to an interaction?

I've configured it to be FlyBase_anatomy_CV so I can test the dialog.

**Comment by vmt25** [comment]
> > For Fly-Canto, which phenotype CV should be used when adding a phenotype term to an interaction?
> 
> I've configured it to be FlyBase_anatomy_CV so I can test the dialog.

Oh, right... I was about to ask what you meant.

Anatomy CV is fine for interaction testing and I'll give it a go. Let's leave configuring phenotype class annotations (and corresponding interactions) for later.

**Comment by vmt25** [comment]
it is not functional yet, right?
I'm getting a few errors and cannot make phenotype anotations, so that I can then make interaction annotations.

**Comment by kimrutherford** [comment]
> it is not functional yet, right?
> I'm getting a few errors 

What sort of errors are you getting?  Are there any messages?  I've just tried making an interaction and a normal phenotype annotation and it was OK for me.  Here's the session I was playing with: https://curation.pombase.org/flybase-test/curs/2e523d5ee64ea295

> cannot make phenotype annotations, so that I can then make interaction annotations.

You shouln't need to make a phenotype annotation to make an interaction annotation.  You can add the phenotype for the interaction in the dialog when you make the interaction.  Are you creating interactions using the links under the "Quick links" heading?

**Comment by vmt25** [comment]
A few different things - these only refer to phenotype annotations, which were working fine before.

1. At the top, I am asked for the species, which is not necessary for FlyBase - but a) I understand this may be needed fo Pombase and PHI base and b) does not bother for testing purposes

2. I am not asked for extensions, even though these were showing up and working fine before

3. the error red banner shows up with something like 'adding annotation failed - missing evidence code' - this even though I am not asked for an evidence code (and I thoguth we were getting rid of it for FlyBase)

**Comment by vmt25** [comment]
> You shouln't need to make a phenotype annotation to make an interaction annotation. You can add the phenotype for the interaction in the dialog when you make the interaction. Are you creating interactions using the links under the "Quick links" heading?

I know but was trying to make things fresh

**Comment by jseager7** [comment]
I've finally tested this in PHI-Canto, and it seems to work fine. I was able to create a genetic interaction, although I used PHIPO's _pathogen host interaction phenotype_ namespace for the phenotypes, since I didn't have FYPO loaded. I'm not sure which phenotype class would (or should) be applied to genetic interactions if we ever have to actually curate genetic interactions for PHI-base.

Here's an example of the genetic interaction modal:

![genetic_interaction_test](https://user-images.githubusercontent.com/37659591/62121754-30924980-b2bc-11e9-9db3-f27ee751d642.PNG)

And here's the completed annotation table row:

![genetic_interaction_created](https://user-images.githubusercontent.com/37659591/62121765-38ea8480-b2bc-11e9-9438-d8625ee5159f.PNG)

- - -

@kimrutherford There's two issues I've noticed regarding the layout of the genetic interaction annotation table:

* The column order (and naming) doesn't match the order from other annotation tables. (This is actually a problem with single-organism phenotypes and pathogen-host interaction tables too.) It would probably be better for users if the column order was consistent, since it should make checking the annotations easier. Here's an example of what that could look like:

  ![gi_strict_order](https://user-images.githubusercontent.com/37659591/62122354-671c9400-b2bd-11e9-93f6-fc5af06ded3d.PNG)

  However, for genetic interactions, I feel it might be better to keep the 'Evidence' column placed between the genotype columns &ndash; as it currently is &ndash; rather than placing the column in the same place as the other tables.

* I'm not too keen on suffixing both the 'Interactor' and 'Taxon Id' columns with 'A' and 'B', since I think it makes the cell headings a bit too verbose. I also think that the 'Interactor' column would be more obviously labelled 'Genotype'. Maybe we could try using column groups instead, and label the group heading with 'Interactor'? Here's an example:

  ![gi_column_naming_order](https://user-images.githubusercontent.com/37659591/62122277-39374f80-b2bd-11e9-9bf4-d11c4f987ba1.PNG)

If you think this should be in its own issue, let me know and I'll make one.

**Comment by ValWood** [comment]
We should keep the evidence in the middle because the evidence is a little more here- it's also  describing the relationship between interactor A and B (although fir  convenience we just call it evidence)

I like  @jseager7  table layout  for multi organism instance.

**Comment by jseager7** [comment]
> We should keep the evidence in the middle because the evidence is a little more here- it's also describing the relationship between interactor A and B (although fir convenience we just call it evidence)

That's what I suspected. Thanks for clarifying. Do you think that 'Interaction type' or 'Relationship' might be a clearer name for that column? (That would follow an earlier decision in https://github.com/pombase/canto/issues/1949.)

I'm presuming it would be easy to rename the column headers in this case, but it might not be.

**Comment by vmt25** [comment]
> A few different things - these only refer to phenotype annotations, which were working fine before.
> 
>     1. At the top, I am asked for the species, which is not necessary for FlyBase - but a) I understand this may be needed fo Pombase and PHI base and b) does not bother for testing purposes
> 
>     2. I am not asked for extensions, even though these were showing up and working fine before
> 
>     3. the error red banner shows up with something like 'adding annotation failed - missing evidence code' - this even though I am not asked for an evidence code (and I thoguth we were getting rid of it for FlyBase)

Kim, apologies for bringing back this issue but I still cannot make fresh phenotype annotations on flycanto, because of 'missing evidence code' despite the fact that these should not be on flycanto. So, issue 3. above is still present. Issues 1. (selection of species) and 2. (extensions) seem resolved.

**Comment by kimrutherford** [comment]
> Kim, apologies for bringing back this issue but I still cannot make fresh phenotype
> annotations on flycanto, because of 'missing evidence code' despite the fact that these
> should not be on flycanto.

Hi Vitor.  Sorry the fix took so long.  It should be working now.  Could you let me know if it still fails?

**Comment by vmt25** [comment]
> Hi Vitor. Sorry the fix took so long. It should be working now. Could you let me know if it still fails?

It is working. It asks to select the species (point 1 on the initial bug report), but I can make phenotype annotations, with extensions. Many thanks.

**Comment by kimrutherford** [comment]
> It is working.

Thanks for testing.

> It asks to select the species (point 1 on the initial bug report), but I can make
> phenotype annotations, with extensions. Many thanks.
 
Could you send me a link to the session where you see that bug?  I haven't been able to reproduce it.

**Comment by vmt25** [comment]
> > 
> 
> Could you send me a link to the session where you see that bug? I haven't been able to reproduce it.

I think this was the session - https://curation.pombase.org/flybase-test/curs/2e523d5ee64ea295#

But now I cannot reproduce the bug

**Comment by kimrutherford** [comment]
> But now I cannot reproduce the bug

I hope it was just a temporary problem. Could you open a separate issue if you see it again? Thanks.

**Comment by ValWood** [comment]
I'm  closing this ticket because it's 57 comments long ;)

If there is anything buried in here that you still need to be done, open a fresh ticket.

Cheers,

Val
