### ISSUE TITLE
bug: can't edit name of allele I just created

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1918]
![1](https://user-images.githubusercontent.com/7359272/58943188-239f2100-8777-11e9-9c1e-d9a0626d5866.jpg)

![bug](https://user-images.githubusercontent.com/7359272/58943228-387bb480-8777-11e9-816f-c9e750883921.jpg)

**Comment by ValWood** [comment]
The allele name is present in the edit box?

**Comment by ValWood** [comment]
I think its OK. I edited it once and now it matches the name of the existing allele, which is why I can't edit it.

**Comment by ValWood** [comment]
This is a bug. It just occurred with some other new alleles I created.

Another oddity is that if you copy and edit, the name is also blank, but you are told you are editing the original allele:

![editing](https://user-images.githubusercontent.com/7359272/58944357-91e4e300-8779-11e9-92be-cfa2c050334d.jpg)

but I am no longer editing klp9delta172 because I copied it.

So in this example the edit window was blank (I added delt234c).

Its almost as if the presence of the editing label and the allele name are mixed up?

**Comment by ValWood** [comment]
here I wanted to remove the hyphen from these allele names so they match  delta92C, but that is not possible?

![egs](https://user-images.githubusercontent.com/7359272/58944536-f1db8980-8779-11e9-8760-0c4ea11957ae.jpg)

**Comment by ValWood** [comment]
- [ ]  note to self. I need to edit all of these do the "K" is lower case. also might be better to add the hyphen to delta92

**Comment by kimrutherford** [comment]
Ah, sorry about that.  I had to make some changes to allele editing to support synonyms and I got it wrong.  I'm working on a fix.

**Comment by kimrutherford** [comment]
I think I've fixed it.  Could you try again?  You'll need to reload the page.

**Comment by ValWood** [comment]
all good!
