### ISSUE TITLE
Use Unicode arrow symbols on navigation buttons

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1919]
Something that I've noticed for a while is that we don't use actual arrow symbols on the navigation buttons in Canto. Instead we create a 'fake' arrow symbol using ASCII characters: -->

![image](https://user-images.githubusercontent.com/37659591/58946310-7c71b800-877d-11e9-8f2d-01750d7503d6.png)

I think it would look better if we used an arrow symbol instead, meaning the HTML entities `&larr;` (**l**eft **arr**ow) and `&rarr;` (**r**ight **arr**ow). That would look like this:

![image](https://user-images.githubusercontent.com/37659591/58946444-c5c20780-877d-11e9-8bf9-55b0b1a44b1e.png)

- - -

@kimrutherford This is simple enough to do in the AngularJS templates, but it's a bit more tricky in the Mason templates, because HTML entities aren't rendered from a string variable. For example, on the gene page, the button text is stored in Perl code:

https://github.com/pombase/canto/blob/4b1f89402184e02ae026fbb40bfc6062ef3d32db/root/curs/gene_page.mhtml#L163

Then that's used in the template as follows:

https://github.com/pombase/canto/blob/4b1f89402184e02ae026fbb40bfc6062ef3d32db/root/curs/gene_page.mhtml#L133

I tried putting the arrow entity in the string variable:

```perl
my $finish_text = '&larr; Back to summary';
```

But it doesn't render the entity in the browser.

![image](https://user-images.githubusercontent.com/37659591/58947047-08d0aa80-877f-11e9-8652-2e3861566e83.png)

I can work around this by moving the arrow entity out of the string variable and into the template, like this:

```diff
- my $finish_text = '&larr; Back to summary';
+ my $finish_text = 'Back to summary';
```
```html
<a>&larr; <% $finish_text %></a>
```
If you're happy with that sort of change, I can go ahead and do that.

**Comment by kimrutherford** [comment]
> my $finish_text = '&larr; Back to summary';
> But it doesn't render the entity in the browser.

By default mason encodes everything.  You should be able to disable the encoding like this:

```
 <% $finish_text |n %>
```

The "n" means something like "No encoding".

Although I'm not sure that's better than putting the "&larr;" in the template.  I'm happy with either plan.

**Comment by jseager7** [comment]
> I'm happy with either plan.

In the pull request at #1920 I put the arrow entity in the template. Seeing as there's no problems with that solution, I'll go ahead and merge that pull request.
