### ISSUE TITLE
still see obsolete term to annotate in canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1922]
cytoplasmic sequestering of protein involved in mitotic G2 DNA damage checkpoint

**Comment by kimrutherford** [comment]
It's not obsolete?: http://amigo.geneontology.org/amigo/term/GO:1905507

**Comment by ValWood** [comment]
not showing up yet.

OK -I thought that happened a good while ago...

shows in QuickGO
https://www.ebi.ac.uk/QuickGO/search/cytoplasmic%20sequestering%20of%20protein%20involved%20in%20mitotic%20G2%20DNA%20damage%20checkpoint

It's odd because we get the obsolete report in the chado logs...

**Comment by kimrutherford** [comment]
I think I've worked this out.  Unfortunately the GO loading for Canto wasn't working and I hadn't noticed.  I had the arguments in the wrong order so owltools was completing successfully but writing to the wrong file.  The OBO file that is loaded into Canto wasn't being updated so the terms were out of date.  I've fixed the Canto ontology update script and it's re-loading now.

**Comment by kimrutherford** [comment]
I forgot to say, GO loading for Chado doesn't use owltools so the GO terms for the website are up to date.

**Comment by ValWood** [comment]
gone
