### ISSUE TITLE
GO config file update

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1923]
GO:0140311 | protein sequestering activity

should have has input/ direct input?

**Comment by ValWood** [comment]
@mah11  I can't find the config file in svn, where does it live I forgot?

**Comment by mah11** [comment]
They've moved to https://github.com/pombase/pombase-config/tree/master/canto/annotation_ex_config

**Comment by ValWood** [comment]
I think I committed a change directly. I'm not sure if it worked, or if I should have done a pull request

**Comment by ValWood** [comment]
If it didn't work, this is what I tried to add

GO:0140313  is_a  has_substrate ProteinID	sequesters		0,1	user

**Comment by mah11** [comment]
Looks like it worked - I now have it in my local copy.

**Comment by kimrutherford** [comment]
> I think I committed a change directly. I'm not sure if it worked, or if I should have done a pull request

In general directly editing is good but it doesn't work well with tab delimited files.  Your new line has some spaces and some tabs.  I've changed the spaces to tabs.

**Comment by ValWood** [comment]
sorry about that. I copied the previous line and edited so I thought I preserved the tabbing. Clearly not...
