### ISSUE TITLE
allele difference reporting confusion

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1924]
warning in 4fa485c82556641b: description for new allele "eso1-H17(G799D)" does not match the existing allele with the same name "eso1-H17(aaG799D)" (from session f07cbe80a4008b28)

BUT

in  f07cbe80a4008b28
eso1-H17 is still eso1-H17(unknown) 

so it seems that the substitution is happening, but the aa part is not being accounted for in the matching?

**Comment by ValWood** [comment]
and

warning in 7803457eba12e494: description for new allele "eso1-H17(G799D)" does not match the existing allele with the same name "eso1-H17(aaG799D)" (from session f07cbe80a4008b28)


I'm going to double check this when I finish processing , I might be doing something dim (also need to check double mutants)

**Comment by kimrutherford** [comment]
I'm confused by this.  I can't see the description "aaG799D" in any session.

**Comment by ValWood** [comment]
It was there in both, but it was unknown " in the other session. Now fixed.

![eso1](https://user-images.githubusercontent.com/7359272/59106413-3ad43f00-892e-11e9-951a-c87b1475ea0a.jpg)
