### ISSUE TITLE
Phenotype annotation edit shows genotypes for all organisms

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1925]
When editing a (single organism) phenotype annotation, PHI-Canto shows all the genotypes for every organism in the genotype drop-down, which allows phenotype annotations to be transferred to a different organism. Canto copes surprisingly well with this, in that it changes the organism for the annotation to match the genotype, but it's still confusing to show genotypes that don't belong to the organism.

We have two possible solutions:

1. Only show genotypes that belong to the same organism as the genotype annotation being edited.

2. Show all genotypes, but group those belonging to different organisms in a separate section of the drop-down. This could be useful for versions of Canto that could have a need to transfer annotations across organisms (I'm thinking of FlyBase).

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/59189223-74e15300-8b71-11e9-8089-278375c5ea73.png)

**Comment by jseager7** [comment]
We decided it would be better if it were possible to edit the organism of the genotype as well; that way the modal can simply display the genotypes of the currently selected organism. However, this makes the solution more complicated, for the following reasons:

* Users may need a way to edit the strain too, otherwise we can only show all existing organism&ndash;strain combinations in the selector, which may not include what the user wants.

* We have pathogen and host single species annotation types, so it wouldn't make sense to allow pathogens to be selected on a host phenotype (or vice versa). I need some way to get the annotation type, but I think I can get this from the `annotationEditDialogCtrl` directive (specifically `$scope.annotationTypeName`).

* The functionality being implemented here is very similar to what the `organismSelector` directive does, so I can probably reuse that directive &ndash; but that selector doesn't display strains, and it might be styled differently to the other feature choosers on the page. Neither of these are particularly major issues, since the strain will probably be provided in a separate selector (see above).

**Comment by jseager7** [comment]
I think this is technically fixed now, since the modal now only shows genotypes for the current organism. I'm not sure if it's necessary to allow the organism to be changed yet; that feature belongs in a separate issue anyway. Closing now.
