### ISSUE TITLE
organism error

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1926]
I can't see what this is? any ideas? nothing obvious in the session?

warning in 296b721850a6d19b: some data from annotation isn't used: organism
warning in 296b721850a6d19b: some data from annotation isn't used: organism
warning in 296b721850a6d19b: some data from annotation isn't used: organism
warning in 296b721850a6d19b: some data from annotation isn't used: organism
warning in 296b721850a6d19b: some data from annotation isn't used: organism
warning in 296b721850a6d19b: some data from annotation isn't used: organism

**Comment by kimrutherford** [comment]
I've made the change but it wasn't in time for tonight's load.  The warning should be soon on Wednesday morning.

**Comment by ValWood** [comment]
message is still in these logs

https://curation.pombase.org/dumps/latest_build/logs/log.2019-06-12-22-46-37.curation-tool-data-load-output

but there is no hurry for this...

**Comment by kimrutherford** [comment]
My fix had a typo.  I think I've now fixed the fix.

**Comment by kimrutherford** [comment]
The messages are gone from the log.
