### ISSUE TITLE
Correctly display diploids from Chado

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1927]
Currently they would be shown as a list of alleles.

**Comment by ValWood** [comment]
what does this one mean?

**Comment by kimrutherford** [comment]
Once there are diploid genotypes with annotation in Chado we need to show them in the existing annotations section.  The Canto code will need to change to support that.  It's not a big task compared to loading the diploids into Canto in the first place.

**Comment by ValWood** [comment]
do you need us o add some examples to this ticket?

**Comment by kimrutherford** [comment]
> do you need us to add some examples to this ticket?

Once there are some diploid annotations in Chado it should be clear how to display them.

**Comment by ValWood** [comment]
but I think there are some aren't there?

**Comment by kimrutherford** [comment]
> but I think there are some aren't there?

The Chado loading code doesn't understand diploids yet so there are none in Chado.

**Comment by ValWood** [comment]
Ah OK got it. Do they go into a log file?

**Comment by kimrutherford** [comment]
> Do they go into a log file?

At the moment they are just stored as multi-allele genotypes.

**Comment by ValWood** [comment]
OK, got it. I probably knew this.
v

**Comment by kimrutherford** [comment]
The display is still mangled.  Diploid genotypes from Chado are still shown as haploid in the "Existing" annotations section.

**Comment by kimrutherford** [comment]
> The display is still mangled. Diploid genotypes from Chado are still shown as haploid in the "Existing" annotations section.

Fixed!  It's only taken 2 years.  :-)

I'm going to close this issue since it's so old.  Please open new issues or bugs and problems.
