### ISSUE TITLE
Hide mentions to evidence code from phenotype annotation pipeline in Fly-canto

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1930]
A couple of thing on evidence 
Evidence code column shows while making new annotations

![Screenshot 2019-06-11 at 11 15 26](https://user-images.githubusercontent.com/33721108/59264077-411e3000-8c3a-11e9-8d4f-609b923f7862.png)

And clicking 'Back' goes into an evidence code menu

![Screenshot 2019-06-11 at 11 16 27](https://user-images.githubusercontent.com/33721108/59264155-614def00-8c3a-11e9-847e-3775a8a933ed.png)

Would it be possible for these not to be appear/be possible in Fly-Canto?

**Comment by vmt25** [comment]
Also about the  phenotype annotation process, would it be possible to hide the 'additional info' step from Fly-Canto?

![Screenshot 2019-06-11 at 12 01 54](https://user-images.githubusercontent.com/33721108/59266970-e76d3400-8c40-11e9-947c-88fe2670691f.png)

Any such kind of comments would be attached to single alleles, as 'new note'

**Comment by ValWood** [comment]
note that your notes are genotype notes (I think?) and this is an "annotation comment"  (i.e specific to the experiment, not the genotype) I use these to note the figure or table the annotation was in, and other notes/comments which might help if the phenotype is reassessed for any reason.
Another option, is to   hide it here if  you don't want to use it all the time, but have it available albeit a bit more hidden  in a  future "quick add", or  the existing  "edit" view

**Comment by kimrutherford** [comment]
> Would it be possible for these not to be appear/be possible in Fly-Canto?

The evidence page is now correctly hidden when using the "back" button and the evidence column is now hidden.

**Comment by vmt25** [comment]
This seems to be done.
