### ISSUE TITLE
Would it be possible to permit direct text edit (find-replace) on genotype annotation tables?

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1933]
For discussion:

Would it be possible to permit direct text edit (find-replace) on genotype annotation tables?

Occasionaly, one finds late during curation that e.g. there is a more appropriate phenotype term for several similar annotations.

This kind of repetitive edits are easily handled by curation to proforma in a text editor but will be time consuming if done one by one. 

Obviously, Canto should only allow existing/authorized CVs and qualifiers.

**Comment by ValWood** [comment]
did we say in the meeting that if

https://github.com/pombase/canto/issues/1830

is implemented, this isn't such a big deal because this can be deleted and the new annotations can be made more quickly.

Kim thinks this would be really difficult and we think the discussion ended with us deciding it would not be too bad if multiple annotations could be made more quickly.

Can you confirm

**Comment by ValWood** [comment]
Vito we thought you may have some notes on this discussion?

**Comment by ValWood** [comment]
We chatted about this some more and for us it isn't high priority but it would be very very nice.

So we thought that if this is something you would like to address in a future collaboration as discussed by @sjm41  this would be a suitable self-contained project, it is likely that FB curators may find the lack of this more cumbersome. Kim could spend a month or two on adding direct table editing throughout.

**Comment by vmt25** [comment]
Agreed that this is not a priority. This was the one I said it was on my wishlist but that I was expecting a big 'no' for an answer.

Notes on the brainstorming: Kim mentioned something like selecting individual cells (or a full column) and allowing direct editing of the text.

**Comment by vmt25** [comment]
> did we say in the meeting that if
> 
> #1830
> 
> is implemented, this isn't such a big deal because this can be deleted and the new annotations can be made more quickly.
> 
> Kim thinks this would be really difficult and we think the discussion ended with us deciding it would not be too bad if multiple annotations could be made more quickly.
> 
> Can you confirm

(forgot to repky to this on my previous comment)

Yes, all of that is correct.
#1830 would be the major improvement and would help deal with mutliple editing.
(forgot to reply to this on my previous comment)

**Comment by ValWood** [comment]
Yes I forgot, we did chat about the ability to edit a single column too.

Anyway we will keep this one on the back burner.

**Comment by vmt25** [comment]
agreed

**Comment by vmt25** [comment]
Closing - This is unrealistic/unfeasible
