### ISSUE TITLE
message to curators

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1935]
We can now edit /append existing messages to curators in approval. However, we can only do this if  a message already exists.

Often I want to add a message to say I made  a correction,  but if no message exists already  I don't see the option otherwise (at least in this session: curs/9ef4b740616f8870)
I would need to "reactivate" the session.

**Comment by ValWood** [comment]
I also just edited a comment  with an existing comment.

There was a comment. I can't remember exactly what ti was but it began 
done because...

I added a comment along the lines
VW 11/06/19 fixed allele type to nonsense

clicked "finish" approved session.

Comment was truncated to 

"done b"

![corrupted note](https://user-images.githubusercontent.com/7359272/59269876-ec81b180-8c47-11e9-8e50-d99ffe4c60f2.jpg)

**Comment by ValWood** [comment]
in 267b85c1b667dcb2

**Comment by kimrutherford** [comment]
The code isn't handling slashes in the message correctly and is messing things up.  I don't know if that explains the bug you saw but as a temporary work around you should be able to save notes if you avoid slashes.  I'll fix this properly tomorrow.

**Comment by kimrutherford** [comment]
> However, we can only do this if a message already exists.

I've changed it so that the "Edit message to curators ..." link always appears if you're logged in as admin.

**Comment by ValWood** [comment]
I bet that is it. I did have / in data. Not sure that there was  a slash at the truncation point though

**Comment by kimrutherford** [comment]
> Not sure that there was a slash at the truncation point though

Yep that's a worry.

I've fixed things so that the comment is sent to the server in the correct way so slashes should now be fine.  Could you have another test?  You'll need to reload.

**Comment by ValWood** [comment]
Seems to be working, thanks!

**Comment by kimrutherford** [comment]
OK, I'll close this.  Could you open a new issue if you spot problems?
