### ISSUE TITLE
separate phenotype annotations in the summary page into 'single allele', 'diploid locus' and 'multi-allele'?

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1936]
Topic for discussion:

Would it be useful to separate phenotype annotations in the summary page into 'single allele', 'diploid locus' and 'multi-allele', mirroing the way genotypes are organized in the genotype management page?

This how the phenotypes are show on the summary page:

![Screenshot 2019-06-11 at 12 50 57](https://user-images.githubusercontent.com/33721108/59269861-e7246700-8c47-11e9-8fb0-017971150d7d.png)

And this is how they show on the genotype management:

![Screenshot 2019-06-11 at 12 54 56](https://user-images.githubusercontent.com/33721108/59269947-2357c780-8c48-11e9-942c-f3488595470b.png)

**Comment by ValWood** [comment]
I'd like to use it for a bit before we decide this, at least for PomBAse. @Antonialock @mah11  do you have any preferences.
My feeling is that the separation at genotype creation time is more useful, to keep  check on the diploids you have constructed/ At annotation time its really only a different genotype so I think I will prefer just the single and multi-table.

That said it might be nice to be able to spot diploid in the tables more easily. I think we discussed this on the PHI-base call too? @kimrutherford  did we?

**Comment by mah11** [comment]
There are actually four, not three, kinds of genotype (although FB won't use either of the haploid types often):

- haploid single locus
- haploid multi-locus
- diploid single locus
- diploid multi-locus

I'll open a ticket for the organization on the genotype management page. I don't have as strong feelings about the tables of annotations, so I could probably carry on without change or adapt to something different if others evolve a clear preference.

**Comment by ValWood** [comment]
in this ticket
https://github.com/pombase/canto/issues/1941
we decided to split the geneotype table into 2 with a sub-split into haploid diploid (i.e there will no longer be 3 tables)

**Comment by ValWood** [comment]
Kim's preference is to call the tables single and multi-locus, and to include the diploids clearly labelled  (at the top or the bottom, configurable)- because it is easier.

Also, this will match the genotype 2 table split in genotypes.

Is this OK? We could revisit later if necessary?

**Comment by ValWood** [comment]
Note for Kim, any occurrence of a diploid locus will automatically be sorted into the diploid  part of the table

**Comment by vmt25** [comment]
> Kim's preference is to call the tables single and multi-locus, and to include the diploids clearly labelled (at the top or the bottom, configurable)- because it is easier.
> 
> Also, this will match the genotype 2 table split in genotypes.
> 
> Is this OK? We could revisit later if necessary?

That is perfect.

**Comment by vmt25** [comment]
I think this is done
