### ISSUE TITLE
Document the format of the JSON export file

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1943]
See: https://github.com/pombase/canto/issues/1854#issuecomment-501220052

**Comment by kimrutherford** [comment]
I've made a first pass at documenting the JSON output format:
  https://github.com/pombase/canto/wiki/JSON-Export-Format

@gm119 please let me know about anything that's not clear or anything I've missed out.  And any typos :-)

**Comment by kimrutherford** [comment]
Still missing: metagenotype and interaction documentation.

**Comment by kimrutherford** [comment]
> Still missing: metagenotype and interaction documentation.

Also the "%" and "Text" rangeTypes aren't mentioned.  And the example JSON at the top of the page doesn't include any extensions.

**Comment by jseager7** [comment]
We do have a pretty comprehensive specification of the JSON export as a JSON Schema, in [etc/export.schema.json](https://github.com/pombase/canto/blob/master/etc/export.schema.json) on this repository. Some parts are very technical (bordering on unintelligible to non-technical users), but I've tried to add labels and descriptions for every field to explain their purpose in plain language. Hopefully any data scientist or developer would understand what I've said.  

I think there are probably tools out there that can generate human-readable documentation from this specification. Deriving it from the schema specification would be much more maintainable than writing the documentation by hand.

**Comment by jseager7** [comment]
So to answer your question, I don't think this is high priority now. The existing wiki page should probably link to the schema file though.

**Comment by gm119** [comment]
I had a look at the doc in the https://github.com/pombase/canto/wiki/JSON-Export-Format link mentioned further up this thread, and it looks like Kim has already documented 'metagenotype and interaction' and the "Text" rangeType (so much of the missing doc has already been added). So I'd be happy for it to no longer be high priority (and it can maybe even be closed - I agree with the comments from jseager7)

**Comment by ValWood** [comment]
Action
- [ ]  Link  wiki to schema doc

**Comment by jseager7** [comment]
>  Link wiki to schema doc

That's done already, see here: https://github.com/pombase/canto/wiki/JSON-Export-Format

**Comment by ValWood** [comment]
OK let's close this. Documentation updates will be ongoing.
