### ISSUE TITLE
3rd allele option pull-down doesn't work

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1944]
I tried a session with more than 2 alleles

Now I see the pulldown, 
![diploid](https://user-images.githubusercontent.com/7359272/59349954-d3920280-8d12-11e9-8a0c-362220f1cca3.jpg)

but  I can't switch to other alleles. I see the  "no entry" sign pop up

**Comment by ValWood** [comment]
seems to be browser specific
Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by kimrutherford** [comment]
You need to tick the box on the left before it gets enabled.  I'll see if I can improve that.

**Comment by mah11** [comment]
If the pulldown isn't active, choose the radio buttor for the third option. If, but only if, it stays inactive, reopen this.

**Comment by kimrutherford** [comment]
> You need to tick the box on the left before it gets enabled. I'll see if I can improve that.

I've change things so that the selector isn't disabled.  If you click on it or select an allele, the third checkbox will be automatically ticked.
