### ISSUE TITLE
bug diploid genotype display

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1948]
I have annotated a number of homozygous diploid (in same genes) session e6d26db4caf74ac5 

![Screenshot 2019-06-13 at 11 19 18](https://user-images.githubusercontent.com/12727506/59425218-56779380-8dcd-11e9-88f4-9ef452587580.png)

but they have disappeared

![Screenshot 2019-06-13 at 11 19 28](https://user-images.githubusercontent.com/12727506/59425209-52e40c80-8dcd-11e9-873f-efcff26be93e.png)

**Comment by ValWood** [comment]
What has disappeared?

**Comment by ValWood** [comment]
You have the same diploid  genotype twice, once the old way and once the new way. You need to transfer your annotation to the "new diploid" and delete the old genotype?

**Comment by ValWood** [comment]
I see you have no rad1delta/rad1 delta diploid allele , but the annotation is still there...that's weird!

**Comment by Antonialock** [comment]
lets keep the ticket on topic :-) 

all the single gene diploids have disappeared from the genotype table.

**Comment by kimrutherford** [comment]
> all the single gene diploids have disappeared from the genotype table.

Sorry for the alarming bug.  The annotation isn't lost.  If there are no single allele genotypes the single locus diploid table gets hidden.  Whoops.  I'll fix that.

**Comment by kimrutherford** [comment]
I think that's fixed.  Can you check that it's OK now?

**Comment by Antonialock** [comment]
not alarming, you can see that the phenotype annotations are still there in the screenshot :-) 

yes back & visible! thanks
