### ISSUE TITLE
small text change, genetic interactions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1949]
Change text on pop up menu 

" Choose evidence code"  

to  "Choose genetic interaction type"

clearer for users

**Comment by kimrutherford** [comment]
> Change text on pop up menu

Which pop-up menu?  I can't find the text "Choose evidence code" in the code.

**Comment by ValWood** [comment]
![code](https://user-images.githubusercontent.com/7359272/59469158-e8ae8480-8e2b-11e9-85de-81e4949026c6.jpg)

**Comment by kimrutherford** [comment]
OK, thanks.  I've change that.
