### ISSUE TITLE
text change on front page

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1950]
https://curation.pombase.org/

Canto is developed as part of the PomBase project, which provides a model organism database for the fission yeast Schizosaccharomyces pombe. PomBase is funded by the Wellcome Trust and is run by a consortium comprising the University of Cambridge, **the European Bioinformatics Institute** and University College London.

**Comment by mah11** [comment]
I have just committed a version without the offending matter ;)

**Comment by kimrutherford** [comment]
Thanks for spotting that and thanks for the fix.  I've re-release Canto.
