### ISSUE TITLE
single and double gene diploids

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1951]
Not sure which tracker to stick this on but wanted to start a discussion....

Currently, annotations to "single gene diploids" appear in in the "multi-allele table"
This is correct in principle (there are multiple alleles....) but it doesn't fit with our phenotype annotations

Unless a mutant does "meiosis in haploid" then **all** meiotic phenotypes are observed in diploids. Sometimes the researcher will explicitly have stated that the mutant is "homozygous diploid yfgXdelta" or "heterozygous diploid yfgdelta", sometimes the researcher will just have called it "yfgdelta". This will have influenced what we put in the allele description. 

So I don't think that single-gene diploids should appear in the multi-allele table - maybe split the tables multi-gene & single gene instead?

**Comment by ValWood** [comment]
https://github.com/pombase/canto/issues/1941
duplicate
