### ISSUE TITLE
Remove spaces at start and end of email addresses

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1952]
When a user enters their name, email and ORCID any spaces at the start or end should be removed before storing in the database.

**Comment by kimrutherford** [comment]
I've checked and in the places where the user can add an email, the spaces are always trimmed.  I can't see how they are getting into the database.

**Comment by ValWood** [comment]
Did you check the place where the assignee can reassign  the session?

**Comment by kimrutherford** [comment]
> Did you check the place where the assignee can reassign the session?

Yep.

**Comment by ValWood** [comment]
Maybe these duplicates predated the space removing code but that I never spotted them before?

I remember you dealing with spaces (I'm thinking about a year ago, but that could easily mean 2 since as you know I have no concept to time)

**Comment by kimrutherford** [comment]
Some of the emails with spaces were added less than a year ago.  I stumped. I'll leave this open and I'll have a think about it.

**Comment by ValWood** [comment]
Let's close. We'll assume it was legacy, and follow up if more occurr.
