### ISSUE TITLE
Add TAS evidence cope as an admin option

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1953]
requested ISS in admin mode here.
https://github.com/pombase/canto/issues/1941
This is a bit complicated since we need a "with field"

In the meantime, we would like to enable TAS evidence code in admin mode. This is easier since it is just an evidence code with no other meta-data.

Most of these will be TAS anyways.

**Comment by kimrutherford** [comment]
Is that for PHI-Canto or PomBase?

**Comment by ValWood** [comment]
PHI Base need ti, but we will need it at some point  since once we don't do TAS in Artemis we will occasionally want to make TAS annotations in Canto. 
We don't want the community to be able to make TAS though, and there is no hurry for PomBase.

**Comment by jseager7** [comment]
@ValWood The TAS evidence code is enabled on the production server now, so I'm closing this issue. Let me know if you notice any problems.

I'll apply this change to the demo server later.
