### ISSUE TITLE
Tidy up the genotype table

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1955]
I've been experimenting with the genotype table.  I think there are too many vertical and horizontal lines at the moment.

Is this an improvement?:

![new-style-genotype-table-4](https://user-images.githubusercontent.com/90474/59507572-7a3af680-8eff-11e9-9cc4-721ce22231f3.png)

We've talked about hiding the gene links.  Perhaps we could hide them until you mouse over the genotype?:

![new-style-genotype-table-5](https://user-images.githubusercontent.com/90474/59507850-5e842000-8f00-11e9-8de8-9b670848dd0a.png)

**Comment by ValWood** [comment]
Oh yes. much.

**Comment by mah11** [comment]
fine with me as long as long things wrap sensibly, so it's easy to tell an continuation apart from the next allele in the genotype

e.g. something like this would be ok:

    cdc17-1-175/ΔNLS-GFP(N-terminal 175 amino acids of cdc17, with 
                 KKK62AAA mutations, fused to GFP)[Not assayed] 
    cds1Δ

but this would annoy:

    cdc17-1-175/ΔNLS-GFP(N-terminal 175 amino acids of cdc17, with
    KKK62AAA mutations, fused to GFP)[Not assayed] 
    cds1Δ

**Comment by kimrutherford** [comment]
Instead of line wrapping, there's also the option of hiding the end of the text until you mouse-over or click:

![new-style-genotype-table-6](https://user-images.githubusercontent.com/90474/59578755-e3985080-911d-11e9-87fc-1c4b1bb73558.png)

after clicking:

![new-style-genotype-table-7](https://user-images.githubusercontent.com/90474/59578789-0cb8e100-911e-11e9-8560-c29f9b174581.png)

**Comment by kimrutherford** [comment]
> I've been experimenting with the genotype table. 

The test Canto has the new look.

**Comment by ValWood** [comment]
I will give it a whirl later. It might also be useful to make a change we discussed a long while ago

[Wild Type Product Level] ->[WT product level]
(also discussed on PHI-BAse call)

**Comment by jseager7** [comment]
The solution here is the same one that was discussed in #1520, and that issue also got stuck on the problem of what happens when genotype names are long enough to wrap onto the next line. If we can solve that here, we can close #1520 too.

@kimrutherford with regards to text appearing on mouse-over and click: does showing the gene names on mouse-over cause the size of the table to change, or does the table always account for the width of the hidden gene names?

Another problem with showing the full genotype name when clicked is that it (presumably) changes the width of the table when clicked, meaning in cases where the table is almost wide enough to wrap (be pushed onto a new row below the gene list), then clicking the link will suddenly shift the entire table down the page, which is going to be pretty jarring for users.

**Comment by kimrutherford** [comment]
> does showing the gene names on mouse-over cause the size of the table to change, or does the
> table always account for the width of the hidden gene names?

They are hidden using "visibility: hidden;" so the table width doesn't jump around when you move the mouse.

> then clicking the link will suddenly shift the entire table down the page, which is going to be pretty
> jarring for users.

Good point.

**Comment by kimrutherford** [comment]
> Another problem with showing the full genotype name when clicked is that it (presumably)
> changes the width of the table when clicked

I've changed it so that it always shows the whole genotype description.

The test Canto has this change.  If the table is an improvement, I'll merge the change into the main code.

Val, are you happy for this to go into the main Canto?  Here's my dodgy test session in case you'd like another look: https://curation.pombase.org/test/curs/05284071e0eba01a/genotype_manage

**Comment by jseager7** [comment]
@kimrutherford I've noticed that allele symbols aren't being decoded on your test session; does that still need to be implemented?

![image](https://user-images.githubusercontent.com/37659591/62280938-c22cc300-b444-11e9-9267-58ae0cd34d6d.png)

**Comment by kimrutherford** [comment]
Hi James.  Thanks for spotting that.  I've fixed it.

**Comment by mah11** [comment]
I've done a bit more testing. Apart from what I put in #1988, #1992, and #1993, it seems to be working pretty well.

**Comment by kimrutherford** [comment]
Thanks for testing Midori.  I'll merge this after I've made the change Val mentioned: https://github.com/pombase/canto/issues/1955#issuecomment-502589393

**Comment by ValWood** [comment]
@kimrutherford This seems close to completion?

**Comment by kimrutherford** [comment]
> This seems close to completion?

Yep, nearly done.

**Comment by kimrutherford** [comment]
> This seems close to completion?

Yep, this is done now.

> It might also be useful to make a change we discussed a long while ago
> [Wild Type Product Level] ->[WT product level]
> (also discussed on PHI-BAse call)

There's a separate issue for this change: #1536
