### ISSUE TITLE
bug can't make heterozygous diploid

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1956]
in
91da8e4c4e7b6d48

it "makes" it but I cant see it in the genotype drop down for phenotypes or in the genotype diploid tables.

**Comment by kimrutherford** [comment]
I can't reproduce the problem.  I'll try more tomorrow.

I was able to make this diploid: cdc2-56(aaG183E)[Not assayed] / cdc2-M63(aaG227C)[Not assayed] 

I can see it in the genotype diploids table.  What is the "genotype drop down for phenotypes"?  Is that the one in the annotation edit dialog?

**Comment by Antonialock** [comment]
It is still bugging for me. I have made heterozygous diploids in other sessions so I dont know why this one isn't working.

this is the diploid I am trying to make.

<img width="857" alt="Screenshot 2019-06-14 at 17 31 48" src="https://user-images.githubusercontent.com/12727506/59523911-6c1eb300-8eca-11e9-8268-65834eef971c.png">

**Comment by kimrutherford** [comment]
Thanks for the example.  I can now reproduce the problem and I'll get on with fixing it.  Canto is getting confused because there is a multi-allele genotype in the session with the same alleles so it decides that you're storing a duplicate genotype - it's ignoring that your new genotype is a diploid.

I'll also fix Canto so that it show a message saying what happened in case we see this again.

**Comment by Antonialock** [comment]
Aha!

**Comment by kimrutherford** [comment]
I think I've fixed that.  Could you again?

**Comment by Antonialock** [comment]
Yes that works now but there is another issue...I'm trying to add homozygous diploids in the same session. 

wee1-50 / wee1-50 - canto tells me the allele has been stored but I cannot see it in the diploid table, nor in the drop down when trying to edit an allele

same for cdc2-1w/cdc2-1w & cdc2-130/cdc2-130 

oddly "cdc2-56(aaG183E)[Not assayed] / cdc2-56(aaG183E)[Not assayed]" worked

at least I dont think the others are in the list...it's difficult to see

<img width="931" alt="Screenshot 2019-07-04 at 10 13 05" src="https://user-images.githubusercontent.com/12727506/60654879-ba2d3380-9e44-11e9-911b-b03c564f44cd.png">

**Comment by kimrutherford** [comment]
Thanks for testing.  I'll find out why homozygous diploids are a problem and fix it.

It might be that the code is deciding that wee1-50 / wee1-50 is just wee1-50, forgetting that it's a diploid.

**Comment by kimrutherford** [comment]
> I'll find out why homozygous diploids are a problem and fix it.

I tried to make a homozygous diploid for wee1-50 and got:

![diploid-bug-1](https://user-images.githubusercontent.com/90474/60698820-58082780-9f45-11e9-9fe1-8f5bdfbbc50f.png)

Make that is what happened to you?  I'll fix that and see if it helps.

**Comment by kimrutherford** [comment]
> Make that is what happened to you?  I'll fix that and see if it helps.

Make -> Maybe

I fixed things so the attempting to create a wee1-50 / wee1-50 works even if there is another genotype with the alleles (ie "wee1-50 wee1-50").

Could you have another try?  Sorry this is taking so long to get right.

**Comment by Antonialock** [comment]
excellent, that all seems to work now. 

thanks!
