### ISSUE TITLE
text has changed for evidence for GO annotation

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1957]
<img width="940" alt="Screenshot 2019-06-14 at 18 03 50" src="https://user-images.githubusercontent.com/12727506/59525690-da657480-8ece-11e9-991a-102698af5dfe.png">

**Comment by Antonialock** [comment]
says "choose genetic interaction type"

**Comment by ValWood** [comment]
Yes thatt's what we decided on the call.
We should probably change the left hand column too. It would be a nice if there was a way to  make this non-repetative though...

Like

Genetic interaction type ||  pull down displays the most common as default (it's clear that a choice is needed so we don't need to say this).

We can deal with this during the overhaul though...

**Comment by Antonialock** [comment]
yes but I am making a cellular component annotation?

**Comment by ValWood** [comment]
Ah that would be  a bug!

**Comment by kimrutherford** [comment]
Sorry about that.  Fixed now.
