### ISSUE TITLE
Add a way to clear the database

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1958]
From @martin2urban:

> I know how to export the phi-canto data to JSON.
> 
> Is there a similar command/script I can use to clear the complete database? I want to do
> this on my test-server after exporting.

**Comment by kimrutherford** [comment]
Hi @martin2urban.  How clear would you like the database to be?  Do you want to just remove the curation sessions or would you like to completely re-initialise everything including organisms, strains, ontology terms and users?

**Comment by ValWood** [comment]
The sessions we are working on won't be remover will they? We are doing real curation.

**Comment by kimrutherford** [comment]
Martin would like to clear his own database not the own you've been using.

**Comment by martin2urban** [comment]
Hi @kimrutherford .
I only want to remove the current curation sessions, so that I can generate example JSON files.  Organisms, strains, ontology terms, users should not be changed. I attached a 'high priority label'.

**Comment by kimrutherford** [comment]
Thanks Martin.

I've put this issue on my to-do list for tomorrow.

**Comment by kimrutherford** [comment]
Hi Martin.

I've added an extra flag to the `canto_delete.pl` script.  If you do a `git pull` then you should be able to remove all sessions with a command like:

```sh
./canto/script/canto_docker ./script/canto_delete.pl --all-canto-sessions
```
(If you're running Canto in Docker)

**Comment by jseager7** [comment]
@kimrutherford Is there some way we can prevent this script from being (accidentally) run on the production server? There's currently no regular backup scheme of the curation sessions on that server besides the backup of the full server &ndash; I'm happy to add a regular backup scheme to guard against this, but this script should never really need to be run in production.

**Comment by kimrutherford** [comment]
> Is there some way we can prevent this script from being (accidentally) run on the production server? 

There's no way for the script to know if the current instance is a production server.  I made the argument long so it wouldn't be typed by mistake.

I think backups or snapshots are quite a high priority if there is now real curation data on the server.

**Comment by jseager7** [comment]
> I made the argument long so it wouldn't be typed by mistake.

My concern is more that if the script is frequently being run on one type of server (the test server, for example), it's more likely that an admin could SSH into the wrong server, or lose track of which one they're connected to, and run the script thinking they're targeting the test server when they're actually not.

> There's no way for the script to know if the current instance is a production server.

True, but it would be useful for configuration management purposes if there was some way for Canto to determine the 'mode' of the server it's running on. I've been struggling to automate the deployment of our config repository when there are differences in the `canto_deploy` file across deployments: production is different from demo, and my local deployment is different from both. Could we use environment variables (or something similar) to achieve this?

For now I can look at setting up a regular backup of the curation sessions themselves (ideally one that can create an 'offsite' backup too). I'll open an issue about that on the config repository.
