### ISSUE TITLE
Add code to upgrade DB for genotype-genotype interactions

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1965]
(Needed for pombase/canto#1915)

The current gene-gene interactions need to be converted to genotype-genotype interactions.

I have forgotten the plan we discussed.  I think the idea was to make an allele with type "unknown" for each gene in an interaction and create the genotypes from those alleles.  Does that sound right?

Should the converted gene-gene interactions have no phenotype (initially)?

**Comment by mah11** [comment]
> I think the idea was to make an allele with type "unknown" for each gene in an interaction and create the genotypes from those alleles. Does that sound right?

Very close - the only difference from what I remember is that we decided to say the alleles are "unspecified" rather than "unknown".

> Should the converted gene-gene interactions have no phenotype (initially)?

I think if the interaction type is "synthetic lethal", the conversion-output genotype can have "inviable cell population", but for the other interaction types, safest to have no phenotype.

**Comment by kimrutherford** [comment]
Thanks Midori.

I'll upgrade the interactions in the test server to genotype-genotype before trying the main Canto.  I'm hoping to do that next week.

**Comment by kimrutherford** [comment]
I think this is done.  I'll do more testing in the morning then my plan is to copy the session data from the main Canto over to the test Canto, then run the upgrade code to turn gene-gene interactions into genotype-genotype interactions.  Then we can check that the interactions look OK and that they can be edited.

I'll let you all know when I need help with testing.

**Comment by kimrutherford** [comment]
In my local Canto the upgraded interactions look like:

![interaction-update-7](https://user-images.githubusercontent.com/90474/60661579-4c1d5680-9eae-11e9-92b8-70f24a86dd02.png)

We can hide the type for allele so that "unspecified-pol1(unspecified)" is displayed as "unspecified-pol1" or we can use a different allele name to avoid repetition.

**Comment by kimrutherford** [comment]
> my plan is to copy the session data from the main Canto over to the test Canto, then run
> the upgrade code to turn gene-gene interactions into genotype-genotype interactions.

That's done now.  It looks OK except that the "Existing annotations" section for the interactions is messed up.  That's expected though because it needs fixing.

https://curation.pombase.org/test/curs/33c4c7d6daa555cf/ro/

**Comment by kimrutherford** [comment]
I'm going to close this and open separate issues for bugs.
