### ISSUE TITLE
disable assayed protein for phospholipid binding terms

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1966]
Annotation extensions
These extension types are available for decreased phospholipid binding (FYPO:0005307):

assayed protein ...

**Comment by mah11** [comment]
config lives here:
https://github.com/pombase/pombase-config/blob/master/canto/annotation_ex_config/FYPO_A_E_config

But do you not want to be able to specify which protein has its binding to phospholipids affected?

**Comment by ValWood** [comment]
OK yes I probably do!
