### ISSUE TITLE
Make sure only one canto_load.pl runs at once

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1967]
This will prevent the possibility of ontology loading getting messed up if a load starts before the previous load finishes.

Note to self, something like:

```perl
use Fcntl qw(:flock);

open my $self, '<', $0 or die "can't open $0 for reading";
flock($self, LOCK_EX) or die "can't get lock on $0";

...
```

**Comment by jseager7** [comment]
Will this prevent other calls to `canto_load.pl` (with different options) from running in parallel? For example, will it prevent loading organisms at the same time as ontologies?

This is more out of curiosity than anything else &ndash; I don't know if the script is even capable of doing this by default already, and we certainly haven't made any attempt to parallelise the loading on our deployment.

**Comment by kimrutherford** [comment]
> Will this prevent other calls to canto_load.pl (with different options) from running in parallel?
> For example, will it prevent loading organisms at the same time as ontologies?

Yep, that was my plan as it's easiest to implement.

**Comment by kimrutherford** [comment]
That's done now - `canto_load.pl` will block if it's already running.  That's the quickest fix.  If we need more subtlety we can work on it later.
