### ISSUE TITLE
"add another [gene]" option missing

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1971]
Certainly missing from the annotation extension interface, e.g. for a protein localization phenotype:

![Screen Shot 2019-07-03 at 3 06 34 PM](https://user-images.githubusercontent.com/5196259/60598874-615a8e00-9da5-11e9-9d8b-833ec70d5fbf.png)

Seems similar but not identical to #1840 

Was it also available for the pulldowns for interactions? If so, it's gone missing there too, although that may not be as big a deal with the new genotype-genotype interactions coming along soonish.

**Comment by kimrutherford** [comment]
Sorry about that.  I accidentally removed the link while working on the new interaction plan.  I edited the master Git branch by mistake.

It's fixed for the interaction pulldowns too.
