### ISSUE TITLE
Read and display new style genotype-genotype interactions from Chado

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1972]
Once pombase/pombase-chado#739 is done we need to change the code for displaying "Existing annotations" for interactions so that it understands genotype-genotype interactions.

Currently it shows this, which isn't ideal:
![interaction-update-chado-1](https://user-images.githubusercontent.com/90474/60652087-a103a180-9e9b-11e9-9b0b-23075e5ba8a6.png)

**Comment by ValWood** [comment]
removing 
next and high priority as this comes after
https://github.com/pombase/canto/issues/2301

**Comment by kimrutherford** [comment]
This is probably a good task for me to work on next, now that we have some of the new style interactions in Chado.

It will take half a day, or maybe 1 day if it goes badly.  :-)

> Currently it shows this, which isn't ideal:

That's not true any more.  Currently none of the new style interactions from Chado appear in Canto.

**Comment by kimrutherford** [comment]
> It will take half a day, or maybe 1 day if it goes badly. :-)

1 day was an underestimate - extensions make things complicated.

**Comment by kimrutherford** [comment]
This is finally (mostly) done.  For now the "Existing annotations" table doesn't match the new annotations table because it isn't split into interactions with a single phenotype and those without.  Also if there are two single allele phenotypes for an interaction, they will be displayed in separate rows.  I can work on those differences later but for now I wanted to get the basic functionality working first.

It's not very useful at the moment because all of the new style interactions come from Canto.  When we are able to convert some of the BioGRID interactions to use genotypes we'll see more.

As an example there screenshots are from https://curation.pombase.org/pombe/curs/0ff28f78db735798/ro

Annotation from Chado:

![image](https://user-images.githubusercontent.com/90474/202376703-bdac314d-8481-450c-96f3-9c5c38ca3020.png)

Existing annotations from Chado:

![image](https://user-images.githubusercontent.com/90474/202375142-d37c0416-a3c6-45e0-aad3-98214ab14473.png)

**Comment by ValWood** [comment]
Looks good.

**Comment by ValWood** [comment]
closing !
