### ISSUE TITLE
triage status of browser papers

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1973]
Val said:
"Once hosted browser sets should move to this list:
https://curation.pombase.org/pombe/view/list/triage_browser_datasets_hosted?model=track
to be assessed for other curation
then can be curatable and->curated "

@kimrutherford can
triage_browser_datasets_hosted
show up as publication pages (eventually with a link to the browser track).

**Comment by Antonialock** [comment]
This is the current status of all hosted browser datasets.
I will move the ones flagged as "Browser datasets, to host" into "Browser datasets, hosted"

Curatable - approved
18488015 
21151114
21511999
23101633
23163955
23900342
25240800
25908789
27662899
29914874

Curatable community curation in progress
25665008

Curatable - sent for community curation
21981922

Browser datasets, hosted
22531001
24709818
30566651

Browser datasets, to host
24152550
24256300
1077324

**Comment by kimrutherford** [comment]
It looks like that change has worked.  I checked a few "hosted" and "to host" publications and they have publication pages now on the main site.

**Comment by Antonialock** [comment]
cheers
