### ISSUE TITLE
GI testing  , workflow

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1983]
If you try to make a GI when you have not curated any genotypes it isn't very obvious
 what to do:

![workflow](https://user-images.githubusercontent.com/7359272/61702476-bf8ce800-ad37-11e9-93a5-339d82a9eff9.jpg)

**Comment by ValWood** [comment]
Maybe the text just needs to be  different...

**Comment by kimrutherford** [comment]
Should the links to start an interaction annotation be hidden or greyed out and replaced with a message if there are no genotypes?

**Comment by ValWood** [comment]
I think people should still see the link and then get the message if they try to do it.

This will alert them that it is possible to curate genetic interactions, even if they haven't added genotypes.

**Comment by kimrutherford** [comment]
I've change it so that if there are no genotypes you get this dialog instead:

![interaction-warning-1](https://user-images.githubusercontent.com/90474/61850525-a7b88e00-af08-11e9-9eb9-e023d07788a3.png)

Let me know what wording you'd like.

**Comment by ValWood** [comment]
I think that's fine for now, unless anyone wants to refine.

**Comment by kimrutherford** [comment]
> I think that's fine for now, unless anyone wants to refine.

OK, thanks.
