### ISSUE TITLE
term suggestion seems odd in the GI pop-up box

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1984]
![term suggestion](https://user-images.githubusercontent.com/7359272/61702954-8c972400-ad38-11e9-894a-921464e4e0b7.jpg)

**Comment by ValWood** [comment]
I wonder if we just omit it here and let people add a comment if they could not find the correct term. It is rarely used  anyway , but for GI 's it  will be used even less because the majority will be existing phenotypes. 

It would be less daunting if the term suggestion wasn't there because it isn't clear what it is for if you don't require it.

OR
on the confirm term box add a new button,  "suggest term"  for those who need it

**Comment by kimrutherford** [comment]
> I wonder if we just omit it here and let people add a comment if they could not find the correct term.

Is that only for interactions?  Or should we hide the term suggestion when you use the dialog to make a normal ontology annotation?

**Comment by ValWood** [comment]
Users probably make the first annotation  using the  long way. Then copy and paste to make additional annotations. This means they know that they can suggest new terms in Canto if they have don GO/phenotype).

For interactions they are hopefully using and existing annotation, so they should not need to deepen.

 So I'm not sure we need to add the extra burden in the GI interface. I might be wrong....

**Comment by kimrutherford** [comment]
OK, thanks.  I've removed the term suggestion for interactions.

I've also arranged for it to be hidden for ontology annotations until the user selects a term.

**Comment by ValWood** [comment]
> I've also arranged for it to be hidden for ontology annotations until the user selects a term.

that makes sense!
