### ISSUE TITLE
Support intra-locus complementation

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1985]
This will be in new annotation type with a different list of evidence codes/interaction types.

The second genotype list will only show genotypes for the locus of the first selected genotype.

Should we show only single locus genotypes?

**Comment by kimrutherford** [comment]
> Should we show only single locus genotypes?

That wasn't clear.  I meant should we exclude multi locus genotypes from the dropdowns for complementation?

@vmt25 @gm119  Could you comment on this?  I'm going on what I remembered from our Skype but there was a bit of discussion so I'm not sure.

**Comment by vmt25** [comment]
> > Should we show only single locus genotypes?
> 
> That wasn't clear. I meant should we exclude multi locus genotypes from the dropdowns for complementation?
> 
> @vmt25 @gm119 Could you comment on this? I'm going on what I remembered from our Skype but there was a bit of discussion so I'm not sure.

Yes, these are single locus genotypes.
To be more precise, the interacting genotypes should be **single alleles** for the **same gene**.
E.g.
genotype A dropdown should show all single alleles associated with record
AND
genotype B dropdown should only show other available single alleles for the same gene as single allele genotype A.

**Comment by vmt25** [comment]
#1986 and #1985 are related, as they are 'genetic interactions' within the same gene.

**Comment by kimrutherford** [comment]
Hi.  I've made a bit of progress on this.  It's now possible to configure an interaction type that is restricted to single allele genotypes and the genotype B dropdown only shows genotypes from the same gene as the selected genotype A.

I've added a "complementation" annotation type in the Quick links menu of the flybase-test Canto.  Here's a dodgy test session as an example:
  https://curation.pombase.org/flybase-test/curs/2e523d5ee64ea295

What interaction types should be available for complementation annotations?  I've temporarily put "complements" in the dropdown for testing.

Is "interaction type" the right description if it's a complementation annotation?

**Comment by vmt25** [comment]
> Hi. I've made a bit of progress on this. It's now possible to configure an interaction type that is restricted to single allele genotypes and the genotype B dropdown only shows genotypes from the same gene as the selected genotype A.
> 
> I've added a "complementation" annotation type in the Quick links menu of the flybase-test Canto. Here's a dodgy test session as an example:
> https://curation.pombase.org/flybase-test/curs/2e523d5ee64ea295

It is not dodgy at all and works great! Huge thanks

> What interaction types should be available for complementation annotations? I've temporarily put "complements" in the dropdown for testing.

There are three values accepted (but I can configure them later on the yaml file):
Complements
Partially complements
Fails to complement

> Is "interaction type" the right description if it's a complementation annotation?

Maybe 'Complementation type' or maybe a question - 'Complements?' Cannot come up with a decent label at this time.


I can only think of three 'requests' to make this fully functional:
a) Having the three 'complementation' types/codes
b) remove genotype A (allele A) from the dropdown list for genotype B (allele B) - one allele cannot complement itself
c) remove alleles of the 'accessory' type from the genotype A dropdown list

**Comment by kimrutherford** [comment]
> I can only think of three 'requests' to make this fully functional:
> a) Having the three 'complementation' types/codes
> b) remove genotype A (allele A) from the dropdown list for genotype B (allele B) -
>     one allele cannot complement itself
> c) remove alleles of the 'accessory' type from the genotype A dropdown list

I've done a) and b).  I'm working on c)

**Comment by kimrutherford** [comment]
> c) remove alleles of the 'accessory' type from the genotype A dropdown list

That's done now too.

Vitor, if you'd like to configure this annotation type for yourself for testing, you'll need to add this to your `available_annotation_type_list` configuration:

```
  - name: complementation
    namespace: FlyBase_anatomy_CV
    can_have_conditions: 0
    single_allele_only: 1
    same_gene_interaction_only: 1
    category: interaction
    display_name: 'complementation'
    feature_type: 'metagenotype'
    evidence_codes:
      - Complements
      - Partially complements
      - Fails to complement
```

And then add `complementation` to the `enabled_annotation_type_list` config.

These changes aren't on the master Git branch yet because we're not ready at PomBase yet.  If you'd like to try this you'll need check out the development branch with:

```
  git pull
  git checkout genotype-interactions
```

If you have local changes you'll need to:

```
  git stash
  git pull
  git checkout genotype-interactions
  git stash pop
```

**Comment by vmt25** [comment]
Thanks a lot.
I'll give it a try

**Comment by vmt25** [comment]
>   - name: complementation
>     namespace: FlyBase_anatomy_CV

Hi just curious that this has a namespace despite of no CVs being involved (other than the list of 'evidence codes') - does it need it?

**Comment by vmt25** [comment]
intra-locus complementation does not need specifying phenotype - remove the 'Phenotype (optional)' field from the annotation menu

![Screenshot 2019-08-09 at 16 53 44](https://user-images.githubusercontent.com/33721108/62792041-51ca1580-bac6-11e9-87aa-c5b01d1adef5.png)

**Comment by kimrutherford** [comment]
> Hi just curious that this has a namespace despite of no CVs being involved (other than the 
> list of 'evidence codes') - does it need it?
> intra-locus complementation does not need specifying phenotype

Good point!  I've changed the code so that if there is no "namespace" configuration, the Phenotype box in the dialog will be hidden.  I've edited the config for the flybase-test Canto to remove "namespace" for the complementation configuration.

**Comment by vmt25** [comment]
Perfect! Thanks

**Comment by vmt25** [comment]
Closing this is working fine on testing and seems to be finished
