### ISSUE TITLE
interacting genotype options for dosage interactions

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1988]
Warning: headache potential ahead.

I regret to inform you that it's not always ideal to show all of the genotypes in the second pulldown ("Interacting genotype"), and the sensible options depend on the interaction type.

Specifically, the interacting genotype options with deletion alleles don't make sense for the "dosage" interaction types (Dosage Growth Defect, Dosage Lethality, Dosage Rescue). These are all interactions where the effect on the first genotype is due to overexpressing another gene*, so it really clangs to see deletions in the list of potential interactors. Moreover, it's usually -- but of course not always! that would be too easy :P -- the wild type allele that's overexpressed.

At a minimum, we need two things to be different for the dosage interaction types:

- Hide all genotypes that include any deletions
- Show the genes in the session, perhaps showing as wild type alleles ("yfg1+")

One possibility would be to show just the gene list, instead of the genotype list, for the dosage interactions. But sometimes a mutant can be overexpressed, and show an interaction with a second mutant. So I think curators should have a think and chat about what to do, because having just the gene list would lose some information, whereas a mix of genes and non-deletion alleles or genotypes could get pretty confusing.

I don't think this affects FlyBase because they're not using the BioGRID genetic interaction categories.

*sometimes more than one gene is overexpressed, although the BioGRID system we're using doesn't cope nicely with those cases anyway

**Comment by ValWood** [comment]
This ticket is at least partially covered by:
https://github.com/pombase/canto/issues/2533

**Comment by kimrutherford** [comment]
> Once my 2 newer tickets are implemented, I don't think there is anything else to do here?

Sorry, I'm a bit confused by this issue so I'll leave it to you to close it when you're ready.

**Comment by ValWood** [comment]
Superseded by https://github.com/pombase/canto/issues/2533 and https://github.com/pombase/canto/issues/2517
