### ISSUE TITLE
Allow gene product target for DNA-binding transcription repressor activity, RNA polymerase II-specific

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1989]
gene targets are not currently allowed

![Screenshot 2019-08-01 at 17 10 37](https://user-images.githubusercontent.com/12727506/62309453-616eac00-b47f-11e9-9497-031cafcd015f.png)

**Comment by ValWood** [comment]
targets could potentially be 2 types here

regulates (i.e. regulates expression of ) gene
and 
has_input "transcription factor" to identify the transcription factor it  represses.

**Comment by ValWood** [comment]
ignore me, this is a trancription factor?

**Comment by ValWood** [comment]
that's weird. Is it available for:
DNA-binding transcription factor activity

If so it should be available for descendants?

**Comment by mah11** [comment]
> DNA-binding transcription factor activity

This is not true (yet) - I just checked. Until two minutes ago, the config file had GO:0000982, not anything more general in the transcription factor branch.

I have now changed it to GO:0003700, which is the ID for the broadest "DNA-binding transcription factor activity" term. It should work next time Canto loads configs.
