### ISSUE TITLE
hyperlink linking to unexpected page

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1990]
after selecting a term; when clicking on the hyperlink "Search: "DNA-binding transcription activator activity, RNA polymerase II-specific""
located in the top left corner here
![Screenshot 2019-08-01 at 17 12 37](https://user-images.githubusercontent.com/12727506/62309684-e5c12f00-b47f-11e9-9309-225465c72441.png)

 I would expect to be taken back to the term locator page (eg https://curation.pombase.org/pombe/curs/2c0b3f9b052bea9e/feature/gene/annotate/2/start/molecular_function) , but instead I am taken to this page

![Screenshot 2019-08-01 at 17 14 13](https://user-images.githubusercontent.com/12727506/62309729-f40f4b00-b47f-11e9-874b-d26f43bdd1d1.png)

**Comment by kimrutherford** [comment]
I think there are two bugs because it also says this in your screenshot:
```
These extension types are available for ():
```

**Comment by kimrutherford** [comment]
I think both bugs are fixed now.
