### ISSUE TITLE
Genotype search/select

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1993]
For the new genetic interactions, I have some suggestions that might make the toggle between the genotype selection pulldown and the search box more intuitive:

- change " ✖️  Please select a genotype" to "[button or checkbox] Show genotype selection pulldown"
- change " 🔍  Please select a genotype" to "[button or checkbox] Show genotype search box"

Rationale:
- An icon that looks more like a button or checkbox will probably do a better job of saying "click me and something will happen" than the cross and magnifying glass (which aren't so obviously clickable). 
- I changed the text to describe the option that isn't active. Both the search box and the pulldown have instructions inside them, so we can use the space outside the box/pulldown for something less repetitious.

(follows on from #1900)

**Comment by vmt25** [comment]
I agree with this proposal - and the toogle looks great

**Comment by kimrutherford** [comment]
OK, I'll change it back to being a toggle, but make it look more like a button or checkbox.

**Comment by ValWood** [comment]
removing "next" as it might not be relevant if we do 
https://github.com/pombase/canto/issues/2301

**Comment by ValWood** [comment]
Is this still relevant? I can't see what it applies to.

**Comment by kimrutherford** [comment]
> Is this still relevant? I can't see what it applies to.

It's talking about the button here:

![annotation-edit-search-1](https://user-images.githubusercontent.com/90474/154383266-f8b297f7-1d31-4cae-963d-38e705e7f1f6.png)

**Comment by ValWood** [comment]
I. still don't fully understand.
For genetic interactions the user should not be editing the genotype at all.
They should select the appropriate double mutant for their genetic interaction.

**Comment by kimrutherford** [comment]
This is unrelated to genetic interactions.

**Comment by ValWood** [comment]
OK. I was confused by the title and the first sentence!

**Comment by ValWood** [comment]
What is the action here and is it quick?

**Comment by kimrutherford** [comment]
Sorry I'm not sure what the action is.

**Comment by ValWood** [comment]
@vmt25  can you describe the action for @kimrutherford.

In the  meantime I will put this at "low priority"

**Comment by kimrutherford** [comment]
Decided on a [search] button.

**Comment by kimrutherford** [comment]
Now I'm coming back to this issue, I'm not sure how useful a search button is since the genotype list is alphabetical order.  Maybe it's best to remove the button since the dialog is already very busy?

If we decide to keep the button, here's an option for making it more obvious:

![image](https://github.com/user-attachments/assets/01bc8e52-38b5-4496-9224-060b343dd7a8)

![image](https://github.com/user-attachments/assets/eb0f1c14-6a87-4186-90ac-5e49cff26b4a)

**Comment by ValWood** [comment]
I think the search was added for long lists, but I have never used it. Discuss on Tuesday

**Comment by ValWood** [comment]
No action
