### ISSUE TITLE
Need a query for strain names in Canto database

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1996]
Our proposed fix to issue #1718 involves loading PHI-base's list of strains, rather than fetching from UniProt. However, we first need to make sure that any strains already being used in curation sessions are renamed so they are consistent with the PHI-base list, where necessary.

In order to do this, I'd like to have a query for Canto's databases that returns the following:

- **curation session ID** (not essential, but would help for checking the context of the strain name)
- **strain name**
- **taxon ID** of the organism that the strain belongs to (not essential)

It would be nice if this could query both the `track` and `curs` databases, since we might have custom strains in our sessions that don't exist in UniProt but _do_ exist in our own list, in which case we could consolidate those custom strains into strains that will exist in `track` (once our new list is loaded).

**Comment by kimrutherford** [comment]
Hi James.

Try this horrific command line.  It uses a dodgy script (`canto_curs_map.pl`) that loops over each session and runs a bit of user supplied Perl code for each session.  In this case it calls the ServiceUtils code that gets called by the strain lookup web service and writes the session ID, the taxon ID and the strain name.  The fourth column will be "NEW" if the strain was added in this session and "EXISTING" if it's in the TrackDB.

Let me know how you get on.

```sh
./canto/script/canto_docker ./script/canto_curs_map.pl 'use Canto::Curs::ServiceUtils; my $service = Canto::Curs::ServiceUtils->new(curs_schema => $curs_schema, config => $config); my @strains = $service->_get_strains(); for my $strain (@strains) { print $curs->curs_key(), "\t", $strain->{taxon_id}, "\t", $strain->{strain_name}, "\t", ($strain->{strain_id} ? "EXISTING" : "NEW"), "\n"; }'
```

**Comment by jseager7** [comment]
The script worked as expected, thanks a lot. I can check these new strains against UniProt and the revised strain list now. Closing.
