### ISSUE TITLE
Hide 'Term ID' column from phenotype and genetic interaction annotations

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1999]
(Related to #1914, as it is about hiding/showing columns...)
(low priority)

The Term ID and Term name columns are redundant - would it be possible to hide the term ID column?

This would apply to both phenotype and interaction annotations

**Comment by mah11** [comment]
note: I really don't want this change in pombe Canto; I use the IDs a lot when looking at annotations the tables

**Comment by kimrutherford** [comment]
> I really don't want this change in pombe Canto; I use the IDs a lot when looking at annotations
> the tables

Yep, this would need to be an option.

**Comment by vmt25** [comment]
This comment is a reminder of the ticket (as discussed on 20 Apr VC)

Hide 'term ID' column to **ALL** annotation tables on all pages (front and genotype pages).
The column is slightly annoying as it does not help curation and only takes real-estate and distracts.

However, this is low priority.

**Comment by kimrutherford** [comment]
I had forgotten that this was partially implemented.  We have a per annotation type option `annotation_table_columns_to_hide` that was already working for ontology annotation.  I've now fixed it to work with interaction tables too.

I've updated the FlyCanto code and configuration to hide the term ID column.  If it works as you need could you close this issue?

The configuration changes are:
  https://github.com/pombase/pombase-config/commit/0c7750d69fd2f2a98b32340b3adc5098778c2dcc#diff-064abf46659edbdd7a91a9f75fcdcf38ab22ee9c00da998454ae3e7184d28bbb
  https://github.com/pombase/pombase-config/commit/4065e933988094de8151aa85befd7f5fd754aceb#diff-064abf46659edbdd7a91a9f75fcdcf38ab22ee9c00da998454ae3e7184d28bbb

**Comment by vmt25** [comment]
Perfect! Thanks
