### ISSUE TITLE
new data types protein feature annotation etc

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#20]
Make the protein feature subset of the sequence ontology available through the curation tool to curate protein features.

Questions
Curators,  we might need to look at these terms and decide if they are all useful

Original comment by: ValWood

**Comment by ValWood** [comment]
I think first we would like to  be able to do "expression levels" in Canto as that is the one we use the most. Also, if this was added it would deter people from curating WT expression phenotypes (which is now possible).

Should we use expression as a test?
 I think we might  only need to make a mini ontology and config files and then tell kim what 
label we want ?
https://curation.pombase.org/pombase-trac/wiki/CapturingGeneExpression

@mah11  could you have a stab  at this part when you get chance?
I'm guessing ti will be very quick for Kim to implement once we have this?

**Comment by kimrutherford** [comment]
> I think we might only need to make a mini ontology and config files and then tell kim what
> label we want ?

Yep, as long as you don't need to need to specify expression levels as percentages too.

Are you planning on just having terms like high, medium, low etc.?

**Comment by ValWood** [comment]
the would only be for  qualitative.

quantitative are rarer and  usually HTP  and we will do these in the spreadsheet

so we probably don't need to capture  numbers in canto

https://www.pombase.org/documentation/quantitative-gene-expression-data-bulk-upload-format

 @mah11  @Antonialock   ?

**Comment by kimrutherford** [comment]
> the would only be for qualitative.

Great.  In that case it probably only configuration is needed.

**Comment by ValWood** [comment]
Wonderful!

**Comment by ValWood** [comment]
Great.
If Midori can suggest text/teaks we can get this into live...

Should we add protein feature subset of SO now too (I know we don't use it very often)

**Comment by mah11** [comment]
Should we split gene expression off into its own ticket?

**Comment by ValWood** [comment]
I think the technology now exists to make it possible to edit protein motifs in Canto.

I was just reminded by this as I want to add nuclear localization sequences  to rec10 from
PMID:33526714
Rec10 NLS  KRKK 497-500
Rec10 NLS  KNNKK 516-519


This ticket has meandered about a  bit so I will make a new ticket for Protein sequence features.
