### ISSUE TITLE
Investigate using two namespaces/CVs for one annotation type

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2000]
The example for Fly-Canto is to be able to use the fly anatomy CV and cellular component interchangeably.

**Comment by vmt25** [comment]
This may have a simple solution.

I had a chat with Clare, our ontologist, and it seems feasible to create an artificial ontology that couples FlyBase's Anatomy ontology and GOs' cellular component ontology!
Clare will have a go at it!

Some terms may be common to both ontologies. Kim, do you think Canto may have issues handling these terms?

**Comment by kimrutherford** [comment]
> Some terms may be common to both ontologies. Kim, do you think Canto may have issues
> handling these terms?

Unfortunately, Canto will fail if there are terms common to two ontologies.  Each term needs to be in one ontology only.

**Comment by vmt25** [comment]
So, do we need to remove the duplications? or can we make them obsolute or add them to the subset 'do_not_annotate'?

Does Canto need a fully functional ontology with all parent/child relationships or could we simply delete some terms (and possibly losing parent/child relationships and breaking the ontology)?

**Comment by ValWood** [comment]
How many duplications do you have?
Are they really   the  same thing (if so how do you decide which ontology to use?)

If they are subtly different -like for example a SO chromosome (sequence feature) and a GO chromosome (component),  and there are not so many maybe these can be separated semantically.

If not, we can think again...

**Comment by vmt25** [comment]
> How many duplications do you have?

Not sure - have to wait for Gillian to be back from hollidays to know for sure.
Since transitioning to using GO Cellular component, FlyBase has been progressively obsolele-ing subcellular terms. There are few more Drosophila-related/relevant terms that we would like to keep, such as ring canals .

> Are they really the same thing (if so how do you decide which ontology to use?)

Yes, they are the same thing (e.g. 'neuromuscular junction' exists in both the FlyBase anatomy ontology and in GO CC.)
Not sure from which ontology the term is picked, since we (meaning curators) use the term rather the unique ID and any check is performed after making the annotation. Again, have to wait for Gillian to be back from hollidays...

> If they are subtly different -like for example a SO chromosome (sequence feature) and a GO chromosome (component), and there are not so many maybe these can be separated semantically.

That is not the case :(

> If not, we can think again...


Kim, Clare made a merged ontology for testing, which is deposited here: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/tree/master/for_canto

Would it be possible to try and load it and see if it breaks Canto?

**Comment by ValWood** [comment]
I'm confused. GO shouldn't matter?  I thought we were only concerned with you phenotype ontologies? So duplications between phenotypes and GO should not matter?

**Comment by vmt25** [comment]
> I'm confused. GO shouldn't matter? I thought we were only concerned with you phenotype ontologies? So duplications between phenotypes and GO should not matter?

Because the fly is a multicellular organism, it is really hard to use a single phenotype annotation type (with a single, pre-composed ontology). 

Therefore, we have two different types of phenotype annotations that go into two different fields, which are easily configurable within Canto (I did it myself in my local test canto - see #1836):

A) annotations for the type of phenotype, e.g. viability/lifespan, fertility, behavior defects, visible/size defects, basic cell size/shape/number/division/death, etc. There is a single ontology for this and it works fine on my local test canto.

and

B) annotations for where the phenotype manifests, which can be macro/multi/unicellular structures or subcellular structures - this is the one that would need combining FlyBase's anatomy ontology and GO's cellular component ontology

Our anatomy ontology includes anything including body parts, such as abdomen or wing, organs such as heart or ovary, tissues or cells, such as motor neuron X or oocyte. This ontology also includes subcellular organeles/structures but FlyBase started using GO CC (which is more compele) and since then most subcellular terms have obsoleted - but remain in the ontology.

Hope this makes it clearer.

**Comment by ValWood** [comment]
yes!

**Comment by kimrutherford** [comment]
> Kim, Clare made a merged ontology for testing, which is deposited here:
> https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/tree/master/for_canto

Thanks.  And thanks to Clare.

I've loaded it but I removed the "namespace: cellular_component" lines in the GO terms so that all the terms would be stored in Canto with the default namespace "fly_anatomy.ontology".  That works for testing but it's a bit hacky.

There were a few CC terms with the same name as an anatomy term.  Here are two examples:

------------------

more than one Term with the name "yolk" in namespace "fly_anatomy.ontology" -
existing:                    
[Term]   
id: GO:0060417  
name: yolk                     
def: The cytoplasmic part that serves as a nutrient reserve or energy source for the developing embryo. [GOC:dph, GOC:tb, PMID:18046696]                                                      
namespace: fly_anatomy.ontology                                                                                      
relationship: is_a GO:0044444                                                                                           
                                                                                      
and:                               
[Term]                          
id: FBbt:00000035 
name: yolk                                                                                               
def: The nutritive substance contained in the egg. [FBC:GG]
namespace: fly_anatomy.ontology                                                             
relationship: part_of FBbt:00000034                                                    
relationship: is_a FBbt:00007012                                                        
subset: cur
subset: FB_gloss                                                                                                                                              

------
                                                                                         
more than one Term with the name "micropyle" in namespace "fly_anatomy.ontology" -                                                                              
existing:                      
[Term]                       
id: GO:0070825                                                                        
name: micropyle                                                                                               
def: An external encapsulating structure part of the chorion. A single cone-shaped specialization that forms an opening in the chorion that allows sperm entry into the egg prior to fertiliza
tion. [GOC:cvs, GOC:mah, PMID:18649270]
namespace: fly_anatomy.ontology 
relationship: is_a GO:0044462                                                                                                                                                                 
                                           
and:                           
[Term]                             
id: FBbt:00000043               
name: micropyle 
def: A small opening at the anterior pole of the egg through which the spermatozoa enter. [FBC:DOS, FBC:GG]
namespace: fly_anatomy.ontology
relationship: develops_from FBbt:00004905                                                                                                                                                     
relationship: is_a FBbt:00007248                                                                                                                                                              
subset: cur                                                                                                                                                                            
subset: FB_gloss

**Comment by kimrutherford** [comment]
Canto seems happy with having GO CC and the FlyBase anatomy terms in the same namespace:

![flybase-canto-new-anatomy-1](https://user-images.githubusercontent.com/90474/63821310-a4e60880-c9a0-11e9-9acf-a6f2819a7590.png)

https://curation.pombase.org/flybase-test/curs/2e523d5ee64ea295#

**Comment by vmt25** [comment]
Tried to do an annotation using a duplicated term and there was an error - see below.

![Screen Shot 2019-09-03 at 11 45 42](https://user-images.githubusercontent.com/33721108/64167398-1a3e5700-ce41-11e9-8849-bba6a9f2b637.jpg)



It seems we (FlyBase) will have to create a fused ontology without duplicated terms...

**Comment by vmt25** [comment]
And it also failing to load non-duplicated terms. We (FlyBase) really need to fix this.

In the meantime, and for testing purposes, could you please load the standard fly anatomy ontology?

**Comment by kimrutherford** [comment]
> Tried to do an annotation using a duplicated term and there was an error - see below

I think I've fixed that problem.  Could you try again?

I forgot that Canto doesn't cope well when a term moves from one namespace to another.  It needed some manual intervention to remove the existing anatomy terms.

**Comment by vmt25** [comment]
> > Tried to do an annotation using a duplicated term and there was an error - see below
> 
> I think I've fixed that problem. Could you try again?

Tried it nd it works fine for Anatomy and Anatomy interaction annotations. Great.

 
> I forgot that Canto doesn't cope well when a term moves from one namespace to another. It needed some manual intervention to remove the existing anatomy terms.

We will work on this on our end, to remove the duplicated terms - Clare is on it!

**Comment by vmt25** [comment]
Had a try today and Anatomy annotations fail - the search box does not show up and says there are no terms for anatomy in the database

See screenshot:

<img width="702" alt="Screen Shot 2019-09-09 at 11 33 07" src="https://user-images.githubusercontent.com/33721108/64524092-bd85e500-d2f5-11e9-80b6-d8c29a6646cd.png">

Same message from the summary page quick links

**Comment by mah11** [comment]
opened #2023 for the anatomy interaction bug; don't know how far along the original issue is

**Comment by kimrutherford** [comment]
The flybase-test Canto is now using the merged OBO provided by Clare and it all seems to be working. I think we can close this but I'll do some more testing when I get back from holiday on Monday.

**Comment by kimrutherford** [comment]
I think this is OK now.  We can open new issues for problems.
