### ISSUE TITLE
Remove ellipses from link text everywhere

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2001]
I was thinking about how to reduce the use of screen width on the summary page, and one thing I noticed was that most of the links on the summary page (and elsewhere) end with a space and ellipses. This sometimes causes links to spill over two lines just because of the ellipsis, which looks weird:

![image](https://user-images.githubusercontent.com/37659591/63010880-22792700-be7f-11e9-975b-d48e3782c79f.png)

I presume the ellipses are there to indicate that the links lead to another page or start a workflow, but I’m not really sure it’s a good idea to have them, because there are inconsistencies: 

- there are links that _don't_ use ellipses and still go to a new page, such as the summary page gene links; and

- there are links that _do_ use ellipses but don't go to a new page, such as 'Delete...' on the genotype row actions (on Genotype Management).

In the interests of simplicity (and external consistency, since I don't often see ellipses used on other web page links these days), **I suggest that we remove ellipses from all links.** The possible exceptions to the rule might be:

- when following a link will interrupt a workflow that doesn't save its progress (such as annotation creation); or

- when the user would normally expect an action to take place immediately, but it doesn't: say, for example, that 'Delete' started a workflow rather than just deleting something &ndash; but even then I'm not convinced the ellipsis is necessary.

- - -

Otherwise, if we decide to keep the ellipses, I'd suggest that we either remove the space before the ellipsis, or replace the space with a non-breaking space, to ensure that the ellipsis can't flow onto a new line by itself.

**Comment by mah11** [comment]
I don't think I would miss the ellipses from any of the links @jseager7 has mentioned in the summary.

Ellipses are only worth keeping where they indicate that some text isn't shown. But I think that only affects abstracts (on publication pages) and some comments and term suggestions in the annotation tables, not any of the workflow or navigation links.

**Comment by jseager7** [comment]
> Ellipses are only worth keeping where they indicate that some text isn't shown.

I agree that we should keep ellipses in any link text that also happens to be truncated. Fortunately, my proposed changes shouldn't affect those cases, because I'm only replacing hard-coded ellipses that are written in the web page templates, whereas the ellipses that indicate truncation are dynamically generated by JavaScript or Perl.

**Comment by mah11** [comment]
In that case, I vote to go for it (tho I'm willing to wait for input from others).

**Comment by ValWood** [comment]
Sounds good to me...

**Comment by kimrutherford** [comment]
The idea behind the "..." is to make it clearer which links open dialog boxes instead of navigating to a new page.  If it's not helping make things clearer we can get rid of them.

**Comment by mah11** [comment]
>  "..." is to make it clearer which links open dialog boxes instead of navigating to a new page

Well, I needed you to tell me that -- i.e. I never figured it out just by using Canto -- so it seems it wasn't doing that job very effectively :/

**Comment by jseager7** [comment]
Since nobody seems to have any objections, I've opened a pull request (#2003) that makes this change.
