### ISSUE TITLE
extension jargon

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#2008]
has_substrate is showing for protien kinase activity 

<img width="899" alt="Screenshot 2019-09-09 at 23 58 27" src="https://user-images.githubusercontent.com/12727506/64572082-d32ef500-d35d-11e9-92b8-8af6df453685.png">

**Comment by mah11** [comment]
This is expected - it's only the interface for adding/editing extensions that uses the biologist-friendly display text. It would be a new feature to show the display text rather than the actual relation once the extension has been added.

**Comment by ValWood** [comment]
I think this is OK?
open on config tracker if not
