### ISSUE TITLE
copy and edit streamline

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2009]
We can  probably merge the 

"confirm term" pop up dialog with the previous pop-up when the term is a leaf node.

**Comment by kimrutherford** [comment]
I've had a go at this.

@ValWood: if you'd like to try this, the change is only in the test pombe instance: https://curation.pombase.org/test

@jseager7: please let me know if you notice any weirdness with term selection from the dialog box

It now looks like this if you're at a leaf term:

![term-confirm-shortcut-1](https://user-images.githubusercontent.com/90474/111718783-73ed6180-88bf-11eb-976f-1e40e7595dd2.png)

**Comment by ValWood** [comment]
great!

**Comment by kimrutherford** [comment]
I'll close this and we can open new issues if there are bugs.

**Comment by jseager7** [comment]
I've tested this on PHI-Canto and it works fine, thanks.

**Comment by kimrutherford** [comment]
> I've tested this on PHI-Canto and it works fine, thanks.

Thanks for testing.
