### ISSUE TITLE
Notes associated with the publication to be visible in the admin pages

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2014]
These are notes associated with the publication, rather than the already implemented allele-associated notes.

e.g. name and email address of corresponding author; a previous curator could not find some information or assumed some information.

These should show up on somewhere on the admin pages or maybe even in the summary page of the curation session.

Needs to have a field on the JSON input file.

**Comment by ValWood** [comment]
We have a note associated with a curation session (quite prominent)
and
A note associated with a publication (rather hidden)

It is possible that a paper may have more than one curation session (although it is not well supported and not used by us).

The difference is:
i) One is added by us upfront (is only visible by admin under publication properties)
ii) Is added by the community, but can be appended by us.

Personally I would be happy if we had a single not at the publication level, and that this was always visible regardless of how many sessions a paper had. I don't see a need for two types of note

**Comment by ValWood** [comment]
use triage comment for this note
https://github.com/pombase/canto/issues/2021

**Comment by kimrutherford** [comment]
> use triage comment for this note

Note to self: the triage comment needs to be exported into the JSON file.

**Comment by vmt25** [comment]
FlyBase's publication-related comments are only for intenal/curator related use.

These are added during
1 - previous curation before import into Canto for phenotype curation
2 - during phenotype curation within Canto

So the requirements are:

case 1 (pre-existent notes):
a) a field on the import json file where to append these notes
b) notes should be visible in two places:
(i) on the admin page for the publication (i.e. before entering a session)
(ii) within a session, in the publication summary page (perhaps on the right, below the authors)
c) these notes should be read-only

case 2 (added during a phenotype curation session):
a) a field on the export json field
b) the notes should be added somewhere in the publication summary page - same place as proposed for case 1, b), (ii).

**Comment by vmt25** [comment]
> b) the notes should be added somewhere in the publication summary page - same place as proposed for case 1, b), (ii).

I guess this (case 2b) is already there in the form of the 'Edit message to curators', but it would be useful if these would show up on the summary page, rather than being hidden from the session - same as case 1, a).

Also, it would be useful that this 'message for curators' is  different from the one proposed for paused curation (#2281), where it should be only temporary, while the session is paused.

**Comment by vmt25** [comment]
According to today's chat with Kim, it is possible to add functionality to display/add publication-level internal notes

Needs:
a) show the publication-level internal notes in the session's front page, probably in-between Annotate genotypes/Genotype management and the first annotations
b) internal notes field must be added to import/export json schema - need to ask Gillian to change script to include data in import; different notes in different lines, separated by an empty line.
c) old internal notes (i.e. imported from FB, in import json): read-only; as mentioned above, multiple notes on multiple lines, separated by an empty line; do not need to be exported from Canto.
d) new internal notes: editable - can we co-opt notes on submission field? @vmt25 will test if feasible; need to be exported

Kim will add notes documentation to JSON import format wiki.

**Comment by kimrutherford** [comment]
I've added the code for reading the notes from the input JSON file and for displaying the notes on the front page of the session.

For now the field is just text but we can change that if needed: https://github.com/pombase/canto/wiki/JSON-Import-Format#notes

**Comment by kimrutherford** [comment]
> and for displaying the notes on the front page of the session.

It looks like this:
![notes-display-1](https://user-images.githubusercontent.com/90474/98167110-6dcc9900-1f4d-11eb-96e9-4a83011e76fd.png)

@gm119 my test input file looked like:
```json
 {
   "PMID:12345": {
     "notes": "test note\nline 2 of notes fields\n\nanother line",
     "genes": [
       "FBgn0004107"
     ]
   }
 }
```

**Comment by gm119** [comment]
A couple of comments/questions

1. json format

The allele level internal notes have the following labels:

- internal notes that are in the input file (this is '_c. old internal notes_' in Vitor's comment above) get the label "comments"

- internal notes that are made by curators in canto (this is '_d) new internal notes_' in Vitor's comment above) and need _exporting_ get are in the  json under "notes" (and then are sub-divided under that, so internal notes are 'internal_note')

For these pub notes, could we follow the same convention if poss, else its going to get confusing.

So I think that the _"notes": "test note\nline 2 of notes fields\n\nanother line_, you just implemented are pub level internal notes in the _input_ file (ie. 'c. old internal notes') - so could they get the field label "comments" in the input json for consistency ?

(then when/if you implement exported pub level notes they can be notes ?) 

2. label on Canto 

The label 'External notes' is going to be a bit confusing for FB curators as what they will be seeing is our 'internal' (i.e. non-public) notes ! I guess 'External' is 'external to canto' ? but if canto is changed so that these pub level note can be added that will no longer be true - so perhaps the label needs changing to something less confusing - I think @vmt25 needs to comment on this bit

**Comment by vmt25** [comment]
> A couple of comments/questions
> 
>     1. json format
> 
> 
> The allele level internal notes have the following labels:
> 
>     * internal notes that are in the input file (this is '_c. old internal notes_' in Vitor's comment above) get the label "comments"
> 
>     * internal notes that are made by curators in canto (this is '_d) new internal notes_' in Vitor's comment above) and need _exporting_ get are in the  json under "notes" (and then are sub-divided under that, so internal notes are 'internal_note')
> 
> 
> For these pub notes, could we follow the same convention if poss, else its going to get confusing.
> 
> So I think that the _"notes": "test note\nline 2 of notes fields\n\nanother line_, you just implemented are pub level internal notes in the _input_ file (ie. 'c. old internal notes') - so could they get the field label "comments" in the input json for consistency ?
> 
> (then when/if you implement exported pub level notes they can be notes ?)
> 
>     1. label on Canto
> 

I agree with this would be useful.

> 
> The label 'External notes' is going to be a bit confusing for FB curators as what they will be seeing is our 'internal' (i.e. non-public) notes ! I guess 'External' is 'external to canto' ? but if canto is changed so that these pub level note can be added that will no longer be true - so perhaps the label needs changing to something less confusing - I think @vmt25 needs to comment on this bit

Yes, this should be labeled 'Internal notes'. Whether they are made upstream of Canto or within Canto they are for FlyBase's internal use and should be called 'internal notes'.

**Comment by kimrutherford** [comment]
> So I think that the "notes": "test note\nline 2 of notes fields\n\nanother line, you just implemented are pub level internal notes in the input file (ie. 'c. old internal notes') - so could they get the field label "comments" in the input json for consistency ?

I've made that change.

> Yes, this should be labeled 'Internal notes'.

Would "Comments" or "Internal comments" be better to match the JSON input?  I've made it a configuration setting so it's now easy to change.

Vitor, I've added this the to the configuration file in Git: https://github.com/pombase/pombase-config/blob/master/canto/flybase/canto_deploy.yaml#L67

**Comment by vmt25** [comment]
> > So I think that the "notes": "test note\nline 2 of notes fields\n\nanother line, you just implemented are pub level internal notes in the input file (ie. 'c. old internal notes') - so could they get the field label "comments" in the input json for consistency ?
> 
> I've made that change.

Thanks, It is not live yet, right?

> 
> > Yes, this should be labeled 'Internal notes'.
> 
> Would "Comments" or "Internal comments" be better to match the JSON input? I've made it a configuration setting so it's now easy to change.
> 

No. 'Internal notes' would be better.

Speaking of which, actually it may be better to rename the json fields for both publication and allele notes from 'comments' to 'internal_notes'. However, as this involved changes to Gillian's scripts that create the import json and that convert the export json into our proformae text files, I would ask for bot of you (@kimrutherford  and @gm119) to comment.

> Vitor, I've added this the to the configuration file in Git: https://github.com/pombase/pombase-config/blob/master/canto/flybase/canto_deploy.yaml#L67

**Comment by kimrutherford** [comment]
> Thanks, It is not live yet, right?

Yep.  We haven't loaded a new JSON file that includes the internal notes.

Currently it doesn't show the "Internal notes" section on the page if there isn't a "comments" field loaded for the publication. Would it be better if it always showed the header "Internal notes" and said "[none]" if there aren't any notes?

> Speaking of which, actually it may be better to rename the json fields for both publication and allele notes from 'comments' to 'internal_notes'.

It's no problem to change the Canto JSON loading code.

**Comment by gm119** [comment]
I'm fine with the canto json label being 'comments' as you have it now, so no need to change the Canto JSON loading code (as mentioned up-ticket, using comments is consistent with allele level internal notes).

So I will implement the input json script so that the input json has the form:

 
   {
     "PMID:12345": {
       "comments": "test note\nline 2 of notes fields\n\nanother line",
       "genes": [
         "FBgn0004107"
       ]
     }
   }

I just want to check before I do this - will these notes only be visible to admin users (this info can contain corresponding author data, so I think that they should only be visible to admin users (or I'll remove the corresponding author info) - just futureproofing in case we eventually expand fly Canto to include community curation)

**Comment by vmt25** [comment]
> I just want to check before I do this - will these notes only be visible to admin users (this info can contain corresponding author data, so I think that they should only be visible to admin users (or I'll remove the corresponding author info) - just futureproofing in case we eventually expand fly Canto to include community curation)


Hi Gillian,
That is an excellent point and I hadn't thought of that. These notes definitely should only be available to admin users.
As that was not spec-ed out, I am assuming they are visible to all types of users, but we must ask @kimrutherford

**Comment by kimrutherford** [comment]
> As that was not spec-ed out, I am assuming they are visible to all types of users, but we must ask @kimrutherford

The notes are visible to all users.  I'll fix that.

**Comment by kimrutherford** [comment]
> The notes are visible to all users. I'll fix that.

Fixed!

**Comment by vmt25** [comment]
Hi Kim

> Currently it doesn't show the "Internal notes" section on the page if there isn't a "comments" field loaded for the publication. Would it be better if it always showed the header "Internal notes" and said "[none]" if there aren't any notes?

Yes, please. Otherwise, if there are no pre-loaded notes how does one add notes within the session?

**Comment by kimrutherford** [comment]
> > Would it be better if it always showed the header "Internal notes" and said "[none]" if there aren't any notes?
>
> Yes, please.

That's done now.

> Otherwise, if there are no pre-loaded notes how does one add notes within the session?

Currently to add notes for exporting from Canto you need to use the "Edit message to curators" link which is only visible if you are logged in as admin.  You can also click the link to view the current message/notes.

![edit-message-1](https://user-images.githubusercontent.com/90474/100685683-b73fc500-33e1-11eb-9ad1-1af2c681d5e0.png)

**Comment by vmt25** [comment]
Oh, OK. Yes, that works.

**Comment by gm119** [comment]
Hi @kimrutherford working on changing the canto input json now.
Two things:
1. could we possibly change the json label from "comments" to "comment" for consistency (I mis-spoke previously when I said the label for the allele level internal notes is "comments" it is "comment" in the singular - really sorry).

2. for the allele level internal notes, if there is no such note, then comment is present as 'null' in the json, as follows:

Example:

   "PMID:31067455" : {
      "alleles" : {
         "FBal0147425" : {
            "comment" : null,
            "gene" : "FBgn0026367",
            "name" : "Scer\\GAL80[ts.&agr;Tub84B]",
            "synonyms" : [
               "tub-GAL80[ts]"
            ],
            "type" : "accessory"
         },
         "FBal0147806" : {
            "comment" : null,
            "gene" : "FBgn0030608",
            "name" : "Lsd-2[51]",
            "synonyms" : [
               "plin2[51]"
            ],
            "type" : "other"
         },
         "FBal0155850" : {
            "comment" : "BDSC number 57592. gm190606.",
            "gene" : "FBgn0014445",
            "name" : "Scer\\GAL4[Gr5a.8.5]",
            "synonyms" : [
               "Gr5a-GAL4"
            ],
            "type" : "accessory"
         },

......

Do you want me to do the same for the publication level internal notes, i.e.

   "PMID:32697999" : {
     "alleles" : {...},
      "comments" : null,
      "curation_priority" : 9,
      "genes" : {...},


   },

   "PMID:31067455" : {
     "alleles" : {...},
      "comments" : "comment added here\nanother one\netc",
      "curation_priority" : 9,
      "genes" : {...},


   },

**Comment by kimrutherford** [comment]
> could we possibly change the json label from "comments" to "comment" for consistency

No problem.  I've changed the code.

> for the allele level internal notes, if there is no such note, then comment is present as 'null' in the json, as follows:
> Do you want me to do the same for the publication level internal notes, i.e.

The loading code treats a null the same as a missing field so go for whichever is easiest.

**Comment by gm119** [comment]
thanks for fixing the label.

> The loading code treats a null the same as a missing field so go for whichever is easiest.

good to know ! I went for using null, so that its the same as the allele code. So input json changes are all done for this ticket now.

**Comment by vmt25** [comment]
Just opened a separate ticket, #2372, for the transfer of the internal notes created within canto (with the 'Message to curator' functionality) from the export json to proformae.

**Comment by kimrutherford** [comment]
> So input json changes are all done for this ticket now.

Great.  Thanks for the quick work.  Let me know when you have a new JSON file for testing.

**Comment by gm119** [comment]
sample json (ticket_2248.json) sent to kim

**Comment by kimrutherford** [comment]
> sample json (ticket_2248.json) sent to kim

Sorry for the slow reply.  The notes successfully load from that JSON file and this issue is a bit long now so I think I'll close it.  Let's open new issues for future problems.
