### ISSUE TITLE
Create annotation summaries (text/notes) for phenotypes, genetic interactions and complementation/rescue

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2015]
(As discussed on Tuesday's in-person meeting)

Create 4 text fields for summarizing (1) phenotypes, (2) genetic interaction, (3) xenogentic interaction (4) and intragene complementation+rescue data.

The overall format can be similar to the current 'new notes':
a) free text field
b) only available for single alleles
c) editable during the session.

These can all be bundled into e.g. a single pop-up window, provided they are in different cells and are well labeled. We will have a "Edit/show notes ..." link for each allele. See a mock-up below.

<img width="364" alt="Screen Shot 2019-09-12 at 14 33 43" src="https://user-images.githubusercontent.com/33721108/64788502-77858700-d56a-11e9-8520-e24dafe4d8f1.png">

(These are the only fields missing so that Fly-Canto becomes fully-functional for phenotype curation)

**Comment by kimrutherford** [comment]
I now have a prototype of this feature.  I've updated flybase-test Canto with the changes.  There is now a "View/edit notes" link in the right hand menu of the single allele genotype tables.  If an allele has notes then there will be a "notes" link beside the allele in the table.

I've called it "notes" because it's a short label to display.  Easy to change that though.

I've only just finish implement this and haven't tested it thoroughly.  Please let me know if you find any problems.

Vitor, we'll need to have a chat about updating your local copy of Canto as a few extra steps will be needed.

The note types are configured with a new setting in the canto_deploy.yaml file.  If no note types are configured then the notes edit links won't be shown.  Example config:

```yaml
allele_note_types:
  phenotype:
    display_name: Phenotype
  genetic_interaction:
    display_name: Genetic interaction
  xenogenetic_interaction:
    display_name: Xenogenetic interaction
  rescue_complementation:
    display_name: Rescue/Complementation
```

![allele-notes-proto-2](https://user-images.githubusercontent.com/90474/66367017-eb427480-e9ee-11e9-8325-bf350515d675.png)

![allele-notes-proto-1](https://user-images.githubusercontent.com/90474/66366708-d87b7000-e9ed-11e9-89d4-9a712d0e6619.png)

**Comment by vmt25** [comment]
> I now have a prototype of this feature. I've updated flybase-test Canto with the changes. There is now a "View/edit notes" link in the right hand menu of the single allele genotype tables. If an allele has notes then there will be a "notes" link beside the allele in the table.
> 
> I've called it "notes" because it's a short label to display. Easy to change that though.
> 
> I've only just finish implement this and haven't tested it thoroughly. Please let me know if you find any problems.
> 
> Vitor, we'll need to have a chat about updating your local copy of Canto as a few extra steps will be needed.
> 
> The note types are configured with a new setting in the canto_deploy.yaml file. If no note types are configured then the notes edit links won't be shown. Example config:
> 
> ```yaml
> allele_note_types:
>   phenotype:
>     display_name: Phenotype
>   genetic_interaction:
>     display_name: Genetic interaction
>   xenogenetic_interaction:
>     display_name: Xenogenetic interaction
>   rescue_complementation:
>     display_name: Rescue/Complementation
> ```
> 
> ![allele-notes-proto-2](https://user-images.githubusercontent.com/90474/66367017-eb427480-e9ee-11e9-8325-bf350515d675.png)
> 
> ![allele-notes-proto-1](https://user-images.githubusercontent.com/90474/66366708-d87b7000-e9ed-11e9-89d4-9a712d0e6619.png)


Tested on a curation session and it works fine.

But does this mean that this commit replaces the previous implementation of 'notes'? i.e. #1872 

Because they are differernt and should probably have different names.

The previous implementation (#1872 ) was for internal curation comments/notes and was working perfectly: existing notes from previous curation were called 'notes' and were read-only, whereas 'new notes' were the ones created during a given phen curation session and were edtable within said session.

These phenotype/interaction/etc are summary description of the data and for display to the website/database users, so should should probably be called 'discriptions' (a better name to be decided). Other than that - and like I said above - they seem to be working fine.

**Comment by vmt25** [comment]
> Vitor, we'll need to have a chat about updating your local copy of Canto as a few extra steps will be needed.

Just back from holidays and getting up to speed at work.
Let me go back to play with my local canto and then will be more than happy to do it.

**Comment by kimrutherford** [comment]
> But does this mean that this commit replaces the previous implementation of 'notes'? i.e. #1872
> Because they are differernt and should probably have different names.

I agree.  The internal notes are still there and they should have a different name.

Although I wondered about adding the internal curation notes (read-only) to same dialog as the other notes, like this:

![allele-notes-proto-3](https://user-images.githubusercontent.com/90474/66536403-4f913f80-eb79-11e9-94cf-54c81bc9e405.png)

We can then label them any way that makes sense in the dialog.  If we did that it would make sense to change the title to "View and edit notes".

**Comment by vmt25** [comment]
> Although I wondered about adding the internal curation notes (read-only) to same dialog as the other notes, like this:

I would prefer having them in different dialog boxes, with different buttons in the genotype table. 
The different buttons wlould warn the curator whether there are some important information about the allele that s/he should read (internal notes) or whether there are some curated discription.

**Comment by kimrutherford** [comment]
I've temporarily renamed the two links to "old note" and "new notes" until we have a chance to chat about it.  I think we should be able to set the two labels in the configuration file.

![allele-notes-proto-4](https://user-images.githubusercontent.com/90474/66884384-865dce80-f02d-11e9-9ff3-623e76162f05.png)

**Comment by kimrutherford** [comment]
> Example config:

The configuration has changed slightly.  It's now:

```yaml
allele_note_types:
  - name: phenotype
    display_name: Phenotype
  - name: genetic_interaction
    display_name: Genetic interaction
  - name: xenogenetic_interaction
    display_name: Xenogenetic interaction
  - name: rescue_complementation
    display_name: Rescue/Complementation
```

**Comment by kimrutherford** [comment]
I think this is done now.  Let's open new issues for any bugs.
