### ISSUE TITLE
Allow curation by FB publication IDS (FBrf)

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2016]
(this was briefly mentioned on Tuesday's in-person meeting, but is far from a priority)

It would be useful to allow searching for publications by the FlyBase's publication identifiers FBrfs because a) FlyBase mostly uses these and b) there are a few cases without PMID, including publications not yet indexed by Pubmed and direct personal communications by authors to FlyBase.

In most cases, however, there will be a correspondence between a FBrf and a PMID (e.g. FBrf0240088 == PMID: 30176986), so we can make do with the current setup.

**Comment by kimrutherford** [comment]
This overlaps with #1366 (although the DOI case is harder).

I think with could support FBrf IDs if we add  title, authors and publication date etc. to the JSON file from FlyBase.  Currently the loader assumes that the publication IDs in the JSON file are PMIDs which the loader uses to look up title, authors etc. from NCBI.  If those details were in the JSON I think we'd be able to use FBrf IDs in Canto.

**Comment by vmt25** [comment]
Ignore this for now - not a priority, as these are very rare and can be done by the current curation-to-proforma method.
