### ISSUE TITLE
gene quick links /interface improvements

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#202]
ok so, after having transferred an annotation it is a bit annoying having to click on 'summary' to then go into the gene that the annotation was transferred to to add an extension or whatever. 

I think it would be neater if:
-you would always stay on the gene page for the gene that is being annotated \(after adding annotation or extension etc\) i.e. no re-direction to the summary page at all unless the link is clicked
-have quicklinks to the right for the other genes in the paper, like on the pombase gene pages \(there is a large margin on the right anyway that isn't used\)

would this be possible?

Original comment by: Antonialock

**Comment by ValWood** [comment]
Antonai I'm closing this as I think its probably obsolete. If there is anything you  would still like could you open a new ticket?
Thanks

Val
