### ISSUE TITLE
bug: 'No interaction types available for...

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2020]
Submitted by @vmt25 

FlyBase phenotype interactions are not working at the moment because 'No interaction types available for "short lived"'. The same kind of message shows for every different 'original' phenotype CV I tried.

<img width="721" alt="Screen Shot 2019-09-09 at 16 06 55" src="https://user-images.githubusercontent.com/33721108/64542692-ec16b680-d31b-11e9-86c3-8a3024a9be73.png">

Could not check anatomy interactions because anatomy annotations are also not working.

Please see 'https://curation.pombase.org/flybase-test/curs/7e6b097ab9f9fca5#'

**Comment by kimrutherford** [comment]
I've temporarily removed the configuration that restricts the available interaction types based on the ontology term.  I think the code that handles that has a bug.

So now all the interaction types appear all the time but at least you should be able to make an annotation.  I'll work on fixing this properly next week.

**Comment by vmt25** [comment]
Yes, it is working without any constrictions. Big thanks

**Comment by kimrutherford** [comment]
I think this was fixed a while ago.
