### ISSUE TITLE
no terms available for anatomy interactions

### ISSUE THREAD

**Issue by mah11** [pombase/canto#2023]
Transferred from #2000 

Vitor says:

Had a try today and Anatomy annotations fail - the search box does not show up and says there are no terms for anatomy in the database

See screenshot:

https://user-images.githubusercontent.com/33721108/64524092-bd85e500-d2f5-11e9-80b6-d8c29a6646cd.png

Same message from the summary page quick links

**Comment by mah11** [comment]
I can confirm this happens to me in the FlyBase test canto

**Comment by mah11** [comment]
what I see when I click "anatomy interaction"

![Screen Shot 2019-09-18 at 16 35 19](https://user-images.githubusercontent.com/5196259/65163168-6b01a280-da32-11e9-8484-9312298099b1.png)

**Comment by kimrutherford** [comment]
I think I've fixed this now. The terms appear for me.

**Comment by vmt25** [comment]
As far as I can see, it looks fixed. Big thanks!

**Comment by kimrutherford** [comment]
> As far as I can see, it looks fixed. Big thanks!

Great.  I'm glad it worked.
