### ISSUE TITLE
Message "added no genes" when genes are added

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2028]
see:

![0genes](https://user-images.githubusercontent.com/7359272/65427693-c8b73580-de0a-11e9-8d49-be64589b6be0.jpg)

**Comment by jseager7** [comment]
Can you remember which genes you added when you triggered this message? Even the category of genes might help, like if you were only adding pathogen genes or host genes. Also, had you already added genes to the session, or did this happen after adding genes for the first time?

**Comment by ValWood** [comment]
session was
curs/11fa7733063e791c
Genes are the ones with a red X above (phxB1 is an example)
pathogen genes (I did not try other types). The genes without the red X were already present in the session.

**Comment by jseager7** [comment]
I've just tested this on my local session, and I couldn't reproduce the bug. I added all the genes that were greyed out in your session, made genotypes involving them so they wouldn't be enabled for deletion, then added the three new genes that triggered the bug for you, but the message said 'Added 3 genes' as expected.

@kimrutherford The message is constructed on the Perl side (in `Controller/Curs.pm`), so I don't think I can debug this any further.

https://github.com/pombase/canto/blob/2e475ba4901823ce18c2a870d6fd853346d66de8/lib/Canto/Controller/Curs.pm#L838-L844

**Comment by kimrutherford** [comment]
I've tried a few things but I can't reproduce this bug.  Val, could you let us know if you see it again?

**Comment by kimrutherford** [comment]
Val, have you seen this again?  Should we close this issue?

**Comment by ValWood** [comment]
yep I'll reopen if it reoccurs
