### ISSUE TITLE
configure PHIPO "altered RNA level"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2029]
To take genes recorded in the session.

![assayed_using_ticket](https://user-images.githubusercontent.com/7359272/65427775-fe5c1e80-de0a-11e9-81af-93befafce4e5.jpg)

**Comment by ValWood** [comment]
Are there already some examples of gene specific assayed using extensions?

**Comment by jseager7** [comment]
I'm not sure I follow &ndash; do you want the _assayed_using_ annotation extension enabled for the term 'altered RNA level' (PHIPO:0001060) and its children with a range of GeneID? Here's an example:

| domain ID | subset relation | extension relation | range ID | Canto display text | Help text | cardinality | role |
| --- | --- | --- | --- | --- | --- | --- | --- |
| PHIPO:0001060 | is_a | assayed_using | GeneID | assayed gene |  | 0,1 | user |

I think this issue possibly overlaps with https://github.com/PHI-base/phipo/issues/109, and that one got stuck on indecision about what the Range ID should be (and how exactly the range is resolved). If you think it should be Gene ID in this case, then this should be easier to configure.

**Comment by ValWood** [comment]
Yess the range should be gene ID  for this one. I wasn't sure how you would access the range because you do not preload, but it could be the IDs in the session. Is that possible? It might require new code?

**Comment by kimrutherford** [comment]
> but it could be the IDs in the session

Currently if you configure Gene ID for the range you can only select genes that you've already added to the session:

<img width="643" alt="Screenshot 2019-09-23 at 19 28 37" src="https://user-images.githubusercontent.com/90474/65452083-5f4e1b80-de38-11e9-97da-a83dd7b31935.png">

I think it should work the same for PHI-Canto but I haven't checked.

**Comment by ValWood** [comment]
>1 please

**Comment by jseager7** [comment]
This got delayed a bit because I forgot to add the _assayed_using_ relation to our extension ontology: hopefully it should be active on the main server by today or tomorrow.

**Comment by jseager7** [comment]
This extension should finally be working for 'altered RNA level' (and its children) on both servers now. Closing.
