### ISSUE TITLE
Allow Canto to reassign UniProt IDs

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2032]
Some of the curation we're doing for PHI-Canto involves cases where the UniProt IDs we're using are somehow incorrect: one example @CuzickA dealt with recently involved UniProt IDs incorrectly classified as _Hyaloperanospera parasitica_ when they should have been _Hyaloperanospera arabidopsis_. Once this is fixed in UniProt, we need some way to reassign the UniProt IDs for the genes (that are often identical in gene name and so on).

This particular example only has one gene that needs changing, but since Canto has no way to amend a UniProt ID, and can't propagate changes to a gene to the whole session (e.g. from genotype to metagenotype), the only way to currently do this is to add a new gene and then re-create everything in the session, short of the actual annotations.

I think @ValWood can advise on how common this situation is likely to be, but given the novelty of the research that PHI-base is focusing on, I'm guessing it will be more common than we'd like.

**Comment by ValWood** [comment]
I'm afraid I don't know how common this will be. I hope it won't happen very often, but I can't remember what caused this particular issue  (i.e. why the misclassification of Hyaloperanospera parasitica occurred). I know @CuzickA  explained. I talked to Kim about it and in this instance we thing that it will be easier to fix in the database ad a one off (Kim will have a call with you to do this).

**Comment by jseager7** [comment]
The session is fixed now. Moving the alleles from one UniProt ID to another was simple enough, but the session also needed alleles moving from one organism to another; that proved too complicated / dangerous to do at the database level. I'll mark this issue as future for now, until we have more need for it.

**Comment by jseager7** [comment]
Replacing this issue with #2677.
