### ISSUE TITLE
Canto views genes with the same gene name as equivalent

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2033]
It seems Canto only checks the gene names the list of existing alleles, rather than the underlying UniProt ID. This can be a problem in the event that a curation session needs to annotate two genes with the same name on the same organism: there's a session @CuzickA is working on now which deals with two RPP1 genes on _Arabidopsis thaliana_ with different UniProt IDs (I think the reason being because one ID is reviewed and the other isn't, so the session needs to migrate from the unreviewed entry to the reviewed one).

Here's the IDs in question: [D9IW02](https://www.uniprot.org/uniprot/D9IW02) and [F4J339](https://www.uniprot.org/uniprot/F4J339).

**Comment by ValWood** [comment]
I will chat with @kimrutherford  about this when he gets back from his meeting

**Comment by jseager7** [comment]
@kimrutherford I've done some more investigation and I think I've tracked the problem down to `sub allele_from_json` in `AlleleManager.pm`. The code only seems to check the 'primary identifier' and the 'name':

```pl
  my $primary_identifier = $json_allele->{primary_identifier};
  my $name = $json_allele->{name};
```
but in the example above, the names are equal, while the primary identifier is blank, for some reason:

![image](https://user-images.githubusercontent.com/37659591/65691019-0f559b80-e068-11e9-89ed-9f9a2198c9dc.png)

It looks like we should probably be using the `gene_systematic_id` field for comparison instead. I don't know what that corresponds to on the Perl side.

**Comment by kimrutherford** [comment]
Great work James.  That's very helpful.  I've added this to my list of jobs for early next week.

**Comment by kimrutherford** [comment]
Hi James.  I've had a go at fixing this on the master branch.  Could you give it a test?

**Comment by jseager7** [comment]
I've tested this with the previously mentioned gene IDs and Canto now allows alleles to be created for each gene. Thanks very much. Closing now.
