### ISSUE TITLE
enable "assayed_using" proteins 

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2035]
for
abolished protein localization (PHIPO:0000245):
and children

**Comment by ValWood** [comment]
also for

PHIPO:0000992 | increased expression of a host gene product involved in pathogen interaction

**Comment by jseager7** [comment]
It seems like 'abolished protein localization' (PHIPO:0000245) has been configured already, probably through the changes in #2044.

- - -

> also for PHIPO:0000992 | increased expression of a host gene product involved in pathogen interaction

Can I just confirm that we _don't_ need assayed_using ProteinID to be enabled on the parent term instead? The parent term is 'increased protein level in a pathogen host interaction' (PHIPO:0000991). I notice that this mentions protein in the term name, but would it still be _assayed_ using a protein?

**Comment by ValWood** [comment]
Hi @jseager7  well spotted. The assayed using should be moved up to the parent term.

v

**Comment by jseager7** [comment]
assayed_using is now enabled on 'increased protein level in a pathogen host interaction' (PHIPO:0000991). Closing.
