### ISSUE TITLE
disable penetrance for "abolished" branch

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2036]
I think we currently have penetrance for everything .
 we should try to restrict it by adding to high level branches but excluding the "abolished" and  "normal" branches where it would not be relevant

(I think we must do this for FYPO so you can take a look at our config?)

**Comment by mah11** [comment]
No. This is not accurate. Penetrance is relevant to any organism-level phenotype (equivalent to cell-level in FYPO but not PHIPO).

It is only population-level phenotypes for which penetrance is not valid.

**Comment by ValWood** [comment]
Of course you could be abolished in only a small number of cells.
