### ISSUE TITLE
include definitions for "extent of infectivity"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2038]
I find it hard to differentiate these but I think we have definitions for them somewhere?
Can these be included ?

![defs](https://user-images.githubusercontent.com/7359272/65895915-10f2cc80-e3a4-11e9-8472-afc9f64ff580.jpg)

**Comment by kimrutherford** [comment]
Val, are you thinking of showing the definitions to the right like we do with autocompleting?  Unfortunately I don't think it's easy for dropdowns?

James, do you think this is possible?

**Comment by ValWood** [comment]
Ah right, I thought we already did this in some places. Obiously not...

**Comment by ValWood** [comment]
like this?

![Untitled 2](https://user-images.githubusercontent.com/7359272/65899096-ebb58c80-e3aa-11e9-97b8-c217483bc43f.jpg)

**Comment by ValWood** [comment]
In fact, the infects tissue extension which is the same as this shows term definitions  exactly like this? So the functionality is already in place...

**Comment by CuzickA** [comment]
These terms are in PHIPO

PHIPO:0000004 unaffected pathogenicity
A phenotype where the ability of a pathogen, to produce an infectious disease in another organism is unaffected (i.e the same as wild-type, this could be pathogenicity present or pathogenicity absent).

PHIPO:0000007 pathogenicity absent
A phenotype where the ability of a pathogen, to produce an infectious disease in another organism is absent.

PHIPO:0000008 pathogenicity present
A phenotype where the ability of a pathogen, to produce an infectious disease in another organism is present.

PHIPO:0000009 gain of pathogenicity
A phenotype where the ability of a pathogen, to produce an infectious disease in another organism is obtained (pathogenicity was absent and is now present).

PHIPO:0000010 loss of pathogenicity
A phenotype where the ability of a pathogen, to produce an infectious disease in another organism is abolished (pathogenicity was present and is now absent).

PHIPO:0000012 unaffected virulence
A phenotype where the degree to which a pathogen (species or strain) is able to cause infectious disease in another organism is unchanged (i.e. the same degree of infectious disease as wild-type interaction).

PHIPO:0000014 increased virulence
A phenotype where the degree to which a pathogen (species or strain) is able to cause infectious disease in another organism is increased (i.e. more symptoms than normal).

PHIPO:0000015 reduced virulence
A phenotype where the degree to which a pathogen (species or strain) is able to cause infectious disease in another organism is decreased (i.e. fewer symptoms than normal).

PHIPO:0000964 loss of virulence
A phenotype where the degree to which a pathogen (species or strain) is able to cause infectious disease in another organism is abolished on a specific host genotype.

PHIPO:0000965 loss of virulence of gain of pathogenicity mutant
A phenotype where the degree to which a pathogen (species or strain) is able to cause infectious disease in another organism is abolished when observed in an interaction with a pathogen mutant which was previously engineered to gain pathogenicity.

**Comment by jseager7** [comment]
> James, do you think this is possible?

I expect it's going to be tricky to do this using a native `<select>` element &ndash; by that I mean the drop-down that gets created for 'extent of infectivity' and other extensions with few terms &ndash; the autocomplete drop-down is most likely using custom HTML markup to simulate the look and feel of a default drop-down.

I can try looking at re-purposing that custom drop-down (from the autocomplete) to behave more like a default one &ndash; meaning it won't allow the user to type anything but will still show hints next to the drop-down entries &ndash; but I'm not sure how long that will take.

**Comment by kimrutherford** [comment]
> like this?

It works for the autocomplete dropdown but not for normal dropdowns.

**Comment by ValWood** [comment]
@kimrutherford  isn't this a solved problem. This should be configured by  the parent of these terms in the ontology? 
Or  @CuzickA  if these terms have children this would not work. Presumably we can  create a "fake" small ontology for this subset with the definitions and it will all work automatically?

**Comment by ValWood** [comment]
> It works for the autocomplete dropdown but not for normal dropdowns.

Hey I will show you. I am sat at the same desk!

**Comment by ValWood** [comment]
OK I see. We need the autocomplete functionality, but we need to see the full list...

**Comment by kimrutherford** [comment]
I've investigated this and I think we can force the autocomplete list to be shown if it is short.  Like this:

![short-term-list-complete-1](https://user-images.githubusercontent.com/90474/68920751-13d24100-07db-11ea-9b75-42c59d3804fb.png)

It's a bit dodgy but it seems to work.  I haven't checked this change in yet.
