### ISSUE TITLE
new conditions do not always show in red

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2039]
Did somebody else mention this. They
 seem to GO red eventually, but I'm not sure why they don't appear red immediately?

![should show red](https://user-images.githubusercontent.com/7359272/65896231-c291fd80-e3a4-11e9-9cc8-8d45f44e49b9.jpg)

**Comment by kimrutherford** [comment]
Very strange!  What session is that?

**Comment by ValWood** [comment]
curs/79c56f92435923ab#

they are al red now. I don't know when they changed though...

**Comment by kimrutherford** [comment]
I think that red high-lighting was missing when you edit a condition with the dialog.  The table wasn't being updated correctly but would be fine if you refresh the page or navigate away and then come back.

I've fixed that bug.  I'll close this issue.  Please re-open if you see the same thing again.
