### ISSUE TITLE
quick links line wrapping

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2042]
This isn't a big deal right now, because its an admin only option (I think? or is it more generally avaiable now?).

Anyway the curation  type  "pathogen host interaction phenotype " line wraps so it looks like  2 annotation types:

**Comment by ValWood** [comment]
![only see this if logged in as admin_line wrap](https://user-images.githubusercontent.com/7359272/65897271-d3dc0980-e3a6-11e9-837c-c78b5be197d6.jpg)

**Comment by jseager7** [comment]
We tried to fix this before by redesigning the gene list to use less width, but I guess that still wasn't enough. The quick links aren't an admin only feature: they display when Advanced Mode is enabled, so any user could potentially see this.

There's some minor changes that could make it clearer that the lines have wrapped: we can capitalise the link labels and also add some bullets to the list:

![image](https://user-images.githubusercontent.com/37659591/65950498-1993e300-e436-11e9-93d8-420772156c29.png)

**Comment by ValWood** [comment]
That's clearer
