### ISSUE TITLE
config file for protein-protein interaction phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2044]
This needs an extension configuration.
All  branches of PHIPO  (pathogen, host and interaction) phenotypes which mention pathogen host interactions should prompt for 2 assayed using genes.

I'm not sure if this needs to be configured in the Canto settings, or the cardinality in the assayed_using file is sufficient.

@mah11  can advise.

This  is fairly high priority as we will use it a lot and it's a bit of  PINTA to navigate back to the gene list to copy paste the uniprot IDs

**Comment by jseager7** [comment]
Unfortunately I still haven't managed to get the `assayed_using` relation working on the PHI-Canto servers, even though I tried to follow PomBase's configuration setup. I'm not really sure what could be going wrong, so I'll have to discuss this with @kimrutherford, seeing as this is blocking multiple issues now.

**Comment by kimrutherford** [comment]
Hi James.  Could you attach your configuration to the issue or add a link to it?

**Comment by jseager7** [comment]
Here's the links to the config files (private repository, but you should all have access):

https://github.com/PHI-base/config/blob/master/annotation_extension/phipo_extensions.tsv

https://github.com/PHI-base/config/blob/master/annotation_extension/phipo_extension_relations.obo

https://github.com/PHI-base/config/blob/master/canto_deploy.yaml

**Comment by kimrutherford** [comment]
Thanks for the files.  It all looks OK.  It's worth checking that there are no errors that make the load script bail out.  Can you also check the process exit with: `echo $?` ?
It should print `0`

On Monday when I'm back home I'll try loading them locally.

**Comment by ValWood** [comment]
Thanks!

**Comment by jseager7** [comment]
@mah11 Thanks for this. I'll test the config on our servers shortly.

With regards to the permissions problems, it looks like with _Read_ permissions, you can only open a pull request on the config repository by forking the repository first. I've just given you _Write_ permissions for now, for the sake of convenience.

**Comment by jseager7** [comment]
It seems like the config started working once I restarted Canto on the server. Not sure if that's supposed to be required or not.

All of the extensions in the config file linked above ([phipo_extensions.tsv-2019-10-03.txt](https://github.com/pombase/canto/files/3686857/phipo_extensions.tsv-2019-10-03.txt)) are now enabled on the demo server, and they should be enabled on the main server sometime tomorrow.

One thing I'm not sure about: @ValWood you said in the first comment that "All branches of PHIPO [...] which mention pathogen host interactions should prompt for 2 assayed using genes." Did you intend for the extension to apply to the entire 'pathogen-host interaction phenotype' branch? Or is the current term domain of 'protein protein interaction phenotype' (PHIPO:0000132) the correct domain for this extension?

**Comment by mah11** [comment]
>  Did you intend for the extension to apply to the entire 'pathogen-host interaction phenotype' branch? Or is the current term domain of 'protein protein interaction phenotype' (PHIPO:0000132) the correct domain for this extension? The issue title suggests that it was for the latter term.

I hope Val meant the latter, because that would be correct, whereas any broader domain would be incorrect.

**Comment by kimrutherford** [comment]
> It seems like the config started working once I restarted Canto on the server. Not sure if
> that's supposed to be required or not.

A restart is required if the config if changed.

**Comment by jseager7** [comment]
This is enabled on both servers now, so I'm going to close this. Feel free to re-open if you notice any terms missing extensions.

**Comment by ValWood** [comment]
yes sory I meant 'protein protein interaction phenotype'
