### ISSUE TITLE
Search not finding all PHIPO terms

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2045]
some terms are not avaiable via autocomplete:

https://github.com/PHI-base/phipo/issues/139

(Search on melanin only finds a single term,  no accumulation terms found)

**Comment by jseager7** [comment]
Unfortunately I can't reproduce this on the annotation creation workflow, or on the annotation edit modal. I see all these terms:

![image](https://user-images.githubusercontent.com/37659591/65957292-5a92f400-e444-11e9-8a1f-1833a3d08ad7.png)

**Comment by ValWood** [comment]
ignore.
