### ISSUE TITLE
sometimes  WT expression level is unknown

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2046]
Sometimes  the  WT pathogen gene is expressed in the host (either by some transgenic construct  or by adding isolated protein to host cells.

In these cases, I don't think it is always possible to sensibly say anything about expression level. So I want to be able to do  WT gene/ expression level unknown.

I'm sure we discussed allowing this for PHI-Canto at some point?

**Comment by jseager7** [comment]
Does this mean you want 'Unknown' as an additional expression type _only_ for wild type alleles? Here's an example:

![image](https://user-images.githubusercontent.com/37659591/65968815-a8ffbd00-e45b-11e9-98a8-34b55a05b48c.png)

**Comment by jseager7** [comment]
Another option is to just make the Expression optional for wild type alleles, and then treat empty values for the expression as 'unknown expression'. That's probably a bit more ambiguous, though.

**Comment by ValWood** [comment]
Let me speak with @CuzickA  about this. I might be missing something.

Or maybe here we do need a different allele type. It's a weird one.  

Can we talk about this on the next call?

**Comment by ValWood** [comment]
I think I have a better idea.

Situation 1 is a WT pathogen gene  engineered into the host.

The best way to decsribe this would be an additional expression option

ectopic expression in host 

 Would this work? I think this would make it clear.

**Comment by ValWood** [comment]
OK scrub this. I just spoke with Midori.
Expression is only for expression level.  So I do want "unknown" to use here.  None of the other options work.

The least cludgy way to deal with the "ectopic expression in host" is to have a new allele type. I will make a ticket for this. It will be a regular type of experiment so we will definitely need a clear way to describe this.

**Comment by ValWood** [comment]
>Does this mean you want 'Unknown' as an additional expression type only for wild type alleles? Here's an example:

Not *only* for WT. It should already be avaiable for all other options. In PHI canto it is also required for unknown. I think for pombase it isn't allowed for unknown (unless  you are curating a diploid, possibly)
