### ISSUE TITLE
do we need to  show text "new annotations from this session" ?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2047]
Do we need to  show text "new annotations from this session" ? and "new single gene annotations"

We could only show the text

"existing annotations for this session" if there are any. I assume people will then be able to tell easily which ones they added. It seems a bit 'surplus'

![new?](https://user-images.githubusercontent.com/7359272/65968125-9df85d00-e45a-11e9-9072-be85c9fd9376.jpg)

**Comment by kimrutherford** [comment]
Yep, it makes sense to me to remove that text.

**Comment by ValWood** [comment]
Seems quick, if so  (undefr 5 mins) go ahead and do this  so we don't need to re-read ;)

**Comment by kimrutherford** [comment]
I've made that change.
