### ISSUE TITLE
new allele type, ectopic expression in host

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2049]
name: ectopic expression in host
    export_type: ectopic_expression_in_host
    show_description: true
    description_required: true
    allow_expression_change: true
    expression_required: true
    allele_name_required: false

**Comment by jseager7** [comment]
This is enabled on the servers now. The allele type is near the bottom of the list, below 'transformant'. Closing.

**Comment by ValWood** [comment]
I di not fully think this through and it doesn't completely work.

1. If you select this "allele type"  you cannot see the allele type in the session (annotations)

2. Allele description is free text. In reality the type can be any of the existing types (except deletion), you can ectoptically express a mutant too. This will be common.

Therefore we need a way to be able to specifiy a=n existing mutant type + ectopic expression.

Could we comment out/remove this allele type.

For now I have reverted the annotation to WT expression unknown.

I added ectopic expression as a comment . This might be adequate at least in the short term

We can discuss this on the next call.

**Comment by jseager7** [comment]
@ValWood Has this allele type been used in any existing annotations? @kimrutherford Can Canto handle allele types being disabled after alleles have been created using those types?

**Comment by jseager7** [comment]
Also, with regards to this:

> Allele description is free text. In reality the type can be any of the existing types (except deletion), you can ectoptically express a mutant too. This will be common.

Does this mean that 'ectopic expression' should be an extra expression type (like Knockdown, Overexpression, etc.)?

**Comment by kimrutherford** [comment]
> can Canto handle allele types being disabled after alleles have been created using those types?

It shouldn't be a problem.

**Comment by ValWood** [comment]
I used in one session, then I changed it back to WT unknown expression and made a comment about ectopic expression instead.

Sorry about this. Until I cam to do the annotation properly I didn't realise these issues.

**Comment by jseager7** [comment]
> Sorry about this. Until I cam to do the annotation properly I didn't realise these issues.

That's no problem. I just wanted to make sure it wouldn't break any existing sessions or prevent Canto from starting properly. I'll disable the allele type now.

**Comment by jseager7** [comment]
'ectopic expression in host' shouldn't appear in the list of alleles on both servers now. Let me know if you notice any problems. Closing.

**Comment by ValWood** [comment]
>Does this mean that 'ectopic expression' should be an extra expression type instead (like Knockdown, Overexpression, etc.)?

This was how I wanted to do it initially, but @mah11  because  this isn't really "expression level"
which is what our expression is. Expression level is part of the genotype, this isn't really  which is why we decided to fudge it into an "allele type"

If we were  totally accurate it would be part of the host genotype, but that would be crazy because we are annotating the pathogen gene. This is just a host construct to get the pathogen gene product into the host without infecting with the pathogen. It is mimicking endogenous expression by the pathogen, and this is OK because its effects can be assessed independently of the other pathogen gene products. The proteins are taken up by the host and function outside the pathogen, so it's a good approximation. So for now I think we are better just to tag them in some way and think if we need a way to distinguish these.

**Comment by jseager7** [comment]
> So for now I think we are better just to tag them in some way and think if we need a way to distinguish these.

Got it. I'm guessing tagging the alleles should be easier once allele comments are enabled on PHI-Canto.

**Comment by ValWood** [comment]
needed for PMID:31076860, a R. Solani gene is expressed in C beticola and causes virulence in sugar beet

**Comment by jseager7** [comment]
@ValWood Do we need to re-open this issue now that ectopic expression is required by a curation session?

**Comment by jseager7** [comment]
Nevermind, there's already a newer issue open at #2103.
