### ISSUE TITLE
"Add another gene"  pop up on extensions, don't ask for confirmation

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2057]
I often add genes here that are only required in extensions.
I don't like that I need to confirm. I would like it to just go into the list. If it's wrong  it can be deleted...

**Comment by ValWood** [comment]
@mah11 
@Antonialock 
would you prefer?

**Comment by mah11** [comment]
not sure I fully understand the question, but I don't have a problem with the current behavior

**Comment by ValWood** [comment]
This is really minor. I just don't like having to do the additional click to confirm the addition of another gene in the extension interface.
I do this a lot  - and it just feels like an unnecessary  additional click.

**Comment by kimrutherford** [comment]
> I don't like that I need to confirm. I would like it to just go into the list. If it's wrong it can be deleted...

My worry is for cases like entering "cdc22", you might end up with cdc2 instead if you don't type fast enough.  It will find cdc2 first:

![add-gene-dialog-1](https://user-images.githubusercontent.com/90474/70021373-642c0a00-15f5-11ea-98d4-d09deec83b07.png)

**Comment by ValWood** [comment]
I never had this problem.
But I will close for now.
I  will have a think when I am curating. I might re-request this at some point when we want to streamline the workflow a little more.

**Comment by Antonialock** [comment]
how about an additional button "add another" that is linked to the enter/return key (if possible?)

**Comment by ValWood** [comment]
Actually I did not describe the issue well.

I don't mind having to click OK here. It's just that since I added a gene to use as an extension at this point I would like it to appear as the extension. I need to then go to the drop-down and select it. But we can assume that I want this to be an extension if I need to add it at this point?

**Comment by kimrutherford** [comment]
> In the current workflow need to then go to the drop-down and select it.

That should be fixable!

**Comment by ValWood** [comment]
This is really minor. If it is easy  do it, but if not close.

**Comment by kimrutherford** [comment]
> In the current workflow need to then go to the drop-down and select it.

Fixed!
