### ISSUE TITLE
Fix term specific evidence codes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2065]
(Continued from #1991)

The implementation is buggy.

From @vmt25:

Had a better look at the interactions and it seems the default setting is not allowing any interaction type unless specified, so that only the terms for which ‘evidence codes' are on specified on canto_deploy will allow adding interaction types and completing the annotation .

**Comment by kimrutherford** [comment]
I think I've fixed the logic so that if there is no specific configuration for a term then the default interaction types / evidence codes are used.

@vmt25 I've updated the flybase-test Canto with the change.  When you get a chance could you let me know if it now works as expected?

**Comment by vmt25** [comment]
Will do.
Sorry for the trouble and thanks a lot.

**Comment by vmt25** [comment]
It seems to be working fine for the few test cases with configured constrictions.
At the moment I cannot make genetic interactions on my local Canto, so cannot test if I am implementing correctly the fuller set of CV terms with constrictions.

**Comment by kimrutherford** [comment]
Hi Vitor.  Can we close this issue?

**Comment by vmt25** [comment]
Yes. It seems to be working as intended on my local Canto.
