### ISSUE TITLE
exporting multispecies GO annotations from Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2066]
GO annotations which involve 2 species  need to have both taxon IDs in the taxon column

I don't know if this applies to all pathogene host interactions (I'll figure out if this makes sense later).

But it does apply to protein binding terms where there is a another organism ID in the with filed
Like

Magnaporthe oryzae | G4MXR2_MAGO7 | GO:0005515 | protein binding | IPI | TPR1 | 

-- | -- | -- | -- | -- | -- | --
where TPR1 is a (rice)host protein

taxon:382|taxon:3880

**Comment by ValWood** [comment]
e.g from  PMID:30610168

**Comment by kimrutherford** [comment]
All of the details are captured in the JSON output from Canto so I don't think there's anything to do here.
