### ISSUE TITLE
Allow assayed using extension on all protein-protein interaction terms

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2068]
PHIPO:0000199 | normal pathogen host protein protein interaction
 is not enabled

**Comment by jseager7** [comment]
Would it be better to enable the assayed_using protein extension on the parent term instead? That's '[pathogen host protein protein interaction phenotype](https://www.ebi.ac.uk/ols/ontologies/phipo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPHIPO_0000131)' (PHIPO:0000131).

**Comment by ValWood** [comment]
Yes can allow it here please.  This term probably won't be used much in annotation , but it is the correct point to place the extension.

**Comment by jseager7** [comment]
I've deployed the new config on the servers, so the extension will be available after the ontologies reload overnight. If you want the extension to be available sooner, let me know and I'll trigger a manual reload.

**Comment by jseager7** [comment]
This is enabled on both servers now. Closing.
