### ISSUE TITLE
text edit GO extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2069]
As admin, I do not have permission to edit GO extensions as free text

Thanks

Val

**Comment by mah11** [comment]
Check to make sure you're logged in, because it's working for me.

**Comment by ValWood** [comment]
I am. PHI canto specific possibly?

**Comment by mah11** [comment]
Could be. Definitely OK in live pombe Canto.

**Comment by kimrutherford** [comment]
> As admin, I do not have permission to edit GO extensions as free text

If you're an admin it should work.  Could you let me know which session you're looking at?

**Comment by ValWood** [comment]
curs/79c56f92435923ab

but I do see the "edit as text only ' link now. How weird...
