### ISSUE TITLE
Hide main navigation links when editing genotype

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2075]
I've just noticed that when a genotype is edited in the Genotype Management view, it seems most of the view is swapped out, but the main navigation links at the bottom of the page stay where they are. The edit page comes with its own action buttons too, and the effect is that you have two sets of navigational buttons at each end of the screen, which is confusing (for example, I kept pressing 'Go to summary' to exit forgetting that I could just press 'Cancel' instead):

![image](https://user-images.githubusercontent.com/37659591/66998984-1b63d480-f0cd-11e9-835b-b8750b568f08.png)

I think it would be clearer if we hid these navigation buttons when you're in the Edit Genotype view, and **only show the buttons for Cancel and Finish.**

@kimrutherford Did you ever intend for the other navigation buttons to remain visible on this view, or is it an oversight?

**Comment by kimrutherford** [comment]
> Did you ever intend for the other navigation buttons to remain visible on this view, or is it an oversight?

It's an oversight.  The buttons should be hidden when editing.

**Comment by kimrutherford** [comment]
That's fixed now.
