### ISSUE TITLE
Allele note creation fails when adding a second note

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2077]
Blocking #2067 

On the `phi-canto-testing` branch, creating an allele note fails with a database exception if you try to add an allele note after already adding one. It doesn't seem to make any difference which genes the alleles are from, or which allele types are used. I don't know if this affects other modes yet.

`Caught exception in Canto::Controller::Curs->ws_allele_set_note "error while creating AlleleNote: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::SQLite::st execute failed: UNIQUE constraint failed: allele_note.key [for Statement "INSERT INTO allele_note ( allele, key, value) VALUES ( ?, ?, ? )" with ParamValues: 1=8, 2="note", 3="test"] at lib/Canto/DB.pm line 248
 with args: {'value' => 'test', 'allele' => '8', 'key' => 'note'}
 at lib/Canto/Curs/AlleleManager.pm line 390." at lib/Canto/Controller/Root.pm line 53.`

Note that this error also dumps an inordinate amount of JSON and HTML data to the web console due to it triggering a 'Possibly unhandled rejection' warning from AngularJS, which isn't good.

**Comment by kimrutherford** [comment]
Hi James.  Thanks for the thorough testing.

I think the problem is that I put an unnecessary constraint on the `key` of the allele_note table.  That meant that only note of each type could be stored. 

I had this:

```sql
 CREATE TABLE allele_note (
        allele_note_id integer PRIMARY KEY,
        allele integer REFERENCES allele(allele_id),
        key text NOT NULL UNIQUE,
        value text
 );
```

instead of: 

```sql
 CREATE TABLE allele_note (
        allele_note_id integer PRIMARY KEY,
        allele integer REFERENCES allele(allele_id),
        key text NOT NULL,
        value text
 );
```

Here's a slightly dodgy but quick fix:

```sh
./script/canto_curs_map.pl 'my $curs_dbh = $curs_schema->storage()->dbh(); $curs_dbh->do("DROP TABLE allele_note"); $curs_dbh->do("CREATE TABLE allele_note (allele_note_id integer PRIMARY KEY, allele integer REFERENCES allele(allele_id), key text NOT NULL, value text);")'
```

That will iterate over the curs DBs and fix each one.

I've checked in a fix for the upgrade script that includes that change.

**Comment by kimrutherford** [comment]
Hi James.  Could you test this again when you get a change?

**Comment by jseager7** [comment]
This seems to be fixed now, but only after applying the script with `canto_curs_map.pl` (as above). I don't think this was because my database was already affected by the notes issues, because I started a fresh curation session after upgrading from database version 29 to version 31. Will it be necessary for this quick fix to be applied to all of our Canto deployments?

**Comment by kimrutherford** [comment]
The quick fix shouldn't be necessary when upgrading because I changed the upgrade code too.  Let's chat about this next time on Skype.

**Comment by jseager7** [comment]
I think this issue was because I forgot to update my branch, because it works after doing that. Closing now.
