### ISSUE TITLE
Link to metagenotype details from metagenotype annotation rows

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2085]
We can do this in PomBase Canto. It's a nice way to check that the phenotypes to a genotype align across experiments in a long table.

It is difficult to implement in PHI-Canto because the multispecies-genotype spans two table columns.

Ideas?

**Comment by kimrutherford** [comment]
That's supposed to be the case.  Could you paste in a screenshot and the session ID?

**Comment by ValWood** [comment]
from th e summary page

<img width="685" alt="Screenshot 2019-10-23 at 09 44 22" src="https://user-images.githubusercontent.com/7359272/67374874-bb13dd80-f579-11e9-8a66-cf606f038c86.png">

we have never been able to do this.

**Comment by ValWood** [comment]
I will have a radical suggestion. I was going to think about it for . a while.

In this table we could merge  pathogen and host genotype into "multispecies genotype"

It *should* be OK becasue  this is a display only view?

**Comment by ValWood** [comment]
@jseager7  are we still going to 

Parastagonospora nodorum -> P. nodorum

**Comment by jseager7** [comment]
> are we still going to Parastagonospora nodorum -> P. nodorum

That's the plan. I think the pull request that applies this change to the summary page is ready to go, I just got distracted and forgot to push it to GitHub. I'll do that shortly.

**Comment by ValWood** [comment]
OK, no hurry. I thought  we decided yes, but sometimes these things are in my head...

**Comment by jseager7** [comment]
> In this table we could merge pathogen and host genotype into "multispecies genotype"

Do you mean by merging the 'Pathogen genotype' and 'Host genotype' columns? That could make the resulting column contain a lot of information. However, it might give us the opportunity to save space in the case where the genotype names are short, and keep the two genotypes on their own lines:

![image](https://user-images.githubusercontent.com/37659591/68863122-a3e28e80-06e6-11ea-9368-1f916242ff0b.png)

Unfortunately trying to keep genotypes on individual lines leads to excessively wide tables in some real-world examples:

![image](https://user-images.githubusercontent.com/37659591/68863453-50247500-06e7-11ea-8fc6-297210b383cf.png)

And if we wrap the genotype names to stop this, we just end up trading height for width:

![image](https://user-images.githubusercontent.com/37659591/68863553-8235d700-06e7-11ea-9abf-89c50509cdbf.png)

Although it may be the case that the merged column is easier to read despite this.

**Comment by ValWood** [comment]
The 2 column multispecies genetype already takes a lot of depth usually:
(even if it isn't long)

<img width="342" alt="Screenshot 2019-11-14 at 14 08 44" src="https://user-images.githubusercontent.com/7359272/68864623-5a477300-06e9-11ea-8496-6e93b0c6a386.png">

However, this wasn't so much to save space as to allow us to  link to the multi-species genotype from the table.

Rows would be OK, but they mightg be easier to read if  they were displayed
organism,strain,allele, expression
rather than
allele, expression, organism, species

Then the rows would always begin with a species, which is more universally  recognisable/consistant  than an allele

**Comment by jseager7** [comment]
> Rows would be OK

Does this mean displaying the table more like a series of grouped rows, where the interactions are distinguished by background colour, kind of like what we used to do for the multi-allele genotypes?

![image](https://user-images.githubusercontent.com/37659591/68866298-17d36580-06ec-11ea-976a-ed6b8c291a5b.png)

I'm not sure exactly how this could be made legible when we have multispecies genotypes consisting of multi-allele genotypes.

**Comment by ValWood** [comment]
Let's keep this on the back burner. I will continue to think...

**Comment by jseager7** [comment]
@ValWood I've read through this issue again and I think I finally understand what you were originally asking for.

I see that for single-species phenotype annotations in PHI-Canto, the genotype name links to the details page for that genotype:

![image](https://user-images.githubusercontent.com/37659591/70432404-1856e600-1a77-11ea-8c6e-322b9e9e8c8a.png)

However, we have nothing equivalent for the pathogen-host interaction phenotype annotations, because the metagenotype name doesn't link to anything:

![image](https://user-images.githubusercontent.com/37659591/70432636-a6cb6780-1a77-11ea-91f6-5e3203e9660f.png)

Plus, adding a link is complicated by the fact that we don't have the metagenotype name in one cell (like we have with the single-species genotype names).

The obvious fix to this is to copy the metagenotype naming convention from the metagenotype details page, and put that all in one cell as a link:

![image](https://user-images.githubusercontent.com/37659591/70433516-dc715000-1a79-11ea-8afd-96487688842c.png)

But putting the entire name in one cell doesn't solve the problem that some rows could have a _lot_ of information: imagine a cell with two multi-allele genotypes, plus description and expression…

- - -

We could think about some of the layouts described above to control the space usage, but the layouts above might make the link destinations less obvious. For example, considering this layout:

![image](https://user-images.githubusercontent.com/37659591/68866298-17d36580-06ec-11ea-976a-ed6b8c291a5b.png)

If we followed the convention of the single-species annotations, and made the genotype names link to the metagenotype details page, then users might initially expect (based on the link names) that these links will go to their respective pathogen and host genotype, and not to the metagenotype that contains them.

**Comment by ValWood** [comment]
Yes that is the issue exactly.

It isn't a  show stopper, but it is quite useful when curating long sessions to see the list of phenotypes you already attached to a genotype, so you can see if there is already anything close, or if the phenotypes are logically inconsistent with each other.

**Comment by jseager7** [comment]
If we want a quick solution, we could make it so that clicking either the pathogen genotype or host genotype name in a metagenotype annotation row takes you to the details page for the metagenotype. If this proves confusing to new curators in future we could think of something else.

**Comment by jseager7** [comment]
Another option is adding an extra link to the row actions on the right, just for the metagenotype annotation rows:

![image](https://user-images.githubusercontent.com/37659591/70441570-8a85f580-1a8c-11ea-9362-717306d0cff6.png)

**Comment by ValWood** [comment]
> If we want a quick solution, we could make it so that clicking either the pathogen genotype name or host genotype name in a metagenotype annotation row takes you to the details page for the metagenotype. If this proves confusing to new curators in future we could think of something else.

I think this could be confusing

**Comment by ValWood** [comment]
>Another option is adding an extra link to the row actions on the right, just for the metagenotype annotation rows:

Let's leave for now. I can get to the annotations from the genotype table if necessary.
Will continue to think...

**Comment by jseager7** [comment]
@ValWood I've been looking at this issue again and thought of another idea. Would you be okay with adding another column to the metagenotype annotation rows, headed 'Metagenotype', that shows a highly abbreviated name for the metagenotype, and links to the metagenotype details page for that metagenotype? Here's an example:

![image](https://user-images.githubusercontent.com/37659591/84029134-d1946b00-a989-11ea-84f3-9b8b8e11b3c8.png)

Note I'm using (WT) as an abbreviation for the wild-type genotype.

**Comment by ValWood** [comment]
I'm not hugely keen on adding another column for this.  Here the collapsing is OK, but it would be another very full field in the frequent scenario where there are multiple strains for an allele.

I think I prefer the current workaround of going to the genotype management to get "other annotation"  to the burden of an additional column. Especially as this is more required  for curators checking than by users curating.

An option is to have visible in admin, but I  would still prefer fewer columns already...
@CuzickA  thoughts?

**Comment by CuzickA** [comment]
I'm not sure which of the above options I prefer. 
I think it is worth considering how we want to display the metagenotype annotations in the new PHI-base 5 Gene-centric view moving forward.
![image](https://user-images.githubusercontent.com/11753634/84125745-e8dc6280-aa34-11ea-85a8-aaf697f8bf16.png)

Where the genotype information (cdc2-r4(D90N aa) is in the screenshot do we want to have a single metagenotype link (linking to all annotations for this metagenotype)? Do we want to break this down into pathogen and host genotype components? If so, will each of these link to all annotations to the respective pathogen or host genotype?

Once we have made these decisions it may help to guide which display options we use for the curation above.

As an aside, @ValWood and I discussed that we would also like to see the background information for the metagenotype.

**Comment by jseager7** [comment]
> As an aside, @ValWood and I discussed that we would also like to see the background information for the metagenotype.

This was already implemented in https://github.com/pombase/canto/issues/2295. I'll update the servers today to apply it.

**Comment by CuzickA** [comment]
> This was already implemented in #2295. I'll update the servers today to apply it.

great thanks

**Comment by jseager7** [comment]
@ValWood @CuzickA do you want to add a 'View metagenotype' link to the metagenotype annotation table as a short-term fix for this? It's probably the easiest solution to the problem. Here's how it looks:

![image](https://user-images.githubusercontent.com/37659591/88173900-44486580-cc1b-11ea-89a0-256c22ebee23.png)

**Comment by ValWood** [comment]
I think it is slowing us down enough that it would be worth adding the link as a temporary solution.

Perhaps at the bottom of the list?

**Comment by jseager7** [comment]
> Perhaps at the bottom of the list?

I'm happy to make that change. The only reason I kept the 'view' link at the top was to keep the layout consistent with what's used for the genotype tables, where 'View annotations' is shown above 'Edit details':

![image](https://user-images.githubusercontent.com/37659591/88175608-fda83a80-cc1d-11ea-9036-409df237013c.png)

**Comment by ValWood** [comment]
OK!

**Comment by CuzickA** [comment]
I think it would be really useful to add this link. I think I would prefer it to be at the top of the list, so that I didn't accidentally press the 'delete' option.

**Comment by jseager7** [comment]
@ValWood @CuzickA This link is now enabled on the main PHI-Canto server. We can leave this issue open for now if the link is meant to be a temporary solution, but I don't mind if anyone decides to close it.

**Comment by jseager7** [comment]
There were no objections to this solution, so closing now.
