### ISSUE TITLE
Error during UniProt ID lookup

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2087]
While looking at #2028 I found a separate problem:

![uniprot-lookup-1](https://user-images.githubusercontent.com/90474/67445239-a2cebc00-f668-11e9-96ec-ce5439bd7216.png)

My IDs were: O69753 P0DPB9 Q7DC82 Q9HWH1

I was testing locally.

**Comment by kimrutherford** [comment]
It was a local database problem.  I had some organisms configured in `species_strain_map` and `host_organism_taxonids` that I hadn't loaded into the database.  I've changed the initialisation code to check this and give a better error:

```
"host_organism_taxonids" list in the configuration contains taxon ID "5755"
which is not in the Track database
```

**Comment by ValWood** [comment]
Is there a restriction to a specific species set?

If so why? I know there is a set of species of interest, but it seems a bit draconian to preven people adding a species.

If it is  a required restriction maybe this should say
Something like (species x is not in our local database, please contact the curators to add it?)
 
TIcket can say closed, but it this point needs discussion please put onto next agenda.

**Comment by ValWood** [comment]
Of course! I forgot about that..
