### ISSUE TITLE
Should we use the "Help text" column from the extension configuration?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2089]
There is a "Help text" column in the extension configuration file.  As far as I can tell, we don't use it and it's not displayed.

Would it be useful?

@vmt25

**Comment by vmt25** [comment]
I managed to add short help text to the previous column, 'Canto display text', which does the job. 
So it is not a priority and there is no need to change it at the moment. Good to know that the capability exists, though.

As an idea, maybe display that help text in smaller font size between the Canto display text/Extension type label and the input window on the extension creating window:
![Screenshot 2019-10-28 at 11 31 00](https://user-images.githubusercontent.com/33721108/67675206-7f608580-f976-11e9-9771-fe6b6370cb09.png)

**Comment by ValWood** [comment]
Can this close?

**Comment by kimrutherford** [comment]
Do you think we need more help text in the extension dialog?  If not this can be closed.
