### ISSUE TITLE
A recent change in copy/edit

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2090]
If I copy edit and switch a genotype, I now need to reload the page to see the changed genotype?

**Comment by kimrutherford** [comment]
That's a strange bug.  The term name changes in the table if edited and the table updates correctly if I change from a single allele to a multiple allele genotype.

i'll investigate this morning.

**Comment by kimrutherford** [comment]
It's a bug from the changes to support diploids.  I've fixed it now.
