### ISSUE TITLE
quicklinks

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2091]
were not visible for me today...

**Comment by ValWood** [comment]
Duplicate  apparantly

**Comment by kimrutherford** [comment]
Did you have "Advanced mode" turned on?

**Comment by ValWood** [comment]
Yep. @mah11 says there is an open issue about this, bit I can't find it?

**Comment by kimrutherford** [comment]
I don't know of an issue about this but we do need to chat about it.  Because currently you can't make an interaction annotation unless you're in Advanced mode.

**Comment by mah11** [comment]
> @mah11 says there is an open issue about this, bit I can't find it?

Not quite - I said there was a ticket (without specifying open vs. closed) about the empty bullets that show up when the quick links don't; that's #2073.

I haven't had quick links fail to appear when I've been curating in advanced mode.

> ... but we do need to chat about it. Because currently you can't make an interaction annotation unless you're in Advanced mode.

True, but tangential to both the #2073 anomaly and Val's missing link problem.

**Comment by ValWood** [comment]
Yesterday I did not notice  the empty bullets, which is odd.  I will check again today...

**Comment by ValWood** [comment]
this session has
https://curation.pombase.org/pombe/curs/310131206c5ef65d/ro

**Comment by ValWood** [comment]
You see the empty bullets in review mode...

**Comment by mah11** [comment]
> You see the empty bullets in review mode...

That is the problem noted in #2073.

**Comment by kimrutherford** [comment]
> You see the empty bullets in review mode...

Ah, sorry.  I fixed that in the new genotype interactions code but forgot to fix in the the main Canto.  It's fixed now.

**Comment by kimrutherford** [comment]
I think this is done now?
