### ISSUE TITLE
Question for community curation paper

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2096]
Hi KIm,

Can you let us know how many GO terms are filtered from PomBAse Canto as "taxonomically restricted"?

Cheers

Val

**Comment by kimrutherford** [comment]
Canto has 30276 GO term and GO has a total of 44700 terms (ignoring obsolete terms).

So that's 14424 terms that are filtered out.

**Comment by ValWood** [comment]
brill, thanks!
