### ISSUE TITLE
Enable GO qualifiers in PHI-Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2097]
I don't think any GO qualifiers are available

**Comment by mah11** [comment]
Needs to be added to extension configuration(s). Also, for pombase Canto we have the qualifiers themselves in a local mini-ontology so they can be loaded.

**Comment by kimrutherford** [comment]
> I don't think any GO qualifiers are available

Are you logged in as admin?

**Comment by ValWood** [comment]
Weird. The session I just accessed I could see them....

**Comment by ValWood** [comment]
very odd, I didn't login recently, I was definitely logged in earlier because I was using the admin interface...anyway, none issue
