### ISSUE TITLE
Multiple ways for users to avoid strain selection

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2102]
## Method 1: Exiting and re-entering the session

Canto's curation state management system doesn't check whether the user needs to enter strains for their organisms when a user returns to a session after exiting it.

That means if a user navigates away from Canto when they're on the confirmation page (`edit_genes`), upon returning to the session they will be put onto the curation summary page without having added any strains. Then, when they try to create a genotype, the strain selection only shows the placeholder option 'Choose a strain...', but of course they can't do that because there are no strains.

![image](https://user-images.githubusercontent.com/37659591/68393712-7b95e580-0164-11ea-828c-aaf83c75fa06.png)

## Method 2: Breadcrumb links

It's also possible to escape the strain selection page by clicking the summary link in the breadcrumb trail, because the link isn't disabled. It would probably be better to just hide the breadcrumb trail here, or at least make it only link back to the gene entry page, and not forward to the summary page.

![image](https://user-images.githubusercontent.com/37659591/68394150-3920d880-0165-11ea-9a5c-857fb32d943c.png)

- - -

I'm assigning this to @kimrutherford because it probably involves back-end routing work, but I'm happy to take a look at any front-end integration.

**Comment by kimrutherford** [comment]
I've had a go at fixing this.  The user now gets sent to the gene edit page if there are missing strains.

**Comment by jseager7** [comment]
@kimrutherford I've tested the bug about re-entering the session, and it looks like that's fixed, thanks. However, it's still possible to escape the organism confirmation page by clicking the summary page link in the breadcrumb trail. Do we want to do anything about this?

**Comment by kimrutherford** [comment]
> However, it's still possible to escape the organism confirmation page by clicking the summary
> page link in the breadcrumb trail. 

Hi James.  I can't reproduce that.  For me it always goes back to the gene and organisms confirmation page.  Let's chat about that on Skype.

**Comment by jseager7** [comment]
I must not have actually tested what the link did, because you're right, it does redirect to the organism confirmation. Closing again.
