### ISSUE TITLE
submit to curators button stays greyed out unless summary page reloaded

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#2105]
If you add annotations using the quicklinks, without reloading the page, then the submit to curators button stays greyed out

It is not a problem for community curators since if you use the "slow route" of going into a gene page and then add annotations you end up reloading the front page.

![Screenshot 2019-11-08 at 10 32 23](https://user-images.githubusercontent.com/12727506/68470376-d9353b00-0213-11ea-87da-9827a87cc5de.png)

**Comment by kimrutherford** [comment]
I think I've fixed this.  Please re-open if you find a case where it doesn't work.
