### ISSUE TITLE
submit to curators button

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2106]
Does not seem to be working for me (pombase canto) , but it could be my connection?

**Comment by ValWood** [comment]
no it seems to be the button...

**Comment by ValWood** [comment]
curs/00c35706b38fef88

**Comment by jseager7** [comment]
Is this a duplicate of https://github.com/pombase/canto/issues/2105? The discussion there implied that this issue was fixed, but we should probably re-open the linked issue if it's not.

**Comment by ValWood** [comment]
#2105 is different and was fixed.

I can now see the button in blue, but when I click it, nothing happens...

**Comment by kimrutherford** [comment]
Sorry about that.  I broke it while fixing #2105.  Fixed now.
