### ISSUE TITLE
Add script to clear Canto's gene cache

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2107]
Related: #1543, #1736 

A recent fix to change the display options of gene names doesn't seem to be working correctly, because Canto is configured to cache gene details when retrieving them from UniProt. This gene cache doesn't seem to clear automatically, so we need a script (`canto_admin.pl` or similar) that can be used to force the cache to rebuild.

Note that in cases where the gene lookup adaptor doesn't perform any caching (FlyBase, Pombase), we should _not_ attempt to rebuild the cache, because that will effectively wipe the gene data from Canto. So this script should only run when the gene adaptor is configured to use UniProt as its data source.

**Comment by kimrutherford** [comment]
I've created a script that will refresh the cached genes by re-fetching the details from UniProt.  This will update gene names, products and synonyms.  Any gene in the cache that has disappeared from UniProt will be left in the cache so that the Canto session is still usable.

Run it like:

```sh
./script/canto_admin.pl --refresh-gene-cache
```

**Comment by jseager7** [comment]
I've tested this locally and can't see any problems. Thanks. Closing now, but I'll re-open if I notice any problems on our servers.

**Comment by jseager7** [comment]
@kimrutherford I've tried running this on the production server, where we were already having issues with the UniProt identifier A9JX75 being cached as A9JX75_PHANO (instead of SNOG_20078) and clearing the cache doesn't seem to have helped. Is there a delay before the cache clearing actually takes effect, or do I need to restart Canto as well?

**Comment by kimrutherford** [comment]
You shouldn't need to restart Canto.  I assume there where no warnings from running the script?

Could you run this query and see what you get?:
```sh
sqlite3 data/track.sqlite3 "select * from gene where primary_identifier = 'A9JX75'"
```

**Comment by jseager7** [comment]
I don't remember seeing any warnings when the script ran. Querying the database gives me this:
```
43|A9JX75|Uncharacterized protein|SNOG_20078|330
```

**Comment by kimrutherford** [comment]
The database has the right name so maybe the gene names are cached and I forgot - it was implemented a long time ago.  Could you try restarting Canto when you get a chance?

**Comment by jseager7** [comment]
I might have been getting confused about seeing the UniProt accession ID on the confirmation page when I reopened this issue, thinking that Canto was treating the ID as the name when it wasn't. Either way, the correct name displays in the interface now. Closing.

**Comment by kimrutherford** [comment]
I've re-opened this because it would be good if the whole process wasn't in a single (long) transaction.  That causes Canto to hang until it completes.

**Comment by kimrutherford** [comment]
> I've re-opened this because it would be good if the whole process wasn't in a single (long) transaction.
>That causes Canto to hang until it completes.

I've finally had a look at this.  It wasn't possible to avoid hanging completely but I've changed the code to use more, shorter transactions.  Users might still see occasional short pauses if this action is run while curation is in progress.
