### ISSUE TITLE
Physical interaction quick link always visible

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2108]
I've noticed in the latest code that the Quick links section is always visible, whether you're in advanced mode or not, because the 'physical interaction' link is always visible:

![image](https://user-images.githubusercontent.com/37659591/68756549-3826f580-0602-11ea-8a02-b5bac9547225.png)

 I'm assuming this is because there's no other place in the interface to access 'physical interaction' now? I can't see it in the list of annotation types on the gene page.

**Comment by kimrutherford** [comment]
> I'm assuming this is because there's no other place in the interface to access 'physical interaction' now?

Yep, that's it.  It is a temporary measure until we can have a discussion about it.

> Maybe it would be better placed under the 'Annotate genotypes' section,

Possibly but it's needs a but of thought.  Some of the interaction types used by FlyBase are a bit weird and might not be a good fit.

**Comment by jseager7** [comment]
Now that the physical interaction annotation involves genes again (see #2116), could we put this link back on the gene details page? Admittedly it doesn't match the other workflows on that page (because it's a quick modal-based workflow, rather than a multi-step guided workflow), but it seems more sensible to have it grouped with genes (unless FlyBase handles physical interactions differently).

**Comment by ValWood** [comment]
P{hysical interaction should appear under "gene specific" curation type.
v
