### ISSUE TITLE
Regression in quick links display

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2109]
@kimrutherford It looks like the 'Quick links' section on the summary page has regressed from the changes introduced in #2048 and #2003. Namely, the bullets on the list are gone and the trailing ellipses are back. The previous changes were important for pathogen-host mode, because the 'pathogen-host interaction phenotype' link tended to wrap onto two lines, and the previously mentioned changes helped to fix the legibility issues from that happening.

Here's how it looked before:

![image](https://user-images.githubusercontent.com/37659591/65971760-a05db580-e460-11e9-954b-8a18fc876227.png)

And here's how it looks now:

![image](https://user-images.githubusercontent.com/37659591/68757496-f0a16900-0603-11ea-8d24-44b284d8fe65.png)

This could be related to changes made as part of #2091, but I'm not sure as that issue doesn't reference any commits.

**Comment by kimrutherford** [comment]
Sorry about that.  I broke it in 776d233af7e86638e8e26a.  Fixed now.

**Comment by jseager7** [comment]
Can I also change the list to remove the trailing ellipses and add capitalisation on the first letters?

**Comment by kimrutherford** [comment]
Ah, sorry about that too.  I've put those changes back and checked it in.

**Comment by jseager7** [comment]
Thanks, it's fixed now. Closing.
