### ISSUE TITLE
wt single gene allele unknown expression

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2112]
Sometimes I would like to be able to create a
WT unknown expression single allele to be able to combine in a "dimer' fusion.

**Comment by ValWood** [comment]
Required for this allele type
options are
Overexpression  
Wild type product level  
Knockdown  
Null

**Comment by jseager7** [comment]
I think this is currently enabled in pathogen-host mode (see #2050), and it's not based on individual Canto configuration (the values are hard-coded). So, if necessary, I could enable the option in single organism mode. Note that this would also enable it for FlyBase.

**Comment by kimrutherford** [comment]
This change was quick so I went ahead and did it.
