### ISSUE TITLE
created 2 identical alleles

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2113]
should I be able to do this?
<img width="525" alt="Screenshot 2019-11-14 at 17 37 03" src="https://user-images.githubusercontent.com/7359272/68888107-351b2a80-0712-11ea-8c30-9a1f82dea858.png">

**Comment by kimrutherford** [comment]
That shouldn't be possible.  Which session is it?

**Comment by ValWood** [comment]
it was
curs/4de0124e8c71968

but I might have done some strange duplicate and edit scenario to get this...

**Comment by ValWood** [comment]
Yes, it is possible to duplicate and edit, then to change our edited version to an already existing allele.

**Comment by kimrutherford** [comment]
> Yes, it is possible to duplicate and edit, then to change our edited version to an already existing allele.

Yep, unfortunately that's still the case.  There's an issue about it: #1130

**Comment by kimrutherford** [comment]
> There's an issue about it: #1130

I'll close this in favour of #1130
