### ISSUE TITLE
bug in publication details, abstract not resolving

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2119]
PMID:29859088
--
Title: | Using in vivo oxidation status of one- and two-component redox relays to determine H 2 O 2 levels linked to signaling and toxicity.
Authors: | Domènech A, Ayté J, Antunes F, Hidalgo E
Abstract: | ARRAY(0x55f907af3338) ARRAY(0x55f907b22ad8) ARRAY(0x55f907b4dfa0)
Citation: | BMC Biol. 2018 06 01;16(1):61
Publication date: | 01 06 2018

**Comment by kimrutherford** [comment]
That's getting through to the website: https://www.pombase.org/reference/PMID:29859088

There are four other publications in Canto that have similarly mangled abstracts:
PMID:25926993
PMID:28096973
PMID:30721412
PMID:31000995

I looks like the abstract details in the XML from PubMed are slightly different for those papers.

**Comment by kimrutherford** [comment]
> I looks like the abstract details in the XML from PubMed are slightly different for those papers.

The abstract is shown differently too on the HTML page.  The are sub-headings:
https://www.ncbi.nlm.nih.gov/pubmed/31000995

**Comment by kimrutherford** [comment]
> The abstract is shown differently too on the HTML page.

EuropePMC doesn't to a good job of format some of these:
http://europepmc.org/abstract/MED/31000995

I've had a look a fixing the parser.  There's a quick fix that will work for 3 of the five papers that have an issue.  I suggest that we just leave the abstract blank for the other two, or I can easily add the two abstracts manually.  The two difficult papers are PMID:28096973 and the one you spotted, PMID:29859088.

**Comment by ValWood** [comment]
I could mail PubMed/epmc about this?

**Comment by kimrutherford** [comment]
I don't think there's anything wrong with the XML we're getting from PubMed.  The structure is just a bit more complicated for those 5 papers.

EPMC aren't formatting it's very well on screen.

**Comment by ValWood** [comment]
OK, we can go with your solution.
v

**Comment by kimrutherford** [comment]
> OK, we can go with your solution.

That's done now.
