### ISSUE TITLE
Add option to nominate individuals to check curated papers

### ISSUE THREAD

**Issue by CuzickA** [pombase/canto#2120]
Kim H-K and I thought it would be useful for author curators who are capturing a very detailed level (Tier 2) of information from their paper to nominate fellow specialists in the field to double check their curation session.

This would probably not be required for Molecular Connections as they will be doing less detailed (Tier1) curation of multiple publications.

Is it possible to re-purpose the 'reassign curators' option on the front pages to the final submission pages to do this?

**Comment by ValWood** [comment]
I like this idea.
If you could somehow "pair" labs so they checked each others  publications it could increase the quality.

We find that people very rarely make incorrect annotations, but they do miss things.

For your community it might be easier to increase the coverage, and having a 'community checker'  might encourage  people work harder to ensure they capture everything correctly. Although in some ways the process is much more complicated, once you have learned it, the biology is more restricted in scope, so once  authors have curated a couple of papers their coverage should be high.

**Comment by kimrutherford** [comment]
> Is it possible to re-purpose the 'reassign curators' option on the front pages to the final
> submission pages to do this?

There is a "Reassign" button at the top right of all pages.  The current curator can reassign at any time and it can reassigned back if needed.  Would that function handle this case?

**Comment by ValWood** [comment]
Yes that will work @CuzickA  you can open a ticket on the curation tracker to implement a system to formalise the checking.
