### ISSUE TITLE
Disable phenotype quick links if there are no genotypes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2125]
In PHI mode disable host phenotype quick link if there are no host genotypes.  Similarly for pathogens.

**Comment by kimrutherford** [comment]
@jseager7 I've just created a pull request that hopefully fixes this.  At the same time I've added code to disable the "Pathogen genotype management" link on the front page if there are no genes.

Could you give this change a test when you have a chance?  Please go ahead and merge it if it looks OK, otherwise I'll fix the problems you find.  :-)

**Comment by jseager7** [comment]
Closed by #2152.
