### ISSUE TITLE
Add basic instructions on the metagenotype page

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2127]
(Extracted from #2053)

Currently there's no explanation on what the user should do when they reach the metagenotype page. Given that the metagenotype is a fairly novel concept that curators might not be familiar with, it would help to have some basic instructions on how to at least create a metagenotype.

@kimrutherford: It might get annoying for experienced curators to always see this message. Does Canto have any existing cookie / database support for storing user preferences like this?

**Comment by jseager7** [comment]
@ValWood is the following text enough to get users started with the metagenotype page?

> Choose a pathogen and host genotype to combine into a metagenotype.

Here's how it looks in Canto:

![image](https://user-images.githubusercontent.com/37659591/69631487-de80eb00-1045-11ea-9ea7-992864a33cb8.png)

**Comment by ValWood** [comment]
Looks fine.

Maybe to "to combine into" ->  "create a" (slightly shorter)

**Comment by jseager7** [comment]
I originally thought to say "create a metagenotype", but I thought "combine into" would make it more obvious that the metagenotype is a concept composed from other concepts. If you think the composition is obvious enough from the interface, then I'll change it to "create a metagenotype".

**Comment by ValWood** [comment]
Yes I wondered that, but I thought that if you are selecting 2 things it should be clear. Keep your wording though it's probably better to be explicit...

**Comment by jseager7** [comment]
These basic instructions are shown at the top of the metagenotype page now. Closing.
