### ISSUE TITLE
Allow interacting gene from different organism in physical interaction

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2129]
The physical interaction dialog prompts the user to select an organism when there is more than one organism in the session, then filters the list of genes according to the selected organism. However, this also filters the list of interacting genes such that you can only have physical interactions within the same species:

![image](https://user-images.githubusercontent.com/37659591/69620888-f94b6380-1035-11ea-81c9-05e134710140.png)

In pathogen-host mode, we need to have physical interactions _between_ species. This used to be possible in the old code because Canto showed all the genes in the session without filtering by organism. There's an example here:

![image](https://user-images.githubusercontent.com/11753634/67094814-702a4c80-f1ac-11e9-8424-3c838ab61ea2.png)

I think we need to add an 'Interacting organism' field to the dialog (that probably only needs to show when the number of organisms is greater than two, and/or when pathogen-host mode is enabled), so that the interacting gene can be chosen from another organism.

**Comment by kimrutherford** [comment]
Do we have to worry about the strain for physical interactions?

@ValWood @CuzickA

**Comment by ValWood** [comment]
No, I don't think so. We will capture variations in  phenotypes.
I think it will mainly be used for within species interactions anyway.

**Comment by kimrutherford** [comment]
When the two proteins are from different organisms, will they always be host and pathogen?

**Comment by ValWood** [comment]
I think so...

**Comment by kimrutherford** [comment]
> I think so...

OK, thanks.  Will protein interactions between species every be used by you in PomBase?  What about other MODs?

**Comment by jseager7** [comment]
> When the two proteins are from different organisms, will they always be host and pathogen?

When I spoke to @CuzickA about this, it seemed like there could conceivably be cases where the protein interactions could be pathogen–pathogen as well. It might be more flexible to not impose any role constraints on the organisms that can be selected for now, if that's easier.

**Comment by ValWood** [comment]
Not by PomBase.
Not sure about other MODs but doubtful outside symbiosis..

**Comment by ValWood** [comment]
but then it would be symbiotic (if functionally relevant) , wouldn't it?

**Comment by CuzickA** [comment]
In PHI-base we currently have a data column for capturing protein-protein interaction within the pathogen so it would be useful if we could continue capturing this in PHI-Canto.

I'm not sure if we would ever need protein-protein interaction between 2 pathogens?? We may well do for some of the more complex experiments where a pathogen gene is transformed into another pathogen for inoculation onto a host. It would probably be a good idea to keep the option open to capture this sort of data.

**Comment by CuzickA** [comment]
> I'm not sure if we would ever need protein-protein interaction between 2 pathogens?? We may well do for some of the more complex experiments where a pathogen gene is transformed into another pathogen for inoculation onto a host. It would probably be a good idea to keep the option open to capture this sort of data.

Maybe I'm mixing this up. This would be a complex genotype and protein-protein interactions here may be captured with a PHIPO term instead of a physical interaction annotation.

**Comment by ValWood** [comment]
Let's talk about the options in the New Year.

**Comment by kimrutherford** [comment]
> Let's talk about the options in the New Year.

Maybe something for the next call?

**Comment by jseager7** [comment]
@kimrutherford I'm going to close this for now because the issue itself is fixed (by #2160). If we ever need additional constraints on the physical interaction organisms then we can re-open this or make a new issue.
