### ISSUE TITLE
canto json output: bug with multiple extensions on same term ??

### ISSUE THREAD

**Issue by gm119** [pombase/canto#2135]
I think I may have found a bug or at least a problem in the json structure (sorry)

PMID:18062953

has in the  'New multi allele annotations'
`Genes 	Genotype (allele and expression) 	Term ID 	Term name 	Phenotype extensions 	Curator`
 `N	N[55e11] / N[55e11]	FBcv:0000414 	locomotor behavior defective 	dv_qual third instar larval stage | somatic clone 	Kim Rutherford <kmr44@cam.ac.uk> `

> 

the '|' in the Phenotype extensions is supposed to indicate that BOTH the extensions belong on the same Term name

So I'm aiming to build an annotation line that contains the following cvterm information:

locomotor behavior defective | third instar larval stage | somatic clone

i.e. both extensions attached to a single Term name.

So I thought that the json should look something like the following, with two extensions in the same annotation structure:

                                                                              {
                                                                                'conditions' => [],
                                                                                'creation_date' => '2019-09-09',
                                                                                'curator' => {
                                                                                               'community_curated' => $VAR1->{'curation_sessions'}{'4e77f8cbed7cd6c6'}{'annotations'}[0]{'curator'}{'community_curated'},
                                                                                               'email' => 'kmr44@cam.ac.uk',
                                                                                               'name' => 'Kim Rutherford'
                                                                                             },
                                                                                'evidence_code' => '',
                                                                                'extension' => [
												[
                                                                                                 {
                                                                                                   'rangeDisplayName' => 'somatic clone',
                                                                                                   'rangeType' => 'Ontology',
                                                                                                   'rangeValue' => 'FBcv:0000336',
                                                                                                   'relation' => 'qual'
                                                                                                 }
                                                                                               ],

												[
                                                                                                 {
                                                                                                   'rangeDisplayName' => 'third instar larval stage',
                                                                                                   'rangeType' => 'Ontology',
                                                                                                   'rangeValue' => 'FBdv:00005339',
                                                                                                   'relation' => 'dv_qual'
                                                                                                 }
                                                                                               ],
												]

                                                                                'genotype' => '7e6b097ab9f9fca5-genotype-16',
                                                                                'publication' => 'PMID:18062953',
                                                                                'status' => 'new',
                                                                                'term' => 'FBcv:0000414',
                                                                                'type' => 'phenotypic_class'
                                                                              },

but what the annotation actually has is two separate annotations:

1. this has FBcv:0000414 = locomotor behavior defective with the 'third instar larval stage' extension

                                                                              {
                                                                                'conditions' => [],
                                                                                'creation_date' => '2019-09-09',
                                                                                'curator' => {
                                                                                               'community_curated' => $VAR1->{'curation_sessions'}{'4e77f8cbed7cd6c6'}{'annotations'}[0]{'curator'}{'community_curated'},
                                                                                               'email' => 'kmr44@cam.ac.uk',
                                                                                               'name' => 'Kim Rutherford'
                                                                                             },
                                                                                'evidence_code' => '',
                                                                                'extension' => [
                                                                                                 {
                                                                                                   'rangeDisplayName' => 'third instar larval stage',
                                                                                                   'rangeType' => 'Ontology',
                                                                                                   'rangeValue' => 'FBdv:00005339',
                                                                                                   'relation' => 'dv_qual'
                                                                                                 }
                                                                                               ],
                                                                                'genotype' => '7e6b097ab9f9fca5-genotype-16',
                                                                                'publication' => 'PMID:18062953',
                                                                                'status' => 'new',
                                                                                'term' => 'FBcv:0000414',
                                                                                'type' => 'phenotypic_class'
                                                                              },

2. this has FBcv:0000414 = locomotor behavior defective with the 'somatic clone' extension

                                                                              {
                                                                                'conditions' => [],
                                                                                'creation_date' => '2019-09-09',
                                                                                'curator' => {
                                                                                               'community_curated' => $VAR1->{'curation_sessions'}{'4e77f8cbed7cd6c6'}{'annotations'}[0]{'curator'}{'community_curated'},
                                                                                               'email' => 'kmr44@cam.ac.uk',
                                                                                               'name' => 'Kim Rutherford'
                                                                                             },
                                                                                'evidence_code' => '',
                                                                                'extension' => [
                                                                                                 {
                                                                                                   'rangeDisplayName' => 'somatic clone',
                                                                                                   'rangeType' => 'Ontology',
                                                                                                   'rangeValue' => 'FBcv:0000336',
                                                                                                   'relation' => 'qual'
                                                                                                 }
                                                                                               ],
                                                                                'genotype' => '7e6b097ab9f9fca5-genotype-16',
                                                                                'publication' => 'PMID:18062953',
                                                                                'status' => 'new',
                                                                                'term' => 'FBcv:0000414',
                                                                                'type' => 'phenotypic_class'
                                                                              },

I think I may have mis-read the description of the format and perhaps there is supposed to be only one extension per annotation ? (I think I had it in my head it was like genotypes loci, but re-reading I think that was a misinterpretation on my part).

However, if that is the case, I'm not sure how we would distinguish between the case where the curator wants to write:

1. locomotor behavior defective | third instar larval stage | somatic clone

which is where they shown a locomotor behavior defective phenotype when testing both in the third instar larval stage AND somatic clone at the same time

2.

locomotor behavior defective | third instar larval stage
locomotor behavior defective | somatic clone

which is where they have looked and seen a locomotor behavior defective in two different experiments:
a. looking at the third instar larval stage
b. looking in somatic clones

(so in this second case, they haven't looked at/for the phenotype with both the extensions being tested at the same time)

We need to be able to distinguish 1. and 2. above as there are often cases where the same phenotype may need to be qualified with either multiple extensions at the same time and/or different single extensions - so I can't just chain all the extensions for a given genotype+term combination into a single line.

**Comment by gm119** [comment]
hang on, I've found a case where there are two items in the 'extension':

                                                                              {
                                                                                'creation_date' => '2019-09-09',
                                                                                'curator' => {
                                                                                               'community_curated' => $VAR1->{'curation_sessions'}{'4e77f8cbed7cd6c6'}{'annotations'}[0]{'curator'}{'community_curated'},
                                                                                               'email' => 'kmr44@cam.ac.uk',
                                                                                               'name' => 'Kim Rutherford'
                                                                                             },
                                                                                'extension' => [
                                                                                                 {
                                                                                                   'rangeDisplayName' => 'adult stage',
                                                                                                   'rangeType' => 'Ontology',
                                                                                                   'rangeValue' => 'FBdv:00005369',
                                                                                                   'relation' => 'dv_qual'
                                                                                                 },
                                                                                                 {
                                                                                                   'rangeDisplayName' => 'nutrition conditional',
                                                                                                   'rangeType' => 'Ontology',
                                                                                                   'rangeValue' => 'FBcv:0000714',
                                                                                                   'relation' => 'qual'
                                                                                                 }
                                                                                               ],
                                                                                'genotype' => '7e6b097ab9f9fca5-genotype-20',
                                                                                'publication' => 'PMID:18062953',
                                                                                'status' => 'new',
                                                                                'term' => 'FBcv:0000362',
                                                                                'type' => 'phenotypic_class'
                                                                              },


which corresponds to :

` Genes Genotype (allele and expression) Term ID Term name Phenotype extensions Curator`
`N	Scer\GAL4 | N[ECN.UAS]	Scer\GAL4[sca.PU](accessory) | FBcv:0000362 | increased cell number | dv_qual	adult stage , nutrition conditional | Kim Rutherford <kmr44@cam.ac.uk>`

so the problem may be me misunderstanding the difference between using a comma in the extensions bit as in this case and a | - so the json may be fine after all and we may just need to doc this well so that it doesn't confuse curators (we are used to the | meaning AND but it looks like the comma means and and | means OR).

So there may not be a problem after all - sorry again !

**Comment by gm119** [comment]
yep, my bad - no bug in the json, I had the , and | syntax muddled, so closing ticket

**Comment by kimrutherford** [comment]
> I had the , and | syntax muddled

That happens to me a lot too.  I'll improve that part of the documentation to make it cleat how the extension "," and "|" are represented in the JSON output: https://github.com/pombase/canto/issues/2136

Let me know if I can help with anything else or document anything better.
