### ISSUE TITLE
Gene unset when trying to store a duplicate physical interaction

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2137]
Possibly related: #2123 

If you try to store a physical interaction without changing any fields, the Gene field is reset to its default value.

For example, with the modal starting like this:

![image](https://user-images.githubusercontent.com/37659591/69798950-43fde480-11ca-11ea-9c3e-0bff002c4747.png)

After clicking OK, the modal appears like this:

![image](https://user-images.githubusercontent.com/37659591/69799000-57a94b00-11ca-11ea-82d5-000c3dae336d.png)

**Comment by kimrutherford** [comment]
Thanks for spotting that James.  I think the problem was that the OK button should have been disabled when no changes had been made.  I've had a go at fixing the logic that controls enabling/disabling.

Please re-open if the bug isn't fixed.
