### ISSUE TITLE
canto_docker: don't echo Docker arguments

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2138]
The `canto_docker` script prints the arguments for the `docker run` command before executing a command:

https://github.com/pombase/canto/blob/22126ba817731872cf9d1b4979fbddebe2330127/script/canto_docker#L36-L42

I don't think this should be enabled by default, because it makes it awkward when you want to pipe the results of a command to a file (usually when using `canto_export.pl`); the Docker arguments get printed into the first line of the file, meaning you have to remove the line afterwards if you want the JSON to be valid.

**Comment by kimrutherford** [comment]
Done!
