### ISSUE TITLE
canto_export.pl: add option to export individual sessions

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2139]
During development of PHI-Canto, we've been using exports from PHI-Canto to help collaborators on PHI-base to understand Canto's schema (mainly because they're planning on mapping from Canto's schema to another data source). I think it would be easier to generate sample data if the export could be restricted to a single curation session (or a specified list of session / PubMed IDs). It would save me from having to search through the full list of exported sessions to pick out the one I actually want.

Could we add an option to export a single session, based on a supplied identifier? I don't mind if it's a curation session hash or a PubMed ID; whichever's easier to implement.

**Comment by kimrutherford** [comment]
Hi James.  If you install the "jq" command you can extract a single session like this:

```sh
jq '.curation_sessions."0003e68d3973e436"' sessions.json > session_0003e68d3973e436.json
```

https://stedolan.github.io/jq/

**Comment by jseager7** [comment]
That still means we need to export all the sessions, which is a bit slower, but I guess it's not worth the effort implementing this in the script considering PHI-base is the only team that needs it. I'll test `jq` later and close this issue if it works.

**Comment by jseager7** [comment]
`jq` seems to work fine. I've tweaked the script so that it takes the session key as an argument, and preserves the rest of the JSON structure (rather than just extracting the curation session object):

```sh
jq --arg key "${1}" '{"curation_sessions": {"\($key)": .[]."\($key)"}}' sessions.json
```
So you can do something like this:
```sh
sh export_session.sh 065bd768c3aa342f
```
To return the following JSON:
```json
{
  "curation_sessions": {
    "065bd768c3aa342f": {
      "metadata": {
        "accepted_timestamp": "2019-04-03 11:35:08",
        "annotation_status": "CURATION_IN_PROGRESS",
        "annotation_status_datestamp": "2019-04-03 11:35:29",
        "canto_session": "065bd768c3aa342f",
        "curation_accepted_date": "2019-04-03 11:35:08",
        "curation_in_progress_timestamp": "2019-04-03 11:35:29",
        "curation_pub_id": "PMID:57576",
        "curator_email": "demo@example.com",
        "curator_name": "Demo User",
        "curator_role": "community",
        "session_created_timestamp": "2019-04-03 11:35:02",
        "session_genes_count": "1",
        "session_term_suggestions_count": "0",
        "session_unknown_conditions_count": "0",
        "term_suggestion_count": "0",
        "unknown_conditions_count": "0"
      },
      "publications": {
        "PMID:57576": {}
      }
    }
  }
}
```
I'll add this to our config repository later. Closing now.
