### ISSUE TITLE
Change summary column widths to fit PHI-Canto gene table

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2140]
I've noticed that when PHI-Canto is using longer organism names (e.g. Parastagonospora nodorum), the gene list on the summary page collapses to one column rather than two:

![image](https://user-images.githubusercontent.com/37659591/69812517-322b3a00-11e8-11ea-9f66-fc235a1e492e.png)

I could fix this by letting the gene column take up a bit more width on the page. I can gain the space from a) narrowing the Publication details column and b) moving the PubMed link below the publication details, rather than having it to the right.

Before:

![image](https://user-images.githubusercontent.com/37659591/69812745-ac5bbe80-11e8-11ea-801c-e7ad53432a4f.png)

After:

![image](https://user-images.githubusercontent.com/37659591/69812760-b7165380-11e8-11ea-8672-c88704cf531f.png)

This should make it more likely that the gene list retains its two-column layout on wide screens.

**Comment by ValWood** [comment]
Could the Pubmed link go immediately to the right of the "publication details"  title in the free space rather than underneath? If not it's fine underneath

**Comment by jseager7** [comment]
> Could the Pubmed link go immediately to the right of the "publication details" title in the free space rather than underneath?

Yes that should work. I'll post a screenshot after I've tested it.

**Comment by jseager7** [comment]
Here's how it looks placed immediately to the right of the title:

![image](https://user-images.githubusercontent.com/37659591/70063008-055b9600-15df-11ea-9a2e-89231cab70c1.png)

Another option is to align it to the right of the section:

![image](https://user-images.githubusercontent.com/37659591/70063106-258b5500-15df-11ea-805b-b012db5c8998.png)

If you think either design needs extra spacing, that can be easily added.

**Comment by ValWood** [comment]
I like the second (or the first with a little more spacing). Your call.

**Comment by jseager7** [comment]
I prefer the second option as well. I've opened a pull request to make these changes.
