### ISSUE TITLE
Annotation extensions to migrate

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2141]
- [ ] annotations with [exists_during] meiotic cell cycle (GO:0051321) 
need to migrate to "[exists during] meiotic cell cycle phase (GO:0098762)" 
(90)

- [ ] annotations with [exists_during] mitotic cell cycle (GO:0000278) need to migrate to "[exists during] mitotic cell cycle phase (GO:0098763)" 
(167)

- [ ] annotations with [exists_during] meiosis II (GO:0007135) need to migrate to "[exists during] meiosis II cell cycle phase (GO:0098765)" 
(12)

- [ ] annotations with [exists_during] meiosis I (GO:0007127) need to migrate to "[exists during] meiosis I cell cycle phase" ~(GO:009876)~     (GO:0098764) 
(13)

**Comment by kimrutherford** [comment]
Do these changes need to be made soon?

**Comment by ValWood** [comment]
In the next few weeks would be good, but if you have a lot on we can wait until the New Year. I know you are going off soon.
In the whole scheme of things GO can wait ;)

**Comment by kimrutherford** [comment]
Just to check: is it just the range of the extension that needs updating in these cases?

> annotations with [exists_during] meiosis I (GO:0007127) need to migrate to
> "[exists during] meiosis I cell cycle phase" (GO:009876)

Is GO:009876 supposed to be GO:0098764?

**Comment by kimrutherford** [comment]
> Just to check: is it just the range of the extension that needs updating in these cases?

I have a script ready to go to change the GO terms.

**Comment by ValWood** [comment]
1.  just a straight swap of one term for the other in extension s
2. yup fixed

**Comment by kimrutherford** [comment]
I've made those changes in Canto.  You'll see them on the main site on Wednesday morning.

**Comment by ValWood** [comment]
I'm not sure if this worked:

vw253-mbp13196:Desktop vw253$ cut -f 16 gene_association.pombase\ \(1\)  |sort |uniq -c | sort |grep "exists_during" |more |grep GO:0051321
   4 exists_during(GO:0000278),exists_during(GO:0051321)
  19 exists_during(GO:0051321)

(on the current GO download file)

**Comment by ValWood** [comment]
and
vw253-mbp13196:Desktop vw253$ cut -f 16 gene_association.pombase\ \(1\)  |sort |uniq -c | sort |grep "exists_during" |more |grep GO:0000278
   4 exists_during(GO:0000278),exists_during(GO:0051321)
  94 exists_during(GO:0000278)

**Comment by ValWood** [comment]
cut -f 16 gene_association.pombase\ \(1\)  |sort |uniq -c | sort |grep "exists_during" |more |grep GO:0007135
   4 exists_during(GO:0007135)

so the numbers seem to have reduced?

**Comment by kimrutherford** [comment]
I've had a look and I think most of these annotations are in the contig files.  Should I change those too?  
Here's an example from SPAC16A10.05c:
```
FT                   /GO="aspect=C; term=condensed chromosome, pericentric
FT                   region;
FT                   annotation_extension=exists_during(GO:0000278)|exists_during(GO:0051321);
FT                   GOid=GO:0000779; evidence=IDA; db_xref=PMID:17035632;
FT                   date=20070529"
```

Some are from Canto because of this:
  https://sourceforge.net/p/pombase/chado/300/#afcf
Ancient history!
The occurs_during extension relations are changed to exists_during when loading into Chado.  When I was changing the terms in Canto I didn't realise these needed changing too - I only checked for exists_during.

Should I change annotations with
`... [occurs_during] meiotic cell cycle (GO:0051321)`
 to
`... [occurs_during] meiotic cell cycle phase (GO:0098762)`
etc. ?

**Comment by kimrutherford** [comment]
> https://sourceforge.net/p/pombase/chado/300/#afcf

Here's the GitHub copy of that ticket:
https://github.com/pombase/pombase-chado/issues/295#issuecomment-119486687

**Comment by ValWood** [comment]
Yes please!

**Comment by kimrutherford** [comment]
I've fixed the occurs_during extensions in Canto.  I'll check the result tomorrow.

Should I go ahead and change the contig files too?

**Comment by ValWood** [comment]
I only mentioned "exists_during" but this change  also applies to "occurs_during"

 Canto and configs.

Cheers

**Comment by kimrutherford** [comment]
OK, I've fixed the contig files too.

I'll check the load tomorrow to see if there are others to fix.

**Comment by kimrutherford** [comment]
Almost all fixed.  I've just changed:
pombe-embl/external_data/external-go-data/PMID_22146723_gaf.tsv

and I'll check again tomorrow.

**Comment by kimrutherford** [comment]
I think this is really fixed now.
