### ISSUE TITLE
Need sugar beet host

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2143]
In PHI Canto.
How do we add that?

**Comment by jseager7** [comment]
I think we just have to add it to the list of hosts on our config repository and then reload the list in Canto.

Is this the correct entry in UniProt?

https://www.uniprot.org/taxonomy/161934

**Comment by jseager7** [comment]
Obviously I'm presuming that you want to use _Beta vulgaris_ as a host with no genes in a metagenotype.

**Comment by ValWood** [comment]
That is correct (to both)

**Comment by jseager7** [comment]
_Beta vulgaris_ should be available for selection on the main server and the demo server now. Closing.
