### ISSUE TITLE
user reported problem accessing session

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2144]
something
<img width="1047" alt="Screenshot 2019-12-02 at 16 46 44" src="https://user-images.githubusercontent.com/7359272/69977855-6faf0080-1523-11ea-9fcc-b3ccd47b7a77.png">
 is odd here. There are 2 "pause curation" buttons?

**Comment by kimrutherford** [comment]
The session looks OK to me with just one pause button.  Does it look OK to you? https://curation.pombase.org/pombe/curs/e3c1e5b363acdcce

**Comment by ValWood** [comment]
yes closing. I will follow up on the helpdesk. the session looks fine to me...
