### ISSUE TITLE
Canto includes trailing newline when parsing a YAML Folded Block Scalar

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2150]
I noticed that Canto was including an extra space after the broad term suggestions in the ontology workflow:

![image](https://user-images.githubusercontent.com/37659591/70150065-44522000-16a1-11ea-9460-dcea9e91cf44.png)

This is not an error with the template, as that doesn't have any space before the closing bracket:

https://github.com/pombase/canto/blob/fdfb0ce5a9521f0ff957c20884a9eb18a4c29fb7/root/static/ng_templates/ontology_term_select.html#L21

After digging deeper, I found that text was being returned from the `CantoConfig` service with a trailing newline:

![image](https://user-images.githubusercontent.com/37659591/70150460-f2f66080-16a1-11ea-8166-b0c0a265abf6.png)

I think this is due to the YAML config file using the Folded Block Scalar syntax (`>`) for the text:

```yaml
broad_term_suggestions: >
  pathogen, lethal, chemical, growth, motility, reproduction
```

When I switch from Folded Block Scalar back to a plain string:
```yaml
broad_term_suggestions: "pathogen, lethal, chemical, growth, motility, reproduction"
```
Then the newline disappears and Canto doesn't render any extra white space.

(Note that there are no trailing spaces in our `canto_deploy.yaml` for this particular property, so it's not an error with text entry.)

The use of the Folded Block Scalar is not peculiar to PHI-Canto's `canto_deploy.yaml`; it's used throughout the defaults in `canto.yaml`. I'm guessing all the text that's written using Folded Block Scalar is being outputted with a trailing newline.

@kimrutherford I can't find where Canto actually parses the YAML files; do you think you could take a look at this sometime to check what's happening?

**Comment by kimrutherford** [comment]
From what I've read (eg. https://github.com/yaml/YAML2/wiki/Folded-Block-Scalars) it sounds like the trailing newline is expected.

> I'm guessing all the text that's written using Folded Block Scalar is being outputted with a
> trailing newline.

In most cases the newline isn't a problem.  I think the fix is to switch to quoted text as in your example when it makes a visual difference:

```
broad_term_suggestions: "pathogen, lethal, chemical, growth, motility, reproduction"
```

**Comment by jseager7** [comment]
> it sounds like the trailing newline is expected.

I suspected this might be the case, and there's no sense in fighting the standard.

> I think the fix is to switch to quoted text as in your example when it makes a visual difference:

Yeah, that's the simplest fix. I'll update our config. Closing now.
