### ISSUE TITLE
Prevent user from entering session with no pathogen genes

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2153]
In issue #2102 we fixed a bug that was allowing users to bypass strain creation, by either leaving and re-entering the session, or by following links that took them from the confirmation page to the summary page. I've now realised there's a similar bug that lets users start sessions with no pathogen genes (which is currently forbidden by the confirmation page).

@kimrutherford Could we amend the check that keeps users on the confirmation page to also cover the case where the user hasn't added any pathogen genes?

I'm marking this as medium priority instead of high, since the changes in #2152 should mitigate most of the problems from this oversight anyway.

**Comment by kimrutherford** [comment]
Hi @jseager7.

I've had a go at fixing this.  Could you try out this pull request when you get a chance?: https://github.com/pombase/canto/pull/2171

Thanks!

**Comment by jseager7** [comment]
I gave my feedback in the reply in #2171, and that's fixed this issue now. Closing.
