### ISSUE TITLE
Try the latest tagit.js version

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2159]
(from pombase/canto#2158)

We should try the most recent version of tagit.js and use it if possible.

https://github.com/aehlke/tag-it

**Comment by ValWood** [comment]
Is this still current? required?

**Comment by ValWood** [comment]
OK I unassigned Kim for now, but feel free to ping him for input.
v

**Comment by jseager7** [comment]
I'm going to close this because based on discussion at https://github.com/pombase/canto/pull/2386, it looks like the tagit.js package is no longer maintained, so even the latest version has bugs that I just ended up patching myself.
