### ISSUE TITLE
Problem handling special characters in notes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2165]
From @vmt25:

When adding ‘new notes’, the text gets truncated after '\' and ‘?' characters. Is there an issue with using ‘special’ characters?
 The notes stay accurate while within the genotype management page
(adding notes to other alleles, flicking between alleles), but they
get truncated when returning after going to a different page. We would like to store the notes literally, as we will need to use a
few unusual characters. '\' are used in non-Drosophila gene and allele
symbols, to separate the species abbreviation and the gene
name. e.g. the symbol for the Saccharomyces cerevisiae gene cdc2 is
'Scer\cdc2'. We also use '??’ frequently, as temporary markers of
comments, uncertain entitites/alleles, etc. Other special may also be
used, but an’t remember at the top of my head

**Comment by kimrutherford** [comment]
Hi Vitor.  I think I've fixed this.  I've updated the fly-canto site with the change.  Let me know it goes.

**Comment by vmt25** [comment]
Hi Kim.
Yes, it seems to be fixed. Thanks!
(Closing ticket)
