### ISSUE TITLE
Rescue annotations: allele/aberration diploids aren't recognized as 'single locus' genotypes

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2166]
(Related to #2015)

Allele/aberration diploids aren't recognized as 'single locus' genotypes on rescues experiments.

Any single diploid should be considered a single locus genotype (i.e. single allele genotype) and available for rescue annotations.

For example,
w[1]
w[1]/+
w[1]/w[1]
w[1]/w[2]
w[1]/Df(X)123456

are all single locus genotypes of the 'w' gene, and should show up on the drop down genotype menus (either of genotype 1 or genotype 2) of rescue experiments.

**Comment by kimrutherford** [comment]
Hi Vitor.  I think it's doing the right thing in the flybase-test Canto.  For example in this session:
 https://curation.pombase.org/flybase-test/curs/2e523d5ee64ea295

if I select "Pdf[01]" as the first genotype in the Rescue dialog, it shows these genotypes for the second genotype:
 - Pdf[UAS.cSa]
 - Pdf[01] / Pdf[01]                                                                                                                                                                             
 - Pdf[UAS.cSa] Scer\GAL4\[elav.PLu](accessory)

Is that correct?

**Comment by vmt25** [comment]
Hi Kim,

Your example annotations are correct but there are none with aberrations. What is missing is the last example in the ticket:
> w[1]/Df(X)123456


If you check https://curation.pombase.org/flybase-test/curs/d048aaffa62adc7d

a) 'Scer\GAL4[twi.PU](accessory) jeb[UAS.cVa]' can rescue 'jeb[unspecified] / jeb[unspecified]' and vice-versa, because 'Scer\GAL4[twi.PU]' is an accessory allele.

However,
b) the diploid 'jeb[unspecified] / Df(2L)Exel7046(aberration)' should also rescue or be rescued by e.g. Scer\GAL4[twi.PU](accessory) jeb[UAS.cVa]'. This is because, in this case, the aberration 'Df(2L)Exel7046' is considered an allele of 'jeb'.

So, any single locus genotype of the same gene, including diploids with abberrations, should be allowed.

**Comment by kimrutherford** [comment]
Hi Vitor.  Thanks for the explanation.  I should have read the issue more carefully, I was get confused between aberrations and accessory alleles.  I'll fix this today.

**Comment by vmt25** [comment]
Thanks for looking into this.

**Comment by kimrutherford** [comment]
I've fixed the rescue dialog to include genotypes with aberrations and I've updated https://curation.pombase.org/flybase-test

It was a code fix and the configuration doesn't need to change so to update your local copy you'll just need to:
```
(cd canto; git pull)
```

**Comment by kimrutherford** [comment]
Hi Vitor.  Can we close this?

**Comment by vmt25** [comment]
Yes, please. thanks
