### ISSUE TITLE
canto_export.pl: tab-zip type exports empty zip file

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2167]
One of our collaborators on PHI-Canto recently requested an export of Canto's data in a tabular format, to supplement the export we previously provided in JSON format. Unfortunately, when I tried the `tab-zip` option in `canto_export.pl`, all it exported was an empty .zip file.

@kimrutherford Is this export type maintained anymore? Also, does it export the same data as the JSON format, or only a subset of the data? The `TabZip.pm` documentation only mentions "annotations", so I'm not sure.

**Comment by kimrutherford** [comment]
> Unfortunately, when I tried the tab-zip option in canto_export.pl, all it exported was an empty .zip file.

Hi James.  I'm looking at this now.  Did you see any warnings or messages when you ran canto_export.pl?

**Comment by kimrutherford** [comment]
> Is this export type maintained anymore?

PomBase hasn't used it in years.  I've tested it locally and there are several issues.  I'll try to fix them and get back to you.

**Comment by kimrutherford** [comment]
> all it exported was an empty .zip file.

The output isn't empty now and the GO annotations are correctly added to the Zip file.  Interactions and genotype/phenotype annotations will need work.  I had forgotten that the Zip file exporting was only implemented for GO and other simple ontology annotation types (like modifications).

I don't think there's an easy way to support turning genotype/phenotype annotations into a TSV file because the genotype and metagenotype data is too complex.  We should discuss this on the next call.

> One of our collaborators on PHI-Canto recently requested an export of Canto's data in a
> tabular format, to supplement the export we previously provided in JSON format.

Could the collaborator use the JSON files?

**Comment by jseager7** [comment]
@kimrutherford Thanks for working on this.

> I don't think there's an easy way to support turning genotype/phenotype annotations into a TSV file because the genotype and metagenotype data is too complex. We should discuss this on the next call.

I suspected it would be awkward to convert PHI-Canto's other data into tabular form. I'm guessing the main reason having TSV would be useful for our collaborators is a) relative ease of parsing and b) you're guaranteed to see every field that can be exported with TSV, since the columns themselves aren't optional – compare this to the JSON export, which seems to simply omit missing values in some cases. Short of exporting multiple TSV files for the different features in Canto, I'm not sure this is worth the effort.

> Could the collaborator use the JSON files?

Yes they can, although as I discussed above, it might be easier for them to have a comprehensive example of every key the JSON exporter can export. Would it be easy to add a flag to force the JSON to export values for everything (but leave the value as `null` in the case where no data is defined)?

**Comment by ValWood** [comment]
Agreed. We have tabular format for go (GAF) and single gene phenotypes (PHAF)

 However, it is difficult to specify a tabular format for multigene phenotypes.
although there is a proposal here:
https://github.com/pombase/pombase-chado/issues/496

**Comment by kimrutherford** [comment]
> Would it be easy to add a flag to force the JSON to export values for everything (but leave the
> value as null in the case where no data is defined)?

We could do, but could you explain how this helps?  Wouldn't it be better to improve the documentation of the possible fields?: https://github.com/pombase/canto/wiki/JSON-Export-Format

**Comment by jseager7** [comment]
> Wouldn't it be better to improve the documentation of the possible fields?

I agree that would be better, but I assumed that would require more effort than changing the script. I presume the documentation would be as useful to our collaborator as a comprehensive JSON export, providing we can keep it up to date.

**Comment by jseager7** [comment]
I'm going to close this now since the issue itself seems to be fixed (the tab-zip file isn't empty anymore), but feel free to re-open if the exporter still needs more work. From PHI-base's perspective, I think that the JSON format is a better fit for Canto's schema than TSV anyway, so I think a better use of our time is to work on keeping the export schema well-documented.
