### ISSUE TITLE
JSON export doesn't include strain data

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2168]
I've been looking through the JSON export file, and I can't see any data on the strain name that's connected to a genotype. It seems like the strain data has been omitted as an oversight.

@kimrutherford could we add an `organism_strain` property to the genotype objects that are exported? I've named that according to the existing property `organism_taxonid`.

**Comment by kimrutherford** [comment]
> and I can't see any data on the strain name that's connected to a genotype.

Yep, good point.  I've added "organism_strain" to the genotypes in the JSON output.  Could you give it a go and close the issue if it's what you need?

**Comment by jseager7** [comment]
I've tested this locally and it works as expected, thanks. Closing now.
