### ISSUE TITLE
"comma" vs pipe separated modification s

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2169]
https://www.pombase.org/reference/PMID:23462181

I was not able to change this  comma to a pipe.
Do I need to spit into separate annotations?

**Comment by mah11** [comment]
It works if you copy "residue()" each time, e.g.

     residue(T403) | residue(T422) | residue(T823)

(also moved to correct tracker)

**Comment by mah11** [comment]
p.s. I did them all for PMID:23462181 - restarted approval to test it, so figured I might as well finish ;)

**Comment by ValWood** [comment]
Thanks.
I am on the train back from Birmingham. 2 molars extracted ;(

**Comment by kimrutherford** [comment]
Can this be closed?

**Comment by mah11** [comment]
I think so
