### ISSUE TITLE
implement change of label for "expressivity" in PHI-Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2170]
In pombe Canto we changed the label from "expressivity" to severity" as some users were not familiar with the term "expressivity"

Can we implement the same change in PHI-canto?

(phenotype extension)

**Comment by jseager7** [comment]
This is easy to change in the configuration to apply to future annotations, but I'll need some advice from @kimrutherford about changing it for existing annotations.

I've noticed there's a script that seems to handle this ([expressivity_to_severity.pl](https://github.com/pombase/canto/blob/master/etc/expressivity_to_severity.pl)); should it just be a case of running this on the database while Canto is offline (or online)?

**Comment by kimrutherford** [comment]
> I've noticed there's a script that seems to handle this (expressivity_to_severity.pl); should it
> just be a case of running this on the database while Canto is offline (or online)?

I think that's the case.  Let's have a chat about that next time on Skype.

**Comment by jseager7** [comment]
This should be done on the main server now. I've updated the extension configuration and used the `expressivity_to_severity.pl` script to rename existing annotation extensions. Closing now; feel free to re-open if you notice any problems.
