### ISSUE TITLE
Removing all host genes should remove host organism

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2172]
In PHI-Canto, if you add a host organism to the session by adding a host gene, then delete that gene, the confirmation page makes it seem like the host organism has been deleted:

#### Before:

![image](https://user-images.githubusercontent.com/37659591/71815564-c86c3e80-3077-11ea-9c5b-44e364535df5.png)

#### After:

![image](https://user-images.githubusercontent.com/37659591/71815527-a7a3e900-3077-11ea-9d7b-597b71526c2c.png)

But this isn't actually the case: the gene is deleted, but the host organism remains as a host with no genes. Once you return to the page, the host reappears:

![image](https://user-images.githubusercontent.com/37659591/71815640-04070880-3078-11ea-96aa-1c6dfc132beb.png)

This is inconsistent with how the pathogens behave: when you delete all their genes, the pathogen is deleted too, because PHI-Canto's curation rules prevent curation sessions without at least one pathogen gene.

I think we should either:

* **a)** remove the host organism when all of its genes are removed; or

* **b)** ensure that the page doesn't hide the host table when no genes exist, instead switching to showing a host with no genes added (as in the screenshot above).

- - -

Considering option B also made me realise that there's no prompt when deleting an organism (upon deleting the final gene). We might want to re-think this, because deleting an organism also deletes all its strains, including any custom strains that would have to be manually re-entered if an organism were deleted by accident.

So for this other problem, we could either: 

* **c)** warn the user that the organism and its strains will be deleted upon deleting the final gene, and prompt for confirmation; or 

* **d)** change the confirmation page so that deleting all the genes of an organism doesn't delete the organism (regardless of whether it's a pathogen or host), but leaves it as an organism with no genes, after which the delete button will remove the organism instead (though we should probably still prompt in this case for the sake of the strains).

I think option D is only worth doing if the user wants to 'amend' a gene by removing it and adding another one (presuming they added a gene in error). The user would still be able to do this under option C by adding the new gene first and removing the old one afterwards, but that might seem less intuitive.

- - -

See also: a54bd8c6462097bfa255763ec05104380ee95383 (from #1514), for a similar fix about deleting pathogen organisms.

**Comment by ValWood** [comment]
re
> a) remove the host organism when all of its genes are removed; or


I don't . think we can do this because sometimes we have host but ho genes.

**Comment by jseager7** [comment]
> I don't think we can do this because sometimes we have host but ho genes.

In this case you add the host in a different way, using the host organism selector on the gene entry page. For option A I'm only talking about the case where you _have_ added host genes, but then want to remove the gene _and_ the host along with it.

However, by removing the host we assume that the curator has no plans to use the wild-type host by itself, and that raises another problem: what happens when the curator has added an organism that they want to use as wild-type, then adds a gene for that organism, then later removes the gene? It won't be the curator's intention to remove the whole organism in this case. With that in mind, maybe it would be better to prompt the user upon deleting the last remaining gene for an organism; ask them then whether they also want to the organism at the same time.

**Comment by jseager7** [comment]
> what happens when the curator has added an organism that they want to use as wild-type, then adds a gene for that organism, then later removes the gene?

Although I should note that Canto will prevent removing genes or wild-type hosts as soon as any annotations are added, so I guess this problem is only likely to occur when the curator is setting up their session. Maybe that implies that this problem is an edge case.

**Comment by ValWood** [comment]
Ah ok, I misunderstood
