### ISSUE TITLE
Allow un-exporting of sessions

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2177]
Once a session has been exported (with canto_export.pl —export-approved) there is no way to change the state in the web interface.  We should add an action that clears the EXPORTED state, but probably there should be a "do you really want to do this?" confirmation dialog.

**Comment by kimrutherford** [comment]
Hi Vitor.

I've added an "un-export" function:

![un-export-1](https://user-images.githubusercontent.com/90474/72199316-3b721c80-349f-11ea-8022-0c42f1f6130e.png)

that is shown if the session has been exported.

Note that after you "git pull" and before you re-start Canto, you'll need to run these three commands to add some new cvterms to Canto's database:

```
./canto/script/canto_docker ./script/canto_add.pl --cvterm 'Canto cursprop types' session_exported_timestamp
./canto/script/canto_docker ./script/canto_add.pl --cvterm 'Canto cursprop types' session_first_exported_timestamp
./canto/script/canto_docker ./script/canto_add.pl --cvterm 'Canto cursprop types' session_unexported_timestamp
```

**Comment by vmt25** [comment]
Perfect. Thanks.
