### ISSUE TITLE
When a session is in EXPORTED state, the annotation aren't visible

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2178]
If a session has been exported that annotations aren't visible in review / read-only mode.

The "View genotypes" link doesn't work either: "couldn’t read the gene list form the server".

**Comment by kimrutherford** [comment]
Hi Vitor.  This problem should be fixed now if you do a "git pull" and re-start Canto.

@vmt25

**Comment by vmt25** [comment]
Perefct. Thanks
