### ISSUE TITLE
show 'exported' status in publication lists/tables (admin)

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2179]
Would it be possible for publication tables (under admin) to show ‘exported’ as the 'session status' for the sessions that have been exported?

PMIDs with either deleted and exported sessions (I deleted test sessions for a couple of PMIDs) do not show a sessions status, so it is impossible to distinguish between them on the publication pages and one has to go the individual publications to find out.

(very low priority - it would just make it neater)

**Comment by kimrutherford** [comment]
Hi Vitor.  It was a quick change so I've fixed the missing "EXPORTED" statuses.

I've also added a new report ("Exported sessions") at the bottom of the admin page:
https://curation.pombase.org/flybase-test/track

**Comment by vmt25** [comment]
Perfect. Thanks
