### ISSUE TITLE
Change text references to UniProt 'identifier' to 'accession number'

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2180]
PHI-Canto currently uses 'Identifier' as a label for UniProt accession numbers in the user interface. While working on documentation for PHI-Canto, we decided it would be more accurate to refer to these identifiers as 'accession numbers', which seems to be UniProt's preferred terminology for this concept. We thought it would be clearer for users if the interface text matched the documentation.

One problem with this is it looks like the use of 'Identifier' is a global setting in Canto, since it also shows up in the PomBase version, so there would probably need to be special logic in PHI-Canto's case.

@ValWood Do you have any preference about this?

**Comment by ValWood** [comment]
UniProt are inconsistent too. Sometimes they just call it "entry" (at the top of the results table), which says "unique and stable entry identifier" on mouse over. 

Does the name behind the scene in Canto need to match what the user sees?  Or can they be different?

**Comment by jseager7** [comment]
> Does the name behind the scene in Canto need to match what the user sees? Or can they be different?

The name in Canto's database doesn't have to match what the user sees in the browser, and if the server (Perl code) is responsible for setting a name, then the browser can override that too, providing it's able to use AngularJS.

It's certainly possible to rename the 'Identifier' field, it's just more work if the name has to be particular to each organisation's version of Canto (PomBase, FlyBase, PHI-base, etc). The bigger question is whether we want the PHI-Canto documentation (and UniProt's documentation) to dictate how PHI-Canto names its concepts, or whether PHI-Canto's user interface should dictate how we name concepts in PHI-Canto's documentation.

**Comment by ValWood** [comment]
I'll let Kim answer this, but it might be an idea to have 2 methods available. Pombe will need to import UniPRot IDs for complementation experiments. I think that is one of the blockers for getting complementation working.

**Comment by kimrutherford** [comment]
> It's certainly possible to rename the 'Identifier' field, it's just more work if the name has to
> be particular to each organisation's version of Canto (PomBase, FlyBase, PHI-base, etc).

Yep, it would need to be a configuration setting.  With "accession number" for PHI-base, "identifier" for PomBase and possibly "uniquename" for FlyBase.

> but it might be an idea to have 2 methods available.

Which methods do you mean?

**Comment by jseager7** [comment]
> Which methods do you mean?

I think this refers to making Canto support UniProt IDs and PomBase IDs in the same instance of Canto, since Val mentioned that "Pombe will need to import UniProt IDs for complementation experiments".

In that case, we'd probably need an option to specify a display name for the different data adaptors in the config, either in `messages` or bundled up with the `implementation_classes` property.

**Comment by jseager7** [comment]
Note that we already have a similar property in the config, called `systematic_identifier_desc`, under `messages`. For PHI-Canto, it's set to 'UniProt identifier'.

**Comment by ValWood** [comment]
Yes that is what I meant. But I must admit I don't know what I am talking about here. I just remember Kim mentioning that the reason we don't have the "complementation curation" type option yet  for PomBase is that we need a mechanism to use Uniprot IDs to describe the complementing/complemented species genes.

**Comment by kimrutherford** [comment]
OK, thanks.  I had forgotten about that.  It's this issue I think: #1980

If we had pombe IDs and UniProt accession numbers in the same Canto session I think we'd have to call them all identifiers for consistency.

**Comment by ValWood** [comment]
Is there an action here? I think we can close, possibly the best way to illustrate with ID/ACC is required is  with an illustrative text prompt?
