### ISSUE TITLE
Rename the 'Back' button on gene entry page

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2181]
Related: #1624 

When you first start a session and reach the gene entry page, the only navigation button available is a 'Continue' button, which is disabled until you've entered at least one gene ID or specified that the paper has no genes:

<img width="400" src="https://user-images.githubusercontent.com/37659591/72737529-a9050380-3b97-11ea-81d8-c4e1cffa3abf.png">

(Note the image shows PHI-Canto's version of the gene entry page, but I believe it works the same way for all versions.)

Then, when you return to the gene entry page after having entered genes, a second navigation button appears, labelled 'Back':

<img width="400" src="https://user-images.githubusercontent.com/37659591/72737882-59730780-3b98-11ea-8de9-dc0d27f39456.png">

The Back button is always enabled, but the Continue button doesn't enable until the user has entered a gene (or picked a host organism in the case of PHI-Canto).

The problem is that the Back button does almost exactly the same thing as the Continue button: they both navigate to the same page; the only difference is that the Continue button stores your changes, whereas the Back button doesn't. If the Back button truly navigated the user backwards in the workflow, it would take them to the page where they entered their curator details. So, the Back button is redundant from a navigational perspective. I think the page would make more sense if the Back button was replaced with a Cancel button (as shown below), since this matches the intended behaviour of the button.

<img width="400" src="https://user-images.githubusercontent.com/37659591/72738304-31d06f00-3b99-11ea-9758-726160e702e9.png">

**Comment by ValWood** [comment]
This seems to make sense. @kimrutherford ? I can't remember why it is "back"

**Comment by ValWood** [comment]
This seems to make sense.

**Comment by jseager7** [comment]
>> the only difference is that the Back button stores your changes, whereas the Continue button doesn't.

> I think you meant that the other way around?

Yes I did, thanks; I've fixed that typo now.
