### ISSUE TITLE
shortcut to restart approval

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2186]
If you have a lot of edits to do in a list of sessiosn, it is quite cumbersome to access each session.

 From the PubMed search,
you need to go "view session"
"Finish reviewing"
"restart session approval"

Would it be possible to have an additional button   direct to "restart session approval" for admin?

**Comment by ValWood** [comment]
From the admin PubMed link it's even more clicks

**Comment by jseager7** [comment]
I'm guessing this is how it would look on the front page:

![image](https://user-images.githubusercontent.com/37659591/73264725-53e67480-41cb-11ea-836b-27274ecd7289.png)

@kimrutherford I think I might be able to fix this by myself. I'll open a pull request once I've made some progress.

**Comment by kimrutherford** [comment]
> I think I might be able to fix this by myself. I'll open a pull request once I've made some progress.

Cheers!  Let me know if I can help.
