### ISSUE TITLE
Hide 'internal notes' from most genotype tables

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2187]
At present, the internal notes/descriptions associated with alleles are showing up for all alleles on all genotype/annotation tables.

This is not helpful because the comments can be very long, which makes it very hard to read genotypes. Additionally, it may hide the information on the synonym being used on the publication   or the 'accessory' label, which are the most important bits of information. see example:

<img width="1243" alt="Screen Shot 2020-01-23 at 15 26 20" src="https://user-images.githubusercontent.com/33721108/72997837-d00c4100-3df4-11ea-8d41-a05efd153927.png">

So
1) only display the internal notes on the single allele table, under genotype management
2) ideally, the pre-existent notes should show as an 'old note' button, as in a previous implementation - see #2015, posts/commits of 16/10/2019
3) always display the synonyms and the 'accessory' label on all tables

**Comment by gm119** [comment]
I just checked my json import maker code, and it is still set to put the internal notes in the 'description' slot in the json. From our discussion just now, this is the reason they are appearing in the genotype/annotation tables, so I need to fix this bug in the code and instead make it put the internal notes in 'comment'

**Comment by gm119** [comment]
OK, fix is in, so when we generate new json import files the internal (pre-existing) notes should be in right place

**Comment by vmt25** [comment]
I can confirm that the notes show up as intended.
And I am very happy with it!

Closing this ticket.
