### ISSUE TITLE
genotype building - diploids of 'aberration'-type alleles are not being creaed/displayed

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2191]
Aberration homozygotes (e.g. Df(2L)X/Df(2L)X) and heterozygotes (e.g. Df(2l)X/Df(2l)X/[+]) are not being created/displayed

There is a message saying they were created, but they do not appear!
It is possible to try and create the same diploid over and over, which suggests there is no problem of display because otherwise Canto would inform that the genotype already existed

Could you please fix this?

**Comment by kimrutherford** [comment]
Hi Vitor.

I was able to reproduce the bug with aberration + wild type.  I'm testing a fix for the problem now.  It's a bit of a tricky bug to fix so it's taking a little while.

I can't reproduce the problem with aberration homozygotes.  Could you check that?

**Comment by kimrutherford** [comment]
I've fixed the aberration + wild type diploid problem and updated the flycanto-test instance.  Could you check that you are able to create those diploids now?

Gillian, I've had to store the wild type of aberrations in a slightly odd way in Canto because the other wild type know which gene they relate to.  In the JSON output the wild type of an aberration is exported in the allele section like this:

```
 "alleles" : {
    "Df(3R)BSC124[+]-aberration_wild_type:0caa60c8acf089cd-1" : {
       "allele_type" : "aberration wild type",
       "name" : "Df(3R)BSC124[+]",
       "notes" : {},
       "primary_identifier" : "Df(3R)BSC124[+]-aberration_wild_type:0caa60c8acf089cd-1",
       "synonyms" : []
    },
```

and the a diploid genotype with the aberration and the wild type looks like:

```
            "0caa60c8acf089cd-genotype-22" : {
               "loci" : [
                  [
                     {
                        "id" : "FBab0043813"
                     },
                     {
                        "id" : "Df(3R)BSC124[+]-aberration_wild_type:0caa60c8acf089cd-1"
                     }
                  ]
               ],
               "organism_taxonid" : 7227
            },
```
(which isn't surprising)

Will that be OK for parsing at your end?  Let me know if you'll need an extra information.

@gm119

**Comment by gm119** [comment]
Hi Kim, I think that should be fine - I'll use the '-aberration_wild_type' to spot that this is the Df/+ case.

FYI, there are some aberrations that have the string '[+]' at the end of their symbols e.g. FBab0029479 Df(3L)aly[+]   I hope that won't affect your fix (I'm imagining that a diploid heterozygote would come out something like the following, which would still be OK to deal with as it'll have the '-aberration_wild_type' string):


            "0caa60c8acf089cd-genotype-22" : {
               "loci" : [
                  [
                     {
                        "id" : "FBab0029479"
                     },
                     {
                        "id" : "Df(3L)aly[+][+]-aberration_wild_type:0caa60c8acf089cd-1"
                     }
                  ]
               ],
               "organism_taxonid" : 7227
            },

**Comment by kimrutherford** [comment]
> I think that should be fine 

Excellent!

> I'm imagining that a diploid heterozygote would come out something like the following

Yep.  If that's OK for you I'll leave the code as is (unless we find bugs).

**Comment by gm119** [comment]
> Yep. If that's OK for you I'll leave the code as is (unless we find bugs).

yep, that won't be a problem for me, so yep, leave the code as is !

**Comment by vmt25** [comment]
> Hi Vitor.
> 
> I was able to reproduce the bug with aberration + wild type. I'm testing a fix for the problem now. It's a bit of a tricky bug to fix so it's taking a little while.
> 
> I can't reproduce the problem with aberration homozygotes. Could you check that?

Hi Kim,

I am seeing the same behavior as you - I was pretty sure of the problem with the homozygotes, but not anymore.

Thanks,
V

**Comment by kimrutherford** [comment]
Hi Vitor and Gillian.  Close this issue be closed?

**Comment by kimrutherford** [comment]
> ~Close this issue be closed?~

Can this issue be closed?

**Comment by vmt25** [comment]
Seems to be fixe. Closing it

**Comment by gm119** [comment]
OK, I have updated the json output parser so it now copes with 'alleles' of allele_type "aberration wild type"
