### ISSUE TITLE
drop-down menus on multi-allele genotype editing?

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2192]
(not a priority - for discussion)

Currently editing of multi-allele genotypes only allows deleting or 'manually' editing/adding an allele by typing.

<img width="515" alt="Screen Shot 2020-01-23 at 16 19 47" src="https://user-images.githubusercontent.com/33721108/73002709-5a0bd800-3dfc-11ea-9f0f-b28f2591b8eb.png">
<img width="510" alt="Screen Shot 2020-01-23 at 16 20 02" src="https://user-images.githubusercontent.com/33721108/73002746-6a23b780-3dfc-11ea-875b-9bfd24d25b30.png">

Would it be useful to have a drop-down menu displaying all other alleles associated with the publication?

Editing is very useful for cases when  e.g. there are already several annotations but the curator realizes that one allele is incorrect. Also, in FlyBase (almost) all alleles are already associated with the publication and it is not desirable to facilitate creation/typing allele names.

**Comment by kimrutherford** [comment]
If you start typing an allele name it should auto-complete using all alleles in the session.  If you select one the dialog will be filled with the details of that allele.  Does that help?

![allele-complete-1](https://user-images.githubusercontent.com/90474/73624517-f8722600-46a5-11ea-84b3-897808976cb1.png)

**Comment by vmt25** [comment]
Hi Kim,
Yes, that helps a lot.
But it only searches for alleles of the same gene.

Here, I am trying to swap a Sema5 allele by a PlexA allele and nothing shows up.
<img width="1106" alt="Screen Shot 2020-02-03 at 10 05 31" src="https://user-images.githubusercontent.com/33721108/73644260-ec1da700-466c-11ea-9141-49c6d607cb28.png">

**Comment by kimrutherford** [comment]
The only way to do that at the moment is to delete the allele and then click "Add allele ...".  From there can do the autocomplete.

It's not possible to swap the gene in the allele edit dialog.

**Comment by vmt25** [comment]
That is fair enough - So no action needed.
I guess I only tried to swap alleles from different genes and could not see any easy edit option.
