### ISSUE TITLE
Json import file - A curator id is not appropariate when importing multiple publications into Canto

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2194]
(to discuss)

Is there a need to add a curator id during import of publications/associated data into Canto?

For FlyBase's purposes, when importing multiple publications into Canto, each one will have been curator by one (occasionally more) 'thin' curators (thin for genetic things) and will then be curated in Canto by a different 'phen' curator ('phen' for 'phenotype').

Would it be possible to:
a) eliminate the need for a curator id on import? and
b) ideally, create a field on the import JSON where the thin curators ids are specified?

**Comment by kimrutherford** [comment]
> create a field on the import JSON where the thin curators ids are specified?

We could easily move the curator information to the JSON file but currently the Canto database schema supports having a only one curator for a session.

**Comment by vmt25** [comment]
Would it be possible to just eliminate the need for a curator id when importing? Namely by making the <curator email> field optional on:
$ sudo ./canto/script/canto_docker ./script/canto_add.pl --sessions-from-json <json filename> <curator email> <taxon id>

That information is not adequate at all, as the bulk import of publications is a mix of publications curated by different people, not from a single curator.


Please ignore for now the idea of having some curator information in the JSON file.

**Comment by kimrutherford** [comment]
> Would it be possible to just eliminate the need for a curator id when importing? Namely by making the curator_email field optional on:

We could do but we'd need to specify the email address somewhere else, maybe in the config file. Every session has to have a curator with a name and an email address but it doesn't have to be a real name and email address.

So if you don't want to have the name and email of a single person attached to the session we could, for example, use "FlyBase Curator" as the name and "ignore@flybase.org" (or anything else) as the email address.

**Comment by vmt25** [comment]
> So if you don't want to have the name and email of a single person attached to the session we could, for example, use "FlyBase Curator" as the name and "[ignore@flybase.org](mailto:ignore@flybase.org)" (or anything else) as the email address.

yes, please... but low priority
