### ISSUE TITLE
use of pipes instead of commas as the separators for extensions

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2196]
Would it be possible to change the separator for extensions from ',' into '|'?

We are asking for this because '|' are what we (FlyBase) uses as separators both internally and on the website and it would help both a) the conversion from JSON into our flat file/proformae system and b) the comparison/review of Canto vs flat file during the test period.

By the way, there is one early test curation session in which both ',' and '|' are being displayed. I am assuming this is because the same publication was annotated using different versions of canto in different separators were in use. Could you comment on that?

**Comment by ValWood** [comment]
Note that the convention for GO extensions, and one that we have adopted for all other extentions is that "|" and "," have different meanings.

| separated extensions mean that the extensions are  dependent/occur simultaneously (i.e is a single annotation)

, separated indicates independent annotations.

this practice allows you to combine  extensions unambiguously.

Although in practice you only need one extension separator, as you always create independent annotations (for us, this would be a pipe because it implies co-occurrence).

I would imagine this would also likely be a common convention in the Alliance, so it might be worht checking this before making this change.

**Comment by mah11** [comment]
THIS IS BACKWARDS:

> | separated extensions mean that the extensions are dependent/occur simultaneously (i.e is a single annotation)
> 
> , separated indicates independent annotations.

In fact, "|" means independent extensions (Boolean OR), and  "," means a pair of extensions that go together.

**Comment by ValWood** [comment]
Oh yes sorry.

**Comment by ValWood** [comment]
So you are fine using only the comma

**Comment by kimrutherford** [comment]
Hi Vitor.  Could you attach an example of where you are seeing the commas in the JSON output?

**Comment by vmt25** [comment]
> "|" separated indicates independent annotations.
> 
> this practice allows you to combine extensions unambiguously.

OK, yes, that brings it back to memory. Thanks.

By the way, the only way of adding these is on the mode 'Edit as text (Admin only)', right?
(It is easy to see that I haven't been using using that option)

> In fact, "|" means independent extensions (Boolean OR), and "," means a pair of extensions that go together.

Yes, you are right and we know. This was just for display purposes on Canto, to make it easier to cross-check between the Canto display and the flat file/proformae format we are using in the early stages of test/implementation of Fly-Canto.


> Hi Vitor. Could you attach an example of where you are seeing the commas in the JSON output?

I was referring to the annotation tables on Canto, not to the JSON output. Apologies.


Anyways, let us all ignore this issue - It is not worth the trouble, as it would be only for our convenience and it would only be temporary.

**Comment by kimrutherford** [comment]
> By the way, the only way of adding these is on the mode 'Edit as text (Admin only)', right?

You can also use "Add independent extension" if you're logged in:

![add-ind-ext-1](https://user-images.githubusercontent.com/90474/73317334-93c85d00-429a-11ea-83bf-5ea475abb074.png)
