### ISSUE TITLE
rescue experiments - change of rules for allowed genotypes on interactor B

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2200]
Sorry to come back to this and ask for yet another change on the rules for what kind of genotype is allowed.

We request Interactor B to only allow single gene genotypes (single alleles, diploids, etc), but not multiple gene genotypes in which alleles of different genes are 'of the accessory' type.

Not sure I am making this clear, so can chat about it in the VC

**Comment by vmt25** [comment]
By the way, would it be easy to make these rules part of the config file, should we decide to revert them to the current rules?

**Comment by kimrutherford** [comment]
> By the way, would it be easy to make these rules part of the config file, should we decide to
> revert them to the current rules?

Possibly, buy let's chat on Skype about that first.

**Comment by vmt25** [comment]
As discussed at today's VC, let me chat with Gillian about this issue.

**Comment by vmt25** [comment]
Closing this issue - it is too complicated to fix and not a priority
