### ISSUE TITLE
'New note' - make it easier to copy allele symbols into the text box

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2202]
Currently, it is very convoluted to make notes/annotations descriptions on Fly-Canto because the window does not allow direct access and copy of allele symbols from the genotype tables, forcing the curator to a) save the current text, b) go back to the genotype management table to copy a symbol, and c) re-open the notes to add the copied symbol - see on the attached screenshot that the genotype management window is below the note's window and it is greyed-out.

<img width="1367" alt="Screen Shot 2020-01-28 at 11 45 37" src="https://user-images.githubusercontent.com/33721108/73261511-20541c00-41c4-11ea-952f-2aca28666f7f.png">

To make life easier, would it be possible to:

1 - Change the window header, so that it includes the respective allele symbol:
e.g. 'Edit notes for '+<allele symbol>

2- Open the notes on a separate window, so that one can freely flick between the window with the allele tables and notes window, without having to save/close and re-open the notes' window.

3 - other solutions?

P.S.: Making these text descriptions per se is very time consuming, so every little helps.

**Comment by kimrutherford** [comment]
> Change the window header, so that it includes the respective allele symbol:

That's quick.  I'll go ahead and do that.

> Open the notes on a separate window

You should be able to open the same session in a separate window to edit the notes.

**Comment by vmt25** [comment]
Cool.
Petty question: could the 'view/edit notes' button open a new window by default?

**Comment by kimrutherford** [comment]
> could the 'view/edit notes' button open a new window by default?

Unfortunately that's difficult to implement.  I'll have a think about how else we could improve things for you.

**Comment by kimrutherford** [comment]
> Change the window header, so that it includes the respective allele symbol:

That's done now.

**Comment by vmt25** [comment]
> > Change the window header, so that it includes the respective allele symbol:
> 
> That's done now.

Looks great, thanks

**Comment by vmt25** [comment]
> > could the 'view/edit notes' button open a new window by default?
> 
> Unfortunately that's difficult to implement. I'll have a think about how else we could improve things for you.

if the browser does it with a right button click>open in new window, then there is no need for you to bother.

**Comment by kimrutherford** [comment]
> if the browser does it with a right button click>open in new window, then there is no need for you
> to bother.

Unfortunately I don't think that will work either on the "Edit/view notes" link because of the way it's implemented.  I'll have a think about how we can improve this.

**Comment by kimrutherford** [comment]
I've been having a think about this.  If you need to be able to copy and paste we could get rid of the dialog and instead include the editing function in the page.  I don't think that would work for PomBase or PHI-base though because of the gene list at the left.  There isn't enough room.

We'd have to think this through.  For example what should happen if you've edited the notes but you click to go to the summary before you save them?  We don't have that problem with a dialog because you can't click on a link until you finish with the dialog.

Here's a mock-up of what I was thinking:

![inline-notes-edit-1](https://user-images.githubusercontent.com/90474/74134953-4790fb80-4c50-11ea-912c-5075667536a9.png)

**Comment by vmt25** [comment]
Hi,
I really like your suggestion, but I also agree we need to think it through.

**Comment by vmt25** [comment]
This issue has mostly been addressed by #2247, so not worth any work.
