### ISSUE TITLE
Allow copy/transfer of notes from one allele to other/several

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2203]
(related to #1830  and #2202)

As mentioned n #2202, making 'notes', brief phenotype/genetic interaction descriptions per se is very time consuming, so every little helps.

Therefore it would be great to be able to copy them to other alleles:
1 - to individual alleles, as a new action option here:
<img width="302" alt="Screen Shot 2020-01-28 at 12 20 16" src="https://user-images.githubusercontent.com/33721108/73263508-9c506300-41c8-11ea-819f-84865cfcb984.png">

2 - to several alleles, as part of a 'multiple annotations in one go' mode? (as already mentioned in #1830)

**Comment by vmt25** [comment]
note from skype call:
This should allow selection of which kind of description to copy.

**Comment by kimrutherford** [comment]
After the discussion in the March 9th Skype, I've created this issue: #2247

**Comment by vmt25** [comment]
#2247 goes a long way in covering this issue, so I don't this is needed.
