### ISSUE TITLE
greek symbols on notes - convert to SGML on export JSON or proformae

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2205]
Fly-Canto uses Greek symbols whereas FlyBase's Chado uses SGML.

Canto converts SGML 'code' from alleles into Greek symbols during import from JSON and converts them back during export to JSON. However, Greek symbols used in 'notes' are not being converted back to SGML.

We need to discuss whether this conversion should occur a) on the export from Canto into JSON (PomBase/Kim's task) or b) on the conversion from JSON into proformae (FlyBase/Gillian's task).

**Comment by kimrutherford** [comment]
> Canto converts SGML 'code' from alleles into Greek symbols during import from JSON

In the Canto database we store the SGML.  They are displayed as Greek symbols by the rendering code.

> We need to discuss whether this conversion should occur a) on the export from Canto into
> JSON (PomBase/Kim's task) or b) on the conversion from JSON into proformae

Fixing symbols in notes when they are exported wouldn't take too long if that's the best plan.

**Comment by vmt25** [comment]
Cool.

**Comment by vmt25** [comment]
Not appropriate at the moment, but maybe in the future, if we decide to go straight from CAnto to Chado without the current intermediary proforma step, where QC occurs - closing ticket
