### ISSUE TITLE
bug: duplicated annotations from a genotype page

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2208]
Found a bug that makes duplicated entries when making a phenotype annotation from a genotype page - it seems to me that the final/confirmation window appears again after clicking confirm.

**Comment by kimrutherford** [comment]
Could you give me a demonstration of this bug sometime on Skype?

**Comment by vmt25** [comment]
note from Skype call: disable 'Confirm' button before making the actual annotation.

**Comment by kimrutherford** [comment]
> disable 'Confirm' button before making the actual annotation.

That's done now.

**Comment by vmt25** [comment]
I can confirm it is fixed - thanks
