### ISSUE TITLE
json to proforma convertion: when diploids are doing the rescue, GA21 field does not show the word 'with'

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2214]
When diploids are doing the rescue, the converter correctly adds the paired allele between brackets, but it is not prefixed by the word 'with'

e.g. (see real example in attachment)
Canto data:
X[BAC1]/X[BAC2] rescues X[RNAi]

Proforma displays:
GA1a:X[BAC1]
GA21:( X[BAC2]) X[RNAi]

**Comment by vmt25** [comment]
Here is example - see ! GA21. fields of ash1[&Dgr;PHD.Ubi-p63E], ash1[&Dgr;SET.Ubi-p63E] or ash1[Ubi-p63E.FL]
(Record as .txt, because GiHub does not support the .phen extension)
[vt1898.phen.txt](https://github.com/pombase/canto/files/4134858/vt1898.phen.txt)

**Comment by gm119** [comment]
Hi Vitor, do you have the json for this example so I can test my bug fix

**Comment by gm119** [comment]
I think that this is fixed - will be visible in export/support_scripts tomorrow
