### ISSUE TITLE
Enable 'Not assayed' expression level on wild-type alleles

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2215]
Previously, issue #2046 added an 'Unknown' expression level type for use in pathogen-host mode. Later, in issue #2112, this 'Unknown' expression level was also enabled for wild-type alleles in single organism mode.

Now, according to Val, it seems it would have been better to use 'Not assayed' for issue #2112 instead.

'Not assayed' is currently disabled in Canto's code when the allele type is wild-type. The documentation doesn't exactly say why this is the case, but it does mention the fact it's disabled:

> Expression level: You will be prompted to define the expression level relative to wild-type […] If the product level was not measured […] choose "Not assayed" […] If a wild-type allele was investigated in the absence of any other changes, then an altered expression level must be set.

@ValWood can you please confirm the following:

* Do you want 'Not assayed' as an expression option for wild-type alleles?

* Do you want 'Not assayed' enabled on just pathogen-host mode, or single-organism mode, or both?

* If 'Not assayed' is enabled on wild-type alleles, do you want 'Unknown' to be disabled for wild-type alleles so you don't see both options at once?

**Comment by jseager7** [comment]
@kimrutherford Regarding the change that shows the 'Unknown' expression type on wild-type alleles (https://github.com/pombase/canto/commit/a117bce4ee80ef911bf300a78ef6b8069c866c7a), that change only exists on the `pombase-release` branch. The change isn't needed in pathogen-host mode because the 'Unknown' level is shown unconditionally, but the change could be moved to `master` without making the logic in pathogen-host mode inconsistent:

```html
<div ng-show="pathogenHostMode || alleleData.type == 'wild type'">
```

**Comment by ValWood** [comment]
@CuzickA  what do you think
"Not assayed" would seem to be OK instead of unknown?
Do we need to check how we have used, or are you OK with this?

**Comment by kimrutherford** [comment]
> the change could be moved to master without making the logic in either mode inconsistent

Hi James.  Thanks for investigating that.  I've applied the change to master: ca67f185554c3f6423d5e2eeb7bc8846c32565fd

**Comment by CuzickA** [comment]
> @CuzickA what do you think
> "Not assayed" would seem to be OK instead of unknown?
> Do we need to check how we have used, or are you OK with this?

I think I remember why we thought we needed 'unknown'. I believe it should really be 'expression present, level unknown'. In transgenic plants expressing a wild type pathogen protein it may be hard to determine if expression is higher or lower than expression when a wildtype pathogen naturally infects host type. Authors may have measured that the expression was present in the transgenic host so 'not assayed' would be incorrect. 

Not sure if that helps! Perhaps it should be combined with the new delivery mechanisms /trangenic host expression types / conditions under discussion.

**Comment by jseager7** [comment]
We've had more discussion on this, and it looks like we want to disable the 'Unknown' expression type and use 'Not assayed' instead. I'll open a PR for this.

**Comment by jseager7** [comment]
I've checked the curation sessions on the main server, and it seems like there are currently multiple sessions that use the 'Unknown' expression type, so I'm not going to try and disable this expression option yet. Instead, I've opened an issue about these sessions on the curation tracker at https://github.com/PHI-base/curation/issues/70.

**Comment by jseager7** [comment]
@ValWood @CuzickA I've checked our previous discussion on this, but I'm not sure what the final configuration of these expression levels should be. From this issue it sounds like we want to disable 'Unknown' expression everywhere, but that conflicts with PomBase apparently needing 'Unknown' expression for wild-type alleles (see #2112).

Can you just confirm that the following rules are correct? (The differences are highlighted)

### PHI-base
- Wild-type alleles
  - Unknown: **disabled**
  - Not assayed: **enabled**
- Mutant alleles
  - Unknown: disabled
  - Not assayed: enabled

### PomBase
- Wild-type alleles
  - Unknown: **enabled**
  - Not assayed: **disabled**
- Mutant alleles
  - Unknown: disabled
  - Not assayed: enabled

**Comment by CuzickA** [comment]
I didn't know that PomBase used 'unknown' expression?? Sorry don't think I can help on this query.

**Comment by ValWood** [comment]
@mah when we have used "unknown" would "not assayed" be appropriate. I can't think if we use these interchangebly.

**Comment by mah11** [comment]
I was surprised to see "Unknown: enabled" in @jseager7's comment above - I'd thought we switched everything, including wild type, from "unknown" to "not assayed" a while ago. Could wild type simply have been omitted by oversight?

**Comment by jseager7** [comment]
> I'd thought we switched everything, including wild type, from "unknown" to "not assayed" a while ago. Could wild type simply have been omitted by oversight?

I might be getting confused thinking that issue #2112 related to single organism mode, but I've now noticed it also has the PHI-Canto label on it, so I'm not sure if 'Unknown' expression was ever required for PomBase.

As it is, the code that controls allele expression levels has 'Unknown' expression allowed only for wild-type alleles in single and multi-organism mode. For pathogen-host mode, 'Unknown' expression is allowed for _all_ allele types.

If PomBase shouldn't be using 'Unknown' expression level for any allele types, then I can disable it for PomBase when I make these changes for PHI-base.

**Comment by mah11** [comment]
@jseager7 

>  I'm not sure if 'Unknown' expression was ever required for PomBase

A bit of history: PomBase used to require "overexpression" or "knockdown" for wild type, on the assumption that we wouldn't annotate a phenotype in Canto for a wild type allele at the wild type expression level. At the time, we also made "unknown" available for all other allele types. We've since made two changes:

- changed "unknown" to "not assayed"; and
- made more expression options available for wild type alleles (to use in multi-allele genotypes; I can supply more details if you're interested)

I thought we did the "unknown" -> "not assayed" change globally, but it's possible that the two changes weren't entirely in sync. Unless @ValWood knows of any reason to continue using "unknown" for wild type, I would be happy to change it to "not assayed" for PomBase, and consign "unknown" to the proverbial history dustbin.

**Comment by jseager7** [comment]
Thanks for explaining the background to all this.

> I thought we did the "unknown" -> "not assayed" change globally, but it's possible that the two changes weren't entirely in sync.

I think they weren't in sync because PHI-base still hadn't made a decision about whether or not we wanted to use 'Unknown' or not, but it seems we decided to follow suit with using 'Not assayed' in its place, since Alayne has made that switch in all our curation sessions.

> made more expression options available for wild type alleles (to use in multi-allele genotypes; I can supply more details if you're interested)

Does that mean that PomBase has more expression options than PHI-base? As far as I can tell, the configuration for expression is in Canto's source code (rather than in a config file, for some reason). The list of available expression types in the source code are:

- Overexpression
- Wild type product level
- Knockdown
- Null
- Not assayed
- Unknown

Or maybe you meant that you _enabled_ more of these for wild-type alleles? It would be interesting to know if there are more expression options than it seems.

**Comment by mah11** [comment]
Oops, sorry for the vagueness, @jseager7! I do just mean that we enabled more of the available expression options for wild type - it should now offer all except "unknown" (deprecated, or so I thought) and "null" (we only use null for deletions and disruptions).

The reasons for coding expression are probably also historical; I wouldn't object to moving them to a config file but that seems like a tangent from this ticket.

**Comment by ValWood** [comment]
No, I got continues and I could not remember what we did, so go ahead and make the change.

**Comment by jseager7** [comment]
Okay, thanks. I'll get rid of the 'Unknown' expression level in a pull request for this issue.

After all this, the only difference between the two Canto instances with regards to expression level should be that PHI-base will allow 'Not assayed' on wild-type alleles. PomBase will stay the same in excluding 'Not assayed' from wild-type alleles (as it's currently configured in code).

**Comment by jseager7** [comment]
> it should now offer all except "unknown" (deprecated, or so I thought) and "null" (we only use null for deletions and disruptions).

@mah11 I was just testing my changes in single organism mode, and it seems, based on Canto's code and interface, that Null expression shows up for _all_ allele types ('wild type' included), not just the disruption allele type:

![image](https://user-images.githubusercontent.com/37659591/80589319-db819080-8a11-11ea-93a0-ef7eeb46cd90.png)

Is this different for you? Should Null expression actually be restricted to the 'disruption' (and maybe 'unknown') allele type? Deletion allele types don't allow an expression level to be set at all, so that's probably not relevant.

**Comment by mah11** [comment]
@jseager7 I do see the same as you in PomBase Canto. I'm not sure we should, at least for wild type, and IIRC "null" didn't appear for all (non-deletion) types in the past.

>  Should Null expression actually be restricted to the 'disruption' (and maybe 'unknown') allele type?

Maybe - I suppose in theory some of the other types could also be present in the genome, but not expressed, but I doubt that we've encountered an example in fission yeast.

For wild type I would still disallow null. To eliminate expression would require some change, if not in the coding sequence then in some regulatory region (and we would capture that as nucleotide change(s)).

**Comment by jseager7** [comment]
In that case I can look at disabling Null for wild-type alleles too. I'll open a new issue about discussing which other allele types might need Null expression as an option, since this issue will be closed as soon as its pull request gets merged.

@CuzickA I assume you don't have any objections to disallowing 'Null' expression for wild-type alleles?

**Comment by CuzickA** [comment]
> @CuzickA I assume you don't have any objections to disallowing 'Null' expression for wild-type alleles?

@ValWood what do you think about this? 
In the gene-for-gene interactions sometimes a resistance gene is naturally present in one strain of host and absent in another strain. I don't think we have curated any papers like this yet so I'm not sure how we would create these genotypes and whether we would need the null expression option??

**Comment by ValWood** [comment]
I'm not sure how we would do this, but it wouldn't be called null expression. That would be misleading.

**Comment by CuzickA** [comment]
Hi @ValWood  and @jseager7 
I am trying to update the expression level in alleles as discussed in https://github.com/PHI-base/curation/issues/76

There is no option to add 'not assayed' to wild type and the 'unknown' expression option remains. Is this what we intended? I thought we were enabling 'not assayed' and removing 'unknown'. Thanks.
 
![image](https://user-images.githubusercontent.com/11753634/82341376-43f7d800-99e8-11ea-86a2-3960c518015a.png)

**Comment by ValWood** [comment]
I don't remember which option was decided. .....

**Comment by ValWood** [comment]
Ah I was just looking for the ticket. It's this one. It's still open so  I guess it isn't done yet?

**Comment by CuzickA** [comment]
It was closed, I just reopened it for this query

**Comment by jseager7** [comment]
@CuzickA This is because I forgot to update the production server after pushing the changes, sorry. It should be fixed now:

![image](https://user-images.githubusercontent.com/37659591/82424504-32acdb00-9a7d-11ea-96ac-f65d7fb5f3b0.png)

**Comment by CuzickA** [comment]
@jseager7 Yes its working now thanks.
