### ISSUE TITLE
Create a non-test Fly-Canto instance

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2217]
We decided to create a non-test instance of Canto for FlyBase.

This is the config file from Vitor after tweaking for the PomBase server (mostly changing paths and Chado params):  [canto_deploy-flybase.yaml.txt](https://github.com/pombase/canto/files/4153200/canto_deploy-flybase.yaml.txt)

I'll edit this with the other commands I use as I go.

----

```sh
cd /var/pomcur/apps/
git clone https://github.com/pombase/canto.git flybase
cd flybase
perl Makefile.PL
make test       # run this mostly as a double check that the Perl code is OK

# create the data directory and create a minimal canto_deploy.yaml
./script/canto_start --initialise /var/pomcur/data/flybase_data

### add Vitor's configuration to canto_deploy.yaml (see attachment above)
### edit Chado config for the local copy of FlyBase Chado

./script/canto_add.pl --organism "Drosophila melanogaster" 7227 fly

./script/canto_load.pl --process-extension-config  --ontology /data/pombase/flybase/ontology_files/FBbt-GO_I.obo  --ontology /data/pombase/flybase/ontology_files/fly_development.obo  --ontology /data/pombase/flybase/ontology_files/flybase_controlled_vocabulary.obo --ontology https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/so-simple.obo --ontology /var/pomcur/sources/pombe-embl/mini-ontologies/has_qualifier_range.obo 2>&1 | tee load-ontology.log

# actual passwords sent by email
./script/canto_add.pl --person 'Admin Person' flybase-admin@pombase.org PASSWORD '' admin
./script/canto_add.pl --person 'Vitor Trovisco-Gradissimo' _____@cam.ac.uk PASSWORD '' admin

/script/canto_add.pl --sessions-from-json /data/pombase/flybase/FBrfs_for_new_canto_import-2020-02-04.json vmt25@cam.ac.uk 7227 2>&1 | tee load-publications.log
```

**Comment by vmt25** [comment]
I managed to log in and start annotating, but the anatomy ontology does not seem to load properly - see the permanent spinning wheel in the attached image.

<img width="1024" alt="Screen Shot 2020-02-05 at 14 36 04" src="https://user-images.githubusercontent.com/33721108/73851674-ce477200-4825-11ea-8f4a-4ad0868bba5b.png">


Perhaps you could try loading the alternative ontology files?

Sorry for this hiccup.

**Comment by vmt25** [comment]
Just checked my canto_deploy.yaml, and realised that the configuration for the top namespace of the 'anatomy' and 'anatomy_interaction' annotations is for an old ontology - 'fly_anatomy.ontology' - and should be 'FlyBase_anatomy_CV' instead.

e.g. 
- name: anatomy
    category: ontology
    namespace: FlyBase_anatomy_CV

- name: anatomy_interaction
    category: interaction
    namespace: FlyBase_anatomy_CV

Does this help?

**Comment by vmt25** [comment]
Quick update: changing the namespace and reloading the ontologies fixed the issue with the anatomy annotations on my local fly-canto. 

Sorry for this stupid mistake.

**Comment by kimrutherford** [comment]
> and should be 'FlyBase_anatomy_CV' instead.

Thanks!  I've made that change on the server too.

**Comment by kimrutherford** [comment]
Is there anything else we need to do for the new Fly-Canto server?  Perhaps we should close this issue and open new issues for problems.

**Comment by vmt25** [comment]
Thanks.
Yes, it can be closed.
