### ISSUE TITLE
strain already configured in a new session (minor bug)

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2219]
strain already configured in a new session.

I just started PMID:20624958

added D7PDA1

The strain amaretto was already configured. I changed to to "bobwhite" but it's a bit confusing to have in a new session. It might be because this gene has been encountered in a different sess.

**Comment by jseager7** [comment]
Strange. I'll see if I can reproduce this locally.

**Comment by jseager7** [comment]
I can't reproduce this bug following the instructions above: _Triticum aestivum_ is always created without any strains on it. It doesn't seem to make a difference whether or not the gene already exists in some other session: I already tried creating an allele of Tsn1 in another session.

The only reason I can think this would normally happen is if a host had been added without any genes and then had a strain added to that, meaning you were adding the gene onto an existing host. But, you said in your original comment that this was a new session, so there's no way a host could've already been there (unless the session actually wasn't new).

@ValWood I'm marking this as 'cannot reproduce'; you can close the issue if you think it's not worth keeping open.

**Comment by ValWood** [comment]
will reopen if it re occurs
