### ISSUE TITLE
Improve display of metagenotype description

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2220]
From #2193

On the Metagenotype details page, we could break the Description section up to describe the constituent parts of the metagenotype, rather than simply repeating the display name:

![image](https://user-images.githubusercontent.com/37659591/73857036-3a2dd880-482e-11ea-86ca-312e8f80161a.png)

This has the advantage that we can link to the genotype pages for the constituent genotypes, and italicise the species names.

**Comment by ValWood** [comment]
much easier fur human parsing
