### ISSUE TITLE
Add version number to JSON export

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2223]
It might be easier to evolve the JSON export and the JSON schema in future if we have some sort of versioning in place to insulate consumers from schema changes. One thing @kimrutherford suggested was to add a version number.

@kimrutherford could you clarify if this means adding a version number to the JSON schema, the JSON export, or both? Thanks.

**Comment by kimrutherford** [comment]
I've added `"schema_version" : 1` to the output.
