### ISSUE TITLE
change to curation graph

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2226]
https://curation.pombase.org/pombe/stats/annotation
Curated vs. uncurated by publication date

please add
i) pale red assigned to community curator 
ii) pale yellow assigned to PomBase curator

thanks!

**Comment by kimrutherford** [comment]
How's this?:

![new-curated-uncurated-canto-graph-1](https://user-images.githubusercontent.com/90474/74287468-e6bc0d00-4d8e-11ea-86fb-5327174515ae.png)

**Comment by ValWood** [comment]
Oh that's great!

Could the "unassigned" go at the top  of the bars?

@Antonialock 
Where should we "bin" the earlier papers currently <1970
<1985?

**Comment by kimrutherford** [comment]
![new-curated-uncurated-canto-graph-2](https://user-images.githubusercontent.com/90474/74294312-525ba580-4da2-11ea-83aa-4ff70880e501.png)

**Comment by kimrutherford** [comment]
That's live now.  I had swap the colours around a bit to make things look OK.  Would you like me to update the community curation image on the front page?

**Comment by ValWood** [comment]
Yes please, that looks great!

**Comment by ValWood** [comment]
@Antonialock  said:
maybe tweak labels

"
uncurated, community assigned
uncurated, curator assigned
uncurated, unassigned

I would also do these in three as shades of the same colors to show that they are related "uncurated"

**Comment by ValWood** [comment]
I think the labels do need to be clearer.

I prefer the contrasting colours (because they are easier to see where the blocks are very small) and the grey for unassigned.

However, it would be better if we could see more clearly curated vs uncuratated.

- [ ] How about
dark green curator curated, light green curator uncurated
dark  blue community curated, pale  blue community uncurated
pale grey unassigned 

 - [ ] Maybe  it  would be better without the thick lines around the colour bars?

- [ ] is it possible to make the key larger and superimpose onto the blank white space in the graph

**Comment by ValWood** [comment]
- [ ] bin all <1980 into a single bin?

**Comment by kimrutherford** [comment]
I can change the colours but there are only limited other changes are possible.  The graphing library that's used by the Canto code isn't very flexible.  I'd like to re-implement the stats page on the main site at some point to add more information and to improve the look of the graphs.

> I would also do these in three as shades of the same colors to show that they are related "uncurated"

I'll try that.

**Comment by kimrutherford** [comment]
> maybe tweak labels

> dark green curator curated, light green curator uncurated
> dark blue community curated, pale blue community uncurated
> pale grey unassigned

> bin all <1980 into a single bin?

Here's what that looks like:

![new-curated-uncurated-canto-graph-3](https://user-images.githubusercontent.com/90474/74388049-34a04600-4e5f-11ea-8bb3-c9913a690818.png)

**Comment by ValWood** [comment]
OK, what do people think of the colours?
I think I preferred the one with 4 contrasting colours ;)

How can we improve the key for the paper?
Note- we are inconsistent  Admin vs curator?

**Comment by kimrutherford** [comment]
> Note- we are inconsistent Admin vs curator?

Yep.  I think we should change "uncurated, curator assigned" to "uncurated, admin assigned".

**Comment by Antonialock** [comment]
yes I preferred the contrasting colours too - the shades are too hard to see.

I don't think the key needs improving, just the test (caption in paper) to clarify that uncurated = not yet curated
community assigned = sent to community for community curation
admin assigned = in progress by admin

**Comment by kimrutherford** [comment]
So back to something like this?:

![new-curated-uncurated-canto-graph-4](https://user-images.githubusercontent.com/90474/74511059-f2aff680-4f69-11ea-9984-1cc780532caf.png)

**Comment by ValWood** [comment]
preferences?
@ValWood 
@Antonialock 
@mah11

**Comment by mah11** [comment]
no preference; I am not the target audience

**Comment by kimrutherford** [comment]
I'm going to close this since they are no objections to how it looks now.

We can open new issues for tweaks.
