### ISSUE TITLE
propagation of "unknown" -> to "known" to include  multi-gene genotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2227]
Yesterday I updated  the allele  description for  cdc13 in this session 
curs/dd0b314b0bd84119
which was labelled as "unknown" (M-7)
(I'm not sure how it was already in Canto, as it isn't on the cdc13 gene page so it has not previously been used in curation)

Anyway it did not propagate to the multi allele genotype

I know that other allele changes do not propagate, but I thought curs/dd0b314b0bd84119

<img width="842" alt="Screenshot 2020-02-11 at 15 31 39" src="https://user-images.githubusercontent.com/7359272/74356248-eedb7300-4db5-11ea-9dfd-887d8409708b.png">
 that  unknown-> known did?

**Comment by mah11** [comment]
I can answer this part:

> (I'm not sure how it was already in Canto, as it isn't on the cdc13 gene page so it has not previously been used in curation)

It was known to Canto in that session, but not anywhere else (it doesn't come up in the autocomplete for cdc13 in any other session).

Come to think of it, maybe that's the answer overall: the "unknown" will automagically update after the session is approved, the data loaded into Chado, etc. @kimrutherford can say if that's right or I'm dreaming ...

**Comment by ValWood** [comment]
Ah OK, Yoshi added it but he didn't put the amino acid change that was in the paper. 
SO this should get transferred when I approve the session. That's good. I will double check though.

**Comment by ValWood** [comment]
this works
