### ISSUE TITLE
Add strain synonyms to Track schema

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2231]
Related: #1718

Now that the PHI-base strain list has been checked and cleaned up, I think we should start thinking about how to add strain synonyms to Canto's `track` schema.

@kimrutherford I think we need a new table, `strainsynonym`, that serves a similar purpose to the `genesynonym` table: a one-to-many mapping between a strain name and its synonyms. For example:

strain_id | organism_id | strain_name
-- | -- | --
191 | 9606 | Caco-2BBE cell line

synonym_id | strain_id | strain_name
-- | -- | --
13 | 191 | C2BBE1
14 | 191 | C2BBe 1
15 | 191 | Caco-2/BBe 1
16 | 191 | Caco-2/BBe
17 | 191 | Caco-2BBe
18 | 191 | Caco-2 BBe
19 | 191 | Caco2-BBE
20 | 191 | Caco2BBe
21 | 191 | BBE

For now the table will probably be empty, but it will be populated once we import the updated strain list.

**Comment by jseager7** [comment]
You might want to bundle this schema change with #2232, providing we can make a decision about that quickly enough.

**Comment by jseager7** [comment]
Also, I first have to export our existing strains from PHI-Canto, so I can ensure that any existing strains (from the old list) get renamed to match the new strain list – that way, we won't have to delete the existing strains and re-add them. So, we can afford to defer the schema changes until that's done.

**Comment by kimrutherford** [comment]
Hi James.

> I think we need a new table, strainsynonym

Yep, I think that makes sense.

> You might want to bundle this schema change with #2232

That makes sense too.

I'll have a go at this on a branch and make a PR.

I've also made an issue about the file format: #2235
