### ISSUE TITLE
Add strain abbreviation column to Track schema

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2232]
Related: #2110 

@kimrutherford In order to display abbreviated strain names, I think we'll need a new column in the `track` schema, in the `strain` table, that stores an abbreviated name for the strain. For example:

strain_id | organism_id | strain_name | abbreviation
-- | -- | -- | --
770 | 4565 | cv. Chinese Spring | CS

This abbreviation is supposed to be like a 'default' short name for display purposes in feature tables (as described in #2110). However, there's a problem that sometimes this short name may overlap with an existing synonym.

If we're not keen on enforcing defaults, another option is to shift this stuff to the `curs` schema, and let curators pick a display name from the list of synonyms instead, meaning abbreviations will be stored on a per-session basis. Then, we can define abbreviations as extra synonyms without needing to add another column.

This is lower priority than adding strain synonyms, so I think we should wait until we're sure about how abbreviations should be stored before committing to anything.

**Comment by kimrutherford** [comment]
@jseager7 

When a curator adds a new strain to the session (ie. one we don't have already), will they need to be able to add an abbreviation and synonyms?

**Comment by jseager7** [comment]
> When a curator adds a new strain to the session (ie. one we don't have already), will they need to be able to add an abbreviation and synonyms?

This might be too much work to force onto community curators – they probably won't have any need to specify synonyms because they'll surely choose their preferred name when adding a new strain. Admin curators should just edit the master strain list and add the abbreviations and synonyms there.

Allowing community curators to add abbreviations might be more useful, but only to prevent them adding the abbreviation as the preferred name rather than the expanded name, in cases where the name is too long (though we should really discourage this).

Overall, I don't think it's worth worrying about this at the moment. In the case of a truly novel strain there probably won't be any widely-used abbreviations or synonyms anyway.

**Comment by jseager7** [comment]
It would probably be more useful to have an admin-only feature that allows admin curators to actually update the `track` strain table with new strains, synonyms, and abbreviations; but again, that's not essential.

**Comment by kimrutherford** [comment]
After discussion we've decided that we don't need a strain abbreviation column.  It's not easy to pick an abbreviation that will be obvious to all users so it's best that we don't try.
