### ISSUE TITLE
Encoding errors in PHI-Canto strain list

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2233]
I've noticed that some of the strains that we've loaded into Canto haven't got the correct encoding.

Examples include the _Gallus gallus_ breed White Leghorn changing from 'weiße Leghorn' to 'weiÃe Leghorn', and the delta symbol getting mangled, such as 'G217B ura5Δ' changing to 'G217B ura5Î'.

I checked the database itself and it looks like these encoding errors are in there too:

![image](https://user-images.githubusercontent.com/37659591/74834336-22b51c00-5313-11ea-8ff5-2125eb4758ba.png)

Some of these examples will get cleaned up because the names will be localised to English, but that won't cover all cases.

@kimrutherford I'm keen to avoid this happening again when I update the strain list. Do you have any idea what might have caused the encoding problems, or how we can prevent it happening?

**Comment by kimrutherford** [comment]
Could you attach the input file that is causing this or let me know where an example is?  I'll do some local testing.

**Comment by jseager7** [comment]
The input files are on our (private) config repository. See here:

https://github.com/PHI-base/config/blob/master/data/

You'll want to download both strain files. You can see an example of a strain that has this encoding issue here:

https://github.com/PHI-base/config/blob/master/data/host_strains.csv#L677

**Comment by kimrutherford** [comment]
I've just tried this locally and the characters made it through to the database.  Maybe this fix solved two problems?: https://github.com/pombase/canto/pull/2238#issuecomment-614035587

Could you test again when you get a chance?

**Comment by jseager7** [comment]
I've tested the changes, and while 'weiße Leghorn' is a synonym now (so I can't see it in the interface), there are other examples of UTF-8 characters that are working correctly (see below).

![image](https://user-images.githubusercontent.com/37659591/79458782-3961b180-7fea-11ea-8fea-9baf0f677178.png)

I'll see if I can mark PR #2238 as fixing this issue.

**Comment by jseager7** [comment]
> I'll see if I can mark PR 2238 as fixing this issue.

Turns out I can't do that without editing the original comment of the PR, so I'll just remember to close this after it's merged.

**Comment by kimrutherford** [comment]
Can this be closed now?
