### ISSUE TITLE
Admin page: Download/export session buttons not working

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2239]
Hi Kim, 

Tried downloading/exporting the approved sessions using the links under Tools:
- Download all session data as Zip
- Download approved sessions data as Zip
- Export approved sessions as Zip file (marks the sessions as exported)
- Download all exported sessions data as Zip 

From the online Fly-Canto instance, none work, always showing an error page with:
"File not found
An error occurred during a connection to curation.pombase.org.
    Check the file name for capitalization or other typing errors.
    Check to see if the file was moved, renamed or deleted."

From my local copy, it takes a long while for a menu to pop-up and the data dump is split into different files, by annotation type. I was expecting a json file similar to the one produced when using --dump-approved or --export-approved.
By the way, --dump-approved or --export-approved are working fine for my local instance works fine, but I cannot use it with the online fly-canto.

By the way, I am not in any rush to download the sessions - just wanted to test it and now I just want to let you know of the issue.

**Comment by kimrutherford** [comment]
Hi Vitor.

Those links might not be useful for you.  When they work you get a Zip file of annotations in tab delimited format.  They links were an experiment and we don't use them at PomBase.

The links work on flybase-test.  Here's what I got: https://send.firefox.com/download/dffe5844b3517b46/#1yvooBkb_-lCqbphCg_QgA

I'll fix the links on the flybase instance.

**Comment by kimrutherford** [comment]
> I'll fix the links on the flybase instance.

I've fixed the links.  Canto was tripping over a couple of broken sessions due to this bug: #2240

**Comment by vmt25** [comment]
Not relevant, so closing
