### ISSUE TITLE
Fix the demo server

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2241]
It doesn't work at the moment.  I've had a quick look and can't work out what the problem is.
eg. https://curation.pombase.org/demo/curs/7e870ceac252916e/feature/gene/annotate/4/start/molecular_function

I'll update to the latest version of Canto first to see if that helps.

**Comment by kimrutherford** [comment]
I've fixed the demo server by completely refreshing it.  I've cleaned out old sessions and updated to the latest code.

**Comment by ValWood** [comment]
Thanks!
