### ISSUE TITLE
Allow transfer of interaction annotation to multiple features

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2244]
See: https://github.com/pombase/canto/issues/1830#issuecomment-590839270

**Comment by kimrutherford** [comment]
After discussion we decided to add this transfer feature for phenotype_interaction first as it's the simple case.  I hope I'm remembering that correctly.

I've started work on this (e9ca0fde6, #2245).  So far it only allows transferring the annotation to genotype A of an interaction (it was the easy case).  I've just added that change to the flybase-test Canto.

@vmt25
@gm119

**Comment by vmt25** [comment]
> phenotype_interaction first as it's the simple case. I hope I'm remembering that correctly.

Yes. This should be the easiest to implement because there are no rules on which genotypes can go with which.

**Comment by vmt25** [comment]
> I've started work on this ([e9ca0fd](https://github.com/pombase/canto/commit/e9ca0fde61b9e657464610840a97209cf162285d), #2245). So far it only allows transferring the annotation to genotype A of an interaction (it was the easy case). I've just added that change to the flybase-test Canto.
> 

Works great!

**Comment by vmt25** [comment]
From today's VC with Kim and Gillian:

A partial implementation that allows transferring to other Interactor A genotypes while keeping the interactor B is working fine on https://curation.pombase.org/flybase-test/  (as in #2245) and would already provide some added value, so it would be good if pushed into production in Fly-Canto after a couple of changes.

<img width="833" alt="Screen Shot 2020-05-05 at 15 30 48" src="https://user-images.githubusercontent.com/33721108/81077898-78966a80-8ee5-11ea-948c-3832d8ea2f32.png">

a) change the title of the menu page to a more generic 'Transfer genetic interaction annotation'

b) show the annotation to transfer (with the title 'interaction annotation to transfer')
<img width="639" alt="Screen Shot 2020-05-05 at 15 32 47" src="https://user-images.githubusercontent.com/33721108/81078163-c4491400-8ee5-11ea-90e0-21d9b8cbd905.png">

c) then list the possible interactor A genotypes where to transfer (as is, but eliminating the genotype of the original annotation)

**Comment by vmt25** [comment]
(For future implementation)
A more common/useful case would be to transfer an interaction annotation, where interactor B ois the the genotype to be changed.

For this, the menu/pipeline will need to select which genotype to change (interactor A or B) and, depending on the selection, list the  possible genotypes (excluding the corresponding genotype on the original annotation)

**Comment by jseager7** [comment]
@kimrutherford In case you don't already know, the Transfer feature isn't disabled when you only have one feature in the session; you get an empty dialog box in this case:

![image](https://user-images.githubusercontent.com/37659591/82305438-86ec8800-99b5-11ea-8095-a5e7240b7ae4.png)

**Comment by kimrutherford** [comment]
Thanks James.  I had forgotten about that.  It's on the to-do list but I had forgotten there was a to-do list.  :-)

https://github.com/pombase/canto/issues/1830#issuecomment-587362776

**Comment by jseager7** [comment]
@kimrutherford Not sure which issue this belongs in, but I've noticed a bug with `annotation_transfer.html`.

The `annotation_transfer.html` template uses the `multi-feature-chooser` directive, which has a `featureType` binding of string type (`@`), but the template code treats the binding like a variable-type (`=` or `<`), since it passes the name of a scope variable `featureType` as a raw string instead of as an interpolation:

```html
      <multi-feature-chooser ng-if="!!otherFeatures" 
                             features="otherFeatures" feature-type="featureType"
                             selected-feature-ids="selectedFeatureIds">
      </multi-feature-chooser>
```
This fixes the value of `featureType` to `"featureType"`, instead of the actual type of the feature, so the following conditional markup in `multi_feature_chooser.html` never shows:
```html
  <div ng-if="featureType == 'gene'" class="clearall">
    <a ng-click="openSingleGeneAddDialog()">Add another gene</a>
  </div>
```
Using interpolation is all that's required to fix this:
```
feature-type="{{featureType}}"
```

**Comment by kimrutherford** [comment]
> Using interpolation is all that's required to fix this:

Thanks James.

I made that fix then found that the "Add another gene" wasn't working.  I've fixed that now but it required a slight code shuffle.  I'm not sure the "Add another gene" link is that useful for Multi-organism/UniProt ID mode.  We can hide it if it's not useful.

**Comment by jseager7** [comment]
> I'm not sure the "Add another gene" link is that useful for Multi-organism/UniProt ID mode. We can hide it if it's not useful.

It's maybe not as user-friendly as PomBase, because you can't just enter gene names, and you can't restrict the gene being added to the selected organism. The latter reason is why we replaced the shortcut with a link back to the gene entry page in pathogen-host mode: if you used the shortcut to add a gene for an organism other than the one that was selected, you didn't get any visual feedback that anything had happened.

Some of the above problems don't apply for transferring annotations, since you see all of the available features from all organisms (so you'd always see the gene that gets added). I think having the option to add a gene before transferring annotations is useful for the case where you want to copy the annotation, but forgot to add the gene in the first place.

All of this assumes the shortcut can actually work for UniProt IDs.

**Comment by kimrutherford** [comment]
I've had a first try at allowing annotation transfer for interactor A or B.  I haven't yet implemented the suggestions in https://github.com/pombase/canto/issues/2244#issuecomment-624111797 but I've updated the main fly-canto instance with the changes so you can start testing.

What should the text be instead of "Choose interactor"?  I couldn't think of a good way to describe things.

![transfer-interactions-1](https://user-images.githubusercontent.com/90474/85530606-2ca0b000-b662-11ea-95d3-3cc77c0bbb14.png)

**Comment by kimrutherford** [comment]
> a) change the title of the menu page to a more generic 'Transfer genetic interaction annotation'
> b) show the annotation to transfer (with the title 'interaction annotation to transfer')

It now looks like this:
![transfer-interactions-2](https://user-images.githubusercontent.com/90474/85546374-f159ad80-b670-11ea-893e-f1f04f981992.png)

Is that close to what you were thinking of?

This change is in the main fly-canto and the test fly-canto.

**Comment by vmt25** [comment]
Hi. The full transfer is working fine.
Yes, that is what I we were thinking of, but could both a) and b) show on the previous menu instead, where the user can pick the interactor?
i.e. here:
![image](https://user-images.githubusercontent.com/33721108/85577882-889f1080-b631-11ea-9f7e-7ddf51c998a8.png)

**Comment by kimrutherford** [comment]
How's this?:

![transfer-interactions-3](https://user-images.githubusercontent.com/90474/85647363-7042fa80-b6f2-11ea-8d64-68e72ba8da89.png)

That change is in Fly-Canto now.

**Comment by vmt25** [comment]
Hmmm, I don't see it... Tried Fly-Canto, both main and test

It should be the initial menu window, correct?

On the main Fly-canto I only see this on the first menu:

<img width="843" alt="Screenshot 2020-07-08 at 20 41 04" src="https://user-images.githubusercontent.com/33721108/86962862-76f25880-c15b-11ea-931f-d39a5d43ebc2.png">

And this on the second menu:

<img width="839" alt="Screenshot 2020-07-08 at 20 43 10" src="https://user-images.githubusercontent.com/33721108/86962985-aacd7e00-c15b-11ea-9043-8dfe4f889104.png">

**Comment by vmt25** [comment]
> How's this?:

Forgot to say that, yes, that is exactly it!

**Comment by kimrutherford** [comment]
> Hmmm, I don't see it... Tried Fly-Canto, both main and test

Sorry, I hadn't updated fly-canto with the change.  Could you try again?

**Comment by vmt25** [comment]
Looks good now, Thanks!

Maybe add a header ('Interactor A' or 'Interactor B', depending on the selection) to the genotype's list on the second menu?
This would provide a check for when the wrong interactor has been selected by mistake

**Comment by vmt25** [comment]
Just noticed that the lists of genotypes from where to select new interactors include the initial genotype; see screenshot below.
This allows for unintentional duplicated annotations - I just made one annotation but luckily noticed it.


Please notice that the list of genotype for possible interactors A includes  'FIG4[KK102943] Scer\GAL4[GMR.PU](accessory)', which is the interactor A on the starting annotation; the list for interactor B shows the same behavior.

<img width="730" alt="Screenshot 2020-07-13 at 12 37 14" src="https://user-images.githubusercontent.com/33721108/87300798-71539480-c506-11ea-8c13-516776994312.png">

**Comment by kimrutherford** [comment]
> Just noticed that the lists of genotypes from where to select new interactors include the initial genotype;

Hi Vitor.  I think I've fixed that.  Please let me know if it's still a problem.

> Maybe add a header ('Interactor A' or 'Interactor B', depending on the selection) to the genotype's list on the second menu?

That makes sense.  I'll do that next.

**Comment by vmt25** [comment]
> > Just noticed that the lists of genotypes from where to select new interactors include the initial genotype;
> 
> Hi Vitor. I think I've fixed that. Please let me know if it's still a problem.

Hi Kim,
At a first glance it seems to be fixed. Thanks.

**Comment by kimrutherford** [comment]
> Maybe add a header ('Interactor A' or 'Interactor B', depending on the selection) to the genotype's list on the second menu?

I've added that now.  It looks like this:
![interaction-header-1](https://user-images.githubusercontent.com/90474/88503621-629ccf80-d026-11ea-8466-aea9202c8ad1.png)

Let me know if you'd like it worded differently.  I don't think it's very clear at the moment.

**Comment by vmt25** [comment]
Looks good! (Will check on my next curation opportunity)

Would it be possible to have the 'Interactor A'/'Interactor B' in bold and start with a capital 'I'?

Thanks

**Comment by kimrutherford** [comment]
> Would it be possible to have the 'Interactor A'/'Interactor B' in bold and start with a capital 'I'?

Like this?:

![interaction-header-2](https://user-images.githubusercontent.com/90474/88589140-c964cc00-d0ac-11ea-927f-29dbaaa7f351.png)

**Comment by vmt25** [comment]
Yes!!

**Comment by kimrutherford** [comment]
Great.  That change is available in fly-canto now.

**Comment by vmt25** [comment]
I think this is done - closing
