### ISSUE TITLE
Increase the size of the text entry boxes in the notes view/edit dialog

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2246]
I'll increase the height and width, then @vmt25 can test how it looks on his (big) screen.

**Comment by vmt25** [comment]
You also mentioned a browser extension that adds a small icon on corner of the text boxes that transfers the text to/fro a text editor - that sounded very useful!

**Comment by kimrutherford** [comment]
> You also mentioned a browser extension that adds a small icon on corner of the text boxes
> that transfers the text to/fro a text editor - that sounded very useful!

Unfortunately the FireFox extension I used in the past doesn't work anymore: https://github.com/docwhat/itsalltext

I've made the text boxes a little bit taller and wider so the notes editing dialog box is bigger now.  Could you check that it still fits on your screen?  :-)

**Comment by vmt25** [comment]
Hi Kim,

Sorry for only replying now.
Now the menu box is wider, but the text boxes do not seem much bigger - checked in Safari and Firefox; please see screenshot

![Screenshot 2020-06-10 at 11 40 41](https://user-images.githubusercontent.com/33721108/84377020-ebc48800-abd9-11ea-8bfc-e20c943e7280.png)

**Comment by kimrutherford** [comment]
Because of the changes in #2247 the right hand column of the dialog now contains the view-only notes from other alleles.  There is an "X" to hide that section if full width edit fields are needed.

**Comment by vmt25** [comment]
Nice!
The X does not show properly on Firefox (some greyed icon) or Safari (question mark icon), but it works!

Thanks,
Vitor

**Comment by kimrutherford** [comment]
> The X does not show properly on Firefox (some greyed icon) 

Hi Vitor.  When you get time, could you send or attach a screenshot of what the greyed icon looks like for you?

**Comment by vmt25** [comment]
Here it is

<img width="843" alt="Screenshot 2020-06-19 at 10 36 10" src="https://user-images.githubusercontent.com/33721108/85119263-6401fd80-b219-11ea-9589-c59575acefc2.png">

**Comment by kimrutherford** [comment]
Thanks!  I had made a typo and linked to the X image on my desktop.  So it was working for me but no one else.  It took me a few minutes to work out what I'd done wrong.

It should be OK now.

**Comment by vmt25** [comment]
I can confirm it is fixed.

**Comment by vmt25** [comment]
Done!
