### ISSUE TITLE
Add a "view" pane on the notes view/edit dialog

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2247]
This is so the curator can view the notes for one allele/genotype while editing the notes for another.  This hopefully will make copy and paste easier.

**Comment by vmt25** [comment]
The "view" pane must be strictly read-only

**Comment by kimrutherford** [comment]
Hi Vitor.  I've made a first attempt at this functionality.  Currently it is restricted to only display notes for alleles of the same gene.  I'll fix that soon.  Perhaps we can discuss other changes next time we have a call?

I've added this code to the main Fly-Canto because I thought the change was low risk.

![view-genotype-notes-1](https://user-images.githubusercontent.com/90474/84986198-3faf0e00-b192-11ea-911d-7c8f80b29f00.png)

**Comment by vmt25** [comment]
Hi. It looks very nice and, yes, it is very helpful. Thanks for pushing it already into the main Fly-Canto.

**Comment by kimrutherford** [comment]
>  Currently it is restricted to only display notes for alleles of the same gene. I'll fix that soon.

That's fixed now.

**Comment by vmt25** [comment]
I can confirm! Very nice, thanks

Just a note: the dropdown list of alleles also shows the allele being edited. This is not a problem, and may be beneficial, as one can compare the old and new text

**Comment by vmt25** [comment]
Would it be possible to head the text of the other allele with the allele's name, so that it can be selected and copied? This kind of change would mostly deal with #2202

**Comment by kimrutherford** [comment]
Hi Vitor.  Is this what you mean?:

![allele-edit-view-1](https://user-images.githubusercontent.com/90474/85136460-c5ff4900-b293-11ea-83a7-e3694e282c63.png)

**Comment by vmt25** [comment]
> Hi Vitor. Is this what you mean?:

Yes!!!! 2 tickets in 1. Thanks a lot.

(P.S.: Gillian and me say '14:19 UK time? Go to sleep!')

**Comment by ValWood** [comment]
Yes you tell him!

**Comment by kimrutherford** [comment]
>>  Hi Vitor. Is this what you mean?:
> Yes!!!! 2 tickets in 1. Thanks a lot.

Great.

Is there anything else that needs to be done for this issue?

**Comment by vmt25** [comment]
Not from the top of my head.
So we can close it
