### ISSUE TITLE
Allow transfer of multiple phenotype lines from a genotype to another

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2250]
(related to #1830)

Allow transfer of multiple phenotype lines from a genotype to another.
In the example below, these feature would copy/transfer of several/all phenotype lines of c(3)G[1] to e.g. c(3)G[68]

The aim is to go from here:
![Step1](https://user-images.githubusercontent.com/33721108/76330394-b1e79b00-62e5-11ea-956a-68a37c59580d.png)

To here:
![Step5](https://user-images.githubusercontent.com/33721108/76331308-dd1eba00-62e6-11ea-9465-4baeaaf5ba2d.png)

**Comment by vmt25** [comment]
One possibility is to co-opt the 'Transfer' because it is kind of the same thing.
(However, not sure if it will ruin 'Transfer', which is working great as it is.)

For that Transfer would need an intermediary step to select:
1 - transfer of one phenotype to other genotypes (i.e. current Transfer function)
2 - or transfer of several phenotypes from one genotype to another:

![Step2](https://user-images.githubusercontent.com/33721108/76331930-a5fcd880-62e7-11ea-8c81-3420b6c1de9f.png)

Selecting the 1st option would be current transfer:
![Step3](https://user-images.githubusercontent.com/33721108/76332119-e3616600-62e7-11ea-8e80-c3d93c97cf1c.png)

Selecting the 2nd option, would need picking both the destination genotype and the phenotype lines to transfer (term with/without extensions...), but not sure this interface would be easy to implement:
![Step4](https://user-images.githubusercontent.com/33721108/76332547-6be00680-62e8-11ea-91e8-6e53c74b59cf.png)

Selecting all of the phenotypes associated with c(3)G[1] would create similar annotations for c(3)G[68]:
<img width="681" alt="Screen Shot 2020-03-10 at 15 27 20" src="https://user-images.githubusercontent.com/33721108/76332804-bb263700-62e8-11ea-865c-f51043c6a0bd.png">

**Comment by vmt25** [comment]
An alternative, which would not ruin 'Transfer' as it is, would be to have a link from the genotype page.

One possibility would be links under 'Actions'

![Picture1](https://user-images.githubusercontent.com/33721108/76336263-a5674080-62ed-11ea-9dd8-d3415a09eb9b.png)

Another possibility would be a button under each list of phenotype annotations ('phenotype class' and 'phenotype anatomy'):

![Picture3](https://user-images.githubusercontent.com/33721108/76337444-45719980-62ef-11ea-9257-02261aedb298.png)
 


Either way, it would open a menu for picking both the destination genotype and the phenotype lines to transfer (term with/without extensions...), but not sure this interface would be easy to implement:

![Step4](https://user-images.githubusercontent.com/33721108/76336503-01ca6000-62ee-11ea-9f61-2aa305e811f2.png)

**Comment by vmt25** [comment]
Not sure if it helps but these are couple of features from other functionalities that may be useful (and from which code may be copied?)

1 - there is already code to find and list annotations (term+extension) already made to a genotype.
This is the 'Suggested terms' dropdown menu on the interaction window:

<img width="849" alt="Screen Shot 2020-03-10 at 19 01 14" src="https://user-images.githubusercontent.com/33721108/76349251-8d012100-6301-11ea-9347-ff075e377f31.png">

2 - The 'edit genotype' function already allows changing the genotype of several annotations in one go.

**Comment by kimrutherford** [comment]
We'll need to have a think about how this would (or could) work for PomBase.  We'll need to think about if it's useful for GO annotations and what to do about transferring evidence codes and conditions along with the term and extension.

**Comment by ValWood** [comment]
Shall we look at this on Thursday?

**Comment by kimrutherford** [comment]
> Shall we look at this on Thursday?

That would be good.

**Comment by vmt25** [comment]
On the backburner because of limited benefit to PomBase and high task complexity.

**Comment by vmt25** [comment]
wild suggestion, with a very different approach that could accomplish several of the purposes of the ticket (and maybe easier).

Currently, editing a genotype transfer all the associated annotation, right?
Would it be possible to tweak the 'Copy/edit' of genotypes, so that it annotations can also be transfered to the new genotype?

**Comment by vmt25** [comment]
Copy/edit here:
<img width="576" alt="Screen Shot 2020-07-08 at 19 38 43" src="https://user-images.githubusercontent.com/33721108/86957483-aea8d280-c152-11ea-84af-f5dafe744e0f.png">

Then add a 'Transfer annotations' box here (un-selected by default and with an associated 'are you sure' warning message):

<img width="1044" alt="Screen Shot 2020-07-08 at 19 40 08" src="https://user-images.githubusercontent.com/33721108/86957695-fe879980-c152-11ea-9afe-d6fd3b706cf8.png">

**Comment by vmt25** [comment]
> wild suggestion, with a very different approach that could accomplish several of the purposes of the ticket (and maybe easier).
> 
> Currently, editing a genotype transfer all the associated annotation, right?
> Would it be possible to tweak the 'Copy/edit' of genotypes, so that it annotations can also be transferred to the new genotype?
> 
> This would accommodate common cases where there are several similar genotypes where only one of the alleles changes, all with the exact same array of phenotypes.

According to Kim in today's chat, this is possible and maybe not too much work.
Kim will check with Val to see if it should be useful to PomBase or made optional, to accommodate both

GUI-wise, it would be an additional menu line on the genotype management tables.

**Comment by ValWood** [comment]
will add to list for our next call.

**Comment by kimrutherford** [comment]
I've had a think about this.

@vmt25 would it be useful to transfer all the annotation from a genotype to multiple other genotypes?  Or would transferring to one other genotype be enough?

**Comment by kimrutherford** [comment]
Will this function need to work with interaction annotations?

**Comment by vmt25** [comment]
> I've had a think about this.
> 
> @vmt25 would it be useful to transfer all the annotation from a genotype to multiple other genotypes? Or would transferring to one other genotype be enough?


To be cautious, it is probably better to be just one-to-one because:
a) this would be a high-throughput functionality and a mistake will be quickly propagated
b) usually there are 2-to-4 genotypes that phenocopy each other, so repeating this action will be quick
c) it is frequent that genotypes do not fully phenocopy each other, so it is better to make curator pause and do the required edits, before moving to the next genotype

**Comment by kimrutherford** [comment]
> To be cautious, it is probably better to be just one-to-one

Thanks Vitor.  I'll work on that.

Will you need to transfer interaction, complementation or rescue annotations?

**Comment by vmt25** [comment]
> > To be cautious, it is probably better to be just one-to-one
> 
> Thanks Vitor. I'll work on that.

Thanks!

> 
> Will you need to transfer interaction, complementation or rescue annotations?

Yes, please.

**Comment by kimrutherford** [comment]
> > Will you need to transfer interaction, complementation or rescue annotations?
>
> Yes, please.

I think we'll need to have a chat about how the user interface should work for those cases.  Maybe in a week or two once the higher priority jobs are under control.

**Comment by kimrutherford** [comment]
> > > Will you need to transfer interaction, complementation or rescue annotations?
>
> Yes, please.

Let's chat about this on the next Skype call.

**Comment by kimrutherford** [comment]
I've made a bit of progress on this.  It's not finished yet but it's a working prototype.  These changes are in the main FlyCanto tool if you're logged in.

Currently there's a link on the genotype details page that opens a transfer dialog.  There is not yet an option to disable to the transferring of extensions.

If you'd like to do some testing, I've updated the test instance of FlyCanto too: https://curation.pombase.org/flybase-test/

![transfer-all-link-1](https://user-images.githubusercontent.com/90474/110057263-2e13a200-7dc5-11eb-9f05-2f26638f8bf9.png)

![transfer-all-dialog-1](https://user-images.githubusercontent.com/90474/110057278-32d85600-7dc5-11eb-9838-505344865601.png)

**Comment by kimrutherford** [comment]
>  There is not yet an option to disable to the transferring of extensions.

I've added that now.

> >    Will you need to transfer interaction, complementation or rescue annotations?
>
> Yes, please.

I haven't tried implementing transfer for those annotation types yet.  I'll wait until we've had a chat about it.

**Comment by vmt25** [comment]
Hi Kim, 

> I've made a bit of progress on this. It's not finished yet but it's a working prototype. These changes are in the main FlyCanto tool if you're logged in.
> 
> Currently there's a link on the genotype details page that opens a transfer dialog. There is not yet an option to disable to the transferring of extensions.
> 
> If you'd like to do some testing, I've updated the test instance of FlyCanto too: https://curation.pombase.org/flybase-test/
>

Just had a play with it and works great. That will be very useful.
I have a suggestion, if easy to implement - add a 'select all' button!
This would be very useful because it is very common to annotate experiments for a genotype only to find further down the paper the same set of experiments for other genotypes, and frequently with very similar outcomes.

**Comment by kimrutherford** [comment]
> I have a suggestion, if easy to implement - add a 'select all' button!

That should be no problem.  I'll implement that.

**Comment by vmt25** [comment]
Hi Kim,
the 'transfer annotation' links disappeared from both main and test flybase cantos.

**Comment by kimrutherford** [comment]
Hi Vitor.

Could you send me a link to the page you're on?  I picked a random session in the main FlyCanto and I see the links:
https://curation.pombase.org/flybase/curs/7f54e67c36e1995a/feature/genotype/view/32

You have to be logged in to see the "Transfer phenotype class annotation ..." link.  I need to fix that because logging in shouldn't be necessary.

![transfer-1](https://user-images.githubusercontent.com/90474/114928265-8212ab80-9e86-11eb-9b6b-0d4b24dcc657.png)

**Comment by vmt25** [comment]
hmmm...
now I can see it...

**Comment by vmt25** [comment]
On the 20th of April VC it was decided to close this ticket (took long already and first pass already in place) and make new tickets for expansion to annotations of the genetic interaction type
