### ISSUE TITLE
Complementation annotation: Change of 'rules' for interacting genotypes

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2252]
(related to closed issue #1985)
(Apologies for this change but I came across an unusual case that does not fit within the rules)

The initial genotype (or genotype A) should be any single allele genotype available.
The interacting genotype (or genotype B) should also be any other single allele genotype available (excluding genotype A)

**Comment by vmt25** [comment]
Update on the genotypes allowed:

> The initial genotype (or genotype A) should be any single allele genotype available.

of the 'other' type (non-accessory/non-aberration)

> The interacting genotype (or genotype B) should also be any other single allele genotype available (excluding genotype A)

of the 'other' type (non-accessory/non-aberration)


By the way, would it be possible/easy to extend these rules to the genotype list on the Transfer feature?
All genotypes (of all types) are showing up on those lists for both complementation and rescue annotations, even those have some underlying rules.

**Comment by vmt25** [comment]
Please ignore the request to make complementation only available to 'other'-type alleles.

Setting the value of 'interaction_same_locus' value to '0' in canto_deploy.yaml did not fix this, so something else needs changing.

**Comment by kimrutherford** [comment]
>  Try to fix this in canto_deploy.yaml, by setting complementation's 'interaction_same_locus' value to '0', did not fix this, so something else needs changing.

I should have realised this earlier, but for the annotation type setting we need "true" and "false" rather than "1" and "0".  I was confused because Perl needs "1"s and "0"s but the annotation types are used by the Javascript code and need true and false.

I've updated the configuration to have `interaction_same_locus: false` and it think that fixed things.  Could you give it a try?

Here is the current configuration used by Fly-Canto:
https://github.com/pombase/pombase-config/blob/master/canto/flybase/canto_deploy.yaml

**Comment by vmt25** [comment]
Hi Kim,

It seems that the 'single_allele_only: true' configuration is only excluding diploids instead of restricting genotypes to pure single alleles.

So, now it allows picking the following genotypes:
a) single allele genotypes (strict) - this is the only desired behavior
b) and complex genotypes made of single alleles

It excludes the following genotypes:
a) diploids (strict)
b) and complex genotypes that include diploids

I've seen this on the website - https://curation.pombase.org/flybase/curs/6473e2fb7fe4ff81# - and on my local machine (see screenshot)

I've also tried 'single_allele_only: 1' but I get the same behavior.
I've also tried adding 'single_locus_only: true' or 'single_locus_only: 1' but I get the same behavior.

<img width="861" alt="Screen Shot 2020-11-05 at 11 11 23" src="https://user-images.githubusercontent.com/33721108/98235887-5fd14500-1f5a-11eb-997b-0eb8b00d9afc.png">

**Comment by kimrutherford** [comment]
Hi Vitor.  I think part of the problem is that the code is ignoring accessory alleles when it looks for single allele genotypes.

I'm a bit confused about the other requirements.  Could we have a quick Skype about this sometime?

**Comment by vmt25** [comment]
Hi Kim,


> I think part of the problem is that the code is ignoring accessory alleles when it looks for single allele genotypes.

Yes, that is what it looks like.

> 
> I'm a bit confused about the other requirements. Could we have a quick Skype about this sometime?


Sure!

**Comment by kimrutherford** [comment]
After chatting we think that the `single_allele_only` setting should have a third possibility, maybe `ignore_accessory`.  That option would be used in the configuration for the rescue annotation type, but not for the complementation type.

**Comment by kimrutherford** [comment]
I've fixed the single_allele_only setting so that it doesn't ignore accessory alleles when deciding which genotypes are single-allele.  I've updated the main Fly-Canto server.  Could you let me know if it helps?

**Comment by vmt25** [comment]
Yes, it seems fixed.

Were there changes to the canto_deploy.yaml or only in the code?

**Comment by kimrutherford** [comment]
> Yes, it seems fixed.

Great.

> Were there changes to the canto_deploy.yaml or only in the code?

This one was a code fix.  The configuration was correct.

**Comment by vmt25** [comment]
Cool. Thanks.
Closing this one then.
