### ISSUE TITLE
Export FlyBase's approved sessions once per week

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2254]
Need to think about how FlyBase can access the .json output files.

Use something like:
```sh
./script/canto_export.pl canto-json --export-approved > flybase-approved-sessions-`date +'%Y-%m-%d'`.json
```

**Comment by kimrutherford** [comment]
@vmt25 The easiest thing to do is to put the exported files on our website in a known place.  You'd be able to download them as needed.  Would it be a problem if the JSON files were (semi-)public like that?

**Comment by vmt25** [comment]
Not scandalous, but I would like @gm119 to comment on that.

**Comment by gm119** [comment]
I think that it would be OK right now, as long as the canto output does not contain any publication level internal notes (they can contain people's email addresses) - Vitor says that at the moment there are not any publication level internal notes in fly-canto, so for now we are good to go with this suggestion

**Comment by kimrutherford** [comment]
Great.  I'll also give the directory an obscure name so it will be hard to stumble across.

**Comment by kimrutherford** [comment]
This is ready to go.  On which day of the week should the file be written?

**Comment by vmt25** [comment]
Cool, thanks.
Wednesday noon UK time would be good.

**Comment by kimrutherford** [comment]
> Wednesday noon UK time would be good.

Done!  I'll send the URL by email.
