### ISSUE TITLE
pipe separated annotation extensions with only one object

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2259]
malformed GO annotations, do we need a check for this?

mf.gaf:PomBase	SPAC17G6.04c	cpp1	contributes_to	GO:0004660	PMID:10617635	IDA		F	protein farnesyltransferase beta subunit Cpp1		protein	taxon:4896	20140227	PomBase	|has_substrate(PomBase:ras1)
mf.gaf:PomBase	SPAPB1A10.04c	cwp1	contributes_to	GO:0004660	PMID:10617635	IDA		F	geranylgeranyltransferase I and farnesyltransferase alpha subunit Cwp1		protein	taxon:4896	20140227	PomBase	|has_substrate(PomBase:ras1)

**Comment by kimrutherford** [comment]
That's fixed now.
