### ISSUE TITLE
Add script to anonymise Canto track database

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2260]
I sometimes need to make a copy of the production database to confirm that schema changes don't cause errors before upgrading the production version of Canto. It's more convenient to do this locally, but I'm concerned about the data protection implications of transferring curators' personal data onto my machine. It doesn't matter at the moment, since all the curators are part of this project, but once community curation is underway it will be more important.

I think this could just be a quick script that replaces personal data in the `person` table with anonymised placeholders, but maybe it will need more work than that.

**Comment by ValWood** [comment]
I don't know if this will be an issue. When  curators sign up to curate  this should be included in the types of data (i.e datamanagement)

**Comment by jseager7** [comment]
I think I'll just close this since I can probably figure out a script by myself when I need it.
