### ISSUE TITLE
Add option to exclude curator information from JSON export

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2261]
Since PHI-base are considering sharing a JSON export directly from Canto with third parties (since we don't have a pipeline from Canto to PHI-base yet), it would be nice if there was an option to not include curator names and emails when exporting as JSON, since this counts as personal data and has privacy implications.

I assume that Canto exports this personal data by default, and not because of some accidental configuration on our side. I notice that it excludes data from the `people` and `lab` tables by default; maybe this should be extended to the personal details on annotations as well, just to be safe?

@kimrutherford I'm marking this as low priority since PHI-base is capable of removing the personal information with post-processing, although personally I'd prefer it if the data wasn't exported by default.

**Comment by kimrutherford** [comment]
I definitely agree that we should remove the email addresses from the JSON output.  I'll start work on that.

At PomBase we need the curator information so that community curators can be credited on our website.  Will you be doing crediting curation like that?

Here's an example: https://www.pombase.org/reference/PMID:28366743
We just show the name, not the email address.

**Comment by kimrutherford** [comment]
I've changed the code so that email addresses aren't exported to JSON.

If you need to filter the names, I'll add an extra command line option as you suggested.

**Comment by jseager7** [comment]
> At PomBase we need the curator information so that community curators can be credited on our website. Will you be doing crediting curation like that?

I'm not sure if there's been a final decision about displaying curator names, but our current privacy policy states that we _may_ do it.

However, excluding curator names from the export is important, because currently we have to share Canto's JSON export with third parties, since we don't yet have a way to get Canto's data in to or out of PHI-base (otherwise we could use an API). Our privacy policy doesn't permit sharing personal data with third parties, so having a command line option to toggle the export of names (or all personal data) would be fine for our purposes.

**Comment by kimrutherford** [comment]
Hi James.

I've added a new flag `--export-curator-name` for use by PomBase.  The default is now to not export curator and approver names.  Please let me know if you spot any problems.

**Comment by kimrutherford** [comment]
> --export-curator-name

I've renamed that to `--export-curator-names` which makes a little more sense.

**Comment by jseager7** [comment]
This works fine for me on my local copy and on the production server, thanks.
