### ISSUE TITLE
complementation bug: after picking initial genotype, no allele is recognized for the interacting genotype

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2262]
The current implementation of complementation is set to allow picking a single allele as initial genotype and then allowing as interacting genotype any other single allele genotype of the same gene.

However, no alleles are showing for the interacting genotype.
Please note that there are 2 alleles for GATAe but then none appears for the interacting genotype list:

<img width="839" alt="Screen Shot 2020-04-07 at 22 05 45" src="https://user-images.githubusercontent.com/33721108/78719531-f897d780-791b-11ea-84b0-1393a84d99d2.png">

<img width="837" alt="Screen Shot 2020-04-07 at 22 07 06" src="https://user-images.githubusercontent.com/33721108/78719640-2a10a300-791c-11ea-8838-ac85a7191d7a.png">

This bug was seen in several sessions on the online Fly-Canto, but not on the one on my laptop's VM.

Of importance, it may be worth fixing this issue at the same time as #2252, which asks for a change in the rules on which interaction genotypes should be accepted.

**Comment by kimrutherford** [comment]
Hi Vitor.  I've just tried this in my local Canto and I can't reproduce the bug.  So any examples of sessions where this happens would be very useful.  Thanks.

**Comment by vmt25** [comment]
OK. Thanks

**Comment by vmt25** [comment]
Closing because the bug is not being reproduced.

**Comment by vmt25** [comment]
Re-opening because the behavior re-surfaced.

See https://curation.pombase.org/flybase/curs/7bd1497ac8c0803b#.

Several genes have multiple alleles, e.g. Dcp-1, so picking any allele of Dcp-1 would allow picking any other of its alleles, which is not happening in this session:

<img width="928" alt="Screen Shot 2020-07-24 at 11 53 46" src="https://user-images.githubusercontent.com/33721108/88384564-8fda4b00-cda4-11ea-97e5-2d6f75fbcb25.png">

<img width="929" alt="Screen Shot 2020-07-24 at 11 55 35" src="https://user-images.githubusercontent.com/33721108/88384629-a8e2fc00-cda4-11ea-92a0-0a219475933f.png">

Again, it would be better to fix #2252 at the same time! (my mistake on the original genotype rules for complementation annotations)

**Comment by kimrutherford** [comment]
Thanks for the link to the session and the example.  I was able to reproduce the bug and (I think) fix it.  Canto we tripping up over the aberration in that session.  Maybe the session I tested on previously didn't have aberrations so didn't show the bug.

> Again, it would be better to fix #2252 at the same time!

I'll look at that next, on Monday.  Sorry it has taken a while.

**Comment by vmt25** [comment]
> Thanks for the link to the session and the example. I was able to reproduce the bug and (I think) fix it. Canto we tripping up over the aberration in that session. Maybe the session I tested on previously didn't have aberrations so didn't show the bug.
>

Thanks!
