### ISSUE TITLE
update modification ontology

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2265]
I thought we had a ticket about this but I can't find it.

I'm waiting on the appearance of this term:
https://github.com/HUPO-PSI/psi-mod-CV/issues/9

**Comment by kimrutherford** [comment]
We last updated PSI-MOD.obo in 2011 so I think I'll be cautious and load it into Canto on my desktop first.  I'll also run a Chado load locally.

See also: pombase/pombase-chado#679

**Comment by ValWood** [comment]
ANy luck with this. I still don't see the term?

**Comment by ValWood** [comment]
not to self PMID:28801462

**Comment by kimrutherford** [comment]
It's updated in the Chado loads.  I wanted to do that first.  I'll try updating the test Canto later today.

**Comment by kimrutherford** [comment]
It looks OK for me in the main pombe Canto now.

**Comment by ValWood** [comment]
Can close. I have this task on multiple to do lists and e-mails. Will do it today as its a 1 minute job
