### ISSUE TITLE
migrate annotation to a session  (in approval)

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2267]
Could we migrate everything on 
PMID:28799013
onto
PMID 28652406

The annotation was made on the wrong session PMID:28799013 is a review.

If it is easier to do this in chado we can approve it through and then migrate?

**Comment by kimrutherford** [comment]
So do we just need to keep the session that same except for changing PMID:28799013 to PMID:28652406?

**Comment by ValWood** [comment]
yup

**Comment by kimrutherford** [comment]
> So do we just need to keep the session that same except for changing PMID:28799013
> to PMID:28652406?

Looks like it's not that simple because both publications have sessions and both sessions have annotations.  I'll have to have a think about the best way to move the annotations.

**Comment by ValWood** [comment]
Oh that's strange.... I assumed the other paper was not yet curated. Let me look into that and get back to you. Shower first.  TMI this morning ;)

**Comment by ValWood** [comment]
I don't see any annotation on this session?
https://www.pombase.org/reference/PMID:28652406

**Comment by ValWood** [comment]
GOt it
PMID:28652406  was partially done by somebody who has presumably moved on, and never submitted.

Both sets of annotations look good.
I have submitted this session.

So if you can
move the annotations from  PMID:28799013 over to PMID:28652406 *keeping* the annotations from PMID:28652406 (i.e just merge) 
that would be good.

That way, we can remove anything redundant when we do the checking/approval.

Is that possible/easy?

**Comment by ValWood** [comment]
Hi Kim could you look at this  , Clàudia Salat Canela  just mailed and asked if I had forgotten about it. I had!

cheers

val

**Comment by kimrutherford** [comment]
Moving the annotations is tricky so I thought I'd try something safer.  I've changed the session for PMID:28799013 to be a session for PMID:28652406:
  https://curation.pombase.org/pombe/view/object/pub/11911?model=track

If you approve Claudia's session:
https://curation.pombase.org/pombe/view/object/curs/4561?model=track
you'll be able to see those annotations in Canto in the second session after the nightly load.

The second session is unchanged so far:
https://curation.pombase.org/pombe/view/object/curs/4492?model=track

Sorry this is more complicated for you.  If it turns out to be too complicated I'll work on moving all the annotations to the same session.

**Comment by ValWood** [comment]
I don't think that sounds complicated. So I just approve the session as normal? Then you will move that annotation?

**Comment by kimrutherford** [comment]
> I don't think that sounds complicated. So I just approve the session as normal? Then you will
> move that annotation?

I was hoping you could just delete any duplicate annotation from the older session and then approve that too.  Two approved sessions for one publication should be supported.  If not I'll fix things.

**Comment by ValWood** [comment]
I'm getting confused. I didn't think there were any annotation on the one being moved to. I won't get chance to look at it today as I still haven't prepared  the  "live demo" for Wednesday.

It will probably be Thursday befoer I get chance to look at it...

**Comment by ValWood** [comment]
I have checked this session, and removed the annotation from the old session, so all is fine.

Thanks!

**Comment by kimrutherford** [comment]
I'm reopening to remind myself to delete the old session.

**Comment by ValWood** [comment]
I deleted it in Canto

**Comment by kimrutherford** [comment]
I forgot that was possible.  :-)
