### ISSUE TITLE
Add admin script option for renaming strains

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2268]
```
canto_admin.pl --rename-strain old-name new-name
```

**Comment by jseager7** [comment]
Do we have a plan for what happens when a strain is renamed to match a strain that already exists in the database? Will the script just fail?

I was wondering – assuming we've got no way to delete strains at the moment – whether it would be better to allow strains to be merged when they're renamed to the same name (in case we discover in future that a strain that we have categorised as a distinct strain turns out to be a synonym of an existing strain). We can afford to wait until that happens, though.

**Comment by kimrutherford** [comment]
Thanks for that.  I'll make sure that the script checks for any existing strain with the same name before renaming.

**Comment by kimrutherford** [comment]
Hi James.

I've added a new option to the `canto_admin.pl` script:

```
  ./script/canto_admin.pl --rename-strain taxonid old_name new_name
```

The script will report an error if there is an existing strains with the new strain name.

Let me know if it works for you.  Could you close the issue if it looks OK?

**Comment by jseager7** [comment]
@kimrutherford Thanks for this. I've tested the script and it works fine for ASCII characters. Unfortunately, some of our strains have UTF-8 characters in them, and entering them from the command line is convoluted. If you're renaming _from_ UTF-8 to ASCII, it might be alright (haven't tested that), but introducing UTF-8 characters in the new strain name doesn't seem to be handled correctly.

With the following contrived example, renaming 'PH-1' to 'PH-ひ', I tried escaping the UTF-8 character in the prompt, which allowed it to load:

```sh
./canto/script/canto_docker /canto/script/canto_admin.pl \ 
--rename-strain 5518 PH-1 PH-"$(printf '\xe3\x81\xb2')"
```

But once it gets into Canto, the encoding gets mangled, displaying as 'PH-ã²':

![image](https://user-images.githubusercontent.com/37659591/82216654-2c99eb80-9911-11ea-9dc2-e037e548ffed.png)

Maybe the Perl script isn't expecting to parse command line arguments as UTF-8?

My terminal locale is definitely UTF-8, so the escape sequence should be correct.

```sh
vagrant@canto-vm:~/canto-docker$ echo $LANG
en_US.UTF-8
```
Even if we fixed the script, I'm not sure if having to interpolate `printf` calls into the command to insert UTF-8 characters is a good idea. Would it be possible to supply the arguments from a file instead in these cases?

**Comment by kimrutherford** [comment]
Hi James.

Thanks for testing and spotting that issue.

I think I've fixed the immediate problem by passing extra flags to Perl.  The "-A" flag tells Perl that the arguments are utf-8.  I can now run:
```
./script/canto_admin.pl --rename-strain 9031 Wistar "Cobb-PH-ひ"
```
and get the expected result.

Does that change work for you?

**Comment by jseager7** [comment]
I get the following error when trying to run the previous command (see https://github.com/pombase/canto/issues/2268#issuecomment-630180124):

```
/usr/bin/env: invalid option -- 'S'
```
I did some searching, and this might be due to a GNU coreutils version mismatch? My version is below:
```
env (GNU coreutils) 8.26
```

**Comment by kimrutherford** [comment]
Drat!

Could you try changing the first line of your copy of canto_admin.pl to this:
```
#!/usr/bin/perl -CA
```

and let me know how it goes?

Thanks.

**Comment by jseager7** [comment]
That worked, thanks. When run with Perl, the UTF-8 name loads and displays with no errors:

![image](https://user-images.githubusercontent.com/37659591/82316425-ae971c80-99c4-11ea-8c91-eefac0be6e65.png)

**Comment by kimrutherford** [comment]
Thanks for testing and thanks for tracking down the env problem and docs.

I've committed the fix.

**Comment by kimrutherford** [comment]
I reopened this issue because we need to support merging two old names into one new name.  After a bit of thought I think it's better to have a separate tool for merging strains.  I've made an issue: #2329
