### ISSUE TITLE
generic Canto configuration

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2269]
- [x] 1.  Title Canto- GO Community Curation
-> Gene Ontology (GO) Community curation

- [x] 2. Curate a paper for Generic GO
-> Annotate your publication using GO terms

- [x] 3. Once you have found your paper, you can curate GO, phenotypes, interactions and protein modifications -- or reassign the paper to a colleague for curation. See the help pages for more information.

->  Once you have found your paper, you can curate GO (Molecular Functions, Biological Processes or Cellular Components) or reassign the paper to a colleague for curation. See the help pages for more information.

4. in the help docs remove the annotation extension example  for severity/expressivity. This one is for phenotypes only

5. I think we should have a better hook than "Add your work" under the title
Suggestions?

@RLovering

**Comment by kimrutherford** [comment]
I've made changes 1-3

> in the help docs remove the annotation extension example for severity/expressivity. This one is
> for phenotypes only

Which page is that on?

**Comment by ValWood** [comment]
On the annotation extension help.

will get link....

**Comment by ValWood** [comment]
https://curation.pombase.org/uniprot/docs/go_annotation
  maybe it is in the wrong place in pombase docs too 
]argh, poorrige burning

**Comment by ValWood** [comment]
yes https://curation.pombase.org/pombe/docs/go_annotation
perhaps this should only appear for  phenotypes.
 is that possible in the way the docs are set up?

**Comment by kimrutherford** [comment]
> maybe it is in the wrong place in pombase docs too

Yep, I think a GO extension example would make more sense on that page.

> perhaps this should only appear for phenotypes.
> is that possible in the way the docs are set up?

I'm not sure what you mean.

**Comment by mah11** [comment]
I found it -- the GO and FYPO documentation pages use the same screenshot of the extension interface, mainly because they're making the same point (but also a bit out of laziness). The GO page does explicitly say that the illustration uses an example from FYPO, so I don't think it's a deal-breaking problem.

The text on the GO documentation pages only talks about extensions available for GO.

**Comment by ValWood** [comment]
but it's on this page,
https://curation.pombase.org/pombe/docs/go_annotation
which is the GO annotation page?

**Comment by ValWood** [comment]
It won't confuse pombe users, but it could confuse people using the generic tool.
We copied the GO annotation help for PHIPO and generic GO canto...
