### ISSUE TITLE
Generic GO Canto, clear out existing sessions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2273]
There are 110 sessions. All can  be cleared out....

**Comment by kimrutherford** [comment]
I removed all the session and publications.  Should I clear out the non-admin people from the database?: https://curation.pombase.org/uniprot/view/list/person?model=track

**Comment by ValWood** [comment]
I think a clean out would be good

**Comment by ValWood** [comment]
I think this is done?

**Comment by kimrutherford** [comment]
> I think this is done?

Yep.  I forgot to close it.
