### ISSUE TITLE
JSON export invalidated by including shell output

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2275]
This is how [the Canto documentation](https://curation.pombase.org/pombe/docs/canto_admin/data_export) says to export curation sessions as JSON:

```sh
script/canto_export.pl canto-json --dump-approved > canto_approved.json
```
Problem is, this also includes any warnings and notices that would normally go to standard output, and that can invalidate the whole JSON file if, for example, you get something like this:

```
Wide character in print at /canto/script/canto_export.pl line 99.
{
  "curation_sessions" : {
    "0d2bc8d23a8667f4" : {
      ...
  }
}
```
@kimrutherford I could fix this with post-processing, but wouldn't it be better to have some way to suppress these notices, or have them sent to somewhere other than standard output? Alternatively, we could add an argument on the script for the file that the JSON should output to, so we don't need to redirect the output in the first place.

**Comment by kimrutherford** [comment]
That's a bit annoying.  In general Perl errors are sent to standard error.

Could you send me a copy of your database so I can track down what is causing the "Wide character" error?

**Comment by jseager7** [comment]
I ended up looking into the problem myself, and it looks like there's a quick fix for this specific warning where we just tell Perl to encode standard output as UTF-8:

```perl
use open ':std', ':encoding(UTF-8)';
```
I replicated the bug by creating a local session with a UTF-8 character in an annotation comment:
![image](https://user-images.githubusercontent.com/37659591/80366587-6bdc9b80-8881-11ea-96c2-f72a6e20588e.png)
Without the `use` function, I get the error, but with it, I don't.
- - -
More generally, I'm not sure if expecting output redirection is a good idea for this script, because if you use the verbose flag `-v`, you get the verbose output in the JSON file, which again invalidates it:
```
1 sessions exported
{
  "curation_sessions" : {
    ...
}
```
If we must use standard output for printing the JSON, could we at least move the diagnostic and warning messages to the standard error stream?

**Comment by kimrutherford** [comment]
> use open ':std', ':encoding(UTF-8)';

Thanks for the fix.  I've checked it in.

> because if you use the verbose flag -v, you get the verbose output in the JSON file, which
> again invalidates it:

Could you double check that?  When I try it the "sessions exported" message goes to stderr.

**Comment by jseager7** [comment]
I ran this exact command:
```
./canto/script/canto_docker /canto/script/canto_export.pl -v canto-json > ~/export_test.json
```
And the output was as follows (still including the old error message because I haven't pulled the fix yet)

```
33 sessions exported
Wide character in print at /canto/script/canto_export.pl line 99.
{
   "curation_sessions" : {
      ...
   }
}
```
Maybe the Docker container is interfering with the redirection?

**Comment by jseager7** [comment]
Looks like it was Docker all along. With the `--non-interactive` flag set, all the diagnostic messages go to standard error, like they're supposed to:
```
> ./canto/script/canto_docker --non-interactive /canto/script/cant o_export.pl -v canto-json > ~/export_test.json
33 sessions exported
Wide character in print at /canto/script/canto_export.pl line 99.
```
Thanks for looking into it. I'll amend the wrapper script that I use to export sessions, so that it runs Docker with that flag set. It was probably worth fixing the UTF-8 issue anyway, because I'm not sure if Perl would've been exporting those characters correctly without it.

I don't think there's anything else to do, so I'm closing this now.
