### ISSUE TITLE
Enable PHI-Canto tool to pull in existing GO annotations (like Canto)

### ISSUE THREAD

**Issue by CuzickA** [pombase/canto#2277]
Yesterday @ValWood and I discussed that this could be useful for PHI-Canto.

We would need an option for the curator to select or reject these non-editable terms and also a way to indicate the source of GO annotation (manually annotated by PHI-Canto curator or automatically pulled in GO annotation).

**Comment by ValWood** [comment]
This may already work. We can try looking at a paper which is used for GO annotation in Uniprot.
I might get chance to look in a minute.....

**Comment by CuzickA** [comment]
@ValWood The session we were looking at yesterday has EPI1 GO annotation in UniProt
https://github.com/PHI-base/curation/issues/41

search QuickGO for 'EPI1' and get annotations to both of the UniProts (still not clear which to use)
![image](https://user-images.githubusercontent.com/11753634/80493724-ab78b580-895d-11ea-8f30-3db360d92cf8.png)

https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q6PQH2
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=D0MVC9

I'm not sure how we automatically load these suggested GO annotations into PHI-Canto.

**Comment by ValWood** [comment]
there is one annotation from this paper:

UniProtKB:Q6PQH2 | EPI1 | involved_in | GO:0052054    negative regulation by symbiont of host peptidase activity | ECO:0000314   IDA | PMID:15096512 |   | 4787 Phytophthora infestans | PAMGO_VMD

This is one of the terms I will  suggesting we obsolete (it isn't incorrect but it is unsustainable to do this when we can make more sensible statement by postcomposing MF+BP as

MF peptidase inhibitor involved_in   BP effector-mediated suppression of host innate immune response  ...

**Comment by ValWood** [comment]
It isn't clear to me why UniProt has 2 entries, one strain specific.  UniPRot should be non-redundant Could you mail 
and ask them, CC me.

**Comment by ValWood** [comment]
related to https://github.com/pombase/canto/issues/2271

**Comment by kimrutherford** [comment]
> I'm not sure how we automatically load these suggested GO annotations into PHI-Canto.

That sounds like quite a lot of work to implement.  We should chat about this on the next call.

**Comment by ValWood** [comment]
it's the same as  #2271 though?

**Comment by ValWood** [comment]
(i.e show existing annotations for a publication)

**Comment by kimrutherford** [comment]
In the generic GO Canto we display the current GO annotation from QuickGO, but we don't load them into Canto.  So viewing is implemented already.

But without loading them into Canto this is tricky to implement:

> We would need an option for the curator to select or reject these non-editable terms

**Comment by kimrutherford** [comment]
@jseager7 if you haven't got it already, add this line to `implementation_classes` in the config to allow curators to see existing GO annotation:

```yaml
    ontology_annotation_adaptor: Canto::UniProt::OntologyAnnotationLookup
```

I fixed a few bug with it recently so you'll need the latest code.

**Comment by ValWood** [comment]
OK  I see why it is tricky. we can start visualising now.
the ability to ' flag' as correct or incorrect is covered in  #2271 
we can discuss this.

**Comment by jseager7** [comment]
I've added the required line to our PHI-Canto configuration, so the existing GO annotations _should_ be visible on the production server now, but I'm not sure how to check this. @ValWood or @CuzickA, if either of you know where to look for this, could you let me know if it's working? Thanks.

**Comment by CuzickA** [comment]
> It isn't clear to me why UniProt has 2 entries, one strain specific. UniPRot should be non-redundant Could you mail and ask them, CC me.

Just emailed UniProt about this
[help #184983] EPI1 from Phytophthora infestans

**Comment by ValWood** [comment]
yes
PMID:15096512 |
now has

Species | Gene | Term ID | Term name | Evidence code
-- | -- | -- | -- | --
P. infestans | EPI1 (Q6PQH2) | GO:0052054 | negative regulation by symbiont of host peptidase activity | IDA |

**Comment by jseager7** [comment]
@ValWood are you happy to close this issue? It sounds like the other part of the issue relating to selection and rejection is covered by issue #2271.

**Comment by jseager7** [comment]
Having said that, this part of the issue might not be implemented:

> a way to indicate the source of GO annotation (manually annotated by PHI-Canto curator or automatically pulled in GO annotation).

@CuzickA why do we need to indicate the source of the term? Is there no way to tell the difference in Canto?

**Comment by ValWood** [comment]
Yes can close. 
Thanks!

**Comment by ValWood** [comment]
I would not worry about the source.
If anyone challenges any existing annotation  I will need to raise a dispute in the EBI curation tool, protein2GO from where it will be sent to the originators.

I'll get access for Alayne too at some point.

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/80798341-19aabb80-8b9c-11ea-89c0-7f4b486ead2f.png)

This is great. I hadn't realised that these terms would appear under sub-heading 'existing annotations'. This makes it nice and clear as to which annotations are existing and which are made in the current session. Out of interest @ValWood how would these results be displayed on your PomBase results page? Are the GO annotations displayed in the same format irrelevant of whether generated from an existing annotation or newly annotation in a session?

**Comment by ValWood** [comment]
Yes they are displayed the same. We pull in all the GO for pombe genes. MAinly IEA from other sources Just about to start pulling in  the phylogenitically inferred PAINT annotations.
There is a small amount of manual annotation from Unirprot, but not so much as Marc concentrates on other fungal species.

We display all EXP annotation, regardless of source, but ask for it to be removed/corrected if wrong.
We  filter any redundant non-EXP because it does not add any information for the user.
I wish other resources would do this too!

This would be good to implement in PHI-BAse. This menas that if you make a TAS, and the annotation does not exist the TAS annotation  would display in PHIBase, but if an experimental annotation is available from an alternative source, you would not see it. It stops masses of redundency.

If this doesn't make sense I can go through it on the next call.

**Comment by CuzickA** [comment]
Ok thanks. It may be useful to have a quick look at this on the next call.

Is it possible that an existing GO annotation made from 'paper A' may be pulled into a PHI-Canto session curating 'paper B' and then be displayed in the results as a GO annotation linked to the newly curated 'paper B'? 
Could this be misleading if the new 'paper B' did not contain experimental evidence for the older 'paper A' GO term annotation? ('paper A' may not have been suitable for PHI-base inclusion).

**Comment by ValWood** [comment]
No we only pull in the annotations from  the paper we are curating.

Anything else will need to be post-processed in your database.

Val
