### ISSUE TITLE
Which allele types should allow 'Null' expression?

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2280]
(Following discussion from #2215)

Canto currently allows setting 'Null' expression on all allele types except 'deletion', which doesn't permit setting any expression level at all. @mah11 noted that this probably shouldn't be the case, at least for PomBase:

> we only use null for deletions and disruptions […] I'm not sure we should [allow Null], at least for wild type, and IIRC "null" didn't appear for all (non-deletion) types in the past.

@ValWood @CuzickA which allele types do you think need Null expression available as an option? Would you be happy to restrict it to the following set?

- Deletion (already implies Null expression)
- Disruption
- Other

I don't know if FlyBase need to be involved in this discussion. I thought I remembered hearing that they don't curate expression level in the same way.

**Comment by ValWood** [comment]
I think you could begin with this set. It can be revised if necessary.

**Comment by jseager7** [comment]
I've restricted Null expression to disruption and 'other' type alleles. Closing now &ndash; we can re-open this issue if we need to change where the expression type is available.
