### ISSUE TITLE
Always update extension config for nightly ontology update

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2284]
Need to "git pull" pombase-config before the ontology update.

**Comment by ValWood** [comment]
;)

**Comment by jseager7** [comment]
@kimrutherford This would be useful for PHI-Canto as well, so could you let me know what your chosen solution is? Just in case it's something more sophisticated than copying files from one directory to another. For PHI-Canto we already clone our config repository to the server, but the config files aren't deployed automatically.

**Comment by kimrutherford** [comment]
> Need to "git pull" pombase-config before the ontology update.

That's fixed now.

> This would be useful for PHI-Canto as well, so could you let me know what your chosen solution is?

It's not a very sophisticated solution.  We have a copy of the pombase config repo checked out on our server and we do `(cd pombase-config; git pull)` just before our nightly ontology update.  Our extension configuration in `canto_deploy.yaml` points to the files to that directory.
