### ISSUE TITLE
a different 'expression' type

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2289]
I'm checking  a session where the expression level has been selected as "overexpression" because this was the best available option.

However for the experiments, I think it's a bit misleading.

This refers to Atf1 (one of the stress responsive transcription factors). Normally,  this TF is expressed in response to stress. The authors wanted to decouple the feedback loop where atf1 upregulated it's own  transcription. Therefore they deleted the genomic atf1 and hooked the WT gene up to a constitutive promoter.

So in a sense the Gene product  is 'overexpressed' because it is expressed outside of its normal stress activation. But THEN, the authors do  all the experiments in stressed conditions to look at the  situation  (they are looking specifically at the effects of sty1 phosphorylation of Atf1, so they are looking at a WT situation during stress). They just wanted to remove the stf1 upregulation of itself.

The atf protein levels are in fact normal (or actually lower. because of the absence of the feedback loop)

"We demonstrate here that the transcriptional
profile of atf1 cells expressing HA-Atf1 is very similar to that
of wild-type cells despite the fact that the concentration of the
TF is constant."

"Importantly, the use of anti-HA antibodies
demonstrates that the levels of HA-Atf1 are not
enhanced upon stress, as would be expected if phosphorylation
would stabilize Atf1 (Fig. 1C)."

So overexpression doesn't work.
I wonder if we need another type, but  maybe that is overkill.
Should I curate as "other" and   type 'promoter swap' or something?

(I'm putting the ticket on this tracker, can move it later)

**Comment by mah11** [comment]
quick off-the-cuff answer: damn, what a headfck; I dunno.

If we add a new expression description, "constitutive" would probably work. But that doesn't address the excellent question of whether it's overkill.

**Comment by ValWood** [comment]
I'll wait until  I finished the session and have any other ideas.

I was thinking  if it was only the WT I could do 
other  -promoter swap.

The problem is they did the same experiments with whole slew of other alleles
phosphomimetic, mutating various phosphorylation sites in different. ways. I think these are valuable to have captured as amino acid changes.

I also considered changing to WT expression and then sticking a comment in the background
"constitutive  promoter used to  decouple from Atf1 +ve. feedback"
(this might be the best option currently, because the premise is that this does indeed not affect the results they are looking at  which is the initial activation of Atf1 by the Sty1 AMP kinase)
 I think we probably don't want another ' expression type' at this stage. I reckon this will work  OK and can be changed if ever we  decide to add more in the future.
