### ISSUE TITLE
user interface: interaction evidence workflow

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#229]
transferred from old item
https://sourceforge.net/tracker/?func=detail&atid=2525791&aid=3518828&group\_id=65526

Could you swap the order of the workflow for interactions.
We think it would make more sense to do the evidence code selection step first. This way they will know if they are curating in the correct direction

I am making this low priority, we will raise it if it confuses people, but I think it is fine, it would be nice but  in light of
\(3\) will take a bit of work as the workflow is quite hard-wired at the
moment.  I'll work on it.

it isn't a necessity unless it confuses people.

Original comment by: ValWood

**Comment by ValWood** [comment]
We want to do this......

**Comment by kimrutherford** [comment]
I've changed to code to ask for the evidence code first.  The change is in the test Canto.  Could you try it and let me know what you think?

**Comment by Antonialock** [comment]
this is better for me

**Comment by mah11** [comment]
yes, huge improvement
thanks :)

**Comment by kimrutherford** [comment]
OK, thanks for having a look.  I can release the change into the main Canto any time  if you're happy that it's working OK and the interactions are appearing in the session correctly.

**Comment by Antonialock** [comment]
there's a taxon ID column showing in the test tool that's not in the normal tool, otherwise it seems fine.

![screen shot 2016-07-21 at 11 23 10](https://cloud.githubusercontent.com/assets/12727506/17019709/9669be52-4f35-11e6-8c0a-ea28db5cac2d.png)
![screen shot 2016-07-21 at 11 23 00](https://cloud.githubusercontent.com/assets/12727506/17019710/9673fd22-4f35-11e6-8345-66c4ef13e2d1.png)

**Comment by kimrutherford** [comment]
> there's a taxon ID column showing in the test tool that's not in the normal tool

The test tool is configured to allow pombe or cerevisiae IDs (for testing) so the tables show the taxon ID too.

**Comment by Antonialock** [comment]
ok that makes sense

**Comment by mah11** [comment]
in that case, it all looks fine to me

**Comment by kimrutherford** [comment]
OK, it's in the main Canto now.  Please open new issues if there are problems.

**Comment by mah11** [comment]
yay, closed an old ticket!
