### ISSUE TITLE
Show species names in Transfer dialog in multi-organism modes

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2290]
Sub-issue of #1830 

For PHI-Canto, in the Transfer annotation dialog, it would be useful to have the species names displayed next to the feature name for gene and genotype annotations, because sometimes we have the same gene or allele on different organisms, and there's no way to distinguish them in this case.

The example below shows TRI5 genes from _Fusarium sporotrichioides_ and _Trichoderma arundinaceum_, but there's no way to tell which is which. (The annotation is being transferred from TRI5 on _F. graminearum_.)

![image](https://user-images.githubusercontent.com/37659591/82307746-afc24c80-99b8-11ea-9b35-370768f545c2.png)

The proposed fix would have it look like this:

![image](https://user-images.githubusercontent.com/37659591/82308650-ff554800-99b9-11ea-9ec2-f4a3b1467bc2.png)

Note that the species name should also be displayed in the title of the modal.

**Comment by jseager7** [comment]
## Species names in modal header

For the modal header, the following code needs amending to show the term, species name, and extension. We probably want to rename `termAndExtension` to something generic, like `termDetails`.

https://github.com/pombase/canto/blob/18efd948d9de55d1bdf0a10ea373d70ee47fae31/root/static/ng_templates/annotation_transfer.html#L3-L9

The string is generated here:

https://github.com/pombase/canto/blob/b1c7b9c4a947f359ad750a967fef888ec242e695/root/static/js/canto-modules.js#L7054-L7060

It looks like `annotationTransferDialogCtrl` already injects `CantoConfig` and `Curs`, so we have the means to check which mode Canto is in, and we also have another way to retrieve the organism details if they're not contained in the data for the feature.

https://github.com/pombase/canto/blob/b1c7b9c4a947f359ad750a967fef888ec242e695/root/static/js/canto-modules.js#L7039-L7043

## Species names in feature chooser

This case is more tricky, since the `multiFeatureChooser` directive that is used by `annotation_transfer.html` is very dynamic, and it always gets the feature name from the `feature.display_name` property:

https://github.com/pombase/canto/blob/18efd948d9de55d1bdf0a10ea373d70ee47fae31/root/static/ng_templates/multi_feature_chooser.html#L8

My ideas are as follows:

* **Option 1**: Add some conditionals to the template to display the organism name when Canto is in multi-organism or pathogen-host mode. However, the `CantoConfig` service would have to be injected into the controller (unless we want to pass the mode in as a binding), and this would only fix the behaviour in `multiFeatureChooser`; the problem could still show up somewhere else.

* **Option 2**: Add a new property to the `feature` objects called `full_display_name` or `unique_display_name` that shows the minimum amount of information required to disambiguate one feature name from another name:

  * For single organism mode, the unique display name is simply the gene name, e.g. cdc2.

  * For multi-organsim mode, the unique display name is the gene name followed by the species name, e.g. TRI5 (Fusarium graminearum).

  * If strains are also enabled, the unique display name should display the strain for genotypes and metagenotypes, e.g. TRI5 (Fusarium graminearum, PH-1)  (genes don't need this because they're assumed wild-type, or the strain isn't relevant).

  This option has the advantage that we only need to change the feature chooser (and any other relevant directives) to show the unique display name instead of `display_name`, so we don't need to keep implementing the same conditional code to handle how the features should be formatted.

* **Option 3**: If it turns out there's lots of variability in how we want to display feature names in different circumstances, it might be better to move the formatting logic to an AngularJS filter or service, with its defaults configured at runtime based on the mode that Canto is in. This filter or service could then control which properties get rendered through its parameters.

- - -

@kimrutherford Do you have any preference?

**Comment by kimrutherford** [comment]
Hi James.

I think the feature-chooser component already uses something like Option 3.  Perhaps this could be re-used?:
https://github.com/pombase/canto/blob/18efd948d9de55d1bdf0a10ea373d70ee47fae31/root/static/js/canto-modules.js#L385-L407

**Comment by jseager7** [comment]
> I think the feature-chooser component already uses something like Option 3. Perhaps this could be re-used?

Thanks for reminding me about this. I was sure there was some code that was already handling these different display modes. It's possible that showing the background might be a bit excessive in this case, but maybe there are cases for PHI-base where the background is the only unique feature. I'll take a look at applying that filter to `multiFeatureChooser`.

**Comment by jseager7** [comment]
@kimrutherford I forgot that `featureChooserFilter` only shows the organism name for genes in multi-organism mode. This is awkward, because for the annotation transfer we really need to show the organism name for the genotypes as well (metagenotypes don't count because they already include the organism names in their `display_name` property).

The simple fix is to change `featureChooserFilter` to show the organism name for both genes and genotypes, but the problem with this is that the organism name is redundant in many other dialogs that show the organism name in another field. We already have this problem with gene annotations:

![feature-chooser-organism](https://user-images.githubusercontent.com/37659591/83511919-49185500-a4c7-11ea-9894-b526871e9b5c.PNG)

The next quickest fix is to add an argument to `featureChooserFilter` that allows the organism name setting to be overridden (while still excluding it for metagenotypes and single-organism mode), then have `multiFeatureChooser` always call `featureChooserFilter` with this argument set. I'll try this first.

- - -

If we want to solve the problem generally, the only solution I can think of is to add multiple arguments to `featureChooserFilter` (or one argument for a configuration object) that controls which properties of the feature are shown – we'll also need corresponding bindings to supply values for the filter's arguments on `featureChooser` and `multiFeatureChooser`.

Once that's done, we can individually configure the feature display mode for each directive that uses the feature choosers. If we want to set defaults for each Canto mode, we could set these in a service at startup, which would later be injected into the feature chooser directives, or directly into `featureChooserFilter`.

**Comment by jseager7** [comment]
I've opened a pull request that adds a quick fix. We might need to come up with something better in future, particularly if we start using `multiFeatureChooser` in other contexts.

**Comment by jseager7** [comment]
I'll close this now, since the issue itself is fixed by #2291, but I'll open a future issue to keep track of the other problems I mentioned.
