### ISSUE TITLE
Broken images on protein modification documentation

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2292]
I've noticed two broken images on the documentation page for the 'Protein modification' annotation type. This affects all versions of Canto.

![image](https://user-images.githubusercontent.com/37659591/83529392-30696880-a4e2-11ea-8700-215f5feebf54.png)

@kimrutherford At first I thought that these images were renamed without being updated in the source document, because some other pages have these similarly named files with the same alt text:

* go_ext_edit_button.png (button to edit annotation extensions)
* edit_go_ext.png (Annotation extension editing interface)

But I think it's more likely that these images either never existed or have stopped existing, since I'd expect them to be named something like mod_ext_edit_button.png and edit_mod_ext.png if they did exist.

**Comment by mah11** [comment]
I've done most (maybe all?) of the documentation screenshots. I'll add the images you suggest.
