### ISSUE TITLE
background"workaround" no longer working

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2294]
I have an alleles which sometimes has a particular background and sometimes  not. So I need to create 2 alleles identical except for background.

Usually to do this, I duplicate and allele and change the name to x-temp, then once duplicated with the new background, I revert the name. This usually works. However, here when I try to edit the name  back I get an error telling me the allele exists already.

<img width="835" alt="Screenshot 2020-06-04 at 09 28 38" src="https://user-images.githubusercontent.com/7359272/83733922-2ceef200-a646-11ea-8e8f-e5a15afce59c.png">

**Comment by ValWood** [comment]
I could do it if I edited the  name proceeding the allele (here the user had used the "name field" which it seems needs to be unique, so I added the background to this.

But now I am very confused what we use the"name" field for?

<img width="987" alt="Screenshot 2020-06-04 at 09 34 05" src="https://user-images.githubusercontent.com/7359272/83734225-9d960e80-a646-11ea-84f1-cf90d53757c0.png">

**Comment by ValWood** [comment]
ignore. we need to work om the background option though. It's quit complicated to fix things

**Comment by mah11** [comment]
fyi, the better workaround is described in [this comment](https://github.com/pombase/canto/issues/1519#issuecomment-400260464); I just checked and it does still work
