### ISSUE TITLE
Add help text for experimental conditions in PHI-Canto

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2299]
Requested by @CuzickA in https://github.com/PHI-base/phi-eco/issues/10#issue-634722641

> The following text or similar would be useful to add to the conditions selection page
'Please add experimental conditions, conditions are aspects of the experimental setup independent of the genotype of the species under study ie pathogen/host strain or construct. They include any third party species used as a experimental assay system (heterologous species).

This is the text that needs to be customised:

![image](https://user-images.githubusercontent.com/37659591/84126621-0fe76400-aa36-11ea-89b9-1fde6fd1e41f.png)

@kimrutherford This will probably involve adding another configuration property that defaults to the text that's already there. The solution could follow what we did for the custom text on the finish form:

```yaml
curs_config:
  finish_form:
    extra_text_gene_information: >
      <p>
        Examples include:
        <ul>
        <li> protein domain data or other protein sequence features
        <li> missing gene names (synonyms)
        <li> transcriptional regulation (of the wild-type allele - transcriptional changes due to mutations can be captured in Canto)
        <li> complementation data (whether the gene complements a homologue in a different organism or vice versa; complementation may be full, partial or absent)
        <li> gene product name updates
        </ul>
        Most of these annotation types will be handled in future releases of the
        curation tool.
      </p>
```
If you're happy to explain how to add new configuration properties, then I'm happy to handle this myself.

**Comment by jseager7** [comment]
> The solution could follow what we did for the custom text on the finish form:

Although in this case we probably don't need any rich formatting, so the configuration value could just be a plain string in the manner of the help text for annotations:

```yaml
    help_text: >
      A protein modification is a covalent modification or other change that
      alters the measured molecular mass of a peptide or protein amino acid
      residue
```

**Comment by jseager7** [comment]
@CuzickA Would you want the following help text added on each phenotype annotation type? Based on the wording, it seems like it's most relevant for pathogen phenotype and host phenotype annotations.

> Please add experimental conditions, conditions are aspects of the experimental setup independent of the genotype of the species under study i.e. pathogen/host strain or construct. They include any third party species used as a experimental assay system (heterologous species)

 If we want the same text on metagenotype phenotypes, we may want to amend the wording as follows:

> ...conditions are aspects of the experimental setup independent of the **metagenotype containing** the species under study i.e. pathogen/host strain or construct.

Note that experimental conditions don't apply to GO annotations.

**Comment by ValWood** [comment]
Personally I don't think this full text will be required. The part about delivery system, which is the only thing people will need to know up front would get a little lost. I would shorten it to

"Delivery mechanisms, including the use of third party species used for expression of the studied protein  are captured  in conditions" (or similar)

Also, the point of confusion is really during genotype creation, not phenotype curation so it probably needs to be  at the point where people add genes and species.

**Comment by ValWood** [comment]
"Delivery mechanisms, including the use of third party species used for expression of the studied protein  are captured  in conditions, and do not need to be included. here" (or similar)

**Comment by jseager7** [comment]
> Also, the point of confusion is really during genotype creation, not phenotype curation so it probably needs to be at the point where people add genes and species.

I'm a bit confused about this. Do you want the notice shown on the 'Gene and host organism list' page at the start of the session, or when the user is creating genotypes on the Genotype Management page? It sounds like it's more sensible to stop curators adding species just because they were used as delivery mechanisms, so I'm guessing you meant the start?

We might still want to consider some help text near the experimental conditions in case users forget that they _should_ be specifying the delivery mechanism once they get to that point of the curation session. If they're only notified at the start of the session they might forget by the time they get to phenotype annotation.

**Comment by CuzickA** [comment]
My notes say that we decided to
i) add help text to the metagenotype management page as a pop up that 'delivery mechanism will be captured later'
ii) add text to the 'conditions' section about selecting 'delivery mechanism' here. (Will eventually move to its own selectable box under/after conditions).

**Comment by ValWood** [comment]
We did discuss on the metagenotype page  (and it will probably be useful there too), but I think people might try to add the 3rd party species even earlier (they would need to do this to include it in a metagenotype, which  would be the correct thing to do if we interpreted this construct  _sensu stricto_ (it really is the new symbiont + the gene of interest) , but   doing this defeats the object of what the experimenter is trying to achieve ( which is how a particular gene interacts with a host).

**Comment by ValWood** [comment]
Yes, it might be easier to look at options on the next call.

**Comment by CuzickA** [comment]
See also https://github.com/PHI-base/curation/issues/69 and https://docs.google.com/spreadsheets/d/1D39pqcpO5mxr_wVCgYWtVGEujqV3Pq1LJZTug3WF4TI/edit#gid=0

for current delivery mechanism terms

**Comment by CuzickA** [comment]
If we decide to move the 'delivery mechanism' into its own selectable box after the conditions option this will impact my annotation screenshots for the PHI-Canto manuscript and other training materials. I assume there will need to be an additional column of data after the conditions to display the 'delivery mechanism'. 

It would be good to make a final decision about whether we want this new option or whether to leave it under the conditions and just improve the Help prompts.

**Comment by jseager7** [comment]
> It would be good to make a final decision about whether we want this new option or whether to leave it under the conditions and just improve the Help prompts.

I've added this to the agenda for the next meeting.

**Comment by ValWood** [comment]
I think with the help prompts, and because the strings are now easy to find we should probably continue as we are. Another field won't particularly help if the help text is clear. Useful to get feedback from everyone though.

**Comment by CuzickA** [comment]
> I think with the help prompts, and because the strings are now easy to find we should probably continue as we are. Another field won't particularly help if the help text is clear. Useful to get feedback from everyone though.

I agree :-)

**Comment by jseager7** [comment]
Finally remembered that I need to add some text to the _edit genes_ page in PHI-Canto that will remind curators not to add species to the curation session if they are only used as a delivery mechanism. Here's the draft text:

> Note: Do not add species here if their only use is as a delivery mechanism. Information about delivery mechanism should be added later, as an experimental condition.

We agreed to do this in the meeting on 8 February. My plan is to add the note as a separate paragraph under the existing note about NCBI Taxonomy ID re-mapping. Here's how that will look:

![image](https://user-images.githubusercontent.com/37659591/115217046-ffdfec80-a0fc-11eb-938d-89c5f374ad2b.png)

If anyone thinks it would be better to combine the notes into one section (or can think of any better way to present this information), I'm happy to change it.

@ValWood @CuzickA Do you have any comments?

**Comment by CuzickA** [comment]
Looks good to me

**Comment by ValWood** [comment]
and me. If anything is confusing in practice we can tweat later.

**Comment by jseager7** [comment]
Thanks. The text should be visible by tomorrow when the PHI-Canto servers are updated.
