### ISSUE TITLE
move "add background" link above  "annotation" link

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2305]
This small change may encourage people to add backgrounds early.
- I hope this doesn't result in every single background always, but it would be nice to collect more where they are informative about the experiment.
- It'll be helpful not to need to split genotypes later when backgrounds are stuck into the conditions field.
- and it won't do any harm especially now we don't display every different background as a separate genotype.

**Comment by kimrutherford** [comment]
That change is done.
