### ISSUE TITLE
When exporting as JSON, cope with metagenotype ranges in extensions

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2306]
See: https://github.com/pombase/canto/issues/2296#issuecomment-644139226

and: #2307

**Comment by kimrutherford** [comment]
That's implemented now.

It looks like this in the JSON output:
```json
{
  "rangeDisplayName": "pmk1-AS(aaQ104G)[Not assayed] Magnaporthe oryzae / wild type Oryza sativa (Mokoto)",
  "rangeType": "Metagenotype",
  "rangeValue": "0d2bc8d23a8667f4-metagenotype-2",
  "relation": "compared_to_control_genotype"
}
```

I've added a little bit about this to the JSON export documentation:
https://github.com/pombase/canto/wiki/JSON-Export-Format#metagenotypes-section

**Comment by jseager7** [comment]
@kimrutherford When running the export on our production server, I get a load of errors related to the changes introduced by https://github.com/pombase/canto/commit/6b618fd02f81fb13c49388ad7cb208bbbf01018d:
```
Use of uninitialized value in lc at lib/Canto/Curs/Serialise.pm line 286.  # repeated 72 times
Can't call method "organism" on an undefined value at lib/Canto/Curs/Serialise.pm line 177.
```
Here's the code causing the first warning:
```perl
map {
  my $extension_bit = $_;

  if (lc $extension_bit->{rangeType} eq 'metagenotype') {
    my $metagenotype =
      _get_metagenotype_by_id($schema, $extension_bit->{rangeValue});

    $extension_bit->{rangeValue} = $metagenotype->identifier();
  }
} @$extension_part;
```
The second message is caused by the bug in #2316, so we don't need to cover that here.
```perl
my $interacting_taxonid = $interacting_gene->organism()->taxonid();
```

**Comment by kimrutherford** [comment]
Maybe a metagenotype was removed but it was referred to by an extension?  I don't think my code handles that case so I'll fix it.

I've committed some code with extra diagnostics that may help identify the problem.  Could you git pull and try again?

**Comment by jseager7** [comment]
Here's the output from the export with the diagnostics enabled:

[phicanto_export_errors.txt](https://github.com/pombase/canto/files/4864060/phicanto_export_errors.txt)

**Comment by kimrutherford** [comment]
> Here's the output from the export with the diagnostics enabled:

Thanks James.  I think the change I made to add the diagnostics (03316254a053a56417c968ab3ed2e9f7d10ab3bd) will fix the initialised value while exporting:
```js
if (defined $extension_bit->{rangeType}) {
 ...
```

I haven't been able to track down why the rangeType is uninitialised.  It should be one of "Gene", "Metagenotype", "Ontology", or "%".  If the curators have been using the "Edit as text (admin only) ..." option for extensions, that would explain things because unfortunately if you edit as text the type information is lost.

I think we can close this but please reopen if I've missed anything.

> The second message is caused by the bug in #2316,

I'll work on that.

**Comment by jseager7** [comment]
Just to confirm, this has removed the warnings on the production server. Thanks.
