### ISSUE TITLE
overexpression -> elevated?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2311]
I wonder if we should change overexpression label to elevated.

Sometimes people increase the level of some protein by tinkering with the UTR degradation signal or a degron box. This increases the level of the protein above WT but overexpression feels/sounds weird.

**Comment by mah11** [comment]
I don't feel any great need to change, especially when there's hardly any difference in meaning.

**Comment by ValWood** [comment]
OK. I think it  looks a bit  odd if they haven't overexpressed the gene but let's leave it.

**Comment by mah11** [comment]
It's a logical consequence of our decision that the expression setting should reflect the actual amount of product observed.

And anyway, mRNA degradation is part of gene expression ...

**Comment by ValWood** [comment]
yes, I don't know why I temporarily got hung up on this!
