### ISSUE TITLE
Canto issues in China

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2314]
This image makes it seem that the "Chinese problem' is that they get stuck  at  the "continue curation" button, but clicking on the summary returns them to the session.

This bug was reported using 360 browser (whatever that is)?

I will forward the e-mail. If we could eradicate this issue it would be very useful.

**Comment by kimrutherford** [comment]
> This bug was reported using 360 browser

https://en.wikipedia.org/wiki/360_Secure_Browser

I'm not game to install that locally.  I think the network connection between China and Cambridge is more likely to be the problem.

**Comment by ValWood** [comment]
OK, I wondered if the e-mail hinted at some other issue but no worries. Maybe it is a network problem, because some people report that they have trouble and then a session appears. 
But they all report the same issue, that the can access the tool, but not  the session.
