### ISSUE TITLE
Should annotation extensions allow features to be related to themselves?

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2315]
(Follow-on from #2296)

Since https://github.com/pombase/canto/pull/2308 was implemented, I've noticed that it's possible to relate a metagenotype to itself, by means of the 'compared to control genotype' extension – you can select the same metagenotype as the control metagenotype – which isn't necessary or sensible in this case. Ideally, the extension interface shouldn't allow the annotated feature to be selected.

Note that the above problem has MetagenotypeID being used as the extension range, but I suspect the same thing is possible with every extension that uses feature types as the range (GeneID, ProteinID, etc.)

This might be difficult to fix in the general case, but assuming a feature never needs to be related to itself, then we can just exclude the annotated feature from the list of features that can be selected. For example, if an annotation on gene _ABC1_ can be extended with a GeneID, then _ABC1_ would be excluded from the list of genes that can be selected, but if the extension was for a GenotypeID, then no genes would be excluded.

- - -

@ValWood @mah11 Have you come across cases where a gene or genotype has been related to itself through an annotation extension? Can you anticipate any situations where this might be necessary?

For example, considering the extension 'regulates activity of' (GO:1904616 **regulates_activity_of** ProteinID), are there cases where a protein regulates its own activity? Or would a gene and a protein not be considered the same 'feature', logically speaking?

**Comment by ValWood** [comment]
This is different. An extension can relate something to itself.

But for this particular extension, I guess it is remotely possible that you might want to specify a phenotypic change related to 
the same genotype with a different condition.

I would say that four our purposes you can disallow for now  and we can allow later if we find  use cases.

**Comment by jseager7** [comment]
> I would say that for our purposes you can disallow for now and we can allow later if we find use cases.

If there's a chance that it _could_ be necessary to relate a metagenotype to itself (even a remote chance), then it would be less work to leave the option open to select the same metagenotype.

**Comment by ValWood** [comment]
Leave it for now

**Comment by jseager7** [comment]
Okay, I'll close this for now and we can rethink if it proves confusing for curators.
