### ISSUE TITLE
Physical interaction doesn't prevent removal of interacting gene

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2316]
Canto is supposed to prevent genes being removed from the session if they're used in a genotype or an annotation. For physical interactions, this protection only applies to 'Interactor A' of the interaction: you can still delete 'Interactor B', and the list of Physical Interactions will be broken until you add the gene again.

This bug affects both single-species mode (Canto) and pathogen-host mode (PHI-Canto).

### Steps to reproduce

1. Add two new genes to the session (not used in any genotypes or annotations)
2. Create a physical interaction using those two genes
3. Remove the gene that has the role of Interactor B, using the edit_genes page (you can't remove the other one)
4. Go back to the summary page, and the Physical Interaction list will show an error:

![image](https://user-images.githubusercontent.com/37659591/86244857-7c223700-bba0-11ea-98df-32597ffa5ab5.png)

The error page linked from the web console shows this:

> Internal error
Caught exception in Canto::Controller::Curs->ws_list "error: could not find a 'Gene' with args: primary_identifier: SPBC11B10.09 at lib/Canto/Curs/Utils.pm line 494."

The console also shows a 'possibly unhandled rejection' from `angular.js` that just seems to dump a load of HTML into the console.

**Comment by kimrutherford** [comment]
Hi James.  Thanks for finding that bug.  I missed some code when I was restoring the gene-gene interaction code: c39470506dd8e6d7dae65390399455b3162111a0

Could you do a quick test when you get a chance?

**Comment by jseager7** [comment]
I've tested this on my local copy and it works fine now. Thanks.
