### ISSUE TITLE
bug creating alleles in Canto

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2317]
Hi Kim, could you check a possible bug?

Arzu tried creating an allele - Scer\GAl4[tub??] - in Fly-Canto but failed. I managed to reproduce the bug, which gave the following error message:

Internal error
Caught exception in Canto::Controller::Curs->annotate "error: could not find a 'Genotype' with genotype_id = 'undefined' at lib/Canto/Controller/Curs.pm line 1203.”  

However, Both Scer\GAl4[tub??] and wg[test] (I suspect another allele created by Arzu in the session) show up on the JSON upon export!

Please compare session b5b3190123b27c31 on the json attached vs on canto (https://curation.pombase.org/flybase/curs/b5b3190123b27c31).

It happen a couple other of times with me - for Scer\GAL4 alleles but not always - so ti is not consistent and I cannot really say what is the issue.

[canto-flybase-export-20-06-11.json.zip](https://github.com/pombase/canto/files/4893113/canto-flybase-export-20-06-11.json.zip)

**Comment by kimrutherford** [comment]
Thanks for all the details.  I'll investigate that bug.

**Comment by kimrutherford** [comment]
Hi Vitor.  Could you explain this bit:

> Arzu tried creating an allele - Scer\GAl4[tub??] - in Fly-Canto but failed.

I thought creating alleles was disabled in fly-canto and all the alleles came from the JSON input files?

**Comment by vmt25** [comment]
hmm, it is complicated.
This is related to #2282.

We don't want to create alleles to be a regular features of Fly-Canto but we want to do it to create temporary alleles, so that curators can carry on curating to a mock allele while waiting for some information from authors or other curators.

The way we've been going around this is by going to a gene page, clicking on the 'Single allele Phenotype class' or 'Single allele Phenotype anatomy' and then adding a mock allele name

We use the allele name to add a mock allele symbol (in flies it is the gene symbol, plus a identifier string that is superscripted/between squared brackets, e.g. Pdk2[overexp??]) labelled with a double question marks, which is the warning sign that rings alarm bells when passing through our internal quality control checks.

<img width="802" alt="Screenshot 2020-07-09 at 12 01 56" src="https://user-images.githubusercontent.com/33721108/87032636-d47ab980-c1dc-11ea-96fe-b1f9685b6840.png">


<img width="855" alt="Screenshot 2020-07-09 at 12 08 53" src="https://user-images.githubusercontent.com/33721108/87032776-0429c180-c1dd-11ea-853a-c557d4139243.png">


It is not the cleanest of ways, hence the original request of #2282, but it has been working and fits the purpose of the ticket.

**Comment by vmt25** [comment]
Oh, and here it is on the single allele genotype table

<img width="627" alt="Screenshot 2020-07-09 at 12 13 10" src="https://user-images.githubusercontent.com/33721108/87033162-a2b62280-c1dd-11ea-8595-49b014ce4ccf.png">

**Comment by kimrutherford** [comment]
Hi Vitor.

I'm still working on the bug.  I think it's happening when Canto attempts to start making an annotation for the new genotype you're creating.

I'm wondering why you are making the temporary alleles this way.  Wouldn't it be easier to use the allele creation table like PomBase does?:

![genotype-genes-1](https://user-images.githubusercontent.com/90474/87161453-a9958000-c318-11ea-95f8-8871f5023e06.png)

If I remember, we turned off that table because you thought it wouldn't be useful.  But maybe it is after all?

**Comment by vmt25** [comment]
> I'm wondering why you are making the temporary alleles this way.

Because it seems to be one of the only two possible ways in Fly-Canto, the other being copy/edit genotypes.


> Wouldn't it be easier to use the allele creation table like PomBase does?:
> If I remember, we turned off that table because you thought it wouldn't be useful.

Initially, the allele creation table seemed like an open invitation to create genotypes, which is not what we wanted and the reason why we asked for it to be disabled.
We only want this to create temporary alleles (clearly marked as such) for the occasional missing/unclear allele.


>  But maybe it is after all?

Maybe, but can it be without the 'deletion' button? And add double question marks by default?

**Comment by vmt25** [comment]
> Maybe, but can it be without the 'deletion' button? And add double question marks by default?

And maybe an extra button at the bottom of the gene list for the creation of aberrations?

**Comment by kimrutherford** [comment]
Hi Vitor.  I think I've fixed this.  Sorry for the delay.

I think the problem was that from that page Canto was trying to create non-melanogaster genotypes.  In the session I was testing, it was trying and failing to create a cerevisiae genotype because the allele was from cerevisiae.  But cerevisiae isn't in the database so it failed.

Please let me know if that's fixed for you.

**Comment by vmt25** [comment]
Thanks for fixing it.

> I think the problem was that from that page Canto was trying to create non-melanogaster genotypes. In the session I was testing, it was trying and failing to create a cerevisiae genotype because the allele was from cerevisiae. But cerevisiae isn't in the database so it failed.

That sounds right. Every now and then we want to create a temporary allele for a gene not associated with the publication and using our strategy would mean picking any gene to create an allele. At the moment this does not create problems down the line because the allele symbol will be fixed eventually to match an existing allele of an existing gene, so no problems.

Anyways, as you suggested, we should discuss bringing back the allele creation table...

**Comment by vmt25** [comment]
Hi Kim, in accordance with today's chat, I (re-)enabled the allele creation table and it also allows building on previously generated complex genotypes.

It would be good if you could make the 'Deletion' column optional.

**Comment by kimrutherford** [comment]
> It would be good if you could make the 'Deletion' column optional.

I've added a new option to do this.  If you add this to your canto_deploy.yaml, the Deletion buttons will be hidden:

```
show_quick_deletion_buttons: 0
```

I've added that to the configuration for that main FlyCanto instance.

**Comment by vmt25** [comment]
Perfect, thanks.

**Comment by vmt25** [comment]
Oh, could you please change the value of 'show_genotype_management_genes_list' to '1' on https://github.com/pombase/pombase-config/blob/master/canto/flybase/canto_deploy.yaml?

**Comment by kimrutherford** [comment]
> Oh, could you please change the value of 'show_genotype_management_genes_list' to '1'

Done!

**Comment by vmt25** [comment]
Cool. Thanks!
