### ISSUE TITLE
curator details required in Fly-Canto's export json

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2319]
This week's export json (created today) does not show the “curator_email” and “curator_name” lines but the “curator_name” line is absolutely required to convert the json data into FlyBase's flat file/proformae format, so that curation is appropriately attributed to the curator.

I am assuming this is due to #2261. However, #2261's changes were committed 14 days ago but last week's export json (created on Wednesday, the 8th) was fine, showing the “curator_email” and “curator_name” lines, so I assume the 'bug' happened in the last 8 days.

**Comment by kimrutherford** [comment]
Hi Vitor.

Sorry about that!  I forgot to update the export script with the `--export-curator-names` option mentioned in #2261

I've re-exported with names:
https://curation.pombase.org/flybase-canto-json-exports/canto-flybase-export-2020-07-15-with-names.json

I've fixed the script for next week.

As mentioned in #2261 the email addresses are no longer exported.  If you need them we can add them back to the JSON file.

**Comment by vmt25** [comment]
Hi Kim!
It seems fixed, huge thanks for the fix and for the json.

**Comment by vmt25** [comment]
> Hi Kim!
> It seems fixed, huge thanks for the fix and for the json.

**Comment by vmt25** [comment]
Oh, email addresses are not necessary for the conversion.

**Comment by kimrutherford** [comment]
I think this can be closed now.  Please let me know if not.

**Comment by vmt25** [comment]
Think so. So far so good but will check this week's export and will reopen if any issue arises.
