### ISSUE TITLE
Capture figure number as a separate data field

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2320]
PHI-base have decided it would be useful to have figure numbers curated separately from the annotation comments. This will need a new field to be added to the annotation creation process, and possibly a new column to the annotation tables.

@ValWood @CuzickA We'll need to discuss which step of the annotation creation workflow should capture the figure number. Maybe on the same page as the comments?

Also, if anybody's not keen on having another column shown in the table, we could just include the figure information in the comments column (as we do now on an informal basis), but always have it shown at the start of the cell, possibly with unique styling. Here's an example:

![image](https://user-images.githubusercontent.com/37659591/87933912-06660880-ca86-11ea-9efd-69a528dfdc5b.png)

Note that a secondary advantage of including figure numbers is to enable sorting by figure, as discussed here: https://github.com/pombase/canto/issues/2310#issuecomment-660929450

**Comment by kimrutherford** [comment]
> PHI-base have decided it would be useful to have figure numbers curated separately from the annotation comments.

I've added the Figure field.  James, could you have a quick test when you get a chance?  No database upgrade is needed.

**Comment by kimrutherford** [comment]
I forgot to say, this isn't available for PomBase yet.  I'll sort that out tomorrow.

**Comment by jseager7** [comment]
Thanks for the quick turnaround. I'll test this as soon as I can.

> No database upgrade is needed.

Can you remind me why this is? Is it because additional annotation data is stored as YAML in the database?

**Comment by ValWood** [comment]
does that also include in the "duplicate and edit" window?

**Comment by kimrutherford** [comment]
> Can you remind me why this is? Is it because additional annotation data is stored as YAML in the database?

Yep, there's a "data" column in the annotation table for storing miscellaneous proprieties.  It's YAML.

**Comment by kimrutherford** [comment]
> does that also include in the "duplicate and edit" window?

Yep!

**Comment by kimrutherford** [comment]
> I forgot to say, this isn't available for PomBase yet. I'll sort that out tomorrow.

I've add a Figure column to the main pombase server too now.  And also the test server in case you'd like to try it first.

**Comment by jseager7** [comment]
@kimrutherford There doesn't seem to be any way to add the figure number when first creating the annotation in the 'standard' annotation workflow (e.g. the workflow that starts from the annotation tables and genotype management pages). The Figure field only seems to exist in the modal that's used for Quick Add, Edit, and Copy and edit.

**Comment by kimrutherford** [comment]
Good point.  We should probably add a new input field for Figure on the last/confirmation page (where it says 'You have made the following annotation: ") and also change this text:

> Additional information (optional): you can supply figure or table numbers, or provide any details you have for this annotation that do not fit into the available evidence, extension options, etc.

**Comment by ValWood** [comment]
Also requires some text prompt  to make it clear that people would need to enter "figure 1" or "table 1" etc explicitly, if they enter only a number it's ambiguous, and its not completely clear that this includes tables too.

**Comment by ValWood** [comment]
This would also affect table sorting on this field (ie. people might type fig or figure inconsistently which would split the number sorting)

**Comment by jseager7** [comment]
@ValWood If we include 'Figure' or 'Table' as a prefix, how would you want the results to be sorted? Should we go with default lexicographical ordering, like this:

Figure 1
Figure 2
Figure 3
Table 1
Table 2
...

or should we preserve the numeric ordering and ignore the prefix?

Figure 1
Table 1
Figure 2
Table 2
Figure 3
Figure 4
...

**Comment by jseager7** [comment]
> This would also affect table sorting on this field (ie. people might type fig or figure inconsistently which would split the number sorting)

If there's generally a convention on figure naming, we could make the figure input more controlled. For example, users would first select 'Figure' or 'Table' from a drop-down (defaulting to 'Figure'), then the text input would be restricted to one or more digits, optionally followed by one alphabetical character.

The above assumes that you won't find figure numbering schemes that are alphabetical (e.g. Figure A, Figure B, etc.) or using roman numerals (Figure i, Figure ii, etc). Not sure if that's a safe assumption.

Alternatively, we could just check the input text and remove anything that's a prefix of 'Figure' or Table', so if the user types 'Fig. 1', that gets converted to '1'. Similarly, we could try to detect if the user has abbreviated 'Figure' or 'Table' and expand them back to their standard spellings.

**Comment by ValWood** [comment]
Actually, I think we should probably not include this feature for pombase, but continue to use the comments field. 

It takes up a bit of space in the copy edit menu, and although  it would be nice the extra clicking won't really make it worthwhile for us.

Kim will this be a pain to revert? I have already used in a couple of sessions, but community curators may also have used it. If you can 'disable'  and give me a list of sessions used in I can fix today.

**Comment by kimrutherford** [comment]
> Actually, I think we should probably not include this feature for pombase, but continue to use the comments field.

OK, I'll add a configuration option so we can disable it for PomBase.

> the extra clicking won't really make it worthwhile for us.

There's no need to click as you can tab to go to the next field and shift-tab to go to previous field.  You can tab to the Cancel and OK buttons too.  Unfortunately you have to click in a field first before tab works but that can probably be fixed.

**Comment by kimrutherford** [comment]
> Good point.  We should probably add a new input field for Figure on the last/confirmation page

Note to self: when this is implemented I need to pay attention to the `annotation_figure_field` config - if false don't show the figure input field.

**Comment by kimrutherford** [comment]
> OK, I'll add a configuration option so we can disable it for PomBase.

That's done now.  It's disable for PomBase.

> I have already used in a couple of sessions, but community curators may also have used it.

Only two sessions I can see:
  - https://curation.pombase.org/pombe/curs/734a10ae784c8c6b/ro/
  - https://curation.pombase.org/pombe/curs/b015a7efb76f7cb7

Once you've changed those I'll double check that they're all gone.

**Comment by kimrutherford** [comment]
Hi Vitor.

Would it be useful for you to have a separate field in each annotation for Figure (or table)?  Currently it's disabled for your server but it's just a configuration option if you'd like it enabled.

![fig-eg-1](https://user-images.githubusercontent.com/90474/88272518-f0c63c80-cd2c-11ea-8eae-a41bbdbf285b.png)

![fig-eg-2](https://user-images.githubusercontent.com/90474/88272523-f4f25a00-cd2c-11ea-8fdc-6e3a4d54a563.png)


@vmt25

**Comment by vmt25** [comment]
Hi Kim,
No, not really. We only use that kind of information to keep track of curation and we can put it in the comments field (which we do not capture/import).

**Comment by CuzickA** [comment]
Also just to add to @jseager7 comments above about using 'Figure' or 'Table' we need to be able to record the Supplementary Figure/Tables. These names can vary eg Extended Data Fig 3d, S4 Fig, S2 Table

**Comment by kimrutherford** [comment]
Hi Alayne.

Currently there are no constraints on the contents of the Figure field so your examples would be no problem.

**Comment by CuzickA** [comment]
Hi Kim, 
Thanks, that's good to know.

**Comment by jseager7** [comment]
> we need to be able to record the Supplementary Figure/Tables. These names can vary eg Extended Data Fig 3d, S4 Fig, S2 Table

If the figure numbers are that variable, then I don't think we should validate them. Fortunately, all those examples still sort correctly with the default sorting logic, providing they have consistent prefixes.

**Comment by ValWood** [comment]
just noting Extended data is *really*  = SUPP data so reporting as

S3d etc is fine (this  is what I do ).

**Comment by kimrutherford** [comment]
Is there anything more to do here?

**Comment by jseager7** [comment]
@kimrutherford I think we still need a Figure field added to the standard (step-based) annotation workflow, see my previous comment [here](https://github.com/pombase/canto/issues/2320#issuecomment-661735072) and your note to self [here](https://github.com/pombase/canto/issues/2320#issuecomment-662906404).

**Comment by kimrutherford** [comment]
Thanks for the reminder James.  I'll implement that before I close the issue.

**Comment by kimrutherford** [comment]
> There doesn't seem to be any way to add the figure number when first creating the annotation in the 'standard' annotation workflow 

That's implemented now, although we need to change the wording above the comment box a bit when the "Figure or table" field is visible.  Any suggestions?  Would removing this bit be enough?: "you can supply figure or table numbers, or "

Here's how it currently looks:

![screen10](https://user-images.githubusercontent.com/90474/91019420-0e950300-e645-11ea-84dc-7bfb9ca79f27.png)

**Comment by jseager7** [comment]
> Would removing this bit be enough?: "you can supply figure or table numbers, or "

That sounds fine to me.

Note that we might also need some help text around the 'Figure or table' field to describe the format we expect for the data &ndash; see https://github.com/pombase/canto/issues/2320#issuecomment-662363488 &ndash; but that can afford to wait until we have community curators, and we can put it in a separate issue.

**Comment by kimrutherford** [comment]
> That sounds fine to me.

I've made that change.  We can tweak it later as needed.

> Note that we might also need some help text around the 'Figure or table' field to describe the format we expect for the data

That makes sense.

**Comment by jseager7** [comment]
Here's some draft text for the Figure field, which is shown during the step-based ontology annotation workflow. I've also added a placeholder to illustrate the expected format.

![image](https://user-images.githubusercontent.com/37659591/92385682-363a9f80-f10a-11ea-9db3-d110c94f7d62.png)

@CuzickA Are you happy with this text?

- - -

Note that neither the message nor the placeholder are shown in the modal-based workflow (e.g. when editing an annotation). I can fix the placeholder easily, but I'm less sure what to do about the explanatory text. I could just follow the example of the experimental conditions field and put some text above the input:

![image](https://user-images.githubusercontent.com/37659591/92386067-f45e2900-f10a-11ea-8898-99f87f8a7dc1.png)

**Comment by jseager7** [comment]
> Note that neither the message nor the placeholder are shown in the modal-based workflow (e.g. when editing an annotation).

This is now ready in pull request #2347. I decided to follow the existing convention for the help text, as described in my comment above.

**Comment by kimrutherford** [comment]
Thanks James.  Is there anything more to do on this issue?

**Comment by jseager7** [comment]
Not as far as I can see. Closing now.

**Comment by ValWood** [comment]
Re:

>OK, I'll add a configuration option so we can disable it for PomBase.
That's done now. It's disabled for PomBase.
I have already used in a couple of sessions, but community curators may also have used it.
Only two sessions I can see:
https://curation.pombase.org/pombe/curs/734a10ae784c8c6b/ro/
https://curation.pombase.org/pombe/curs/b015a7efb76f7cb7
Once you've changed those I'll double check that they're all gone.

I fixed these 2 sessions. Are there any more?

@kimrutherford

**Comment by kimrutherford** [comment]
> I fixed these 2 sessions. Are there any more?

There are quite a few sessions.  Why do they need to be changed?

https://curation.pombase.org/pombe/curs/acd1a2d2ddcf29cc/ro
https://curation.pombase.org/pombe/curs/8ca59104c61e0b02/ro
https://curation.pombase.org/pombe/curs/f54275f3a8758cf5/ro
https://curation.pombase.org/pombe/curs/95ec493fb8fa90cf/ro
https://curation.pombase.org/pombe/curs/734a10ae784c8c6b/ro
https://curation.pombase.org/pombe/curs/b015a7efb76f7cb7/ro
https://curation.pombase.org/pombe/curs/53e0b793e37b4408/ro
https://curation.pombase.org/pombe/curs/21d843433d804639/ro

**Comment by ValWood** [comment]
I need to move the "figure" column data to the beginning of the "comment column" since we decided not to use it...

**Comment by kimrutherford** [comment]
> I need to move the "figure" column data to the beginning of the "comment column" since we decided not to use it...

It won't hurt to leave old sessions with data in the figure column.  The figure field is hidden now so you can't add more but Canto will happily show the figures you've already added.

**Comment by kimrutherford** [comment]
Val, can we close this?   For PomBase the figure is ignored when loading into the main database so if it's still in a few sessions it's not going to cause problems.

**Comment by ValWood** [comment]
yep.
