### ISSUE TITLE
Misleading strain curation message

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2321]
I find this message a little misleading:

Note: PHI-Canto does not curate at taxonomic ranks lower than species. If you have entered UniProt identifiers that are at the strain or subspecies level, their corresponding NCBI taxonomy identifiers will have been re-mapped to the nearest species rank (the UniProt identifier itself is not modified). Please use the 'experimental strains' field to specify lower taxonomic ranks (such as strains, pathovars, and subspecies).

because we do curate to the level of strain, but we don't use Uniprot IDs to do so.

I think we should reword this, to make things clearer for  the user. No hurry we can do it quickly on the next call.

**Comment by jseager7** [comment]
@ValWood How about this?

Note: PHI-Canto does not ~curate~ **use UniProt identifiers** at taxonomic ranks lower than species. If you have entered UniProt identifiers that are at the strain or subspecies level, their corresponding NCBI taxonomy identifiers will have been ~re-mapped~ **reassigned** to the nearest ~species rank~ **species-level identifier** (the UniProt identifier itself is not modified). Please use the 'experimental strains' field to specify lower taxonomic ranks (such as strains, pathovars, and subspecies).

**Comment by ValWood** [comment]
Perfect!

**Comment by jseager7** [comment]
This is visible on both PHI-Canto servers now. Closing.
