### ISSUE TITLE
Difficult to remember 'extent of infectivity' options

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2322]
I'm really struggling here because i can't remember what the options are.

The users will have even less of a clue.

<img width="879" alt="Screenshot 2020-07-20 at 15 10 55" src="https://user-images.githubusercontent.com/7359272/87947784-bbef8680-ca9b-11ea-892d-95e73a605cfb.png">

This is only a short list, so we really need to be able to see all of the options.

I thought there was a ticket about this but I can't find it.

This is a blocker for release.

Also where is the list so I can see the options (to continue with this session) ?
I'm sure that is in a ticket somewhere. I'll continue looking but if anyone knows please add a link in this ticket.

**Comment by mah11** [comment]
maybe #2038?

**Comment by jseager7** [comment]
According to our extension config, the terms available for the infective_ability extension, including their children, are:

### Pathogenicity

- pathogenicity phenotype (PHIPO:0000006)
  - unaffected pathogenicity (PHIPO:0000004)
  - pathogenic ability absent (PHIPO:0000007)
    - loss of pathogenicity (PHIPO:0000010)
  - pathogenic ability present (PHIPO:0000008)
    - virulence phenotype (PHIPO:0000011)
      - unaffected virulence (PHIPO:0000012)
      - increased virulence (PHIPO:0000014)
        - gain of pathogenicity (PHIPO:0000009)
          - loss of virulence of gain of pathogenicity mutant (PHIPO:0000965)
      - reduced virulence (PHIPO:0000015)
        - loss of virulence (PHIPO:0000964)
          - loss of virulence of gain of pathogenicity mutant (PHIPO:0000965)

### Mutualism

- mutualism phenotype (PHIPO:0000038)
  - normal mutualism (PHIPO:0000039)
    - mutualism present (PHIPO:0000035)
    - mutualism absent (PHIPO:0000948)
  - abnormal mutualism (PHIPO:0000040)
    - loss of mutualism (PHIPO:0000207)

### Host resistance

- host resistance to pathogen phenotype (PHIPO:0001183)
  - host resistance present (PHIPO:0001186)
    - gain of host resistance (PHIPO:0001185)
  - host resistance absent (PHIPO:0001187)
    - loss of host resistance (PHIPO:0001184)

**Comment by ValWood** [comment]
Yes thanks both. After my initial post vacation confusion it is not so bad. I'm still struggling m  with when I need to capture virulence but that is a question in the curation tracker ticket.

**Comment by jseager7** [comment]
> This is only a short list, so we really need to be able to see all of the options. I thought there was a ticket about this but I can't find it.

My best guess is that the amount of terms available for the infective ability extension has already exceeded the limit that Canto uses to choose whether or not to display all the terms on click. @kimrutherford can you confirm?

**Comment by ValWood** [comment]
I think it's OK.

Perhaps the prompt text could be better though.
It could perhaps be more 'direct'

begin with "pathogenicity phenotype" "mutualism phenotype" or "host resistance phenotype"
since these are the  3 mutually exclusive branches.

This would not  leave the user feeling that  they ever need to guess for something that is not in the examples?

(or som,e other way to indicate that the prompts cover all the options)

**Comment by ValWood** [comment]
OK the suggestions did help. I typed pathogenicity and  found what I needed, so I presume you can find everything with one of these 2 terms. That could perhaps be clearer.

Also the term "virulence phenotype"
is a descendant of "pathognicity present"

(I typed this message before the previous one but in a different browser window)

**Comment by jseager7** [comment]
> Perhaps the prompt text could be better though.
It could perhaps be more 'direct'
begin with "pathogenicity phenotype" "mutualism phenotype" or "host resistance phenotype"
since these are the 3 mutually exclusive branches.

I think that message is automatically generated by Canto. From what I understand from the code, Canto selects the first few terms that appear in the ontology (in source order), and displays them as examples. So, the examples can't be customised on a per-extension basis.

I think the only way to solve this is to add another column to the extension configuration file where examples can be listed, and then Canto will display them in the pop-up.

On this topic, I think it would be better to show the example text outside of the input, since the input placeholder text tends to overflow the input for some extensions (which is obvious from the example above). Then we can change the placeholder to simply read 'Type a term name or term ID'. Here's a mockup:

![image](https://user-images.githubusercontent.com/37659591/88033803-b2b3f780-cb37-11ea-8f58-9dbeda073335.png)

**Comment by ValWood** [comment]
This works.

Start typing either 'pathogenicity phenotype','mutualism phenotype' or 'host resistance phenotype'
Would makes it clearer that they need one of these (if the user sees in the drop down  (or knows) the precise term, they can over-ride these instructions.

@CuzickA  should we shorten "host resistance to pathogen phenotype' to 'host resistance phenotype'?

**Comment by kimrutherford** [comment]
> @kimrutherford can you confirm exactly how many terms can be in an extension range before Canto stops showing the list automatically?

The maximum number of terms in a list is set to `max_term_name_select_count` from `canto.yaml`, which is currently 20.

Just noticed that I got the logic wrong and the maximum term count was `max_term_name_select_count`-1.  I've fixed it.

**Comment by CuzickA** [comment]
> @CuzickA should we shorten "host resistance to pathogen phenotype' to 'host resistance phenotype'?

This longer label was created so as not to confuse 'host resistance' with 'host resistance to chemical' which may be used in the future.

**Comment by CuzickA** [comment]
> begin with "pathogenicity phenotype" "mutualism phenotype" or "host resistance phenotype"

Just to note that @jseager7 and I recently put these grouping terms into a subset that was not displayed in this menu. We did this because the list was flat so they did not provide informative hierarchy information and we didn't want these grouping terms to be selected by the curator.

**Comment by ValWood** [comment]
> This longer label was created so as not to confuse 'host resistance' with 'host resistance to chemical' which may be used in the future.

OK

**Comment by ValWood** [comment]
>Just to note that @jseager7 and I recently put these grouping terms into a subset that was not displayed in this menu. We did this because the list was flat so they did not provide informative hierarchy information and we didn't want these grouping terms to be selected by the curator.

I'm not sure what you mean here ;)

That is true they should not be used, but they are a good starting point for drilling down, no?

**Comment by CuzickA** [comment]
https://github.com/PHI-base/phipo/issues/254
In this ticket we thought that the flat list of all terms was not so helpful so we moved the grouping terms from view. This is how it used to display before the changes
![image](https://user-images.githubusercontent.com/11753634/88404421-c5dbf700-cdc5-11ea-81da-1efb97ae2f95.png)

I do agree with the above comments on needing to give people a starting point or the list and definitions of the available terms. Without this information it will be really difficult to get started here.

**Comment by jseager7** [comment]
It seems this issue has somehow fixed itself, since all the terms in the extension range now show automatically when you select the extension (or at least when you click the input box). Perhaps the number of terms in the extension has dropped below the threshold where Canto shows the terms automatically.

I'll close this issue for now, since having the terms visible solves the usability problem. Feel free to re-open if the problem returns.
