### ISSUE TITLE
new allele type "fusion"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2323]
We need a new allele type for fusion alleles 

(We also need to decide the syntax)

I really thought we had a ticket for this, but I can't find anything...

**Comment by ValWood** [comment]
for a kinetochore fusion (mutant) I just did

TetR-spc7(1-666)-9TE. with  a note: "kinetochore fusion"

Notes/thoughts

- 1. Usually I would put the gene of interest  (study) first  (if it is a gene chimera) , but here is is  clearly not TetR
- 2. Convention seems to be  to arrange in the order which would scupper (1.), we would need a way to identify the gene of interest/study (especially since the phenotypes are not really of interest if the intention was just to localize something somewhere...
-3. Maybe the formal description could be the complete  construct  but the name 
could 

x localized y
e.g. 
x localized spc7(1-666)-9TE 


We also need to look what we already have.
It might be nice to do this soon, because it's one of those jobs that is more work to fix, the longer we leave it...

**Comment by kimrutherford** [comment]
> I really thought we had a ticket for this, but I can't find anything...

There's this one: https://github.com/pombase/curation/issues/652

**Comment by ValWood** [comment]
From
https://github.com/pombase/curation/issues/652
I've punted on the tiny number (two or three?) of occasions when I've curated
fusion proteins -- I've arbitrarily selected one of the genes and entered the
fusion protein details as an "other"-type allele of that gene. If there's more
of one protein present in the fusion, I'd use that one, but otherwise (if all
of both proteins present, or roughly the same proportion of each) the choice is
really truly arbitrary.

This approach is deeply unsatisfying, because it doesn't link the fusion
description to both genes. But we don't have a better approach in Canto, even
with the multi-allele genotype system; there are some alternative options that
are differently bad rather than better or worse overall. For example, we could
put the same fusion description in for both genes, which would capture links to
both genes but would give the misleading impression that there are two
constructs rather than one. A fusion isn't exactly the same as the more typical
"double mutant" scenario to which Canto is now well suited. For those, you'd
have one allele of gene a and a different allele of gene b. A fusion, in
contrast, is a single construct, so not multiple alleles, but one allele that
affects two genes. We haven't modeled that.


and
There are still only a small number of these (20-30) , and it might be a long job for Kim, so we will revisit this after gene pages.

For now,
i) always add either "fusion" or "chimera" to the description, so we can find them easily. Use "chimera" if a part of one protein is replaced by another, or a fragment of one protein is added to another, use fusion if full length gene B is fused to gene A.
ii) Treat the fusion or chimera as an allele of the gene studied. For example, if gene-A is fused to gene-B in order to move it to the cellular location of gene B, it would be an allele of gene A.

**Comment by ValWood** [comment]
First task for @kimrutherford  extract all allels of type "other" with "chimaera" or "fusion" in the label
Or maybe there is already a log file you can point me too with all the odd bods?

From here I will try to  scope out something for discussion.

**Comment by mah11** [comment]
> Or maybe there is already a log file ...

There is already a log file. log.[timestamp].alleles_of_type_other

**Comment by ValWood** [comment]
holy crap (740 rows)

**Comment by ValWood** [comment]
I  *think* this is most of the fusions, enough to define a scheme anyway...


[fusion1.txt](https://github.com/pombase/canto/files/4953759/fusion1.txt)
[fusion2.txt](https://github.com/pombase/canto/files/4953761/fusion2.txt)
[fusion3.txt](https://github.com/pombase/canto/files/4953763/fusion3.txt)
[fusion4.txt](https://github.com/pombase/canto/files/4953764/fusion4.txt)
[fusion5.txt](https://github.com/pombase/canto/files/4953766/fusion5.txt)

**Comment by ValWood** [comment]
Questions

1  What is the default assumption for chimeras and fusions  Re WT present or deleted?
Is it the same of different?

I have been assuming deleted  for both parts of a fusion,  otherwise the ectopic localization would be obscured, similar to an amino acid change, but I might need to add this explicitly. For chimeras I would need to check.

- Problem explicitly adding the deletion part is that a construct for " localization of A to B"  (Where A is the gene of interest)
B would be treated as part of a multi-gene allele including A, (and although is likely to have an effect it is not a  phenotype of B of  great interest to people looking at phenotypes of gene B, because it's artificial)
Perhaps this needs a completely different 'type'


1. We could have 2 separate 'types'  of constuct

- a) Chimeras of endogenous fission yeast proteins  (i.e both proteins are partial, for domain swaps etc)

- b) Fusions   (where the  protein fused to  is  ALWAYS full-length, (the protein of interest may be complete or mutated, this  will  vary in different experiments, as people often  ectopically localize the WT control and then the mutants)
- Could also be used for fusion of protein of interest to Tet or NLS (these are all similar in the way that something is added to the protein of interest in order to localize it to B)

 What are the  reasons to  make a fusion  of this type?
i) ectopic localization of X  to Y
ii)  Any others....?

 We could call this  type something like 
"ectoptic localization'   
Description  X ectopically  localized to Y 
Formal   X-Y fusion , Y-X fusion, X(allele)-Y fusion etc (could be represented in the construct order N-C)
But have it modelled in such a way that it did not spawn a multi allele genotype (depending on 1 above)

Another potential problem if you are just fusing 2 proteins that are mutually dependent for localization
(I haven't come across this in the kinetochore work), usually  a  protein which is constitutively localized to the spindle or kinetochore will be selected  to  localize a protein that is not constitutively localized)
