### ISSUE TITLE
Can't access organism page in review mode

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2325]
I've noticed that in PHI-Canto, once a session has been submitted (which changes the session to review mode), it's no longer possible to access the page where you would normally edit genes, organisms, and strains. This means you have no way to review all the strains and wild-type hosts added to the session.

Specifically, it's the link highlighted below that gets hidden:

![image](https://user-images.githubusercontent.com/37659591/88175210-74910380-cc1d-11ea-88d0-0d754739dcdc.png)

Rather than hiding the link, I think it would be better to keep the page accessible, but disable all the edit actions (e.g. adding and deleting strains).

It seems this problem also applies to PomBase's version of Canto, where it's not possible to access the gene list page in review mode. However, it's less awkward to hide the page in PomBase's case, because PomBase doesn't use strains, meaning there's always a way to see all the information on the page in other places (specifically the detail pages for each gene).

- - -

@ValWood @CuzickA Have you ever had problems with the fact that the organism editing page is hidden in review mode? Maybe this is a non-issue since the link is still visible when approving the session – it's only hidden from non-admin curators that are visiting a submitted session. Also, any strains or wild-type hosts that have been used in genotypes or metagenotypes are still visible from the summary page, so the only thing that's hidden is the unused data.

**Comment by ValWood** [comment]
I had not noticed so defer to @CuzickA

**Comment by CuzickA** [comment]
Yes I agree with you @jseager7 
To view the information I reactivate the session and then resubmit once I've finished.

**Comment by jseager7** [comment]
Okay, I'll try to fix this. It's possible that the reason the page is hidden is because it doesn't support read-only mode yet, so the fix might not be as simple as just keeping the link visible. I'll investigate further.

**Comment by jseager7** [comment]
I just tried to access the Gene and Host Organism List page in read-only mode by appending 'ro' to the URL. Unfortunately, I got a 'page not found' error message:

> Page not found: curs/c7313b53a1533f0c/edit_genes/ro

@kimrutherford It looks like the subroutine in Curs.pm for edit_genes is different from other pages that do support read-only mode with 'ro', like genotype_manage:

```pl
sub edit_genes : Chained('top') Args(0) Form
```
```pl
sub genotype_manage : Chained('top')
```
Is the `Args(0)` method attribute causing the edit_genes page to ignore any extra arguments at the end of the URL?

**Comment by kimrutherford** [comment]
Hi James.

The edit_genes page is quite complicated so it's going to be a bit of work to disable all the edit functions in read-only mode.  Do you think we could so the strains on the front page in read-only mode instead?  It might work to include them in this table:
![read-only-strains-1](https://user-images.githubusercontent.com/90474/98296292-93be7000-2017-11eb-8b8a-2d0907726f10.png)

**Comment by jseager7** [comment]
That's an option, since the summary page already shows hosts without any genes. Showing strain names here could get more awkward if we have to display strain synonyms and/or abbreviations. It's also a bit incongruous when the section (as I understand it) is meant to be for links to gene annotations; strains aren't valid features for annotation. We'd obviously have to change the section heading to 'Genes and strains from this publication'.

Also, I think the summary page is a bit crowded already, especially when the Quick links section is shown:

![image](https://user-images.githubusercontent.com/37659591/98538512-c5873f00-2282-11eb-92b9-d1e6007b1910.png)

Having said that, if the Quick links are disabled in read-only mode, then the lack of space is less of an issue.

Another dilemma I have with including strains on the summary page is that it might seem arbitrary to users to only have the strains shown on this page in read-only mode: surely it would be useful to have an overview of strains in the same place regardless of mode? If the edit_genes page supported read-only mode, then we'd have a consistent place.

I don't mind taking care of the hard work of making the edit_genes page compatible with read-only mode, assuming it's not going to be a lot of work for you to configure the routing on the back-end to provide the read-only flag that I'd need.

**Comment by kimrutherford** [comment]
> I don't mind taking care of the hard work of making the edit_genes page compatible with read-only mode, assuming it's not going to be a lot of work for you to configure the routing on the back-end to provide the read-only flag that I'd need.

I'll make a new route on the Perl side for this.  I think '/edit_genes/ro' doesn't make sense in this case.  We should have something like '/view_genes_and_strains/' but shorter.

**Comment by kimrutherford** [comment]
> I'll make a new route on the Perl side for this. I think '/edit_genes/ro' doesn't make sense in this case. We should have something like '/view_genes_and_strains/' but shorter.

I've implemented that on a branch and created a pull request (https://github.com/pombase/canto/pull/2364).  Using that branch you can go to .../view_genes_and_strains/

At the same time I removed a bunch of old, unused code from the gene_list_edit.mhtml template and moved a bunch of Perl into the controller, where it should have been in the first place.  It's now much smaller.

I've made a simple template for the new read-only gene and strains view: https://github.com/pombase/canto/blob/view-genes-and-strains/root/curs/view_genes_and_strains.mhtml
It currently just renders the genes and strains using the edit-organisms component like the edit_genes does.  I don't know if you are thinking of using that as a starting point.  I added it to test that everything was working.

The pull request is a draft because I'm still testing and tweaking.

**Comment by jseager7** [comment]
> something like '/view_genes_and_strains/' but shorter.

Maybe 'organism_manage', in reference to the Genotype Management page? The organisms (or species, not sure which is more accurate) seem to be the key feature on the page, because strains are of an organism / species, and an organism can exist without genes, but not the other way around.

**Comment by jseager7** [comment]
Forgot to close this issue, it was finished months ago.
