### ISSUE TITLE
Add script option to delete unused strains

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2327]
Before loading the updated strain list, it would help to remove all the old strains that aren't used in any curation sessions. Deleting these unused strains will ensure that only the reviewed strains from PHI-base are initially available for curators.

This could be done by adding a new option to the `canto_admin.pl` script that will delete any strains from the Track database that aren't referenced in any of the Curs databases.

The existing `--rename-strain` option can be used to handle (most of) the rest of the old strains that are already in use.

**Comment by kimrutherford** [comment]
I've added a `--delete-unused-strains` option to the `canto_admin.pl` script.

I've tested locally but I think it's worth testing before trying in production.

**Comment by jseager7** [comment]
@kimrutherford Sorry about the delay on testing this. I've tried the script on my local copy, but got the following error:

```
./canto/script/canto_docker /canto/script/canto_admin.pl --delete-unused-strains
```
`
failed to delete unused strains: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::SQLite::st execute failed: FOREIGN KEY constraint failed [for Statement "DELETE FROM strain WHERE ( strain_id = ? )" with ParamValues: 1=13] at lib/Canto/Track/TrackUtil.pm line 161
`

Assuming strain_id 13 is the root of the problem, the details are here:

### `strain` table

```
SELECT * FROM strain WHERE strain_id = 13;
```
strain_id|organism_id|strain_name|strain_abbreviation
---|---|---|---
13|3|serotype 15 strain HS143|

### `strainsynonym` table

```
SELECT * FROM strainsynonym WHERE strain_id = 13;
```
strainsynonym_id|strain_id|synonym
---|---|---
1|13|HS143

Note that the `strain_abbreviation` column is presumably still around because I tested some old schema upgrade before the column was removed.

### Curs `strain` table

It doesn't seem like the strain is in use in the one session that I have:

strain_id|organism_id|track_strain_id|strain_name
---|---|---|---
1|1|465|
2|2|1293|
5|1||Unknown strain
6|1||custom

**Comment by kimrutherford** [comment]
Thanks for testing James.  I forgot about strain synonyms.  I'll fix that.

**Comment by kimrutherford** [comment]
>  I forgot about strain synonyms. I'll fix that.

That was a quick fix.  Could you try again?  Thanks.

**Comment by jseager7** [comment]
Seems like this works fine on my local copy now, thanks. Closing now, but I'll re-open if there are any problems when I test this on the PHI-Canto servers.
