### ISSUE TITLE
penetrance

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2328]
Do we have any examples of use of "penetrance" extension with multi multi gene genotypes.

we think the types of experiments we are looking at this is probably not required (and might be misleading). Is it  the population fo the  fungus or the plant?

If we have not used it so far, we will remove as an option here (because in the pathogens host context it can be confused with the more common meaning of fungal penetrance of the host)

**Comment by jseager7** [comment]
@ValWood The only example I can find is in PMID:28715477, where there's a metagenotype containing _P. aeruginosa_ phzΔ and wild-type _C. elegans_. The metagenotype is annotated with 'survival of host organism with pathogen' (PHIPO:0001068) with the extension **has_penetrance** 'complete'. The phzΔ genotype has 11 alleles.

While it's also possible to use **has_penetrance** extensions on genotype annotations, it doesn't look like this has been used yet.

**Comment by ValWood** [comment]
Hmm we should look at that.,It sounds a strange term...
@CuzickA

**Comment by CuzickA** [comment]
Thanks for identifying this session. This was one of our earlier curated papers looking at bacteria-worm kill assays.
Here are the metagenotype annotations using 'has_penetrance' and a few comments noting penetrance but not adding it as an AE for some reason!!
![image](https://user-images.githubusercontent.com/11753634/89026084-ef45d700-d31f-11ea-995e-30b0ab89f7a1.png)

**Comment by ValWood** [comment]
It seems as though these terms should be population terms ?

so they would be in/viable population with...
or 
decreased population growth

(penetrance is  only for cell level).
This way we could remove penetracne from multi-species

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/89027447-6ed4a580-d322-11ea-9796-67a3fe7a721f.png)

At the time we created them under 'organism level' as the whole worm was affected. @ValWood do you think we should re-consider this?

**Comment by mah11** [comment]
> (penetrance is only for cell level)

Penetrance is for *organism* level. It is true that it's not applicable to population growth or viability phenotypes for unicellular or multicellular species. So the important things for the "death|survival of host organism within pathogen" terms are

- whether penetrance applies to the host or the pathogen (from the term names host would make more sense to me);
- if it is for the host, whether death or survival is evaluated for each host plant or for a population of host plants; similarly, if it applies to the pathogen, is an individual or a population assayed?

... and, of course, the larger question of whether it's worth capturing penetrance in light of the potential for confusion ;)

**Comment by ValWood** [comment]
> Penetrance is for organism level.
Sorry, so used to single-celled organisms.

I think organism level should. be defined as "individual" organism level though?

In the experiments above  we are looking at  a population of worms. So I a population level term seems more appropriate.

**Comment by mah11** [comment]
> I think organism level should. be defined as "individual" organism level though?

It is.

> In the experiments above we are looking at a population of worms. So I a population level term seems more appropriate.

That's where my question of whether penetrance applies to the host or to the pathogen is relevant.

**Comment by CuzickA** [comment]
The current definition for 'pathogen host interaction organism level phenotype' is 
A pathogen host interaction phenotype that is observed at the level of an individual organism (eg a worm host).

**Comment by ValWood** [comment]
It seems that the penetrance would apply to the  organism you are describing the phenotype of, and not necessarily the one that is  the focus of the variant under study.
I think it will be just too confusing to have penetrance in this branch.

For population viability we can try to  use population terms rather than (organism level + penetrance)

**Comment by CuzickA** [comment]
We don't have population level under the PHI-branch (we made it obsolete). 
We currently have cell level, tissue level and organism level which we were planning to evaluate https://github.com/PHI-base/phipo/issues/179

**Comment by ValWood** [comment]
Yes I remember we thought we would not need it becasue we were unlikely to be looking at populations of plants in this respect. However didn't consider worms... more complications...

**Comment by ValWood** [comment]
I think we can. close this and just open. tickets for configuration as required.
