### ISSUE TITLE
Add admin script option for merging strains

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2329]
Sometimes we have the same strain in the database twice with two different names.  We need a way of merging entries in this case.

@jseager7 should the name we discard be kept as a synonym?

**Comment by jseager7** [comment]
> should the name we discard be kept as a synonym?

I'm not sure it's a good idea to keep them by default: sometimes a strain name needs to be merged because one is incorrect and the other isn't; in other cases, the merged name would be redundant as a synonym because both the primary and the synonym would be matched by the typeahead (e.g. two strain names that differ only in their use of uppercase).

If the script takes two arguments (the strain to be merged and the strain to be merged into), then I think it would be safest to add another argument that controls whether the merged name is added as a synonym or discarded &ndash; but we could probably just default to discarding the strain for now if that's easier.

**Comment by kimrutherford** [comment]
> but we could probably just default to discarding the strain for now if that's easier.

Yep, that's easier.  I'll go ahead and implement this without storing a synonym.

**Comment by kimrutherford** [comment]
I've added a ``--merge-strains`` to do this.  Here is a summary:

```
  ./script/canto_admin.pl --merge-strains taxonid old_name new_name

  Merge strain <old_name> in <taxonid> into <new_name>, <old_name> will be
  removed and all sessions using <old_name> will be changed to use <new_name>
```

Please let me know if it works for you.

**Comment by jseager7** [comment]
I've tested this on my local copy and it seems to work as expected, thanks. Note that the strains I tried merging didn't have synonyms. I can check this too, if needed.

The only improvement I can suggest is be having a more obvious error message when you try to merge a strain that's in use, but it's not high priority.

To illustrate, given the following command, where both CO39 and CO-39 are used in the session:
```
./canto/script/canto_docker /canto/script/canto_admin.pl --merge-strains 4530 CO39 CO-39
```
You get the following error message:

`rename failed: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::SQLite::st execute failed: UNIQUE constraint failed: strain.track_strain_id [for Statement "UPDATE strain SET track_strain_id = ? WHERE ( strain_id = ? )" with ParamValues: 1=238, 2=2] at lib/Canto/Track/TrackUtil.pm line 130`

Which probably isn't very clear if you don't know about the constraint.

**Comment by kimrutherford** [comment]
> To illustrate, given the following command, where both CO39 and CO-39 are used in the session:

Thanks for testing.  I hadn't thought of that case.  We should merge the strains in the session too.  I'll work on that.

**Comment by kimrutherford** [comment]
Hi James.  I've fixed this by changing the code so that the strains in sessions are merged when necessary and to update any genotypes that refer to the "old" strain.

**Comment by jseager7** [comment]
I've tested this and it all works fine, thanks. The script works as expected when merging strains with synonyms as well.

Note that it's not possible to merge custom strains that only exist in the Curs database, but I think it might be better to wait until this feature is needed before doing this. As a workaround, the custom strains can be moved into the Track database first, then merged.

Also note that merging strains can lead to identical genotypes in some cases, but I'd like to think this is rare enough that we don't need to worry about it now.

Closing now, but feel free to re-open if anything else needs implementing.
