### ISSUE TITLE
Bug: cannot transfer phenotype annotations

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2330]
Hi Kim, 

Cannot 'Transfer' phenotype annotations.
A red 'no such evidence code:' error message shows and the annotations is not completed.

The 'Transfer' of genetic interaction annotations works fine.

(working on session 'https://curation.pombase.org/flybase/curs/6771ac528de9eb4d#')

<img width="370" alt="Screen Shot 2020-07-28 at 13 07 09" src="https://user-images.githubusercontent.com/33721108/88666454-fd091b80-d0d7-11ea-8d8c-b888f771e2d5.png">

**Comment by kimrutherford** [comment]
Hi Vitor.

Thanks for reporting that bug.  I saw it while I was implementing interaction transfer but I couldn't reproduce it.  I think I've fixed it now.  I've updated the main fly-canto and the test fly-canto with the fix.

**Comment by vmt25** [comment]
Hi Kim,
All seems good now, thanks. But will keep probing.
