### ISSUE TITLE
Display publication year in publication details

### ISSUE THREAD

**Issue by martin2urban** [pombase/canto#2333]
@kimrutherford: Date to be included in Publication details.   
Note: config item for date to be included to allow display in PHI-Canto. Can be pulled in from Pubmed.
![image](https://user-images.githubusercontent.com/2812591/89157966-4ab4d680-d565-11ea-9af2-4fed0bfe67b9.png)

**Comment by jseager7** [comment]
@kimrutherford Is this going to require schema changes? I can't see anything in `Pub.pm` that references the publication year.

**Comment by kimrutherford** [comment]
> Is this going to require schema changes?

Possibly.  The TrackDB contains all the publication details and the CursDB/session databases only contain the fields that need to be displayed.  It's a bit daft replicating the information in the CursDB.  I think we should just store the PubMed ID in the CursDB and look up the other details from the TrackDB as needed.  I'll have a go at that soon.

**Comment by kimrutherford** [comment]
I've added the publication date to the front page.  We can easily change that to a full citation if it would help.

@ValWood @mah11 we can hide this in pombe Canto if it isn't useful.

**Comment by mah11** [comment]
Don't bother - I don't mind having it visible

**Comment by kimrutherford** [comment]
> Don't bother - I don't mind having it visible

OK, thanks.
