### ISSUE TITLE
Possible bug with filterFeatures function

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2334]
The TypeScript linter is reporting some argument errors: in `annotationTransferDialogCtrl`, there's a function called `filterFeatures` that accepts no arguments. It seems to filter the collection of features in the `$scope`. However, the function is called twice in the controller with one argument, first in `$scope.getGeneFeatures`:

```js
$scope.getGeneFeatures = function() {
  CursGeneList.geneList().then(function (features) {
    $scope.features = features;
    $scope.otherFeatures = filterFeatures(null);
  }).catch(function (err) {
    toaster.pop('note', "couldn't read the gene list from the server");
  });
};
```
And then in the body of `$q.all`, where it seems to be filtering genotypes:

```js
CursGenotypeList.cursGenotypeList({include_allele: 1})
  .then(function (features) {
    $scope.features = features;
    $scope.otherFeatures = filterFeatures(features);
  }).catch(function (err) {
    toaster.pop('note', "couldn't read the genotype list from the server");
  });
```
I'm not sure what the purpose of the argument is, and I think in both cases it doesn't do anything anyway (since `filterFeatures` directly accesses `$scope`), but it might be worth double-checking.

**Comment by kimrutherford** [comment]
> but it might be worth double-checking.

Thanks for spotting that.  I've double-checked and the argument was a hold over from a previous version of the code.  I've committed a fix.
