### ISSUE TITLE
Add sorting buttons to column headers

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2336]
(Sub-issue of https://github.com/pombase/canto/issues/2310)

Sorting annotation tables on the summary page is currently done by clicking the text in the column header. Unfortunately, It isn't very obvious how to sort the columns (or that sorting is even possible) until you mouse-over the column headers.

We could make it more obvious how to sort the tables by adding a visual cue. I'd suggest an icon, which is always visible, that indicates whether the columns are sortable. Clicking the icon would change the sorting mode of the column. The icons could change their appearance depending on the sort order.

Here's an example from Wikipedia:

![image](https://user-images.githubusercontent.com/37659591/89163967-5eb10600-d56e-11ea-87d7-1a605f14a85e.png)

**Comment by kimrutherford** [comment]
> Here's an example from Wikipedia:

I've implement that using the Wikipedia icons, although in Wikipedia tables you can sort in reverse order too.

@jseager7 could you give this a go and close the issue if it looks OK?  Thanks.

**Comment by jseager7** [comment]
The sorting works fine for me. Thanks a lot for your help. I've just made some minor additions and fixes in a pull request at #2340.
