### ISSUE TITLE
fly canto appears to only be reporting Drosophila melanogaster in json output file

### ISSUE THREAD

**Issue by gm119** [pombase/canto#2337]
Hi,
not sure whether this is a bug, or a change in the expected output of the json output (or other !).

In the canto-flybase-export-20-04-17.json file, session 04dba88f98d690ea, the genes section only has the organism info for Drosophila melanogaster genes
```
        "genes" : {
            "Drosophila melanogaster FBgn0004198" : {
               "organism" : "Drosophila melanogaster",
               "uniquename" : "FBgn0004198"
            },
            "Drosophila melanogaster FBgn0013770" : {
               "organism" : "Drosophila melanogaster",
               "uniquename" : "FBgn0013770"
            },
            "Drosophila melanogaster FBgn0034443" : {
               "organism" : "Drosophila melanogaster",
               "uniquename" : "FBgn0034443"
            },
            "FBgn0014445" : {
               "uniquename" : "FBgn0014445"
            },
            "FBgn0086827" : {
               "uniquename" : "FBgn0086827"
            },
            "FBgn0246404" : {
               "uniquename" : "FBgn0246404"
            }
         },
```
NB:

FBgn0014445 = Scer\GAL4 = Saccharomyces cerevisiae gene (this species is taxon id 4932)
FBgn0086827 = Hsim\VP16 = Herpes simplex virus Type 1 gene (this species is taxon id 10298)
FBgn0246404 = Dpse\GA25021 = Drosophila pseudoobscura pseudoobscura gene (this species is taxon id 46245)

the blanks in the genes section above are possibly because there is 'null' info in the organisms data:

```
         "organisms" : {
            "10298" : {
               "full_name" : null
            },
            "46245" : {
               "full_name" : null
            },
            "4932" : {
               "full_name" : null
            },
            "7227" : {
               "full_name" : "Drosophila melanogaster"
            }
         },
```
However, older test json output (that I used to write the code that turns the json into FlyBase curation records) had information for multiple species:

e.g.

```
         "genes" : {
            "Drosophila melanogaster FBgn0040505" : {
               "organism" : "Drosophila melanogaster",
               "uniquename" : "FBgn0040505"
            },
            "Drosophila melanogaster FBgn0086677" : {
               "organism" : "Drosophila melanogaster",
               "uniquename" : "FBgn0086677"
            },
            "Mus musculus FBgn0284422" : {
               "organism" : "Mus musculus",
               "uniquename" : "FBgn0284422"
            },
            "Saccharomyces cerevisiae FBgn0014445" : {
               "organism" : "Saccharomyces cerevisiae",
               "uniquename" : "FBgn0014445"
            }
         },



         "organisms" : {
            "10090" : {
               "full_name" : "Mus musculus"
            },
            "4932" : {
               "full_name" : "Saccharomyces cerevisiae"
            },
            "7227" : {
               "full_name" : "Drosophila melanogaster"
            }
         },
```

I don't think that the 'null' values are causing data loss when we turn the canto json into FlyBase curation records, but the code was using the genes 'organism' info to 'count' how many different species the alleles in a genotype come from (for non-accessory alleles), and was using that to determine which particular proforma field a genetic interaction annotation belongs in (there are two possibilities depending on whether its a single species or multiple), so data may be ending up in the wrong field in the records (we do have a secondary check for this, but then any errors will need fixing manually), so it would be good to fix the issue either in canto or in my code, whichever is appropriate depending on whether this is a deliberate change in format or a bug (and if its a bug, whether the problem is in canto, or in the input json that FlyBase is providing)

**Comment by kimrutherford** [comment]
Hi GIllian.

I think the file that has the full organism names came from the test Canto on in development machine where I had loaded all the organisms.  The main fly-canto just has melanogaster loaded.  We should be able to load all the FlyBase organisms into Canto but we'd need to remember to keep it up to date in case a new organism is added to FlyBase.  Loading all the current organisms into Canto would solve the immediate problem so I can go ahead with that if that's best.  Unfortunately it will be a few days before I have time.

**Comment by gm119** [comment]
I think that you should be able to get the organism info directly from chado rather than the precomputed file.

Have added the chado location of the $genus, $species, $abbreviation, $common_name, $taxonid values that you are currently grabbing in your script in case that helps.

genus = organism.genus
abbreviation = organism.abbreviation
species = organism.species
common_name = organism.common_name

taxonid	= Stored in chado as organism_dbxref, using NCBITaxon (db.db_id = '140') as the database.

So it should be possible to use the feature.organism_id for a FBgn to get the relevant organism info from chado.

I can see a couple of ways we could so this.

1. implement a script that can be run weekly to add *all* relevant organism info to the canto instance.

In this case, the script could scoot over the entire organism table, and add info into canto for any organism where organism.abbreviation is NOT null (as an abbreviation must exist if we make a gene/allele,or any other feature, for this species so that would grab all organism info that could possibly be relevant)

2. add the organism info into the fly canto input json

**Comment by kimrutherford** [comment]
As discussed on Skype, to fix this I'll change Canto to get the organism details from Chado using the hints in Gillian's comment.

Note to self - example Chado query to get organism details for a taxon ID:

```sql
SELECT org.*
  FROM organism org
  JOIN organism_dbxref org_xref ON org_xref.organism_id = org.organism_id
  JOIN dbxref xref ON org_xref.dbxref_id = xref.dbxref_id
  JOIN db ON db.db_id = xref.db_id
  WHERE db.name = 'NCBITaxon'
    AND xref.accession = '7227';

```

Note to self part 2: add a new OrganismLookup implementation for FlyCanto.

**Comment by kimrutherford** [comment]
> As discussed on Skype, to fix this I'll change Canto to get the organism details from Chado using the hints in Gillian's comment.

That's done now.  I'll keep an eye on this week's JSON export file to make sure all is OK.

**Comment by kimrutherford** [comment]
It looks OK but there aren't many genes in this weeks export file.

I'll close this issue but please re-open or make a new issue if you spot any problems.
