### ISSUE TITLE
Move session from demo to main server

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2338]
This session was curated in the demo Canto by mistake:
https://curation.pombase.org/demo/curs/b552791b9e9b4311/ro/

Need to finish this first: https://github.com/pombase/pombase-chado/issues/739#issuecomment-668473480

**Comment by kimrutherford** [comment]
> Need to finish this first: pombase/pombase-chado#739 (comment)

And more importantly: https://github.com/pombase/canto/issues/2301

**Comment by kimrutherford** [comment]
There are only four annotations and they are genotype/phenotype annotations.  I can probably move the session to the main Canto quite easily since there are no interaction annotations.

**Comment by ValWood** [comment]
Wow, I thought I remembered it being a large session. There are 9 annotations (also 5 multi gene).
Probably we didn't fancy recreating the genotypes if it was easy to migrate but to be honest we could probably have just as easily moved manually......

**Comment by kimrutherford** [comment]
No problem.  I'll move it tomorrow.

**Comment by kimrutherford** [comment]
OK, done:
https://curation.pombase.org/pombe/curs/934c9e88c393b2ff/

It's a bit of a hacky thing to do so please keep a look out for any weirdness.

After moving the session I reactivated it then submitted it so that the database status would be correct.  It's now in the needs approval list:
https://curation.pombase.org/pombe/view/list/publications_with_session_needing_approval?model=track
