### ISSUE TITLE
Canto workaround for chinese users

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2343]
Proposed message text:

Occasionally, users in China report problems using Canto caused by firewall issues at some institutions. 
If you experience  access issues, colleagues in China have reported success with some of the following options:
- VPN connection may be necessary
- IE/Microsoft Edge may not work
- 360 browser does work,  if from the "start curating" link you click on the PMID:xxxx summary" link in the upper left corner. The "start curating" link should then work.

@mah11 could you tidy this text? 
@kimrutherford would it be possible to "append" this message as a footnote to the curation request e-mail 
*IF* the email address is xxxxx.cn?

Also, have we got any other workaround reports that might be useful? This is the most detailed one that I can find. I think usually people have told us. "ok we got it to work" but did not provide any specifics.

**Comment by ValWood** [comment]
this was sun li's screen shot
![1](https://user-images.githubusercontent.com/7359272/91960609-03f00300-ed02-11ea-946b-006872199300.png)

it's odd that this particular button is a problem, but the link is OK?

**Comment by mah11** [comment]
massaged text:

We have received occasional reports of problems with access to Canto, apparently due to firewall issues, especially from users in China. If you have any trouble, we have some suggestions relayed from colleagues in China:

- Some browsers work better than others. Users report better success with the "360" browser than with Microsoft IE or Edge.
- With any browser, connecting via a VPN may help.
- When you follow the curation link in an invitation email, it may help to refresh the page or click on the "PMID:nnn summary" link in the upper left corner of the page before clicking the "Start curating" button.

**Comment by ValWood** [comment]
Should this go int he help docs? If it isn't already.
Or other suggestions?

**Comment by ValWood** [comment]
Should we ask them to do this in between?
(this was in the ticket I am answering now)

Could you try  going to the page and  doing  a 'hard refresh' on you browser to clear the cache


How to do a hard refresh in Chrome, Firefox and IE?
Hold down Ctrl and click the Reload button.
Hold down Ctrl and click F5.
Hold down Ctrl + Shift and click R.
Open Chrome dev tools by clicking F12 and right-click Reload button. Then, click Hard Reload.

**Comment by ValWood** [comment]
Alos where  should this go in the docs so that we can point to it from helpdesk tickets

**Comment by ValWood** [comment]
@kimrutherford  any other suggestions fro this list. I don't really get it because some people try these options and get it to work, and for others it doesn't...

**Comment by mah11** [comment]
Maybe I should do a FAQ entry, in case people can't even get to the documentation in Canto itself ...

**Comment by ValWood** [comment]
> Maybe I should do a FAQ entry, in case people can't even get to the documentation in Canto itself ...

good plan...

**Comment by ValWood** [comment]
I'll close this. We can keep the FAQ in case there are further issues, but this might be no longer needed.
