### ISSUE TITLE
pombe canto help pages down

### ISSUE THREAD

**Issue by mah11** [pombase/canto#2344]
I though about adding a bit to the Canto documentation for #2343, but the help link is giving me the "Please come back later" message.

Help is working fine from the test Canto instance.

**Comment by kimrutherford** [comment]
Sorry about that.  I made a cut and paste error last time the docs were updated.  Fixed now.

**Comment by kimrutherford** [comment]
For completeness, fixed by: 897fa905edeb57333702ded21b481de8ca83a9dd
