### ISSUE TITLE
Reduce vertical spacing on allele type list

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2348]
@ValWood recently suggested reducing the vertical spacing in the allele type drop-down list, so the list doesn't need to be scrolled so much to see all of the options.

I've now investigated this, and unfortunately, the styling applied to the list items is specific to the browser and/or operating system, so it's not possible to override the height of the list items. This means a macOS user on Safari will see the list differently to a Windows user on Google Chrome.

The only way we can fix this is by replacing the native drop-downs with custom drop-downs (as we've used elsewhere for the strain picker and the ontology term picker). If we still want Canto to look consistent, we'd have to change every native drop-down to use the same styles. This could involve a lot of work.

- - -

For reference, here's how the list looks on my web browser (Google Chrome, Windows). @ValWood, just to confirm, could you paste a screenshot of how the list looks on your web browser?

![image](https://user-images.githubusercontent.com/37659591/93193672-0c532f80-f73f-11ea-9fd9-5fd027c34036.png)

**Comment by ValWood** [comment]
pombase looks like this:

<img width="617" alt="Screenshot 2020-09-15 at 16 45 10" src="https://user-images.githubusercontent.com/7359272/93233443-fe1f0680-f772-11ea-9917-242ba85eb0d1.png">

**Comment by jseager7** [comment]
That's as I suspected. The appearance of the drop-down on your machine is controlled by macOS.

If we don't mind making one drop-down look inconsistent with the others, then we could just replace this specific drop-down menu with a custom implementation. Otherwise I think the best solution is replacing all our native drop-downs with custom implementations. I'm not sure how many menus would need changing in that case.

**Comment by mah11** [comment]
Honestly, I don't think there's any problem here worth any of your (@jseager7, @kimrutherford or both) time.

**Comment by ValWood** [comment]
@mah11 But you aren't using PHI-Canto, it's annoying that the options are hidden.

@jseager7 if you can work out why PHI -Canto is different from the PomBase one please go ahead and fix.

**Comment by jseager7** [comment]
> But you aren't using PHI-Canto, it's annoying that the options are hidden.

The drop-down should look the same for you in PHI-Canto as well, except for the one extra allele type (transformant). The display of the drop-down is dependent on the user's operating system, so the height issue probably only affects Microsoft Windows users (I can't say how it looks on Linux).

> if you can work out why PHI -Canto is different from the PomBase one please go ahead and fix.

The difference lies in the user's operating system, not Canto itself. I'll investigate to see how much effort this will be to fix.

**Comment by ValWood** [comment]
Thinking about it we saw this on a zoom session with Alayne. So maybe it's a Microsoft issue.

**Comment by mah11** [comment]
I don't see a difference between pombe Canto and the demo PHI-Canto.

**Comment by jseager7** [comment]
I just checked PHI-Canto today, and I think the problem might've fixed itself, probably because of an update to Windows 10. The drop-down list has much less vertical spacing now: 

![image](https://user-images.githubusercontent.com/37659591/96591082-c01b8200-12de-11eb-82f7-3f497444037c.png)

@CuzickA can you confirm that the list has the same amount of vertical spacing on your machine?

**Comment by jseager7** [comment]
Alayne has confirmed that the padding problem still exists on her work machine (Windows 10 version 1909, build 18363.1139), and her Windows version seems to be more recent than my work machine. I've checked how the drop-down looks on another PC (Windows 10 Pro), but that _doesn't_ have the padding problem, so I'm really not sure what's going on.

I suppose the only surefire way to fix this is to reimplement the drop-down to use a custom display.

**Comment by kimrutherford** [comment]
I've tried it too on a Windows 10 machine and it looks fine.  Makes it quite hard to debug.

**Comment by ValWood** [comment]
OK let's not worry about this and assume it only affects a small number. It's a minor irritation  but not a how stopper.
