### ISSUE TITLE
Use a more conventional style for radio buttons

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2350]
I've noticed the way Canto displays radio buttons is a bit non-standard. Specifically, the circular buttons are on the right hand side of the label (but it seems conventional to place them on the left), and the label text is always bold, which doesn't make much sense with this type of input.

I suggest moving the radio buttons to the other side of the label and removing the boldface:

**Before**

![expression-picker-before](https://user-images.githubusercontent.com/37659591/93206770-d66b7680-f751-11ea-897d-9813a26a76fc.PNG)

**After**

![expression-picker-after](https://user-images.githubusercontent.com/37659591/93206781-da979400-f751-11ea-81f5-680d09b3ccc9.PNG)

@ValWood @kimrutherford @mah11 Any objections to this change? FlyBase might need to be consulted too, but I'm not sure who to mention for that.

**Comment by mah11** [comment]
I don't really mind. If it doesn't change, I'll be fine (the button position never bothered me); if it changes, it'll take me a few papers' worth of time to adjust and then I'll be fine. No preference.

For FlyBase, probably ask Vitor @vmt25

**Comment by jseager7** [comment]
For anyone who doesn't know, clicking the label text next to the button has the same effect as clicking the button itself, so it's not necessary to be precise when clicking the button &ndash; although I admit this isn't obvious, and muscle memory could still make it difficult to adapt if you're used to clicking the button on the right. To illustrate, both outlined regions in the image below do the same thing when clicked:

![radio_click_regions](https://user-images.githubusercontent.com/37659591/93212714-dd4ab700-f75a-11ea-8b95-4b1d1e0bd887.png)

Note that labels being clickable might not be true everywhere in Canto, but if I make this change I'll be sure to make it so the label is always clickable.

**Comment by kimrutherford** [comment]
Sounds like a good idea to me.

**Comment by ValWood** [comment]
OK,  @jseager7  you can go ahead with this since nobody objected and @kimrutherford  thought it was a good idea.
