### ISSUE TITLE
Annotation extension term names are reverting to previous values

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2353]
(Found by @CuzickA)

We recently changed some term names in the _infective_ability_ annotation extension, but now when these extensions are edited, the term name sometimes reverts to the name it previously had. In the example below, 'pathogenic ability present' (middle row) has been renamed in PHIPO to 'functional pathogen effector present', but the old name is shown after the extension is edited.

![image](https://user-images.githubusercontent.com/37659591/94675948-76a8ca00-0312-11eb-8a55-a9058078dd19.png)

Refreshing the page apparently fixes the display to the new name again, but I'm not sure if the bug reoccurs if you edit the extension after a refresh.

It seems like some sort of caching issue, but it's particularly odd that it only occurs after editing. The extension term names are always shown as their new values when first loading the session.

**Comment by kimrutherford** [comment]
The term name and term id are both stored in the session and the code can't handle a term name changing - if the term ID hasn't changed it doesn't update the term name in the session. Sometimes in the display we show the current term name from the main Canto database when that's easier which is why you sometimes see the new term name.

I'll have a think about how to fix this.

This bug shouldn't be a problem for loading Canto annotation into PHI-base because we only export the term ID.

**Comment by kimrutherford** [comment]
I've changed the ontology loading code so that it fixes any term names stored in extensions in sessions when they change in the ontology.

Could you let me know if they problem is fixed after your next ontology update?

**Comment by jseager7** [comment]
I've checked the existing curation sessions, and found only two sessions that I know were affected by this bug. Both those sessions now have the correct term labels for their extensions.

Note that I don't know if Alayne manually amended these extension terms already, so I can't be entirely sure that the problem is fixed. The only way I can really be sure is by changing an ontology on my local copy, but given that I can't see any sign from the sessions that the problem _isn't_ fixed (no terms exist with their old labels), it would be simpler just to re-open this issue if the problem occurs again.

Thanks for your help.
