### ISSUE TITLE
searching  in extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2355]
When searching in extensions I always struggle locating the  G2/M transition terms

https://github.com/pombase/pombase-config/issues/35

  G2/M transition of mitotic cell cycle and descendants do not appear as options, although I can find them with the GO IDs

I suspect it is caused by the "/"?

**Comment by ValWood** [comment]
These are the terms I can never locate via their strings , but I can find them using their IDs
GO:0000086    G2/M transition of mitotic cell cycle 
GO:0010389    regulation of G2/M transition of mitotic cell cycle

**Comment by kimrutherford** [comment]
Is this a Canto or website issue?

**Comment by ValWood** [comment]
Canto.
So in summary, I can't locate "G2/M transition of mitotic cell cycle" in the "involved in process" modification extensions. I didn't check the others. The situation might be improved now that the phases are filtered. I'll check shortly...

**Comment by kimrutherford** [comment]
> I suspect it is caused by the "/"?

I think so.  I've tried a few indexing changes locally and haven't been able to persuade Lucene to do the right thing.  I'm still working on it.

**Comment by kimrutherford** [comment]
> I think so.

After investigation, I've changed my mind.  I think it might be a configuration issue.  Currently for happens_during it only shows descendants of GO:0022403, GO:0033554 or GO:0072690.  When I added GO:0044770 ("cell cycle phase transition") as well "G2/M transition of mitotic cell cycle" was the top match.  I made this change to canto/annotation_ex_config/GO_MF_A_E_config:

```diff
-GO:0003674     is_a    happens_during  GO:0022403|GO:0033554|GO:0072690        has function during             0,1     user
+GO:0003674     is_a    happens_during  GO:0022403|GO:0033554|GO:0072690|GO:0044770     has function during             0,1     user
```

**Comment by kimrutherford** [comment]
> I made this change to canto/annotation_ex_config/GO_MF_A_E_config:

Should I make that change permanent?


There's a similar line in the BP config that might need changing to match:
```
GO:0008150     is_a    happens_during  GO:0022403|GO:0033554|GO:0072690        happens during (e.g. cell cycle phase or stress response)               0,1     user
```

**Comment by ValWood** [comment]
Yes please!

**Comment by kimrutherford** [comment]
I've changed the config and the pombe Canto now autocompletes "G2/M transition of mitotic cell cycle" correctly,

**Comment by ValWood** [comment]
thankyou, and well spotted.

**Comment by ValWood** [comment]
Actually it was in the "involved in process" that I could not locate them.
I will recheck that...

**Comment by ValWood** [comment]
I can find these terms in the "required for process"annotations, so closing
