### ISSUE TITLE
duplicating gene expression annotations - term name selection lost

### ISSUE THREAD

**Issue by mah11** [pombase/canto#2357]
When I duplicate gene expression annotations ("copy and edit"), the popup doesn't retain the selection in the Term name pulldown; it reverts to "Choose a term ...". This isn't a big deal, but it's mildly inconvenient when I want to transfer the annotation (i.e. the same term) to a different gene.

The same thing happens with both RNA level and protein level.

Let me know if a screenshot or demo will help.

**Comment by kimrutherford** [comment]
I think I've fixed that.  Please let me know if it's still a problem.

**Comment by mah11** [comment]
Looks good in the quick check I just did. Thanks!
