### ISSUE TITLE
link to gene expression curation documentation

### ISSUE THREAD

**Issue by mah11** [pombase/canto#2359]
On the Canto help index page, there are now entries for RNA level and Protein level under "Curating specific data types", but they have no description and no links. Suggested tag lines:

- RNA level: Qualitative descriptions of presence, absence, increase, decrease, etc. of the RNA transcribed from a gene.
- Protein level: Qualitative descriptions of presence, absence, increase, decrease, etc. of the protein product of a gene.

Both can link to gene_expression.mhtml (which I've just updated).

(I would do it myself, but I don't know where these bits go and I don't want to break anything.)

**Comment by kimrutherford** [comment]
Thanks for the documentation.  I've added the necessary configuration.
