### ISSUE TITLE
Update OBO IDs on terms when reloading ontologies

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2362]
Related: https://github.com/PHI-base/phipo/issues/206#issuecomment-721648585

Canto currently doesn't update the OBO ID of an ontology term when said term is merged into another term (with the old ID becoming an alternative ID of the new term). Instead, Canto keeps showing the alternative ID as the ID of the term.

For example, the PHIPO term 'decreased size of colony' (PHIPO:0001056) is shown with its alternative ID (PHIPO:0000181) in some annotations. It would be better if Canto updates the term ID for these annotations to the ID of the 'winning' term when reloading ontologies. It already seems to update the term name.

**Comment by kimrutherford** [comment]
Alternate IDs in annotations are now changed to the primary ID as part of the ontology update process ie. `script/canto_load.pl --ontology ...`

**Comment by jseager7** [comment]
@kimrutherford Based on testing, it seems like this fix doesn't apply to the range terms of ontology extensions. For example, in one of our sessions, the term 'innate immune response-activating signal transduction' had its ID changed in GO from GO:0009870 to GO:0002758, and while this change was reflected in Canto for the 'primary' term for the annotation, it didn't apply to the same term when it was used in an annotation extension. I've confirmed that the extension in question wasn't edited as text (it was a reference to a GO ID).

Should the ontology update process also handle terms in extension ranges, or is this too complicated / out of scope?

**Comment by kimrutherford** [comment]
> Should the ontology update process also handle terms in extension ranges, or is this too complicated / out of scope?

It doesn't fix term ID in extensions at the moment.  I'll fix that soon.

**Comment by kimrutherford** [comment]
> It doesn't fix term ID in extensions at the moment. I'll fix that soon.

I've just pushed a fix for this.  Please let me know if it fixes things for you.  I've tested it on the PomBase Canto and it worked OK.

**Comment by jseager7** [comment]
I think I can only prove this has worked by testing the change on the production server. I've deployed the latest code, so I'll see if the problem is fixed after the next ontology reload.

**Comment by jseager7** [comment]
I can't see any evidence of alternative IDs being used in place of current IDs in the latest export, so I'm assuming this is fixed.
