### ISSUE TITLE
Transferring gene-for-gene annotations to new annotation type

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2366]
We need to transfer annotations from one type to another in PHI-Canto. Specifically, we need to migrate some existing annotations with the type **pathogen_host_interaction_phenotype**  to the new **gene_for_gene_phenotype** annotation type. The new annotation type is already enabled on the main server, so there should be no problems with missing configuration. Both annotation types have the same ontology namespace, feature type, and evidence codes.

Since we should only need to do this transfer once, I don't think there's any need for changes to Canto's code. All we need is a script that will do the following:

1. query the list of annotations in each session,
2. parse their extensions to check whether they have relation names that indicate a gene-for-gene annotation,
3. if the extensions match the criteria, update the 'type' column to the new annotation type name.

In terms of the extensions we'll need to check, Alayne is planning to replace all the old gene-for-gene extensions with a new, unified extension (see #2345), which has the relation name **gene_for_gene_interaction**. So the presence of that new extension _should_ be enough to catch all the relevant annotations. I can do some extra checks beforehand to make sure that there are none of the old extensions left over.

Note that it might be best to defer this issue until after the old gene_for_gene_interaction extension has been renamed &ndash; as discussed in https://github.com/pombase/canto/issues/2345#issuecomment-729634520 &ndash; just to keep things more organised, but it's not essential since even the presence of the old extension indicates that the annotation needs to be transferred to the new type.

**Comment by jseager7** [comment]
Fixed by 3d030ba2036ecf4e00dc95f4d439bd6fd502f932.

**Comment by jseager7** [comment]
Closed this in error, since I got confused thinking the script to rename annotation extensions was the script we needed for this issue.

**Comment by kimrutherford** [comment]
So is this a good summary?:

Change annotation type `pathogen_host_interaction_phenotype` to `new gene_for_gene_phenotype` on annotations that have an extension with the relation `gene_for_gene_interaction`

**Comment by kimrutherford** [comment]
I've added a first attempt at a script to change the types:

https://github.com/pombase/canto/blob/master/etc/change-annotation-type-example.pl

**Comment by jseager7** [comment]
Thanks. The script looks fine to me. I'll test it on my local copy of the production database today.

**Comment by jseager7** [comment]
I've tested the script locally and it seems to work fine. Thanks again. Closing now, but I'll re-open if I notice any problems when the change is applied to our servers.
