### ISSUE TITLE
Should PHI-Canto be using Protein Modification extensions?

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2368]
I've noticed that the pombase/pombase-config repository has an extension configuration file for PSI-MOD, called [PSI&#8209;MOD_A_E_config](https://github.com/pombase/pombase-config/blob/master/canto/annotation_ex_config/PSI-MOD_A_E_config). As far as I know, we're not using this config in PHI-Canto, and it doesn't seem to be included in Canto's repository by default.

@ValWood do you know if these Protein Modification extensions should be included in PHI-Canto?

**Comment by ValWood** [comment]
Yes, we haven't needed them so far, but I am sure that one day we will.

**Comment by jseager7** [comment]
Thanks. For now, PHI-Canto will share the same configuration as PomBase. I'll work on enabling this on our servers. Closing.
