### ISSUE TITLE
'Add another...' link is misleading for multiple-cardinality extensions

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2369]
(Raised by @CuzickA)

When adding annotation extensions with cardinality greater than one, and a biological feature as the extension range, it's easy to misinterpret the meaning of the 'Add another...' link. In the example below, the 'Add another...' link adds another gene to the _session_, but it looks like it's there to add the other protein or binding partner for the extension.

(Obviously if you try to use the link to add the other range value, it probably won't work, because the gene that you'll try to add should already be in the session, and therefore can't be added.)

![image](https://user-images.githubusercontent.com/37659591/100241666-da72fc00-2f2b-11eb-9733-e4d395bb90ff.png)

We could remove the confusion by making the link text more clear. For maximum clarity, I'd suggest **'Add new gene to this session'.**

- - -

Related to the above issue, I've always thought it would be better if the number of input fields in the extension editing pop-up matched the cardinality of the extension: so if you have cardinality 2, you get input fields for both the required values, and the two extensions are automatically created. Here's an example, with the link text change from above also applied:

![image](https://user-images.githubusercontent.com/37659591/100242903-3722e680-2f2d-11eb-81fb-cd50b31162ea.png)

**Comment by ValWood** [comment]
I'd agree to both of those.

**Comment by ValWood** [comment]
@mah11  do you envisage any problems with these 2 changes?

**Comment by mah11** [comment]
Fine with me.

**Comment by jseager7** [comment]
I'll go ahead with amending the link text since that's quick and easy.

Repeating the input fields to match the cardinality of the extension is going to be more difficult, and how sensible this solution is depends on how strict we want to be about required extensions (see #2365): for example, it's fine if we use it for extensions where the cardinality must be either 0 or 2 &ndash; since you never want the curator to add only one instance of the extension &ndash; but for cases where the cardinality can be 0 or 1 or 2, then repeating the input field in the pop-up might mislead the curator into thinking they have to add two instances of the extension.

We might be able to get around this usability issue with more prompting (and blocking the curator where multiple extensions are required), but maybe it would be better to limit the above solution to the case where the only valid cardinality values are 0 and some _n_ > 1 (with no intermediate values).

**Comment by jseager7** [comment]
I've discussed this with @kimrutherford and we agreed that adding extra input fields probably isn't worth the effort until we can be sure which extensions are actually _required_. However, we did come up with some extra ideas for increasing the usability of the extension editing process:

### Required extensions

For cases where the extension is definitely _not_ optional (where the cardinality does not include zero), we could show a message indicating how many extension values are expected. The image below shows an example of an extension with cardinality 2:

![image](https://user-images.githubusercontent.com/37659591/101631943-13779a00-3a1d-11eb-9fa2-7d5785bb336b.png)

Note: if we automatically derive the warning from the cardinality of the extension, then we can remove this information from the display name of the extension: in the example above, the previous display name was 'affected proteins (add TWO, i.e. both binding partners)'.

After the user adds one extension, the message could be updated to reflect how many extensions still need to be added. For example:

![image](https://user-images.githubusercontent.com/37659591/101631861-f3e07180-3a1c-11eb-9c5a-0525f8bfb94b.png)

### Optional extensions

For optional extensions with only a minimum and maximum cardinality (such as 0,2) we can hide the warning initially, and only show the warning once the user has added one extension.

For optional extensions with multiple cardinality intervals (such as 0,1,2) it may be better to show a notice instead of a warning, to prompt curators that they can still add more extensions – although we can afford omit the notice entirely in this case. For example, given the cardinality above, the user would see this notice after adding one extension:

![image](https://user-images.githubusercontent.com/37659591/101632614-1030de00-3a1e-11eb-824a-93b847712f62.png)

I think it's only worth including the notice if the extension should usually be annotated with the higher cardinality, e.g. cardinality 2 is preferred and cardinality 1 is only for edge cases. Otherwise it's possible that the notice could confuse users.

@ValWood @mah11 @CuzickA what are your thoughts on these suggestions?

**Comment by jseager7** [comment]
The above comment is sort of off-topic for this issue and probably belongs in #2365. I can move the discussion later if required.

**Comment by mah11** [comment]
I like the suggestions, especially the distinction between "required" and "available".

**Comment by jseager7** [comment]
I've committed the changes to the wording of the cardinality notices, but they won't be enabled in PomBase until it's updated to the latest release of the code.

Below is a table that lists the messages shown under various cardinality configurations. Please let me know if you notice any problems with the values.

Cardinality range | Extensions added | Message
-: | -: | --
`*` | _n_ | [none]
`0,1` | 0 | [none]
`0,1,2` | 0 | [none]
`0,1,2` | 1 | 1 more available
`1` | 0 | 1 required
`2` | 1 | 1 more required
`0,1,3` | 2 | 1 more required
`2,*` | 0 | 2 required
`2,*` | _n_ &ge; 2 | [none]

As shown above, it's now possible to define a cardinality range of '_n_ or more' with the syntax `n,*`, where _n_ is any number. I think the code even supports ranges of '_n_ or _m_ or more' with the syntax `n,m,*`, up to an arbitrary number of intervals.

Zero is also a valid cardinality range, both for the sake of completeness and because it seemed safer to handle zero explicitly. Zero cardinality [0] has the effect of disabling the extension (but not hiding it), so it's not useful in practice.

**Comment by kimrutherford** [comment]
Thanks James.

> they won't be enabled in PomBase until it's updated to the latest release of the code.

@ValWood @mah11 that depends on #2301

**Comment by jseager7** [comment]
I think everything in this issue is done, but I forgot to close it.
