### ISSUE TITLE
Make 'canto_json_output_parser.pl' convert the metadata field 'message_for_curators' into publication-level 'internal_notes'

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2372]
[related to #2014]

Hi Gillian,
As per subject.

Publication-level internal notes are added in the curation session front page via the ‘ Edit message to curators’ link (bottom-right, just under the ‘Pause curation’ and ‘Submit to curators’ buttons).

These notes appear in the export json, in the ‘metadata’ section, in the "message_for_curators” field. Please check the test export json output below. The test internal note reads ‘Test’.

The converter script ‘canto_json_output_parser.pl’ will have to transfer the value in this json field to the internal notes proformae field.

Thanks,
Vitor

{
   "curation_sessions" : {
      "874b9f8a38c74956" : {
         "alleles" : {
            "FBal0062158" : {
               "allele_type" : "other",
               "gene" : "FBgn0014459",
               "name" : "BacA\\p35[UAS.cHa]",
               "notes" : {},
               "primary_identifier" : "FBal0062158",
               "synonyms" : []
            },
            "FBal0093995" : {
               "allele_type" : "other",
               "gene" : "Drosophila melanogaster FBgn0003997",
               "name" : "hid[Ala5.GMR]",
               "notes" : {},
               "primary_identifier" : "FBal0093995",
               "synonyms" : []
            },
            "FBal0159524" : {
               "allele_type" : "other",
               "gene" : "Drosophila melanogaster FBgn0261854",
               "name" : "aPKC[M.UAS]",
               "notes" : {
                  "phenotype" : "testing"
               },
               "primary_identifier" : "FBal0159524",
               "synonyms" : []
            },
            "FBal0240437" : {
               "allele_type" : "accessory",
               "gene" : "FBgn0014445",
               "name" : "Scer\\GAL4[dpp.PU]",
               "notes" : {},
               "primary_identifier" : "FBal0240437",
               "synonyms" : []
            },
            "FBal0240667" : {
               "allele_type" : "accessory",
               "gene" : "FBgn0014445",
               "name" : "Scer\\GAL4[GMR.PU]",
               "notes" : {},
               "primary_identifier" : "FBal0240667",
               "synonyms" : []
            },
            "FBal0343922" : {
               "allele_type" : "other",
               "gene" : "FBgn0286795",
               "name" : "Rnor\\Prkcz[UAS.act]",
               "notes" : {},
               "primary_identifier" : "FBal0343922",
               "synonyms" : []
            }
         },
         "annotations" : [
            {
               "creation_date" : "2020-12-03",
               "curator" : {
                  "community_curated" : false,
                  "name" : "Vitor Trovisco"
               },
               "extension" : [],
               "genotype" : "genotype-FBal0159524",
               "publication" : "PMID:16116079",
               "status" : "new",
               "term" : "FBcv:0000351",
               "type" : "phenotypic_class"
            }
         ],
         "genes" : {
            "Drosophila melanogaster FBgn0003997" : {
               "organism" : "Drosophila melanogaster",
               "uniquename" : "FBgn0003997"
            },
            "Drosophila melanogaster FBgn0261854" : {
               "organism" : "Drosophila melanogaster",
               "uniquename" : "FBgn0261854"
            },
            "FBgn0014445" : {
               "uniquename" : "FBgn0014445"
            },
            "FBgn0014459" : {
               "uniquename" : "FBgn0014459"
            },
            "FBgn0286795" : {
               "uniquename" : "FBgn0286795"
            }
         },
         "genotypes" : {
            "874b9f8a38c74956-genotype-7" : {
               "loci" : [
                  [
                     {
                        "id" : "FBal0159524"
                     }
                  ],
                  [
                     {
                        "id" : "FBal0240437"
                     }
                  ]
               ],
               "organism_taxonid" : 7227
            },
            "genotype-FBal0062158" : {
               "loci" : [
                  [
                     {
                        "id" : "FBal0062158"
                     }
                  ]
               ],
               "organism_taxonid" : 7227
            },
            "genotype-FBal0093995" : {
               "loci" : [
                  [
                     {
                        "id" : "FBal0093995"
                     }
                  ]
               ],
               "organism_taxonid" : 7227
            },
            "genotype-FBal0159524" : {
               "loci" : [
                  [
                     {
                        "id" : "FBal0159524"
                     }
                  ]
               ],
               "organism_taxonid" : 7227
            },
            "genotype-FBal0240437" : {
               "loci" : [
                  [
                     {
                        "id" : "FBal0240437"
                     }
                  ]
               ],
               "organism_taxonid" : 7227
            },
            "genotype-FBal0240667" : {
               "loci" : [
                  [
                     {
                        "id" : "FBal0240667"
                     }
                  ]
               ],
               "organism_taxonid" : 7227
            },
            "genotype-FBal0343922" : {
               "loci" : [
                  [
                     {
                        "id" : "FBal0343922"
                     }
                  ]
               ],
               "organism_taxonid" : 7227
            }
         },
         "metadata" : {
            "accepted_timestamp" : "2020-07-06 20:16:05",
            "annotation_mode" : "advanced",
            "annotation_status" : "APPROVED",
            "annotation_status_datestamp" : "2020-12-03 13:11:50",
            "approval_in_progress_timestamp" : "2020-12-03 13:11:44",
            "approved_timestamp" : "2020-12-03 13:11:50",
            "approver_name" : "Vitor Trovisco",
            "canto_session" : "874b9f8a38c74956",
            "curation_accepted_date" : "2020-07-06 20:16:05",
            "curation_in_progress_timestamp" : "2020-07-08 18:26:55",
            "curation_pub_id" : "PMID:16116079",
            "curator_name" : "Vitor Trovisco",
            "curator_role" : "Fly-Canto",
            "first_approved_timestamp" : "2020-07-08 12:28:29",
            "first_exported_timestamp" : "2020-07-08 12:43:11",
            "initial_curator_name" : "Vitor Trovisco",
            "message_for_curators" : "Test",
            "needs_approval_timestamp" : "2020-12-03 13:11:36",
            "previous_approved_timestamp" : "2020-07-08 14:19:37",
            "reactivated_timestamp" : "2020-07-08 18:26:55",
            "session_created_timestamp" : "2020-03-20 20:37:07",
            "session_exported_timestamp" : "2020-07-08 14:22:44",
            "session_first_exported_timestamp" : "2020-07-08 12:43:11",
            "session_first_submitted_timestamp" : "2020-07-08 12:28:10",
            "session_genes_count" : "5",
            "session_reactivated_timestamp" : "2020-07-08 18:26:55",
            "session_term_suggestions_count" : "0",
            "session_unexported_timestamp" : "2020-07-08 18:26:50",
            "session_unknown_conditions_count" : "0",
            "term_suggestion_count" : "0",
            "unexported_timestamp" : "2020-07-08 18:26:50",
            "unknown_conditions_count" : "0"
         },
         "organisms" : {
            "10116" : {
               "full_name" : null
            },
            "46015" : {
               "full_name" : null
            },
            "4932" : {
               "full_name" : null
            },
            "7227" : {
               "full_name" : "Drosophila melanogaster"
            }
         },
         "publications" : {
            "PMID:16116079" : {}
         }
      },
   },
   "schema_version" : 1
}

**Comment by gm119** [comment]
this is now implemented. There is no need for the curator to write a 'ao210122' style curator datestamp in the message - it is automatically added by the script.
The script does not add any ?? for checking, so if the curator is adding a message to themselves to check something, they should add the ?? themselves so that it trips the peeves check
