### ISSUE TITLE
tag-it uses an obsolete jQuery method 

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2376]
@kimrutherford I've noticed that the experimental conditions picker is broken on the `webpack` branch, because tag-it.js uses the `andSelf` method from jQuery, which has been deprecated and removed in favour of `addBack` in jQuery 3.0 ([source](https://api.jquery.com/andSelf/)). There's a lot of other deprecated functions in the script, but this is the only breaking one.

Unfortunately, we're loading tag-it from npm, and there doesn't seem to be a straightforward way to patch the file prior to bundling it with webpack. The easiest fix I can think of is checking in a patched version of tag-it.js that we can use in the interim, but I'm open to other ideas.

In future it would be best to migrate away from tag-it to something more up-to-date or compatible with AngularJS, since tag-it hasn't been updated in over six years, judging by its repository. I could look at adapting the solution used for the strain picker (since that also uses a tag-like interface), but it would need some extra work to integrate with the autocomplete.

**Comment by kimrutherford** [comment]
> The easiest fix I can think of is checking in a patched version of tag-it.js that we can use in the interim,

I think that's the best plan.

> In future it would be best to migrate away from tag-it to something more up-to-date or compatible with AngularJS,

I agree.  I haven't had a look for a replacement for a few years and I haven't noticed this one before:
  https://mbenford.github.io/ngTagsInput/

From the demos it looks like it's close to what we need.

**Comment by jseager7** [comment]
Fixed by #2386.
