### ISSUE TITLE
RNA and Protein level data types

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2378]
Canto data types
Protein level
RNA level

Could/Should we prefix these

wild-type protein level
and 
wild-type RNA level

I have already come across people attempting to use them for mutant RNA/protein level. It is a bit confusing. If you are annotating an experiment which  describes changes in RNA/PROtein level there is nothing to clearly indicate that these are not the correct thing to use

and perhaps in the pop-up
Edit fields to create a new RNA level annotation ->

Edit fields to create a new wild-type RNA level annotation ->

**Comment by ValWood** [comment]
@mah11?

**Comment by mah11** [comment]
no objection

**Comment by ValWood** [comment]
OK let's do that. I think it will prevent a bit of confusion for newer curators.

**Comment by kimrutherford** [comment]
That's done.
