### ISSUE TITLE
Restricted extensions don't display in step-based workflow

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2382]
See #2004 

We've noticed that the step-based workflow isn't behaving correctly when annotation extensions are restricted to a specific annotation type: it never seems to include the restricted extensions, even when the annotation type is correct. This might be because the extension list directive isn't receiving data about the annotation type when used in the step-based workflow.

To illustrate, here's what the annotation extension list looks like in the modal workflow, which is what we expect to see:

![image](https://user-images.githubusercontent.com/37659591/102212541-4c0bed80-3ecd-11eb-9bff-c8bf915eefb8.png)

But here's what it looks like in the step-based workflow:

![image](https://user-images.githubusercontent.com/37659591/102212396-0d763300-3ecd-11eb-9e02-ea7c6c80fa7f.png)

The two extensions that are missing in the step-based workflow are the same ones that are restricted to pathogen-host interaction phenotypes in our config file:

domain ID | subset relation | extension relation | range ID | Canto display text | annotation_type_name
-- | -- | -- | -- | -- | --
PHIPO:0000001 | is_a | infective_ability | PHIPO:0001179 | extent of infectivity | pathogen_host_interaction_phenotype
PHIPO:0000001 | is_a | interaction_outcome | PHIPO:0001198 | outcome of interaction | pathogen_host_interaction_phenotype

(some less relevant columns are excluded)

I haven't investigated the code yet to see if there are any differences in implementation.

**Comment by jseager7** [comment]
I managed to work around this bug by disabling the restrictions for pathogen-host interaction phenotypes on the demo server. It's only a temporary fix because it means that invalid extensions now show up on the gene-for-gene phenotypes, but at least we can still use PHI-Canto for demonstrations.

**Comment by jseager7** [comment]
I found out why this is happening. The `annotation_type_name` is declared in the `args` block of the Mason template:
```
<%args>
$annotation_type_name
$curs_root_uri
$feature_type
$feature
$pub
</%args>
```
but then it's passed into the `extensionBuilder` directive like an AngularJS interpolation of a JavaScript variable, and because the variable doesn't exist in JavaScript, the string value is empty:
```html
    <div class="curs-box-body">
      <extension-builder extension="data.extension"
                         feature-display-name='<% $feature_display_name %>'
                         term-id="{{currentTerm()}}"
                         is-valid="extensionBuilderIsValid"
                         annotation-type-name="{{annotation_type_name}}"></extension-builder>
    </div>
```
The fix is simply to change the syntax to use Mason variable substitution:
```diff
- annotation-type-name="{{annotation_type_name}}"></extension-builder>
+ annotation-type-name="<% $annotation_type_name %>"></extension-builder>
```

**Comment by kimrutherford** [comment]
> The fix is simply to change the syntax to use Mason variable substitution:

Excellent!  Thanks for tracking that down.  I've checked in your fix.
