### ISSUE TITLE
PHIPO term erroneously included in canto_root_subset

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2383]
The term 'decreased hyphal growth' (PHIPO:0001212) is wrongly behaving like a term that shouldn't be used for direct annotation. @CuzickA is planning to use this term in a demonstration of PHI-Canto in January, so it's important that this is fixed.

![image](https://user-images.githubusercontent.com/37659591/102214020-88d8e400-3ecf-11eb-8ac2-2af7856e7a36.png)

Here's the values in `cvterm` for the affected term:

cvterm_id|cv_id|name|dbxref_id|definition|is_obsolete|is_relationshiptype
---|---|---|---|---|---|---
171033|35|decreased hyphal growth|179412|An individual organism growth phenotype in which the growth of hyphae is decreased.|0|0

Based on the linked values in `cvtermprop`, it seems like the term has somehow ended up in the `canto_root_subset`:

cvtermprop_id|cvterm_id|type_id|value|rank
---|---|---|---|---
6524|171033|6|Although this phenotype is for an individual it can be inferred from a population in a colony.|0
89280|171033|8|is_a(PHIPO:0000002)|0
89281|171033|8|is_a(PHIPO:0000402)|1
89282|171033|8|is_a(canto_root_subset)|2

This is how the term appears in the OBO file that we're loading:

```
[Term]
id: PHIPO:0001212
name: decreased hyphal growth
namespace: single_species_phenotype
alt_id: PHIPO:0000181
alt_id: PHIPO:0001056
alt_id: PHIPO:0001146
def: "An individual organism growth phenotype in which the growth of hyphae is decreased." []
comment: Although this phenotype is for an individual it can be inferred from a population in a colony.
synonym: "decreased filament growth" EXACT []
synonym: "decreased filamentous growth" RELATED []
synonym: "decreased size of colony" RELATED []
synonym: "decreased size of filamentous colony" RELATED []
synonym: "reduced filament growth" EXACT []
synonym: "reduced hyphal growth" EXACT []
is_a: PHIPO:0001215 ! abnormal hyphal growth
created_by: alaynecuzick
creation_date: 2020-11-17T10:05:15Z
```

The parent term 'abnormal hyphal growth' is not obsolete, nor is it marked as 'do not annotate'.

I'm currently reloading the ontologies on the demo server just to confirm that it wasn't a transient bug with the ontology load, but I think that's unlikely since the bug occurs both on the production server and the demo server.

**Comment by jseager7** [comment]
It doesn't seem like `cvtermprop` is referenced by any other tables, so if we can't figure out what's going on in time, it might be enough to just remove the offending row and temporarily disable nightly ontology loading (_only_ on the demo server) just to get things working.

**Comment by jseager7** [comment]
Another quick (and safer) fix would be to temporarily remove `canto_root_subset` from the `do_not_annotate_subsets` list in `ontology_namespace_config` in the canto_deploy file.

**Comment by jseager7** [comment]
I've applied the above configuration fix to the demo server, so the issue isn't time-critical anymore.

**Comment by kimrutherford** [comment]
Hi James.  I think you mentioned this possibility on Skype: it's the alt_ids that are the problem.

The OBO file loading code assumes that if two terms have an alt_id in common, then they are the same term.  It's getting in a mess with a parent of "decreased hyphal growth" - PHIPO:0001215 and then it concludes that "decreased hyphal growth" doesn't have a parent.

When I removed all the alt_ids from PHIPO:0001215 the canto_root_subset disappears from "decreased hyphal growth" after re-loading.

**Comment by jseager7** [comment]
@kimrutherford I'm not sure I follow. Which two terms have an alternative ID in common? I've queried all the alternative IDs from the ontology and I can't see any alternative IDs that are duplicated. We can't afford to remove the `alt_id` properties from 'abnormal hyphal growth' (PHIPO:0001215) because then we lose all record of the terms being merged.

**Comment by jseager7** [comment]
Ah, I've just noticed that 'abnormal hyphal growth' (PHIPO:0001215) has an alternative ID PHIPO:0001052, which matches the ID of an extant term 'hyper-smooth unicellular colony shape', so maybe that's confusing things.

**Comment by jseager7** [comment]
Looks like the erroneous alternative ID comes from https://github.com/PHI-base/phipo/commit/7f510c1f8a668a753481e3149ac75ac126aee80f: PHIPO:0001052 was meant to be PHIPO:0001054 'abnormal size of filamentous colony' (see also https://github.com/PHI-base/phipo/issues/288)

**Comment by kimrutherford** [comment]
> Ah, I've just noticed that 'abnormal hyphal growth' (PHIPO:0001215) has an alternative ID PHIPO:0001052, which matches the ID of an extant term 'hyper-smooth unicellular colony shape', so maybe that's confusing things.

That's it!  Sorry for the confusion.  You're right that there weren't any terms with alt_ids in common.

**Comment by jseager7** [comment]
I've fixed the incorrect alternative ID in the PHIPO repository, and reloaded the ontologies. The canto_root_subset property is gone from the database for this term now.

cvtermprop_id|cvterm_id|type_id|value|rank
---|---|---|---|---
6536|171035|6|Although this phenotype is for an individual it can be inferred from a population in a colony.|0
89293|171035|8|is_a(PHIPO:0000002)|0
89294|171035|8|is_a(PHIPO:0000402)|1

Surprisingly, I had to restart Canto for it to stop blocking the term, even after reloading the ontologies.

Thanks for your help tracking down the problem.
