### ISSUE TITLE
reassign community session to pombase

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2384]
this paper
https://www.pombase.org/reference/PMID:22684255
has appeared in the community feed because I curated as .gmail by mistake (autofilled!)
could it be switch to cam.ac.uk?

tks

**Comment by kimrutherford** [comment]
The safest way to fix that is for you to reassign the session to yourself (at cam.ac.uk) using Canto.

You might need to re-approve it after that.  I can't remember.

**Comment by ValWood** [comment]
OK will give that a  go, I couldn't remember...
