### ISSUE TITLE
Link gene_expression help page to phi_base_docs

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2387]
Now that PHI-Canto has the 'RNA level' and 'Protein level' gene annotation types enabled, it would make sense to have PomBase's documentation for these annotation types shared with the PHI-Canto documentation.

The relevant page is `gene_expression.mhtml`: this exists in `root/docs/` but not in `root/phi_base_docs/`.

@kimrutherford It looks like you used symbolic links in the past for shared documentation in the `phi_base_docs` directory (such as `go_annotation.mhtml`). I would create a symbolic link to `gene_expression.mhtml` myself, but I'm on a Windows machine and I'm not sure whether the links I create will be compatible with Linux systems.

**Comment by jseager7** [comment]
The issue that prompted this is at https://github.com/PHI-base/canto-docs/issues/2.

**Comment by kimrutherford** [comment]
I've added that link.

We probably should have a quick chat about gene expression annotation on the next call.  The summary is that for PomBase we've changed from using expression terms like "increased" and "decreased", to using terms like "RNA level increased".  This made life easier for loading into our annotation database.

**Comment by jseager7** [comment]
@kimrutherford Is there anything that needs to be discussed in the next meeting now that PHI-Canto supports the new terms and namespaces?

**Comment by kimrutherford** [comment]
I think we covered everything when we chatted so there's no need to talk about it at the next meeting.

**Comment by jseager7** [comment]
Finally got around to testing this and it works fine. Thanks.
