### ISSUE TITLE
bug in test

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2388]
When I go to a curation session in test I get:

DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=pombase-build-2020-09-09;host=oliver1','kmr44',...) failed: FATAL: database "pombase-build-2020-09-09" does not exist at /usr/local/share/perl/5.24.1/DBIx/Class/Storage/DBI.pm line 1517. Stack: [/usr/share/perl/5.24/Carp.pm:167] [/usr/local/lib/x86_64-linux-gnu/perl/5.24.1/DBI.pm:689] [/usr/local/lib/x86_64-linux-gnu/perl/5.24.1/DBI.pm:745] [/usr/local/share/perl/5.24.1/DBIx/Class/Storage/DBI.pm:1517] [/usr/share/perl5/Try/Tiny.pm:103] [/usr/local/share/perl/5.24.1/DBIx/Class/Storage/DBI.pm:1559] [/usr/local/share/perl/5.24.1/DBIx/Class/Storage/DBI.pm:1048] [/usr/local/share/perl/5.24.1/DBIx/Class/Storage/DBI.pm:962] [lib/Canto/DB.pm:138] [lib/Canto/DB.pm:84] [lib/Canto/Chado/ChadoLookup.pm:58] [reader Canto::Chado::GeneLookup::schema (defined at lib/Canto/Chado/ChadoLookup.pm line 48):8] [lib/Canto/Role/ChadoLikeGeneLookup.pm:219] [lib/Canto/Role/GeneLookupCache.pm:77] [/usr/local/lib/x86_64-linux-gnu/perl/5.24.1/Class/MOP/Method/Wrapped.pm:164] [/usr/local/lib/x86_64-linux-gnu/perl/5.24.1/Class/MOP/Method/Wrapped.pm:95] [lib/Canto/Curs/GeneProxy.pm:104] [reader Canto::Curs::GeneProxy::gene_data (defined at lib/Canto/Curs/GeneProxy.pm line 65):8] [lib/Canto/Curs/GeneProxy.pm:133] [reader Canto::Curs::GeneProxy::primary_name (defined at lib/Canto/Curs/GeneProxy.pm line 57):8] [lib/Canto/Curs/ServiceUtils.pm:211] [lib/Canto/Curs/ServiceUtils.pm:819] [/data/pombase/pomcur/apps/test/root/curs/front_gene_section.mhtml:128] [/data/pombase/pomcur/apps/test/root/curs/front.mhtml:18] [/data/pombase/pomcur/apps/test/root/curs/autohandler:43] [/data/pombase/pomcur/apps/test/root/curs/page_template.mhtml:35] at lib/Canto/DB.pm line 138

**Comment by kimrutherford** [comment]
Sorry about that.  Fixed now.
