### ISSUE TITLE
drop down evidence selector

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2389]
The mouse-over action on the evidence code selector now repeates the evidence term label.   Didn't it use to display a definition?

**Comment by mah11** [comment]
Which annotation type(s) are you looking at? The interaction evidence pulldowns do display definitions. I don't think the others ever did; for most of them there aren't definitions anyway (many are mapped to ECO but as far as I know Canto doesn't take IDs, names, defs, etc. from ECO directly).

**Comment by ValWood** [comment]
OK, I was looking at phenotype. It was in the long workflow which I hadn't used for a while.  I'm not so bothered about seeing the defs, but there was a right-hand pop-up repeating the term label which seemed unnecessary. However, I just went to screenshot it and now I don't see it???
So I will close this. If I see it again I'll get a screenshot.
