### ISSUE TITLE
Add new annotation type for disease

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2390]
(Successor to https://github.com/pombase/canto/issues/2206, https://github.com/pombase/canto/issues/2099, https://github.com/pombase/canto/issues/1975)

We've decided to add disease curation as a separate annotation type, which presumably should be applied to a metagenotype that consists of the 'default' case of a wild-type host strain and a wild-type pathogen strain, or at least some case where the disease is practically guaranteed to be observed. Ontology terms for this annotation type will be sourced from PHIDO (our disease ontology). The annotation type may need to be supplemented with extensions (such as tissue type), in order to disambiguate diseases that depend on specific anatomy or other conditions.

We decided to take this approach because curating the disease as an annotation extension on every interaction was too much manual work, and sometimes wasn't appropriate (e.g. model hosts or interactions with no pathogenicity). We also preferred this approach over curating diseases outside of Canto because we thought it would be better to keep the data in one place and use the curation system we already have. We decided that curating the disease manually (explicitly) would be less error-prone than inferring the disease based on past data (although there may still be scope to suggest diseases to curators in future; see past discussion from https://github.com/pombase/canto/issues/1975).

**Comment by jseager7** [comment]
The disease name annotation type is enabled on both servers now. It can be accessed through the Quick links menu or the Metagenotype Management page:

![image](https://user-images.githubusercontent.com/37659591/106887098-95fa9e00-66dc-11eb-909d-31a36a07eb63.png)

Here's an example of a completed annotation. Note that the annotation type also supports the tissue type annotation extension, here referred to as **infects_tissue**:

![image](https://user-images.githubusercontent.com/37659591/106886948-6350a580-66dc-11eb-84b7-e80c41597b91.png)

- - -

I've just got a few questions about this implementation:

1. Currently the disease name annotation type appears as a link on every metagenotype row, because Canto automatically populates those links with all the annotation types in the config file for that _feature_ (e.g. a metagenotype). This might not be ideal, because I think we're planning to only have these disease annotations on the wild-type control metagenotypes.
   
   It might be better to have a separate curation workflow for the disease names (entered from the summary page), but that doesn't really make sense at the moment because the curator has to make the metagenotypes first, so they can't do the diseases up front (unless we only ask for a pathogen and a host instead of a metagenotype; see below).

2. The disease currently relates to a metagenotype instead of a simple combination of pathogen and host species; this means that the disease is indirectly related to a wild-type pathogen gene, and the pathogen and host strains.
   
   Maybe relating the disease to a metagenotype is too specific; it could require the curator to make disease annotations on every control metagenotype that has a different pathogen gene. Also, I don't think PSO's disease names are going to include strains, so this could present issues for mapping to their ontology.

   Unfortunately the current configuration doesn't support the configuration of multiple feature types. We'd need extra configuration properties, e.g. `second_feature_type` to include another organism and `second_feature_subtype` to restrict the role of each organism to pathogen or host.

**Comment by ValWood** [comment]
If there are issues to discuss, could this be added to the next PHI-base meeting agenda?

**Comment by jseager7** [comment]
I've added the above points to the agenda for next week.

**Comment by jseager7** [comment]
In the meeting we decided that we wouldn't add a dedicated link to the Disease name annotation type on the summary page, since we thought that the existing system is good enough, especially considering curators will need to create a metagenotype before annotating diseases anyway.

The Quick Links section does provide a dedicated link to the Disease name annotation type, but only for users in advanced mode. We wondered about making these links visible by default, but didn't come to any decision.

Another problem raised by this discussion was that the Metagenotype annotation options (i.e. the link to the Metagenotype Management page) should belong in their own section on the summary page, rather than being placed in the 'Annotate genotypes' section, but I'll open a new issue for that.

I don't think there were any disagreements with regards to our decision of relating a disease to a metagenotype.

I'll close this issue now since the discussion is resolved.
