### ISSUE TITLE
Labels for "Expression"curation types

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2392]
In PomBase we prefixed  "RNA level" and "Protein level" 
with "Wild-type RNA level" and "Wild-type Protein level"  to prevent people trying to use these to describe mutant expression levels.

<img width="227" alt="Screenshot 2021-01-25 at 16 28 51" src="https://user-images.githubusercontent.com/7359272/105734485-951e7b00-5f2a-11eb-8fa2-0ff2aadbd608.png">

**Comment by ValWood** [comment]
This might be hard-coded and just waiting on a code update. However, @CuzickA  will probably want to be aware that this change is imminent.

**Comment by CuzickA** [comment]
This sounds good :-)

**Comment by kimrutherford** [comment]
> This might be hard-coded and just waiting on a code update.

It's mostly a configuration thing.  I'll be chatting to James on Tuesday morning.  We'll talk about it then.

@jseager7 you'll probably need to start loading this ontology if you aren't already: https://curation.pombase.org/dumps/latest_build/pombe-embl/mini-ontologies/pombase_gene_expression_ontology.obo

**Comment by jseager7** [comment]
We're already loading that ontology because we needed it to enable the RNA level and Protein level annotation types in the first place.

**Comment by jseager7** [comment]
I've made this change now. Both expression level annotation types are prefixed with 'Wild-type'.

![image](https://user-images.githubusercontent.com/37659591/106137834-31cb5d80-6163-11eb-957e-e944b165d7f6.png)
