### ISSUE TITLE
It is possible to select a strain synonym and have "both" the strain and synonym display

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2401]
<img width="368" alt="Screenshot 2021-01-27 at 18 06 48" src="https://user-images.githubusercontent.com/7359272/106034464-db124500-60ca-11eb-9f02-17ee6d6d25bd.png">

Behaviur should be,  that if a synonym is selected, only the primary strain name shows

Although I'm a bit worried that these "races" will probably  have  strain-specific variation at these polymorphic loci (Need to ask MAtin and K-H-K about this-  How would we specify  these?)

**Comment by kimrutherford** [comment]
> It is possible to select a strain synonym and have "both" the strain and synonym display

Hi Val.  Could you example this a bit more?  I don't get it.

**Comment by ValWood** [comment]
I wanted strain "P6497"
I selected   "race 2 strain P6497" has synonym  "P6497"
but there is an independent entry for "P6497" 
Wou can see if I select both I get 2 independent strain labels.

I think synonyms here need to be typed. I was assuming they were exact? Maybe not.
Do we go to the level of race? I can't remember. If we do this should be narrow.
This one is for @jseager7  its more about the strain data than Canto per se.

**Comment by jseager7** [comment]
@ValWood Is this _Phytophthora sojae_? I don't see an independent entry for the strain name 'P6497'; it doesn't exist as a primary strain name except where qualified by 'race 2'. There's 'P6954', which is similar, but not identical.

**Comment by ValWood** [comment]
Gah, total number dyslexia!
