### ISSUE TITLE
Create a Canto instance for SEA-PHAGES

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2405]
https://seaphages.org/
From a discussion with Ivan Erill.

This will be more or less a clone of the UniProt/Generic GO instance.

**Comment by kimrutherford** [comment]
A SEA-PHAGES Canto instance is ready for testing: https://curation.pombase.org/sea-phages/

Please give it a go with some test sessions and annotations.  I'll clear the test sessions after we're happy that it's all OK.

@ivanerill

**Comment by ivanerill** [comment]
Yes, this has been tested and multiple curations submitted and validated, thanks!
