### ISSUE TITLE
internal genotype ID visible

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2406]
I see this?
<img width="620" alt="Screenshot 2021-02-03 at 17 47 49" src="https://user-images.githubusercontent.com/7359272/106787823-128f6d00-6648-11eb-8ea1-cd53ec6a3307.png">

**Comment by mah11** [comment]
Kim explained what that's for in https://github.com/pombase/curation/issues/2949#issuecomment-771991132

**Comment by kimrutherford** [comment]
If you're seeing it when a session isn't in approval please let me know.

**Comment by ValWood** [comment]
No, I didn't read those tickets. Ignore, was in approval.
