### ISSUE TITLE
GO cellular component term error

### ISSUE THREAD

**Issue by arzuozturk** [pombase/canto#2407]
Fly-Canto>Quick links>Phenotype Anatomy>Term Name 
1. does not recognise names of any GO cellular components terms I've checked so far (GO:0000805, GO:0000803, GO:0110165, GO:0031977, GO:0120120)
2. it recognises the term ID's but with a warning.

![Screenshot 2021-02-05 at 12 36 25](https://user-images.githubusercontent.com/66944690/107050420-1e536e80-67c3-11eb-862a-aea1d3d2a15a.png)

**Comment by kimrutherford** [comment]
Hi Arzu.

It looks like the GO terms from the new combined anatomy file (FBbt-GO.obo) are in an incorrect ontology namespace.

I compared the new OBO file with the previous version and the major difference is that the GO terms have "namespace: cellular_component" in the new version and not in the previous.

Both files have "default-namespace: FlyBase anatomy CV" at the top so in the previous file the GO terms ended up in the same namespace as the FBbt: terms.

I could do a quick fix by removing the "namespace: cellular_component" lines from the new file but I think it's safer to check with Clare.

In the meantime, if it's preventing you from curating, you can ignore the warning and use the term IDs until the ontology is fixed and re-loaded.

Have good weekend!

CC @gm119

**Comment by gm119** [comment]
Hi @kimrutherford - I had a look at the file too, and I think you are right, removing the namespace: cellular_component lines looks like the right thing to do - I checked the local script that will eventually do this for us automatically, and it has a grep -v line to remove these lines, so I think you are safe just to remove them from the file you have

**Comment by kimrutherford** [comment]
Thanks Gillian.  I've updated Canto with the changed file.  I hope that fixes things.

**Comment by arzuozturk** [comment]
Hi Gillian and Kim, 
I did a quick test and It seems okay right now.
Many thanks.
Arzu
