### ISSUE TITLE
Hide redundant allele descriptions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2408]
I  realise we had older tickets about this issue, and I think we decided for now to ignore the problem. However, in PHI-Canto, it's very frustrating and really impede navigation between annotations and genotypes. 

These examples are full screen on my laptop.  Once you have a few screens of annotations to scroll through navigation becomes really difficult because you need to scroll right before you can scroll up or down.

Here are a couple of screenshots from the session I am working on at full screen resolution:

<img width="1665" alt="screen width" src="https://user-images.githubusercontent.com/7359272/107125148-0f8eb980-68a0-11eb-9ac1-28e5d300fe05.png">

<img width="1674" alt="screen width 2" src="https://user-images.githubusercontent.com/7359272/107125151-1289aa00-68a0-11eb-884f-bb8f8dbe6aad.png">

**Comment by ValWood** [comment]
I'm going to suggest a small improvement that was probably suggested before.

There is quite a bit of duplication in  amino acid alteration names and descriptions

Gip1-G3-T324A,E325A,T326A,R327A,G329A,P330A(aaT324A,E325A,T326A,R327A,G329A,P330A)[Not assayed]

Gip1-G3-T324A,E325A,T326A,R327A,G329A,P330A

We made this change recently on PomBaseweb pages. It has the added benefit of making allele names and descriptions easier for a human to read
https://github.com/pombase/website/issues/1560

I would be in favour of implementing in Canto. Can anyone remember why we never did it? (we do this already for WT and deletion)

Could be displayed as

**Comment by jseager7** [comment]
@ValWood So for the example above, and based on the discussion in https://github.com/pombase/website/issues/1560, would this be how you'd prefer to have the allele / genotype name displayed?

Gip1-G3-T324A,E325A,T326A,R327A,G329A,P330A (aa) [Not assayed]

Also, is the description part of this name automatically generated by Canto, or is it manually entered by the curator? I'm referring to the following text:

(aaT324A,E325A,T326A,R327A,G329A,P330A)

**Comment by ValWood** [comment]
We enter it manually.
Sometimes the name  might be a diminutive. For example might give a mutant with 3 mutations to alanine AAA. 

Gip1-AAA(R327A,G329A,P330A)

But if we have curated the name it should be easy to know what the description is (and could also be visible by mouse over).

**Comment by jseager7** [comment]
@kimrutherford Do you think it would be possible to port the changes in https://github.com/pombase/website/commit/f0084d1f2b0b00d2949114faebbc65e0ff2bd399 and https://github.com/pombase/website/commit/9312eea0671a3205089e71fa5de046f93f8f6cb9 to Canto to fix this issue on the front-end?

**Comment by kimrutherford** [comment]
It might be best to do this in the Perl code because that where the display_names are created but let's have a chat about this at some point.

**Comment by kimrutherford** [comment]
If the allele display should always be shortened everywhere then I think we can make a change here: https://github.com/pombase/canto/blob/master/lib/Canto/Curs/Utils.pm#L1308

**Comment by kimrutherford** [comment]
This is done now.  James, will you be able to deploy the change tomorrow?

I've updated the PomBase Canto.

**Comment by jseager7** [comment]
> This is done now. James, will you be able to deploy the change tomorrow?

It's deployed now, but I'm not sure it's working as intended. I made an amino acid substitution allele that has a description equal to the allele name, but the description isn't abbreviated. Here's the setup:

![image](https://user-images.githubusercontent.com/37659591/114535525-0fb48800-9c48-11eb-88c3-b3dbae1f65f0.png)

And here's the created genotype:

![image](https://user-images.githubusercontent.com/37659591/114535594-1fcc6780-9c48-11eb-8942-e0ffb95596e6.png)

Does it work as expected on PomBase Canto? It might just be a mistake on my end.

**Comment by kimrutherford** [comment]
Could you try adding an extra character at the start of the allele name to see what happens?

Currently it won't hide that description if it's identical to the name.  Mostly the allele name starts with the gene name (for pombe at least, like: "cdc2-4w") so this probably won't be a common case.

It could be fixed with something like:
```diff                                                                                                                                                                                      
   $description ||= $type || 'unknown';

-  if ($name =~ /[^a-z\d]$description$/) {
+  if ($name =~ /(^|[^a-z\d])$description$/) {
     $description = '';
   }
```

**Comment by jseager7** [comment]
I tried setting the name to the description prefixed by the gene name and a hyphen, TRI5-K132A, and then the abbreviation worked as expected:

![image](https://user-images.githubusercontent.com/37659591/114538703-9159e500-9c4b-11eb-9031-0223233f418a.png)

The abbreviation doesn't work if you prefix the name with a letter or a number, but I guess that is the expected behaviour, based on the regular expression. So it was my mistake after all. Thanks for the hint.
