### ISSUE TITLE
could not see full genotype in pull down menu at maximum width

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2410]
For the selected phenotype I couldn't see the host (which was fine here, because I could easily guess- but will sometimes be a problem)

<img width="1446" alt="genotype pulldown" src="https://user-images.githubusercontent.com/7359272/107125387-a3ad5080-68a1-11eb-8e7b-183c14c2df15.png">

**Comment by jseager7** [comment]
Ironically, I just closed an issue already covering this because I thought this problem would never arise in practice. I'll re-open that issue and close this as a duplicate. I'll move the image to the new issue.
