### ISSUE TITLE
Developmental stage qualifier doesn't recognise names of the FBdv terms

### ISSUE THREAD

**Issue by arzuozturk** [pombase/canto#2414]
Developmental stage qualifier doesn't recognise the names of FBdv terms such as adult stage or third instar larval stage. Instead it shows "occurrent" term which has been obsoleted.

![Screenshot 2021-02-08 at 14 07 29](https://user-images.githubusercontent.com/66944690/107231685-7f27b480-6a18-11eb-90bc-7824e3adcccc.png)

but it does recognise the term ID's

![Screenshot 2021-02-08 at 14 00 50](https://user-images.githubusercontent.com/66944690/107231723-88188600-6a18-11eb-80cd-0d30c2ff1ca2.png)

**Comment by kimrutherford** [comment]
Hi Arzu.

Canto was configured to only show descendants of FBdv:00007008 ("occurrent") for the "Developmental stage qualifier" which is now obsolete (as in your screenshot).  I've changed the configuration to show descendants of FBdv:00005259 ("developmental stage") which should help with your two examples ("adult stage" and "third instar larval stage").  That seems like the right plan but let's check with Vitor when he's back at work.  :-)

Could you let me know if the configuration change helped?

**Comment by arzuozturk** [comment]
Hi Kim,

It helped the phenotype class annotations but not the phenotype anatomy annotations. Although I've checked both of them before creating this ticket, I guess my examples were not clear enough to let you know that the problem exists for both. Sorry about that. Could you please check whether you can change the configuration for phenotype anatomy annotations as well?

Many thanks.

**Comment by kimrutherford** [comment]
Hi Arzu.  Sorry I missed that.  I've changed the extension configuration for anatomy now.  Could you try again?

**Comment by arzuozturk** [comment]
Hi Kim,

Thanks for looking into this. It seems to be working fine now.

Best,

**Comment by vmt25** [comment]
I need to fix this on the script that generates the extension_config.tsv file. I am creating a new ticket for this.
