### ISSUE TITLE
A suggestion: quick link to create WT allele

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2415]
I wondered whether, since we use them so often, it might be useful to be able to create the WT alleles with a single click from the create genotype table (in the same way as deletion currently).
Having WT  more prominently might also make it clearer that expression levels for over-expression, or knockdown should be added to a WT allele

**Comment by kimrutherford** [comment]
Would this be a PHI-Canto only button?

**Comment by ValWood** [comment]
Yes, if we did it. 
I meant to tag @CuzickA  to see if useful.
It isn't super urgent. It's something that could be implemented if people get this wrong.  I think we saw some examples from the tester.

**Comment by CuzickA** [comment]
Good idea. 
I think this would be really useful especially as we want curators to annotate all WT metagenotype controls.

**Comment by jseager7** [comment]
> I think this would be really useful especially as we want curators to annotate all WT metagenotype controls.

What would be even better is a feature to automatically derive control metagenotypes from the mutant metagenotypes, but adding a WT button should be a lot easier than that.

**Comment by jseager7** [comment]
@kimrutherford I'm happy to take a look at this if it's as simple as adapting the existing code in genotype_gene_list.html. One thing I might need to know is what configuration values to use for the wild type alleles. For reference, here's what we currently have for the deletion alleles in `GenotypeGeneListCtrl.makeDeletionAllele(geneId)`:

```js
var deletionAllele = {
  description: "",
  expression: "",
  gene_display_name: displayName,
  gene_id: geneId,
  gene_systematic_id: gene.primary_identifier,
  name: displayName + "delta",
  primary_identifier: "",
  type: "deletion",
};
```
One thing I'm a bit wary of is that there's a lot of code in `diploidConstructorDialogCtrl.ok()` that relates to wild type allele names. Is this a problem? I can't remember whether the quick allele buttons create diploids or haploids when Canto is in diploid mode. If they only create haploids then it should be unrelated to this change.

**Comment by jseager7** [comment]
@ValWood I presume you'd still want the expression picker shown when the user uses the wild type shortcut button? Should the expression picker default to any particular value, if so? Currently there isn't any option selected by default, and if we want to make sure the curator pays attention to the expression level, then it's sensible to not have a default option.

Even with the shortcut, the user still has to select the strain and might have to select the expression level, so the shortcut won't be quite as fast as the deletion one (especially compared to PomBase where there's no strains).

**Comment by ValWood** [comment]
>I presume you'd still want the expression picker shown when the user uses the wild type shortcut button? 
yes please
>Should the expression picker default to any particular value, if so?

no we need to force them to pay attention. and make a selection. No default.

> so the shortcut won't be quite as fast as the deletion one

that's. OK, it is mainly to make WT allele creation more prominent since it is such a key part of the curation.

**Comment by kimrutherford** [comment]
> I'm happy to take a look at this if it's as simple as adapting the existing code in genotype_gene_list.html

Thanks.  I'm happy to help.

> One thing I might need to know is what configuration values to use for the wild type alleles.

I think only `gene_id`, `name` and `type` are required.  Unfortunately some shenanigans are required to make a wild type allele name as they are different across species.

Here's some (untested) code to start from:

```javascript
CantoConfig.get('wildtype_name_template')
  .then(function (data) {
    var nameTemplate = data.value;

    var wildTypeIdentifier = makeAutopopulateName(nameTemplate, geneDisplayName);
    var wildTypeAllele = {
      gene_id: geneId,
      name: wildTypeIdentifier,
      type: "deletion",
   };
   if (CantoGlobals.alleles_have_expression) {
     // Fly-Canto alleles don't have expression levels
     // (but on the other hand Fly-Canto won't be using the new buttons for WT alleles)
     wildTypeAllele['expression'] = ...
   }

  // store genotpe ...
});
```

> I presume you'd still want the expression picker shown when the user uses the wild type shortcut button?

Do we need a new dialog box that contains the strain picker and the expression selector?
The expression selection is currently hard-coded in `allele_edit.html`.  I think we could extract it without too much pain:
https://github.com/pombase/canto/blob/master/root/static/ng_templates/allele_edit.html#L188
(And I think extracting it is a good idea anyway)

**Comment by jseager7** [comment]
> Do we need a new dialog box that contains the strain picker and the expression selector?

Yes, but we could use the existing `selectStrainPicker` and `strainPickerDialogCtrl` as a starting point.

I'm in favour of extracting the expression selector. It seems like the main things it depends on are the `alleleData.type`, which can be passed in as a binding, and the pathogen-host mode setting, which we can get from a service. The `isValidExpression()` function might be a bit more tricky, but that can probably be passed in as a callback.

**Comment by jseager7** [comment]
There were no objections to this change when it was demoed, and the change is now live. Closing now.
