### ISSUE TITLE
Slim down the conditions and term suggestion sections of the edit dialog

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2428]
For example:
![suggestion-suggestion-1](https://user-images.githubusercontent.com/90474/109954930-c585e000-7d46-11eb-88fa-ef7043367dbe.png)

**Comment by ValWood** [comment]
<img width="1078" alt="Screenshot 2021-03-04 at 10 52 55" src="https://user-images.githubusercontent.com/7359272/109966262-f4b93480-7ce7-11eb-9f8f-9733200c02ac.png">


1. We have a box that says "type a condition" so do we really need to say "please add experimental conditions" ain't that bleeding obvious?
2. Conditions are yada yada (this is important but it could be under an info mouse over link)
3. Previously used conditions (click to add to list)
Maybe 
Previously used [+ ergwerg] [ + high temperature]

is sufficient?

**Comment by kimrutherford** [comment]
How's this?:
![conditions-shrink-1](https://user-images.githubusercontent.com/90474/111426675-dd536000-8759-11eb-99f7-64f1b22009a8.png)

(The help text shows on mouse-over)

**Comment by mah11** [comment]
fine

**Comment by jseager7** [comment]
@ValWood For PHI-Canto, would you still want all the help text moved into the help pop-up? There was a lot of discussion in the past about stressing the fact that curators should add the delivery mechanism as an experimental condition, and it might not be as explicit if it's hidden in the help pop-up. Although, this might not matter if we've already told the curator that the delivery mechanism will be added as a condition at the start of the curation session.

**Comment by ValWood** [comment]
There is a ticket here about the text that needs to be customised for PHI-Canto
https://github.com/pombase/canto/issues/2299
So, you are correct  in that you do require additional prompting.
I suggest for the PHI-Canto configuration  "start typing a condition, or delivery mechanism", and whatever  additions (if any) required for the pop up. Most of the  help about delivery mechanisms will be further forward  to prevent people from adding the organisms and strains used as  experimental tools but are not the species of interest.
The configuration  can be addressed in the other ticket as it is additional to the simplification described here.

**Comment by jseager7** [comment]
@kimrutherford Seeing as PHI-Canto needs some help text to always be visible, I suggest commenting out the `experimental_conditions_help_text` property in `canto.yaml` (or somehow leaving the value unset), and having the help text above the picker only show when the value is set. That way, we can set the help text that we need in `canto_deploy.yaml`, and it can be hidden for everyone else (see commit 5daf031003f4906ada13b5d5d124cf4b8492c9b5).

Note that I'm assuming the new tooltip text in the help icon won't be using the `experimental_conditions_help_text` property, and will instead exist as a new property in the `help_text` associative array, kind of like this:

```yaml
help_text:
  experimental_conditions:
    inline: >
      Please add experimental conditions. Conditions are the aspects of the 
      experimental setup that are independent of what cells (strain, genotype,
      constructs, etc.) are used.

**Comment by kimrutherford** [comment]
> I suggest commenting out the experimental_conditions_help_text property in canto.yaml (or somehow leaving the value unset), and having the help text above the picker only show when the value is set. 

I've more or less implemented that in a PR (#2438) but I'm happy to tune it further.

This conditions picker will now show help text at the top if the `experimental_conditions_help_text` config is set.  If `experimental_conditions_help_tooltip_text` is set then the configured text is show in a tooltip.  One, both or neither can be set.

James, for PHI-Canto, set `experimental_conditions_help_tooltip_text` to unset / "`~`"

**Comment by kimrutherford** [comment]
How this for the term suggestion button?:
![term-suggestion-button-1](https://user-images.githubusercontent.com/90474/111711007-bc048800-88af-11eb-9ec6-0141ec1e69e9.png)

**Comment by ValWood** [comment]
Yes from me.

**Comment by kimrutherford** [comment]
> Yes from me.

Great. Should be in the test Canto now and will be in the new version of pombe Canto.

**Comment by kimrutherford** [comment]
Let's close this and open new issues for fixes/changes.
