### ISSUE TITLE
add evidence options for gene expression

### ISSUE THREAD

**Issue by mah11** [pombase/canto#2429]
For PMID:32059768, we need a couple of new evidence options for gene expression, one each for RNA and protein:

- WT RNA level: add ECO:0001838 'in situ hybridization evidence used in manual assertion' (but if possible, just display as `in situ hybridization`)
- WT protein level: add `microscopy` (can use the same thing as for phenotype annotations for this one, I think).

relevant to https://github.com/pombase/curation/issues/2962

**Comment by kimrutherford** [comment]
I've added the evidence codes.

> (but if possible, just display as in situ hybridization)

Unfortunately the display name has to match the ECO term name at the moment.

**Comment by mah11** [comment]
> Unfortunately the display name has to match the ECO term name at the moment.

eh, we'll cope. thanks!
