### ISSUE TITLE
diploid button has disappeared from genotype management.

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2433]
I can no longer create a diploid genotype. An unintended consequence of https://github.com/pombase/canto/issues/2430 ? 

(i.e the button has disappeared)

**Comment by kimrutherford** [comment]
It's there for me.  Are you logged in?

**Comment by ValWood** [comment]
I wasn't! I did not realise that creating a diploid was only available for admin. Users should (need to) be able to create diploid genotypes too.

**Comment by ValWood** [comment]
We should probably have a think about the button positioning , which is a bit confusing.

**Comment by kimrutherford** [comment]
> I wasn't! I did not realise that creating a diploid was only available for admin. Users should (need to) be able to create diploid genotypes too.

It was admin only so we could test it before making it widely available.  I think it's pretty well tested now though.
