### ISSUE TITLE
once a diploid is created it is slightly unclear how to create multi- allele genotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2437]
<img width="640" alt="Screenshot 2021-03-16 at 18 45 50" src="https://user-images.githubusercontent.com/7359272/111363513-0d323300-8688-11eb-9d6a-1e1994253e2c.png">

I wonder if it would be helpful if the combine genotype action. was also below the single locus table, in addition to below the diploid table.
Or other suggestions.....

**Comment by kimrutherford** [comment]
I'm not sure about this.  I agree that it's a bit of a weird interface at the moment but I'm not sure that I like the idea of two buttons that do the same thing.

**Comment by ValWood** [comment]
Just throwing this suggestion in there:
How about if the diploids  did not appear in their own table, but appeared in the respective single or multi-allele table?
That would also look less cluttered.....

Then the  current button labelling  and placement would continue to make sense. I can't think of a really compelling reason to have  diploids in separate tables.

**Comment by kimrutherford** [comment]
I think the diploids are in separate table to make it clear that it's only the single allele genotypes that can be used to start a diploid.  That's why the "Create diploid locus" button is under the single allele table.

**Comment by ValWood** [comment]
That *might* be OK.

The [create dipoid locus] [combine selected genotypes] would be under the table.


bub1 | bub1Δ / bub1Δ | 6 |  
-- | -- | -- | --
mad2 | mad2Δ / mad2Δ | 2 |  
rec8 | rec8Δ / rec8Δ | 1 | V

**Comment by ValWood** [comment]
So  the 'create diploid button would be  allowed for a selection that was not a diploid?

**Comment by kimrutherford** [comment]
> So the 'create diploid button would be allowed for a selection that was not a diploid?

Yep, it would need to be enabled just for single allele genotypes.

**Comment by ValWood** [comment]
I think it might be OK like this. You can only create a diploid from a haploid. That  should be obvius. You wouldn't  hopefully try to creat a diploid from a  diploid, but in case, that could be blocked.

@mah11  do you see any  problem with this approach?
We could block problematic combinations with error message like "You cannot create a  multigene phenotype from a haploid and a diploid" or whatever was appropriate to disallow.

I think fewer tables with only a single  gene/ multi gene locus split would simplify somewhat.

**Comment by mah11** [comment]
> @mah11 do you see any problem with this approach?

It'll probably be fine for pombe. We can sweep things that really form viable organisms with higher ploidy (plants, lookin' at you) under the rug until they get their own Canto instance.

It also seems compatible with eventually implementing #2012 & #2190.

> I think fewer tables with only a single / multi-locus split would simplify somewhat.

I've been arguing since #1941 that having three tables is the stupidest option. Two's fine (I'd also accept four if there were any desire).

**Comment by ValWood** [comment]
It seems that  this is what we decided to do anyway  in  #1941 !

**Comment by ValWood** [comment]
Closing as covered by  #1941
