### ISSUE TITLE
RNA & protein level annotations not saved

### ISSUE THREAD

**Issue by mah11** [pombase/canto#2440]
For 'Wild-type RNA level' or 'Wild-type Protein level', I try to make an annotation and it just doesn't appear ... most of the time. A couple of times I've seen a protein level annotation show up as expected, but usually not (and I haven't got any RNA levels to appear).

It doesn't seem to matter whether I use the 'OK' button or the alt-enter shortcut to close the pop-up. I don't think there's any correlation with exvidence or extension.

This is in the live pombe Canto. The ones I've tried today are testing guff, NOT real annotations that I want to keep, so I actually kind of hope this isn't just a failure to display annotations that are actually being created & stored.

Test Canto is behaving differently -- it looks like it hasn't been updated to use the newer PomGeneEx combinatorial terms (e.g. "RNA level increased"), and has the the older terms in a text box instead of a pulldown menu. But it does display all the annotations I tried.

**Comment by mah11** [comment]
Hmm. It's now working again for me. Could it somehow have interacted with the pop-up alt-enter bug?? That seems bizarre but is the only thing that's changed since the annotations were disappearing for me.

**Comment by kimrutherford** [comment]
Yep, that's a bit weird.  It might have been a temporary network problem.

**Comment by mah11** [comment]
Weird that it was so specific for the interactions ... I didn't think it was a network issue because connecting to the world generally, and all the other annotation types in Canto specifically, have been fine all along. But if it's working and stays that way I won't lose sleep over it.

**Comment by mah11** [comment]
I'll close this because the problem seems not to have resurfaced. Thanks for humoring me.
