### ISSUE TITLE
Wrong feature name in Quick Links tooltip

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2444]
Just noticed that the tooltip that shows on disabled links in the Quick Links section uses 'genotype' as the feature name for metagenotype annotation types, instead of 'metagenotype'.

![image](https://user-images.githubusercontent.com/37659591/112150478-0cddee80-8bd8-11eb-8243-11db16eb590f.png)

**Comment by jseager7** [comment]
Actually, it seems like the bug is because Canto is checking for genotypes instead of metagenotypes. If you have one pathogen genotype in your session but no metagenotypes, the links are enabled.

**Comment by jseager7** [comment]
The tooltip display issue is happening because I didn't configure a `feature_subtype` in `canto_deploy.yaml` for the metagenotype annotation types. With this set, the feature name displays correctly:

![image](https://user-images.githubusercontent.com/37659591/112164432-c8594f80-8be5-11eb-8410-fa56f3d45c07.png)

Unfortunately, setting `feature_subtype` seems to break the logic for enabling the quick links: I have a metagenotype in the session with a pathogen genotype and a wild-type host (no genes), but Canto won't enable the links. I managed to fix this by adding one host gene to the session (didn't even have to make any genes or genotypes including the gene), so I suspect something is wrong with the checks in `front_page_quick_links.mhtml`.

@kimrutherford Could you try to debug this? If you need to reproduce my setup, the steps are:

1. Add `feature_subtype: 'pathogen-host'` to all annotations with `feature_type: 'metagenotype'` in `canto_deploy.yaml`.
2. Add one or more pathogen genes and genotypes to a new curation session.
3. Create a metagenotype with a mutant pathogen genotype and a wild-type host (no genes)
4. Check if the Quick Links for the metagenotype annotations remain disabled.
5. (Optional) Add a host gene to the session and check if the metagenotype annotation links are enabled.

**Comment by kimrutherford** [comment]
> If you need to reproduce my setup, the steps are:

Thanks for the detail.  That made it easy to reproduce.  I've fixed that bug.

I noticed another bug while testing: the "Host phenotype" quick link was enabled when there were only wild-type host genotypes.  I've fixed that too.

**Comment by kimrutherford** [comment]
Hi James.  When you get a chance, could you give this a test and close the issue if it's OK?

Thanks.

**Comment by jseager7** [comment]
Thanks for fixing this. I meant to test this sooner but I couldn't find the time. Closing now.
