### ISSUE TITLE
PHI-base need a way to import ncRNA annotation objects from RNA central

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2446]
PHI-base need a way to import ncRNAs from any species. The most sensible way would be to use RNA central IDs.

@jseager7  can you explore  this? (hopefully the uniprot mechanism can be  modified).

**Comment by kimrutherford** [comment]
Seems like a duplicate of: #1505?

**Comment by ValWood** [comment]
Yes doplicate, closing.
