### ISSUE TITLE
Genotype table alternating rows aren't consistent with other tables

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2448]
I've noticed that the alternating background colours on the genotype table (on the  Genotype Management page) don't match the pattern used for other tables in Canto. It seems pretty much every other table has a white background for the first row, whereas the order is flipped for the genotype table.

![image](https://user-images.githubusercontent.com/37659591/113138793-2d342b80-921e-11eb-8391-6b350134a472.png)

I've tracked this bug down to an empty, invisible row that was included in the genotype table as a 'border fix for Firefox'.

https://github.com/pombase/canto/blob/687f3b2e69e7d524cf339a06b75fa69befbbfb99/root/static/ng_templates/genotype_list_view.html#L27-L29

This means that the `nth-child(even)` and `nth-child(odd)` CSS selectors get shifted out of sequence.

@kimrutherford It looks the fix causing this bug was introduced in commit 3055d04b01d726d43054ca89dc6651c85bae689c to fix the fact that "the border [of the top row] is missing if the first genotype is selected."

Does this bug still occur in newer versions of Firefox? If so, we might have to try to override the styling for this table if we can't find a fix that doesn't rely on adding elements.

**Comment by kimrutherford** [comment]
> Does this bug still occur in newer versions of Firefox?

Yep.  I've just tried a few things and can't see an obvious fix.
![missing-top-table-border-1](https://user-images.githubusercontent.com/90474/114862041-28888d80-9e42-11eb-94ca-162a5a6fd9b1.png)

To get the odd-even row style fixed we could have two copies of:
```html
 <tr> 
 <!-- border fix for FireFox --> 
 </tr> 
```
but that's just making a bad hack worse.  :-)

**Comment by jseager7** [comment]
I'll take a look at this myself. Hypothetically, if we push the alternating row styling down to the level of a `<tbody>` element that doesn't include the hidden rows, that will probably offer the most reliable fix. Unfortunately it means extra markup for the sake of styling and could involve changing all the table directives, but worst case we can just have the genotype table override the default styling and set its own rules.

**Comment by kimrutherford** [comment]
I've just tried moving the hack into its own `tbody`.  That seemed to work on Firefox and Chrome and the colours alternated correctly.

```html
<tbody> 
  <tr> 
   <!-- border fix for FireFox --> 
  </tr>
</tbody>
```

It's still a hack though.

**Comment by jseager7** [comment]
> It's still a hack though.

My proposed fix is as much of a hack as that one, so if I can't find any way to force the border to show in Firefox, I'm happy to use your fix.

**Comment by jseager7** [comment]
@kimrutherford Seems like if you change the styling to `outline` instead of `border`, it works fine. This also gets rid of the subtle rippling effect when the rows are hovered over because `outline` adds no height to the element:

```diff
.curs-genotype-list .selected, .curs-genotype-details .selected {
  background-color: #eee !important;
-  border: 2.5px solid #888;
+  outline: 2.5px solid #888;
}
```

![image](https://user-images.githubusercontent.com/37659591/114866036-fef04780-9dea-11eb-999f-909071126328.png)

**Comment by kimrutherford** [comment]
> Seems like if you change the styling to outline instead of border, it works fine. This also gets rid of the subtle rippling effect when the rows are hovered over, because outline adds no height to the element:

Perfect!  I didn't know about the outline style.

Thanks for investigating this.

**Comment by jseager7** [comment]
@kimrutherford I've pushed the fix I mentioned here to the `master` branch. I haven't bumped the `app_version` number.

**Comment by kimrutherford** [comment]
> I've pushed the fix I mentioned here to the master branch.

Thanks very much.

>  I haven't bumped the app_version number.

Done!
