### ISSUE TITLE
Always display curator notes on the session front page

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2449]
(related to #2014)
(if quick/easy)

Hi Kim,

If quick/easy, would it be possible to show on the front page the curator notes created within the session (via the 'Edit message for curators')?

The ideal place would be just below the imported internal notes.
Both notes would have slightly different labels, to make the distinction between imported and in-session curator notes noted
See mock-up.
![Picture1](https://user-images.githubusercontent.com/33721108/113905894-8c201480-97cb-11eb-8ddc-581ada9491fe.png)

**Comment by kimrutherford** [comment]
Hi Vitor.  Sorry for going quiet for so long.  I'm switching back to working on Canto now so I'll catch up soon.

This seemed like a good Friday afternoon task so I've had a go at it.  It now looks like this.  The headers are configurable (I just had a guess) so let me know what they should be.  And please let me know if the functionality is what you were thinking of.

![internal-notes-1](https://user-images.githubusercontent.com/90474/121656543-b35cd000-caf3-11eb-86bc-ac9747e7768b.png)

**Comment by vmt25** [comment]
Hi Kim, looks good.

I am thinking that maybe the 'Internal notes from JSON' header could be renamed 'Preexisting Internal notes' (not totally sure on this)

**Comment by kimrutherford** [comment]
> I am thinking that maybe the 'Internal notes from JSON' header could be renamed 'Preexisting Internal notes' (not totally sure on this)

The header is in the configuration:
  https://github.com/pombase/pombase-config/blob/master/canto/flybase/canto_deploy.yaml#L76

If you change it, let me know so I can restart Canto.

**Comment by vmt25** [comment]
OK. I think this can be closed then.
