### ISSUE TITLE
Some publications in Canto are in a weird state

### ISSUE THREAD

**Issue by arzuozturk** [pombase/canto#2451]
Some publications in Canto are in a weird state as:

![Screenshot 2021-04-08 at 10 09 02](https://user-images.githubusercontent.com/66944690/114181112-fdc9a100-9938-11eb-851b-aecac61ce181.png)

Here are the papers that are in that situation (I've spotted so far):
PMID:33137101
PMID:33037049
PMID:32697999
PMID:32629421
PMID:33177084
PMID:33064773
PMID:32709620
PMID:32504809
PMID:32754202
PMID:32059759

Thanks.

**Comment by kimrutherford** [comment]
I've checked those publications and they all failed to load because I forgot to update FlyCanto to FB2021_01 before loading the latest JSON file.  Tonight (UK time) I'll do a full backup of FlyCanto, change to FB2021_01 and then re-load the JSON file.  That should add the missing publications.

I did a test load on my desktop yesterday and confirmed that using the wrong database was the problem.

**Comment by kimrutherford** [comment]
> Tonight (UK time) ...

I got deep into something else and ran out of time to do this.  I'll re-load the JSON at the weekend when (I hope) no one will be working.

**Comment by arzuozturk** [comment]
Sure, no problem. I will let Vitor know.
Thanks.

**Comment by kimrutherford** [comment]
> I'll re-load the JSON at the weekend when (I hope) no one will be working.

Done!  The re-load created sessions for 77 extra publications.  Please let me know if you spot any problems.

**Comment by arzuozturk** [comment]
This is great. Thank you so much!

By the way, just so that you know, the papers I've reported to you in my first message do not seem to have any genes added until I assign myself as the curator, then I can see that there are genes added in fact.

**Comment by kimrutherford** [comment]
> By the way, just so that you know, the papers I've reported to you in my first message do not seem to have any genes added until I assign myself as the curator, then I can see that there are genes added in fact.

Hi Arzu.  Sorry I didn't reply to this.  I think that's the expected behaviour.
