### ISSUE TITLE
Internal change: move to the most recent version of AngularJS

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2453]

**Comment by jseager7** [comment]
Here's the AngularJS change log, for reference:

https://github.com/angular/angular.js/blob/master/CHANGELOG.md

Seems like there's only one minor breaking change, and a few renamed functions on AngularJS services, none of which we're using anyway.

**Comment by kimrutherford** [comment]
Thanks James.  I'll try updating this week.

**Comment by jseager7** [comment]
Note to self: the `webpack` branch (package.json) will need to be updated too if we go ahead with updating AngularJS.

**Comment by kimrutherford** [comment]
I updated Angular and tested everything that I think could break.  It all works fine for me and there are no (extra) warnings in the console.

I've committed that change.

**Comment by kimrutherford** [comment]
> Note to self: the webpack branch (package.json) will need to be updated too if we go ahead with updating AngularJS.

James could you fix the webpack branch?  Thanks.

**Comment by jseager7** [comment]
I've fixed this on the webpack branch too, see commit afd961012.
