### ISSUE TITLE
complex genotypes not showing on the genotype management page

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2457]
Hi Kim,

Complex genotypes are not appearing on the genotype management page, only single alleles and diploids - please see 1st screenshot.

However, these genotypes are still available when creating an annotation, on the drop-down menu - please see double diploid genotypes at the bottom of the dropdown menu, 2nd screenshot.

This behavior only occurred today.

<img width="520" alt="Screen Shot 2021-04-22 at 18 08 55" src="https://user-images.githubusercontent.com/33721108/115758542-291ba980-a397-11eb-8dc4-efa35aeb4d03.png">

<img width="762" alt="Screen Shot 2021-04-22 at 18 17 12" src="https://user-images.githubusercontent.com/33721108/115758551-2caf3080-a397-11eb-94b1-f6dd23b98368.png">

**Comment by kimrutherford** [comment]
Hi Vitor.

Sorry about this bug.  It took me a while to reproduce the problem.  Then I noticed that the multi-locus table disappeared when there were no haploid multi-locus genotypes.  If I added a haploid genotype, all the diploid genotypes appeared.  I'm working on a fix!

**Comment by kimrutherford** [comment]
I think I've fixed this.  If you still have a problem, could you send me the URL of the session where you are working?  Thanks.

**Comment by vmt25** [comment]
Hi Kim,

Yes, it seems to be fixed.
Apologies for not providing a session (FYI this was the session I was working on - https://curation.pombase.org/flybase/curs/2fb24933f90be907)

Thanks,
Vitor
