### ISSUE TITLE
multi-locus diploids do not seem to be appearing

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2458]
Multi -locus genotypes are not displayed in genotype management:

<img width="661" alt="Screenshot 2021-04-27 at 12 30 17" src="https://user-images.githubusercontent.com/7359272/116234992-36e57c00-a755-11eb-8721-23fe807d9c79.png">

However they are created, as they appear in the selector from the pop-up (so I can use them)

**Comment by kimrutherford** [comment]
Which session is that?

**Comment by ValWood** [comment]
I'm not telling you. Go to bed!

**Comment by ValWood** [comment]
https://curation.pombase.org/pombe/curs/b2b583def5375c2d
They all magically appeared once I added a haploid multi-locus genotype:

<img width="733" alt="Screenshot 2021-04-27 at 13 07 51" src="https://user-images.githubusercontent.com/7359272/116238923-ede3f680-a759-11eb-8053-56f39a8d4cea.png">

but don't worry about this tonight. A multi allele diploid isn't so common that it is likely to affect anyone.

**Comment by kimrutherford** [comment]
It sound very similar to this, which is fixed: https://github.com/pombase/canto/issues/2457

I'll investigate!

**Comment by kimrutherford** [comment]
I can't reproduce this locally with the same session.  Could you let me know if you see this again?

**Comment by ValWood** [comment]
Will do...

**Comment by ValWood** [comment]
This is a non issue.
You can't create the diploids unto you have a multi allele genotype.

**Comment by kimrutherford** [comment]
> You can't create the diploids until you have a multi allele genotype.

I think you can?

**Comment by ValWood** [comment]
yes sorry, you create the diploids and then combine them. Anyway it works fine.
