### ISSUE TITLE
enable diploids for non admin

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2462]
At the moment, I don't think the community can curate diploids. They should be able to. This might be in a ticket but I don't see it.

**Comment by kimrutherford** [comment]
The diploids from Chado aren't displayed correctly yet: #1927

Should we fix that first?

**Comment by ValWood** [comment]
yes, I couldn't remember if they were already in use for non-admin.

**Comment by kimrutherford** [comment]
> yes, I couldn't remember if they were already in use for non-admin.

Yep, it's admin only at the moment.
