### ISSUE TITLE
Blocker: can't save genotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2466]
I don't think this is my connection as everything else seems to be OK?

**Comment by ValWood** [comment]
Copy and edit does not seem to be working either.  The edit box appears but is incomplete...no annotations show, so it seems to be an issue connecting to the database.

**Comment by kimrutherford** [comment]
Sorry!  The root partition filled up.  I've had a good clean out and started pombe and fly Canto.

Please let me know if there are still problems.

@vmt25
