### ISSUE TITLE
~lots~ some of special characters not resolving

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2468]
Did the library change or somthing? It was pretty good, but I notice a few creeping in:

Authors
PagÃ© V, Chen JJ, Durand-Dubief M, Grabowski D, Oya E, SansÃ´ M, Martin RD, HÃ©bert TE, Fisher RP, Ekwall K, Tanny JC

**Comment by ValWood** [comment]
I don't think it's so many. PubMed has indexed a bunch of papers twice. Probably it is just one character...

**Comment by ValWood** [comment]
PMID:33837814 | A modified culture medium and hyphae isolation method can increase quality of the RNA extracted from mycelia of a dimorphic fungal species. | Papp LA, Ãcs-SzabÃ³ L, PÃ³liska S, MiklÃ³s I

**Comment by ValWood** [comment]
japonicus Canto

PMID:31380845 | Analysis of Lipid Droplet Content in Fission and Budding Yeasts using Automated Image Processing. | PrincovÃ¡ J, SchÃ¤tz M, Å¤upa O, PÅevorovskÃ½ M

**Comment by kimrutherford** [comment]
This is an annoying problem that I've now failed to fix permanently several times.  I'll try again.

**Comment by kimrutherford** [comment]
OK, I think the code is fixed (again).

I've fixed the mangled authors in the databases that I could see.  Except for two that are no longer in PubMed because they were duplicates (and are triaged as "Loaded in error").  Those two now have a blank authors list.
