### ISSUE TITLE
Table sorting for gene column only working in one direction:

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2470]
Table sorting for gene column only working in one direction:

<img width="124" alt="Screenshot 2021-05-12 at 14 17 54" src="https://user-images.githubusercontent.com/7359272/117987318-46a6b800-b332-11eb-8017-dd077dd1d004.png">

<img width="103" alt="Screenshot 2021-05-12 at 14 18 02" src="https://user-images.githubusercontent.com/7359272/117987330-49091200-b332-11eb-988c-6f091a4dd41f.png">

**Comment by ValWood** [comment]
Actually maybe that is intentional? You can either sort alphabetically, or it's the input order.

**Comment by kimrutherford** [comment]
> Actually maybe that is intentional?

Yep, it's only ever been single direction.

**Comment by ValWood** [comment]
Makes sense. I was only trying to sort reverse alphabetically for a screen shot but it isn't something that would normally be required.
