### ISSUE TITLE
Transfer multiple genetic interaction annotations to another genotype

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2471]
(Stemming to #2250)
For the transfer of multiple genetic interaction annotations to another genotype, the destination (transferee?) genotype should be added to the slot of the origin (transferor?) genotype, regardless of the origin genotype being the interactor genotype A or the interactor genotype B.

In the following example from https://curation.pombase.org/flybase/curs/ac29ea37d585dafb/feature/genotype/view/55/ro, the genotype Rab32[1] / Rab32[1] is used both as interactor A or interactor B. The transfer genetic interaction annotations from Rab32[1] / Rab32[1] should allow to transfer any of these.

<img width="805" alt="Screen Shot 2021-06-11 at 12 28 10" src="https://user-images.githubusercontent.com/33721108/121681286-850ad080-cab2-11eb-892c-ab9a75696829.png">

So: 
a) if the origin genotype is the interactor A, the destination genotype will be added to the interaction A slot
b) if the origin genotype is the interactor B, the destination genotype will be added to the interaction B slot

I think this is already the behavior when editing a genotype that has annotations. And actually, if easy, it would be good to have an option to transfer ALL annotations in one go, regardless of the annotation type (phenotype, genetic interaction , rescue). I'll create a separate ticket for it.

For the benefit of the curator, it is probably better to split them up in the transfer menu. A suggestion is:
![Transfer-of-annotations](https://user-images.githubusercontent.com/33721108/121703160-73352780-caca-11eb-9d9e-9d4ce0d64a5a.png)

**Comment by vmt25** [comment]
Maybe it would help to have an intermediary menu asking which interaction types would one want to transfer: Where the origin genotype appears as Interactor A or Interactor B? And also avoids making loads of transfers in one go, which can lead to curation mistakes.

**Comment by kimrutherford** [comment]
Hi Vitor.

I've started work on this.  Below is a screenshot of my prototype, in which the new annotation is previewed to make it clear what is going to be created.  Would something like this design work OK for you?  Let me know any concerns you have.  I'm happy to have another Skype chat if that's easier.

I'll let you know when something is ready for testing.

![interaction-transfer-2](https://user-images.githubusercontent.com/90474/124051433-9ff8b100-da70-11eb-8861-5384c7054c92.png)

**Comment by kimrutherford** [comment]
Hi Vitor.

I haven't finished testing things, but I've added this prototype functionality to the test version of FlyCanto for when you have time to have a look.  I've copied the current configuration and data across so the test server should work the same as the main server, apart from this new interaction transfer code.

Here is an example session in the test server to try: https://curation.pombase.org/flybase-test/curs/7f54e67c36e1995a
(It's a copy of one of Arzu's sessions from the main server)

**Comment by vmt25** [comment]
Hi Kim,

Your mock-up/implementation looks good AND seems to work fine. I added a couple of fake annotations so that there was a case in which the genotype to be edited was both on interactor A and interactor B. All worked fine.

Just need to see if it also works on rescue/complemetation interactions but I assume they are covered. (For some reason the front session page in the test instance is not showing the links for creating annotations from scratch).

Small suggestion - could the select all button function for both select all/unselect all?
Thanks a lot.

**Comment by kimrutherford** [comment]
> (For some reason the front session page in the test instance is not showing the links for creating annotations from scratch

Could that be because you hadn't turned on "Advanced mode" in the menu?  I need to fix that!

> Small suggestion - could the select all button function for both select all/unselect all?

No problem.  I'll add an un-select button.

**Comment by vmt25** [comment]
> Could that be because you hadn't turned on "Advanced mode" in the menu? I need to fix that!

Probably (holding his facing in shame)

**Comment by vmt25** [comment]
> No problem. I'll add an un-select button.

Thanks

**Comment by kimrutherford** [comment]
> Probably (holding his facing in shame)

:-)

It happens to me too.

**Comment by vmt25** [comment]
Oh, I wonder whether advanced mode could/should the default for signed-in admin users

**Comment by kimrutherford** [comment]
> Oh, I wonder whether advanced mode could/should the default for signed-in admin users

That's a good plan!

@ValWood @mah11  Any objections?

**Comment by kimrutherford** [comment]
> Your mock-up/implementation looks good AND seems to work fine. 

That's great news.  I still have some testing to do in PomBase mode and I need to check with @jseager7 to make sure this works OK for PHI-base.

I hope to get that done on Monday.

**Comment by kimrutherford** [comment]
> I still have some testing to do in PomBase mode

I done some testing and fixed some bugs.  The annotation transfer now works for ontology and interaction annotation for genes and genotypes.

Val and Midori: if you'd like to try these changes, go to a gene or genotype page in the test instance of Canto.

Vitor, my plan is to deploy these changes in FlyCanto on Monday.  I'll let you know how that goes.

**Comment by kimrutherford** [comment]
> Vitor, my plan is to deploy these changes in FlyCanto on Monday. I'll let you know how that goes.

Done!

Let me know if you find any problems or if there are any changes you'd like.

**Comment by mah11** [comment]
>> Oh, I wonder whether advanced mode could/should the default for signed-in admin users
> 
> That's a good plan!
> @mah11  Any objections?

Sounds good to me.

**Comment by kimrutherford** [comment]
> Oh, I wonder whether advanced mode could/should the default for signed-in admin users

I moved that to its own issue #1721.

**Comment by vmt25** [comment]
> > Vitor, my plan is to deploy these changes in FlyCanto on Monday. I'll let you know how that goes.
> 
> Done!
> 
> Let me know if you find any problems or if there are any changes you'd like.

Hi Kim, I finally managed to have time to play with it and all seems to work fine. 
I'll keep testing but I think this can be closed for now.
Huge thanks

**Comment by kimrutherford** [comment]
> I wonder whether advanced mode could/should the default for signed-in admin users

Thanks for the suggestion.  I've made that changed now.

**Comment by vmt25** [comment]
> > I wonder whether advanced mode could/should the default for signed-in admin users
> 
> Thanks for the suggestion. I've made that changed now.

Thanks.
