### ISSUE TITLE
multiple redundant messages for unused genotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2477]
I haven't
<img width="790" alt="Screenshot 2021-06-23 at 12 46 18" src="https://user-images.githubusercontent.com/7359272/123097111-b2973880-d427-11eb-83d7-b390cd16c97f.png">
 noticed this before:

**Comment by ValWood** [comment]
PMID:11950884  session

**Comment by mah11** [comment]
I think I saw something like that recently; I didn't worry about it because reloading the page made them go away (so I also don't remember which session(s)).

**Comment by kimrutherford** [comment]
I think I've fixed this but please let me know if you spot it again.
