### ISSUE TITLE
JSON export: --dump-approved includes unapproved sessions

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2479]
It seems like the `--dump-approved` flag on `canto_export.pl` doesn't export only approved sessions when used with the `canto-json` argument.

I ran the following command in the shell on our server, just to make sure my own script wasn't causing problems (the redirection is omitted).

```sh
./canto/script/canto_docker /canto/script/canto_export.pl canto-json --dump-approved
```

The command follows the example given in the documentation, at data_export.md:

```sh
script/canto_export.pl canto-json --dump-approved > canto_approved.json
```

I'd expect the export to only include sessions with the status 'APPROVED', but instead, the metadata objects contain these statuses:

* APPROVED
* NEEDS_APPROVAL
* APPROVAL_IN_PROGRESS
* CURATION_IN_PROGRESS

I then ran the script both with and without the flag on my local virtual machine (on commit bf26fdc9e91cd553b1911b71c991747ae8895318), and compared the number of curation sessions in the export. The number of sessions included is identical in both cases, so it seems like the flag isn't doing anything at all, or it's not being passed to the correct place.

For now I can probably just filter the full export for sessions with status 'APPROVED' with some additional script (hence the medium priority label), but we definitely need this fixed before we start importing data into PHI-base.

**Comment by kimrutherford** [comment]
Hi James.  The flag is badly named.  We export the metadata for all the statuses you list so that we can show the curation status for each publication on pombase.org.  But we only include the annotation in the JSON output if the status is "APPROVED".  Is that the behaviour you are seeing?

**Comment by jseager7** [comment]
> But we only include the annotation in the JSON output if the status is "APPROVED". Is that the behaviour you are seeing?

Yes, I think that's the case. I was wondering why some sessions were missing their annotations. Thanks for clarifying that.

Currently, I don't think we have plans to include _any_ data (or metadata) from unapproved sessions in PHI-base 5, so it would probably be simpler for our loading pipeline to only include curation session objects for approved sessions.

I'm not sure any fix is necessary, except perhaps clarifying the documentation at data_export.md. I'd suggest something like the following:

> To export data only from sessions that have been "approved" by administrators using the admin interface, use the `--dump-approved` flag. Note that metadata and publication details will still be included for all sessions, but only approved sessions will include data on annotations and biological features (genes, genotypes, and so on).

**Comment by kimrutherford** [comment]
>  I'd suggest something like the following:

Thanks for that.  I've added it.

**Comment by jseager7** [comment]
Thanks. I'll close this now, since the documentation is improved.
