### ISSUE TITLE
Metagenotype details page is broken

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2481]
I'm getting an error from Catalyst on the latest code version (commit bf26fdc9e91cd553b1911b71c991747ae8895318) when I try to access the details page for a metagenotype, for example through the 'View phenotype annotations' link, shown below:

![image](https://user-images.githubusercontent.com/37659591/124901859-4c3f1800-dfda-11eb-86cc-ca84bcd71838.png)

Fortunately this bug isn't affecting the server at the moment, but only because it hasn't been updated. I'm still able to make annotations on my local version, the problem seems to be isolated to the metagenotype details page.

This is the error message in the shell:
```
[error] Couldn't render component "curs/metagenotype_page.mhtml" - error was "Can't use an undefined value as an ARRAY reference at lib/Canto/CursDB/Genotype.pm line 286.

Stack:
  [lib/Canto/CursDB/Genotype.pm:286]
  [lib/Canto/CursDB/Genotype.pm:357]
  [lib/Canto/CursDB/Genotype.pm:406]
  [/canto/root/curs/metagenotype_page.mhtml:151]
  [/canto/root/curs/metagenotype_page.mhtml:183]
  [/canto/root/curs/autohandler:44]
  [/canto/root/curs/page_template.mhtml:35]"
```
Here's the offending line in the `Genotype.pm` module:
```pl
  for (my $idx = 0; $idx < @{$config->{allele_type_list}}; $idx++) {
```
I've confirmed that `allele_type_list` is defined in my `canto_deploy.yaml`, and the list isn't empty in the config.

**Comment by kimrutherford** [comment]
Sorry about that!  I've pushed a change that I hope will fix things.  Could you try it?

**Comment by jseager7** [comment]
@kimrutherford Yep, that seems to have fixed it. Thanks very much.
