### ISSUE TITLE
Modelling causal interactions in Canto , part 2 gene product to term relation

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2483]
We also need to record the relationship between the entity and the term.

The see of allowed is in the GPAD file description.
https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md#allowed-gene-product-to-go-term-relations

We  can default to 
MP enables
BP part_of
CC part_of for noncomplexes and located in  for non-complexes

Then  we need to decide
I) which other relations we need.  
- We probably only need to allow something to say that a gene product acts upstream of a process.  This will be useful for some models.
- Can switch the  MF contributes_to qualifier (or implement in the 'causally. upstream as a qualifier in the  same way- this will be admin only so it doesn't need to be fancy).

Before anything is done here  I'll add some of the example use cases I have collected so far.

**Comment by mah11** [comment]
The default for BP is `involved_in`.

**Comment by ValWood** [comment]
These relations must be in the GPI file so this can close?
