### ISSUE TITLE
Update Canto link to japonicus

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2486]
Make a live link.
Fix text. Currently:

"We are currently configuring Canto instance to support community curation of the emergibng model Schizosaccharomyces japonicus"

**Comment by ValWood** [comment]
In collaboration with Rothamsted Research, we are extending Canto to enable the curation of pathogen-host interaction (multispecies) phenotypes and genotypes for PHI-base

-> 
In collaboration with Rothamsted Research (PHI-base), we have extended Canto to enable the curation of multiple strains in a single Canto instance, and to curate pathogen-host interaction (multispecies) phenotypes and genotypes.

**Comment by kimrutherford** [comment]
> "We are currently configuring Canto instance to support community curation of the emergibng model Schizosaccharomyces japonicus"

What should we change that to?

**Comment by ValWood** [comment]
"We have  implemented Canto to support community curation of the emerging model Schizosaccharomyces japonicus"

**Comment by kimrutherford** [comment]
Thanks.  I've updated the PHI-Canto and japonicus texts and it now links to the live japonicus Canto.
