### ISSUE TITLE
Broken symbolic links in go_uniprot_docs directory

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2488]
I was testing rsync as an alternative synced folder method for my Canto virtual machine, and it reported some errors about symbolic links with no referents in the `go_uniprot_docs` directory:

- `root/static/images/go_uniprot_docs/edit_ext.png`
- `root/static/images/go_uniprot_docs/ext_edit_button.png`
- `root/static/img/go_uniprot_docs/edit_ext.png`
- `root/static/img/go_uniprot_docs/ext_edit_button.png`

I think this is because the files have been renamed in `root/static/images/docs`, judging by the fact there are files with similar names there: `edit_go_ext.png`, and `go_ext_edit_button.png`. The symlinks probably just need updating to those files, although I'm not sure how to confirm whether those are the correct images.

It's not urgent to fix this bug because rsync still works despite the errors, and rsync turned out to be less suitable than the synced folder method I was already using anyway.

**Comment by mah11** [comment]
Oh yes, I remember having to rename some of the images when we added extensions to annotation types other than GO. (I'll leave it to @kimrutherford to update symlinks, though - I've never touched them and don't trust myself not to break anything if I did.)

**Comment by kimrutherford** [comment]
Thanks for finding those James.  I've fixed the symlinks.
