### ISSUE TITLE
automagically create GO process annotations when added as part_of links to functions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2490]
I have been thinking this would be  nice for a while. Currently we need to add them manually. e.g.

<img width="602" alt="Screenshot 2021-09-01 at 16 09 18" src="https://user-images.githubusercontent.com/7359272/131696814-c83154ad-9a7a-44df-87ec-5ffeffb9f36c.png">

**Comment by kimrutherford** [comment]
Could this be done during the Chado loading rather than in Canto?

**Comment by ValWood** [comment]
Yes, I think it could.

My only slight worry is that it might be a bit confusing for users.

Some MF are not connected to BP and some BP are not connected to MF.
So the user will see some BP instantiated, and some not. They will probably make the ones that would be inferred anyway (but that is OK) At least with your suggestion  I  know that if the BP is not made explicitly, it will be created.

**Comment by kimrutherford** [comment]
Where do we get the MF-BP relations?  I can't see those relations in the OBO file and there are no MF-BP relationships in Chado.

I think this is related: https://github.com/pombase/website/issues/485

**Comment by ValWood** [comment]
We make them using extensions:

MF part_of BP

**Comment by ValWood** [comment]
I just put this at "low priority" as it isn't  a blocker for making progress.

**Comment by kimrutherford** [comment]
Do the community curators add those extensions too?

**Comment by ValWood** [comment]
Yes, they do use them too! and when they add them they tend  not to add the BP explicitly. I add these in checking because that is the only way to get into GO.

However, this takes very little time, because many papers do not have GO, and many people Omit the GO altogether so I do them. Its odd,  for GO annotation they seem to do it  too completeness, or not at all. I guess they look at the gene pages and copy. what they have seen.

**Comment by kimrutherford** [comment]
OK, so we need to add a process annotation if there is a part_of(BP) extension for a MF annotation?

Does the new process annotation need an extension?  Should it use the same evidence code as the original extension?

Will MF annotations with these sorts of extensions ever come into Chado from external sources like GOA?

**Comment by ValWood** [comment]
> OK, so we need to add a process annotation if there is a part_of(BP) extension for a MF annotation?
yep

The extensions  don't need to be transferred. it would not be incorrect, but I try to make the extensions only on the mF as it would be redundant to add on the BP.

> Will MF annotations with these sorts of extensions ever come into Chado from external sources like GOA?

I would say no. I would like an alert if they do !

**Comment by kimrutherford** [comment]
OK, thanks.

What about the evidence code?

**Comment by ValWood** [comment]
> What about the evidence code?

good question.
The evidence code applies to the root annotation. The evidence for the p[process itself is sometimes different. That means we can't really do this. I will continue to add them (it isn't a lot of work)

can close this!
