### ISSUE TITLE
allele display oddity (splitting synonyms on internal commas)

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2494]
This one,
SPAC694.06c	mrc1-S599A,S604A,S614A	[null]	S599A,S604A,S614A	mrc1-3SA	ed5a1aa8c1ecb938

I fixed like:
<img width="593" alt="Screenshot 2021-09-29 at 09 36 24" src="https://user-images.githubusercontent.com/7359272/135235462-35e93baf-add7-49bc-86d5-01c1ea7f7870.png">

but the synonym displays with spaces between the comma's
https://www.pombase.org/genotype/mrc1-3SA-S599A,S604A,S614A-amino_acid_mutation-expression-not_assayed

so I think it is splitting into separate synonyms?

mrc1-S599A, S604A, S614A

Maybe we should change to a different separator?

At present we should be able to fix as the commas that are separators will have spaces after them,.

**Comment by mah11** [comment]
I've made a new ticket in curation-dom for the fixes in specific sessions, so if the code change is done & working this can be closed.
