### ISSUE TITLE
Admin interface indentation has disappeared

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2496]
Now looks like:

<img width="512" alt="Screenshot 2021-10-28 at 00 04 26" src="https://user-images.githubusercontent.com/7359272/139159825-3dbaa7b7-5127-45aa-a4b2-9c687db6951b.png">

**Comment by kimrutherford** [comment]
Val, did this problem disappear?

**Comment by ValWood** [comment]
Yes, magically!
