### ISSUE TITLE
future: Conditions: link out to bioportal

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#250]
Once we have submitted pco (and agreed on a new name...), can we get a link to bioportal by the conditions addition box saying something along the line of 'to browse the full list of available conditions, see clicky'  (or something)
see the FYPO browser for an example: http://bioportal.bioontology.org/ontologies/47646/?p=terms&conceptid=FYPO:0000001

Original comment by: Antonialock

**Comment by ValWood** [comment]
closing. Lilklihood in next 10 years =0
