### ISSUE TITLE
canto can't be reached

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2500]
I can log in but triage gives
https://www.poetryfashion.co.uk/product-UA76-POEST/colour-e-pale-grey/shirts-tunics/seersucker-linen-and-cotton-shirt.htm?Media=CMDBG037&gclid=EAIaIQobChMI2NDXy9398QIVG-ztCh2_qQmCEAQYBSABEgKOevD_BwE

**Comment by ValWood** [comment]
No hurry because everything else is working normally, and I don't need to triage in a hurry.

**Comment by kimrutherford** [comment]
It seems to be intermittent and I also couldn't reproduce the problem in Chrome.  Could you keep an eye out for any patterns?

**Comment by ValWood** [comment]
will do, can close for now, I can reopen if necessary.
