### ISSUE TITLE
check for new comma separated synonyms

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2503]
These were fixed  to pipes on Oct 19th, but I have added new ones.

**Comment by kimrutherford** [comment]
Here is a list of allele names containing commas that were added or changed since Oct 17th.  There's no easy way to find just the new ones.

[new_alleles_with_commas.txt](https://github.com/pombase/canto/files/7591748/new_alleles_with_commas.txt)

**Comment by ValWood** [comment]
OK they all look fine!
I was sure I added a couple of comma separated synonyms, but perhaps not...
