### ISSUE TITLE
make quicklinks available by default

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2504]
Currently  are only available in advanced mode.

I think this is more confusing to users than helpful, and it might explain why we often get phenotype curation(which is the most complicated because they need to curate alleles) but no other curation types.

**Comment by kimrutherford** [comment]
There's some other discussion about this here: #1456

**Comment by ValWood** [comment]
I reilised after I  responded that users can use 'advanced mode", but I still think we  could improve the workflow for users in this area.

Closing this ticket.

**Comment by ValWood** [comment]
#1456 duplicate
