### ISSUE TITLE
Metagenotype changes should propagate to annotation extensions

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2505]
(Requested by @CuzickA)

We've noticed that once a metagenotype is used in our **compared_to_control** annotation extension (which has `MetagenotypeID` as its range), the extension value doesn't update if the metagenotype it references is changed. This means the curator has to recreate all of the annotation extensions manually (sometimes upwards of 20 at a time).

@kimrutherford Am I right in thinking that the annotation extension merely sets its value to a copy of the display name of the metagenotype? If so, how difficult would it be (for me) to change the extension so that it references the current version of the metagenotype? I doubt this has ever been a problem before, because the only other feature that's used as a range ID is `GeneID`, and that's immutable in a curation session.

Another option could be to add a feature for bulk-editing annotation extension range values across multiple annotations, but that could be even more complicated than the other fix.

**Comment by kimrutherford** [comment]
> Am I right in thinking that the annotation extension merely sets its value to a copy of the display name of the metagenotype?

It stores the metagenome database ID and the display name.  If the metagenotype changes the display name stored in the extension isn't updated.  The current implementation isn't great.  In the database the extension should probably just contain the ID and the Perl code should fill in the name before returning the JSON to Javascript code.  I'll have a look at doing that.

**Comment by ValWood** [comment]
This is similar to needing to edit "multi-gene genotypes" when one of the contributing genotype changes. I thought there was a ticket about this, but I can't find it.

**Comment by mah11** [comment]
> This is similar to needing to edit multi-~gene~locus genotypes when one of the contributing ~genotype~ allele names or descriptions changes. I thought there was a ticket about this, but I can't find it.

The main one is #2505 (and it links to #1901, but that one has less detail).

**Comment by mah11** [comment]
corrected ticket link (#2304) ...doh

**Comment by jseager7** [comment]
@kimrutherford This problem keeps showing up now that we have new curators on the project. Could you please take another look at this when you have time? I'm happy to help test or make changes.

**Comment by kimrutherford** [comment]
Just to be clear, what sort of metagenotype changes are we talking about?  Can metagenotypes change after creation?

**Comment by jseager7** [comment]
If the genotype display names are always updated correctly, perhaps it's easy for PHI-Canto to just concatenate the genotype display names to form the metagenotype display name at runtime, like you suggested.

An ideal fix would be recalculating relevant metagenotype display names only when their constituent genotypes are updated (then caching the display names for later), though if this can't be enforced by some constraint in the database then it could be a bit flaky.

**Comment by kimrutherford** [comment]
> perhaps it's easy for PHI-Canto to just concatenate the genotype display names to form the metagenotype display name at runtime

I haven't investigated that plan yet.  Sorry!  My current excuse is that I have Covid.  I've put it at the top of my to-do list for when my brain is not so fuzzy.

**Comment by jseager7** [comment]
@kimrutherford No worries. We can already work around this issue manually anyway, so it's not urgent. If I get any spare time I'll try to take a look at the code myself. Get well soon!

**Comment by kimrutherford** [comment]
> The current implementation isn't great. In the database the extension should probably just contain the ID and the Perl code should fill in the name before returning the JSON to Javascript code.

I've made a PR that implements a first pass at this: pombase/canto#2557

@jseager7 would you be able to try out the change when you have a chance?

Currently there is no caching of the metagenotype display name - it's calculated as needed.  This may be too slow for large sessions.  If so, we'll need to do some more work.
 
On Monday I'll investigate how this change interacts with exporting Canto sessions to JSON.  That code might need changes too.

**Comment by kimrutherford** [comment]
> On Monday I'll investigate how this change interacts with exporting Canto sessions to JSON. That code might need changes too.

It's all fine as far as I can see.  No changes needed.

**Comment by jseager7** [comment]
Fixed by #2557. The metagenotype display names are now calculated as needed in the interface and when exported as JSON.
