### ISSUE TITLE
Add curation option for peptide motif (SO)

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2507]
Follow on from
https://github.com/pombase/canto/issues/20

**Curation type**
Protein sequence feature or motif

**Description/prompt text**
A Protein localization signal is a peptide sub-sequence used to target the protein to a specific organelle.
 
Start typing in the search box (type at least 2 characters). If you do not find the term you are looking for with your initial search, begin with a broad term (peptide_localization_signal ). Note that sequence ontology term names include underscores instead of spaces.
More specific terms will be suggested allowing you to refine your search iteratively before making your final selection.

**Branch of SO**
We only need this SO subset to be avaiable
http://sequenceontology.org/browser/current_svn/term/SO:0001527

**Evidence selection**
EXP or ISS

**Extension** 
 “region/residue” (Mandatory)
This will be an amino acid range   i.e. R97-K101

I wanted to avoid a generic "protein feature" option as people might try to capture domains and families, or modification sites, which are also available in this branch of SO, but which we capture in other ways.

[ Future: Once this works we will add an option for protein stability element ( the stability element we use are currently missing this parent in SO). I don’t think there are any other branches that we will use]

**Comment by kimrutherford** [comment]
> “region/residue” (Mandatory)

We don't have a way to make extensions mandatory at the moment.

**Comment by ValWood** [comment]
> We don't have a way to make extensions mandatory at the moment.

That's OK, I think most people would add automatically if describing a motif, and we will check.

**Comment by ValWood** [comment]
It will be a bit like the gene expression terms I hope. everyone used the extensions for those.

Can you put a time estimate on this?
Is it mainly configuration?

**Comment by kimrutherford** [comment]
Unless I'm misunderstanding things, it should be less than an hour to change the config and test the changes.  We'll probably want to deploy it in the test Canto before going live.

We'll need to update the documentation too.

**Comment by kimrutherford** [comment]
I had a fix some bugs that cropped up because of the new configuration.  But I've now had a first go at this and it's deployed in the test Canto.  Let me know any changes you'd like.

On this page:
 https://curation.pombase.org/test/curs/f7d275c886036eab/feature/gene/annotate/2/start/protein_sequence_feature_or_motif

Do we need any extra help text when you click "more..."  ?

**Comment by ValWood** [comment]
Oh wow!, I will check that out later when I am doing the GI's.

**Comment by ValWood** [comment]
I just checked. That works really well.

Only one small text change to the prompt:
make the example a range K23-K30 because these are never a single amino acid (just to make sure they get the syntax correct).

I don't think any extra help is needed it's all really obvious, especially with the pull down menu showing the available options (If anyone wants an additional one they can ask)

**Comment by ValWood** [comment]
> especially with the pull down menu showing the available options 

This is probably temporary because on closer inspection it doesn't include all the terms we use. We will need to browse the ontology sub tree.

**Comment by ValWood** [comment]
Right  I put just "protein localization signal"
but  we also  annotate degron signals like KEN boxes.
 We  need to go up the hierarchy (but also to avoid letting users add 'domains' and either protein features that we don't want them to curate.

Let's discuss next week. I will have a poke around SO to see what we need. At the moment I see just problems.

**Comment by kimrutherford** [comment]
> Only one small text change to the prompt:
> make the example a range K23-K30

Is that change for the extension dialog?

**Comment by ValWood** [comment]
> Is that change for the extension dialog?

yep

**Comment by ValWood** [comment]
>Do we need any extra help text when you click "more..." ?

- [ ] We will need to tweak the part under "more..." once the correct SO subset is in place

**Comment by kimrutherford** [comment]
> make the example a range K23-K30

That's done for the next time I re-release the test Canto.

> We need to go up the hierarchy

If it helps we should be able to configure Canto to include multiple sub-ontologies and also, if needed, to exclude sub-ontologies.

**Comment by ValWood** [comment]
>If it helps we should be able to configure Canto to include multiple sub-ontologies and also, if needed, to exclude sub-ontologies.

Oh wow that will be perfect. I will see if I can get SO to push some fixes through (some of the confusing terms are children of our required starting terms)

I will also identify the branches that we need.

**Comment by ValWood** [comment]
> If it helps we should be able to configure Canto to include multiple sub-ontologies and also, if needed, to exclude sub-ontologies.

I had a look and this won;'t help us at the moment.
UNtil these are fixed:
https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/569
https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/571
https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/574
we need to use "polypeptide_region"

I think this will be fine because  although there are some things we don't want to capture this way (like domain), they are stubs, and also I doubt that our community will try to use the. If so we can fix.

polypeptide_metal_contact
will not appear using this subset, but I opened a ticket for that and we only used it once so far, so it isn't show stopper.

Late, we can probably exclude  some terms.

**Comment by ValWood** [comment]
pinging this ticket. 
I am going to show @manulera  shortly the curation of these features in Artemis, but maybe  this is too close?

**Comment by kimrutherford** [comment]
It's working in the test Canto.  I can deploy it in the main Canto anytime.
Sorry, I misread this comment and thought we were waiting for SO changes: https://github.com/pombase/canto/issues/2507#issuecomment-1008105091=

Are you happy with how it works in the test Canto?

**Comment by ValWood** [comment]
Yes, I forgot where we were up to with this too!
It works fine. We might need to rethink how we configure the terms if we add more, but for now the static list works OK>
I think longer term we are hoping the SO makes it easier  by correctly grouping all of the terms we need.


<img width="1056" alt="Screenshot 2022-05-12 at 13 52 07" src="https://user-images.githubusercontent.com/7359272/168079020-28724bda-4b6a-4a4a-9773-6782bcefe4a0.png">

**Comment by manulera** [comment]
Ok I saw it, looks nice!

**Comment by kimrutherford** [comment]
> We might need to rethink how we configure the terms if we add more, but for now the static list works OK

Should I deploy it in the main Canto?

**Comment by ValWood** [comment]
Yes please, deploy. Even if we do add new terms over time we can survive in this mode for quite a while because the rate we add and use them is so slow.

**Comment by kimrutherford** [comment]
> Yes please, deploy.

Done!  Let me know if you see any problems.

**Comment by kimrutherford** [comment]
I'm leaving this open for now.  Once you've successfully done some curation with this annotation type, please let me know so I can close it.

The annotations should automatically appear in the "Protein sequence features" of the "Protein features" section, but I'd like to double check once there are some of these annotations in an approved session.

One other thing to think about: if the help text on the long workflow isn't right we should change that too.  This is how it looks at the moment:

![image](https://user-images.githubusercontent.com/90474/168945472-cc71c671-2171-465b-9104-154f5c347981.png)

**Comment by ValWood** [comment]
@manulera

**Comment by ValWood** [comment]
Closing. It's a long ticket and we can open  new tickets if there are problems.
