### ISSUE TITLE
cant delete canto annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2508]
I would like to defete these 2 annotations from 74503deb11e399af
<img width="656" alt="Screenshot 2021-12-20 at 09 50 55" src="https://user-images.githubusercontent.com/7359272/146747954-a1f02e75-3792-48f3-afe4-aefcf1d7d04b.png">

but I get the message

"couldn't delete annotation: undefined'

**Comment by kimrutherford** [comment]
I can't see those two annotations in the session.  Did you manage to delete them?

**Comment by ValWood** [comment]
yes sorry meant to update the ticket and got side tracked. I think I had been logged out, but I still looked login in. I logged out and in again and it worked.
