### ISSUE TITLE
change "column_17" text in display

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2509]
to "modified form"
(In GO column 17 is alternative transcript or Isoform- we  separate these in Canto, but merge into column_17 of the GAF file)

**Comment by ValWood** [comment]
I have a note underneath this which looks like
"move over to hand? hans? hansi ? tansi?"
I know I needed to do something else, or do something to another  ticket, but I can't remember what?

also,
PR:nnnnID for gene product form
>
PR:nnnID for modified protein form

**Comment by kimrutherford** [comment]
> also,
> PR:nnnnID for gene product form
>
> PR:nnnID for modified protein form

I've made that change.

Changing the relation name from column_17 to modified_form will need a bit of Canto down time while I change the existing annotations.

It's only available for admin users at the moment.  Are you thinking of making it available to other users?

**Comment by ValWood** [comment]
Ah I forgot that. Not immediately, because we need to request PRO Ids which is a bit of a pAIN, so I usually add them while checking. Hopefully an easier way to do this will evolve.

**Comment by kimrutherford** [comment]
> but merge into column_17 of the GAF file

Note to self: we also need to make sure this is OK in the GPAD/GPI files.

**Comment by kimrutherford** [comment]
> Changing the relation name from column_17 to modified_form will need a bit of Canto down time while I change the existing annotations.

Should I go ahead and do that?  It will take 5-10 minutes one night.

**Comment by ValWood** [comment]
I think so.  I know this is only for admin, but  it might be possible to open up to the community at some point- especially as more modified forms are included- authors may want to have the option  to use them to make sense of their data.
It will help curators too!

**Comment by kimrutherford** [comment]
OK, I'll do this tonight UK time.

**Comment by kimrutherford** [comment]
> OK, I'll do this tonight UK time.

All done now.  Let me know if you spot any problems.

**Comment by ValWood** [comment]
looks good.
