### ISSUE TITLE
Genotype comment and  allele comments

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2511]
I think we want to display these comments on allele pages.
First I would like to check. Could I get a list of the comments?

**Comment by kimrutherford** [comment]
All the comments are here: pombe-embl/supporting_files/allele_comments.txt

**Comment by ValWood** [comment]
Thanks. I need to fix some of those, is it possible to add session ID or PMID?

**Comment by ValWood** [comment]
hang on, is this a file you write out, or a file we maintain (like allele synonyms)?
I'm confused but he time stamp (27 OCt), I have been adding allele comments in Canto regularly recently.

**Comment by kimrutherford** [comment]
> hang on, is this a file you write out, or a file we maintain

It's a file we maintain.

**Comment by ValWood** [comment]
OK, we can also add allele comments in Canto. That was the list I was asking for originally. I didn't know this file existed!

But now I realise I mean 'genotype' comments.  We have been using this to record "allele comments' historically, so it is a bit of a mix up.

**Comment by kimrutherford** [comment]
> OK, we can also add allele comments in Canto. That was the list I was asking for originally. 

Here are the session IDs, the genotype comments and the allele details for the genoype.  It's tab delimited.  Is that what you need?:
[genotype_comments.tsv.txt](https://github.com/pombase/canto/files/7818695/genotype_comments.tsv.txt)

**Comment by ValWood** [comment]
Yes it is the right thing, but it seems a really low number. I 'm sure I have added loads...
Maybe I am mistaken.
I will find some soon and check that they are in this list.

**Comment by ValWood** [comment]
I'll take this for now. I'll move genotype comments to the external "allele comments" where appropriate. Mostly these are also allele comments, and they apply to every allele so it doesn't make sense to assign to a specific session.

**Comment by ValWood** [comment]
new genotype comment to test
curs/c480fb02b530ca54

**Comment by kimrutherford** [comment]
> but it seems a really low number.

Sorry!  You're right.  I had the wrong query.

Here's the list after fixing the query: [genotype_comments.tsv.txt](https://github.com/pombase/canto/files/7858826/genotype_comments.tsv.txt)

> new genotype comment to test
> curs/c480fb02b530ca54

That's in the list.

**Comment by ValWood** [comment]
That's more like it! If you make create a log file I can review the allele and genotype comments.
Maybe we should maintain these in external files?

**Comment by kimrutherford** [comment]
I generated the log file by querying the Canto database.  For making a nightly log file it's easier to query from Chado.  At the moment the genotype comments aren't loaded into Chado but I'm fixing that now.  Once it's done a nightly log file is easy.

**Comment by kimrutherford** [comment]
> At the moment the genotype comments aren't loaded into Chado but I'm fixing that now.

That's done for tonight's load.  I'll add a log file next.

**Comment by kimrutherford** [comment]
> That's done for tonight's load. I'll add a log file next.

It turns out that the code that loads the Canto data into Chado wasn't storing the session ID of the genotypes.  I've fixed that for tonight's load which will make the necessary query easier.

**Comment by kimrutherford** [comment]
I've added a log file containing the genotypes and comments for tomorrow's load.

The output will be in a file ending with `.qc_queries` on Friday, with luck

I've added to the wiki: https://github.com/pombase/pombase-chado/wiki/Log-files-generated-by-the-nightly-load#qc-queries

**Comment by kimrutherford** [comment]
> The output will be in a file ending with .qc_queries on Friday, with luck

There was another load failure last night due to a typo.  I've fixed it and I'll check on Sunday or Monday.

**Comment by kimrutherford** [comment]
> There was another load failure last night due to a typo.

I checked again and needed to fix two typos this time - my typos are multiplying!  I'll check the logs again on Wednesday morning.

**Comment by kimrutherford** [comment]
> I think we want to display these comments on allele pages.

Shouldn't the genotype comments go on the genotype pages?

**Comment by ValWood** [comment]
Yes, the title of this ticket changed from allele comments at some point!

**Comment by kimrutherford** [comment]
> I checked again and needed to fix two typos this time - my typos are multiplying! I'll check the logs again on Wednesday morning.

I finally fixed all the typos.  I this file OK?:
https://curation.pombase.org/dumps/builds/pombase-build-2022-03-02/logs/log.2022-03-02-21-24-42.qc_queries

**Comment by ValWood** [comment]
yep.

I requested this though ;)
https://github.com/pombase/canto/issues/2545

**Comment by ValWood** [comment]
I need to fix a few..... there are phenotypes, allele descriptions etc in there ;)

**Comment by ValWood** [comment]
for example sometimes  the author put helpful (but un noticed comments in there if the phenotype did not exist like:
the pho8 deletion has decreased alkaline phosphatase activity in high zinc conditions	2c0b3f9b052bea9e

**Comment by ValWood** [comment]
OK, I tidied these. The ones which do not make sense as 'general ' genotype comments are removed, so these comments can now be displayed. 
I will make further improvements.

could you add this file to the logs?
and also check that the allele comments gets populated (it currently isn't)

**Comment by ValWood** [comment]
I don't see the genotype comments file (I think we have both allele and genotype comments?)

**Comment by ValWood** [comment]
Ah maybe we only have  genotype comments  in canto, and allele comments are in the external file.
Does the log file name need to change? I'm a bit confused by the external allele comments file. I can't remember why we needed it.

**Comment by kimrutherford** [comment]
> I see this file
> log.2022-03-02-21-24-42.allele-comments-from-supporting-data
> but it is empty?

That's the log file from loading `pombe-embl/supporting_files/allele_comments.txt` and there are no warnings.

> I don't see the genotype comments file (I think we have both allele and genotype comments?)

There genotype comments are here, sorry about the awkward name:
https://curation.pombase.org/dumps/builds/pombase-build-2022-03-02/logs/log.2022-03-02-21-24-42.qc_queries
There's an open issue about fixing that file name.

> I'm a bit confused by the external allele comments file. 

Was it created before we could add allele comments in Canto?  I can't remember.

**Comment by kimrutherford** [comment]
Sorry I've made a bit of a dog's breakfast of this issue.

**Comment by ValWood** [comment]
I think we both have!

**Comment by ValWood** [comment]
Let's discuss when we next speak it will be easier.
I can't remember the history, and I never touched the external file.

Aside from the 'load warning's  for the external file, it would be useful if there was a 'log;'  somewhere that I could see all of the contents of this field. Mainly so that I can re-factor some of them into the appropriate place (i.e the stuff connected to expression eventually), or adjust them so that they make a little bit more sense when displayed onthee allel/genotype pages .

**Comment by ValWood** [comment]
Actions
1. Val to migrate the ones which are allele comments to the allele comments file. https://github.com/pombase/curation/issues/3213

some comments are phenotypes
some are expression levels
some are allee descriptions
most are allele comments
etc

**Comment by ValWood** [comment]
I think we are done for this ticket for Canto.
I have a task on the curation tracker (1 in the comment above)

If you can confirm 2, plus you might need an addition to one of the website tickets for 3, then can close...

**Comment by kimrutherford** [comment]
> confirm that all allele comments are in the external file and all genotype comments are in Canto

I checked and that's the case.

**Comment by ValWood** [comment]
OK so only 3. left for this ticket, but is that covered by website tickets? If so this can close.

**Comment by kimrutherford** [comment]
There's a comment about allele comments: https://github.com/pombase/website/issues/1294#issuecomment-815287525

But I can't see one about genotype comments.  I've made an issue: pombase/website#1860
