### ISSUE TITLE
Genetic interactions  workflow from multigene phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2512]
We will need to  know that the "edit genetic interactions" option is available from here:

<img width="1015" alt="Screenshot 2022-01-06 at 18 24 18" src="https://user-images.githubusercontent.com/7359272/148432059-4e9eb042-fa0c-4008-b3bb-8ef0b9f66a74.png">

Otherwise most people will miss it in the edit pop up.

Don't worry about this for now, but we will need to make it clearer where GIs are added.

**Comment by ValWood** [comment]
I think this is one of the last things mentioned in this ticket:

https://github.com/pombase/canto/issues/2301#issuecomment-819361743

**Comment by kimrutherford** [comment]
> We will need to see that this option is available from here:

Could you explain what you mean?  Which option?

**Comment by ValWood** [comment]
Edited above, don't worry about this for now.

**Comment by kimrutherford** [comment]
Duplicate of #2516
