### ISSUE TITLE
Genetic interactions workflow show a table of genotype-genotype interactions on the summary page

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2513]
from:
#2301 (comment)

show a table of genotype-genotype interactions on the front page
(currently they're only visible in the edit dialog)

**Comment by kimrutherford** [comment]
We'll need to chat about what to show in the table.  In the edit dialog the information is split into two tables:

![genotype-interactions-table-1](https://user-images.githubusercontent.com/90474/150270695-95af8e00-796e-4624-bcdb-ff9dd235d12c.png)

![genotype-interactions-table-2](https://user-images.githubusercontent.com/90474/150270712-1b638a66-43f6-43e0-902b-ef79231e0a3a.png)

Should we do that on the summary page too?

**Comment by kimrutherford** [comment]
I've been working on this.  I've finally got to the point where I can get the tables to show up on the summary page.  I haven't put much thought into the table contents yet.

![genotype-interaction-table-3](https://user-images.githubusercontent.com/90474/151945549-225e4629-f210-4828-941a-1cd1e12b47cb.png)

**Comment by kimrutherford** [comment]
>  I've finally got to the point where I can get the tables to show up on the summary page.

That change is now in the test Canto instance.  There is more work to do, starting with:

  - [ ] editing
  - [ ] delete annotations?
  - [ ] make the genotype names into links

**Comment by ValWood** [comment]
Looking good!

**Comment by kimrutherford** [comment]
est. 1 hour to make genotypes clickable

**Comment by kimrutherford** [comment]
> make the genotype names into links

That's done now.

**Comment by kimrutherford** [comment]
Another issue is that the interaction table doesn't change when a new interaction is added.  The new interaction isn't visible until you reload the page or navigate away and then back again.

**Comment by kimrutherford** [comment]
> Another issue is that the interaction table doesn't change when a new interaction is added.

We now have a separate issue for that:
 - pombase/canto#2590

**Comment by kimrutherford** [comment]
The plan from Zoom:

  - add a column for the phenotype name of the double mutant
    - column name: "Double mutant phenotype"?
  - instead of a "View..." link for the single allele phenotype, put the phenotype name directly in the table
    - column name: "Rescued phenotype"?

**Comment by kimrutherford** [comment]
> The plan from Zoom:

I've done that.  Please let me know if you'd like me to change the headings. 

![image](https://user-images.githubusercontent.com/90474/178640658-19739475-fadc-4fc8-b45f-6f906fbb4090.png)

(Sorry about the dodgy biology)

If it's clearer we could use bullet points if there are multiple phenotypes:

![image](https://user-images.githubusercontent.com/90474/178638301-c39df295-a633-489d-ad80-1f539c68be98.png)

**Comment by ValWood** [comment]
Ignoring the biology, I think this is much clearer (and might be almost how we would want to represent the new style GIs  the gene pages with some tweaks.

I quite light the bullets...

**Comment by kimrutherford** [comment]
> If it's clearer we could use bullet points if there are multiple phenotypes:

I've added the bullet points.

**Comment by kimrutherford** [comment]
I think this is done so I'm closing it.  Please re-open if I've missed something.
