### ISSUE TITLE
Genetic interactions workflow, copy edit behaviour

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2514]
If I copy edit a multigene phenotype annotation that has a GI annotation attached to it, that is copied over too (probably only at display level, because it remains even if the genes are different)

**Comment by kimrutherford** [comment]
> If I copy edit a multigene phenotype annotation that has a GI annotation attached to it, that is copied over too

What change do we need?

> (probably only at display level, because it remains even if the genes are different)

I don't understand that bit.

**Comment by ValWood** [comment]
Easier to demo on next call.
