### ISSUE TITLE
Genetic interactions workflow reduced set of options only

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2515]
Whatever combination of alleles + phenotypes I select, I only seem to see two GI options

Synthetic growth defect
and
Synthetic lethality

**Comment by ValWood** [comment]
The table for relevance based on phenotype is here:
https://github.com/pombase/canto/issues/2301#issuecomment-765535014

**Comment by ValWood** [comment]
example 
https://curation.pombase.org/test/curs/f7d275c886036eab#

rga2+[Overexpression]
rga4Δ

**Comment by kimrutherford** [comment]
All the options are available for the `rga1Δ rga2Δ` genotype because `rga1Δ` has a phenotype annotation.

`rga2+[Overexpression]` and `rga4Δ` don't have annotations so it only shows the two options for `rga2+[Overexpression] rga4Δ`.

**Comment by kimrutherford** [comment]
I think this is now out of date.
