### ISSUE TITLE
Genetic interactions workflow, identify phenotypes with GIs associates

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2516]
https://github.com/pombase/canto/issues/2301#issuecomment-825531655

We need a way to see which phenotype annotations have interactions associated with them once they are curated (I.e a link out?)

**Comment by kimrutherford** [comment]
> We need a way to see which phenotype annotations have interactions associated with them once they are curated

I can't think of a tidy way to do this.  I'd rather not add a column because there are too many already.

**Comment by ValWood** [comment]
I agree that we don't want another label.
I wonder if we could flag the genotype in some way:

e.g.
<img width="807" alt="Screenshot 2022-02-16 at 14 45 40" src="https://user-images.githubusercontent.com/7359272/154289224-70bd5cc7-39e8-4a3d-8d65-d9d19eb66eb2.png">

**Comment by kimrutherford** [comment]
> I wonder if we could flag the existtance of a GI typ evidence code in the genotype box in some way:

That's a good idea.  It makes it visible and obvious that there's an interaction.  It could have a link to see the interaction in a dialog:

   Dosage rescue: **View details...**

**Comment by kimrutherford** [comment]
> Dosage rescue: **View details...**

Later on once editing is possible that could be: **View/edit interaction...**

**Comment by kimrutherford** [comment]
Copied from #2539:

----------------
Something like this, wording to be decided:

![interaction-link-1](https://user-images.githubusercontent.com/90474/156095795-d3a779d7-aff3-4bb5-8be7-9fc5d2507852.png)

**Comment by kimrutherford** [comment]
I've made a first rough attempt at implementing this.  The changes are in the test Canto but you'll need to shift-reload.  I'm a bit concerned about the number of dialog boxes.

The tables in the "Genetic interaction" section currently don't update when an interaction is added or removed.

For now the new links are worded like this:

![add-edit-interaction-row-link-2](https://user-images.githubusercontent.com/90474/157636578-35773609-8a9a-4d6a-ac47-55b50eac918a.png)

but it's easy to change.

**Comment by ValWood** [comment]
ping

**Comment by kimrutherford** [comment]
I'm waiting for you to try the current implementation and to comment.

**Comment by ValWood** [comment]
ok on my list for today!

**Comment by ValWood** [comment]
I'm sure the new links were visible and looked OK, but now I no longer see them...

**Comment by kimrutherford** [comment]
> I'm sure the new links were visible and looked OK, but now I no longer see them...

Could you try shift-reload for this problem too?

**Comment by ValWood** [comment]
Yep I see them again.

I think this looks a bit cluttered, do you?
<img width="684" alt="Screenshot 2022-03-23 at 18 45 55" src="https://user-images.githubusercontent.com/7359272/159773871-564d088d-587a-4db4-b2ed-c69777bca0e3.png">

Do you think it would look a bit better if there was a bit of white space to separate the alleles from the interaction link??

very minor 

1.
No associated interactions ...add interaction...
could be just
No associated interactions ...add ...
Maybe

2.
would te text be better as
Associated interactions (0)  ...add ...

3. Maybe we should say explicitly 
Associated _genetic_ interactions (0)  ...add ...

**Comment by kimrutherford** [comment]
Is this what you were thinking?  I've slightly reduced the font size of the interaction link too:

![add-edit-interaction-row-link-3](https://user-images.githubusercontent.com/90474/160035033-56f3fb8d-7310-4abd-a2bb-5622e9dfe9a3.png)

**Comment by ValWood** [comment]
Yes. I think this willbe fine. Not everything will have interactions anyways...

**Comment by kimrutherford** [comment]
I've committed that change.  I'll close this issue.  We can open other issues for changes and fixes.

**Comment by kimrutherford** [comment]
> I'm sure the new links were visible and looked OK, but now I no longer see them...

This was a while ago, but it was still happening to me so I did some diggin.  I've now tracked down the problem and fixed it so please let me know if you see it again.
