### ISSUE TITLE
Genetic interactions interface: refining the pull-down  options for genetic interaction annotations.

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2517]
Improving the available options for genetic interaction annotations.

- [x] If one of the alleles is "overexpression" only display:
Dosage Growth Defect 
Dosage Lethality
Dosage Rescue
Phenotypic Enhancement
Phenotypic Suppression

**Comment by ValWood** [comment]
- [ ] If both alleles are deletion, only display:
Dosage Growth Defect
Dosage Lethality
Dosage Rescue
Phenotypic Enhancement 
Phenotypic Suppression 
Synthetic Growth Defect
Synthetic Lethality
Synthetic Rescue

**Comment by ValWood** [comment]
corrected above comment

- [ ] if double mutant phenotype is a population phenotype, only show
Dosage Growth Defect
Dosage Lethality
Dosage Rescue
Synthetic Growth Defect
Synthetic Lethality
Synthetic Rescue

**Comment by ValWood** [comment]
Note, these are 'additive'
So, if 
If one of the alleles is "overexpression" 
AND
if double mutant phenotype is a population phenotype, only show

only display
Dosage Growth Defect
Dosage Lethality
Dosage Rescue

**Comment by ValWood** [comment]
if double mutant phenotype NOT is a population phenotype, only show
Phenotypic Enhancement
Phenotypic Suppression

**Comment by ValWood** [comment]
I just saw this ticket, I think there is partial overlap here
https://github.com/pombase/canto/issues/1988

**Comment by kimrutherford** [comment]
It would be helpful to come up with grouping names for these sets of evidence codes so that the configuration is understandable.  For example is there an ECO parent term that contains each set?

**Comment by kimrutherford** [comment]
Val to add labels for each group.

**Comment by ValWood** [comment]
These are the restrictions:
<img width="1083" alt="Evidence_allele_type_Venn" src="https://user-images.githubusercontent.com/7359272/153583935-d0ba64fa-46f8-4ea1-b9e8-091ed14ab24e.png">


Some combinations of  allele types/ phenoticpic class and evidence code are disallowed and so we will not display them in he avaiable evidence codes.
(I.e ) you cant have evidence which require an overexpression if both  alleles are deleted.

DGD = Dosage growth defect
DL = Dosage lethal
DR = Dosage rescue
SGD = Synthetic growth defect
SL = Synthetic lethal
SR = Synthetic rescue
PE = Phenotypic enhancement
PS = Phenotypic supression


The 'types' are 
Only Pop (DGD, DL, DR, SGD, SL,SR)
Not Pop (PE,PS)
both delta (SGD,SL,SR)
only O-EX (DGD, DL, DR, PE,PS)
And the  intersect combinations Only POP + only O-EX (DG, DL, DR)

We don’t need these 
Not POP + only O-EX  (PE,PS)   is the same set as “Not POP’
and Only POP + both delta  is the same as “Both delta’

For any other combination  that is none of the above display all codes

Doe that help?

**Comment by kimrutherford** [comment]
est. 2 days

**Comment by kimrutherford** [comment]
I've made a first attempt at implementing this but I haven't done a lot of testing.  I'm heading to bed and I'll do more tomorrow.

The test Canto will have the change in 30 minutes or so.  It's currently updating its ontology database which was necessary to implement the code that makes use of the population phenotype term.  The new code won't work properly until the update finishes.

**Comment by kimrutherford** [comment]
I've done a bit more testing and it seems OK.  Could you have a try and let me know?

**Comment by kimrutherford** [comment]
> I've done a bit more testing and it seems OK.

I obviously didn't test very well because while implementing #2533 I noticed that the evidence codes for when one allele is overexpressed were mis-configured.  Fixed now.

**Comment by ValWood** [comment]
I tested and this is looking  pretty good. I only found the relevant combinations of evidence codes.

a useful test would be to see  if any of our existing GIs violate these combinations! (for later)

I think we will notice pretty quickly if we have blocked something that should be allewed.

**Comment by ValWood** [comment]
I just tried to add an interaction to:

<img width="697" alt="Screenshot 2022-03-23 at 19 00 01" src="https://user-images.githubusercontent.com/7359272/159775738-1921a089-c10d-44c4-bd62-44afaa60cdbf.png">

I was going to complain that only one evidence code was available (PS), but I followed the logic and this is correct. I think I got the logic a bit wrong 9subtly) although you encoded correctly.

Only O-E means  if one allele is over expression it MUST be one of these types,
NOT  the inverse only allow  these types for O-E alleles

This would mean that for the allele and phenotype combination above I would also see PE and PS

**Comment by ValWood** [comment]
I will just re-cast the restrictions more explicitly for you to check

if one allele is overexpression, only display
Dosage Growth Defect
Dosage Lethality
Dosage Rescue
Phenotypic Enhancement
Phenotypic Suppression

SGD,SL,SR and should only be displayed if both alleles are delta (BUT other  types COULD be relevant to both alleles being delta, it is just that these particular evidence would not be relevant to any other alleles)

**Comment by ValWood** [comment]
SO, if both allels are delta, AND the phenotype is nOT a population phenotype 
PE and PS should. be displayed

**Comment by ValWood** [comment]
OK that worked.
I am not sure if some of these combinations ever occur in reality. That is something many could perhaps look at, as we might be able to block other combinations.
I think we are good here though.

**Comment by kimrutherford** [comment]
Should we close this issue?

**Comment by ValWood** [comment]
yep
