### ISSUE TITLE
Allow a way to add phenotypes to single alleles from the GI interface

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2520]
Often (perhaps usually), the single allele phenotype that is being suppressed wnt have been annotated, and we will need the ability to add it in a pop up (the single alleles will already exist, so it shouldn't be too complicated for the user).

There are 2 situations:
1.  There are some phenotypes, but they are not the correct ones:
<img width="819" alt="Screenshot 2022-01-08 at 16 46 28" src="https://user-images.githubusercontent.com/7359272/148652573-7b691061-42f4-4f88-b8f2-7713f6763057.png">

in this case we want the ability to add another phenotype

2. There will also be the situation where no  phenotypes are captured- we need to cater for this scenario too.

**Comment by ValWood** [comment]
Note: scenario 2 will occur most often for the growth andviability phenotypes.  Often people do not repeat these as there are many confirmations already.
We might  want to over-ride in this case (especially for lethality; that may already be the implemented).

**Comment by kimrutherford** [comment]
Just to check: currently we only show the directional interaction options if there is a phenotype annotated for one of the alleles.  Do we instead need to show all the interaction options and allow the user to add phenotypes to the single alleles?

**Comment by kimrutherford** [comment]
I've deployed a prototype for this change in the test Canto.  Let me know how you get on.

**Comment by ValWood** [comment]
This worked OK.
The only thing that seemed slightly odd is that when you select the direction, because the same pop-up is used, if there are no existing phenotypes it isn't totally obvious that anything changed, so I was trying to click "OK" before adding phenotypes.

I wonder , if the Add edit phenotype button was under the instruction, rather than after it, the change would be more obvious. Or maybe you have a better way?

**Comment by kimrutherford** [comment]
We can put some help text or headings in and around the existing details.  Would that help?

**Comment by kimrutherford** [comment]
Let's chat about this on the next Skype.
