### ISSUE TITLE
add evidence to "transcript level"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2521]
From @bahler 
"The tlh2 RNA is increased during stationary phase as assayed by RNA-seq. I could not capture this, because RNA-seq is not among the available Evidence codes to measure transcript levels. This evidence code should really be added as it is probably the most common assay now to measure transcription."

Can we add this to Canto?
I think we have avoided so far, because although we allow for HTP, we have not yet used for small-scale papers curated in Canto.

The evidence code is
https://evidenceontology.org/browse/#ECO_0000295

**Comment by kimrutherford** [comment]
Just to be sure: by "transcript level" do you mean "RNA level"?  Adding the evidence code is quick config change.

**Comment by ValWood** [comment]
sorry "RNA level"
