### ISSUE TITLE
Slow edit dialog with large session

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2527]
https://curation.pombase.org/pombe/curs/b2d538188151fdf1/ro/

The edit dialog opens very slowly in this session because of the large number of genes.

I've been investigating the bug and it's definitely fixable.

**Comment by kimrutherford** [comment]
Fixed!

**Comment by ValWood** [comment]
cool! I will try later. this will be good for many sessions ;)

**Comment by kimrutherford** [comment]
> this will be good for many sessions

Yep!  It should speed up any session that has lots of annotations.

**Comment by kimrutherford** [comment]
Hi Vitor!  Yes, I think the fix should help you too.

There have been a few other fixes and minor changes over the last few months so it's probably a good idea to a quick bit of testing before using the latest Canto on your main server.  Please let me know if you spot any problems.

**Comment by vmt25** [comment]
Cool. That is very good to know.
I thought the same. But my virtual machine, where my Canto test is, is not working at the moment, probably out of sync  between Mac OS and VirtualBox updates. Once it is back, I will give the updates a try.
