### ISSUE TITLE
geneotype management actions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2528]
In the genotype workflow there are options to add a GI

<img width="912" alt="Screenshot 2022-02-16 at 12 52 25" src="https://user-images.githubusercontent.com/7359272/154268565-df41edcf-9f4d-447d-8d69-c3aeee1e3e3d.png">

a) this option will only be relevant from multi gene phenotypes but is currently available from single
b) SInce this action requires a phenotype annotation should  we have a single menu item

Add phenotypes and genetic interactions?

**Comment by ValWood** [comment]
It would be great if we could streamline the workflow around genotypes, but I wonder if shorrt term the label could be improved.

Edit details -> Edit geneotype details
Copy and edit -> Copy and edit genotype

I know it is obvious for a curator, but because these options are a mixture of access to annotations and genotype actions this might be helpful  (no urgency for this, it would be useful to have feedback here)

**Comment by kimrutherford** [comment]
> SInce this action requires a phenotype annotation should we have a single menu item

Yep, I'll remove the second link. It's a accidental consequence of how the new genotype interactions are configured.

> but I wonder if short term the label could be improved.
> Edit details -> Edit geneotype details
> Copy and edit -> Copy and edit genotype

I think that's a good plan to make the menu items more obvious.

**Comment by kimrutherford** [comment]
> SInce this action requires a phenotype annotation should we have a single menu item

I've removed the link to start a genotype interaction.

>  wonder if short term the label could be improved.

I've made your suggested changes to the menu item labels.

**Comment by kimrutherford** [comment]
> no urgency for this, it would be useful to have feedback here

All the recent changes, including changing the menu labels, are only in the test Canto.

**Comment by kimrutherford** [comment]
Is there more to do on this issue?

**Comment by ValWood** [comment]
closing.
