### ISSUE TITLE
GI workflow: Make a separate "block" in pop-up for genetic interaction  annotation type?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2530]
<img width="1365" alt="Screenshot 2022-02-16 at 13 01 00" src="https://user-images.githubusercontent.com/7359272/154271631-370a5235-61f1-49be-a9b5-1f3a143ca3d0.png">

Because the genetic interaction will generate a separate annotation type, I wonder if it should have its own 'section'

**Add/edit genetic interaction type for genotype blah**

**Comment by kimrutherford** [comment]
How's this?

I think the wording of "Add/edit genetic interaction type for genotype ..." could be improved.  Should we remove "type" to get "Add/edit genetic interaction for genotype ..."?

Same with "Genetic interaction type (Optional)".  Could we change that to "Genetic interaction (Optional)"?

![extra-header-1](https://user-images.githubusercontent.com/90474/155919613-322ea8fc-6da5-4137-aa05-002ba4adee70.png)

**Comment by ValWood** [comment]
Looks good.
Agree, remove the word  'type'

**Comment by kimrutherford** [comment]
Those changes are now in the test Canto.
