### ISSUE TITLE
Rationale for placement of "new term suggestion" box

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2531]
I can't remember why we decided to separate this box  from the term curation and selection of any child terms?

<img width="1365" alt="Screenshot 2022-02-16 at 13 01 00" src="https://user-images.githubusercontent.com/7359272/154274653-df7688e9-6af5-47ac-9cd9-3202d0e9eb7e.png">

Can you? 

I wondered, since this option is not used much - if we could just remove this row and simply include a "suggest new term" button next to the term box once a term is selected?

**Comment by kimrutherford** [comment]
I can't remember.  There may not be a reason.

> I wondered, since this option is not used much - if we could just remove this row and simply include a "suggest new term" button next to the term box once a term is selected?

That makes sense.

**Comment by kimrutherford** [comment]
Here are two options.  The second option is less tidy but more explicit.  It might help if we change the button colour and size.

![move-term-suggest-1](https://user-images.githubusercontent.com/90474/165227923-7e19354e-9592-401a-b3c1-031d9e32edfe.png)

![move-term-suggest-2](https://user-images.githubusercontent.com/90474/165227933-dcff1f80-0398-445d-bae7-33df968b80db.png)

**Comment by ValWood** [comment]
Or the first option with test "Suggest a more specific term" ?



@manulera  any preferences/thoughts?

**Comment by manulera** [comment]
I like the first option as well. "Suggest a more specific term" feels like you would be necessarily suggesting a child term, while "new term" is more open ended. I imagine typically people suggest child terms and not so much strictly new terms?

**Comment by ValWood** [comment]
Yes you are right. Only sometimes they are more specific (although logically they should always be more specific than some existing term,  a new term is not necessarily requested with the correct parent as a placeholder).

**Comment by kimrutherford** [comment]
I've changed the code to add a "Suggest a new term" button.  If you're happy with the change I can release it straight away.  We can add some text to show when you mouse-over the new button if that would make things clearer.

![move-term-suggest-3](https://user-images.githubusercontent.com/90474/165444097-e71c65ba-fb24-4abe-8175-5b4e23774b1f.png)

![move-term-suggest-4](https://user-images.githubusercontent.com/90474/165444113-676c769a-06ec-4fc7-84d6-7c95f26cb4d6.png)

**Comment by ValWood** [comment]
The mouse over could say "Suggest a more specific term,  if you cannot find a related term use any term as a placeholder for your suggestion"

Can anyone make this clearer? This covers all cases, for instance people will often use abnormal placeholder  to suggest normal, or sensitive to suggest resistant. The term doesn't really matter, but obviously, we hope they searched with the right keywords and found something.

**Comment by manulera** [comment]
Mouse over sounds good to me 🐭

**Comment by kimrutherford** [comment]
Those changes are in the main Canto now.  Let me know if you see any problems.
