### ISSUE TITLE
GI workflow: change display statements for selection of direction

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2532]
At present options are

Dosage Growth Defect (growth defect in presence of overexpressed)
Dosage Lethality (inviable in the presence of overexpressed
Dosage Rescue (lethality or growth defect rescued by overrexpression of
Phenotypic enhancement (phenotype ehanced by)
Phenotype suppression (non-growth or non-viability phenotype suppressed by)
Synthetic growth defect
Synthetic lethality
Synthetic rescue (lethality or growth defect synthetically rescued by)

But when direction needs to be selected the evidence code is displayed, instead of:

- gad8-K263C(aaK263C)[Not assayed] **Phenotypic Enhancement** fkh2-T14A(aaT14A)[Not assayed]
- fkh2-T14A(aaT14A)[Not assayed] **Phenotypic Enhancement** gad8-K263C(aaK263C)[Not assayed]

It would be more intuitive to display:
 **Phenotypic Enhancement**

- gad8-K263C(aaK263C)[Not assayed] **phenotype ehanced by** fkh2-T14A(aaT14A)[Not assayed]
- fkh2-T14A(aaT14A)[Not assayed] **phenotype ehanced by** gad8-K263C(aaK263C)[Not assayed]

**Comment by kimrutherford** [comment]
That's done now.

**Comment by ValWood** [comment]
Anyway testing in your session, looks good.
