### ISSUE TITLE
GI workflow: Some directional evidence codes we can infer direction

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2533]
Dosage Growth Defect (growth defect in presence of overexpressed)
Dosage Lethality (inviable in the presence of overexpressed
Dosage Rescue (lethality or growth defect rescued by overrexpression of

For these 3 evidence codes, one of the genotypes will be overexpression, so we can  always infer that this will be in column 2 and do not require the user to select.

**Comment by kimrutherford** [comment]
est. 3 hours

**Comment by kimrutherford** [comment]
> For these 3 evidence codes, one of the genotypes will be overexpression

In this comment you mention 5 evidence codes: https://github.com/pombase/canto/issues/2517#issue-1096935251

Do we need a different list (with 3 ev. codes) when inferring the direction of the interaction?

**Comment by kimrutherford** [comment]
> In this comment you mention 5 evidence codes

For now I've implemented this using the 5 overexpression evidence codes we already had configured so we can start testing.

**Comment by ValWood** [comment]
You did it correctly.

**Comment by ValWood** [comment]
actually testing I see both directions still avaiable:
<img width="885" alt="Screenshot 2022-03-23 at 12 21 32" src="https://user-images.githubusercontent.com/7359272/159698122-ffea0843-f111-4800-9715-fd9c4c13fea1.png">

This was  for DR,dL, and DGD

**Comment by ValWood** [comment]
With this selection, no  GI types are available in the pull down:

<img width="864" alt="Screenshot 2022-03-23 at 12 25 55" src="https://user-images.githubusercontent.com/7359272/159698820-4ac9a55a-d37f-40ae-97a7-63de17f65818.png">

**Comment by ValWood** [comment]
i also changed the phenotype to "normal"  thinking that might make the "rescue" type phenotypes available, but it didn't.

Happy to discuss tomorrow if you like...if the issue isn't obvious.

**Comment by ValWood** [comment]
i'm testing in https://curation.pombase.org/test/curs/f3b1b527716d6117

**Comment by kimrutherford** [comment]
> i also changed the phenotype to "normal" thinking that might make the "rescue" type phenotypes available, but it didn't.

Could you try shift-reload?

**Comment by kimrutherford** [comment]
> actually testing I see both directions still avaiable:

That works for me so maybe shift-reload will fix that too?

**Comment by kimrutherford** [comment]
Is there anything else to do on this issue?

**Comment by ValWood** [comment]
I think you ate done here. If a problem, I can open new ticket.
