### ISSUE TITLE
change text on GI phenotype selection request (specific for evidence code)

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2534]
Currently

Select annotation phenotypes for gad8-K263C(aaK263C)[Overexpression]:

This should be tailored to the evidence type so that users are clear which phenotypes are required:

Select [insert appropriate text]  gad8-K263C(aaK263C)[Overexpression]:

Dosage Growth Defect = [ causes/exacerbates growth defect  of] 
Dosage Lethality = [symmetrical interaction],
Dosage Rescue   = [phenotype rescued by]
Phenotypic enhancement = [phenotype enhanced by]
Phenotype suppression = [phenotype suppressed by]
Synthetic growth defect = [causes/exacerbates growth defect  of] 
Synthetic lethality = [symmetrical interaction]
Synthetic rescue = [phenotype rescued by]

**Comment by kimrutherford** [comment]
> Dosage Lethality N/A?
> Synthetic lethality NA?

What should the text be in these cases?

**Comment by ValWood** [comment]
> What should the text be in these cases?

Those examples won't be applicable. I should have just excluded them (would have been clearer)

**Comment by kimrutherford** [comment]
> Those examples won't be applicable. I should have just excluded them (would have been clearer)

Does that mean we should exclude them from the interaction type drop-down?

**Comment by ValWood** [comment]
Sorry scrub that, they should be included in the drop-down, but they  do not need an explainer (because these skip the stage  where you select the direction)

We could add some text like [symmetrical interaction], would that work?

**Comment by ValWood** [comment]
Note: I edited the suggestions above to "causes/exacerbates growth defect  of"

**Comment by kimrutherford** [comment]
We have have some message like these configured already for the old style gene interactions (the bit in brackets).  Are there any you'd like to re-use?

![interaction-types-1](https://user-images.githubusercontent.com/90474/156948946-c595cbb4-c290-4065-8964-c6d8c7b0b1a0.png)

**Comment by ValWood** [comment]
i considered it, but these text (existing dropdown) are referring to the effect **of a phenotype** on a **genotype**, whereas the text suggested above are referring to the **phenotype affected by the interaction**, so the text needs a slightly different construction.

**Comment by kimrutherford** [comment]
OK, no problem.

**Comment by kimrutherford** [comment]
Just to check, should the text on the buttons below stay as it is or change too?:

![interaction-dialog-1](https://user-images.githubusercontent.com/90474/157008253-e5601c6c-9d7e-49cb-8a7d-af47d250b5b6.png)

**Comment by kimrutherford** [comment]
> Dosage Lethality = [symmetrical interaction],

In the current configuration Dosage Lethality isn't symmetrical.  So it that a typo?

The only configured symmetric interaction types at the moment are "Synthetic Growth Defect" and "Synthetic lethality".  In your comment you have:

> Synthetic growth defect = [causes/exacerbates growth defect of]
> Synthetic lethality = [symmetrical interaction]

Is your text for Synthetic growth defect a mistake?

**Comment by ValWood** [comment]
I think button text is fine...

**Comment by kimrutherford** [comment]
> I think button text is fine...

OK, I'll leave it as is.

I've added new text to the test Canto.
Except for "Dosage Lethality" which is still using the default text: Select affected phenotypes for ...

**Comment by ValWood** [comment]
Seems ok. I can open new tickets to tweak.
