### ISSUE TITLE
refine labels describing phenotype addition in GI interface

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2536]
Select phenotypes of blah to
Select *affected* phenotypes of blah
<img width="756" alt="Screenshot 2022-02-25 at 12 16 45" src="https://user-images.githubusercontent.com/7359272/155719692-a18c7322-8698-4b98-8391-11fa7761a4e0.png">

and here:
Select annotation phenotypes for blah ->
Select *affected* phenotypes of blah

<img width="628" alt="Screenshot 2022-02-25 at 12 16 34" src="https://user-images.githubusercontent.com/7359272/155719834-c0fda96b-5606-451f-81e9-31b0a4e61cfc.png">

**Comment by kimrutherford** [comment]
Done!
