### ISSUE TITLE
background log question

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2537]
https://curation.pombase.org/dumps/latest_build/logs/log.2022-02-24-21-51-04.chado_checks

I was surprised to see
h- 
leul-32  (this one is leu "L" fixing now)
ura4-294

In background checks? Are these not in the allowed ?

**Comment by ValWood** [comment]
and 
ura4-D18 leu1-32 ade6-210

**Comment by ValWood** [comment]
Do I need to ensure that the different background components are comma separated? I guess I must do because some currently have spaces like "constitutive promoter"

**Comment by kimrutherford** [comment]
> h-

I can't see that one, except for "M cell (h-)" which the code doesn't handle yet.

> leul-32 (this one is leu "L" fixing now)

There are no alleles with that name.

> ura4-294

I can't see an allele in Chado with that name.

> ura4-D18

There is an allele that name but I can't see any warning for it in the log.  I can only see a warning for "ura4-D19" with isn't an allele name in Chado.

> leu1-32

I can see a couple of warnings about "leu1-32h-" but I can't see any about "leu1-32".  Could you paste the line from the log?

> ade6-210

That appears twice in the log but neither case is a warning about that allele.

```
UNKNOWN,"mat1M-smt0 his2 leu1-32 ura4-DSE ade6-210 otr1R:ura4 + Spr156","mat1M-smt0 ura4-DSE otr1R:ura4 + Spr156"
```

That is a warning about "mat1M-smt0 ura4-DSE otr1R:ura4 + Spr156"

```
UNKNOWN,"ura4-D18 leu1-32 ade6-210 DS2","DS2"
```

And that is a warning about "DS2".  The "leu1-32" is in the second column which is the background as it appears in Chado.  The third column has the parts of the background that aren't valid, for example they aren't existing allele names.

Sorry it's a bit of a pain having comma separated values mixed in with other text.  I haven't got around to putting it in a separate file yet.

**Comment by ValWood** [comment]
many of my comments were irrelevant because I had forgotten that the problem allele was in the final column.

**Comment by kimrutherford** [comment]
Is there anything left to do here?

**Comment by ValWood** [comment]
nope, new ticket if required. This is for the future.
