### ISSUE TITLE
Add link/button for "Add/edit interaction" for each double mutant

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2539]
This needs to be quite obvious so users know how to add interactions they missed earlier.

**Comment by kimrutherford** [comment]
Something like this, wording to be decided:

![interaction-link-1](https://user-images.githubusercontent.com/90474/156095795-d3a779d7-aff3-4bb5-8be7-9fc5d2507852.png)

**Comment by ValWood** [comment]
yep

**Comment by kimrutherford** [comment]
I think this is a duplicate of #2516

**Comment by ValWood** [comment]
yep.
