### ISSUE TITLE
Make the Select/Add phenotype button clearer for interaction

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2541]
It's currently not obvious what to do next after selecting an interaction direction.

![phenotype-button-1](https://user-images.githubusercontent.com/90474/156085540-98a7be12-11d5-4822-9dae-23aa95916e2f.png)

**Comment by kimrutherford** [comment]
I've made the button bigger and blue.  Do you think that's enough to make it clear?

![phenotype-button-2](https://user-images.githubusercontent.com/90474/156085992-4a169c23-b798-456a-983f-448fd7d90943.png)

**Comment by ValWood** [comment]
Yes. We can always improve later.
