### ISSUE TITLE
Capturing expression in Canto (with implications for website allele /genotype)

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2544]
1. The ability to specify the ~plasmid~ promoter (mostly of these are stored in names, background and comments)

~2. If overexpression is selected, the ability  to specify the "fold" overexpression  (I.e 2X, 10X, 100X)
We probably need to discuss the details. 
We need this to 
a) be able to distinguish  different expression levels (and hence phenotypes) for overexpression alleles (and knockdowns)
b) to clean up backgrounds and comments
c) To fix some allele names which do not follow standard naming conventions
d) also ectopic expression~

example
Check cut12-s11
https://www.pombase.org/genotype/cut12.s11-G71V-amino_acid_mutation-expression-not_assayed
https://www.pombase.org/genotype/cut12.s11-G71V-amino_acid_mutation-expression-wild_type_product_level

**Comment by ValWood** [comment]
@manulera 
tagging

**Comment by manulera** [comment]
Hello,

Yes, mostly that, but I think the (4x) or (20x) should go in the `allele expression` column, not in the promoter, since the expression levels will depend on experimental conditions for a given promoter.

For example, It is not very common, but sometimes you see that people use nmt41-GFP-gene constructs just to tag proteins in their N-term. They then do the experiments in presence of thiamine (overexpression not induced). These nmt1 promoters are quite leaky, so even in the presence of thiamine they can produce equal or higher levels of protein than the wild type. nmt1 always that I have used it produces an overexpression even when repressed, nmt41 not so sure.

If used for a localisation experiment, people probably will not test whether the expression levels are higher than if GFP-gene was expressed from the normal promoter. I think this is mostly done to quickly tag a protein in the N-term when a C-term tag would be lethal or perturb the behaviour of the protein.

**Comment by ValWood** [comment]
@manulera says:

It was in my todo list to make an issue about this exactly. I think the problem is the ambiguous use of expression levels and alleles. We discussed this briefly before. I think allele description should be only concerned with describing the DNA sequence, and expression level should be a different field since it is conditional.

We could make promoter_changed a type of allele, and we could indicate which promoter has been used when it is known. Also, a change in promoter alone may not lead to a change in expression (it may need to be induced or repressed), but typically if a phenotype has been described it is safe to assume that the experiment has been conducted at conditions where the expression levels change.

You can see what I mean with the following query, you see that all alleles that come up in wild_type are from those that come from changes in expression levels (see that the only values are knockdown and overexpression):

<query model="genomic" view="Gene.symbol Gene.primaryIdentifier Gene.alleles.symbol Gene.alleles.type Gene.alleles.description Gene.alleles.expression" constraintLogic="(nil and A)" sortOrder="Gene.primaryIdentifier ASC">
   <constraint path="Gene.alleles.type" value="wild_type" op="=" code="A"/>
</query>

**Comment by ValWood** [comment]
@manulera says
And for deletion, I think it would be ok to say 'deletion' in the description.

**Comment by ValWood** [comment]
Let's discuss this after @manulera vacation.

There are 2 possible solutions. We could either extend the expression section to capture the plasmid. Manu's suggestion is more radical (in terms of changes and retrofitting).

Maybe we can think of a better way.
Some comments:
- Note that wild type use  is only allowed with knockdown and over-expression. 
- Maybe we should make it clear that in this case that the expressed protein  has wild-type sequence , but the expression level is changed?
- We definitely need somewhere sensible to store all of the promoter annotations that are currently in the background, and in allele type "other" but  we haven't always recorded the promoter  for WT expression changes.

 This isn't super urgent (but the longer it is put off the harder the retrofitting will be...) .. a few months won't make too much difference.

**Comment by manulera** [comment]
So we have a call on this when I come back?

**Comment by ValWood** [comment]
Yep.

**Comment by ValWood** [comment]
> We could still change the description field from wild_type to promoter_change.

I think this might be possible. However, I think we have also used when an alteration to the  allee is made in a second copy, but  the WT copy remains. They did not show up in the query because I think from memory, that although they are  displayed as single gene genotypes, they are modelled behind the scenes as multi-gene. We would need to check this.

**Comment by ValWood** [comment]
Can use this to illistrate the website issue to Kim
<img width="1126" alt="expression not_assayed_undefined" src="https://user-images.githubusercontent.com/7359272/186934194-021ef25f-7341-42ca-9a3c-8cb44bc5d59f.png">

**Comment by ValWood** [comment]
we don't need 
https://github.com/pombase/canto/issues/2629
becasue of this proposal.

**Comment by ValWood** [comment]
Another nice example  of how annotations are split
Ths should be high priority in the New Year because lots of annotations get split up:

https://www.pombase.org/genotype/asp1-H397A-H397A-amino_acid_mutation-expression-not_assayed
https://www.pombase.org/genotype/asp1-H397A-H397A-amino_acid_mutation-expression-wild_type_product_level

**Comment by ValWood** [comment]
Here are some examples of expression differences that need differentiating:
https://curation.pombase.org/dumps/latest_build/logs/log.2023-04-04-21-42-39.chado_checks.duplicate_allele_descriptions

**Comment by ValWood** [comment]
DECISION:


i) An extra option for ectopic expression

ii) Add additonal dialogue If you select Overexpression, Knockdown or  Ectopic
Pombe gene promoter [text box] ->  pick a gene 
Exogenous promoter [ free text and autocomplete from existing]

iii) Store promoter info in Chado

mock up; )

<img width="1090" alt="Screenshot 2023-04-05 at 12 36 12" src="https://user-images.githubusercontent.com/7359272/230074808-c49e7d2a-d227-4e31-a0c8-4612224ab7a8.png">

**Comment by ValWood** [comment]
I put this at high priority, since it will be useful to finish up all of the allele QC work.

**Comment by manulera** [comment]
Impressive mockup

**Comment by kimrutherford** [comment]
> An extra option for ectopic expression

Which allele types is that ectopic allowed for?

**Comment by ValWood** [comment]
@manulera 
All except deletion?

**Comment by kimrutherford** [comment]
>> Which allele types is that ectopic allowed for?
>
> All except deletion?

What about disruption?

**Comment by manulera** [comment]
> What about disruption?

Probably the case will not arise, but I think it's OK to allow the user to select it. I don't think it will ever happen though.

**Comment by kimrutherford** [comment]
> An extra option for ectopic expression

I've made a separate issue for that: pombase/canto#2723

**Comment by kimrutherford** [comment]
It's now in the test Canto if you'd like to try it:
https://curation.pombase.org/test/curs/4666975359de04dd/genotype_manage

**Comment by kimrutherford** [comment]
@jseager7 @CuzickA

Are these two new fields of use to PHI-base?  If not, I'll add a configuration item to hide them.

Also we added Ectopic expression a while ago and forgot to discuss it with you.  Does it make sense for PHI-base?

**Comment by ValWood** [comment]
@kimrutherford  sorry I haven't tested this yet. It's on my list for today.
v

**Comment by jseager7** [comment]
> Also we added Ectopic expression a while ago and forgot to discuss it with you. Does it make sense for PHI-base?

PHI-base is already using ectopic expression in curation sessions.

**Comment by CuzickA** [comment]
> > Also we added Ectopic expression a while ago and forgot to discuss it with you. Does it make sense for PHI-base?
> 
> PHI-base is already using ectopic expression in curation sessions.

I haven't seen the ectopic expression option in PHI-Canto.

**Comment by CuzickA** [comment]
> @jseager7 @CuzickA
> 
> Are these two new fields of use to PHI-base? If not, I'll add a configuration item to hide them.
> 
> Also we added Ectopic expression a while ago and forgot to discuss it with you. Does it make sense for PHI-base?

I think that both of the proposed new fields would be useful in PHI-Canto. This type of information is often recorded in our comments section.

**Comment by jseager7** [comment]
> I haven't seen the ectopic expression option in PHI-Canto.

@CuzickA One of our curators said that they selected the ectopic expression level for PMID:12543662: https://github.com/PHI-base/curation/issues/135#issuecomment-1582852691

Was that on the demo server?

**Comment by CuzickA** [comment]
> > I haven't seen the ectopic expression option in PHI-Canto.
> 
> @CuzickA One of our curators said that they selected the ectopic expression level for PMID:12543662: [PHI-base/curation#135 (comment)](https://github.com/PHI-base/curation/issues/135#issuecomment-1582852691)
> 
> Was that on the demo server?

Ok, thanks for spotting that. I haven't managed to work through some of those tickets yet.

I've just tried and it looks like ectopic expression is available on the main PHI-Canto server but not the demo server.

**Comment by ValWood** [comment]
I tested, but I don't see where  the information goes. I don't see it showing up alongside the genotype in genotype management.
MAybe we can discuss tomorrow.

I'm hoping this can resolve duplicate allele descriptions like:
SPCC24B10.14c	xlf1.AA	c23b5043b024b0a5	T180A,S192A	nmt41-xlf1.AA	c23b5043b024b0a5
  SPCC24B10.14c	xlf1.AA	c23b5043b024b0a5	T180A,S192A	nmt1-xlf1.AA	c23b5043b024b0a5

but how will we deal with expression levels altered by different copy number:
SPBC12D12.02c	cdm1+(1 copy)	b5089e77a1ba9a37	wild type	cdm1+(3 copies)	b5089e77a1ba9a37
  SPBC1734.02c	cdc27+(1 copy)	b5089e77a1ba9a37	wild type	cdc27+(3 copies)	b5089e77a1ba9a37
  SPBC336.04	cdc6+(1 copy)	b5089e77a1ba9a37	wild type	cdc6+(3 copies)	b5089e77a1ba9a37

**Comment by ValWood** [comment]
> but how will we deal with expression levels altered by different copy number:
this is a question for when we chat tomorrow...

**Comment by CuzickA** [comment]
I don't see the option for entering promoter information yet (in the main PHI-Canto).

**Comment by jseager7** [comment]
> I've just tried and it looks like ectopic expression is available on the main PHI-Canto server but not the demo server.

That's because I haven't updated the demo server in a while. I'll hide this comment thread now.

**Comment by jseager7** [comment]
> I don't see the option for entering promoter information yet (in the main PHI-Canto).

I haven't updated PHI-Canto with these fields yet because PomBase isn't done with testing them.

**Comment by kimrutherford** [comment]
> I tested, but I don't see where the information goes. I don't see it showing up alongside the genotype in genotype management.
> MAybe we can discuss tomorrow.

Yep, that's one of the things to discuss.  Currently you can only see the information if you edit the allele.

**Comment by kimrutherford** [comment]
> I haven't updated PHI-Canto with these fields yet because PomBase isn't done with testing them.

Hi James.  Yep, it's still on a branch.  Unfortunately, it will need a schema update when deployed.

**Comment by manulera** [comment]
Hello, I had a look at this and I think the interface makes sense. However, it should not be possible to add a value for both "gene promoter" and "exogenous promoter". It should be one or the other.

**Comment by manulera** [comment]
For now, display in square brackets after the expression level.

- Gene promoters: P.gene-name (e.g. Ectopic[P.ase1])
- Named promoters: used only the name (e.g. Overexpression[P3nmt1], Knockdown[P41nmt1])

**Comment by manulera** [comment]
Ideally, exogenous promoters should be auto-completed

**Comment by kimrutherford** [comment]
> However, it should not be possible to add a value for both "gene promoter" and "exogenous promoter".

What do you think of this interface instead?  It's in the test Canto if you'd like to try it.

![image](https://github.com/pombase/canto/assets/90474/3b72745d-4851-4394-bf00-db8b045ce3ec)

-------

![image](https://github.com/pombase/canto/assets/90474/8b5377ac-2da3-4fb8-8037-338a5364d074)

--------

![image](https://github.com/pombase/canto/assets/90474/80fae8e2-2636-4e22-8365-efa8aa12f86b)

**Comment by manulera** [comment]
Hi @kimrutherford. It's perfect like that, I think. The only thing is I would remove the first option ("None"), so the default is that no option is ticked. The title could then be "Used promoter (optional)". Alternatively, we can also replace "None" by "Unspecified".

There are cases where overexpression or knockdown can be driven without changing the promoter, so you would not want to say "None":

* Overexpression through gene duplication in the genome or in a plasmid.
* Knockdown through RNA degradation, like the CRISPr method we mentioned the other day.

**Comment by ValWood** [comment]
Nice

**Comment by manulera** [comment]
An extra possibility could be `multi-copy` + number of copies (should be bigger than 1)

**Comment by ValWood** [comment]
pinging myself for discussion when Kimback

**Comment by kimrutherford** [comment]
Hi Val.  Did you mention on a call that this was an issue that think needs doing soon?

The prototype is still available in the test Canto: https://curation.pombase.org/test/curs/4666975359de04dd/genotype_manage

**Comment by kimrutherford** [comment]
> we can also replace "None" by "Unspecified".

I've done that since was quick.  I've also fixed a few bugs.

**Comment by ValWood** [comment]
Thanks I'l check this out before we next chat.

**Comment by kimrutherford** [comment]
I've started work on pombase/pombase-chado#1087 but I noticed that the promoter details were being written to the JSON export file incorrectly.  I'm fixing that now.

Note to self, the changes for this issue are on this branch:  https://github.com/pombase/canto/tree/issue-2544-allele-promoters

**Comment by kimrutherford** [comment]
> I noticed that the promoter details were being written to the JSON export file incorrectly. I'm fixing that now.

That's fixed now.

I've also fixed the Canto code for editing alleles to understand that alleles/genotypes with different promoters are distinct.  So there's now no problem having multiple genotypes that are identical except for the promoter of an allele.

For now, alleles with promoters are shown like this in the genotype list:
```
abc1-a(F124D)[Overexpression]{promoter:SPBC15D4.03}
```
or
```
abc1-a(F124D)[Ectopic]{exogenous_promoter:ADH1}
```

**Comment by ValWood** [comment]
Currently we have:

<img width="529" alt="Screenshot 2024-02-21 at 13 48 34" src="https://github.com/pombase/curation/assets/7359272/abfa0f19-db0c-4338-8610-d675bfac8f80">

When people choose WT or not assayed they don't need to add a promoter (fine).

When we say "exogenous promoter"  does this "introduced into a cell or organism from an external source" mean just that it is plasmid expressed, or that it is 'external DNA' . I guess  with the current labelling  I would not know which 'type ' to use for   the S. cerevisiae ADH promoter)


- should be precise  relabel "gene" to "promoter swap (fission yeast)" ?
- Plasmid expressed (which would  cover everything expressed on a plasmid)

@manulera  I'm not sure what the best axis of classification are here.
Are we more bothered about plasmid vs genome integrated ?

This would only work if "exogenous promoters (i.e promoters from other species)" are always introduced on plasmids and not integrated (in which case "plasmid expressed + exogenous integrated).

Does this make sense?

**Comment by manulera** [comment]
> should be precise relabel "gene" to "promoter swap (fission yeast)" ?

I agree with this

> Plasmid expressed (which would cover everything expressed on a plasmid)

I don't think that when we started talking about this I was thinking of making a difference between genome-integrated constructs vs. plasmids. I can see that this is important because cells may have more than one copy of the plasmid, but this is parallel to the type of promoter used (see below).

> This would only work if "exogenous promoters (i.e promoters from other species)" are always introduced on plasmids and not integrated (in which case "plasmid expressed + exogenous integrated).

That's not the case, you could drive the expression of a gene under the same exogenous promoter from a plasmid or from the genome.

Sorry not to bring a solution here... I personally don't think that the distinction plasmid / genome is so important, especially for the ectopic expression case (the altered context of expression is what matters, which is in principle evident from the promoter).

For overexpression/knockdown, the level of overexpression is given by the plasmid number & primer, but what ultimately matters is that the protein is overexpressed, not so much how.

The only case that remains is how we capture the fact that sometimes people will overexpress an allele of a gene from a plasmid, in a strain where the wild-type allele is still there. In that case, I guess we can just force the users to add the wild-type allele to the genotype (e.g. `ase1+ ase1-S3A(Overexpression)`).

**Comment by ValWood** [comment]
So are you saying we need not worry about the plasmid at all,  we  expect people to specify  P3nmt1 as promoter swap
nmt1? and only use exogenous for foreign promoters? this would simplify and get around all the different names used.....

> In that case, I guess we can just force the users to add the wild-type allele to the genotype (e.g. ase1+ ase1-S3A(Overexpression)).

this is what I have done in the past (usually in the background)

**Comment by manulera** [comment]
Yes, I think that is a good compromise.

Also I am remembering now that we discussed at some point about overexpression of non-wild-type alleles. In the example above `ase1+ ase1-S3A`, if `ase1-S3A` is expressed from a nmt1 promoter from a plasmid, the control should be a strain (over)expressing wild-type ase1 (`ase1+`) from the same plasmid. Because we are comparing those two conditions, in principle the phenotype comes from the difference between `ase1+` and `ase1-S3A`, and not from the overexpression, so I would not annotate it as overexpression now, but I am sure I have done this in the past.

**Comment by ValWood** [comment]
Hi Kim,
Sorry for the dealy on this one. We can change the text to "promoter swap (fission yeast)"
and make this live

**Comment by kimrutherford** [comment]
> Sorry for the dealy on this one. We can change the text to "promoter swap (fission yeast)" and make this live

I've merged the code into the branch.  It took a while because there were a lot of conflicts to sort out.  I'll deploy the change when oliver1 is back.

**Comment by kimrutherford** [comment]
> "promoter swap (fission yeast)"

Would "promoter swap (Schizosaccharomyces pombe)" or "promoter swap (S. pombe)" be OK?  We don't have "fission yeast" in the config or in the Canto database (this has to work for non-pombe Canto instances too).

**Comment by kimrutherford** [comment]
> I've merged the code into the branch

I meant, I've merged the promoter branch into the main branch.

**Comment by kimrutherford** [comment]
> Would "promoter swap (Schizosaccharomyces pombe)" or "promoter swap (S. pombe)" be OK?

![image](https://github.com/pombase/canto/assets/90474/4f89bca7-4ae7-4feb-b708-3d6a0a9b323e)

**Comment by ValWood** [comment]
> Would "promoter swap (Schizosaccharomyces pombe)" or "promoter swap (S. pombe)" be OK?

yep

**Comment by kimrutherford** [comment]
OK, great.  I've implemented that ready for when oliver1 is back.

**Comment by ValWood** [comment]
@PCarme  and I tried to use the new promoter feature but we couldn't see it?

**Comment by kimrutherford** [comment]
Ah, sorry.  I never got around to updating the main Canto with the change.  We will need 10-20 minutes of down time to do the upgrade.

**Comment by kimrutherford** [comment]
> I never got around to updating the main Canto with the change. We will need 10-20 minutes of down time to do the upgrade.

That's done now.

We should discuss how the promoters should look in the genotype list.

**Comment by ValWood** [comment]
I'm going to do this session now and we can use as an example

mad1~10%,SPBC3D6.04c:allele-28,nmt81 promoter,{ed9652a888c24c94}
mad1~30%,SPBC3D6.04c:allele-29,bub3 promoter,{ed9652a888c24c94}
mad1~300%,SPBC3D6.04c:allele-31,ark1 promoter,{ed9652a888c24c94}
mad1~500%,SPBC3D6.04c:allele-30,nmt1 promoter,{ed9652a888c24c94}
mad2~10%,SPBC20F10.06:allele-14,mad3 promoter,{ed9652a888c24c94}
mad2~65%,SPBC20F10.06:allele-11,hphNT1 cassette in promoter,{ed9652a888c24c94}
mad3~30%,SPCC1795.01c:allele-10,hphNT1 cassette in promoter,{ed9652a888c24c94}

**Comment by ValWood** [comment]
I've done this one, it looks like this in Canto genotype list: 

<img width="917" alt="Screenshot 2024-03-18 at 10 08 55" src="https://github.com/pombase/canto/assets/7359272/aae997fb-8d30-4da2-ada3-487c1e854787">


which is fine?

**Comment by kimrutherford** [comment]
Yep, that's how it looks for now.  I'll check Chado in the morning.

**Comment by ValWood** [comment]
Yep, promoter should be in a separate column to be precise.

I also used the genotype comment fie;ld to recorded the % overexpression
