### ISSUE TITLE
Canto page loading slow

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2547]
Everytime I access a publication in Canto I get

<img width="1073" alt="Screenshot 2022-03-10 at 16 30 06" src="https://user-images.githubusercontent.com/7359272/157709613-76f083f2-3cf1-492a-bfb3-a46ed503f045.png">

it appears only when I reload the page?

**Comment by kimrutherford** [comment]
Very odd!  I'm seeing that too now, but only very occasionally - less than one time in 20 reload.

Are you using Chrome?  Which version?

**Comment by ValWood** [comment]
Version 98.0.4758.109 (Official Build) (x86_64)

**Comment by kimrutherford** [comment]
I have a slightly newer Chrome but I still sometimes see the problem.  I can't reproduce it in Firefox.  I did some Google searching and got no clues.  I'll try some other browsers.

**Comment by ValWood** [comment]
It doesn't bother me and it seems sporadic. It doesn't happen all the time, and then it does.
I just worry that if it happens to community curators they think it is broken as they might not think to reload......nobody has mentioned it though...
