### ISSUE TITLE
copy edit  phenotype annotation  brings associated genetic interaction

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2548]
If I copy edit a ~interaction~ phenotype annotation and change the genotype an attached genetic interaction remains.

**Comment by kimrutherford** [comment]
> If I copy edit and interaction and change the genotype an attached genetic interaction remains.

Yep, as it's part of the same annotation.  By default everything in an annotation gets copied by copy and edit.  Should we change that behavior?

**Comment by ValWood** [comment]
For the genetic interaction if the genotype is changed I think it it should 'disappear' , because the interaction is strictly attached to the genotype.

**Comment by kimrutherford** [comment]
I've changed the code so that if you copy and edit, the interaction(s) are cleared.

**Comment by kimrutherford** [comment]
> For the genetic interaction if the genotype is changed I think it it should 'disappear' 

I think you may have found a bug.  It shouldn't be possible to change the genotype if there are attached interactions.  Do you remember the details?

**Comment by ValWood** [comment]
I'm not sure now what the behaviusr should be.

Take the  first multi gene phenotype in this session
https://curation.pombase.org/test/curs/f3b1b527716d6117

it has a GI atttahced. 
Now when  you go to copy edit, it says there are no interactions.

So I can change the genotype.

I think this is OK.

I can open ticket if it seems odd later.

**Comment by ValWood** [comment]
It does seem odd that it says "there are no annotations for this phenotype" when you copy and edit, if you haven't edited anything.

But,  as soon as you edit the genetoype or the phenotype the interactions are incorrect.  So this might be the best behavior?
