### ISSUE TITLE
genetic interactions links

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2549]
For some reason, i always need to "shift reload" to see the
"Associated genetic interactions (1) - [view or add ...]()" 
links. 
Even though I am using the same session.

**Comment by ValWood** [comment]
Also does not appear when I make a new muti-gene annotation:

<img width="926" alt="Screenshot 2022-03-29 at 09 12 12" src="https://user-images.githubusercontent.com/7359272/160567825-7fb46f31-9db3-4631-9b16-dd8bac096da6.png">

**Comment by kimrutherford** [comment]
It's happening to me too and I don't know why.  I'll work on it.

**Comment by kimrutherford** [comment]
I think this is fixed now so I'll close this issue.  Please re-open if you see it again.
