### ISSUE TITLE
The phenotype is requested for the wrong allele of a multi gene phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2550]
Here wee1 is the 'rescued phenotye"

<img width="902" alt="Screenshot 2022-03-29 at 08 58 26" src="https://user-images.githubusercontent.com/7359272/160562996-ee22c681-2a7c-4b87-9daf-1a6b6b3c5359.png">

and here cdc5... is the rescued phenotype

<img width="677" alt="Screenshot 2022-03-29 at 08 55 56" src="https://user-images.githubusercontent.com/7359272/160563025-ef00f53b-eb7e-4e94-a5b4-b70f7221a3f1.png">

**Comment by kimrutherford** [comment]
Is it the wrong way around in all cases?

**Comment by ValWood** [comment]
It is where I checked. I id not check them all. I will do this shortly...

**Comment by ValWood** [comment]
I was misreading it!

Possibly it should be more explicit , like"

Select wee1 delta phenotypes affected by cdc1 overexpression

Select phenotypes affected by cdc1 overexpression reads as if cdc1 phenotypes are wanted

**Comment by ValWood** [comment]
Oh it is the wrong way around. Its also confused by the wording.

**Comment by ValWood** [comment]
DGD = Dosage growth defect. ->incorrect alleles phenotypes requested
DL = Dosage lethal.  N/A no starting phenotype is required for dosage lethal
DR = Dosage rescue. ->incorrect alleles phenotypes requested
PE = Phenotypic enhancement. ->incorrect alleles phenotypes requested
PS = Phenotypic supression. ->incorrect alleles phenotypes requested

**Comment by kimrutherford** [comment]
> DL = Dosage lethal. N/A no starting phenotype is required for dosage lethal

Could you explain that one?

I'm a bit confused but I had a go at changing the dialog to match your suggestion.  Have I understood?  The text is a bit repetitive now. 

![interaction-annotation-1](https://user-images.githubusercontent.com/90474/160756493-fb335aa0-656b-4d60-a6c9-b67264876b0e.png)

**Comment by ValWood** [comment]
It does look a bit repetitive, but it is clearer. Once I get using (testing more), I can probably refine the dialog. 
For instance here we likely don't need the first line, but I would like to re check the previous steps first.



The starting phenotype will always be "viable", but I don't think we need to force people to explicitly make a viable phenotype for the 2 starting mutations (they will exist in other sessions for sure).
I can explain more easily in person,

**Comment by ValWood** [comment]
I will test again later...

**Comment by kimrutherford** [comment]
OK.  I've updated the Canto instance with this change.

**Comment by ValWood** [comment]
- [ ] Dosage growth defect
- [ ]  Dosage lethal
- [ ] DR = Dosage rescue
- [ ] SGD = Synthetic growth defect
- [ ] Synthetic lethal
- [ ] Synthetic rescue
- [ ] Phenotypic enhancement
- [ ] m Phenotypic supression

**Comment by ValWood** [comment]
Synthetic rescue is the wrong way around.
<img width="898" alt="Screenshot 2022-03-31 at 15 50 20" src="https://user-images.githubusercontent.com/7359272/161084456-42c70b10-cc0c-454f-bfb9-92a2deaee931.png">

If I select that  cdc5-balh os rescued by wss1 delta, the phenotypes I  am presented with should. e phenotypes of cdc5-blah (the rescued phenotypes)

The pop-up :
<img width="886" alt="Screenshot 2022-03-31 at 15 52 36" src="https://user-images.githubusercontent.com/7359272/161084979-83694d80-6f7b-4393-87a8-3af9daedc6b4.png">

says 
"add new phenotypes for wss1 delta" but this should be "cdc5-blah"

**Comment by ValWood** [comment]
Dosage growth defect is the wrong way around:

<img width="895" alt="Screenshot 2022-03-31 at 15 57 18" src="https://user-images.githubusercontent.com/7359272/161086317-5185c486-6633-4f7e-b06d-bd7f1bcf052e.png">



wee1 delta growth defect in presence of overexpressed cdc1 (correct way round)
but 

Select wee1delta causes/exacerbates growth defect of cdc1+ [overexpression]
should be
cdc1+ [overexpression]  causes/exacerbates growth wee1delta

But these 2 lines say the same thing in a reciprocal manner, so. we only need 1 statement.

either
wee1 delta growth defect in presence of overexpressed cdc1 (correct way round)
OR
cdc1+ [overexpression]  causes/exacerbates growth defect of wee1delta (I think this is more understandable)

Then the next screen says:

<img width="903" alt="Screenshot 2022-03-31 at 16 04 54" src="https://user-images.githubusercontent.com/7359272/161087604-8580f10c-7980-444b-b3f3-e4ef5a5aa37d.png">

this is a bit confusing too (I don't think the word "select" is required?, ) the title should be whatever we decide above

**cdc1+ [overexpression]  causes/exacerbates growth defect of wee1delta**
and here we would see the wee1 population phenotypes, or be asked to add one.

**Comment by ValWood** [comment]
Dosage rescue is partially correct.

The statemnts here are correct (although redundant with each other)
<img width="901" alt="Screenshot 2022-03-31 at 16 13 32" src="https://user-images.githubusercontent.com/7359272/161089671-761bb5fd-6005-469c-8eff-f94216093d22.png">


but on the next screen I am asked for phenotypes of  cdc1 when it should be the rescued phenotypes of wee1
<img width="877" alt="Screenshot 2022-03-31 at 16 16 59" src="https://user-images.githubusercontent.com/7359272/161090210-33559973-b1e6-4ffd-9d28-d8a76231881b.png">

**Comment by ValWood** [comment]
Phenotypic enhancement is partially correct:

<img width="880" alt="Screenshot 2022-03-31 at 16 23 25" src="https://user-images.githubusercontent.com/7359272/161091531-04446d6f-c641-496d-849d-6653030312cd.png">

but in the next screen, for this direction we want enhanced phenotypes of cdc1
Better wording here would be:
Select cdc1delta phenotypes enhanced by wee1 delta (and the lines are redundant with each other)

**Comment by ValWood** [comment]
Phenotypic suppression is incorrect in the same way as phenotypic. enhancement (the phenotypes of the wrong gene are requested)

**Comment by kimrutherford** [comment]
Should we always be asking for phenotypes of the first genotype in the statements?

**Comment by ValWood** [comment]
yes, that's correct  it's always the gene that is rescued/enhanced, not the one doing the enhancing.

**Comment by kimrutherford** [comment]
OK, thanks.  That's a nice simple rule to implement.  I was getting a bit confused.

**Comment by kimrutherford** [comment]
> Should we always be asking for phenotypes of the first genotype in the statements?

Except that not true in this case?:

> cdc1+ [overexpression] causes/exacerbates growth defect of wee1delta

I'm getting quite confused.  I think it would be quicker if we could spend 20 minutes on a call sometime.  I can make changes as we chat until it's right.

**Comment by ValWood** [comment]
Right, sorry. It's not always the first one in the statement. But it always the phenotype of the gene that is been "acted on" i.e phenotype enhanced, phenotype rescued.

we could change the way around that we present
cdc1+ [overexpression] causes/exacerbates growth wee1delta.

We can do it on  a call...

**Comment by kimrutherford** [comment]
> we could change the way around that we present

That would help because it would make the configuration easier.

**Comment by kimrutherford** [comment]
I've updated the test Canto with the changes we talked about.

Tomorrow I'll change things so that Dosage Growth Defect and Dosage Lethality don't need a single allele phenotype.

**Comment by kimrutherford** [comment]
> Tomorrow I'll change things so that Dosage Growth Defect and Dosage Lethality don't need a single allele phenotype.

I've had a first go at this but it's likely to be bit buggy.  I've including the change in the test Canto in case you'd like to try it.  I'll do some more work on it next week.

I also need to do some database schema changes to cope better with storing these interactions.

Note to self, investigate this JS console error: ``` Error: [ngRepeat:dupes] ```

**Comment by ValWood** [comment]
will test soon, today or more likely tomorrow...

**Comment by kimrutherford** [comment]
>>  Tomorrow I'll change things so that Dosage Growth Defect and Dosage Lethality don't need a single allele phenotype.
>
> I've had a first go at this but it's likely to be bit buggy. I've including the change in the test Canto in case you'd like to try it. I'll do some more work on it next week.
> I also need to do some database schema changes to cope better with storing these interaction

I've made various fixes and I've made the schema changes that were needed.  I can't guarantee that it's bug free yet but I think it's working better.

**Comment by ValWood** [comment]
Checked. I think it is all working OK now!

**Comment by kimrutherford** [comment]
> Checked. I think it is all working OK now!

Thanks.  I'll close this because it's a bit long and we can open new issues for bugs and changes.
