### ISSUE TITLE
phenotype restictions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2551]
transferred from https://github.com/pombase/canto/issues/2301

In the pop-up to select the rescued phenotype 
1. Don't display any normal phenotypes

~2. Only  display "population phenotypes" (i.e lethality) for 
Dosage growth defect
Synthetic Rescue
2. Only  display NONE  "population phenotypes" for 
Phenotypic Enhancement
Phenotypic Suppression~ 

covered by table below

**Comment by ValWood** [comment]
Interaction type  |  symmetric? | Phenotype to report |  FYPO branch restriction for phenotype acted on | Notes
--- | --- | --- | --- | ---
Dosage rescue | asymmetric | rescued phenotype (genotype1) | FYPO:0000046 decreased cell population growth OR FYPO:0002061 inviable vegetative cell population | 
Phenotypic enhancement | asymmetric | enhanced  phenotype (genotype1) |  NOT (FYPO:0000046 decreased cell population growth OR FYPO:0002061 inviable vegetative cell population) | 
Phenotypic suppression  | asymmetric|  suppressed phenotype (genotype1) |   NOT (FYPO:0000046 decreased cell population growth OR FYPO:0002061 inviable vegetative cell population) | 
Synthetic rescue | asymmetric | rescued phenotype (inviability or growth defect) (genotype1) | FYPO:0000046 decreased cell population growth OR FYPO:0002061 inviable vegetative cell population | prompt if no multi-allele  annotation  for allele combination in FYPO:0002060 viable vegetative cell population OR FYPO:0003937 increased cell population growth
Synthetic growth defect | symmetric |  outcome is compromised growth, do not need to record here? | n/a | prompt if no multi-allele  annotation  for allele combination in  FYPO:0000046 decreased cell population growth branch | 
Synthetic lethality  | symmetric |  outcome is inviability, do not need to record here | n/a | prompt if no multi-allele  annotation   for allele combination in FYPO:0002061 inviable vegetative cell population  branch
Dosage lethality | symmetric |  outcome is inviability, do not need to record here | n/a | prompt if no multi-allele  annotation  for allele combination in FYPO:0002061 inviable vegetative cell population branch

**Comment by ValWood** [comment]
still need to decide about this:

-  [ ]  Probably for the phenotypes with "assayed using" these are unlikely to be used in GIs. We could therefore maybe collapse them to show the phenotype only, without the extension.

**Comment by kimrutherford** [comment]
Is this issue related to: https://github.com/pombase/canto/issues/2565
?

I'm a bit confused.
