### ISSUE TITLE
New GI interface: Skip this screen 

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2553]
<img width="897" alt="Screenshot 2022-03-31 at 15 21 35" src="https://user-images.githubusercontent.com/7359272/161077814-de4a47b6-8afa-427c-be7a-ee7e91f3d1bd.png">

I think we can skip this and just present the curated interaction (easy. to delete if wrong).

go directly to:
<img width="871" alt="Screenshot 2022-03-31 at 15 23 27" src="https://user-images.githubusercontent.com/7359272/161078151-e987981b-1ecb-4cb1-94e8-592d710a3e79.png">

**Comment by kimrutherford** [comment]
I'm not so sure about this plan.  I think that making a dialog close when you select something from a drop-down is a bit surprising.

**Comment by ValWood** [comment]
Discuss today?

**Comment by ValWood** [comment]
we decided it was OK for now
