### ISSUE TITLE
New GI interface, combine screen

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2554]
Here

<img width="896" alt="Screenshot 2022-03-31 at 15 45 12" src="https://user-images.githubusercontent.com/7359272/161083144-67981d7b-c2b7-45f1-b684-c1fbc2c0082b.png">

If there are no interactions, maybe the pulldown on the next screen can appear here instead?

**Comment by ValWood** [comment]
i.e. 

<img width="877" alt="Screenshot 2022-03-31 at 15 46 55" src="https://user-images.githubusercontent.com/7359272/161083564-cc9e1154-f869-4dd6-9dc2-695a1f903762.png">

**Comment by ValWood** [comment]
(i.e combine these 2 screens)

**Comment by kimrutherford** [comment]
I think this is fixed now.
