### ISSUE TITLE
missing regulation terms in Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2556]
I don't see 
"regulation of mitochondrial fusion"

as a child of ",mitochondrial fusion"

I suspect this is to do with GO changes around 'regulation'

Could you check this files we use, and let me know if this is a general issue before I report it?
<img width="1016" alt="Screenshot 2022-04-04 at 13 59 23" src="https://user-images.githubusercontent.com/7359272/161549408-85032a59-90c7-44bb-8c26-31f366ef50db.png">

(I only see stress induced mitochondrial fusion)

**Comment by ValWood** [comment]
Actually, I think this is to do with the taxon restrictions and the anatomical structure branch, because some regulation terms are available.

<img width="1016" alt="Screenshot 2022-04-04 at 13 59 23" src="https://user-images.githubusercontent.com/7359272/161550168-2e8a84d0-0901-46d6-ae77-f8dd49e8af13.png">

@cmungall 
@balhoff

**Comment by kimrutherford** [comment]
> Actually, I think this is to do with the taxon restrictions

I think so because "regulation of mitochondrial fusion" is in Jim's list: https://github.com/geneontology/go-ontology/issues/23012#issuecomment-1076710729

**Comment by ValWood** [comment]
OK closing. I have a curation ticket tracker ticket to remind me.
