### ISSUE TITLE
GI interface testing text prompts

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2559]
from
https://github.com/pombase/canto/issues/2550#issuecomment-1087445792

Dosage growth defects displays
<img width="884" alt="Screenshot 2022-04-11 at 10 38 13" src="https://user-images.githubusercontent.com/7359272/162711559-e0ef0cca-430e-4d24-8557-f64c93937bfa.png">

Is that what we intended?

**Comment by ValWood** [comment]
Some are good, like
<img width="664" alt="Screenshot 2022-04-11 at 10 45 05" src="https://user-images.githubusercontent.com/7359272/162712474-454294ef-529e-49c9-97bb-319a27ab10f1.png">

**Comment by ValWood** [comment]
i think the reason is we only dealt with the cases where a selection of rescued/enhanced needed to be made, but we could improve the text in the other cases too. I will work on that.

**Comment by ValWood** [comment]
1. confirm Wee1 _displays **Dosage growth defect** with_  XXX overxpression

**Comment by kimrutherford** [comment]
> Is that what we intended?

Should the wording change?

**Comment by kimrutherford** [comment]
> confirm Wee1 displays Dosage growth defect with XXX overxpression

Does that work for Dosage Lethality too?

**Comment by ValWood** [comment]
yep
confirm wee1 delta displays dosage lethality with XXX overexpression

**Comment by ValWood** [comment]
And synthetic growth defect:

confirm cdc1delta diplays synthetic growth defect with wss2delta

These could stay as they are, but I think it helps the user to see them spelled out, its easier to parse and confirm.

**Comment by kimrutherford** [comment]
I've made that change.

**Comment by ValWood** [comment]
ping
