### ISSUE TITLE
GI interface Make interaction type more explicit 

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2560]
Currently 

<img width="495" alt="Screenshot 2022-04-11 at 10 41 41" src="https://user-images.githubusercontent.com/7359272/162711805-41bcb70c-6e30-44e5-98c0-cbb7117c3e88.png">

I think we should display the full text here . like we do in the  legacy version.
<img width="366" alt="Screenshot 2022-04-11 at 10 42 49" src="https://user-images.githubusercontent.com/7359272/162712071-4df87bdb-061e-461a-9415-c8fcd41f9b31.png">

**Comment by kimrutherford** [comment]
That's done now.
