### ISSUE TITLE
GI interface Another restriction for synthetic lethal

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2561]
A viable population phenotype is incompatible with "synthetic lethal " evidence:
<img width="720" alt="Screenshot 2022-04-11 at 11 04 32" src="https://user-images.githubusercontent.com/7359272/162716064-6d61e21d-2ed8-4545-ad52-98477002e981.png">

**Comment by kimrutherford** [comment]
> viable population phenotype

Is that this term?:
```
 id: FYPO:0002058
 name: viable cell population
```

**Comment by kimrutherford** [comment]
Or is it this one?:
```
 id: FYPO:0002057
 name: cell population viability
```

**Comment by ValWood** [comment]
it was
viable vegetative cell population ([FYPO:0002060]

but the 
FYPO:0002058 name: viable cell population
you suggested is more appropriate. We can't go up to FYPO:0002058 because that includes lethal.

**Comment by kimrutherford** [comment]
Is it the same for Dosage Lethality or any other interaction types?

**Comment by kimrutherford** [comment]
I've implemented this now but I have a question.  The currently implement shows "Synthetic Lethality" only for child terms of "inviable cell population".

But I've just noticed that there are a quite a few FYPO terms that are direct children of "cell population viability", but aren't children of "viable cell population" or "inviable cell population", like:
`loss of viability following cellular response to hydroxyurea` (FYPO:0005704)

Are any of these other terms compatible with "Synthetic Lethality"?

**Comment by ValWood** [comment]
> Is it the same for Dosage Lethality or any other interaction types?

It is the same for "Dosage Lethality" but not for any others.

**Comment by ValWood** [comment]
I think for now we can omit the "loss of viability" terms. 
if we do need to add them, I will add a grouping parent.

Loss of viability terms were added for experiments where a successive loss of viability has been shown over successive generations. 

 I think, but am not sure, that loss of viability would lead to an inviable population over time? but maybe this is not always the case. 

We don't use "loss of viability" terms very often, and I am not sure that they have always been used as intended, or how such term relate to population growth rate terms. I even wonder if they are so useful .....

(For example, I suspect a lot of the 
loss of viability at high temperature](https://www.pombase.org/term/FYPO:0001387)
have been used instead of 
"slow vegetative population growth" with "high temperature" as a condition.

**Comment by kimrutherford** [comment]
> It is the same for "Dosage Lethality" but not for any others.

OK, thanks.  I've made that change.

**Comment by kimrutherford** [comment]
> I think for now we can omit the "loss of viability" terms.

Thanks.  The current implementation shows "Synthetic Lethality" and "Dosage Rescue" only when the double mutant is "inviable cell population" (FYPO:0002059) and descendants.  I hope I've understood things.

The "FYPO:0002059" is in the config file, so we can easily add any of the the "loss of viability" terms later if it makes sense.

https://github.com/pombase/canto/blob/efd0d77f216f3ef6cc3d1d7c955d8c2c10ec1c2b/canto.yaml#L2162=

https://github.com/pombase/canto/commit/efd0d77f216f3ef6cc3d1d7c955d8c2c10ec1c2b#diff-1943dfca85225feb8cd565332ab55152ef6307965f44d36c92d94b9622c661e2R440

**Comment by ValWood** [comment]
gah, also "Synthetic Rescue - Mutation/deletion of one gene rescues the lethality or growth defect of a strain mutated/deleted for another gene"

Sorry!

**Comment by kimrutherford** [comment]
OK, I've added Synthetic Rescue to the list.
