### ISSUE TITLE
Gi interface error

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2562]
You might have mentioned this one:
<img width="976" alt="Screenshot 2022-04-11 at 10 54 58" src="https://user-images.githubusercontent.com/7359272/162716165-2f30c37c-6a2d-44fd-afce-0daee906fc61.png">

**Comment by kimrutherford** [comment]
I think I've fixed this.  It should be working in the test server by the morning.  (The test server is currently offline while I reset the test database)
