### ISSUE TITLE
GI interface title

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2563]
I remember we discussed this. i wonder if we can think of a better heading for this workflow?

It seems odd to have a title "Add interactions" when you have added the interactions. Users might find it confusing.

<img width="602" alt="Screenshot 2022-04-11 at 10 45 21" src="https://user-images.githubusercontent.com/7359272/162716374-d9ff359e-7d34-43e0-a39c-d657f53918fe.png">

I don't have a better suggestion...

**Comment by ValWood** [comment]
Change dialogue i to "select phenotype and create interaction"
and skip final  dialogue (pop-up).

**Comment by kimrutherford** [comment]
> Change dialogue "select phenotype" to "select phenotype and create interaction"
and skip final dialogue (pop-up).

I can't see "select phenotype" in the dialog(s) now.  Perhaps it has already changed?

**Comment by ValWood** [comment]
It's this one, sorry text was not precise:

<img width="627" alt="Screenshot 2022-05-23 at 08 59 38" src="https://user-images.githubusercontent.com/7359272/169772045-9ddfa60b-a6f0-47ff-b429-380327d72168.png">

**Comment by kimrutherford** [comment]
> Change dialogue "select phenotype" to "select phenotype and create interaction"

I'm still confused by this.  I can't see "select phenotype" anywhere.  Do you mean "Add interactions"?

**Comment by ValWood** [comment]
Yes sorry.
I remember we discussed this on a call recently. Did we decide to change it to
"Select phenotype and create interaction" ? throughout? Or would that also be confusing?

If you think it is not a good suggestion, close and we will keep this as it is until we think of a better header.

**Comment by kimrutherford** [comment]
> If you think it is not a good suggestion, close and we will keep this as it is until we think of a better header.

I'm working on this now as part of combining two of the steps to remove a dialog.

**Comment by kimrutherford** [comment]
I've merge two interaction dialogs because I thought it was unnecessary to have a separate dialog for selecting phenotypes.  Also the dialog title now changes when you start selecting phenotypes which might mean this issue can close.

Maybe we can have a chat about this once things calm down.

**Comment by ValWood** [comment]
I have a list for next week. Will add.
