### ISSUE TITLE
GI interface, unnecessary pop-up?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2564]
If there are no genetic interactions the link says

Associated genetic interactions 0 add...

Then you get a screen:
<img width="972" alt="Screenshot 2022-04-11 at 11 26 57" src="https://user-images.githubusercontent.com/7359272/162721877-a96d6a0c-8af3-4b31-811e-50ac5f1f529f.png">

I think we could skip this screen and go straight to:
<img width="937" alt="Screenshot 2022-04-11 at 11 27 13" src="https://user-images.githubusercontent.com/7359272/162721946-18b46f60-7add-4e63-aab2-6a7b99edf76c.png">

**Comment by kimrutherford** [comment]
Is this the same as: pombase/canto#2554

**Comment by ValWood** [comment]
yes!
