### ISSUE TITLE
another restriction for synthetic rescue

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2565]
synthetic rescue.
Only show phenotyes to  be rescued from the population branch

**Comment by kimrutherford** [comment]
> Only show phenotyes to be rescued from the population branch

Just to be clear, that's "cell population phenotype" FYPO:0000003 right?  Does it include all descendants of that term including both normal and abnormal phenotypes?

**Comment by kimrutherford** [comment]
> Just to be clear, that's "cell population phenotype" FYPO:0000003 right? 

I've implemented this using FYPO:0000003 for now.  We can change the config if that's not the right term.

**Comment by ValWood** [comment]
This contraint could be more specific?
@manulera

**Comment by kimrutherford** [comment]
Does this need to be re-opened?

**Comment by ValWood** [comment]
Reopening to check.

**Comment by manulera** [comment]
I think the constrains are already covered here:

https://github.com/pombase/canto/blob/9bcee847e9690a3b4bbb2d611b7debb02120f881/canto.yaml#L2159-L2166
