### ISSUE TITLE
Penetrance dialogue

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2569]
Hi Kim,

Two things regarding the penetrance dialogue:

## Suggestion

When clicking on the penetrance dialogue, it always starts with the top dropdown open covering the quantitative penetrance box (you can see it in the video). I think it would be better to either start with the dropdown closed, and only if you click it opens. Alternatively, since there are only three options, they could be best shown as a multiselect with a button, like this:

![Screenshot 2022-05-09 at 19 04 57](https://user-images.githubusercontent.com/22526102/167470405-144c9714-7d51-4920-8a6a-5ebaef644214.png)

What do you think @ValWood?

## Bug

If you select the categorical penetrance (e.g. low), but then a quantitative one (e.g. 12%) the result is (low percent). The new addition should always override, I suppose?

https://user-images.githubusercontent.com/22526102/167469897-442966bb-d347-4f92-b1d6-db1b70df1633.mov

**Comment by ValWood** [comment]
We can review the expression options when this ticket is addressed because this proposed more substantial changes to expression curation
https://github.com/pombase/canto/issues/2544

**Comment by kimrutherford** [comment]
Hi Manu.  Thanks for the clearly structured issue!

We'll need to chat to Val about this.  There are some constraints on the problem that we'll need to discuss.

The drop down shows automatically because Val thought that would be more obvious for the users: https://github.com/pombase/canto/issues/2038#issuecomment-536978856

> Alternatively, since there are only three options, they could be best shown as a multiselect with a button, like this:

And we use a drop down menu so that we can show the term name and definition to the right as the user moves down the list.

**Comment by ValWood** [comment]
Presumably, the thinking was that it is had for users to know what the options are.

We could: 
- make a clearer text prompt "low, medium, high or complete" in the box so at least they know in advance. But the drop-down still needs to appear when you click in the box, no?
AND/OR
- would it be helpful to put the"quantitative value"  box above the quantitative drop-down? (Also we prefer quantitative to qualitative so it would make  sense to reorder anyway?)

**Comment by kimrutherford** [comment]
> would it be helpful to put the"quantitative value" box above the quantitative drop-down?

That's a quick fix.  Should I go ahead and do that now while we think about bigger changes?

**Comment by ValWood** [comment]
OK!

**Comment by kimrutherford** [comment]
> would it be helpful to put the"quantitative value" box above the quantitative drop-down?

Done!

**Comment by ValWood** [comment]
Close?

**Comment by kimrutherford** [comment]
Hi @manulera

Do you think my quick-fix here is good enough for now?
