### ISSUE TITLE
Cannot delete annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2572]
I am trying to delete the 2 annotations to 0000743, but I'm not allowed?

<img width="1396" alt="Screenshot 2022-05-12 at 10 58 22" src="https://user-images.githubusercontent.com/7359272/168045417-296a0f8d-b5fb-405c-a8f5-750ae52afb0e.png">

**Comment by kimrutherford** [comment]
Which session is that?

**Comment by ValWood** [comment]
ignore., I just tried again it is fine.
