### ISSUE TITLE
Check that all genetic interactions prompts are sensible

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2577]
Here:

<img width="790" alt="Screenshot 2022-05-18 at 08 34 25" src="https://user-images.githubusercontent.com/7359272/169059191-c55a49e9-17b3-4f29-8ed5-779ac80c1fa0.png">

and that they align with the direction in the output here:
<img width="561" alt="Screenshot 2022-05-18 at 08 36 33" src="https://user-images.githubusercontent.com/7359272/169059258-20e42f92-3d0c-4507-ad54-3658f5ccc7ad.png">

ideally that the "statement" in the first box can be configured (so as few text variations as possible)

@manulera  I will assign this one to you as a fresh pair of eyes. You might notice/ suggest other tweaks.

**Comment by kimrutherford** [comment]
Would it make sense to display it something like?:

any1delta **invisible in the presence of** tmp1+[Overexpression] &nbsp;&nbsp; (**Dosage Lethality**)

It looks different to what's in the table but it reads better and includes the same information.

**Comment by ValWood** [comment]
That looks ok - |I like your new  genetic terminology ;)

**Comment by manulera** [comment]
Hello, I tested this. Here are my comments.

## General comments

* Genetic interactions cannot be deleted (by clicking on the `view or add...` thing in the genotype table).
* The page has to be refreshed to see changes made to genetic interactions (I think we also mentioned this yesterday), but also for the right constrains to be applied to the genetic interactions once phenotype annotations are added or edited. In this context, the constrains can be violated after adding a new phenotype (if I add a new phenotype, the constrains are probably copied from the last one row or something like that).
* When deleting a phenotype annotation that has genetic interaction an error comes from the database:
    ```
    Couldn't delete the annotation: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::SQLite::st execute failed: FOREIGN KEY constraint failed [for Statement "DELETE FROM genotype_annotation WHERE ( annotation = ? )" with ParamValues: 1=22] at lib/Canto/CursDB/Annotation.pm line 209
    ```
    I guess this is because you would orphan the genetic interaction if you delete the phenotype annotation. I guess here you can display a dialogue for the user saying something like "Deleting this phenotype annotation will also delete the following genetic interactions, do you want to proceed?" and show a list.

* Perhaps an edge case, but I think it would be good to constrain phenotypes if editing a phenotype annotation with existing genetic interactions, or show a warning if a constrain is violated by a change in FYPO term. For example, right now I could create an inviable cell population phenotype, add a synthetic lethality interaction, then change the phenotype to short spindle.
* Can you refer me to the config file where you set the constrains for what interactions are allowed? I can then have a look at that and have a better picture.

## Regarding constrains

Defs here: https://wiki.thebiogrid.org/doku.php/experimental_systems

* Dosage Growth Defect
  > Definition: Overexpression/increased dosage of one gene causes a growth defect in a strain that is mutated/deleted for another gene
  * The order of products is inverted in the statement, but this we covered the other day I believe: "pkl1+ displays Dosage Growth Defect with cut7delta"
  * I tried a few random phenotypes and they seem not to be accepted, such as short spindle. Those constrains make sense. However, increased apoptosis is accepted. Perhaps it's better to discuss this directly at the config file level.
  * Biogrid only contemplates overexpression for dosage growth (see definition), but I can also select knockdowns. I don't know if we allow this in Pombase differently from them.
  * I wonder if in this case we should also require both single allele phenotypes. If I understand correctly the requirement for this genetic interaction is:
    * gene A deleted: no or smaller changes in cell pop. growth
    * gene B overexpressed: no or smaller changes in cell pop. growth
    * combined genotype: bigger changes in cell pop. growth

    In other words, the phenotype for this kind of genetic interaction should not be solely due to either the overexpression or deletion. This could also apply to other genetic interactions.

* Dosage Lethality
  * Same for knockdowns (they are selectable but biogrid only contemplates overexpression)
  * The gene names are also inverted 'pkl1+ displays Dosage Lethality with cut7delta', but we discussed this yesterday probably as well.
  * I can select this for 'increased apoptosis', but I think this could be restricted to children of FYPO:0002057 'cell population viability'. To be discussed at the config file level as well.

* Dosage Rescue
  * Same comment about only overexpression being contemplated by biogrid.
  * 

* Negative Genetic
  * Not sure if we have these ones, I guess not.
* Phenotypic Enhancement
  * I think here the phenotype constrains are also not correct. For example, I cannot select the increased apoptosis phenotype as being enhanced. I don't think this should have phenotype constrains, if anything maybe excluding some children from FYPO:0000045 ('abnormal cell population growth') that may fall under "Synthetic" or "Dosage" "growth defect", such as:
    * FYPO:0001355 - 'decreased vegetative cell population growth'
    * FYPO:0001234 - 'slow vegetative cell population growth'

    Other FYPO:0000045 children are not obvious exclusions, such as the ones related to resistance or sensitivity to chemicals. To be discussed at the config file level as well
  * Expression phenotypes should be enhanceable. For example, now I only get the option:
    * pkl1delta phenotype(s) phenotype enhanced by cut7+
    * In this case the order is correct, as when I select it, it prompts me to chose a phenotype for pkl1D


* Phenotypic Suppression
  * Expression phenotypes should be suppresable. For example, now I only get the option:
    * pkl1delta phenotype(s) phenotype suppressed by cut7+
    * In this case the order is correct, as when I select it, it prompts me to chose a phenotype for pkl1D

* Positive Genetic
  * I don't think we have this.
* Synthetic Growth Defect
  * Constrains to be discussed at the config file level.
* Synthetic Haploinsufficiency
  * This seems to be not supported (haploid genotypes do not have the `Add...` dialogue). Seems reasonable for pombe.
* Synthetic Lethality
  * This should only accept phenotypes with 'inviable cell population' I think.
  * I don't think this can be annotated right now.
* Synthetic Rescue
  * I think this is covered inside phenotypic supression right now. Could be inferred if the phenotype of the single allele is lethal.


## Some ideas

* Put a warning if the:
  * condition
  * genetic backgrounds
  * evidence code

  differ in the single allele phenotype and double allele phenotype after annotating a genetic interaction (making sure people don't forget to annotate those in the double mutant as well). I think they should probably always match, but there may be some edge cases. Showing a warning probably is sufficient.

* Dialogue when annotating double genotypes that are lethal or phenotypes that match the single allele. For example:
  * If someone annotates a double mutant as lethal, suggest to create a synthetic lethal annotation / dosage lethal.
  * If someone annotates the same phenotype as single mutant with double, ask if this is a genetic interaction + suggest adding a change if severity / penetrance if it exists.

**Comment by manulera** [comment]
I just realised that @ValWood comment only concerned the prompts, but well at least I tested a few things! @kimrutherford , you can refer to the config files / code where you put the prompts when you add the final ones, and I can check them all and don't miss any.

**Comment by ValWood** [comment]
Feel free to comment away!
We can go through these on Monday.

**Comment by kimrutherford** [comment]
> Genetic interactions cannot be deleted (by clicking on the view or add... thing in the genotype table).

Now fixed:
  - pombase/canto#2587

**Comment by kimrutherford** [comment]
> but also for the right constrains to be applied to the genetic interactions once phenotype annotations are added or edited

I think this is fixed now.  If the bug is still there could you give me an example?

>

**Comment by kimrutherford** [comment]
> When deleting a phenotype annotation that has genetic interaction an error comes from the database

I made an issue for that:
  - pombase/canto#2588

> Can you refer me to the config file where you set the constrains for what interactions are allowed?

That would be here I think:
https://github.com/pombase/canto/blob/b4e38f2ab600089a542c222b8f3b9b584c4d134c/canto.yaml#L2155

I've started documenting the config settings here:
https://github.com/pombase/canto/blob/b4e38f2ab600089a542c222b8f3b9b584c4d134c/root/docs/md/canto_admin/configuration_file.md#evidence_code_groups=

> you can refer to the config files / code where you put the prompts when you add the final ones, and I can check them all and don't miss any.

It's a bit tricky. :-)

The text and prompts in the interface are created from the evidence code configuration.  Here is how "Dosage Growth Defect" is configured for example:
https://github.com/pombase/canto/blob/b4e38f2ab600089a542c222b8f3b9b584c4d134c/canto.yaml#L1637
The "interactor_a" config is used in the edit dialog.

**Comment by kimrutherford** [comment]
> Perhaps an edge case, but I think it would be good to constrain phenotypes if editing a phenotype annotation with existing genetic interactions, or show a warning if a constrain is violated by a change in FYPO term. For example, right now I could create an inviable cell population phenotype, add a synthetic lethality interaction, then change the phenotype to short spindle.

Could you make an issue for this problem?  Thanks.

**Comment by manulera** [comment]
> Could you make an issue for this problem? Thanks.
#2589

**Comment by manulera** [comment]
When I move the comments to separate issues, I will cross them out from my original comment.

**Comment by manulera** [comment]
@kimrutherford you said you wanted to read this once more, but after that, this can be closed as all of it was trasnferred to the new ticket

**Comment by kimrutherford** [comment]
Thanks Manu.

I've read through again.  You have listed two ideas under the heading "Some ideas".  Should we keep those as separate issues?  They seem sensible to me.
