### ISSUE TITLE
Protein sequence feature or motif dialogue

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2581]
When you have to annotate the sequence motif, this is the dialogue that comes:

![Screenshot 2022-06-01 at 11 41 59](https://user-images.githubusercontent.com/22526102/171386743-7cacc756-7e7e-4f77-91cf-048b476c6f44.png)

Instead of `position modified` it should something like `residues range` or something like that, I think.

**Comment by kimrutherford** [comment]
Hi @manulera

I've made that change.  It should be visible in a few hours.  The file is here if you'd like to make other changes:
  https://github.com/pombase/pombase-config/blob/master/canto/annotation_ex_config/protein_sequence_feature_or_motif_A_E_config

The configuration is documented here:
https://github.com/pombase/canto/wiki/AnnotationExtensionConfig
