### ISSUE TITLE
Quicker annotation of protein modifications for phosphorylation?

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2582]
Hello,

I was curating the phosphorylation of a protein and it was a bit confusing to annotate the residues, I can imagine that if someone lands there for the first time, it can be a bit challenging to understand what to pick from the list. Couldn't we have something where you just select phosphorylation and the MOD is inferred once you specify the residue? All threonins give O-phospho-L-threonine, etc. Also less error prone for community curation, I can imagine.

For speed, it could be good to be able to annotate them in bulk, comma separated like we annotate the modifications of a protein, for example: (S50,S51,T100,T116,T131). Since typically you want to specify that all of them will be phosphorylated by the same thing and dephosphorylated by the same protein, same phase. Maybe this would require more changes, so I guess we can skip it, but if you have to annotate a bunch of proteins I can see it becoming quite heavy.

**Comment by ValWood** [comment]
I will close this and add this comment to 
https://github.com/pombase/canto/issues/2586
