### ISSUE TITLE
Marking paper as non-curatable

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2585]
Hello @ValWood ,

One of the papers you assigned me ([PMID:10607565](https://curation.pombase.org/pombe/view/object/pub/5489?model=track)) only describes experiments performed in a wild type background. I guess to indicate that the paper cannot be curated I just go to the paper in canto, then Actions > Edit and mark it as `Cell composition or WT feature`. Anything else?

**Comment by kimrutherford** [comment]
Hi Manu.

Using Edit will probably work but I recommend using "Triage" and then clicking on correct status.  The Edit function isn't as well tested as Triage.

**Comment by ValWood** [comment]
yep just reclassify anything that is not suitable for curation.
I sent you a bunch of old papers. They are nice to do because they are usually very quick!

**Comment by manulera** [comment]
Ok, got it! Thanks!
