### ISSUE TITLE
Constrain phenotypes once genetic interactions have been added

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2589]
From #2577 

If editing a phenotype annotation with existing genetic interactions, if a constrain for the genetic interaction is violated by a change in FYPO term this should either give a warning, or not be allowed at all.

For example, right now I could create an inviable cell population phenotype, add a synthetic lethality interaction, then change the phenotype to short spindle.

When I add a genetic interaction to the phenotype annotation 'short spindles' for the double deleted `ase1D peg1D`, I can't choose `synthetic lethality` because of the constrains.

https://user-images.githubusercontent.com/22526102/176394374-bb8f24c8-0693-4797-9c57-39daf9d0c5ad.mov

However, if I have a phenotype annotation `inviable cell population`, associated to a genetic interaction `synthetic lethality`, I can switch back the FYPO term to `short spindles`:

https://user-images.githubusercontent.com/22526102/176394917-991958c3-4369-41d4-a488-ad707047a867.mov

**Comment by kimrutherford** [comment]
I went for the option of preventing the term from changing when there are interactions attached to the annotation.  That's done now.
