### ISSUE TITLE
Refresh genetic interactions list when a new interaction is added

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2590]
From #2577

> The page has to be refreshed to see changes made to genetic interactions, but also for the right constrains to be applied to the genetic interactions once phenotype annotations are added or edited. 

The second part mentioned in the issue (below) is already fixed.
> In this context, the constrains can be violated after adding a new phenotype (if I add a new phenotype, the constrains are probably copied from the last one row or something like that).

**Comment by kimrutherford** [comment]
I've made the slightly dodgy fix we discussed: the page now reloads if you add or remove an interaction.
