### ISSUE TITLE
Contradicting information in tooltips in legacy genetic interactions dialogue

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2591]
Related to #2577 

<img width="836" alt="Screenshot 2022-06-29 at 11 12 36" src="https://user-images.githubusercontent.com/22526102/176401258-9c4541bf-4055-43a8-9c7d-5f2a05693ab9.png">

According to biogrid's definition below, the right definition is the one in the tooltip. Phenotypic suppression should not be used to annotate synthetic rescue.

> Mutation/deletion/overexpression of one gene results in suppression of any phenotype (other than lethality/growth defect) associated with mutation/deletion/overexpression of another gene

**Comment by kimrutherford** [comment]
Phenotypic enhancement (non-growth or non-viability phenotype enhanced by) ->
phenotype other than growth defect or lethality enhanced by

Phenotypic suppression (non-growth or non-viability phenotype suppressed by) ->
phenotype other than growth defect or lethality rescued by

**Comment by kimrutherford** [comment]
I've made those changes.
