### ISSUE TITLE
evidence_code_groups for genetic interactions

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2592]
Following #2577 

Hi @kimrutherford. I had a look at the yaml file. I think I get how it works, and I think I found one problem.

https://github.com/pombase/canto/blob/a59c92f202b89aa36e21bb378f9c09a592c0c196/canto.yaml#L2163-L2167

If I understand, this is a list of genetic interactions that can be associated with a phenotype that is lethal. The list should only contain:

* Dosage lethality
* Synthetic lethality

The lethality constrains for `Synthetic Rescue` and `Dosage rescue` should be applied to the single-allele phenotype, not the double-allele phenotype.

I can make a list of the constrains for each genetic interaction, but I am not sure it would be possible to use this kind of format to keep it.

**Comment by manulera** [comment]
See #2593

**Comment by kimrutherford** [comment]
I think I fixed this in the changes for: https://github.com/pombase/canto/issues/2593#issuecomment-1180329326
