### ISSUE TITLE
Full-list of constrains for genetic interactions

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2593]
I think this would be an exhaustive list of the constrains that would need to be applied, from the biogrid definitions here: https://wiki.thebiogrid.org/doku.php/experimental_systems

* Interactions that contain `Dosage` in their name:
  * Only overexpressed alleles can be included (no knockdowns).
  * Only one can be overexpressed, and from this we infer the directionality.
    * As it is now, we can annotate a double overexpression as `Dosage X` and cannot set directionality.

* Interactions that contain `Synthetic` in their name:
  * No expression alleles allowed (Overexpression or knockdown).

* Interactions that contain `Lethality` in their name:
  * Constrain on phenotype of double mutant: is_a FYPO:0002059 (`inviable cell population`)

* Interactions that do not contain `Lethality` in their name:
  * Constrain on phenotype of double mutant: NOT is_a FYPO:0002059 (`inviable cell population`)

* Interactions that contain `Growth Defect` in their name:
  * Constrain on phenotype of double mutant: is_a (`decreased vegetative cell population growth` or `slow vegetative cell population growth`)

* Interactions that contain `Rescue` in their name:
  * Constrain on phenotype of double mutant: is_a (`cell population growth phenotype` or `viable cell population`).
  * Constrain on single mutant: pedantic, but should be is_a (`decreased vegetative cell population growth` or `slow vegetative cell population growth` or `inviable cell population`).
    * Even more pedantic, it should not be possible to link double mutant from a population growth genotypes to a viability phenotype and vice-versa.

* Interactions that don't contain `Phenotypic` in their name:
  * Constrain on phenotype of double mutant and single mutant: NOT is_a (`decreased vegetative cell population growth` or `slow vegetative cell population growth` or `viable cell population`)
    * This one is a bit pedantic, but in theory we should not have annotations that cause or rescue decreased population growth or lethality outside the genetic interactions that contain `Growth Defect` or `Rescue` in them.
    * Alternatively, instead of preventing it, if the author makes one of these annotations, we can raise a warning saying, do you mean XYZ?
    * We could instead have this warning only at the review stage for admin only if you think this would confuse users.

Some phenotypes fall out of these interactions or I don't see where to put them, for example:
 * If overexpression of gene X is lethal or causes growth defect and another mutation/deletion/overexpression rescues lethality or growth.
 * Knockdowns.
 * If double deletion rescues lethality in presence of a certain drug, but I think those would fall under 'increased sensitivity to chemical during vegetative growth'.

**Comment by ValWood** [comment]
I agree with all of these. I  don't know what I would have used for the ones that you could not classify. I wonder if we have seen  samples of these ?

**Comment by manulera** [comment]
Phenotype suppresions with knockdowns of essential genes probably

**Comment by ValWood** [comment]
@manulera  could you test these (I think you may have done this already?)
