### ISSUE TITLE
Clean up the "sessions" table

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2596]
I noticed that the Canto database is getting quite large - much larger than I thought it should it be. 

I checked and the "sessions" table is huge.  A bit of information is stored in the table each time a user starts using Canto (or probably when a web crawler hits the site).  And it has been doing that since Canto was launched.  It has been working perfectly for 10 years so I have ignored it.  There are now 1.5 million rows and that one table is 75% of the space used by the database.  Whoops.  :-)

I'm using a standard Perl library to maintain the table and I didn't realise that I needed to explicitly call a function to remove the expired sessions from the table.

When I fix this it will make no difference to how Canto works but will make backups quicker since the database will be a lot smaller.

**Comment by ValWood** [comment]
Could that be making Canto a bit slow. I noticed that for me it was a bit slow at my mums and her  broad band seems better than mine. It seems to be fast for some things, but slow for loading tables. And logs me out quite frequently (this never used to happen)

**Comment by kimrutherford** [comment]
That's done now.  The table will now be kept to a modest size by trimming it when anyone logs in.

**Comment by kimrutherford** [comment]
Log-in on the test server was very slow but I think that was because the session table was still big.  It's cleaned up now I think it's all OK.
