### ISSUE TITLE
Add curators field to JSON export schema

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2598]
Issue https://github.com/pombase/canto/issues/2594 added a new `curators` field to the JSON export, so `etc/export.schema.json` will need to be updated to match.

**Comment by kimrutherford** [comment]
Hi James.  Just so you know, you won't see the new `annotation_curators` field in your JSON output because it's only present when the curator names are exported using `--export-curator-names`.

**Comment by jseager7** [comment]
Thanks. I'll update the schema anyway since I use it more for documentation than validation, even for our own Canto instance.
