### ISSUE TITLE
Transfer extensions by default when transfering annotations via the genotype page

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2604]
(related to #2250 and #2471)

Hi Kim,

For the feature that transfers multiple different annotations from one genotype to another, present on the genotype page via the link 'Transfer phenotype class annotation ...'), would it be possible have the 'Transfer extensions' box ticked by default?

![Screenshot 2022-08-10 at 09 58 44](https://user-images.githubusercontent.com/33721108/183860625-c4374ca2-6473-4c32-b378-5c48d4be8fcb.png)
![Screenshot 2022-08-10 at 09 58 33](https://user-images.githubusercontent.com/33721108/183860670-23265abd-6a08-4e2d-bc95-91e21d518d57.png)

This would be helpful, because that is what applies to the the most common situation, i.e the same experiment repeated, and with the same outcome, for multiple genotypes.

That behavior is already the default when transferring one annotation to multiple genotypes, via the 'Transfer' link on the right of the annotation (between  the 'Edit' and 'Copy and edit' links) 

![Screenshot 2022-08-10 at 10 01 17](https://user-images.githubusercontent.com/33721108/183860972-2be4840e-d511-4318-b7b1-1163852a8ea1.png)

**Comment by kimrutherford** [comment]
Hi Vitor.

I've fixed that now.
