### ISSUE TITLE
Remove double mutant phenotype column in dialogs

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2608]
![image](https://user-images.githubusercontent.com/90474/186373809-c664c923-d0b1-4366-9d11-eb9c029d0e4c.png)

**Comment by ValWood** [comment]
I also dont thisnk we need the double mutant  phenotype in the new type GI summary table:

<img width="983" alt="Screenshot 2022-08-24 at 15 12 59" src="https://user-images.githubusercontent.com/7359272/186441198-dd547471-de39-4cc7-af35-1d95e6ff3dea.png">
 
 we could in theory make the interaction from a number of double mutant phenotypes for the same genetype.

**Comment by ValWood** [comment]
ignore.

**Comment by kimrutherford** [comment]
That's fixed now.
