### ISSUE TITLE
Small dialog when you can't change genotype due to GI being there

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2609]
I think it would be nice to have a little tooltip explaining that you can't change this genotype because there are associated GIs:

https://user-images.githubusercontent.com/22526102/186403232-15903ccd-2a11-414c-97c1-8a229c7d82be.mov

What do you think @ValWood @kimrutherford

**Comment by kimrutherford** [comment]
How's this - first attempt:

![image](https://user-images.githubusercontent.com/90474/187208391-f27dccf7-383e-4597-bde1-b03d338ecfcd.png)

**Comment by kimrutherford** [comment]
> We have "Edit" and "copy Edit"
> For "Copy edit" I think the behaviour could be that the phenotype annotation is copied without the genetic interactions, and everything remains editable.

I made a separate issue for that: #2621

**Comment by ValWood** [comment]
works for me.

**Comment by kimrutherford** [comment]
That change is in the test Canto.  Let me know if it's OK.

**Comment by manulera** [comment]
Hello! Looks good. The only thing is that at least in my browser it took a while to appear (I had to leave the cursor on it for a bit on top of the ? icon), so initially I thought it was not working for me. Perhaps a shorter delay until it appears? Or maybe it is because it is the test canto and that's why there is delay.

**Comment by kimrutherford** [comment]
> Perhaps a shorter delay until it appears?

I've fixed it so that it pop-ups immediately.
