### ISSUE TITLE
GI: phenotype curated not available  for selection

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2611]
This phenotype is curated:

<img width="1121" alt="Screenshot 2022-08-24 at 12 48 10" src="https://user-images.githubusercontent.com/7359272/186411221-609a7c9a-641d-465b-81a2-119e9f18cfa1.png">

I want. to add an interaction to
<img width="993" alt="Screenshot 2022-08-24 at 12 48 22" src="https://user-images.githubusercontent.com/7359272/186411273-fa335503-05bd-4e19-9d38-ab7a4372d85b.png">

but the sensitivity phenotype (which is a type of growth defect in FYPO)
is not available to select for "dosage rescue" , even though it is curated:

<img width="878" alt="Screenshot 2022-08-24 at 12 48 53" src="https://user-images.githubusercontent.com/7359272/186411422-d07f0f39-090c-4f45-a25a-fd1cefd03023.png">

**Comment by kimrutherford** [comment]
Which session is that?

**Comment by ValWood** [comment]
duplicate of https://github.com/pombase/canto/issues/2613

**Comment by ValWood** [comment]
I was testing in 
https://curation.pombase.org/test/curs/8702be0070bbe887
