### ISSUE TITLE
GI: Selection of single allele phenotype does not work when either allele is overexpressed

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2613]
@kimrutherford @ValWood 

The full list of constrains is in this issue: https://github.com/pombase/canto/issues/2593

The problem that we discussed this morning:

When the user selects `Dosage Rescue`, in this case for pkl1[OE] any1delta

<img width="521" alt="Screenshot 2022-08-24 at 13 43 02" src="https://user-images.githubusercontent.com/22526102/186421249-4423b085-c374-43be-bea1-a9895728d46e.png">

The single allele phenotypes of any1D are not shown in this window.

And when clicking add phenotype the genotype is not pre-filled with the single allele phenotype (any1delta in this case)

<img width="541" alt="Screenshot 2022-08-24 at 13 44 36" src="https://user-images.githubusercontent.com/22526102/186421592-9b92c721-dd35-4c0d-a34c-5519d726086c.png">

The same problem occurs in phenotypic enhancement or phenotypic suppression has either one or both of the alleles overexpressed.

**Comment by kimrutherford** [comment]
This should be fixed now.

**Comment by manulera** [comment]
Yes! looking good 👀👀👀
