### ISSUE TITLE
GI: It should be possible to select dosage lethal for inviability phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2614]
<img width="951" alt="Screenshot 2022-08-24 at 14 03 43" src="https://user-images.githubusercontent.com/7359272/186425760-5bd46f93-6d24-4303-b166-54bcd7f3199b.png">

It should be possible to select "dosage lethal" for inviability phenotypes:

<img width="897" alt="Screenshot 2022-08-24 at 14 03 23" src="https://user-images.githubusercontent.com/7359272/186425804-552bee45-55c1-4cdc-b4fb-e7626d9c7c55.png">

testing with https://curation.pombase.org/test/curs/8702be0070bbe887

**Comment by kimrutherford** [comment]
What was the double allele phenotype for this annotation?

**Comment by ValWood** [comment]
cdc42+[Overexpression]esh2-1(aaP612S)[Not assayed]Associated genetic interactions (0) - add ... | FYPO:0002061 | inviable vegetative cell population
-- | -- | --

**Comment by kimrutherford** [comment]
Hi Val.  I get a different list.  Can you shift-reload to see if that changes anything?

![image](https://user-images.githubusercontent.com/90474/186610513-effdc91e-c828-4684-92bc-7110cddfc936.png)

**Comment by ValWood** [comment]
I also see "dosage lethal" now.

Note that 
phenotypic Enhancement and Phenotypic impression should not be a=vaiable for growth or viability phenotypes (but I think that is in another ticket)
