### ISSUE TITLE
GI: can only select phenotypic enhancement or suppression

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2626]
Hi @kimrutherford

In the current test version, I can only select either phenotypic suppression or enhancement as GI, regardless of genotype and phenotype:

<img width="483" alt="Screenshot 2022-08-30 at 15 41 26" src="https://user-images.githubusercontent.com/22526102/187466991-f7dbef07-4004-4b56-9116-c3d4c037a2ad.png">

**Comment by kimrutherford** [comment]
Thanks for testing.  I think I've fixed this now.

Fixed in 6c4f5deff298c8b4379

**Comment by manulera** [comment]
Hi @kimrutherford all good as far as I can tell, including constrains for genetic interaction types depending on phenotype.
