### ISSUE TITLE
Able to create duplicate annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2627]
The RNA SPNCRNA.289 merged into SPNCRNA.1303
by editing the extension (at first I did not notice that SPNCRNA.1303 already existed)

<img width="1203" alt="Screenshot 2022-08-27 at 08 49 49" src="https://user-images.githubusercontent.com/7359272/187020707-cfdf7598-206c-479c-b845-7abba9a0bbff.png">

I deleted the duplicate, but would this cause a log warning, or would it be automatically fixed?

**Comment by kimrutherford** [comment]
Now I think about it, this shouldn't happen.  You should have seen a "Not storing: an identical annotation exists." message.  Can you reproduce this?

**Comment by ValWood** [comment]
The session is pombe/curs/c757e60bdb79c5cb
I was able to create a duplicate annotation (it is there now).

**Comment by kimrutherford** [comment]
> I was able to create a duplicate annotation (it is there now).

I can't see a duplication.  There is only one new annotation with the extension "assayed_using PomBase:SPNCRNA.1303".  The other is in the existing annotation section.

I'll try to reproduce this locally.

**Comment by ValWood** [comment]
> I can't see a duplication. There is only one new annotation with the extension "assayed_using PomBase:SPNCRNA.1303". The other is in the existing annotation section.

but it is an exact duplicate of an existing annotation, no?

**Comment by kimrutherford** [comment]
> but it is an exact duplicate of an existing annotation, no?

The annotation in the session is the same annotation as the existing one in Chado.  The Canto annotation was loaded into Chado and then displayed in Canto.  All the "Existing annotations" are the annotations from Chado.  If the session is an approved session then all of the session annotations will appear in the  "Existing annotations" section.  That's always been how it works.

**Comment by ValWood** [comment]
I don't know why I said existing. There are two identical annotations though (top and bottom in this table). The only difference is the author.

<img width="1162" alt="Screenshot 2022-09-13 at 12 32 47" src="https://user-images.githubusercontent.com/7359272/189890718-9773bbaf-83fe-4f29-8cfd-55f8ff2c4451.png">

**Comment by kimrutherford** [comment]
But they're different?

One is "assayed_using SPNCRNA.1330" and one is "assayed_transcript SPNCRNA.1330"?

**Comment by kimrutherford** [comment]
> I don't really know how they get different relations though? It should always be assayed transcript?

It looks like one annotation (by Cornelia) was made before the extension configuration changed from assayed_using to assayed_transcript.  That happened on 2021-05-07.  Your annotation was more recent.

**Comment by ValWood** [comment]
is it possible update automatically based on the current relationship for a term?

This might be the same reason:

<img width="664" alt="display  label H2AZ" src="https://user-images.githubusercontent.com/7359272/190588572-d85feebe-bef1-4f51-a021-e96316848a9c.png">

I found one histone chaperone with "has substrate"

**Comment by kimrutherford** [comment]
> is it possible update automatically based on the current relationship for a term?

Probably.  I'll have to have a think about how to do it.

**Comment by kimrutherford** [comment]
> is it possible update automatically based on the current relationship for a term?

I've had a think about this and I'm not sure there's a reliable way to do this automatically.

Would it make sense to have a process at the end of a load that checks all the annotations in Chado and reports any extensions with relations that aren't configured for Canto?  We might even have an existing issue about that.

Incorrect GO extensions get reported by GO but we don't have any checking for incorrect FYPO extensions.

**Comment by ValWood** [comment]
Yes a check would be good. Maybe a logfile.

**Comment by ValWood** [comment]
IO won't worry about this. The chaperone one was a config file issue, which was fixed.
If I see them, I can fix them.
