### ISSUE TITLE
canto error

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2628]
/curs/1068c5e5c8e4b6df/ro

I am getting
<img width="787" alt="Screenshot 2022-09-10 at 16 12 01" src="https://user-images.githubusercontent.com/7359272/189489615-11e28d33-cbcc-4edc-a1c5-ec6de7f0e6b2.png">

**Comment by kimrutherford** [comment]
Sorry about that.  I made a typo when updating Canto.  It's fixed now.
