### ISSUE TITLE
Not assayed expression allows to chose Dosage GIs

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2629]
When an allele has [not assayed] has expression, it can be selected for Dosage GIs. This should only happen with Overexpressions and Knockdowns.

**Comment by kimrutherford** [comment]
> When an allele has [not assayed] as expression, it can be selected for Dosage GIs.

Just to check: is this a problem only when both alleles have expression "not assayed"?  For example if one allele is "not assayed" and the other is over-expressed, can that be a Dosage interaction?

**Comment by manulera** [comment]
>  if one allele is "not assayed" and the other is over-expressed, can that be a Dosage interaction?

In principle yes, but only the overexpressed one should be allowed to be the interacting allele (the one that is not present in the single allele genotype)
