### ISSUE TITLE
Error: Labels not showing when GI interaction is selected

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2632]
The label does not show up on symmetric interactions (see example and console error)

https://user-images.githubusercontent.com/22526102/191232845-87575344-f273-4710-98a5-4c9ba984405a.mov

![Screenshot 2022-09-20 at 11 17 39](https://user-images.githubusercontent.com/22526102/191232810-19af6a79-26e6-45dc-a33c-d4959d7f4940.png)

**Comment by manulera** [comment]
cc: @ValWood

**Comment by kimrutherford** [comment]
Thanks for testing.  I think I've fixed that.  Please re-open if it's still a problem.

**Comment by manulera** [comment]
![Screenshot 2022-09-20 at 13 40 57](https://user-images.githubusercontent.com/22526102/191260060-184faa63-a952-493c-a64c-9270d7af1be9.png)

This is what is shown, but I think it would be good to have the interaction name shown as well (e.g. Synthetic Lethality shown on top in bold)

Otherwise it is not very clear what you are confirming in this dialogue. Not a bug, so it could be closed, but I think it's clearer

**Comment by kimrutherford** [comment]
I think I've fixed this.

Again :-)

**Comment by manulera** [comment]
Looking good! Also with the constrains of lethality, I can see. Thanks!
