### ISSUE TITLE
genotype field blank

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2633]
In the case where I added a synthetic rescue , and then. select the direction

<img width="672" alt="Screenshot 2022-09-20 at 11 46 15" src="https://user-images.githubusercontent.com/7359272/191239049-d4ab89c9-fff6-4d55-a627-0f263f45993f.png">

and then add the phenotype, 
The  genotype field  for the rescued phenotype is blank

<img width="815" alt="Screenshot 2022-09-20 at 11 44 21" src="https://user-images.githubusercontent.com/7359272/191238095-2a2904cd-69a0-4f44-bce2-ad6a87facedf.png">

(I did not see this issue for DR, DL,  SL so it might be specific for those where a  direction needs to be selected, or where the rescued phenotype fdoes not already exist)

**Comment by manulera** [comment]
I think this first empty column should not be shown at all, since it probably refers to the double mutant phenotype, which is already on the title?

**Comment by ValWood** [comment]
usually the genotypes are the 2 single genotypes (at least, in the BioGRID format these 2 fields will replace gene and gene?)

**Comment by kimrutherford** [comment]
@manulera:
> I think this first empty column should not be shown at all, since it probably refers to the double mutant phenotype, which is already on the title?

@ValWood:
> usually the genotypes are the 2 single genotypes (at least, in the BioGRID format these 2 fields will replace gene and gene?)

I don't understand this conversation.

**Comment by ValWood** [comment]
i think the blank  column should contain skb1delta. @manulera  thought it  should be the double mutant.

(At least that's what I think we are saying?)

**Comment by kimrutherford** [comment]
> i think the blank column should contain skb1delta. @manulera thought it should be the double mutant.

Ah, OK.  I think you're right that the skb1delta is missing.

**Comment by manulera** [comment]
Ah OK, I see

**Comment by kimrutherford** [comment]
I can't reproduce this bug now so I wonder if it had the same cause as #2636.  When you get a chance could you re-try this and see if it's still a problem?

**Comment by manulera** [comment]
Yes it seems to not happen anymore, I tried with synthetic lethality on a [not assayed] allele

**Comment by kimrutherford** [comment]
Since we can't reproduce this problem I'm going to assume it's fixed.
