### ISSUE TITLE
cannot copy edit a genotype

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2635]
I tried to copy edit

<img width="1283" alt="Screenshot 2022-09-20 at 11 54 56" src="https://user-images.githubusercontent.com/7359272/191240234-493cf304-f533-4ee9-bfda-c01a54c027c5.png">

in
/test/curs/4c718237e0521f89
to
skb1Δ

I. can select skb1Δ but  the "OK" button is unavailable.
(the annotation I am trying to create does not already exist)

**Comment by ValWood** [comment]
This seems to be the case for any copy/edit genotype. I can copy edit other fields .

**Comment by kimrutherford** [comment]
I think I've fixed this now.
