### ISSUE TITLE
Wrong constrains on when adding a single mutant phenotype annotation from the GI

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2637]
We could choose to not apply any constrain when adding a single phenotype. If we were to inforce those in this case (Phenotypic enhancement) they should only allow non-growth phenotype or non-viability phenotype:

https://user-images.githubusercontent.com/22526102/191241889-f1d3677f-b196-4c59-956c-e5ce2e99dbbd.mov

cc:@ValWood

**Comment by manulera** [comment]
Same problem happens for the non-overexpressed allele:

![Screenshot 2022-09-20 at 12 08 03](https://user-images.githubusercontent.com/22526102/191242551-863bac61-44b7-4510-975d-dae739de33de.png)

**Comment by manulera** [comment]
And is the same for Phenotypic suppresion

**Comment by kimrutherford** [comment]
I've tracked down the problem and fixed it.  I had started to implement constraints on the single allele phenotypes (I forgot) but it was only half implemented and it was causing problems.  I've disabled the code so this should be OK now.
