### ISSUE TITLE
Cannot copy and edit phenotype annotation changing genotype only

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2639]
https://user-images.githubusercontent.com/22526102/191243598-818df4e2-371b-4599-983d-3bdb3afb9491.mov

Changing the other things (condition, phenotype, etc.) it works

**Comment by manulera** [comment]
cc: @ValWood

**Comment by kimrutherford** [comment]
Is this the same as pombase/canto#2635?

**Comment by manulera** [comment]
Yes

Duplicate of #2635

**Comment by manulera** [comment]
Duplicate of #2635
