### ISSUE TITLE
Many sessions have multiple copies of the same allele

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2642]
I noticed this while debugging pombase/canto#2636.  There are a bunch of sessions that multiple copies of the same deletion alleles in the database for the session.  (There may be other types with duplicates, but I haven't checked yet.)

I don't know how this could happen but the sessions I've checked are all 7 or more years old so I'm hoping this was caused by an old bug that's now fixed.

In most cases the duplicates aren't visible in the interface.  For example in this session:
https://curation.pombase.org/pombe/curs/1f991e4ad5694cb6/genotype_manage/ro
there are two copies of iss10Δ, rmn1Δ, nrl1Δ and rrp6Δ in the session database but they aren't visible on the genotype management page.

In this session:
https://curation.pombase.org/pombe/curs/1f8a9a6747848375/genotype_manage/ro
taz1Δ is duplicated and is visible on the genotype management page.

In the cases above the alleles have the same name.  In this session, sog2Δ is also present as lrp1Δ and SPBC887.09cΔ:
https://curation.pombase.org/pombe/curs/59ec05d8416a6e4d/genotype_manage/ro
:-(

In this session we have fxn1Δ and SPCC1183.03cΔ which are the same allele and both genotypes have annotations:
https://curation.pombase.org/pombe/curs/1f78fe7de80af20c/genotype_manage/ro

What a mess.

We probably haven't noticed this because the Chado loading code will merge the deletion alleles even if they have different names.

I think this needs fixing before with go live with the new interactions interface because it's the cause of pombase/canto#2636.

**Comment by kimrutherford** [comment]
As a first step I've checked all the deletion and wild type allele names to make sure that they are easily fixable.  Fixable means that the allele either has no name, uses the gene name (like "cdc2delta", "cdc2+") or uses a gene synonym in the allele name (like "dmr1delta").  All of those cases can be fixed/merged automatically.

All the allele name look fixable / merge-able except for:

  -  `pap1-Δ`   (session [0370b9834de2dfe6](https://curation.pombase.org/pombe/curs/0370b9834de2dfe6/genotype_manage/ro))

Is this just a typo for `pap1Δ`, which is also in the session?  If so there's no need to try to fix it as it will be sorted out when I run the code to fix duplicate alleles (which I'm still working on).

  - `csi11Δ`   (session [5c30b3bf5c5da95c](https://curation.pombase.org/pombe/curs/5c30b3bf5c5da95c/genotype_manage/ro))

Is this a typo for `csi1Δ`?  If will be fixed when I run my script to fix the duplicates.
There is no `csi11` in PomBase and that session has a bunch of alleles with `csi11` in the name.  Do they need fixing?

**Comment by ValWood** [comment]
I fixed all the  alleles starting csi11 (there were multiple cse11 alleles, not just deletion)
e.g.
csi11(Δ2-29 aa)(2-29)[Not assayed]
csi11-2LP(aaL199P,L209P)
csi11ΔNLS(47-65)

The author did these, and they even created a correct csi1 deletion as well!

But they should have popped up in the log "alleles not starting with a gene name" because ccsi11 is neither a primary name or a synonym?

https://curation.pombase.org/dumps/latest_build/logs/log.2022-09-22-22-13-54.chado_checks.AlleleNotStartingWithGeneName

So I wonder if this log is missing some things?

**Comment by ValWood** [comment]
> There is no csi11 in PomBase and that session has a bunch of alleles with csi11 in the name. Do they need fixing?
right you spotted that!, they should be caught already by the check?

**Comment by ValWood** [comment]
Also, I don't think these 2 examples are the only ones, because created WT alleles with a promoter prefix
e.g. nmt1-xxx1

**Comment by kimrutherford** [comment]
> Also, I don't think these 2 examples are the only ones, because created WT alleles with a promoter prefix
> e.g. nmt1-xxx1

This was only checking for multiple alleles in a session with the same name.

**Comment by kimrutherford** [comment]
> But they should have popped up in the log "alleles not starting with a gene name"

All your examples start with "csi1" and they are alleles of that that gene.  That's all the check does, it looks for the gene name at the start of the allele name.

**Comment by ValWood** [comment]
Right, so the check cannot differentiate  substring,

Could you tighten the check so that we see everything where there is not a dash. i.e. we should check for csi1- OR csi1delta not just csi1  (I have been trying to ensure that there is always a "-" seperator  are delta after the  gene name).

This will pick up things with spaces, and we can  repair these  with the  proposed script if there are many.

**Comment by ValWood** [comment]
> This was only checking for multiple alleles in a session with the same name.


OK!

**Comment by kimrutherford** [comment]
Unfortunately I'm still working on this.  It's more complicated than I thought.

I think tonight (Monday night) I'll be able to run the fix-up script I've been working on.  So that it will all be sorted out on Tuesday morning.

I'll be running the script on the test Canto instance first to check that it works and to see if it fixes #2636.

**Comment by kimrutherford** [comment]
> I think tonight (Monday night) I'll be able to run the fix-up script I've been working on. So that it will all be sorted out on Tuesday morning.

I think I got my days wrong in that comment.

I've now fixed on the test Canto database.  I'll do a little bit of final testing before doing the same thing to the main Canto instance.

**Comment by kimrutherford** [comment]
>  I'll do a little bit of final testing before doing the same thing to the main Canto instance.

I finally got back to this.  I did some more testing and found a case where the script probably isn't doing the right thing.

In this session `cdc13+[Knockdown]` appears in two single allele genotypes, one with a background and one without.  The script is merging the two genotypes.  The background may or may not be kept in the merged genotype depending on the order that the genotypes are found by the script.

Should the two genotypes be kept separate in these cases?

https://curation.pombase.org/pombe/curs/30da765280e4ffe0/genotype_manage/ro

Would it help to have a list of these cases?  There probably won't be too many.

**Comment by ValWood** [comment]
If there are 2 alleles with differnet backgrounds the script should n't merge them. BUT in the website we display them on the same page if that makes sense.

I think we would need a list but I am not quite sure I am understanding what is happening. How would we get the infor back if it is merged?
I will add this for discussion on the next call.

**Comment by kimrutherford** [comment]
>  BUT in the website we display them on the same page if that makes sense.

Don't we do that already?

> I think we would need a list

I'll make a list.

> How would we get the infor back if it is merged?

I was asking if they should be merged and you've said that they shouldn't.  So there's no problem.

**Comment by ValWood** [comment]
Val to find examples

**Comment by ValWood** [comment]
Actually the different deletions I mentioned are not curated differently. I did not know how to describe them because it isn't clear how they differ
curs/661292025a8cdee8/genotype_manage/ro
so one genotype has gls1Δ-H as the background 


I found a couple of sessions in the logs that have WT alleles with different names  from the same session:

nmt1-cig2-III	cig2	SPAPB2B4.03	5e98db8475cc3f3a
nmt1-cig2-II	cig2	SPAPB2B4.03	5e98db8475cc3f3a
nmt1-cig2-I	cig2	SPAPB2B4.03	5e98db8475cc3f3a

6x nmt:tif1-d3	tif1	SPAC1006.07	7cc0d044cd0fd080
1x nmt:tif1-d3	tif1	SPAC1006.07	7cc0d044cd0fd080
4x nmt:tif1-d3	tif1	SPAC1006.07	7cc0d044cd0fd080

**Comment by kimrutherford** [comment]
> I found a couple of sessions in the logs that have WT alleles with different names from the same session:

Hi Val.  Those examples aren't wild types.

![image](https://user-images.githubusercontent.com/90474/197711507-16bb17f9-8973-452d-b894-4475fb7e9e2a.png)
![image](https://user-images.githubusercontent.com/90474/197711626-270c799e-994a-4471-a2eb-412e61d5526a.png)

**Comment by ValWood** [comment]
I still did not find any, but it is on my radar...

**Comment by kimrutherford** [comment]
After double checking things and fixing some bugs I think I'm ready to run my script to remove duplicate alleles.  It's taken a while because didn't want to get it wrong on the main Canto database.

It will fix lots of cases like this:

https://curation.pombase.org/pombe/curs/b020334f9d974ddf/genotype_manage/ro

![image](https://github.com/pombase/canto/assets/90474/b8396a6e-c0fa-4e34-98d8-4b9eed2f8e50)

Most of the duplicates get merged on loading into Chado so this is mostly about tidying up Canto.

I'm going to run the script at the weekend because I'll be temporarily stopping the main Canto for a full backup and then to apply the fixing.

**Comment by ValWood** [comment]
Woo Hoo!

**Comment by kimrutherford** [comment]
> I'm going to run the script at the weekend

That's done now so the there should be no duplicate alleles in the Canto database.

Unfortunately there are still sessions with duplicate genotypes.  That's more of a cosmetic problem so I'll work on that later.
