### ISSUE TITLE
GO MF has_input prompt displays two ways

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2646]
ubiquitinates
and
modifies

<img width="318" alt="Screenshot 2022-10-17 at 15 26 47" src="https://user-images.githubusercontent.com/7359272/196208701-4029345d-b322-4c11-8d22-f849aa0672d5.png">

**Comment by kimrutherford** [comment]
These are the matching configurations:

    GO:0019787      is_a    has_input       ProteinID       modifies                0,1     user
    GO:0004842      is_a    has_input       ProteinID       ubiquitinates           0,1     user

Should we change things so that we don't suggest `modifies` if the term is a GO:0004842?  (GO:0004842 is more specific than GO:0019787)

**Comment by ValWood** [comment]
yes please

**Comment by kimrutherford** [comment]
I've changed the configuration and Canto now seems to be doing the right thing.
