### ISSUE TITLE
Enable diploid creation for all users

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2648]
Currently it's only for admin users.

**Comment by kimrutherford** [comment]
Fix pombase/canto#2652 first.

**Comment by ValWood** [comment]
wow thansks.
@manu to announce wth the GI  changes

**Comment by ValWood** [comment]
will reopen until announced

**Comment by manulera** [comment]
I think we should only announce the GIs in canto once we have an example curation session display, so that people can go and see them, you agree?

**Comment by ValWood** [comment]
makes sense.

**Comment by ValWood** [comment]
Can go ahead and announce diploid annotation  and GI

**Comment by manulera** [comment]
Announced late, but announced
