### ISSUE TITLE
debug-like error message when deleting single mutant phenotype annotation involved in GI

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2650]
Hi @kimrutherford 

When deleting a single mutant phenotype annotation involved in GI, you get this debug-like error:

![Screenshot 2022-10-24 at 19 33 14](https://user-images.githubusercontent.com/22526102/197600574-00e17222-251f-4286-8c2b-fe720a3a1cf2.png)

Instead of the more comprehensive one from double mutants:

![Screenshot 2022-10-24 at 19 32 51](https://user-images.githubusercontent.com/22526102/197600660-59282d84-7acc-4d48-b2ef-eb701b624137.png)

**Comment by kimrutherford** [comment]
Thanks Manu.  I think this is fixed now.  Please re-open if you see the problem again.
