### ISSUE TITLE
Show extension in single allele phenotype selection table

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2655]
Currently we only show the term ID and term name.

![image](https://user-images.githubusercontent.com/90474/199078352-37da6bea-74a8-4202-8364-10aadd36ca4f.png)

**Comment by kimrutherford** [comment]
I got that screenshot wrong.  We do show the extension in the dialog:

![image](https://user-images.githubusercontent.com/90474/200217754-6901b671-85eb-4021-a26d-da49c54f1b66.png)

but it's missing from the interaction table:

![image](https://user-images.githubusercontent.com/90474/200217806-74aed48b-ee20-4fa3-9d72-a8ed72396499.png)

**Comment by kimrutherford** [comment]
How's this?  The phenotypes are very readable now if there is more than one.

![image](https://user-images.githubusercontent.com/90474/200219290-28c48b4d-72ee-4f90-859b-4545ecd165c3.png)

**Comment by kimrutherford** [comment]
> How's this? The phenotypes are very readable now if there is more than one.

That's supposed to say "aren't very reabable".  :-)

I've deployed this change since it's better than not having the extensions.  But we can still tweak things.

**Comment by ValWood** [comment]
I think it's OK like this.

**Comment by kimrutherford** [comment]
OK, thanks.  We can change it later if needed.
