### ISSUE TITLE
Additional configuration

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2657]
In this situation:
<img width="950" alt="Screenshot 2022-11-07 at 12 50 55" src="https://user-images.githubusercontent.com/7359272/200319790-1becc9dc-456e-45c0-b35d-0bdc02f3b1c6.png">

a population growth mutant, with no over expression alleles., we don't need to see the first 2 
 GI types in the list.

**Comment by kimrutherford** [comment]
Which session was that?  I'd like to reproduce the problem on my desktop.

**Comment by ValWood** [comment]
https://www.pombase.org/reference/PMID:18667531
This one. It is also the one I curated not as PomBase...

**Comment by kimrutherford** [comment]
That should be fixed now.

We needed to limit the interaction types in the case where the genotype is not a double deletion and neither allele is over-expressed.
