### ISSUE TITLE
Assayed using with more than one gene or protein

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2658]
Is it possible to use more than one gene / protein in an assayed_using relation at the same time?

For context, we have a curation session with a heterodimer of two proteins, so it seems we need two UniProtKB accession numbers as the range of the assayed_using extension. There doesn't seem to be an obvious way to do this: maybe it requires editing the extension as text?

I'm presuming that the semantics of making two individual assayed_using extensions is that the assay is valid with _either_ protein (an OR relation) rather than it only being valid with _both_ proteins (an AND relation), but I don't know for sure if Canto makes this distinction.

CC: @CuzickA

**Comment by ValWood** [comment]
You can put 2 Ids in the assayed using extension.

if 2 proteins are to be considered simultaneously use a comma operator.
(If you use a pipe separator it will be interpreted as 2 independent annotations)
You will need to do this via the "edit as text"

**Comment by CuzickA** [comment]
Thanks @ValWood 

I have edited as text using a comma _assayed_using(P43431), assayed_using(P43432)_ and get the the below. Does this look correct to you?
![image](https://user-images.githubusercontent.com/11753634/200533610-a6727f7a-326c-4d79-b39a-4e65aace0636.png)

**Comment by ValWood** [comment]
yep!
