### ISSUE TITLE
Single alleles missing from genotype pages in view mode

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2659]
In this page, I only see the double allele phenotypes, but in the main session I can see all annotations
https://curation.pombase.org/pombe/curs/48be31dcce9039d3/genotype_manage/ro

**Comment by manulera** [comment]
When navigating in the same session I got some errors, did not manage to screenshot or trigger them again, but they said something did not manage to store genotype or something like that.

**Comment by kimrutherford** [comment]
Hi Manu.  I think this is OK.  There are no single allele genotypes in the session.  The front page shows a lot of single alleles in the "Existing single allele annotations" section, but they are from Chado.

**Comment by manulera** [comment]
Oh I see! I did not realise.
