### ISSUE TITLE
synthetic growth defect GIs don't appear in the  GI table

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2661]
PMID:21976700 

synthetic growth defect GIs don't appear in the  GI table?

<img width="1028" alt="Screenshot 2022-11-10 at 18 05 13" src="https://user-images.githubusercontent.com/7359272/201174597-92e6f290-4ebc-4143-902a-6328410bef28.png">

**Comment by kimrutherford** [comment]
I can see some interactions.  Which ones are missing?

![image](https://user-images.githubusercontent.com/90474/201271992-2a9d4fc1-b80e-4c1e-b5c0-6d7bbc67ec2e.png)
