### ISSUE TITLE
existing single allele  table not fully populating

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2664]
<img width="915" alt="Screenshot 2022-11-11 at 11 15 34" src="https://user-images.githubusercontent.com/7359272/201338553-ba599b3a-3321-4fe1-a358-819a87e64b3d.png">

**Comment by kimrutherford** [comment]
Which session is that?

**Comment by kimrutherford** [comment]
> Which session is that?

No problem, found it: https://curation.pombase.org/pombe/curs/95ec493fb8fa90cf/ro/

**Comment by kimrutherford** [comment]
That's fixed now.  The rows with missing phenotypes with extra phantom rows that shouldn't have been in the table.
