### ISSUE TITLE
Canto GI documentation

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2667]
Currently we have a section
[legacy genetic interaction](https://curation.pombase.org/pombe/docs/genetic_interaction_annotation): 

This should be replaced by a section describing how GIs are now created, and refer to the legacy GI to explain what they are.

This section should also be linked to , and from
"multiple alle  -phenotypes" since these need to be curated first.

**Comment by manulera** [comment]
We discussed that we would remove this Canto documentation, so I guess this can be closed when we do.

**Comment by ValWood** [comment]
see
https://github.com/pombase/canto/issues/2787
