### ISSUE TITLE
Upgrade to new Google Analytics system

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2671]
Needs to be done by June 2023: https://support.google.com/analytics/answer/11583528

Useful link from @jseager7: https://developers.google.com/analytics/devguides/migration/measurement/add-ga4

**Comment by kimrutherford** [comment]
Hi @jseager7.

We've done this now for PomBase Canto by following the prompts inside Analytics to get ourselves set up with GA4.  I can't remember, do you use Google Analytics?

**Comment by jseager7** [comment]
> I can't remember, do you use Google Analytics?

@kimrutherford We do, and currently we're still using the old UA-style identifier in `canto_deploy.yaml`.

**Comment by kimrutherford** [comment]
> We do, and currently we're still using the old UA-style identifier in canto_deploy.yaml.

So you'll need to set up GA4 and then add a `google_tag_manager_id` setting to `canto_deploy.yaml`.  For PomBase Canto, we were able just to follow the prompts in Analytics to set create a basic GA4 setup with a default configuration.  I'm happy to get on Skype/Zoom sometime to help if there's a problem.

**Comment by jseager7** [comment]
Thanks. Martin at PHI-base manages our Google Analytics, so I'll forward this to him.

**Comment by ValWood** [comment]
@kimrutherford  anything else for us to do here?

**Comment by kimrutherford** [comment]
> anything else for us to do here?

I'll close it.  If there are problems I'll open new issues.

**Comment by jseager7** [comment]
@kimrutherford Just to confirm, is the value of `google_tag_manager_id` the ID that would be included at the end of the googletagmanager.com URL?

`https://googletagmanager.com/gtag/js?id=[ID]`

I'm assuming it's not the Property ID of the GA4 Property Name.

**Comment by kimrutherford** [comment]
>  Just to confirm, is the value of google_tag_manager_id the ID that would be included at the end of the googletagmanager.com URL?

Yep!
