### ISSUE TITLE
normal vegetative cell population growth, improve search

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2672]
It is not possible to easily locate
normal vegetative cell population growth
even though it is an exact  term name, the li=onger stigns match with priority.

<img width="721" alt="normal" src="https://user-images.githubusercontent.com/7359272/204303175-52bca05a-0c40-4bc6-a7da-5e70983b32d9.png">

the only way I can ever got to it is with the ID FYPO:0001357

However if people search with a substring they find "normal vegetative cell growth"
so users always us this term instead, and I need to swap them over. I'm not even sure I have always noticed...

**Comment by kimrutherford** [comment]
Hi Val.  I'm surprised we haven't noticed this before.

Lucene weights matches higher if the text you search for occurs more frequently.  The words "normal vegetative cell population growth" occurs in the exact synonym "normal vegetative cell population growth on CCCP" and the words "normal cell population growth" occurs in three other synonyms of the same term.  Lucene thinks that's a good match.

Lucene's algorithm makes sense for documents but it's not so good in our case.

I've fixed this by weighting the text from the synonyms lower if a term has more synonyms.  It's somewhat undoing Lucene's algorithm but it seems to help.

The changes are deployed in the test Canto instance.  Could you have a quick test when you get a chance?  Maybe test with GO too?

**Comment by ValWood** [comment]
OMG this is so much better!!!
I seem to remember there was a reason for weighting for more frequent matches (maybe some special case), but exact matching seems preferable. If there are. any issues I will try to find old tickets, maybe tweaking the names/ synonyms in these cases would work better now. Let's go with this and improve from there.

**Comment by kimrutherford** [comment]
I've now updated the main Canto server with this change.

I'll close this issue but please open new issues if you see problems with the new completion suggestions.
