### ISSUE TITLE
Using Canto with Docker rootless mode

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2673]
Out of curiosity, I recently tried switching to Docker [rootless mode](https://docs.docker.com/engine/security/rootless/) on my development machine to see if it worked with Canto.

The good news is, Canto seems to work fine in rootless mode. The bad news is, it requires reverting a previous commit to `canto_start_docker` (da1e4e00aeab1e17f6640778c2df2cdc9535f430) that replaced published ports with host networking:

```sh
CANTO_DOCKER_RUN_ARGS="--rm -ti --publish 5000:5000"  # other arguments omitted
```

@kimrutherford Based on the commit message, you changed to host networking to make it "easier to connect with host services". I haven't tested any networking integration outside of connecting to Canto via a web browser, so I don't know if this change is going to break any other workflows. It might not bode well for running Canto with Vagrant (I should test this). Can you think of anything else that might be complicated by using published ports?

By the way, I can't find any obvious way to check whether the host machine is using Docker in rootless mode, so it's probably not straightforward to add a check for rootless mode and adjust the Docker arguments accordingly.

**Comment by kimrutherford** [comment]
I wish I had added a better commit message when I added host networking.  But I'm fairly sure that the "easier to connect with host services" means connecting to a PostgreSQL server.  FlyBase use Canto with Docker and their Canto needs to connect to an instance of the full FlyBase database.  I was easier with host networking.

If you're interested in using rootless mode for PHI-Canto we could add a new option to `canto_start_docker` to disable host networking and to add a `--publish` flag.

**Comment by jseager7** [comment]
Thanks for clarifying. In that case, adding an option sounds like the best choice. The most straightforward would be a `--rootless` argument that adds `--publish 5000:5000` when set, but since published ports aren't only needed for rootless mode, I'd prefer something more generic.

Maybe an argument named `--port` would be the most obvious, or `--publish` if we want to be consistent with Docker (since `--publish` seems to require specifying both a container port and a host port). If the argument is not set, then we default to host networking.

(Ideally, we would default to published ports since `--network=host` is apparently insecure ([see here](https://docs.docker.com/engine/reference/run/#network-host)), but that would cause problems for FlyBase now.)

I'm happy to create a PR for this if either of the options are okay with you.

**Comment by kimrutherford** [comment]
> Maybe an argument named --port would be the most obvious, or --publish if we want to be consistent with Docker

That makes sense.  Either `--port` or `--publish` sounds OK to me.

> I'm happy to create a PR for this if either of the options are okay with you.

Thanks!  That would be great.
