### ISSUE TITLE
diploids in the wrong table

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2674]
PMID:36408846

diploid multi-alle genotypes  appear in the single allele genotype table:

<img width="990" alt="Screenshot 2022-11-28 at 18 38 23" src="https://user-images.githubusercontent.com/7359272/204355056-bea03165-2530-48f5-9bf8-8cf0ce9ddc0a.png">

This means that I can't add phenotypic rescue interactions to them. I don't often diploids very often, clearly!

**Comment by ValWood** [comment]
ignore me they aren't in the wrong table. BUT, there is no add interactions link visible. ?

**Comment by kimrutherford** [comment]
> ignore me they aren't in the wrong table. BUT, there is no add interactions link visible. ?

The code doesn't support diploids at all at the moment.  Let's talk about this on Zoom.

**Comment by ValWood** [comment]
I think that is OK. I thought that the whole table  no longer supported interactions if the table contains diploids, but when I look closely that was not the case.
It wouldn't really make sense to do GIs in diploids. So no problem here, and no action required.
