### ISSUE TITLE
Canto weirdness synonyms

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2683]
In this session curs/a6782fab5fd233d0/

The author had added lots of synonyms  in the gene name line. I went through the session and migrated these to  allele synonyms (About 30 of them).

I could see them appearing as genotype synonyms just fine. However after I reloaded the page, all of the synonyms disappeared from the session?

**Comment by ValWood** [comment]
This is what the alleles looked like before I moved the bracketed part  into the synonyms field

https://www.pombase.org/genotype/asp1-%281-584%29_%28STF12%29-585-920-partial_amino_acid_deletion-expression-not_assayed

**Comment by ValWood** [comment]
these were some of them (but there were many more that did not cause log file conflicts)


SPCC1672.06c	asp1-H686Y (STF7)	a6782fab5fd233d0	H686Y	asp1-H686Y	4228fd893e7a1a88
  SPCC1672.06c	asp1-G863D (STF3,11,14)	a6782fab5fd233d0	G863D	asp1-G863D	4228fd893e7a1a88
  SPCC1672.06c	asp1-C643Y (STF5,8)	a6782fab5fd233d0	C643Y	asp1-C643Y	4228fd893e7a1a88
  SPCC1672.06c	asp1-(1-492) (STF9)	a6782fab5fd233d0	493-920	asp1-(1-492)	4228fd893e7a1a88

**Comment by kimrutherford** [comment]
I think I'll need you to walk me through this on Zoom sometime.  I can't reproduce the problem.

**Comment by kimrutherford** [comment]
>> I think I'll need you to walk me through this on Zoom sometime. I can't reproduce the problem.
>
> OK let me know when.
> It can be after the holidays.

I forgot about this issue.  It's definitely after the holidays now.  :-)

I can chat any morning.

**Comment by ValWood** [comment]
not reproducible
