### ISSUE TITLE
Duplicate genotypes in 4927cddae28a3185

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2684]
There are multiple "fin1-as3(analog-sensitive)[Not assayed]" genotypes.

https://curation.pombase.org/pombe/curs/4927cddae28a3185/genotype_manage/ro

![image](https://user-images.githubusercontent.com/90474/210121934-f9caf264-64bf-487b-bfce-231ba32cf32b.png)

**Comment by kimrutherford** [comment]
I retrieved this session from the backups from Dec 18th, from before you edited it.  There are no duplicates in that version.  I've tried to reproduce the problem starting with that.  No luck so far.

**Comment by ValWood** [comment]
try removing  a single mutant with no annotations that is associated with a double mutant. then reload (I didn't try it but I think most of the duplicates have no annotations)

**Comment by kimrutherford** [comment]
I just tried that.  Still no luck.  I'll have a think and try again on Monday.

**Comment by kimrutherford** [comment]
> I just tried that. Still no luck. I'll have a think and try again on Monday.

I've had no joy with this.

I think it's the same problem as pombase/canto#2682 so I'm going to close it.
