### ISSUE TITLE
Amino acid ordering in allele descriptions

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2686]
@ValWood For allele types that involve an amino acid substitution, is the new amino acid supposed to be placed after the old amino acid, or before?

The PomBase help text has the following instructions:

> For combinations of substitutions, insertions, and/or deletions, separate parts of the description with commas. For example, "858-MKGYP,F124D" means five amino acid residues were inserted after position 858, **and Asp was changed to Phe at position 124**.

The text mentions a substitution from Asp (D) to Phe (F), but the allele description (F124D) seems to imply the opposite direction, from Phe (F) to Asp (D). I've found guidance from one other source ([here](https://varnomen.hgvs.org/recommendations/protein/variant/substitution/)) that recommends placing the old amino acid before the new amino acid:

> Format: “prefix”“amino_acid”“position”“new_amino_acid”, e.g. p.(Arg54Ser)

Is the example in the documentation a mistake, or does PomBase use different conventions?

**Comment by ValWood** [comment]
Well spotted, this should be
Phe was changed to Ala at position 124
@kimrutherford

**Comment by jseager7** [comment]
> this should be Phe was changed to Ala at position 124

@ValWood Did you mean to say "Phe was changed to **Asp** at position 124"? Alanine's 1-letter symbol is A, not D. Or should the allele description be F124A?

**Comment by ValWood** [comment]
fixed

**Comment by ValWood** [comment]
Fixed comment
