### ISSUE TITLE
Use the allele_qc api to prevent addition of errors

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2688]
There is a small python http API in the allele_qc repo that can be used to check whether an allele description is correct: https://github.com/pombase/allele_qc/blob/master/api.py

You can try it in your machine easily using docker, see instructions [here](https://github.com/pombase/allele_qc#running-the-api-in-docker). If you go to the root url, you will be re-directed to the api docs built with swagger.

## Check alleles

The end-point to be used is `/check_allele` (POST).

An example request payload:

```json
{
  "systematic_id": "SPBC359.03c",
  "allele_description": "V123A,PLR140AAA,150-600",
  "allele_type": "partial_amino_acid_deletion"
}
```

The generated response:

```json
{
  "allele_parts": "V123A|PLR140AAA|150-600",
  "needs_fixing": true,
  "change_description_to": "V123A,PLR-140-AAA,150-600",
  "rules_applied": "amino_acid_mutation:single_aa|amino_acid_mutation:multiple_aa|partial_amino_acid_deletion:multiple_aa",
  "pattern_error": "",
  "invalid_error": "",
  "sequence_error": "V123|P140/L141/R142|600",
  "change_type_to": "amino_acid_deletion_and_mutation",
  "user_friendly_fields": {
    "allele_parts": "We identified 3 parts in the allele description, which are: V123A, PLR140AAA, 150-600",
    "needs_fixing": true,
    "change_description_to": "There is a syntax error in the allele description, it should be changed to: V123A,PLR-140-AAA,150-600",
    "rules_applied": "We identified that the allele parts correspond to the following types of mutations: amino_acid_mutation, amino_acid_mutation, partial_amino_acid_deletion",
    "pattern_error": "",
    "invalid_error": "",
    "sequence_error": "The following sequence positions don't exist: 600\nThe following sequence positions don't contain the indicated residues: V123,P140/L141/R142",
    "change_type_to": "The indicated allele_type is not correct based on the existing mutations, it should be changed to amino_acid_deletion_and_mutation",
    "user_friendly_fields": null
  }
}
```

The fields in the response correspond to the columns in `allele_auto_fix.tsv` file (see https://github.com/pombase/canto/issues/2689), but there is the extra `user_friendly_fields` json which contains human-readable versions of the table fields. If `needs_fixing` is true, the error messages could be combined into something like this (I could do it at the API level but probably you need the formatting to be done at the frontend):

> We identified 3 parts in the allele description, which are: V123A, PLR-140-AAA, 150-600. We identified that the allele parts correspond to the following types of mutations: amino_acid_mutation, amino_acid_mutation, partial_amino_acid_deletion. We found the following errors:
> 
> * **Syntax error**: There is a syntax error in the allele description, it should be changed to: V123A,PLR-140-AAA,150-600.
> * **Sequence error:** 
>     * The following sequence positions don't exist: 600
>     * The following sequence positions don't contain the indicated residues: V123,P140/L141/R142.
> * **Type error:** The indicated allele_type is not correct based on the existing mutations, it should be changed to amino_acid_deletion_and_mutation

## Check protein modifications

Same story with the protein modifications, POST request to `/check_modification` (can only have sequence and syntax errors):

Example request:

```json
{
  "systematic_id": "SPBC359.03c",
  "sequence_position": "V123; V124,V125"
}
```

Generated response:

```json
{
  "needs_fixing": true,
  "sequence_error": "V123|V124|",
  "change_sequence_position_to": "V123,V124,V125",
  "user_friendly_fields": {
    "needs_fixing": true,
    "sequence_error": "The following sequence positions don't contain the indicated residues: V123,V124",
    "change_sequence_position_to": "There is a syntax error in the modification description, it should be changed to: V123,V124,V125",
    "user_friendly_fields": null
  }
}
```

If `needs_fixing`, could give a message like this:

> The following errors were found:
>  * **Syntax error:** There is a syntax error in the modification description, it should be changed to: V123,V124,V125
>  * **Sequence error:** The following sequence positions don't contain the indicated residues: V123,V124

**Comment by kimrutherford** [comment]
I'm working on this now.  Below are some screenshots.  I'll update Canto with these changes tomorrow.  The changes are only visible when logged in as admin for now.

Because it's simpler, in the current implementation you need to manually click on the "Check" button to get checking to happen.  It would be better to check as the user types the description.

![image](https://github.com/pombase/canto/assets/90474/2cdc5146-cea2-4a68-8362-21277f77f39e)

-----------------------------------------

Enter allele name, type and description to get a "Check" button:

![image](https://github.com/pombase/canto/assets/90474/ed89c581-9c22-4fbd-8620-24c4125db9a2)

-----------------------------------------

Result dialog:

![image](https://github.com/pombase/canto/assets/90474/5b9b7e22-474c-4ad8-b42b-01ba25c21d89)

-----------------------------------------

Errors are marked with "X":

![image](https://github.com/pombase/canto/assets/90474/c0b9eeac-dc53-4e34-b331-a68d029b9f19)

-----------------------------------------

Mouse over in case you forgot what the error was:

![image](https://github.com/pombase/canto/assets/90474/fbf69b27-7caa-4174-959a-fcc1ab84f8a0)

-----------------------------------------

If all is OK you get a ":heavy_check_mark:": 

![image](https://github.com/pombase/canto/assets/90474/52df3b4c-b453-49f7-9146-beb6c61f54c6)

**Comment by kimrutherford** [comment]
I've started implementing things in a similar way for modifications.  It's just a prototype for now but it's testable in the main Canto if you log in as admin.

![image](https://github.com/pombase/canto/assets/90474/2cc67e17-72dd-4ee7-b4e1-6fb51076a373)

---------------------------------

![image](https://github.com/pombase/canto/assets/90474/be4ae1c9-9744-4fe3-8b23-a6dca8a87f4a)

---------------------------------

![image](https://github.com/pombase/canto/assets/90474/69e5b755-1b95-46f6-9010-46bc624a7c57)

**Comment by kimrutherford** [comment]
I've added the summary messages to allele description error dialog to more closely match your suggestion.

![image](https://github.com/pombase/canto/assets/90474/6913acd6-a786-4e94-ab14-c7bc71bd38ee)

**Comment by manulera** [comment]
> Here's the test session to play with: https://curation.pombase.org/pombe/curs/4666975359de04dd/genotype_manage

Hi @kimrutherford, the screenshots look great! I cannot access the canto test server today, and the PMID:1 session in the normal canto session mentioned.

**Comment by manulera** [comment]
I tested and it looks great both for modifications and alleles!

I wonder if people will always check, or if they will forget.

It would be good if either:
* The wrong ones could be flagged even if approved (I guess this would require some extra field in canto db, so not great)
* We had an admin-only button to run on all the alleles of a session at any point, and flag/print the ones that give errors (even if the exact error is not shown, we can then go into the allele and click on Check).

Not sure what's easiest / requires less changes, or if there is an easier solution.

**Comment by kimrutherford** [comment]
That's a good point.  We will need an easy way for the approver to check that all the alleles are OK in the session.

**Comment by kimrutherford** [comment]
> I cannot access the canto test server today

I've fixed the test Canto by updating to the latest code and restarting.

**Comment by kimrutherford** [comment]
> By the way, the allele types that can be checked are those that contain either "nucleotide" or "amino" in them.

Thanks.

I've added that to the code and configuration.

And I've removed the "Check" button.  The allele QC checks now happen when you click on "OK".

I've deployed these changes in the test Canto for now:
https://curation.pombase.org/test/curs/4666975359de04dd/genotype_manage#/edit/60

**Comment by ValWood** [comment]
I'm loving the "check" button. It caught a misclassified mutant type for me yesterday!

**Comment by kimrutherford** [comment]
> I'm loving the "check" button. It caught a misclassified mutant type for me yesterday!

Could you try the same annotation in the test Canto when you get a chance?  I'd like to know what you think of the changes.

**Comment by manulera** [comment]
Looks great to me! I think it feels very natural to encounter this type of message, like a form validation.

**Comment by manulera** [comment]
@ValWood remember that it's only on the admin mode, even on the test server

**Comment by ValWood** [comment]
Yes it works well.

This is the message if you get it wrong:
<img width="681" alt="Screenshot 2023-08-31 at 11 11 01" src="https://github.com/pombase/canto/assets/7359272/b5594ec3-9066-4208-a846-3a9bb447ceba">

The first 2 line of the message seem unecessary, at least in this case.
Will they be hidden?

**Comment by manulera** [comment]
> The first 2 line of the message seem unecessary, at least in this case.
> Will they be hidden?

I think they should come below the error. The header can be "More info" or something like this. In some case, the person might not understand why they are getting an error, and it could be that they have used the syntax for another type of allele.

They could also be omitted

**Comment by manulera** [comment]
Also, another thing that I realised, this time for the protein modification checking. As it is now, you can select the extension before picking the gene, so it makes more sense to do the checking when you do the "final click" on OK, like for the alleles.

**Comment by ValWood** [comment]
I love it, only see what  you need.

**Comment by kimrutherford** [comment]
> We could do something like this:

That's committed and in the main Canto now.

**Comment by manulera** [comment]
Alrightt

**Comment by kimrutherford** [comment]
Still to do:

> Also, another thing that I realised, this time for the protein modification checking. As it is now, you can select the extension before picking the gene, so it makes more sense to do the checking when you do the "final click" on OK, like for the alleles.

**Comment by kimrutherford** [comment]
> Also, another thing that I realised, this time for the protein modification checking. As it is now, you can select the extension before picking the gene, so it makes more sense to do the checking when you do the "final click" on OK, like for the alleles.

I'll work on that soon.

For now I've made the interface a bit more consistent by removing this "Check" button:

![image](https://github.com/pombase/canto/assets/90474/be4ae1c9-9744-4fe3-8b23-a6dca8a87f4a)

and instead the checks are now done when you click "Ok".

**Comment by manulera** [comment]
Nice!

**Comment by kimrutherford** [comment]
I've enabled the allele QC checker for all users.

**Comment by kimrutherford** [comment]
Hi @ValWood 

The modification position modified checker is only enabled for admin users at the moment.  Should I make it available for all users?

**Comment by ValWood** [comment]
yes please!

**Comment by kimrutherford** [comment]
> The modification position modified checker is only enabled for admin users at the moment. Should I make it available for all users?

Done!

**Comment by kimrutherford** [comment]
I think this is all done.
