### ISSUE TITLE
Cant message for partially curated papers

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2694]
https://www.pombase.org/reference/PMID:30155942

Here the message says:
This paper has partial curation that predates PomBase and Canto. Please [contact the curators](mailto:helpdesk@pombase.org?subject=Request%20to%20contribute%20annotations%20for%20PMID:30155942) if you would like to contribute to its full curation.

but this message does not always work. In this instance the curation is from BioGRID.

Maybe the message should say:
This paper has partial curation that predates PomBase and Canto, OR IS IMPORTED FROM A THIRD PARTY DATABASE. Please [contact the curators](mailto:helpdesk@pombase.org?subject=Request%20to%20contribute%20annotations%20for%20PMID:30155942) if you would like to contribute to its full curation.

**Comment by kimrutherford** [comment]
I've added that to the reference pages.
