### ISSUE TITLE
new style genetic interactions are not always displayed

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2695]
In this session, I only see the synthetic lethals, even though I curated 4 GIs
<img width="969" alt="canto bug, not all GIs appearing" src="https://user-images.githubusercontent.com/7359272/216831996-237eb320-57f8-465c-8f0b-c5a8b41d62ed.png">

**Comment by ValWood** [comment]
curs/291d614ef0c90bc4

**Comment by kimrutherford** [comment]
Could you try re-loading?  I see 4 rows:

![image](https://user-images.githubusercontent.com/90474/216849334-76550f26-4cc2-4751-a50c-f912ed8c8d9f.png)

**Comment by ValWood** [comment]
yep all good.
