### ISSUE TITLE
Display comments in canto annotation interface when adding a phenotype

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2696]
Hello @kimrutherford @ValWood 

I was adding a term for Maria's HTP paper to FYPO (finally) and I realised that the comment annotations are not displayed in Canto when you select the terms. My understanding is that warnings to curators do not belong in the definition, but it would be good to show them to users. The example right now is a new term: 

* **Label:** `increased cell population viability during vegetative growth`
* **Definition:** A vegetative cell population phenotype in which a larger than normal proportion of cells is viable. In High Throughput Phenotyping this is typically assessed using phloxine as a dye.
* **Comment:** Not to be confused with cell population growth phenotypes, which are measured with culture density or by serial dilution on solid medium.

I think it would be good to show this kind of warning in Canto to help users make better annotations. Also comments such as "We recommend noting which protein(s) were used in the assay when annotating to this term."

They could be shown in this kind of pop-up. Also, probably the headers in the popup could be smaller if more space is needed.

![Screenshot 2023-02-16 at 17 08 12](https://user-images.githubusercontent.com/22526102/219437516-90e6ced8-4043-4798-a7f2-b873d41de671.png)

**Comment by manulera** [comment]
Also probably better to say 'increased vegetative cell population viability'

**Comment by ValWood** [comment]
Agree, I thought we could see comments.  But maybe it is when you get to the page, but really you need the comment earlier...
