### ISSUE TITLE
add a select all box for annotation transfer

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2697]
Here:
<img width="408" alt="Screenshot 2023-02-17 at 17 04 31" src="https://user-images.githubusercontent.com/7359272/219782997-7e0c9941-fd80-44c2-a1ad-cee8f063ff3b.png">

not urgent, but would be nice

**Comment by kimrutherford** [comment]
That's done now.  Let me know if there are any problems.

![image](https://user-images.githubusercontent.com/90474/224612443-f9ccf0c4-5830-435c-b735-0b12e3a1c457.png)
