### ISSUE TITLE
New roles in Canto

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2698]
Currently we have "user" and "admin" roles.  We could use the role to capture:

  - retired_user
  - group_leader
  - retired_group_leader

We had a better word than "retired" to cover those user who aren't retired but who don't do pombe work anymore.  I can't remember it though.

I'm sure there we another role that we talked about that I've forgotten.

**Comment by ValWood** [comment]
inactive ?

**Comment by kimrutherford** [comment]
> inactive ?

Thanks.  That's much better.

So:
  - admin
  - user
  - inactive_user
  - group_leader
  - inactive_group_leader

**Comment by ValWood** [comment]
Looks good!

**Comment by kimrutherford** [comment]
That's done now.

https://curation.pombase.org/pombe/view/object/cv/6?model=track
