### ISSUE TITLE
canto unavailable message

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2704]
I keep getting this, and sometimes it doesn't go away until I reload:

<img width="1075" alt="Screenshot 2023-03-11 at 15 05 06" src="https://user-images.githubusercontent.com/7359272/224495496-c13f9da9-81dc-4b3b-86fb-a5f3095cbda2.png">

**Comment by kimrutherford** [comment]
Sounds like it could be a Chrome bug on slow or unstable connections: https://bugs.chromium.org/p/chromium/issues/detail?id=1237907

**Comment by ValWood** [comment]
I think it is my connection, but a reload usually solves it. It's a pity the message isn't different. I am worried if others get this they abandon Canto (it only happens for me with Canto and sometimes the message is there for a minute or more)

**Comment by ValWood** [comment]
duplicate
https://github.com/pombase/canto/issues/2547
