### ISSUE TITLE
ORCID prefilling

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2705]
Sometimes my ORCID is prefilled, but sometimes it has my e-mail

<img width="604" alt="Canto orcids" src="https://user-images.githubusercontent.com/7359272/224495642-b6a18bd9-8255-4f50-800c-3a145db30b8c.png">

I haven't figured out when this happens, will document next time...

**Comment by kimrutherford** [comment]
I haven't worked this out entirely but if it's a session that you have assigned to yourself the ORCID should be pre-filled.

If we implement your suggestion here I think the problem will go away: https://github.com/pombase/canto/issues/1409#issuecomment-462071319

**Comment by ValWood** [comment]
I haven't noticed it recently
