### ISSUE TITLE
map all merged  GO IDs over to primary IDs

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2708]
GO will at some unmerge and obsolete all merged IDs with a "replaced_by" tag.

We need to map secondary GO IDs over to the primary IDs throughout PomBase ( Chado and Canto).
Currently, we automatically Display the correct term for secondary IDs, but in Canto, we keep the old ID. Eventually, the merged IDs will be emerged and obsoleted by GO.
For now, we will deal with continue to deal with  'replaced by' obsoletions is in the log file. If this becomes too time-consuming, we will automatically remap. This can be done as a separate task later.

**Comment by kimrutherford** [comment]
Hi Val.  I've started work on this.

Unless I've messed up my script, there are only 27 alt_ids in extensions and there are no alt_ids as the main annotation term.  Is it possible that you've been fixing them as they occur?

**Comment by ValWood** [comment]
I don't remember fixing them.
unless they are reported in the logs with the obsoletes, and i have forgotten.

**Comment by kimrutherford** [comment]
> 27 alt_ids in extensions

This weekend, I'll run the script to fix the 27 alt_ids in extensions.  It needs a bit of down time so I'll do it on Sunday morning.

I've double checked and the only place where there are alt_ids are in extensions.

**Comment by kimrutherford** [comment]
> If you don't get time don't worry. I don't think GO will be doing this soon ;)

I'm keen to get it done while it's fresh in my mind.  Also it will mean there are very few fixes to make when GO does go ahead.

Here's the output of the script showing the changes I'll be making.  The number at the start of the line is the number of occurrences in the session:

```
 1 1eee81410bebb43e: found alt_id in extension: GO:0072434 -> GO:0007095 (mitotic G2 DNA damage checkpoint signaling)
 1 2f5adb6aec169e1f: found alt_id in extension: GO:0098783 -> GO:0140429 (positive regulation of mitotic sister chromatid biorientation)
 1 3d88b1b5a61259cf: found alt_id in extension: GO:0000081 -> GO:0007089 (traversing start control point of mitotic cell cycle)
 2 4488533ca5f8fdc3: found alt_id in extension: GO:0000081 -> GO:0007089 (traversing start control point of mitotic cell cycle)
 1 6dd31d982c2e470c: found alt_id in extension: GO:1990141 -> GO:0031508 (pericentric heterochromatin formation)
 3 8b5476ba0daf2d2d: found alt_id in extension: GO:1904804 -> GO:0120306 (cellular response to actin cytoskeletal stress)
 2 8b5476ba0daf2d2d: found alt_id in extension: GO:1904805 -> GO:0120306 (cellular response to actin cytoskeletal stress)
 2 98f0242de16564e8: found alt_id in extension: GO:0072434 -> GO:0007095 (mitotic G2 DNA damage checkpoint signaling)
 1 9b6d37d028f7da71: found alt_id in extension: GO:0072450 -> GO:0031568 (mitotic G1 cell size control checkpoint signaling)
 2 a0db0af7ec94b4a9: found alt_id in extension: GO:0000081 -> GO:0007089 (traversing start control point of mitotic cell cycle)
 1 c22f209fe76ffcd8: found alt_id in extension: GO:1902409 -> GO:0000920 (septum digestion after cytokinesis)
 1 f02a15cea2c40c03: found alt_id in extension: GO:1990421 -> GO:0099115 (chromosome, subtelomeric region)
 2 f938aca48cd3f966: found alt_id in extension: GO:1904804 -> GO:0120306 (cellular response to actin cytoskeletal stress)
 2 fa51a7649e995191: found alt_id in extension: GO:1905121 -> GO:0000022 (mitotic spindle elongation)
 5 fb4ffc5eba4ac1e6: found alt_id in extension: GO:0010388 -> GO:0000338 (protein deneddylation)
```

**Comment by kimrutherford** [comment]
That's done now.  There should be no GO alt_ids in Canto now.

Note to self:
```
./etc/remove_alt_ids.pl 'GO'
```
