### ISSUE TITLE
Canto fix reversions?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2710]
SPCC24B10.07	gad8ts-S240P	155dba22ce11dc4f	S240P	gad8-S240P	155dba22ce11dc4f

I fixed these last night, and made gad8ts-S240P a synonym. I definitely did it because I was on the phone to a friend (I was listening to her honestly) but today they are back to gad8ts-S240P

Any ideas.

<img width="527" alt="Screenshot 2023-03-16 at 08 25 47" src="https://user-images.githubusercontent.com/7359272/225558652-91ba42e2-cc5a-404c-ad3e-41b458283ff6.png">

CC
@manulera 
@kimrutherford

**Comment by kimrutherford** [comment]
Can we have Zoom call sometime about this?  It would help to see how you're making the changes so I can reproduce the problem.

**Comment by ValWood** [comment]
yes sure. I won't do any logs today. I'll do GO tomorrow. We can chat about this on Tuesday or Weds.
val

**Comment by ValWood** [comment]
Kim will auto fix

**Comment by kimrutherford** [comment]
Hi Val.

> Kim will auto fix

I've finally got to this.  Its been long enough that I want to check my work before I go ahead.  I've made this change to my local copy of Canto as a test.  If the screenshot looks OK, I'll change the main Canto.

![image](https://user-images.githubusercontent.com/90474/234173363-b1f1af8a-976f-442e-aef7-0a444bd85f36.png)

**Comment by ValWood** [comment]
Looks good.  Do they have the -ts version of the allele as a synonym?

**Comment by ValWood** [comment]
If so, go ahead.

**Comment by kimrutherford** [comment]
> Looks good. Do they have the -ts version of the allele as a synonym?

Yep!  If there are any problems, I'll fix them.
