### ISSUE TITLE
Remove "nonsense" mutation option from Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2712]
Once annotations are migrated
https://github.com/pombase/canto/issues/2689#issuecomment-1478480261

**Comment by kimrutherford** [comment]
There are still 63 nonsense mutations but pombase/canto#2689 is closed/finished.  We probably need a quick chat about that when Manu is back.

**Comment by kimrutherford** [comment]
We're down to 18 nonsense mutations.  None of them have any annotations as far as I can see:

|curation_sessions |allele_description |allele_name        |gene                |references     |
|-------------------|--------------------|--------------------|--------------------|---------------|
|[155dba22ce11dc4f ](https://curation.pombase.org/pombe/curs/155dba22ce11dc4f )  |E31->stop         |not2-E31STOP       |not2(SPCC4G3.15c)|PMID:34028542  |
|[155dba22ce11dc4f ](https://curation.pombase.org/pombe/curs/155dba22ce11dc4f )  |E644->stop        |bro1-E644STOP      |bro1(SPAC17G6.05c)|PMID:34028542  |
|[155dba22ce11dc4f ](https://curation.pombase.org/pombe/curs/155dba22ce11dc4f )  |L636STOP            |tsc2-L636STOP      |tsc2(SPAC630.13c)|PMID:34028542  |
|[155dba22ce11dc4f ](https://curation.pombase.org/pombe/curs/155dba22ce11dc4f )  |N147D               |pcs2-N147D         |pcs2(SPAC3H1.10) |PMID:34028542  |
|[155dba22ce11dc4f ](https://curation.pombase.org/pombe/curs/155dba22ce11dc4f )  |Q175->stop        |SPAC1296.01c-Q175STOP|SPAC1296.01c       |PMID:34028542  |
|[155dba22ce11dc4f ](https://curation.pombase.org/pombe/curs/155dba22ce11dc4f )  |Q202->stop        |sst4-Q202STOP      |sst4(SPAC19A8.05c)|PMID:34028542  |
|[155dba22ce11dc4f ](https://curation.pombase.org/pombe/curs/155dba22ce11dc4f )  |Q207->stop        |sst6-Q207STOP      |sst6(SPAC11H11.01)|PMID:34028542  |
|[155dba22ce11dc4f ](https://curation.pombase.org/pombe/curs/155dba22ce11dc4f )  |Q40->stop         |puf2-Q40STOP       |puf2(SPBP35G2.14)|PMID:34028542  |
|[155dba22ce11dc4f ](https://curation.pombase.org/pombe/curs/155dba22ce11dc4f )  |Q688STOP            |tsc1-Q688STOP      |tsc1(SPAC22F3.13)|PMID:34028542  |
|[155dba22ce11dc4f ](https://curation.pombase.org/pombe/curs/155dba22ce11dc4f )  |R148->stop        |ppk14-R148STOP     |ppk14(SPAC4G8.05)|PMID:34028542  |
|[155dba22ce11dc4f ](https://curation.pombase.org/pombe/curs/155dba22ce11dc4f )  |S117->stop        |osh6-S117STOP      |osh6(SPCC23B6.01c)|PMID:34028542  |
|[155dba22ce11dc4f ](https://curation.pombase.org/pombe/curs/155dba22ce11dc4f )  |W113->stop        |vps25-W113STOP     |vps25(SPBC4B4.06)|PMID:34028542  |
|[155dba22ce11dc4f ](https://curation.pombase.org/pombe/curs/155dba22ce11dc4f )  |W170->stop        |sst4-W170STOP      |sst4(SPAC19A8.05c)|PMID:34028542  |
|[155dba22ce11dc4f ](https://curation.pombase.org/pombe/curs/155dba22ce11dc4f )  |Y416->stop        |puf2-Y416STOP      |puf2(SPBP35G2.14)|PMID:34028542  |
|[5eae8ab56540b745 ](https://curation.pombase.org/pombe/curs/5eae8ab56540b745 )  |D543->stop        |tht1-D543*        |tht1(SPAC13C5.03)|PMID:9442101   |
|[865ebc50ec806a07 ](https://curation.pombase.org/pombe/curs/865ebc50ec806a07 )  |Q64->stop         |                    |sgf11(SPAC57A10.14)|PMID:29352077  |
|[865ebc50ec806a07 ](https://curation.pombase.org/pombe/curs/865ebc50ec806a07 )  |Q64->stop         |sgf11-Q64->stop  |sgf11(SPAC57A10.14)|PMID:29352077  |
|[94b54d8b1a931fb9 ](https://curation.pombase.org/pombe/curs/94b54d8b1a931fb9 )  |R162->stop        |slr9-1             |ctp1(SPCC338.08) |PMID:18378696  |

**Comment by kimrutherford** [comment]
The nonsense mutation open was removed from Canto a while ago, so I'll close this.

I've moved the list of remaining nonsense mutations to a curation issue:
  -  pombase/curation#3574

**Comment by jseager7** [comment]
@kimrutherford by 'removed from Canto' do you mean removed from the configuration that PomBase uses for Canto, or removed from the application entirely? Because PHI-base are using this allele type for annotations in at least two curation sessions and we may need it in future.

**Comment by ValWood** [comment]
@jseager7 for some background, we. decided to treat these as partial amino acid deletion (they represent truncated proteins), because mutating a residue to a stop codon, or deleting the C-terminal portion of a gene are technically equivalent. 
You mat want to do the same  (it means that the information on such alleles will be represented   on te same genotype)
@CuzickA

**Comment by kimrutherford** [comment]
> by 'removed from Canto' do you mean removed from the configuration that PomBase uses for Canto, or removed from the application entirely? 

Hi James.  Sorry I didn't mention this to you earlier.  We've removed nonsense mutation from the default configuration.  Existing sessions and exporting of alleles of that type will still be OK but you won't be able to add more unless you change the PHI-Canto config.  You'll need to copy the `allele_type_list` setting into your `canto_deploy.yaml` and uncomment the `nonsense mutation` bit:

```yaml
   # - name: nonsense mutation                                                                                                                                               
   #   export_type: nonsense_mutation                                                                                                                                        
   #   show_description: true                                                                                                                                                
   #   description_required: true                                                                                                                                            
   #   allow_expression_change: true                                                                                                                                         
   #   expression_required: true                                                                                                                                             
   #   allele_name_required: false                                                                                                                                           
   #   placeholder: 'e.g. P123*' 
```

**Comment by jseager7** [comment]
> You'll need to copy the allele_type_list setting into your canto_deploy.yaml and uncomment the nonsense mutation bit:

Thanks. We've already done this because we had to add a new allele type some time ago, so we shouldn't have any disruption from this change.

**Comment by kimrutherford** [comment]
> We've already done this because we had to add a new allele type some time ago

OK, no problem then.  :-)
