### ISSUE TITLE
Cannot copy physical interaction in Canto

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2713]
https://user-images.githubusercontent.com/22526102/227541561-b8929852-eb4d-40ae-ba0c-06d3f2b2442a.mov

Probably to do with some GI constrain?

Same when using transfer:

![Screenshot 2023-03-24 at 14 01 04](https://user-images.githubusercontent.com/22526102/227541922-e489a2ab-e38e-49bc-bcc2-519520646c31.png)

**Comment by kimrutherford** [comment]
Thanks Manu.  I think I've fixed that now.
