### ISSUE TITLE
Headers of GI table in Canto

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2715]
I think we could simply rename the last header "Single mutant phenotype", because it's not always a rescue.

![Screenshot 2023-03-24 at 14 44 45](https://user-images.githubusercontent.com/22526102/227558200-749e30a5-6cf2-4019-8513-89823dde1b65.png)

cc: @ValWood

**Comment by ValWood** [comment]
Yes, I think we decided this verbally at some point.

**Comment by kimrutherford** [comment]
OK, done.
