### ISSUE TITLE
Genotype management: Annotations not being counted for a phenotype

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2716]
![Screenshot 2023-03-27 at 12 17 05](https://user-images.githubusercontent.com/22526102/227926799-e88440dd-3d44-4e0c-a921-2972dbc277fd.png)

In this session:

PMID:33536434
https://curation.pombase.org/pombe/curs/a5289f010104594b/genotype_manage

mamRNAdelta has several phenotype annotations, and Canto does not allow to delete the genotype, but the count of annotations is zero.

**Comment by kimrutherford** [comment]
> This is because the genotype is used in a multi-gene genotype so I think this is OK?

I think that's probably what's happening here.  I will check though.  We should think about how to indicate to the user that a genotype can't be deleted because one of it's allele is in use.  It's not a good user experience at the moment.

**Comment by manulera** [comment]
> This is because the genotype is used in a multi-gene genotype so I think this is OK?

The genotype was also in single allele phenotypes in this case, but I would agree otherwise

**Comment by kimrutherford** [comment]
Hi @manulera

There's a mouse-over message on the grey-out delete menu item that's supposed to explain the situation.  Do you think we should make this clearer?:

![screenshot-2023-05-02_16-39-crop](https://user-images.githubusercontent.com/90474/235581448-204dcfa5-04a0-4c25-b93e-a71f1a65ee6a.png)

(You'll have to imagine seeing my mouse pointer over the "Delete" - the screenshot didn't capture it)

**Comment by manulera** [comment]
Hi @kimrutherford. Yes, that tooltip is good. The problem in this case is that the authors created alleles named mamRNAdelta and SPNCRNA.1715.2delta, and I had not realised, so I did not understand why the count was zero, but it's just that the same deletion had a different name. I will fix that.
