### ISSUE TITLE
remove "required_for" as an option on modification annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2719]
https://github.com/pombase/curation/issues/3369

I removed the existing (there were not many), 
To curate this we create a PRO modified form as the entitiy to annotate the GO BP too.

I could not locate
SPAC17G8.12 sec3 MOD:00046 201 PMID:30726745
in the session, or the   HTP file PMID_30726745_modifications.tsv ?

**Comment by kimrutherford** [comment]
I've removed these two line from the configuration:
```
MOD:00000       is_a    required_for    GO:0003674      required for activity           0,1     user
MOD:00000       is_a    required_for    GO:0009987      required for process            0,1     user
```

The change should be visible by the morning.

> I could not locate
> SPAC17G8.12 sec3 MOD:00046 201 PMID:30726745

Is that this line?:
```
SPAC17G8.12  sec3    MOD:00046       ECO:0007464     S201    affected_by(Pombase:SPAC821.12) PMID:30726745   4896    2019-02-05
```
It's in: `external_data/modification_files/PMID_30726745_modifications.tsv`

**Comment by kimrutherford** [comment]
I think we can close this?
