### ISSUE TITLE
Promoter swap temporary solution

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2720]
Related to #2544

cc: @ValWood @kimrutherford

I curated a few alleles in which the promoter had been changed like this:

![Screenshot 2023-04-04 at 11 11 39](https://user-images.githubusercontent.com/22526102/229760919-09e4f411-fe46-4b8a-8b73-ee09f2f008ee.png)

I think it's consistent, because we show that the product is wild type and underexpressed, and the reason for it is implicit in the name. I think Canto is still loading the older versions, because I see the old names in the logs:

```bash
# Query
logs $grep "rad21" *|grep cdc25 --color

# What I get
log.2023-03-31-21-42-24.alleles_of_type_other:prad21-cdc25,SPAC24H6.05:allele-14,rad21 promoter control,{915dd27f11d0b65d}
log.2023-03-31-21-42-24.chado_checks.AlleleNotStartingWithGeneName:prad21-cdc25 cdc25   SPAC24H6.05     915dd27f11d0b65d
```

However, not sure what will happen with an allele that is marked as "wild-type" but has a different name than gene_name+.

**Comment by manulera** [comment]
Also neither the old nor new phenotype annotations show up in the website.

https://www.pombase.org/reference/PMID:25492408

**Comment by kimrutherford** [comment]
> I think Canto is still loading the older versions, because I see the old names in the logs:

That looks like an old log directory.  That old allele name isn't in the latest log directory:
https://curation.pombase.org/dumps/builds/pombase-build-2023-04-04/logs/

> However, not sure what will happen with an allele that is marked as "wild-type" but has a different name than gene_name+.

Currently the allele name for wild type alleles is always set to `gene_name+` and the annotated allele name is ignored.  From looking at the Git log for that code, I think we used to keep the allele name from Canto for wild type alleles but I broke things when fixing a bug almost 5 years ago.   I'll fix the code.

> Also neither the old nor new phenotype annotations show up in the website.

I think it could be this one:

![image](https://user-images.githubusercontent.com/90474/229768776-48838339-199e-4b1c-b939-bd403e303c8f.png)

**Comment by ValWood** [comment]
I think I have been doing something similar with some alleles labelled as "other" over time. Because it worked in canto I assumed it was OK but did not check the website, so there may be quite a few WT alleles with slightly different names that are not showing up.

This means that there may be some promoter alleles in the WT allele set that do not follow the new standard.

We should discuss this  related ticket tomorrow
https://github.com/pombase/canto/issues/2544

**Comment by manulera** [comment]
> That looks like an old log directory. That old allele name isn't in the latest log directory:

I was using this folder https://www.pombase.org/data/releases/latest/logs/

I will check on the other then!

**Comment by kimrutherford** [comment]
> I was using this folder https://www.pombase.org/data/releases/latest/logs/

That's the correct one to use.

The older log directories are available here: https://curation.pombase.org/dumps/builds/

**Comment by manulera** [comment]
Ok, now I see it, maybe the changes hadn't been picked up yet:

```
grep "rad21" *|grep cdc25 --color
log.2023-03-31-21-42-24.alleles_of_type_other:prad21-cdc25,SPAC24H6.05:allele-14,rad21 promoter control,{915dd27f11d0b65d}
log.2023-03-31-21-42-24.chado_checks.AlleleNotStartingWithGeneName:prad21-cdc25 cdc25   SPAC24H6.05     915dd27f11d0b65d
```

In any case, is this not being displayed because of the `AlleleNotStartingWithGeneName` or `alleles_of_type_other`? Or maybe something in the chado loading code that does not allow wild-type alleles to go in if they don't have the gene+ allele name?

**Comment by kimrutherford** [comment]
> maybe something in the chado loading code that does not allow wild-type alleles to go in if they don't have the gene+ allele name?

Yep.  Currently the loading code always sets the allele name of wild type alleles to `gene_name+` but I've just committed a fix for that problem.

**Comment by kimrutherford** [comment]
> Yep. Currently the loading code always sets the allele name of wild type alleles to gene_name+ but I've just committed a fix for that problem.

Hi @manulera 

When you're back at work, could you check that the main site has the correct details for that genotype and annotation now?:

 - https://www.pombase.org/genotype/P.rad21-cdc25%2B-expression-knockdown
 - https://www.pombase.org/reference/PMID:25492408

**Comment by manulera** [comment]
Hi @Kimrutherford. This looks good to me. We can close if so.
