### ISSUE TITLE
Export alleles from canto to tsv file

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2726]
Hi @kimrutherford. What we discussed this morning, to export all Canto alleles to a tsv file. The fields should be the same ones as [alleles.tsv](https://github.com/pombase/allele_qc/blob/master/data/alleles.tsv).

* `systematic_id`
* `allele_description`
* `gene_name`
* `allele_name`
* `allele_synonym`
* `allele_type`
* `reference`: PMIDs, comma-separated

Plus two extra ones, that could be:

* `nb_annotations`, better than true / false, since it can be used to prioritise correcting those with more annotations.
* `curation_sessions`: comma-separated

The fields can be written like that, or in capitals with spaces, like in the PHAF file.

**Comment by kimrutherford** [comment]
Hi @manulera

I've made a first attempt at this.  Here's an example of the output:
https://curation.pombase.org/kmr44/canto_allele_table_example.tsv

Val, this is a table of all alleles from Canto, including those with no annotation.

**Comment by manulera** [comment]
Reminder for Manu: not to drop the phaf file entirely, as it contains the HTP alleles.

**Comment by kimrutherford** [comment]
Job for Kim: write this file each night.

**Comment by kimrutherford** [comment]
> Job for Kim: write this file each night.

Done: https://curation.pombase.org/data/pombe-allele-table.tsv

We should decide if we should document and announce this file or if it should be only for internal use.

**Comment by manulera** [comment]
Yep
