### ISSUE TITLE
error updating physical interactions comment

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2729]
yesterday I wanted to edit  a comment for physical interactions but that isn't possible.

curs/4d56e9e82da23d80

I get this error when I try to save:
<img width="475" alt="Screenshot 2023-05-04 at 14 06 48" src="https://user-images.githubusercontent.com/7359272/236213691-2fa363c2-5324-4279-bca1-3c8a73183144.png">

**Comment by kimrutherford** [comment]
That's fixed now.  It must have been broken for ages.
