### ISSUE TITLE
Don't run Canto as root when using Docker

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2741]
FlyBase have asked if there is a way to avoid running Canto as root in the Docker container.

@jseager7 Did you ask about something like this a while ago?

**Comment by jseager7** [comment]
Yep, I use rootless mode on my local machine. All that's needed is to set the `--publish` argument when running the `canto_start_docker` script to the required port mapping. For example:

```
./canto/script/canto_start_docker --publish 5000:5000
```
I think these are the instructions I followed to set up rootless mode:

https://docs.docker.com/engine/security/rootless/

Previous discussion on this is at issue #2673.

**Comment by kimrutherford** [comment]
Thanks James.  I'll give that a try.

**Comment by kimrutherford** [comment]
> Yep, I use rootless mode on my local machine.

Do you use rootless mode on your server?

**Comment by jseager7** [comment]
> Do you use rootless mode on your server?

No, we use Podman on our server because our IT department chose that instead of Docker rootless mode. I can't remember having any problems with it so far, but I wasn't involved with setting up things like Apache so I'm not sure if there were any problems there.

**Comment by kimrutherford** [comment]
> we use Podman on our server

I've tried Podman on my desktop and it seems to work very well as a Docker replacement.  Thanks for mentioning it which prompted my to have a look.

To help FlyBase, I've added a `--use-podman` flag to `script/canto_docker` and `script/canto_start_docker`.  I hope that doesn't cause problems in your setup.  The default it still Docker.

**Comment by jseager7** [comment]
> I hope that doesn't cause problems in your setup. The default it still Docker.

Thanks for the heads up. I'll test that today.

**Comment by jseager7** [comment]
I've tested the changes now and I don't see any problems running Canto using my local setup.

**Comment by jseager7** [comment]
Just a note on the commit for this issue: if the machine running Canto has the `podman-docker` package installed, then all commands to `docker` should be automatically aliased to `podman`, which presumably makes the code below unnecessary:
```sh
if [ $1 = '--use-podman' ]
then
    shift
    DOCKER_COMMAND="podman"
fi

**Comment by kimrutherford** [comment]
> I've tested the changes now and I don't see any problems running Canto using my local setup.

Thanks for testing.

> Just a note on the commit for this issue: if the machine running Canto has the podman-docker package installed, then all commands to docker should be automatically aliased to podman

Thanks, I didn't notice that package.  I've been testing on my desktop where I'm still using Docker for builder containers, so I need both.
