### ISSUE TITLE
Diploid constuctor is behaving strangely

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2743]
In PHI-base/curation#169, one of our curators noticed some strange behaviour with the diploid constructor dialog.

Firstly, it's possible to select two options at once:

![image](https://github.com/pombase/canto/assets/37659591/066b4160-3b29-4812-8032-bd01ae7b7027)

Looking at the HTML markup (diploid_constructor.html), I think this is because the `name` attributes of the radio button inputs don't match the `name` attribute of the enclosing `form` element, meaning the radio buttons are not treated as part of the same form and can be selected independently.

```html
<form name="cursDiploidConstructor" class="curs-diploid-constructor-dialog modal-content">
         <!-- lines hidden -->
        <input type="radio" value="homozygous" id="homozygous" name="homozygous" ng-model="diploidType"/>
        <!-- lines hidden -->
        <input type="radio" value="wild type" id="wild-type" name="wild-type" ng-model="diploidType"/>
        <!-- lines hidden -->
</form>
```

Secondly, it doesn't seem possible to create a mutant / wild-type diploid locus because the `diploidType` in the model never changes from 'homozygous' to 'wild type'.

Fortunately, there is a workaround where the wild-type side of the diploid can be selected first, followed by the mutant side of the diploid. Quoting from the original issue:

> in order to create a heterozygous genotype "altered allele + wild type", the user must first create a wild type allele of the gene in question, and then start the create diploid locus process by selecting this allele [...] Here, by selecting the second option, the curator can select which altered allele he would like to include in this heterozygous, diploid genotype.

@kimrutherford I've looked at the code but I can't really figure out what's going wrong. I'm tagging this issue as PHI-Canto because I'm assuming these problems are somehow related to pathogen-host mode (otherwise I presume that PomBase would've noted the problem by now).

**Comment by ValWood** [comment]
We probably wouldn't spot this because I think all small-scale the curated diploids are homozygous

**Comment by kimrutherford** [comment]
Val, does the order we display the alleles of a diploid matter biologically?

**Comment by ValWood** [comment]
We'll assume not. I never noticed any ordering.

**Comment by jseager7** [comment]
Thanks. I'll close this as completed.
