### ISSUE TITLE
Allow the option to supply "modified residue"  for this GO term and its children

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2744]
GO:0008173  RNA methyltransferase activity

**Comment by ValWood** [comment]
High priority of quick, medium if tricky, but I think we do it on other GO terms (or maybe it is only phenotypes).
It wouldn't be part of the GO export.

**Comment by kimrutherford** [comment]
I've added that config.  It will be ready to use in Canto tomorrow morning.

**Comment by kimrutherford** [comment]
I got the configuration wrong on my first go but it's fixed now.

**Comment by ValWood** [comment]
that works, thanks
