### ISSUE TITLE
JSON export should not include email address in curator_orcid

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2748]
The `curator_orcid` property (in the `curator` object of each `annotation` object) in the JSON export will include an email address if the curator's ORCID ID is set to an email address in the database.

I think this can happen when adding a user via the command line (`canto_add.pl --person`) based on the following documentation:
```
  --person  - add a person to the database, the user_type can be "user"
              or "admin" with the default being "user"
              The ORCID can't be blank.  If the user has no ORCID, use a
              unique string such as the email address.
```
I think it would be better to filter out these cases and only export valid ORCID IDs.

**Comment by ValWood** [comment]
This seems like a GDPR issue

**Comment by kimrutherford** [comment]
I've fixed the export code to filter anything that doesn't look like an ORCID.
