### ISSUE TITLE
Add a link to the privacy policy

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2749]
[James added a configuration option](https://github.com/pombase/canto/pull/2745) to make this simple:

```
privacy_policy_url: "https://pombase.org/about/privacy-policy"
```

**Comment by kimrutherford** [comment]
I've added the config.

Val, it looks like this.  Let me know if we need to change the wording.

![image](https://github.com/pombase/canto/assets/90474/23a91445-eca3-4c31-b240-3c5551245784)

**Comment by ValWood** [comment]
Looks good!
