### ISSUE TITLE
Allow the option to supply "modified residue" for this GO term and its children

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2750]
as for
https://github.com/pombase/canto/issues/2744
could we add residue=. to MF term in this branch?
https://www.pombase.org/term/GO:0030555

It was actually a guide I needed it for here:
https://www.pombase.org/reference/PMID:37403782
not a methytransferase

**Comment by kimrutherford** [comment]
Hi Val.  I've added that configuration and I've updated Canto so you should be able to use it now.  You might need to reload to see it.
