### ISSUE TITLE
Missing message when background cannot be removed

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2752]
cc @kimrutherford

In the case below, two klp9delta alleles existed, one with a background and one without. I had not realised that there was the second one without the background, so I wanted to edit the first one and remove the background. It seemed to not be working, since nothing happenned, but then I realised that it was not being edited because the edited allele already existed. I think probably a pop-up error message is missing in this case

https://github.com/pombase/canto/assets/22526102/0d2fddf5-823d-4432-ad03-f038e67f9860

**Comment by kimrutherford** [comment]
I've fixed Canto to show a warning:

![image](https://github.com/pombase/canto/assets/90474/aa866153-5633-47c9-b328-c876c1636db3)

Let me know if the wording needs improvement.
