### ISSUE TITLE
Can we automatically name all alleles?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2755]
And add the gene name as a prefix if the name is the same as the description?

**Comment by manulera** [comment]
And generate a name with gene_name + description for alleles that have empty names following the same pattern as when you load into Chado (e.g. allele of gene `erh1` with description becomes `erh1-L72S`, and `sap1` `137-254` becomes `sap1delta137-254`). I went through all canto alleles with empty names and fixed the two that were a bit more complicated than that.

**Comment by kimrutherford** [comment]
We'll be doing the same as in these issues, but instead of fixing allele names when loading into Chado we will apply the fixes directly to the Canto database:
  - pombase/pombase-chado#881
  - pombase/pombase-chado#868

**Comment by kimrutherford** [comment]
I've written most of the script to do this.  I have few questions.

If the description is "C(-165)A,C(-164)A,G(-154)A" should the name be "mfm1-C(-165)A,C(-164)A,G(-154)A"?

There are a bunch of descriptions like "CTD-T4A" and "CTD-P6A(r2-r29-2)".  Should those have the gene name added to form the allele name like the other cases?

**Comment by manulera** [comment]
> If the description is "C(-165)A,C(-164)A,G(-154)A" should the name be "mfm1-C(-165)A,C(-164)A,G(-154)A"?

> Should those have the gene name added to form the allele name like the other cases?

Yes to both!

**Comment by kimrutherford** [comment]
This is done now.  The script fixed 657 allele names in Canto.

**Comment by kimrutherford** [comment]
That has helped a lot.  There are now only two alleles in Canto without names and both have no annotations:

```
396866ab84f69995 cnd2(SPCC306.03c)     description: T117I
865ebc50ec806a07 sgf11(SPAC57A10.14)   description: Q64->stop
```

Good result!

**Comment by kimrutherford** [comment]
> Alrighttt, should we close?

Yep!

I've made a curation issue about the two alleles without names: pombase/curation#3541
