### ISSUE TITLE
Should we disallow alleles without a name?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2757]
These allele types are not configure to require a name.  Should we change that?

 - amino_acid_insertion
 - amino_acid_mutation
 - amino_acid_insertion_and_mutation
 - amino_acid_insertion_and_deletion
 - amino_acid_deletion_and_mutation
 - partial_amino_acid_deletion
 - nucleotide_insertion
 - nucleotide_mutation
 - partial_nucleotide_deletion
 - nucleotide_deletion_and_mutation
 - nucleotide_insertion_and_mutation
 - ~fusion_or_chimera~ - EDIT: already required
 - other

**Comment by ValWood** [comment]
If the user supplies only a description then can we use the description to provide the standard allele name?
can discuss tomorrow,

**Comment by kimrutherford** [comment]
> If the user supplies only a description then can we use the description to provide the standard allele name?

Is that the same as this?:
  -  pombase/canto#1284

**Comment by ValWood** [comment]
Not sure, we can discuss both and figure out.

**Comment by ValWood** [comment]
Dicision, all alleles should be named in Canto.
Question:
Do we prepopulate the name for known alleles if description is added first?
OR
Do we allow user to add their name and then tell them this allele has another name and should it be a synonym?

We need to allow non-admin users to add synonyms.

Add a warning to say that the allele already exists with a different name.

**Comment by kimrutherford** [comment]
All allele types require a name now.
