### ISSUE TITLE
Prevent changes to alleles that are existing alleles in Chado

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2758]
In a Zoom call recently Manu suggested that we should prevent changes in Canto if the allele is in Chado (same name, description, type, etc.).  I've started experimenting with this on a branch.

This change will make it easier to maintain stable allele identifiers.

See:

 - pombase/pombase-chado#986

**Comment by kimrutherford** [comment]
I've fixed a bunch of bugs and I think this is done now.

I'll demonstrate the changes next time we chat.  The interface hasn't changed too much but there has been quite a bit of moving things around under the hood. 

The systematic allele IDs from Chado are now exported to the JSON file for loading into Chado.  I've made an issue about the Chado changes that are needed because of that:
  - pombase/pombase-chado#1107

The Canto changes are waiting on a Git branch because this change will need be coordinated with changes to the nightly load and the changes to the loading code.

**Comment by kimrutherford** [comment]
> The Canto changes are waiting on a Git branch because this change will need be coordinated with changes to the nightly load and the changes to the loading code.

[issue-2758-disable-edits-for-existing-alleles](https://github.com/pombase/canto/tree/issue-2758-disable-edits-for-existing-alleles)

**Comment by kimrutherford** [comment]
I've done some more testing and I think this is mostly done.  I have some questions about the handling of deletions and wild type alleles.  It's easy to talk about it while I demo the problem on a call.

**Comment by ValWood** [comment]
This one isn't so urgent

**Comment by kimrutherford** [comment]
Bugs to fix:
  - if the user make a deletion allele check for existing
    - could be from clicking the "Deletion" button
    - or by select "deletion" as the allele type in the dropdown
  - same for wild type alleles

-------------------------------

Get rid of the new allele in this case.  Selecting either the existing or new allele gives the same result in the allele dialog: 

![image](https://github.com/pombase/canto/assets/90474/e774a01e-dc9b-43ea-8695-1d994bdb34e9)

**Comment by kimrutherford** [comment]
> - if the user makes a deletion allele, check for existing
>    - or by select "deletion" as the allele type in the dropdown

That's done too now.

**Comment by kimrutherford** [comment]
> Get rid of the new allele in this case. Selecting either the existing or new allele gives the same result in the allele dialog:

That's fixed now.

**Comment by kimrutherford** [comment]
All these changes are available on my desktop for testing: https://desktop.kmr.nz/test/curs/4666975359de04dd/genotype_manage#/

**Comment by ValWood** [comment]
When we chat on Friday you will need to remind me about which allee changes can be made in Canto in future.
Or is it like a temporary freeze until all of the IDs are established?

**Comment by kimrutherford** [comment]
> When we chat on Friday you will need to remind me about which allee changes can be made in Canto in future.
> Or is it like a temporary freeze until all of the IDs are established?

You'll be able to replace one allele with another in a genotype, but to rename an allele everywhere we'll need to implement this:
 - pombase/canto#2669

**Comment by kimrutherford** [comment]
I wonder if we should have a button to clear the name field and unlink the allele with the existing allele.  I worry that a new user could select an existing allele when they didn't mean to and then get stuck.  Also it's not obvious at the moment how to edit an allele that's part of a genotype.

Working-ish mock up here: https://desktop.kmr.nz/test/curs/4666975359de04dd/genotype_manage

![Untitled](https://github.com/pombase/canto/assets/90474/39fe2d5a-8c51-4189-b843-a8be2734d25b)

to get you back to:

![image](https://github.com/pombase/canto/assets/90474/8ba55b52-1d3e-4e45-ba91-67c37bb5aff2)

**Comment by kimrutherford** [comment]
Hi Val.

Did we discuss changing the text "This is an existing allele"?  I can't remember what we decided.

![image](https://github.com/pombase/website/assets/90474/4d2f027f-4a31-49ba-bc01-b420dce91617)

**Comment by ValWood** [comment]
Click OK to use this allele or "cancel" to create a new allele. 
Note: this allele can not be edited because it is already used in PomBase.

**Comment by kimrutherford** [comment]
> I wonder if we should have a button to clear the name field and unlink the allele with the existing allele. 

On the last call, we decided to instead have a `Clear` button that resets the form, possibly at bottom left on the same row as the `Ok` and `Cancel`.

**Comment by kimrutherford** [comment]
> On the last call, we decided to instead have a Clear button that resets the form, possibly at bottom left on the same row as the Ok and Cancel.

How's this?  Available here for testing: https://desktop.kmr.nz/test/curs/4666975359de04dd/genotype_manage#/edit/36

![image](https://github.com/pombase/canto/assets/90474/f7ddef8e-c289-4ee5-ba94-88d37ededad0)

**Comment by kimrutherford** [comment]
> Click "OK" to use this allele or "Cancel" to create a new allele.
> Note: this allele can not be edited because it is already used in PomBase.

We might need to re-word that a bit because the heading says `Editing ...` and expression level can be edited.

![image](https://github.com/pombase/canto/assets/90474/53914608-56e3-4da7-969d-211f2151c5fe)

**Comment by ValWood** [comment]
I tested but I could not see the button for a new allele I created ?

**Comment by kimrutherford** [comment]
The button is currently only visible for existing alleles from Chado.  We can change that if you think it would be useful.

**Comment by kimrutherford** [comment]
It works for me.  I just double checked.

From here: https://desktop.kmr.nz/test/curs/4666975359de04dd/genotype_manage
I clicked "Other genotype" for cdc2 and then used the name of an existing allele cdc2-DL41.

**Comment by kimrutherford** [comment]
I've just changed the button colour to blue to make it stand out.  It was grey which made it look deactivated.

![image](https://github.com/pombase/canto/assets/90474/29167a24-8160-45d7-bce7-c703455ebe7e)

**Comment by kimrutherford** [comment]
I've just changed the button colour to blue to make it stand out.  It was grey which made it look deactivated.

![image](https://github.com/pombase/canto/assets/90474/29167a24-8160-45d7-bce7-c703455ebe7e)

**Comment by ValWood** [comment]
I still don't see it?
<img width="1244" alt="Screenshot 2024-02-28 at 09 29 54" src="https://github.com/pombase/canto/assets/7359272/a0251a79-26a0-4f76-afea-339875581af8">

**Comment by kimrutherford** [comment]
The button currently doesn't show until you have selected the existing allele name.  You might need to shift-reload as well.

**Comment by ValWood** [comment]
I still can't see it, you will have to show me on Friday...

**Comment by kimrutherford** [comment]
As discussed, I've remove the "Clear" button.
