### ISSUE TITLE
bug  sending curation sessions out:

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2760]
<img width="900" alt="Screenshot 2023-08-29 at 13 50 07" src="https://github.com/pombase/canto/assets/7359272/d15d1bf0-04c8-4224-907a-c1d786360a1a">

**Comment by kimrutherford** [comment]
Which session was that?

**Comment by ValWood** [comment]
https://curation.pombase.org/pombe/view/object/pub/14150?model=track

**Comment by ValWood** [comment]
It can wait, I don't need to send them out today.

**Comment by kimrutherford** [comment]
I think I've fixed that.  It's an old bug so I'm surprised we haven't seen it before.

Please re-open if there are still problems.

**Comment by ValWood** [comment]
great, all good
