### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2764]
I'm not sure where this is configured but

GTPAse inhibitor activity
has the relation "activates" configured, rather than "inhibits"

<img width="839" alt="Screenshot 2023-08-30 at 18 57 22" src="https://github.com/pombase/canto/assets/7359272/05a6445f-727f-4c0a-b0b3-6a6288af0233">

**Comment by kimrutherford** [comment]
> I'm not sure where this is configured but

It's configured here: https://github.com/pombase/pombase-config/blob/master/canto/annotation_ex_config/GO_MF_A_E_config

"activates" is configured for has_input for children of GO:0030234, GO:0001671 and GO:0000772:

```
GO:0030234      is_a    has_input       ProteinID       activates               0,1     user  
GO:0001671      is_a    has_input       ProteinID       activates               0,1     user
GO:0000772      is_a    has_input       ProteinID       activates               0,1     user
```

I guess GO:0030234 line is the problem?  It looks like the web site is configured the same way:
  - https://www.pombase.org/term/GO:0030234
  - https://www.pombase.org/term/GO:0005096

Are there other children of GO:0030234 that shouldn't show "activates" for has_input?

**Comment by ValWood** [comment]
GO:0030234      is_a    has_input       ProteinID       ~activates~ regulates               0,1     user  


GO:0001671      is_a    has_input       ProteinID       activates               0,1     user
This line should not be required when https://github.com/geneontology/go-ontology/issues/26006 is fixed

GO:0000772      is_a    has_input       ProteinID       activates               0,1     user

GO:0004857   enzyme inhibitor activity (and all descendants) should be inhibits

**Comment by kimrutherford** [comment]
It's now configured to use regulates for GO:0030234 and descendants, except for GO:0004857 and GO:0008047 and their descendants.

> GO:0004857 enzyme inhibitor activity (and all descendants) should be inhibits
> GO:0008047 enzyme activator activity (and all descendants) should be activates

And I've added configuration for each of those.

It should be updated by the morning unless I got the syntax wrong.

**Comment by ValWood** [comment]
That is fixed, thanks
