### ISSUE TITLE
making ISS in Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2765]
I noticed yesterday that this is available

<img width="520" alt="Screenshot 2023-08-30 at 17 32 25" src="https://github.com/pombase/canto/assets/7359272/f8ec18be-d7e7-4542-817a-168cf5bd7948">

btu we can't use it becasue (as far as I am aware) we can load non pombe iDs. Should this be disabled until we can  use non pombe IDs in the 'with' field?

**Comment by kimrutherford** [comment]
It's only visible if you're logged in as admin.  It was added as part of this unfinished issue: pombase/canto#1852
I haven't implemented this bit yet:
> Allowing free text for "with" is going to take longer than adding admin-only evidence codes.

**Comment by ValWood** [comment]
OK we can ignore if it is only admin. No hurry, I can make ISS in the special spreadsheet.
