### ISSUE TITLE
Change ordering of MF extensions in Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2766]
can we change the order of the molcecular function extensions from

	•	transcript isoform ID
	•	has function during
	•	physical location
	•	involved in biological process
	•	anchors
	•	PR:nnnID for modified protein form
	•	qualifier

to
	•	anchors (gene product acted upon)
	•	involved in biological process
	•	physical location
	•	has function during
	•	transcript isoform ID
	•	PR:nnnID for modified protein form
	•	qualifier

This would be a more logical order.

@manu  
- do you think "location in cell" would be better than "physical location"?
- do you think we should add some text in parentheses after  the "has_input" relations (because this will be different each time, this might  help to 'normalize it a little)
- Note that transcript isoform and modified protein form are admin only

**Comment by kimrutherford** [comment]
There are a bunch of other possible extensions depending on the term.  Does it matter which order those are in?

The config file is here: https://github.com/pombase/pombase-config/blob/master/canto/annotation_ex_config/GO_MF_A_E_config

This is list of non-admin MF extension names:


|Extension display name                          |
|--------------------------------------------|
|activates                                   |
|acts on                                     |
|adenylates                                  |
|anchors                                     |
|binds \(RNA gene or type\)                  |
|binds chromatin region                      |
|binds ligand                                |
|binds region                                |
|carries                                     |
|chaperone for                               |
|chaperones \(protein or RNA\)               |
|cleaves                                     |
|deacetylates                                |
|dephosphorylates                            |
|deubiquitinates                             |
|exchange factor for                         |
|has function during                         |
|has ligand \(protein or chemical substance\)|
|has\_input                                  |
|inserts                                     |
|involved in biological process              |
|isomerizes                                  |
|methylates                                  |
|modified residue                            |
|modifies                                    |
|palmitoylates                               |
|phosphorylates                              |
|physical location                           |
|prenylates                                  |
|reads                                       |
|recruits                                    |
|regulates activity of transcription factor  |
|regulates transcription of                  |
|sequesters                                  |
|stabilizes                                  |
|transports                                  |
|ubiquitinates                               |
|uridylylates                                |

**Comment by ValWood** [comment]
i.e they are all flavours of has_input

Except  "modified residue"
Which MF terms is that available for?

**Comment by kimrutherford** [comment]
> Except "modified residue"
> Which MF terms is that available for?

It's in the config file:

```
GO:0008173	is_a	modified_residue	Text	modified residue		0,1	user
GO:0030555	is_a	modified_residue	Text	modified residue		0,1	user
```
https://github.com/pombase/pombase-config/blob/master/canto/annotation_ex_config/GO_MF_A_E_config

**Comment by kimrutherford** [comment]
> These are all for has_input on molcecular function (I believe) so they would all appear at the top as as

OK, I'll move all the has_input extension to the top of the [MF config file](https://github.com/pombase/pombase-config/blob/master/canto/annotation_ex_config/GO_MF_A_E_config).

> do you think "location in cell" would be better than "physical location"?

Wouldn't "cellular component" be the most consistent with the rest of PomBase?

There is a "Help text" column in the [extension config files](https://github.com/pombase/pombase-config/blob/master/canto/annotation_ex_config/GO_MF_A_E_config) that we've never shown.  Perhaps we should show it?  There's an old (closed) issue about it:

  - pombase/canto#2089

The "physical location" extension has a help text.  Here's how it could look in the dialog: 

![image](https://github.com/pombase/canto/assets/90474/ca04ec40-ad3f-4ed6-a743-1c9c42214c3e)

Or:

![image](https://github.com/pombase/canto/assets/90474/6bef560e-84af-44bf-a2c0-7d9d5a9dcba0)

**Comment by kimrutherford** [comment]
Here's the updated order:

![image](https://github.com/pombase/canto/assets/90474/43b4d1d0-f838-416f-92bc-72a74c746736)

**Comment by ValWood** [comment]
a) would these label be better?

	•	anchors
	•	in biological process
	•	at cellular location
	•	during phase (or stress)

Non admin do not see these:
	•	transcript isoform ID
	•	PR:nnnID for modified protein form
	•	qualifier

**Comment by ValWood** [comment]
I don't know why we used "physical location". I suspect it might be because we want them to specify the location and not any component (which could also be a complex)

**Comment by ValWood** [comment]
OK, modified residue we enabled for gene products which modify RNAs, becasue we could not get the specificity into the  GO  terms (the residues are not conserved between species)

https://www.pombase.org/term/GO:0030555

When that does appear (rarely), it could be first in the list.

**Comment by ValWood** [comment]
correction
When that does appear (rarely), it could be after the subtrate (has_input)

**Comment by ValWood** [comment]
@manulera  what do you think about these minor prompt suggestion changes? If you agree @kimrutherford  can implement in the next half hour so that it is correct in the video.

**Comment by manulera** [comment]
> •	anchors
> •	in biological process
> •	at cellular location
> •	during phase (or stress)

I would say `during cell cyle phase or stress`.

**Comment by manulera** [comment]
Now that I am leaving pombase, poor @manu is going to finally catch a break from PomBase tickets.

**Comment by ValWood** [comment]
Agreed , to both!

**Comment by kimrutherford** [comment]
I did that yesterday so the extension order should be updated now.

**Comment by kimrutherford** [comment]
> There is a "Help text" column in the extension config files that we've never shown.

That text is now shown:

![image](https://github.com/pombase/canto/assets/90474/7d13db5f-f815-448f-a706-cbd55743f719)

**Comment by ValWood** [comment]
nice!
