### ISSUE TITLE
Make GO "qualifier" admin only

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2767]
I think we should make the GO qualifier (covers negative annotations and 'contributes' to for compound functions).

In 10 years I don't think any of the community ever used it. A couple of people have requested to make negative annotations but they never found this themselves. It's annoying to see because they won't know what it is and they won't be any wiser if they click on it.

@manulera

**Comment by kimrutherford** [comment]
It was admin only for CC and BP already.  I've made it admin only for MF now too.  The change will be in the main Canto on Friday morning.
