### ISSUE TITLE
Out of place pop-up on gene specific BP quicklinks

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2768]
<img width="1165" alt="Screenshot 2023-08-31 at 15 15 15" src="https://github.com/pombase/canto/assets/7359272/5f636fea-3ffd-450a-8279-6d44f183375f">

This message should only apply to phenotype annotation?

**Comment by kimrutherford** [comment]
Sorry about that.  I think it must have been a copy and paste error.  Fixed now.
