### ISSUE TITLE
Cannot select Latrunculin A in protein modification increased in presence of

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2769]
I can select hydroxyurea, but not Latrunculin A:

<img width="606" alt="Screenshot 2023-08-31 at 16 30 31" src="https://github.com/pombase/canto/assets/22526102/859d0fd0-54f1-4211-aa16-7d628ab06314">

I guess the CHEBI term has to be added somewhere in the configuration, but I did not see where. This CHEBI term seems to be in FYPO, though.

**Comment by kimrutherford** [comment]
Hi @manulera 

I've added that term to our subset of the ChEBI ontology in pombe-embl/mini-ontologies/chebi.obo

It should be available by the morning.
