### ISSUE TITLE
Losing extensions when editing

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2772]
In this session I was trying to edit to add the new terms
<img width="1447" alt="Screenshot 2023-09-01 at 16 19 47" src="https://github.com/pombase/canto/assets/7359272/5bc95088-b051-49bc-8feb-588c6dc8dfc0">

However when I used edit, and added the new term name, the extension disappeared.
I don't think this usually happens?
In fact for one, it didn't but I could not work out what I did differently in this case.

I can demo if you like...

**Comment by kimrutherford** [comment]
From looking at the code, the only case I can see where the extension gets cleared is if you clear the term name field.  Could that be what happened?

**Comment by ValWood** [comment]
Probably, but I need to clear the field to  add the correct term?
MAybe I am misunderstanding...we can discuss Tuesday

**Comment by kimrutherford** [comment]
> Probably, but I need to clear the field to add the correct term?

I usually select the text and then start typing which is probably why I've never noticed this.

**Comment by ValWood** [comment]
I think I probably do sometimes, which is why it doesn't always lose the extension. I only noticed this because it would not let me proceed on the second one as it would make an identical annotation

**Comment by kimrutherford** [comment]
The extension and conditions are cleared when you clear the term because FlyBase requested it: https://github.com/pombase/canto/issues/1915#issuecomment-511279181

There's no discussion about why in that issue so it must have been discussed on a call.  I imagine that they didn't want to risk getting the wrong extension on a term.

**Comment by ValWood** [comment]
It's a bit of a problem when you have an old term as a place holder.
I would want to edit the extension explicitly I think.
If I am editing an annotation (rather than copy edit), I should be mindful that I edit all of the relevant parts, but I would not expect existing parts to disappear unless I actively removed them.
For example, if you got the term or allele incorrect it would be unlikely that you also got the extension incorrect (this would be a completely different annotation and I would be more likely to use 'copy edit' for this.

I will think about it. I can be mindful not to clear the term field and just edit it in the meantime.

**Comment by kimrutherford** [comment]
> I will think about it. I can be mindful not to clear the term field and just edit it in the meantime.

OK.

It's a one line change to fix this so that clearing the extension and conditions only happens for FlyCanto.  Although I think they happily using an older version of Canto so it wouldn't be a problem for them.

**Comment by ValWood** [comment]
duplicate of https://github.com/pombase/canto/issues/2788
