### ISSUE TITLE
canto prompts under "membrane adaptor activity"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2775]
I think I would like to change some of these to "connects"
<img width="622" alt="____change to  connects" src="https://github.com/pombase/canto/assets/7359272/23cd5094-021a-4503-8d16-42b24ee19ef0">

'recruits" does not work for all, and it doesn't encourage the capture of bothe 'adapted' molecules'

Not sure  until I see all...

**Comment by kimrutherford** [comment]
currently has_input for GO:0030674 is displayed as "recruits": https://www.pombase.org/term/GO:0030674
except for GO:0008093 and descendants where it's displayed as "anchors": https://www.pombase.org/term/GO:0008093
and GO:0140566 and descendants where it's displayed as "reads": https://www.pombase.org/term/GO:0140566

The Canto config is matches that.

**Comment by ValWood** [comment]
OK in that case, we can change "recruits" to "connects" (which is better for all non specified)
and add new specific ones where necessary

**Comment by kimrutherford** [comment]
> OK in that case, we can change "recruits" to "connects" (which is better for all non specified)

Should I go ahead and do that now or should we think about the more specific cases first?

**Comment by ValWood** [comment]
Go ahead. I will figure out the specifc ones over time.

**Comment by kimrutherford** [comment]
OK, I'll do that.

After the change only GO:0005484 ("SNAP receptor activity") and descendants will display "recruits" for has_input.

**Comment by kimrutherford** [comment]
> After the change only GO:0005484 ("SNAP receptor activity") and descendants will display "recruits" for has_input.

I was looking as the website config.  Just to check: is "recruits" how has_input() should be displayed in Canto for GO:0005484?

**Comment by ValWood** [comment]
Yes, but we don't know their substrates yet (they are all ISS), so there are non annotated at present.

**Comment by kimrutherford** [comment]
OK, done.  But the changes won't be visible in Canto or the website until tomorrow.
