### ISSUE TITLE
incomplete error message

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2777]
This is because of the presence of  spaces "and" added by the user before the checks were in place.
It's quite common for users to add spaces and "and" so if they do this it would be useful it the part of the string which didn't fit was reported in the error message

<img width="857" alt="Screenshot 2023-09-08 at 11 59 03" src="https://github.com/pombase/canto/assets/7359272/27b189d8-dcb4-44e8-a792-4de0d25c8855">

no hurry

**Comment by kimrutherford** [comment]
> it would be useful it the part of the string which didn't fit was reported in the error message

Maybe the message needs to be clearer, but it is reporting the part of the string that's a problem?  It's showing the "and" on the second line of the message.

It would be the same with any part of the description that isn't legal:
![image](https://github.com/pombase/canto/assets/90474/2bd7f313-a29f-49a0-ac1b-716c7c8df801)
![image](https://github.com/pombase/canto/assets/90474/fdd3d71e-5920-4f3a-9c79-0b7a69f45514)

**Comment by ValWood** [comment]
Of course, doh. I would put it in red and/or quotes  and/or maybe.

**Comment by kimrutherford** [comment]
> I would put it in red and/or quotes and/or maybe.

The messages now have quotes around them.
