### ISSUE TITLE
Fix admin login for japonicus Canto

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2779]
Currently shows:

![image](https://github.com/pombase/canto/assets/90474/8e57c3ba-0f93-4528-bc5f-ec5cdc80c713)

**Comment by kimrutherford** [comment]
Fixed!  I think.  I'm able to log in using ORCID now.  @ValWood  Let me know if you can.

**Comment by ValWood** [comment]
yes!

**Comment by ValWood** [comment]
Hi @snezhkaoliferenko if you had been unable to log in to Canto, this is now fixed (log in is via ORCID)
