### ISSUE TITLE
Add new triage classifiers

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2783]
I was looking at  the bin classified as "other " for various reasons.
I think I  need 2 new classifiers
i) bioinformatics (as a catch all for a lot of pubs)
ii) Educational resources (this will be a very small bin, but I can think of a few papers which could be filed here, and it could be  really useful to be able to grab these quickly

**Comment by kimrutherford** [comment]
> I think I need 2 new classifiers

Done!

**Comment by ValWood** [comment]
Thanks!
