### ISSUE TITLE
a small problem with the inability to change an annotation with a GI

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2786]
So, in this session:

<img width="1249" alt="Screenshot 2023-10-09 at 10 07 44" src="https://github.com/pombase/canto/assets/7359272/d58168f5-c66e-41bc-9eb5-09ad79a5403d">

The author did all the annotation and requested the correct more specific term.
I can't edit this to make it more specific.
I would need to delete, and remake the annotation, and the interaction, which 
a) takes time, and b) loses the original attribution.

You should be able to edit an annotation to make it more specific , perhaps?

**Comment by ValWood** [comment]
Actually I could edit it and keep the attribution. It's a bit of a pain, but not a blocker.

Lets keep this open though for now.

**Comment by kimrutherford** [comment]
Is this the same problem as:
  - #2815 

If so should we close this issue?

**Comment by kimrutherford** [comment]
> Is this the same problem as:

Please ignore that.  Now I've read again I realise this about the double mutant.

We could allow editing but show a warning about why the user should be careful?:

![image](https://github.com/pombase/canto/assets/90474/7bc9c691-f0e6-4fc2-8a77-48fc2167a6ce)

**Comment by ValWood** [comment]
MAke this an admin only option.

**Comment by kimrutherford** [comment]
I've changed things so that for admin users there is a warning but you can edit the double mutant phenotype that is part of an interaction. 

I'll close this because I think it's all working but please re-open if there are problems.
