### ISSUE TITLE
Losing conditions and extensions when editing annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2788]
In this situation it's a little annoying. that If I use a new FYPO Id directly to update, like here:
<img width="1136" alt="report Canto using editing losing extensions" src="https://github.com/pombase/canto/assets/7359272/51ad3f41-8160-4470-b134-230bc98018bb">

I lose any metadata.
(I can edit by navigating to the term, but since we are often not even in the correct branch it takes more time)

**Comment by kimrutherford** [comment]
Is this the same problem as #2772?

**Comment by ValWood** [comment]
Yes I thought I had submitted this one.
I'm trying to remember not to edit  by clearing but it's difficult.
I think in this situation when I am editing I would expect any metadata to remain (I can always remove if inappropriate)

I have probably lost quite a lot of metadata because I sometimes only realise when the lack of an extension causes a duplicate annotation and I get a warning.

**Comment by kimrutherford** [comment]
Shall I change the code to clear the extension/condition only for FlyCanto?

**Comment by ValWood** [comment]
Let's wait for a while. Now I know I'll figure out what is the best option over the next few sessions.

**Comment by ValWood** [comment]
From the old ticket

It's a bit of a problem when you have an old term as a place holder.
I would want to edit the extension explicitly I think.
If I am editing an annotation (rather than copy edit), I should be mindful that I edit all of the relevant parts, but I would not expect existing parts to disappear unless I actively removed them.
For example, if you got the term or allele incorrect it would be unlikely that you also got the extension incorrect (this would be a completely different annotation and I would be more likely to use 'copy edit' for this.

I will think about it. I can be mindful not to clear the term field and just edit it in the meantime.

**Comment by ValWood** [comment]
I'm still undecided...

**Comment by ValWood** [comment]
This is related, but when annotations are duplicated https://github.com/pombase/canto/issues/1963

**Comment by ValWood** [comment]
I do find this a big problem. I think it unexpected that when you add a term the extensions disappear.  also usually if we edit a term, the extensions would nearly always be correct. I think if you  need to edit extensions you should do this explicitly.

For us the main use case is to add a new term, and I bet we have lost a lot of extension by not noticing that they got wiped. Also you need to remember the extensions and add them back.

**Comment by kimrutherford** [comment]
It's a one line (-ish) fix.  Should I go ahead?

**Comment by ValWood** [comment]
I think so. I know when you edit the term you do retain the extensions, 
but often we  need to use a term that is unrelated to the new term as a placeholder. In these cases the normal workflow is to completely remove the existing term, and this wipes everything.

**Comment by kimrutherford** [comment]
Action: change to keep the extension (except for FlyBase)

**Comment by kimrutherford** [comment]
> Action: change to keep the extension (except for FlyBase)

I've changed the code so that the extension and condition don't get cleared when the term name is cleared, except when in FlyBase mode.

The change is in the main Canto now.  Let me know if it's doing what you expect.
