### ISSUE TITLE
existing allele not recognized

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2793]
When  I tried to add the following allele:
<img width="746" alt="Screenshot 2023-11-26 at 19 27 02" src="https://github.com/pombase/canto/assets/7359272/1ad2c0dd-19d1-4546-8e75-a8b364fd7498">

to PMID: 9092661
I cpud not locate the existing allele

**Comment by kimrutherford** [comment]
It's working for me.  Maybe a temporary network glitch?

![image](https://github.com/pombase/canto/assets/90474/d4cf7eef-4300-4e29-94c6-67f072d70d5a)

**Comment by ValWood** [comment]
OK, it may be because in that session, the curator had added   it as a disruption, and this might have over-ridden the actual allele in the database

**Comment by ValWood** [comment]
I'll reopen if it happens again
