### ISSUE TITLE
Suggestion for ontology drill down:

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2796]
Suggestion from Penelope:

For one of the terms I chose, there were almost 70 child term. I do not remember which exactly term was that but it had to do the the nutrient available in the medium and since I was adding that in the extension, I decided to go with the broader term for this exercise. 

I notice that when there are more specific entities for a given term, you click the link and you see a long list of Children terms. But the definition is only available if you click a specific term and you go to another window. It would be extremely useful, if the definition was appearing in a pop up window as the cursor moving to each term. This way, the curator can check the definitions quickly and chose the most suitable term much faster.

**Comment by kimrutherford** [comment]
Good plan.  Is this the sort of thing that you mean?  (Sorry, the mouse pointer is missing from the screenshot)

Does it need the term ID?

![image](https://github.com/pombase/canto/assets/90474/a0b5aa88-dc36-4663-93e7-d4289355e324)

**Comment by kimrutherford** [comment]
That's done and released now.
