### ISSUE TITLE
copy edit not working for physical interactions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2799]
the existing selection does not show and this error instead:

<img width="1680" alt="Screenshot 2024-01-12 at 10 52 20" src="https://github.com/pombase/canto/assets/7359272/bb8bb82a-f881-4d67-8e5a-8b5521be7f3d">

**Comment by kimrutherford** [comment]
That's fixed now.

I wasn't careful enough when implementing pombase/canto#2621
