### ISSUE TITLE
user was able to add incorrect format AA substitution description

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2801]
<img width="636" alt="Screenshot 2024-01-26 at 11 17 41" src="https://github.com/pombase/canto/assets/7359272/16f73faf-e65d-4870-9ecc-78d2dd508718">

**Comment by kimrutherford** [comment]
It's only active for admin users at the moment.  I thought we were still testing:
  - #2688.

**Comment by ValWood** [comment]
I had lost track of this one! I think it is working pretty well. I worry that people might get stuck, but they can always contact us in that case.....

**Comment by kimrutherford** [comment]
I've enabled the allele QC checker for all users.
