### ISSUE TITLE
bug modification residue

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2802]
I tested with "phosphorylated residue"
cid12 S26 (was told "no such residue at this position), so maybe I had not used this yet!

**Comment by kimrutherford** [comment]
Could you double check that?  I just tried and it was OK:

![image](https://github.com/pombase/canto/assets/90474/b9ef5b88-89dd-494e-9cb7-c765f96c9f4c)

**Comment by ValWood** [comment]
Now, I cannot make the residue accept at all?

I press OK and it stays like this:
<img width="1129" alt="Screenshot 2024-01-31 at 11 29 17" src="https://github.com/pombase/canto/assets/7359272/5756451c-fbd5-4b45-85c1-22e7368cf159">

**Comment by kimrutherford** [comment]
That's not good!

We'll need to debug that on a call.

**Comment by kimrutherford** [comment]
I haven't been able to reproduce the problem.  It's only enabled for admin users at the moment.

**Comment by ValWood** [comment]
I tried again, it happens when there is an existing annotation (usually you see a message that the annotation already  exists .

**Comment by kimrutherford** [comment]
Sorry I still can't reproduce the problem.  I've put it on my list for our next call.

**Comment by kimrutherford** [comment]
Note to self: the bug is in the long workflow.

**Comment by kimrutherford** [comment]
> Note to self: the bug is in the long workflow.

We've talked about removing the long workflow so I thought about holding off on fixing this bug.  But it turned out to be a quick to fix.  It should be working now in the main Canto.

Could you give it a test when you get a chance?

**Comment by ValWood** [comment]
It works too well ;) I could create 2 annotations:

<img width="764" alt="Screenshot 2024-02-29 at 07 54 11" src="https://github.com/pombase/canto/assets/7359272/38b0fdeb-80ea-4e3f-87b5-c7c95e8aa40d">

**Comment by kimrutherford** [comment]
Thanks for testing.

**Comment by ValWood** [comment]
SOrry my comment was too cryptic. I was allowed to create 2 identical annotations. The error should be that the annotation already exists ;)

**Comment by kimrutherford** [comment]
OK, I've made a separate issue about that: #2806
