### ISSUE TITLE
can bypass modification residue checks with duplicate and edit

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2803]
This isn't super urgent, but I noticed that I could copy and edit a modification, and the residues from the precious gene would be accepted, even if no residue at that position:

<img width="805" alt="ticket canto residue check bypass" src="https://github.com/pombase/canto/assets/7359272/d21f58c7-f0ac-44c7-a866-068740c72301">

**Comment by kimrutherford** [comment]
That's unfortunate!  The simplest fix would be to remove the residue extension if you change the gene in the edit dialog.  We could put a message box up explaining things.  Would that be OK?

**Comment by ValWood** [comment]
Yes I think that is safest.

**Comment by kimrutherford** [comment]
> The simplest fix would be to remove the residue extension if you change the gene in the edit dialog. We could put a message box up explaining things.

I've implement this now.  The change will be in the main Canto on Monday morning.  I'll close the issue then.

![image](https://github.com/pombase/canto/assets/90474/fc66cfd0-3e50-482d-801f-4567769d4850)
