### ISSUE TITLE
Spt5 CTD  allele 

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2804]
I was not allowed to create the correct Spt5 CTD  allele here:

<img width="1220" alt="Screenshot 2024-02-26 at 12 08 31" src="https://github.com/pombase/canto/assets/7359272/729331a6-1529-4247-a621-82bf2632f526">

Althought I worked around it. Will explain ion person.

**Comment by kimrutherford** [comment]
Won't fix for now.  Maybe later.
