### ISSUE TITLE
CTD_S5 etc modifications

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2807]
I could not add
CTD_S2
CTD_S5
CTD_S7
for rpb1 modifications in PMID:22508988

**Comment by kimrutherford** [comment]
Hi @manulera 

Is this the correct fix for adding support for these abbreviations?:
  - pombase/allele_qc#114

**Comment by kimrutherford** [comment]
Action for Kim: email Manu

**Comment by kimrutherford** [comment]
> Action for Kim: email Manu

No need as Manu noticed my PR: https://github.com/pombase/allele_qc/pull/114

**Comment by kimrutherford** [comment]
Hi @ValWood

Manu fixed this in pombase/allele_qc#115

Could you confirm the fix when you get a chance?

**Comment by ValWood** [comment]
hmm, i can't access Canto, can you?

**Comment by ValWood** [comment]
ignore. just slow (very)

**Comment by ValWood** [comment]
All done
