### ISSUE TITLE
Message to curators

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2808]
I always feel this is a bit hidden and often forget to look at it, even when it has vital information about a session (i.e. what was curated/not curated and why), or some other insights that might be useful to curators revisiting the session.

It would be useful if   there was a prominent message  like this

after approval
<img width="747" alt="Screenshot 2024-02-29 at 12 05 42" src="https://github.com/pombase/canto/assets/7359272/c0eece7a-939e-46f0-b44a-f8f2b1a61984">

saying this session has a curator note (it isn't only messages to pombase team from the community curator, it's e everything we note of interest)

**Comment by kimrutherford** [comment]
That's a good plan.  I'll do it today.

**Comment by kimrutherford** [comment]
> after approval

And during approval?

Should the message only be visible to admin users?

**Comment by kimrutherford** [comment]
Is this enough?:

![image](https://github.com/pombase/canto/assets/90474/34308dd2-f59a-4eee-a4aa-e49566030969)

Or we could show the message for admin users:

![image](https://github.com/pombase/canto/assets/90474/b180d5cc-f5d0-4cca-97a0-0a2bca2b55cf)

**Comment by ValWood** [comment]
The messages can get quite long, I think we only need to see that there is one.
Also admin only.

**Comment by kimrutherford** [comment]
OK, done.  And released in the main Canto.
