### ISSUE TITLE
cant add CDT modified residue in Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2809]
I wanted to make these more specific rpb1 modifications more specific 
so that they would group correctly in the protein viewer

<img width="949" alt="Screenshot 2024-03-05 at 16 37 28" src="https://github.com/pombase/canto/assets/7359272/1a1d36ef-ffde-45a6-966a-0d689c074c6f">

oddly, they weren't in the session (even as existing), so they must come from the reciprocal of the CTD kinase S2 and S5 kinase annotations which is super impressive!

anyway the  curation interface doesn't accept CTD_S2/5, I was able to work around using the "text" editor.
This isn't a priority, as it only applies to rpb1 and I can do them by hand, but in case it is easy...

**Comment by ValWood** [comment]
Although oddly these don't get instantiated as modifications:
<img width="1147" alt="Screenshot 2024-03-05 at 16 48 51" src="https://github.com/pombase/canto/assets/7359272/285cd0eb-de1c-4345-8cad-709efbab40ce">

**Comment by kimrutherford** [comment]
Looks good!

![image](https://github.com/pombase/canto/assets/90474/e1b339c8-fcec-4f44-843a-91c567ab51a9)

**Comment by ValWood** [comment]
even better!

**Comment by ValWood** [comment]
Do you know why there are still 2 phosphorylation sites per position? I looked on the web page, and I cant see which annotations are causing this?

**Comment by kimrutherford** [comment]
Aren't these the annotations?

![image](https://github.com/pombase/canto/assets/90474/ea892c9f-2985-4302-a8ba-dd39b7b716a6)

![image](https://github.com/pombase/canto/assets/90474/d22de180-9c24-488f-96e0-8c9bd98751f2)

**Comment by ValWood** [comment]
I thought I fixed the, and I see this:

<img width="1020" alt="Screenshot 2024-03-09 at 06 53 06" src="https://github.com/pombase/canto/assets/7359272/98b9c39b-fec8-4cec-b1ad-6c8c5553e5af">

**Comment by kimrutherford** [comment]
There are some phosphorylated residue annotations are only visible in the detailed view.

**Comment by ValWood** [comment]
OK! I thought I checked that. I will fix these on Monday

**Comment by ValWood** [comment]
In the  curation session they look like this:
<img width="699" alt="Screenshot 2024-03-09 at 07 27 18" src="https://github.com/pombase/canto/assets/7359272/f712b12a-8d1b-4037-b9d6-fd7689283c52">

will check on Monday

**Comment by kimrutherford** [comment]
Confusing!

I found them in `pombe-embl/supporting_files/legacy_modifications_from_contigs.tsv` after a bit of looking:

```
SPBC28F2.12     rpb1    MOD:00696       Inferred from Direct Assay      CTD_S2  added_by(PomBase:SPBC32H8.10)  PMID:19328067   4896    2009-07-12
SPBC28F2.12     rpb1    MOD:00696       Inferred from Direct Assay      CTD_S5  added_by(PomBase:SPBC19F8.07)  PMID:19328067   4896    2009-07-12
SPBC28F2.12     rpb1    MOD:00696       Inferred from Direct Assay      CTD_S2  added_by(PomBase:SPAC2F3.15)   PMID:19328067   4896    2009-07-12
SPBC28F2.12     rpb1    MOD:00696       Inferred from Direct Assay      CTD_S5  added_by(PomBase:SPBC32H8.10)  PMID:19328067   4896    2009-07-12
```

**Comment by ValWood** [comment]
fixed , with  some others
