### ISSUE TITLE
Phenotypes curated as "Wild type RNA level"

### ISSUE THREAD

**Issue by PCarme** [pombase/canto#2813]
It could be useful to add a message that shows when people select the "Wild-type RNA level" option, indicating that this option is not meant to report phenotypes affecting gene expression.

**Comment by kimrutherford** [comment]
Is something like this what we need?

![image](https://github.com/pombase/canto/assets/90474/2291ad7e-01af-4fa9-a678-6e89a0eae972)

**Comment by PCarme** [comment]
Yes, exactly !

**Comment by ValWood** [comment]
Maybe the message should say  
This datatype represents ONLY NORMAL protein and RNA levels. To report phenotypes affecting levels of gene expression, use the corresponding altered protein/RNA level phenotype terms.

so we guide them to the correct place to report mutant expression? or is this too long?

**Comment by kimrutherford** [comment]
I think that's good.  It's better to be clear with the users.

How's this?  (It's only a mock-up)

![image](https://github.com/pombase/canto/assets/90474/7de346a7-07d6-4738-abc7-a9cbacab2b3c)

**Comment by ValWood** [comment]
OK!
