### ISSUE TITLE
cant edit annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2815]
in this session to  add new terms?
pombe/curs/c56a652b8b068e66

**Comment by ValWood** [comment]
or this one
/pombe/curs/2c52a27e773dd541

but some, I could

cc @PCarme

**Comment by kimrutherford** [comment]
I just tried to add an annotation in c56a652b8b068e66 and that worked (I removed it afterwards).

Which term were you trying to use in the annotation and which ontology was it?

**Comment by ValWood** [comment]
i was trying to add 
increased centromeric inner repeat transcript level
as per term request
(the edit button is greyed out for me)

**Comment by kimrutherford** [comment]
There are some edit buttons greyed out for annotations that are part of genotype-genotype interactions:
  - https://github.com/pombase/canto/issues/2740#issuecomment-1978529267

Changing the genotype would change the interaction in those cases.

**Comment by PCarme** [comment]
I also had this problem with phenotypes of genotypes involved in multi-locus interactions yesterday. Even for phenotypes that are not involved in the interactions themselves. I had to remove the interactions to be able to edit them.

**Comment by ValWood** [comment]
>Changing the genotype would change the interaction in those cases.

in this case I'm trying to change the annotation not the genotype, and the specific annotation isn't used in an interaction.

**Comment by kimrutherford** [comment]
> the specific annotation isn't used in an interaction.

In the database it is using the whole annotation because the interactions with a phenotype need the term and extension as well as the genotype.  So the whole annotation referenced by the interaction:

![image](https://github.com/pombase/canto/assets/90474/9ac08d7c-f236-4ae6-81c6-2041cf52ca82)

We decided to prevent editing in this case so that changes to the genotype annotation wouldn't change the interaction:
  - https://github.com/pombase/canto/issues/2740#issuecomment-1978529267

Let's talk about this on Friday.

**Comment by ValWood** [comment]
Oh actually I see that actual phenotype is used.
I can work around by re-making the annotation. we'll talk about it on Friday.

**Comment by ValWood** [comment]
In the Stachan session I fixed one of the new terms by removing the interaction, adding the new term and adding the interaction back. We probably have to do it like this for the reasons discussed.

However, the remaining one, I can't fix because I can't locate the GI which references it?

I removed the interaction  from this one, which does reference it:
<img width="1427" alt="Screenshot 2024-03-21 at 11 14 42" src="https://github.com/pombase/canto/assets/7359272/4e6d6a95-492a-4e18-87b3-33da5a4961df">

but I still could not edit the annotation. I'm assuming it must be references in another GI, but none of the others are about this phenotype?

recording it here because otherwise I might forget that I still need to add the GI back to the annotation above once we locate the other cause!

Can look on Friday.

**Comment by ValWood** [comment]
this is what I removed
<img width="894" alt="Screenshot 2024-03-21 at 11 21 46" src="https://github.com/pombase/canto/assets/7359272/f51983d2-c72e-4eb9-ad88-82a66b277e3b">

**Comment by ValWood** [comment]
Clicking on edit will give a message

"changes to this annotation will change xx genetic interactions that it refers to"
(or something the same)

**Comment by kimrutherford** [comment]
This annotation should be editable:

![image](https://github.com/pombase/canto/assets/90474/1ef7bbcc-09e7-4948-84aa-8ea1b5d2931e)

**Comment by kimrutherford** [comment]
> Clicking on edit will give a message
>
> "changes to this annotation will change xx genetic interactions that it refers to"
> (or something the same)

How's this?:

![image](https://github.com/pombase/canto/assets/90474/6ed36ab8-fcef-4071-9b98-9fcee52e5f61)

**Comment by kimrutherford** [comment]
> Clicking on edit will give a message
>
> "changes to this annotation will change xx genetic interactions that it refers to"
> (or something the same)

I've deployed that change.  Let me know if there are any problems.

**Comment by ValWood** [comment]
Seems to be working for me.

**Comment by kimrutherford** [comment]
Thanks for testing.  I'll close this and we can open new issue if there are any bugs.
