### ISSUE TITLE
annotation I cannot edit

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2820]
I wanted to remove the top annotation here, because it is covered by the more specific annotation by Pascal at the bottom

<img width="1365" alt="Screenshot 2024-03-25 at 17 44 05" src="https://github.com/pombase/canto/assets/7359272/2fb2fd34-cadd-4a02-abd5-8a32b7b1ee1d">

But, I could not edit it, but I could not find this annotation used in any GI either

**Comment by kimrutherford** [comment]
Probably the same as this bug: https://github.com/pombase/canto/issues/2815#issuecomment-2014912649

**Comment by kimrutherford** [comment]
Could you add a link to the session?

**Comment by ValWood** [comment]
pombe/curs/682113d8f12b3fe4#

You are right. I was thinking that it only happened when the annotation was part of an interaction, but it's that allele isn't it?

**Comment by kimrutherford** [comment]
I think I've fixed this.  Please re-open if it's still a problem.

I'm working on this next:
  - https://github.com/pombase/canto/issues/2815#issuecomment-2014898687

**Comment by ValWood** [comment]
@PCarme FYI
