### ISSUE TITLE
Promoter swap with wild-type product level

### ISSUE THREAD

**Issue by PCarme** [pombase/canto#2821]
I have found an allele which is expressed at the same level as the wild-type (assayed in the paper) under control of an exogenous promoter.
![image](https://github.com/pombase/canto/assets/163283897/c76657a8-43ad-40ea-9af5-56d7eb40dfa4)
Do you think it might be worth making it possible to choose between the promoter options after selecting "Wild-type product level" in the allele description ?

**Comment by ValWood** [comment]
Yes, Kim this is similar to
https://github.com/pombase/canto/issues/2818
we might want to add a promoter even if the expression level  is WT

Is that an old annotation or one you are making ? If old it might be worth checking that they really did say it was WT level

**Comment by PCarme** [comment]
It is an old annotation, but I checked and it is backed by the data presented in the paper.

**Comment by kimrutherford** [comment]
Should I make that change in Canto or do we need to think about it first?

Will this be an admin-only option?

**Comment by ValWood** [comment]
Make it possible to always add promoter for all users

**Comment by kimrutherford** [comment]
> Make it possible to always add promoter for all users

OK, that's done now.  The promoter input box is shown when you select any expression level.
