### ISSUE TITLE
Merge promoter fields on allele edit dialog

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2823]
~~(I can't see an existing issue about this)~~ - found the comment:
  - https://github.com/pombase/website/issues/2161#issuecomment-2039393595

We decided to have just one free text field for adding a promoter.

Needs a schema change and then some Canto downtime to merge the fields in the database.

We'll remove the `exogenous_promoter` field in the database.

Once these changes are made:
  - pombase/pombase-chado#1163

**Comment by kimrutherford** [comment]
The code and schema changes are now done.  Let me know if you'd like different wording for the promoter field label.

I'll update the main Canto instance with this change over the weekend - probably 2-3am one morning.  It will need 15-30 minutes down time because of the schema change.

![image](https://github.com/pombase/canto/assets/90474/4a4f4001-5aac-4182-b215-c4e8fe9fdf1d)

**Comment by kimrutherford** [comment]
I forgot that we also need to remove any promoters from the list of genes in the session.  I'll fix that before deploying this change.

**Comment by kimrutherford** [comment]
Will you be putting the gene name or the systematic ID in the promoter field if it's a pombe gene?

![image](https://github.com/pombase/canto/assets/90474/ff4162a2-382f-4612-bcf6-a12c43ce9a38)

**Comment by kimrutherford** [comment]
> I forgot that we also need to remove any promoters from the list of genes in the session.

Note to self: only try to remove promoters that have no annotation.

**Comment by ValWood** [comment]
the gene name always so far. I don't think they will be mixed up, its quite a limited set. I guess there may be an occasion where an uncharacterized gene promoter s used, but not so far...

**Comment by kimrutherford** [comment]
I also need to update the japonicus Canto

**Comment by kimrutherford** [comment]
Canto has been updated now so there is only one promoter field.

I'll check the load on Sunday to make sure that all the promoter get put in the right place in Chado,

**Comment by kimrutherford** [comment]
> I also need to update the japonicus Canto

I've done that, mostly so the it's uses the same code and the pombe Canto.

> I'll check the load on Sunday to make sure that all the promoter get put in the right place in Chado,

All fine now.  Let's open new issues if there are changes needed.
