### ISSUE TITLE
Two partners required when annotating loss of actin filament binding 

### ISSUE THREAD

**Issue by PCarme** [pombase/canto#2825]
The interface indicates it is required to input 2 binding partners when annotating a phenotype as "abolished actin filament binding" (FYPO:0006025), like when annotating for loss of protein-protein interaction.  
![image](https://github.com/pombase/canto/assets/163283897/c947c5c4-02d9-4b6f-a907-0478c720df4a)
But it doesn't make much sense to me to be forced to input two binding partners in the case of interaction with actin filaments.

**Comment by ValWood** [comment]
Agreed, but  you can over-ride this in the text interface (I have been over riding, I assume this way, or it is possible the rule is not enforced and one is acceptable)
Maybe we should  make the requirement non mandatory though.

**Comment by PCarme** [comment]
Actually it is written as required, but possible to confirm the annotation with just one partner already.

**Comment by ValWood** [comment]
In this case it might be useful to add actin if that is the binding partner. Although "actin " is in the GO term, if we are doing clever computational stuff later a computer won't be aware that actin = act1, so if you know the binding partner add it even if redundent.

**Comment by kimrutherford** [comment]
I've change the configuration so you won't see the "(2 required)" in red.  Is the rest of the message OK?:

```
affected proteins (add TWO, i.e. both binding partners)
```

**Comment by ValWood** [comment]
yes!
