### ISSUE TITLE
How to know when a session has been accepted

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2833]
Does Canto have any way to notify admin curators when a session is started by a community curator, even if that session hasn't been sent out to the community curator by an admin curator in advance?

Currently, the only way we know to check this is in the list of publications in the the Canto admin interface.

@ValWood Do you normally get this information as part of the daily summary email that Canto is meant to send? Because I'm not sure if we've ever received this with PHI-Canto.

CC @CuzickA

**Comment by ValWood** [comment]
I think I would only know this from the email , but I don't think it ever happens ;)

If it did that session would just become one of the 'in progress' sessions and dealt with in the usual way.

**Comment by jseager7** [comment]
Thanks. @CuzickA Have you ever seen this daily summary email in the curation inbox?

**Comment by kimrutherford** [comment]
@jseager7 the daily summary runs from a cron job.  Do you have that set up?

PomBase has something like this in the crontab of the user that runs Canto:

```
40 1 * * * (cd $CANTO_DIR; ./script/canto_daily.pl http://curation.pombase.org/pombe)
```

You may need some shenanigans to run the script with Docker.  To make sure it's working, you can also run the script from the command line in the Canto directory.

You'll probably need `https://canto.phi-base.org/` as the argument to the script to make sure the links in the email work for you.

It's possible to view the contents of the daily summary email by going to https://canto.phi-base.org/tools/daily_summary
(It's a bit slow so you might have to wait a bit)

Let me know if I can help with anything.

**Comment by kimrutherford** [comment]
Hi @jseager7

Have you had any luck with this?

The first thing to try is this on the command line to see if an email is sent:
```
(cd $CANTO_DIR; ./script/canto_daily.pl http://curation.pombase.org/pombe)
```
(with your URL)

Or something like this with Docker:
```
canto/script/canto_docker ./script/canto_daily.pl http://curation.pombase.org/pombe
```

You'll need to set `admin_address` in `canto_deploy.yaml`.

**Comment by jseager7** [comment]
@kimrutherford I just haven't had time to get round to this yet, sorry. I should have some time to look into it today or later this week though.

**Comment by jseager7** [comment]
I've confirmed that I can access the daily report via the Canto website and I've added a call to the daily report script in our daily update script. I'll check whether an email is delivered tomorrow morning.

**Comment by ValWood** [comment]
Hi @jseager7 can we close?
v

**Comment by jseager7** [comment]
Yes, I'll close this since the question's been answered. I still haven't confirmed whether emails are working on our server but that's a separate issue.
