### ISSUE TITLE
404 not found error on  Canto help docs/ swap canto help docs over

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2835]
(I need to find instructions!)

https://pombase.github.io/canto_tutorial/phenotypes/genes_alleles_genotypes.md

**Comment by kimrutherford** [comment]
I've added configuration for linking to Manuel's new pages and updated the main Canto instance.

@jseager7 I've added a new config option `use_external_help`, which defaults to 0/false.  I think you'll be able to ignore these changes but if you see any weirdness around help or help links in Canto, please open an issue.

@ValWood I've changed the documentation links in the emails for community curators but we should test that by assigning / reassigning a session to one of us. 

I've also changed the inline links from clicking on the help icons:

![image](https://github.com/user-attachments/assets/13069073-f9cc-460d-af17-8c7369fbe481)

I may have missing some.  Please let me know if you notice any problems.
