### ISSUE TITLE
message to curators

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2836]
I think it would be useful, if here:
the message to curators was immediately visible.

<img width="1048" alt="Screenshot 2024-06-15 at 09 03 47" src="https://github.com/pombase/canto/assets/7359272/879cd43d-ac44-4c59-be86-9c1a0eea6f74">

**Comment by ValWood** [comment]
They are easy  to overlook becase you need to go to the session and then click on the lin. I often don't even notice this banner.

**Comment by kimrutherford** [comment]
> I think it would be useful, if here:
> the message to curators was immediately visible.

Yep, no problem.  I'll do that on Monday.

**Comment by kimrutherford** [comment]
That's done now.

**Comment by kimrutherford** [comment]
> That's done now.

But now it appears twice.  I wasn't paying attention. Whoops.  Shall I undo that change?

![image](https://github.com/pombase/canto/assets/90474/42b05881-f60e-47b3-8f35-fb7e10c89058)

**Comment by ValWood** [comment]
thanks that will be helpful

**Comment by ValWood** [comment]
ah right. so was it always there? it's better at the top, but I want noticing it?

**Comment by kimrutherford** [comment]
It's always been on that page.

**Comment by kimrutherford** [comment]
@ValWood Since we both missed that the message was already there, maybe having the message twice isn't the end of the world.

The other thing to think about that we need somewhere to put the "Edit" button.  Where it is now makes sense, directly under the message:
![mess-2](https://github.com/pombase/canto/assets/90474/b40fa185-01ed-4b33-92ea-97eea340a008)

**Comment by ValWood** [comment]
Yes go ahead with the edit button
I always see the messages now, and it's often very useful, so they were definitely hidden before.

**Comment by kimrutherford** [comment]
> Yes go ahead with the edit button

Sorry, I wasn't clear: the edit button is already there and has been for several years.

**Comment by ValWood** [comment]
got it, this is on the front page. that's fine

**Comment by kimrutherford** [comment]
Close we close this?

**Comment by ValWood** [comment]
Yes, all good!
