### ISSUE TITLE
cannot select term

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2838]
I cannot select the terms

increased cellular phosphate (Pi) level 
in Canto.

Maybe parenthesis are not allowed in their labels? If so I can fix

**Comment by kimrutherford** [comment]
That's very odd.  It looks like at some point the term was loaded into Canto with the namespace "fission__yeast_phenotype" (two underscores after "fission").  That has left us with two terms with the same ID but different namespaces which is causing an error when the term is looked up by ID.

I'll fix that.

**Comment by kimrutherford** [comment]
Fixed!

**Comment by kimrutherford** [comment]
> Did you just delete the duplicate term with the bad namespace from the obo file? Or do I need to do anything in the next edits?

I removed it from the Chado database.  I think that's all we need to do.

I don't know where or when the weird namespace crept in but it's not in FYPO now.

**Comment by ValWood** [comment]
OK, I remeeber it happening. It caused a release problem, and was fixed. I though it had recurred.

Thanks
Val
