### ISSUE TITLE
session admin: Reports : annotations grouped by session status

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#284]
Like this:

CURATION_IN_PROGRESS 789
SESSION_ACCEPTED 0
APPROVED 1673
SESSION_CREATED 0
CURATION_PAUSED 13
APPROVAL_IN_PROGRESS 80
NEEDS_APPROVAL 635

Original comment by: kimrutherford

**Comment by ValWood** [comment]
We have these numbers in the tool, I guess  we could also publish them in our curation statistics

**Comment by kimrutherford** [comment]
> I guess we could also publish them in our curation statistics

So on the this page?: https://curation.pombase.org/pombe/stats/annotation

Or does it just need to be on an admin page?

I created this issue but I don't remember why.  :-)

**Comment by ValWood** [comment]
Actually, we probably don't need this. We can just look in the tool, and it probably isn't that useful on a public-facing page. This ticket may even predate the grouping being availabe in Canto admin?

**Comment by kimrutherford** [comment]
> This ticket may even predate the grouping being availabe in Canto admin?

Yep, it's a very old issue.
