### ISSUE TITLE
New condition in PMID:25831549

### ISSUE THREAD

**Issue by PCarme** [pombase/canto#2840]
For this session, I need the condition "+ tetracycline", which is not available in Canto at the moment.

**Comment by kimrutherford** [comment]
Hi Pascal.  It will need to be added to the FYECO ontology.

Can you provide a definition for the new term?
There are lots of examples in the FYECO OBO file:
https://github.com/pombase/fypo/blob/master/fyeco.obo

**Comment by ValWood** [comment]
I was going to show you this when we next chat but you can probably figure it out.

I add them to the bottom of the file with the next ID number (this is a mini ontology but its very flat  so we don't use Protege).

They need. the appropriate grouping term so I look for a similar  type of term and use the same grouping class.

Your initial should be the same as we use in Protege usually initial (so pc would be fine) , and I think they might need to be put in a file somewhere... I need to look into that (I need  will sometimes need to use in protege for definition sources)

Definitiosn can also be copied from a similar term.

**Comment by ValWood** [comment]
@PCarme  you can add a new page with instructions here:
https://github.com/pombase/curation/wiki/Training
we don't have  any documentation for FYECO

**Comment by PCarme** [comment]
Okay, thanks for the instructions. 
I have added the term to the obo file, and the associated documentation to https://github.com/pombase/curation/wiki/Training.
