### ISSUE TITLE
GO not updating?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2844]
It seems as though GO is not updating in Canto or on the PomBase website.

1. This term has not appeared in Canto:
https://www.ebi.ac.uk/QuickGO/term/GO:0180043

2. On the website
https://www.pombase.org/gene/SPBC11B10.01
The terms 

GO:0000033 | alpha-1,3-mannosyltransferase activity
and
GO:0033164 | glycolipid 1,6-alpha-mannosyltransferase activity

should be hidden based on the new ancestry:
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0004378

**Comment by kimrutherford** [comment]
Hi Val.  The snapshot hasn't been updated for a while: http://snapshot.geneontology.org/summary.txt

We use the snapshot for Canto and Chado.

**Comment by ValWood** [comment]
It's weird that QUickGO is updating. They must be using something different.

Anyway will ask about the snapshot...

**Comment by kimrutherford** [comment]
We talked about using the daily updated version:
https://ontology-build.geneontology.org/
(Email thread with subject line "Fwd: Daily ontology builds")

But we haven't swapped to that yet.

**Comment by kimrutherford** [comment]
> This term has not appeared in Canto:
> https://www.ebi.ac.uk/QuickGO/term/GO:0180043

The daily update file contains `GO:0180043` "inositol pyrophosphate sensor activity":
https://ontology-build.geneontology.org/go-basic.obo
