### ISSUE TITLE
cannot add  new term requests to the same 'base' term

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2846]
So if I want to add multiple child terms to the same term, I am not allowed.
There should be an exemption  if there is a term request.
(I wanted to request terms for different chemicals)

<img width="1340" alt="Screenshot 2024-07-09 at 14 49 56" src="https://github.com/pombase/canto/assets/7359272/7e084237-80b8-472f-85d3-dd2d111f13e1">

**Comment by kimrutherford** [comment]
I've fixed that in the test Canto.

I will update the main Canto with the pending changes once we're happy with:
  - pombase/canto#2841

**Comment by kimrutherford** [comment]
> I will update the main Canto with the pending changes once we're happy with:

That change has been in the main Canto for a couple of weeks.  I'll close this but please re-open if you see any problems.
