### ISSUE TITLE
Missing GO term

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2852]
logs have:
warning in a7c6118865e72409: can't find term with ID: GO:0160199
warning in a7c6118865e72409: can't find term with ID: GO:0160199

but I see it here:
https://www.ebi.ac.uk/QuickGO/term/GO:0160199

**Comment by kimrutherford** [comment]
It looks like a timing issue.  It wasn't in last night's Chado but it's there tonight.  So the message should be gone in the morning.

**Comment by kimrutherford** [comment]
It looks like there was a delay between the snapshot running and the files appearing on the snapshot server?

We use this file for Chado:
```
http://snapshot.geneontology.org/ontology/go-basic.obo
```

The date in the file is:
```
data-version: releases/2024-08-04
```

Be the file timestamp implies that the file was copied to the snapshot web site three days later:
```sh
curl -s -I http://snapshot.geneontology.org/ontology/go-basic.obo | grep Last-Modified
```
```
Last-Modified: Wed, 07 Aug 2024 03:15:33 GMT
```

That doesn't explain why QuickGO is up to date though.

**Comment by ValWood** [comment]
Hi @kltm do you know how QuickGo is ahead of the snapshot? are we using the correct file?

**Comment by kltm** [comment]
@ValWood There are a few factors here, but most of them boil down to a combination of 1) syncing lag and 2) we are in a transition in how we setup our pipelines.

Most importantly for this, maybe, is that the initial part of a snapshot release is a "freezing" of the data, which _usually_ happens on Sunday. That is then manually checked and a secondary phase is run to produce associated product that we need; this used to be automated, and will be again soon. There can be a lag of a few days in there, but generally not more than that unless there is a problem.

The next bit is just informational, as we are changing this interaction and how our pipelines interact overall. QuickGO (currently) uses the QC version of the ontology, for some purposes, which is not synced with QC or annotation data. We will be switching to a faster and lighter pipeline which will better align all of these concerns soon (e.g. https://github.com/geneontology/pipeline/issues/382).

**Comment by ValWood** [comment]
Thanks for the info!
v

**Comment by kimrutherford** [comment]
All fine now: https://www.pombase.org/reference/PMID:19328067
