### ISSUE TITLE
Can't add extensions to phenotype annotations from genotype page

### ISSUE THREAD

**Issue by PCarme** [pombase/canto#2853]
I was doing a phenotype annotation using the long framework (from the genotype page) and at the step where we can normally add the extensions, it looked like this :
 
<img width="1206" alt="Screenshot 2024-08-14 at 11 15 22" src="https://github.com/user-attachments/assets/912bd17e-c35a-4d6c-b97a-d2eb6db3859f">

I had the same problem with other FYPO terms, but it seems to be specific to this genotype (the same page was normal for other genotypes), and I could still add the extensions afterwards using the editing window.

**Comment by kimrutherford** [comment]
Hi Pascal.  Could you add a link to the session where you see this bug?

**Comment by PCarme** [comment]
It is this one https://curation.pombase.org/pombe/curs/5f656dfe4953442a

**Comment by kimrutherford** [comment]
Thanks Pascal.  I think I've fixed the bug now.  Could you try again when you get time?   You'll need to reload the Canto page.

Canto was failing to cope with the prime (') character after the 3 in the allele name.  The bug has been there for 9 years!

**Comment by PCarme** [comment]
Yes that's working now, thanks Kim ! 
Given the specificity of the bug's cause, no wonder it remained unnoticed for so long...
