### ISSUE TITLE
Use GO daily build when updating the ontologies in Canto?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2856]
The nightly Chado load now uses GO daily build:
https://ontology-build.geneontology.org/

Should we do the same for Canto?

**Comment by ValWood** [comment]
I think so. ....

**Comment by kimrutherford** [comment]
OK, I'm trying it now.

**Comment by kimrutherford** [comment]
Seems OK.  There are no errors during the update and Canto is now using GO from 2024-09-25.
