### ISSUE TITLE
publication status numbers

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2859]
We have
[All publications ](https://curation.pombase.org/pombe/view/list/all_publications?model=track)(14412)

and here we seem to have almost 7000 total
<img width="504" alt="Screenshot 2024-10-03 at 11 40 16" src="https://github.com/user-attachments/assets/d69ce1dd-aad3-4cd7-b340-f87aa6ed4153">

I expected more since we are only excluding
[Wrong organism ](https://curation.pombase.org/pombe/view/list/triage_wrong_organism_publications?model=track)(3223)
[Loaded in error ](https://curation.pombase.org/pombe/view/list/triage_loaded_in_error_publications?model=track)(168)
[Bioarchive ](https://curation.pombase.org/pombe/view/list/triage_bioarchive_publications?model=track)(22)
[Duplicated in PubMed ](https://curation.pombase.org/pombe/view/list/triage_duplicated_in_pubmed_publications?model=track)(15)

**Comment by ValWood** [comment]
Ignore, it isn't live yet!

**Comment by ValWood** [comment]
I wasn't actually looking at the graph!

**Comment by kimrutherford** [comment]
The new graph is live.  You might have to shift-reload to see it.  If that doesn't work, let me know.

![image](https://github.com/user-attachments/assets/43fe57b7-8bb1-483d-84ca-a2350110cafb)
