### ISSUE TITLE
hide e-mails

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2864]
If you are not logged in to Canto you can find a curated with PMID you can see the e-mail addresses of curators
We should hide the e-mails in this case.

**Comment by ValWood** [comment]
In the canto session, but I think they should only be visible to logged-in users, not to everyone.

**Comment by kimrutherford** [comment]
Do you mean the email after "Curated by:"?

Is it helpful to community curators to know who will get credit for the annotations?  I'm thinking of the case where a PI just forwards the session link to a post-doc.  The PI will get credit and there would be no way for a community curator to see that in the session.

**Comment by ValWood** [comment]
We can discuss. I think it is OK if logged in , but at the moment anyone can access?

**Comment by kimrutherford** [comment]
> We can discuss. I think it is OK if logged in , but at the moment anyone can access?

Yep, anyone can access.

**Comment by ValWood** [comment]
Make is e-mails are not visible in review

**Comment by kimrutherford** [comment]
I'd forgotten that we already hide the "Curated by:" section at the top right in review mode.  But we do show the emails beside the annotations.  I'll fix that.

![image](https://github.com/user-attachments/assets/960884c5-0d8b-433a-a2e3-a4ff4cbfef6a)
