### ISSUE TITLE
Fix PubMed loading to add missing field data

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#309]
Change the loader to fix any missing abstract, citation or author lists.

Original comment by: kimrutherford

**Comment by ValWood** [comment]
Is this an issue? I never noticed it.

**Comment by kimrutherford** [comment]
> Change the loader to fix any missing abstract, citation or author lists.

Maybe this was added to the wrong tracker.  The Chado loader fixes missing PubMed data.
