### ISSUE TITLE
session admin: new session doesn't have status

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#310]
This is a small thing, but I noticed it, so here ya go ...

I assigned PMID:2908246 to Ryoko, and created a curation session, also assigned to her. Almost everything looks fine, but the curation session status column is blank everywhere All the other sessions I assigned to Ryoko have a status; the new ones say SESSION\_CREATED.

I don't see how the session could exist without being created, and I don't remember doing anything differently this time compared to when I set up the other sessions. Am I just being a numpty?

m

Original comment by: mah11

**Comment by ValWood** [comment]
I think I get this. I think there is a gap between assignment and the creation of a session (Kim can you confirm). I think you can assign a session to someone but it doesn't get "session created" until they accept it. Is that correct?

**Comment by mah11** [comment]
That doesn't make sense. How can you assign a session that doesn't exist? Anyway, I kind of suspect that this isn't a current problem -- I only saw the anomalous behaviour once, years ago, and the paper in question now has a different session in progress. I'm going to close this as out of date.

Aside - when someone accepts a session, its status changes FROM "session created" TO "session accepted".

**Comment by kimrutherford** [comment]
> I'm going to close this as out of date.

Fair enough.  It seems like a bug so please shout out if you see it again.
