### ISSUE TITLE
quick: distinguish AA and nt mutations

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#317]
From Antonia:

I think that protein mutations should be converted to capital letters automatically, and nucleotide mutations small letters. Capitals for amino acids is the convention. For DNA mutations I think it would be useful in order to distinguish it from protein mutations \(for instance in the table after finishing an annotation it is not clear whether G89A is a protein or DNA mutation\).

Original comment by: kimrutherford

**Comment by kimrutherford** [comment]
I've made this change in the test Canto.  Could you let me know if it's what you were thinking of?

**Comment by mah11** [comment]
Jarring at first, but I'll get used to it. More importantly, it does the job. thanks!

**Comment by kimrutherford** [comment]
OK, thanks.  I'll close this.  Please open new tickets for any tweaks.
