### ISSUE TITLE
QC: new check for protein binding phenotype extensions

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#377]
Hi,

In light of the Newfangled Approach to Binding Phenotypes that prompted Chado tracker item 3568453

we would also like the curation tool to run a new check: any assayed\_using\(\) extension to any annotations to the 'protein binding' phenotype terms \(see The List\) contains two or more gene/protein IDs.

The List:
FYPO:0000702
FYPO:0000703
FYPO:0000704
FYPO:0000705
FYPO:0001275

relevant background info:

https://sourceforge.net/tracker/index.php?func=detail&aid=3565516&group\_id=65526&atid=2096431
https://sourceforge.net/tracker/index.php?func=detail&aid=3568427&group\_id=65526&atid=2096431
https://sourceforge.net/tracker/?func=detail&atid=2096276&aid=3568453&group\_id=65526

https://sourceforge.net/apps/trac/pombase/wiki/ProteinBindingPhenotypeExtensions

thanks,
m/v/a

Original comment by: mah11

**Comment by ValWood** [comment]
A comment from an old e-mail which might be useful:
Midori:

More details on wiki (there may be slight changes to the exact syntax, depending on whether Kim has suggestions; what the wiki has now is a bit different from what Antonia put in the session):

https://sourceforge.net/apps/trac/pombase/wiki/ProteinBindingPhenotypeExtensions

**Comment by ValWood** [comment]
Is this still relevant, or is it enforced by AE interface?

**Comment by kimrutherford** [comment]
It's still relevant because we are keeping the free text AE field: #1063 

This should probably on the other issue tracker: https://github.com/pombase/pombase-chado/issues

**Comment by mah11** [comment]
Actually, I think this ticket could be closed, because as Kim notes, a check for anything dodgy in the free text field would fall under the Chado tracker's remit ... but there already is a Chado check for these extensions.
