### ISSUE TITLE
Form a plan for when oliver0 dies

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#4]
We need a backup plan to cope with oliver0 dying.

Original comment by: kimrutherford

**Comment by ValWood** [comment]
We said we would look into university managed web servers (only around £100 er year)
http://www.ucs.cam.ac.uk/managed-web-service/mws-facilities
Kim, if you could ask the Paul's I will do any necessary follow up. Or tell me what to do ....

Val

**Comment by kimrutherford** [comment]
I've had a look at the specs and the managed web service isn't going to work for us because we need too much space (for Chado and loading Chado) and it's not clear that we'd be able to run Canto.

**Comment by ValWood** [comment]
closing will be dealt with by mover to either biochemistry or ICS
