### ISSUE TITLE
user interface: message to curators/ triage comment  editable inside session

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#407]
I'd like the message to curators to be addable/editable inside the session (in approval mode)
...I find myself submitting + reactivating a session sometimes to add a comment on the fly (thoughts don't always stay in my head until the end of the paper!)

Original comment by: Antonialock

Added by Val:
This is not good because session reactivation changes the  dates and affects the stats

**Comment by ValWood** [comment]
- [ ] also preserve line breaks in the message

**Comment by ValWood** [comment]
I think this one is done via another ticket?

@Antonialock  please confirm

**Comment by ValWood** [comment]
how are these related, if at all

https://github.com/pombase/canto/issues/1987

**Comment by Antonialock** [comment]
yes this done. it is not related to #1987
