### ISSUE TITLE
session admin: preserve line breaks in the 'message to curators'

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#408]
I think it would make the comment more easy to read / look nicer if when the message is displayed (i.e. once in approval mode), any time the return/enter key has been clicked then the following text is shown on a new row.

Like this.

Original comment by: Antonialock

**Comment by ValWood** [comment]
Quick?

**Comment by ValWood** [comment]
Added to
https://github.com/pombase/canto/issues/407
