### ISSUE TITLE
if you find a genotype match need clearer instruction what to do next

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#44]
if you find a genotype match need clearer instruction what to do next
See screenshot

Original comment by: ValWood

**Comment by kimrutherford** [comment]
Could you have a look at the "Genotype search" page and let me know what text to add at the top?  Currently it just says "Select one or more genes to find matching genotypes: " then there are links beside the genotypes.  Seems a bit sparse.

**Comment by ValWood** [comment]
This must be "out of date" number 44.....
