### ISSUE TITLE
user interface: Admin panel within curation sessions

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#459]
we would like some form of admin panel inside each curation session.

This admin panel would contain links to relevant 'higher level' pages. For instance:
http://curation.pombase.org/test/view/object/curs/379?model=track

possibly also:
http://curation.pombase.org/test/view/object/pub/192?model=track

maybe there are others but if the panel is in place it should be easy to add in more links?

Original comment by: Antonialock

**Comment by ValWood** [comment]
I don't know what these higher level pages are so I am guessing this is no longer relevant?
