### ISSUE TITLE
session admin: read-only view of session in progress

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#481]
At present, canto has read-only links for sessions that have been submitted to curators (whether approved or not). It would be handy to have a read-only view of a session in progress, too.

I thought of this whilst talking with Val about the demo tool "being curated by somebody else" issue. This is my little scenario: Joe Bloggs looks up a paper by PMID, and gets the "being curated" message. Right now, that's a dead end. Joe might like to be able to click a linky to see that Jane Sploggs is curating the paper, what annotations have been added, get in touch if any look dodgy, etc.

Perhaps a button that says "view annotations" or something like that? I can do a mock-up if you want one.

Low priority until a bunch of other stuff is done.

Original comment by: mah11

**Comment by kimrutherford** [comment]
See also:  #943

**Comment by kimrutherford** [comment]
> Still need to change the "being curated by somebody else" message to add a link
> to the read-only session in progress. So I won't close this yet.

I think that's: #1166 

So I'll close this now.
