### ISSUE TITLE
session admin: Inconsistent behaviour when assigning curator

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#492]
Most importantly, it would help to add autocomplete to the popup that appears when you click "assign to curator ..." on the publication details page.

Should reuse the person autocomplete code from the triage page.

It would also be nice for autocomplete to offer to add a new user to the database if the name you type in can't be found.

(This may be a duplicate)

Original comment by: kimrutherford

**Comment by ValWood** [comment]
this isn't an issue for me. shauld we close? Is it fixed possibly?
