### ISSUE TITLE
session admin: streamline or speed up setting of community curation flag outside triage

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#516]
If I do not set the community curation flag whilst triaging (which I usually don't). I need to go back and set this later.
i usually do this by browsing the list of "publications without session"

However it takes quite a lot of clicks/steps:
click on PMID -> http://curation.pombase.org/pombe/view/object/pub/9568?model=track
click on "triage"
check community curation box
click on "curatable" (otherwise it doesn't work)
back button to go back to http://curation.pombase.org/pombe/view/object/pub/9568?model=track 
back button again to go back to the list

(It would be nice to be able to do this from the publication page, or even from the table itself)

Original comment by: ValWood

**Comment by ValWood** [comment]
will be sorted by
https://github.com/pombase/canto/issues/654
