### ISSUE TITLE
Table loading is slow - especially the publication tables

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#585]
Loading the all publications table is very slow:
  http://curation.pombase.org/pombe/view/list/all_publications?model=track

It just took 31 seconds to load for me.  That's no fun when you're using the next and previous links a lot.

It shouldn't be that slow, so find out where the slow down is and fix it.

Original comment by: kimrutherford

**Comment by kimrutherford** [comment]
I couldn't think of a way to fix this in a non-hacky way so I've had a go at fixing it in a hacky way.  Could you try the test tool and see if you spot any problems in the lists in the admin interface?  eg.
  https://curation.pombase.org/pombe/view/list/curatable_publications?model=track

Should be much faster than the main Canto.

**Comment by ValWood** [comment]
A *lot* faster

**Comment by ValWood** [comment]
that sooo much better...

**Comment by kimrutherford** [comment]
I've just fixed a bug and release the changes into the main Canto.  Let me know if you spot any problems.
