### ISSUE TITLE
session admin: nastiness in add person interface

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#591]
when you add a person and submit, their details remain in the text fields.

I have sometimes edited these fields to create a new person, which has overwritten the previous person. I don't think I have done this all the time. I think I have usually reloaded to get a blank form.

I can easily fix the problems but can you make it so that the text fields are blank after the form is submitted?

thanks
Val

Original comment by: ValWood

**Comment by ValWood** [comment]
I'm not sure that this still happens so closing.
