### ISSUE TITLE
session admin: not clear when session resent

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#592]
For this one

http://curation.pombase.org/pombe/view/object/pub/812?model=track

it appeared to be sent out a while ago,2012-07-13 15:33:12  so I resent the link

however this isn't recorded, so If I came back to this session I would not know that I had sent a reminder today?
v

Original comment by: ValWood

**Comment by ValWood** [comment]
Actually I think this is done...we have a last sent date now?
