### ISSUE TITLE
double mutant phenotype in combination with WT allele endogenous expression

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#599]
For "double mutant" phenotypes we want it to be possible to capture the combination
mutant allele + any expression level + WT allele endogenous expression level

Original comment by: Antonialock

**Comment by kimrutherford** [comment]
Should be fixed by 005dbb2a1341.  Could you see if it's doing what you think it should now?

**Comment by ValWood** [comment]
Is this done?

**Comment by kimrutherford** [comment]
I'll let Midori give it a go before I close the issue.

**Comment by mah11** [comment]
Yes, that's working nicely now. Thanks!
