### ISSUE TITLE
user interface: feedback to link to page where  papers can be self selected

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#616]
Antonai pointed out that
feedback should provide link to page where they can curate more papers from their lab.
At present if we send the link to them, they never see this page

Original comment by: ValWood

**Comment by ValWood** [comment]
do you mean a link to this page antonia?
https://curation.pombase.org/pombe/

**Comment by ValWood** [comment]
Add some text to make them go and look at their in progress list/front page link

**Comment by mah11** [comment]
maybe "Return to the PomBase Canto home page to find more of your publications" ?

**Comment by kimrutherford** [comment]
I've added a link.  Please close this if you're happy with how it looks.

**Comment by ValWood** [comment]
yep!
