### ISSUE TITLE
simplify changing expression for an allele in a genotype

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#62]
It would be nice to have a quick way to change the expression setting for an allele when editing a genotype. Right now, the only way I could see to do it was to delete the allele with wrong or unset expression, and add it back with the correct expression level.

Definitely not urgent, though. Especially since I haven't thought through exactly what the interface should look like - maybe "edit" and "delete" options instead of just the red x for "delete"? Or specifically "change expression level"?

(follow-up to, and inspired by, [curation-tool:#879])

Original comment by: mah11

**Comment by kimrutherford** [comment]
There is now an "edit" link beside each allele on the genotype edit page.

I've updated the test tool.  Could someone give allele editing a quick test before I re-release the main tool?

**Comment by mah11** [comment]
Yes, that looks great!

thanks :)

**Comment by kimrutherford** [comment]
> before I re-release the main tool?

I've re-released.  Let me know if you find any problems with allele editing.
