### ISSUE TITLE
Combine genes and interacting genes sections in the JSON output

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#660]
We only use the interacting_genes section when the annotation type is interaction.  It would be cleaner to put it all in the genes section.

It would probably be good to do this before we change the output to handle the multi-gene phenotypes.

eg. currently:

               "genes" : {
                  "Schizosaccharomyces pombe SPAC23H3.13c" : {
                     "organism" : "Schizosaccharomyces pombe",
                     "uniquename" : "SPAC23H3.13c"
                  }
               },
               "interacting_genes" : [
                  {
                     "primary_identifier" : "SPCC1753.02c"
                  }
               ],

Original comment by: kimrutherford

**Comment by kimrutherford** [comment]
I think this is nonsense - closing.
