### ISSUE TITLE
obvious-ify obsolete terms 

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#7]
Currently if you make an annotation to an obsolete term, the obsoleted term gets a red strikethrough on the annotations summary page, which is obvious & fine.

However, it is less obvious that the term has been obsoleted when you are browsing terms.

At the point of the lucene search, could obsoleted terms say:
genome stability defects (FYPO:0000241) OBSOLETE (or similar),

Also likewise point it out from the term overview page (see screenshots for what parts of the tool I am on about)

Original comment by: Antonialock

**Comment by ValWood** [comment]
@Antonialock This ticket might need updating, not sure what the current behavior is?

**Comment by kimrutherford** [comment]
> not sure what the current behavior is

Obsolete terms don't show up in the autocomplete.  Is that what was needed?

**Comment by Antonialock** [comment]
sounds good!

**Comment by ValWood** [comment]
I think so!
