### ISSUE TITLE
Add a way to select curator for annotation in approval mode

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#714]
In approval mode it would be useful to be able to choose if new or edited annotation should be attributed to the approver or to the original curator - an "Annotate as admin" checkbox might be enough.  And/or it would be nice to be able to edit fields in the "Curator" column in the lists of annotation.

Original comment by: kimrutherford

**Comment by ValWood** [comment]
Is all of this still true?

**Comment by kimrutherford** [comment]
This bit is fixed:
> if you reactivate a session all the flags and timestamps get reset so there is no way to tell if
> a session was once in approval.

But this hasn't been fixed:
> In approval mode it would be useful to be able to choose if new or edited annotation
> should be attributed to the approver or to the original curator

**Comment by ValWood** [comment]
The outstanding part of this ticket is redundant with newer
https://github.com/pombase/canto/issues/1182
