### ISSUE TITLE
allele selection, multiple options for the same allele

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#716]
I notice recently that there are often multiple options available for the same allele.

For example, see the attached screenshot

vas3-1(ntG507A)
vas3-1(unknown)
vas3-1(ntG507A)

So often the same allele is duplicated.

This isn't such a big problem, but it is confusing. Especially in the cases where th unnknown allele appears first in the list

vas3-1(unknown)
Int these cases, even if you selected  vas3-1(ntG507A)
"unknown" always appears as your allele description.

We can ignore this (as I am assuming that behind the scenes, the correct description is inserted), but users wouldn't know this and would therefore find it very confusing.

If there is a "real" description, "unknown" should not be available to select

Original comment by: ValWood

**Comment by ValWood** [comment]
EVERYONE, I don't think we are seeing duplicates of this type anymore. PLEASE REOPEN IF  WE ARE....

**Comment by mah11** [comment]
actually, I'm not sure I ever stopped seeing this.

it's all over the place in a15216784fcaa950 - a new copy of the same allele in the pulldown every time I add another genotype using the allele (e.g. plo1-ts35 in the session)

but it's just odd; it doesn't bother me, and if no one else has seen it lately, leave as is.

**Comment by kimrutherford** [comment]
This might be related to #938.  I'll fix that then check this bug again.

> it's all over the place in a15216784fcaa950

Thanks for the example.

**Comment by kimrutherford** [comment]
> a new copy of the same allele in the pulldown every time

That should be fixed now.
