### ISSUE TITLE
Accessing a paper by PMID

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#738]
Its actually pretty difficult to track down a paper by PMID

Say I wan tot search for PMID:24758716

I could go here

http://curation.pombase.org/pombe/tools/pubmed_id_start

but if a session already exists I get
can't create new session - a session already exists for: PMID:24758716

and if it doesn't exist I have to assign it to myself and then reassign it to a person

I can also go
to All publications and search on PMID but this takes ~ 2 minutes to load

Its not so bad If I know which subset a paper is in because I can  go straight there, and the shorter list take less time to search

Original comment by: ValWood

**Comment by ValWood** [comment]
I can do this in the Admin interface?
