### ISSUE TITLE
under consideration, show relationships in canto

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#744]
we chatted about showing the relation in  canto  but it is't urgent and we don't quit know what we would want it too look like. We will think about it....maybe an admin fetature at first

Original comment by: ValWood

**Comment by ValWood** [comment]
Comment form a while back
we chatted about showing the relation in  canto  but it is't urgent and we don't quit know what we would want it too look like. We will think about it....maybe an admin fetature at first

**Comment by ValWood** [comment]
We aren't sure if we would ever want to do this so its going tot he very back burner

**Comment by ValWood** [comment]
closing, it hasn't been mentioned for years, and I don't think it is necessary
