### ISSUE TITLE
ability to view 'upstream' terms

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#745]
Currently, the tool shows the child terms of whatever term you selected from the term search (and in the case of FYPO, a few other things that are not strictly children (is_a), but comes from other relations).

We also think it would be useful to browse the immediate parents of whatever term you selected in the search. 

For us (val and I) it would particularly be useful for the phenotype ontology. For general users it might also be beneficial for GO (us curators use QuickGO for this but general users are probably not very familiar with this tool). 

Original comment by: Antonialock

**Comment by ValWood** [comment]
https://github.com/pombase/canto/issues/188
