### ISSUE TITLE
Documentation: explain that multiple OBO files must be loaded at the same time

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#753]
Alistair Irvine has had some problems with Canto installation.  In particular the documentation about loading ontologies is not very clear.  It should be more detailed and it should point out that all ontologies in Canto have to be updated simultaneously. 

Original comment by: kimrutherford

**Comment by ValWood** [comment]
Kim, can this one be closed (I was wondering if chobo will supersede?)

**Comment by kimrutherford** [comment]
I've updated the docs.

> Kim, can this one be closed (I was wondering if chobo will supersede?)

Yep, I do plan to use Chobo for Canto loading.  It would solve a few problems.
