### ISSUE TITLE
lucene search: matching FYPO term 'flocculation'

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#767]
When I search on flocculation

increased mannose-specific cell-cell adhesion
Definition
A cell adhesion phenotype observed in the vegetative growth phase of the life cycle in which mannose-specific cell-cell adhesion is increased. Mannose-specific cell-cell adhesion is the attachment of one cell to another cell, mediated via the binding of cell wall proteins on one cell to mannose residues on the other, and when it is increased cells adhere to each other more strongly or to a greater extent than normal.
Synonym	
increased mannose-specific cell-cell adhesion during vegetative growth

is matched.
Should a 'flocculation synonym' be showing.... I can't see what is matching.
Val

Original comment by: ValWood

**Comment by ValWood** [comment]
@valwood needs to test behaviour and improve ticket when Canto back

**Comment by ValWood** [comment]
non issue
