### ISSUE TITLE
find genotype by name

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#776]
This is probably low priority, but was on the wiki:

Offer an option to search for genotypes by genotype name on the "find an existing genotype" page.

Original comment by: mah11

**Comment by ValWood** [comment]
Is this covered by
https://github.com/pombase/canto/issues/808

**Comment by ValWood** [comment]
parking this one for now. Not sure if we need it?

**Comment by ValWood** [comment]
duplicate of #808
