### ISSUE TITLE
allow wild type endogenous or not specified in genotype

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#779]
transferred from wiki

I think it was part of the original multi-gene phenotype spec that for genotypes that have both a wild-type copy and a mutant copy of the same gene, either or both can be at the endogenous expression level (if not, it should've been). So we need this change in the interface:

 Allow a wild type allele at endogenous or "not specified" expression as part of a genotype. The single gene phenotype version should not change -- that should still only offer overexpression and knockdown for wild type. If possible, it would be nice to have a warning if a genotype only has wild type, endogenous expression (and no other alleles) for any one gene.

Original comment by: mah11

**Comment by mah11** [comment]
I've added a bit about this to the FYPO Canto documentation.
