### ISSUE TITLE
make all evidence code description visible via mouse over

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#790]
a la "ontology definitions"

Original comment by: ValWood

**Comment by kimrutherford** [comment]
> make all evidence code description visible via mouse over

Is this referring to the annotation tables?

**Comment by ValWood** [comment]
Its when making the annotation,  when using the pull down menu. We should show the defs (from ECO) in the same way that we show the defs of ontology terms.

**Comment by ValWood** [comment]
![ev2](https://cloud.githubusercontent.com/assets/7359272/9434558/272dfa74-4a38-11e5-87bb-d6bef3689077.jpg)

**Comment by ValWood** [comment]
so here....

**Comment by kimrutherford** [comment]
> Its when making the annotation, when using the pull down menu. We should show the
> defs (from ECO) in the same way that we show the defs of ontology terms.

OK, thanks.

Unfortunately due to the way browsers implement these pull downs it's not possible to have it looking as nice as for the term completion, but we can do something basic quickly.

Where can I get some nice, brief descriptions of the evidence codes for GO?  Should I just use the first sentence on pages like this?: 
  http://geneontology.org/page/ida-inferred-direct-assay

Are these definitions OK for interaction evidence codes?:
  http://wiki.thebiogrid.org/doku.php/experimental_systems

**Comment by ValWood** [comment]
I think that all of the GO evidence codes are mapped to ECO, if this is the case we should be able to use the ECO descriptions for GO & FYPO?

**Comment by kimrutherford** [comment]
OK, thanks.  I found the mapping:
  https://evidenceontology.googlecode.com/svn/trunk/gaf-eco-mapping.txt

**Comment by kimrutherford** [comment]
I've got the definitions now but they aren't very friendly.  Should I use these for now?:

    EXP A type of experimental evidence that is used in a manual assertion.
    IBA A type of biological aspect of ancestor evidence that is used in a manual assertion.
    IBD A type of biological aspect of descendant evidence that is used in a manual assertion.
    IC A type of curator inference that is used in a manual assertion.
    IDA A type of direct assay evidence that is used in a manual assertion.
    IEA A type of evidence that is used in an automatic assertion.
    IEP A type of expression pattern evidence that is used in a manual assertion.
    IGC A type of genomic context evidence that is used in a manual assertion.
    IGI A type of genetic interaction experiment evidence that is used in a manual assertion.
    IKR A type of phylogenetic determination of loss of key residues evidence that is used in a manual assertion.
    IMP A type of mutant phenotype evidence that is used in a manual assertion.
    IMR A type of phylogenetic determination of loss of key residues evidence that is used in a manual assertion.
    IPI A type of physical interaction evidence that is used in a manual assertion.
    IRD A type of rapid divergence from ancestral sequence evidence that is used in a manual assertion.
    ISA Sequence alignment evidence that is used in a manual assertion.
    ISM A match to sequence model evidence that is employed in a manual assertion.
    ISO Sequence orthology evidence that is employed in a manual assertion.
    ISS Sequence similarity evidence that is used in a manual assertion.
    NAS A type of non-traceable author statement that is used in a manual assertion.
    ND A type of no biological data found that is used in a manual assertion.
    RCA A type of computational combinatorial analysis that is used in a manual assertion.
    TAS A type of traceable author statement that is used in a manual assertion.

**Comment by ValWood** [comment]
Oh.
Maybe we should only do this for biogrid codes then!

**Comment by kimrutherford** [comment]
Will these ones do?: http://wiki.thebiogrid.org/doku.php/experimental_systems

**Comment by kimrutherford** [comment]
The best I can do at the moment is this:

![screenshot 2015-08-28 22 02 50](https://cloud.githubusercontent.com/assets/90474/9544201/bc9868c2-4dd2-11e5-892c-d3219981ec90.png)

The description appears if you hover the mouse over an evidence code for a second.

**Comment by ValWood** [comment]
perfect,
thanks

Val
