### ISSUE TITLE
Show interaction direction in the annotation tables

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#794]
for asymmetric interactions we need to add the appropriate text from columns 3 or 4 (depending on if the gene is bait or prey) from this page:
https://sourceforge.net/apps/trac/pombase/wiki/BioGridBaitHitNotationMapping

to the annotation table so that the direction is clear.

The text should appear in brackets after the evidence code.

This ticket replaces: https://sourceforge.net/p/pombase/curation-tool/587/
which is mostly done.

Original comment by: kimrutherford

**Comment by ValWood** [comment]
bumping the priority as this often leads to missannotation

**Comment by kimrutherford** [comment]
The wiki has moved since this ticket was made.  Here's the new location:
  https://curation.pombase.org/pombase-trac/wiki/BioGridBaitHitNotationMapping

Is that page still up to date?

Sorry it's taken so long to fix this.

**Comment by mah11** [comment]
> Is that page still up to date?

yep.

**Comment by kimrutherford** [comment]
I've updated the test tool to add a more directional message.  I only remembered when I started implementing it that currently all of the interactions are displayed in one direction.  

What I mean is on the wee1 page of my test session after fixing the evidence text I now see:
   wee1 	Phenotypic Enhancement (phenotype enhanced by) 	cdc2 

and on the cdc2 page I see exactly the same thing.  So I'm not using the "enhances phenotype of" text.

Is that OK as it is?

(I've also removed the organism taxon ID columns from the tables as I don't think they are needed for pombe.  I can put them back if needed.)

![screenshot 2015-08-20 15 38 01](https://cloud.githubusercontent.com/assets/90474/9375165/842aa964-4751-11e5-95ce-cfcb7a04156f.png)

**Comment by kimrutherford** [comment]
Actually now I look at the old sourceforge ticket I see you have the picture below as an example.  Would you prefer on the gene pages to have the current gene in the left hand column?  Would it be better to have consistent positions for bait and prey in the table so that the table looks the same on the gene pages and on the front page?

![screenshot 2015-08-20 15 53 09](https://cloud.githubusercontent.com/assets/90474/9375357/cc25e63c-4753-11e5-8559-980264af4d95.png)

**Comment by ValWood** [comment]
I think so...do others agree

**Comment by mah11** [comment]
Hang on, I think this just happened:

Kim: Which is better, A or B?
Val: Yes.

I think Kim wants to know which we prefer:

- have the columns in "bait -> interaction -> prey" order everywhere in canto, OR

- on a gene-specific canto page, always have that gene listed first, even if it means swapping relative to how the interaction is displayed on the paper summary page?

For example, if aca1 affinity captures cdc3, the summary page will show "aca1 affinity captures cdc3".

The aca1 page will also show "aca1 affinity captures cdc3".

What do we want on the cdc3 page -- "aca1 affinity captures cdc3" or "cdc3 affinity captured by aca1"? The old-old-old mockup has the latter. I'll bumble along happily enough either way.

**Comment by ValWood** [comment]
Oh, I don't know. Antonia? preferences?

**Comment by kimrutherford** [comment]
> - have the columns in "bait -> interaction -> prey" order everywhere in canto

Just so you know, this option has the slight advantage that it's already done.

**Comment by ValWood** [comment]
Lets go with
have the columns in "bait -> interaction -> prey" order everywhere in canto

**Comment by ValWood** [comment]
Its done, OK
