### ISSUE TITLE
Warn about genotypes with wild type endogenous allele

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#797]
For after release of multi-allele version:

We can add a wild type endogenous allele if there is a wild type allele of the same gene with a non-endogenous expression.  But we can also then delete the non-endogenous expression allele.  That should be disallowed.

See also: https://sourceforge.net/p/pombase/curation-tool/782/

Original comment by: kimrutherford

**Comment by kimrutherford** [comment]
This is done in the test Canto.  Could you try it and let me know if it's doing what you expect?

The warning it displays is very long.  Could anyone suggest an improved text?  It's currently:

    A wild type allele with wild type product level is only valid in a genotype
    that has a wild type allele of the same gene with non wild type product level
    (eg. Overexpression or Knockdown)

**Comment by ValWood** [comment]
Would this be enough?

Wild type allele and expression level is only valid in a genotype with a mutant allele of the same gene.
