### ISSUE TITLE
question about has_output /output_of

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#803]
abnormal microtubule cytoskeleton organization during vegetative growth
has term suggestion
abnormal microtubule cytoskeleton during vegetative growth

'abnormal microtubule cytoskeleton during vegetative growth' is output_of 'abnormal microtubule cytoskeleton organization during vegetative growth'.

Here:
http://curation.pombase.org/pombase-trac/wiki/RelationsAndTransitivity

we say

output_of

Propagation: Annotations should propagate over output_of in the direction output A implies input B (A output_of B: all genes annotated to A should have annotation to B inferred).

Meaning: Phenotype A results from phenotype B. A mutation that causes phenotype A must also cause phenotype B.

Search results: A query for B should retrieve both genes annotated directly to B and genes annotated to A. Genes annotated to A can therefore be found by searching directly for A or by searching for B. A query for A will not necessarily retrieve all genes annotated to B.

Canto: TBD (under discussion)

Therefore
(A output_of B: all genes annotated to A should have annotation to B inferred)

'A abnormal microtubule cytoskeleton during vegetative growth' is output_of 'B abnormal microtubule cytoskeleton organization during vegetative growth'.

Canto is listed as under discussion. I don't think it was ever discussed? but the link is in place. It seems that we want to remove this link too? 

Original comment by: ValWood

**Comment by ValWood** [comment]
I think it is all working as we want now? At least I haven't noticed any incorrect of missing expected suggestions for *ages*?

**Comment by kimrutherford** [comment]
> I think it is all working as we want now?

As far as I know it's all fine.
