### ISSUE TITLE
Add duplicate link for genotypes

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#807]
Moved from: https://sourceforge.net/p/pombase/curation-tool/778/

For any genotypes, add a "duplicate" link that behaves like the duplicate-annotation link (to speed up & simplify adding new ones)

Original comment by: kimrutherford

**Comment by kimrutherford** [comment]
This is now implemented enough for testing.  I haven't released it into the main Canto yet, but it's available in the test version.  Could you try it and let me know what you think?

**Comment by kimrutherford** [comment]
I should have said: it's currently not clear that you're duplicating a genotype once you're on the genotype edit page.  Please let me know any text you think needs changing.

**Comment by mah11** [comment]
well, just now I got the "please come back later" message when I clicked on "add a genotype" ...

from http://curation.pombase.org/test/curs/dc80ed40f3a61b23/genotype_manage

**Comment by mah11** [comment]
p.s. I logged in

**Comment by kimrutherford** [comment]
> well, just now I got the "please come back later" message when I clicked on "add a genotype" ...

Sorry about that.  Should be fixed now.

**Comment by kimrutherford** [comment]
Currently there are duplicate links in two places:
  http://curation.pombase.org/test/curs/dc80ed40f3a61b23/feature/genotype/view/1
  http://curation.pombase.org/test/curs/dc80ed40f3a61b23/genotype_manage

Should we just have one?  If so, which one?

**Comment by mah11** [comment]
That is a thing of beauty. I love it and will use it a lot. I think it's good to have the duplicate links in both places.

For text on the page, this seems to cover everything, and is only a little wordier than I like:

"Add alleles from the genes below, and/or edit or delete existing alleles, until the new genotype is fully specified."

Don't know if it's worth changing the page header, but if so, we could use "Duplicating a genotype".

**Comment by kimrutherford** [comment]
> That is a thing of beauty. I love it and will use it a lot.

Excellent!

> I think it's good to have the duplicate links in both places.

OK, I'll leave both there for now.

> For text on the page, this seems to cover everything, and is only a little wordier than I like:

Fixed!  (In the test Canto at least, I'll update the main tool later today)
