### ISSUE TITLE
multi-allele Canto: "Find a genotype" function

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#808]
Moved from: https://sourceforge.net/p/pombase/curation-tool/778/

"Find a genotype" link - KMR 2014-11-20, this is partly done: there's a find a genotype function but it only searches genotypes from this session.

Is the current search function enough or is searching by genotype name needed too?

Original comment by: kimrutherford

**Comment by kimrutherford** [comment]
Closing because #776 covers finding a genotype by name.
