### ISSUE TITLE
Grey out the genotype delete link if the genotype has annotations

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#809]
Currently it only complains about existing annotations after you've tried to delete the genotype - not very slick.

Original comment by: kimrutherford

**Comment by ValWood** [comment]
Kim, Is this still current?

**Comment by kimrutherford** [comment]
> Kim, Is this still current?

Yep.  I haven't improved things yet.

**Comment by kimrutherford** [comment]
Fixed in the test Canto.
