### ISSUE TITLE
Restrict genotype matches displayed to "multi-allele matches"

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#817]
Decided to restrict alleles shown here to 'multi-allele'
as single gene phenotype bypasses this part of the interface. Less to look at....

Slightly related to:
https://sourceforge.net/p/pombase/curation-tool/821/

Original comment by: ValWood

**Comment by ValWood** [comment]
closing, superseded by
https://github.com/pombase/canto/issues/820
