### ISSUE TITLE
Force into ontology interface if annotation duplication/term change uses an ontology term which is new for a session

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#822]
Currently you can take a short cut to create a new annotation for a specific allele by duplicating and changing the ontology term.

If this creates an annotation to a term not previously used in the session the user should be forced into the ontology interface to inspect child terms to see if a more specific annotation is appropriate.

Less important than the rest so 6.
If this is not done before release to general public we will need to check annotation specificity more carefully.

Original comment by: ValWood

**Comment by kimrutherford** [comment]
@mah11:
> Yuck. When I do already know exactly which term I want, the extra clicking is a pain.
> Not sure if there's an answer that will work for everyone all the time.

Any thoughts on how we can improve the interface.  I agree it's too clicky now.

**Comment by ValWood** [comment]
Personally I prefer to  usually check the def and descendants. There are frequently used terms where I know I don't need to, but I don't have a big problem with the extra clicks for these.

How about if we added an "OK" button next to the term name for admin users only, which could over-ride selection from the drop-down, def check & descendent check?

**Comment by mah11** [comment]
That sounds like the same number of clicks for the case where you already know which term you want. Unless I don't fully understand what you mean ...

What if it could skip all the extra clicking if you type/paste an ID instead of a name? That could also be admin only if necessary.

**Comment by ValWood** [comment]
That would work. I think the likelihood of community pasting Is is low, and will probably indicate that they looked up the ID elsewhere so they know its the correct term.....

**Comment by kimrutherford** [comment]
> What if it could skip all the extra clicking if you type/paste an ID instead of a name?

Good plan.  I'll work on that.

**Comment by mah11** [comment]
>> What if it could skip all the extra clicking if you type/paste an ID instead of a name?
> 
> Good plan. I'll work on that.

I am already delighted by the implication that it's feasible.

**Comment by kimrutherford** [comment]
> What if it could skip all the extra clicking if you type/paste an ID instead of a name?

I've had a quick hack at that in the test Canto.  Could you let me know if it's what you're after?

**Comment by kimrutherford** [comment]
Even bigger hack.  As a test, I've changed things so that if you put double quotes around your search string you won't be asked for confirmation.  For example searching for:
  alcohol binding
will ask for confirmation and show the child terms but
  "alcohol binding"
won't.

I not sure that's a good idea in the main tool but I thought I'd try it.

**Comment by mah11** [comment]
Those seem to be working -- thanks!! My clicking muscles are heaving a sigh of relief :)

**Comment by kimrutherford** [comment]
> Those seem to be working -- thanks!! My clicking muscles are heaving a sigh of relief :)

Great.  Is it fixed enough to push those changes into the main Canto and close this issue?  We can tune things more later.

**Comment by kimrutherford** [comment]
I'll close this issue.  Please open a new one if there is more to do.

**Comment by mah11** [comment]
I thought it was fine; thanks
