### ISSUE TITLE
if a known allele description is added, prefil the name

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#828]
for example if I add to cdc2
mutation of single amino acid residue   G183E
via description, it should prefil cdc2-56

 It would  prevent people from adding the incorrect name for alleles which are already named.
At the moment "noname' appears  even for known alleles if you add only the description.

**Comment by ValWood** [comment]
if this is trciky it isn't absolutely required for release, so remove the tag

**Comment by kimrutherford** [comment]
This isn't too tricky, but it might introduce bugs.  I'd rather get Canto out to the users first and work on it in parallel.

**Comment by kimrutherford** [comment]
This is a very old issue.  :-)

What should happen when multiple alleles with different names have the same description?  Which name should be filled in?

We don't currently don't merge alleles from different sessions that have the same description when loading into Chado.  Should we be doing that?

Here's an example: "KQ(aaK106Q)[Not assayed]"  vs  "psm3-K106Q(aaK106Q)[Not assayed]"

https://curation.pombase.org/pombe/curs/74dade3ace393390/feature/gene/view/3/ro
https://curation.pombase.org/pombe/curs/94ca468a0f015cd5/feature/gene/view/3/ro

**Comment by ValWood** [comment]
This shouldn't happen and we are fixing them.

For this one, I standardized (both were wrong. The name should be psm3-KQ)
We always put the gene name as the prefix
Plus we would use the author name KQ instead or repeating the description K106Q.

So it now looks like this:

**Comment by ValWood** [comment]
As an aside, when I was doing this, I had to edit the single and multi allele genotypes descriptions. I'm sure that in PHI-Canto  the multi alleles are automagically updated (or did I imagine this?).
Anyway, it would be good to have a warning  if a multi-allele genotype referring to the edited allele exists

**Comment by ValWood** [comment]
We had a log file which reported an allele with the same description but different names. I can no longer find this, which one is it?

**Comment by ValWood** [comment]
I wanted to check this one was in the file...

**Comment by kimrutherford** [comment]
> We had a log file which reported an allele with the same description but different names. I can
> no longer find this, which one is it?

I don't remember that log file.  Should we add one?

**Comment by ValWood** [comment]
It was in the Canto log  and I no longer see this log here:
https://curation.pombase.org/dumps/latest_build/logs/

I know @mah11  recently fixed the ones which were reported as both nucleic acid and protein (we now report protein description for these). Perhaps others were "normalized" at the same time. But this one should be in the current log?

**Comment by kimrutherford** [comment]
> https://curation.pombase.org/dumps/builds/pombase-build-2019-09-23/logs/log.2019-09-23-21-27-00.curation-tool-data-load-output

I forgot that was something that was reported.  I found some in an older log file:
https://curation.pombase.org/dumps/builds/pombase-build-2019-09-23/logs/log.2019-09-23-21-27-00.curation-tool-data-load-output

I'll look into why my example isn't in the current log.

**Comment by kimrutherford** [comment]
> I forgot that was something that was reported.

Now I look closer the errors that are reported are the opposite of what we're after.  The loader complains when the description of an allele doesn't match the description of an allele from another session that has the same name:

warning in 58d8ad0dec113279: description for new allele "cdc10-K28(P383S,R610C)" does not match the existing allele with the same name "cdc10-K28(C1147T,C1557T,C1828T)" (from session 277ac92c6cd07f54)

We want a warning when an allele name is different in allele with the same description.

**Comment by ValWood** [comment]
Oh yes good point. We need both.
I  still don't see the Canto log though?

**Comment by kimrutherford** [comment]
> I still don't see the Canto log though?

It's here:
https://curation.pombase.org/dumps/latest_build/logs/log.2019-10-23-22-57-01.curation-tool-data-load-output

The file name changes but always ends with ".curation-tool-data-load-output"

**Comment by ValWood** [comment]
"psm3-KKQQ(K106Q,K107Q)" (from session f07cbe80a4008b28)
was wrong. I fixed the single alleles and multi-alleles containing this.

Nice catch!

**Comment by kimrutherford** [comment]
I've attempted a Chado query for all duplicate allele descriptions.  Here's a tab-delimited file with the results:
Dropbox/pombase/Chado/queries/duplicate_allele_disciptions-2019-11-07.tsv

The columns are: gene systematic ID, allele name, description, other allele name

Should I filter out that cases where the description is "unknown"?

**Comment by kimrutherford** [comment]
> The columns are: gene systematic ID, allele name, description, other allele name

I got that wrong.  It's: gene systematic ID, allele name, allele1 session, allele description, other allele name, other allele session

**Comment by ValWood** [comment]
I don't think we need to do this.
Especially if we  do this: https://github.com/pombase/canto/issues/1284

**Comment by ValWood** [comment]
...and the logs catch any errors
