### ISSUE TITLE
multi-allele: fix expression in JSON output

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#844]
The expression level is written out as part of the alleles in the JSON file for Chado.  It should be separate as the same allele can have different expression levels in different experiment.

This is needed before the multi-allele data can be loaded into Chado correctly.

Original comment by: kimrutherford

**Comment by kimrutherford** [comment]
Fixed by [5f1e058ad80ac38033f7bdf4fbf392ce395f0686].
