### ISSUE TITLE
editing  an allele in exisiting session

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#861]
This might be OK, but I wanted to note it.

I changed an allele of cdc2 in an existing session to standardize it.
See screenshot cdc2-1w gene page
cdc2.1w is the same as cdc2-1w so I changed to -1w which is used on the rest of the page

The edit  *seemed* to go OK, except  in the title 
New phenotype annotations fro this session...
it is still called  SPBC1B10.09-cdc2.1w
(see screenshot cdc2-1w)

Original comment by: ValWood

**Comment by ValWood** [comment]
Jacky says:

I have finished curating Pilar’s paper and I’m just rechecking for any inconsistencies as there were many many multi allele strains.  One problem I had was, for example, I would add several gene deletion alleles which also have pat1 for zygotic meiosis After  I annotated this then  I wanted to annotate the strain without pat1 and I  I had to redo the genotype I couldn’t just delete pat1, even if I had duplicated it first.  Im sure there is a way round this but I couldn’t find it as it always changed to one I had previously annotated . Sorry this sounds so complicated, the only reason it was a problem is that there were so many different strains

Is this the same issue I had? I won't know until go back to it...
If it isn't I'll put it in a new ticket.
We also might need to make it clearer what goes in a genotype and what goes in the strain background.

**Comment by mah11** [comment]
I think Jacky's problem is slightly different, although I'm not sure exactly what she wanted to do. The bits about with or without pat1 suggest that she had an annotation for genotype "pat1-114 gene1-1", and she wanted to make a new annotation for just "gene1-1" (without pat1-114). The part that's not clear is whether she wanted to keep both, or have the "gene1-1" annotation replace the "pat1-114 gene1-1" annotation.

To replace, she would have to edit the genotype (not the annotation) -- she should either click the genotype name in the annotation table, or go to the genotpye management page and click it there. Then she could remove the pat1-114 allele. All annotations to the genotype would be affected.

To keep both, she should add a new genotype with just the allele(s) she wants. That will be loads easier when the "duplicate a genotype" feature is available - requested in #807.

This ticket is about having to change the allele description and genotype name separately.

**Comment by ValWood** [comment]
non-isseu, need to manually fix
