### ISSUE TITLE
ability to add multiple genotypes in one go

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#864]
currently after you have created a new genotype, you are taken to the genotype page where you are asked to add a phenotype.

This is fine, but it would also be nice to have the option of adding another genotype from this page (so that I can add a few genotypes, then create the phenotype, and then transfer the phenotype across to the other genotypes in one go)

Original comment by: Antonialock

**Comment by ValWood** [comment]
not critical for release but ASAP after would be nice

**Comment by kimrutherford** [comment]
Did you mean to close this?

**Comment by ValWood** [comment]
nope, hmm, I see how it happened though..... very accessible close button

**Comment by kimrutherford** [comment]
After chatting, we should try adding a checkbox under the "finish" button with the text "Add another".  On mouse over, show the text: "If selected you can immediately add another genotype"

**Comment by kimrutherford** [comment]
I've added the "Add another" checkbox in the main Canto.  Could you try it and let me know if it's what you were thinking of?

**Comment by ValWood** [comment]
antonia can you check this feature?

Thanks

Val

**Comment by Antonialock** [comment]
Seems perfect!
