### ISSUE TITLE
missing "gene" in the navigation menu for single mutants

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#884]
When you enter a single mutant phenotype, the "navigation menu" (in the top left corner is:
PMID:25733668 summary
Genotype: genotypeX

could this be
PMID:25733668 summary
Gene: geneX
Genotype: genotypeX

instead? 

Original comment by: Antonialock

**Comment by ValWood** [comment]
Need to think of a neat way to do this which works for multi-gene genotypes.

**Comment by Antonialock** [comment]
ps. I need the gene name to be hyperlinked, I want to use it for "click navigation" not just visual navigation

**Comment by kimrutherford** [comment]
I've modified the trail in the test Canto to add links to the gene pages.  I'm not sure this is the right way to do it but I thought it would give us something to talk about:

![screenshot 2016-06-22 13 40 10](https://cloud.githubusercontent.com/assets/90474/16252006/eb3b4e00-387e-11e6-91d1-b372b93c1bc2.png)

**Comment by Antonialock** [comment]
I like that!

**Comment by ValWood** [comment]
What happens for multigene?

**Comment by Antonialock** [comment]
that is a multi gene example :-)

**Comment by ValWood** [comment]
ah right! got it. yep looks good....

**Comment by Antonialock** [comment]
go here to see:
https://curation.pombase.org/test/curs/18bff4f0eaed7095/feature/genotype/view/1

**Comment by ValWood** [comment]
nice...

**Comment by ValWood** [comment]
all done
