### ISSUE TITLE
the "Edit" pop-up lists genotype as gene

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#888]
I try to use the 'edit' pop up from a 'gene' page
(e.g. alp1 in this session) curs/c4669f01934c07d6/feature/gene/view/3

It appears
Edit phenotype annotation for alp1-1315(unknown)[Not specified]
geneotype alp1

I think I would expect to see
Edit phenotype annotation for alp1
genotype alp1-1315

**Comment by kimrutherford** [comment]
Could you confirm that this is still a bug?  If so I don't understand it, it seems OK to me.

**Comment by ValWood** [comment]
closing, I think this was fixed yesterday?
