### ISSUE TITLE
Add ability to change the genotype of an existing (duplicated) annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#889]
We would like to be able to change the genotype of an existing (duplicated) annotation from the gene page, and the genotype page.
(CAVEAT, in the first instance this will only work if the genotype already exists, we need to think further about how to  be able to add a new genotype at this point)

From these two pages, the allele/genotype selection  should be limited to alleles/genotypes for this gene (the summary page offers ALL genotypes for the session, which is fine)

**Comment by ValWood** [comment]
Also might need warning:
possible wording:
"Duplicate annotation not saved. Edit at least one field to create a new annotation using the "duplicate" feature."

**Comment by mah11** [comment]
That warning is *not* specific to switching a phenotype annotation to another genotype. It's applicable any time the "duplicate" feature is used for any annotation (and is not applicable to phenotypes where you do switch genotypes; it's meant to warn that you hit "duplicate" but didn't actually change anything).

I recommend that we ignore the comment about warning for this ticket, and put it in the correct ticket (which I think doesn't exist yet; I'll open one).

**Comment by kimrutherford** [comment]
> From these two pages, the allele/genotype selection should be limited to alleles/genotypes for this gene

How do we limited to the genotypes for "this gene" when we're on the genotype page?  The current genotype could have alleles from more than one gene.

**Comment by ValWood** [comment]
good point, maybe we can't restrict at all. I don't think we need to.
