### ISSUE TITLE
don't save duplicate annotation, but do warn

### ISSUE THREAD

**Issue by mah11** [pombase/canto#890]
If someone uses the "duplicate" feature (by that or any other name; there's also some discussion about possibly changing the text to "transfer"), but doesn't actually change any fields, right now Canto merrily saves a totally duplicate annotation.

Changed behaviour request: Don't save a duplicate annotation; instead issue a warning:

Duplicate annotation not saved. Edit at least one field to create a new annotation using the "duplicate" feature.

**Comment by ValWood** [comment]
I think we decided to keep as 'duplicate' for now.
Will add "multi-allele release",  not critical, but looks quick

**Comment by kimrutherford** [comment]
I had a look and it's a a bit fiddly to get right so I've postponed this.

**Comment by mah11** [comment]
OK. It would be kinda nice but is far from essential or urgent.

**Comment by kimrutherford** [comment]
> Don't save a duplicate annotation; instead issue a warning:

I've implemented this a slightly different way - the OK button is now greyed out until you modify the annotation.  If you mouse over the OK button it says: Make some changes or click "Cancel"

The changes are in the test Canto.  Let me know what you think.

**Comment by ValWood** [comment]
That works and seems sensible to me!
If anyone disagrees re-open.

I still think we need a better action than "duplicate" ...keep thinking
copy & edit ?
