### ISSUE TITLE
labelling of existing vs new annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#891]
I know we discussed this at length, but I can't see a ticket or remember the outcome.

I wonder if the best option would be to ONLY show the header 
"existing annotations for genex"

Is there any reason to show the header for new? We only need to be alerted about existing annotations?

**Comment by kimrutherford** [comment]
It was mentioned here: https://github.com/pombase/canto/issues/871#issuecomment-119434070
but I closed that ticket.

My suggestion there was: "Other annotation for PMID:01242424 in PomBase:"

**Comment by ValWood** [comment]
I guess this problem will cease to exist once we fully load artemis. I think it might be helpful in the meantime if ALL new annotations showed above the existing ones, maybe? At  present they are alternating...

**Comment by ValWood** [comment]
let's leave this as is for now. If it't ever a big problem we can adress.
