### ISSUE TITLE
showing "empty" headers

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#892]
I think we now only show the headers which are used in annotation.
This works fine on the summary page, but on 'gene' pages it looks a bit odd.

See attached screenshot.

Would it also be better if  you only showed the headers for the existing gene/genotype annotations

**Comment by kimrutherford** [comment]
I noticed that last week and fixed it.  Then I noticed it again today.  Whoops.  I'll fix it (again).

(I couldn't see your screenshot but I don't know where to look)

**Comment by ValWood** [comment]
I did not reilise I needed ti hit the "comment" button to add a screenshot, as I could see it.
Anyway it seems you don't need it here...

**Comment by ValWood** [comment]
![empty_headers](https://cloud.githubusercontent.com/assets/7359272/8569965/c5ecf518-2574-11e5-880b-eda2934e0744.jpg)

**Comment by kimrutherford** [comment]
I haven't fix this yet.

**Comment by kimrutherford** [comment]
There should be no empty headers now.
