### ISSUE TITLE
cannot add expression ...

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#893]
Somehow, in this session, I ended up with some phenotype annotations without "expression" information.
I cannot figure out how I can add this restrospectivly (shouldn't I be forced to specify)

screenshot attached

**Comment by mah11** [comment]
I don't see a screenshot. But the "edit" popup should offer the "please add experimental conditions" box; it does for me.

**Comment by ValWood** [comment]
Its expression.

**Comment by ValWood** [comment]
![no_expression](https://cloud.githubusercontent.com/assets/7359272/8569900/221d7e1c-2574-11e5-998e-418dcaba9185.jpg)

**Comment by kimrutherford** [comment]
Currently you have to edit the genotype to change the expression (it will warn that you have annotations for the genotype).  I think that makes sense because the expression is part of the genotype.  Am I understanding things?

**Comment by mah11** [comment]
Sorry, ignore my previous. For expression it's a bit of a pain: you have to go to the page for the genotype, and use the "edit" link there to change the genotype details. What's really a pain is that you have to delete and re-add the allele; you can't just change expression.

there's a ticket on the SF tracker about that, but I don't see its equivalent on this tracker - what's up with that? SF link is https://sourceforge.net/p/pombase/curation-tool/886/

**Comment by kimrutherford** [comment]
Is this the one?: #62.

**Comment by mah11** [comment]
Yep, that's the beast. Didn't occur to me that it would get so far out of order. thanks.

**Comment by ValWood** [comment]
I keep adding alleles with no expression because I am not forced to select an option as I used to be.
Perhaps if you were forced to select, it would not matter so much that you can't edit (I suspect that most need to edit comes from ommitting the expression in the first place?)

**Comment by kimrutherford** [comment]
Just to check: is the expression required for every allele type including "other"?

**Comment by mah11** [comment]
yes

**Comment by kimrutherford** [comment]
This fix is only in the test tool for now.
