### ISSUE TITLE
context specific advice about what to supply for the annotation extension field

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#894]
We need to transfer this from the old tool, even though annotation extensions will be revamped shortly.

For now, I suggest that the txt which used to appear appears directly in the text box as greyed out text if nobody objects.

**Comment by mah11** [comment]
Not sure what this refers to ... I don't remember there being any text that isn't still there on the "finish" page. I don't think there's any point moving the text from above the boxes to in the box on that page.

If you mean we should add some text to the "edit" and "duplicate" popups, that makes more sense, but it's a lot to put inside a type-here field. Also remember that there won't be an "annotation extension" box for non-admin users until the big extension-interface revamp is done anyway, so the helpful text would have to be associated with the comment box instead.

**Comment by ValWood** [comment]
yeah ignore me....
