### ISSUE TITLE
fixing an allele description

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#895]
I want to edit an allele description in
curs/c4669f01934c07d6/feature/genotype/view/5

I have made a bunch of single and multigene phenotype annotations  using 
alp2-996(unknown), now I want to change it to  nt G1065A /(C356)Y

but I can't seem to create an allele with the new description

**Comment by ValWood** [comment]
also 
atb2-1212 nt G737A / G246D

**Comment by mah11** [comment]
I have done the first one, so I can tell you how to do the other one ;)

- Go to the genotype page (for atb2-1212 it's http://curation.pombase.org/pombe/curs/c4669f01934c07d6/feature/genotype/view/3).

- Click "Edit", and click "OK" in the "really edit?" pop-up.

- Add the allele with the known description, i.e. click the "Add allele" button for the gene, and fill in all the details, including the name.

- Delete the allele with the same name and the "unknown" description. Click "Finish". Ta-da!

If that's what you tried, note specifically which step went wrong and how, so Kim can debug. But it just worked for me for alp2-996.

**Comment by mah11** [comment]
one more hint: when you put in the allele name, *don't* select any of the autocomplete matches. then you'll be able to fill in new details.

**Comment by ValWood** [comment]
thanks, got it...I think I just got scared...

**Comment by kimrutherford** [comment]
See also #62

**Comment by ValWood** [comment]
This should be easier, but not important for release as its a relatively rare action...hopefully people will mail us if they want to do this

**Comment by ValWood** [comment]
I'll close this... it's a non- issue
