### ISSUE TITLE
show biogrid evidence code directionality and description

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#896]
Start with what we had in the old version.
Are there other tickets about this? Do we need more (I think there was something still to do)

**Comment by mah11** [comment]
these are open: #794 #790 #229

**Comment by kimrutherford** [comment]
> Start with what we had in the old version.

Has it changed?  Could you give me an example?

**Comment by kimrutherford** [comment]
The existing issues about directionality are low priority.  Should they be?

**Comment by ValWood** [comment]
It can be low, actually I think this is probably just a duplicate of the outstanding ticket, it was never implemented in Canto, I thought it was.

I think we just want  the directionality displayed on the gene pages
http://www.pombase.org/spombe/result/SPBC11B10.09#interactionPhysical
(column 1)

It can be later

**Comment by ValWood** [comment]
actually , i think it has changed, but i can't check the old tool now ;)

I think the old tool did used to have the 'tips' about directionaliy in brackets after the evidence code. can anyone confirm. I'm sure this must be the case because I used to be able to do the biogrid annotation, and now I have no idea if I am going in the right direction or not......

**Comment by ValWood** [comment]
![directionality](https://cloud.githubusercontent.com/assets/7359272/8645154/b9aa01b2-293c-11e5-8f66-38dbbb99dfcc.jpg)

**Comment by ValWood** [comment]
found it (the demo is still the old version). This looks quick (basically you just need to add the note in brackets to the evidence code selector so we get the right 'directionality'

**Comment by ValWood** [comment]
https://github.com/pombase/canto/issues/794

**Comment by ValWood** [comment]
Highish priority as quick and stops people annotating in the wrong direction
