### ISSUE TITLE
Annotations added with "Quick add ..." don't always show up

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#898]
Annotations only show up if there is one of the same type in the table already.  eg. a new component annotation will only show if there is already a component annotation.

**Comment by ValWood** [comment]
Is this a duplicate of
https://github.com/pombase/canto/issues/919 ?

**Comment by ValWood** [comment]
Adding "next" because it *looks* quick if its easy to track down.

**Comment by mah11** [comment]
de-nexting because it only affects admins, and therefore won't scare community users

**Comment by kimrutherford** [comment]
This is fixed in the test Canto.  I haven't released it in the main Canto yet.  Some rearrangement of code was needed so I think it needs to sit in the test tool for a while to mature (like a fine wine).

Please let me know if you spot any problems with the annotation tables or with adding, deleting, editing or duplicating annotation.  I'll close this now but please re-open if there are bugs.
