### ISSUE TITLE
refine text on gene list page options

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#901]
This text is on the add gene list page, can anyone suggest a text refinement (we could be more verbose here because the page is quite empty).

>
> There is a box at the bottom saying this paper does not contain any gene-specific information. Does this mean that as I have only put the gene name and no additional information  I should therefore tick it.
Maybe we should make that clearer. You might use this for example if I mistakenly sent out a review, or a methods paper where some genes were mentioned, but there was no experimental data.

>
> Sorry and

**Comment by ValWood** [comment]
Maybe we can also make it clearer here that missing genes can easily be added later? ....

We  want to get people past the first pages before the confusion sets in;)

**Comment by mah11** [comment]
one set of suggestions ...

top - add at end:
You can edit this list later if you need to to add more genes or remove "unused" genes.

bottom - add between big text box and tickbox:
If this paper does not mention any genes individually, check this box and select a reason from the pulldown menu that will appear.

**Comment by mah11** [comment]
I've also just added a tiny bit of text to the documentation.

**Comment by ValWood** [comment]
Re
bottom - add between big text box and tickbox:
If this paper does not mention any genes individually, check this box and select a reason from the pulldown menu that will appear.

I think you can still select this option if you have added genes but there is no gene specific information to curate?

**Comment by mah11** [comment]
What's the use case for listing genes but then ticking the box? If there's really no gene-specific information, how and why would pick genes to put in the session?

**Comment by ValWood** [comment]
Say it was a review (but this was not obvious) I might send it out, and it might mention some genes. Sometimes people have added the genes and said it is a review.

Or it may focus on discussion of certain genes, but then not do any experiment types which are relevant. I have seen examples of both, I'm sure.

Even though our instructions say you are only curating experimental data, it isn't really explicit that you only enter genes for which you have experimental data....

**Comment by mah11** [comment]
Those sound like "gene-specific information" to me. In those situations you could list the genes, continue, and then use the "No experimental results to add?" tickbox on the summary page to submit the gene list.

**Comment by mah11** [comment]
... which is undocumented at the moment. Going on my to-do list ...

**Comment by ValWood** [comment]
OK I think I'm confused. I'll pay attention to the options next time I start a  session

**Comment by mah11** [comment]
Meanwhile, back at the ranch, I've updated the documentation again.

**Comment by ValWood** [comment]
I wonder if this is clear but we should discuss with workflow and decide if any changes are required. It might need clarification.

**Comment by ValWood** [comment]
Please list the genes studied in this paper using the systematic identifier (eg. SPCC1739.10) or standard name (eg. cdc11) separated by commas, spaces, tabs or one per line.
OR
For large scale datasets  e-mail the help desk to discuss bulk submission options.
OR
if this paper does not contain gene-specific data tick here  [] and choose a reason.

[ Gene list BOX]

**Comment by kimrutherford** [comment]
> ... OR ... OR ...

Maybe we should have one extra click on this page.

We could have a little menu like with a button or link for each possibility:

- I have a list of genes from the publication [enter genes ...]
- I have a large scale dataset [contact curators ...]
- this paper does not contain gene-specific data [choose reason ...]

The first option would go to the normal gene upload page.  The second to a form for contacting you.  And the third for choosing a reason, then finishing.

It's an extra click, but we could do this without reloading the page.

**Comment by ValWood** [comment]
@mah11 @Antonialock 
what do you think  of this suggestion?
I think this might be quite useful. We could also begin to point people to spreadsheet formats or other routes eventually by checking their data types form the large scale dataset route?

**Comment by Antonialock** [comment]
yeah that sounds good?

for large scale datasets they will still probably take pat of the paper through canto (because they will probbaly have additional charactrerization of a subset of the genes identified in the screen) but then when they contact us we can tell them about that..

**Comment by ValWood** [comment]
Good point. In these cases it probably makes sense to do stuff in spreadsheets first, and then  Canto the rest...

**Comment by mah11** [comment]
Arg, it's so much clicking already ...

What is the problem that adding a new click would solve?

If we do add it, could it be implemented such that admin users skip it? We'll already know whether we need to do a bulk file, a Canto session, or both. (Description wording would also need tweaking, because anything with a large-scale dataset could arguably also have a list of genes, so any user who would need such an extensive revamp would very likely also not get the distinction between the first and second options as presented above.)

**Comment by ValWood** [comment]
OK, let's go with our original proposal for now (which is a slight text rearrangement and ordering).

Any further changes will probably benefit from user testing.

**Comment by kimrutherford** [comment]
> OK, let's go with our original proposal for now (which is a slight text rearrangement and ordering).

Do you mean the text from Midori's comment that starts: "one set of suggestions ..." - https://github.com/pombase/canto/issues/901#issuecomment-121218476 ?

**Comment by ValWood** [comment]
Yep.
Val

**Comment by kimrutherford** [comment]
I've changed the text on the gene upload page.

But I think it's still unclear - the check box is hard to see.

**Comment by kimrutherford** [comment]
> I've changed the text on the gene upload page.

I should have said: it's only in the test Canto for now.

**Comment by ValWood** [comment]
That's OK, we'll close this and do user testing for further improvements
