### ISSUE TITLE
field labels invisible on Add and Edit pages

### ISSUE THREAD

**Issue by mah11** [pombase/canto#902]
Various pages for adding or editing items have text boxes that seem not to have labels in the live pombe Canto. In the test instance, I noticed that it's actually because the labels are there, but are in white text that barely shows up against the yellow "test" background (and not at all against the white background on live). Black's much more visible ... fix please?

Affected pages (that I've found so far):
New person
New lab
New curs
New pub
Edit person
Edit lab
Edit pub

**Comment by mah11** [comment]
ooh, sometimes the field content is invisible white-on-white too

e.g. this is supposedly me:
http://curation.pombase.org/pombe/object/edit/person/2?model=track

shout if you want a screenshot

**Comment by kimrutherford** [comment]
That was a bit of a head-scratcher.  I worked fine on my laptop.  I narrowed it down and upgraded one perl library(*) on oliver0 and it's fixed.

(*) for the record it was HTML::FormFu - we needed version > v2.0
