### ISSUE TITLE
Do we need the New curs form?

### ISSUE THREAD

**Issue by mah11** [pombase/canto#903]
Can we remove the New curs page (reached via the "Add ... Curation session" admin link)? It looks buggy in the test instance right now (and I ain't about to mess with what's in live), and I don't think it would be the most useful thing even if it got fixed. Doesn't seem like fun to generate hex-gibberish session IDs manually.

We can easily do without it, since we can find and add papers, and then push the button to create sessions for them, with autogenerated IDs creation dates.

**Comment by kimrutherford** [comment]
I agree, it's no use anymore.  I'll remove it.
