### ISSUE TITLE
Which pub fields are mandatory?

### ISSUE THREAD

**Issue by mah11** [pombase/canto#904]
On the New pub page (admin link "Add ... Publication details"), which fields are mandatory? Do any of the text fields have controlled input? I wanna know for the documentation, and I'm too lazy to find out by trial & error.

These are the fields:
Publication ID
title
authors
abstract
citation
publication date
affiliation
corresponding author
community curatable
load type
triage status
curation priority

**Comment by mah11** [comment]
That said, is it even working at the moment? On both live and test I can't actually input anything into any of the text fields (not that I want actually add anything on live, but I was trying it out on test so I could document it).

This one I think we should fix somewhere along the line. It isn't urgent at all for pombe, because we hardly ever encounter papers without PubMed IDs, but could be useful for other dbs/species.

**Comment by mah11** [comment]
There's also a tickbox floating off by itself near the left-hand margin. I guess it's supposed to go with the "community curatable" label.

I can open a separate ticket for this if you think it's worth it, and/or upload a screenshot if you can't see what I mean.

**Comment by kimrutherford** [comment]
I agree, it's not functional at the moment, so I've temporarily removed the new to the new publication page in 9fdf825ab8d6dfa333eec45bbf463a21aa9b1712.

I'll close this issue.  We can open another when it becomes needed.

Thanks for testing these pages.  I haven't looked at them in ages.
