### ISSUE TITLE
remove old annotation transfer method from GO interface?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#905]
shall we get rid of this? it seems so old fashioned now....

**Comment by ValWood** [comment]
![remove](https://cloud.githubusercontent.com/assets/7359272/8685311/987dde2a-2a75-11e5-8b5c-e2c72ed8d5ee.jpg)

**Comment by mah11** [comment]
also see #795

**Comment by ValWood** [comment]
If its easy could get rid of the annotation transfer section now.  Then we only need to think about the other sections later.

For what its worth, I think the adding a comment box, in the eventual incarnation,  could be very small. it is not usually used for long comments.....

Tonight, I was wondering if the annotation extension par could move forward to be done on the same page as evidence for GO?..... thoughts.? maybe begin with separate pages and then see if any steps can be combined into a single page once we we see  how much space they take?

**Comment by kimrutherford** [comment]
> For what its worth, I think the adding a comment box, in the eventual incarnation,
> could be very small. it is not usually used for long comments.....

If we get rid of the transfer page, where should the comment box go?  On a page of its own?

> Tonight, I was wondering if the annotation extension par could move forward to be done on the same page as evidence for GO?

I vote for a separate page for now.  It won't need a page reload which should reduce the annoyance levels.

**Comment by ValWood** [comment]
duplicates #795
