### ISSUE TITLE
Fix title when gene or genotype name is long

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#908]
This looks naff:

![screenshot 2015-07-16 18 45 26](https://cloud.githubusercontent.com/assets/90474/8717004/f96cc126-2bea-11e5-91de-921274e8f669.png)

**Comment by ValWood** [comment]
1. Make the  Genotype page link shorter (Genotype details), and not a link, ditto gene page

**Comment by kimrutherford** [comment]
> and not a link

Forgot that bit.  I've added a note to #824.
