### ISSUE TITLE
can't edit extensions for GO MF annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#910]
In this session curs/7cec44eee583f82d/feature/gene/view/4
I want to change the extension relation from has_direct_input to has_regulation_target

I don't seem to be able to do this.

1. If I try to edit, I do not see an option to edit extensions
2. Same if I duplicate and edit
3. I created a new annotation with an extension, but I could not edit the resulting extension

**Comment by ValWood** [comment]
I have created annotations with the correct extensions by making individual annotation. 
It's odd as I am sure I have been editing extensions all the time until today..... but it doesn't seem to be possible to edit them at all...I guess this can wait for the new interface though...

**Comment by kimrutherford** [comment]
> but I could not edit the resulting extension

Could you give a bit more detail?  Does the edit button not work?  Is there an error?

**Comment by ValWood** [comment]
There was no editable box for annotations after the annotation was duplicated.
However I have seen the editable box in other sessions, so I think that this restriction applies only to legacy sessions, in which case  it is a non-issue. We can manage the updates in the old sessions ny making new annotations from scratch.

If it becomes an issue we'll open a new ticket

**Comment by kimrutherford** [comment]
The edit box should definitely pop up if you click "duplicate".  It should do for all sessions including old sessions.

It's possible the Uni network problems caused this but it sounds like a bug.  Which browser was it?

**Comment by ValWood** [comment]
sorry wasn't clear. You get the edit box, but it excludes the annotations "extensions option", even if curated annotation_extensions exist...

**Comment by mah11** [comment]
Val - could the network problem or fixing thereof have logged you out? Canto login was definitely affected from the office, and what you describe is exactly what a non-logged-in (or non-admin) user would get from the edit link.

**Comment by ValWood** [comment]
I bet thats it. I did think of that and it still showed my as logged in, but the problem went away later so that would explain...

**Comment by ValWood** [comment]
nope, I rechecked the session. I could reach the admin page, so logged in properly, but the edit button showed me no extensions options. It seems to be session specific. Maybe it applies to sessions which were started before the move?

**Comment by kimrutherford** [comment]
Sorry for the hassle, I've worked this our after a bit of a think.  The extension can't be edited because the session is community curated (Mark Corkins).  You're editing as an admin but the session has a "community curated" flag set.  The code for the edit dialog should be checking the status of whoever is doing the editing rather than the session owner - bug.

**Comment by ValWood** [comment]
ah OK. That will be better if the curator can also be preserved. The way I did it I ended up as the curator, I lost the community curator assignment as I had to make totally new annotations.

val

**Comment by ValWood** [comment]
Same problem here
curs/186e8e06649ff2d7/feature/genotype/view/3
It isn't network related, I'm logged in

In this session I have no access to edit an extension. I can create an extension in a new annotation, but I can't edit it.

**Comment by kimrutherford** [comment]
> The way I did it I ended up as the curator, I lost the community curator assignment as
> I had to make totally new annotations.

I don't follow that.

**Comment by ValWood** [comment]
> I don't follow that.

don't worry, I'll open a new ticket if further issues...
