### ISSUE TITLE
ntr:decreased protein localization to mitotic contractile ring

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#915]
descendent of
decreased protein localization to actomyosin contractile ring

def
A cell phenotype observed in the vegetative growth phase of the life cycle in which the localization of a protein to the mitotic contractile ring is decreased.

PMID:25688133

**Comment by mah11** [comment]
a) wrong tracker
b) the existing term is already defined as applying to vegetative growth/mitotic cytokinesis, so I'll add a synonym
c) GO CC doesn't define a "mitotic contractile ring"
