### ISSUE TITLE
distinguish between existing conditions  and new conditions in CO 

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#920]
It would be really useful if you can see at a glance which conditions are in the ontology and which are not.
Sometimes a community person will use a mixture of established and new condition terms. You can't approve the session if terms are not in the ontology, but it is not easy to know exactly which terms are not in the ontology 
which can be a problem if they used a lot of condition terms....
flagging the new ones in a different colour or something would work, as this distinction is only required by curators when checking....

**Comment by ValWood** [comment]
Or sooner if quick

**Comment by kimrutherford** [comment]
Fixed in test and will be in the main Canto next time I update.
