### ISSUE TITLE
not having to click in the ontology search field in edit window

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#922]
When you go to edit a term, you not only need to 'click' in the filed to edit, you also need to type something.
This means that to access a descendent term I need to do the following steps
i) click in the box, and add a space to get the drop down to appear
ii) click on the drop down  to get the term to appear
iii) click "next" to see decendants
Which is 3 clicks, so making  the drop down immediately you click in the box would help

I also wonder if the little bit of text "this term has x children" could actually be a quicklink to the descendent page part of the pop-up (would cut out steps 1-3)

https://github.com/pombase/canto/issues/874

**Comment by kimrutherford** [comment]
The autocomplete now activates when you click and the "The term has X children" text is now clickable.
