### ISSUE TITLE
name does not automatically appear for the same genotype

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#923]
I  added a "name" for a genotype in this session, but the name only appeared on a single instance of the genotype. Can the name appear for all instances of the same genotype?

**Comment by ValWood** [comment]
![name does not automatically appear for same genotype](https://cloud.githubusercontent.com/assets/7359272/8914026/9dc6bbee-3494-11e5-9d50-6b05b4ad0380.jpg)

**Comment by ValWood** [comment]
see name deltaCCPR above appears for 1st instance of 
cig1delta/cig2delta/puc1delta/rem1delta, but not the following two

**Comment by ValWood** [comment]
I now wonder if this is the same bug. For this one, I noticed that  there are 2 alleles appearing for
rem1delta/crs1delta. The only difference is the background, but this is separate from the genotype.
All instances of rem1delta/crs1delta should be merged...

Let me know if I need to do anything to fix this...

Val

**Comment by ValWood** [comment]
![rem1delta crs1delta 2 genotypes](https://cloud.githubusercontent.com/assets/7359272/8914121/4de7c586-3495-11e5-8752-7bffd12b6801.jpg)

**Comment by mah11** [comment]
I don't see a bug here. You have assigned a name to the cig2Δ/cig1Δ/puc1Δ/rem1Δ genotype that has pat1as2 in the background, and you haven't named the genotype that has the same deletions but without the pat1as2 background. They are two different genotypes in Canto as they are in reality -- the background is part of the genotype, NOT separate from it.

If there's really only one genotype used in the paper, then you'll have to move some annotations to whichever genotype has the correct description (counting both "alleles of interest" and background). You would then be able to delete the other.

I also tested naming a genotype in one of my sessions, and the name does appear for all annotations to the same genotype.

**Comment by ValWood** [comment]
ah ok I thought it was separate.  will need to bear this in mind for querying purposes ....

this is OK since I need to ADD ALL PAT1 back....

I see a small issue thought that I think most would probably add  a name which excludes the background For example throughout this paper the short name for
deltaCCPC is deltaCCPC with or without pat1. I guess this needs to be part of our checks, otherwise
deltaCCPC
and
deltaCCPC pat1as 
will have the same short name (because that's what the authors do in the papers).

I actually  think it will be a bit of a pain to have to include nutritional markers etc in the 'genotype name' when the authors don't....A pity there isn't a workaround for this.....
