### ISSUE TITLE
small bugs in edit interface display

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#924]
1. Abnormally long box appearing for genotype
2 Conditions going off the end of box instead of wrapping
3. Condition explanatory  text going off end of  edit box.
(in curs/9f25f26d17f2ec78 I don't know if it is specific to this session)

(When you do this could the text be formatted like:
Please add experimental conditions. Conditions are aspects...
(I.e don't start a new line , just continue and line wrap as necessary)

**Comment by ValWood** [comment]
![small bug](https://cloud.githubusercontent.com/assets/7359272/8914477/81eb752e-3497-11e5-8aec-6dda4adb6f5e.jpg)

**Comment by kimrutherford** [comment]
This should be fixed now.  I _think_ the problem was that there was a genotype with a very long name or description.  That was causing the selector to be very wide and was screwing up the rest of the dialog.  The maximum width of the selector is now restricted.
