### ISSUE TITLE
change prompt in background box to:

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#925]
change text in allele box to
"alleles which do not affect the phenotype (optional)"

**Comment by ValWood** [comment]
![genotype_greyed_out_text](https://cloud.githubusercontent.com/assets/7359272/8930418/aa713dd8-3525-11e5-9a02-86e5d96436a4.jpg)

**Comment by ValWood** [comment]
I just saw Midoris comment.
This is how it looks in Chrome....

Can we try it, if it looks horrible we'll move to icon....?

**Comment by mah11** [comment]
looks like it may or may not quite fit even on Val's ...

**Comment by ValWood** [comment]
Well I can type it in the box with room to spare;)

**Comment by ValWood** [comment]
![alleles](https://cloud.githubusercontent.com/assets/7359272/8930543/c734289e-3526-11e5-8ddc-edf6a60aa149.jpg)

**Comment by kimrutherford** [comment]
We can easily change the width of the boxes on this page if that helps.  Currently the name and background input boxes have a width of 50.  I wouldn't want them too long though because long boxes make users think they need to type a lot of text.  We don't want an essay about the genotype background.

**Comment by ValWood** [comment]
not an issue

**Comment by kimrutherford** [comment]
What was the decision on this?  Is "Genotype background" not clear?  We could have a help icon beside the box if that helps.

**Comment by mah11** [comment]
I think we decided to go for the help icon, and leave the text in the box as is.

**Comment by ValWood** [comment]
yep.

**Comment by kimrutherford** [comment]
I've added an icon beside the name and background fields that shows a help text if you move your mouse over.  Currently the help text isn't very helpful and maybe it's not needed for the genotype name?

The text can be edited here:
https://github.com/pombase/canto/blob/master/canto.yaml#L1639

There are two settings, genotype_edit_name_input and genotype_edit_background_input.  You can either edit the file yourselves or I'm happy to do it if you tell me the text you'd like.

If you'd like the help icon for the name field removed, let me know.

Also the help icon is a bit naff.  Suggestions welcome.

Also it's now very easy to add a help icon anywhere it's needed.  Please open an issue for any others you'd like.

**Comment by mah11** [comment]
I've stuck in some text for those help icons. Happy to edit further if 'n' when someone suggests better text.

**Comment by kimrutherford** [comment]
Thanks, I've deployed those changes.
