### ISSUE TITLE
provide a list of genotypes which use 'other' as allele description

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#926]
can we get a list of these. We want to see if any can be added to the allele type dropdown with standard syntax (and what syntax we have been using if there is any exisiting consensus....

thanks

val

**Comment by kimrutherford** [comment]
Here's the list: https://www.dropbox.com/s/ov246btw26u0ryy/other_alleles.txt?dl=0

What other information do you need in that table?

**Comment by ValWood** [comment]
the description field,
so 
cdc27-R22  would have (nt C inserted after 782; translated product has aa 1-164 plus 12 aa from different reading frame)

**Comment by ValWood** [comment]
and the PMID.

No hurry though....

**Comment by kimrutherford** [comment]
Is a session ID enough?  It's easier than getting the PMID:
  https://www.dropbox.com/s/yqdk8z6syot7iiq/other_alleles.csv?dl=0

I've added the allele descriptions and the gene names too.

**Comment by ValWood** [comment]
perfect.
