### ISSUE TITLE
don't remember "unfinished alleles" in search box

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#927]
At present if you are creating alleles, and you create an allele which you end up deleting  because you did it wrong, it is still available for search in the drop down.

Sometimes this can be very subtle
i.e. 
cut14(G35N)
cut14-G35N
G35N
while you get the allele and expression correct (I only just figured this out so I ended up with a big mess as I kept selecting names which I didn't want as they had the correctly specified allele details)

Is it possible to only show the alleles which actually exist here?

**Comment by kimrutherford** [comment]
This should be fixed now.

(Although I can't push changes to GitHub at the moment so I haven't updated the Canto server yet)
