### ISSUE TITLE
phaf file content reduced

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#928]
I noticed that the  current phaf only has 6000 rows

**Comment by ValWood** [comment]
ah this might be because only canto data is included in the current build. If so, that's probably right (but it still seems low?)

v

**Comment by mah11** [comment]
a) wrong tracker

b) probably a known problem: https://github.com/pombase/pombase-chado/issues/465 (and yesterday's build didn't have the Canto annotations; 6000 from the embl files may be sensible)
