### ISSUE TITLE
attribution for primary approval

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#930]
Because approval takes a long time (you need to read the paper in much the same depth as primary curation), and add annotation, it would be good if individual curators could 'claim' the approved sessions for their  personal totals.

However at present the 'last approver' is recorded, so if we re-approve a  session to fix something (often), tha attribution is lost. 

Can we have a way of recording the primary approver?
In the meantime we will keep a record of our individual approved sessions and at some point we can give you a list of these for  most of the ones we already did.

Val

**Comment by ValWood** [comment]
Was just chatting with Kim about this. Kim isn't sure if the primary approver is associated with a session. So we should do this first so that this info isn't lost. I will raise priority of this one.

**Comment by kimrutherford** [comment]
> Kim isn't sure if the primary approver is associated with a session.

I've checked this now.  Canto stores the approver name and email address of the admin user who does the first approval.  It doesn't change the name and email if the session gets re-approved by someone else.

The name and email are stored in Chado when the Canto data is loaded.

**Comment by kimrutherford** [comment]
I think this is all done.
