### ISSUE TITLE
very small text change, to completed sessions to explain how to reactivate (quick)

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#931]
At present Canto says:

"review only, no changes are possible"
I wonder if we can add a little more text  here

review only, no changes are possible *without reactivation. Please contact the help desk if you would like to edit this session*

or similar? maybe?

**Comment by mah11** [comment]
I don't see the exact text "review only, no changes are possible" anywhere. There's already a fair bit of text on the "arrival" page for a submitted or approved session, which may be enough. We could add a bit if you want, though (basically, change the last line from "If you wish to modify an annotation you have made, please contact the curators." to "If you wish to modify an annotation you have made, please contact the curators to reactivate the session.").

The text on the review page itself (yada/ro/) is "Review only - this session can be viewed but not edited". Might be simplest to change it to "Review only - this session can be viewed but not edited. Click 'finish reviewing' to see more options.".

**Comment by ValWood** [comment]
OK, I maybe misremembered (was in some noted i jotted down)
Make any tweaks you think are appropriate, otherwise close

**Comment by ValWood** [comment]
Resolution
Change text to "Review only - this session can be viewed but not edited. Click 'finish reviewing' to see more options.".
