### ISSUE TITLE
frequently popping up error message

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#932]
I often get an error message when I load pages
I don't think it is indicative of an actual problem, 

for example here I I just reloaded the page
http://curation.pombase.org/pombe/curs/67c7ee73b6bc39ab
![screen shot 2015-08-04 at 12 06 14](https://cloud.githubusercontent.com/assets/12727506/9059386/6d10d526-3aa1-11e5-92ba-bbe8463632fc.png)

**Comment by kimrutherford** [comment]
I noticed that a while ago but forgot to make a ticket. Thanks for making one.

**Comment by Antonialock** [comment]
The error shown in the original post stays on the screen for quite a long time so it is easy to screenshot. Some errors disappears a lot quicker. I managed to grab this one just after I created a single gene mutant allele (type: mutation of multiple amino acid residues) 
![screen shot 2015-08-04 at 13 34 05](https://cloud.githubusercontent.com/assets/12727506/9060664/bca4f232-3aad-11e5-9074-683f19f5d591.png)

**Comment by Antonialock** [comment]
reported to the canto dev :-)

**Comment by Antonialock** [comment]
actually that might be a different bug, I will open a new ticket

**Comment by kimrutherford** [comment]
> I noticed that a while ago but forgot to make a ticket. Thanks for making one.

I think what you were seeing is not what I was thinking of.  I think you were seeing this bug: #933

I'll make another ticket about what I'm seeing.

**Comment by kimrutherford** [comment]
I closed this a bit early.  I've fixed some of the problems but errors still pop up in the annotation tables if you click a link before the page finishes loading.

**Comment by kimrutherford** [comment]
Fixed by b45cc3f
