### ISSUE TITLE
can't create single mutant allele

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#933]
I can't create a single mutant allele in session
http://curation.pombase.org/pombe/curs/67c7ee73b6bc39ab

this also seems to be a new problem in other sessions (I also tried c23b5043b024b0a5 which worked the other day)

If I try and make a deletion, the allele comes up like this
![screen shot 2015-08-04 at 13 39 22](https://cloud.githubusercontent.com/assets/12727506/9060728/61d2f7ae-3aae-11e5-9a0e-c001e1cbace6.png)

If I make it then I get this: (and no allele is created)
![screen shot 2015-08-04 at 13 34 05](https://cloud.githubusercontent.com/assets/12727506/9060734/717de04c-3aae-11e5-8518-fe43f4d1347d.png)

**Comment by Antonialock** [comment]
I can create single mutant alleleles using the multiple allele interface

**Comment by Antonialock** [comment]
argh ok, so now I can't make any phenotype annotations for the single allele I created, using the multi allele interface. I get this error
![screen shot 2015-08-04 at 13 55 50](https://cloud.githubusercontent.com/assets/12727506/9061004/97c5fa76-3ab0-11e5-8b37-64b1fb100c78.png)

I can make them in other sessions where I had already created alleles

**Comment by mah11** [comment]
I've just had it fail once and work once in the "normal" multi-step phenotype addition interface. The one that failed simply froze.

So far it's worked every time I've tried "duplicate" or "quick add".

**Comment by Antonialock** [comment]
I think they are created just not shown in my session, because I can't delete the genotype "because annotations exist" (but I cant see them)

**Comment by kimrutherford** [comment]
I'm looking at this now.  Were you using existing alleles from Chado?

**Comment by kimrutherford** [comment]
Please ignore that.  I think I've found the problem.

**Comment by kimrutherford** [comment]
It was bit confusing but I think I know what's going on.  The "storing genotype failed" problem was the same bug as #934, but I think the problem with:
  http://curation.pombase.org/pombe/curs/67c7ee73b6bc39ab
was different.

There was an annotation to FYPO:0002019 with genotype associated with it.  That's not supposed to happen and may mean that the user tried to make an annotation but it partially failed.  I've added a dummy genotype (called "DUMMY") to the session and attached the annotation to it.  Antonia could you have a look and delete or fix the annotation as appropriate?

That broken annotation was what was causing the annotations to fail to display.

> I think they are created just not shown in my session, because I can't delete the
> genotype "because annotations exist" (but I cant see them)

Yep, I think your annotations were made but were failing to display.  Could you check the session and see if it looks OK?

**Comment by kimrutherford** [comment]
> There was an annotation to FYPO:0002019 with genotype associated with it.
> That's not supposed to happen

I think I've worked that out to.  I checked and found 4 other sessions with the same problem.  The common factor was that the annotation was missing an evidence code.  So I think the script that upgraded the database to multi-allele genotypes missed them and didn't add the genotypes.

Here are the four other sessions that have the same problem.  One had three broken annotations and the others just had 1:

http://curation.pombase.org/pombe/curs/4790838a75d3b907
http://curation.pombase.org/pombe/curs/6b8ae0c3fd41751d
http://curation.pombase.org/pombe/curs/ff6fc192a2bc990a
http://curation.pombase.org/pombe/curs/5e67af395c1e5f9e

Could you have a look and delete or edit the annotations with the "DUMMY" genotypes?  They don't have an evidence code either.

I'll leave this open until you let me know it's OK.

Thanks.

**Comment by Antonialock** [comment]
They are going to go through checks anyway so I have removed them from now. 

Do you have a solution for how to deal with this? Or know what happened?

**Comment by kimrutherford** [comment]
> Do you have a solution for how to deal with this? Or know what happened?

I'm fairly sure the script that upgraded the database to cope with multi-allele genotypes went wrong for those annotations because there were incomplete (no evidence was set).  I think it is fixed now.
