### ISSUE TITLE
allele name search not working

### ISSUE THREAD

**Issue by mah11** [pombase/canto#934]
Hope the summary says it all: when I add any allele in the "add a genotype" interface, it doesn't search existing allele names even in the current session, let alone Canto's database -- no autocomplete suggestions appear.

Everything else about adding genotypes seems to be ok.

**Comment by kimrutherford** [comment]
The autocomplete is fixed.  Sorry for the hassle.  I broke it when implementing the allele editing.  I think #933 is related.
