### ISSUE TITLE
bug adding single allele phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#936]
I wanted to add some single allele phenotypes for avt3delta in this session (see fig)

when i selece
single allele phenotype
--deletion 

see what happens?

v

**Comment by ValWood** [comment]
![avt3](https://cloud.githubusercontent.com/assets/7359272/9114591/8f4232d6-3c52-11e5-8f13-75a9b59bacfb.jpg)

**Comment by ValWood** [comment]
ue appears as undefineddelta
instead of avt3delta

**Comment by mah11** [comment]
Antonia put a similar screenshot in #933 but there was a bunch of other stuff going on in that ticket ...

**Comment by mah11** [comment]
p.s. you can work around it by adding the allele in the genotype interface
