### ISSUE TITLE
some annotations not showing on the add another phenotype for this genotype page immediately

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#937]
When I was on the genotype and adding additional phenotypes, I could not see all of the phenotypes I had added (the view appeared to be restricted to the first 5 rows although I coudn't be sure).

http://curation.pombase.org/pombe/curs/5785790242ac75ac/feature/genotype/view/1

When I went to the main page, I could see all of them, and when I returned to this page I could see them all.

Has anyone else seen this bug?

**Comment by ValWood** [comment]
I just continued and it seems fine now, possibly a non-issue

**Comment by mah11** [comment]
I haven't seen this specifically, but I have seen that any phenotypes - new or otherwise - are sometimes slow to load, especially if the network is slow generally. Waiting usually sorts what I've seen.

**Comment by ValWood** [comment]
Yeah I now think its my mums slow connection. Now off to sneak into Hannah's Ioanthe rehearsal....

**Comment by kimrutherford** [comment]
I think I'll close this.  Please reopen if you see a consistent problem.
