### ISSUE TITLE
cellular component annotations showing in biological process table

### ISSUE THREAD

**Issue by mah11** [pombase/canto#939]
session 6601e49e3b15b194

I don't recall seeing this before, and I'm about to make some changes to these annotations, so it might not remain a problem. But I thought it was worth mentioning.

![2015-08-13 03 10 59 pm](https://cloud.githubusercontent.com/assets/5196259/9252116/a7a88fc4-41ce-11e5-80cf-6240af106a58.png)

**Comment by kimrutherford** [comment]
Thanks.  That is weird.  I have reproduced the problem on my laptop so go ahead and make any changes you need to.

**Comment by mah11** [comment]
Welp, I went ahead and did the updates later the same day, and there are still some CCs showing in the BP department (as well as in the CC table where they belong). It's happening in "review" mode too, and looks the same whether I'm logged in or not.

Some of the "existing" annotations will go away in one or two purge-and-reload cycles as a result of my changes, but there are two "new" CC annotations appearing in the BP table.

**Comment by kimrutherford** [comment]
I've looked at this now.   I think the only way this can happen is if you paste a term ID into the term name search box.  It's then possible for the annotation type ("molecular_function", etc.) to not match the term ID.  I've fixed the code so that it won't happen again.

I checked the database and 6601e49e3b15b194 is the only session with the problem.  I've fixed the annotations in the session.

**Comment by mah11** [comment]
Interesting. I paste IDs all the time, and I could've sworn it bleated at me about a mismatch on one occasion (more recently, I've seen the autocomplete spin without finding anything for long enough for me to realize I'd picked the wrong annotation type, and start over).

Anyway, thanks for the fix!

**Comment by kimrutherford** [comment]
>  I could've sworn it bleated at me about a mismatch on one occasion

Yep, it warns if that ID you paste is from a different ontology.  But it then went ahead and did the wrong thing.  Fixed now though.

**Comment by mah11** [comment]
> Yep, it warns if that ID you paste is from a different ontology.

Good to know I didn't just dream that part ;)
