### ISSUE TITLE
details from PHAF not displayed sensibly in Canto

### ISSUE THREAD

**Issue by mah11** [pombase/canto#940]
PMID:7969124 has Canto session 1c5c00db9eb607a9 and a PHAF in the pombe-embl repository. Similarly, PMID:10079327 has 265b5ed439aaa802 and a PHAF.

Phenotypes from the PHAFs are displayed in the sessions, but there's one big and a couple of small problems with how they appear:

- Expression isn't shown anywhere for any alleles. The "Genotype" column shown the name (if there is one) and description, but not the expression. This is the most serious problem.

- If the gene name is omitted from the allele name in the PHAF, the systematic ID is plugged into the session "genotype" column -- i.e., the gene name isn't automagically substituted, when it seems like it could be (and would look nicer).

- It also seems odd that the allele name and description appear in both the "Genotype name" and "Genotype" columns, when the "genotype" column in the PHAF is blank (it's optional).

I have not rigorously investigated whether sessions for other papers with PHAFs are similarly affected (although I suspect at least some are ... I have a few vague recollections consistent with the notion).

Let me know if this should be split into a separate ticket for each oddity.

**Comment by kimrutherford** [comment]
> Expression isn't shown anywhere for any alleles.

I'll fix that.

> If the gene name is omitted from the allele name in the PHAF, the systematic ID is plugged
> into the session "genotype" column

I could change them from  "SPCC188.06c:allele-49" to "srp54:allele-49" but maybe they should really be "unknown" to be consistent with the gene page: http://www.pombase.org/spombe/result/SPCC188.06c#fission_yeast_phenotype

> It also seems odd that the allele name and description appear in both the "Genotype name"
> and "Genotype" columns, when the "genotype" column

I'll fix that too.

**Comment by kimrutherford** [comment]
I've made some changes to improve things and released the changes into the test Canto.  I'll update the main Canto once we're sure #807 won't destroy the world.

**Comment by mah11** [comment]
> I could change them from "SPCC188.06c:allele-49" to "srp54:allele-49" but maybe they should really be "unknown"

"Unnamed" would be better than "unkown", e.g. "srp54:unnamed" would be fine (or I could go through the PHAFs and copy the description to be the name as well). It was the gene name substitution that I was after. It shouldn't use "unknown" because that's for when we don't know the description.

**Comment by mah11** [comment]
Looking at the test canto display, it seems like it might make more sense for the Genotype name column to be blank if there's no name in the PHAF. Then the Genotype column should have stuff like "srp54+[knockdown]" or "srp54:unnamed(R194Q)[not specified]".

For PHAFs with allele names, it's actually working fine apart from the missing expression. For example, see PMID:9917066 and its session 72012f5a69c300fe.

**Comment by mah11** [comment]
i.e. for 72012f5a69c300fe it looks better on live pombe than on test, and it would be good to improve the unnamed allele situation in a way that doesn't break what's working for named alleles

**Comment by kimrutherford** [comment]
> Looking at the test canto display, it seems like it might make more sense for the 
> Genotype name column to be blank if there's no name in the PHAF.

Done!  Although if there is nothing in the column currently it hides the whole column.  That can be configured.

> "Unnamed" would be better than "unkown", e.g. "srp54:unnamed" would be fine

Done too, in the test tool.

Could you have a look and see what you think?:
  http://curation.pombase.org/test/curs/1c5c00db9eb607a9/ro/

**Comment by kimrutherford** [comment]
> for 72012f5a69c300fe it looks better on live pombe than on test

I think that was mostly because the test tool was pointing at an old Chado DB that had screwy genotype names stored in it - fixed now to point to v54.

**Comment by mah11** [comment]
That's looking good now. I'll test the #807 genotype duplication after lunch and comment on that ticket.

**Comment by kimrutherford** [comment]
Great.  I'll close this, but please reopen if you need further tweaks.
