### ISSUE TITLE
possible duplication issue

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#941]
I don't know if this is a curation, PomBase or curation issue  so once the cause is identified this ticket might need to be rerouted.

I spotted that tip1 has some seemingly duplicate annotation. Will upload screenshots

**Comment by ValWood** [comment]
![tip1_duplicated](https://cloud.githubusercontent.com/assets/7359272/9351476/94654038-4651-11e5-982f-3819029f1437.jpg)

**Comment by ValWood** [comment]
![tip1_duplicated_2](https://cloud.githubusercontent.com/assets/7359272/9351488/b6144eb8-4651-11e5-8adc-f61cf2b64dea.jpg)

**Comment by ValWood** [comment]
It might be a consequence of the biogrid import/export process?

**Comment by kimrutherford** [comment]
It looks like there are duplicates in Chado.  I'll investigate and find out where they came from.

**Comment by kimrutherford** [comment]
I double checked and what I thought were duplicates weren't.  The same annotation was coming from two different papers, PMID:15177031 and PMID:15062095, by the same authors.  I couldn't see any duplication in Chado.

But the PomBase gene page for tip1 lists this annotation twice from the same paper:
   forms complex with - mal3 - EB1 family Mal3 - Reconstituted Complex - Busch KE et al. (2004b)

I'll make a Jira ticket.

**Comment by kimrutherford** [comment]
Created: https://www.ebi.ac.uk/panda/jira/browse/PB-2352
