### ISSUE TITLE
read-only genotype view for review mode

### ISSUE THREAD

**Issue by mah11** [pombase/canto#943]
I would occasionally find it useful to be able to see all the genotypes in a finished session without having to reactivate it or restart approval. So, can we have a link on the summary page and a genotype page?

The link can go where the "genotype management" link is in active sessions, and say "View genotypes".

The linked page would be like the active genotype management page, except with the "Review only" box at the top, and without the "do stuff" links. I suppose the "Actions" box wouldn't be needed. The table of genotypes can say "Click a name or description to view  genotype details" (instead of "view and edit").

Holler if a mock-up or chat or more comments would help.

**Comment by kimrutherford** [comment]
Good point.  It shouldn't be too hard to have a read only view of genotypes.

**Comment by kimrutherford** [comment]
See also: #481

**Comment by kimrutherford** [comment]
This is fixed now I think.  Please let me know if anything needs tweaking.

**Comment by mah11** [comment]
looks fine; thanks
