### ISSUE TITLE
Consider warning about non-ASCII characters in annotation

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#947]
See: http://sourceforge.net/p/pombase/curation-tool/880/ 
and: http://sourceforge.net/p/pombase/chado/400/

**Comment by ValWood** [comment]
if quick

**Comment by ValWood** [comment]
I haven't seen this for ages, was it done?

**Comment by kimrutherford** [comment]
I looked into this and I'm not sure we want to do this.  I've fixed a couple of problems with displaying non-ASCII characters and sometimes they'll be needed in annotation.  For example for temperatures: 15°C - the "°" isn't ASCII.

I'm going to to close this for now and I'll reopen if it becomes a problem.
