### ISSUE TITLE
evidence unset upon duplication

### ISSUE THREAD

**Issue by mah11** [pombase/canto#948]
Since the last update, when I use the "duplicate" feature for any ontology annotations, the Evidence selection is lost (i.e. the popup shows "Choose an evidence code" instead of the evidence that was chosen for the annotation I'm duplicating).

Is this intentional?

Seen is bbe966c7c31d9042; I'll comment when I move on to another session to say whether I see it again. Let me know if any other info would help.

**Comment by mah11** [comment]
The "edit" function is also affected.

amended summary accordingly

**Comment by mah11** [comment]
also in 72fbfb14c00e0ddd, so I bet it's everywhere, not just an oddball session

**Comment by JackyVH** [comment]
I have also had a problem using the the duplicate function and have stopped using it.

**Comment by kimrutherford** [comment]
Sorry about that.  It should be fixed now.  You'll need to reload the page if you have a session open in a tab.

**Comment by mah11** [comment]
looks fine now; thanks
