### ISSUE TITLE
Does the world really need the curation session Edit link?

### ISSUE THREAD

**Issue by mah11** [pombase/canto#950]
On a "Details for curation session blah" page (randomly selected example: https://curation.pombase.org/pombe/view/object/curs/1277?model=track), there's an "Actions: Edit" link in the upper right corner, like the one on a publication details page. The curation session edit link doesn't look very useful, though -- it offers to let you change some things that I would think really ought to be automagically generated and then not changed: PMID, curs key, and creation date. Shall we get rid of it?

spotted whilst working on some admin documentation

**Comment by kimrutherford** [comment]
Yep, that edit link is pretty pointless.  I'll remove it.
