### ISSUE TITLE
A GO annotation from InterPro that should be filtered.

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#952]
I can't figure this out.

In this log file
http://curation.pombase.org/dumps/latest_build/logs/log.2015-09-02-21-42-47.excluded_go_terms

we have
SPAC3H8.10.1		GO:0006810	transport		InterPro

BUT
This is an IEA, which should be filtered if there are more specific manual annotations, and there are...

on www
http://www.pombase.org/spombe/result/SPAC3H8.10
GO:0006893	Golgi to plasma membrane transport	IMP
GO:0048193	Golgi vesicle transport	IMP
GO:0015914	phospholipid transport	ISO	SGD:S000004684

on stage
GO:0006893	Golgi to plasma membrane transport	IMP
GO:0048193	Golgi vesicle transport	IMP
GO:0015914	phospholipid transport	ISO	SGD:S000004684

in canto
http://curation.pombase.org/pombe/view/object/pub/4886?model=track

The parentage of these seems to be OK....

Also this is the ONLY mapping to transport that I'm picking up. You would think if there was a problem with the filtering or the loader or the ontology we would get 100's....

I really can't think why this particular annotation is appearing....I must have forgotten something, but what???

**Comment by ValWood** [comment]
I found another example
SPBC83.04.1		GO:0030071	regulation of mitotic metaphase/anaphase transition		InterPro

but this has a more specific manual annotation:
positive regulation of mitotic metaphase/anaphase transition		Evidence	With/From	Reference
IMP		Yoon HJ et al. (2002)

again its the only one to this term that is showing?....

**Comment by ValWood** [comment]
and sod2/SPAC977.10

has an experimental annotation to 
Term ID	Term Name	Evidence	With/From	Reference	Count
GO:0006883	cellular sodium ion homeostasis	IMP		Ndayizeye M et al. (2009)	
but a mapping is reported to the less specific
SPAC977.10.1		GO:0030004	cellular monovalent inorganic cation homeostasis		InterPro

**Comment by ValWood** [comment]
2 more
SPAC977.10.1		GO:0006814	sodium ion transport		UniProt
SPAC15A10.06.1		GO:0006814	sodium ion transport		UniProt

these have experimental annotation to sodium ion import into cell

**Comment by ValWood** [comment]
SPBC16C6.01c.1		GO:0006479	protein methylation		PomBase
SPAC3C7.09.1		GO:0006479	protein methylation		PomBase

have more specific annotation but via ISM. Maybe this is not filtered against?

**Comment by mah11** [comment]
a) wrong tracker - this should go in pombase-chado

b) the offending annotations all have the datestamp 20150718 in the latest-build GAF; they’re not in the v54 GAF (i.e. the problem, which does look like filtering, arose recently)

**Comment by ValWood** [comment]
move to
https://github.com/pombase/pombase-chado/issues/484
