### ISSUE TITLE
when restricting to specific  'ranges' in annotation extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#953]
Allow this:

Some enzymes act on a specific(defined) subset of proteins.

For example
GO:0032542 sulfiredoxin activity
peroxiredoxin-(S-hydroxy-S-oxocysteine) + ATP + 2 R-SH = peroxiredoxin-(S-hydroxycysteine) + ADP + phosphate + R-S-S-R

where peroredoxin =  PomBase:SPBC32F12.03c|PomBase:SPBC1773.02c|PomBase:SPCC330.06c|PomBase:SPCC576.03c|PomBase:SPAC27D7.12c|PomBase:SPBC17D11.03c|PomBase:SPBC17D11.03c

so, in this case, I have put 
GO:0032542 PomBase:SPBC32F12.03c|PomBase:SPBC1773.02c|PomBase:SPCC330.06c|PomBase:SPCC576.03c|PomBase:SPAC27D7.12c|PomBase:SPBC17D11.03c|PomBase:SPBC17D11.03c sulfiredoxin for

(you can default this to PomBase GENE until you are ready to deal with ranges, so I am putting in a now ticket as its  not so urgent)

**Comment by mah11** [comment]
now covered by #1006 and #1007
