### ISSUE TITLE
load the rest of session with warnings

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#954]
The canto log has quite a lot of warnings to do with alleles and promoters that are yet to deal with.

Ideally, we would load all of the annotations from a session which are not generating a warning.

**Comment by mah11** [comment]
It's been doing exactly that all along. (e.g. gcn5 PMID:https://github.com/pombase/canto/issues/954 session fc9305f756e323a2)

**Comment by kimrutherford** [comment]
Yep, sorry about that Val.  Midori is right, the session does get loaded when there are warnings.  I was misreading things.  I queried what I thought was the latest load but I was looking at yesterday's one which was missing session 1f490bc22fcecb5e.  Today's load has that session despite the warnings.
