### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#955]
I just made a multigene genotype in this session:
http://curation.pombase.org/pombe/curs/abf32a065b08bcd5/

and got this little gem:

Internal error
Caught exception in Canto::Controller::Curs->top "Can't use string ("Created new genotype") as an ARRAY ref while "strict refs" in use at lib/Canto/Controller/Curs.pm line 237."
Created new genotype
There has been an internal error. The problem has been logged and will be investigated.

the genotype had actually been created so I think it's just cosmetic

**Comment by Antonialock** [comment]
also

Caught exception in Canto::Controller::Curs->top "Can't use string ("Added 1 gene") as an ARRAY ref while "strict refs" in use at lib/Canto/Controller/Curs.pm line 237." 

when adding a gene

**Comment by Antonialock** [comment]
I think this session goes right back to when we started, so could be just a problem in this one

**Comment by kimrutherford** [comment]
Sorry about that.  I'm testing a fix now.

**Comment by kimrutherford** [comment]
Should be fixed now.
