### ISSUE TITLE
slow speeds searching

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#956]
It is really slow searching for terms and alleles at the moment. I thought it was my connection but I just tried to load other pages with a lot of images (facebook, newspaper) and they seem to load normally

**Comment by kimrutherford** [comment]
I can't see any warnings in the logs files and it's pretty quick from New Zealand currently.  Are you still having problems?

**Comment by Antonialock** [comment]
wait and see if it persists...

**Comment by kimrutherford** [comment]
Same as #981 I think.
