### ISSUE TITLE
Not clear what to do after annotation created / quick

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#959]
From here, I only have one obvious action option when I have created an annotation "back to genotypes".
I think there should also be a "finish" or 'back to summary" option (I know I can get there  via the breadcrum trail, but  I don't think this is so obvious for a novice (or indeed somebody who had been on holiday for a while!).

**Comment by ValWood** [comment]
![2 things](https://cloud.githubusercontent.com/assets/7359272/9813225/bdb4a280-587b-11e5-92b4-b3f23501dc03.jpg)

**Comment by mah11** [comment]
I don't know what you mean by "a 'finish' option" -- at the point in the screenshot, the annotation is finished, and we don't want people to be able to submit the session from this screen.

A "back to summary" button would be good.

**Comment by ValWood** [comment]
Need to discuss this. Kim doesn't like 2 "back' buttons. Instead maybe 2 actions.
Add another genotypes or GO to summary
> kim thinks we need a better navigation button. 
Anyway this ticket seems like it requires discussion so taking off Kim's immediate priorities for now. If time can discuss tomorrow

**Comment by mah11** [comment]
I think we want a button to go to the genotype management page, and a button to go to the paper summary (at least I do ;) ). I don't care whether either of them has "back" as part of its label.

**Comment by ValWood** [comment]
Decision
Add another button "GO to summary"
Just so people can get back to the place they have all options

**Comment by kimrutherford** [comment]
I think this is superseded by #1078.

**Comment by ValWood** [comment]
It is...
