### ISSUE TITLE
A suggestion for the genotype page

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#960]
Does anyone else think that this page would work better if it were arranged:

Actions

Find and existing genotype          =================  Add a new genotype

===========================
Genotypes used in this session

It seems that it would be a better use of the space?

**Comment by ValWood** [comment]
![a suggestion](https://cloud.githubusercontent.com/assets/7359272/9813329/7ba7b084-587c-11e5-9c43-705634c3b5e2.jpg)

**Comment by mah11** [comment]
I don't think it would be good to have the two "action" options stretching horizontally across the page. They're grouped nicely in a sensibly proportioned box now, and it looks like a list from which you pick one.

Apart from that, I really don't care (if anything, I worry a bit about overthinking this page).

**Comment by ValWood** [comment]
I might overthinking the page,  be but after a time gap I found it confusing when I came back to curation. Others appear to find it a little confusing what their action should be at this point too.

I guesspart of the issue is that  I rarely refer to this list- I don't find it so useful. I would rather search for a genotype than scan a long list. I think it would be more useful to see alleles which could match your selection on the allele selection page.

I think I would also prefer that this list is always "collapsed/hidden" by default. Even if it only has a single entry.  I don't like the way it pushes the annotations  down the page.

My original horizontal suggestion is rubbish though.......

I think it would be a useful  to discuss this on our next call and decide if any action is required...

**Comment by mah11** [comment]
> I don't like the way it pushes the annotations down the page.

Wait, what? I thought this was about the genotype summary page, which doesn't show any annotations anyway.

**Comment by ValWood** [comment]
I am confusing 2 pages.  I'll scrub that and open another ticket for the list issues.

**Comment by kimrutherford** [comment]
> They're grouped nicely in a sensibly proportioned box now, and it looks like a list from which you pick one.

It also matching the pattern from other pages: actions in a list on the left, details on the right.

**Comment by ValWood** [comment]
not an issue
