### ISSUE TITLE
small workflow inprovement, possibly just text change

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#961]
Based on previous helpdesk ticket from Gerry and this  one from Katharina, I think we might need to make very minor tweaks to the interface to make it clearer how to add genotypes. This may possibly only require small text changes. I think we need to think about it.

Here Katharina did not realise how to add a new allele. I am guessing that is because  from this page (uploading) it might not be very clear what to do if you do not see the allele you want  already under "geneotypes for this gene" on the gene page.

She has clearly guessed where she needs to go next "single allele", but she is put off by the fact that the allele does not appear.

see
https://rt.sanger.ac.uk/Ticket/Display.html?id=488431

My immediate suggestions:
1) Small txt change
"Genotypes for this gene " -> "genotypes for *geneX*  in this session"

2) Single allele (add allele details and phenotype)
change text to
"add new allele and phenotype details"

Or ?

Also a question. Why is there a "duplicate" button for "genotypes"
Shouldn't this just be "add"?

**Comment by ValWood** [comment]
![if here not very clear to add new geneotye](https://cloud.githubusercontent.com/assets/7359272/9845599/135d1dbc-5ac4-11e5-96c8-1b7aca41c189.jpg)

**Comment by ValWood** [comment]
would it be better if the default was always 'closed' like:
(I think the default is to close once the list reaches a certain size?)

![closed](https://cloud.githubusercontent.com/assets/7359272/9848614/b9dbb958-5ada-11e5-8ccf-1d0d85d9042e.jpg)

**Comment by mah11** [comment]
> Why is there a "duplicate" button for "genotypes"

Because it's damn useful and I will shriek if anyone tries to take it away from me ;)

> Shouldn't this just be "add"?

NO!!! It's exactly analogous to the "duplicate" link for annotations. Use it when you have one genotype with two or more alleles, and you want to add another genotype that has all but one alleles the same -- e.g. if genotype A exists with alleles geneX-1 and geneY-2, you can add genotype B (geneX-1 geneZ-3) without re-doing the geneX-1 addition.

**Comment by ValWood** [comment]
OK!

**Comment by ValWood** [comment]
1. Keep the text "This session has 2 genotypes that include this gene." visible at all times (colalpsed and uncollapsed"

**Comment by kimrutherford** [comment]
>  Keep the text "This session has 2 genotypes that include this gene." visible at all times
> (collapsed and uncollapsed"

That's done now.

> would it be better if the default was always 'closed' like:

What was the decision on that?

And should I go ahead and make these changes?:

> "Genotypes for this gene " -> "genotypes for geneX in this session"

> change text to "add new allele and phenotype details"

**Comment by ValWood** [comment]
>would it be better if the default was always 'closed' like:
<What was the decision on that?

Not sure ....leave as it is for now...

>And should I go ahead and make these changes?:
>"Genotypes for this gene " -> "genotypes for geneX in this session"
>change text to "add new allele and phenotype details"

Not sure again. I think it could be slightly clearer. Will assign to Midori to see if it can be tweaked, if not M. can close.

**Comment by mah11** [comment]
> > would it be better if the default was always 'closed' like:
>
> What was the decision on that?

I have no preference, so if Val doesn't feel a need to change it, leave as is until further notice.

> And should I go ahead and make these changes?:
>
>>  "Genotypes for this gene " -> "genotypes for geneX in this session"

Yes; it's a small thing but certainly won't hurt and may help a bit.

>> change text to "add new allele and phenotype details"

I don't know which existing text this refers to; the new phrase is certainly too long to replace the "add phenotype" or "Duplicate" links in the table.

Maybe it means to _add_ a link to the genotypes box, using that text? That would be OK but I think not urgent.

**Comment by ValWood** [comment]
>Maybe it means to add a link to the genotypes box, using that text? That would be OK but I think not urgent.

It was to the "choose a curation type" text. But we can wait to see if others are confused and if other tweaks help

**Comment by ValWood** [comment]
The summary of this ticket is a very small text change
change 
"Genotypes for this gene " -> "genotypes for geneX in this session"

**Comment by kimrutherford** [comment]
I've changed the text.  It looks a bit odd if there are no genotypes.  Any thoughts?

![screenshot 2016-03-09 18 43 22](https://cloud.githubusercontent.com/assets/90474/13626483/3c0c1c60-e627-11e5-91c8-7ac68d0753fd.png)

**Comment by ValWood** [comment]
This gene is not *yet* part of a genotype in this session?

**Comment by mah11** [comment]
Why? Just because a gene is on the list for a session doesn't imply that there must be a genotype that includes it. (A gene could just have annotations of other types, not phenotypes.)

**Comment by mah11** [comment]
I think Kim's text is basically OK. If anything's odd, it's that there's a box with a "genotypes for x" header even if there are none for the gene. But I can live with that if it's a pain to hide the header if there are no genotypes.

**Comment by ValWood** [comment]
I don't have a problem with the existing text.

**Comment by kimrutherford** [comment]
I think it would read better if we changed "This gene is not part of a genotype in this session" to "(None yet)" or something equally short.  Shall I do that or leave it?

**Comment by ValWood** [comment]
I think its fine. We'll open a new ticket if it seems confusing from user testing
