### ISSUE TITLE
how would we use the edit button here?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#962]
Am I being a dimbo?

Here I have a genotype (allele) and I notice that I entered it incorrectly
so  I have description 387A instead of L387A (I know it doesn't match the name L3A but thats because the naming of these alleles only applies to this specific helix).

Anyway, from here if I click "edit" I expected to be able to edit the allele, but I can't.  I know I *can* edit the alleles in another place, so I will go and do this now. I just wanted to record that I'm not sure what I would use the "edit" button for here. The pop up option only allows me to do two things (use or cancel). Should I be presented with a different pop-up here?

**Comment by ValWood** [comment]
![edit_button](https://cloud.githubusercontent.com/assets/7359272/9846472/4366b8fa-5aca-11e5-9189-a79736796efc.jpg)

**Comment by kimrutherford** [comment]
> Anyway, from here if I click "edit" I expected to be able to edit the allele, but I can't.

It works when I test it.  Which session were you having trouble with?

**Comment by ValWood** [comment]
Yeah I see now,  it means "edit the genotype"
not edit the allele.

You can take a contributing allele and change it to another one to 'edit' the genotype. You can't edit the allele itself.
This might not be clear when this option does, especially  when you only have a single allele.

Would "change allele" work better than "edit"?

**Comment by mah11** [comment]
I can edit alleles from the "edit" link for a genotype -- each allele has its own edit link

**Comment by ValWood** [comment]
You can add or remove alleles from the genotype. You can't fix an allele here which is incorrectly described which is what I was trying to do...It would be difficult to make this clear though....

**Comment by mah11** [comment]
I have just been doing exactly that, i.e. fixing allele descriptions.

**Comment by ValWood** [comment]
I see this pop up, but I can't "edit" the allele

![edit](https://cloud.githubusercontent.com/assets/7359272/9876849/0b3d94c0-5bb1-11e5-9f44-5577d88addc2.jpg)

**Comment by ValWood** [comment]
i.e I wanted to to edit  the description of this allele
387A to L387A
I went to the correct place to do it. I don't think this will be obvious to users they can not do this here

**Comment by mah11** [comment]
ah, ok, the difference is that I was editing alleles added in the session, not drawn from the database

**Comment by ValWood** [comment]
Yeah here the only  thing which can be edited is the "expression". I just wonder if this can be clearer...we can look at  a few of these on Thursday and see if small tweaks can be made.

**Comment by ValWood** [comment]
The problem is that  what you are allowed to do is different depending if the allele was pre-existing in the database or not.
We need to make this clearer to the users.

Once you have added an allele to a genotype, you might still need  to be able to edit the expression.
However when you do this the pop up text should change.

At present you see:
This is an existing allele, click "OK" to use this allele or "Cancel" to create a new allele

Instead  it should say 
This allele is already in the database, so you cannot edit it here.
To use a different allele you need to delete this one, and add the correct one.

For the ones which were created in this session.
Add the text to the pop up
Allele details for cdc2 (new in this session)

This way the user will know why the behavior is slightly different

We think it would be nice to have a visual cue as to which alleles are new in this session (maybe a different shading in the name column with a mouse over saying "new allele in this session".

Finally, if you have picked deletion it should be handled as an existing allele and you need to delete it (currently editable). At present you can create a different allele with a "delta" name. This should need to be deleted and recreated.

**Comment by kimrutherford** [comment]
> This is an existing allele, click "OK" to use this allele or "Cancel" to create a new allele

Yep, that makes no sense.

Perhaps the clearest thing to do would be to grey-out the edit button for existing alleles.  We could have a text box pop up when you hover over it that says something like:

"This is a pre-existing allele that can't be edited.  If this isn't the allele you need, please remove it from the genotype and add another"
(or something shorter)

Also, changing "delete" to "remove" beside each allele would probably be less scary for users.   "delete" sounds wrong.

**Comment by ValWood** [comment]
> Also, changing "delete" to "remove" beside each allele would probably be less scary for users. "delete" sounds wrong.

Agreed!
Also, when you get the pop up, it says
Are you sure you want to delete this genotype?
change to
Are you sure you want to remove this genotype from your session ?

**Comment by ValWood** [comment]
I think the changes suggested  re editing would also work.

**Comment by kimrutherford** [comment]
> Perhaps the clearest thing to do would be to grey-out the edit button for existing alleles

Done.

> Also, changing "delete" to "remove" beside each allele would probably be less scary for users. "delete" sounds wrong.

Done.

> Are you sure you want to remove this genotype from your session ?

Also done.

Is anything else needed here?

**Comment by ValWood** [comment]
I think so....I think anything else, new ticket.
Val
