### ISSUE TITLE
behavior when duplicating annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#964]
It worries me a little that when we duplicate an annotation to edit, we duplicate the annotation extension and comment.
Do you think we should? How often will they be valid if you are editing the term or allele?  I wonder if its safer not to duplicate and force them to be added.
(mainly because I keep retaining the penetrances and forgetting to edit, then I don't know if they are right or wrong)

**Comment by mah11** [comment]
I really truly love that it does duplicate everything, precisely because it saves me a lot of pasting.

We could make the duplicate-everything an admin-only feature to protect community curators, tho that wouldn't help you ;)

**Comment by ValWood** [comment]
I couldn't see the purpose when I only had a single allele. I can see if you have lots of alleles and you change one it is useful. I worry about how obvious this is, but we can evaluate that over time...

**Comment by ValWood** [comment]
OK we can't think of an elegant way to do this, and we are hoping that the checks will make mistakes negligible...... will continue to think about this and address it it appears to be a problem
