### ISSUE TITLE
unused alleles warning

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#965]
I see a warning in this session:
BUT I don't know which genotypes aren't used.

 I think the warning should happen earlier maybe when you submit the session?
Then show the unused genotypes in a list and ask if they should be deleted?

**Comment by ValWood** [comment]
![which](https://cloud.githubusercontent.com/assets/7359272/9849852/9b60ba62-5ae6-11e5-9107-a80687088b5e.jpg)

**Comment by mah11** [comment]
Yeah, actually it would be nice to be able to see which genotypes in the list do and don't have annotations - nothing fancy, maybe jut a column with a count? (straying a bit from original issue, oops)

**Comment by ValWood** [comment]
will let you off, its a solution to the problem ;)

**Comment by kimrutherford** [comment]
Fixed.  Please let me know if you spot any oddities.
