### ISSUE TITLE
how does canto/chado handle the same genotype specified in different ways?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#966]
what happens if somebody puts

cdc22delta alp7-1421
and somebody else puts
alp7-1421 cdc22delta

are these recognized/interpreted as being the same?

**Comment by kimrutherford** [comment]
The first genotype is already in the session, when you add the second one it displays a message and then redirects to the genotype page for the first one.  So within a session it won't let you add a duplicate.

When loading into Chado if the two genotypes came from different sessions you'll get two genotype features.  There are currently no checks when loading.  This needs fixing but for now it doesn't cause for Ensembl loading.

**Comment by kimrutherford** [comment]
Moved to pombase/pombase-chado#551
