### ISSUE TITLE
"genotypes for this gene" list

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#967]
referring to :
![genetypes for this gene list](https://cloud.githubusercontent.com/assets/7359272/9854347/475b7c3a-5b00-11e5-9317-949b3e6642c8.jpg)

**Comment by ValWood** [comment]
How useful is it to see this list?

I would prefer that it is always "hidden" and showing the text
This session has 2 genotypes that include this gene.
View list

rather than open by default if the gene list is short...

**Comment by mah11** [comment]
covered by comments on #961
