### ISSUE TITLE
clarify meaning of gene expression check buttons

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#971]
From Jacky:

I think the consensus is that for expression of a wild type gene behind it’s own promoter we can put endogenous,  but for a mutant allele gene behind the endogenous promoter we need to know the protein level , if this is not known then expression level is ’not specified’.  If it’s known to be  the same as wild type then it is endogenous, If it is  reduced it is ‘knockdown ‘ and if no protein is produced it is a null, so here we are looking at protein levels to determine expression. If a gene was cloned behind an inducible promoter used to over expressed a gene unless there was a blot to to show over expression even if there was a phenotype associated with induction then it should be unspecified?

 I think what my problem is that I’m was not sure whether the drop down menu was referring to the type of promoter used to express the gene, the transcript level or the protein level or all three but now after looking at your emails I think it is protein level irrespective of the promoter or transcript and if this is not known then it is unspecified.

**Comment by ValWood** [comment]
Change "Endogenous" to "Wild Type product level"
Change "Not specified" to "Not assayed"

Help icon text needs to be done

**Comment by mah11** [comment]
Kim - I can do some help text if I know where it should go ...

I have added a bit to the FYPO part of the Canto documentation in root/docs

**Comment by kimrutherford** [comment]
> Change "Endogenous" to "Wild Type product level"
> Change "Not specified" to "Not assayed"

Should this be done globally, including for old sessions?  That would be the most consistent.


> Help icon text needs to be done

Is this a new help icon or one that needs changing?

**Comment by ValWood** [comment]
> Should this be done globally, including for old sessions? That would be the most consistent.
yes.

**Comment by kimrutherford** [comment]
The allele dialog now shows the new text and the the database is updated.  There is a little bit of help text to update.

**Comment by mah11** [comment]
I seem to have written/updated the existing documentation in anticipation of these changes ;)

There isn't a help icon for expression right now, so it would be a new one, and I don't know where Val is thinking it should go. If it's meant to appear on the allele popup by the expression selections, it could say "Indicate the level of gene product present if assayed; otherwise choose 'not assayed'".

Very very finicky thing: "type" shouldn't be capitalized in "Wild type product level".

**Comment by mah11** [comment]
Handing back on the assumption that I got it to do documentation things, which I've done.

**Comment by kimrutherford** [comment]
> "type" shouldn't be capitalized in "Wild type product level".

I wondered about that.  I've changed it.

> Help icon text needs to be done

Val, which icon do you mean?

**Comment by ValWood** [comment]
I think we should add one of these,

![icon](https://cloud.githubusercontent.com/assets/7359272/14880420/9bbe0ada-0d26-11e6-88e7-e8cd09a400a2.jpg)

with the help text for this section
if poss?

**Comment by mah11** [comment]
I think the question is "where do you want the icon?" (not "what does the icon look like?"). I'm inferring that it would be a new icon, not more text for one of the existing ones.

Yesterday I suggested this text for it: "Indicate the level of gene product present if assayed; otherwise choose 'not assayed'". OK?

**Comment by kimrutherford** [comment]
How's this?  

![screenshot 2016-04-28 21 16 40](https://cloud.githubusercontent.com/assets/90474/14881091/91b70392-0d86-11e6-826e-b2242e68badb.png)

The text is shown when you hover the mouse over the icon:

![screenshot 2016-04-28 21 16 50](https://cloud.githubusercontent.com/assets/90474/14881094/9675099c-0d86-11e6-84b7-4ef67babb3b7.png)

**Comment by mah11** [comment]
looks good to me

**Comment by kimrutherford** [comment]
> looks good to me

OK, I've added that.  It's easy to move the icon if needed.

**Comment by ValWood** [comment]
Yep, sorry I am a dope sending you a picture of the icon....

**Comment by kimrutherford** [comment]
Should I close this now?

**Comment by ValWood** [comment]
yep
