### ISSUE TITLE
New documentation page for annotation extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#972]
From call with Alistair. Move from wiki.

Need a list of what is required

**Comment by kimrutherford** [comment]
I've made a start:
  https://github.com/pombase/canto/wiki/AnnotationExtensionConfig

**Comment by ValWood** [comment]
What else is required on this page?

**Comment by kimrutherford** [comment]
I've just fixed some things that were out of date.  The basics are there now so I'll close this.
