### ISSUE TITLE
Configuration of Demo version available

### ISSUE THREAD

**Issue by airvine** [pombase/canto#973]
Currently, the Demo for all versions of Canto links to only the PomBase Canto Demo version.
It would be good to be able to configure this so that the Demo button links to a Demo version relevant to the specific instance, e.g. PHI-base Canto

**Comment by kimrutherford** [comment]
You should now be able to change the URL of the Canto demo by setting "canto_demo_url" in canto_deploy.yaml like:

    canto_demo_url: "http://curation.pombase.org/demo"

**Comment by airvine** [comment]
Yes, this is working (although I don't yet have a Demo version for PHI-base)
