### ISSUE TITLE
Lookup service for NCBI taxa

### ISSUE THREAD

**Issue by airvine** [pombase/canto#974]
Currently in PHI-base, we specify the experimental host as an annotation extension where the user supplies the taxon ID of the host species. It would be good to be able to have a lookup service to check the taxon ID against the NCBI taxonomy, then retrieve the basic details.
This would be similar to the way in which UniProt accessions are given for a gene, then basic details are returned from UniProt.

**Comment by ValWood** [comment]
closing this, we will open a new ticket when we get to it.
