### ISSUE TITLE
Improve text on genotype add/edit page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#977]
I have a note to my myself to change the text on the genotype add/edit page but I can't find an issue for it.

I think the main problem with that the current text makes less sense when editing a genotype than when adding.

Can anyone suggest any improvements for the add genotype page and some new text for the edit genotype page?

**Comment by mah11** [comment]
I think it was ...

On the "Add a genotype" page, change the text to "Specify alleles of genes from the list, until the new genotype is complete.".

For "Editing genotype: ", I don't remember whether this is the exact wording we thought of on Thursday but I think it'll do: "Add, edit, or delete alleles of genes from the list until the genotype is correctly described.".

**Comment by kimrutherford** [comment]
I've updated the text.  Let me know if you'd like further tweaks.

**Comment by mah11** [comment]
Looks fine. In the unlikely event that we think of any further improvements, we'll open a new ticket.
