### ISSUE TITLE
bug adding comment interactions

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#978]
from user:

Hi,

I have a problem with annotating genetic interactions. Could you pls help?

I create a genetic interaction between cbf11 and e.g. sty1.
I click the "edit" link next to the interaction.
I type in a comment (such as in which phenotypes the interaction manifests) and click OK.
I click the "edit" link again, but the comment is gone. It doesn't seem to be saved.

Thanks for any help!

Best,

Martin

Also I spotted that Martins name isn't displayed correctly in the rightmost column of the annotations (he has a lot of czech apostrophies in his name)

**Comment by ValWood** [comment]
not good if the comments  really are disappearing....I didn't try this though
