### ISSUE TITLE
Antonias problem

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#981]
The conditions box doesn't appear when I add phenotypes "the long route" 
(i.e. going to a genetype page, entering a phenotype, then specifying evidence and conditions - the short route being duplicating another annotation and then editing the information)

![screen shot 2015-09-24 at 15 57 33](https://cloud.githubusercontent.com/assets/12727506/10076912/bf6fb506-62d5-11e5-9c6a-5e65f45bc2a0.png)

**Comment by Antonialock** [comment]
I havent seen this before but I normally enter phenotypes by duplicating other phenotypes, and I dont always add conditions.

the session in this case is 1d9460b2fe58c1c2

**Comment by kimrutherford** [comment]
Hi Antonia.

Did this happen on your home connection?

**Comment by Antonialock** [comment]
yeah repeatedly.

**Comment by Antonialock** [comment]
it is ok today.

I really don't get why Im having all these problems. I know you said it is sending lots of little requests, unlike normal browsing, but I can stream HD tv no problems so, yeah, it doesn't seem like it should be a problem.

**Comment by Antonialock** [comment]
I always get stuck on loading pages (the cog turns but nothing happens). I then have to click into the address bar and physically reload. Usually my annotation is then stored. This is frustrating because I end up spending a lot of time waiting for a page to load and then reloading it. 

I don't have a problem doing anything else, just canto. If it genuinly is an underlying problem with my connection (which it must be because I had no problems at Val's place) then I just need to know what to tell BT so they take it seriously because for all other purposes my connection seems fine to me.

**Comment by Antonialock** [comment]
I often see accessing server failed:0

**Comment by Antonialock** [comment]
and when annotations fail to load it is only phenotypes that fail to load, GO and interactions load fine

**Comment by kimrutherford** [comment]
I think it would help to try to debug the problem live to find out what BT needs to be told.  I can chat in the evening UK time most days.  Perhaps you could email if it's happening and we can Skype to talk about it if I'm around?  Monday and Thursday evenings I can't talk for so long because I need to head off to me other job.

**Comment by Antonialock** [comment]
yeah that would be good

**Comment by Antonialock** [comment]
so far today canto has been a joy to use again :-)
Perhaps there was a teething period....fingers crossed it lasts!
Will let you know if it reoccurs in the near'ish future.

**Comment by ValWood** [comment]
Closing this, just re-open this ticket if you need to.
val

**Comment by Antonialock** [comment]
it was a bit iffy still before I left for the states, but since I got back now I have had zero problem. I was worried it was going to remain this way forever so PHEW
