### ISSUE TITLE
Fix email address in Canto DB

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#983]
All these email address appear in Annotation data.curation field in the database:
> a.lock@ucl.ac.uk
> A.lock@ucl.ac.uk
> Antonia.nilsson@gmail.com

> val@sanger.ac.uk
> vw253@cam.ac.uk

Fix them to be consistent.

**Comment by ValWood** [comment]
transrfered from
https://github.com/pombase/canto/issues/918

I managed to get a couple of duplicated accounts, both with sessions attached

Hugh Cam hugh.cam@bc.edu 3 
Hugh P. Cam camh@bc.edu 1

Julie Cooper Julie julie.cooper@cancer.org.uk user 5
Julie Cooper Julie julie.cooper@nih.gov user 2
Julie’s current address is julie.cooper@nih.gov

What is the easiest way to merge them?

**Comment by ValWood** [comment]
from duplicate https://github.com/pombase/canto/issues/593

We have a few people in the tool twice

Damien Hermand
and another one I spotted, but I have forgotten who it was...

I think a warning should appear if we try to add a name which is already present.
At the moment we don't have any poeple with identical names so we can figure out a way to disambiguate later. Any of the existing people with the same name will need their "accounts" merged

**Comment by ValWood** [comment]
ignore I made 
https://github.com/pombase/canto/issues/593
the extant ticket, its longer
