### ISSUE TITLE
Decide what to do with "residue=..." in extension

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#985]
We currently have "residue=..." in the annotation_extension fields in Canto.  Can they be changed to be in the form "relation(range)"?

**Comment by ValWood** [comment]
I don't see why now. I think we use them in 2 cases
i) the modified residue
ii) the cleavage site
(I think we stopped using them for protein binding range and removed, a while ago).

So do we need 2 relations?

**Comment by ValWood** [comment]
site of a modification (need to go in PSImod config file)
 
range can be  free text for now 

Kim will report in logs, we will fix....

**Comment by ValWood** [comment]
Also,  note that these logs only report  the use of qualifiers in Canto. The migration/fix will also need to include the  use of the same qualifiers in Artemis

**Comment by kimrutherford** [comment]
>  Can they be changed to be in the form "relation(range)"?

So does that mean that residues can be treated as another sort of extension relation and shown on the extension edit page in Canto?

**Comment by kimrutherford** [comment]
After chatting we decided we should make a relation something like "modifies_residue(...)" and show it for admin users only.

**Comment by ValWood** [comment]
Ah whoops sorry. I meant for the qualifier= (for GO)

I think the modifies_residue(...) etc should be avaiable to users

**Comment by kimrutherford** [comment]
> Ah whoops sorry. I meant for the qualifier=

I don't understand that.  We have a bunch of residue=... qualifiers at the moment.

> I think the modifies_residue(...) etc should be avaiable to users

OK.  If you add the relations to the annotation extension config files in Subversion, the new relations should appear overnight.

**Comment by ValWood** [comment]
convert all of our residue=x-y to residue(x-y)
and treat residue as the relation.
We will add this to the config file.

**Comment by mah11** [comment]
"residue" is already in the psi-mod config file.
I can update the contig files as a late afternoon task soon.

**Comment by kimrutherford** [comment]
> "residue" is already in the psi-mod config file.

Thanks.

> I can update the contig files as a late afternoon task soon.

Please don't change the contig files.  That uses the old extension loader and will continue to work without a problem.

**Comment by kimrutherford** [comment]
I've fixed all the warnings about "residue=..." by assuming that they should be "residue(...)".  Athough they are stored in a relationy way, I'll store them in Chado the same way that the residue= qualifiers from the contig file.

There are still many warnings about other qualifiers.  Here is the log from processing the latest annotation from Canto:
https://www.dropbox.com/s/qahu1zmynik72b1/upgrade-to-v10-extension-6.log?dl=0

**Comment by ValWood** [comment]
log file looking good. We'll chat about the others on our next call. Any ideas for the GO qualifiers? Can we treat these int he same way as residue=?
v

**Comment by kimrutherford** [comment]
I'm closing this in favour of  #1015

**Comment by kimrutherford** [comment]
> I've fixed all the warnings about "residue=..." by assuming that they should be "residue(...)".

I've just changed the relation name to "modifies_residue" as it sounds more relationy.

**Comment by mah11** [comment]
> I've just changed the relation name to "modifies_residue" as it sounds more relationy. 

That's not a problem, but it is an awkward fit for the cleavage site usage. (Not reopening ticket because it's just me being fussy about natural language usage ;) .)

**Comment by kimrutherford** [comment]
> That's not a problem, but it is an awkward fit for the cleavage site usage

Ah, OK.  I've changed it back.
