### ISSUE TITLE
has function during ...

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#986]
When you make and MF annotation you can add a
has function during ... extension

Could we  change the wording of the prompt so that the users knows that they need to supply a phase or a process?
I don't think it necessarily needs the "has function" part
Maybe  just "during process or phase?"

`suggestions...

**Comment by mah11** [comment]
What could something happen "during" other than a phase or process? (i.e. what could the intent be confused with?)

**Comment by ValWood** [comment]
I just think it might focus people to think more about the "phases", as this is what is most commonly used in the extension....and "phases" aren't really "processes" even though they are in the process ontology...
At present it is not often that community curators provide this, even if the data is there...

I'm sure there are other ways a community curator could interpret  "has function during"...a condition, during my experiment.....OK, but why not be more explicit?
Also happy to leave as it is ....

**Comment by mah11** [comment]
If the autocomplete etc. offers anything that matches a condition* or "during my experiment" at that step, then we have configured it horribly wrong.

*some text that could describe a condition could match a term for a response to that condition ... but that ought to be OK
