### ISSUE TITLE
Update to the OWLTools from Git

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#987]
Currently we have an old SVN checkout.  Try the Git version instead:
  https://github.com/owlcollab/owltools

@airvine

**Comment by ValWood** [comment]
Will chobo supersede this one?

**Comment by kimrutherford** [comment]
> Will chobo supersede this one?

We still need to run owtools to calculate the closure, so we'll need it.

I've just tried the latest owltools from GitHub.  There were no errors.  It has produced more ancestors and descendants than the version we're using.  I'll try the new version in the next load.  It may be that there GO filtering results will be different.

**Comment by ValWood** [comment]
More ancestors with the same relations? That seems odd. I wonder if it is doing the thing where
"regulates relation" annotations are transitive  over MF.

 So where in the pipeline(s) do we use this. I will need to think about which outputs I need to check....

**Comment by kimrutherford** [comment]
It looks fine - closing.
