### ISSUE TITLE
text suggestions for annotation extensions

### ISSUE THREAD

**Issue by mah11** [pombase/canto#988]
"Edit extension" box:

You have annotated $gene* to $term_name ($ID). Can you extend this annotation by providing additional details (still based on the experiments in this paper)?

These extension types are allowed for $ID. You can use more than one of these types in one extension, if all that you choose apply to the annotation at once (this creates a "compound" annotation extension).

When you finish one extension, you will have the option to add another independent extension. Any extension may be single or compound.

----

general comment box (the last step):

Please provide any additional details you have for this annotation that do not fit into the available evidence, extension options, etc. The curators will record this additional information in PomBase.

----

*or $genotype for FYPO, obv

**Comment by kimrutherford** [comment]
I've change the text in the Edit extension box, except for:

> When you finish one extension, you will have the option to add another independent extension.
> Any extension may be single or compound.

which doesn't apply yet.

> general comment box (the last step):

The text that is show before the comment box is in the configuration file is different for FYPO, GO and modifications.  Should we unify it to one more generic message?  Here is how the mod text is configured:
   https://github.com/pombase/canto/blob/master/canto.yaml#L1562

The config file key for this text is "annotation_comment_help_text"

**Comment by mah11** [comment]
Yes, I think now that all of the specificity for extensions should be covered by the shiny new system and its configured options, we can use a unified generic message for the comment box. It really is turning into "anything else you want to tell us?".

**Comment by ValWood** [comment]
I have not had chance to test yet. I was hoping to finish 2  papers today before testing but I am still on the second one.
Antonia if you get chance could you test  a little. I will also  test tomorrow before we speak at 10...

**Comment by Antonialock** [comment]
Is it not supposed to work with all terms yet? I've added a MF and phenotype annotation to this session. I was asked if I wanted to add an extension, but there was nowhere to actually do anything about it

http://curation.pombase.org/test/curs/896d66665709d950

**Comment by mah11** [comment]
Is that the same as the bug from #996 (and #992)?

**Comment by kimrutherford** [comment]
> Is that the same as the bug from #996 (and #992)?

Yep, I think so.  Sorry Antonia.  I'm going to fix #996 next which should solve the problem.

**Comment by ValWood** [comment]
did the part about the final comment box get implemented? If so can close this ticket?

**Comment by ValWood** [comment]
I moved the outstanding part to accompany
 
>When you finish one extension, you will have the option to add another independent extension.
>Any extension may be single or compound.

To the ticket which needs to be done in order for this text to be relevant
https://github.com/pombase/canto/issues/1013

**Comment by ValWood** [comment]
reopen or new tickets if still relevant

**Comment by kimrutherford** [comment]
> did the part about the final comment box get implemented?

Just committed it now.  Please open a new issue if it needs tweaking.
