### ISSUE TITLE
ideas for extension workflow

### ISSUE THREAD

**Issue by mah11** [pombase/canto#989]
Just some fodder for discussion, based on what I remember from previous discussions plus a little bit of brainstorming today ...

Initial step-by-step extension interface:
After clicking a relation to get the gene selector or autocomplete box (as appropriate), include two buttons: "Add another part to this extension" and "Finish this extension".

Then, after hitting "finish this ...", buttons for two possible next steps: "Add a separate extension" (goes back to full set of allowable relations, i.e. starts over) and "Finish all extensions" (exits extension interface and proceeds to final comment box).

Popups:
In Edit [annotation] popup: if there's already an extension, show an "Edit ..." button, and show an "Add new ..." button; if there are no extensions, just show the "Add new ..." button. Use wordy versions "Edit this extension" and "Add new extension" only if we really think it would otherwise be confusing.

Should we also include a "Delete" (wordy: "Delete extension") button?

If "Add new ..." gets used for an annotation that already had an extension, spawn a new annotation in the table upon "OK".

The Duplicate [annotation] popup should work essentially the same way; for duplicating I think we definitely want all three options (edit|delete|add new) for an existing extension.

**Comment by kimrutherford** [comment]
I've changed the link to "Add..." and "Edit..." and fixed the "Delete..." link beside each part (relation) of the extension.  There is currently no way to delete the whole extension, only the parts one by one.   And for now the "Delete..." links only appear in the pop up you get by clicking "Edit...".

**Comment by ValWood** [comment]
refer to
https://github.com/pombase/canto/issues/1013

closing. If any is still relevant put in a new (or existing) ticket
