### ISSUE TITLE
'background' appears in "name" column

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#991]
I thought this was a little confusing. Should it have its own column if used?

Pic coming...

**Comment by ValWood** [comment]
![background](https://cloud.githubusercontent.com/assets/7359272/10435133/01d9b876-7116-11e5-8338-239cf410c93a.jpg)

**Comment by kimrutherford** [comment]
My reasoning for this was that I thought the background is often "h+" or something else that's short so it would look odd in its own column.  Are they often long?

**Comment by ValWood** [comment]
They are not often captured. Its just that when they are I  think its a bit confusing to see them in the name column. I think it helps interpretation if they are in another column.

Any thoughts anyone else?

Val

**Comment by mah11** [comment]
Background descriptions can sometimes get long, and I have no objection to giving them their own column.

**Comment by kimrutherford** [comment]
OK, I'll change that.

**Comment by kimrutherford** [comment]
Not done yet, but I'll wait until after #1078 because we may decide this idea needs tweaking.

**Comment by kimrutherford** [comment]
> Not done yet, but I'll wait until after #1078 because we may decide this idea needs tweaking.

I changed my mind since it was a simple fix.
