### ISSUE TITLE
annotation extension bug - options don't always show up

### ISSUE THREAD

**Issue by mah11** [pombase/canto#992]
Intermittent bug, transferred from #181:

Sometimes the actual extension options just don't show up. You just see the text that explains what to do, no hyperlinked relation display text to click, and therefore no gene dropdown or autocomplete box.

![extension_bug_screenshot](https://cloud.githubusercontent.com/assets/5196259/10453454/0f9d9250-71a4-11e5-8d1c-1b552ec2e86d.jpg)

First spotted by Val on or around Oct 8th. The screenshot's from her, then.

Should've been fixed by loading up all the relevant configs, data, etc. but has reappeared since. Midori got the bug on Mon 12th. Kim had extensions working on Mon 12th and once in Tues 13th demo, but then it stopped working in subsequent attempts in the demo (13th)

**Comment by kimrutherford** [comment]
I think this is the same as mentioned here:
  https://github.com/pombase/canto/issues/181#issuecomment-147919747

There's an issue open for fixing this: #996
