### ISSUE TITLE
searching by synonyms and popup

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#993]
If I search by synonym in the pop up window
e.g. sodium orthovanadate for  sensitive to trisodium vanadate

even though the correct term is presented it is not clear whether this is really the correct term, or a fortuitous close match because the pop up does not display the matched synonym.

1. Show matched synonym in pop up
2. Show comments in pop-up

**Comment by kimrutherford** [comment]
> Show matched synonym in pop up

The synonyms are missing from the main workflow too.  I'll fix that.

> Show comments in pop-up

I can see the comment.  Which session did you see that problem in?

![screenshot 2015-10-14 17 27 44](https://cloud.githubusercontent.com/assets/90474/10474875/08bd3cec-7299-11e5-90c5-965ae8689a5d.png)

**Comment by ValWood** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7359272/10481069/2fef9130-7266-11e5-9244-fd49bded1ae4.jpg)

**Comment by ValWood** [comment]
this one (above)
v

**Comment by ValWood** [comment]
here is another synonym issue (in main tool, possibly related)
I searched on "readthrough" as I wondered whether "increased transcriptional readthrough" was a synonym.
I found the correct term (below), but there doesn't appear to be a matching synonym?

**Comment by ValWood** [comment]
![readthrough](https://cloud.githubusercontent.com/assets/7359272/10483677/80bc349e-7278-11e5-8df0-c6e9fa94eb15.jpg)

**Comment by mah11** [comment]
in that example, the matching synonym is related (and does Canto only show exact?)

id: FYPO:0003049
name: increased transcript length by 3' extension
synonym: "3'-extended transcript" EXACT [PomBase:mah]
synonym: "poly(A) readthrough" RELATED [PomBase:vw]

**Comment by kimrutherford** [comment]
related synonyms are loaded but they have a low weight in the index.  So Lucene will find "readthrough" for that term but only as a last resort.

Here are the weights:

     name => 1.1
     exact => 1.1
     broad => 0.2
     related => 0.2

As I understand it, it's not a linear scale but you get the idea.

The idea behind giving related and broad synonyms low weight it that we want more exact synonyms a better chance of appearing in the completion list.  It's very easy to tweak these and I picked those weights out of thin air.

For displaying the term details, we decided in #458 to always show the exact synonyms.

**Comment by ValWood** [comment]
I thought we always displayed the "matched" syonym though....maybe not....

**Comment by kimrutherford** [comment]
> I thought we always displayed the "matched" syonym though....maybe not....

You're right, I think that's broken.  It's supposed to always show the matched synonym and then also show any exact synonyms for phenotypes.  I'll fix it now.  Sorry about that.

**Comment by ValWood** [comment]
I may have misremembered....

**Comment by kimrutherford** [comment]
> I may have misremembered....

It definitely used to.

**Comment by kimrutherford** [comment]
The matching synonym stuff is displaying again in the main Canto.  Unfortunately it's broken in the test tools because of the annotation extension changes.  I'll leave this open until I've fixed that.

**Comment by kimrutherford** [comment]
>  Unfortunately it's broken in the test tool

Now fixed (or will be next time I re-release the test tool).  The missing comment should be back now too.
