### ISSUE TITLE
Move extension config loading into the ontology load script

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#996]
From: https://github.com/pombase/canto/issues/181#issuecomment-147919747

Running "owltools --save-closure-for-chado" and loading the canto_subset cvtermprops should happen in the OntologyLoad code.  The cvtermprops get wiped by the load so if we load the extension conf as a separate script there will be a window of 30-ish minutes when the extension GUI won't work.

Add a --load-subsets flag on canto_load.pl so that running owltools is optional.

**Comment by kimrutherford** [comment]
I haven't quite finished this.  It should only take another hour-ish.  In the meantime I've made sure that the test Canto database is OK for testing today.

**Comment by kimrutherford** [comment]
This fix will solve the problem of the extension edit page having no options sometimes.  The ontology data in the database was being reloaded each night and clearing the information needed for the extensions.  I think I've fixed that now.

**Comment by ValWood** [comment]
It seems to work well for the option types which are configured. Works for GO, but does not currently work for SO, or for any extension which requires a gene ID, so I dod not test my full GO list yet.

**Comment by ValWood** [comment]
Actually it works fine for type protein ID
So its only TranscriptID and defined subsets which don't work. These can default to protein ID for now.

I spent about 15 mins testing and I didn't come across any howlers.

**Comment by kimrutherford** [comment]
> I spent about 15 mins testing and I didn't come across any howlers. 

Great!

> Works for GO, but does not currently work for SO

Yep, SO isn't loaded yet.
